In [1]:
import pandas as pd
import numpy as np
import os
import time

import matplotlib.pyplot as plt

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

In [2]:
df_games = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_games_all.csv').drop(columns=['matchup',
                                                                                                          'a_team_id', 'wl','w',
                                                                                                          'l', 'w_pct'])
df_games.head()

,game_id,game_date,team_id,is_home,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
0,20800741,2009-02-06,1610612762,f,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,2008,Regular Season,2008-09
1,20800701,2009-01-31,1610612762,f,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,2008,Regular Season,2008-09
2,20800584,2009-01-16,1610612762,f,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,2008,Regular Season,2008-09
3,20800558,2009-01-12,1610612762,t,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,2008,Regular Season,2008-09
4,20800440,2008-12-27,1610612762,f,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,2008,Regular Season,2008-09

In [3]:
df_games = df_games[(df_games.season_type == 'Regular Season' ) |
                    (df_games.season_type == 'Playoffs')][(df_games.season == '2006-07') |
                    (df_games.season == '2007-08') |
                    (df_games.season == '2008-09') |
                    (df_games.season == '2009-10') | 
                    (df_games.season == '2010-11') |
                    (df_games.season == '2011-12') |
                    (df_games.season == '2012-13') |
                    (df_games.season == '2013-14') |
                    (df_games.season == '2014-15') |
                    (df_games.season == '2015-16') | 
                    (df_games.season == '2016-17') | 
                    (df_games.season == '2017-18')]
df_games

C:\Users\Paul\anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  del sys.path[0]

,game_id,game_date,team_id,is_home,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
0,20800741,2009-02-06,1610612762,f,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,2008,Regular Season,2008-09
1,20800701,2009-01-31,1610612762,f,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,2008,Regular Season,2008-09
2,20800584,2009-01-16,1610612762,f,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,2008,Regular Season,2008-09
3,20800558,2009-01-12,1610612762,t,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,2008,Regular Season,2008-09
4,20800440,2008-12-27,1610612762,f,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125619,20801131,2009-04-03,1610612762,t,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,2008,Regular Season,2008-09
125620,20801058,2009-03-24,1610612762,t,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,2008,Regular Season,2008-09
125621,20801029,2009-03-20,1610612762,f,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,2008,Regular Season,2008-09
125622,20800839,2009-02-23,1610612762,t,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,2008,Regular Season,2008-09
125623,20800810,2009-02-19,1610612762,t,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,2008,Regular Season,2008-09

In [4]:
df_games['game_date'] = pd.to_datetime(df_games['game_date'])

In [5]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31038 entries, 0 to 125623
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   game_id      31038 non-null  int64
 1   game_date    30312 non-null  datetime64[ns]
 2   team_id      31038 non-null  int64
 3   is_home      31038 non-null  object
 4   min          31038 non-null  int64
 5   fgm          31038 non-null  float64
 6   fga          31038 non-null  float64
 7   fg_pct       31038 non-null  float64
 8   fg3m         31038 non-null  float64
 9   fg3a         31038 non-null  float64
 10  fg3_pct      31038 non-null  float64
 11  ftm          31038 non-null  float64
 12  fta          31038 non-null  float64
 13  ft_pct       31038 non-null  float64
 14  oreb         31038 non-null  float64
 15  dreb         31038 non-null  float64
 16  reb          31038 non-null  int64
 17  ast          31038 non-null  float64
 18  stl          31038 non-null  float64
 19  blk          31038 non-null  float64
 20  tov          31038 non-null  float64
 21  pf           31038 non-null  float64
 22  pts          31038 non-null  int64
 23  season_year  31038 non-null  int64
 24  season_type  31038 non-null  object
 25  season       31038 non-null  object
dtypes: datetime64[ns](1), float64(16), int64(6), object(3)
memory usage: 6.4+ MB

In [6]:
column_names = df_games.columns
column_names

Index(['game_id', 'game_date', 'team_id', 'is_home', 'min', 'fgm', 'fga',
       'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta', 'ft_pct', 'oreb',
       'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'season_year',
       'season_type', 'season'],
      dtype='object')

In [7]:
column_names = column_names.drop(['game_id', 'game_date', 'is_home', 'season_year', 'season_type', 'season'])
column_names

Index(['team_id', 'min', 'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct',
       'ftm', 'fta', 'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk',
       'tov', 'pf', 'pts'],
      dtype='object')

In [8]:
empty_df = df_games[df_games.is_home == 'f']

for column_name in column_names:
    empty_df = empty_df[empty_df.is_home == 'f'].rename(columns={column_name: column_name + '_away'})
    
empty_df = empty_df.drop(columns=['is_home'])

In [9]:
for column_name in column_names:
    df_games = df_games[df_games.is_home == 't'].rename(columns={column_name: column_name + '_home'})
    
df_games = df_games.drop(columns='is_home')

In [10]:
df_games.info() #<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15519 entries, 3 to 125623
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       15519 non-null  int64
 1   game_date     15156 non-null  datetime64[ns]
 2   team_id_home  15519 non-null  int64
 3   min_home      15519 non-null  int64
 4   fgm_home      15519 non-null  float64
 5   fga_home      15519 non-null  float64
 6   fg_pct_home   15519 non-null  float64
 7   fg3m_home     15519 non-null  float64
 8   fg3a_home     15519 non-null  float64
 9   fg3_pct_home  15519 non-null  float64
 10  ftm_home      15519 non-null  float64
 11  fta_home      15519 non-null  float64
 12  ft_pct_home   15519 non-null  float64
 13  oreb_home     15519 non-null  float64
 14  dreb_home     15519 non-null  float64
 15  reb_home      15519 non-null  int64
 16  ast_home      15519 non-null  float64
 17  stl_home      15519 non-null  float64
 18  blk_home      15519 non-null  float64
 19  tov_home      15519 non-null  float64
 20  pf_home       15519 non-null  float64
 21  pts_home      15519 non-null  int64
 22  season_year   15519 non-null  int64
 23  season_type   15519 non-null  object
 24  season        15519 non-null  object
dtypes: datetime64[ns](1), float64(16), int64(6), object(2)
memory usage: 3.1+ MB

In [11]:
#number of games actual: https://www.landofbasketball.com/results/2015_2016_scores.htm
df_games['season'].value_counts().sort_index()

2006-07    1309
2007-08    1316
2008-09    1315
2009-10    1312
2010-11    1311
2011-12    1074
2012-13    1315
2013-14    1319
2014-15    1311
2015-16    1316
2016-17    1309
2017-18    1312
Name: season, dtype: int64

<font color='red'> hereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehere</font>

In [12]:
#add columns to original dataframe
df_games.columns

Index(['game_id', 'game_date', 'team_id_home', 'min_home', 'fgm_home',
       'fga_home', 'fg_pct_home', 'fg3m_home', 'fg3a_home', 'fg3_pct_home',
       'ftm_home', 'fta_home', 'ft_pct_home', 'oreb_home', 'dreb_home',
       'reb_home', 'ast_home', 'stl_home', 'blk_home', 'tov_home', 'pf_home',
       'pts_home', 'season_year', 'season_type', 'season'],
      dtype='object')

In [13]:
away_column_names = empty_df.columns.drop(['game_id', 'game_date',
                                           'team_id_away'])
away_column_names

Index(['min_away', 'fgm_away', 'fga_away', 'fg_pct_away', 'fg3m_away',
       'fg3a_away', 'fg3_pct_away', 'ftm_away', 'fta_away', 'ft_pct_away',
       'oreb_away', 'dreb_away', 'reb_away', 'ast_away', 'stl_away',
       'blk_away', 'tov_away', 'pf_away', 'pts_away', 'season_year',
       'season_type', 'season'],
      dtype='object')

In [14]:
cols_numeric = empty_df.select_dtypes([np.number]).columns.drop('game_id')
cols_numeric

Index(['team_id_away', 'min_away', 'fgm_away', 'fga_away', 'fg_pct_away',
       'fg3m_away', 'fg3a_away', 'fg3_pct_away', 'ftm_away', 'fta_away',
       'ft_pct_away', 'oreb_away', 'dreb_away', 'reb_away', 'ast_away',
       'stl_away', 'blk_away', 'tov_away', 'pf_away', 'pts_away',
       'season_year'],
      dtype='object')

In [15]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15519 entries, 3 to 125623
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       15519 non-null  int64
 1   game_date     15156 non-null  datetime64[ns]
 2   team_id_home  15519 non-null  int64
 3   min_home      15519 non-null  int64
 4   fgm_home      15519 non-null  float64
 5   fga_home      15519 non-null  float64
 6   fg_pct_home   15519 non-null  float64
 7   fg3m_home     15519 non-null  float64
 8   fg3a_home     15519 non-null  float64
 9   fg3_pct_home  15519 non-null  float64
 10  ftm_home      15519 non-null  float64
 11  fta_home      15519 non-null  float64
 12  ft_pct_home   15519 non-null  float64
 13  oreb_home     15519 non-null  float64
 14  dreb_home     15519 non-null  float64
 15  reb_home      15519 non-null  int64
 16  ast_home      15519 non-null  float64
 17  stl_home      15519 non-null  float64
 18  blk_home      15519 non-null  float64
 19  tov_home      15519 non-null  float64
 20  pf_home       15519 non-null  float64
 21  pts_home      15519 non-null  int64
 22  season_year   15519 non-null  int64
 23  season_type   15519 non-null  object
 24  season        15519 non-null  object
dtypes: datetime64[ns](1), float64(16), int64(6), object(2)
memory usage: 3.1+ MB

In [16]:
for column in cols_numeric:
    df_games[column] = 0
df_games

,game_id,game_date,team_id_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,season_type,season,team_id_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away
3,20800558,2009-01-12,1610612762,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,20800344,2008-12-13,1610612762,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,20800325,2008-12-11,1610612762,240,35.0,72.0,0.486,3.0,10.0,0.300,24.0,30.0,1.0,10.0,28.0,38,23.0,9.0,1.0,11.0,21.0,97,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,20801116,2009-04-01,1610612763,240,38.0,79.0,0.481,8.0,18.0,0.444,28.0,34.0,1.0,12.0,25.0,37,21.0,10.0,6.0,12.0,22.0,112,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,20800762,2009-02-09,1610612763,240,28.0,77.0,0.364,3.0,15.0,0.200,26.0,35.0,1.0,20.0,44.0,64,18.0,3.0,9.0,18.0,21.0,85,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125616,20800030,2008-11-01,1610612765,240,42.0,79.0,0.532,6.0,14.0,0.429,27.0,32.0,1.0,16.0,33.0,49,24.0,5.0,7.0,17.0,24.0,117,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125619,20801131,2009-04-03,1610612762,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125620,20801058,2009-03-24,1610612762,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125622,20800839,2009-02-23,1610612762,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125623,20800810,2009-02-19,1610612762,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [19]:
empty_df.drop(columns=[ 'season_type', 'season'], axis=1, inplace=True)
empty_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15519 entries, 0 to 125621
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       15519 non-null  int64
 1   game_date     15156 non-null  datetime64[ns]
 2   team_id_away  15519 non-null  int64
 3   min_away      15519 non-null  int64
 4   fgm_away      15519 non-null  float64
 5   fga_away      15519 non-null  float64
 6   fg_pct_away   15519 non-null  float64
 7   fg3m_away     15519 non-null  float64
 8   fg3a_away     15519 non-null  float64
 9   fg3_pct_away  15519 non-null  float64
 10  ftm_away      15519 non-null  float64
 11  fta_away      15519 non-null  float64
 12  ft_pct_away   15519 non-null  float64
 13  oreb_away     15519 non-null  float64
 14  dreb_away     15519 non-null  float64
 15  reb_away      15519 non-null  int64
 16  ast_away      15519 non-null  float64
 17  stl_away      15519 non-null  float64
 18  blk_away      15519 non-null  float64
 19  tov_away      15519 non-null  float64
 20  pf_away       15519 non-null  float64
 21  pts_away      15519 non-null  int64
 22  season_year   15519 non-null  int64
dtypes: datetime64[ns](1), float64(16), int64(6)
memory usage: 2.8 MB

In [20]:
empty_df

,game_id,game_date,team_id_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_year
0,20800741,2009-02-06,1610612762,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,2008
1,20800701,2009-01-31,1610612762,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,2008
2,20800584,2009-01-16,1610612762,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,2008
4,20800440,2008-12-27,1610612762,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,2008
5,20800395,2008-12-20,1610612762,240,38.0,79.0,0.481,2.0,11.0,0.182,20.0,22.0,1.0,12.0,21.0,33,21.0,9.0,5.0,20.0,19.0,98,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125610,20800585,2009-01-16,1610612765,240,37.0,80.0,0.463,2.0,8.0,0.250,3.0,8.0,0.0,5.0,30.0,35,15.0,9.0,5.0,10.0,20.0,79,2008
125613,20800441,2008-12-27,1610612765,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87,2008
125614,20800052,2008-11-05,1610612765,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100,2008
125615,20800042,2008-11-03,1610612765,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101,2008
125621,20801029,2009-03-20,1610612762,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,2008

In [21]:
df = pd.concat([df_games, empty_df])
df

,game_id,game_date,team_id_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,season_type,season,team_id_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away
3,20800558,2009-01-12,1.610613e+09,240.0,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40.0,24.0,10.0,6.0,8.0,20.0,120.0,0,Regular Season,2008-09,0,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
9,20800344,2008-12-13,1.610613e+09,240.0,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46.0,25.0,11.0,4.0,22.0,23.0,94.0,0,Regular Season,2008-09,0,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
10,20800325,2008-12-11,1.610613e+09,240.0,35.0,72.0,0.486,3.0,10.0,0.300,24.0,30.0,1.0,10.0,28.0,38.0,23.0,9.0,1.0,11.0,21.0,97.0,0,Regular Season,2008-09,0,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
11,20801116,2009-04-01,1.610613e+09,240.0,38.0,79.0,0.481,8.0,18.0,0.444,28.0,34.0,1.0,12.0,25.0,37.0,21.0,10.0,6.0,12.0,22.0,112.0,0,Regular Season,2008-09,0,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
15,20800762,2009-02-09,1.610613e+09,240.0,28.0,77.0,0.364,3.0,15.0,0.200,26.0,35.0,1.0,20.0,44.0,64.0,18.0,3.0,9.0,18.0,21.0,85.0,0,Regular Season,2008-09,0,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125610,20800585,2009-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,240,37.0,80.0,0.463,2.0,8.0,0.250,3.0,8.0,0.0,5.0,30.0,35,15.0,9.0,5.0,10.0,20.0,79
125613,20800441,2008-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87
125614,20800052,2008-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100
125615,20800042,2008-11-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101
125621,20801029,2009-03-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612762,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101

In [ ]:
#fillna of game_date

#fillna of game stats with 0

#groupby

In [ ]:
df.info()

In [ ]:

start  = time.time()
df = df.groupby(['game_id', 'game_date']).sum()
t = time.time() - start
df

In [ ]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '1games_df.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=True)