In [1]:
import pandas as pd
import numpy as np
import os
import time

import matplotlib.pyplot as plt

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

In [2]:
df_games = pd.read_csv('C:\\Users\\Paul\\sb\DSCapstone2\\raw_data\\nba_games_all.csv').drop(columns=['matchup',
                                                                                                          'a_team_id', 'wl','w',
                                                                                                          'l', 'w_pct'])
df_games.head()

,game_id,game_date,team_id,is_home,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
0,20800741,2009-02-06,1610612762,f,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,2008,Regular Season,2008-09
1,20800701,2009-01-31,1610612762,f,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,2008,Regular Season,2008-09
2,20800584,2009-01-16,1610612762,f,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,2008,Regular Season,2008-09
3,20800558,2009-01-12,1610612762,t,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,2008,Regular Season,2008-09
4,20800440,2008-12-27,1610612762,f,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,2008,Regular Season,2008-09

In [3]:
df_games.shape

(125624, 26)

In [4]:
df2 = pd.read_csv('C:\\Users\\Paul\\sb\DSCapstone2\\raw_data\\games.csv')
df2.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2021-03-21,22000645,Final,1610612748,1610612754,2020,1610612748,106.0,0.402,0.826,0.243,27.0,51.0,1610612754,109.0,0.388,0.900,0.333,27.0,50.0,0
1,2021-03-21,22000016,Final,1610612745,1610612760,2020,1610612745,112.0,0.494,0.741,0.368,22.0,38.0,1610612760,114.0,0.462,0.680,0.333,22.0,52.0,0
2,2021-03-21,22000646,Final,1610612743,1610612740,2020,1610612743,108.0,0.500,0.800,0.353,30.0,37.0,1610612740,113.0,0.482,0.767,0.286,26.0,45.0,0
3,2021-03-21,22000167,Final,1610612738,1610612753,2020,1610612738,112.0,0.455,1.000,0.426,27.0,45.0,1610612753,96.0,0.381,0.700,0.324,20.0,44.0,1
4,2021-03-21,22000647,Final,1610612751,1610612764,2020,1610612751,113.0,0.489,0.727,0.310,24.0,35.0,1610612764,106.0,0.532,0.789,0.333,24.0,43.0,1

In [5]:
df2.shape

(24195, 21)

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24195 entries, 0 to 24194
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     24195 non-null  object
 1   GAME_ID           24195 non-null  int64
 2   GAME_STATUS_TEXT  24195 non-null  object
 3   HOME_TEAM_ID      24195 non-null  int64
 4   VISITOR_TEAM_ID   24195 non-null  int64
 5   SEASON            24195 non-null  int64
 6   TEAM_ID_home      24195 non-null  int64
 7   PTS_home          24096 non-null  float64
 8   FG_PCT_home       24096 non-null  float64
 9   FT_PCT_home       24096 non-null  float64
 10  FG3_PCT_home      24096 non-null  float64
 11  AST_home          24096 non-null  float64
 12  REB_home          24096 non-null  float64
 13  TEAM_ID_away      24195 non-null  int64
 14  PTS_away          24096 non-null  float64
 15  FG_PCT_away       24096 non-null  float64
 16  FT_PCT_away       24096 non-null  float64
 17  FG3_PCT_away      24096 non-null  float64
 18  AST_away          24096 non-null  float64
 19  REB_away          24096 non-null  float64
 20  HOME_TEAM_WINS    24195 non-null  int64
dtypes: float64(12), int64(7), object(2)
memory usage: 3.9+ MB

In [7]:
#GAME_DATE_EST to datetime

#filter rows for dates 2006-18

#filter for date and game id columns

#rename GAME_DATE_EST and GAME_ID

#probably merge on game id, fill dates that are missing

In [8]:
#GAME_DATE_EST to datetime
df2['GAME_DATE_EST'] = pd.to_datetime(df2['GAME_DATE_EST'])
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24195 entries, 0 to 24194
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     24195 non-null  datetime64[ns]
 1   GAME_ID           24195 non-null  int64
 2   GAME_STATUS_TEXT  24195 non-null  object
 3   HOME_TEAM_ID      24195 non-null  int64
 4   VISITOR_TEAM_ID   24195 non-null  int64
 5   SEASON            24195 non-null  int64
 6   TEAM_ID_home      24195 non-null  int64
 7   PTS_home          24096 non-null  float64
 8   FG_PCT_home       24096 non-null  float64
 9   FT_PCT_home       24096 non-null  float64
 10  FG3_PCT_home      24096 non-null  float64
 11  AST_home          24096 non-null  float64
 12  REB_home          24096 non-null  float64
 13  TEAM_ID_away      24195 non-null  int64
 14  PTS_away          24096 non-null  float64
 15  FG_PCT_away       24096 non-null  float64
 16  FT_PCT_away       24096 non-null  float64
 17  FG3_PCT_away      24096 non-null  float64
 18  AST_away          24096 non-null  float64
 19  REB_away          24096 non-null  float64
 20  HOME_TEAM_WINS    24195 non-null  int64
dtypes: datetime64[ns](1), float64(12), int64(7), object(1)
memory usage: 3.9+ MB

In [9]:
#filter rows for dates 2006-18

df2 = df2[(df2['GAME_DATE_EST'].dt.year > 2005) & (df2['GAME_DATE_EST'].dt.year < 2018)]
df2

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
1602,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,25.0,40.0,1610612748,87.0,0.400,0.741,0.280,14.0,41.0,1
1603,2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,13.0,27.0,1610612759,107.0,0.571,0.720,0.429,25.0,44.0,0
1604,2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,17.0,26.0,1610612759,111.0,0.594,0.813,0.450,21.0,29.0,0
1605,2014-06-08,41300402,Final,1610612759,1610612748,2013,1610612759,96.0,0.439,0.600,0.462,26.0,37.0,1610612748,98.0,0.529,0.762,0.421,16.0,38.0,0
1606,2014-06-05,41300401,Final,1610612759,1610612748,2013,1610612759,110.0,0.588,0.773,0.520,30.0,39.0,1610612748,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24190,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
24191,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
24192,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
24193,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
24194,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [10]:
df2['GAME_DATE_EST'].dt.year.value_counts()

2012    1580
2006    1451
2008    1442
2014    1441
2013    1432
2010    1432
2016    1429
2009    1428
2015    1419
2017    1417
2007    1404
2011     915
Name: GAME_DATE_EST, dtype: int64

In [11]:
df2.GAME_ID.value_counts()[df2.GAME_ID.value_counts() == 2]

Series([], Name: GAME_ID, dtype: int64)

In [12]:
df2[df2.GAME_ID == 22000008]

Empty DataFrame
Columns: [GAME_DATE_EST, GAME_ID, GAME_STATUS_TEXT, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON, TEAM_ID_home, PTS_home, FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, TEAM_ID_away, PTS_away, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away, HOME_TEAM_WINS]
Index: []

In [13]:
#clean up duplicate rows?

In [14]:
df2 = df2.drop_duplicates().reset_index().drop(columns='index')
df2

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,25.0,40.0,1610612748,87.0,0.400,0.741,0.280,14.0,41.0,1
1,2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,13.0,27.0,1610612759,107.0,0.571,0.720,0.429,25.0,44.0,0
2,2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,17.0,26.0,1610612759,111.0,0.594,0.813,0.450,21.0,29.0,0
3,2014-06-08,41300402,Final,1610612759,1610612748,2013,1610612759,96.0,0.439,0.600,0.462,26.0,37.0,1610612748,98.0,0.529,0.762,0.421,16.0,38.0,0
4,2014-06-05,41300401,Final,1610612759,1610612748,2013,1610612759,110.0,0.588,0.773,0.520,30.0,39.0,1610612748,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
16786,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
16787,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
16788,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
16789,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [15]:
df2.GAME_ID.value_counts()[df2.GAME_ID.value_counts() == 2]

Series([], Name: GAME_ID, dtype: int64)

In [16]:
df2.GAME_ID.value_counts()[df2.GAME_ID.value_counts() == 2].count()

0

In [17]:
df2[df2.GAME_ID == 22000018]

Empty DataFrame
Columns: [GAME_DATE_EST, GAME_ID, GAME_STATUS_TEXT, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON, TEAM_ID_home, PTS_home, FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, TEAM_ID_away, PTS_away, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away, HOME_TEAM_WINS]
Index: []

In [18]:
df2.iloc[144,:] == df2.iloc[668,:]

GAME_DATE_EST       False
GAME_ID             False
GAME_STATUS_TEXT     True
HOME_TEAM_ID        False
VISITOR_TEAM_ID     False
SEASON               True
TEAM_ID_home        False
PTS_home            False
FG_PCT_home         False
FT_PCT_home         False
FG3_PCT_home        False
AST_home            False
REB_home             True
TEAM_ID_away        False
PTS_away            False
FG_PCT_away         False
FT_PCT_away         False
FG3_PCT_away        False
AST_away            False
REB_away            False
HOME_TEAM_WINS       True
dtype: bool

In [19]:
df2.iloc[144,:]

GAME_DATE_EST       2014-04-10 00:00:00
GAME_ID                        21301174
GAME_STATUS_TEXT                  Final
HOME_TEAM_ID                 1610612742
VISITOR_TEAM_ID              1610612759
SEASON                             2013
TEAM_ID_home                 1610612742
PTS_home                            100
FG_PCT_home                        0.47
FT_PCT_home                        0.81
FG3_PCT_home                      0.417
AST_home                             16
REB_home                             42
TEAM_ID_away                 1610612759
PTS_away                            109
FG_PCT_away                       0.432
FT_PCT_away                       0.773
FG3_PCT_away                      0.471
AST_away                             22
REB_away                             48
HOME_TEAM_WINS                        0
Name: 144, dtype: object

In [20]:
df2.iloc[668,:].FG3_PCT_away

0.545

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16790 entries, 0 to 16789
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     16790 non-null  datetime64[ns]
 1   GAME_ID           16790 non-null  int64
 2   GAME_STATUS_TEXT  16790 non-null  object
 3   HOME_TEAM_ID      16790 non-null  int64
 4   VISITOR_TEAM_ID   16790 non-null  int64
 5   SEASON            16790 non-null  int64
 6   TEAM_ID_home      16790 non-null  int64
 7   PTS_home          16790 non-null  float64
 8   FG_PCT_home       16790 non-null  float64
 9   FT_PCT_home       16790 non-null  float64
 10  FG3_PCT_home      16790 non-null  float64
 11  AST_home          16790 non-null  float64
 12  REB_home          16790 non-null  float64
 13  TEAM_ID_away      16790 non-null  int64
 14  PTS_away          16790 non-null  float64
 15  FG_PCT_away       16790 non-null  float64
 16  FT_PCT_away       16790 non-null  float64
 17  FG3_PCT_away      16790 non-null  float64
 18  AST_away          16790 non-null  float64
 19  REB_away          16790 non-null  float64
 20  HOME_TEAM_WINS    16790 non-null  int64
dtypes: datetime64[ns](1), float64(12), int64(7), object(1)
memory usage: 2.7+ MB

In [22]:
df2.iloc[668,:].FG3_PCT_away

0.545

In [23]:
df2.iloc[144,:].FG3_PCT_away

0.47100000000000003

In [24]:
#round FG3_PCT_away column to 3 decimal places and check for duplicate rows again?

In [25]:
df2.FG3_PCT_away = round(df2.FG3_PCT_away, 3)
df2

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,25.0,40.0,1610612748,87.0,0.400,0.741,0.280,14.0,41.0,1
1,2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,13.0,27.0,1610612759,107.0,0.571,0.720,0.429,25.0,44.0,0
2,2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,17.0,26.0,1610612759,111.0,0.594,0.813,0.450,21.0,29.0,0
3,2014-06-08,41300402,Final,1610612759,1610612748,2013,1610612759,96.0,0.439,0.600,0.462,26.0,37.0,1610612748,98.0,0.529,0.762,0.421,16.0,38.0,0
4,2014-06-05,41300401,Final,1610612759,1610612748,2013,1610612759,110.0,0.588,0.773,0.520,30.0,39.0,1610612748,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
16786,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
16787,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
16788,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
16789,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [26]:
df2.iloc[668,:].FG3_PCT_away

0.545

In [27]:
df2.iloc[144,:].FG3_PCT_away

0.471

In [28]:
df2.iloc[144,:] == df2.iloc[668,:]

GAME_DATE_EST       False
GAME_ID             False
GAME_STATUS_TEXT     True
HOME_TEAM_ID        False
VISITOR_TEAM_ID     False
SEASON               True
TEAM_ID_home        False
PTS_home            False
FG_PCT_home         False
FT_PCT_home         False
FG3_PCT_home        False
AST_home            False
REB_home             True
TEAM_ID_away        False
PTS_away            False
FG_PCT_away         False
FT_PCT_away         False
FG3_PCT_away        False
AST_away            False
REB_away            False
HOME_TEAM_WINS       True
dtype: bool

In [29]:
df2 = df2.drop_duplicates()
df2

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,25.0,40.0,1610612748,87.0,0.400,0.741,0.280,14.0,41.0,1
1,2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,13.0,27.0,1610612759,107.0,0.571,0.720,0.429,25.0,44.0,0
2,2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,17.0,26.0,1610612759,111.0,0.594,0.813,0.450,21.0,29.0,0
3,2014-06-08,41300402,Final,1610612759,1610612748,2013,1610612759,96.0,0.439,0.600,0.462,26.0,37.0,1610612748,98.0,0.529,0.762,0.421,16.0,38.0,0
4,2014-06-05,41300401,Final,1610612759,1610612748,2013,1610612759,110.0,0.588,0.773,0.520,30.0,39.0,1610612748,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
16786,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
16787,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
16788,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
16789,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [30]:
columns_names2 = df2.columns
columns_names2

Index(['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'PTS_home', 'FG_PCT_home',
       'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TEAM_ID_away',
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
       'REB_away', 'HOME_TEAM_WINS'],
      dtype='object')

In [31]:
df2.drop(columns=['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'TEAM_ID_away']).round(3)

,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,104.0,0.474,0.783,0.462,25.0,40.0,87.0,0.400,0.741,0.280,14.0,41.0,1
1,86.0,0.451,0.650,0.409,13.0,27.0,107.0,0.571,0.720,0.429,25.0,44.0,0
2,92.0,0.516,0.750,0.476,17.0,26.0,111.0,0.594,0.813,0.450,21.0,29.0,0
3,96.0,0.439,0.600,0.462,26.0,37.0,98.0,0.529,0.762,0.421,16.0,38.0,0
4,110.0,0.588,0.773,0.520,30.0,39.0,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,93.0,0.419,0.821,0.421,24.0,50.0,87.0,0.366,0.643,0.375,17.0,43.0,1
16786,81.0,0.338,0.719,0.381,18.0,40.0,85.0,0.411,0.636,0.267,17.0,47.0,0
16787,98.0,0.448,0.682,0.500,29.0,45.0,95.0,0.387,0.659,0.500,19.0,43.0,1
16788,99.0,0.440,0.771,0.333,21.0,30.0,94.0,0.469,0.725,0.385,18.0,45.0,1
16789,86.0,0.431,0.679,0.333,18.0,42.0,98.0,0.462,0.706,0.438,19.0,42.0,0

In [32]:
df2[['PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
      'REB_away', 'HOME_TEAM_WINS']] = df2.drop(columns=['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'TEAM_ID_away']).round(3)

df2[['PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
      'REB_away', 'HOME_TEAM_WINS']]

,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,104.0,0.474,0.783,0.462,25.0,40.0,87.0,0.400,0.741,0.280,14.0,41.0,1
1,86.0,0.451,0.650,0.409,13.0,27.0,107.0,0.571,0.720,0.429,25.0,44.0,0
2,92.0,0.516,0.750,0.476,17.0,26.0,111.0,0.594,0.813,0.450,21.0,29.0,0
3,96.0,0.439,0.600,0.462,26.0,37.0,98.0,0.529,0.762,0.421,16.0,38.0,0
4,110.0,0.588,0.773,0.520,30.0,39.0,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,93.0,0.419,0.821,0.421,24.0,50.0,87.0,0.366,0.643,0.375,17.0,43.0,1
16786,81.0,0.338,0.719,0.381,18.0,40.0,85.0,0.411,0.636,0.267,17.0,47.0,0
16787,98.0,0.448,0.682,0.500,29.0,45.0,95.0,0.387,0.659,0.500,19.0,43.0,1
16788,99.0,0.440,0.771,0.333,21.0,30.0,94.0,0.469,0.725,0.385,18.0,45.0,1
16789,86.0,0.431,0.679,0.333,18.0,42.0,98.0,0.462,0.706,0.438,19.0,42.0,0

In [33]:
df2 = df2.drop_duplicates().reset_index().drop(columns='index')
df2

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,25.0,40.0,1610612748,87.0,0.400,0.741,0.280,14.0,41.0,1
1,2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,13.0,27.0,1610612759,107.0,0.571,0.720,0.429,25.0,44.0,0
2,2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,17.0,26.0,1610612759,111.0,0.594,0.813,0.450,21.0,29.0,0
3,2014-06-08,41300402,Final,1610612759,1610612748,2013,1610612759,96.0,0.439,0.600,0.462,26.0,37.0,1610612748,98.0,0.529,0.762,0.421,16.0,38.0,0
4,2014-06-05,41300401,Final,1610612759,1610612748,2013,1610612759,110.0,0.588,0.773,0.520,30.0,39.0,1610612748,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
16786,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
16787,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
16788,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
16789,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [34]:
df2.GAME_ID.value_counts()[df2.GAME_ID.value_counts() == 2]

Series([], Name: GAME_ID, dtype: int64)

In [35]:
df2[df2.GAME_ID == 22000070]

Empty DataFrame
Columns: [GAME_DATE_EST, GAME_ID, GAME_STATUS_TEXT, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON, TEAM_ID_home, PTS_home, FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, TEAM_ID_away, PTS_away, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away, HOME_TEAM_WINS]
Index: []

In [36]:
df2.iloc[74,:]

GAME_DATE_EST       2014-04-23 00:00:00
GAME_ID                        41300142
GAME_STATUS_TEXT                  Final
HOME_TEAM_ID                 1610612759
VISITOR_TEAM_ID              1610612742
SEASON                             2013
TEAM_ID_home                 1610612759
PTS_home                             92
FG_PCT_home                         0.5
FT_PCT_home                       0.621
FG3_PCT_home                        0.5
AST_home                             17
REB_home                             32
TEAM_ID_away                 1610612742
PTS_away                            113
FG_PCT_away                       0.489
FT_PCT_away                       0.938
FG3_PCT_away                      0.381
AST_away                             19
REB_away                             35
HOME_TEAM_WINS                        0
Name: 74, dtype: object

In [37]:
df2.iloc[626,:]

GAME_DATE_EST       2014-01-31 00:00:00
GAME_ID                        21300690
GAME_STATUS_TEXT                  Final
HOME_TEAM_ID                 1610612755
VISITOR_TEAM_ID              1610612737
SEASON                             2013
TEAM_ID_home                 1610612755
PTS_home                             99
FG_PCT_home                       0.368
FT_PCT_home                       0.784
FG3_PCT_home                      0.273
AST_home                             19
REB_home                             46
TEAM_ID_away                 1610612737
PTS_away                            125
FG_PCT_away                       0.506
FT_PCT_away                       0.794
FG3_PCT_away                        0.5
AST_away                             36
REB_away                             46
HOME_TEAM_WINS                        0
Name: 626, dtype: object

In [38]:
df2.iloc[74,:] == df2.iloc[626,:]

GAME_DATE_EST       False
GAME_ID             False
GAME_STATUS_TEXT     True
HOME_TEAM_ID        False
VISITOR_TEAM_ID     False
SEASON               True
TEAM_ID_home        False
PTS_home            False
FG_PCT_home         False
FT_PCT_home         False
FG3_PCT_home        False
AST_home            False
REB_home            False
TEAM_ID_away        False
PTS_away            False
FG_PCT_away         False
FT_PCT_away         False
FG3_PCT_away        False
AST_away            False
REB_away            False
HOME_TEAM_WINS       True
dtype: bool

In [39]:
df2[df2.GAME_ID == 22000076]

Empty DataFrame
Columns: [GAME_DATE_EST, GAME_ID, GAME_STATUS_TEXT, HOME_TEAM_ID, VISITOR_TEAM_ID, SEASON, TEAM_ID_home, PTS_home, FG_PCT_home, FT_PCT_home, FG3_PCT_home, AST_home, REB_home, TEAM_ID_away, PTS_away, FG_PCT_away, FT_PCT_away, FG3_PCT_away, AST_away, REB_away, HOME_TEAM_WINS]
Index: []

In [40]:
df2.iloc[80,:] == df2.iloc[627,:]

GAME_DATE_EST       False
GAME_ID             False
GAME_STATUS_TEXT     True
HOME_TEAM_ID        False
VISITOR_TEAM_ID     False
SEASON               True
TEAM_ID_home        False
PTS_home            False
FG_PCT_home         False
FT_PCT_home         False
FG3_PCT_home        False
AST_home            False
REB_home            False
TEAM_ID_away        False
PTS_away            False
FG_PCT_away         False
FT_PCT_away         False
FG3_PCT_away        False
AST_away            False
REB_away            False
HOME_TEAM_WINS      False
dtype: bool

In [41]:
df2.rename(columns={'GAME_DATE_EST':'game_date', 'GAME_ID':'game_id'}, inplace=True)
df2

,game_date,game_id,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2014-06-15,41300405,Final,1610612759,1610612748,2013,1610612759,104.0,0.474,0.783,0.462,25.0,40.0,1610612748,87.0,0.400,0.741,0.280,14.0,41.0,1
1,2014-06-12,41300404,Final,1610612748,1610612759,2013,1610612748,86.0,0.451,0.650,0.409,13.0,27.0,1610612759,107.0,0.571,0.720,0.429,25.0,44.0,0
2,2014-06-10,41300403,Final,1610612748,1610612759,2013,1610612748,92.0,0.516,0.750,0.476,17.0,26.0,1610612759,111.0,0.594,0.813,0.450,21.0,29.0,0
3,2014-06-08,41300402,Final,1610612759,1610612748,2013,1610612759,96.0,0.439,0.600,0.462,26.0,37.0,1610612748,98.0,0.529,0.762,0.421,16.0,38.0,0
4,2014-06-05,41300401,Final,1610612759,1610612748,2013,1610612759,110.0,0.588,0.773,0.520,30.0,39.0,1610612748,95.0,0.474,0.818,0.414,16.0,29.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16785,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
16786,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
16787,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
16788,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
16789,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [42]:
df2[['game_date', 'game_id']]

       game_date   game_id
0     2014-06-15  41300405
1     2014-06-12  41300404
2     2014-06-10  41300403
3     2014-06-08  41300402
4     2014-06-05  41300401
...          ...       ...
16785 2014-10-06  11400007
16786 2014-10-06  11400004
16787 2014-10-06  11400005
16788 2014-10-05  11400002
16789 2014-10-04  11400001

[16790 rows x 2 columns]

In [46]:
df2 = df2[['game_date', 'game_id']].drop_duplicates().sort_values('game_id').reset_index().drop('index', axis=1)
df2

       game_date   game_id
0     2006-10-09  10600007
1     2006-10-10  10600008
2     2006-10-10  10600009
3     2006-10-10  10600010
4     2006-10-10  10600012
...          ...       ...
16785 2017-06-01  41600401
16786 2017-06-04  41600402
16787 2017-06-07  41600403
16788 2017-06-09  41600404
16789 2017-06-12  41600405

[16790 rows x 2 columns]

In [47]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16790 entries, 0 to 16789
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_date  16790 non-null  datetime64[ns]
 1   game_id    16790 non-null  int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 262.5 KB

In [48]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '2game_id_game_date.csv')
if not os.path.exists(datapath_df):
    df2.to_csv(datapath_df, index=True)

In [ ]:
#df2.drop(columns=['PTS_home', 'FG_PCT_home',
#       'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 
#       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
 #      'REB_away', 'HOME_TEAM_WINS'])

In [ ]:
df2.game_id.value_counts()[df2.game_id.value_counts() == 2]

In [ ]:
df2.game_id.value_counts()[df2.game_id.value_counts() == 2].count()

In [ ]:
df_games = df_games[(df_games.season_type == 'Regular Season' ) |
                    (df_games.season_type == 'Playoffs')][(df_games.season == '2006-07') |
                    (df_games.season == '2007-08') |
                    (df_games.season == '2008-09') |
                    (df_games.season == '2009-10') | 
                    (df_games.season == '2010-11') |
                    (df_games.season == '2011-12') |
                    (df_games.season == '2012-13') |
                    (df_games.season == '2013-14') |
                    (df_games.season == '2014-15') |
                    (df_games.season == '2015-16') | 
                    (df_games.season == '2016-17') | 
                    (df_games.season == '2017-18')]
df_games

In [ ]:
df_games.info()

In [ ]:
df_games[df_games.game_date.isnull()]

In [ ]:
df_games[df_games.game_date.isnull()].season.value_counts()

In [ ]:
df_games[df_games.game_date.isnull()].season.value_counts().sort_index()

In [ ]:
df_games[df_games.season == '2017-18']

In [ ]:
df_games[df_games.game_id == 21700049]

In [ ]:
df_games['game_date'] = pd.to_datetime(df_games['game_date'])
df_games.info()

In [ ]:
column_names = df_games.columns
column_names

In [ ]:
column_names = column_names.drop(['game_id', 'game_date', 'is_home', 'season_year', 'season_type', 'season'])
column_names

In [ ]:
empty_df = df_games[df_games.is_home == 'f']

for column_name in column_names:
    empty_df = empty_df[empty_df.is_home == 'f'].rename(columns={column_name: column_name + '_away'})
    
empty_df = empty_df.drop(columns=['is_home'])

In [ ]:
for column_name in column_names:
    df_games = df_games[df_games.is_home == 't'].rename(columns={column_name: column_name + '_home'})
    
df_games = df_games.drop(columns='is_home')

In [ ]:
df_games.info() #<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<

In [ ]:
#df_games[df_games['w_home'].isnull()]['season'].hist(bins=111)

In [ ]:
#df_games[df_games['w_home'].isnull()]['season'].value_counts().sort_index()

In [ ]:
#number of games actual: https://www.landofbasketball.com/results/2015_2016_scores.htm
df_games['season'].value_counts().sort_index()

In [ ]:
#uniques
df_games[df_games['season'] == '2005-06']

In [ ]:
df_games[df_games['season'] == '2005-06'].game_id.value_counts().hist(bins=11)

In [ ]:
df_games[df_games['season'] == '2005-06'][df_games['season_type'] == 'Regular Season']

In [ ]:
df_games[df_games['season'] == '2005-06'].season_type.value_counts()

In [ ]:
#do we have betting data for preseason games?

In [ ]:
df_totals = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_betting_totals.csv')
df_totals

In [ ]:
df_totals.game_id.unique()

In [ ]:
type(df_totals.game_id.unique())

In [ ]:
len(df_totals.game_id.unique())

In [ ]:
df_games[df_games['season'] == '2005-06'][df_games['season_type'] == 'Pre Season']

In [ ]:
series_pre = df_games[df_games['season'] == '2005-06'][df_games['season_type'] == 'Pre Season'].game_id
series_pre

In [ ]:
type(series_pre)

In [ ]:
set_pre = set(series_pre)
set_pre

In [ ]:
set_totals = set(df_totals.game_id)
set_totals

In [ ]:
set_totals.intersection(set_pre)

In [ ]:
set_pre.intersection(set_totals)

In [ ]:
series_reg = df_games[df_games['season'] == '2005-06'][df_games['season_type'] == 'Regular Season'].game_id
series_reg

In [ ]:
set_reg = set(series_reg)

In [ ]:
set_totals.intersection(set_reg)

In [ ]:
set_reg.intersection(set_totals)

In [ ]:
{1, 2, 3}.intersection({1, 2})

In [ ]:
set_reg

In [ ]:
set_totals

In [ ]:
df_game_id_totals = df_totals.game_id.value_counts().to_frame().reset_index().drop(columns='game_id').rename(columns={'index':'game_id'})
df_game_id_totals

In [ ]:
df_intersection = pd.merge(df_game_id_totals, df_games, how='inner')
df_intersection

In [ ]:
df_intersection.season_type.value_counts()

In [ ]:
df_intersection[df_intersection['season'] == '2016-17']

In [ ]:
df_intersection.season.value_counts().sort_index()

In [ ]:
#2006-07 to 2017-18 are the seasons of interest and looking at just regular season and playoffs

In [ ]:
df_intersection[df_intersection.season_type == 'Pre Season']['season'].value_counts()

In [ ]:
df_intersection = df_intersection[df_intersection.season_type != 'Pre Season']
df_intersection

In [ ]:
df_intersection.game_id.value_counts()

<font color='red'> hereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehereherehere</font>

In [ ]:
#add columns to original dataframe
df_games.columns

In [ ]:
away_column_names = empty_df.columns.drop(['game_id', 'game_date', 'is_home',
                                           'team_id_away', 'is_home'])
away_column_names

In [ ]:
cols_numeric = empty_df.select_dtypes([np.number]).columns.drop('game_id')
cols_numeric

In [ ]:
df_games.info()

In [ ]:
for column in cols_numeric:
    df_games[column] = 0
df_games

In [ ]:
empty_df.drop(columns=['is_home', 'season_type', 'season'], inplace=True)
empty_df.info()

In [ ]:
df = pd.concat([df_games, empty_df])
df

In [ ]:
df.info()

In [ ]:

start  = time.time()
df = df.groupby(['game_id', 'game_date']).sum()
t = time.time() - start
df

In [ ]:
t

In [ ]:
df

In [ ]:
#pd.merge(df_games, empty_df, on=['game_id', 'game_date']).set_index(['game_id', 'game_date'])

In [ ]:
#pd.merge(df_games, empty_df, on=['game_id', 'game_date']).set_index(['game_id', 'game_date'])

In [ ]:
df_years = pd.to_datetime(df_games.game_date)
df_years

In [ ]:
df_years.dt.year.value_counts().sort_values()

In [ ]:
df_teams = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_teams_all.csv')
df_teams.head()

In [ ]:
df_games = df_games[df_games.season_type == 'Regular Season'][(df_games.season == '2006-07') |
                                                   (df_games.season == '2007-08') |
                                                   (df_games.season == '2008-09') |
                                                   (df_games.season == '2009-10') | 
                                                   (df_games.season == '2010-11') |
                                                   (df_games.season == '2011-12') |
                                                   (df_games.season == '2012-13') |
                                                   (df_games.season == '2013-14') |
                                                   (df_games.season == '2014-15') |
                                                   (df_games.season == '2015-16') | 
                                                   (df_games.season == '2016-17') | 
                                                   (df_games.season == '2017-18')]
df_games

In [ ]:
df_games = pd.merge(df_games
         , df_teams[['team_id','abbreviation']], on=['team_id'], how='left')
df_games

In [ ]:
df_games.sort_values('game_id')

In [ ]:
df_games[df_games['game_id'] == 20600001]

In [ ]:
df_games = df_games[df_games['game_date'].notnull()]

In [ ]:
df_games.shape

In [ ]:
df_games.sort_values('game_id', inplace=True)

In [ ]:
df_games = df_games.reset_index().drop(columns='index')
df_games

In [ ]:
game_ids = df_games.game_id.unique()
game_ids

In [ ]:
df_games['game_date'] = pd.to_datetime(df_games['game_date'])

In [ ]:
def build_game_date_indexed_rows():
    df_empty = pd.DataFrame({})

    for id_ in game_ids:

        visitor_ = df_games[df_games['is_home'] == 'f'][df_games['game_id'] == id_]
        home_ = df_games[df_games['is_home'] == 't'][df_games['game_id'] == id_]


        #visitor team abbreviation
        s0 = str('_') + df_games[df_games['game_id'] == id_][df_games['is_home'] == 'f']['abbreviation'].iloc[0]

        #home team abbreviation
        s1 = str('_') + df_games[df_games['game_id'] == id_][df_games['is_home'] == 't']['abbreviation'].iloc[0]


        df_single_game = pd.merge(visitor_, home_, on=['game_id', 'game_date'], how='inner', suffixes=[s0, s1])

        df_empty = pd.concat([df_empty, df_single_game])
    
    df_empty = df_empty.reset_index().drop(columns='index').set_index(['game_id', 'game_date'])
    return df_empty

In [ ]:
import time
start_time = time.time()

In [ ]:

df = build_game_date_indexed_rows()

In [ ]:
df

In [ ]:
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
print("--- %s minutes ---" % ((time.time() - start_time) / 60))

In [ ]:
df.iloc[:, 1]

In [ ]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '1games_df.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=True)