In [1]:
import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

In [2]:
df_games = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_games_all.csv').drop(columns=['matchup',
                                                                                                          'a_team_id', 'wl'])
df_games.head()

,game_id,game_date,team_id,is_home,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
0,20800741,2009-02-06,1610612762,f,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,2008,Regular Season,2008-09
1,20800701,2009-01-31,1610612762,f,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,2008,Regular Season,2008-09
2,20800584,2009-01-16,1610612762,f,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,2008,Regular Season,2008-09
3,20800558,2009-01-12,1610612762,t,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,2008,Regular Season,2008-09
4,20800440,2008-12-27,1610612762,f,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,2008,Regular Season,2008-09

In [3]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125624 entries, 0 to 125623
Data columns (total 29 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      125624 non-null  int64
 1   game_date    119376 non-null  object
 2   team_id      125624 non-null  int64
 3   is_home      125624 non-null  object
 4   w            41000 non-null   float64
 5   l            41000 non-null   float64
 6   w_pct        41000 non-null   float64
 7   min          125624 non-null  int64
 8   fgm          125607 non-null  float64
 9   fga          90894 non-null   float64
 10  fg_pct       90871 non-null   float64
 11  fg3m         95248 non-null   float64
 12  fg3a         84316 non-null   float64
 13  fg3_pct      80062 non-null   float64
 14  ftm          125605 non-null  float64
 15  fta          120011 non-null  float64
 16  ft_pct       119960 non-null  float64
 17  oreb         83786 non-null   float64
 18  dreb         83639 non-null   float64
 19  reb          125624 non-null  int64
 20  ast          90068 non-null   float64
 21  stl          83960 non-null   float64
 22  blk          84407 non-null   float64
 23  tov          84293 non-null   float64
 24  pf           121742 non-null  float64
 25  pts          125624 non-null  int64
 26  season_year  125624 non-null  int64
 27  season_type  125624 non-null  object
 28  season       125624 non-null  object
dtypes: float64(19), int64(6), object(4)
memory usage: 27.8+ MB

In [4]:
df_games['game_date'] = pd.to_datetime(df_games['game_date'])
df_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125624 entries, 0 to 125623
Data columns (total 29 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      125624 non-null  int64
 1   game_date    119376 non-null  datetime64[ns]
 2   team_id      125624 non-null  int64
 3   is_home      125624 non-null  object
 4   w            41000 non-null   float64
 5   l            41000 non-null   float64
 6   w_pct        41000 non-null   float64
 7   min          125624 non-null  int64
 8   fgm          125607 non-null  float64
 9   fga          90894 non-null   float64
 10  fg_pct       90871 non-null   float64
 11  fg3m         95248 non-null   float64
 12  fg3a         84316 non-null   float64
 13  fg3_pct      80062 non-null   float64
 14  ftm          125605 non-null  float64
 15  fta          120011 non-null  float64
 16  ft_pct       119960 non-null  float64
 17  oreb         83786 non-null   float64
 18  dreb         83639 non-null   float64
 19  reb          125624 non-null  int64
 20  ast          90068 non-null   float64
 21  stl          83960 non-null   float64
 22  blk          84407 non-null   float64
 23  tov          84293 non-null   float64
 24  pf           121742 non-null  float64
 25  pts          125624 non-null  int64
 26  season_year  125624 non-null  int64
 27  season_type  125624 non-null  object
 28  season       125624 non-null  object
dtypes: datetime64[ns](1), float64(19), int64(6), object(3)
memory usage: 27.8+ MB

In [5]:
column_names = df_games.columns
column_names

Index(['game_id', 'game_date', 'team_id', 'is_home', 'w', 'l', 'w_pct', 'min',
       'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
       'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'pts', 'season_year', 'season_type', 'season'],
      dtype='object')

In [6]:
type(column_names)

pandas.core.indexes.base.Index

In [7]:
column_names = column_names.drop(['game_id', 'game_date', 'is_home', 'season_year', 'season_type', 'season'])
column_names

Index(['team_id', 'w', 'l', 'w_pct', 'min', 'fgm', 'fga', 'fg_pct', 'fg3m',
       'fg3a', 'fg3_pct', 'ftm', 'fta', 'ft_pct', 'oreb', 'dreb', 'reb', 'ast',
       'stl', 'blk', 'tov', 'pf', 'pts'],
      dtype='object')

In [8]:
empty_df = df_games[df_games.is_home == 'f']

for column_name in column_names:
    empty_df = empty_df[empty_df.is_home == 'f'].rename(columns={column_name: column_name + '_away'})
    
empty_df

,game_id,game_date,team_id_away,is_home,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_year,season_type,season
0,20800741,2009-02-06,1610612762,f,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,2008,Regular Season,2008-09
1,20800701,2009-01-31,1610612762,f,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,2008,Regular Season,2008-09
2,20800584,2009-01-16,1610612762,f,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,2008,Regular Season,2008-09
4,20800440,2008-12-27,1610612762,f,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,2008,Regular Season,2008-09
5,20800395,2008-12-20,1610612762,f,17.0,12.0,0.586,240,38.0,79.0,0.481,2.0,11.0,0.182,20.0,22.0,1.0,12.0,21.0,33,21.0,9.0,5.0,20.0,19.0,98,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125613,20800441,2008-12-27,1610612765,f,17.0,11.0,0.607,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87,2008,Regular Season,2008-09
125614,20800052,2008-11-05,1610612765,f,4.0,0.0,1.000,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100,2008,Regular Season,2008-09
125615,20800042,2008-11-03,1610612765,f,3.0,0.0,1.000,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101,2008,Regular Season,2008-09
125618,10800025,NaT,1610612765,f,3.0,0.0,1.000,240,27.0,67.0,0.403,1.0,6.0,0.167,18.0,26.0,1.0,5.0,31.0,36,18.0,13.0,4.0,17.0,17.0,73,2008,Pre Season,2008-09
125621,20801029,2009-03-20,1610612762,f,43.0,26.0,0.623,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,2008,Regular Season,2008-09

In [9]:
for column_name in column_names:
    df_games = df_games[df_games.is_home == 't'].rename(columns={column_name: column_name + '_home'})
    
df_games

,game_id,game_date,team_id_home,is_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,season_type,season
3,20800558,2009-01-12,1610612762,t,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,2008,Regular Season,2008-09
6,29800603,1999-04-21,1610612764,t,NaN,NaN,NaN,240,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43,18.0,7.0,3.0,15.0,24.0,91,1998,Regular Season,1998-99
7,29800577,1999-04-18,1610612764,t,NaN,NaN,NaN,240,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39,23.0,9.0,5.0,17.0,26.0,98,1998,Regular Season,1998-99
8,29800561,1999-04-16,1610612764,t,NaN,NaN,NaN,240,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51,21.0,9.0,4.0,14.0,16.0,87,1998,Regular Season,1998-99
9,20800344,2008-12-13,1610612762,t,15.0,10.0,0.600,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125617,10800107,NaT,1610612765,t,6.0,2.0,0.750,240,34.0,87.0,0.391,5.0,14.0,0.357,14.0,18.0,1.0,10.0,32.0,42,21.0,9.0,4.0,14.0,23.0,87,2008,Pre Season,2008-09
125619,20801131,2009-04-03,1610612762,t,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,2008,Regular Season,2008-09
125620,20801058,2009-03-24,1610612762,t,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,2008,Regular Season,2008-09
125622,20800839,2009-02-23,1610612762,t,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,2008,Regular Season,2008-09
125623,20800810,2009-02-19,1610612762,t,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,2008,Regular Season,2008-09

In [10]:
#add columns to original dataframe
df_games.columns

Index(['game_id', 'game_date', 'team_id_home', 'is_home', 'w_home', 'l_home',
       'w_pct_home', 'min_home', 'fgm_home', 'fga_home', 'fg_pct_home',
       'fg3m_home', 'fg3a_home', 'fg3_pct_home', 'ftm_home', 'fta_home',
       'ft_pct_home', 'oreb_home', 'dreb_home', 'reb_home', 'ast_home',
       'stl_home', 'blk_home', 'tov_home', 'pf_home', 'pts_home',
       'season_year', 'season_type', 'season'],
      dtype='object')

In [11]:
away_column_names = empty_df.columns.drop(['game_id', 'game_date', 'is_home',
                                           'team_id_away', 'is_home'])
away_column_names

Index(['w_away', 'l_away', 'w_pct_away', 'min_away', 'fgm_away', 'fga_away',
       'fg_pct_away', 'fg3m_away', 'fg3a_away', 'fg3_pct_away', 'ftm_away',
       'fta_away', 'ft_pct_away', 'oreb_away', 'dreb_away', 'reb_away',
       'ast_away', 'stl_away', 'blk_away', 'tov_away', 'pf_away', 'pts_away',
       'season_year', 'season_type', 'season'],
      dtype='object')

In [12]:
cols_numeric = empty_df.select_dtypes([np.number]).columns.drop('game_id')
cols_numeric

Index(['team_id_away', 'w_away', 'l_away', 'w_pct_away', 'min_away',
       'fgm_away', 'fga_away', 'fg_pct_away', 'fg3m_away', 'fg3a_away',
       'fg3_pct_away', 'ftm_away', 'fta_away', 'ft_pct_away', 'oreb_away',
       'dreb_away', 'reb_away', 'ast_away', 'stl_away', 'blk_away', 'tov_away',
       'pf_away', 'pts_away', 'season_year'],
      dtype='object')

In [13]:
df_games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62812 entries, 3 to 125623
Data columns (total 29 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       62812 non-null  int64
 1   game_date     59688 non-null  datetime64[ns]
 2   team_id_home  62812 non-null  int64
 3   is_home       62812 non-null  object
 4   w_home        20500 non-null  float64
 5   l_home        20500 non-null  float64
 6   w_pct_home    20500 non-null  float64
 7   min_home      62812 non-null  int64
 8   fgm_home      62802 non-null  float64
 9   fga_home      45447 non-null  float64
 10  fg_pct_home   45434 non-null  float64
 11  fg3m_home     47624 non-null  float64
 12  fg3a_home     42158 non-null  float64
 13  fg3_pct_home  40025 non-null  float64
 14  ftm_home      62800 non-null  float64
 15  fta_home      60004 non-null  float64
 16  ft_pct_home   59981 non-null  float64
 17  oreb_home     41893 non-null  float64
 18  dreb_home     41819 non-null  float64
 19  reb_home      62812 non-null  int64
 20  ast_home      45032 non-null  float64
 21  stl_home      41980 non-null  float64
 22  blk_home      42203 non-null  float64
 23  tov_home      42147 non-null  float64
 24  pf_home       60868 non-null  float64
 25  pts_home      62812 non-null  int64
 26  season_year   62812 non-null  int64
 27  season_type   62812 non-null  object
 28  season        62812 non-null  object
dtypes: datetime64[ns](1), float64(19), int64(6), object(3)
memory usage: 14.4+ MB

In [14]:
for column in cols_numeric:
    df_games[column] = 0
df_games

,game_id,game_date,team_id_home,is_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,season_type,season,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away
3,20800558,2009-01-12,1610612762,t,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,29800603,1999-04-21,1610612764,t,NaN,NaN,NaN,240,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43,18.0,7.0,3.0,15.0,24.0,91,0,Regular Season,1998-99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,29800577,1999-04-18,1610612764,t,NaN,NaN,NaN,240,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39,23.0,9.0,5.0,17.0,26.0,98,0,Regular Season,1998-99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,29800561,1999-04-16,1610612764,t,NaN,NaN,NaN,240,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51,21.0,9.0,4.0,14.0,16.0,87,0,Regular Season,1998-99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,20800344,2008-12-13,1610612762,t,15.0,10.0,0.600,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125617,10800107,NaT,1610612765,t,6.0,2.0,0.750,240,34.0,87.0,0.391,5.0,14.0,0.357,14.0,18.0,1.0,10.0,32.0,42,21.0,9.0,4.0,14.0,23.0,87,0,Pre Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125619,20801131,2009-04-03,1610612762,t,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125620,20801058,2009-03-24,1610612762,t,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125622,20800839,2009-02-23,1610612762,t,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125623,20800810,2009-02-19,1610612762,t,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
empty_df.drop(columns=['is_home', 'season_type', 'season'], inplace=True)
empty_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62812 entries, 0 to 125621
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       62812 non-null  int64
 1   game_date     59688 non-null  datetime64[ns]
 2   team_id_away  62812 non-null  int64
 3   w_away        20500 non-null  float64
 4   l_away        20500 non-null  float64
 5   w_pct_away    20500 non-null  float64
 6   min_away      62812 non-null  int64
 7   fgm_away      62805 non-null  float64
 8   fga_away      45447 non-null  float64
 9   fg_pct_away   45437 non-null  float64
 10  fg3m_away     47624 non-null  float64
 11  fg3a_away     42158 non-null  float64
 12  fg3_pct_away  40037 non-null  float64
 13  ftm_away      62805 non-null  float64
 14  fta_away      60007 non-null  float64
 15  ft_pct_away   59979 non-null  float64
 16  oreb_away     41893 non-null  float64
 17  dreb_away     41820 non-null  float64
 18  reb_away      62812 non-null  int64
 19  ast_away      45036 non-null  float64
 20  stl_away      41980 non-null  float64
 21  blk_away      42204 non-null  float64
 22  tov_away      42146 non-null  float64
 23  pf_away       60874 non-null  float64
 24  pts_away      62812 non-null  int64
 25  season_year   62812 non-null  int64
dtypes: datetime64[ns](1), float64(19), int64(6)
memory usage: 12.9 MB

In [16]:
df = pd.concat([df_games, empty_df])
df

,game_id,game_date,team_id_home,is_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,season_type,season,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away
3,20800558,2009-01-12,1.610613e+09,t,23.0,15.0,0.605,240.0,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40.0,24.0,10.0,6.0,8.0,20.0,120.0,0,Regular Season,2008-09,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
6,29800603,1999-04-21,1.610613e+09,t,NaN,NaN,NaN,240.0,38.0,85.0,0.447,3.0,8.0,0.375,12.0,19.0,1.0,16.0,27.0,43.0,18.0,7.0,3.0,15.0,24.0,91.0,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
7,29800577,1999-04-18,1.610613e+09,t,NaN,NaN,NaN,240.0,33.0,76.0,0.434,4.0,7.0,0.571,28.0,40.0,1.0,11.0,28.0,39.0,23.0,9.0,5.0,17.0,26.0,98.0,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
8,29800561,1999-04-16,1.610613e+09,t,NaN,NaN,NaN,240.0,37.0,83.0,0.446,2.0,10.0,0.200,11.0,15.0,1.0,6.0,45.0,51.0,21.0,9.0,4.0,14.0,16.0,87.0,0,Regular Season,1998-99,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
9,20800344,2008-12-13,1.610613e+09,t,15.0,10.0,0.600,240.0,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46.0,25.0,11.0,4.0,22.0,23.0,94.0,0,Regular Season,2008-09,0,0.0,0.0,0.000,0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125613,20800441,2008-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,17.0,11.0,0.607,240,34.0,79.0,0.430,3.0,16.0,0.188,16.0,20.0,1.0,15.0,38.0,53,16.0,8.0,5.0,12.0,27.0,87
125614,20800052,2008-11-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,4.0,0.0,1.000,240,39.0,85.0,0.459,3.0,12.0,0.250,19.0,22.0,1.0,10.0,33.0,43,21.0,6.0,5.0,5.0,18.0,100
125615,20800042,2008-11-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,3.0,0.0,1.000,240,42.0,84.0,0.500,8.0,16.0,0.500,9.0,11.0,1.0,16.0,26.0,42,23.0,4.0,4.0,8.0,22.0,101
125618,10800025,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612765,3.0,0.0,1.000,240,27.0,67.0,0.403,1.0,6.0,0.167,18.0,26.0,1.0,5.0,31.0,36,18.0,13.0,4.0,17.0,17.0,73
125621,20801029,2009-03-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008,NaN,NaN,1610612762,43.0,26.0,0.623,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 125624 entries, 3 to 125621
Data columns (total 52 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   game_id       125624 non-null  int64
 1   game_date     119376 non-null  datetime64[ns]
 2   team_id_home  62812 non-null   float64
 3   is_home       62812 non-null   object
 4   w_home        20500 non-null   float64
 5   l_home        20500 non-null   float64
 6   w_pct_home    20500 non-null   float64
 7   min_home      62812 non-null   float64
 8   fgm_home      62802 non-null   float64
 9   fga_home      45447 non-null   float64
 10  fg_pct_home   45434 non-null   float64
 11  fg3m_home     47624 non-null   float64
 12  fg3a_home     42158 non-null   float64
 13  fg3_pct_home  40025 non-null   float64
 14  ftm_home      62800 non-null   float64
 15  fta_home      60004 non-null   float64
 16  ft_pct_home   59981 non-null   float64
 17  oreb_home     41893 non-null   float64
 18  dreb_home     41819 non-null   float64
 19  reb_home      62812 non-null   float64
 20  ast_home      45032 non-null   float64
 21  stl_home      41980 non-null   float64
 22  blk_home      42203 non-null   float64
 23  tov_home      42147 non-null   float64
 24  pf_home       60868 non-null   float64
 25  pts_home      62812 non-null   float64
 26  season_year   125624 non-null  int64
 27  season_type   62812 non-null   object
 28  season        62812 non-null   object
 29  team_id_away  125624 non-null  int64
 30  w_away        83312 non-null   float64
 31  l_away        83312 non-null   float64
 32  w_pct_away    83312 non-null   float64
 33  min_away      125624 non-null  int64
 34  fgm_away      125617 non-null  float64
 35  fga_away      108259 non-null  float64
 36  fg_pct_away   108249 non-null  float64
 37  fg3m_away     110436 non-null  float64
 38  fg3a_away     104970 non-null  float64
 39  fg3_pct_away  102849 non-null  float64
 40  ftm_away      125617 non-null  float64
 41  fta_away      122819 non-null  float64
 42  ft_pct_away   122791 non-null  float64
 43  oreb_away     104705 non-null  float64
 44  dreb_away     104632 non-null  float64
 45  reb_away      125624 non-null  int64
 46  ast_away      107848 non-null  float64
 47  stl_away      104792 non-null  float64
 48  blk_away      105016 non-null  float64
 49  tov_away      104958 non-null  float64
 50  pf_away       123686 non-null  float64
 51  pts_away      125624 non-null  int64
dtypes: datetime64[ns](1), float64(42), int64(6), object(3)
memory usage: 50.8+ MB

In [18]:
import time
start  = time.time()
df = df.groupby(['game_id', 'game_date']).sum()
t = time.time() - start
df

,,team_id_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away
game_id,game_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11100001,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,29.0,86.0,0.337,4.0,12.0,0.333,24.0,38.0,1.0,21.0,25.0,46.0,11.0,8.0,6.0,14.0,25.0,86.0,2011,1610612741,1.0,0.0,1.0,240,34.0,69.0,0.493,3.0,7.0,0.429,24.0,28.0,1.0,8.0,40.0,48,17.0,5.0,4.0,24.0,30.0,95
11100002,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,36.0,72.0,0.500,4.0,14.0,0.286,14.0,21.0,1.0,9.0,28.0,37.0,24.0,4.0,9.0,21.0,22.0,90.0,2011,1610612740,1.0,0.0,1.0,240,37.0,82.0,0.451,2.0,10.0,0.200,21.0,26.0,1.0,9.0,20.0,29,17.0,12.0,3.0,11.0,15.0,97
11100003,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,26.0,79.0,0.329,3.0,15.0,0.200,23.0,27.0,1.0,12.0,23.0,35.0,10.0,12.0,4.0,20.0,21.0,78.0,2011,1610612755,1.0,0.0,1.0,240,39.0,77.0,0.506,8.0,17.0,0.471,17.0,21.0,1.0,8.0,34.0,42,24.0,8.0,1.0,18.0,21.0,103
11100004,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,29.0,77.0,0.377,6.0,19.0,0.316,23.0,35.0,1.0,11.0,34.0,45.0,15.0,9.0,10.0,21.0,39.0,87.0,2011,1610612739,1.0,0.0,1.0,240,25.0,71.0,0.352,3.0,19.0,0.158,38.0,56.0,1.0,14.0,35.0,49,17.0,12.0,8.0,21.0,28.0,91
11100005,2011-12-17,1.610613e+09,0.0,1.0,0.0,240.0,33.0,69.0,0.478,2.0,14.0,0.143,15.0,25.0,1.0,9.0,37.0,46.0,19.0,3.0,6.0,25.0,23.0,83.0,2011,1610612752,1.0,0.0,1.0,240,34.0,84.0,0.405,7.0,26.0,0.269,17.0,25.0,1.0,11.0,26.0,37,21.0,11.0,2.0,14.0,22.0,92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49900084,2000-06-09,1.610613e+09,0.0,0.0,0.0,240.0,36.0,75.0,0.480,7.0,15.0,0.467,32.0,57.0,1.0,11.0,36.0,47.0,29.0,3.0,8.0,9.0,26.0,111.0,1999,1610612754,0.0,0.0,0.0,240,33.0,88.0,0.375,5.0,20.0,0.250,33.0,39.0,1.0,13.0,33.0,46,19.0,5.0,5.0,4.0,38.0,104
49900085,2000-06-11,1.610613e+09,0.0,0.0,0.0,240.0,36.0,78.0,0.462,7.0,18.0,0.389,21.0,24.0,1.0,9.0,30.0,39.0,14.0,8.0,3.0,12.0,19.0,100.0,1999,1610612747,0.0,0.0,0.0,240,38.0,76.0,0.500,7.0,17.0,0.412,8.0,19.0,0.0,8.0,25.0,33,23.0,9.0,4.0,16.0,27.0,91
49900086,2000-06-14,1.610613e+09,0.0,0.0,0.0,265.0,42.0,84.0,0.500,10.0,19.0,0.526,24.0,28.0,1.0,9.0,30.0,39.0,22.0,5.0,3.0,12.0,28.0,118.0,1999,1610612747,0.0,0.0,0.0,265,48.0,93.0,0.516,4.0,12.0,0.333,20.0,30.0,1.0,14.0,28.0,42,20.0,6.0,4.0,12.0,31.0,120
49900087,2000-06-16,1.610613e+09,0.0,0.0,0.0,240.0,39.0,68.0,0.574,10.0,20.0,0.500,32.0,36.0,1.0,6.0,40.0,46.0,26.0,7.0,4.0,14.0,24.0,120.0,1999,1610612747,0.0,0.0,0.0,240,36.0,90.0,0.400,4.0,19.0,0.211,11.0,21.0,1.0,13.0,21.0,34,18.0,9.0,2.0,12.0,33.0,87
49900088,2000-06-19,1.610613e+09,0.0,0.0,0.0,240.0,43.0,90.0,0.478,10.0,17.0,0.588,20.0,33.0,1.0,13.0,31.0,44.0,25.0,5.0,7.0,5.0,24.0,116.0,1999,1610612754,0.0,0.0,0.0,240,36.0,77.0,0.468,12.0,25.0,0.480,27.0,32.0,1.0,9.0,32.0,41,24.0,2.0,6.0,9.0,27.0,111

In [19]:
t

0.15010833740234375

In [20]:
df

,,team_id_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away
game_id,game_date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11100001,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,29.0,86.0,0.337,4.0,12.0,0.333,24.0,38.0,1.0,21.0,25.0,46.0,11.0,8.0,6.0,14.0,25.0,86.0,2011,1610612741,1.0,0.0,1.0,240,34.0,69.0,0.493,3.0,7.0,0.429,24.0,28.0,1.0,8.0,40.0,48,17.0,5.0,4.0,24.0,30.0,95
11100002,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,36.0,72.0,0.500,4.0,14.0,0.286,14.0,21.0,1.0,9.0,28.0,37.0,24.0,4.0,9.0,21.0,22.0,90.0,2011,1610612740,1.0,0.0,1.0,240,37.0,82.0,0.451,2.0,10.0,0.200,21.0,26.0,1.0,9.0,20.0,29,17.0,12.0,3.0,11.0,15.0,97
11100003,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,26.0,79.0,0.329,3.0,15.0,0.200,23.0,27.0,1.0,12.0,23.0,35.0,10.0,12.0,4.0,20.0,21.0,78.0,2011,1610612755,1.0,0.0,1.0,240,39.0,77.0,0.506,8.0,17.0,0.471,17.0,21.0,1.0,8.0,34.0,42,24.0,8.0,1.0,18.0,21.0,103
11100004,2011-12-16,1.610613e+09,0.0,1.0,0.0,240.0,29.0,77.0,0.377,6.0,19.0,0.316,23.0,35.0,1.0,11.0,34.0,45.0,15.0,9.0,10.0,21.0,39.0,87.0,2011,1610612739,1.0,0.0,1.0,240,25.0,71.0,0.352,3.0,19.0,0.158,38.0,56.0,1.0,14.0,35.0,49,17.0,12.0,8.0,21.0,28.0,91
11100005,2011-12-17,1.610613e+09,0.0,1.0,0.0,240.0,33.0,69.0,0.478,2.0,14.0,0.143,15.0,25.0,1.0,9.0,37.0,46.0,19.0,3.0,6.0,25.0,23.0,83.0,2011,1610612752,1.0,0.0,1.0,240,34.0,84.0,0.405,7.0,26.0,0.269,17.0,25.0,1.0,11.0,26.0,37,21.0,11.0,2.0,14.0,22.0,92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49900084,2000-06-09,1.610613e+09,0.0,0.0,0.0,240.0,36.0,75.0,0.480,7.0,15.0,0.467,32.0,57.0,1.0,11.0,36.0,47.0,29.0,3.0,8.0,9.0,26.0,111.0,1999,1610612754,0.0,0.0,0.0,240,33.0,88.0,0.375,5.0,20.0,0.250,33.0,39.0,1.0,13.0,33.0,46,19.0,5.0,5.0,4.0,38.0,104
49900085,2000-06-11,1.610613e+09,0.0,0.0,0.0,240.0,36.0,78.0,0.462,7.0,18.0,0.389,21.0,24.0,1.0,9.0,30.0,39.0,14.0,8.0,3.0,12.0,19.0,100.0,1999,1610612747,0.0,0.0,0.0,240,38.0,76.0,0.500,7.0,17.0,0.412,8.0,19.0,0.0,8.0,25.0,33,23.0,9.0,4.0,16.0,27.0,91
49900086,2000-06-14,1.610613e+09,0.0,0.0,0.0,265.0,42.0,84.0,0.500,10.0,19.0,0.526,24.0,28.0,1.0,9.0,30.0,39.0,22.0,5.0,3.0,12.0,28.0,118.0,1999,1610612747,0.0,0.0,0.0,265,48.0,93.0,0.516,4.0,12.0,0.333,20.0,30.0,1.0,14.0,28.0,42,20.0,6.0,4.0,12.0,31.0,120
49900087,2000-06-16,1.610613e+09,0.0,0.0,0.0,240.0,39.0,68.0,0.574,10.0,20.0,0.500,32.0,36.0,1.0,6.0,40.0,46.0,26.0,7.0,4.0,14.0,24.0,120.0,1999,1610612747,0.0,0.0,0.0,240,36.0,90.0,0.400,4.0,19.0,0.211,11.0,21.0,1.0,13.0,21.0,34,18.0,9.0,2.0,12.0,33.0,87
49900088,2000-06-19,1.610613e+09,0.0,0.0,0.0,240.0,43.0,90.0,0.478,10.0,17.0,0.588,20.0,33.0,1.0,13.0,31.0,44.0,25.0,5.0,7.0,5.0,24.0,116.0,1999,1610612754,0.0,0.0,0.0,240,36.0,77.0,0.468,12.0,25.0,0.480,27.0,32.0,1.0,9.0,32.0,41,24.0,2.0,6.0,9.0,27.0,111

In [21]:
#pd.merge(df_games, empty_df, on=['game_id', 'game_date']).set_index(['game_id', 'game_date'])

In [22]:
#pd.merge(df_games, empty_df, on=['game_id', 'game_date']).set_index(['game_id', 'game_date'])

In [23]:
df_years = pd.to_datetime(df_games.game_date)
df_years

3        2009-01-12
6        1999-04-21
7        1999-04-18
8        1999-04-16
9        2008-12-13
            ...
125617          NaT
125619   2009-04-03
125620   2009-03-24
125622   2009-02-23
125623   2009-02-19
Name: game_date, Length: 62812, dtype: datetime64[ns]

In [24]:
df_years.dt.year.value_counts().sort_values()

1950.0     157
1958.0     298
1957.0     306
1955.0     307
1959.0     307
1960.0     315
1954.0     317
1956.0     321
1961.0     342
1963.0     354
1965.0     356
1953.0     357
1951.0     362
1952.0     363
1962.0     364
1964.0     366
1966.0     376
1967.0     438
1968.0     521
1969.0     568
1970.0     607
1971.0     649
1972.0     655
1974.0     661
1973.0     664
1975.0     732
2018.0     770
1976.0     812
1998.0     838
1980.0     855
1981.0     860
1979.0     879
1978.0     881
1977.0     899
2011.0     916
1983.0     969
1986.0     971
1985.0     978
1987.0     982
1982.0     983
1984.0    1001
1988.0    1065
1989.0    1122
1992.0    1148
1991.0    1185
1990.0    1186
1994.0    1187
1993.0    1194
1999.0    1213
1995.0    1223
2001.0    1237
2017.0    1246
2004.0    1248
1997.0    1249
2003.0    1254
2002.0    1257
2000.0    1269
1996.0    1270
2009.0    1279
2010.0    1279
2015.0    1282
2016.0    1289
2007.0    1299
2013.0    1307
2008.0    1308
2014.0    1309
2005.0    1323
2006.0    1340
2012.0    1463
Name: game_date, dtype: int64

In [25]:
df_teams = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_teams_all.csv')
df_teams.head()

   league_id     team_id  min_year  max_year abbreviation
0          0  1610612737    1949.0    2018.0          ATL
1          0  1610612738    1946.0    2018.0          BOS
2          0  1610612739    1970.0    2018.0          CLE
3          0  1610612740    2002.0    2018.0          NOP
4          0  1610612741    1966.0    2018.0          CHI

In [26]:
df_games = df_games[df_games.season_type == 'Regular Season'][(df_games.season == '2006-07') |
                                                   (df_games.season == '2007-08') |
                                                   (df_games.season == '2008-09') |
                                                   (df_games.season == '2009-10') | 
                                                   (df_games.season == '2010-11') |
                                                   (df_games.season == '2011-12') |
                                                   (df_games.season == '2012-13') |
                                                   (df_games.season == '2013-14') |
                                                   (df_games.season == '2014-15') |
                                                   (df_games.season == '2015-16') | 
                                                   (df_games.season == '2016-17') | 
                                                   (df_games.season == '2017-18')]
df_games

C:\Users\Paul\anaconda3\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if sys.path[0] == '':

,game_id,game_date,team_id_home,is_home,w_home,l_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,season_type,season,team_id_away,w_away,l_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away
3,20800558,2009-01-12,1610612762,t,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,20800344,2008-12-13,1610612762,t,15.0,10.0,0.600,240,33.0,77.0,0.429,8.0,18.0,0.444,20.0,29.0,1.0,17.0,29.0,46,25.0,11.0,4.0,22.0,23.0,94,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,20800325,2008-12-11,1610612762,t,15.0,9.0,0.625,240,35.0,72.0,0.486,3.0,10.0,0.300,24.0,30.0,1.0,10.0,28.0,38,23.0,9.0,1.0,11.0,21.0,97,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,20801116,2009-04-01,1610612763,t,20.0,54.0,0.270,240,38.0,79.0,0.481,8.0,18.0,0.444,28.0,34.0,1.0,12.0,25.0,37,21.0,10.0,6.0,12.0,22.0,112,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,20800762,2009-02-09,1610612763,t,15.0,36.0,0.294,240,28.0,77.0,0.364,3.0,15.0,0.200,26.0,35.0,1.0,20.0,44.0,64,18.0,3.0,9.0,18.0,21.0,85,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125616,20800030,2008-11-01,1610612765,t,2.0,0.0,1.000,240,42.0,79.0,0.532,6.0,14.0,0.429,27.0,32.0,1.0,16.0,33.0,49,24.0,5.0,7.0,17.0,24.0,117,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125619,20801131,2009-04-03,1610612762,t,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125620,20801058,2009-03-24,1610612762,t,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125622,20800839,2009-02-23,1610612762,t,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
125623,20800810,2009-02-19,1610612762,t,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,0,Regular Season,2008-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [27]:
df_games = pd.merge(df_games
         , df_teams[['team_id','abbreviation']], on=['team_id'], how='left')
df_games

KeyError: 'team_id'

In [ ]:
df_games.sort_values('game_id')

In [ ]:
df_games[df_games['game_id'] == 20600001]

In [ ]:
df_games = df_games[df_games['game_date'].notnull()]

In [ ]:
df_games.shape

In [ ]:
df_games.sort_values('game_id', inplace=True)

In [ ]:
df_games = df_games.reset_index().drop(columns='index')
df_games

In [ ]:
game_ids = df_games.game_id.unique()
game_ids

In [ ]:
df_games['game_date'] = pd.to_datetime(df_games['game_date'])

In [ ]:
def build_game_date_indexed_rows():
    df_empty = pd.DataFrame({})

    for id_ in game_ids:

        visitor_ = df_games[df_games['is_home'] == 'f'][df_games['game_id'] == id_]
        home_ = df_games[df_games['is_home'] == 't'][df_games['game_id'] == id_]


        #visitor team abbreviation
        s0 = str('_') + df_games[df_games['game_id'] == id_][df_games['is_home'] == 'f']['abbreviation'].iloc[0]

        #home team abbreviation
        s1 = str('_') + df_games[df_games['game_id'] == id_][df_games['is_home'] == 't']['abbreviation'].iloc[0]


        df_single_game = pd.merge(visitor_, home_, on=['game_id', 'game_date'], how='inner', suffixes=[s0, s1])

        df_empty = pd.concat([df_empty, df_single_game])
    
    df_empty = df_empty.reset_index().drop(columns='index').set_index(['game_id', 'game_date'])
    return df_empty

In [ ]:
import time
start_time = time.time()

In [ ]:

df = build_game_date_indexed_rows()

In [ ]:
df

In [ ]:
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
print("--- %s minutes ---" % ((time.time() - start_time) / 60))

In [ ]:
df.iloc[:, 1]

In [ ]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '1games_df.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=True)