# Basics and Package Structure

If you're just interested in pulling data, you will primarily be using `nba_api.stats.endpoints`.
This submodule contains a class for each API endpoint supported by stats.nba.com.
For example, [the PlayerCareerStats class](https://github.com/swar/nba_api/blob/master/nba_api/stats/endpoints/playercareerstats.py) is initialized with a player ID and returns some career statistics for the player.

In [1]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203076')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203076,2012-13,00,1610612740,NOH,20.0,64,60,1846.0,349,...,0.751,165,357,522,63,75,112,89,158,867
1,203076,2013-14,00,1610612740,NOP,21.0,67,66,2358.0,522,...,0.791,207,466,673,105,89,189,109,200,1394
2,203076,2014-15,00,1610612740,NOP,22.0,68,68,2455.0,642,...,0.805,173,523,696,149,100,200,95,141,1656
3,203076,2015-16,00,1610612740,NOP,23.0,61,61,2164.0,560,...,0.758,130,497,627,116,78,125,121,148,1481
4,203076,2016-17,00,1610612740,NOP,24.0,75,75,2708.0,770,...,0.802,172,712,884,157,94,167,181,168,2099
5,203076,2017-18,00,1610612740,NOP,25.0,75,75,2727.0,780,...,0.828,187,644,831,174,115,193,162,159,2110
6,203076,2018-19,00,1610612740,NOP,25.0,16,16,599.0,151,...,0.787,59,143,202,78,24,43,36,44,432

`career`, above, is a `PlayerCareerStats` object.
This class (and the other endpoint classes) supports several methods of accessing the data: `get_dict()`, `get_json()`, `get_data_frames()`, and more.
`get_data_frames()` returns a list of pandas DataFrames, and when working in notebooks, this is often your best option for viewing data.
In general, the first DataFrame in this list is the primary returned data structure and the one you'll want to look at.

Almost all of the endpoint classes take at least one required argument, along with several optional ones.
In the case of `PlayerCareerStats`, a player ID is required, but the user may also specify a league ID.

At the time of writing this notebook, these are the endpoints available:

<table><tr></tr><tr><td>boxscoreadvancedv2</td><td>boxscorefourfactorsv2</td><td>boxscoremiscv2</td><td>boxscoreplayertrackv2</td></tr><tr><td>boxscorescoringv2</td><td>boxscoresummaryv2</td><td>boxscoretraditionalv2</td><td>boxscoreusagev2</td></tr><tr><td>commonallplayers</td><td>commonplayerinfo</td><td>commonplayoffseries</td><td>commonteamroster</td></tr><tr><td>commonteamyears</td><td>defensehub</td><td>draftcombinedrillresults</td><td>draftcombinenonstationaryshooting</td></tr><tr><td>draftcombineplayeranthro</td><td>draftcombinespotshooting</td><td>draftcombinestats</td><td>drafthistory</td></tr><tr><td>franchisehistory</td><td>homepageleaders</td><td>homepagev2</td><td>infographicfanduelplayer</td></tr><tr><td>leaderstiles</td><td>leaguedashlineups</td><td>leaguedashplayerbiostats</td><td>leaguedashplayerclutch</td></tr><tr><td>leaguedashplayerptshot</td><td>leaguedashplayershotlocations</td><td>leaguedashplayerstats</td><td>leaguedashptdefend</td></tr><tr><td>leaguedashptstats</td><td>leaguedashptteamdefend</td><td>leaguedashteamclutch</td><td>leaguedashteamptshot</td></tr><tr><td>leaguedashteamshotlocations</td><td>leaguedashteamstats</td><td>leaguegamefinder</td><td>leaguegamelog</td></tr><tr><td>leagueleaders</td><td>leaguestandings</td><td>playbyplay</td><td>playbyplayv2</td></tr><tr><td>playerawards</td><td>playercareerstats</td><td>playercompare</td><td>playerdashboardbyclutch</td></tr><tr><td>playerdashboardbygamesplits</td><td>playerdashboardbygeneralsplits</td><td>playerdashboardbylastngames</td><td>playerdashboardbyopponent</td></tr><tr><td>playerdashboardbyshootingsplits</td><td>playerdashboardbyteamperformance</td><td>playerdashboardbyyearoveryear</td><td>playerdashptpass</td></tr><tr><td>playerdashptreb</td><td>playerdashptshotdefend</td><td>playerdashptshots</td><td>playerfantasyprofile</td></tr><tr><td>playerfantasyprofilebargraph</td><td>playergamelog</td><td>playergamestreakfinder</td><td>playernextngames</td></tr><tr><td>playerprofilev2</td><td>playersvsplayers</td><td>playervsplayer</td><td>playoffpicture</td></tr><tr><td>scoreboard</td><td>scoreboardv2</td><td>shotchartdetail</td><td>shotchartlineupdetail</td></tr><tr><td>teamdashboardbyclutch</td><td>teamdashboardbygamesplits</td><td>teamdashboardbygeneralsplits</td><td>teamdashboardbylastngames</td></tr><tr><td>teamdashboardbyopponent</td><td>teamdashboardbyshootingsplits</td><td>teamdashboardbyteamperformance</td><td>teamdashboardbyyearoveryear</td></tr><tr><td>teamdashlineups</td><td>teamdashptpass</td><td>teamdashptreb</td><td>teamdashptshots</td></tr><tr><td>teamdetails</td><td>teamgamelog</td><td>teamgamestreakfinder</td><td>teamhistoricalleaders</td></tr><tr><td>teaminfocommon</td><td>teamplayerdashboard</td><td>teamplayeronoffdetails</td><td>teamplayeronoffsummary</td></tr><tr><td>teamvsplayer</td><td>teamyearbyyearstats</td><td>videodetails</td><td>videoevents</td></tr><tr><td>videostatus</td></tr></table>

In [9]:
from nba_api.stats.endpoints import boxscoreadvancedv2
import nba_api.stats.endpoints as ep

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

import pandas as pd

In [5]:
df2 = pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\3game_date_home_away.csv', parse_dates=['game_date'])
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [69]:
ep.commonallplayers.CommonAllPlayers().get_data_frames()[0]

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,76001,"Abdelnaby, Alaa",Alaa Abdelnaby,0,1990,1994,HISTADD_alaa_abdelnaby,0,,,,,Y,00
1,76002,"Abdul-Aziz, Zaid",Zaid Abdul-Aziz,0,1968,1977,HISTADD_zaid_abdul-aziz,0,,,,,Y,00
2,76003,"Abdul-Jabbar, Kareem",Kareem Abdul-Jabbar,0,1969,1988,HISTADD_kareem_abdul-jabbar,0,,,,,Y,00
3,51,"Abdul-Rauf, Mahmoud",Mahmoud Abdul-Rauf,0,1990,2000,mahmoud_abdul-rauf,0,,,,,Y,00
4,1505,"Abdul-Wahad, Tariq",Tariq Abdul-Wahad,0,1997,2003,tariq_abdul-wahad,0,,,,,Y,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4592,1627790,"Zizic, Ante",Ante Zizic,0,2017,2019,ante_zizic,0,,,,,Y,01
4593,78647,"Zoet, Jim",Jim Zoet,0,1982,1982,HISTADD_jim_zoet,0,,,,,Y,00
4594,78648,"Zopf, Bill",Bill Zopf,0,1970,1970,HISTADD_zip_zopf,0,,,,,Y,00
4595,1627826,"Zubac, Ivica",Ivica Zubac,1,2016,2020,ivica_zubac,1610612746,LA,Clippers,LAC,clippers,Y,01
4596,78650,"Zunic, Matt",Matt Zunic,0,1948,1948,HISTADD_matt_zunic,0,,,,,Y,00

In [ ]:
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [52]:
game_id_ = '0020600001'
ep.boxscoreusagev2.BoxScoreUsageV2(game_id=game_id_).get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,USG_PCT,PCT_FGM,PCT_FGA,PCT_FG3M,PCT_FG3A,PCT_FTM,PCT_FTA,PCT_OREB,PCT_DREB,PCT_REB,PCT_AST,PCT_TOV,PCT_STL,PCT_BLK,PCT_BLKA,PCT_PF,PCT_PFD,PCT_PTS
0,0020600001,1610612741,CHI,Chicago,2736,Luol Deng,F,,24:07,0.273,0.250,0.231,0.000,0.000,0.308,0.333,0.125,0.083,0.100,0.111,0.375,0.250,0.000,0.333,0.222,0.231,0.250
1,0020600001,1610612741,CHI,Chicago,136,P.J. Brown,F,,18:23,0.113,0.071,0.061,0.000,0.000,0.222,0.200,0.000,0.250,0.167,0.125,0.286,0.250,0.500,0.000,0.300,0.125,0.100
2,0020600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,,28:29,0.077,0.105,0.106,0.000,0.000,0.067,0.043,0.750,0.238,0.379,0.077,0.000,0.000,0.500,0.000,0.182,0.133,0.089
3,0020600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,,22:56,0.235,0.077,0.231,0.000,0.333,0.308,0.263,0.000,0.063,0.042,0.222,0.250,0.500,0.000,0.500,0.333,0.167,0.146
4,0020600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,,34:38,0.237,0.357,0.310,0.750,0.556,0.200,0.190,0.000,0.182,0.121,0.214,0.000,0.286,0.000,0.000,0.133,0.294,0.347
5,0020600001,1610612741,CHI,Chicago,2804,Andres Nocioni,,,28:54,0.153,0.160,0.170,0.200,0.375,0.000,0.000,0.143,0.476,0.393,0.182,0.200,0.000,0.000,1.000,0.167,0.133,0.130
6,0020600001,1610612741,CHI,Chicago,2768,Chris Duhon,,,16:40,0.287,0.467,0.308,0.750,0.429,0.429,0.273,0.000,0.154,0.125,0.375,0.250,0.000,0.000,0.000,0.000,0.250,0.488
7,0020600001,1610612741,CHI,Chicago,200748,Tyrus Thomas,,,16:23,0.271,0.067,0.143,0.000,0.000,0.500,0.667,0.200,0.286,0.263,0.286,0.600,0.333,0.500,0.000,0.300,0.375,0.114
8,0020600001,1610612741,CHI,Chicago,2751,Viktor Khryapa,,,14:00,0.234,0.133,0.190,0.000,0.000,0.143,0.222,0.500,0.200,0.235,0.273,0.400,0.250,0.000,0.000,0.333,0.333,0.125
9,0020600001,1610612741,CHI,Chicago,1559,Adrian Griffin,,,11:14,0.130,0.091,0.118,0.000,0.000,0.000,0.000,0.000,0.083,0.077,0.250,0.333,0.000,0.000,0.000,0.000,0.000,0.065
10,0020600001,1610612741,CHI,Chicago,2124,Malik Allen,,,13:42,0.197,0.154,0.273,0.000,0.000,0.000,0.000,0.333,0.154,0.188,0.143,0.000,0.250,1.000,0.000,0.200,0.000,0.111
11,0020600001,1610612741,CHI,Chicago,200757,Thabo Sefolosha,,,10:34,0.203,0.364,0.222,0.000,0.000,0.600,0.500,0.667,0.000,0.167,0.200,0.000,0.500,0.000,0.000,0.500,0.333,0.393
12,0020600001,1610612748,MIA,Miami,952,Antoine Walker,F,,35:47,0.202,0.158,0.180,0.000,0.462,0.250,0.286,0.000,0.300,0.250,0.182,0.200,0.333,0.667,0.000,0.200,0.211,0.173
13,0020600001,1610612748,MIA,Miami,2617,Udonis Haslem,F,,27:34,0.158,0.188,0.225,0.000,0.000,0.000,0.000,0.000,0.353,0.316,0.000,0.000,0.333,0.000,0.667,0.143,0.154,0.146
14,0020600001,1610612748,MIA,Miami,406,Shaquille O'Neal,C,,24:26,0.284,0.200,0.303,0.000,0.000,0.143,0.167,1.000,0.182,0.357,0.000,0.273,0.000,0.333,0.500,0.200,0.333,0.184
15,0020600001,1610612748,MIA,Miami,2548,Dwyane Wade,G,,34:07,0.304,0.476,0.319,0.667,0.231,0.333,0.429,0.250,0.063,0.100,0.300,0.250,0.250,0.000,0.000,0.176,0.286,0.463
16,0020600001,1610612748,MIA,Miami,56,Gary Payton,G,,34:41,0.155,0.053,0.102,0.333,0.286,0.364,0.250,0.000,0.143,0.125,0.364,0.308,0.333,0.000,0.000,0.235,0.167,0.135
17,0020600001,1610612748,MIA,Miami,297,Alonzo Mourning,,,15:23,0.156,0.000,0.095,0.000,0.000,0.200,0.222,0.000,0.200,0.182,0.000,0.286,0.000,0.000,0.667,0.100,0.125,0.048
18,0020600001,1610612748,MIA,Miami,1899,James Posey,,,22:35,0.045,0.100,0.037,0.000,0.000,0.000,0.000,0.000,0.111,0.091,0.250,0.077,0.000,0.000,0.000,0.231,0.125,0.071
19,0020600001,1610612748,MIA,Miami,200809,Chris Quinn,,,13:51,0.179,0.143,0.294,0.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.333,0.143,0.105
20,0020600001,1610612748,MIA,Miami,2574,Jason Kapono,,,10:32,0.049,0.200,0.071,0.000,0.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.333,0.000,0.000,0.000,0.000,0.273
21,0020600001,1610612748,MIA,Miami,2748,Dorell Wright,,,8:14,0.304,0.333,0.364,0.000,0.000,0.000,0.000,0.000,0.500,0.500,0.000,0.200,0.000,0.000,0.000,0.250,0.000,0.286
22,0020600001,1610612748,MIA,Miami,101134,Wayne Simien,,,7:43,0.130,0.333,0.100,0.000,0.000,0.000,0.000,0.000,0.250,0.250,0.000,0.200,0.000,0.000,0.000,0.250,1.000,0.286
23,0020600001,1610612748,MIA,Miami,200823,Robert Hite,,,5:07,0.455,0.000,0.500,0.000,1.000,0.000,0.000,0.000,0.333,0.333,0.000,0.400,0.500,0.000,0.000,0.500,0.000,0.000

In [53]:
game_id_ = '0020600001'
ep.boxscoreusagev2.BoxScoreUsageV2(game_id=game_id_).get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,USG_PCT,PCT_FGM,PCT_FGA,PCT_FG3M,PCT_FG3A,PCT_FTM,PCT_FTA,PCT_OREB,PCT_DREB,PCT_REB,PCT_AST,PCT_TOV,PCT_STL,PCT_BLK,PCT_BLKA,PCT_PF,PCT_PFD,PCT_PTS
0,0020600001,1610612748,Heat,MIA,Miami,240:00,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,0020600001,1610612741,Bulls,CHI,Chicago,240:00,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [48]:
game_id_ = '0020600001'
ep.boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id_).get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0020600001,1610612741,CHI,Chicago,2736,Luol Deng,F,,24:07,4,9,0.444,0,0,0.000,4,6,0.667,1,1,2,1,1,0,3,2,12,8.0
1,0020600001,1610612741,CHI,Chicago,136,P.J. Brown,F,,18:23,1,2,0.500,0,0,0.000,2,2,1.000,0,3,3,1,1,1,2,3,4,15.0
2,0020600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,,28:29,2,5,0.400,0,0,0.000,1,1,1.000,6,5,11,1,0,1,0,2,5,13.0
3,0020600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,,22:56,1,9,0.111,0,2,0.000,4,5,0.800,0,1,1,2,1,0,2,3,6,7.0
4,0020600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,,34:38,10,18,0.556,3,5,0.600,3,4,0.750,0,4,4,3,2,0,0,2,26,23.0
5,0020600001,1610612741,CHI,Chicago,2804,Andres Nocioni,,,28:54,4,8,0.500,1,3,0.333,0,0,0.000,1,10,11,2,0,0,2,2,9,28.0
6,0020600001,1610612741,CHI,Chicago,2768,Chris Duhon,,,16:40,7,8,0.875,3,3,1.000,3,3,1.000,0,2,2,3,0,0,1,0,20,18.0
7,0020600001,1610612741,CHI,Chicago,200748,Tyrus Thomas,,,16:23,1,4,0.250,0,0,0.000,2,6,0.333,1,4,5,2,1,2,3,3,4,15.0
8,0020600001,1610612741,CHI,Chicago,2751,Viktor Khryapa,,,14:00,2,4,0.500,0,0,0.000,1,2,0.500,1,3,4,3,1,0,2,2,5,28.0
9,0020600001,1610612741,CHI,Chicago,1559,Adrian Griffin,,,11:14,1,2,0.500,0,0,0.000,0,0,0.000,0,1,1,2,0,0,1,0,2,19.0
10,0020600001,1610612741,CHI,Chicago,2124,Malik Allen,,,13:42,2,6,0.333,0,0,0.000,0,0,0.000,1,2,3,1,1,1,0,1,4,19.0
11,0020600001,1610612741,CHI,Chicago,200757,Thabo Sefolosha,,,10:34,4,4,1.000,0,0,0.000,3,3,1.000,2,0,2,1,2,0,0,1,11,17.0
12,0020600001,1610612748,MIA,Miami,952,Antoine Walker,F,,35:47,3,9,0.333,0,6,0.000,3,6,0.500,0,6,6,2,1,2,3,3,9,-24.0
13,0020600001,1610612748,MIA,Miami,2617,Udonis Haslem,F,,27:34,3,9,0.333,0,0,0.000,0,0,0.000,0,6,6,0,1,0,0,2,6,-13.0
14,0020600001,1610612748,MIA,Miami,406,Shaquille O'Neal,C,,24:26,3,10,0.300,0,0,0.000,1,2,0.500,3,2,5,0,0,1,3,2,7,-19.0
15,0020600001,1610612748,MIA,Miami,2548,Dwyane Wade,G,,34:07,10,15,0.667,2,3,0.667,3,6,0.500,1,1,2,3,1,0,4,3,25,-23.0
16,0020600001,1610612748,MIA,Miami,56,Gary Payton,G,,34:41,1,5,0.200,1,4,0.250,4,5,0.800,0,3,3,4,1,0,4,4,7,-16.0
17,0020600001,1610612748,MIA,Miami,297,Alonzo Mourning,,,15:23,0,2,0.000,0,0,0.000,1,2,0.500,0,2,2,0,0,0,2,1,1,-9.0
18,0020600001,1610612748,MIA,Miami,1899,James Posey,,,22:35,1,1,1.000,0,0,0.000,0,0,0.000,0,1,1,1,0,0,1,3,2,-32.0
19,0020600001,1610612748,MIA,Miami,200809,Chris Quinn,,,13:51,1,5,0.200,0,2,0.000,0,0,0.000,0,0,0,3,0,0,0,2,2,-21.0
20,0020600001,1610612748,MIA,Miami,2574,Jason Kapono,,,10:32,1,1,1.000,0,0,0.000,1,1,1.000,0,0,0,0,1,0,0,0,3,-17.0
21,0020600001,1610612748,MIA,Miami,2748,Dorell Wright,,,8:14,1,4,0.250,0,0,0.000,0,0,0.000,0,2,2,0,0,0,1,1,2,-12.0
22,0020600001,1610612748,MIA,Miami,101134,Wayne Simien,,,7:43,1,1,1.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,1,1,2,-12.0
23,0020600001,1610612748,MIA,Miami,200823,Robert Hite,,,5:07,0,3,0.000,0,2,0.000,0,0,0.000,0,1,1,0,1,0,2,2,0,-12.0

In [49]:
ep.boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id_).get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0020600001,1610612748,Heat,MIA,Miami,240:00,25,65,0.385,3,17,0.176,13,22,0.591,4,25,29,13,6,3,21,24,66,-42.0
1,0020600001,1610612741,Bulls,CHI,Chicago,240:00,39,79,0.494,7,13,0.538,23,32,0.719,13,36,49,22,10,5,16,21,108,42.0

In [50]:
ep.boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id_).get_data_frames()[2]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,STARTERS_BENCH,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
0,0020600001,1610612748,Heat,MIA,Miami,Starters,156:35,20,48,0.417,3,13,0.231,11,19,0.579,4,18,22,9,4,3,14,14,54
1,0020600001,1610612748,Heat,MIA,Miami,Bench,83:25,5,17,0.294,0,4,0.000,2,3,0.667,0,7,7,4,2,0,7,10,12
2,0020600001,1610612741,Bulls,CHI,Chicago,Starters,128:33,18,43,0.419,3,7,0.429,14,18,0.778,7,14,21,8,5,2,7,12,53
3,0020600001,1610612741,Bulls,CHI,Chicago,Bench,111:27,21,36,0.583,4,6,0.667,9,14,0.643,6,22,28,14,5,3,9,9,55

In [ ]:
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [35]:
game_id_ = '0020600001'
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[0]

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,GAME_STATUS_ID,GAME_STATUS_TEXT,GAMECODE,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,LIVE_PERIOD,LIVE_PC_TIME,NATL_TV_BROADCASTER_ABBREVIATION,LIVE_PERIOD_TIME_BCAST,WH_STATUS
0,2006-10-31T00:00:00,1,0020600001,3,Final,20061031/CHIMIA,1610612748,1610612741,2006,4,,TNT,Q4 - TNT,1

In [38]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[1]

,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PTS_PAINT,PTS_2ND_CHANCE,PTS_FB,LARGEST_LEAD,LEAD_CHANGES,TIMES_TIED,TEAM_TURNOVERS,TOTAL_TURNOVERS,TEAM_REBOUNDS,PTS_OFF_TO
0,00,1610612748,MIA,Miami,26,2,6,2,2,3,2,23,9,32
1,00,1610612741,CHI,Chicago,36,18,21,42,2,3,0,16,11,15

In [39]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[2]

   OFFICIAL_ID FIRST_NAME   LAST_NAME JERSEY_NUM
0         1204      Derek  Richardson         63
1         1156        Tim     Donaghy         21
2         1163     Bernie       Fryer          7

In [40]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[3]

,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION
0,2552,Michael,Sweetney,50,1610612741,Chicago,Bulls,CHI
1,2857,Andre,Barrett,11,1610612741,Chicago,Bulls,CHI
2,101149,Martynas,Andriuskevicius,15,1610612741,Chicago,Bulls,CHI
3,2853,Earl,Barron,30,1610612748,Miami,Heat,MIA
4,1715,Jason,Williams,55,1610612748,Miami,Heat,MIA
5,1720,Michael,Doleac,51,1610612748,Miami,Heat,MIA

In [41]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[4]

                   GAME_DATE  ATTENDANCE GAME_TIME
0  TUESDAY, OCTOBER 31, 2006       20229      2:26

In [42]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[5]

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY_NAME,TEAM_NICKNAME,TEAM_WINS_LOSSES,PTS_QTR1,PTS_QTR2,PTS_QTR3,PTS_QTR4,PTS_OT1,PTS_OT2,PTS_OT3,PTS_OT4,PTS_OT5,PTS_OT6,PTS_OT7,PTS_OT8,PTS_OT9,PTS_OT10,PTS
0,2006-10-31T00:00:00,1,0020600001,1610612741,CHI,Chicago,Bulls,1-0,22,37,21,28,0,0,0,0,None,None,None,None,None,None,108
1,2006-10-31T00:00:00,1,0020600001,1610612748,MIA,Miami,Heat,0-1,16,14,21,15,0,0,0,0,None,None,None,None,None,None,66

In [43]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[6]

,GAME_ID,LAST_GAME_ID,LAST_GAME_DATE_EST,LAST_GAME_HOME_TEAM_ID,LAST_GAME_HOME_TEAM_CITY,LAST_GAME_HOME_TEAM_NAME,LAST_GAME_HOME_TEAM_ABBREVIATION,LAST_GAME_HOME_TEAM_POINTS,LAST_GAME_VISITOR_TEAM_ID,LAST_GAME_VISITOR_TEAM_CITY,LAST_GAME_VISITOR_TEAM_NAME,LAST_GAME_VISITOR_TEAM_CITY1,LAST_GAME_VISITOR_TEAM_POINTS
0,0020600001,0040500116,2006-05-04T00:00:00,1610612748,Miami,Heat,MIA,113,1610612741,Chicago,Bulls,CHI,96

In [44]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[7]

,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,GAME_DATE_EST,HOME_TEAM_WINS,HOME_TEAM_LOSSES,SERIES_LEADER
0,0020600001,1610612748,1610612741,2006-10-31T00:00:00,1,3,Chicago

In [45]:
ep.boxscoresummaryv2.BoxScoreSummaryV2(game_id=game_id_).get_data_frames()[8]

,GAME_ID,VIDEO_AVAILABLE_FLAG,PT_AVAILABLE,PT_XYZ_AVAILABLE,WH_STATUS,HUSTLE_STATUS,HISTORICAL_STATUS
0,0020600001,0,0,0,1,1,0

In [ ]:
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [36]:
game_id_ = '0020600001'
ep.boxscorescoringv2.BoxScoreScoringV2(game_id=game_id_).get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,PCT_FGA_2PT,PCT_FGA_3PT,PCT_PTS_2PT,PCT_PTS_2PT_MR,PCT_PTS_3PT,PCT_PTS_FB,PCT_PTS_FT,PCT_PTS_OFF_TOV,PCT_PTS_PAINT,PCT_AST_2PM,PCT_UAST_2PM,PCT_AST_3PM,PCT_UAST_3PM,PCT_AST_FGM,PCT_UAST_FGM
0,0020600001,1610612741,CHI,Chicago,2736,Luol Deng,F,,24:07,1.000,0.000,0.667,0.333,0.000,0.583,0.333,0.250,0.333,1.000,0.000,0.000,0.000,1.000,0.000
1,0020600001,1610612741,CHI,Chicago,136,P.J. Brown,F,,18:23,1.000,0.000,0.500,0.500,0.000,0.000,0.500,0.000,0.000,1.000,0.000,0.000,0.000,1.000,0.000
2,0020600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,,28:29,1.000,0.000,0.800,0.000,0.000,0.000,0.200,0.200,0.800,0.500,0.500,0.000,0.000,0.500,0.500
3,0020600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,,22:56,0.778,0.222,0.333,0.000,0.000,0.667,0.667,0.333,0.333,1.000,0.000,0.000,0.000,1.000,0.000
4,0020600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,,34:38,0.722,0.278,0.538,0.231,0.346,0.000,0.115,0.308,0.308,0.571,0.429,0.667,0.333,0.600,0.400
5,0020600001,1610612741,CHI,Chicago,2804,Andres Nocioni,,,28:54,0.625,0.375,0.667,0.222,0.333,0.000,0.000,0.444,0.444,0.333,0.667,1.000,0.000,0.500,0.500
6,0020600001,1610612741,CHI,Chicago,2768,Chris Duhon,,,16:40,0.625,0.375,0.400,0.300,0.450,0.150,0.150,0.250,0.100,0.250,0.750,0.667,0.333,0.429,0.571
7,0020600001,1610612741,CHI,Chicago,200748,Tyrus Thomas,,,16:23,1.000,0.000,0.500,0.000,0.000,0.500,0.500,0.500,0.500,0.000,1.000,0.000,0.000,0.000,1.000
8,0020600001,1610612741,CHI,Chicago,2751,Viktor Khryapa,,,14:00,1.000,0.000,0.800,0.800,0.000,0.400,0.200,0.400,0.000,1.000,0.000,0.000,0.000,1.000,0.000
9,0020600001,1610612741,CHI,Chicago,1559,Adrian Griffin,,,11:14,1.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000,0.000,0.000,1.000
10,0020600001,1610612741,CHI,Chicago,2124,Malik Allen,,,13:42,1.000,0.000,1.000,0.000,0.000,0.000,0.000,0.500,1.000,0.500,0.500,0.000,0.000,0.500,0.500
11,0020600001,1610612741,CHI,Chicago,200757,Thabo Sefolosha,,,10:34,1.000,0.000,0.727,0.364,0.000,0.273,0.273,0.273,0.364,0.250,0.750,0.000,0.000,0.250,0.750
12,0020600001,1610612748,MIA,Miami,952,Antoine Walker,F,,35:47,0.333,0.667,0.667,0.000,0.000,0.000,0.333,0.000,0.667,0.333,0.667,0.000,0.000,0.333,0.667
13,0020600001,1610612748,MIA,Miami,2617,Udonis Haslem,F,,27:34,1.000,0.000,1.000,0.667,0.000,0.000,0.000,0.667,0.333,1.000,0.000,0.000,0.000,1.000,0.000
14,0020600001,1610612748,MIA,Miami,406,Shaquille O'Neal,C,,24:26,1.000,0.000,0.857,0.000,0.000,0.000,0.143,0.286,0.857,0.667,0.333,0.000,0.000,0.667,0.333
15,0020600001,1610612748,MIA,Miami,2548,Dwyane Wade,G,,34:07,0.800,0.200,0.640,0.320,0.240,0.160,0.120,0.160,0.320,0.375,0.625,0.000,1.000,0.300,0.700
16,0020600001,1610612748,MIA,Miami,56,Gary Payton,G,,34:41,0.200,0.800,0.000,0.000,0.429,0.000,0.571,0.714,0.000,0.000,0.000,1.000,0.000,1.000,0.000
17,0020600001,1610612748,MIA,Miami,297,Alonzo Mourning,,,15:23,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
18,0020600001,1610612748,MIA,Miami,1899,James Posey,,,22:35,1.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,1.000,1.000,0.000,0.000,0.000,1.000,0.000
19,0020600001,1610612748,MIA,Miami,200809,Chris Quinn,,,13:51,0.600,0.400,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000,0.000,0.000,1.000
20,0020600001,1610612748,MIA,Miami,2574,Jason Kapono,,,10:32,1.000,0.000,0.667,0.667,0.000,0.000,0.333,0.000,0.000,1.000,0.000,0.000,0.000,1.000,0.000
21,0020600001,1610612748,MIA,Miami,2748,Dorell Wright,,,8:14,1.000,0.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,1.000,0.000
22,0020600001,1610612748,MIA,Miami,101134,Wayne Simien,,,7:43,1.000,0.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,1.000
23,0020600001,1610612748,MIA,Miami,200823,Robert Hite,,,5:07,0.333,0.667,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [32]:
ep.boxscorescoringv2.BoxScoreScoringV2(game_id=game_id_).get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,PCT_FGA_2PT,PCT_FGA_3PT,PCT_PTS_2PT,PCT_PTS_2PT_MR,PCT_PTS_3PT,PCT_PTS_FB,PCT_PTS_FT,PCT_PTS_OFF_TOV,PCT_PTS_PAINT,PCT_AST_2PM,PCT_UAST_2PM,PCT_AST_3PM,PCT_UAST_3PM,PCT_AST_FGM,PCT_UAST_FGM
0,0020600001,1610612748,Heat,MIA,Miami,240:00,0.738,0.262,0.667,0.273,0.136,0.091,0.197,0.227,0.394,0.545,0.455,0.333,0.667,0.520,0.480
1,0020600001,1610612741,Bulls,CHI,Chicago,240:00,0.835,0.165,0.593,0.259,0.194,0.194,0.213,0.296,0.333,0.531,0.469,0.714,0.286,0.564,0.436

In [ ]:
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

In [14]:
game_id_ = '0020600001'
ep.boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id=game_id_).get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,SPD,DIST,ORBC,DRBC,RBC,TCHS,SAST,FTAST,PASS,AST,CFGM,CFGA,CFG_PCT,UFGM,UFGA,UFG_PCT,FG_PCT,DFGM,DFGA,DFG_PCT
0,0020600001,1610612741,CHI,Chicago,2736,Luol Deng,F,,24:07,0.0,0.0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0.0,0.444,0,0,0.0
1,0020600001,1610612741,CHI,Chicago,136,P.J. Brown,F,,18:23,0.0,0.0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0.0,0.500,0,0,0.0
2,0020600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,,28:29,0.0,0.0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0.0,0.400,0,0,0.0
3,0020600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,,22:56,0.0,0.0,0,0,0,0,0,0,0,2,0,0,0.0,0,0,0.0,0.111,0,0,0.0
4,0020600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,,34:38,0.0,0.0,0,0,0,0,0,0,0,3,0,0,0.0,0,0,0.0,0.556,0,0,0.0
5,0020600001,1610612741,CHI,Chicago,2804,Andres Nocioni,,,28:54,0.0,0.0,0,0,0,0,0,0,0,2,0,0,0.0,0,0,0.0,0.500,0,0,0.0
6,0020600001,1610612741,CHI,Chicago,2768,Chris Duhon,,,16:40,0.0,0.0,0,0,0,0,0,0,0,3,0,0,0.0,0,0,0.0,0.875,0,0,0.0
7,0020600001,1610612741,CHI,Chicago,200748,Tyrus Thomas,,,16:23,0.0,0.0,0,0,0,0,0,0,0,2,0,0,0.0,0,0,0.0,0.250,0,0,0.0
8,0020600001,1610612741,CHI,Chicago,2751,Viktor Khryapa,,,14:00,0.0,0.0,0,0,0,0,0,0,0,3,0,0,0.0,0,0,0.0,0.500,0,0,0.0
9,0020600001,1610612741,CHI,Chicago,1559,Adrian Griffin,,,11:14,0.0,0.0,0,0,0,0,0,0,0,2,0,0,0.0,0,0,0.0,0.500,0,0,0.0
10,0020600001,1610612741,CHI,Chicago,2124,Malik Allen,,,13:42,0.0,0.0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0.0,0.333,0,0,0.0
11,0020600001,1610612741,CHI,Chicago,200757,Thabo Sefolosha,,,10:34,0.0,0.0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0.0,1.000,0,0,0.0
12,0020600001,1610612748,MIA,Miami,952,Antoine Walker,F,,35:47,0.0,0.0,0,0,0,0,0,0,0,2,0,0,0.0,0,0,0.0,0.333,0,0,0.0
13,0020600001,1610612748,MIA,Miami,2617,Udonis Haslem,F,,27:34,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0.0,0.333,0,0,0.0
14,0020600001,1610612748,MIA,Miami,406,Shaquille O'Neal,C,,24:26,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0.0,0.300,0,0,0.0
15,0020600001,1610612748,MIA,Miami,2548,Dwyane Wade,G,,34:07,0.0,0.0,0,0,0,0,0,0,0,3,0,0,0.0,0,0,0.0,0.667,0,0,0.0
16,0020600001,1610612748,MIA,Miami,56,Gary Payton,G,,34:41,0.0,0.0,0,0,0,0,0,0,0,4,0,0,0.0,0,0,0.0,0.200,0,0,0.0
17,0020600001,1610612748,MIA,Miami,297,Alonzo Mourning,,,15:23,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0.0,0.000,0,0,0.0
18,0020600001,1610612748,MIA,Miami,1899,James Posey,,,22:35,0.0,0.0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,0.0,1.000,0,0,0.0
19,0020600001,1610612748,MIA,Miami,200809,Chris Quinn,,,13:51,0.0,0.0,0,0,0,0,0,0,0,3,0,0,0.0,0,0,0.0,0.200,0,0,0.0
20,0020600001,1610612748,MIA,Miami,2574,Jason Kapono,,,10:32,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0.0,1.000,0,0,0.0
21,0020600001,1610612748,MIA,Miami,2748,Dorell Wright,,,8:14,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0.0,0.250,0,0,0.0
22,0020600001,1610612748,MIA,Miami,101134,Wayne Simien,,,7:43,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0.0,1.000,0,0,0.0
23,0020600001,1610612748,MIA,Miami,200823,Robert Hite,,,5:07,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0.0,0.000,0,0,0.0

In [12]:
game_id_ = '0020600001'
ep.boxscoremiscv2.BoxScoreMiscV2(game_id=game_id_).get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,PTS_OFF_TOV,PTS_2ND_CHANCE,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLK,BLKA,PF,PFD
0,0020600001,1610612741,CHI,Chicago,2736,Luol Deng,F,,24:07,3,2,7,4,9,2,2,16,0,1,2,3
1,0020600001,1610612741,CHI,Chicago,136,P.J. Brown,F,,18:23,0,0,0,0,4,0,2,10,1,0,3,1
2,0020600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,,28:29,1,2,0,4,11,2,4,16,1,0,2,2
3,0020600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,,22:56,2,0,4,2,9,2,2,10,0,1,3,2
4,0020600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,,34:38,8,6,0,8,13,2,6,24,0,0,2,5
5,0020600001,1610612741,CHI,Chicago,2804,Andres Nocioni,,,28:54,4,0,0,4,11,2,4,16,0,1,2,2
6,0020600001,1610612741,CHI,Chicago,2768,Chris Duhon,,,16:40,5,0,3,2,4,0,2,14,0,0,0,2
7,0020600001,1610612741,CHI,Chicago,200748,Tyrus Thomas,,,16:23,2,2,2,2,4,0,4,14,2,0,3,3
8,0020600001,1610612741,CHI,Chicago,2751,Viktor Khryapa,,,14:00,2,0,2,0,2,0,0,0,0,0,2,2
9,0020600001,1610612741,CHI,Chicago,1559,Adrian Griffin,,,11:14,0,0,0,2,2,0,0,0,0,0,0,0
10,0020600001,1610612741,CHI,Chicago,2124,Malik Allen,,,13:42,2,4,0,4,4,0,2,6,1,0,1,0
11,0020600001,1610612741,CHI,Chicago,200757,Thabo Sefolosha,,,10:34,3,2,3,4,2,0,2,4,0,0,1,2
12,0020600001,1610612748,MIA,Miami,952,Antoine Walker,F,,35:47,0,0,0,6,23,11,16,24,2,0,3,4
13,0020600001,1610612748,MIA,Miami,2617,Udonis Haslem,F,,27:34,4,0,0,2,16,9,11,18,0,2,2,2
14,0020600001,1610612748,MIA,Miami,406,Shaquille O'Neal,C,,24:26,2,2,0,6,16,9,16,20,1,1,2,4
15,0020600001,1610612748,MIA,Miami,2548,Dwyane Wade,G,,34:07,4,0,4,8,23,16,16,28,0,0,3,4
16,0020600001,1610612748,MIA,Miami,56,Gary Payton,G,,34:41,5,0,0,0,18,9,11,20,0,0,4,3
17,0020600001,1610612748,MIA,Miami,297,Alonzo Mourning,,,15:23,0,0,0,0,9,7,0,8,0,2,1,1
18,0020600001,1610612748,MIA,Miami,1899,James Posey,,,22:35,0,0,2,2,20,10,10,20,0,0,3,1
19,0020600001,1610612748,MIA,Miami,200809,Chris Quinn,,,13:51,0,0,0,2,13,7,5,12,0,0,2,1
20,0020600001,1610612748,MIA,Miami,2574,Jason Kapono,,,10:32,0,0,0,0,7,6,5,12,0,0,0,0
21,0020600001,1610612748,MIA,Miami,2748,Dorell Wright,,,8:14,0,0,0,0,5,2,5,6,0,0,1,0
22,0020600001,1610612748,MIA,Miami,101134,Wayne Simien,,,7:43,0,0,0,0,5,2,5,6,0,0,1,1
23,0020600001,1610612748,MIA,Miami,200823,Robert Hite,,,5:07,0,0,0,0,5,2,5,6,0,0,2,0

In [11]:
game_id_ = '0020600001'
ep.boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id=game_id_).get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,OREB_PCT,OPP_EFG_PCT,OPP_FTA_RATE,OPP_TOV_PCT,OPP_OREB_PCT
0,0020600001,1610612741,CHI,Chicago,2736,Luol Deng,F,,24:07,0.449,0.462,0.171,0.381,0.544,0.147,0.281,0.200
1,0020600001,1610612741,CHI,Chicago,136,P.J. Brown,F,,18:23,0.470,0.303,0.182,0.375,0.457,0.304,0.305,0.077
2,0020600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,,28:29,0.436,0.489,0.140,0.308,0.440,0.262,0.215,0.125
3,0020600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,,22:56,0.359,0.487,0.169,0.333,0.470,0.212,0.222,0.059
4,0020600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,,34:38,0.517,0.362,0.188,0.393,0.459,0.245,0.253,0.154
5,0020600001,1610612741,CHI,Chicago,2804,Andres Nocioni,,,28:54,0.585,0.404,0.171,0.318,0.405,0.459,0.248,0.087
6,0020600001,1610612741,CHI,Chicago,2768,Chris Duhon,,,16:40,0.654,0.423,0.126,0.273,0.333,0.667,0.249,0.188
7,0020600001,1610612741,CHI,Chicago,200748,Tyrus Thomas,,,16:23,0.554,0.321,0.156,0.385,0.320,0.280,0.193,0.176
8,0020600001,1610612741,CHI,Chicago,2751,Viktor Khryapa,,,14:00,0.786,0.429,0.179,0.286,0.176,0.647,0.243,0.000
9,0020600001,1610612741,CHI,Chicago,1559,Adrian Griffin,,,11:14,0.735,0.412,0.136,0.167,0.231,0.769,0.223,0.000
10,0020600001,1610612741,CHI,Chicago,2124,Malik Allen,,,13:42,0.659,0.364,0.182,0.333,0.353,0.471,0.226,0.000
11,0020600001,1610612741,CHI,Chicago,200757,Thabo Sefolosha,,,10:34,0.639,0.333,0.185,0.429,0.357,0.071,0.294,0.000
12,0020600001,1610612748,MIA,Miami,952,Antoine Walker,F,,35:47,0.400,0.420,0.214,0.129,0.525,0.339,0.169,0.310
13,0020600001,1610612748,MIA,Miami,2617,Udonis Haslem,F,,27:34,0.438,0.275,0.219,0.091,0.424,0.500,0.175,0.346
14,0020600001,1610612748,MIA,Miami,406,Shaquille O'Neal,C,,24:26,0.470,0.364,0.238,0.167,0.571,0.310,0.164,0.389
15,0020600001,1610612748,MIA,Miami,2548,Dwyane Wade,G,,34:07,0.479,0.298,0.246,0.160,0.534,0.362,0.164,0.407
16,0020600001,1610612748,MIA,Miami,56,Gary Payton,G,,34:41,0.418,0.408,0.192,0.100,0.464,0.455,0.162,0.300
17,0020600001,1610612748,MIA,Miami,297,Alonzo Mourning,,,15:23,0.381,0.429,0.226,0.067,0.400,0.560,0.160,0.333
18,0020600001,1610612748,MIA,Miami,1899,James Posey,,,22:35,0.389,0.407,0.303,0.111,0.667,0.417,0.138,0.357
19,0020600001,1610612748,MIA,Miami,200809,Chris Quinn,,,13:51,0.412,0.529,0.260,0.091,0.654,0.308,0.136,0.400
20,0020600001,1610612748,MIA,Miami,2574,Jason Kapono,,,10:32,0.357,0.071,0.294,0.000,0.639,0.333,0.185,0.429
21,0020600001,1610612748,MIA,Miami,2748,Dorell Wright,,,8:14,0.273,0.091,0.304,0.000,0.625,0.417,0.185,0.200
22,0020600001,1610612748,MIA,Miami,101134,Wayne Simien,,,7:43,0.300,0.100,0.324,0.000,0.682,0.455,0.197,0.200
23,0020600001,1610612748,MIA,Miami,200823,Robert Hite,,,5:07,0.000,0.000,0.455,0.000,0.571,0.714,0.268,0.250

In [8]:
game_id_ = '0020600001'
boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_id_).get_data_frames()[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0020600001,1610612741,CHI,Chicago,2736,Luol Deng,F,,24:07,102.3,102.1,86.6,87.0,15.7,15.2,0.083,0.33,6.3,0.040,0.056,0.047,18.8,0.444,0.515,0.263,0.273,92.67,92.55,77.13,47,0.064
1,0020600001,1610612741,CHI,Chicago,136,P.J. Brown,F,,18:23,104.2,108.1,69.3,65.8,34.9,42.3,0.077,0.50,16.7,0.000,0.200,0.086,33.3,0.500,0.694,0.111,0.113,97.24,97.91,81.60,37,0.088
2,0020600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,,28:29,98.0,103.7,77.0,76.8,21.0,26.9,0.059,0.00,16.7,0.194,0.192,0.193,0.0,0.400,0.460,0.077,0.077,95.18,92.69,77.24,54,0.152
3,0020600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,,22:56,86.6,91.1,75.4,73.9,11.1,17.2,0.167,1.00,13.3,0.000,0.050,0.020,13.3,0.111,0.268,0.232,0.235,96.77,95.26,79.38,45,-0.096
4,0020600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,,34:38,108.3,113.6,77.3,76.5,31.0,37.2,0.167,0.00,13.6,0.000,0.133,0.065,0.0,0.639,0.658,0.241,0.237,94.60,92.86,77.38,66,0.296
5,0020600001,1610612741,CHI,Chicago,2804,Andres Nocioni,,,28:54,118.2,121.1,72.6,73.2,45.6,47.8,0.095,1.00,16.7,0.042,0.385,0.220,16.7,0.563,0.563,0.152,0.153,95.38,93.85,78.21,57,0.179
6,0020600001,1610612741,CHI,Chicago,2768,Chris Duhon,,,16:40,128.8,128.1,71.5,67.6,57.3,60.5,0.375,3.00,23.1,0.000,0.118,0.069,7.7,1.063,1.073,0.278,0.287,92.12,95.00,79.17,32,0.561
7,0020600001,1610612741,CHI,Chicago,200748,Tyrus Thomas,,,16:23,109.5,112.9,64.4,66.7,45.2,46.2,0.143,0.67,16.7,0.067,0.222,0.152,25.0,0.250,0.301,0.270,0.271,92.35,89.36,74.47,31,-0.017
8,0020600001,1610612741,CHI,Chicago,2751,Viktor Khryapa,,,14:00,143.1,142.9,41.6,42.9,101.5,100.0,0.231,1.50,30.0,0.143,0.188,0.174,20.0,0.500,0.512,0.233,0.234,97.37,96.00,80.00,28,0.129
9,0020600001,1610612741,CHI,Chicago,1559,Adrian Griffin,,,11:14,140.4,140.9,53.6,52.2,86.8,88.7,0.200,2.00,40.0,0.000,0.083,0.053,20.0,0.500,0.500,0.125,0.130,95.03,96.14,80.12,22,0.082
10,0020600001,1610612741,CHI,Chicago,2124,Malik Allen,,,13:42,130.8,133.3,64.1,60.7,66.7,72.6,0.091,0.00,14.3,0.100,0.154,0.130,0.0,0.333,0.333,0.194,0.197,94.67,96.35,80.29,27,0.091
11,0020600001,1610612741,CHI,Chicago,200757,Thabo Sefolosha,,,10:34,129.4,133.3,53.8,52.4,75.6,81.0,0.143,0.00,16.7,0.250,0.000,0.118,0.0,1.000,1.034,0.200,0.203,95.55,95.36,79.47,21,0.424
12,0020600001,1610612748,MIA,Miami,952,Antoine Walker,F,,35:47,74.0,74.3,107.3,113.4,-33.3,-39.1,0.125,0.67,11.8,0.000,0.176,0.087,17.6,0.333,0.387,0.200,0.202,94.60,91.89,76.57,70,0.048
13,0020600001,1610612748,MIA,Miami,2617,Udonis Haslem,F,,27:34,74.8,75.9,94.5,100.0,-19.8,-24.1,0.000,0.00,0.0,0.000,0.194,0.105,0.0,0.333,0.333,0.158,0.158,97.47,94.03,78.36,54,0.096
14,0020600001,1610612748,MIA,Miami,406,Shaquille O'Neal,C,,24:26,82.1,84.4,117.0,123.9,-34.9,-39.5,0.000,0.00,0.0,0.158,0.091,0.122,21.4,0.300,0.322,0.286,0.284,93.32,89.39,74.49,45,-0.029
15,0020600001,1610612748,MIA,Miami,2548,Dwyane Wade,G,,34:07,82.9,84.4,114.5,120.3,-31.6,-35.9,0.273,0.75,12.5,0.037,0.032,0.034,16.7,0.733,0.709,0.304,0.304,93.14,90.04,75.04,64,0.169
16,0020600001,1610612748,MIA,Miami,56,Gary Payton,G,,34:41,76.7,76.5,100.0,103.0,-23.3,-26.6,0.222,1.00,26.7,0.000,0.086,0.043,26.7,0.300,0.486,0.153,0.155,93.97,92.72,77.27,68,0.028
17,0020600001,1610612748,MIA,Miami,297,Alonzo Mourning,,,15:23,67.8,63.6,96.3,100.0,-28.4,-36.4,0.000,0.00,0.0,0.000,0.118,0.059,40.0,0.000,0.174,0.147,0.156,96.87,98.25,81.87,33,-0.133
18,0020600001,1610612748,MIA,Miami,1899,James Posey,,,22:35,65.4,65.1,137.6,136.4,-72.3,-71.2,0.111,1.00,33.3,0.000,0.067,0.029,33.3,1.000,1.000,0.044,0.045,91.89,92.48,77.07,43,0.000
19,0020600001,1610612748,MIA,Miami,200809,Chris Quinn,,,13:51,70.5,65.5,135.5,142.9,-65.0,-77.3,0.500,0.00,37.5,0.000,0.000,0.000,0.0,0.200,0.200,0.167,0.179,97.87,98.77,82.31,29,-0.023
20,0020600001,1610612748,MIA,Miami,2574,Jason Kapono,,,10:32,53.8,55.0,129.4,133.3,-75.6,-78.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,1.000,1.042,0.050,0.049,95.88,93.42,77.85,20,0.121
21,0020600001,1610612748,MIA,Miami,2748,Dorell Wright,,,8:14,42.6,43.8,117.3,118.8,-74.7,-75.0,0.000,0.00,0.0,0.000,0.333,0.143,20.0,0.250,0.250,0.313,0.304,95.14,93.28,77.73,16,-0.047
22,0020600001,1610612748,MIA,Miami,101134,Wayne Simien,,,7:43,45.3,46.7,125.0,118.8,-79.7,-72.1,0.000,0.00,0.0,0.000,0.200,0.083,50.0,1.000,1.000,0.133,0.130,95.30,96.41,80.35,15,0.043
23,0020600001,1610612748,MIA,Miami,200823,Robert Hite,,,5:07,0.0,0.0,107.1,100.0,-107.1,-100.0,0.000,0.00,0.0,0.000,0.250,0.100,40.0,0.000,0.000,0.455,0.455,104.13,107.88,89.90,11,-0.909

### Getting Team and Player IDs
The package also includes utilities for fetching player and team information available under `nba_api.stats.static`.
You can use this to fetch player IDs and team IDs, which are often used as inputs to API endpoints.

In [2]:
from nba_api.stats.static import teams
# get_teams returns a list of 30 dictionaries, each an NBA team.
nba_teams = teams.get_teams()
print('Number of teams fetched: {}'.format(len(nba_teams)))
nba_teams[:3]

Number of teams fetched: 30

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Atlanta',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970}]

In [3]:
from nba_api.stats.static import players
# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_players()
print('Number of players fetched: {}'.format(len(nba_players)))
nba_players[:5]

Number of players fetched: 4374

[{'id': 76001,
  'full_name': 'Alaa Abdelnaby',
  'first_name': 'Alaa',
  'last_name': 'Abdelnaby'},
 {'id': 76002,
  'full_name': 'Zaid Abdul-Aziz',
  'first_name': 'Zaid',
  'last_name': 'Abdul-Aziz'},
 {'id': 76003,
  'full_name': 'Kareem Abdul-Jabbar',
  'first_name': 'Kareem',
  'last_name': 'Abdul-Jabbar'},
 {'id': 51,
  'full_name': 'Mahmoud Abdul-Rauf',
  'first_name': 'Mahmoud',
  'last_name': 'Abdul-Rauf'},
 {'id': 1505,
  'full_name': 'Tariq Abdul-Wahad',
  'first_name': 'Tariq',
  'last_name': 'Abdul-Wahad'}]

To search for an individual team or player by its name (or other attribute), dictionary comprehensions are your friend.

In [4]:
spurs = [team for team in nba_teams
         if team['full_name'] == 'San Antonio Spurs'][0]
spurs

{'id': 1610612759,
 'full_name': 'San Antonio Spurs',
 'abbreviation': 'SAS',
 'nickname': 'Spurs',
 'city': 'San Antonio',
 'state': 'Texas',
 'year_founded': 1976}

In [5]:
big_fundamental = [player for player in nba_players
                   if player['full_name'] == 'Tim Duncan'][0]
big_fundamental

{'id': 1495,
 'full_name': 'Tim Duncan',
 'first_name': 'Tim',
 'last_name': 'Duncan'}