In [1]:
# Target variable 'spread_a' is most predicted by stat differences which should be used.

random_state_2909 = 2909

# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

## 4.2 Introduction<a id='4.2_Introduction'></a>

## 4.3 Imports<a id='4.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 4.4 Functions<a id='4.4_Imports'></a>

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 4.5 Load Data<a id='4.5_Load_Data'></a>

In [4]:
df_stats = rcp('53AAprediction_stats_2010_2018.csv', ['game_date'])
p(df_stats)

(10266, 107)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,team_id_a,spread_a,away_home_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,team_id_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,Celtics,BOS,Boston,1610612738,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami,1610612748,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,1610612756,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland,1610612757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,1610612745,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles,1610612747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,1610612750,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento,1610612758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,Heat,MIA,Miami,1610612748,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia,1610612755,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,Warriors,GSW,Golden State,1610612744,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston,1610612745,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,Cavaliers,CLE,Cleveland,1610612739,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,Cavaliers,CLE,Cleveland,1610612739,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,Cavaliers,CLE,Cleveland,1610612739,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,Cavaliers,CLE,Cleveland,1610612739,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [5]:
df_stats_gitiab_spread = df_stats.loc[:, ['game_id', 'team_id_a', 'team_id_b', 'spread_a']]
p(df_stats_gitiab_spread)

(10266, 4)

        game_id   team_id_a   team_id_b  spread_a
0      21000001  1610612738  1610612748        -8
1      21000002  1610612756  1610612757        14
2      21000003  1610612745  1610612747         2
3      21000009  1610612750  1610612758         1
4      21000006  1610612748  1610612755       -10
10261  41700317  1610612744  1610612745        -9
10262  41700401  1610612739  1610612744        10
10263  41700402  1610612739  1610612744        19
10264  41700403  1610612739  1610612744         8
10265  41700404  1610612739  1610612744        23

In [6]:
df_stat_cma5_12_999_diff = rcp('58Bstats_cma5_12_999_diff_cmax5_12_999_diff_2010_2018.csv', ['game_date'])
p(df_stat_cma5_12_999_diff)

(10266, 301)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,-101.60,-106.80,-105.30,-107.70,3.80,0.90,-0.6580,-1.190,-16.70,-0.3960,-0.6950,-0.5540,-19.3870,-20.40,-0.4620,-5.320000e-01,-1.0,-0.1960,-1.073200e+02,-103.5,-86.250,-103.0,-0.5070,-240.0,0.0000,-240.0,-38.0,-91.0,-0.4180,-8.0,-20.0,-0.4000,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.000,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000,7.7,5.3,-7.7,-5.3,24.1,24.6,0.011,0.86,2.7,0.034,-0.002,-0.005,-2.597,-3.8,-0.010,-0.005,0.0,0.002,0.00,0.0,0.00,-4.0,0.121,0.0,0.067,0.0,3.0,4.0,0.011,0.0,-5.0,0.036,-7.0,-9.0,0.092593,6.0,1.0,2.0,3.0,1.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,-0.7,-4.0,-7.7,-5.3,20.5,21.7,0.193,-3.11,1.0,0.034,-0.029,0.013,-2.597,-3.8,-0.008,0.018,0.0,0.003,7.48,5.0,4.17,4.0,0.076,0.0,0.0,0.0,3.0,4.0,0.014,-2.0,-4.0,-0.110,-3.0,0.0,0.003268,5.0,4.0,8.0,7.0,0.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,6.6,5.4,-0.3,3.0,18.1,13.9,0.089,-1.80,6.9,0.014,-0.029,0.012,3.969,5.0,-0.024,-0.022,0.0,0.000,2.26,2.0,1.67,-3.0,0.124,-25.0,0.0,-25.0,6.0,1.0,0.032,-2.0,-16.0,-0.022,-8.0,-12.0,0.058824,7.0,4.0,7.0,15.0,0.0,3.0,3.0,-5.0,-5.0,-1.0,0.0
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051,-9.4,-7.8,5.8,6.9,-11.7,-12.5,-0.019,-0.97,-1.4,0.047,0.001,0.033,-0.416,0.2,0.007,0.019,0.0,0.000,4.66,1.0,0.83,2.0,-0.019,0.0,-0.096,0.0,-7.0,-5.0,-0.016,1.0,-4.0,0.079,5.0,7.0,-0.111111,-1.0,1.0,-2.0,-3.0,-2.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-2.5,-2.4,-11.1,-5.6,-0.215,5.64,-1.4,0.047,-0.052,0.015,-0.416,0.2,0.061,0.036,0.0,-0.001,-10.94,-10.5,-8.75,-9.0,-0.019,25.0,0.0,25.0,2.0,3.0,0.070,1.0,-5.0,0.079,7.0,8.0,-0.094444,-1.0,-5.0,-10.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0

In [7]:
df_stat_cma5_12_999_diff = pd.merge(df_stat_cma5_12_999_diff, df_stats_gitiab_spread, on=['game_id', 'team_id_a', 'team_id_b'])
p(df_stat_cma5_12_999_diff)

(10266, 302)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,spread_a
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-8
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
4,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,-101.60,-106.80,-105.30,-107.70,3.80,0.90,-0.6580,-1.190,-16.70,-0.3960,-0.6950,-0.5540,-19.3870,-20.40,-0.4620,-5.320000e-01,-1.0,-0.1960,-1.073200e+02,-103.5,-86.250,-103.0,-0.5070,-240.0,0.0000,-240.0,-38.0,-91.0,-0.4180,-8.0,-20.0,-0.4000,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.000,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-4
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000,7.7,5.3,-7.7,-5.3,24.1,24.6,0.011,0.86,2.7,0.034,-0.002,-0.005,-2.597,-3.8,-0.010,-0.005,0.0,0.002,0.00,0.0,0.00,-4.0,0.121,0.0,0.067,0.0,3.0,4.0,0.011,0.0,-5.0,0.036,-7.0,-9.0,0.092593,6.0,1.0,2.0,3.0,1.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,-0.7,-4.0,-7.7,-5.3,20.5,21.7,0.193,-3.11,1.0,0.034,-0.029,0.013,-2.597,-3.8,-0.008,0.018,0.0,0.003,7.48,5.0,4.17,4.0,0.076,0.0,0.0,0.0,3.0,4.0,0.014,-2.0,-4.0,-0.110,-3.0,0.0,0.003268,5.0,4.0,8.0,7.0,0.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,6.6,5.4,-0.3,3.0,18.1,13.9,0.089,-1.80,6.9,0.014,-0.029,0.012,3.969,5.0,-0.024,-0.022,0.0,0.000,2.26,2.0,1.67,-3.0,0.124,-25.0,0.0,-25.0,6.0,1.0,0.032,-2.0,-16.0,-0.022,-8.0,-12.0,0.058824,7.0,4.0,7.0,15.0,0.0,3.0,3.0,-5.0,-5.0,-1.0,0.0,-9
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051,-9.4,-7.8,5.8,6.9,-11.7,-12.5,-0.019,-0.97,-1.4,0.047,0.001,0.033,-0.416,0.2,0.007,0.019,0.0,0.000,4.66,1.0,0.83,2.0,-0.019,0.0,-0.096,0.0,-7.0,-5.0,-0.016,1.0,-4.0,0.079,5.0,7.0,-0.111111,-1.0,1.0,-2.0,-3.0,-2.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-2.5,-2.4,-11.1,-5.6,-0.215,5.64,-1.4,0.047,-0.052,0.015,-0.416,0.2,0.061,0.036,0.0,-0.001,-10.94,-10.5,-8.75,-9.0,-0.019,25.0,0.0,25.0,2.0,3.0,0.070,1.0,-5.0,0.079,7.0,8.0,-0.094444,-1.0,-5.0,-10.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0,10

In [8]:
column_names_stat_list = list(df_stat_cma5_12_999_diff.columns)
pl(column_names_stat_list)

302

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'team_id_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'team_id_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'E_OFF_RATING_cma5_diff',
 'OFF_RATING_cma5_diff',
 'E_DEF_RATING_cma5_diff',
 'DEF_RATING_cma5_diff',
 'E_NET_RATING_cma5_diff',
 'NET_RATING_cma5_diff',
 'AST_PCT_cma5_diff',
 'AST_TOV_cma5_diff',
 'AST_RATIO_cma5_diff',
 'OREB_PCT_cma5_diff',
 'DREB_PCT_cma5_diff',
 'REB_PCT_cma5_diff',
 'E_TM_TOV_PCT_cma5_diff',
 'TM_TOV_PCT_cma5_diff',
 'EFG_PCT_cma5_diff',
 'TS_PCT_cma5_diff',
 'USG_PCT_cma5_diff',
 'E_USG_PCT_cma5_diff',
 'E_PACE_cma5_diff',
 'PACE_cma5_diff',
 'PACE_PER40_cma5_diff',
 'POSS_cma5_diff',
 'PIE_cma5_diff',
 'duration_minutes_cma5_diff',
 'w_pct_cma5_diff',
 'min_cma5_diff',
 'fgm_cma5_diff',
 'fga_cma5_diff',
 'fg_pct_cma5_diff',
 'fg3m_cma5_diff',
 'fg3a_cma5_diff',
 'fg3_pct_cma5_diff',
 'ftm_cma5_diff',
 'fta_cma5_diff',
 'ft_pct_cma5_diff',
 'oreb_cma5_diff',
 'dreb_cma5_diff',
 'reb_cma5_diff',
 'ast_cma5_diff',
 'stl_cma5_diff',
 'blk_cma5_diff',
 'tov_cma5_diff',
 'pf_cma5_diff',
 'pts_cma5_diff',
 'spread_cma5_diff',
 'away_home__cma5_diff',
 'E_OFF_RATING_cma12_diff',
 'OFF_RATING_cma12_diff',
 'E_DEF_RATING_cma12_diff',
 'DEF_RATING_cma12_diff',
 'E_NET_RATING_cma12_diff',
 'NET_RATING_cma12_diff',
 'AST_PCT_cma12_diff',
 'AST_TOV_cma12_diff',
 'AST_RATIO_cma12_diff',
 'OREB_PCT_cma12_diff',
 'DREB_PCT_cma12_diff',
 'REB_PCT_cma12_diff',
 'E_TM_TOV_PCT_cma12_diff',
 'TM_TOV_PCT_cma12_diff',
 'EFG_PCT_cma12_diff',
 'TS_PCT_cma12_diff',
 'USG_PCT_cma12_diff',
 'E_USG_PCT_cma12_diff',
 'E_PACE_cma12_diff',
 'PACE_cma12_diff',
 'PACE_PER40_cma12_diff',
 'POSS_cma12_diff',
 'PIE_cma12_diff',
 'duration_minutes_cma12_diff',
 'w_pct_cma12_diff',
 'min_cma12_diff',
 'fgm_cma12_diff',
 'fga_cma12_diff',
 'fg_pct_cma12_diff',
 'fg3m_cma12_diff',
 'fg3a_cma12_diff',
 'fg3_pct_cma12_diff',
 'ftm_cma12_diff',
 'fta_cma12_diff',
 'ft_pct_cma12_diff',
 'oreb_cma12_diff',
 'dreb_cma12_diff',
 'reb_cma12_diff',
 'ast_cma12_diff',
 'stl_cma12_diff',
 'blk_cma12_diff',
 'tov_cma12_diff',
 'pf_cma12_diff',
 'pts_cma12_diff',
 'spread_cma12_diff',
 'away_home__cma12_diff',
 'E_OFF_RATING_cma999_diff',
 'OFF_RATING_cma999_diff',
 'E_DEF_RATING_cma999_diff',
 'DEF_RATING_cma999_diff',
 'E_NET_RATING_cma999_diff',
 'NET_RATING_cma999_diff',
 'AST_PCT_cma999_diff',
 'AST_TOV_cma999_diff',
 'AST_RATIO_cma999_diff',
 'OREB_PCT_cma999_diff',
 'DREB_PCT_cma999_diff',
 'REB_PCT_cma999_diff',
 'E_TM_TOV_PCT_cma999_diff',
 'TM_TOV_PCT_cma999_diff',
 'EFG_PCT_cma999_diff',
 'TS_PCT_cma999_diff',
 'USG_PCT_cma999_diff',
 'E_USG_PCT_cma999_diff',
 'E_PACE_cma999_diff',
 'PACE_cma999_diff',
 'PACE_PER40_cma999_diff',
 'POSS_cma999_diff',
 'PIE_cma999_diff',
 'duration_minutes_cma999_diff',
 'w_pct_cma999_diff',
 'min_cma999_diff',
 'fgm_cma999_diff',
 'fga_cma999_diff',
 'fg_pct_cma999_diff',
 'fg3m_cma999_diff',
 'fg3a_cma999_diff',
 'fg3_pct_cma999_diff',
 'ftm_cma999_diff',
 'fta_cma999_diff',
 'ft_pct_cma999_diff',
 'oreb_cma999_diff',
 'dreb_cma999_diff',
 'reb_cma999_diff',
 'ast_cma999_diff',
 'stl_cma999_diff',
 'blk_cma999_diff',
 'tov_cma999_diff',
 'pf_cma999_diff',
 'pts_cma999_diff',
 'spread_cma999_diff',
 'away_home__cma999_diff',
 'E_OFF_RATING_cmax5_diff',
 'OFF_RATING_cmax5_diff',
 'E_DEF_RATING_cmax5_diff',
 'DEF_RATING_cmax5_diff',
 'E_NET_RATING_cmax5_diff',
 'NET_RATING_cmax5_diff',
 'AST_PCT_cmax5_diff',
 'AST_TOV_cmax5_diff',
 'AST_RATIO_cmax5_diff',
 'OREB_PCT_cmax5_diff',
 'DREB_PCT_cmax5_diff',
 'REB_PCT_cmax5_diff',
 'E_TM_TOV_PCT_cmax5_diff',
 'TM_TOV_PCT_cmax5_diff',
 'EFG_PCT_cmax5_diff',
 'TS_PCT_cmax5_diff',
 'USG_PCT_cmax5_diff',
 'E_USG_PCT_cmax5_diff',
 'E_PACE_cmax5_diff',
 'PACE_cmax5_diff',
 'PACE_PER40_cmax5_diff',
 'POSS_cmax5_diff',
 'PIE_cmax5_diff',
 'duration_minutes_cmax5_diff',
 'w_pct_cmax5_diff',
 'min_cmax5_diff',
 'fgm_cmax5_diff',
 'fga_cmax5_diff',
 'fg_pct_cmax5_diff',
 'fg3m_cmax5_diff',
 'fg3a_cmax5_diff',
 'fg3_pct_cmax5_diff',
 'ftm_cmax5_diff',
 'fta_cmax5_diff',
 'ft_pct_cmax5_diff',
 'oreb_cmax5_diff',
 'dreb_cmax5_diff',
 'reb_cmax5_diff',
 'ast_cmax5_diff',
 'stl_cmax5_diff',
 'blk_cmax5_diff',
 'tov_cmax5_diff',
 'pf_cmax5_diff',
 'pts_cmax5_diff',
 'spread_cmax5_diff',
 'away_home__cmax5_diff',
 'E_OFF_RATING_cmax12_diff',
 'OFF_RATING_cmax12_diff',
 'E_DEF_RATING_cmax12_diff',
 'DEF_RATING_cmax12_diff',
 'E_NET_RATING_cmax12_diff',
 'NET_RATING_cmax12_diff',
 'AST_PCT_cmax12_diff',
 'AST_TOV_cmax12_diff',
 'AST_RATIO_cmax12_diff',
 'OREB_PCT_cmax12_diff',
 'DREB_PCT_cmax12_diff',
 'REB_PCT_cmax12_diff',
 'E_TM_TOV_PCT_cmax12_diff',
 'TM_TOV_PCT_cmax12_diff',
 'EFG_PCT_cmax12_diff',
 'TS_PCT_cmax12_diff',
 'USG_PCT_cmax12_diff',
 'E_USG_PCT_cmax12_diff',
 'E_PACE_cmax12_diff',
 'PACE_cmax12_diff',
 'PACE_PER40_cmax12_diff',
 'POSS_cmax12_diff',
 'PIE_cmax12_diff',
 'duration_minutes_cmax12_diff',
 'w_pct_cmax12_diff',
 'min_cmax12_diff',
 'fgm_cmax12_diff',
 'fga_cmax12_diff',
 'fg_pct_cmax12_diff',
 'fg3m_cmax12_diff',
 'fg3a_cmax12_diff',
 'fg3_pct_cmax12_diff',
 'ftm_cmax12_diff',
 'fta_cmax12_diff',
 'ft_pct_cmax12_diff',
 'oreb_cmax12_diff',
 'dreb_cmax12_diff',
 'reb_cmax12_diff',
 'ast_cmax12_diff',
 'stl_cmax12_diff',
 'blk_cmax12_diff',
 'tov_cmax12_diff',
 'pf_cmax12_diff',
 'pts_cmax12_diff',
 'spread_cmax12_diff',
 'away_home__cmax12_diff',
 'E_OFF_RATING_cmax999_diff',
 'OFF_RATING_cmax999_diff',
 'E_DEF_RATING_cmax999_diff',
 'DEF_RATING_cmax999_diff',
 'E_NET_RATING_cmax999_diff',
 'NET_RATING_cmax999_diff',
 'AST_PCT_cmax999_diff',
 'AST_TOV_cmax999_diff',
 'AST_RATIO_cmax999_diff',
 'OREB_PCT_cmax999_diff',
 'DREB_PCT_cmax999_diff',
 'REB_PCT_cmax999_diff',
 'E_TM_TOV_PCT_cmax999_diff',
 'TM_TOV_PCT_cmax999_diff',
 'EFG_PCT_cmax999_diff',
 'TS_PCT_cmax999_diff',
 'USG_PCT_cmax999_diff',
 'E_USG_PCT_cmax999_diff',
 'E_PACE_cmax999_diff',
 'PACE_cmax999_diff',
 'PACE_PER40_cmax999_diff',
 'POSS_cmax999_diff',
 'PIE_cmax999_diff',
 'duration_minutes_cmax999_diff',
 'w_pct_cmax999_diff',
 'min_cmax999_diff',
 'fgm_cmax999_diff',
 'fga_cmax999_diff',
 'fg_pct_cmax999_diff',
 'fg3m_cmax999_diff',
 'fg3a_cmax999_diff',
 'fg3_pct_cmax999_diff',
 'ftm_cmax999_diff',
 'fta_cmax999_diff',
 'ft_pct_cmax999_diff',
 'oreb_cmax999_diff',
 'dreb_cmax999_diff',
 'reb_cmax999_diff',
 'ast_cmax999_diff',
 'stl_cmax999_diff',
 'blk_cmax999_diff',
 'tov_cmax999_diff',
 'pf_cmax999_diff',
 'pts_cmax999_diff',
 'spread_cmax999_diff',
 'away_home__cmax999_diff',
 'spread_a']

## 4.6 Get Indicator Variables<a id='4.6 Get_Indicator_Variables'></a>

In [9]:
df_stat_cma5_12_999_diff.select_dtypes('object')

,season,season_type,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b
0,2010-11,Regular Season,Celtics,BOS,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA
1,2010-11,Regular Season,Suns,PHX,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR
2,2010-11,Regular Season,Rockets,HOU,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL
3,2010-11,Regular Season,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,W,MIL vs. NOH,MIL,NOH
4,2010-11,Regular Season,Warriors,GSW,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,2017-18,Playoffs,Warriors,GSW,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU
10262,2017-18,Playoffs,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW
10263,2017-18,Playoffs,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW
10264,2017-18,Playoffs,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW
10265,2017-18,Playoffs,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW

In [10]:
column_names_categorical_list = list(df_stat_cma5_12_999_diff.select_dtypes('object').columns) + ['team_id_a', 'team_id_b']
pl(column_names_categorical_list)

22

['season',
 'season_type',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'team_id_a',
 'team_id_b']

In [11]:
df_indicator_variables = pd.get_dummies(df_stat_cma5_12_999_diff[column_names_categorical_list])
p(df_indicator_variables)

(10266, 1330)

,team_id_a,team_id_b,season_2010-11,season_2011-12,season_2012-13,season_2013-14,season_2014-15,season_2015-16,season_2016-17,season_2017-18,season_type_Playoffs,season_type_Regular Season,TEAM_NAME_a_76ers,TEAM_NAME_a_Bobcats,TEAM_NAME_a_Bucks,TEAM_NAME_a_Bulls,TEAM_NAME_a_Cavaliers,TEAM_NAME_a_Celtics,TEAM_NAME_a_Clippers,TEAM_NAME_a_Grizzlies,TEAM_NAME_a_Hawks,TEAM_NAME_a_Heat,TEAM_NAME_a_Hornets,TEAM_NAME_a_Jazz,TEAM_NAME_a_Kings,TEAM_NAME_a_Knicks,TEAM_NAME_a_Lakers,TEAM_NAME_a_Magic,TEAM_NAME_a_Mavericks,TEAM_NAME_a_Nets,TEAM_NAME_a_Nuggets,TEAM_NAME_a_Pacers,TEAM_NAME_a_Pelicans,TEAM_NAME_a_Pistons,TEAM_NAME_a_Raptors,TEAM_NAME_a_Rockets,TEAM_NAME_a_Spurs,TEAM_NAME_a_Suns,TEAM_NAME_a_Thunder,TEAM_NAME_a_Timberwolves,TEAM_NAME_a_Trail Blazers,TEAM_NAME_a_Warriors,TEAM_ABBREVIATION_a_ATL,TEAM_ABBREVIATION_a_BKN,TEAM_ABBREVIATION_a_BOS,TEAM_ABBREVIATION_a_CHA,TEAM_ABBREVIATION_a_CHI,TEAM_ABBREVIATION_a_CLE,TEAM_ABBREVIATION_a_DAL,TEAM_ABBREVIATION_a_DEN,TEAM_ABBREVIATION_a_DET,TEAM_ABBREVIATION_a_GSW,TEAM_ABBREVIATION_a_HOU,TEAM_ABBREVIATION_a_IND,TEAM_ABBREVIATION_a_LAC,TEAM_ABBREVIATION_a_LAL,TEAM_ABBREVIATION_a_MEM,TEAM_ABBREVIATION_a_MIA,TEAM_ABBREVIATION_a_MIL,TEAM_ABBREVIATION_a_MIN,TEAM_ABBREVIATION_a_NJN,TEAM_ABBREVIATION_a_NOH,TEAM_ABBREVIATION_a_NOP,TEAM_ABBREVIATION_a_NYK,TEAM_ABBREVIATION_a_OKC,TEAM_ABBREVIATION_a_ORL,TEAM_ABBREVIATION_a_PHI,TEAM_ABBREVIATION_a_PHX,TEAM_ABBREVIATION_a_POR,TEAM_ABBREVIATION_a_SAC,TEAM_ABBREVIATION_a_SAS,TEAM_ABBREVIATION_a_TOR,TEAM_ABBREVIATION_a_UTA,TEAM_CITY_a_Atlanta,TEAM_CITY_a_Boston,TEAM_CITY_a_Brooklyn,TEAM_CITY_a_Charlotte,TEAM_CITY_a_Chicago,TEAM_CITY_a_Cleveland,TEAM_CITY_a_Dallas,TEAM_CITY_a_Denver,TEAM_CITY_a_Detroit,TEAM_CITY_a_Golden State,TEAM_CITY_a_Houston,TEAM_CITY_a_Indiana,TEAM_CITY_a_Los Angeles,TEAM_CITY_a_Memphis,TEAM_CITY_a_Miami,TEAM_CITY_a_Milwaukee,TEAM_CITY_a_Minnesota,TEAM_CITY_a_New Jersey,TEAM_CITY_a_New Orleans,TEAM_CITY_a_New York,TEAM_CITY_a_Oklahoma City,TEAM_CITY_a_Orlando,TEAM_CITY_a_Philadelphia,TEAM_CITY_a_Phoenix,TEAM_CITY_a_Portland,TEAM_CITY_a_Sacramento,TEAM_CITY_a_San Antonio,TEAM_CITY_a_Toronto,TEAM_CITY_a_Utah,MIN_a_239:56,MIN_a_240:00,MIN_a_265:00,MIN_a_290:00,MIN_a_315:00,MIN_a_340:00,duration_a_0 days 03:59:56,duration_a_0 days 04:00:00,duration_a_0 days 04:25:00,duration_a_0 days 04:50:00,duration_a_0 days 05:15:00,duration_a_0 days 05:40:00,wl_a_L,wl_a_W,matchup_a_ATL vs. BKN,matchup_a_ATL vs. BOS,matchup_a_ATL vs. CHA,matchup_a_ATL vs. CHI,matchup_a_ATL vs. CLE,matchup_a_ATL vs. DAL,matchup_a_ATL vs. DEN,matchup_a_ATL vs. DET,matchup_a_ATL vs. GSW,matchup_a_ATL vs. HOU,matchup_a_ATL vs. IND,matchup_a_ATL vs. LAC,matchup_a_ATL vs. LAL,matchup_a_ATL vs. MEM,matchup_a_ATL vs. MIA,matchup_a_ATL vs. MIL,matchup_a_ATL vs. MIN,matchup_a_ATL vs. NJN,matchup_a_ATL vs. NOH,matchup_a_ATL vs. NOP,matchup_a_ATL vs. NYK,matchup_a_ATL vs. OKC,matchup_a_ATL vs. ORL,matchup_a_ATL vs. PHI,matchup_a_ATL vs. PHX,matchup_a_ATL vs. POR,matchup_a_ATL vs. SAC,matchup_a_ATL vs. SAS,matchup_a_ATL vs. TOR,matchup_a_ATL vs. UTA,matchup_a_ATL vs. WAS,matchup_a_BKN vs. BOS,matchup_a_BKN vs. CHA,matchup_a_BKN vs. CHI,matchup_a_BKN vs. CLE,matchup_a_BKN vs. DAL,matchup_a_BKN vs. DEN,matchup_a_BKN vs. DET,matchup_a_BKN vs. GSW,matchup_a_BKN vs. HOU,matchup_a_BKN vs. IND,matchup_a_BKN vs. LAC,matchup_a_BKN vs. LAL,matchup_a_BKN vs. MEM,matchup_a_BKN vs. MIA,matchup_a_BKN vs. MIL,matchup_a_BKN vs. MIN,matchup_a_BKN vs. NOH,matchup_a_BKN vs. NOP,matchup_a_BKN vs. NYK,matchup_a_BKN vs. OKC,matchup_a_BKN vs. ORL,matchup_a_BKN vs. PHI,matchup_a_BKN vs. PHX,matchup_a_BKN vs. POR,matchup_a_BKN vs. SAC,matchup_a_BKN vs. SAS,matchup_a_BKN vs. TOR,matchup_a_BKN vs. UTA,matchup_a_BKN vs. WAS,matchup_a_BOS vs. CHA,matchup_a_BOS vs. CHI,matchup_a_BOS vs. CLE,matchup_a_BOS vs. DAL,matchup_a_BOS vs. DEN,matchup_a_BOS vs. DET,matchup_a_BOS vs. GSW,matchup_a_BOS vs. HOU,matchup_a_BOS vs. IND,matchup_a_BOS vs. LAC,matchup_a_BOS vs. LAL,matchup_a_BOS vs. MEM,matchup_a_BOS vs. MIA,matchup_a_BOS vs. MIL,matchup_a_BOS vs. MIN,matchup_a_BOS vs. NJN,matchup_a_BOS vs. NOH,matchup_a_BOS vs. NOP,matchup_a_BOS vs. NYK,matchup_a_BOS vs. OKC,matchup_a_BOS vs. ORL,matchup_a_BOS vs. PHI,matchup_a_BOS vs. PHX,matchup_a_BOS vs. POR,matchup_a_BOS vs. SAC,matchup_a_BOS vs. SAS,matchup_a_BOS vs. TOR,matchup_a_BOS vs. UTA,matchup_a_BOS vs. WAS,matchup_a_CHA vs. CHI,matchup_a_CHA vs. CLE,matchup_a_CHA vs. DAL,matchup_a_CHA vs. DEN,matchup_a_CHA vs. DET,matchup_a_CHA vs. GSW,matchup_a_CHA vs. HOU,matchup_a_CHA vs. IND,matchup_a_CHA vs. LAC,matchup_a_CHA vs. LAL,matchup_a_CHA vs. MEM,matchup_a_CHA vs. MIA,matchup_a_CHA vs. MIL,matchup_a_CHA vs. MIN,matchup_a_CHA vs. NJN,matchup_a_CHA vs. NOH,matchup_a_CHA vs. NOP,matchup_a_CHA vs. NYK,matchup_a_CHA vs. OKC,matchup_a_CHA vs. ORL,matchup_a_CHA vs. PHI,matchup_a_CHA vs. PHX,matchup_a_CHA vs. POR,matchup_a_CHA vs. SAC,matchup_a_CHA vs. SAS,matchup_a_CHA vs. TOR,matchup_a_CHA vs. UTA,matchup_a_CHA vs. WAS,matchup_a_CHI vs. CLE,matchup_a_CHI vs. DAL,matchup_a_CHI vs. DEN,matchup_a_CHI vs. DET,matchup_a_CHI vs. GSW,matchup_a_CHI vs. HOU,matchup_a_CHI vs. IND,matchup_a_CHI vs. LAC,matchup_a_CHI vs. LAL,matchup_a_CHI vs. MEM,matchup_a_CHI vs. MIA,matchup_a_CHI vs. MIL,matchup_a_CHI vs. MIN,matchup_a_CHI vs. NJN,matchup_a_CHI vs. NOH,matchup_a_CHI vs. NOP,matchup_a_CHI vs. NYK,matchup_a_CHI vs. OKC,matchup_a_CHI vs. ORL,matchup_a_CHI vs. PHI,matchup_a_CHI vs. PHX,matchup_a_CHI vs. POR,matchup_a_CHI vs. SAC,matchup_a_CHI vs. SAS,matchup_a_CHI vs. TOR,matchup_a_CHI vs. UTA,matchup_a_CHI vs. WAS,matchup_a_CLE vs. DAL,matchup_a_CLE vs. DEN,matchup_a_CLE vs. DET,matchup_a_CLE vs. GSW,matchup_a_CLE vs. HOU,matchup_a_CLE vs. IND,matchup_a_CLE vs. LAC,matchup_a_CLE vs. LAL,matchup_a_CLE vs. MEM,matchup_a_CLE vs. MIA,matchup_a_CLE vs. MIL,matchup_a_CLE vs. MIN,matchup_a_CLE vs. NJN,matchup_a_CLE vs. NOH,matchup_a_CLE vs. NOP,matchup_a_CLE vs. NYK,matchup_a_CLE vs. OKC,matchup_a_CLE vs. ORL,matchup_a_CLE vs. PHI,matchup_a_CLE vs. PHX,matchup_a_CLE vs. POR,matchup_a_CLE vs. SAC,matchup_a_CLE vs. SAS,matchup_a_CLE vs. TOR,matchup_a_CLE vs. UTA,matchup_a_CLE vs. WAS,matchup_a_DAL vs. DEN,matchup_a_DAL vs. DET,matchup_a_DAL vs. GSW,matchup_a_DAL vs. HOU,matchup_a_DAL vs. IND,matchup_a_DAL vs. LAC,matchup_a_DAL vs. LAL,matchup_a_DAL vs. MEM,matchup_a_DAL vs. MIA,matchup_a_DAL vs. MIL,matchup_a_DAL vs. MIN,matchup_a_DAL vs. NJN,matchup_a_DAL vs. NOH,matchup_a_DAL vs. NOP,matchup_a_DAL vs. NYK,matchup_a_DAL vs. OKC,matchup_a_DAL vs. ORL,matchup_a_DAL vs. PHI,matchup_a_DAL vs. PHX,matchup_a_DAL vs. POR,matchup_a_DAL vs. SAC,matchup_a_DAL vs. SAS,matchup_a_DAL vs. TOR,matchup_a_DAL vs. UTA,matchup_a_DAL vs. WAS,matchup_a_DEN vs. DET,matchup_a_DEN vs. GSW,matchup_a_DEN vs. HOU,matchup_a_DEN vs. IND,matchup_a_DEN vs. LAC,matchup_a_DEN vs. LAL,matchup_a_DEN vs. MEM,matchup_a_DEN vs. MIA,matchup_a_DEN vs. MIL,matchup_a_DEN vs. MIN,matchup_a_DEN vs. NJN,matchup_a_DEN vs. NOH,matchup_a_DEN vs. NOP,matchup_a_DEN vs. NYK,matchup_a_DEN vs. OKC,matchup_a_DEN vs. ORL,matchup_a_DEN vs. PHI,matchup_a_DEN vs. PHX,matchup_a_DEN vs. POR,matchup_a_DEN vs. SAC,matchup_a_DEN vs. SAS,matchup_a_DEN vs. TOR,matchup_a_DEN vs. UTA,matchup_a_DEN vs. WAS,matchup_a_DET vs. GSW,matchup_a_DET vs. HOU,matchup_a_DET vs. IND,matchup_a_DET vs. LAC,matchup_a_DET vs. LAL,matchup_a_DET vs. MEM,matchup_a_DET vs. MIA,matchup_a_DET vs. MIL,matchup_a_DET vs. MIN,matchup_a_DET vs. NJN,matchup_a_DET vs. NOH,matchup_a_DET vs. NOP,matchup_a_DET vs. NYK,matchup_a_DET vs. OKC,matchup_a_DET vs. ORL,matchup_a_DET vs. PHI,matchup_a_DET vs. PHX,matchup_a_DET vs. POR,matchup_a_DET vs. SAC,matchup_a_DET vs. SAS,matchup_a_DET vs. TOR,matchup_a_DET vs. UTA,matchup_a_DET vs. WAS,matchup_a_GSW vs. HOU,matchup_a_GSW vs. IND,matchup_a_GSW vs. LAC,matchup_a_GSW vs. LAL,matchup_a_GSW vs. MEM,matchup_a_GSW vs. MIA,matchup_a_GSW vs. MIL,matchup_a_GSW vs. MIN,matchup_a_GSW vs. NJN,matchup_a_GSW vs. NOH,matchup_a_GSW vs. NOP,matchup_a_GSW vs. NYK,matchup_a_GSW vs. OKC,matchup_a_GSW vs. ORL,matchup_a_GSW vs. PHI,matchup_a_GSW vs. PHX,matchup_a_GSW vs. POR,matchup_a_GSW vs. SAC,matchup_a_GSW vs. SAS,matchup_a_GSW vs. TOR,matchup_a_GSW vs. UTA,matchup_a_GSW vs. WAS,matchup_a_HOU vs. IND,matchup_a_HOU vs. LAC,matchup_a_HOU vs. LAL,matchup_a_HOU vs. MEM,matchup_a_HOU vs. MIA,matchup_a_HOU vs. MIL,matchup_a_HOU vs. MIN,matchup_a_HOU vs. NJN,matchup_a_HOU vs. NOH,matchup_a_HOU vs. NOP,matchup_a_HOU vs. NYK,matchup_a_HOU vs. OKC,matchup_a_HOU vs. ORL,matchup_a_HOU vs. PHI,matchup_a_HOU vs. PHX,matchup_a_HOU vs. POR,matchup_a_HOU vs. SAC,matchup_a_HOU vs. SAS,matchup_a_HOU vs. TOR,matchup_a_HOU vs. UTA,matchup_a_HOU vs. WAS,matchup_a_IND vs. LAC,matchup_a_IND vs. LAL,matchup_a_IND vs. MEM,matchup_a_IND vs. MIA,matchup_a_IND vs. MIL,matchup_a_IND vs. MIN,matchup_a_IND vs. NJN,matchup_a_IND vs. NOH,matchup_a_IND vs. NOP,matchup_a_IND vs. NYK,matchup_a_IND vs. OKC,matchup_a_IND vs. ORL,matchup_a_IND vs. PHI,matchup_a_IND vs. PHX,matchup_a_IND vs. POR,matchup_a_IND vs. SAC,matchup_a_IND vs. SAS,matchup_a_IND vs. TOR,matchup_a_IND vs. UTA,matchup_a_IND vs. WAS,matchup_a_LAC vs. LAL,matchup_a_LAC vs. MEM,matchup_a_LAC vs. MIA,matchup_a_LAC vs. MIL,matchup_a_LAC vs. MIN,matchup_a_LAC vs. NJN,matchup_a_LAC vs. NOH,matchup_a_LAC vs. NOP,matchup_a_LAC vs. NYK,matchup_a_LAC vs. OKC,matchup_a_LAC vs. ORL,matchup_a_LAC vs. PHI,matchup_a_LAC vs. PHX,matchup_a_LAC vs. POR,matchup_a_LAC vs. SAC,matchup_a_LAC vs. SAS,matchup_a_LAC vs. TOR,matchup_a_LAC vs. UTA,matchup_a_LAC vs. WAS,matchup_a_LAL vs. MEM,matchup_a_LAL vs. MIA,matchup_a_LAL vs. MIL,matchup_a_LAL vs. MIN,matchup_a_LAL vs. NJN,matchup_a_LAL vs. NOH,matchup_a_LAL vs. NOP,matchup_a_LAL vs. NYK,matchup_a_LAL vs. OKC,matchup_a_LAL vs. ORL,matchup_a_LAL vs. PHI,matchup_a_LAL vs. PHX,matchup_a_LAL vs. POR,matchup_a_LAL vs. SAC,matchup_a_LAL vs. SAS,matchup_a_LAL vs. TOR,matchup_a_LAL vs. UTA,matchup_a_LAL vs. WAS,matchup_a_MEM vs. MIA,matchup_a_MEM vs. MIL,matchup_a_MEM vs. MIN,matchup_a_MEM vs. NJN,matchup_a_MEM vs. NOH,matchup_a_MEM vs. NOP,matchup_a_MEM vs. NYK,matchup_a_MEM vs. OKC,matchup_a_MEM vs. ORL,matchup_a_MEM vs. PHI,matchup_a_MEM vs. PHX,matchup_a_MEM vs. POR,matchup_a_MEM vs. SAC,matchup_a_MEM vs. SAS,matchup_a_MEM vs. TOR,matchup_a_MEM vs. UTA,matchup_a_MEM vs. WAS,matchup_a_MIA vs. MIL,matchup_a_MIA vs. MIN,matchup_a_MIA vs. NJN,matchup_a_MIA vs. NOH,matchup_a_MIA vs. NOP,matchup_a_MIA vs. NYK,matchup_a_MIA vs. OKC,matchup_a_MIA vs. ORL,matchup_a_MIA vs. PHI,matchup_a_MIA vs. PHX,matchup_a_MIA vs. POR,matchup_a_MIA vs. SAC,matchup_a_MIA vs. SAS,matchup_a_MIA vs. TOR,matchup_a_MIA vs. UTA,matchup_a_MIA vs. WAS,matchup_a_MIL vs. MIN,matchup_a_MIL vs. NJN,matchup_a_MIL vs. NOH,matchup_a_MIL vs. NOP,matchup_a_MIL vs. NYK,matchup_a_MIL vs. OKC,matchup_a_MIL vs. ORL,matchup_a_MIL vs. PHI,...,matchup_b_BKN vs. SAS,matchup_b_BKN vs. TOR,matchup_b_BKN vs. UTA,matchup_b_BKN vs. WAS,matchup_b_BOS vs. CHA,matchup_b_BOS vs. CHI,matchup_b_BOS vs. CLE,matchup_b_BOS vs. DAL,matchup_b_BOS vs. DEN,matchup_b_BOS vs. DET,matchup_b_BOS vs. GSW,matchup_b_BOS vs. HOU,matchup_b_BOS vs. IND,matchup_b_BOS vs. LAC,matchup_b_BOS vs. LAL,matchup_b_BOS vs. MEM,matchup_b_BOS vs. MIA,matchup_b_BOS vs. MIL,matchup_b_BOS vs. MIN,matchup_b_BOS vs. NJN,matchup_b_BOS vs. NOH,matchup_b_BOS vs. NOP,matchup_b_BOS vs. NYK,matchup_b_BOS vs. OKC,matchup_b_BOS vs. ORL,matchup_b_BOS vs. PHI,matchup_b_BOS vs. PHX,matchup_b_BOS vs. POR,matchup_b_BOS vs. SAC,matchup_b_BOS vs. SAS,matchup_b_BOS vs. TOR,matchup_b_BOS vs. UTA,matchup_b_BOS vs. WAS,matchup_b_CHA vs. CHI,matchup_b_CHA vs. CLE,matchup_b_CHA vs. DAL,matchup_b_CHA vs. DEN,matchup_b_CHA vs. DET,matchup_b_CHA vs. GSW,matchup_b_CHA vs. HOU,matchup_b_CHA vs. IND,matchup_b_CHA vs. LAC,matchup_b_CHA vs. LAL,matchup_b_CHA vs. MEM,matchup_b_CHA vs. MIA,matchup_b_CHA vs. MIL,matchup_b_CHA vs. MIN,matchup_b_CHA vs. NJN,matchup_b_CHA vs. NOH,matchup_b_CHA vs. NOP,matchup_b_CHA vs. NYK,matchup_b_CHA vs. OKC,matchup_b_CHA vs. ORL,matchup_b_CHA vs. PHI,matchup_b_CHA vs. PHX,matchup_b_CHA vs. POR,matchup_b_CHA vs. SAC,matchup_b_CHA vs. SAS,matchup_b_CHA vs. TOR,matchup_b_CHA vs. UTA,matchup_b_CHA vs. WAS,matchup_b_CHI vs. CLE,matchup_b_CHI vs. DAL,matchup_b_CHI vs. DEN,matchup_b_CHI vs. DET,matchup_b_CHI vs. GSW,matchup_b_CHI vs. HOU,matchup_b_CHI vs. IND,matchup_b_CHI vs. LAC,matchup_b_CHI vs. LAL,matchup_b_CHI vs. MEM,matchup_b_CHI vs. MIA,matchup_b_CHI vs. MIL,matchup_b_CHI vs. MIN,matchup_b_CHI vs. NJN,matchup_b_CHI vs. NOH,matchup_b_CHI vs. NOP,matchup_b_CHI vs. NYK,matchup_b_CHI vs. OKC,matchup_b_CHI vs. ORL,matchup_b_CHI vs. PHI,matchup_b_CHI vs. PHX,matchup_b_CHI vs. POR,matchup_b_CHI vs. SAC,matchup_b_CHI vs. SAS,matchup_b_CHI vs. TOR,matchup_b_CHI vs. UTA,matchup_b_CHI vs. WAS,matchup_b_CLE vs. DAL,matchup_b_CLE vs. DEN,matchup_b_CLE vs. DET,matchup_b_CLE vs. GSW,matchup_b_CLE vs. HOU,matchup_b_CLE vs. IND,matchup_b_CLE vs. LAC,matchup_b_CLE vs. LAL,matchup_b_CLE vs. MEM,matchup_b_CLE vs. MIA,matchup_b_CLE vs. MIL,matchup_b_CLE vs. MIN,matchup_b_CLE vs. NJN,matchup_b_CLE vs. NOH,matchup_b_CLE vs. NOP,matchup_b_CLE vs. NYK,matchup_b_CLE vs. OKC,matchup_b_CLE vs. ORL,matchup_b_CLE vs. PHI,matchup_b_CLE vs. PHX,matchup_b_CLE vs. POR,matchup_b_CLE vs. SAC,matchup_b_CLE vs. SAS,matchup_b_CLE vs. TOR,matchup_b_CLE vs. UTA,matchup_b_CLE vs. WAS,matchup_b_DAL vs. DEN,matchup_b_DAL vs. DET,matchup_b_DAL vs. GSW,matchup_b_DAL vs. HOU,matchup_b_DAL vs. IND,matchup_b_DAL vs. LAC,matchup_b_DAL vs. LAL,matchup_b_DAL vs. MEM,matchup_b_DAL vs. MIA,matchup_b_DAL vs. MIL,matchup_b_DAL vs. MIN,matchup_b_DAL vs. NJN,matchup_b_DAL vs. NOH,matchup_b_DAL vs. NOP,matchup_b_DAL vs. NYK,matchup_b_DAL vs. OKC,matchup_b_DAL vs. ORL,matchup_b_DAL vs. PHI,matchup_b_DAL vs. PHX,matchup_b_DAL vs. POR,matchup_b_DAL vs. SAC,matchup_b_DAL vs. SAS,matchup_b_DAL vs. TOR,matchup_b_DAL vs. UTA,matchup_b_DAL vs. WAS,matchup_b_DEN vs. DET,matchup_b_DEN vs. GSW,matchup_b_DEN vs. HOU,matchup_b_DEN vs. IND,matchup_b_DEN vs. LAC,matchup_b_DEN vs. LAL,matchup_b_DEN vs. MEM,matchup_b_DEN vs. MIA,matchup_b_DEN vs. MIL,matchup_b_DEN vs. MIN,matchup_b_DEN vs. NJN,matchup_b_DEN vs. NOH,matchup_b_DEN vs. NOP,matchup_b_DEN vs. NYK,matchup_b_DEN vs. OKC,matchup_b_DEN vs. ORL,matchup_b_DEN vs. PHI,matchup_b_DEN vs. PHX,matchup_b_DEN vs. POR,matchup_b_DEN vs. SAC,matchup_b_DEN vs. SAS,matchup_b_DEN vs. TOR,matchup_b_DEN vs. UTA,matchup_b_DEN vs. WAS,matchup_b_DET vs. GSW,matchup_b_DET vs. HOU,matchup_b_DET vs. IND,matchup_b_DET vs. LAC,matchup_b_DET vs. LAL,matchup_b_DET vs. MEM,matchup_b_DET vs. MIA,matchup_b_DET vs. MIL,matchup_b_DET vs. MIN,matchup_b_DET vs. NJN,matchup_b_DET vs. NOH,matchup_b_DET vs. NOP,matchup_b_DET vs. NYK,matchup_b_DET vs. OKC,matchup_b_DET vs. ORL,matchup_b_DET vs. PHI,matchup_b_DET vs. PHX,matchup_b_DET vs. POR,matchup_b_DET vs. SAC,matchup_b_DET vs. SAS,matchup_b_DET vs. TOR,matchup_b_DET vs. UTA,matchup_b_DET vs. WAS,matchup_b_GSW vs. HOU,matchup_b_GSW vs. IND,matchup_b_GSW vs. LAC,matchup_b_GSW vs. LAL,matchup_b_GSW vs. MEM,matchup_b_GSW vs. MIA,matchup_b_GSW vs. MIL,matchup_b_GSW vs. MIN,matchup_b_GSW vs. NJN,matchup_b_GSW vs. NOH,matchup_b_GSW vs. NOP,matchup_b_GSW vs. NYK,matchup_b_GSW vs. OKC,matchup_b_GSW vs. ORL,matchup_b_GSW vs. PHI,matchup_b_GSW vs. PHX,matchup_b_GSW vs. POR,matchup_b_GSW vs. SAC,matchup_b_GSW vs. SAS,matchup_b_GSW vs. TOR,matchup_b_GSW vs. UTA,matchup_b_GSW vs. WAS,matchup_b_HOU vs. IND,matchup_b_HOU vs. LAC,matchup_b_HOU vs. LAL,matchup_b_HOU vs. MEM,matchup_b_HOU vs. MIA,matchup_b_HOU vs. MIL,matchup_b_HOU vs. MIN,matchup_b_HOU vs. NJN,matchup_b_HOU vs. NOH,matchup_b_HOU vs. NOP,matchup_b_HOU vs. NYK,matchup_b_HOU vs. OKC,matchup_b_HOU vs. ORL,matchup_b_HOU vs. PHI,matchup_b_HOU vs. PHX,matchup_b_HOU vs. POR,matchup_b_HOU vs. SAC,matchup_b_HOU vs. SAS,matchup_b_HOU vs. TOR,matchup_b_HOU vs. UTA,matchup_b_HOU vs. WAS,matchup_b_IND vs. LAC,matchup_b_IND vs. LAL,matchup_b_IND vs. MEM,matchup_b_IND vs. MIA,matchup_b_IND vs. MIL,matchup_b_IND vs. MIN,matchup_b_IND vs. NJN,matchup_b_IND vs. NOH,matchup_b_IND vs. NOP,matchup_b_IND vs. NYK,matchup_b_IND vs. OKC,matchup_b_IND vs. ORL,matchup_b_IND vs. PHI,matchup_b_IND vs. PHX,matchup_b_IND vs. POR,matchup_b_IND vs. SAC,matchup_b_IND vs. SAS,matchup_b_IND vs. TOR,matchup_b_IND vs. UTA,matchup_b_IND vs. WAS,matchup_b_LAC vs. LAL,matchup_b_LAC vs. MEM,matchup_b_LAC vs. MIA,matchup_b_LAC vs. MIL,matchup_b_LAC vs. MIN,matchup_b_LAC vs. NJN,matchup_b_LAC vs. NOH,matchup_b_LAC vs. NOP,matchup_b_LAC vs. NYK,matchup_b_LAC vs. OKC,matchup_b_LAC vs. ORL,matchup_b_LAC vs. PHI,matchup_b_LAC vs. PHX,matchup_b_LAC vs. POR,matchup_b_LAC vs. SAC,matchup_b_LAC vs. SAS,matchup_b_LAC vs. TOR,matchup_b_LAC vs. UTA,matchup_b_LAC vs. WAS,matchup_b_LAL vs. MEM,matchup_b_LAL vs. MIA,matchup_b_LAL vs. MIL,matchup_b_LAL vs. MIN,matchup_b_LAL vs. NJN,matchup_b_LAL vs. NOH,matchup_b_LAL vs. NOP,matchup_b_LAL vs. NYK,matchup_b_LAL vs. OKC,matchup_b_LAL vs. ORL,matchup_b_LAL vs. PHI,matchup_b_LAL vs. PHX,matchup_b_LAL vs. POR,matchup_b_LAL vs. SAC,matchup_b_LAL vs. SAS,matchup_b_LAL vs. TOR,matchup_b_LAL vs. UTA,matchup_b_LAL vs. WAS,matchup_b_MEM vs. MIA,matchup_b_MEM vs. MIL,matchup_b_MEM vs. MIN,matchup_b_MEM vs. NJN,matchup_b_MEM vs. NOH,matchup_b_MEM vs. NOP,matchup_b_MEM vs. NYK,matchup_b_MEM vs. OKC,matchup_b_MEM vs. ORL,matchup_b_MEM vs. PHI,matchup_b_MEM vs. PHX,matchup_b_MEM vs. POR,matchup_b_MEM vs. SAC,matchup_b_MEM vs. SAS,matchup_b_MEM vs. TOR,matchup_b_MEM vs. UTA,matchup_b_MEM vs. WAS,matchup_b_MIA vs. MIL,matchup_b_MIA vs. MIN,matchup_b_MIA vs. NJN,matchup_b_MIA vs. NOH,matchup_b_MIA vs. NOP,matchup_b_MIA vs. NYK,matchup_b_MIA vs. OKC,matchup_b_MIA vs. ORL,matchup_b_MIA vs. PHI,matchup_b_MIA vs. PHX,matchup_b_MIA vs. POR,matchup_b_MIA vs. SAC,matchup_b_MIA vs. SAS,matchup_b_MIA vs. TOR,matchup_b_MIA vs. UTA,matchup_b_MIA vs. WAS,matchup_b_MIL vs. MIN,matchup_b_MIL vs. NJN,matchup_b_MIL vs. NOH,matchup_b_MIL vs. NOP,matchup_b_MIL vs. NYK,matchup_b_MIL vs. OKC,matchup_b_MIL vs. ORL,matchup_b_MIL vs. PHI,matchup_b_MIL vs. PHX,matchup_b_MIL vs. POR,matchup_b_MIL vs. SAC,matchup_b_MIL vs. SAS,matchup_b_MIL vs. TOR,matchup_b_MIL vs. UTA,matchup_b_MIL vs. WAS,matchup_b_MIN vs. NJN,matchup_b_MIN vs. NOH,matchup_b_MIN vs. NOP,matchup_b_MIN vs. NYK,matchup_b_MIN vs. OKC,matchup_b_MIN vs. ORL,matchup_b_MIN vs. PHI,matchup_b_MIN vs. PHX,matchup_b_MIN vs. POR,matchup_b_MIN vs. SAC,matchup_b_MIN vs. SAS,matchup_b_MIN vs. TOR,matchup_b_MIN vs. UTA,matchup_b_MIN vs. WAS,matchup_b_NJN vs. NOH,matchup_b_NJN vs. NYK,matchup_b_NJN vs. OKC,matchup_b_NJN vs. ORL,matchup_b_NJN vs. PHI,matchup_b_NJN vs. PHX,matchup_b_NJN vs. POR,matchup_b_NJN vs. SAC,matchup_b_NJN vs. SAS,matchup_b_NJN vs. TOR,matchup_b_NJN vs. UTA,matchup_b_NJN vs. WAS,matchup_b_NOH vs. NYK,matchup_b_NOH vs. OKC,matchup_b_NOH vs. ORL,matchup_b_NOH vs. PHI,matchup_b_NOH vs. PHX,matchup_b_NOH vs. POR,matchup_b_NOH vs. SAC,matchup_b_NOH vs. SAS,matchup_b_NOH vs. TOR,matchup_b_NOH vs. UTA,matchup_b_NOH vs. WAS,matchup_b_NOP vs. NYK,matchup_b_NOP vs. OKC,matchup_b_NOP vs. ORL,matchup_b_NOP vs. PHI,matchup_b_NOP vs. PHX,matchup_b_NOP vs. POR,matchup_b_NOP vs. SAC,matchup_b_NOP vs. SAS,matchup_b_NOP vs. TOR,matchup_b_NOP vs. UTA,matchup_b_NOP vs. WAS,matchup_b_NYK vs. OKC,matchup_b_NYK vs. ORL,matchup_b_NYK vs. PHI,matchup_b_NYK vs. PHX,matchup_b_NYK vs. POR,matchup_b_NYK vs. SAC,matchup_b_NYK vs. SAS,matchup_b_NYK vs. TOR,matchup_b_NYK vs. UTA,matchup_b_NYK vs. WAS,matchup_b_OKC vs. ORL,matchup_b_OKC vs. PHI,matchup_b_OKC vs. PHX,matchup_b_OKC vs. POR,matchup_b_OKC vs. SAC,matchup_b_OKC vs. SAS,matchup_b_OKC vs. TOR,matchup_b_OKC vs. UTA,matchup_b_OKC vs. WAS,matchup_b_ORL vs. PHI,matchup_b_ORL vs. PHX,matchup_b_ORL vs. POR,matchup_b_ORL vs. SAC,matchup_b_ORL vs. SAS,matchup_b_ORL vs. TOR,matchup_b_ORL vs. UTA,matchup_b_ORL vs. WAS,matchup_b_PHI vs. PHX,matchup_b_PHI vs. POR,matchup_b_PHI vs. SAC,matchup_b_PHI vs. SAS,matchup_b_PHI vs. TOR,matchup_b_PHI vs. UTA,matchup_b_PHI vs. WAS,matchup_b_PHX vs. POR,m

In [12]:
#cat drop
df_stat_cma5_12_999_diff = df_stat_cma5_12_999_diff.drop(columns=column_names_categorical_list)
p(df_stat_cma5_12_999_diff)

(10266, 280)

,game_id,game_date,season_year,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,spread_a
0,21000001,2010-10-26,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-8
1,21000002,2010-10-26,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14
2,21000003,2010-10-26,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,21000010,2010-10-27,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
4,21000015,2010-10-27,2010,-101.60,-106.80,-105.30,-107.70,3.80,0.90,-0.6580,-1.190,-16.70,-0.3960,-0.6950,-0.5540,-19.3870,-20.40,-0.4620,-5.320000e-01,-1.0,-0.1960,-1.073200e+02,-103.5,-86.250,-103.0,-0.5070,-240.0,0.0000,-240.0,-38.0,-91.0,-0.4180,-8.0,-20.0,-0.4000,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.000,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-4
10261,41700317,2018-05-28,2017,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000,7.7,5.3,-7.7,-5.3,24.1,24.6,0.011,0.86,2.7,0.034,-0.002,-0.005,-2.597,-3.8,-0.010,-0.005,0.0,0.002,0.00,0.0,0.00,-4.0,0.121,0.0,0.067,0.0,3.0,4.0,0.011,0.0,-5.0,0.036,-7.0,-9.0,0.092593,6.0,1.0,2.0,3.0,1.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,-0.7,-4.0,-7.7,-5.3,20.5,21.7,0.193,-3.11,1.0,0.034,-0.029,0.013,-2.597,-3.8,-0.008,0.018,0.0,0.003,7.48,5.0,4.17,4.0,0.076,0.0,0.0,0.0,3.0,4.0,0.014,-2.0,-4.0,-0.110,-3.0,0.0,0.003268,5.0,4.0,8.0,7.0,0.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,6.6,5.4,-0.3,3.0,18.1,13.9,0.089,-1.80,6.9,0.014,-0.029,0.012,3.969,5.0,-0.024,-0.022,0.0,0.000,2.26,2.0,1.67,-3.0,0.124,-25.0,0.0,-25.0,6.0,1.0,0.032,-2.0,-16.0,-0.022,-8.0,-12.0,0.058824,7.0,4.0,7.0,15.0,0.0,3.0,3.0,-5.0,-5.0,-1.0,0.0,-9
10262,41700401,2018-05-31,2017,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051,-9.4,-7.8,5.8,6.9,-11.7,-12.5,-0.019,-0.97,-1.4,0.047,0.001,0.033,-0.416,0.2,0.007,0.019,0.0,0.000,4.66,1.0,0.83,2.0,-0.019,0.0,-0.096,0.0,-7.0,-5.0,-0.016,1.0,-4.0,0.079,5.0,7.0,-0.111111,-1.0,1.0,-2.0,-3.0,-2.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-2.5,-2.4,-11.1,-5.6,-0.215,5.64,-1.4,0.047,-0.052,0.015,-0.416,0.2,0.061,0.036,0.0,-0.001,-10.94,-10.5,-8.75,-9.0,-0.019,25.0,0.0,25.0,2.0,3.0,0.070,1.0,-5.0,0.079,7.0,8.0,-0.094444,-1.0,-5.0,-10.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0,10

In [13]:
df_stat_cma5_12_999_diff.drop(columns=['game_id', 'game_date'], inplace=True)

In [14]:
df_features = df_stat_cma5_12_999_diff.drop(columns='spread_a')
p(df_features)

(10266, 277)

,season_year,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff
0,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2010,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010,-101.60,-106.80,-105.30,-107.70,3.80,0.90,-0.6580,-1.190,-16.70,-0.3960,-0.6950,-0.5540,-19.3870,-20.40,-0.4620,-5.320000e-01,-1.0,-0.1960,-1.073200e+02,-103.5,-86.250,-103.0,-0.5070,-240.0,0.0000,-240.0,-38.0,-91.0,-0.4180,-8.0,-20.0,-0.4000,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.000,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0
10261,2017,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000,7.7,5.3,-7.7,-5.3,24.1,24.6,0.011,0.86,2.7,0.034,-0.002,-0.005,-2.597,-3.8,-0.010,-0.005,0.0,0.002,0.00,0.0,0.00,-4.0,0.121,0.0,0.067,0.0,3.0,4.0,0.011,0.0,-5.0,0.036,-7.0,-9.0,0.092593,6.0,1.0,2.0,3.0,1.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,-0.7,-4.0,-7.7,-5.3,20.5,21.7,0.193,-3.11,1.0,0.034,-0.029,0.013,-2.597,-3.8,-0.008,0.018,0.0,0.003,7.48,5.0,4.17,4.0,0.076,0.0,0.0,0.0,3.0,4.0,0.014,-2.0,-4.0,-0.110,-3.0,0.0,0.003268,5.0,4.0,8.0,7.0,0.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,6.6,5.4,-0.3,3.0,18.1,13.9,0.089,-1.80,6.9,0.014,-0.029,0.012,3.969,5.0,-0.024,-0.022,0.0,0.000,2.26,2.0,1.67,-3.0,0.124,-25.0,0.0,-25.0,6.0,1.0,0.032,-2.0,-16.0,-0.022,-8.0,-12.0,0.058824,7.0,4.0,7.0,15.0,0.0,3.0,3.0,-5.0,-5.0,-1.0,0.0
10262,2017,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051,-9.4,-7.8,5.8,6.9,-11.7,-12.5,-0.019,-0.97,-1.4,0.047,0.001,0.033,-0.416,0.2,0.007,0.019,0.0,0.000,4.66,1.0,0.83,2.0,-0.019,0.0,-0.096,0.0,-7.0,-5.0,-0.016,1.0,-4.0,0.079,5.0,7.0,-0.111111,-1.0,1.0,-2.0,-3.0,-2.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-2.5,-2.4,-11.1,-5.6,-0.215,5.64,-1.4,0.047,-0.052,0.015,-0.416,0.2,0.061,0.036,0.0,-0.001,-10.94,-10.5,-8.75,-9.0,-0.019,25.0,0.0,25.0,2.0,3.0,0.070,1.0,-5.0,0.079,7.0,8.0,-0.094444,-1.0,-5.0,-10.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0
10263,2017,-4.60,-3.98,3.72,4.32,-8.32,-8.34,-0.1340,-0.676,-4.22,-0.0048,0.0666,0.0312,-0.3668,-0.24,-0.0276,-2.460000e-02,0.0,-0.0010,-4.640000e-01,-0.9,-0.752,-0.6,-0.0694,0.0,-0.2000,0.0,-1.6,-2.2,-0.0070,-3.8,-2.8,-0.0758,2.6,5.4,-0.062235,0.0,1.4,1.4,-6.6,-3.8,0.8,-0.4,-0.4,-4.4,7.4,-0.2,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-1.901545,-0.857465,5.452475,4.759653,-7.349000,-5.623109,-0.107564,-0.197637,-3.449980,0.004219,0.014580,-0.003960,-1.280636,-1.171089,-0.020696,-0.018612,0.0,-0.000144,-2.523637,-2.570218,-2.142013,-2.408911,-0.055020,0.240099,-0.148643,0.240099,-2.717525,-1.399802,-0.024299,0.413564,2.571386,-0.015929,1.359802,2.857426,-0.044027,-0.075248,-1.933762,-2.009010,-6.185050,-1.188614,-3.159208,-1.510693,-0.718020,-3.661683,5.618812,-0.014950,-4.3,-5.5,8.5,12.4,-24.7,-18.8,-0.126,-2.38,-7.6,0.047,0.014,0.033,-0.416,0.2,-0.032,-0.036,0.0,-0.001,5.06,4.0,3.33,2.0,-0.129,0.0,-0.429,0.0,-2.0,9.0,-0.005,-6.0,-2.0,-0.030,1.0,6.0,-0.131818,3.0,2.0,4.0,-13.0,-3.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-1.7,2.0,-11.1,-5.6,-0.215,4.45,-1.4,0.047,-0.052,0.033,-0.416,0.2,0.061,0.036,0.0,-0.002,-10.94,-10.5,-8.75,-8.0,-0.019,0.0,0.0,0.0,2.0,3.0,0.070,1.0,-3.0,0.079,3.0,3.0,-0.100000,3.0,-3.0,1.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0

In [15]:
df_target = df_stat_cma5_12_999_diff[['spread_a']]
p(df_target)

(10266, 1)

       spread_a
0            -8
1            14
2             2
3             4
4            -4
10261        -9
10262        10
10263        19
10264         8
10265        23

In [16]:
scaler = StandardScaler() 
scaler

StandardScaler()

In [17]:
# Fitting data to the scaler object
scaled_df_features = scaler.fit_transform(df_features) 
scaled_df_features

array([[-1.55738154e+00, -5.72990536e-03, -1.92885051e-03, ...,
        -2.83384565e-02,  1.88694546e-02,  8.89911843e-04],
       [-1.55738154e+00, -5.72990536e-03, -1.92885051e-03, ...,
        -2.83384565e-02,  1.88694546e-02,  8.89911843e-04],
       [-1.55738154e+00, -5.72990536e-03, -1.92885051e-03, ...,
        -2.83384565e-02,  1.88694546e-02,  8.89911843e-04],
       ...,
       [ 1.50706227e+00, -4.54557206e-01, -3.91144277e-01, ...,
        -2.74188536e-01, -4.74878601e-01,  8.89911843e-04],
       [ 1.50706227e+00, -1.04583839e+00, -1.10894358e+00, ...,
        -2.74188536e-01, -4.74878601e-01,  8.89911843e-04],
       [ 1.50706227e+00, -1.10828393e+00, -1.10894358e+00, ...,
        -2.74188536e-01, -4.74878601e-01,  8.89911843e-04]])

In [18]:
scaled_df_features = pd.DataFrame(scaled_df_features, columns=df_features.columns)
p(scaled_df_features)

(10266, 277)

,season_year,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff
0,-1.557382,-0.005730,-0.001929,0.014070,0.013248,-0.017154,-0.013702,-0.150182,-0.094567,-0.110076,0.033535,-0.031645,-0.021132,0.035235,0.036656,-0.019367,-0.013987,-0.006580,-0.007497,-0.021274,-0.023063,-0.023064,-0.020779,-0.019354,-0.003544,-0.047487,-0.003545,0.017555,-0.001756,0.017442,-0.110797,-0.139016,-0.001501,0.002744,-0.010752,0.015783,0.055256,-0.047500,-0.006144,-0.110448,0.018268,0.065962,0.031699,0.118089,-0.015272,0.016283,-0.001937,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.020129,-0.016556,0.023406,0.021431,-0.042845,-0.039299,-0.187685,-0.127006,-0.146191,0.035462,-0.026867,-0.029662,0.030398,0.031400,-0.041311,-0.030891,-0.006580,-0.008044,-0.031536,-0.032130,-0.032135,-0.029435,-0.048615,-0.002329,-0.049286,-0.002329,0.000716,-0.004775,-0.000452,-0.132651,-0.152585,-0.008676,-0.002646,-0.028478,0.033599,0.059791,-0.078879,-0.028412,-0.153264,0.028046,0.069342,0.020868,0.150282,-0.035511,0.042704,0.014355,-0.021850,-0.015143,0.015482,0.014742,-0.020620,-0.021002,-0.133044,-0.070689,-0.104554,0.049191,-0.000208,0.026909,0.030249,0.030814,-0.029795,-0.022353,-0.006580,-0.007625,-0.024029,-0.022503,-0.022497,-0.015680,-0.008393,0.002126,-0.053290,0.002126,-0.005746,-0.002164,0.009112,-0.099422,-0.126377,0.018099,0.001406,-0.011497,0.007959,0.035583,-0.035609,-0.015201,-0.102891,0.005836,0.055541,0.026842,0.100533,-0.034297,-0.004703,0.00357,-0.031399,-0.024140,0.012026,0.015847,-0.031080,-0.031020,-0.133245,-0.084142,-0.119993,0.053584,0.003117,0.032403,0.044253,0.043860,-0.048745,-0.042261,-0.006580,-0.005576,-0.020172,-0.017197,-0.017187,-0.013603,-0.016367,-0.000707,-0.058286,-0.000707,-0.018258,0.002303,-0.000443,-0.110475,-0.139808,0.039308,0.004417,-0.008846,0.001855,0.037901,-0.049817,-0.019899,-0.122364,0.007512,0.052107,0.039270,0.104586,-0.049045,0.001918,0.00089,-0.037081,-0.021951,0.036225,0.039149,-0.053350,-0.042011,-0.121054,-0.059950,-0.148628,0.039688,0.017082,0.011801,0.022555,0.020869,-0.087719,-0.067270,-0.006580,-0.003876,-0.028242,-0.028304,-0.028294,-0.054187,-0.067481,-0.011873,-0.05399,-0.011873,-0.042387,-0.014049,-0.041143,-0.085115,-0.130945,0.076467,0.017158,0.015688,0.004473,0.047190,-0.069322,-0.017250,-0.162600,0.016281,0.047090,0.041205,0.110128,-0.028338,0.018869,0.00089
1,-1.557382,-0.005730,-0.001929,0.014070,0.013248,-0.017154,-0.013702,-0.150182,-0.094567,-0.110076,0.033535,-0.031645,-0.021132,0.035235,0.036656,-0.019367,-0.013987,-0.006580,-0.007497,-0.021274,-0.023063,-0.023064,-0.020779,-0.019354,-0.003544,-0.047487,-0.003545,0.017555,-0.001756,0.017442,-0.110797,-0.139016,-0.001501,0.002744,-0.010752,0.015783,0.055256,-0.047500,-0.006144,-0.110448,0.018268,0.065962,0.031699,0.118089,-0.015272,0.016283,-0.001937,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.020129,-0.016556,0.023406,0.021431,-0.042845,-0.039299,-0.187685,-0.127006,-0.146191,0.035462,-0.026867,-0.029662,0.030398,0.031400,-0.041311,-0.030891,-0.006580,-0.008044,-0.031536,-0.032130,-0.032135,-0.029435,-0.048615,-0.002329,-0.049286,-0.002329,0.000716,-0.004775,-0.000452,-0.132651,-0.152585,-0.008676,-0.002646,-0.028478,0.033599,0.059791,-0.078879,-0.028412,-0.153264,0.028046,0.069342,0.020868,0.150282,-0.035511,0.042704,0.014355,-0.021850,-0.015143,0.015482,0.014742,-0.020620,-0.021002,-0.133044,-0.070689,-0.104554,0.049191,-0.000208,0.026909,0.030249,0.030814,-0.029795,-0.022353,-0.006580,-0.007625,-0.024029,-0.022503,-0.022497,-0.015680,-0.008393,0.002126,-0.053290,0.002126,-0.005746,-0.002164,0.009112,-0.099422,-0.126377,0.018099,0.001406,-0.011497,0.007959,0.035583,-0.035609,-0.015201,-0.102891,0.005836,0.055541,0.026842,0.100533,-0.034297,-0.004703,0.00357,-0.031399,-0.024140,0.012026,0.015847,-0.031080,-0.031020,-0.133245,-0.084142,-0.119993,0.053584,0.003117,0.032403,0.044253,0.043860,-0.048745,-0.042261,-0.006580,-0.005576,-0.020172,-0.017197,-0.017187,-0.013603,-0.016367,-0.000707,-0.058286,-0.000707,-0.018258,0.002303,-0.000443,-0.110475,-0.139808,0.039308,0.004417,-0.008846,0.001855,0.037901,-0.049817,-0.019899,-0.122364,0.007512,0.052107,0.039270,0.104586,-0.049045,0.001918,0.00089,-0.037081,-0.021951,0.036225,0.039149,-0.053350,-0.042011,-0.121054,-0.059950,-0.148628,0.039688,0.017082,0.011801,0.022555,0.020869,-0.087719,-0.067270,-0.006580,-0.003876,-0.028242,-0.028304,-0.028294,-0.054187,-0.067481,-0.011873,-0.05399,-0.011873,-0.042387,-0.014049,-0.041143,-0.085115,-0.130945,0.076467,0.017158,0.015688,0.004473,0.047190,-0.069322,-0.017250,-0.162600,0.016281,0.047090,0.041205,0.110128,-0.028338,0.018869,0.00089
2,-1.557382,-0.005730,-0.001929,0.014070,0.013248,-0.017154,-0.013702,-0.150182,-0.094567,-0.110076,0.033535,-0.031645,-0.021132,0.035235,0.036656,-0.019367,-0.013987,-0.006580,-0.007497,-0.021274,-0.023063,-0.023064,-0.020779,-0.019354,-0.003544,-0.047487,-0.003545,0.017555,-0.001756,0.017442,-0.110797,-0.139016,-0.001501,0.002744,-0.010752,0.015783,0.055256,-0.047500,-0.006144,-0.110448,0.018268,0.065962,0.031699,0.118089,-0.015272,0.016283,-0.001937,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.020129,-0.016556,0.023406,0.021431,-0.042845,-0.039299,-0.187685,-0.127006,-0.146191,0.035462,-0.026867,-0.029662,0.030398,0.031400,-0.041311,-0.030891,-0.006580,-0.008044,-0.031536,-0.032130,-0.032135,-0.029435,-0.048615,-0.002329,-0.049286,-0.002329,0.000716,-0.004775,-0.000452,-0.132651,-0.152585,-0.008676,-0.002646,-0.028478,0.033599,0.059791,-0.078879,-0.028412,-0.153264,0.028046,0.069342,0.020868,0.150282,-0.035511,0.042704,0.014355,-0.021850,-0.015143,0.015482,0.014742,-0.020620,-0.021002,-0.133044,-0.070689,-0.104554,0.049191,-0.000208,0.026909,0.030249,0.030814,-0.029795,-0.022353,-0.006580,-0.007625,-0.024029,-0.022503,-0.022497,-0.015680,-0.008393,0.002126,-0.053290,0.002126,-0.005746,-0.002164,0.009112,-0.099422,-0.126377,0.018099,0.001406,-0.011497,0.007959,0.035583,-0.035609,-0.015201,-0.102891,0.005836,0.055541,0.026842,0.100533,-0.034297,-0.004703,0.00357,-0.031399,-0.024140,0.012026,0.015847,-0.031080,-0.031020,-0.133245,-0.084142,-0.119993,0.053584,0.003117,0.032403,0.044253,0.043860,-0.048745,-0.042261,-0.006580,-0.005576,-0.020172,-0.017197,-0.017187,-0.013603,-0.016367,-0.000707,-0.058286,-0.000707,-0.018258,0.002303,-0.000443,-0.110475,-0.139808,0.039308,0.004417,-0.008846,0.001855,0.037901,-0.049817,-0.019899,-0.122364,0.007512,0.052107,0.039270,0.104586,-0.049045,0.001918,0.00089,-0.037081,-0.021951,0.036225,0.039149,-0.053350,-0.042011,-0.121054,-0.059950,-0.148628,0.039688,0.017082,0.011801,0.022555,0.020869,-0.087719,-0.067270,-0.006580,-0.003876,-0.028242,-0.028304,-0.028294,-0.054187,-0.067481,-0.011873,-0.05399,-0.011873,-0.042387,-0.014049,-0.041143,-0.085115,-0.130945,0.076467,0.017158,0.015688,0.004473,0.047190,-0.069322,-0.017250,-0.162600,0.016281,0.047090,0.041205,0.110128,-0.028338,0.018869,0.00089
3,-1.557382,-0.005730,-0.001929,0.014070,0.013248,-0.017154,-0.013702,-0.150182,-0.094567,-0.110076,0.033535,-0.031645,-0.021132,0.035235,0.036656,-0.019367,-0.013987,-0.006580,-0.007497,-0.021274,-0.023063,-0.023064,-0.020779,-0.019354,-0.003544,-0.047487,-0.003545,0.017555,-0.001756,0.017442,-0.110797,-0.139016,-0.001501,0.002744,-0.010752,0.015783,0.055256,-0.047500,-0.006144,-0.110448,0.018268,0.065962,0.031699,0.118089,-0.015272,0.016283,-0.001937,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.020129,-0.016556,0.023406,0.021431,-0.042845,-0.039299,-0.187685,-0.127006,-0.146191,0.035462,-0.026867,-0.029662,0.030398,0.031400,-0.041311,-0.030891,-0.006580,-0.008044,-0.031536,-0.032130,-0.032135,-0.029435,-0.048615,-0.002329,-0.049286,-0.002329,0.000716,-0.004775,-0.000452,-0.132651,-0.152585,-0.008676,-0.002646,-0.028478,0.033599,0.059791,-0.078879,-0.028412,-0.153264,0.028046,0.069342,0.020868,0.150282,-0.035511,0.042704,0.014355,-0.021850,-0.015143,0.015482,0.014742,-0.020620,-0.021002,-0.133044,-0.070689,-0.104554,0.049191,-0.000208,0.026909,0.030249,0.030814,-0.029795,-0.022353,-0.006580,-0.007625,-0.024029,-0.022503,-0.022497,-0.015680,-0.008393,0.002126,-0.053290,0.002126,-0.005746,-0.002164,0.009112,-0.099422,-0.126377,0.018099,0.001406,-0.011497,0.007959,0.035583,-0.035609,-0.015201,-0.102891,0.005836,0.055541,0.026842,0.100533,-0.034297,-0.004703,0.00357,-0.031399,-0.024140,0.012026,0.015847,-0.031080,-0.031020,-0.133245,-0.084142,-0.119993,0.053584,0.003117,0.032403,0.044253,0.043860,-0.048745,-0.042261,-0.006580,-0.005576,-0.020172,-0.017197,-0.017187,-0.013603,-0.016367,-0.000707,-0.058286,-0.000707,-0.018258,0.002303,-0.000443,-0.110475,-0.139808,0.039308,0.004417,-0.008846,0.001855,0.037901,-0.049817,-0.019899,-0.122364,0.007512,0.052107,0.039270,0.104586,-0.049045,0.001918,0.00089,-0.037081,-0.021951,0.036225,0.039149,-0.053350,-0.042011,-0.121054,-0.059950,-0.148628,0.039688,0.017082,0.011801,0.022555,0.020869,-0.087719,-0.067270,-0.006580,-0.003876,-0.028242,-0.028304,-0.028294,-0.054187,-0.067481,-0.011873,-0.05399,-0.011873,-0.042387,-0.014049,-0.041143,-0.085115,-0.130945,0.076467,0.017158,0.015688,0.004473,0.047190,-0.069322,-0.017250,-0.162600,0.016281,0.047090,0.041205,0.110128,-0.028338,0.018869,0.00089
4,-1.557382,-9.918959,-10.446202,-10.475246,-10.785638,0.308881,0.067157,-7.492594,-2.442125,-6.164947,-4.492728,-4.236415,-3.928597,-6.691006,-6.880317,-8.179451,-9.607591,-16.893824,-16.654055,-15.065255,-14.842574,-14.842516,-14.344535,-6.221344,-15.991513,-0.047487,-15.991515,-8.844703,-12.421651,-8.638008,-2.793744,-3.149681,-5.323434,-5.547953,-4.766837,-10.484708,-5.161019,-8.695014,-9.654661,-6.040659,-2.627929,-3.430668,-6.863152,-7.047670,-10.075809,-0.170060,-0.001937,-11.374689,-11.956212,-12.125088,-12.430145,0.371969,0.073498,-8.558801,-3.098099,-7.129325,-5.639774,-5.899071,-5.340411,-8.211836,-8.436224,-9.571133,-11.026144,-16.893824,-16.721528,-15.635715,-15.410366,-15.410292,-15.103783,-7.392598,-16.443273,-0.047253,-16.443276,-10.365925,-13.680912,-10.147737,-3.188432,-3.413331,-6.883285,-6.734089,-5.730942,-12.303815,-6.241787,-10.450073,-11.449063,-7.009372,-3.207138,-4.213505,-8.322027,-8.219411,-11.478206,-0.199719,0.000029,-12.389863,-13.060319,-13.387304,-13.662886,0.422677,0.076836,-9.468716,-3.845803,-7.812565,-6.683038,-7.817194,-6.919640,-9.422204,-9.667463,-10.469963,-11.880171,-16.893824,-16.753349,-16.203924,-15.956599,-15.956458,-15.718493,-8.157800,-16.688231,-0.049286,-16.688231,-11.541243,-14.703916,-11.051441,-3.573199,-3.701781,-8.304352,-7.698296,-6.544597,-13.633882,-7.166129,-11.752370,-12.830605,-7.769435,-3.665232,-4.789135,-9.425921,-9.074114,-12.528800,-0.223530,0.014355,-7.996336,-8.500195,-8.262964,-8.567455,0.232415,0.039567,-6.354284,-1.086909,-4.926584,-4.694611,-7.828833,-7.116898,-4.724174,-4.837708,-6.228685,-7.566770,-16.893824,-16.612795,-13.497709,-13.286966,-13.286765,-10.945095,-4.916053,-9.698697,-0.053290,-9.698697,-6.777271,-9.404556,-6.663758,-2.003655,-2.576818,-3.619922,-3.713463,-3.180095,-9.148978,-3.433048,-6.421758,-7.157348,-4.504780,-1.756237,-2.082250,-4.736531,-4.901744,-8.008289,-0.144848,0.00357,-8.728867,-9.265172,-9.055183,-9.365947,0.249061,0.034697,-6.985464,-0.978343,-5.405526,-5.335481,-8.787222,-8.904923,-5.150086,-5.274527,-6.854930,-8.349853,-16.893824,-16.675908,-13.834724,-13.607081,-13.606732,-10.535893,-5.326116,-8.294654,-0.058286,-8.294654,-7.453163,-9.517914,-7.374240,-2.076475,-2.637891,-3.952320,-3.991762,-3.367950,-10.323229,-3.689968,-7.045297,-7.731429,-4.849845,-1.881162,-2.198193,-5.073586,-5.114528,-8.588204,-0.151350,0.00089,-9.376728,-10.054777,-9.706923,-10.233642,0.247655,0.028104,-7.933974,-0.885961,-5.796779,-6.129416,-9.536642,-9.687198,-5.656827,-5.780865,-7.452552,-9.048790,-16.893824,-16.706247,-14.382423,-13.954370,-13.954211,-10.198835,-5.454626,-8.115401,-0.05399,-8.115401,-8.132184,-9.538359,-8.086401,-2.167438,-2.706435,-4.259750,-4.203887,-3.400524,-11.869492,-4.067032,-7.880519,-8.457857,-5.144258,-1.942408,-2.231696,-5.473969,-5.308672,-9.042841,-0.145713,0.00089

In [19]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df_features, 
                                                    df_target, test_size=0.3, 
                                                    random_state=random_state_2909)

In [20]:
X_train.shape

(7186, 277)

In [21]:
y_train.shape

(7186, 1)

In [22]:
X_test.shape

(3080, 277)

In [23]:
y_test.shape

(3080, 1)

In [24]:
#export dataframes

#https://stackoverflow.com/questions/30829748/multiple-pandas-dataframe-to-one-csv-file

In [25]:
df_train = pd.concat([X_train, y_train], axis=1)
p(df_train)

(7186, 278)

,season_year,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,spread_a
3134,-0.681826,-0.208678,-0.213161,0.966377,0.787318,-1.015850,-0.903150,0.151102,1.759807,0.042202,-1.068313,-0.803628,-1.626437,-1.136818,-1.150080,-0.687010,-0.554980,-0.00658,0.060448,-0.476014,-0.323749,-0.323405,-0.354536,-1.110513,-0.003544,-1.218960,-0.003545,-0.355593,0.353099,-0.699014,-0.177871,-0.289549,0.014465,-0.253442,-0.690193,0.557528,-0.009948,-0.608420,-0.479468,-0.063006,-1.304830,-1.632401,-1.209374,-0.111216,-0.435985,0.985267,-0.639802,-0.376770,-0.355536,0.800750,0.692448,-1.089342,-1.017284,-0.448620,0.594500,-0.583000,-0.590909,0.342986,-0.234494,-1.076958,-1.089729,-0.940024,-0.698561,-0.00658,0.062981,-0.547169,-0.475748,-0.475523,-0.705987,-0.999528,-0.289282,-1.249473,-0.289282,-0.804030,-0.027771,-0.815858,-0.801194,-0.766357,-0.262801,-0.086053,-0.695343,1.105986,-0.030841,-0.639680,-0.508504,-0.863614,-1.684980,-0.991951,-1.148502,-0.284695,-0.865912,1.032158,-1.671873,-0.727736,-0.649936,0.610777,0.446572,-1.318376,-1.141290,-0.743136,-0.704513,-1.071664,-0.553933,-0.425463,-1.127084,-0.326194,-0.276681,-0.908559,-0.710666,-0.00658,0.019296,-0.406310,-0.362682,-0.362696,-0.428516,-1.422858,-0.071853,-0.851137,-0.071853,-1.153480,-0.072617,-1.155782,0.220006,0.113604,0.256370,-0.269033,-0.861610,1.176166,-0.373764,-1.082168,-1.028432,-1.286550,-0.279727,-1.929574,-0.470365,0.570915,-0.907770,1.139590,-0.432741,-0.948021,-0.531555,0.817383,0.684105,-0.892924,-0.310389,0.727341,1.876355,0.501809,-1.651869,0.134962,-0.888633,-0.849909,-0.876068,-0.298146,-0.617965,-0.00658,0.161815,-1.076111,-0.791457,-0.791440,-0.652345,-0.589181,0.002126,-1.186036,0.002126,0.350651,0.101159,-0.246308,-0.099422,-0.616465,0.018099,1.001563,0.441160,0.585126,-0.397996,-0.380806,-1.093261,0.601411,-1.168879,-1.776852,-1.164001,2.101443,-0.469242,1.326674,0.00357,-1.041538,-0.586562,0.632006,0.895663,-0.996829,-0.344999,0.220821,1.508889,0.196506,-0.586027,-0.692521,-0.725818,-1.362642,-1.337878,-0.343385,-0.698124,-0.00658,0.164530,-0.710127,-0.805017,-0.804986,-1.035185,-0.780887,-0.864660,-1.148005,-0.864660,0.373053,-0.416168,-0.282694,-1.093475,-1.014137,0.488366,0.772912,0.471026,1.009039,-0.195090,-0.995153,-1.183904,-0.311463,-0.936825,-1.555250,-1.750230,0.104586,-0.514818,0.001918,0.00089,-1.121804,-0.632563,-0.000786,0.506528,-1.091025,-0.377001,-0.227918,1.411599,-0.317734,0.039688,0.910596,-0.023213,1.371581,1.357543,-0.406542,-0.776338,-0.00658,0.081340,-0.745148,-0.768337,-0.767781,-0.743629,-0.843145,-0.011873,0.942096,-0.011873,0.383392,-1.479327,-0.349096,0.175175,0.384154,0.293278,0.828898,-0.228327,1.479937,-0.724227,-1.124890,-1.609818,-0.760399,0.342729,-0.603992,0.316964,0.110128,-0.520039,0.265743,0.00089,8
8383,1.069285,0.105501,0.238641,0.167475,0.037312,-0.049757,0.182156,-0.942449,-0.769243,-0.733691,0.614177,1.115441,1.039667,0.489804,0.518132,0.008893,0.058145,-0.00658,-0.024483,-0.035572,-0.016763,-0.017222,-0.326723,0.049149,-0.336627,0.155350,-0.336627,0.390702,-0.220127,0.572385,-1.720565,-1.283068,-0.983397,0.301628,0.362940,0.014940,0.642086,-0.000757,0.357951,-0.679748,-0.599178,-2.032016,0.514338,1.436588,-0.033564,-0.132791,-0.639802,-0.084139,-0.008774,0.606608,0.501749,-0.635103,-0.489904,-0.858697,-0.253461,-0.691291,0.707439,0.243057,0.565180,0.140630,0.150274,-0.203410,-0.197004,-0.00658,0.070087,-0.354422,-0.321515,-0.321811,-0.181322,-0.468385,0.138827,0.157016,0.138827,0.379824,0.097488,0.249831,-1.374131,-1.064990,-0.768542,-0.129223,-0.167966,0.028900,0.494954,-0.311887,0.031326,-0.611363,-0.520977,-1.298766,0.279239,1.218725,-0.137022,0.440093,-0.417947,0.115400,0.200899,0.164728,0.066475,-0.044939,0.144723,-0.950591,-0.275645,-0.579667,1.020149,-0.074992,0.363323,0.014839,0.040881,-0.029708,-0.115277,-0.00658,0.026101,-0.557008,-0.545166,-0.545256,-0.683276,-0.094728,-0.178209,0.648518,-0.178209,0.239494,-0.130111,0.290712,-0.942138,-0.855332,-0.382546,-0.715555,-0.712187,-0.141790,0.604154,-0.606724,-0.141382,-0.725125,-0.334687,-1.420013,-0.127340,0.214288,-0.344270,-0.174404,-0.676311,-0.218073,0.000747,0.778074,0.644262,0.625285,0.470283,-0.123589,-0.651386,-0.104554,1.438790,0.855871,1.664569,0.913105,0.842234,-0.365233,-0.518697,-0.00658,-0.177066,-0.493574,0.169736,0.169739,-0.015680,0.688553,-1.008376,0.169719,-1.008376,-0.362142,0.101159,0.025076,-1.289568,-1.474119,-0.282038,-0.284353,-0.124661,-0.086408,0.902740,0.482187,0.928102,-0.455042,-0.581522,-1.166054,1.455854,1.301079,-0.469242,-0.004703,0.00357,-0.202609,0.252745,-0.375461,-0.410994,0.042641,0.268356,-0.476897,0.051116,0.196506,1.632199,0.268724,2.016683,1.008797,0.878116,-0.417045,-0.588813,-0.00658,-0.090628,-0.220980,-0.082849,-0.083362,0.599346,0.392075,0.863246,0.156252,0.863246,1.155674,0.002303,0.017197,-1.093475,-1.388850,0.039308,0.772912,0.231090,0.020143,0.037901,0.139250,0.998605,0.255835,0.637070,-0.590836,1.061842,1.148408,0.028583,0.308455,0.00089,0.459318,0.851693,-0.232105,-0.189771,0.968483,1.142140,-0.394150,-0.066891,-0.858874,1.441758,1.130537,1.272321,0.093449,-0.178210,0.247047,-0.489334,-0.00658,0.081340,-0.343895,-0.566510,-0.565956,-0.054187,0.325663,-0.011873,0.903360,-0.011873,1.234949,-0.014049,0.016598,0.175175,-1.289916,0.369161,-0.632233,-0.472343,-0.549091,0.047190,0.352905,0.619776,-0.162600,-0.310167,-1.255073,-0.234553,0.110128,0.053612,0.348035,0.00089,-20
7423,0.631507,0.649948,0.721738,1.241310,1.392938,-0.494194,-0.583308,0.282774,0.572219,0.607807,0.842776,-1.470341,-0.145268,-0.364447,-0.343099,0.683601,0.728976,-0.00658,-0.041469,0.021621,-0.112983,-0.112754,0.229539,-0.322726,0.329538,0.339682,0.329538,0.717206,0.462284,0.352892,1.431898,0.764184,1.241171,-0.253442,-0.860053,1.497693,-0.596779,0.419933,-0.006144,0.696061,-1.128417,1.564517,-0.244095,-0.512498,0.844447,0.538044,0.635929,0.556110,0.547723,0.560475,0.683780,0.017205,-0.111224,0.252549,0.728169,0.622166,0.229666,-1.268548,-0.368039,-0.561384,-0.570175,0.448871,0.380389,-0.00658,-0.008080,-0.414064,-0.477483,-0.477456,-0.144717,0.089375,0.281530,0.373883,0.281530,0.584722,0.423159,0.227545,0.949448,0.943996,0.288787,-0.712005,-1.120647,0.844477,0.002022,0.788563,0.607145,0.626962,-1.908827,0.797801,-0.521689,-0.173330,0.418323,-0.008731,0.835980,0.188366,0.051295,-0.167099,-0.123805,0.351046,0.180425,-0.529337,1.027957,-0.368710,-0.633984,-0.227074,-0.579817,-1.304364,-1.362547,-0.161072,-0.036150,-0.00658,0.034674,-0.836887,-0.784953,-0.784989,-0.598523,0.132433,0.190795,0.591129,0.190795,-0.648941,-0.269503,-0.434839,0.643862,0.865343,-0.216644,-0.257523,-0.794510,1.055282,-0.661547,0.008760,-0.347124,-0.817563,-1.254342,-0.374090,-1.507675,-0.305813,-0.414096,-0.212437,0.221344,0.794436,0.755503,1.312675,0.970976,-0.540007,-0.646886,0.065506,0.347755,0.530684,0.097109,0.574266,-0.411519,-0.921763,-0.852202,1.352208,1.083783,-0.00658,-0.177066,-0.114423,-0.535139,-0.536151,-0.121791,-0.685979,1.012629,0.332551,1.012629,1.241641,0.514451,0.727484,2.042839,0.608755,1.837109,-1.141631,-1.822124,1.259944,0.252372,0.309588,-0.149958,0.425336,-0.875200,0.360939,-0.449495,-0.699831,1.125557,0.625949,0.00357,0.858894,0.815167,0.554509,0.460110,-0.606106,-0.491035,0.199994,0.284059,0.607955,0.108019,0.799939,0.016271,-1.389167,-1.285737,1.409723,1.160153,-0.00658,-0.175681,-0.759042,-0.870668,-0.871162,-0.320078,-0.749469,0.863246,0.387817,0.863246,1.351330,0.525392,0.916871,2.101275,1.359041,1.037215,-0.456681,-0.848622,0.804586,0.270893,0.328317,-0.165400,0.444934,-2.510720,0.052107,-1.238944,-0.104179,1.193014,0.308455,0.00089,-0.368013,-0.416501,1.174314,0.697295,0.390237,0.581227,-0.132928,2.334787,0.291049,-0.832710,-0.189114,-0.110749,-2.016948,-2.026802,-0.326836,-0.472452,-0.00658,-0.003876,-0.795974,-0.902888,-0.903407,-0.645137,-0.120609,-0.011873,1.329463,-0.011873,-0.893945,-0.746688,-1.022742,1.476627,1.414350,0.477567,0.666550,-0.350335,0.585716,-0.467088,-0.702663,-0.654277,-0.561133,-1.289512,-1.255073,-2.440623,-0.756880,-0.847839,0.677200,0.00089,22
2528,-0.681826,-0.048661,0.103687,1.065990,1.011919,-0.967803,-0.815104,-0.942449,-1.463647,-0.885970,0.067825,-0.178055,-0.843534,0.856803,0.904668,-0.125342,-0.122186,-0.00658,-0.109414,0.419448,0.363533,0.363530,0.340792,-1.029777,-0.003544,-1.046014,-0.003545,0.250772,0.489581,-0.086092,-0.110797,0.764184,-1.709841,0.344325,0.362940,-0.361161,1.098511,-1.216083,-0.333830,-0.584865,0.282888,-1.532497,0.790132,1.035306,0.313982,0.817559,-1.277667,0.418803,0.565744,1.240614,1.173048,-0.744261,-0.566871,-0.379919,-1.023449,-0.217375,0.485274,-0.002778,-0.419751,0.967410,1.021970,0.530334,0.409115,-0.00658,-0.036504,0.552093,0.520884,0.520683,0.497896,-0.965651,-0.003876,-0.608369,-0.003876,0.744087,0.281200,0.565892,0.206751,0.369354,-0.638645,0.547093,1.096604,-1.110645,0.944070,-1.365509,-0.532496,0.114815,0.553487,-1.895350,0.917659,1.395052,0.843509,0.589701,-1.114573,0.449282,0.611748,1.371977,1.292027,-0.871801,-0.668721,-0.419632,-1.258965,-0.243104,0.567061,0.009251,-0.542334,1.090168,1.151313,0.570664,0.434369,-0.00658,-0.036522,0.565208,0.532021,0.531806,0.512150,-1.077591,-0.002329,-0.594660,-0.002329,0.810678,0.300336,0.598805,0.249633,0.419229,-0.771418,0.622215,1.238546,-1.217429,1.063391,-1.551211,-0.618869,0.117533,0.643592,-2.167100,1.018029,1.544191,0.910950,0.693499,-1.641555,-0.131735,-0.158149,1.658593,1.496904,-1.059395,-0.976652,-1.002883,-1.641988,-1.432778,0.995556,0.281397,-0.437309,1.047986,1.009291,0.090962,0.204546,-0.00658,-0.092346,-0.435823,-0.342900,-0.343915,-0.121791,-1.421644,0.002126,-0.998425,0.002126,-0.362142,0.927743,-0.102634,0.138607,0.853799,-1.136973,0.144285,-0.577318,-0.523035,1.119530,-1.243799,-0.958503,-1.159344,-0.287843,-0.860656,0.979517,0.900897,-0.106787,-0.214920,0.00357,-0.151246,-0.041445,0.244519,0.390422,-0.097429,-0.461828,0.324958,-1.466772,-0.879590,1.550546,0.901123,0.387315,0.904841,0.825975,0.083843,0.207591,-0.00658,-0.090628,-0.210682,-0.082849,-0.083362,-0.013603,-0.414337,-0.000707,-0.058286,-0.000707,-0.018258,0.943863,-0.123928,0.872525,0.734521,-0.689164,0.004417,-0.368750,-0.596878,-0.195090,-0.238885,-0.019899,-0.689661,-0.307267,-1.876721,0.550556,0.939644,0.106212,0.538358,0.00089,-0.165777,-0.040739,0.286049,0.449298,-0.124640,-0.501648,0.401390,-1.337143,-0.960338,1.753329,0.993074,0.396960,0.963504,0.874065,0.055752,0.202850,-0.00658,-0.089093,-0.226193,-0.095580,-0.096108,-0.054187,-0.471252,-0.011873,-0.053990,-0.011873,-0.042387,0.927916,-0.175872,0.956046,0.770477,-0.714893,0.017158,-0.350335,-0.684076,-0.209949,-0.280436,-0.017250,-0.760399,-0.310167,-1.906155,0.592723,0.977137,0.135562,0.594909,0.00089,7
10064,1.507062,-0.655554,-0.932917,-0.808738,-0.831011,0.123556,-0.110733,0.896502,0.331545,0.818096,-0.832856,0.043376,-0.143858,0.799765,0.680884,-0.075887,-0.104152,-0.00658,-0.007497,0.956613,1.136725,1.136719,1.091746,0.161690,-0.003544,-0.188405,-0.003545,0.344059,0.052837,0.274207,-1.049828,-1.463708,-0.065364,-0.125349,-0.044724,-0.476324,-0.727186,0.326447,-0.151782,1.075595,0.371095,-0.433557,0.652235,-1.028433,-0.070147,0.146724,0.635929,-0.854860,-1.033213,-0.088268,0.105904,-0.724894,-1.127194,0.773113,0.581969,1.111219,-1.116459,-0.462077,-0.476795,0.534761,0.448151,-0.033026,-0.265947,-0.00658,-0.036504,0.685198,0.675737,0.675833,0.660583,-0.375224,-0.003876,-0.147138,-0.003876,0.880685,0.348004,0.592230,-1.628770,-1.702978,-0.408936,-1.640140,-1.767109,0.398620,-1.181016,-0.007507,-0.652459,1.291988,0.643026,1.411431,0.488176,-0.089807,-0.432049,1.165850,-0.417947,0.076224,-0.091927,0.248744,0.269113,-0.162656,-0.371171,1.610083,0.750267,1.663544,-0.680338,-0.223298,-0.292865,0.415824,0.333823,0.527439,0.395583,-0.00658,0.001161,0.547619,0.637291,0.637256,0.815633,0.047343,0.184610,-0.276577,0.184610,0.959996,0.229535,0.732298,-0.257324,-0.101798,-0.330552,-0.190692,-0.026108,-0.456002,-0.593729,-0.050378,-0.356128,1.969451,0.586618,0.574411,0.690905,0.063605,0.576812,0.362584,-0.138760,-0.186677,-0.301156,-0.558427,-1.029147,0.538720,0.322224,1.757911,0.928452,1.599038,-1.112801,-0.090322,-0.114935,1.317992,1.247944,0.050710,0.062734,-0.00658,-0.007625,0.736784,1.323167,1.323153,1.045428,0.746632,0.002126,-0.194883,0.002126,1.063443,0.411128,0.759411,-1.051538,-1.229075,-0.736790,0.001406,-0.237826,-0.539892,-1.265154,-0.035609,0.119557,1.481789,1.474230,0.971737,1.217685,-0.499740,0.400649,1.256602,0.00357,-0.690557,-0.932668,-0.616565,-0.985923,-0.414431,-0.381508,2.147357,0.795031,1.715701,-1.048725,-1.350216,-0.596759,-0.123203,-0.164704,0.673123,0.504291,-0.00658,-0.090628,0.752166,0.573667,0.573663,0.497188,0.800517,-0.000707,-0.177474,-0.000707,1.155674,0.839245,1.163840,-1.830725,-1.263946,-1.687071,-1.225177,-1.568430,1.237335,-0.894066,-0.238885,0.271102,2.335926,1.266628,1.980935,-0.216373,0.104586,0.183841,1.381335,0.00089,0.018074,-0.510441,1.146555,0.916677,-1.597981,-1.989627,1.660007,-0.143245,1.339508,-1.751845,-0.354070,-0.898574,-0.384056,-0.206650,0.390517,0.152203,-0.00658,-0.003876,0.790316,0.711728,0.712806,1.226206,-1.788817,0.832244,-1.177354,0.832244,1.022060,0.509265,0.247562,-0.605696,0.126604,0.282437,-0.469885,-0.838365,0.004473,0.047190,-0.280436,-0.654277,1.830063,1.322074,0.372631,0.592723,0.543632,0.955062,0.594909,0.00089,4

In [26]:
df_test = pd.concat([X_test, y_test], axis=1)
p(df_test)

(3080, 278)

,season_year,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,spread_a
2583,-0.681826,-0.735562,-0.440041,0.016063,0.346138,-0.665791,-0.710886,-0.255074,-0.283950,-0.661178,0.211842,0.949670,0.767414,-0.254742,-0.085408,-0.683478,-0.998594,-0.00658,-0.058456,0.264130,-0.137610,-0.137152,-0.215471,-1.137425,-0.003544,-2.227451,-0.003545,-0.588810,0.817139,-1.266381,1.364824,1.396424,0.288545,-0.936605,-0.520333,-0.863383,0.837697,0.373190,0.758455,-0.489981,-0.422765,-0.733268,-0.175147,-0.913781,-0.490861,0.798924,-0.639802,-0.652458,-0.662046,1.046442,1.053182,-1.577352,-1.665154,-0.656073,-0.845667,-0.830385,-0.635755,1.044474,0.109003,0.425229,0.439965,-0.195275,-0.549081,-0.00658,0.029388,0.233472,0.246091,0.246144,0.223547,-1.976571,-0.003876,-1.462768,-0.003876,-0.375607,0.203388,-0.595206,0.984171,1.068632,0.074403,-0.916077,-0.217456,-1.434579,0.172307,-0.609881,-0.374364,-0.738531,-0.362250,-1.977477,0.510336,0.087364,-0.386296,1.639850,-1.481885,-0.688474,-0.746192,0.974933,0.980331,-1.632337,-1.783216,-0.650483,-1.098391,-0.847628,-0.583260,1.450696,0.325352,0.736948,0.716292,-0.177695,-0.562953,-0.00658,0.034973,0.188391,0.223944,0.223945,0.209165,-1.992668,-0.002329,-1.240700,-0.002329,-0.428338,0.143199,-0.594655,1.064323,1.135549,0.056297,-1.093449,-0.293744,-1.610375,0.350343,-0.478218,-0.178747,-0.764688,-0.488496,-2.095374,0.757453,0.085776,-0.458838,1.745301,-1.757353,-0.076792,-0.174039,0.322091,0.739886,-0.167114,-0.148871,-0.501780,-0.788021,-0.566545,-0.058622,0.506681,-0.063356,0.061394,0.341063,-0.231058,-0.362703,-0.00658,-0.092346,-0.003942,-0.471059,-0.471560,-0.440123,-0.831176,0.002126,-2.233826,0.002126,-1.253132,0.307805,-1.012571,1.566781,1.588932,0.200000,-0.855872,-0.124661,0.510693,1.119530,1.345180,1.467132,-0.455042,0.593193,-0.249858,-0.211327,0.700806,0.038194,0.205515,0.00357,-0.091322,-0.197193,1.010883,1.183127,-0.982085,-0.907240,-0.216555,-0.715343,-1.196089,-0.041677,1.900313,-0.080524,0.169644,-0.008281,-0.446509,-0.198419,-0.00658,-0.090628,0.046764,0.179757,0.179763,0.190713,-1.053182,-0.000707,-1.382975,-0.000707,-0.800880,0.211539,-0.864836,-0.110475,0.859425,-0.140315,-0.917778,-0.128814,0.568722,0.037901,0.328317,0.562103,-0.878761,-0.622046,-1.233779,0.550556,0.730879,-0.049045,1.534603,0.00089,-0.101429,-0.209832,1.109544,1.317287,-0.528621,-0.922333,-0.216044,-0.643017,-1.298551,-0.069361,2.079037,0.046816,0.771623,0.475907,-0.518131,-0.236096,-0.00658,-0.089093,0.041309,0.173523,0.173530,0.142797,-0.524379,-0.011873,0.253137,-0.011873,-0.893945,0.195277,-0.984248,-0.085115,0.899252,-0.118663,-0.956929,-0.106320,0.656377,0.047190,0.352905,0.619776,-0.959665,-0.636615,-1.255073,0.592723,0.760384,-0.028338,1.664696,0.00089,6
9370,1.507062,1.120241,1.073792,0.587845,0.935715,0.480478,0.146219,1.215640,0.745820,1.615743,-0.229354,-0.364396,-0.149500,0.409590,0.396067,1.428960,1.518826,-0.00658,0.026476,0.552898,0.377851,0.377620,0.702362,0.814917,0.329538,-1.250987,0.329538,1.230284,-0.083645,1.388233,0.761161,0.312584,0.583912,0.557814,0.125136,1.146068,-0.987999,-0.421446,-0.879972,1.692337,0.106475,0.965095,0.790132,0.232741,1.411495,-0.170060,-0.639802,0.462915,0.428407,0.651780,0.775277,-0.156215,-0.322730,0.401281,0.454566,0.566274,0.233249,-0.250959,-0.089753,-0.116341,-0.144140,0.312907,0.382113,-0.00658,-0.029398,0.017494,-0.018004,-0.018103,0.148119,0.169228,0.138827,-1.553327,0.138827,0.584722,0.247797,0.403810,-0.005448,-0.046923,-0.035002,0.065038,-0.304063,0.747245,0.034884,-0.803577,-0.598475,0.604030,0.240102,0.439851,-0.103814,-0.423900,0.470387,0.306401,0.835980,-0.034108,-0.089383,0.546514,0.597905,-0.559638,-0.705521,0.335764,-0.052931,0.309473,-0.315795,-0.425828,-0.290834,0.381524,0.343074,0.179401,0.265258,-0.00658,0.045749,0.248976,0.252795,0.252810,0.297773,-0.189011,0.062046,-1.528105,0.062046,0.124460,-0.088531,0.228676,-0.100794,-0.244602,0.134194,0.172754,-0.114670,0.786554,-0.626002,-0.335953,-0.592030,0.331914,0.575198,0.454935,0.615666,0.409932,0.132749,0.782244,-0.261630,1.390952,1.033572,0.801660,1.114411,0.938249,0.625071,1.739001,0.851595,2.494145,-0.957070,-0.777439,-0.102040,-0.897975,-0.804472,1.862074,1.920476,-0.00658,0.077095,0.505778,0.361974,0.361974,0.620985,0.920868,1.012629,-1.359488,1.012629,0.885245,0.101159,1.589529,1.090723,0.241189,0.663847,0.715804,0.327995,0.594121,-1.265154,0.482187,-0.015201,2.186092,0.299515,0.666338,-0.449495,1.301079,1.198048,0.065370,0.00357,0.002843,-0.110666,-0.031028,-0.053841,-0.554501,-0.805014,1.210123,-0.271999,0.956104,-0.368287,-0.869593,-0.128921,-0.416049,-0.138634,-0.446509,-0.417040,-0.00658,0.079477,-0.990743,-0.805017,-0.804986,-0.217919,-0.738996,0.863246,-1.624756,0.863246,-0.800880,0.734627,-0.953039,0.626775,-0.264713,0.548240,-0.302982,-0.248782,0.662793,-0.894066,-0.238885,-0.019899,0.255835,0.322291,0.373578,-0.472015,0.313350,-1.135847,0.461724,0.00089,0.615591,0.767147,-0.010039,-0.037157,2.235873,1.819911,0.330148,-0.233482,1.745363,-1.050810,0.168292,0.974698,0.517637,0.817185,1.315107,1.030096,-0.00658,-0.089093,0.060034,0.375350,0.375355,0.339780,1.823863,0.832244,-0.053990,0.832244,-0.255276,0.299939,1.113679,0.435465,-0.259719,-0.216228,1.153594,0.503718,0.004473,-0.981366,0.141791,-0.176507,1.431530,-0.636615,0.047090,1.144240,-0.540128,-0.438089,0.512618,0.00089,14
5655,0.193729,0.121113,0.209304,0.832894,0.622878,-0.614312,-0.365888,0.829550,-0.208986,0.709326,1.094235,-1.624012,-1.110144,0.911412,0.972482,0.044218,-0.021200,-0.00658,-0.058456,-0.583110,-0.524206,-0.524434,-0.521415,-0.290921,-0.003544,-1.456670,-0.003545,0.157485,-0.165534,0.232793,-0.580313,-1.012109,0.280562,-0.296140,-0.248556,-0.258077,1.033307,-0.000757,0.576408,0.743503,-0.952004,-0.233749,0.652235,0.290067,-0.161607,0.370335,0.635929,-0.544521,-0.381636,0.635441,0.584578,-1.099025,-0.938778,0.475648,0.308365,0.290309,0.386136,-1.368477,-1.277268,0.254977,0.351168,-0.613022,-0.638236,-0.00658,-0.107565,-0.011115,-0.096173,-0.095999,-0.010501,-0.780537,0.138827,-1.522132,0.138827,0.152160,0.360530,-0.181712,-1.405961,-1.214306,-0.711235,-0.215561,-0.116930,-0.225624,0.560678,-0.780163,-0.292572,0.489370,0.329640,-0.429457,0.105124,1.330090,-0.353953,0.984411,-0.835922,-0.499119,-0.464587,0.611899,0.645152,-1.090631,-1.143969,0.517351,0.238644,0.438685,0.404028,0.315642,0.675668,0.215903,0.260159,-0.335323,-0.377313,-0.00658,0.020740,0.310986,0.259991,0.259950,0.294553,-0.723463,0.018400,-1.275148,0.018400,0.283079,0.245080,0.072477,-1.271294,-0.913535,-0.870596,-0.146491,0.005521,-0.415672,-0.024501,-0.780617,-0.610755,0.640416,0.821246,-0.650386,0.309849,0.910016,-0.180240,1.115103,0.232082,0.339199,0.286760,1.171163,0.875352,0.232415,0.059757,0.793524,-0.651386,1.252544,0.803887,-0.146643,0.323493,0.451813,0.508120,-0.257893,-0.305978,-0.00658,-0.092346,-0.696960,-0.855537,-0.856031,-0.864567,0.272322,0.002126,-1.497541,0.002126,0.528849,-0.518779,-0.086670,-0.337451,-0.493943,0.090859,0.572924,0.327995,-0.238574,0.469161,-0.553405,-0.419473,1.129638,-2.343594,-0.249858,0.503179,0.300624,-0.396751,0.135442,0.00357,0.054206,-0.024140,1.260597,0.956640,-0.502896,-0.038321,0.324958,0.524516,0.259806,-0.300244,-0.275138,-0.403171,-0.193400,0.148142,-0.696953,-0.495119,-0.00658,-0.090628,-0.146320,-0.279804,-0.280312,0.497188,0.182617,-0.000707,-1.454488,-0.000707,0.568708,0.839245,-0.106287,-1.093475,-0.389617,-0.260064,0.619213,0.351058,-0.276128,0.503885,-0.238885,-0.165400,0.634033,-1.881162,-0.269365,0.039270,1.148408,-0.437189,0.308455,0.00089,-0.184162,-0.717110,0.563632,0.191763,-0.489015,-0.392581,0.080799,0.502293,0.561619,0.008531,0.484458,1.184785,1.874865,1.841020,0.071693,-0.404921,-0.00658,0.081340,0.506763,0.509901,0.509367,0.241288,0.134404,-0.855991,-0.053990,-0.855991,0.170502,-0.746688,0.574762,-1.386567,-1.289916,-0.367996,0.828898,0.747733,-0.149963,1.075745,-0.280436,-0.495021,0.435199,0.342729,-0.929532,1.419999,0.977137,0.135562,0.594909,0.00089,-1
7258,0.631507,-0.202824,-0.310954,-0.571658,-0.626463,0.315745,0.273797,-0.094389,-0.212931,-0.044814,-0.112769,0.264807,0.204570,0.206002,0.138376,0.100738,0.184377,-0.00658,-0.075442,-0.200983,-0.114701,-0.114816,-0.465789,0.142117,-0.336627,-1.044591,-0.336627,-0.635454,-1.175504,0.290772,-0.714460,-1.764775,1.368897,0.258930,0.328968,-0.450466,-1.248813,-1.870489,-2.154305,-0.347656,1.958813,0.065962,-0.313044,1.035306,-0.582320,-0.225963,1.911660,-0.805467,-1.011774,-1.044562,-0.966055,0.195908,-0.076127,-0.458181,-0.564659,-0.506149,-0.539549,-0.894869,-0.883029,0.749123,0.635191,-0.268811,-0.322824,-0.00658,0.013238,-0.111731,-0.054673,-0.054672,0.050507,0.130511,0.138827,-1.157687,0.138827,-0.621898,-0.867000,0.081671,-1.278642,-1.988037,0.864730,-0.129223,0.359411,-1.215484,-0.918119,-0.522611,-0.904379,-0.657227,1.627951,0.439851,0.418531,0.132922,-0.874589,0.086764,1.253955,-0.975665,-1.064139,0.357616,0.345433,-1.325995,-1.476415,0.544406,0.075114,0.234388,-0.605685,-0.354101,-0.204981,0.288812,0.230776,-0.593253,-0.625080,-0.00658,-0.035603,-0.428297,-0.376925,-0.376857,-0.375843,-1.000027,-0.002329,-1.108873,-0.002329,-0.895795,-0.702997,-0.303633,-1.214759,-1.423426,-0.065876,-0.675776,-0.460133,-0.532250,-0.952712,-1.244193,-1.462133,-0.040250,0.445029,-0.244108,-0.009605,0.543063,-1.250035,1.461905,-0.466393,-0.163130,-0.253487,-0.865036,-0.646653,0.159168,-0.014272,0.141145,-0.121927,0.241939,-0.429981,-2.140408,-1.597856,0.680129,0.388793,-0.257893,-0.461972,-0.00658,-0.007625,0.209488,0.015945,0.015950,-1.289010,0.165844,-1.008376,-1.072761,-1.008376,0.172453,-1.138717,0.328388,-0.099422,-1.474119,1.491497,0.715804,0.667488,-0.328222,-1.265154,-2.451990,-2.575593,0.249260,1.767908,-0.249858,-0.211327,0.900897,-0.251769,-0.284993,0.00357,-0.185488,-0.283719,-0.952387,-0.707169,-0.377570,-0.834221,0.491577,0.937803,0.924454,-0.286635,-1.426104,-0.887141,0.754265,0.434918,-0.299189,-0.526350,-0.00658,-0.090628,0.136870,0.022194,0.022203,0.292871,-0.246771,0.863246,-1.161626,0.863246,0.177397,0.630010,0.352370,-0.356225,-1.513754,1.316629,-0.149283,-0.488718,-0.377213,-0.428082,0.328317,0.271102,0.634033,0.951849,0.373578,0.039270,-0.312943,-0.281932,-0.841058,0.00089,-0.698946,-0.717110,0.702423,0.773601,-0.980128,-1.452085,0.520128,0.238524,0.426334,-1.471431,-1.096374,-0.863560,0.634817,0.646546,-0.358719,-0.590630,-0.00658,-0.003876,-0.737123,-0.701061,-0.699968,-0.743629,-1.193788,-0.011873,-1.240992,-0.011873,-0.042387,-0.642025,0.382291,-0.345406,-0.646043,0.510088,-1.443973,-0.350335,0.004473,-0.209949,0.352905,0.301263,0.235932,0.016281,-0.603992,0.868482,0.543632,-0.929789,1.170948,0.00089,8
2386,-0.681826,-0.005730,-0.001929,0.014070,0.013248,-0.017154,-0.013702,-0.150182,-0.094567,-0.110076,0.033535,-0.031645,-0.021132,0.035235,0.036656,-0.019367,-0.013987,-0.00658,-0.007497,-0.021274,-0.023063,-0.023064,-0.020779,-0.019354,-0.003544,-0.047487,-0.003545,0.017555,-0.001756,0.017442,-0.110797,-0.139016,-0.001501,0.002744,-0.010752,0.015783,0.055256,-0.047500,-0.006144,-0.110448,0.018268,0.065962,0.031699,0.118089,-0.015272,0.016283,-0.001937,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.00658,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.020129,-0.016556,0.023406,0.021431,-0.042845,-0.039299,-0.187685,-0.127006,-0.146191,0.035462,-0.026867,-0.029662,0.030398,0.031400,-0.041311,-0.030891,-0.00658,-0.008044,-0.031536,-0.032130,-0.032135,-0.029435,-0.048615,-0.002329,-0.049286,-0.002329,0.000716,-0.004775,-0.000452,-0.132651,-0.152585,-0.008676,-0.002646,-0.028478,0.033599,0.059791,-0.078879,-0.028412,-0.153264,0.028046,0.069342,0.020868,0.150282,-0.035511,0.042704,0.014355,-0.021850,-0.015143,0.015482,0.014742,-0.020620,-0.021002,-0.133044,-0.070689,-0.104554,0.049191,-0.000208,0.026909,0.030249,0.030814,-0.029795,-0.022353,-0.00658,-0.007625,-0.024029,-0.022503,-0.022497,-0.015680,-0.008393,0.002126,-0.053290,0.002126,-0.005746,-0.002164,0.009112,-0.099422,-0.126377,0.018099,0.001406,-0.011497,0.007959,0.035583,-0.035609,-0.015201,-0.102891,0.005836,0.055541,0.026842,0.100533,-0.034297,-0.004703,0.00357,-0.031399,-0.024140,0.012026,0.015847,-0.031080,-0.031020,-0.133245,-0.084142,-0.119993,0.053584,0.003117,0.032403,0.044253,0.043860,-0.048745,-0.042261,-0.00658,-0.005576,-0.020172,-0.017197,-0.017187,-0.013603,-0.016367,-0.000707,-0.058286,-0.000707,-0.018258,0.002303,-0.000443,-0.110475,-0.139808,0.039308,0.004417,-0.008846,0.001855,0.037901,-0.049817,-0.019899,-0.122364,0.007512,0.052107,0.039270,0.104586,-0.049045,0.001918,0.00089,-0.037081,-0.021951,0.036225,0.039149,-0.053350,-0.042011,-0.121054,-0.059950,-0.148628,0.039688,0.017082,0.011801,0.022555,0.020869,-0.087719,-0.067270,-0.00658,-0.003876,-0.028242,-0.028304,-0.028294,-0.054187,-0.067481,-0.011873,-0.053990,-0.011873,-0.042387,-0.014049,-0.041143,-0.085115,-0.130945,0.076467,0.017158,0.015688,0.004473,0.047190,-0.069322,-0.017250,-0.162600,0.016281,0.047090,0.041205,0.110128,-0.028338,0.018869,0.00089,-10

In [27]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '158B_train_split.csv')
if not os.path.exists(datapath_df):
    df_train.to_csv(datapath_df, index=True)

In [28]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '158B_test_split.csv')
if not os.path.exists(datapath_df):
    df_test.to_csv(datapath_df, index=True)

In [29]:
df_train_readback = rcp('158B_train_split.csv', None, 0)
p(df_train_readback)

(7186, 278)

,season_year,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,spread_a
3134,-0.681826,-0.208678,-0.213161,0.966377,0.787318,-1.015850,-0.903150,0.151102,1.759807,0.042202,-1.068313,-0.803628,-1.626437,-1.136818,-1.150080,-0.687010,-0.554980,-0.00658,0.060448,-0.476014,-0.323749,-0.323405,-0.354536,-1.110513,-0.003544,-1.218960,-0.003545,-0.355593,0.353099,-0.699014,-0.177871,-0.289549,0.014465,-0.253442,-0.690193,0.557528,-0.009948,-0.608420,-0.479468,-0.063006,-1.304830,-1.632401,-1.209374,-0.111216,-0.435985,0.985267,-0.639802,-0.376770,-0.355536,0.800750,0.692448,-1.089342,-1.017284,-0.448620,0.594500,-0.583000,-0.590909,0.342986,-0.234494,-1.076958,-1.089729,-0.940024,-0.698561,-0.00658,0.062981,-0.547169,-0.475748,-0.475523,-0.705987,-0.999528,-0.289282,-1.249473,-0.289282,-0.804030,-0.027771,-0.815858,-0.801194,-0.766357,-0.262801,-0.086053,-0.695343,1.105986,-0.030841,-0.639680,-0.508504,-0.863614,-1.684980,-0.991951,-1.148502,-0.284695,-0.865912,1.032158,-1.671873,-0.727736,-0.649936,0.610777,0.446572,-1.318376,-1.141290,-0.743136,-0.704513,-1.071664,-0.553933,-0.425463,-1.127084,-0.326194,-0.276681,-0.908559,-0.710666,-0.00658,0.019296,-0.406310,-0.362682,-0.362696,-0.428516,-1.422858,-0.071853,-0.851137,-0.071853,-1.153480,-0.072617,-1.155782,0.220006,0.113604,0.256370,-0.269033,-0.861610,1.176166,-0.373764,-1.082168,-1.028432,-1.286550,-0.279727,-1.929574,-0.470365,0.570915,-0.907770,1.139590,-0.432741,-0.948021,-0.531555,0.817383,0.684105,-0.892924,-0.310389,0.727341,1.876355,0.501809,-1.651869,0.134962,-0.888633,-0.849909,-0.876068,-0.298146,-0.617965,-0.00658,0.161815,-1.076111,-0.791457,-0.791440,-0.652345,-0.589181,0.002126,-1.186036,0.002126,0.350651,0.101159,-0.246308,-0.099422,-0.616465,0.018099,1.001563,0.441160,0.585126,-0.397996,-0.380806,-1.093261,0.601411,-1.168879,-1.776852,-1.164001,2.101443,-0.469242,1.326674,0.00357,-1.041538,-0.586562,0.632006,0.895663,-0.996829,-0.344999,0.220821,1.508889,0.196506,-0.586027,-0.692521,-0.725818,-1.362642,-1.337878,-0.343385,-0.698124,-0.00658,0.164530,-0.710127,-0.805017,-0.804986,-1.035185,-0.780887,-0.864660,-1.148005,-0.864660,0.373053,-0.416168,-0.282694,-1.093475,-1.014137,0.488366,0.772912,0.471026,1.009039,-0.195090,-0.995153,-1.183904,-0.311463,-0.936825,-1.555250,-1.750230,0.104586,-0.514818,0.001918,0.00089,-1.121804,-0.632563,-0.000786,0.506528,-1.091025,-0.377001,-0.227918,1.411599,-0.317734,0.039688,0.910596,-0.023213,1.371581,1.357543,-0.406542,-0.776338,-0.00658,0.081340,-0.745148,-0.768337,-0.767781,-0.743629,-0.843145,-0.011873,0.942096,-0.011873,0.383392,-1.479327,-0.349096,0.175175,0.384154,0.293278,0.828898,-0.228327,1.479937,-0.724227,-1.124890,-1.609818,-0.760399,0.342729,-0.603992,0.316964,0.110128,-0.520039,0.265743,0.00089,8
8383,1.069285,0.105501,0.238641,0.167475,0.037312,-0.049757,0.182156,-0.942449,-0.769243,-0.733691,0.614177,1.115441,1.039667,0.489804,0.518132,0.008893,0.058145,-0.00658,-0.024483,-0.035572,-0.016763,-0.017222,-0.326723,0.049149,-0.336627,0.155350,-0.336627,0.390702,-0.220127,0.572385,-1.720565,-1.283068,-0.983397,0.301628,0.362940,0.014940,0.642086,-0.000757,0.357951,-0.679748,-0.599178,-2.032016,0.514338,1.436588,-0.033564,-0.132791,-0.639802,-0.084139,-0.008774,0.606608,0.501749,-0.635103,-0.489904,-0.858697,-0.253461,-0.691291,0.707439,0.243057,0.565180,0.140630,0.150274,-0.203410,-0.197004,-0.00658,0.070087,-0.354422,-0.321515,-0.321811,-0.181322,-0.468385,0.138827,0.157016,0.138827,0.379824,0.097488,0.249831,-1.374131,-1.064990,-0.768542,-0.129223,-0.167966,0.028900,0.494954,-0.311887,0.031326,-0.611363,-0.520977,-1.298766,0.279239,1.218725,-0.137022,0.440093,-0.417947,0.115400,0.200899,0.164728,0.066475,-0.044939,0.144723,-0.950591,-0.275645,-0.579667,1.020149,-0.074992,0.363323,0.014839,0.040881,-0.029708,-0.115277,-0.00658,0.026101,-0.557008,-0.545166,-0.545256,-0.683276,-0.094728,-0.178209,0.648518,-0.178209,0.239494,-0.130111,0.290712,-0.942138,-0.855332,-0.382546,-0.715555,-0.712187,-0.141790,0.604154,-0.606724,-0.141382,-0.725125,-0.334687,-1.420013,-0.127340,0.214288,-0.344270,-0.174404,-0.676311,-0.218073,0.000747,0.778074,0.644262,0.625285,0.470283,-0.123589,-0.651386,-0.104554,1.438790,0.855871,1.664569,0.913105,0.842234,-0.365233,-0.518697,-0.00658,-0.177066,-0.493574,0.169736,0.169739,-0.015680,0.688553,-1.008376,0.169719,-1.008376,-0.362142,0.101159,0.025076,-1.289568,-1.474119,-0.282038,-0.284353,-0.124661,-0.086408,0.902740,0.482187,0.928102,-0.455042,-0.581522,-1.166054,1.455854,1.301079,-0.469242,-0.004703,0.00357,-0.202609,0.252745,-0.375461,-0.410994,0.042641,0.268356,-0.476897,0.051116,0.196506,1.632199,0.268724,2.016683,1.008797,0.878116,-0.417045,-0.588813,-0.00658,-0.090628,-0.220980,-0.082849,-0.083362,0.599346,0.392075,0.863246,0.156252,0.863246,1.155674,0.002303,0.017197,-1.093475,-1.388850,0.039308,0.772912,0.231090,0.020143,0.037901,0.139250,0.998605,0.255835,0.637070,-0.590836,1.061842,1.148408,0.028583,0.308455,0.00089,0.459318,0.851693,-0.232105,-0.189771,0.968483,1.142140,-0.394150,-0.066891,-0.858874,1.441758,1.130537,1.272321,0.093449,-0.178210,0.247047,-0.489334,-0.00658,0.081340,-0.343895,-0.566510,-0.565956,-0.054187,0.325663,-0.011873,0.903360,-0.011873,1.234949,-0.014049,0.016598,0.175175,-1.289916,0.369161,-0.632233,-0.472343,-0.549091,0.047190,0.352905,0.619776,-0.162600,-0.310167,-1.255073,-0.234553,0.110128,0.053612,0.348035,0.00089,-20
7423,0.631507,0.649948,0.721738,1.241310,1.392938,-0.494194,-0.583308,0.282774,0.572219,0.607807,0.842776,-1.470341,-0.145268,-0.364447,-0.343099,0.683601,0.728976,-0.00658,-0.041469,0.021621,-0.112983,-0.112754,0.229539,-0.322726,0.329538,0.339682,0.329538,0.717206,0.462284,0.352892,1.431898,0.764184,1.241171,-0.253442,-0.860053,1.497693,-0.596779,0.419933,-0.006144,0.696061,-1.128417,1.564517,-0.244095,-0.512498,0.844447,0.538044,0.635929,0.556110,0.547723,0.560475,0.683780,0.017205,-0.111224,0.252549,0.728169,0.622166,0.229666,-1.268548,-0.368039,-0.561384,-0.570175,0.448871,0.380389,-0.00658,-0.008080,-0.414064,-0.477483,-0.477456,-0.144717,0.089375,0.281530,0.373883,0.281530,0.584722,0.423159,0.227545,0.949448,0.943996,0.288787,-0.712005,-1.120647,0.844477,0.002022,0.788563,0.607145,0.626962,-1.908827,0.797801,-0.521689,-0.173330,0.418323,-0.008731,0.835980,0.188366,0.051295,-0.167099,-0.123805,0.351046,0.180425,-0.529337,1.027957,-0.368710,-0.633984,-0.227074,-0.579817,-1.304364,-1.362547,-0.161072,-0.036150,-0.00658,0.034674,-0.836887,-0.784953,-0.784989,-0.598523,0.132433,0.190795,0.591129,0.190795,-0.648941,-0.269503,-0.434839,0.643862,0.865343,-0.216644,-0.257523,-0.794510,1.055282,-0.661547,0.008760,-0.347124,-0.817563,-1.254342,-0.374090,-1.507675,-0.305813,-0.414096,-0.212437,0.221344,0.794436,0.755503,1.312675,0.970976,-0.540007,-0.646886,0.065506,0.347755,0.530684,0.097109,0.574266,-0.411519,-0.921763,-0.852202,1.352208,1.083783,-0.00658,-0.177066,-0.114423,-0.535139,-0.536151,-0.121791,-0.685979,1.012629,0.332551,1.012629,1.241641,0.514451,0.727484,2.042839,0.608755,1.837109,-1.141631,-1.822124,1.259944,0.252372,0.309588,-0.149958,0.425336,-0.875200,0.360939,-0.449495,-0.699831,1.125557,0.625949,0.00357,0.858894,0.815167,0.554509,0.460110,-0.606106,-0.491035,0.199994,0.284059,0.607955,0.108019,0.799939,0.016271,-1.389167,-1.285737,1.409723,1.160153,-0.00658,-0.175681,-0.759042,-0.870668,-0.871162,-0.320078,-0.749469,0.863246,0.387817,0.863246,1.351330,0.525392,0.916871,2.101275,1.359041,1.037215,-0.456681,-0.848622,0.804586,0.270893,0.328317,-0.165400,0.444934,-2.510720,0.052107,-1.238944,-0.104179,1.193014,0.308455,0.00089,-0.368013,-0.416501,1.174314,0.697295,0.390237,0.581227,-0.132928,2.334787,0.291049,-0.832710,-0.189114,-0.110749,-2.016948,-2.026802,-0.326836,-0.472452,-0.00658,-0.003876,-0.795974,-0.902888,-0.903407,-0.645137,-0.120609,-0.011873,1.329463,-0.011873,-0.893945,-0.746688,-1.022742,1.476627,1.414350,0.477567,0.666550,-0.350335,0.585716,-0.467088,-0.702663,-0.654277,-0.561133,-1.289512,-1.255073,-2.440623,-0.756880,-0.847839,0.677200,0.00089,22
2528,-0.681826,-0.048661,0.103687,1.065990,1.011919,-0.967803,-0.815104,-0.942449,-1.463647,-0.885970,0.067825,-0.178055,-0.843534,0.856803,0.904668,-0.125342,-0.122186,-0.00658,-0.109414,0.419448,0.363533,0.363530,0.340792,-1.029777,-0.003544,-1.046014,-0.003545,0.250772,0.489581,-0.086092,-0.110797,0.764184,-1.709841,0.344325,0.362940,-0.361161,1.098511,-1.216083,-0.333830,-0.584865,0.282888,-1.532497,0.790132,1.035306,0.313982,0.817559,-1.277667,0.418803,0.565744,1.240614,1.173048,-0.744261,-0.566871,-0.379919,-1.023449,-0.217375,0.485274,-0.002778,-0.419751,0.967410,1.021970,0.530334,0.409115,-0.00658,-0.036504,0.552093,0.520884,0.520683,0.497896,-0.965651,-0.003876,-0.608369,-0.003876,0.744087,0.281200,0.565892,0.206751,0.369354,-0.638645,0.547093,1.096604,-1.110645,0.944070,-1.365509,-0.532496,0.114815,0.553487,-1.895350,0.917659,1.395052,0.843509,0.589701,-1.114573,0.449282,0.611748,1.371977,1.292027,-0.871801,-0.668721,-0.419632,-1.258965,-0.243104,0.567061,0.009251,-0.542334,1.090168,1.151313,0.570664,0.434369,-0.00658,-0.036522,0.565208,0.532021,0.531806,0.512150,-1.077591,-0.002329,-0.594660,-0.002329,0.810678,0.300336,0.598805,0.249633,0.419229,-0.771418,0.622215,1.238546,-1.217429,1.063391,-1.551211,-0.618869,0.117533,0.643592,-2.167100,1.018029,1.544191,0.910950,0.693499,-1.641555,-0.131735,-0.158149,1.658593,1.496904,-1.059395,-0.976652,-1.002883,-1.641988,-1.432778,0.995556,0.281397,-0.437309,1.047986,1.009291,0.090962,0.204546,-0.00658,-0.092346,-0.435823,-0.342900,-0.343915,-0.121791,-1.421644,0.002126,-0.998425,0.002126,-0.362142,0.927743,-0.102634,0.138607,0.853799,-1.136973,0.144285,-0.577318,-0.523035,1.119530,-1.243799,-0.958503,-1.159344,-0.287843,-0.860656,0.979517,0.900897,-0.106787,-0.214920,0.00357,-0.151246,-0.041445,0.244519,0.390422,-0.097429,-0.461828,0.324958,-1.466772,-0.879590,1.550546,0.901123,0.387315,0.904841,0.825975,0.083843,0.207591,-0.00658,-0.090628,-0.210682,-0.082849,-0.083362,-0.013603,-0.414337,-0.000707,-0.058286,-0.000707,-0.018258,0.943863,-0.123928,0.872525,0.734521,-0.689164,0.004417,-0.368750,-0.596878,-0.195090,-0.238885,-0.019899,-0.689661,-0.307267,-1.876721,0.550556,0.939644,0.106212,0.538358,0.00089,-0.165777,-0.040739,0.286049,0.449298,-0.124640,-0.501648,0.401390,-1.337143,-0.960338,1.753329,0.993074,0.396960,0.963504,0.874065,0.055752,0.202850,-0.00658,-0.089093,-0.226193,-0.095580,-0.096108,-0.054187,-0.471252,-0.011873,-0.053990,-0.011873,-0.042387,0.927916,-0.175872,0.956046,0.770477,-0.714893,0.017158,-0.350335,-0.684076,-0.209949,-0.280436,-0.017250,-0.760399,-0.310167,-1.906155,0.592723,0.977137,0.135562,0.594909,0.00089,7
10064,1.507062,-0.655554,-0.932917,-0.808738,-0.831011,0.123556,-0.110733,0.896502,0.331545,0.818096,-0.832856,0.043376,-0.143858,0.799765,0.680884,-0.075887,-0.104152,-0.00658,-0.007497,0.956613,1.136725,1.136719,1.091746,0.161690,-0.003544,-0.188405,-0.003545,0.344059,0.052837,0.274207,-1.049828,-1.463708,-0.065364,-0.125349,-0.044724,-0.476324,-0.727186,0.326447,-0.151782,1.075595,0.371095,-0.433557,0.652235,-1.028433,-0.070147,0.146724,0.635929,-0.854860,-1.033213,-0.088268,0.105904,-0.724894,-1.127194,0.773113,0.581969,1.111219,-1.116459,-0.462077,-0.476795,0.534761,0.448151,-0.033026,-0.265947,-0.00658,-0.036504,0.685198,0.675737,0.675833,0.660583,-0.375224,-0.003876,-0.147138,-0.003876,0.880685,0.348004,0.592230,-1.628770,-1.702978,-0.408936,-1.640140,-1.767109,0.398620,-1.181016,-0.007507,-0.652459,1.291988,0.643026,1.411431,0.488176,-0.089807,-0.432049,1.165850,-0.417947,0.076224,-0.091927,0.248744,0.269113,-0.162656,-0.371171,1.610083,0.750267,1.663544,-0.680338,-0.223298,-0.292865,0.415824,0.333823,0.527439,0.395583,-0.00658,0.001161,0.547619,0.637291,0.637256,0.815633,0.047343,0.184610,-0.276577,0.184610,0.959996,0.229535,0.732298,-0.257324,-0.101798,-0.330552,-0.190692,-0.026108,-0.456002,-0.593729,-0.050378,-0.356128,1.969451,0.586618,0.574411,0.690905,0.063605,0.576812,0.362584,-0.138760,-0.186677,-0.301156,-0.558427,-1.029147,0.538720,0.322224,1.757911,0.928452,1.599038,-1.112801,-0.090322,-0.114935,1.317992,1.247944,0.050710,0.062734,-0.00658,-0.007625,0.736784,1.323167,1.323153,1.045428,0.746632,0.002126,-0.194883,0.002126,1.063443,0.411128,0.759411,-1.051538,-1.229075,-0.736790,0.001406,-0.237826,-0.539892,-1.265154,-0.035609,0.119557,1.481789,1.474230,0.971737,1.217685,-0.499740,0.400649,1.256602,0.00357,-0.690557,-0.932668,-0.616565,-0.985923,-0.414431,-0.381508,2.147357,0.795031,1.715701,-1.048725,-1.350216,-0.596759,-0.123203,-0.164704,0.673123,0.504291,-0.00658,-0.090628,0.752166,0.573667,0.573663,0.497188,0.800517,-0.000707,-0.177474,-0.000707,1.155674,0.839245,1.163840,-1.830725,-1.263946,-1.687071,-1.225177,-1.568430,1.237335,-0.894066,-0.238885,0.271102,2.335926,1.266628,1.980935,-0.216373,0.104586,0.183841,1.381335,0.00089,0.018074,-0.510441,1.146555,0.916677,-1.597981,-1.989627,1.660007,-0.143245,1.339508,-1.751845,-0.354070,-0.898574,-0.384056,-0.206650,0.390517,0.152203,-0.00658,-0.003876,0.790316,0.711728,0.712806,1.226206,-1.788817,0.832244,-1.177354,0.832244,1.022060,0.509265,0.247562,-0.605696,0.126604,0.282437,-0.469885,-0.838365,0.004473,0.047190,-0.280436,-0.654277,1.830063,1.322074,0.372631,0.592723,0.543632,0.955062,0.594909,0.00089,4

In [30]:
df_test_readback = rcp('158B_test_split.csv', None, 0)
p(df_test_readback)

(3080, 278)

,season_year,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff,spread_a
2583,-0.681826,-0.735562,-0.440041,0.016063,0.346138,-0.665791,-0.710886,-0.255074,-0.283950,-0.661178,0.211842,0.949670,0.767414,-0.254742,-0.085408,-0.683478,-0.998594,-0.00658,-0.058456,0.264130,-0.137610,-0.137152,-0.215471,-1.137425,-0.003544,-2.227451,-0.003545,-0.588810,0.817139,-1.266381,1.364824,1.396424,0.288545,-0.936605,-0.520333,-0.863383,0.837697,0.373190,0.758455,-0.489981,-0.422765,-0.733268,-0.175147,-0.913781,-0.490861,0.798924,-0.639802,-0.652458,-0.662046,1.046442,1.053182,-1.577352,-1.665154,-0.656073,-0.845667,-0.830385,-0.635755,1.044474,0.109003,0.425229,0.439965,-0.195275,-0.549081,-0.00658,0.029388,0.233472,0.246091,0.246144,0.223547,-1.976571,-0.003876,-1.462768,-0.003876,-0.375607,0.203388,-0.595206,0.984171,1.068632,0.074403,-0.916077,-0.217456,-1.434579,0.172307,-0.609881,-0.374364,-0.738531,-0.362250,-1.977477,0.510336,0.087364,-0.386296,1.639850,-1.481885,-0.688474,-0.746192,0.974933,0.980331,-1.632337,-1.783216,-0.650483,-1.098391,-0.847628,-0.583260,1.450696,0.325352,0.736948,0.716292,-0.177695,-0.562953,-0.00658,0.034973,0.188391,0.223944,0.223945,0.209165,-1.992668,-0.002329,-1.240700,-0.002329,-0.428338,0.143199,-0.594655,1.064323,1.135549,0.056297,-1.093449,-0.293744,-1.610375,0.350343,-0.478218,-0.178747,-0.764688,-0.488496,-2.095374,0.757453,0.085776,-0.458838,1.745301,-1.757353,-0.076792,-0.174039,0.322091,0.739886,-0.167114,-0.148871,-0.501780,-0.788021,-0.566545,-0.058622,0.506681,-0.063356,0.061394,0.341063,-0.231058,-0.362703,-0.00658,-0.092346,-0.003942,-0.471059,-0.471560,-0.440123,-0.831176,0.002126,-2.233826,0.002126,-1.253132,0.307805,-1.012571,1.566781,1.588932,0.200000,-0.855872,-0.124661,0.510693,1.119530,1.345180,1.467132,-0.455042,0.593193,-0.249858,-0.211327,0.700806,0.038194,0.205515,0.00357,-0.091322,-0.197193,1.010883,1.183127,-0.982085,-0.907240,-0.216555,-0.715343,-1.196089,-0.041677,1.900313,-0.080524,0.169644,-0.008281,-0.446509,-0.198419,-0.00658,-0.090628,0.046764,0.179757,0.179763,0.190713,-1.053182,-0.000707,-1.382975,-0.000707,-0.800880,0.211539,-0.864836,-0.110475,0.859425,-0.140315,-0.917778,-0.128814,0.568722,0.037901,0.328317,0.562103,-0.878761,-0.622046,-1.233779,0.550556,0.730879,-0.049045,1.534603,0.00089,-0.101429,-0.209832,1.109544,1.317287,-0.528621,-0.922333,-0.216044,-0.643017,-1.298551,-0.069361,2.079037,0.046816,0.771623,0.475907,-0.518131,-0.236096,-0.00658,-0.089093,0.041309,0.173523,0.173530,0.142797,-0.524379,-0.011873,0.253137,-0.011873,-0.893945,0.195277,-0.984248,-0.085115,0.899252,-0.118663,-0.956929,-0.106320,0.656377,0.047190,0.352905,0.619776,-0.959665,-0.636615,-1.255073,0.592723,0.760384,-0.028338,1.664696,0.00089,6
9370,1.507062,1.120241,1.073792,0.587845,0.935715,0.480478,0.146219,1.215640,0.745820,1.615743,-0.229354,-0.364396,-0.149500,0.409590,0.396067,1.428960,1.518826,-0.00658,0.026476,0.552898,0.377851,0.377620,0.702362,0.814917,0.329538,-1.250987,0.329538,1.230284,-0.083645,1.388233,0.761161,0.312584,0.583912,0.557814,0.125136,1.146068,-0.987999,-0.421446,-0.879972,1.692337,0.106475,0.965095,0.790132,0.232741,1.411495,-0.170060,-0.639802,0.462915,0.428407,0.651780,0.775277,-0.156215,-0.322730,0.401281,0.454566,0.566274,0.233249,-0.250959,-0.089753,-0.116341,-0.144140,0.312907,0.382113,-0.00658,-0.029398,0.017494,-0.018004,-0.018103,0.148119,0.169228,0.138827,-1.553327,0.138827,0.584722,0.247797,0.403810,-0.005448,-0.046923,-0.035002,0.065038,-0.304063,0.747245,0.034884,-0.803577,-0.598475,0.604030,0.240102,0.439851,-0.103814,-0.423900,0.470387,0.306401,0.835980,-0.034108,-0.089383,0.546514,0.597905,-0.559638,-0.705521,0.335764,-0.052931,0.309473,-0.315795,-0.425828,-0.290834,0.381524,0.343074,0.179401,0.265258,-0.00658,0.045749,0.248976,0.252795,0.252810,0.297773,-0.189011,0.062046,-1.528105,0.062046,0.124460,-0.088531,0.228676,-0.100794,-0.244602,0.134194,0.172754,-0.114670,0.786554,-0.626002,-0.335953,-0.592030,0.331914,0.575198,0.454935,0.615666,0.409932,0.132749,0.782244,-0.261630,1.390952,1.033572,0.801660,1.114411,0.938249,0.625071,1.739001,0.851595,2.494145,-0.957070,-0.777439,-0.102040,-0.897975,-0.804472,1.862074,1.920476,-0.00658,0.077095,0.505778,0.361974,0.361974,0.620985,0.920868,1.012629,-1.359488,1.012629,0.885245,0.101159,1.589529,1.090723,0.241189,0.663847,0.715804,0.327995,0.594121,-1.265154,0.482187,-0.015201,2.186092,0.299515,0.666338,-0.449495,1.301079,1.198048,0.065370,0.00357,0.002843,-0.110666,-0.031028,-0.053841,-0.554501,-0.805014,1.210123,-0.271999,0.956104,-0.368287,-0.869593,-0.128921,-0.416049,-0.138634,-0.446509,-0.417040,-0.00658,0.079477,-0.990743,-0.805017,-0.804986,-0.217919,-0.738996,0.863246,-1.624756,0.863246,-0.800880,0.734627,-0.953039,0.626775,-0.264713,0.548240,-0.302982,-0.248782,0.662793,-0.894066,-0.238885,-0.019899,0.255835,0.322291,0.373578,-0.472015,0.313350,-1.135847,0.461724,0.00089,0.615591,0.767147,-0.010039,-0.037157,2.235873,1.819911,0.330148,-0.233482,1.745363,-1.050810,0.168292,0.974698,0.517637,0.817185,1.315107,1.030096,-0.00658,-0.089093,0.060034,0.375350,0.375355,0.339780,1.823863,0.832244,-0.053990,0.832244,-0.255276,0.299939,1.113679,0.435465,-0.259719,-0.216228,1.153594,0.503718,0.004473,-0.981366,0.141791,-0.176507,1.431530,-0.636615,0.047090,1.144240,-0.540128,-0.438089,0.512618,0.00089,14
5655,0.193729,0.121113,0.209304,0.832894,0.622878,-0.614312,-0.365888,0.829550,-0.208986,0.709326,1.094235,-1.624012,-1.110144,0.911412,0.972482,0.044218,-0.021200,-0.00658,-0.058456,-0.583110,-0.524206,-0.524434,-0.521415,-0.290921,-0.003544,-1.456670,-0.003545,0.157485,-0.165534,0.232793,-0.580313,-1.012109,0.280562,-0.296140,-0.248556,-0.258077,1.033307,-0.000757,0.576408,0.743503,-0.952004,-0.233749,0.652235,0.290067,-0.161607,0.370335,0.635929,-0.544521,-0.381636,0.635441,0.584578,-1.099025,-0.938778,0.475648,0.308365,0.290309,0.386136,-1.368477,-1.277268,0.254977,0.351168,-0.613022,-0.638236,-0.00658,-0.107565,-0.011115,-0.096173,-0.095999,-0.010501,-0.780537,0.138827,-1.522132,0.138827,0.152160,0.360530,-0.181712,-1.405961,-1.214306,-0.711235,-0.215561,-0.116930,-0.225624,0.560678,-0.780163,-0.292572,0.489370,0.329640,-0.429457,0.105124,1.330090,-0.353953,0.984411,-0.835922,-0.499119,-0.464587,0.611899,0.645152,-1.090631,-1.143969,0.517351,0.238644,0.438685,0.404028,0.315642,0.675668,0.215903,0.260159,-0.335323,-0.377313,-0.00658,0.020740,0.310986,0.259991,0.259950,0.294553,-0.723463,0.018400,-1.275148,0.018400,0.283079,0.245080,0.072477,-1.271294,-0.913535,-0.870596,-0.146491,0.005521,-0.415672,-0.024501,-0.780617,-0.610755,0.640416,0.821246,-0.650386,0.309849,0.910016,-0.180240,1.115103,0.232082,0.339199,0.286760,1.171163,0.875352,0.232415,0.059757,0.793524,-0.651386,1.252544,0.803887,-0.146643,0.323493,0.451813,0.508120,-0.257893,-0.305978,-0.00658,-0.092346,-0.696960,-0.855537,-0.856031,-0.864567,0.272322,0.002126,-1.497541,0.002126,0.528849,-0.518779,-0.086670,-0.337451,-0.493943,0.090859,0.572924,0.327995,-0.238574,0.469161,-0.553405,-0.419473,1.129638,-2.343594,-0.249858,0.503179,0.300624,-0.396751,0.135442,0.00357,0.054206,-0.024140,1.260597,0.956640,-0.502896,-0.038321,0.324958,0.524516,0.259806,-0.300244,-0.275138,-0.403171,-0.193400,0.148142,-0.696953,-0.495119,-0.00658,-0.090628,-0.146320,-0.279804,-0.280312,0.497188,0.182617,-0.000707,-1.454488,-0.000707,0.568708,0.839245,-0.106287,-1.093475,-0.389617,-0.260064,0.619213,0.351058,-0.276128,0.503885,-0.238885,-0.165400,0.634033,-1.881162,-0.269365,0.039270,1.148408,-0.437189,0.308455,0.00089,-0.184162,-0.717110,0.563632,0.191763,-0.489015,-0.392581,0.080799,0.502293,0.561619,0.008531,0.484458,1.184785,1.874865,1.841020,0.071693,-0.404921,-0.00658,0.081340,0.506763,0.509901,0.509367,0.241288,0.134404,-0.855991,-0.053990,-0.855991,0.170502,-0.746688,0.574762,-1.386567,-1.289916,-0.367996,0.828898,0.747733,-0.149963,1.075745,-0.280436,-0.495021,0.435199,0.342729,-0.929532,1.419999,0.977137,0.135562,0.594909,0.00089,-1
7258,0.631507,-0.202824,-0.310954,-0.571658,-0.626463,0.315745,0.273797,-0.094389,-0.212931,-0.044814,-0.112769,0.264807,0.204570,0.206002,0.138376,0.100738,0.184377,-0.00658,-0.075442,-0.200983,-0.114701,-0.114816,-0.465789,0.142117,-0.336627,-1.044591,-0.336627,-0.635454,-1.175504,0.290772,-0.714460,-1.764775,1.368897,0.258930,0.328968,-0.450466,-1.248813,-1.870489,-2.154305,-0.347656,1.958813,0.065962,-0.313044,1.035306,-0.582320,-0.225963,1.911660,-0.805467,-1.011774,-1.044562,-0.966055,0.195908,-0.076127,-0.458181,-0.564659,-0.506149,-0.539549,-0.894869,-0.883029,0.749123,0.635191,-0.268811,-0.322824,-0.00658,0.013238,-0.111731,-0.054673,-0.054672,0.050507,0.130511,0.138827,-1.157687,0.138827,-0.621898,-0.867000,0.081671,-1.278642,-1.988037,0.864730,-0.129223,0.359411,-1.215484,-0.918119,-0.522611,-0.904379,-0.657227,1.627951,0.439851,0.418531,0.132922,-0.874589,0.086764,1.253955,-0.975665,-1.064139,0.357616,0.345433,-1.325995,-1.476415,0.544406,0.075114,0.234388,-0.605685,-0.354101,-0.204981,0.288812,0.230776,-0.593253,-0.625080,-0.00658,-0.035603,-0.428297,-0.376925,-0.376857,-0.375843,-1.000027,-0.002329,-1.108873,-0.002329,-0.895795,-0.702997,-0.303633,-1.214759,-1.423426,-0.065876,-0.675776,-0.460133,-0.532250,-0.952712,-1.244193,-1.462133,-0.040250,0.445029,-0.244108,-0.009605,0.543063,-1.250035,1.461905,-0.466393,-0.163130,-0.253487,-0.865036,-0.646653,0.159168,-0.014272,0.141145,-0.121927,0.241939,-0.429981,-2.140408,-1.597856,0.680129,0.388793,-0.257893,-0.461972,-0.00658,-0.007625,0.209488,0.015945,0.015950,-1.289010,0.165844,-1.008376,-1.072761,-1.008376,0.172453,-1.138717,0.328388,-0.099422,-1.474119,1.491497,0.715804,0.667488,-0.328222,-1.265154,-2.451990,-2.575593,0.249260,1.767908,-0.249858,-0.211327,0.900897,-0.251769,-0.284993,0.00357,-0.185488,-0.283719,-0.952387,-0.707169,-0.377570,-0.834221,0.491577,0.937803,0.924454,-0.286635,-1.426104,-0.887141,0.754265,0.434918,-0.299189,-0.526350,-0.00658,-0.090628,0.136870,0.022194,0.022203,0.292871,-0.246771,0.863246,-1.161626,0.863246,0.177397,0.630010,0.352370,-0.356225,-1.513754,1.316629,-0.149283,-0.488718,-0.377213,-0.428082,0.328317,0.271102,0.634033,0.951849,0.373578,0.039270,-0.312943,-0.281932,-0.841058,0.00089,-0.698946,-0.717110,0.702423,0.773601,-0.980128,-1.452085,0.520128,0.238524,0.426334,-1.471431,-1.096374,-0.863560,0.634817,0.646546,-0.358719,-0.590630,-0.00658,-0.003876,-0.737123,-0.701061,-0.699968,-0.743629,-1.193788,-0.011873,-1.240992,-0.011873,-0.042387,-0.642025,0.382291,-0.345406,-0.646043,0.510088,-1.443973,-0.350335,0.004473,-0.209949,0.352905,0.301263,0.235932,0.016281,-0.603992,0.868482,0.543632,-0.929789,1.170948,0.00089,8
2386,-0.681826,-0.005730,-0.001929,0.014070,0.013248,-0.017154,-0.013702,-0.150182,-0.094567,-0.110076,0.033535,-0.031645,-0.021132,0.035235,0.036656,-0.019367,-0.013987,-0.00658,-0.007497,-0.021274,-0.023063,-0.023064,-0.020779,-0.019354,-0.003544,-0.047487,-0.003545,0.017555,-0.001756,0.017442,-0.110797,-0.139016,-0.001501,0.002744,-0.010752,0.015783,0.055256,-0.047500,-0.006144,-0.110448,0.018268,0.065962,0.031699,0.118089,-0.015272,0.016283,-0.001937,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.00658,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.020129,-0.016556,0.023406,0.021431,-0.042845,-0.039299,-0.187685,-0.127006,-0.146191,0.035462,-0.026867,-0.029662,0.030398,0.031400,-0.041311,-0.030891,-0.00658,-0.008044,-0.031536,-0.032130,-0.032135,-0.029435,-0.048615,-0.002329,-0.049286,-0.002329,0.000716,-0.004775,-0.000452,-0.132651,-0.152585,-0.008676,-0.002646,-0.028478,0.033599,0.059791,-0.078879,-0.028412,-0.153264,0.028046,0.069342,0.020868,0.150282,-0.035511,0.042704,0.014355,-0.021850,-0.015143,0.015482,0.014742,-0.020620,-0.021002,-0.133044,-0.070689,-0.104554,0.049191,-0.000208,0.026909,0.030249,0.030814,-0.029795,-0.022353,-0.00658,-0.007625,-0.024029,-0.022503,-0.022497,-0.015680,-0.008393,0.002126,-0.053290,0.002126,-0.005746,-0.002164,0.009112,-0.099422,-0.126377,0.018099,0.001406,-0.011497,0.007959,0.035583,-0.035609,-0.015201,-0.102891,0.005836,0.055541,0.026842,0.100533,-0.034297,-0.004703,0.00357,-0.031399,-0.024140,0.012026,0.015847,-0.031080,-0.031020,-0.133245,-0.084142,-0.119993,0.053584,0.003117,0.032403,0.044253,0.043860,-0.048745,-0.042261,-0.00658,-0.005576,-0.020172,-0.017197,-0.017187,-0.013603,-0.016367,-0.000707,-0.058286,-0.000707,-0.018258,0.002303,-0.000443,-0.110475,-0.139808,0.039308,0.004417,-0.008846,0.001855,0.037901,-0.049817,-0.019899,-0.122364,0.007512,0.052107,0.039270,0.104586,-0.049045,0.001918,0.00089,-0.037081,-0.021951,0.036225,0.039149,-0.053350,-0.042011,-0.121054,-0.059950,-0.148628,0.039688,0.017082,0.011801,0.022555,0.020869,-0.087719,-0.067270,-0.00658,-0.003876,-0.028242,-0.028304,-0.028294,-0.054187,-0.067481,-0.011873,-0.053990,-0.011873,-0.042387,-0.014049,-0.041143,-0.085115,-0.130945,0.076467,0.017158,0.015688,0.004473,0.047190,-0.069322,-0.017250,-0.162600,0.016281,0.047090,0.041205,0.110128,-0.028338,0.018869,0.00089,-10