In [1]:
# Target variable 'spread_a' is most predicted by stat differences which should be used.

# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

## 4.2 Introduction<a id='4.2_Introduction'></a>

## 4.3 Imports<a id='4.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 4.4 Functions<a id='4.4_Imports'></a>

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 4.5 Load Data<a id='4.5_Load_Data'></a>

In [4]:
df = rcp('53AAprediction_stats_2010_2018.csv')
p(df)

(10266, 107)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,team_id_a,spread_a,away_home_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,team_id_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,Celtics,BOS,Boston,1610612738,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami,1610612748,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,1610612756,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland,1610612757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,1610612745,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles,1610612747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,1610612750,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento,1610612758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,Heat,MIA,Miami,1610612748,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia,1610612755,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,Warriors,GSW,Golden State,1610612744,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston,1610612745,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,Cavaliers,CLE,Cleveland,1610612739,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,Cavaliers,CLE,Cleveland,1610612739,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,Cavaliers,CLE,Cleveland,1610612739,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,Cavaliers,CLE,Cleveland,1610612739,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

## 4.6 Get Indicator Variables<a id='4.6 Get_Indicator_Variables'></a>

In [5]:
# Create dummy or indicator features for categorical variables Hint: you’ll need
# to think about your old favorite pandas functions here like get_dummies().

df.select_dtypes('object')

,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b
0,Celtics,BOS,Boston,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami
1,Suns,PHX,Phoenix,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland
2,Rockets,HOU,Houston,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles
3,Timberwolves,MIN,Minnesota,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento
4,Heat,MIA,Miami,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia
...,...,...,...,...,...,...,...,...,...,...
10261,Warriors,GSW,Golden State,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston
10262,Cavaliers,CLE,Cleveland,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State
10263,Cavaliers,CLE,Cleveland,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State
10264,Cavaliers,CLE,Cleveland,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State
10265,Cavaliers,CLE,Cleveland,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State

In [6]:
column_names_categorical_list = list(df.select_dtypes('object').columns) + ['team_id_a', 'team_id_b', 'away_home_a']
pl(column_names_categorical_list)

13

['TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'team_id_a',
 'team_id_b',
 'away_home_a']

In [7]:
column_names_categorical_drop_list = [k for k in column_names_categorical_list if
                                     not k in ['away_home_a']]
pl(column_names_categorical_drop_list)

12

['TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'team_id_a',
 'team_id_b']

<font color='red'> add matchup???????????</font>

In [8]:
column_names_categorical_list_cleaned = [k for k in column_names_categorical_list if
                                     not k in column_names_categorical_drop_list]
pl(column_names_categorical_list_cleaned)

1

['away_home_a']

In [9]:
df_indicator_variables = pd.get_dummies(df[column_names_categorical_list_cleaned])
p(df_indicator_variables)

(10266, 1)

       away_home_a
0                1
1                0
2                0
3                1
4                0
10261            0
10262            0
10263            0
10264            1
10265            1

In [10]:
#cat drop
df = df.drop(columns=column_names_categorical_list)
p(df)

(10266, 94)

,game_id,spread_a,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,-8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,-10,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,-9,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,10,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,19,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,8,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,23,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [11]:
df_numeric = df.select_dtypes('number')
p(df_numeric)

(10266, 94)

,game_id,spread_a,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,-8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,-10,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,-9,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,10,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,19,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,8,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,23,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [12]:
column_names_numeric_list  = list(df_numeric.columns)
pl(column_names_numeric_list)

94

['game_id',
 'spread_a',
 'E_OFF_RATING_cma_diff',
 'OFF_RATING_cma_diff',
 'E_DEF_RATING_cma_diff',
 'DEF_RATING_cma_diff',
 'E_NET_RATING_cma_diff',
 'NET_RATING_cma_diff',
 'AST_PCT_cma_diff',
 'AST_TOV_cma_diff',
 'AST_RATIO_cma_diff',
 'OREB_PCT_cma_diff',
 'DREB_PCT_cma_diff',
 'REB_PCT_cma_diff',
 'E_TM_TOV_PCT_cma_diff',
 'TM_TOV_PCT_cma_diff',
 'EFG_PCT_cma_diff',
 'TS_PCT_cma_diff',
 'USG_PCT_cma_diff',
 'E_USG_PCT_cma_diff',
 'E_PACE_cma_diff',
 'PACE_cma_diff',
 'PACE_PER40_cma_diff',
 'POSS_cma_diff',
 'PIE_cma_diff',
 'duration_minutes_cma_diff',
 'w_pct_cma_diff',
 'min_cma_diff',
 'fgm_cma_diff',
 'fga_cma_diff',
 'fg_pct_cma_diff',
 'fg3m_cma_diff',
 'fg3a_cma_diff',
 'fg3_pct_cma_diff',
 'ftm_cma_diff',
 'fta_cma_diff',
 'ft_pct_cma_diff',
 'oreb_cma_diff',
 'dreb_cma_diff',
 'reb_cma_diff',
 'ast_cma_diff',
 'stl_cma_diff',
 'blk_cma_diff',
 'tov_cma_diff',
 'pf_cma_diff',
 'pts_cma_diff',
 'spread_cma_diff',
 'away_home_cma_diff',
 'E_OFF_RATING_sm_cma_diff',
 'OFF_RATING_sm_cma_diff',
 'E_DEF_RATING_sm_cma_diff',
 'DEF_RATING_sm_cma_diff',
 'E_NET_RATING_sm_cma_diff',
 'NET_RATING_sm_cma_diff',
 'AST_PCT_sm_cma_diff',
 'AST_TOV_sm_cma_diff',
 'AST_RATIO_sm_cma_diff',
 'OREB_PCT_sm_cma_diff',
 'DREB_PCT_sm_cma_diff',
 'REB_PCT_sm_cma_diff',
 'E_TM_TOV_PCT_sm_cma_diff',
 'TM_TOV_PCT_sm_cma_diff',
 'EFG_PCT_sm_cma_diff',
 'TS_PCT_sm_cma_diff',
 'USG_PCT_sm_cma_diff',
 'E_USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'POSS_sm_cma_diff',
 'PIE_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'w_pct_sm_cma_diff',
 'min_sm_cma_diff',
 'fgm_sm_cma_diff',
 'fga_sm_cma_diff',
 'fg_pct_sm_cma_diff',
 'fg3m_sm_cma_diff',
 'fg3a_sm_cma_diff',
 'fg3_pct_sm_cma_diff',
 'ftm_sm_cma_diff',
 'fta_sm_cma_diff',
 'ft_pct_sm_cma_diff',
 'oreb_sm_cma_diff',
 'dreb_sm_cma_diff',
 'reb_sm_cma_diff',
 'ast_sm_cma_diff',
 'stl_sm_cma_diff',
 'blk_sm_cma_diff',
 'tov_sm_cma_diff',
 'pf_sm_cma_diff',
 'pts_sm_cma_diff',
 'spread_sm_cma_diff',
 'away_home_sm_cma_diff']

In [13]:
column_names_numeric_remove_list = ['USG_PCT_sm_cma_diff', 'E_PACE_sm_cma_diff', 'PACE_sm_cma_diff', 'PACE_PER40_sm_cma_diff', 'duration_minutes_sm_cma_diff', 'min_sm_cma_diff']
pl(column_names_numeric_remove_list)

6

['USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'min_sm_cma_diff']

In [14]:
column_names_numeric_remove_list_check = [k for k in column_names_numeric_remove_list if k in column_names_numeric_list]
pl(column_names_numeric_remove_list_check)

6

['USG_PCT_sm_cma_diff',
 'E_PACE_sm_cma_diff',
 'PACE_sm_cma_diff',
 'PACE_PER40_sm_cma_diff',
 'duration_minutes_sm_cma_diff',
 'min_sm_cma_diff']

In [15]:
#diff drop
df = df.drop(columns=column_names_numeric_remove_list_check)
p(df)

(10266, 88)

,game_id,spread_a,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,-8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,-10,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,-9,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.002111,0.111111,0.106000,0.028778,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,10,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.000000,0.500000,-0.205000,-0.141500,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,19,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.000667,1.000000,-0.199333,-0.427667,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,8,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,-0.000250,1.500000,-0.182000,-0.570750,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,23,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,-0.000600,1.400000,-0.173200,-0.656600,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [16]:

df = pd.concat([df, df_indicator_variables], axis=1)
p(df)

(10266, 89)

,game_id,spread_a,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a
0,21000001,-8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
1,21000002,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2,21000003,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
3,21000009,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
4,21000006,-10,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
10261,41700317,-9,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.002111,0.111111,0.106000,0.028778,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,0
10262,41700401,10,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.000000,0.500000,-0.205000,-0.141500,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,0
10263,41700402,19,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.000667,1.000000,-0.199333,-0.427667,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,0
10264,41700403,8,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,-0.000250,1.500000,-0.182000,-0.570750,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,1
10265,41700404,23,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,-0.000600,1.400000,-0.173200,-0.656600,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,1

In [17]:
df = df.drop(columns=['game_id'], axis=1)
p(df)

(10266, 88)

,spread_a,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a
0,-8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
1,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
2,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
3,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1
4,-10,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
10261,-9,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.002111,0.111111,0.106000,0.028778,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,0
10262,10,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.000000,0.500000,-0.205000,-0.141500,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,0
10263,19,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.000667,1.000000,-0.199333,-0.427667,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,0
10264,8,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,-0.000250,1.500000,-0.182000,-0.570750,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,1
10265,23,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,-0.000600,1.400000,-0.173200,-0.656600,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,1

In [18]:
scaler = StandardScaler() 
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [19]:
# Fitting data to the scaler object
scaled_df = scaler.fit_transform(df) 
scaled_df

array([[-0.5693137 , -0.01237877, -0.0097064 , ...,  0.02098294,
         0.00288562,  1.00058462],
       [ 1.03909025, -0.01237877, -0.0097064 , ...,  0.02098294,
         0.00288562, -0.99941572],
       [ 0.16177901, -0.01237877, -0.0097064 , ...,  0.02098294,
         0.00288562, -0.99941572],
       ...,
       [ 1.40463661, -0.04313306,  0.17113178, ...,  0.96761057,
        -0.54031476, -0.99941572],
       [ 0.60043463, -0.23138657, -0.07775376, ...,  1.23056269,
        -0.81191495,  1.00058462],
       [ 1.69707369, -0.7635289 , -0.56527111, ...,  1.15693609,
        -0.32303461,  1.00058462]])

In [20]:
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
p(scaled_df)

(10266, 88)

,spread_a,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a
0,-0.569314,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585
1,1.039090,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416
2,0.161779,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416
3,0.088670,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.006580,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585
4,-0.715532,9.817809,9.822670,11.056652,11.077836,-0.842855,-0.879667,6.917898,2.089919,5.236731,3.619465,6.151548,4.505173,7.995332,7.815429,8.623899,9.718648,16.880664,17.046458,13.286464,13.578067,13.578001,13.301359,5.790387,16.435521,-0.047253,16.435523,7.391881,11.120207,8.888809,2.922898,3.102298,6.870588,4.662543,5.088790,9.570603,4.405550,7.812711,8.416689,3.997956,5.388576,3.763676,7.139358,7.148882,8.305956,0.946213,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416
10261,-0.642423,0.270933,0.117999,-0.864837,-0.770541,1.046285,0.854871,1.174691,0.437857,1.278895,-0.060581,-0.053212,0.086176,-0.160228,-0.216878,0.047864,0.082213,-0.006580,0.169571,0.521060,0.564243,0.564042,0.514165,0.880644,-0.003876,0.442873,-0.003876,1.085583,0.598520,0.636803,-1.342301,-1.350048,-0.381715,0.151376,-0.014857,0.536612,0.560678,0.577839,0.751100,1.567171,0.508718,0.030765,0.348885,-0.201171,0.522450,-0.839532,0.000029,0.841009,0.610506,-0.841009,-0.610506,0.840983,0.609358,1.164810,0.907359,1.417544,-0.288745,-0.142689,-0.011273,-0.176247,-0.256165,0.676177,0.768611,0.943420,0.132847,0.749084,0.072579,0.882034,-0.035582,0.905600,-0.370799,-1.435101,0.581567,-0.103643,-0.561451,1.199410,-0.133537,0.172852,0.054407,1.357550,-0.061233,0.920128,0.031477,0.472743,0.621789,-0.621789,-0.178181,-0.999416
10262,0.746653,0.059381,0.324937,0.709446,0.806097,-0.593728,-0.452036,-1.321893,0.598677,-1.138425,0.431525,-0.113029,0.069382,-0.358340,-0.275761,-0.003768,0.028782,-0.006580,-0.121777,-1.111225,-1.309971,-1.309940,-1.108638,-0.424829,0.138827,-0.491187,0.138827,-0.758497,-1.004784,0.105984,-0.610215,-0.644189,-0.056493,0.388806,0.682642,-0.723997,-0.392324,-0.920646,-0.922374,-1.620368,-1.908827,-0.173779,-0.800272,0.355651,-0.588240,0.411445,0.000029,-1.050596,-0.938264,1.050596,0.938264,-1.045810,-0.938357,-2.606269,-0.952064,-2.481998,0.327201,0.165143,0.013093,-0.487255,-0.426714,-1.434394,-1.447539,-0.037969,0.693003,-1.529759,-0.560865,-0.909712,1.254063,-1.576715,-0.024232,-0.433556,0.104821,-0.134644,-0.055083,-0.206441,1.101473,-1.035696,-0.142527,-2.421169,0.390785,-1.550545,-0.289047,0.080677,-0.915020,0.915020,0.002886,-0.999416
10263,1.404637,-0.043133,0.171132,0.647935,0.741567,-0.635103,-0.542549,-1.404758,0.281214,-1.229249,0.610690,0.166351,0.253307,-0.227992,-0.161459,-0.079494,-0.129785,-0.006580,-0.128883,-0.918721,-1.080789,-1.080858,-0.852406,-0.570016,0.138827,-0.662461,0.138827,-0.530833,-0.679113,0.075593,-0.673874,-0.657763,-0.098041,0.172961,0.580569,-0.997916,0.034884,-0.569439,-0.418532,-1.574504,-2.043135,-0.020371,-0.626158,0.216445,-0.518821,0.430543,-0.417947,-0.982692,-1.049452,0.982692,1.049452,-0.979522,-1.049550,-2.643528,-1.863747,-2.648230,0.879379,0.441106,1.008335,0.045070,0.058004,-1.426548,-1.559654,0.271943,1.413205,-1.488236,-1.625423,-0.756134,1.334110,-1.467022,-0.336142,-0.247428,-0.230545,-0.289646,0.046190,-0.882885,2.071838,-0.693654,0.716824,-2.525811,-0.348881,-1.418188,0.191739,0.080677,-0.967611,0.967611,-0.540315,-0.999416
10264,0.600435,-0.231387,-0.077754,0.788256,0.884110,-0.941450,-0.925847,-1.062673,-0.132324,-1.141918,0.572468,0.313430,0.302087,0.037458,0.084464,-0.320442,-0.269394,-0.006580,-0.143095,-0.697002,-0.829432,-0.829477,-0.693786,-0.676487,-0.003876,-0.962416,-0.003876,-0.735730,-0.716691,-0.129035,-0.896683,-0.712060,-0.325840,0.475144,0.767702,-0.720696,0.133470,-0.522611,-0.328560,-1.391048,-1.550672,-0.071507,-0.312751,-0.201171,-0.614271,0.755224,-0.417947,-1.227631,-1.388070,1.227631,1.388070,-1.225273,-1.388182,-1.785721,-1.423358,-2.232649,0.866336,0.434587,0.898689,-0.038808,-0.056444,-1.877692,-1.855359,-0.154186,2.133406,-1.361227,-2.157702,-1.140080,1.334110,-1.846377,-0.726030,-0.553210,-0.380966,0.097860,0.210760,-0.281190,2.160053,-0.933084,0.582550,-2.054924,0.298327,-1.451277,-0.000575,-0.597897,-1.230563,1.230563,-0.811915,1.000585
10265,1.697074,-0.763529,-0.565271,0.838233,0.913967,-1.489882,-1.439374,-1.077546,-1.702932,-1.515694,0.830465,0.350024,0.346070,0.416476,0.482788,-0.874623,-0.784739,-0.006580,-0.157307,-0.528743,-0.680773,-0.680820,-0.547368,-1.061232,-0.003876,-1.362256,-0.003876,-1.122759,-0.478700,-0.734817,-0.960343,-0.576317,-0.596619,0.475144,0.784715,-0.788664,0.593540,-0.382128,0.031326,-1.620368,-1.282056,-0.071507,0.105124,-0.173330,-0.926653,1.261345,0.000029,-1.238786,-1.308216,1.238786,1.308216,-1.236914,-1.310347,-1.724243,-1.455808,-2.176545,1.034163,0.518462,1.183767,0.110408,0.117247,-1.790601,-1.834337,-0.316890,1.989366,-1.296745,-2.477070,-1.001859,1.430166,-1.788788,-0.585671,-0.289971,-0.415983,-0.078843,0.096827,-0.485194,2.212982,-0.707336,0.792017,-1.939819,0.242852,-1.232887,0.172508,-0.570754,-1.156936,1.156936,-0.323035,1.000585

In [21]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df.drop(columns='spread_a'), 
                                                    scaled_df.spread_a, test_size=0.3, 
                                                    random_state=2909)

In [22]:
X_train.shape

(7186, 87)

In [23]:
#export dataframes

#https://stackoverflow.com/questions/30829748/multiple-pandas-dataframe-to-one-csv-file

In [24]:
df_train = pd.concat([X_train, y_train], axis=1)
p(df_train)

(7186, 88)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a,spread_a
3134,-0.018902,-0.016231,1.321667,1.343521,-1.228430,-1.303603,-1.318706,-1.481543,-1.903444,0.921242,-2.507811,-0.529573,0.446845,0.430833,-0.575159,0.121855,-0.00658,-0.050716,0.174116,0.184420,0.184667,0.087111,-0.946293,-0.146579,-0.692156,-0.146579,-1.441489,-0.954681,-0.761156,0.058212,-0.155516,0.712864,2.741520,2.536967,1.145528,-0.129427,-0.499197,-0.454521,-1.849687,0.374410,0.695530,0.314062,1.079520,0.019169,1.242246,-1.671873,-0.972992,-0.574376,0.972992,0.574376,-0.982755,-0.574453,0.482854,-0.689375,-0.331362,0.453289,0.228158,0.772176,0.513350,0.650436,-0.657641,-0.640307,-0.502838,-1.467600,-0.218142,-0.622246,-1.140080,-0.426922,-0.790581,-0.024232,-0.034710,-0.003680,0.702370,1.160200,-1.334506,0.042893,0.400880,0.340858,-0.223699,0.020952,0.037745,-0.000575,-2.090760,-0.652068,0.652068,1.632487,-0.999416,0.819762
8383,-0.099050,-0.203595,-0.808132,-0.713716,0.644865,0.483580,1.728190,1.736950,1.631711,-1.010155,0.087533,-0.470397,-0.467579,-0.507828,0.560740,0.066701,-0.00658,-0.015186,0.085137,0.074908,0.074809,0.087111,0.662864,-0.003876,1.124071,-0.003876,0.038328,-0.153029,0.213363,1.076767,0.781105,0.678480,-1.100526,-0.236015,-1.452563,-0.918119,1.069529,0.319236,1.475443,-0.610516,0.797801,-0.417220,-1.175610,-0.119667,-0.495752,0.000029,1.384239,1.275388,-1.384239,-1.275388,1.384224,1.275392,-0.650163,-0.418961,-0.082013,-0.146715,-0.071707,0.552885,0.329894,0.273434,1.586312,1.831840,0.891767,1.413205,1.547778,2.450526,0.357308,-2.027860,1.476410,0.911499,0.124828,1.707674,1.539383,1.691886,-0.160638,-1.544978,1.529618,0.260294,-0.328340,-2.382964,2.221644,0.432133,-2.362190,1.504139,-1.504139,1.632487,-0.999416,-0.715532
7423,0.556110,0.547723,0.560475,0.683780,0.017205,-0.111224,0.252549,0.728169,0.622166,0.229666,-1.268548,-0.368039,-0.561384,-0.570175,0.448871,0.380389,-0.00658,-0.008080,-0.414064,-0.477483,-0.477456,-0.144717,0.089375,0.281530,0.373883,0.281530,0.584722,0.423159,0.227545,0.949448,0.943996,0.288787,-0.712005,-1.120647,0.844477,0.002022,0.788563,0.607145,0.626962,-1.908827,0.797801,-0.521689,-0.173330,0.418323,-0.008731,0.835980,-0.513833,-0.527205,0.513833,0.527205,-0.513886,-0.523911,-0.286039,-0.251561,-0.269025,0.644595,-1.124856,-0.262426,0.240646,0.237529,-0.547797,-0.640307,0.581855,-0.507332,-0.604055,0.553294,0.088546,1.013922,-0.565101,-0.024232,0.337545,-0.158211,-1.157660,-1.624824,0.450235,0.748613,-0.009571,0.448277,-0.223699,0.144230,0.302460,0.480211,1.890209,-0.581947,0.581947,0.546086,-0.999416,1.623964
2528,-0.952155,-0.852996,0.086268,0.042980,-0.977366,-0.882992,-0.515762,-0.081084,-0.681277,2.626812,0.005854,2.378467,-0.394616,-0.309012,-1.152861,-1.548392,-0.00658,-0.105670,0.256468,0.219933,0.219938,0.520672,-1.192465,0.376666,0.098365,0.376665,0.325185,1.490359,-0.995229,-0.595361,0.193794,-1.862357,-1.165280,-0.405002,-1.634884,1.688945,-0.069944,0.871062,-0.236808,0.177424,-2.781703,-0.113100,1.001565,-0.382878,0.918201,-0.780192,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416,0.746653
10064,-0.095322,-0.018096,0.455715,0.277340,-0.506578,-0.283939,0.008202,-0.123970,0.063248,-0.684075,-0.034915,-0.180116,-0.021720,0.046363,0.195875,0.192521,-0.00658,-0.135989,0.180541,0.231867,0.231643,0.221328,-0.317149,-0.003876,-0.751248,-0.003876,0.083861,-0.077874,0.158660,0.185531,-0.155516,0.361854,0.108207,0.189289,0.113047,-0.753808,0.179804,-0.274577,0.076595,0.911642,0.030765,0.070301,-0.423900,0.158005,0.335049,-0.835922,1.374539,1.780788,-1.374539,-1.780788,1.374523,1.780814,2.708242,2.292911,2.567320,0.870684,0.436760,1.851760,-0.630081,-0.534429,1.005709,1.007791,1.821504,-0.027198,1.628380,-0.298601,1.163594,0.533641,0.708558,1.535320,0.124828,1.426558,0.516367,0.552558,0.162722,0.042893,1.016555,0.824243,3.124827,0.760618,0.037745,-0.289047,-1.276471,1.872272,-1.872272,1.632487,-0.999416,0.307998
3378,-1.174518,-1.003384,1.645557,1.503400,-2.614035,-2.438719,-0.579292,-0.263904,-1.131438,0.463775,-1.348773,-0.788668,-0.929084,-0.809170,-1.557884,-1.439692,-0.00658,-0.036504,-0.101063,-0.129497,-0.129447,-0.169121,-2.231198,-0.003876,-0.435995,-0.003876,-0.986161,0.285375,-1.381120,-1.119492,-0.114794,-2.811566,0.151376,0.342399,-0.443959,0.133470,-2.255234,-1.660142,-1.092933,0.508718,0.081900,-1.009210,-0.702311,-0.996071,2.416826,-1.253898,0.035864,-0.001589,-0.035864,0.001589,0.035822,0.001728,-0.922832,0.196554,-0.206688,-0.723531,-0.359983,-1.297028,-0.896358,-0.920408,0.179265,0.234194,-0.657794,-0.027198,0.436445,1.157184,0.242125,-0.320193,0.269786,-0.128202,-1.098298,0.173867,-0.289646,-0.662725,0.605846,-1.721408,-0.420021,-1.377845,-0.432982,0.760618,-0.756400,-1.058306,-0.281229,0.014077,-0.014077,-0.540315,1.000585,-0.349986
1965,0.229928,0.230790,-0.150739,-0.311130,0.351722,0.523296,-0.936250,0.030585,-0.827527,-0.322162,-0.963834,-1.338044,-1.142593,-1.120902,-0.514922,-0.298694,-0.00658,-0.079141,-1.153290,-1.066171,-1.066141,-0.913413,0.153499,0.138827,0.501964,0.138827,-0.576365,-0.428597,-0.244519,-1.024003,-1.092138,-0.135291,0.518313,0.376423,0.163888,0.330643,0.203218,0.337230,-1.184661,-1.058209,0.337579,-1.566377,0.411333,-0.510144,-0.533950,0.000029,-2.476575,-1.585176,2.476575,1.585176,-2.486369,-1.585297,-0.086195,-1.384727,-1.359927,2.696784,-2.996478,0.029961,1.258467,1.673729,-2.069919,-1.632530,-2.827180,-0.027198,-2.196558,0.486332,-2.061549,0.053359,-2.052052,-0.959963,-0.991940,-0.191090,1.074376,0.856379,0.391005,-0.221752,-0.830471,-0.787041,-1.060831,-2.937713,-1.947618,1.730257,0.080677,-1.598696,1.598696,-1.626716,1.000585,1.039090
1161,-0.466237,-0.596032,-0.951336,-0.901526,0.431830,0.271150,-0.390189,-0.673265,-0.555054,-0.160913,-0.082768,0.266902,0.500312,0.389269,-0.112194,-0.047054,-0.00658,0.134041,-0.381091,-0.350132,-0.350204,-0.217927,0.252710,0.138827,-0.334310,0.138827,-0.986161,-0.854475,-0.256675,0.153702,0.604640,-1.215543,0.129792,0.257338,-0.228590,-0.753808,0.905632,0.283247,-0.726022,-0.252361,0.388715,0.418531,-0.034125,-0.657658,-0.352510,0.835980,-1.593826,-1.847984,1.593826,1.847984,-1.589051,-1.858225,-0.137003,-1.276561,-1.282005,-1.068461,-0.532369,-2.129208,0.658242,0.623508,-0.924404,-0.800072,0.891767,-0.747399,-1.903460,-0.246520,-2.637468,-1.467531,-1.448740,0.599589,-0.034710,0.982691,0.609368,0.628514,-0.059622,-1.015687,-1.446147,-1.753811,-1.688679,-0.718714,-0.756400,0.576369,-0.597897,-1.861648,1.861648,0.002886,-0.999416,-0.569314
2771,-1.113941,-1.106853,-0.899436,-0.889968,-0.231041,-0.241453,1.173629,-2.120647,0.444011,1.095629,-0.975798,0.104568,2.734147,2.737653,-0.924534,-0.531375,-0.00658,-0.072035,-0.395881,-0.433009,-0.433007,-0.461957,0.558813,-0.003876,-0.807939,-0.003876,-0.917862,-1.104991,-0.052046,-2.901964,-3.168995,0.103969,0.561482,0.019168,1.272546,0.462092,0.835391,0.895055,0.374710,-0.610516,1.155752,2.090032,0.383492,-1.265066,0.277752,0.418004,1.015619,0.931716,-1.015619,-0.931716,1.005895,0.941813,0.076391,0.021429,1.040058,-0.172802,-0.084744,0.670965,1.270588,1.189012,1.727540,1.646849,1.356636,-1.467600,1.716309,-0.622246,1.624329,-0.907203,2.079722,-0.336142,-1.630092,1.870425,-0.971657,-1.574187,1.810104,-1.015687,2.247906,1.146500,0.822715,0.020952,0.037745,1.153313,0.894966,0.820464,-0.820464,1.632487,-0.999416,-0.276877
9937,0.411658,0.267144,-0.741816,-0.554801,1.066532,0.796684,-0.120345,-0.566747,-0.167305,-0.362773,-0.276997,-0.150528,0.497225,0.392732,0.448871,0.707866,-0.00658,-0.072035,-0.348482,-0.345053,-0.344853,-0.059307,0.822570,0.281530,0.506464,0.281530,-0.485300,-0.967207,0.296430,0.408340,-0.114794,0.816018,1.165849,0.988861,0.558551,-0.589497,-0.030921,-0.346555,-0.336180,1.045950,0.388715,0.209593,0.717585,0.210069,-0.868180,0.835980,1.049571,0.845798,-1.049571,-0.845798,1.049548,0.850837,-0.233538,0.693602,0.136167,-1.690204,-0.843099,-2.702738,-1.663329,-1.773152,0.778175,1.175964,1.356636,-0.747399,0.800376,0.454712,-0.333794,-1.547578,0.571442,0.755544,0.124828,0.898850,1.539383,1.539976,0.398789,-2.206590,-0.830471,-1.995504,-0.328340,1.685201,0.831890,-1.442935,-0.190752,0.820464,-0.820464,0.002886,1.000585,-0.569314

In [25]:
df_test = pd.concat([X_test, y_test], axis=1)
p(df_test)

(3080, 88)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a,spread_a
2583,0.364128,0.314684,-0.920580,-0.982429,1.188895,1.256641,-1.064798,-0.921805,-0.600467,0.252360,-0.514153,-0.408023,0.720669,0.669828,0.574508,0.578599,-0.00658,-0.064928,0.449053,0.506638,0.506363,0.416552,1.000424,-0.146579,1.079977,-0.146579,0.607488,-0.115451,0.802937,-0.387406,-0.101220,-1.221274,0.561482,0.733678,-0.036432,0.100608,-0.101162,-0.022657,-0.496703,2.433799,0.490987,0.801583,1.385772,0.583191,-1.202410,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585,0.527325
9370,-0.726251,-0.886865,-0.028679,-0.236006,-0.661512,-0.653382,-1.661853,-0.376687,-1.774194,-0.807101,0.385914,-0.289671,-1.054252,-1.086265,-1.014029,-1.034655,-0.00658,-0.086247,-0.983940,-0.785825,-0.785623,-0.803600,-0.960811,-0.003876,-1.871279,-0.003876,-1.487022,-0.340916,-1.206882,-0.164597,-0.060497,-0.274263,-0.668836,-0.593270,-0.465613,-0.162289,-0.147990,-0.202600,-2.468849,-1.058209,-3.139654,-1.636023,0.494856,-1.447289,0.783873,1.253955,-3.175014,-2.959863,3.175014,2.959863,-3.175121,-2.960045,-1.397040,-0.488496,-2.419660,0.435898,0.219467,-0.779727,-1.174939,-1.019147,-3.199741,-3.566522,1.821504,-0.027198,-2.562932,-1.894508,-2.291917,1.654297,-2.984443,-1.895694,-1.630092,-0.743458,-0.785654,0.552558,-2.471957,1.101473,-2.472272,-1.270426,-2.525811,1.870118,-3.138836,-1.154463,-0.733612,-3.176408,3.176408,1.632487,-0.999416,1.112200
5655,-0.544521,-0.381636,0.635441,0.584578,-1.099025,-0.938778,0.475648,0.308365,0.290309,0.386136,-1.368477,-1.277268,0.254977,0.351168,-0.613022,-0.638236,-0.00658,-0.107565,-0.011115,-0.096173,-0.095999,-0.010501,-0.780537,0.138827,-1.522132,0.138827,0.152160,0.360530,-0.181712,-1.405961,-1.214306,-0.711235,-0.215561,-0.116930,-0.225624,0.560678,-0.780163,-0.292572,0.489370,0.329640,-0.429457,0.105124,1.330090,-0.353953,0.984411,-0.835922,-0.400660,-0.736104,0.400660,0.736104,-0.400711,-0.736188,-0.858476,1.350323,-0.643048,-0.224976,-0.110820,-1.353257,-2.178713,-2.230941,-0.893020,-1.195279,-0.037969,1.413205,-0.862959,-1.656424,0.011757,1.494203,-0.772299,-0.648053,0.603442,-1.493099,-0.785654,-0.510815,-1.166473,0.572183,-2.267047,-1.431554,-0.642265,1.870118,-0.756400,-2.308351,0.623537,-0.652068,0.652068,1.632487,-0.999416,-0.057549
7258,0.291436,0.402306,-1.376142,-1.278108,1.534856,1.621467,-0.564419,0.437857,-0.052028,0.799410,0.302170,-0.137733,-0.701027,-0.649840,-0.241274,-0.181492,-0.00658,0.027450,-0.146765,-0.280510,-0.280484,-0.254531,1.744507,-0.003876,1.468719,-0.003876,0.835153,0.385581,0.565892,-2.233537,-2.422412,-1.131014,0.367222,0.410447,-0.017143,0.987886,2.427531,2.406579,0.007799,-1.147748,1.002344,-0.765449,-1.593227,0.175360,-1.698981,0.000029,0.632447,0.699232,-0.632447,-0.699232,0.632417,0.699211,0.223734,-0.905707,0.229673,0.453289,0.228158,1.446916,1.080934,1.054368,0.582025,0.898478,-0.037969,0.693003,1.240024,2.046899,0.242125,-1.547578,1.083343,-1.427828,-2.268245,-0.112180,1.818388,2.223573,-0.368319,0.042893,1.324393,1.065936,0.299508,-0.903631,1.228963,1.153313,-2.497904,0.767873,-0.767873,0.002886,1.000585,-0.349986
2386,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.00658,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585,-0.715532
8109,-0.310602,-0.362993,0.036676,-0.020266,-0.326115,-0.342126,0.625443,-0.625227,0.353187,-0.510882,-0.006062,-0.803062,1.249406,1.196309,0.011722,-0.081526,-0.00658,0.112723,0.215332,0.291702,0.291403,0.209127,-0.296581,-0.003876,-0.601570,-0.003876,-0.075504,0.084962,-0.175634,0.535660,0.753957,-0.176839,-0.668836,-0.712355,0.231635,0.429230,-0.007507,0.229264,0.443506,-0.879132,0.746665,1.184635,0.634062,-0.180408,0.497390,1.671931,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416,0.161779
9743,-0.409389,-0.383501,-0.060396,0.109756,-0.334037,-0.486209,0.994087,0.385643,0.772375,-0.263635,-0.231959,-0.190512,-0.036053,-0.009056,-0.466732,-0.383149,-0.00658,0.006132,0.446749,0.337043,0.336744,0.721591,0.056708,0.424233,0.379883,0.424233,0.334291,0.711253,-0.228311,-0.642045,-0.019774,-0.953360,0.280884,0.121240,0.399791,0.166332,0.413942,0.409208,1.131464,-0.207592,0.439851,0.314062,-0.089807,0.192714,0.526038,0.835980,0.031014,0.279750,-0.031014,-0.279750,0.030971,0.279710,0.117037,-0.643019,0.245257,-0.077149,-0.039113,0.063698,1.074461,1.135154,0.715407,0.520088,0.426899,-1.467600,0.045647,0.097586,0.357308,0.053359,0.315491,1.535320,-0.194249,1.712605,-1.157660,-1.194411,-0.002106,-0.089430,0.298267,0.179729,0.299508,-1.273464,1.030426,1.297549,0.352107,0.189379,-0.189379,-1.626716,1.000585,1.770183
4546,-0.467169,-0.596032,0.630636,0.387137,-1.018917,-0.959097,-0.415686,-1.155725,-0.803074,-0.440411,-0.371296,-0.920614,0.434960,0.375414,-0.800618,-0.669260,-0.00658,0.084299,0.152053,0.354139,0.353840,0.367746,-0.744241,0.138827,-0.677159,0.138827,-0.371468,0.247797,-0.655802,-0.673874,-0.359130,-0.602350,0.647821,0.852763,-0.604374,1.152197,0.296873,0.859066,-0.519635,0.329640,-0.378322,0.453353,-0.730152,-0.206440,1.041707,-0.417947,-0.439462,-0.564268,0.439462,0.564268,-0.439514,-0.564344,0.797863,-1.801938,-0.487205,0.079374,0.041286,0.198646,1.866957,1.862231,-0.673333,-0.303961,-0.037969,-2.908003,-0.599170,-0.599926,-1.831182,-1.707672,-0.754017,-0.336142,-0.194249,-0.329182,1.818388,2.375483,-1.220404,1.366118,-0.009571,0.824243,-0.432982,-1.088548,1.626035,1.730257,-1.276471,-0.757249,0.757249,-1.626716,1.000585,0.454216
4962,-0.389818,-0.352740,-0.339115,-0.285125,-0.055860,-0.073356,-0.408249,-0.988639,-0.031069,-1.190514,0.422507,-0.529573,0.974376,1.019661,0.180386,-0.133232,-0.00658,-0.072035,0.185996,0.138584,0.138880,0.209127,-0.315939,0.138827,-0.050853,0.138827,0.789620,0.736304,0.164738,0.408340,0.197413,0.005113,-2.114999,-2.294486,0.609875,0.232057,0.367114,0.409208,0.145391,-0.162823,-0.480593,1.010520,0.689744,-0.137022,0.153610,-0.417947,-0.266065,-0.237021,0.266065,0.237021,-0.266114,-0.233293,0.546364,-0.026860,0.366036,-0.398891,0.345497,0.055264,0.781165,0.808643,0.001422,-0.091642,0.194465,-0.207248,-0.249284,0.157572,0.098145,0.293500,-0.022729,0.092734,0.005174,0.085094,-0.715903,-0.890591,0.107523,0.472941,0.195655,0.441563,0.482631,-0.996089,-0.408962,0.828782,0.827109,-0.283935,0.283935,0.002886,-0.999416,0.746653
5706,-0.235114,-0.458073,-0.062318,0.005739,-0.168540,-0.462195,-0.430559,1.448727,-0.052028,-2.189059,-0.509227,-1.382825,-2.012811,-2.118446,-0.681865,-0.703732,-0.00658,0.134041,-0.915691,-0.831042,-0.830964,-0.571771,-0.144134,0.281530,-0.052652,0.281530,-0.280402,0.022333,-0.280987,-1.374131,-1.200732,-0.506359,-0.733589,-0.797416,0.114238,-0.556635,0.390528,-0.004662,-0.473771,-1.774519,0.439851,-2.193190,-0.535265,-0.883267,0.449642,0.000029,-0.468564,-0.341892,0.468564,0.341892,-0.468616,-0.341959,-0.848314,0.175951,-0.144350,-2.877169,2.909561,0.029961,-0.644129,-0.561358,-0.422261,-0.791663,-2.362311,-0.027198,-0.115558,-0.239080,1.163594,1.013922,0.562301,-2.831425,-1.789630,-1.532554,-0.785654,-0.206994,-1.424832,0.572183,0.195655,0.501986,-0.014416,-0.718714,2.023108,-0.865991,-0.190752,-0.336525,0.336525,-1.626716,-0.999416,0.381107

In [26]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '150_train_split.csv')
if not os.path.exists(datapath_df):
    df_train.to_csv(datapath_df, index=True)

In [27]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '150_test_split.csv')
if not os.path.exists(datapath_df):
    df_test.to_csv(datapath_df, index=True)

In [28]:
df_train_ = rcp('150_train_split.csv', None, 0)
p(df_train_)

(7186, 88)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a,spread_a
3134,-0.018902,-0.016231,1.321667,1.343521,-1.228430,-1.303603,-1.318706,-1.481543,-1.903444,0.921242,-2.507811,-0.529573,0.446845,0.430833,-0.575159,0.121855,-0.00658,-0.050716,0.174116,0.184420,0.184667,0.087111,-0.946293,-0.146579,-0.692156,-0.146579,-1.441489,-0.954681,-0.761156,0.058212,-0.155516,0.712864,2.741520,2.536967,1.145528,-0.129427,-0.499197,-0.454521,-1.849687,0.374410,0.695530,0.314062,1.079520,0.019169,1.242246,-1.671873,-0.972992,-0.574376,0.972992,0.574376,-0.982755,-0.574453,0.482854,-0.689375,-0.331362,0.453289,0.228158,0.772176,0.513350,0.650436,-0.657641,-0.640307,-0.502838,-1.467600,-0.218142,-0.622246,-1.140080,-0.426922,-0.790581,-0.024232,-0.034710,-0.003680,0.702370,1.160200,-1.334506,0.042893,0.400880,0.340858,-0.223699,0.020952,0.037745,-0.000575,-2.090760,-0.652068,0.652068,1.632487,-0.999416,0.819762
8383,-0.099050,-0.203595,-0.808132,-0.713716,0.644865,0.483580,1.728190,1.736950,1.631711,-1.010155,0.087533,-0.470397,-0.467579,-0.507828,0.560740,0.066701,-0.00658,-0.015186,0.085137,0.074908,0.074809,0.087111,0.662864,-0.003876,1.124071,-0.003876,0.038328,-0.153029,0.213363,1.076767,0.781105,0.678480,-1.100526,-0.236015,-1.452563,-0.918119,1.069529,0.319236,1.475443,-0.610516,0.797801,-0.417220,-1.175610,-0.119667,-0.495752,0.000029,1.384239,1.275388,-1.384239,-1.275388,1.384224,1.275392,-0.650163,-0.418961,-0.082013,-0.146715,-0.071707,0.552885,0.329894,0.273434,1.586312,1.831840,0.891767,1.413205,1.547778,2.450526,0.357308,-2.027860,1.476410,0.911499,0.124828,1.707674,1.539383,1.691886,-0.160638,-1.544978,1.529618,0.260294,-0.328340,-2.382964,2.221644,0.432133,-2.362190,1.504139,-1.504139,1.632487,-0.999416,-0.715532
7423,0.556110,0.547723,0.560475,0.683780,0.017205,-0.111224,0.252549,0.728169,0.622166,0.229666,-1.268548,-0.368039,-0.561384,-0.570175,0.448871,0.380389,-0.00658,-0.008080,-0.414064,-0.477483,-0.477456,-0.144717,0.089375,0.281530,0.373883,0.281530,0.584722,0.423159,0.227545,0.949448,0.943996,0.288787,-0.712005,-1.120647,0.844477,0.002022,0.788563,0.607145,0.626962,-1.908827,0.797801,-0.521689,-0.173330,0.418323,-0.008731,0.835980,-0.513833,-0.527205,0.513833,0.527205,-0.513886,-0.523911,-0.286039,-0.251561,-0.269025,0.644595,-1.124856,-0.262426,0.240646,0.237529,-0.547797,-0.640307,0.581855,-0.507332,-0.604055,0.553294,0.088546,1.013922,-0.565101,-0.024232,0.337545,-0.158211,-1.157660,-1.624824,0.450235,0.748613,-0.009571,0.448277,-0.223699,0.144230,0.302460,0.480211,1.890209,-0.581947,0.581947,0.546086,-0.999416,1.623964
2528,-0.952155,-0.852996,0.086268,0.042980,-0.977366,-0.882992,-0.515762,-0.081084,-0.681277,2.626812,0.005854,2.378467,-0.394616,-0.309012,-1.152861,-1.548392,-0.00658,-0.105670,0.256468,0.219933,0.219938,0.520672,-1.192465,0.376666,0.098365,0.376665,0.325185,1.490359,-0.995229,-0.595361,0.193794,-1.862357,-1.165280,-0.405002,-1.634884,1.688945,-0.069944,0.871062,-0.236808,0.177424,-2.781703,-0.113100,1.001565,-0.382878,0.918201,-0.780192,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416,0.746653
10064,-0.095322,-0.018096,0.455715,0.277340,-0.506578,-0.283939,0.008202,-0.123970,0.063248,-0.684075,-0.034915,-0.180116,-0.021720,0.046363,0.195875,0.192521,-0.00658,-0.135989,0.180541,0.231867,0.231643,0.221328,-0.317149,-0.003876,-0.751248,-0.003876,0.083861,-0.077874,0.158660,0.185531,-0.155516,0.361854,0.108207,0.189289,0.113047,-0.753808,0.179804,-0.274577,0.076595,0.911642,0.030765,0.070301,-0.423900,0.158005,0.335049,-0.835922,1.374539,1.780788,-1.374539,-1.780788,1.374523,1.780814,2.708242,2.292911,2.567320,0.870684,0.436760,1.851760,-0.630081,-0.534429,1.005709,1.007791,1.821504,-0.027198,1.628380,-0.298601,1.163594,0.533641,0.708558,1.535320,0.124828,1.426558,0.516367,0.552558,0.162722,0.042893,1.016555,0.824243,3.124827,0.760618,0.037745,-0.289047,-1.276471,1.872272,-1.872272,1.632487,-0.999416,0.307998
3378,-1.174518,-1.003384,1.645557,1.503400,-2.614035,-2.438719,-0.579292,-0.263904,-1.131438,0.463775,-1.348773,-0.788668,-0.929084,-0.809170,-1.557884,-1.439692,-0.00658,-0.036504,-0.101063,-0.129497,-0.129447,-0.169121,-2.231198,-0.003876,-0.435995,-0.003876,-0.986161,0.285375,-1.381120,-1.119492,-0.114794,-2.811566,0.151376,0.342399,-0.443959,0.133470,-2.255234,-1.660142,-1.092933,0.508718,0.081900,-1.009210,-0.702311,-0.996071,2.416826,-1.253898,0.035864,-0.001589,-0.035864,0.001589,0.035822,0.001728,-0.922832,0.196554,-0.206688,-0.723531,-0.359983,-1.297028,-0.896358,-0.920408,0.179265,0.234194,-0.657794,-0.027198,0.436445,1.157184,0.242125,-0.320193,0.269786,-0.128202,-1.098298,0.173867,-0.289646,-0.662725,0.605846,-1.721408,-0.420021,-1.377845,-0.432982,0.760618,-0.756400,-1.058306,-0.281229,0.014077,-0.014077,-0.540315,1.000585,-0.349986
1965,0.229928,0.230790,-0.150739,-0.311130,0.351722,0.523296,-0.936250,0.030585,-0.827527,-0.322162,-0.963834,-1.338044,-1.142593,-1.120902,-0.514922,-0.298694,-0.00658,-0.079141,-1.153290,-1.066171,-1.066141,-0.913413,0.153499,0.138827,0.501964,0.138827,-0.576365,-0.428597,-0.244519,-1.024003,-1.092138,-0.135291,0.518313,0.376423,0.163888,0.330643,0.203218,0.337230,-1.184661,-1.058209,0.337579,-1.566377,0.411333,-0.510144,-0.533950,0.000029,-2.476575,-1.585176,2.476575,1.585176,-2.486369,-1.585297,-0.086195,-1.384727,-1.359927,2.696784,-2.996478,0.029961,1.258467,1.673729,-2.069919,-1.632530,-2.827180,-0.027198,-2.196558,0.486332,-2.061549,0.053359,-2.052052,-0.959963,-0.991940,-0.191090,1.074376,0.856379,0.391005,-0.221752,-0.830471,-0.787041,-1.060831,-2.937713,-1.947618,1.730257,0.080677,-1.598696,1.598696,-1.626716,1.000585,1.039090
1161,-0.466237,-0.596032,-0.951336,-0.901526,0.431830,0.271150,-0.390189,-0.673265,-0.555054,-0.160913,-0.082768,0.266902,0.500312,0.389269,-0.112194,-0.047054,-0.00658,0.134041,-0.381091,-0.350132,-0.350204,-0.217927,0.252710,0.138827,-0.334310,0.138827,-0.986161,-0.854475,-0.256675,0.153702,0.604640,-1.215543,0.129792,0.257338,-0.228590,-0.753808,0.905632,0.283247,-0.726022,-0.252361,0.388715,0.418531,-0.034125,-0.657658,-0.352510,0.835980,-1.593826,-1.847984,1.593826,1.847984,-1.589051,-1.858225,-0.137003,-1.276561,-1.282005,-1.068461,-0.532369,-2.129208,0.658242,0.623508,-0.924404,-0.800072,0.891767,-0.747399,-1.903460,-0.246520,-2.637468,-1.467531,-1.448740,0.599589,-0.034710,0.982691,0.609368,0.628514,-0.059622,-1.015687,-1.446147,-1.753811,-1.688679,-0.718714,-0.756400,0.576369,-0.597897,-1.861648,1.861648,0.002886,-0.999416,-0.569314
2771,-1.113941,-1.106853,-0.899436,-0.889968,-0.231041,-0.241453,1.173629,-2.120647,0.444011,1.095629,-0.975798,0.104568,2.734147,2.737653,-0.924534,-0.531375,-0.00658,-0.072035,-0.395881,-0.433009,-0.433007,-0.461957,0.558813,-0.003876,-0.807939,-0.003876,-0.917862,-1.104991,-0.052046,-2.901964,-3.168995,0.103969,0.561482,0.019168,1.272546,0.462092,0.835391,0.895055,0.374710,-0.610516,1.155752,2.090032,0.383492,-1.265066,0.277752,0.418004,1.015619,0.931716,-1.015619,-0.931716,1.005895,0.941813,0.076391,0.021429,1.040058,-0.172802,-0.084744,0.670965,1.270588,1.189012,1.727540,1.646849,1.356636,-1.467600,1.716309,-0.622246,1.624329,-0.907203,2.079722,-0.336142,-1.630092,1.870425,-0.971657,-1.574187,1.810104,-1.015687,2.247906,1.146500,0.822715,0.020952,0.037745,1.153313,0.894966,0.820464,-0.820464,1.632487,-0.999416,-0.276877
9937,0.411658,0.267144,-0.741816,-0.554801,1.066532,0.796684,-0.120345,-0.566747,-0.167305,-0.362773,-0.276997,-0.150528,0.497225,0.392732,0.448871,0.707866,-0.00658,-0.072035,-0.348482,-0.345053,-0.344853,-0.059307,0.822570,0.281530,0.506464,0.281530,-0.485300,-0.967207,0.296430,0.408340,-0.114794,0.816018,1.165849,0.988861,0.558551,-0.589497,-0.030921,-0.346555,-0.336180,1.045950,0.388715,0.209593,0.717585,0.210069,-0.868180,0.835980,1.049571,0.845798,-1.049571,-0.845798,1.049548,0.850837,-0.233538,0.693602,0.136167,-1.690204,-0.843099,-2.702738,-1.663329,-1.773152,0.778175,1.175964,1.356636,-0.747399,0.800376,0.454712,-0.333794,-1.547578,0.571442,0.755544,0.124828,0.898850,1.539383,1.539976,0.398789,-2.206590,-0.830471,-1.995504,-0.328340,1.685201,0.831890,-1.442935,-0.190752,0.820464,-0.820464,0.002886,1.000585,-0.569314

In [29]:
df_test_ = rcp('150_test_split.csv', None, 0)
p(df_test_)

(3080, 88)

,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,w_pct_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff,away_home_a,spread_a
2583,0.364128,0.314684,-0.920580,-0.982429,1.188895,1.256641,-1.064798,-0.921805,-0.600467,0.252360,-0.514153,-0.408023,0.720669,0.669828,0.574508,0.578599,-0.00658,-0.064928,0.449053,0.506638,0.506363,0.416552,1.000424,-0.146579,1.079977,-0.146579,0.607488,-0.115451,0.802937,-0.387406,-0.101220,-1.221274,0.561482,0.733678,-0.036432,0.100608,-0.101162,-0.022657,-0.496703,2.433799,0.490987,0.801583,1.385772,0.583191,-1.202410,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585,0.527325
9370,-0.726251,-0.886865,-0.028679,-0.236006,-0.661512,-0.653382,-1.661853,-0.376687,-1.774194,-0.807101,0.385914,-0.289671,-1.054252,-1.086265,-1.014029,-1.034655,-0.00658,-0.086247,-0.983940,-0.785825,-0.785623,-0.803600,-0.960811,-0.003876,-1.871279,-0.003876,-1.487022,-0.340916,-1.206882,-0.164597,-0.060497,-0.274263,-0.668836,-0.593270,-0.465613,-0.162289,-0.147990,-0.202600,-2.468849,-1.058209,-3.139654,-1.636023,0.494856,-1.447289,0.783873,1.253955,-3.175014,-2.959863,3.175014,2.959863,-3.175121,-2.960045,-1.397040,-0.488496,-2.419660,0.435898,0.219467,-0.779727,-1.174939,-1.019147,-3.199741,-3.566522,1.821504,-0.027198,-2.562932,-1.894508,-2.291917,1.654297,-2.984443,-1.895694,-1.630092,-0.743458,-0.785654,0.552558,-2.471957,1.101473,-2.472272,-1.270426,-2.525811,1.870118,-3.138836,-1.154463,-0.733612,-3.176408,3.176408,1.632487,-0.999416,1.112200
5655,-0.544521,-0.381636,0.635441,0.584578,-1.099025,-0.938778,0.475648,0.308365,0.290309,0.386136,-1.368477,-1.277268,0.254977,0.351168,-0.613022,-0.638236,-0.00658,-0.107565,-0.011115,-0.096173,-0.095999,-0.010501,-0.780537,0.138827,-1.522132,0.138827,0.152160,0.360530,-0.181712,-1.405961,-1.214306,-0.711235,-0.215561,-0.116930,-0.225624,0.560678,-0.780163,-0.292572,0.489370,0.329640,-0.429457,0.105124,1.330090,-0.353953,0.984411,-0.835922,-0.400660,-0.736104,0.400660,0.736104,-0.400711,-0.736188,-0.858476,1.350323,-0.643048,-0.224976,-0.110820,-1.353257,-2.178713,-2.230941,-0.893020,-1.195279,-0.037969,1.413205,-0.862959,-1.656424,0.011757,1.494203,-0.772299,-0.648053,0.603442,-1.493099,-0.785654,-0.510815,-1.166473,0.572183,-2.267047,-1.431554,-0.642265,1.870118,-0.756400,-2.308351,0.623537,-0.652068,0.652068,1.632487,-0.999416,-0.057549
7258,0.291436,0.402306,-1.376142,-1.278108,1.534856,1.621467,-0.564419,0.437857,-0.052028,0.799410,0.302170,-0.137733,-0.701027,-0.649840,-0.241274,-0.181492,-0.00658,0.027450,-0.146765,-0.280510,-0.280484,-0.254531,1.744507,-0.003876,1.468719,-0.003876,0.835153,0.385581,0.565892,-2.233537,-2.422412,-1.131014,0.367222,0.410447,-0.017143,0.987886,2.427531,2.406579,0.007799,-1.147748,1.002344,-0.765449,-1.593227,0.175360,-1.698981,0.000029,0.632447,0.699232,-0.632447,-0.699232,0.632417,0.699211,0.223734,-0.905707,0.229673,0.453289,0.228158,1.446916,1.080934,1.054368,0.582025,0.898478,-0.037969,0.693003,1.240024,2.046899,0.242125,-1.547578,1.083343,-1.427828,-2.268245,-0.112180,1.818388,2.223573,-0.368319,0.042893,1.324393,1.065936,0.299508,-0.903631,1.228963,1.153313,-2.497904,0.767873,-0.767873,0.002886,1.000585,-0.349986
2386,-0.012379,-0.009706,0.019376,0.017296,-0.029451,-0.026252,-0.170277,-0.115615,-0.128880,0.036168,-0.029989,-0.024179,0.042035,0.042899,-0.029584,-0.022925,-0.00658,-0.008080,-0.023965,-0.024198,-0.024198,-0.022702,-0.031614,-0.003876,-0.047253,-0.003876,0.015561,-0.002719,0.014812,-0.132767,-0.155516,-0.006349,0.000285,-0.014857,0.017131,0.067746,-0.054334,-0.004662,-0.129792,0.016255,0.081900,0.035478,0.132922,-0.024217,0.029467,0.000029,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,1.000585,-0.715532
8109,-0.310602,-0.362993,0.036676,-0.020266,-0.326115,-0.342126,0.625443,-0.625227,0.353187,-0.510882,-0.006062,-0.803062,1.249406,1.196309,0.011722,-0.081526,-0.00658,0.112723,0.215332,0.291702,0.291403,0.209127,-0.296581,-0.003876,-0.601570,-0.003876,-0.075504,0.084962,-0.175634,0.535660,0.753957,-0.176839,-0.668836,-0.712355,0.231635,0.429230,-0.007507,0.229264,0.443506,-0.879132,0.746665,1.184635,0.634062,-0.180408,0.497390,1.671931,-0.022339,-0.018436,0.022339,0.018436,-0.022383,-0.018489,-0.025225,-0.009476,-0.019676,0.018504,0.010865,0.029961,0.002373,0.004146,-0.029962,-0.034884,-0.037969,-0.027198,-0.027628,-0.034476,0.011757,0.053359,-0.022729,-0.024232,-0.034710,-0.003680,-0.041642,-0.055083,0.009755,0.042893,-0.009571,0.018601,-0.014416,0.020952,0.037745,-0.000575,0.080677,-0.020983,0.020983,0.002886,-0.999416,0.161779
9743,-0.409389,-0.383501,-0.060396,0.109756,-0.334037,-0.486209,0.994087,0.385643,0.772375,-0.263635,-0.231959,-0.190512,-0.036053,-0.009056,-0.466732,-0.383149,-0.00658,0.006132,0.446749,0.337043,0.336744,0.721591,0.056708,0.424233,0.379883,0.424233,0.334291,0.711253,-0.228311,-0.642045,-0.019774,-0.953360,0.280884,0.121240,0.399791,0.166332,0.413942,0.409208,1.131464,-0.207592,0.439851,0.314062,-0.089807,0.192714,0.526038,0.835980,0.031014,0.279750,-0.031014,-0.279750,0.030971,0.279710,0.117037,-0.643019,0.245257,-0.077149,-0.039113,0.063698,1.074461,1.135154,0.715407,0.520088,0.426899,-1.467600,0.045647,0.097586,0.357308,0.053359,0.315491,1.535320,-0.194249,1.712605,-1.157660,-1.194411,-0.002106,-0.089430,0.298267,0.179729,0.299508,-1.273464,1.030426,1.297549,0.352107,0.189379,-0.189379,-1.626716,1.000585,1.770183
4546,-0.467169,-0.596032,0.630636,0.387137,-1.018917,-0.959097,-0.415686,-1.155725,-0.803074,-0.440411,-0.371296,-0.920614,0.434960,0.375414,-0.800618,-0.669260,-0.00658,0.084299,0.152053,0.354139,0.353840,0.367746,-0.744241,0.138827,-0.677159,0.138827,-0.371468,0.247797,-0.655802,-0.673874,-0.359130,-0.602350,0.647821,0.852763,-0.604374,1.152197,0.296873,0.859066,-0.519635,0.329640,-0.378322,0.453353,-0.730152,-0.206440,1.041707,-0.417947,-0.439462,-0.564268,0.439462,0.564268,-0.439514,-0.564344,0.797863,-1.801938,-0.487205,0.079374,0.041286,0.198646,1.866957,1.862231,-0.673333,-0.303961,-0.037969,-2.908003,-0.599170,-0.599926,-1.831182,-1.707672,-0.754017,-0.336142,-0.194249,-0.329182,1.818388,2.375483,-1.220404,1.366118,-0.009571,0.824243,-0.432982,-1.088548,1.626035,1.730257,-1.276471,-0.757249,0.757249,-1.626716,1.000585,0.454216
4962,-0.389818,-0.352740,-0.339115,-0.285125,-0.055860,-0.073356,-0.408249,-0.988639,-0.031069,-1.190514,0.422507,-0.529573,0.974376,1.019661,0.180386,-0.133232,-0.00658,-0.072035,0.185996,0.138584,0.138880,0.209127,-0.315939,0.138827,-0.050853,0.138827,0.789620,0.736304,0.164738,0.408340,0.197413,0.005113,-2.114999,-2.294486,0.609875,0.232057,0.367114,0.409208,0.145391,-0.162823,-0.480593,1.010520,0.689744,-0.137022,0.153610,-0.417947,-0.266065,-0.237021,0.266065,0.237021,-0.266114,-0.233293,0.546364,-0.026860,0.366036,-0.398891,0.345497,0.055264,0.781165,0.808643,0.001422,-0.091642,0.194465,-0.207248,-0.249284,0.157572,0.098145,0.293500,-0.022729,0.092734,0.005174,0.085094,-0.715903,-0.890591,0.107523,0.472941,0.195655,0.441563,0.482631,-0.996089,-0.408962,0.828782,0.827109,-0.283935,0.283935,0.002886,-0.999416,0.746653
5706,-0.235114,-0.458073,-0.062318,0.005739,-0.168540,-0.462195,-0.430559,1.448727,-0.052028,-2.189059,-0.509227,-1.382825,-2.012811,-2.118446,-0.681865,-0.703732,-0.00658,0.134041,-0.915691,-0.831042,-0.830964,-0.571771,-0.144134,0.281530,-0.052652,0.281530,-0.280402,0.022333,-0.280987,-1.374131,-1.200732,-0.506359,-0.733589,-0.797416,0.114238,-0.556635,0.390528,-0.004662,-0.473771,-1.774519,0.439851,-2.193190,-0.535265,-0.883267,0.449642,0.000029,-0.468564,-0.341892,0.468564,0.341892,-0.468616,-0.341959,-0.848314,0.175951,-0.144350,-2.877169,2.909561,0.029961,-0.644129,-0.561358,-0.422261,-0.791663,-2.362311,-0.027198,-0.115558,-0.239080,1.163594,1.013922,0.562301,-2.831425,-1.789630,-1.532554,-0.785654,-0.206994,-1.424832,0.572183,0.195655,0.501986,-0.014416,-0.718714,2.023108,-0.865991,-0.190752,-0.336525,0.336525,-1.626716,-0.999416,0.381107