In [1]:
# Target variable 'spread_a' is most predicted by stat differences which should be used.

random_state_2909 = 2909

# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

## 4.2 Introduction<a id='4.2_Introduction'></a>

## 4.3 Imports<a id='4.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 4.4 Functions<a id='4.4_Imports'></a>

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 4.5 Load Data<a id='4.5_Load_Data'></a>

In [4]:
df_stats = rcp('53AAprediction_stats_2010_2018.csv', ['game_date'])
p(df_stats)

(10266, 107)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,team_id_a,spread_a,away_home_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,team_id_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,Celtics,BOS,Boston,1610612738,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami,1610612748,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,1610612756,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland,1610612757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,1610612745,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles,1610612747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,1610612750,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento,1610612758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,Heat,MIA,Miami,1610612748,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia,1610612755,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,Warriors,GSW,Golden State,1610612744,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston,1610612745,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,Cavaliers,CLE,Cleveland,1610612739,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,Cavaliers,CLE,Cleveland,1610612739,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,Cavaliers,CLE,Cleveland,1610612739,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,Cavaliers,CLE,Cleveland,1610612739,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [5]:
df_stats_gitiab_spread = df_stats.loc[:, ['game_id', 'team_id_a', 'team_id_b', 'spread_a']]
p(df_stats_gitiab_spread)

(10266, 4)

        game_id   team_id_a   team_id_b  spread_a
0      21000001  1610612738  1610612748        -8
1      21000002  1610612756  1610612757        14
2      21000003  1610612745  1610612747         2
3      21000009  1610612750  1610612758         1
4      21000006  1610612748  1610612755       -10
10261  41700317  1610612744  1610612745        -9
10262  41700401  1610612739  1610612744        10
10263  41700402  1610612739  1610612744        19
10264  41700403  1610612739  1610612744         8
10265  41700404  1610612739  1610612744        23

In [6]:
df_strength_of_schedule_diff = rcp('54strength_of_schedule_diff_opp_win_pct_diff_win_pct_diff_2010_2018.csv', ['game_date'])
p(df_strength_of_schedule_diff)

(10266, 17)

,game_id,team_id_a,TEAM_ABBREVIATION_a,game_date,season,team_id_b,TEAM_ABBREVIATION_b,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff
0,21000001,1610612738,BOS,2010-10-26,2010-11,1610612748,MIA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
1,21000002,1610612756,PHX,2010-10-26,2010-11,1610612757,POR,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
2,21000003,1610612745,HOU,2010-10-26,2010-11,1610612747,LAL,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
3,21000013,1610612754,IND,2010-10-27,2010-11,1610612759,SAS,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
4,21000014,1610612743,DEN,2010-10-27,2010-11,1610612762,UTA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
10261,41700317,1610612744,GSW,2018-05-28,2017-18,1610612745,HOU,7.0,-7.0,-0.071429,0.071429,-7.0,7.0,26.0,81.0,0.004736,0.049198
10262,41700401,1610612739,CLE,2018-05-31,2017-18,1610612744,GSW,9.0,-8.0,-0.087071,0.087071,-9.0,8.0,-49.0,-98.0,-0.003654,0.056829
10263,41700402,1610612739,CLE,2018-06-03,2017-18,1610612744,GSW,10.0,-9.0,-0.096139,0.096139,-10.0,9.0,-39.0,-107.0,-0.005391,0.062295
10264,41700403,1610612739,CLE,2018-06-06,2017-18,1610612744,GSW,11.0,-10.0,-0.105028,0.105028,-11.0,10.0,-28.0,-117.0,-0.007256,0.067600
10265,41700404,1610612739,CLE,2018-06-08,2017-18,1610612744,GSW,12.0,-11.0,-0.113745,0.113745,-12.0,11.0,-16.0,-128.0,-0.009240,0.072750

In [7]:
df_strength_of_schedule_diff = pd.merge(df_strength_of_schedule_diff, df_stats_gitiab_spread, on=['game_id', 'team_id_a', 'team_id_b'])
p(df_strength_of_schedule_diff)

(10266, 18)

,game_id,team_id_a,TEAM_ABBREVIATION_a,game_date,season,team_id_b,TEAM_ABBREVIATION_b,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,spread_a
0,21000001,1610612738,BOS,2010-10-26,2010-11,1610612748,MIA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-8
1,21000002,1610612756,PHX,2010-10-26,2010-11,1610612757,POR,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,14
2,21000003,1610612745,HOU,2010-10-26,2010-11,1610612747,LAL,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,2
3,21000013,1610612754,IND,2010-10-27,2010-11,1610612759,SAS,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,13
4,21000014,1610612743,DEN,2010-10-27,2010-11,1610612762,UTA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-22
10261,41700317,1610612744,GSW,2018-05-28,2017-18,1610612745,HOU,7.0,-7.0,-0.071429,0.071429,-7.0,7.0,26.0,81.0,0.004736,0.049198,-9
10262,41700401,1610612739,CLE,2018-05-31,2017-18,1610612744,GSW,9.0,-8.0,-0.087071,0.087071,-9.0,8.0,-49.0,-98.0,-0.003654,0.056829,10
10263,41700402,1610612739,CLE,2018-06-03,2017-18,1610612744,GSW,10.0,-9.0,-0.096139,0.096139,-10.0,9.0,-39.0,-107.0,-0.005391,0.062295,19
10264,41700403,1610612739,CLE,2018-06-06,2017-18,1610612744,GSW,11.0,-10.0,-0.105028,0.105028,-11.0,10.0,-28.0,-117.0,-0.007256,0.067600,8
10265,41700404,1610612739,CLE,2018-06-08,2017-18,1610612744,GSW,12.0,-11.0,-0.113745,0.113745,-12.0,11.0,-16.0,-128.0,-0.009240,0.072750,23

In [8]:
column_name_list = list(df_strength_of_schedule_diff.columns)
pl(column_name_list)

18

['game_id',
 'team_id_a',
 'TEAM_ABBREVIATION_a',
 'game_date',
 'season',
 'team_id_b',
 'TEAM_ABBREVIATION_b',
 'losses_diff',
 'wins_diff',
 'win_pct_diff',
 'opp_win_pct_diff',
 'opp_losses_diff',
 'opp_wins_diff',
 'opp_opps_losses_diff',
 'opp_opps_wins_diff',
 'opp_opps_win_pct_diff',
 'strength_of_schedule_diff',
 'spread_a']

## 4.6 Get Indicator Variables<a id='4.6 Get_Indicator_Variables'></a>

In [9]:
df_strength_of_schedule_diff.select_dtypes('object')

      TEAM_ABBREVIATION_a   season TEAM_ABBREVIATION_b
0                     BOS  2010-11                 MIA
1                     PHX  2010-11                 POR
2                     HOU  2010-11                 LAL
3                     IND  2010-11                 SAS
4                     DEN  2010-11                 UTA
...                   ...      ...                 ...
10261                 GSW  2017-18                 HOU
10262                 CLE  2017-18                 GSW
10263                 CLE  2017-18                 GSW
10264                 CLE  2017-18                 GSW
10265                 CLE  2017-18                 GSW

[10266 rows x 3 columns]

In [10]:
column_names_categorical_list = list(df_strength_of_schedule_diff.select_dtypes('object').columns) + ['team_id_a', 'team_id_b']
pl(column_names_categorical_list)

5

['TEAM_ABBREVIATION_a',
 'season',
 'TEAM_ABBREVIATION_b',
 'team_id_a',
 'team_id_b']

In [11]:
df_indicator_variables = pd.get_dummies(df_strength_of_schedule_diff[column_names_categorical_list])
p(df_indicator_variables)

(10266, 72)

,team_id_a,team_id_b,TEAM_ABBREVIATION_a_ATL,TEAM_ABBREVIATION_a_BKN,TEAM_ABBREVIATION_a_BOS,TEAM_ABBREVIATION_a_CHA,TEAM_ABBREVIATION_a_CHI,TEAM_ABBREVIATION_a_CLE,TEAM_ABBREVIATION_a_DAL,TEAM_ABBREVIATION_a_DEN,TEAM_ABBREVIATION_a_DET,TEAM_ABBREVIATION_a_GSW,TEAM_ABBREVIATION_a_HOU,TEAM_ABBREVIATION_a_IND,TEAM_ABBREVIATION_a_LAC,TEAM_ABBREVIATION_a_LAL,TEAM_ABBREVIATION_a_MEM,TEAM_ABBREVIATION_a_MIA,TEAM_ABBREVIATION_a_MIL,TEAM_ABBREVIATION_a_MIN,TEAM_ABBREVIATION_a_NJN,TEAM_ABBREVIATION_a_NOH,TEAM_ABBREVIATION_a_NOP,TEAM_ABBREVIATION_a_NYK,TEAM_ABBREVIATION_a_OKC,TEAM_ABBREVIATION_a_ORL,TEAM_ABBREVIATION_a_PHI,TEAM_ABBREVIATION_a_PHX,TEAM_ABBREVIATION_a_POR,TEAM_ABBREVIATION_a_SAC,TEAM_ABBREVIATION_a_SAS,TEAM_ABBREVIATION_a_TOR,TEAM_ABBREVIATION_a_UTA,season_2010-11,season_2011-12,season_2012-13,season_2013-14,season_2014-15,season_2015-16,season_2016-17,season_2017-18,TEAM_ABBREVIATION_b_BKN,TEAM_ABBREVIATION_b_BOS,TEAM_ABBREVIATION_b_CHA,TEAM_ABBREVIATION_b_CHI,TEAM_ABBREVIATION_b_CLE,TEAM_ABBREVIATION_b_DAL,TEAM_ABBREVIATION_b_DEN,TEAM_ABBREVIATION_b_DET,TEAM_ABBREVIATION_b_GSW,TEAM_ABBREVIATION_b_HOU,TEAM_ABBREVIATION_b_IND,TEAM_ABBREVIATION_b_LAC,TEAM_ABBREVIATION_b_LAL,TEAM_ABBREVIATION_b_MEM,TEAM_ABBREVIATION_b_MIA,TEAM_ABBREVIATION_b_MIL,TEAM_ABBREVIATION_b_MIN,TEAM_ABBREVIATION_b_NJN,TEAM_ABBREVIATION_b_NOH,TEAM_ABBREVIATION_b_NOP,TEAM_ABBREVIATION_b_NYK,TEAM_ABBREVIATION_b_OKC,TEAM_ABBREVIATION_b_ORL,TEAM_ABBREVIATION_b_PHI,TEAM_ABBREVIATION_b_PHX,TEAM_ABBREVIATION_b_POR,TEAM_ABBREVIATION_b_SAC,TEAM_ABBREVIATION_b_SAS,TEAM_ABBREVIATION_b_TOR,TEAM_ABBREVIATION_b_UTA,TEAM_ABBREVIATION_b_WAS
0,1610612738,1610612748,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1610612756,1610612757,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,1610612745,1610612747,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1610612754,1610612759,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,1610612743,1610612762,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
10261,1610612744,1610612745,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10262,1610612739,1610612744,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10263,1610612739,1610612744,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10264,1610612739,1610612744,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10265,1610612739,1610612744,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
#cat drop
df_strength_of_schedule_diff = df_strength_of_schedule_diff.drop(columns=column_names_categorical_list)
p(df_strength_of_schedule_diff)

(10266, 13)

,game_id,game_date,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,spread_a
0,21000001,2010-10-26,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-8
1,21000002,2010-10-26,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,14
2,21000003,2010-10-26,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,2
3,21000013,2010-10-27,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,13
4,21000014,2010-10-27,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-22
10261,41700317,2018-05-28,7.0,-7.0,-0.071429,0.071429,-7.0,7.0,26.0,81.0,0.004736,0.049198,-9
10262,41700401,2018-05-31,9.0,-8.0,-0.087071,0.087071,-9.0,8.0,-49.0,-98.0,-0.003654,0.056829,10
10263,41700402,2018-06-03,10.0,-9.0,-0.096139,0.096139,-10.0,9.0,-39.0,-107.0,-0.005391,0.062295,19
10264,41700403,2018-06-06,11.0,-10.0,-0.105028,0.105028,-11.0,10.0,-28.0,-117.0,-0.007256,0.067600,8
10265,41700404,2018-06-08,12.0,-11.0,-0.113745,0.113745,-12.0,11.0,-16.0,-128.0,-0.009240,0.072750,23

In [13]:
df_strength_of_schedule_diff.drop(columns=['game_id', 'game_date'], inplace=True)

In [14]:
df_features = df_strength_of_schedule_diff.drop(columns='spread_a')
p(df_features)

(10266, 10)

,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff
0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
2,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
3,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
4,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
10261,7.0,-7.0,-0.071429,0.071429,-7.0,7.0,26.0,81.0,0.004736,0.049198
10262,9.0,-8.0,-0.087071,0.087071,-9.0,8.0,-49.0,-98.0,-0.003654,0.056829
10263,10.0,-9.0,-0.096139,0.096139,-10.0,9.0,-39.0,-107.0,-0.005391,0.062295
10264,11.0,-10.0,-0.105028,0.105028,-11.0,10.0,-28.0,-117.0,-0.007256,0.067600
10265,12.0,-11.0,-0.113745,0.113745,-12.0,11.0,-16.0,-128.0,-0.009240,0.072750

In [15]:
df_target = df_strength_of_schedule_diff[['spread_a']]
p(df_target)

(10266, 1)

       spread_a
0            -8
1            14
2             2
3            13
4           -22
10261        -9
10262        10
10263        19
10264         8
10265        23

In [16]:
scaler = StandardScaler() 
scaler

StandardScaler()

In [17]:
# Fitting data to the scaler object
scaled_df_features = scaler.fit_transform(df_features) 
scaled_df_features

array([[ 0.05235166, -0.05104729, -0.05152127, ...,  0.00722028,
        -0.01395749,  0.05396027],
       [ 0.05235166, -0.05104729, -0.05152127, ...,  0.00722028,
        -0.01395749,  0.05396027],
       [ 0.05235166, -0.05104729, -0.05152127, ...,  0.00722028,
        -0.01395749,  0.05396027],
       ...,
       [ 1.00475674, -0.91077442, -0.42052448, ..., -2.0506941 ,
        -0.06249409,  0.4526166 ],
       [ 1.09999725, -1.00629965, -0.45464467, ..., -2.24302255,
        -0.07928371,  0.48656417],
       [ 1.19523776, -1.10182489, -0.48810023, ..., -2.45458384,
        -0.09714664,  0.5195187 ]])

In [18]:
scaled_df_features = pd.DataFrame(scaled_df_features, columns=df_features.columns)
p(scaled_df_features)

(10266, 10)

,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff
0,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,0.053960
1,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,0.053960
2,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,0.053960
3,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,0.053960
4,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,0.053960
10261,0.719035,-0.719724,-0.325681,0.325681,-0.719035,0.719724,0.494667,1.565081,0.028685,0.368799
10262,0.909516,-0.815249,-0.385720,0.385720,-0.909516,0.815249,-0.889948,-1.877599,-0.046855,0.417635
10263,1.004757,-0.910774,-0.420524,0.420524,-1.004757,0.910774,-0.705333,-2.050694,-0.062494,0.452617
10264,1.099997,-1.006300,-0.454645,0.454645,-1.099997,1.006300,-0.502256,-2.243023,-0.079284,0.486564
10265,1.195238,-1.101825,-0.488100,0.488100,-1.195238,1.101825,-0.280717,-2.454584,-0.097147,0.519519

In [19]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df_features, 
                                                    df_target, test_size=0.3, 
                                                    random_state=random_state_2909)

In [20]:
X_train.shape

(7186, 10)

In [21]:
y_train.shape

(7186, 1)

In [22]:
X_test.shape

(3080, 10)

In [23]:
y_test.shape

(3080, 1)

In [24]:
#export dataframes

#https://stackoverflow.com/questions/30829748/multiple-pandas-dataframe-to-one-csv-file

In [25]:
df_train = pd.concat([X_train, y_train], axis=1)
p(df_train)

(7186, 11)

,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,spread_a
3134,0.814276,-0.910774,-0.709506,0.709506,-0.814276,0.910774,0.993128,0.680370,-0.101156,0.764666,-25
8383,1.861921,-1.770502,-1.528396,1.528396,-1.861921,1.770502,0.014667,-0.839025,-0.175809,1.657195,15
7423,1.480959,-1.292875,-0.800212,0.800212,-1.480959,1.292875,-1.997640,0.007220,0.174190,0.930723,15
2528,-0.138129,0.044478,0.534877,-0.534877,0.138129,-0.044478,-0.003794,0.141850,0.933791,-0.373293,11
10064,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.679282,-1.050586,-0.161001,0.019123,-7
3378,-1.185775,1.286306,0.720171,-0.720171,1.185775,-1.286306,-2.533024,0.853465,0.356187,-0.716098,23
1965,0.719035,-0.433148,-0.569379,0.569379,-0.719035,0.433148,-1.093025,-0.319738,0.191887,0.678340,-7
1161,3.385769,-3.489956,-1.808319,1.808319,-3.385769,3.489956,1.676205,-2.781542,-0.349872,1.927096,32
2771,0.147592,0.331054,0.407399,-0.407399,-0.147592,-0.331054,-0.889948,-0.127410,0.510078,-0.331985,-32
9937,0.623795,-0.719724,-0.444572,0.444572,-0.623795,0.719724,0.716205,0.411110,-0.051002,0.482069,16

In [26]:
df_test = pd.concat([X_test, y_test], axis=1)
p(df_test)

(3080, 11)

,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,spread_a
2583,0.147592,-0.146573,-0.371375,0.371375,-0.147592,0.146573,0.033129,0.007220,-0.063269,0.397802,-7
9370,-0.519091,0.617629,0.862346,-0.862346,0.519091,-0.617629,-0.797640,0.488041,0.769342,-0.776244,-23
5655,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.254667,-0.300505,-0.153378,0.020929,-23
7258,0.147592,-0.242098,-0.142908,0.142908,-0.147592,0.242098,0.273129,-0.204341,-0.072106,0.141762,-20
2386,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,0.053960,-10
8109,-0.519091,0.522104,0.716127,-0.716127,0.519091,-0.522104,-0.391487,0.949630,0.644726,-0.643243,14
9743,-0.138129,0.140003,0.096103,-0.096103,0.138129,-0.140003,0.697744,-1.089052,-0.315471,-0.181563,6
4546,1.195238,-1.292875,-0.911387,0.911387,-1.195238,1.292875,-1.333025,1.122725,0.357631,1.097758,5
4962,0.909516,-0.910774,-0.453198,0.453198,-0.909516,0.910774,0.439282,-1.396777,-0.125361,0.474039,-1
5706,1.195238,-1.388401,-1.182166,1.182166,-1.195238,1.388401,1.916205,-0.088944,-0.491298,1.197606,17

In [27]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '154_train_split.csv')
if not os.path.exists(datapath_df):
    df_train.to_csv(datapath_df, index=True)

In [28]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '154_test_split.csv')
if not os.path.exists(datapath_df):
    df_test.to_csv(datapath_df, index=True)

In [29]:
df_train_readback = rcp('154_train_split.csv', None, 0)
p(df_train_readback)

(7186, 11)

,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,spread_a
3134,0.814276,-0.910774,-0.709506,0.709506,-0.814276,0.910774,0.993128,0.680370,-0.101156,0.764666,-25
8383,1.861921,-1.770502,-1.528396,1.528396,-1.861921,1.770502,0.014667,-0.839025,-0.175809,1.657195,15
7423,1.480959,-1.292875,-0.800212,0.800212,-1.480959,1.292875,-1.997640,0.007220,0.174190,0.930723,15
2528,-0.138129,0.044478,0.534877,-0.534877,0.138129,-0.044478,-0.003794,0.141850,0.933791,-0.373293,11
10064,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.679282,-1.050586,-0.161001,0.019123,-7
3378,-1.185775,1.286306,0.720171,-0.720171,1.185775,-1.286306,-2.533024,0.853465,0.356187,-0.716098,23
1965,0.719035,-0.433148,-0.569379,0.569379,-0.719035,0.433148,-1.093025,-0.319738,0.191887,0.678340,-7
1161,3.385769,-3.489956,-1.808319,1.808319,-3.385769,3.489956,1.676205,-2.781542,-0.349872,1.927096,32
2771,0.147592,0.331054,0.407399,-0.407399,-0.147592,-0.331054,-0.889948,-0.127410,0.510078,-0.331985,-32
9937,0.623795,-0.719724,-0.444572,0.444572,-0.623795,0.719724,0.716205,0.411110,-0.051002,0.482069,16

In [30]:
df_test_readback = rcp('154_test_split.csv', None, 0)
p(df_test_readback)

(3080, 11)

,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff,spread_a
2583,0.147592,-0.146573,-0.371375,0.371375,-0.147592,0.146573,0.033129,0.007220,-0.063269,0.397802,-7
9370,-0.519091,0.617629,0.862346,-0.862346,0.519091,-0.617629,-0.797640,0.488041,0.769342,-0.776244,-23
5655,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.254667,-0.300505,-0.153378,0.020929,-23
7258,0.147592,-0.242098,-0.142908,0.142908,-0.147592,0.242098,0.273129,-0.204341,-0.072106,0.141762,-20
2386,0.052352,-0.051047,-0.051521,0.051521,-0.052352,0.051047,0.014667,0.007220,-0.013957,0.053960,-10
8109,-0.519091,0.522104,0.716127,-0.716127,0.519091,-0.522104,-0.391487,0.949630,0.644726,-0.643243,14
9743,-0.138129,0.140003,0.096103,-0.096103,0.138129,-0.140003,0.697744,-1.089052,-0.315471,-0.181563,6
4546,1.195238,-1.292875,-0.911387,0.911387,-1.195238,1.292875,-1.333025,1.122725,0.357631,1.097758,5
4962,0.909516,-0.910774,-0.453198,0.453198,-0.909516,0.910774,0.439282,-1.396777,-0.125361,0.474039,-1
5706,1.195238,-1.388401,-1.182166,1.182166,-1.195238,1.388401,1.916205,-0.088944,-0.491298,1.197606,17