In [1]:
random_state_2909 = 2909

# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

## 4.2 Introduction<a id='4.2_Introduction'></a>

## 4.3 Imports<a id='4.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 4.4 Functions<a id='4.4_Imports'></a>

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 4.5 Load Data<a id='4.5_Load_Data'></a>

In [4]:
df_173A_train_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b = \
rcp('173A_train_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b.csv')

p(df_173A_train_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b)

(9239, 55)

,Unnamed: 0,game_id,team_id_a,team_id_b,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a
0,0,21000001,1610612738,1610612748,-1.045984,2.249661,0.309284,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,-0.778288,0.010356,0.778288,-0.007252,0,0,0,0,3.197979,-0.016167,0.608012,-3.197979,0,0,-0.012572,0.499961,-0.261653,0,-2.477298,0.261653,2.477298,-0.433034,0.014199,-1.045520,0.656838,0.592052,-0.003691,-0.537609,0,0,0,-1.212704,-0.623967,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,-8
1,1,21000002,1610612756,1610612757,0.835137,-1.609206,0.383027,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,-0.560672,0.010356,0.560672,-0.007252,0,0,0,0,-3.178224,-0.016167,0.003533,3.178224,0,0,-0.012572,-0.493093,-0.347263,0,2.447929,0.347263,-2.447929,0.440350,0.014199,-2.094206,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-2.438905,-1.247085,-0.008491,0.014907,0.014752,-1.892685,0.876529,0,14
2,2,21000003,1610612745,1610612747,1.138839,-0.562003,1.001028,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,0.869375,0.010356,-0.869375,-0.007252,0,0,0,0,-3.178224,-0.016167,-1.205425,3.178224,0,0,-0.012572,-0.493093,1.065297,0,2.447929,-1.065297,-2.447929,0.440350,0.014199,-1.045520,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-1.212704,0.622268,-0.008491,0.014907,0.014752,1.897854,0.876529,0,2
3,3,21000009,1610612750,1610612758,-1.256725,0.877570,1.270549,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,0.232071,0.010356,-0.232071,-0.007252,0,1,0,0,3.197979,-0.016167,0.003533,-3.197979,0,0,-0.012572,0.499961,-0.004824,1,-2.477298,0.004824,2.477298,-0.433034,0.014199,1.051853,0.656838,0.592052,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,1
4,4,21000006,1610612748,1610612755,0.848535,-1.892884,-0.403891,0,6.083854,0,-0.030497,0.030497,6.416819,0.414362,-6.416819,0.232071,0.687540,-0.232071,4.133512,0,0,0,0,-3.178224,-6.722156,-0.600946,3.178224,0,0,-0.706445,-0.493093,0.252005,0,2.447929,-0.252005,-2.447929,0.877042,1.019453,-1.045520,-0.645925,-0.590669,2.735631,1.096386,0,0,1,-1.212704,-0.000850,0.762917,1.192078,1.560055,0.002585,1.751780,1,-10
9234,9234,21700279,1610612757,1610612764,1.950338,0.908407,-2.448327,0,1.781375,0,0.163685,-0.163685,-0.176936,1.347733,0.176936,-0.871552,0.687540,0.871552,1.373003,0,0,0,0,-0.141937,-1.692664,0.608012,0.141937,0,0,-0.706445,0.499961,-0.004824,0,0.108446,0.004824,-0.108446,0.003658,1.019453,-1.045520,0.005457,0.000691,1.092038,0.551721,0,0,0,0.013497,-0.000850,1.534324,1.192078,1.560055,0.002585,1.751780,0,-3
9235,9235,21700283,1610612742,1610612760,-0.159237,-0.346823,-0.114386,0,0.464945,0,0.163685,-0.163685,-0.838007,0.414362,0.838007,-0.218705,0.687540,0.218705,0.682875,1,0,1,0,1.072578,1.660330,0.608012,-1.072578,0,0,-0.706445,1.493014,-1.074945,0,-0.630338,1.074945,0.630338,-0.869726,0.014199,1.051853,0.656838,1.183412,-0.003691,-1.082274,0,0,0,1.239698,-0.623967,0.762917,0.014907,-1.530551,0.002585,-0.873972,0,-16
9236,9236,21700281,1610612738,1610612754,0.668894,0.365307,0.609586,0,-1.933986,0,0.059225,-0.059225,0.113645,-1.452381,-0.113645,-0.545128,0.687540,0.545128,-0.697380,0,0,0,0,-0.673287,-0.016167,0.608012,0.673287,0,0,-0.706445,0.003434,-0.646897,0,0.724099,0.646897,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,-1.099420,1.096386,0,0,0,0.013497,-0.623967,-0.779899,1.192078,1.560055,0.002585,0.876529,0,-10
9237,9237,21700282,1610612745,1610612752,-1.178771,-1.458661,-1.226125,0,-0.016676,0,-0.395302,0.395302,0.992650,-0.052324,-0.992650,-0.273109,0.010356,0.273109,-0.697380,0,0,0,0,0.328688,1.660330,-0.600946,-0.328688,0,0,-0.012572,-1.486146,-0.860921,0,-0.425120,0.860921,0.425120,1.313734,-0.991056,-2.094206,0.005457,0.000691,-1.099420,-0.537609,0,0,0,0.013497,-0.623967,-0.779899,-1.162265,-1.530551,0.002585,-1.749222,0,-15
9238,9238,21700284,1610612744,1610612740,-1.593147,1.080693,-1.772901,0,1.203430,0,0.009482,-0.009482,-0.346441,0.881048,0.346441,0.698391,0.010356,-0.698391,-0.007252,0,0,0,0,-0.521473,-0.016167,-0.600946,0.521473,1,0,-0.012572,0.499961,-0.646897,0,0.231577,0.646897,-0.231577,-0.433034,0.014199,1.051853,0.005457,-0.590669,1.092038,0.551721,1,0,0,0.013497,-0.623967,-0.008491,1.192078,0.014752,0.002585,-1.749222,0,-15

In [5]:
df_173A_test_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b = \
rcp('173A_test_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b.csv')

p(df_173A_test_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b)

(1027, 55)

,Unnamed: 0,game_id,team_id_a,team_id_b,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a
0,9239,21700285,1610612749,1610612762,1.028423,0.322683,1.055866,0,-0.423378,0,-0.094902,0.094902,0.619739,-0.519009,-0.619739,1.086991,-1.344011,-1.086991,-0.007252,0,0,0,0,0.222418,-0.016167,-1.205425,-0.222418,0,0,1.375175,-1.486146,1.279321,0,0.600969,-1.279321,-0.600969,0.440350,-0.991056,0.003167,-0.645925,0.000691,-1.099420,-0.537609,0,0,0,0.013497,1.245386,-0.008491,0.014907,0.014752,0.002585,0.876529,0,13
1,9240,21700287,1610612741,1610612748,-0.989872,2.184396,-0.524758,0,1.374673,0,-0.239616,0.239616,0.521802,0.881048,-0.521802,-1.089168,-0.666828,1.089168,1.373003,0,0,0,0,-0.673287,-0.016167,1.212491,0.673287,0,0,0.681302,-0.989619,-0.903726,0,0.724099,0.903726,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,1.092038,1.096386,0,0,0,-1.212704,-1.247085,1.534324,1.192078,0.014752,0.002585,-0.873972,0,7
2,9241,21700289,1610612751,1610612763,0.792883,0.757034,0.660032,0,0.625485,0,-0.091714,0.091714,0.653640,0.414362,-0.653640,0.542951,0.010356,-0.542951,0.682875,0,0,0,0,-0.734013,-0.016167,-0.600946,0.734013,0,1,-0.012572,-0.989619,0.637248,0,0.600969,-0.637248,-0.600969,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,0.622268,0.762917,0.014907,0.014752,1.897854,0.876529,0,-10
3,9242,21700288,1610612750,1610612756,-1.063182,1.568692,0.796300,0,-1.091531,0,-0.355300,0.355300,0.742428,-0.985695,-0.742428,-0.933728,-0.666828,0.933728,-0.697380,0,0,0,0,0.161692,-0.016167,1.212491,-0.161692,0,0,0.681302,-1.486146,-1.545799,0,-0.137815,1.545799,0.137815,0.877042,1.019453,0.003167,0.656838,0.592052,-0.003691,0.007056,0,0,0,1.239698,-1.247085,-0.779899,1.192078,0.014752,0.002585,-0.873972,0,-11
4,9243,21700292,1610612738,1610612765,-0.509033,0.020163,0.452923,0,-0.921539,0,-0.149777,0.149777,0.098895,-0.519009,-0.098895,-1.788648,2.041908,1.788648,-0.007252,0,0,0,0,0.738587,-0.854416,1.816969,-0.738587,0,0,-2.094192,0.499961,-2.059457,0,-0.178859,2.059457,0.178859,0.877042,2.024708,-1.045520,0.656838,1.183412,-0.003691,0.007056,0,0,0,-1.212704,-2.493320,-0.008491,2.369250,1.560055,0.002585,-0.873972,0,10
1022,10261,41700317,1610612744,1610612745,1.359732,1.106411,-1.506188,0,-0.016676,0,0.009482,-0.009482,0.040681,-0.052324,-0.040681,-0.001089,0.010356,0.001089,-0.007252,0,0,0,0,0.647498,-0.016167,0.003533,-0.647498,1,0,-0.012572,-0.493093,-0.004824,0,-0.014685,0.004824,0.014685,0.440350,0.014199,0.003167,0.005457,0.592052,-0.003691,-0.537609,1,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,-9
1023,10262,41700401,1610612739,1610612744,1.789289,0.507847,1.893345,0,-0.154391,0,0.009482,-0.009482,0.071918,-0.519009,-0.071918,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-0.840283,0.822081,0.003533,0.840283,0,0,-0.012572,-0.493093,-0.004824,0,0.395751,0.004824,-0.395751,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,-1.162265,0.014752,0.002585,0.876529,0,10
1024,10263,41700402,1610612739,1610612744,1.789289,0.507847,1.893345,0,-0.152875,0,0.009482,-0.009482,0.134429,-0.519009,-0.134429,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.265363,-0.016167,0.003533,1.265363,0,0,-0.012572,-0.989619,-0.004824,0,1.627057,0.004824,-1.627057,1.313734,0.014199,0.003167,-1.297306,-1.182030,-0.003691,1.096386,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,19
1025,10264,41700403,1610612739,1610612744,-1.790571,0.507847,1.893345,0,-0.151392,0,0.009482,-0.009482,0.070036,-0.519009,-0.070036,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.105958,-0.016167,0.003533,1.105958,0,0,-0.012572,-0.493093,-0.004824,0,0.806186,0.004824,-0.806186,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,8
1026,10265,41700404,1610612739,1610612744,-1.790571,0.507847,1.893345,0,-0.149940,0,0.009482,-0.009482,0.006887,-0.519009,-0.006887,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,0.328688,-0.016167,0.003533,-0.328688,0,0,-0.012572,0.003434,-0.004824,0,-0.835556,0.004824,0.835556,0.440350,-0.991056,0.003167,0.656838,0.000691,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,23

In [6]:
df_173B_train_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b = \
rcp('173B_train_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b.csv')

p(df_173B_train_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b)

(9239, 55)

,Unnamed: 0,game_id,team_id_a,team_id_b,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff,spread_a
0,0,21000001,1610612738,1610612748,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080,-8
1,1,21000002,1610612756,1610612757,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080,14
2,2,21000003,1610612745,1610612747,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080,2
3,3,21000009,1610612750,1610612758,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080,1
4,4,21000006,1610612748,1610612755,-1.032897,1.107642,-0.999416,-0.986140,6.365159,-0.051521,0.051521,0.053960,0.147592,-0.147592,5.790387,-0.842855,0.014355,7.898775,3.102298,-0.533348,3.264847,3.187965,0.946213,0.051047,3.536283,-0.013957,-0.047253,9.416709,10.459730,2.431156,10.681638,4.598174,4.885967,11.056652,-0.047487,4.450292,3.591373,2.529850,-0.053290,-0.051047,1.107269,2.667424,10.718900,3.552210,-0.879667,4.661921,-0.319484,1.247488,1.691365,8.286999,8.007766,3.521210,-0.677803,-0.598734,-10
9234,9234,21700279,1610612757,1610612764,-0.062390,0.043482,-0.999416,0.000068,-0.077003,0.038262,-0.038262,-0.126464,0.052352,-0.052352,-0.213098,-0.074347,0.602639,-0.305004,-0.793505,0.492109,1.087232,1.077779,0.277752,-0.044478,1.065005,-0.354275,-0.104545,-0.782981,-0.642620,0.296912,-0.476867,0.538429,-0.104984,-0.642822,-0.140721,-1.294302,-0.653168,-0.369978,-0.247981,0.044478,-1.914563,1.384050,-0.521085,-0.787147,-0.234987,-0.973632,-1.004135,-2.694313,0.931848,0.273061,0.163264,-0.448480,0.130420,0.013153,-3
9235,9235,21700283,1610612742,1610612760,-1.527583,1.549030,1.000585,-1.610131,-1.329247,-0.949356,0.949356,0.861512,0.528554,-0.528554,-0.966861,-1.133357,0.602639,-0.385919,0.210988,0.665238,1.800107,1.709931,0.965312,0.433148,1.506447,-0.817651,-1.179583,-0.324660,-0.293805,1.570976,-0.555684,2.049322,-0.542915,0.621986,-1.120744,0.592677,0.559558,0.507467,-1.076301,-0.433148,1.514838,-0.657875,-0.670930,1.003283,-0.967409,-0.540128,-1.002372,0.228034,1.378510,0.025707,0.196310,-0.184705,-0.567981,0.543946,-16
9236,9236,21700281,1610612738,1610612754,0.756971,-0.765107,-0.999416,0.511752,0.533583,0.988844,-0.988844,-0.819677,-0.423851,0.423851,0.360391,0.314749,0.230059,0.517316,0.943996,-0.806360,1.425820,1.257133,-0.562598,-0.522104,1.300402,1.179489,1.171164,-0.881496,-0.605537,-0.104654,-0.466565,-0.282372,-0.344745,-0.910008,1.167400,0.129369,-1.490526,-0.566802,1.044057,0.522104,0.411178,-1.009866,-0.406191,-0.875123,0.552851,0.543632,-1.278631,0.481034,-0.087806,-1.030682,-0.349282,1.555168,-0.463307,-0.900991,-10
9237,9237,21700282,1610612745,1610612752,1.112012,-1.162746,1.000585,1.219646,0.207296,0.801421,-0.801421,-0.873725,-0.328610,0.328610,0.137771,1.265482,-1.641555,0.457762,2.993704,0.465473,0.392415,0.580856,-1.231059,-0.331054,0.735847,0.072064,0.613248,0.731182,0.908290,-0.481408,0.732687,-0.400990,0.680357,-0.535179,0.664933,-0.898965,-0.393298,-0.509316,0.647596,0.331054,4.764505,-1.429827,0.654495,-0.396330,1.152273,0.977137,-0.462101,5.274412,-1.226123,0.139954,-0.431214,0.707843,1.522073,0.507086,-15
9238,9238,21700284,1610612744,1610612740,1.221205,-1.330505,1.000585,1.431094,0.742689,0.554517,-0.554517,-0.727349,-0.233370,0.233370,0.699161,1.504045,0.014355,0.558098,0.102394,1.584154,-1.030504,-0.983785,-1.498443,-0.235528,-1.113579,-0.468469,0.720931,1.017236,0.999532,-0.544344,0.938487,0.046932,0.450382,-0.909047,0.671339,0.932720,0.357437,1.349259,0.605118,0.235528,0.023156,-2.005767,0.844800,-0.745973,1.435821,-0.540128,-0.305763,0.053790,-0.145745,1.330639,0.001855,0.458857,0.813377,1.745603,-15

In [7]:
df_173B_test_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b = \
rcp('173B_test_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b.csv')

p(df_173B_test_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b)

(1027, 55)

,Unnamed: 0,game_id,team_id_a,team_id_b,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff,spread_a
0,9239,21700285,1610612749,1610612762,-0.438280,0.422273,-0.999416,-0.323850,-0.303239,0.364387,-0.364387,-0.410536,-0.233370,0.233370,-0.098158,-0.227520,-0.354764,0.983048,-1.024267,-1.565465,0.053647,0.047178,0.258654,-0.044478,0.663141,-0.023263,0.182812,0.513925,0.242592,0.311049,0.254052,0.780793,-0.770444,0.343267,0.432205,-0.444761,-0.653168,-0.074866,0.477684,0.044478,0.141268,0.889084,0.270134,0.704470,-0.323654,0.543632,-0.623327,0.183842,0.547129,-0.093945,-0.615885,0.401065,-1.033010,-1.505506,13
1,9240,21700287,1610612741,1610612748,-1.463110,1.550496,1.000585,-1.615443,-1.349915,-1.293305,1.293305,1.605389,0.528554,-0.528554,-1.271754,-1.461712,-1.081468,-0.838477,-0.440575,-0.706478,1.158199,1.137953,1.442784,0.624199,1.076303,0.708464,-0.913223,-1.258179,-1.238733,1.416558,-0.968262,1.129257,-1.406545,0.902627,-0.969862,-0.228538,-0.941912,0.170096,-1.005505,-0.624199,-0.723010,2.111757,-0.854721,-0.329222,-1.365485,-0.106624,-1.258891,-0.790590,2.544037,-0.582190,0.316977,1.269063,-1.523778,0.278550,7
2,9241,21700289,1610612751,1610612763,-0.184826,0.308938,-0.999416,-0.450517,-0.500014,-0.264757,0.264757,0.264632,0.147592,-0.147592,-0.157443,-0.040895,-0.399622,-0.116200,0.794679,0.059286,-0.385329,0.022127,-0.123324,0.146573,0.231652,-0.125155,-0.661561,0.018883,-0.092761,0.453353,0.207136,0.438744,0.073614,0.234662,-0.323630,0.200596,-0.653168,0.964429,-0.407273,-0.146573,-0.314013,0.669720,0.290133,0.625032,0.285004,0.326880,1.028775,-0.317461,0.295721,0.448738,-1.731027,-0.381070,0.322609,-0.067941,-10
3,9242,21700288,1610612750,1610612756,0.969342,-1.023985,1.000585,0.952290,0.938874,0.827234,-0.827234,-0.791469,-0.423851,0.423851,1.248452,1.321822,-1.299479,-1.839274,-0.766357,0.778438,-0.646212,-0.859737,-1.192861,-0.331054,-0.961706,0.540350,0.920701,0.574334,0.659574,-0.680178,0.822921,-2.086473,0.587388,-0.580351,0.875599,-0.898558,-0.624294,-0.231809,0.930783,0.331054,1.213666,-1.355574,0.909145,-1.922871,1.161510,-0.756880,0.248091,1.364641,0.100918,0.879725,0.404729,0.836795,0.753318,0.853576,-11
4,9243,21700292,1610612738,1610612765,0.790235,-0.745434,1.000585,0.642313,0.828795,0.679572,-0.679572,-0.638625,-0.233370,0.233370,0.708840,0.479367,-0.517902,0.410908,0.115968,0.798414,1.405140,1.360078,-0.724938,-0.522104,1.242045,0.492718,0.516962,-0.402118,-0.044503,0.518474,-0.137724,-1.410632,1.189238,-0.796598,0.619384,-0.450706,0.010944,-0.041443,0.566180,0.522104,0.687934,-0.837663,-0.121338,-1.248243,0.792989,-0.973632,0.899901,0.785766,-1.158458,-0.596616,-1.233626,1.533060,1.247518,-0.001591,10
1022,10261,41700317,1610612744,1610612745,-0.163598,0.183971,-0.999416,0.081536,0.420610,-0.325681,0.325681,0.368799,0.719035,-0.719035,0.880644,1.046285,0.014355,0.176638,-1.350048,1.584154,-0.798927,-0.824359,-0.839532,0.719724,-0.883876,0.028685,0.442873,0.359011,0.275932,-0.819971,0.034037,-0.599040,1.360496,-0.864837,0.047882,0.723472,0.675056,0.882450,0.183878,-0.719724,-4.541305,-0.539986,-0.127597,-0.742688,0.854871,-0.973632,0.731619,-1.495076,0.110108,0.406319,0.038192,-0.733868,1.695387,1.480207,-9
1023,10262,41700401,1610612739,1610612744,-0.740074,0.771474,-0.999416,-0.931315,-0.907299,-0.385720,0.385720,0.417635,0.909516,-0.909516,-0.424829,-0.593728,-0.023279,-0.117356,-0.644189,-0.799701,0.436074,0.393390,0.411445,0.815249,0.510405,-0.046855,-0.491187,-0.493237,-0.426349,-0.016023,-0.243501,-0.220378,-0.454839,0.709446,-0.285198,-1.508795,-0.508796,-0.708426,-0.393114,-0.815249,-0.510766,-0.168402,-0.107024,-0.380787,-0.452036,0.543632,1.359431,0.365893,0.047835,-0.323504,-1.048304,-0.077045,-0.640052,-0.849386,10
1024,10263,41700402,1610612739,1610612744,-0.764898,0.790665,-0.999416,-0.943140,-0.928631,-0.420524,0.420524,0.452617,1.004757,-1.004757,-0.570016,-0.635103,-0.097050,-0.114650,-0.657763,-1.665347,-0.067221,-0.139355,0.430543,0.910774,0.373135,-0.062494,-0.662461,-0.508473,-0.445433,-0.016023,-0.251641,-0.229044,-0.868305,0.647935,-0.759196,-2.372004,-2.299011,-0.708426,-1.571878,-0.910774,-0.510766,-0.214702,-0.121281,-0.519386,-0.542549,0.543632,1.359431,0.365893,0.047835,-0.339029,-1.110078,-0.077045,-0.730998,-0.849386,19
1025,10264,41700403,1610612739,1610612744,-0.817711,0.833086,1.000585,-0.982494,-0.940404,-0.454645,0.454645,0.486564,1.099997,-1.099997,-0.676487,-0.941450,-0.169367,-0.148423,-0.712060,-1.665347,-0.057644,-0.108611,0.755224,1.006300,0.376990,-0.079284,-0.962416,-0.549259,-0.476677,0.763998,-0.273419,-0.226886,-1.423671,0.788256,-1.470905,-2.303677,-1.346154,-0.708426,-1.571878,-1.006300,-0.510766,0.075022,-0.148718,-0.185688,-0.925847,0.543632,1.359431,0.392504,0.590597,-0.352941,-1.110078,1.181174,-1.566677,-0.849386,8
1026,10265,41700404,1610612739,1610612744,-0.834496,0.846108,1.000585,-1.004348,-0.953197,-0.488100,0.488100,0.519519,1.195238,-1.195238,-1.061232,-1.489882,-0.094872,-0.152702,-0.576317,-1.665347,0.379101,0.356149,1.261345,1.101825,0.309502,-0.097147,-1.362256,-0.564070,-0.494439,0.763998,-0.286379,-0.202012,-1.528872,0.838233,-2.182613,-1.649521,-1.346154,-0.708426,-1.571878,-1.101825,-0.510766,0.613609,-0.158870,0.596338,-1.439374,0.543632,1.359431,0.392504,0.590597,-0.360802,-1.110078,1.195694,-1.915019,-0.849386,23

In [8]:
df_train = \
pd.merge(df_173A_train_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b, 
          df_173B_train_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b,
          on=['game_id', 'team_id_a', 'team_id_b', 'Unnamed: 0', 'spread_a'])

p(df_train)

(9239, 105)

,Unnamed: 0,game_id,team_id_a,team_id_b,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff
0,0,21000001,1610612738,1610612748,-1.045984,2.249661,0.309284,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,-0.778288,0.010356,0.778288,-0.007252,0,0,0,0,3.197979,-0.016167,0.608012,-3.197979,0,0,-0.012572,0.499961,-0.261653,0,-2.477298,0.261653,2.477298,-0.433034,0.014199,-1.045520,0.656838,0.592052,-0.003691,-0.537609,0,0,0,-1.212704,-0.623967,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,-8,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
1,1,21000002,1610612756,1610612757,0.835137,-1.609206,0.383027,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,-0.560672,0.010356,0.560672,-0.007252,0,0,0,0,-3.178224,-0.016167,0.003533,3.178224,0,0,-0.012572,-0.493093,-0.347263,0,2.447929,0.347263,-2.447929,0.440350,0.014199,-2.094206,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-2.438905,-1.247085,-0.008491,0.014907,0.014752,-1.892685,0.876529,0,14,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
2,2,21000003,1610612745,1610612747,1.138839,-0.562003,1.001028,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,0.869375,0.010356,-0.869375,-0.007252,0,0,0,0,-3.178224,-0.016167,-1.205425,3.178224,0,0,-0.012572,-0.493093,1.065297,0,2.447929,-1.065297,-2.447929,0.440350,0.014199,-1.045520,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-1.212704,0.622268,-0.008491,0.014907,0.014752,1.897854,0.876529,0,2,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
3,3,21000009,1610612750,1610612758,-1.256725,0.877570,1.270549,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,0.232071,0.010356,-0.232071,-0.007252,0,1,0,0,3.197979,-0.016167,0.003533,-3.197979,0,0,-0.012572,0.499961,-0.004824,1,-2.477298,0.004824,2.477298,-0.433034,0.014199,1.051853,0.656838,0.592052,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,1,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
4,4,21000006,1610612748,1610612755,0.848535,-1.892884,-0.403891,0,6.083854,0,-0.030497,0.030497,6.416819,0.414362,-6.416819,0.232071,0.687540,-0.232071,4.133512,0,0,0,0,-3.178224,-6.722156,-0.600946,3.178224,0,0,-0.706445,-0.493093,0.252005,0,2.447929,-0.252005,-2.447929,0.877042,1.019453,-1.045520,-0.645925,-0.590669,2.735631,1.096386,0,0,1,-1.212704,-0.000850,0.762917,1.192078,1.560055,0.002585,1.751780,1,-10,-1.032897,1.107642,-0.999416,-0.986140,6.365159,-0.051521,0.051521,0.053960,0.147592,-0.147592,5.790387,-0.842855,0.014355,7.898775,3.102298,-0.533348,3.264847,3.187965,0.946213,0.051047,3.536283,-0.013957,-0.047253,9.416709,10.459730,2.431156,10.681638,4.598174,4.885967,11.056652,-0.047487,4.450292,3.591373,2.529850,-0.053290,-0.051047,1.107269,2.667424,10.718900,3.552210,-0.879667,4.661921,-0.319484,1.247488,1.691365,8.286999,8.007766,3.521210,-0.677803,-0.598734
9234,9234,21700279,1610612757,1610612764,1.950338,0.908407,-2.448327,0,1.781375,0,0.163685,-0.163685,-0.176936,1.347733,0.176936,-0.871552,0.687540,0.871552,1.373003,0,0,0,0,-0.141937,-1.692664,0.608012,0.141937,0,0,-0.706445,0.499961,-0.004824,0,0.108446,0.004824,-0.108446,0.003658,1.019453,-1.045520,0.005457,0.000691,1.092038,0.551721,0,0,0,0.013497,-0.000850,1.534324,1.192078,1.560055,0.002585,1.751780,0,-3,-0.062390,0.043482,-0.999416,0.000068,-0.077003,0.038262,-0.038262,-0.126464,0.052352,-0.052352,-0.213098,-0.074347,0.602639,-0.305004,-0.793505,0.492109,1.087232,1.077779,0.277752,-0.044478,1.065005,-0.354275,-0.104545,-0.782981,-0.642620,0.296912,-0.476867,0.538429,-0.104984,-0.642822,-0.140721,-1.294302,-0.653168,-0.369978,-0.247981,0.044478,-1.914563,1.384050,-0.521085,-0.787147,-0.234987,-0.973632,-1.004135,-2.694313,0.931848,0.273061,0.163264,-0.448480,0.130420,0.013153
9235,9235,21700283,1610612742,1610612760,-0.159237,-0.346823,-0.114386,0,0.464945,0,0.163685,-0.163685,-0.838007,0.414362,0.838007,-0.218705,0.687540,0.218705,0.682875,1,0,1,0,1.072578,1.660330,0.608012,-1.072578,0,0,-0.706445,1.493014,-1.074945,0,-0.630338,1.074945,0.630338,-0.869726,0.014199,1.051853,0.656838,1.183412,-0.003691,-1.082274,0,0,0,1.239698,-0.623967,0.762917,0.014907,-1.530551,0.002585,-0.873972,0,-16,-1.527583,1.549030,1.000585,-1.610131,-1.329247,-0.949356,0.949356,0.861512,0.528554,-0.528554,-0.966861,-1.133357,0.602639,-0.385919,0.210988,0.665238,1.800107,1.709931,0.965312,0.433148,1.506447,-0.817651,-1.179583,-0.324660,-0.293805,1.570976,-0.555684,2.049322,-0.542915,0.621986,-1.120744,0.592677,0.559558,0.507467,-1.076301,-0.433148,1.514838,-0.657875,-0.670930,1.003283,-0.967409,-0.540128,-1.002372,0.228034,1.378510,0.025707,0.196310,-0.184705,-0.567981,0.543946
9236,9236,21700281,1610612738,1610612754,0.668894,0.365307,0.609586,0,-1.933986,0,0.059225,-0.059225,0.113645,-1.452381,-0.113645,-0.545128,0.687540,0.545128,-0.697380,0,0,0,0,-0.673287,-0.016167,0.608012,0.673287,0,0,-0.706445,0.003434,-0.646897,0,0.724099,0.646897,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,-1.099420,1.096386,0,0,0,0.013497,-0.623967,-0.779899,1.192078,1.560055,0.002585,0.876529,0,-10,0.756971,-0.765107,-0.999416,0.511752,0.533583,0.988844,-0.988844,-0.819677,-0.423851,0.423851,0.360391,0.314749,0.230059,0.517316,0.943996,-0.806360,1.425820,1.257133,-0.562598,-0.522104,1.300402,1.179489,1.171164,-0.881496,-0.605537,-0.104654,-0.466565,-0.282372,-0.344745,-0.910008,1.167400,0.129369,-1.490526,-0.566802,1.044057,0.522104,0.411178,-1.009866,-0.406191,-0.875123,0.552851,0.543632,-1.278631,0.481034,-0.087806,-1.030682,-0.349282,1.555168,-0.463307,-0.900991
9237,9237,21700282,1610612745,1610612752,-1.178771,-1.458661,-1.226125,0,-0.016676,0,-0.395302,0.395302,0.992650,-0.052324,-0.992650,-0.273109,0.010356,0.273109,-0.697380,0,0,0,0,0.328688,1.660330,-0.600946,-0.328688,0,0,-0.012572,-1.486146,-0.860921,0,-0.425120,0.860921,0.425120,1.313734,-0.991056,-2.094206,0.005457,0.000691,-1.099420,-0.537609,0,0,0,0.013497,-0.623967,-0.779899,-1.162265,-1.530551,0.002585,-1.749222,0,-15,1.112012,-1.162746,1.000585,1.219646,0.207296,0.801421,-0.801421,-0.873725,-0.328610,0.328610,0.137771,1.265482,-1.641555,0.457762,2.993704,0.465473,0.392415,0.580856,-1.231059,-0.331054,0.735847,0.072064,0.613248,0.731182,0.908290,-0.481408,0.732687,-0.400990,0.680357,-0.535179,0.664933,-0.898965,-0.393298,-0.509316,0.647596,0.331054,4.764505,-1.429827,0.654495,-0.396330,1.152273,0.977137,-0.462101,5.274412,-1.226123,0.139954,-0.431214,0.707843,1.522073,0.507086
9238,9238,21700284,1610612744,1610612740,-1.593147,1.080693,-1.772901,0,1.203430,0,0.009482,-0.009482,-0.346441,0.881048,0.346441,0.698391,0.010356,-0.698391,-0.007252,0,0,0,0,-0.521473,-0.016167,-0.600946,0.521473,1,0,-0.012572,0.499961,-0.646897,0,0.231577,0.646897,-0.231577,-0.433034,0.014199,1.051853,0.005457,-0.590669,1.092038,0.551721,1,0,0,0.013497,-0.623967,-0.008491,1.192078,0.014752,0.002585,-1.749222,0,-15,1.221205,-1.330505,1.000585,1.431094,0.742689,0.554517,-0.554517,-0.727349,-0.233370,0.233370,0.699161,1.504045,0.014355,0.558098,0.102394,1.584154,-1.030504,-0.983785,-1.498443,-0.235528,-1.113579,-0.468469,0.720931,1.017236,0.999532,-0.544344,0.938487,0.046932,0.450382,-0.909047,0.671339,0.932720,0.357437,1.349259,0.605118,0.235528,0.023156,-2.005767,0.844800,-0.745973,1.435821,-0.540128,-0.305763,0.053790,-0.145745,1.330639,0.001855,0.458857,0.813377,1.745603

In [9]:
df_test = \
pd.merge(df_173A_test_split_time_series_172_trial4_top_50_trial_1_game_id_team_id_a_team_id_b, 
          df_173B_test_split_time_series_161_trial1_top_50_trial1_game_id_team_id_a_team_id_b,
          on=['game_id', 'team_id_a', 'team_id_b', 'Unnamed: 0', 'spread_a'])

p(df_test)

(1027, 105)

,Unnamed: 0,game_id,team_id_a,team_id_b,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff
0,9239,21700285,1610612749,1610612762,1.028423,0.322683,1.055866,0,-0.423378,0,-0.094902,0.094902,0.619739,-0.519009,-0.619739,1.086991,-1.344011,-1.086991,-0.007252,0,0,0,0,0.222418,-0.016167,-1.205425,-0.222418,0,0,1.375175,-1.486146,1.279321,0,0.600969,-1.279321,-0.600969,0.440350,-0.991056,0.003167,-0.645925,0.000691,-1.099420,-0.537609,0,0,0,0.013497,1.245386,-0.008491,0.014907,0.014752,0.002585,0.876529,0,13,-0.438280,0.422273,-0.999416,-0.323850,-0.303239,0.364387,-0.364387,-0.410536,-0.233370,0.233370,-0.098158,-0.227520,-0.354764,0.983048,-1.024267,-1.565465,0.053647,0.047178,0.258654,-0.044478,0.663141,-0.023263,0.182812,0.513925,0.242592,0.311049,0.254052,0.780793,-0.770444,0.343267,0.432205,-0.444761,-0.653168,-0.074866,0.477684,0.044478,0.141268,0.889084,0.270134,0.704470,-0.323654,0.543632,-0.623327,0.183842,0.547129,-0.093945,-0.615885,0.401065,-1.033010,-1.505506
1,9240,21700287,1610612741,1610612748,-0.989872,2.184396,-0.524758,0,1.374673,0,-0.239616,0.239616,0.521802,0.881048,-0.521802,-1.089168,-0.666828,1.089168,1.373003,0,0,0,0,-0.673287,-0.016167,1.212491,0.673287,0,0,0.681302,-0.989619,-0.903726,0,0.724099,0.903726,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,1.092038,1.096386,0,0,0,-1.212704,-1.247085,1.534324,1.192078,0.014752,0.002585,-0.873972,0,7,-1.463110,1.550496,1.000585,-1.615443,-1.349915,-1.293305,1.293305,1.605389,0.528554,-0.528554,-1.271754,-1.461712,-1.081468,-0.838477,-0.440575,-0.706478,1.158199,1.137953,1.442784,0.624199,1.076303,0.708464,-0.913223,-1.258179,-1.238733,1.416558,-0.968262,1.129257,-1.406545,0.902627,-0.969862,-0.228538,-0.941912,0.170096,-1.005505,-0.624199,-0.723010,2.111757,-0.854721,-0.329222,-1.365485,-0.106624,-1.258891,-0.790590,2.544037,-0.582190,0.316977,1.269063,-1.523778,0.278550
2,9241,21700289,1610612751,1610612763,0.792883,0.757034,0.660032,0,0.625485,0,-0.091714,0.091714,0.653640,0.414362,-0.653640,0.542951,0.010356,-0.542951,0.682875,0,0,0,0,-0.734013,-0.016167,-0.600946,0.734013,0,1,-0.012572,-0.989619,0.637248,0,0.600969,-0.637248,-0.600969,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,0.622268,0.762917,0.014907,0.014752,1.897854,0.876529,0,-10,-0.184826,0.308938,-0.999416,-0.450517,-0.500014,-0.264757,0.264757,0.264632,0.147592,-0.147592,-0.157443,-0.040895,-0.399622,-0.116200,0.794679,0.059286,-0.385329,0.022127,-0.123324,0.146573,0.231652,-0.125155,-0.661561,0.018883,-0.092761,0.453353,0.207136,0.438744,0.073614,0.234662,-0.323630,0.200596,-0.653168,0.964429,-0.407273,-0.146573,-0.314013,0.669720,0.290133,0.625032,0.285004,0.326880,1.028775,-0.317461,0.295721,0.448738,-1.731027,-0.381070,0.322609,-0.067941
3,9242,21700288,1610612750,1610612756,-1.063182,1.568692,0.796300,0,-1.091531,0,-0.355300,0.355300,0.742428,-0.985695,-0.742428,-0.933728,-0.666828,0.933728,-0.697380,0,0,0,0,0.161692,-0.016167,1.212491,-0.161692,0,0,0.681302,-1.486146,-1.545799,0,-0.137815,1.545799,0.137815,0.877042,1.019453,0.003167,0.656838,0.592052,-0.003691,0.007056,0,0,0,1.239698,-1.247085,-0.779899,1.192078,0.014752,0.002585,-0.873972,0,-11,0.969342,-1.023985,1.000585,0.952290,0.938874,0.827234,-0.827234,-0.791469,-0.423851,0.423851,1.248452,1.321822,-1.299479,-1.839274,-0.766357,0.778438,-0.646212,-0.859737,-1.192861,-0.331054,-0.961706,0.540350,0.920701,0.574334,0.659574,-0.680178,0.822921,-2.086473,0.587388,-0.580351,0.875599,-0.898558,-0.624294,-0.231809,0.930783,0.331054,1.213666,-1.355574,0.909145,-1.922871,1.161510,-0.756880,0.248091,1.364641,0.100918,0.879725,0.404729,0.836795,0.753318,0.853576
4,9243,21700292,1610612738,1610612765,-0.509033,0.020163,0.452923,0,-0.921539,0,-0.149777,0.149777,0.098895,-0.519009,-0.098895,-1.788648,2.041908,1.788648,-0.007252,0,0,0,0,0.738587,-0.854416,1.816969,-0.738587,0,0,-2.094192,0.499961,-2.059457,0,-0.178859,2.059457,0.178859,0.877042,2.024708,-1.045520,0.656838,1.183412,-0.003691,0.007056,0,0,0,-1.212704,-2.493320,-0.008491,2.369250,1.560055,0.002585,-0.873972,0,10,0.790235,-0.745434,1.000585,0.642313,0.828795,0.679572,-0.679572,-0.638625,-0.233370,0.233370,0.708840,0.479367,-0.517902,0.410908,0.115968,0.798414,1.405140,1.360078,-0.724938,-0.522104,1.242045,0.492718,0.516962,-0.402118,-0.044503,0.518474,-0.137724,-1.410632,1.189238,-0.796598,0.619384,-0.450706,0.010944,-0.041443,0.566180,0.522104,0.687934,-0.837663,-0.121338,-1.248243,0.792989,-0.973632,0.899901,0.785766,-1.158458,-0.596616,-1.233626,1.533060,1.247518,-0.001591
1022,10261,41700317,1610612744,1610612745,1.359732,1.106411,-1.506188,0,-0.016676,0,0.009482,-0.009482,0.040681,-0.052324,-0.040681,-0.001089,0.010356,0.001089,-0.007252,0,0,0,0,0.647498,-0.016167,0.003533,-0.647498,1,0,-0.012572,-0.493093,-0.004824,0,-0.014685,0.004824,0.014685,0.440350,0.014199,0.003167,0.005457,0.592052,-0.003691,-0.537609,1,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,-9,-0.163598,0.183971,-0.999416,0.081536,0.420610,-0.325681,0.325681,0.368799,0.719035,-0.719035,0.880644,1.046285,0.014355,0.176638,-1.350048,1.584154,-0.798927,-0.824359,-0.839532,0.719724,-0.883876,0.028685,0.442873,0.359011,0.275932,-0.819971,0.034037,-0.599040,1.360496,-0.864837,0.047882,0.723472,0.675056,0.882450,0.183878,-0.719724,-4.541305,-0.539986,-0.127597,-0.742688,0.854871,-0.973632,0.731619,-1.495076,0.110108,0.406319,0.038192,-0.733868,1.695387,1.480207
1023,10262,41700401,1610612739,1610612744,1.789289,0.507847,1.893345,0,-0.154391,0,0.009482,-0.009482,0.071918,-0.519009,-0.071918,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-0.840283,0.822081,0.003533,0.840283,0,0,-0.012572,-0.493093,-0.004824,0,0.395751,0.004824,-0.395751,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,-1.162265,0.014752,0.002585,0.876529,0,10,-0.740074,0.771474,-0.999416,-0.931315,-0.907299,-0.385720,0.385720,0.417635,0.909516,-0.909516,-0.424829,-0.593728,-0.023279,-0.117356,-0.644189,-0.799701,0.436074,0.393390,0.411445,0.815249,0.510405,-0.046855,-0.491187,-0.493237,-0.426349,-0.016023,-0.243501,-0.220378,-0.454839,0.709446,-0.285198,-1.508795,-0.508796,-0.708426,-0.393114,-0.815249,-0.510766,-0.168402,-0.107024,-0.380787,-0.452036,0.543632,1.359431,0.365893,0.047835,-0.323504,-1.048304,-0.077045,-0.640052,-0.849386
1024,10263,41700402,1610612739,1610612744,1.789289,0.507847,1.893345,0,-0.152875,0,0.009482,-0.009482,0.134429,-0.519009,-0.134429,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.265363,-0.016167,0.003533,1.265363,0,0,-0.012572,-0.989619,-0.004824,0,1.627057,0.004824,-1.627057,1.313734,0.014199,0.003167,-1.297306,-1.182030,-0.003691,1.096386,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,19,-0.764898,0.790665,-0.999416,-0.943140,-0.928631,-0.420524,0.420524,0.452617,1.004757,-1.004757,-0.570016,-0.635103,-0.097050,-0.114650,-0.657763,-1.665347,-0.067221,-0.139355,0.430543,0.910774,0.373135,-0.062494,-0.662461,-0.508473,-0.445433,-0.016023,-0.251641,-0.229044,-0.868305,0.647935,-0.759196,-2.372004,-2.299011,-0.708426,-1.571878,-0.910774,-0.510766,-0.214702,-0.121281,-0.519386,-0.542549,0.543632,1.359431,0.365893,0.047835,-0.339029,-1.110078,-0.077045,-0.730998,-0.849386
1025,10264,41700403,1610612739,1610612744,-1.790571,0.507847,1.893345,0,-0.151392,0,0.009482,-0.009482,0.070036,-0.519009,-0.070036,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.105958,-0.016167,0.003533,1.105958,0,0,-0.012572,-0.493093,-0.004824,0,0.806186,0.004824,-0.806186,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,8,-0.817711,0.833086,1.000585,-0.982494,-0.940404,-0.454645,0.454645,0.486564,1.099997,-1.099997,-0.676487,-0.941450,-0.169367,-0.148423,-0.712060,-1.665347,-0.057644,-0.108611,0.755224,1.006300,0.376990,-0.079284,-0.962416,-0.549259,-0.476677,0.763998,-0.273419,-0.226886,-1.423671,0.788256,-1.470905,-2.303677,-1.346154,-0.708426,-1.571878,-1.006300,-0.510766,0.075022,-0.148718,-0.185688,-0.925847,0.543632,1.359431,0.392504,0.590597,-0.352941,-1.110078,1.181174,-1.566677,-0.849386
1026,10265,41700404,1610612739,1610612744,-1.790571,0.507847,1.893345,0,-0.149940,0,0.009482,-0.009482,0.006887,-0.519009,-0.006887,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,0.328688,-0.016167,0.003533,-0.328688,0,0,-0.012572,0.003434,-0.004824,0,-0.835556,0.004824,0.835556,0.440350,-0.991056,0.003167,0.656838,0.000691,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,23,-0.834496,0.846108,1.000585,-1.004348,-0.953197,-0.488100,0.488100,0.519519,1.195238,-1.195238,-1.061232,-1.489882,-0.094872,-0.152702,-0.576317,-1.665347,0.379101,0.356149,1.261345,1.101825,0.309502,-0.097147,-1.362256,-0.564070,-0.494439,0.763998,-0.286379,-0.202012,-1.528872,0.838233,-2.182613,-1.649521,-1.346154,-0.708426,-1.571878,-1.101825,-0.510766,0.613609,-0.158870,0.596338,-1.439374,0.543632,1.359431,0.392504,0.590597,-0.360802,-1.110078,1.195694,-1.915019,-0.849386

In [10]:
df_train = \
df_train.drop(columns=['game_id', 'team_id_a', 'team_id_b', 'Unnamed: 0'])

p(df_train)

(9239, 101)

,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff
0,-1.045984,2.249661,0.309284,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,-0.778288,0.010356,0.778288,-0.007252,0,0,0,0,3.197979,-0.016167,0.608012,-3.197979,0,0,-0.012572,0.499961,-0.261653,0,-2.477298,0.261653,2.477298,-0.433034,0.014199,-1.045520,0.656838,0.592052,-0.003691,-0.537609,0,0,0,-1.212704,-0.623967,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,-8,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
1,0.835137,-1.609206,0.383027,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,-0.560672,0.010356,0.560672,-0.007252,0,0,0,0,-3.178224,-0.016167,0.003533,3.178224,0,0,-0.012572,-0.493093,-0.347263,0,2.447929,0.347263,-2.447929,0.440350,0.014199,-2.094206,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-2.438905,-1.247085,-0.008491,0.014907,0.014752,-1.892685,0.876529,0,14,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
2,1.138839,-0.562003,1.001028,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,0.869375,0.010356,-0.869375,-0.007252,0,0,0,0,-3.178224,-0.016167,-1.205425,3.178224,0,0,-0.012572,-0.493093,1.065297,0,2.447929,-1.065297,-2.447929,0.440350,0.014199,-1.045520,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-1.212704,0.622268,-0.008491,0.014907,0.014752,1.897854,0.876529,0,2,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
3,-1.256725,0.877570,1.270549,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,0.232071,0.010356,-0.232071,-0.007252,0,1,0,0,3.197979,-0.016167,0.003533,-3.197979,0,0,-0.012572,0.499961,-0.004824,1,-2.477298,0.004824,2.477298,-0.433034,0.014199,1.051853,0.656838,0.592052,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,1,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
4,0.848535,-1.892884,-0.403891,0,6.083854,0,-0.030497,0.030497,6.416819,0.414362,-6.416819,0.232071,0.687540,-0.232071,4.133512,0,0,0,0,-3.178224,-6.722156,-0.600946,3.178224,0,0,-0.706445,-0.493093,0.252005,0,2.447929,-0.252005,-2.447929,0.877042,1.019453,-1.045520,-0.645925,-0.590669,2.735631,1.096386,0,0,1,-1.212704,-0.000850,0.762917,1.192078,1.560055,0.002585,1.751780,1,-10,-1.032897,1.107642,-0.999416,-0.986140,6.365159,-0.051521,0.051521,0.053960,0.147592,-0.147592,5.790387,-0.842855,0.014355,7.898775,3.102298,-0.533348,3.264847,3.187965,0.946213,0.051047,3.536283,-0.013957,-0.047253,9.416709,10.459730,2.431156,10.681638,4.598174,4.885967,11.056652,-0.047487,4.450292,3.591373,2.529850,-0.053290,-0.051047,1.107269,2.667424,10.718900,3.552210,-0.879667,4.661921,-0.319484,1.247488,1.691365,8.286999,8.007766,3.521210,-0.677803,-0.598734
9234,1.950338,0.908407,-2.448327,0,1.781375,0,0.163685,-0.163685,-0.176936,1.347733,0.176936,-0.871552,0.687540,0.871552,1.373003,0,0,0,0,-0.141937,-1.692664,0.608012,0.141937,0,0,-0.706445,0.499961,-0.004824,0,0.108446,0.004824,-0.108446,0.003658,1.019453,-1.045520,0.005457,0.000691,1.092038,0.551721,0,0,0,0.013497,-0.000850,1.534324,1.192078,1.560055,0.002585,1.751780,0,-3,-0.062390,0.043482,-0.999416,0.000068,-0.077003,0.038262,-0.038262,-0.126464,0.052352,-0.052352,-0.213098,-0.074347,0.602639,-0.305004,-0.793505,0.492109,1.087232,1.077779,0.277752,-0.044478,1.065005,-0.354275,-0.104545,-0.782981,-0.642620,0.296912,-0.476867,0.538429,-0.104984,-0.642822,-0.140721,-1.294302,-0.653168,-0.369978,-0.247981,0.044478,-1.914563,1.384050,-0.521085,-0.787147,-0.234987,-0.973632,-1.004135,-2.694313,0.931848,0.273061,0.163264,-0.448480,0.130420,0.013153
9235,-0.159237,-0.346823,-0.114386,0,0.464945,0,0.163685,-0.163685,-0.838007,0.414362,0.838007,-0.218705,0.687540,0.218705,0.682875,1,0,1,0,1.072578,1.660330,0.608012,-1.072578,0,0,-0.706445,1.493014,-1.074945,0,-0.630338,1.074945,0.630338,-0.869726,0.014199,1.051853,0.656838,1.183412,-0.003691,-1.082274,0,0,0,1.239698,-0.623967,0.762917,0.014907,-1.530551,0.002585,-0.873972,0,-16,-1.527583,1.549030,1.000585,-1.610131,-1.329247,-0.949356,0.949356,0.861512,0.528554,-0.528554,-0.966861,-1.133357,0.602639,-0.385919,0.210988,0.665238,1.800107,1.709931,0.965312,0.433148,1.506447,-0.817651,-1.179583,-0.324660,-0.293805,1.570976,-0.555684,2.049322,-0.542915,0.621986,-1.120744,0.592677,0.559558,0.507467,-1.076301,-0.433148,1.514838,-0.657875,-0.670930,1.003283,-0.967409,-0.540128,-1.002372,0.228034,1.378510,0.025707,0.196310,-0.184705,-0.567981,0.543946
9236,0.668894,0.365307,0.609586,0,-1.933986,0,0.059225,-0.059225,0.113645,-1.452381,-0.113645,-0.545128,0.687540,0.545128,-0.697380,0,0,0,0,-0.673287,-0.016167,0.608012,0.673287,0,0,-0.706445,0.003434,-0.646897,0,0.724099,0.646897,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,-1.099420,1.096386,0,0,0,0.013497,-0.623967,-0.779899,1.192078,1.560055,0.002585,0.876529,0,-10,0.756971,-0.765107,-0.999416,0.511752,0.533583,0.988844,-0.988844,-0.819677,-0.423851,0.423851,0.360391,0.314749,0.230059,0.517316,0.943996,-0.806360,1.425820,1.257133,-0.562598,-0.522104,1.300402,1.179489,1.171164,-0.881496,-0.605537,-0.104654,-0.466565,-0.282372,-0.344745,-0.910008,1.167400,0.129369,-1.490526,-0.566802,1.044057,0.522104,0.411178,-1.009866,-0.406191,-0.875123,0.552851,0.543632,-1.278631,0.481034,-0.087806,-1.030682,-0.349282,1.555168,-0.463307,-0.900991
9237,-1.178771,-1.458661,-1.226125,0,-0.016676,0,-0.395302,0.395302,0.992650,-0.052324,-0.992650,-0.273109,0.010356,0.273109,-0.697380,0,0,0,0,0.328688,1.660330,-0.600946,-0.328688,0,0,-0.012572,-1.486146,-0.860921,0,-0.425120,0.860921,0.425120,1.313734,-0.991056,-2.094206,0.005457,0.000691,-1.099420,-0.537609,0,0,0,0.013497,-0.623967,-0.779899,-1.162265,-1.530551,0.002585,-1.749222,0,-15,1.112012,-1.162746,1.000585,1.219646,0.207296,0.801421,-0.801421,-0.873725,-0.328610,0.328610,0.137771,1.265482,-1.641555,0.457762,2.993704,0.465473,0.392415,0.580856,-1.231059,-0.331054,0.735847,0.072064,0.613248,0.731182,0.908290,-0.481408,0.732687,-0.400990,0.680357,-0.535179,0.664933,-0.898965,-0.393298,-0.509316,0.647596,0.331054,4.764505,-1.429827,0.654495,-0.396330,1.152273,0.977137,-0.462101,5.274412,-1.226123,0.139954,-0.431214,0.707843,1.522073,0.507086
9238,-1.593147,1.080693,-1.772901,0,1.203430,0,0.009482,-0.009482,-0.346441,0.881048,0.346441,0.698391,0.010356,-0.698391,-0.007252,0,0,0,0,-0.521473,-0.016167,-0.600946,0.521473,1,0,-0.012572,0.499961,-0.646897,0,0.231577,0.646897,-0.231577,-0.433034,0.014199,1.051853,0.005457,-0.590669,1.092038,0.551721,1,0,0,0.013497,-0.623967,-0.008491,1.192078,0.014752,0.002585,-1.749222,0,-15,1.221205,-1.330505,1.000585,1.431094,0.742689,0.554517,-0.554517,-0.727349,-0.233370,0.233370,0.699161,1.504045,0.014355,0.558098,0.102394,1.584154,-1.030504,-0.983785,-1.498443,-0.235528,-1.113579,-0.468469,0.720931,1.017236,0.999532,-0.544344,0.938487,0.046932,0.450382,-0.909047,0.671339,0.932720,0.357437,1.349259,0.605118,0.235528,0.023156,-2.005767,0.844800,-0.745973,1.435821,-0.540128,-0.305763,0.053790,-0.145745,1.330639,0.001855,0.458857,0.813377,1.745603

In [11]:
df_test = \
df_test.drop(columns=['game_id', 'team_id_a', 'team_id_b', 'Unnamed: 0'])

p(df_test)

(1027, 101)

,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff
0,1.028423,0.322683,1.055866,0,-0.423378,0,-0.094902,0.094902,0.619739,-0.519009,-0.619739,1.086991,-1.344011,-1.086991,-0.007252,0,0,0,0,0.222418,-0.016167,-1.205425,-0.222418,0,0,1.375175,-1.486146,1.279321,0,0.600969,-1.279321,-0.600969,0.440350,-0.991056,0.003167,-0.645925,0.000691,-1.099420,-0.537609,0,0,0,0.013497,1.245386,-0.008491,0.014907,0.014752,0.002585,0.876529,0,13,-0.438280,0.422273,-0.999416,-0.323850,-0.303239,0.364387,-0.364387,-0.410536,-0.233370,0.233370,-0.098158,-0.227520,-0.354764,0.983048,-1.024267,-1.565465,0.053647,0.047178,0.258654,-0.044478,0.663141,-0.023263,0.182812,0.513925,0.242592,0.311049,0.254052,0.780793,-0.770444,0.343267,0.432205,-0.444761,-0.653168,-0.074866,0.477684,0.044478,0.141268,0.889084,0.270134,0.704470,-0.323654,0.543632,-0.623327,0.183842,0.547129,-0.093945,-0.615885,0.401065,-1.033010,-1.505506
1,-0.989872,2.184396,-0.524758,0,1.374673,0,-0.239616,0.239616,0.521802,0.881048,-0.521802,-1.089168,-0.666828,1.089168,1.373003,0,0,0,0,-0.673287,-0.016167,1.212491,0.673287,0,0,0.681302,-0.989619,-0.903726,0,0.724099,0.903726,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,1.092038,1.096386,0,0,0,-1.212704,-1.247085,1.534324,1.192078,0.014752,0.002585,-0.873972,0,7,-1.463110,1.550496,1.000585,-1.615443,-1.349915,-1.293305,1.293305,1.605389,0.528554,-0.528554,-1.271754,-1.461712,-1.081468,-0.838477,-0.440575,-0.706478,1.158199,1.137953,1.442784,0.624199,1.076303,0.708464,-0.913223,-1.258179,-1.238733,1.416558,-0.968262,1.129257,-1.406545,0.902627,-0.969862,-0.228538,-0.941912,0.170096,-1.005505,-0.624199,-0.723010,2.111757,-0.854721,-0.329222,-1.365485,-0.106624,-1.258891,-0.790590,2.544037,-0.582190,0.316977,1.269063,-1.523778,0.278550
2,0.792883,0.757034,0.660032,0,0.625485,0,-0.091714,0.091714,0.653640,0.414362,-0.653640,0.542951,0.010356,-0.542951,0.682875,0,0,0,0,-0.734013,-0.016167,-0.600946,0.734013,0,1,-0.012572,-0.989619,0.637248,0,0.600969,-0.637248,-0.600969,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,0.622268,0.762917,0.014907,0.014752,1.897854,0.876529,0,-10,-0.184826,0.308938,-0.999416,-0.450517,-0.500014,-0.264757,0.264757,0.264632,0.147592,-0.147592,-0.157443,-0.040895,-0.399622,-0.116200,0.794679,0.059286,-0.385329,0.022127,-0.123324,0.146573,0.231652,-0.125155,-0.661561,0.018883,-0.092761,0.453353,0.207136,0.438744,0.073614,0.234662,-0.323630,0.200596,-0.653168,0.964429,-0.407273,-0.146573,-0.314013,0.669720,0.290133,0.625032,0.285004,0.326880,1.028775,-0.317461,0.295721,0.448738,-1.731027,-0.381070,0.322609,-0.067941
3,-1.063182,1.568692,0.796300,0,-1.091531,0,-0.355300,0.355300,0.742428,-0.985695,-0.742428,-0.933728,-0.666828,0.933728,-0.697380,0,0,0,0,0.161692,-0.016167,1.212491,-0.161692,0,0,0.681302,-1.486146,-1.545799,0,-0.137815,1.545799,0.137815,0.877042,1.019453,0.003167,0.656838,0.592052,-0.003691,0.007056,0,0,0,1.239698,-1.247085,-0.779899,1.192078,0.014752,0.002585,-0.873972,0,-11,0.969342,-1.023985,1.000585,0.952290,0.938874,0.827234,-0.827234,-0.791469,-0.423851,0.423851,1.248452,1.321822,-1.299479,-1.839274,-0.766357,0.778438,-0.646212,-0.859737,-1.192861,-0.331054,-0.961706,0.540350,0.920701,0.574334,0.659574,-0.680178,0.822921,-2.086473,0.587388,-0.580351,0.875599,-0.898558,-0.624294,-0.231809,0.930783,0.331054,1.213666,-1.355574,0.909145,-1.922871,1.161510,-0.756880,0.248091,1.364641,0.100918,0.879725,0.404729,0.836795,0.753318,0.853576
4,-0.509033,0.020163,0.452923,0,-0.921539,0,-0.149777,0.149777,0.098895,-0.519009,-0.098895,-1.788648,2.041908,1.788648,-0.007252,0,0,0,0,0.738587,-0.854416,1.816969,-0.738587,0,0,-2.094192,0.499961,-2.059457,0,-0.178859,2.059457,0.178859,0.877042,2.024708,-1.045520,0.656838,1.183412,-0.003691,0.007056,0,0,0,-1.212704,-2.493320,-0.008491,2.369250,1.560055,0.002585,-0.873972,0,10,0.790235,-0.745434,1.000585,0.642313,0.828795,0.679572,-0.679572,-0.638625,-0.233370,0.233370,0.708840,0.479367,-0.517902,0.410908,0.115968,0.798414,1.405140,1.360078,-0.724938,-0.522104,1.242045,0.492718,0.516962,-0.402118,-0.044503,0.518474,-0.137724,-1.410632,1.189238,-0.796598,0.619384,-0.450706,0.010944,-0.041443,0.566180,0.522104,0.687934,-0.837663,-0.121338,-1.248243,0.792989,-0.973632,0.899901,0.785766,-1.158458,-0.596616,-1.233626,1.533060,1.247518,-0.001591
1022,1.359732,1.106411,-1.506188,0,-0.016676,0,0.009482,-0.009482,0.040681,-0.052324,-0.040681,-0.001089,0.010356,0.001089,-0.007252,0,0,0,0,0.647498,-0.016167,0.003533,-0.647498,1,0,-0.012572,-0.493093,-0.004824,0,-0.014685,0.004824,0.014685,0.440350,0.014199,0.003167,0.005457,0.592052,-0.003691,-0.537609,1,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,-9,-0.163598,0.183971,-0.999416,0.081536,0.420610,-0.325681,0.325681,0.368799,0.719035,-0.719035,0.880644,1.046285,0.014355,0.176638,-1.350048,1.584154,-0.798927,-0.824359,-0.839532,0.719724,-0.883876,0.028685,0.442873,0.359011,0.275932,-0.819971,0.034037,-0.599040,1.360496,-0.864837,0.047882,0.723472,0.675056,0.882450,0.183878,-0.719724,-4.541305,-0.539986,-0.127597,-0.742688,0.854871,-0.973632,0.731619,-1.495076,0.110108,0.406319,0.038192,-0.733868,1.695387,1.480207
1023,1.789289,0.507847,1.893345,0,-0.154391,0,0.009482,-0.009482,0.071918,-0.519009,-0.071918,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-0.840283,0.822081,0.003533,0.840283,0,0,-0.012572,-0.493093,-0.004824,0,0.395751,0.004824,-0.395751,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,-1.162265,0.014752,0.002585,0.876529,0,10,-0.740074,0.771474,-0.999416,-0.931315,-0.907299,-0.385720,0.385720,0.417635,0.909516,-0.909516,-0.424829,-0.593728,-0.023279,-0.117356,-0.644189,-0.799701,0.436074,0.393390,0.411445,0.815249,0.510405,-0.046855,-0.491187,-0.493237,-0.426349,-0.016023,-0.243501,-0.220378,-0.454839,0.709446,-0.285198,-1.508795,-0.508796,-0.708426,-0.393114,-0.815249,-0.510766,-0.168402,-0.107024,-0.380787,-0.452036,0.543632,1.359431,0.365893,0.047835,-0.323504,-1.048304,-0.077045,-0.640052,-0.849386
1024,1.789289,0.507847,1.893345,0,-0.152875,0,0.009482,-0.009482,0.134429,-0.519009,-0.134429,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.265363,-0.016167,0.003533,1.265363,0,0,-0.012572,-0.989619,-0.004824,0,1.627057,0.004824,-1.627057,1.313734,0.014199,0.003167,-1.297306,-1.182030,-0.003691,1.096386,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,19,-0.764898,0.790665,-0.999416,-0.943140,-0.928631,-0.420524,0.420524,0.452617,1.004757,-1.004757,-0.570016,-0.635103,-0.097050,-0.114650,-0.657763,-1.665347,-0.067221,-0.139355,0.430543,0.910774,0.373135,-0.062494,-0.662461,-0.508473,-0.445433,-0.016023,-0.251641,-0.229044,-0.868305,0.647935,-0.759196,-2.372004,-2.299011,-0.708426,-1.571878,-0.910774,-0.510766,-0.214702,-0.121281,-0.519386,-0.542549,0.543632,1.359431,0.365893,0.047835,-0.339029,-1.110078,-0.077045,-0.730998,-0.849386
1025,-1.790571,0.507847,1.893345,0,-0.151392,0,0.009482,-0.009482,0.070036,-0.519009,-0.070036,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.105958,-0.016167,0.003533,1.105958,0,0,-0.012572,-0.493093,-0.004824,0,0.806186,0.004824,-0.806186,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,8,-0.817711,0.833086,1.000585,-0.982494,-0.940404,-0.454645,0.454645,0.486564,1.099997,-1.099997,-0.676487,-0.941450,-0.169367,-0.148423,-0.712060,-1.665347,-0.057644,-0.108611,0.755224,1.006300,0.376990,-0.079284,-0.962416,-0.549259,-0.476677,0.763998,-0.273419,-0.226886,-1.423671,0.788256,-1.470905,-2.303677,-1.346154,-0.708426,-1.571878,-1.006300,-0.510766,0.075022,-0.148718,-0.185688,-0.925847,0.543632,1.359431,0.392504,0.590597,-0.352941,-1.110078,1.181174,-1.566677,-0.849386
1026,-1.790571,0.507847,1.893345,0,-0.149940,0,0.009482,-0.009482,0.006887,-0.519009,-0.006887,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,0.328688,-0.016167,0.003533,-0.328688,0,0,-0.012572,0.003434,-0.004824,0,-0.835556,0.004824,0.835556,0.440350,-0.991056,0.003167,0.656838,0.000691,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,23,-0.834496,0.846108,1.000585,-1.004348,-0.953197,-0.488100,0.488100,0.519519,1.195238,-1.195238,-1.061232,-1.489882,-0.094872,-0.152702,-0.576317,-1.665347,0.379101,0.356149,1.261345,1.101825,0.309502,-0.097147,-1.362256,-0.564070,-0.494439,0.763998,-0.286379,-0.202012,-1.528872,0.838233,-2.182613,-1.649521,-1.346154,-0.708426,-1.571878,-1.101825,-0.510766,0.613609,-0.158870,0.596338,-1.439374,0.543632,1.359431,0.392504,0.590597,-0.360802,-1.110078,1.195694,-1.915019,-0.849386

In [12]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 
                           '173C_train_split_time_series_merge_173A_and_173B.csv')
if not os.path.exists(datapath_df):
    df_train.to_csv(datapath_df, index=False)

In [13]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 
                           '173C_test_split_time_series_merge_173A_and_173B.csv')
if not os.path.exists(datapath_df):
    df_test.to_csv(datapath_df, index=False)

In [14]:
df_train_readback = \
rcp('173C_train_split_time_series_merge_173A_and_173B.csv')

p(df_train_readback)

(9239, 101)

,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff
0,-1.045984,2.249661,0.309284,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,-0.778288,0.010356,0.778288,-0.007252,0,0,0,0,3.197979,-0.016167,0.608012,-3.197979,0,0,-0.012572,0.499961,-0.261653,0,-2.477298,0.261653,2.477298,-0.433034,0.014199,-1.045520,0.656838,0.592052,-0.003691,-0.537609,0,0,0,-1.212704,-0.623967,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,-8,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
1,0.835137,-1.609206,0.383027,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,-0.560672,0.010356,0.560672,-0.007252,0,0,0,0,-3.178224,-0.016167,0.003533,3.178224,0,0,-0.012572,-0.493093,-0.347263,0,2.447929,0.347263,-2.447929,0.440350,0.014199,-2.094206,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-2.438905,-1.247085,-0.008491,0.014907,0.014752,-1.892685,0.876529,0,14,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
2,1.138839,-0.562003,1.001028,0,-0.016676,0,0.009482,-0.009482,6.416819,-0.052324,-6.416819,0.869375,0.010356,-0.869375,-0.007252,0,0,0,0,-3.178224,-0.016167,-1.205425,3.178224,0,0,-0.012572,-0.493093,1.065297,0,2.447929,-1.065297,-2.447929,0.440350,0.014199,-1.045520,-0.645925,-0.590669,-0.003691,0.551721,0,0,0,-1.212704,0.622268,-0.008491,0.014907,0.014752,1.897854,0.876529,0,2,-0.039299,0.042704,-0.999416,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
3,-1.256725,0.877570,1.270549,0,-0.016676,0,0.009482,-0.009482,-6.465582,-0.052324,6.465582,0.232071,0.010356,-0.232071,-0.007252,0,1,0,0,3.197979,-0.016167,0.003533,-3.197979,0,0,-0.012572,0.499961,-0.004824,1,-2.477298,0.004824,2.477298,-0.433034,0.014199,1.051853,0.656838,0.592052,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,1,-0.039299,0.042704,1.000585,-0.042845,-0.048615,-0.051521,0.051521,0.053960,0.052352,-0.052352,-0.031614,-0.029451,0.014355,0.150282,-0.155516,-0.020620,-0.053063,-0.057707,0.029467,0.051047,-0.061937,-0.013957,-0.047253,-0.041311,-0.030891,-0.048821,-0.020129,-0.045168,-0.019354,0.019376,-0.047487,-0.015372,-0.104554,-0.007870,-0.053290,-0.051047,-0.106398,-0.093396,-0.016556,-0.032872,-0.026252,0.110128,-0.049559,-0.088860,-0.094422,-0.008676,0.001855,-0.025856,-0.017154,-0.031080
4,0.848535,-1.892884,-0.403891,0,6.083854,0,-0.030497,0.030497,6.416819,0.414362,-6.416819,0.232071,0.687540,-0.232071,4.133512,0,0,0,0,-3.178224,-6.722156,-0.600946,3.178224,0,0,-0.706445,-0.493093,0.252005,0,2.447929,-0.252005,-2.447929,0.877042,1.019453,-1.045520,-0.645925,-0.590669,2.735631,1.096386,0,0,1,-1.212704,-0.000850,0.762917,1.192078,1.560055,0.002585,1.751780,1,-10,-1.032897,1.107642,-0.999416,-0.986140,6.365159,-0.051521,0.051521,0.053960,0.147592,-0.147592,5.790387,-0.842855,0.014355,7.898775,3.102298,-0.533348,3.264847,3.187965,0.946213,0.051047,3.536283,-0.013957,-0.047253,9.416709,10.459730,2.431156,10.681638,4.598174,4.885967,11.056652,-0.047487,4.450292,3.591373,2.529850,-0.053290,-0.051047,1.107269,2.667424,10.718900,3.552210,-0.879667,4.661921,-0.319484,1.247488,1.691365,8.286999,8.007766,3.521210,-0.677803,-0.598734
9234,1.950338,0.908407,-2.448327,0,1.781375,0,0.163685,-0.163685,-0.176936,1.347733,0.176936,-0.871552,0.687540,0.871552,1.373003,0,0,0,0,-0.141937,-1.692664,0.608012,0.141937,0,0,-0.706445,0.499961,-0.004824,0,0.108446,0.004824,-0.108446,0.003658,1.019453,-1.045520,0.005457,0.000691,1.092038,0.551721,0,0,0,0.013497,-0.000850,1.534324,1.192078,1.560055,0.002585,1.751780,0,-3,-0.062390,0.043482,-0.999416,0.000068,-0.077003,0.038262,-0.038262,-0.126464,0.052352,-0.052352,-0.213098,-0.074347,0.602639,-0.305004,-0.793505,0.492109,1.087232,1.077779,0.277752,-0.044478,1.065005,-0.354275,-0.104545,-0.782981,-0.642620,0.296912,-0.476867,0.538429,-0.104984,-0.642822,-0.140721,-1.294302,-0.653168,-0.369978,-0.247981,0.044478,-1.914563,1.384050,-0.521085,-0.787147,-0.234987,-0.973632,-1.004135,-2.694313,0.931848,0.273061,0.163264,-0.448480,0.130420,0.013153
9235,-0.159237,-0.346823,-0.114386,0,0.464945,0,0.163685,-0.163685,-0.838007,0.414362,0.838007,-0.218705,0.687540,0.218705,0.682875,1,0,1,0,1.072578,1.660330,0.608012,-1.072578,0,0,-0.706445,1.493014,-1.074945,0,-0.630338,1.074945,0.630338,-0.869726,0.014199,1.051853,0.656838,1.183412,-0.003691,-1.082274,0,0,0,1.239698,-0.623967,0.762917,0.014907,-1.530551,0.002585,-0.873972,0,-16,-1.527583,1.549030,1.000585,-1.610131,-1.329247,-0.949356,0.949356,0.861512,0.528554,-0.528554,-0.966861,-1.133357,0.602639,-0.385919,0.210988,0.665238,1.800107,1.709931,0.965312,0.433148,1.506447,-0.817651,-1.179583,-0.324660,-0.293805,1.570976,-0.555684,2.049322,-0.542915,0.621986,-1.120744,0.592677,0.559558,0.507467,-1.076301,-0.433148,1.514838,-0.657875,-0.670930,1.003283,-0.967409,-0.540128,-1.002372,0.228034,1.378510,0.025707,0.196310,-0.184705,-0.567981,0.543946
9236,0.668894,0.365307,0.609586,0,-1.933986,0,0.059225,-0.059225,0.113645,-1.452381,-0.113645,-0.545128,0.687540,0.545128,-0.697380,0,0,0,0,-0.673287,-0.016167,0.608012,0.673287,0,0,-0.706445,0.003434,-0.646897,0,0.724099,0.646897,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,-1.099420,1.096386,0,0,0,0.013497,-0.623967,-0.779899,1.192078,1.560055,0.002585,0.876529,0,-10,0.756971,-0.765107,-0.999416,0.511752,0.533583,0.988844,-0.988844,-0.819677,-0.423851,0.423851,0.360391,0.314749,0.230059,0.517316,0.943996,-0.806360,1.425820,1.257133,-0.562598,-0.522104,1.300402,1.179489,1.171164,-0.881496,-0.605537,-0.104654,-0.466565,-0.282372,-0.344745,-0.910008,1.167400,0.129369,-1.490526,-0.566802,1.044057,0.522104,0.411178,-1.009866,-0.406191,-0.875123,0.552851,0.543632,-1.278631,0.481034,-0.087806,-1.030682,-0.349282,1.555168,-0.463307,-0.900991
9237,-1.178771,-1.458661,-1.226125,0,-0.016676,0,-0.395302,0.395302,0.992650,-0.052324,-0.992650,-0.273109,0.010356,0.273109,-0.697380,0,0,0,0,0.328688,1.660330,-0.600946,-0.328688,0,0,-0.012572,-1.486146,-0.860921,0,-0.425120,0.860921,0.425120,1.313734,-0.991056,-2.094206,0.005457,0.000691,-1.099420,-0.537609,0,0,0,0.013497,-0.623967,-0.779899,-1.162265,-1.530551,0.002585,-1.749222,0,-15,1.112012,-1.162746,1.000585,1.219646,0.207296,0.801421,-0.801421,-0.873725,-0.328610,0.328610,0.137771,1.265482,-1.641555,0.457762,2.993704,0.465473,0.392415,0.580856,-1.231059,-0.331054,0.735847,0.072064,0.613248,0.731182,0.908290,-0.481408,0.732687,-0.400990,0.680357,-0.535179,0.664933,-0.898965,-0.393298,-0.509316,0.647596,0.331054,4.764505,-1.429827,0.654495,-0.396330,1.152273,0.977137,-0.462101,5.274412,-1.226123,0.139954,-0.431214,0.707843,1.522073,0.507086
9238,-1.593147,1.080693,-1.772901,0,1.203430,0,0.009482,-0.009482,-0.346441,0.881048,0.346441,0.698391,0.010356,-0.698391,-0.007252,0,0,0,0,-0.521473,-0.016167,-0.600946,0.521473,1,0,-0.012572,0.499961,-0.646897,0,0.231577,0.646897,-0.231577,-0.433034,0.014199,1.051853,0.005457,-0.590669,1.092038,0.551721,1,0,0,0.013497,-0.623967,-0.008491,1.192078,0.014752,0.002585,-1.749222,0,-15,1.221205,-1.330505,1.000585,1.431094,0.742689,0.554517,-0.554517,-0.727349,-0.233370,0.233370,0.699161,1.504045,0.014355,0.558098,0.102394,1.584154,-1.030504,-0.983785,-1.498443,-0.235528,-1.113579,-0.468469,0.720931,1.017236,0.999532,-0.544344,0.938487,0.046932,0.450382,-0.909047,0.671339,0.932720,0.357437,1.349259,0.605118,0.235528,0.023156,-2.005767,0.844800,-0.745973,1.435821,-0.540128,-0.305763,0.053790,-0.145745,1.330639,0.001855,0.458857,0.813377,1.745603

In [15]:
df_test_readback = \
rcp('173C_test_split_time_series_merge_173A_and_173B.csv')

p(df_test_readback)

(1027, 101)

,travel_distance_diff,latitude_diff,longitude_diff,team_id_b_1610612759,games_back_to_back_percentage_game_window999_diff,city_proper_metro_Area_b_San Antonio,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,away_game_percent_day_window999_diff,games_back_to_back_count_game_window999_diff,home_game_percent_day_window999_diff,future_Away_game_percent_day_window12_diff,game_count_day_window999_diff,future_home_game_percent_day_window12_diff,games_back_to_back_percentage_game_window12_diff,city_proper_metro_Area_b_Oklahoma City,city_proper_metro_Area_b_Sacramento,team_id_b_1610612760,season_2011-12,home_game_percent_day_window12_diff,game_date_diff_diff,future_home_game_count_day_window12_diff,away_game_percent_day_window12_diff,team_id_a_1610612744,team_id_a_1610612751,future_game_count_day_window999_diff,home_game_count_day_window999_diff,future_Away_game_percent_day_window8_diff,team_id_b_1610612758,away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window999_diff,game_count_day_window12_diff,future_game_count_day_window12_diff,home_game_count_day_window8_diff,home_game_count_day_window12_diff,games_back_to_back_percentage_game_window5_diff,away_game_count_day_window12_diff,city_proper_metro_Area_a_San Francisco,team_id_a_1610612747,team_id_b_1610612755,future_game_count_day_window8_diff,future_Away_game_count_day_window8_diff,games_back_to_back_count_game_window12_diff,game_count_day_window8_diff,game_count_day_window5_diff,future_game_count_day_window2_diff,away_game_count_day_window2_diff,city_proper_metro_Area_b_Philadelphia,spread_a,NET_RATING_cma999_diff,spread_cma999_diff,away_home_a,E_NET_RATING_cma999_diff,PIE_cma999_diff,win_pct_diff,opp_win_pct_diff,strength_of_schedule_diff,losses_diff,opp_losses_diff,PIE_cma12_diff,E_NET_RATING_cma12_diff,away_home__cma999_diff,pf_cma999_diff,fg3a_cma12_diff,E_NET_RATING_cmax5_diff,lc_max_MIN_cma5_diff,lc_max_POSS_cma5_diff,spread_cma12_diff,opp_wins_diff,lc_max_MIN_cma12_diff,opp_opps_win_pct_diff,w_pct_cma12_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,lc_sum_POSS_cmax5_diff,E_OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma999_diff,PIE_cma5_diff,E_DEF_RATING_cma12_diff,w_pct_cma5_diff,lc_mean_TS_PCT_cma5_diff,AST_RATIO_cmax5_diff,lc_mean_EFG_PCT_cmax999_diff,w_pct_cmax5_diff,wins_diff,lc_max_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cma5_diff,OFF_RATING_cma999_diff,lc_sum_TS_PCT_cma5_diff,NET_RATING_cma12_diff,pf_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_max_AST_TOV_cmax12_diff,lc_sum_AST_PCT_cmax5_diff,fg3_pct_cma999_diff,ft_pct_cmax12_diff,lc_max_MIN_cmax5_diff,E_NET_RATING_cma5_diff,E_NET_RATING_cmax12_diff
0,1.028423,0.322683,1.055866,0,-0.423378,0,-0.094902,0.094902,0.619739,-0.519009,-0.619739,1.086991,-1.344011,-1.086991,-0.007252,0,0,0,0,0.222418,-0.016167,-1.205425,-0.222418,0,0,1.375175,-1.486146,1.279321,0,0.600969,-1.279321,-0.600969,0.440350,-0.991056,0.003167,-0.645925,0.000691,-1.099420,-0.537609,0,0,0,0.013497,1.245386,-0.008491,0.014907,0.014752,0.002585,0.876529,0,13,-0.438280,0.422273,-0.999416,-0.323850,-0.303239,0.364387,-0.364387,-0.410536,-0.233370,0.233370,-0.098158,-0.227520,-0.354764,0.983048,-1.024267,-1.565465,0.053647,0.047178,0.258654,-0.044478,0.663141,-0.023263,0.182812,0.513925,0.242592,0.311049,0.254052,0.780793,-0.770444,0.343267,0.432205,-0.444761,-0.653168,-0.074866,0.477684,0.044478,0.141268,0.889084,0.270134,0.704470,-0.323654,0.543632,-0.623327,0.183842,0.547129,-0.093945,-0.615885,0.401065,-1.033010,-1.505506
1,-0.989872,2.184396,-0.524758,0,1.374673,0,-0.239616,0.239616,0.521802,0.881048,-0.521802,-1.089168,-0.666828,1.089168,1.373003,0,0,0,0,-0.673287,-0.016167,1.212491,0.673287,0,0,0.681302,-0.989619,-0.903726,0,0.724099,0.903726,-0.724099,0.440350,1.019453,0.003167,-0.645925,-0.590669,1.092038,1.096386,0,0,0,-1.212704,-1.247085,1.534324,1.192078,0.014752,0.002585,-0.873972,0,7,-1.463110,1.550496,1.000585,-1.615443,-1.349915,-1.293305,1.293305,1.605389,0.528554,-0.528554,-1.271754,-1.461712,-1.081468,-0.838477,-0.440575,-0.706478,1.158199,1.137953,1.442784,0.624199,1.076303,0.708464,-0.913223,-1.258179,-1.238733,1.416558,-0.968262,1.129257,-1.406545,0.902627,-0.969862,-0.228538,-0.941912,0.170096,-1.005505,-0.624199,-0.723010,2.111757,-0.854721,-0.329222,-1.365485,-0.106624,-1.258891,-0.790590,2.544037,-0.582190,0.316977,1.269063,-1.523778,0.278550
2,0.792883,0.757034,0.660032,0,0.625485,0,-0.091714,0.091714,0.653640,0.414362,-0.653640,0.542951,0.010356,-0.542951,0.682875,0,0,0,0,-0.734013,-0.016167,-0.600946,0.734013,0,1,-0.012572,-0.989619,0.637248,0,0.600969,-0.637248,-0.600969,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,0.622268,0.762917,0.014907,0.014752,1.897854,0.876529,0,-10,-0.184826,0.308938,-0.999416,-0.450517,-0.500014,-0.264757,0.264757,0.264632,0.147592,-0.147592,-0.157443,-0.040895,-0.399622,-0.116200,0.794679,0.059286,-0.385329,0.022127,-0.123324,0.146573,0.231652,-0.125155,-0.661561,0.018883,-0.092761,0.453353,0.207136,0.438744,0.073614,0.234662,-0.323630,0.200596,-0.653168,0.964429,-0.407273,-0.146573,-0.314013,0.669720,0.290133,0.625032,0.285004,0.326880,1.028775,-0.317461,0.295721,0.448738,-1.731027,-0.381070,0.322609,-0.067941
3,-1.063182,1.568692,0.796300,0,-1.091531,0,-0.355300,0.355300,0.742428,-0.985695,-0.742428,-0.933728,-0.666828,0.933728,-0.697380,0,0,0,0,0.161692,-0.016167,1.212491,-0.161692,0,0,0.681302,-1.486146,-1.545799,0,-0.137815,1.545799,0.137815,0.877042,1.019453,0.003167,0.656838,0.592052,-0.003691,0.007056,0,0,0,1.239698,-1.247085,-0.779899,1.192078,0.014752,0.002585,-0.873972,0,-11,0.969342,-1.023985,1.000585,0.952290,0.938874,0.827234,-0.827234,-0.791469,-0.423851,0.423851,1.248452,1.321822,-1.299479,-1.839274,-0.766357,0.778438,-0.646212,-0.859737,-1.192861,-0.331054,-0.961706,0.540350,0.920701,0.574334,0.659574,-0.680178,0.822921,-2.086473,0.587388,-0.580351,0.875599,-0.898558,-0.624294,-0.231809,0.930783,0.331054,1.213666,-1.355574,0.909145,-1.922871,1.161510,-0.756880,0.248091,1.364641,0.100918,0.879725,0.404729,0.836795,0.753318,0.853576
4,-0.509033,0.020163,0.452923,0,-0.921539,0,-0.149777,0.149777,0.098895,-0.519009,-0.098895,-1.788648,2.041908,1.788648,-0.007252,0,0,0,0,0.738587,-0.854416,1.816969,-0.738587,0,0,-2.094192,0.499961,-2.059457,0,-0.178859,2.059457,0.178859,0.877042,2.024708,-1.045520,0.656838,1.183412,-0.003691,0.007056,0,0,0,-1.212704,-2.493320,-0.008491,2.369250,1.560055,0.002585,-0.873972,0,10,0.790235,-0.745434,1.000585,0.642313,0.828795,0.679572,-0.679572,-0.638625,-0.233370,0.233370,0.708840,0.479367,-0.517902,0.410908,0.115968,0.798414,1.405140,1.360078,-0.724938,-0.522104,1.242045,0.492718,0.516962,-0.402118,-0.044503,0.518474,-0.137724,-1.410632,1.189238,-0.796598,0.619384,-0.450706,0.010944,-0.041443,0.566180,0.522104,0.687934,-0.837663,-0.121338,-1.248243,0.792989,-0.973632,0.899901,0.785766,-1.158458,-0.596616,-1.233626,1.533060,1.247518,-0.001591
1022,1.359732,1.106411,-1.506188,0,-0.016676,0,0.009482,-0.009482,0.040681,-0.052324,-0.040681,-0.001089,0.010356,0.001089,-0.007252,0,0,0,0,0.647498,-0.016167,0.003533,-0.647498,1,0,-0.012572,-0.493093,-0.004824,0,-0.014685,0.004824,0.014685,0.440350,0.014199,0.003167,0.005457,0.592052,-0.003691,-0.537609,1,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,-9,-0.163598,0.183971,-0.999416,0.081536,0.420610,-0.325681,0.325681,0.368799,0.719035,-0.719035,0.880644,1.046285,0.014355,0.176638,-1.350048,1.584154,-0.798927,-0.824359,-0.839532,0.719724,-0.883876,0.028685,0.442873,0.359011,0.275932,-0.819971,0.034037,-0.599040,1.360496,-0.864837,0.047882,0.723472,0.675056,0.882450,0.183878,-0.719724,-4.541305,-0.539986,-0.127597,-0.742688,0.854871,-0.973632,0.731619,-1.495076,0.110108,0.406319,0.038192,-0.733868,1.695387,1.480207
1023,1.789289,0.507847,1.893345,0,-0.154391,0,0.009482,-0.009482,0.071918,-0.519009,-0.071918,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-0.840283,0.822081,0.003533,0.840283,0,0,-0.012572,-0.493093,-0.004824,0,0.395751,0.004824,-0.395751,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,-1.162265,0.014752,0.002585,0.876529,0,10,-0.740074,0.771474,-0.999416,-0.931315,-0.907299,-0.385720,0.385720,0.417635,0.909516,-0.909516,-0.424829,-0.593728,-0.023279,-0.117356,-0.644189,-0.799701,0.436074,0.393390,0.411445,0.815249,0.510405,-0.046855,-0.491187,-0.493237,-0.426349,-0.016023,-0.243501,-0.220378,-0.454839,0.709446,-0.285198,-1.508795,-0.508796,-0.708426,-0.393114,-0.815249,-0.510766,-0.168402,-0.107024,-0.380787,-0.452036,0.543632,1.359431,0.365893,0.047835,-0.323504,-1.048304,-0.077045,-0.640052,-0.849386
1024,1.789289,0.507847,1.893345,0,-0.152875,0,0.009482,-0.009482,0.134429,-0.519009,-0.134429,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.265363,-0.016167,0.003533,1.265363,0,0,-0.012572,-0.989619,-0.004824,0,1.627057,0.004824,-1.627057,1.313734,0.014199,0.003167,-1.297306,-1.182030,-0.003691,1.096386,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,0.876529,0,19,-0.764898,0.790665,-0.999416,-0.943140,-0.928631,-0.420524,0.420524,0.452617,1.004757,-1.004757,-0.570016,-0.635103,-0.097050,-0.114650,-0.657763,-1.665347,-0.067221,-0.139355,0.430543,0.910774,0.373135,-0.062494,-0.662461,-0.508473,-0.445433,-0.016023,-0.251641,-0.229044,-0.868305,0.647935,-0.759196,-2.372004,-2.299011,-0.708426,-1.571878,-0.910774,-0.510766,-0.214702,-0.121281,-0.519386,-0.542549,0.543632,1.359431,0.365893,0.047835,-0.339029,-1.110078,-0.077045,-0.730998,-0.849386
1025,-1.790571,0.507847,1.893345,0,-0.151392,0,0.009482,-0.009482,0.070036,-0.519009,-0.070036,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,-1.105958,-0.016167,0.003533,1.105958,0,0,-0.012572,-0.493093,-0.004824,0,0.806186,0.004824,-0.806186,0.877042,-0.991056,0.003167,-0.645925,-1.182030,-0.003691,0.551721,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,8,-0.817711,0.833086,1.000585,-0.982494,-0.940404,-0.454645,0.454645,0.486564,1.099997,-1.099997,-0.676487,-0.941450,-0.169367,-0.148423,-0.712060,-1.665347,-0.057644,-0.108611,0.755224,1.006300,0.376990,-0.079284,-0.962416,-0.549259,-0.476677,0.763998,-0.273419,-0.226886,-1.423671,0.788256,-1.470905,-2.303677,-1.346154,-0.708426,-1.571878,-1.006300,-0.510766,0.075022,-0.148718,-0.185688,-0.925847,0.543632,1.359431,0.392504,0.590597,-0.352941,-1.110078,1.181174,-1.566677,-0.849386
1026,-1.790571,0.507847,1.893345,0,-0.149940,0,0.009482,-0.009482,0.006887,-0.519009,-0.006887,-0.001089,0.687540,0.001089,-0.007252,0,0,0,0,0.328688,-0.016167,0.003533,-0.328688,0,0,-0.012572,0.003434,-0.004824,0,-0.835556,0.004824,0.835556,0.440350,-0.991056,0.003167,0.656838,0.000691,-0.003691,-0.537609,0,0,0,0.013497,-0.000850,-0.008491,0.014907,0.014752,0.002585,-0.873972,0,23,-0.834496,0.846108,1.000585,-1.004348,-0.953197,-0.488100,0.488100,0.519519,1.195238,-1.195238,-1.061232,-1.489882,-0.094872,-0.152702,-0.576317,-1.665347,0.379101,0.356149,1.261345,1.101825,0.309502,-0.097147,-1.362256,-0.564070,-0.494439,0.763998,-0.286379,-0.202012,-1.528872,0.838233,-2.182613,-1.649521,-1.346154,-0.708426,-1.571878,-1.101825,-0.510766,0.613609,-0.158870,0.596338,-1.439374,0.543632,1.359431,0.392504,0.590597,-0.360802,-1.110078,1.195694,-1.915019,-0.849386