In [1]:
# Target variable 'spread_a' is most predicted by stat differences which should be used.

random_state_2909 = 2909

# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

## 4.2 Introduction<a id='4.2_Introduction'></a>

## 4.3 Imports<a id='4.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 4.4 Functions<a id='4.4_Imports'></a>

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 4.5 Load Data<a id='4.5_Load_Data'></a>

In [4]:
df_stats = rcp('53AAprediction_stats_2010_2018.csv', ['game_date'])
p(df_stats)

(10266, 107)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,team_id_a,spread_a,away_home_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,team_id_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,Celtics,BOS,Boston,1610612738,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami,1610612748,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,1610612756,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland,1610612757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,1610612745,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles,1610612747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,1610612750,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento,1610612758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,Heat,MIA,Miami,1610612748,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia,1610612755,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,Warriors,GSW,Golden State,1610612744,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston,1610612745,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,Cavaliers,CLE,Cleveland,1610612739,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,Cavaliers,CLE,Cleveland,1610612739,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,Cavaliers,CLE,Cleveland,1610612739,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,Cavaliers,CLE,Cleveland,1610612739,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [5]:
df_stats_gitiab_spread = df_stats.loc[:, ['game_id', 'team_id_a', 'team_id_b', 'spread_a']]
p(df_stats_gitiab_spread)

(10266, 4)

        game_id   team_id_a   team_id_b  spread_a
0      21000001  1610612738  1610612748        -8
1      21000002  1610612756  1610612757        14
2      21000003  1610612745  1610612747         2
3      21000009  1610612750  1610612758         1
4      21000006  1610612748  1610612755       -10
10261  41700317  1610612744  1610612745        -9
10262  41700401  1610612739  1610612744        10
10263  41700402  1610612739  1610612744        19
10264  41700403  1610612739  1610612744         8
10265  41700404  1610612739  1610612744        23

In [6]:
df = rcp('72_71C_schedule_location_differences_2010_2018.csv', ['game_date'])
p(df)

(10266, 85)

,game_id,team_id_a,game_date,season,game_time_zone_a,time_zone_a,time_zone_diff_a,time_zone_diff_abs_a,city_proper_metro_area_a,Country/Region_a,city_proper_metro_area_GDP_bil_a,city_proper_metro_area_GDP_bil1_a,team_id_b,game_time_zone_b,time_zone_b,city_proper_metro_area_b,Country/Region_b,city_proper_metro_area_GDP_bil_b,city_proper_metro_area_GDP_bil1_b,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff
0,21000001,1610612738,2010-10-26,2010-11,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,1610612748,America/New_York,America/New_York,Miami,United States,377.5,262.7,1.0,16.586081,9.135329,0.0,0.0,-1257.755091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.5,0.5,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,-2.0,1.0,-1.0,-0.238095,0.238095,-5.0,-7.0,-12.0,0.010349,-0.010349
1,21000002,1610612756,2010-10-26,2010-11,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,1610612757,America/Los_Angeles,America/Los_Angeles,Portland,United States,164.419,158.5,-1.0,-12.071810,10.600053,0.0,0.0,1005.606855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,0.0,-1.0,-1.0,0.5,-0.5,0.0,0.0,0.0,0.000000,0.000000,-2.0,0.0,-2.0,-0.133333,0.133333,-2.0,0.0,-2.0,-0.171429,0.171429,-3.0,-3.0,-6.0,0.000000,0.000000
2,21000003,1610612745,2010-10-26,2010-11,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,1610612747,America/Los_Angeles,America/Los_Angeles,Los Angeles,United States,"1,048","1,528.27",-1.0,-4.294753,22.875069,0.0,0.0,1371.020326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,2.0,-1.0,1.0,1.0,-1.0,1.0,0.0,1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.416667,-0.416667,1.0,-2.0,-1.0,0.266667,-0.266667,-5.0,-5.0,-10.0,0.000000,0.000000
3,21000006,1610612748,2010-10-27,2010-11,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,1610612755,America/New_York,America/New_York,Philadelphia,United States,444.148,746.5,-1.0,-14.178551,-5.030094,0.0,0.0,1021.727021,-8.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,-1.0,1.0,1.0,-1.0,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,-1.0,-1.0,0.100000,-0.100000,0.0,-1.0,-1.0,0.071429,-0.071429,6.0,9.0,15.0,-0.015551,0.015551
4,21000005,1610612765,2010-10-27,2010-11,America/New_York,America/Detroit,0,0,Detroit,United States,267.731,407.5,1610612751,America/New_York,America/New_York,New York,United States,"1,732","1,803",-1.0,1.497562,-8.949554,0.0,0.0,473.715215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,0.666667,-0.666667,3.0,-2.0,1.0,0.600000,-0.600000,1.0,0.0,1.0,0.095238,-0.095238,0.0,0.0,0.0,0.000000,0.000000
10261,41700317,1610612744,2018-05-28,2017-18,America/Chicago,America/Los_Angeles,2,2,San Francisco,United States,995.0,631.0,1610612745,America/Chicago,America/Chicago,Houston,United States,478.778,883.2,-1.0,8.095728,-26.924439,0.0,0.0,1636.798262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.200000,0.200000,1.0,-1.0,0.0,0.010101,-0.010101,1.0,-1.0,0.0,1.0,-1.0,1.0,0.0,1.0,0.500000,-0.500000,1.0,1.0,2.0,0.333333,-0.333333,3.0,1.0,4.0,0.600000,-0.600000,3.0,1.0,4.0,0.600000,-0.600000
10262,41700401,1610612739,2018-05-31,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135.0,215.1,1610612744,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011287,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.500000,-0.500000,0.0,-1.0,-1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.266667,-0.266667,2.0,-1.0,1.0,0.014950,-0.014950,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
10263,41700402,1610612739,2018-06-03,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135.0,215.1,1610612744,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011163,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,2.0,-2.0,0.0,0.666667,-0.666667,2.0,-2.0,0.0,0.400000,-0.400000,3.0,-2.0,1.0,0.024655,-0.024655,1.0,-1.0,0.0,1.0,-1.0,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333
10264,41700403,1610612739,2018-06-06,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135.0,215.1,1610612744,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011041,-1.0,1.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.000000,0.000000,1.0,-1.0,0.0,0.333333,-0.333333,1.0,-2.0,-1.0,0.350000,-0.350000,2.0,-1.0,1.0,0.014658,-0.014658,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000
10265,41700404,1610612739,2018-06-08,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135.0,215.1,1610612744,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.010922,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,1.0,0.0,1.0,0.004854,-0.004854,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000

In [7]:
df_stats_gitiab_spread.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10266 entries, 0 to 10265
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_id    10266 non-null  int64
 1   team_id_a  10266 non-null  int64
 2   team_id_b  10266 non-null  int64
 3   spread_a   10266 non-null  int64
dtypes: int64(4)
memory usage: 320.9 KB

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10266 entries, 0 to 10265
Data columns (total 85 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   game_id                                            10266 non-null  int64
 1   team_id_a                                          10266 non-null  int64
 2   game_date                                          10266 non-null  datetime64[ns]
 3   season                                             10266 non-null  object
 4   game_time_zone_a                                   10266 non-null  object
 5   time_zone_a                                        10266 non-null  object
 6   time_zone_diff_a                                   10266 non-null  int64
 7   time_zone_diff_abs_a                               10266 non-null  int64
 8   city_proper_metro_area_a                           10266 non-null  object
 9   Country/Region_a                                   10266 non-null  object
 10  city_proper_metro_area_GDP_bil_a                   10266 non-null  object
 11  city_proper_metro_area_GDP_bil1_a                  10266 non-null  object
 12  team_id_b                                          10266 non-null  int64
 13  game_time_zone_b                                   10266 non-null  object
 14  time_zone_b                                        10266 non-null  object
 15  city_proper_metro_area_b                           10266 non-null  object
 16  Country/Region_b                                   10266 non-null  object
 17  city_proper_metro_area_GDP_bil_b                   10266 non-null  object
 18  city_proper_metro_area_GDP_bil1_b                  10266 non-null  object
 19  away_home__diff                                    10266 non-null  float64
 20  latitude_diff                                      10266 non-null  float64
 21  longitude_diff                                     10266 non-null  float64
 22  game_latitude_diff                                 10266 non-null  float64
 23  game_longitude_diff                                10266 non-null  float64
 24  travel_distance_diff                               10266 non-null  float64
 25  game_date_diff_diff                                10266 non-null  float64
 26  game_date_diff1_diff                               10266 non-null  float64
 27  games_back_to_back_count_game_window2_diff         10266 non-null  float64
 28  games_back_to_back_count_game_window5_diff         10266 non-null  float64
 29  games_back_to_back_count_game_window12_diff        10266 non-null  float64
 30  games_back_to_back_count_game_window999_diff       10266 non-null  float64
 31  games_back_to_back_percentage_game_window2_diff    10266 non-null  float64
 32  games_back_to_back_percentage_game_window5_diff    10266 non-null  float64
 33  games_back_to_back_percentage_game_window12_diff   10266 non-null  float64
 34  games_back_to_back_percentage_game_window999_diff  10266 non-null  float64
 35  away_game_count_day_window2_diff                   10266 non-null  float64
 36  home_game_count_day_window2_diff                   10266 non-null  float64
 37  game_count_day_window2_diff                        10266 non-null  float64
 38  away_game_percent_day_window2_diff                 10266 non-null  float64
 39  home_game_percent_day_window2_diff                 10266 non-null  float64
 40  away_game_count_day_window5_diff                   10266 non-null  float64
 41  home_game_count_day_window5_diff                   10266 non-null  float64
 42  game_count_day_window5_diff                        10266 non-null  float64
 43  away_game_percent_day_window5_diff                 10266 non-null  float64
 44  home_game_percent_day_window5_diff                 10266 non-null  float64
 45  away_game_count_day_window8_diff                   10266 non-null  float64
 46  home_game_count_day_window8_diff                   10266 non-null  float64
 47  game_count_day_window8_diff                        10266 non-null  float64
 48  away_game_percent_day_window8_diff                 10266 non-null  float64
 49  home_game_percent_day_window8_diff                 10266 non-null  float64
 50  away_game_count_day_window12_diff                  10266 non-null  float64
 51  home_game_count_day_window12_diff                  10266 non-null  float64
 52  game_count_day_window12_diff                       10266 non-null  float64
 53  away_game_percent_day_window12_diff                10266 non-null  float64
 54  home_game_percent_day_window12_diff                10266 non-null  float64
 55  away_game_count_day_window999_diff                 10266 non-null  float64
 56  home_game_count_day_window999_diff                 10266 non-null  float64
 57  game_count_day_window999_diff                      10266 non-null  float64
 58  away_game_percent_day_window999_diff               10266 non-null  float64
 59  home_game_percent_day_window999_diff               10266 non-null  float64
 60  future_Away_game_count_day_window2_diff            10266 non-null  float64
 61  future_home_game_count_day_window2_diff            10266 non-null  float64
 62  future_game_count_day_window2_diff                 10266 non-null  float64
 63  future_Away_game_percent_day_window2_diff          10266 non-null  float64
 64  future_home_game_percent_day_window2_diff          10266 non-null  float64
 65  future_Away_game_count_day_window5_diff            10266 non-null  float64
 66  future_home_game_count_day_window5_diff            10266 non-null  float64
 67  future_game_count_day_window5_diff                 10266 non-null  float64
 68  future_Away_game_percent_day_window5_diff          10266 non-null  float64
 69  future_home_game_percent_day_window5_diff          10266 non-null  float64
 70  future_Away_game_count_day_window8_diff            10266 non-null  float64
 71  future_home_game_count_day_window8_diff            10266 non-null  float64
 72  future_game_count_day_window8_diff                 10266 non-null  float64
 73  future_Away_game_percent_day_window8_diff          10266 non-null  float64
 74  future_home_game_percent_day_window8_diff          10266 non-null  float64
 75  future_Away_game_count_day_window12_diff           10266 non-null  float64
 76  future_home_game_count_day_window12_diff           10266 non-null  float64
 77  future_game_count_day_window12_diff                10266 non-null  float64
 78  future_Away_game_percent_day_window12_diff         10266 non-null  float64
 79  future_home_game_percent_day_window12_diff         10266 non-null  float64
 80  future_Away_game_count_day_window999_diff          10266 non-null  float64
 81  future_home_game_count_day_window999_diff          10266 non-null  float64
 82  future_game_count_day_window999_diff               10266 non-null  float64
 83  future_Away_game_percent_day_window999_diff        10266 non-null  float64
 84  future_home_game_percent_day_window999_diff        10266 non-null  float64
dtypes: datetime64[ns](1), float64(66), int64(5), object(13)
memory usage: 6.7+ MB

In [9]:
#merge
df = pd.merge(df_stats_gitiab_spread,
              df,
              on=['game_id', 'team_id_a', 'team_id_b'],)
p(df)

(10266, 86)

,game_id,team_id_a,team_id_b,spread_a,game_date,season,game_time_zone_a,time_zone_a,time_zone_diff_a,time_zone_diff_abs_a,city_proper_metro_area_a,Country/Region_a,city_proper_metro_area_GDP_bil_a,city_proper_metro_area_GDP_bil1_a,game_time_zone_b,time_zone_b,city_proper_metro_area_b,Country/Region_b,city_proper_metro_area_GDP_bil_b,city_proper_metro_area_GDP_bil1_b,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff
0,21000001,1610612738,1610612748,-8,2010-10-26,2010-11,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,America/New_York,America/New_York,Miami,United States,377.5,262.7,1.0,16.586081,9.135329,0.0,0.0,-1257.755091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.5,0.5,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,-2.0,1.0,-1.0,-0.238095,0.238095,-5.0,-7.0,-12.0,0.010349,-0.010349
1,21000002,1610612756,1610612757,14,2010-10-26,2010-11,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,America/Los_Angeles,America/Los_Angeles,Portland,United States,164.419,158.5,-1.0,-12.071810,10.600053,0.0,0.0,1005.606855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,0.0,-1.0,-1.0,0.5,-0.5,0.0,0.0,0.0,0.000000,0.000000,-2.0,0.0,-2.0,-0.133333,0.133333,-2.0,0.0,-2.0,-0.171429,0.171429,-3.0,-3.0,-6.0,0.000000,0.000000
2,21000003,1610612745,1610612747,2,2010-10-26,2010-11,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,America/Los_Angeles,America/Los_Angeles,Los Angeles,United States,"1,048","1,528.27",-1.0,-4.294753,22.875069,0.0,0.0,1371.020326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,2.0,-1.0,1.0,1.0,-1.0,1.0,0.0,1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.416667,-0.416667,1.0,-2.0,-1.0,0.266667,-0.266667,-5.0,-5.0,-10.0,0.000000,0.000000
3,21000009,1610612750,1610612758,1,2010-10-27,2010-11,America/Chicago,America/Chicago,0,0,Minneapolis/St. Paul,United States,263.690,211.4,America/Chicago,America/Los_Angeles,Sacramento,United States,145.479,127.4,1.0,6.396239,28.228426,0.0,0.0,-1511.318417,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-0.666667,0.666667,0.0,0.0,0.0,0.000000,0.000000,1.0,0.0,1.0,0.071429,-0.071429,0.0,0.0,0.0,0.000000,0.000000
4,21000006,1610612748,1610612755,-10,2010-10-27,2010-11,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,America/New_York,America/New_York,Philadelphia,United States,444.148,746.5,-1.0,-14.178551,-5.030094,0.0,0.0,1021.727021,-8.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,-1.0,1.0,1.0,-1.0,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,-1.0,-1.0,0.100000,-0.100000,0.0,-1.0,-1.0,0.071429,-0.071429,6.0,9.0,15.0,-0.015551,0.015551
10261,41700317,1610612744,1610612745,-9,2018-05-28,2017-18,America/Chicago,America/Los_Angeles,2,2,San Francisco,United States,995.0,631.0,America/Chicago,America/Chicago,Houston,United States,478.778,883.2,-1.0,8.095728,-26.924439,0.0,0.0,1636.798262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.200000,0.200000,1.0,-1.0,0.0,0.010101,-0.010101,1.0,-1.0,0.0,1.0,-1.0,1.0,0.0,1.0,0.500000,-0.500000,1.0,1.0,2.0,0.333333,-0.333333,3.0,1.0,4.0,0.600000,-0.600000,3.0,1.0,4.0,0.600000,-0.600000
10262,41700401,1610612739,1610612744,10,2018-05-31,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135.0,215.1,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011287,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.500000,-0.500000,0.0,-1.0,-1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.266667,-0.266667,2.0,-1.0,1.0,0.014950,-0.014950,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
10263,41700402,1610612739,1610612744,19,2018-06-03,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135.0,215.1,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011163,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,2.0,-2.0,0.0,0.666667,-0.666667,2.0,-2.0,0.0,0.400000,-0.400000,3.0,-2.0,1.0,0.024655,-0.024655,1.0,-1.0,0.0,1.0,-1.0,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333
10264,41700403,1610612739,1610612744,8,2018-06-06,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135.0,215.1,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011041,-1.0,1.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.000000,0.000000,1.0,-1.0,0.0,0.333333,-0.333333,1.0,-2.0,-1.0,0.350000,-0.350000,2.0,-1.0,1.0,0.014658,-0.014658,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000
10265,41700404,1610612739,1610612744,23,2018-06-08,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135.0,215.1,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.010922,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,1.0,0.0,1.0,0.004854,-0.004854,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000

In [10]:
column_name_list = list(df.columns)
pl(column_name_list)

86

['game_id',
 'team_id_a',
 'team_id_b',
 'spread_a',
 'game_date',
 'season',
 'game_time_zone_a',
 'time_zone_a',
 'time_zone_diff_a',
 'time_zone_diff_abs_a',
 'city_proper_metro_area_a',
 'Country/Region_a',
 'city_proper_metro_area_GDP_bil_a',
 'city_proper_metro_area_GDP_bil1_a',
 'game_time_zone_b',
 'time_zone_b',
 'city_proper_metro_area_b',
 'Country/Region_b',
 'city_proper_metro_area_GDP_bil_b',
 'city_proper_metro_area_GDP_bil1_b',
 'away_home__diff',
 'latitude_diff',
 'longitude_diff',
 'game_latitude_diff',
 'game_longitude_diff',
 'travel_distance_diff',
 'game_date_diff_diff',
 'game_date_diff1_diff',
 'games_back_to_back_count_game_window2_diff',
 'games_back_to_back_count_game_window5_diff',
 'games_back_to_back_count_game_window12_diff',
 'games_back_to_back_count_game_window999_diff',
 'games_back_to_back_percentage_game_window2_diff',
 'games_back_to_back_percentage_game_window5_diff',
 'games_back_to_back_percentage_game_window12_diff',
 'games_back_to_back_percentage_game_window999_diff',
 'away_game_count_day_window2_diff',
 'home_game_count_day_window2_diff',
 'game_count_day_window2_diff',
 'away_game_percent_day_window2_diff',
 'home_game_percent_day_window2_diff',
 'away_game_count_day_window5_diff',
 'home_game_count_day_window5_diff',
 'game_count_day_window5_diff',
 'away_game_percent_day_window5_diff',
 'home_game_percent_day_window5_diff',
 'away_game_count_day_window8_diff',
 'home_game_count_day_window8_diff',
 'game_count_day_window8_diff',
 'away_game_percent_day_window8_diff',
 'home_game_percent_day_window8_diff',
 'away_game_count_day_window12_diff',
 'home_game_count_day_window12_diff',
 'game_count_day_window12_diff',
 'away_game_percent_day_window12_diff',
 'home_game_percent_day_window12_diff',
 'away_game_count_day_window999_diff',
 'home_game_count_day_window999_diff',
 'game_count_day_window999_diff',
 'away_game_percent_day_window999_diff',
 'home_game_percent_day_window999_diff',
 'future_Away_game_count_day_window2_diff',
 'future_home_game_count_day_window2_diff',
 'future_game_count_day_window2_diff',
 'future_Away_game_percent_day_window2_diff',
 'future_home_game_percent_day_window2_diff',
 'future_Away_game_count_day_window5_diff',
 'future_home_game_count_day_window5_diff',
 'future_game_count_day_window5_diff',
 'future_Away_game_percent_day_window5_diff',
 'future_home_game_percent_day_window5_diff',
 'future_Away_game_count_day_window8_diff',
 'future_home_game_count_day_window8_diff',
 'future_game_count_day_window8_diff',
 'future_Away_game_percent_day_window8_diff',
 'future_home_game_percent_day_window8_diff',
 'future_Away_game_count_day_window12_diff',
 'future_home_game_count_day_window12_diff',
 'future_game_count_day_window12_diff',
 'future_Away_game_percent_day_window12_diff',
 'future_home_game_percent_day_window12_diff',
 'future_Away_game_count_day_window999_diff',
 'future_home_game_count_day_window999_diff',
 'future_game_count_day_window999_diff',
 'future_Away_game_percent_day_window999_diff',
 'future_home_game_percent_day_window999_diff']

## 4.6 Get Indicator Variables<a id='4.6 Get_Indicator_Variables'></a>

In [11]:
p(df.select_dtypes('object'))

(10266, 13)

,season,game_time_zone_a,time_zone_a,city_proper_metro_area_a,Country/Region_a,city_proper_metro_area_GDP_bil_a,city_proper_metro_area_GDP_bil1_a,game_time_zone_b,time_zone_b,city_proper_metro_area_b,Country/Region_b,city_proper_metro_area_GDP_bil_b,city_proper_metro_area_GDP_bil1_b
0,2010-11,America/New_York,America/New_York,Boston,United States,463.570,560.1,America/New_York,America/New_York,Miami,United States,377.5,262.7
1,2010-11,America/Los_Angeles,America/Phoenix,Phoenix,United States,255.211,607.1,America/Los_Angeles,America/Los_Angeles,Portland,United States,164.419,158.5
2,2010-11,America/Los_Angeles,America/Chicago,Houston,United States,478.778,883.2,America/Los_Angeles,America/Los_Angeles,Los Angeles,United States,"1,048","1,528.27"
3,2010-11,America/Chicago,America/Chicago,Minneapolis/St. Paul,United States,263.690,211.4,America/Chicago,America/Los_Angeles,Sacramento,United States,145.479,127.4
4,2010-11,America/New_York,America/New_York,Miami,United States,377.5,262.7,America/New_York,America/New_York,Philadelphia,United States,444.148,746.5
10261,2017-18,America/Chicago,America/Los_Angeles,San Francisco,United States,995.0,631.0,America/Chicago,America/Chicago,Houston,United States,478.778,883.2
10262,2017-18,America/Los_Angeles,America/New_York,Cleveland,United States,135.0,215.1,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0
10263,2017-18,America/Los_Angeles,America/New_York,Cleveland,United States,135.0,215.1,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0
10264,2017-18,America/New_York,America/New_York,Cleveland,United States,135.0,215.1,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0
10265,2017-18,America/New_York,America/New_York,Cleveland,United States,135.0,215.1,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0

In [12]:
column_names_categorical_list = list(df.select_dtypes('object').columns) + ['team_id_a', 'team_id_b']
pl(column_names_categorical_list)

15

['season',
 'game_time_zone_a',
 'time_zone_a',
 'city_proper_metro_area_a',
 'Country/Region_a',
 'city_proper_metro_area_GDP_bil_a',
 'city_proper_metro_area_GDP_bil1_a',
 'game_time_zone_b',
 'time_zone_b',
 'city_proper_metro_area_b',
 'Country/Region_b',
 'city_proper_metro_area_GDP_bil_b',
 'city_proper_metro_area_GDP_bil1_b',
 'team_id_a',
 'team_id_b']

In [13]:
df_indicator_variables = pd.get_dummies(df[column_names_categorical_list])
p(df_indicator_variables)

(10266, 220)

,team_id_a,team_id_b,season_2010-11,season_2011-12,season_2012-13,season_2013-14,season_2014-15,season_2015-16,season_2016-17,season_2017-18,game_time_zone_a_America/Chicago,game_time_zone_a_America/Denver,game_time_zone_a_America/Detroit,game_time_zone_a_America/Indiana/Indianapolis,game_time_zone_a_America/Los_Angeles,game_time_zone_a_America/New_York,game_time_zone_a_America/Phoenix,game_time_zone_a_America/Toronto,time_zone_a_America/Chicago,time_zone_a_America/Denver,time_zone_a_America/Detroit,time_zone_a_America/Indiana/Indianapolis,time_zone_a_America/Los_Angeles,time_zone_a_America/New_York,time_zone_a_America/Phoenix,time_zone_a_America/Toronto,city_proper_metro_area_a_Atlanta,city_proper_metro_area_a_Boston,city_proper_metro_area_a_Charlotte,city_proper_metro_area_a_Chicago,city_proper_metro_area_a_Cleveland,city_proper_metro_area_a_Dallas–Fort Worth,city_proper_metro_area_a_Denver,city_proper_metro_area_a_Detroit,city_proper_metro_area_a_Houston,city_proper_metro_area_a_Indianapolis,city_proper_metro_area_a_Los Angeles,city_proper_metro_area_a_Memphis,city_proper_metro_area_a_Miami,city_proper_metro_area_a_Milwaukee,city_proper_metro_area_a_Minneapolis/St. Paul,city_proper_metro_area_a_New Orleans,city_proper_metro_area_a_New York,city_proper_metro_area_a_Oklahoma City,city_proper_metro_area_a_Orlando,city_proper_metro_area_a_Philadelphia,city_proper_metro_area_a_Phoenix,city_proper_metro_area_a_Portland,city_proper_metro_area_a_Sacramento,city_proper_metro_area_a_Salt Lake City,city_proper_metro_area_a_San Antonio,city_proper_metro_area_a_San Francisco,city_proper_metro_area_a_Toronto,Country/Region_a_Canada,Country/Region_a_United States,"city_proper_metro_area_GDP_bil_a_1,048","city_proper_metro_area_GDP_bil_a_1,732",city_proper_metro_area_GDP_bil_a_103.731,city_proper_metro_area_GDP_bil_a_133.633,city_proper_metro_area_GDP_bil_a_135,city_proper_metro_area_GDP_bil_a_135.0,city_proper_metro_area_GDP_bil_a_138.947,city_proper_metro_area_GDP_bil_a_140.762,city_proper_metro_area_GDP_bil_a_145.479,city_proper_metro_area_GDP_bil_a_164.419,city_proper_metro_area_GDP_bil_a_169.862,city_proper_metro_area_GDP_bil_a_181.016,city_proper_metro_area_GDP_bil_a_214.157,city_proper_metro_area_GDP_bil_a_255.211,city_proper_metro_area_GDP_bil_a_263.690,city_proper_metro_area_GDP_bil_a_267.731,city_proper_metro_area_GDP_bil_a_377.5,city_proper_metro_area_GDP_bil_a_380.287,city_proper_metro_area_GDP_bil_a_397.261,city_proper_metro_area_GDP_bil_a_405,city_proper_metro_area_GDP_bil_a_444.148,city_proper_metro_area_GDP_bil_a_463.57,city_proper_metro_area_GDP_bil_a_463.570,city_proper_metro_area_GDP_bil_a_478.778,city_proper_metro_area_GDP_bil_a_478.778,city_proper_metro_area_GDP_bil_a_620.6,city_proper_metro_area_GDP_bil_a_689.464,city_proper_metro_area_GDP_bil_a_76.749,city_proper_metro_area_GDP_bil_a_94.306,city_proper_metro_area_GDP_bil_a_995,city_proper_metro_area_GDP_bil_a_995.0,"city_proper_metro_area_GDP_bil1_a_1,528.27","city_proper_metro_area_GDP_bil1_a_1,803",city_proper_metro_area_GDP_bil1_a_102.771,city_proper_metro_area_GDP_bil1_a_113.606,city_proper_metro_area_GDP_bil1_a_127.4,city_proper_metro_area_GDP_bil1_a_158.5,city_proper_metro_area_GDP_bil1_a_173.836,city_proper_metro_area_GDP_bil1_a_211.4,city_proper_metro_area_GDP_bil1_a_215.1,city_proper_metro_area_GDP_bil1_a_262.7,city_proper_metro_area_GDP_bil1_a_276.3,city_proper_metro_area_GDP_bil1_a_316.2,city_proper_metro_area_GDP_bil1_a_368.4,city_proper_metro_area_GDP_bil1_a_374.2,city_proper_metro_area_GDP_bil1_a_407.5,city_proper_metro_area_GDP_bil1_a_426.2,city_proper_metro_area_GDP_bil1_a_494.4,city_proper_metro_area_GDP_bil1_a_560.1,city_proper_metro_area_GDP_bil1_a_607.1,city_proper_metro_area_GDP_bil1_a_631.0,city_proper_metro_area_GDP_bil1_a_65.0,city_proper_metro_area_GDP_bil1_a_70.010,city_proper_metro_area_GDP_bil1_a_712.7,city_proper_metro_area_GDP_bil1_a_746.5,city_proper_metro_area_GDP_bil1_a_86.5,city_proper_metro_area_GDP_bil1_a_883.2,city_proper_metro_area_GDP_bil1_a_963.2,game_time_zone_b_America/Chicago,game_time_zone_b_America/Denver,game_time_zone_b_America/Detroit,game_time_zone_b_America/Indiana/Indianapolis,game_time_zone_b_America/Los_Angeles,game_time_zone_b_America/New_York,game_time_zone_b_America/Phoenix,game_time_zone_b_America/Toronto,time_zone_b_America/Chicago,time_zone_b_America/Denver,time_zone_b_America/Detroit,time_zone_b_America/Indiana/Indianapolis,time_zone_b_America/Los_Angeles,time_zone_b_America/New_York,time_zone_b_America/Phoenix,time_zone_b_America/Toronto,city_proper_metro_area_b_Boston,city_proper_metro_area_b_Charlotte,city_proper_metro_area_b_Chicago,city_proper_metro_area_b_Cleveland,city_proper_metro_area_b_Dallas–Fort Worth,city_proper_metro_area_b_Denver,city_proper_metro_area_b_Detroit,city_proper_metro_area_b_Houston,city_proper_metro_area_b_Indianapolis,city_proper_metro_area_b_Los Angeles,city_proper_metro_area_b_Memphis,city_proper_metro_area_b_Miami,city_proper_metro_area_b_Milwaukee,city_proper_metro_area_b_Minneapolis/St. Paul,city_proper_metro_area_b_New Orleans,city_proper_metro_area_b_New York,city_proper_metro_area_b_Oklahoma City,city_proper_metro_area_b_Orlando,city_proper_metro_area_b_Philadelphia,city_proper_metro_area_b_Phoenix,city_proper_metro_area_b_Portland,city_proper_metro_area_b_Sacramento,city_proper_metro_area_b_Salt Lake City,city_proper_metro_area_b_San Antonio,city_proper_metro_area_b_San Francisco,city_proper_metro_area_b_Toronto,"city_proper_metro_area_b_Washington, D.C.",Country/Region_b_Canada,Country/Region_b_United States,"city_proper_metro_area_GDP_bil_b_1,048","city_proper_metro_area_GDP_bil_b_1,732",city_proper_metro_area_GDP_bil_b_103.731,city_proper_metro_area_GDP_bil_b_133.633,city_proper_metro_area_GDP_bil_b_135,city_proper_metro_area_GDP_bil_b_135.0,city_proper_metro_area_GDP_bil_b_138.947,city_proper_metro_area_GDP_bil_b_140.762,city_proper_metro_area_GDP_bil_b_145.479,city_proper_metro_area_GDP_bil_b_164.419,city_proper_metro_area_GDP_bil_b_169.862,city_proper_metro_area_GDP_bil_b_181.016,city_proper_metro_area_GDP_bil_b_214.157,city_proper_metro_area_GDP_bil_b_255.211,city_proper_metro_area_GDP_bil_b_263.690,city_proper_metro_area_GDP_bil_b_267.731,city_proper_metro_area_GDP_bil_b_377.5,city_proper_metro_area_GDP_bil_b_380.287,city_proper_metro_area_GDP_bil_b_380.287,city_proper_metro_area_GDP_bil_b_405,city_proper_metro_area_GDP_bil_b_405.0,city_proper_metro_area_GDP_bil_b_444.148,city_proper_metro_area_GDP_bil_b_444.148,city_proper_metro_area_GDP_bil_b_463.570,city_proper_metro_area_GDP_bil_b_478.778,city_proper_metro_area_GDP_bil_b_478.778,city_proper_metro_area_GDP_bil_b_540.684,city_proper_metro_area_GDP_bil_b_620.6,city_proper_metro_area_GDP_bil_b_689.464,city_proper_metro_area_GDP_bil_b_76.749,city_proper_metro_area_GDP_bil_b_94.306,city_proper_metro_area_GDP_bil_b_94.306,city_proper_metro_area_GDP_bil_b_995,city_proper_metro_area_GDP_bil_b_995.0,"city_proper_metro_area_GDP_bil1_b_1,528.27","city_proper_metro_area_GDP_bil1_b_1,803",city_proper_metro_area_GDP_bil1_b_102.771,city_proper_metro_area_GDP_bil1_b_113.606,city_proper_metro_area_GDP_bil1_b_127.4,city_proper_metro_area_GDP_bil1_b_158.5,city_proper_metro_area_GDP_bil1_b_173.83599999999996,city_proper_metro_area_GDP_bil1_b_173.836,city_proper_metro_area_GDP_bil1_b_211.4,city_proper_metro_area_GDP_bil1_b_215.1,city_proper_metro_area_GDP_bil1_b_262.7,city_proper_metro_area_GDP_bil1_b_276.3,city_proper_metro_area_GDP_bil1_b_316.2,city_proper_metro_area_GDP_bil1_b_368.4,city_proper_metro_area_GDP_bil1_b_374.2,city_proper_metro_area_GDP_bil1_b_407.5,city_proper_metro_area_GDP_bil1_b_426.2,city_proper_metro_area_GDP_bil1_b_560.1,city_proper_metro_area_GDP_bil1_b_607.1,city_proper_metro_area_GDP_bil1_b_631.0,city_proper_metro_area_GDP_bil1_b_634.8,city_proper_metro_area_GDP_bil1_b_65.0,city_proper_metro_area_GDP_bil1_b_70.010,city_proper_metro_area_GDP_bil1_b_712.7,city_proper_metro_area_GDP_bil1_b_746.5,city_proper_metro_area_GDP_bil1_b_86.5,city_proper_metro_area_GDP_bil1_b_883.2,city_proper_metro_area_GDP_bil1_b_963.2
0,1610612738,1610612748,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1610612756,1610612757,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1610612745,1610612747,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1610612750,1610612758,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1610612748,1610612755,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10261,1610612744,1610612745,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
10262,1610612739,1610612744,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
10263,1610612739,1610612744,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
10264,1610612739,1610612744,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
10265,1610612739,1610612744,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [14]:
#cat drop
df = df.drop(columns=column_names_categorical_list)
p(df)

(10266, 71)

,game_id,spread_a,game_date,time_zone_diff_a,time_zone_diff_abs_a,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff
0,21000001,-8,2010-10-26,0,0,1.0,16.586081,9.135329,0.0,0.0,-1257.755091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.5,0.5,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,-2.0,1.0,-1.0,-0.238095,0.238095,-5.0,-7.0,-12.0,0.010349,-0.010349
1,21000002,14,2010-10-26,0,0,-1.0,-12.071810,10.600053,0.0,0.0,1005.606855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,0.0,-1.0,-1.0,0.5,-0.5,0.0,0.0,0.0,0.000000,0.000000,-2.0,0.0,-2.0,-0.133333,0.133333,-2.0,0.0,-2.0,-0.171429,0.171429,-3.0,-3.0,-6.0,0.000000,0.000000
2,21000003,2,2010-10-26,-2,2,-1.0,-4.294753,22.875069,0.0,0.0,1371.020326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,2.0,-1.0,1.0,1.0,-1.0,1.0,0.0,1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.416667,-0.416667,1.0,-2.0,-1.0,0.266667,-0.266667,-5.0,-5.0,-10.0,0.000000,0.000000
3,21000009,1,2010-10-27,0,0,1.0,6.396239,28.228426,0.0,0.0,-1511.318417,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-0.666667,0.666667,0.0,0.0,0.0,0.000000,0.000000,1.0,0.0,1.0,0.071429,-0.071429,0.0,0.0,0.0,0.000000,0.000000
4,21000006,-10,2010-10-27,0,0,-1.0,-14.178551,-5.030094,0.0,0.0,1021.727021,-8.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,-1.0,1.0,1.0,-1.0,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,-1.0,-1.0,0.100000,-0.100000,0.0,-1.0,-1.0,0.071429,-0.071429,6.0,9.0,15.0,-0.015551,0.015551
10261,41700317,-9,2018-05-28,2,2,-1.0,8.095728,-26.924439,0.0,0.0,1636.798262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.200000,0.200000,1.0,-1.0,0.0,0.010101,-0.010101,1.0,-1.0,0.0,1.0,-1.0,1.0,0.0,1.0,0.500000,-0.500000,1.0,1.0,2.0,0.333333,-0.333333,3.0,1.0,4.0,0.600000,-0.600000,3.0,1.0,4.0,0.600000,-0.600000
10262,41700401,10,2018-05-31,-3,3,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011287,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.500000,-0.500000,0.0,-1.0,-1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.266667,-0.266667,2.0,-1.0,1.0,0.014950,-0.014950,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
10263,41700402,19,2018-06-03,-3,3,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011163,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,2.0,-2.0,0.0,0.666667,-0.666667,2.0,-2.0,0.0,0.400000,-0.400000,3.0,-2.0,1.0,0.024655,-0.024655,1.0,-1.0,0.0,1.0,-1.0,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333
10264,41700403,8,2018-06-06,0,0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011041,-1.0,1.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.000000,0.000000,1.0,-1.0,0.0,0.333333,-0.333333,1.0,-2.0,-1.0,0.350000,-0.350000,2.0,-1.0,1.0,0.014658,-0.014658,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000
10265,41700404,23,2018-06-08,0,0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.010922,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,1.0,0.0,1.0,0.004854,-0.004854,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000

In [15]:
df.drop(columns=['game_id', 'game_date'], inplace=True)

In [16]:
df_features = df.drop(columns='spread_a')
p(df_features)

(10266, 68)

,time_zone_diff_a,time_zone_diff_abs_a,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff
0,0,0,1.0,16.586081,9.135329,0.0,0.0,-1257.755091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.5,0.5,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,-2.0,1.0,-1.0,-0.238095,0.238095,-5.0,-7.0,-12.0,0.010349,-0.010349
1,0,0,-1.0,-12.071810,10.600053,0.0,0.0,1005.606855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,0.0,-1.0,-1.0,0.5,-0.5,0.0,0.0,0.0,0.000000,0.000000,-2.0,0.0,-2.0,-0.133333,0.133333,-2.0,0.0,-2.0,-0.171429,0.171429,-3.0,-3.0,-6.0,0.000000,0.000000
2,-2,2,-1.0,-4.294753,22.875069,0.0,0.0,1371.020326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,2.0,-1.0,1.0,1.0,-1.0,1.0,0.0,1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.416667,-0.416667,1.0,-2.0,-1.0,0.266667,-0.266667,-5.0,-5.0,-10.0,0.000000,0.000000
3,0,0,1.0,6.396239,28.228426,0.0,0.0,-1511.318417,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-0.666667,0.666667,0.0,0.0,0.0,0.000000,0.000000,1.0,0.0,1.0,0.071429,-0.071429,0.0,0.0,0.0,0.000000,0.000000
4,0,0,-1.0,-14.178551,-5.030094,0.0,0.0,1021.727021,-8.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,-1.0,1.0,1.0,-1.0,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,-1.0,-1.0,0.100000,-0.100000,0.0,-1.0,-1.0,0.071429,-0.071429,6.0,9.0,15.0,-0.015551,0.015551
10261,2,2,-1.0,8.095728,-26.924439,0.0,0.0,1636.798262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.200000,0.200000,1.0,-1.0,0.0,0.010101,-0.010101,1.0,-1.0,0.0,1.0,-1.0,1.0,0.0,1.0,0.500000,-0.500000,1.0,1.0,2.0,0.333333,-0.333333,3.0,1.0,4.0,0.600000,-0.600000,3.0,1.0,4.0,0.600000,-0.600000
10262,-3,3,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011287,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.500000,-0.500000,0.0,-1.0,-1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.266667,-0.266667,2.0,-1.0,1.0,0.014950,-0.014950,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
10263,-3,3,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011163,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,2.0,-2.0,0.0,0.666667,-0.666667,2.0,-2.0,0.0,0.400000,-0.400000,3.0,-2.0,1.0,0.024655,-0.024655,1.0,-1.0,0.0,1.0,-1.0,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333
10264,0,0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011041,-1.0,1.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.000000,0.000000,1.0,-1.0,0.0,0.333333,-0.333333,1.0,-2.0,-1.0,0.350000,-0.350000,2.0,-1.0,1.0,0.014658,-0.014658,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000
10265,0,0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.010922,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,1.0,0.0,1.0,0.004854,-0.004854,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000

In [17]:
df_target = df[['spread_a']]
p(df_target)

(10266, 1)

       spread_a
0            -8
1            14
2             2
3             1
4           -10
10261        -9
10262        10
10263        19
10264         8
10265        23

In [18]:
scaler = StandardScaler() 
scaler

StandardScaler()

In [19]:
# Fitting data to the scaler object
scaled_df_features = scaler.fit_transform(df_features) 
scaled_df_features

array([[ 0.09712784, -0.57858846,  1.00058462, ..., -1.31666601,
         0.08848446, -0.08848446],
       [ 0.09712784, -0.57858846, -0.99941572, ..., -0.70314023,
         0.01116104, -0.01116104],
       [-1.85799837,  1.66962846, -0.99941572, ..., -1.11215741,
         0.01116104, -0.01116104],
       ...,
       [-2.83556147,  2.79373692, -0.99941572, ..., -0.08961445,
        -2.47939715,  2.47939715],
       [ 0.09712784, -0.57858846,  1.00058462, ..., -0.08961445,
        -7.46051352,  7.46051352],
       [ 0.09712784, -0.57858846,  1.00058462, ..., -0.08961445,
        -7.46051352,  7.46051352]])

In [20]:
scaled_df_features = pd.DataFrame(scaled_df_features, columns=df_features.columns)
p(scaled_df_features)

(10266, 68)

,time_zone_diff_a,time_zone_diff_abs_a,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff
0,0.097128,-0.578588,1.000585,2.249661,0.309284,0.0,0.0,-1.045984,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-2.477298,2.477298,-0.537609,0.592052,0.014199,-3.197979,3.197979,-0.433034,0.499961,0.010356,-6.465582,6.465582,-0.881322,1.029814,0.002585,-0.550090,0.550090,-0.693870,0.733236,0.003853,-0.624650,0.624650,-0.605558,0.006353,-1.118891,-0.251630,0.251630,-1.082796,0.583748,-0.841732,-0.773067,0.773067,-1.024181,-1.389136,-1.316666,0.088484,-0.088484
1,0.097128,-0.578588,-0.999416,-1.609206,0.383027,0.0,0.0,0.835137,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,2.447929,-2.447929,0.551721,-0.590669,0.014199,3.178224,-3.178224,0.440350,-0.493093,0.010356,6.416819,-6.416819,0.001807,-1.031219,-1.892685,0.546671,-0.546671,0.002782,-0.001073,0.003853,0.000457,-0.000457,-1.213485,0.006353,-2.253252,-0.334800,0.334800,-1.082796,0.002266,-1.688828,-0.556508,0.556508,-0.645930,-0.644394,-0.703140,0.011161,-0.011161
2,-1.857998,1.669628,-0.999416,-0.562003,1.001028,0.0,0.0,1.138839,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,2.447929,-2.447929,0.551721,-0.590669,0.014199,3.178224,-3.178224,0.440350,-0.493093,0.010356,6.416819,-6.416819,1.768064,-1.031219,1.897854,1.095052,-1.095052,0.699435,-0.001073,1.525129,0.313010,-0.313010,0.610296,-1.298089,-1.118891,1.037511,-1.037511,0.543378,-1.160699,-0.841732,0.866595,-0.866595,-1.024181,-1.016765,-1.112157,0.011161,-0.011161
3,0.097128,-0.578588,1.000585,0.877570,1.270549,0.0,0.0,-1.256725,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-2.477298,2.477298,-0.537609,0.592052,0.014199,-3.197979,3.197979,-0.433034,0.499961,0.010356,-6.465582,6.465582,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.249757,1.249757,0.002369,0.006353,0.015470,-0.002119,0.002119,0.543378,0.002266,0.852459,0.232386,-0.232386,-0.078554,-0.085838,-0.089614,0.011161,-0.011161
4,0.097128,-0.578588,-0.999416,-1.892884,-0.403891,0.0,0.0,0.848535,-6.722156,1.873000,1.559181,1.115153,0.762917,0.414362,1.559181,2.735631,4.133512,6.083854,1.751780,-1.035164,1.873000,1.095736,-1.095736,1.371399,-0.730067,1.560055,1.841889,-1.841889,1.204873,-0.645925,1.192078,2.447929,-2.447929,1.096386,-0.590669,1.019453,3.178224,-3.178224,0.877042,-0.493093,0.687540,6.416819,-6.416819,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.699435,-0.735382,0.003853,0.625563,-0.625563,0.002369,-0.645868,-1.118891,0.247392,-0.247392,0.001320,-0.579217,-0.841732,0.232386,-0.232386,1.056199,1.589830,1.444200,-0.105031,0.105031
10261,2.052254,1.669628,-0.999416,1.106411,-1.506188,0.0,0.0,1.359732,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.607712,-0.607712,0.002577,0.005457,0.014907,-0.014685,0.014685,-0.537609,0.592052,0.014199,-0.647498,0.647498,0.440350,-0.493093,0.010356,0.040681,-0.040681,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.699435,-0.001073,1.525129,0.938117,-0.938117,0.610296,0.658574,2.284191,0.829585,-0.829585,1.627494,0.583748,3.393747,1.949391,-1.949391,0.488823,0.100347,0.319403,4.494166,-4.494166
10262,-2.835561,2.793737,-0.999416,0.507847,1.893345,0.0,0.0,1.789289,0.822081,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.154391,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.916256,-0.916256,0.002577,-0.645925,-1.162265,0.395751,-0.395751,0.551721,-1.182030,-0.991056,0.840283,-0.840283,0.877042,-0.493093,0.687540,0.071918,-0.071918,0.884935,-1.031219,0.002585,1.095052,-1.095052,1.396088,-1.469691,0.003853,1.875777,-1.875777,0.610296,-0.645868,0.015470,0.829585,-0.829585,0.001320,0.002266,0.005363,0.000359,-0.000359,-0.078554,-0.085838,-0.089614,0.011161,-0.011161
10263,-2.835561,2.793737,-0.999416,0.507847,1.893345,0.0,0.0,1.789289,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.152875,0.876529,-1.035164,0.008717,1.095736,-1.095736,1.371399,-1.465507,0.014752,1.841889,-1.841889,1.204873,-1.297306,0.014907,1.627057,-1.627057,1.096386,-1.182030,0.014199,1.265363,-1.265363,1.313734,-0.989619,0.687540,0.134429,-0.134429,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.002782,-0.001073,0.003853,0.000457,-0.000457,-0.605558,0.658574,0.015470,-0.833822,0.833822,-0.540738,0.583748,0.005363,-1.082437,1.082437,-0.267679,0.100347,-0.089614,-2.479397,2.479397
10264,0.097128,-0.578588,1.000585,0.507847,1.893345,0.0,0.0,-1.790571,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.151392,-0.873972,1.041840,0.008717,-1.098300,1.098300,0.001535,0.005373,0.014752,-0.009377,0.009377,0.603725,-0.645925,0.014907,0.806186,-0.806186,0.551721,-1.182030,-0.991056,1.105958,-1.105958,0.877042,-0.493093,0.687540,0.070036,-0.070036,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.874863,1.874863,-1.213485,1.310795,0.015470,-2.497229,2.497229,-1.082796,1.165230,0.005363,-3.248028,3.248028,-0.456804,0.286533,-0.089614,-7.460514,7.460514
10265,0.097128,-0.578588,1.000585,0.507847,1.893345,0.0,0.0,-1.790571,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.149940,-0.873972,1.041840,0.008717,-1.098300,1.098300,-1.368330,1.476253,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-0.835556,0.835556,-0.537609,0.000691,-0.991056,-0.328688,0.328688,0.440350,0.003434,0.687540,0.006887,-0.006887,-0.881322,1.029814,0.002585,-1.098471,1.098471,-0.693870,0.733236,0.003853,-1.874863,1.874863,-0.605558,0.658574,0.015470,-2.497229,2.497229,-0.540738,0.583748,0.005363,-3.248028,3.248028,-0.267679,0.100347,-0.089614,-7.460514,7.460514

In [21]:
''' # Only keep the last 100 datapoints in the training data
window = 100

# Initialize the CV with this window size
cv = TimeSeriesSplit(n_splits=10, max_train_size=window)'''

' # Only keep the last 100 datapoints in the training data\nwindow = 100\n\n# Initialize the CV with this window size\ncv = TimeSeriesSplit(n_splits=10, max_train_size=window)'

In [22]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df_features, 
                                                    df_target,
                                                    test_size=0.1, 
                                                    random_state=random_state_2909,
                                                    shuffle=False)

In [23]:
X_train.shape

(9239, 68)

In [24]:
y_train.shape

(9239, 1)

In [25]:
X_test.shape

(1027, 68)

In [26]:
y_test.shape

(1027, 1)

In [27]:
#export dataframes

#https://stackoverflow.com/questions/30829748/multiple-pandas-dataframe-to-one-csv-file

In [28]:
df_train = pd.concat([X_train, y_train], axis=1)
p(df_train)

(9239, 69)

,time_zone_diff_a,time_zone_diff_abs_a,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,spread_a
0,0.097128,-0.578588,1.000585,2.249661,0.309284,0.0,0.0,-1.045984,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-2.477298,2.477298,-0.537609,0.592052,0.014199,-3.197979,3.197979,-0.433034,0.499961,0.010356,-6.465582,6.465582,-0.881322,1.029814,0.002585,-0.550090,0.550090,-0.693870,0.733236,0.003853,-0.624650,0.624650,-0.605558,0.006353,-1.118891,-0.251630,0.251630,-1.082796,0.583748,-0.841732,-0.773067,0.773067,-1.024181,-1.389136,-1.316666,0.088484,-0.088484,-8
1,0.097128,-0.578588,-0.999416,-1.609206,0.383027,0.0,0.0,0.835137,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,2.447929,-2.447929,0.551721,-0.590669,0.014199,3.178224,-3.178224,0.440350,-0.493093,0.010356,6.416819,-6.416819,0.001807,-1.031219,-1.892685,0.546671,-0.546671,0.002782,-0.001073,0.003853,0.000457,-0.000457,-1.213485,0.006353,-2.253252,-0.334800,0.334800,-1.082796,0.002266,-1.688828,-0.556508,0.556508,-0.645930,-0.644394,-0.703140,0.011161,-0.011161,14
2,-1.857998,1.669628,-0.999416,-0.562003,1.001028,0.0,0.0,1.138839,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,2.447929,-2.447929,0.551721,-0.590669,0.014199,3.178224,-3.178224,0.440350,-0.493093,0.010356,6.416819,-6.416819,1.768064,-1.031219,1.897854,1.095052,-1.095052,0.699435,-0.001073,1.525129,0.313010,-0.313010,0.610296,-1.298089,-1.118891,1.037511,-1.037511,0.543378,-1.160699,-0.841732,0.866595,-0.866595,-1.024181,-1.016765,-1.112157,0.011161,-0.011161,2
3,0.097128,-0.578588,1.000585,0.877570,1.270549,0.0,0.0,-1.256725,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-2.477298,2.477298,-0.537609,0.592052,0.014199,-3.197979,3.197979,-0.433034,0.499961,0.010356,-6.465582,6.465582,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.249757,1.249757,0.002369,0.006353,0.015470,-0.002119,0.002119,0.543378,0.002266,0.852459,0.232386,-0.232386,-0.078554,-0.085838,-0.089614,0.011161,-0.011161,1
4,0.097128,-0.578588,-0.999416,-1.892884,-0.403891,0.0,0.0,0.848535,-6.722156,1.873000,1.559181,1.115153,0.762917,0.414362,1.559181,2.735631,4.133512,6.083854,1.751780,-1.035164,1.873000,1.095736,-1.095736,1.371399,-0.730067,1.560055,1.841889,-1.841889,1.204873,-0.645925,1.192078,2.447929,-2.447929,1.096386,-0.590669,1.019453,3.178224,-3.178224,0.877042,-0.493093,0.687540,6.416819,-6.416819,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.699435,-0.735382,0.003853,0.625563,-0.625563,0.002369,-0.645868,-1.118891,0.247392,-0.247392,0.001320,-0.579217,-0.841732,0.232386,-0.232386,1.056199,1.589830,1.444200,-0.105031,0.105031,-10
9234,3.029817,2.793737,-0.999416,0.908407,-2.448327,0.0,0.0,1.950338,-1.692664,1.873000,1.559181,1.115153,1.534324,1.347733,1.559181,1.092038,1.373003,1.781375,1.751780,-1.035164,1.873000,1.095736,-1.095736,1.371399,-0.730067,1.560055,0.916256,-0.916256,0.603725,0.005457,1.192078,0.108446,-0.108446,0.551721,0.000691,1.019453,0.141937,-0.141937,0.003658,0.499961,0.687540,-0.176936,0.176936,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.002782,-0.735382,-1.517423,0.625563,-0.625563,0.002369,0.006353,0.015470,-0.002119,0.002119,-1.082796,0.583748,-0.841732,-0.865878,0.865878,-0.078554,-0.644394,-0.396377,0.178437,-0.178437,-3
9235,0.097128,-0.578588,1.000585,-0.346823,-0.114386,0.0,0.0,-0.159237,1.660330,-1.855566,-1.547078,-0.003487,0.762917,0.414362,-1.547078,-0.003691,0.682875,0.464945,-0.873972,0.003338,-1.855566,-0.549791,0.549791,0.001535,-0.730067,-1.530551,0.299167,-0.299167,-0.598572,0.656838,0.014907,-0.630338,0.630338,-1.082274,1.183412,0.014199,-1.072578,1.072578,-0.869726,1.493014,0.687540,-0.838007,0.838007,-0.881322,1.029814,0.002585,-1.098471,1.098471,-0.693870,1.467545,1.525129,-1.249757,1.249757,-0.605558,1.310795,1.149830,-1.041748,1.041748,0.001320,0.583748,0.852459,-0.216201,0.216201,-0.456804,-1.016765,-0.805395,0.189058,-0.189058,-16
9236,0.097128,-0.578588,-0.999416,0.365307,0.609586,0.0,0.0,0.668894,-0.016167,0.008717,0.006052,-1.122127,-0.779899,-1.452381,0.006052,-1.099420,-0.697380,-1.933986,0.876529,-1.035164,0.008717,0.547227,-0.547227,1.371399,-0.730067,1.560055,1.224801,-1.224801,1.204873,-0.645925,1.192078,0.724099,-0.724099,1.096386,-0.590669,1.019453,0.673287,-0.673287,0.440350,0.003434,0.687540,0.113645,-0.113645,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.002782,-0.735382,-1.517423,0.313010,-0.313010,-0.605558,0.658574,0.015470,-0.625896,0.625896,-0.540738,0.583748,0.005363,-0.541039,0.541039,0.677948,1.217459,1.035183,-0.112708,0.112708,-10
9237,0.097128,-0.578588,1.000585,-1.458661,-1.226125,0.0,0.0,-1.178771,1.660330,-1.855566,-1.547078,-1.122127,-0.779899,-0.052324,-1.547078,-1.099420,-0.697380,-0.016676,-1.749222,1.041840,-1.855566,-1.098300,1.098300,-1.368330,0.740813,-1.530551,-1.243555,1.243555,-0.598572,0.005457,-1.162265,-0.425120,0.425120,-0.537609,0.000691,-0.991056,-0.328688,0.328688,1.313734,-1.486146,0.010356,0.992650,-0.992650,-0.881322,1.029814,0.002585,-1.098471,1.098471,-0.693870,0.733236,0.003853,-0.624650,0.624650,-0.605558,0.658574,0.015470,-0.833822,0.833822,-0.540738,-0.579217,-1.688828,-0.270340,0.270340,0.488823,2.520757,1.648709,-0.569681,0.569681,-15
9238,0.097128,-0.578588,1.000585,1.080693,-1.772901,0.0,0.0,-1.593147,-0.016167,0.008717,0.006052,1.115153,-0.008491,0.881048,0.006052,1.092038,-0.007252,1.203430,-1.749222,2.080342,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-0.626466,0.626466,0.603725,0.005457,1.192078,0.231577,-0.231577,0.551721,-0.590669,0.014199,0.521473,-0.521473,-0.433034,0.499961,0.010356,-0.346441,0.346441,-0.881322,1.029814,0.002585,-1.098471,1.098471,0.002782,0.733236,1.525129,-0.312097,0.312097,-0.605558,0.658574,0.015470,-0.625896,0.625896,1.085436,-0.579217,0.852459,0.696441,-0.696441,0.867074,1.217459,1.137437,-0.077787,0.077787,-15

In [29]:
df_test = pd.concat([X_test, y_test], axis=1)
p(df_test)

(1027, 69)

,time_zone_diff_a,time_zone_diff_abs_a,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,spread_a
9239,-0.880435,0.545520,-0.999416,0.322683,1.055866,0.0,0.0,1.028423,-0.016167,0.008717,0.006052,-1.122127,-0.008491,-0.519009,0.006052,-1.099420,-0.007252,-0.423378,0.876529,-1.035164,0.008717,1.095736,-1.095736,1.371399,-1.465507,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,0.600969,-0.600969,-0.537609,0.000691,-0.991056,-0.222418,0.222418,0.440350,-1.486146,-1.344011,0.619739,-0.619739,0.884935,-1.031219,0.002585,1.095052,-1.095052,1.396088,-1.469691,0.003853,1.875777,-1.875777,1.218223,-1.298089,0.015470,1.245437,-1.245437,1.085436,-1.160699,0.005363,1.083154,-1.083154,-0.456804,-0.085838,-0.294123,-0.087003,0.087003,13
9240,0.097128,-0.578588,1.000585,2.184396,-0.524758,0.0,0.0,-0.989872,-0.016167,0.008717,0.006052,1.115153,1.534324,0.881048,0.006052,1.092038,1.373003,1.374673,-0.873972,1.041840,0.008717,-1.098300,1.098300,0.001535,0.005373,0.014752,-0.009377,0.009377,1.204873,-0.645925,1.192078,0.724099,-0.724099,1.096386,-0.590669,1.019453,0.673287,-0.673287,0.440350,-0.989619,-0.666828,0.521802,-0.521802,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.249757,1.249757,-1.213485,0.658574,-1.118891,-0.875407,0.875407,-1.082796,1.165230,0.005363,-1.082437,1.082437,-1.024181,0.100347,-0.498632,-0.330354,0.330354,7
9241,-0.880435,0.545520,-0.999416,0.757034,0.660032,0.0,0.0,0.792883,-0.016167,0.008717,0.006052,-0.003487,0.762917,0.414362,0.006052,-0.003691,0.682875,0.625485,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.607712,-0.607712,0.603725,-0.645925,0.014907,0.600969,-0.600969,0.551721,-1.182030,-0.991056,0.734013,-0.734013,0.877042,-0.989619,0.010356,0.653640,-0.653640,1.768064,-1.031219,1.897854,1.095052,-1.095052,1.396088,-0.735382,1.525129,0.938117,-0.938117,0.610296,-0.645868,0.015470,0.621659,-0.621659,0.543378,-0.579217,0.005363,0.541756,-0.541756,-0.267679,0.100347,-0.089614,-0.105584,0.105584,-10
9242,0.097128,-0.578588,1.000585,1.568692,0.796300,0.0,0.0,-1.063182,-0.016167,0.008717,0.006052,-0.003487,-0.779899,-0.985695,0.006052,-0.003691,-0.697380,-1.091531,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-0.626466,0.626466,0.002577,0.656838,1.192078,-0.137815,0.137815,0.007056,0.592052,1.019453,-0.161692,0.161692,0.877042,-1.486146,-0.666828,0.742428,-0.742428,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.249757,1.249757,-1.213485,1.963016,1.149830,-1.499185,1.499185,-1.082796,1.165230,0.005363,-0.927752,0.927752,-0.078554,1.031274,0.523911,-0.350372,0.350372,-11
9243,0.097128,-0.578588,1.000585,0.020163,0.452923,0.0,0.0,-0.509033,-0.854416,0.008717,1.559181,-0.003487,-0.008491,-0.519009,1.559181,-0.003691,-0.007252,-0.921539,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,1.476253,1.560055,-1.243555,1.243555,0.603725,0.656838,2.369250,-0.178859,0.178859,0.007056,1.183412,2.024708,-0.738587,0.738587,0.877042,0.499961,2.041908,0.098895,-0.098895,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,0.733236,-1.517423,-1.249757,1.249757,-2.429339,1.963016,-1.118891,-1.998207,1.998207,-2.166912,1.746713,-0.841732,-1.778520,1.778520,0.867074,1.962201,1.546454,-0.269027,0.269027,10
10261,2.052254,1.669628,-0.999416,1.106411,-1.506188,0.0,0.0,1.359732,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.607712,-0.607712,0.002577,0.005457,0.014907,-0.014685,0.014685,-0.537609,0.592052,0.014199,-0.647498,0.647498,0.440350,-0.493093,0.010356,0.040681,-0.040681,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.699435,-0.001073,1.525129,0.938117,-0.938117,0.610296,0.658574,2.284191,0.829585,-0.829585,1.627494,0.583748,3.393747,1.949391,-1.949391,0.488823,0.100347,0.319403,4.494166,-4.494166,-9
10262,-2.835561,2.793737,-0.999416,0.507847,1.893345,0.0,0.0,1.789289,0.822081,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.154391,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.916256,-0.916256,0.002577,-0.645925,-1.162265,0.395751,-0.395751,0.551721,-1.182030,-0.991056,0.840283,-0.840283,0.877042,-0.493093,0.687540,0.071918,-0.071918,0.884935,-1.031219,0.002585,1.095052,-1.095052,1.396088,-1.469691,0.003853,1.875777,-1.875777,0.610296,-0.645868,0.015470,0.829585,-0.829585,0.001320,0.002266,0.005363,0.000359,-0.000359,-0.078554,-0.085838,-0.089614,0.011161,-0.011161,10
10263,-2.835561,2.793737,-0.999416,0.507847,1.893345,0.0,0.0,1.789289,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.152875,0.876529,-1.035164,0.008717,1.095736,-1.095736,1.371399,-1.465507,0.014752,1.841889,-1.841889,1.204873,-1.297306,0.014907,1.627057,-1.627057,1.096386,-1.182030,0.014199,1.265363,-1.265363,1.313734,-0.989619,0.687540,0.134429,-0.134429,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.002782,-0.001073,0.003853,0.000457,-0.000457,-0.605558,0.658574,0.015470,-0.833822,0.833822,-0.540738,0.583748,0.005363,-1.082437,1.082437,-0.267679,0.100347,-0.089614,-2.479397,2.479397,19
10264,0.097128,-0.578588,1.000585,0.507847,1.893345,0.0,0.0,-1.790571,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.151392,-0.873972,1.041840,0.008717,-1.098300,1.098300,0.001535,0.005373,0.014752,-0.009377,0.009377,0.603725,-0.645925,0.014907,0.806186,-0.806186,0.551721,-1.182030,-0.991056,1.105958,-1.105958,0.877042,-0.493093,0.687540,0.070036,-0.070036,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.874863,1.874863,-1.213485,1.310795,0.015470,-2.497229,2.497229,-1.082796,1.165230,0.005363,-3.248028,3.248028,-0.456804,0.286533,-0.089614,-7.460514,7.460514,8
10265,0.097128,-0.578588,1.000585,0.507847,1.893345,0.0,0.0,-1.790571,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.149940,-0.873972,1.041840,0.008717,-1.098300,1.098300,-1.368330,1.476253,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-0.835556,0.835556,-0.537609,0.000691,-0.991056,-0.328688,0.328688,0.440350,0.003434,0.687540,0.006887,-0.006887,-0.881322,1.029814,0.002585,-1.098471,1.098471,-0.693870,0.733236,0.003853,-1.874863,1.874863,-0.605558,0.658574,0.015470,-2.497229,2.497229,-0.540738,0.583748,0.005363,-3.248028,3.248028,-0.267679,0.100347,-0.089614,-7.460514,7.460514,23

In [30]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '172_train_split_time_series.csv')
if not os.path.exists(datapath_df):
    df_train.to_csv(datapath_df, index=True)

In [31]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '172_test_split_time_series.csv')
if not os.path.exists(datapath_df):
    df_test.to_csv(datapath_df, index=True)

In [32]:
df_train_readback = rcp('172_train_split_time_series.csv', None, 0)
p(df_train_readback)

(9239, 69)

,time_zone_diff_a,time_zone_diff_abs_a,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,spread_a
0,0.097128,-0.578588,1.000585,2.249661,0.309284,0.0,0.0,-1.045984,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-2.477298,2.477298,-0.537609,0.592052,0.014199,-3.197979,3.197979,-0.433034,0.499961,0.010356,-6.465582,6.465582,-0.881322,1.029814,0.002585,-0.550090,0.550090,-0.693870,0.733236,0.003853,-0.624650,0.624650,-0.605558,0.006353,-1.118891,-0.251630,0.251630,-1.082796,0.583748,-0.841732,-0.773067,0.773067,-1.024181,-1.389136,-1.316666,0.088484,-0.088484,-8
1,0.097128,-0.578588,-0.999416,-1.609206,0.383027,0.0,0.0,0.835137,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,2.447929,-2.447929,0.551721,-0.590669,0.014199,3.178224,-3.178224,0.440350,-0.493093,0.010356,6.416819,-6.416819,0.001807,-1.031219,-1.892685,0.546671,-0.546671,0.002782,-0.001073,0.003853,0.000457,-0.000457,-1.213485,0.006353,-2.253252,-0.334800,0.334800,-1.082796,0.002266,-1.688828,-0.556508,0.556508,-0.645930,-0.644394,-0.703140,0.011161,-0.011161,14
2,-1.857998,1.669628,-0.999416,-0.562003,1.001028,0.0,0.0,1.138839,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,2.447929,-2.447929,0.551721,-0.590669,0.014199,3.178224,-3.178224,0.440350,-0.493093,0.010356,6.416819,-6.416819,1.768064,-1.031219,1.897854,1.095052,-1.095052,0.699435,-0.001073,1.525129,0.313010,-0.313010,0.610296,-1.298089,-1.118891,1.037511,-1.037511,0.543378,-1.160699,-0.841732,0.866595,-0.866595,-1.024181,-1.016765,-1.112157,0.011161,-0.011161,2
3,0.097128,-0.578588,1.000585,0.877570,1.270549,0.0,0.0,-1.256725,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-2.477298,2.477298,-0.537609,0.592052,0.014199,-3.197979,3.197979,-0.433034,0.499961,0.010356,-6.465582,6.465582,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.249757,1.249757,0.002369,0.006353,0.015470,-0.002119,0.002119,0.543378,0.002266,0.852459,0.232386,-0.232386,-0.078554,-0.085838,-0.089614,0.011161,-0.011161,1
4,0.097128,-0.578588,-0.999416,-1.892884,-0.403891,0.0,0.0,0.848535,-6.722156,1.873000,1.559181,1.115153,0.762917,0.414362,1.559181,2.735631,4.133512,6.083854,1.751780,-1.035164,1.873000,1.095736,-1.095736,1.371399,-0.730067,1.560055,1.841889,-1.841889,1.204873,-0.645925,1.192078,2.447929,-2.447929,1.096386,-0.590669,1.019453,3.178224,-3.178224,0.877042,-0.493093,0.687540,6.416819,-6.416819,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.699435,-0.735382,0.003853,0.625563,-0.625563,0.002369,-0.645868,-1.118891,0.247392,-0.247392,0.001320,-0.579217,-0.841732,0.232386,-0.232386,1.056199,1.589830,1.444200,-0.105031,0.105031,-10
9234,3.029817,2.793737,-0.999416,0.908407,-2.448327,0.0,0.0,1.950338,-1.692664,1.873000,1.559181,1.115153,1.534324,1.347733,1.559181,1.092038,1.373003,1.781375,1.751780,-1.035164,1.873000,1.095736,-1.095736,1.371399,-0.730067,1.560055,0.916256,-0.916256,0.603725,0.005457,1.192078,0.108446,-0.108446,0.551721,0.000691,1.019453,0.141937,-0.141937,0.003658,0.499961,0.687540,-0.176936,0.176936,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.002782,-0.735382,-1.517423,0.625563,-0.625563,0.002369,0.006353,0.015470,-0.002119,0.002119,-1.082796,0.583748,-0.841732,-0.865878,0.865878,-0.078554,-0.644394,-0.396377,0.178437,-0.178437,-3
9235,0.097128,-0.578588,1.000585,-0.346823,-0.114386,0.0,0.0,-0.159237,1.660330,-1.855566,-1.547078,-0.003487,0.762917,0.414362,-1.547078,-0.003691,0.682875,0.464945,-0.873972,0.003338,-1.855566,-0.549791,0.549791,0.001535,-0.730067,-1.530551,0.299167,-0.299167,-0.598572,0.656838,0.014907,-0.630338,0.630338,-1.082274,1.183412,0.014199,-1.072578,1.072578,-0.869726,1.493014,0.687540,-0.838007,0.838007,-0.881322,1.029814,0.002585,-1.098471,1.098471,-0.693870,1.467545,1.525129,-1.249757,1.249757,-0.605558,1.310795,1.149830,-1.041748,1.041748,0.001320,0.583748,0.852459,-0.216201,0.216201,-0.456804,-1.016765,-0.805395,0.189058,-0.189058,-16
9236,0.097128,-0.578588,-0.999416,0.365307,0.609586,0.0,0.0,0.668894,-0.016167,0.008717,0.006052,-1.122127,-0.779899,-1.452381,0.006052,-1.099420,-0.697380,-1.933986,0.876529,-1.035164,0.008717,0.547227,-0.547227,1.371399,-0.730067,1.560055,1.224801,-1.224801,1.204873,-0.645925,1.192078,0.724099,-0.724099,1.096386,-0.590669,1.019453,0.673287,-0.673287,0.440350,0.003434,0.687540,0.113645,-0.113645,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.002782,-0.735382,-1.517423,0.313010,-0.313010,-0.605558,0.658574,0.015470,-0.625896,0.625896,-0.540738,0.583748,0.005363,-0.541039,0.541039,0.677948,1.217459,1.035183,-0.112708,0.112708,-10
9237,0.097128,-0.578588,1.000585,-1.458661,-1.226125,0.0,0.0,-1.178771,1.660330,-1.855566,-1.547078,-1.122127,-0.779899,-0.052324,-1.547078,-1.099420,-0.697380,-0.016676,-1.749222,1.041840,-1.855566,-1.098300,1.098300,-1.368330,0.740813,-1.530551,-1.243555,1.243555,-0.598572,0.005457,-1.162265,-0.425120,0.425120,-0.537609,0.000691,-0.991056,-0.328688,0.328688,1.313734,-1.486146,0.010356,0.992650,-0.992650,-0.881322,1.029814,0.002585,-1.098471,1.098471,-0.693870,0.733236,0.003853,-0.624650,0.624650,-0.605558,0.658574,0.015470,-0.833822,0.833822,-0.540738,-0.579217,-1.688828,-0.270340,0.270340,0.488823,2.520757,1.648709,-0.569681,0.569681,-15
9238,0.097128,-0.578588,1.000585,1.080693,-1.772901,0.0,0.0,-1.593147,-0.016167,0.008717,0.006052,1.115153,-0.008491,0.881048,0.006052,1.092038,-0.007252,1.203430,-1.749222,2.080342,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-0.626466,0.626466,0.603725,0.005457,1.192078,0.231577,-0.231577,0.551721,-0.590669,0.014199,0.521473,-0.521473,-0.433034,0.499961,0.010356,-0.346441,0.346441,-0.881322,1.029814,0.002585,-1.098471,1.098471,0.002782,0.733236,1.525129,-0.312097,0.312097,-0.605558,0.658574,0.015470,-0.625896,0.625896,1.085436,-0.579217,0.852459,0.696441,-0.696441,0.867074,1.217459,1.137437,-0.077787,0.077787,-15

In [33]:
df_test_readback = rcp('172_test_split_time_series.csv', None, 0)
p(df_test_readback)

(1027, 69)

,time_zone_diff_a,time_zone_diff_abs_a,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff,spread_a
9239,-0.880435,0.545520,-0.999416,0.322683,1.055866,0.0,0.0,1.028423,-0.016167,0.008717,0.006052,-1.122127,-0.008491,-0.519009,0.006052,-1.099420,-0.007252,-0.423378,0.876529,-1.035164,0.008717,1.095736,-1.095736,1.371399,-1.465507,0.014752,1.841889,-1.841889,0.603725,-0.645925,0.014907,0.600969,-0.600969,-0.537609,0.000691,-0.991056,-0.222418,0.222418,0.440350,-1.486146,-1.344011,0.619739,-0.619739,0.884935,-1.031219,0.002585,1.095052,-1.095052,1.396088,-1.469691,0.003853,1.875777,-1.875777,1.218223,-1.298089,0.015470,1.245437,-1.245437,1.085436,-1.160699,0.005363,1.083154,-1.083154,-0.456804,-0.085838,-0.294123,-0.087003,0.087003,13
9240,0.097128,-0.578588,1.000585,2.184396,-0.524758,0.0,0.0,-0.989872,-0.016167,0.008717,0.006052,1.115153,1.534324,0.881048,0.006052,1.092038,1.373003,1.374673,-0.873972,1.041840,0.008717,-1.098300,1.098300,0.001535,0.005373,0.014752,-0.009377,0.009377,1.204873,-0.645925,1.192078,0.724099,-0.724099,1.096386,-0.590669,1.019453,0.673287,-0.673287,0.440350,-0.989619,-0.666828,0.521802,-0.521802,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.249757,1.249757,-1.213485,0.658574,-1.118891,-0.875407,0.875407,-1.082796,1.165230,0.005363,-1.082437,1.082437,-1.024181,0.100347,-0.498632,-0.330354,0.330354,7
9241,-0.880435,0.545520,-0.999416,0.757034,0.660032,0.0,0.0,0.792883,-0.016167,0.008717,0.006052,-0.003487,0.762917,0.414362,0.006052,-0.003691,0.682875,0.625485,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.607712,-0.607712,0.603725,-0.645925,0.014907,0.600969,-0.600969,0.551721,-1.182030,-0.991056,0.734013,-0.734013,0.877042,-0.989619,0.010356,0.653640,-0.653640,1.768064,-1.031219,1.897854,1.095052,-1.095052,1.396088,-0.735382,1.525129,0.938117,-0.938117,0.610296,-0.645868,0.015470,0.621659,-0.621659,0.543378,-0.579217,0.005363,0.541756,-0.541756,-0.267679,0.100347,-0.089614,-0.105584,0.105584,-10
9242,0.097128,-0.578588,1.000585,1.568692,0.796300,0.0,0.0,-1.063182,-0.016167,0.008717,0.006052,-0.003487,-0.779899,-0.985695,0.006052,-0.003691,-0.697380,-1.091531,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,0.740813,0.014752,-0.626466,0.626466,0.002577,0.656838,1.192078,-0.137815,0.137815,0.007056,0.592052,1.019453,-0.161692,0.161692,0.877042,-1.486146,-0.666828,0.742428,-0.742428,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.249757,1.249757,-1.213485,1.963016,1.149830,-1.499185,1.499185,-1.082796,1.165230,0.005363,-0.927752,0.927752,-0.078554,1.031274,0.523911,-0.350372,0.350372,-11
9243,0.097128,-0.578588,1.000585,0.020163,0.452923,0.0,0.0,-0.509033,-0.854416,0.008717,1.559181,-0.003487,-0.008491,-0.519009,1.559181,-0.003691,-0.007252,-0.921539,-0.873972,1.041840,0.008717,-1.098300,1.098300,-0.683398,1.476253,1.560055,-1.243555,1.243555,0.603725,0.656838,2.369250,-0.178859,0.178859,0.007056,1.183412,2.024708,-0.738587,0.738587,0.877042,0.499961,2.041908,0.098895,-0.098895,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,0.733236,-1.517423,-1.249757,1.249757,-2.429339,1.963016,-1.118891,-1.998207,1.998207,-2.166912,1.746713,-0.841732,-1.778520,1.778520,0.867074,1.962201,1.546454,-0.269027,0.269027,10
10261,2.052254,1.669628,-0.999416,1.106411,-1.506188,0.0,0.0,1.359732,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.052324,0.006052,-0.003691,-0.007252,-0.016676,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.607712,-0.607712,0.002577,0.005457,0.014907,-0.014685,0.014685,-0.537609,0.592052,0.014199,-0.647498,0.647498,0.440350,-0.493093,0.010356,0.040681,-0.040681,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.699435,-0.001073,1.525129,0.938117,-0.938117,0.610296,0.658574,2.284191,0.829585,-0.829585,1.627494,0.583748,3.393747,1.949391,-1.949391,0.488823,0.100347,0.319403,4.494166,-4.494166,-9
10262,-2.835561,2.793737,-0.999416,0.507847,1.893345,0.0,0.0,1.789289,0.822081,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.154391,0.876529,-1.035164,0.008717,1.095736,-1.095736,0.686467,-0.730067,0.014752,0.916256,-0.916256,0.002577,-0.645925,-1.162265,0.395751,-0.395751,0.551721,-1.182030,-0.991056,0.840283,-0.840283,0.877042,-0.493093,0.687540,0.071918,-0.071918,0.884935,-1.031219,0.002585,1.095052,-1.095052,1.396088,-1.469691,0.003853,1.875777,-1.875777,0.610296,-0.645868,0.015470,0.829585,-0.829585,0.001320,0.002266,0.005363,0.000359,-0.000359,-0.078554,-0.085838,-0.089614,0.011161,-0.011161,10
10263,-2.835561,2.793737,-0.999416,0.507847,1.893345,0.0,0.0,1.789289,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.152875,0.876529,-1.035164,0.008717,1.095736,-1.095736,1.371399,-1.465507,0.014752,1.841889,-1.841889,1.204873,-1.297306,0.014907,1.627057,-1.627057,1.096386,-1.182030,0.014199,1.265363,-1.265363,1.313734,-0.989619,0.687540,0.134429,-0.134429,0.884935,-1.031219,0.002585,1.095052,-1.095052,0.002782,-0.001073,0.003853,0.000457,-0.000457,-0.605558,0.658574,0.015470,-0.833822,0.833822,-0.540738,0.583748,0.005363,-1.082437,1.082437,-0.267679,0.100347,-0.089614,-2.479397,2.479397,19
10264,0.097128,-0.578588,1.000585,0.507847,1.893345,0.0,0.0,-1.790571,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.151392,-0.873972,1.041840,0.008717,-1.098300,1.098300,0.001535,0.005373,0.014752,-0.009377,0.009377,0.603725,-0.645925,0.014907,0.806186,-0.806186,0.551721,-1.182030,-0.991056,1.105958,-1.105958,0.877042,-0.493093,0.687540,0.070036,-0.070036,-0.881322,1.029814,0.002585,-1.098471,1.098471,-1.390523,1.467545,0.003853,-1.874863,1.874863,-1.213485,1.310795,0.015470,-2.497229,2.497229,-1.082796,1.165230,0.005363,-3.248028,3.248028,-0.456804,0.286533,-0.089614,-7.460514,7.460514,8
10265,0.097128,-0.578588,1.000585,0.507847,1.893345,0.0,0.0,-1.790571,-0.016167,0.008717,0.006052,-0.003487,-0.008491,-0.519009,0.006052,-0.003691,-0.007252,-0.149940,-0.873972,1.041840,0.008717,-1.098300,1.098300,-1.368330,1.476253,0.014752,-1.860644,1.860644,-0.598572,0.656838,0.014907,-0.835556,0.835556,-0.537609,0.000691,-0.991056,-0.328688,0.328688,0.440350,0.003434,0.687540,0.006887,-0.006887,-0.881322,1.029814,0.002585,-1.098471,1.098471,-0.693870,0.733236,0.003853,-1.874863,1.874863,-0.605558,0.658574,0.015470,-2.497229,2.497229,-0.540738,0.583748,0.005363,-3.248028,3.248028,-0.267679,0.100347,-0.089614,-7.460514,7.460514,23