In [1]:
# Target variable 'spread_a' is most predicted by stat differences which should be used.

random_state_2909 = 2909

# 4 Pre-Processing and Training Data<a id='4_Pre-Processing_and_Training_Data'></a>

## 4.2 Introduction<a id='4.2_Introduction'></a>

## 4.3 Imports<a id='4.3_Imports'></a>

In [2]:
import pandas as pd
import numpy as np
import os
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import __version__ as sklearn_version
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV, learning_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression
import datetime

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

## 4.4 Functions<a id='4.4_Imports'></a>

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None, ic_=None):
    if (pd_ == None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    elif (pd_ != None) and (ic_ == None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    elif (pd_ != None) and (ic_ != None):
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_, index_col = ic_)
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), index_col = ic_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_, ascending_=True):
    df_ = df_.sort_values(column_, ascending=ascending_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of dictionary
def pdc(dict_):
    print(len(dict_))
    return dict_

## 4.5 Load Data<a id='4.5_Load_Data'></a>

In [4]:
df_stats = rcp('53AAprediction_stats_2010_2018.csv', ['game_date'])
p(df_stats)

(10266, 107)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,team_id_a,spread_a,away_home_a,game_date,matchup,season_type,season,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,team_id_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff,E_OFF_RATING_sm_cma_diff,OFF_RATING_sm_cma_diff,E_DEF_RATING_sm_cma_diff,DEF_RATING_sm_cma_diff,E_NET_RATING_sm_cma_diff,NET_RATING_sm_cma_diff,AST_PCT_sm_cma_diff,AST_TOV_sm_cma_diff,AST_RATIO_sm_cma_diff,OREB_PCT_sm_cma_diff,DREB_PCT_sm_cma_diff,REB_PCT_sm_cma_diff,E_TM_TOV_PCT_sm_cma_diff,TM_TOV_PCT_sm_cma_diff,EFG_PCT_sm_cma_diff,TS_PCT_sm_cma_diff,USG_PCT_sm_cma_diff,E_USG_PCT_sm_cma_diff,E_PACE_sm_cma_diff,PACE_sm_cma_diff,PACE_PER40_sm_cma_diff,POSS_sm_cma_diff,PIE_sm_cma_diff,duration_minutes_sm_cma_diff,w_pct_sm_cma_diff,min_sm_cma_diff,fgm_sm_cma_diff,fga_sm_cma_diff,fg_pct_sm_cma_diff,fg3m_sm_cma_diff,fg3a_sm_cma_diff,fg3_pct_sm_cma_diff,ftm_sm_cma_diff,fta_sm_cma_diff,ft_pct_sm_cma_diff,oreb_sm_cma_diff,dreb_sm_cma_diff,reb_sm_cma_diff,ast_sm_cma_diff,stl_sm_cma_diff,blk_sm_cma_diff,tov_sm_cma_diff,pf_sm_cma_diff,pts_sm_cma_diff,spread_sm_cma_diff,away_home_sm_cma_diff
0,21000001,Celtics,BOS,Boston,1610612738,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,Heat,MIA,Miami,1610612748,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,1610612756,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,Trail Blazers,POR,Portland,1610612757,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,1610612745,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,Lakers,LAL,Los Angeles,1610612747,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000009,Timberwolves,MIN,Minnesota,1610612750,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,Kings,SAC,Sacramento,1610612758,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000006,Heat,MIA,Miami,1610612748,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,76ers,PHI,Philadelphia,1610612755,87.900000,87.900000,95.700000,95.700000,-7.700000,-7.700000,0.556000,0.880000,12.800000,0.250000,0.732000,0.472000,18.681000,18.700000,0.419000,0.471000,1.0,0.200000,91.500000,91.500000,76.250000,91.000000,0.401000,240.000000,0.000000,240.000000,27.000000,74.000000,0.365000,8.000000,20.000000,0.400000,18.000000,25.000000,0.720000,11.000000,28.000000,39.000000,15.000000,10.000000,6.000000,17.000000,21.000000,80.000000,8.000000,0.000000,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,Warriors,GSW,Golden State,1610612744,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,Rockets,HOU,Houston,1610612745,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,Cavaliers,CLE,Cleveland,1610612739,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,Cavaliers,CLE,Cleveland,1610612739,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,Cavaliers,CLE,Cleveland,1610612739,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,Cavaliers,CLE,Cleveland,1610612739,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,Warriors,GSW,Golden State,1610612744,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [5]:
df_stats_gitiab_spread = df_stats.loc[:, ['game_id', 'team_id_a', 'team_id_b', 'spread_a']]
p(df_stats_gitiab_spread)

(10266, 4)

        game_id   team_id_a   team_id_b  spread_a
0      21000001  1610612738  1610612748        -8
1      21000002  1610612756  1610612757        14
2      21000003  1610612745  1610612747         2
3      21000009  1610612750  1610612758         1
4      21000006  1610612748  1610612755       -10
10261  41700317  1610612744  1610612745        -9
10262  41700401  1610612739  1610612744        10
10263  41700402  1610612739  1610612744        19
10264  41700403  1610612739  1610612744         8
10265  41700404  1610612739  1610612744        23

In [6]:
df_stat_season_matchup_cma12_diff = rcp('58Cstat_season_matchup_cmax12_diff_2010_2018.csv', ['game_date'])
p(df_stat_season_matchup_cma12_diff)

(10266, 163)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,7.7,5.3,-7.7,-5.3,24.1,24.6,0.195,0.54,5.2,0.022,-0.080,-0.011,-2.597,-3.6,0.036,0.042,0.0,0.003,0.0,0.0,0.0,-1.0,0.121,0.0,0.000,0.0,1.0,-5.0,0.041,0.0,-12.0,0.148,-5.0,-7.0,0.092593,4.0,2.0,2.0,7.0,-3.0,1.0,-2.0,1.0,-1.0,-19.0,0.0,4.8,4.341667,-1.091667,0.325000,1.858333,0.991667,0.138250,0.127500,5.841667,-0.029333,-0.010333,0.005583,1.6335,1.641667,0.043583,0.035917,0.0,0.00125,1.653333,1.111667,0.925833,-0.916667,0.033583,-2.083333,0.067583,-2.083333,4.916667,-1.416667,0.068167,-4.250000,-13.50,0.036083,-3.416667,-5.333333,0.029458,-1.166667,1.833333,3.000000,8.916667,0.000000,1.750000,1.333333,-1.416667,3.000000,0.00,0.083333
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,-14.3,-9.7,14.3,9.7,-21.1,-18.2,-0.200,-0.21,-4.3,0.017,0.054,-0.001,-1.740,-1.8,-0.058,-0.080,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.094,0.0,2.0,9.0,-0.025,3.0,-1.0,0.042,-3.0,-5.0,0.040000,6.0,-6.0,2.0,-7.0,1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-3.650000,-1.950000,-0.059667,-0.265000,-1.658333,-0.028250,0.023667,-0.023000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.461667,-2.125000,-1.770000,-2.666667,-0.051583,-4.166667,-0.078667,-4.166667,-2.666667,-0.833333,-0.008500,3.666667,6.00,0.049583,1.416667,2.250000,-0.010437,0.500000,-3.333333,-2.833333,-4.250000,-0.583333,-4.833333,-2.833333,-1.333333,-2.833333,10.75,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,-8.5,-12.4,8.5,12.4,-21.1,-20.9,-0.200,-2.15,-4.5,0.071,0.126,0.059,-1.740,-1.8,-0.088,-0.104,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-2.0,9.0,-0.054,2.0,0.0,0.042,-3.0,-5.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,-0.000167,-0.009833,0.002167,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,-2.083333,-0.078667,-2.083333,-2.666667,-3.083333,-0.008500,2.583333,2.00,0.049583,1.416667,2.750000,-0.010437,-0.250000,-3.083333,-4.166667,-4.250000,-1.333333,-3.583333,-2.833333,0.666667,-2.833333,10.75,0.000000
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,0.002667,0.001917,0.007250,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.416667,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,0.500000,-2.833333,10.75,0.000000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.341667,-2.608333,-0.059667,-0.098333,-1.658333,0.006750,0.009083,0.011000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.250000,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,-0.083333,-2.833333,10.75,0.000000

In [7]:
df_stat_season_matchup_cma12_diff = pd.merge(df_stat_season_matchup_cma12_diff, df_stats_gitiab_spread, on=['game_id', 'team_id_a', 'team_id_b'])
p(df_stat_season_matchup_cma12_diff)

(10266, 164)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,-8
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,14
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,2
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,8
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,3
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,7.7,5.3,-7.7,-5.3,24.1,24.6,0.195,0.54,5.2,0.022,-0.080,-0.011,-2.597,-3.6,0.036,0.042,0.0,0.003,0.0,0.0,0.0,-1.0,0.121,0.0,0.000,0.0,1.0,-5.0,0.041,0.0,-12.0,0.148,-5.0,-7.0,0.092593,4.0,2.0,2.0,7.0,-3.0,1.0,-2.0,1.0,-1.0,-19.0,0.0,4.8,4.341667,-1.091667,0.325000,1.858333,0.991667,0.138250,0.127500,5.841667,-0.029333,-0.010333,0.005583,1.6335,1.641667,0.043583,0.035917,0.0,0.00125,1.653333,1.111667,0.925833,-0.916667,0.033583,-2.083333,0.067583,-2.083333,4.916667,-1.416667,0.068167,-4.250000,-13.50,0.036083,-3.416667,-5.333333,0.029458,-1.166667,1.833333,3.000000,8.916667,0.000000,1.750000,1.333333,-1.416667,3.000000,0.00,0.083333,-9
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,-14.3,-9.7,14.3,9.7,-21.1,-18.2,-0.200,-0.21,-4.3,0.017,0.054,-0.001,-1.740,-1.8,-0.058,-0.080,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.094,0.0,2.0,9.0,-0.025,3.0,-1.0,0.042,-3.0,-5.0,0.040000,6.0,-6.0,2.0,-7.0,1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-3.650000,-1.950000,-0.059667,-0.265000,-1.658333,-0.028250,0.023667,-0.023000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.461667,-2.125000,-1.770000,-2.666667,-0.051583,-4.166667,-0.078667,-4.166667,-2.666667,-0.833333,-0.008500,3.666667,6.00,0.049583,1.416667,2.250000,-0.010437,0.500000,-3.333333,-2.833333,-4.250000,-0.583333,-4.833333,-2.833333,-1.333333,-2.833333,10.75,0.000000,10
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,-8.5,-12.4,8.5,12.4,-21.1,-20.9,-0.200,-2.15,-4.5,0.071,0.126,0.059,-1.740,-1.8,-0.088,-0.104,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-2.0,9.0,-0.054,2.0,0.0,0.042,-3.0,-5.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,-0.000167,-0.009833,0.002167,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,-2.083333,-0.078667,-2.083333,-2.666667,-3.083333,-0.008500,2.583333,2.00,0.049583,1.416667,2.750000,-0.010437,-0.250000,-3.083333,-4.166667,-4.250000,-1.333333,-3.583333,-2.833333,0.666667,-2.833333,10.75,0.000000,19
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,0.002667,0.001917,0.007250,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.416667,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,0.500000,-2.833333,10.75,0.000000,8
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.341667,-2.608333,-0.059667,-0.098333,-1.658333,0.006750,0.009083,0.011000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.250000,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,-0.083333,-2.833333,10.75,0.000000,23

In [8]:
column_name_list = list(df_stat_season_matchup_cma12_diff.columns)
pl(column_name_list)

164

['game_id',
 'TEAM_ABBREVIATION_a',
 'TEAM_ABBREVIATION_b',
 'team_id_a',
 'team_id_b',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'E_OFF_RATING_sm_cma12_diff',
 'OFF_RATING_sm_cma12_diff',
 'E_DEF_RATING_sm_cma12_diff',
 'DEF_RATING_sm_cma12_diff',
 'E_NET_RATING_sm_cma12_diff',
 'NET_RATING_sm_cma12_diff',
 'AST_PCT_sm_cma12_diff',
 'AST_TOV_sm_cma12_diff',
 'AST_RATIO_sm_cma12_diff',
 'OREB_PCT_sm_cma12_diff',
 'DREB_PCT_sm_cma12_diff',
 'REB_PCT_sm_cma12_diff',
 'E_TM_TOV_PCT_sm_cma12_diff',
 'TM_TOV_PCT_sm_cma12_diff',
 'EFG_PCT_sm_cma12_diff',
 'TS_PCT_sm_cma12_diff',
 'USG_PCT_sm_cma12_diff',
 'E_USG_PCT_sm_cma12_diff',
 'E_PACE_sm_cma12_diff',
 'PACE_sm_cma12_diff',
 'PACE_PER40_sm_cma12_diff',
 'POSS_sm_cma12_diff',
 'PIE_sm_cma12_diff',
 'duration_minutes_sm_cma12_diff',
 'w_pct_sm_cma12_diff',
 'min_sm_cma12_diff',
 'fgm_sm_cma12_diff',
 'fga_sm_cma12_diff',
 'fg_pct_sm_cma12_diff',
 'fg3m_sm_cma12_diff',
 'fg3a_sm_cma12_diff',
 'fg3_pct_sm_cma12_diff',
 'ftm_sm_cma12_diff',
 'fta_sm_cma12_diff',
 'ft_pct_sm_cma12_diff',
 'oreb_sm_cma12_diff',
 'dreb_sm_cma12_diff',
 'reb_sm_cma12_diff',
 'ast_sm_cma12_diff',
 'stl_sm_cma12_diff',
 'blk_sm_cma12_diff',
 'tov_sm_cma12_diff',
 'pf_sm_cma12_diff',
 'pts_sm_cma12_diff',
 'spread_sm_cma12_diff',
 'away_home_sm_cma12_diff',
 'E_OFF_RATING_sm_cmax12_diff',
 'OFF_RATING_sm_cmax12_diff',
 'E_DEF_RATING_sm_cmax12_diff',
 'DEF_RATING_sm_cmax12_diff',
 'E_NET_RATING_sm_cmax12_diff',
 'NET_RATING_sm_cmax12_diff',
 'AST_PCT_sm_cmax12_diff',
 'AST_TOV_sm_cmax12_diff',
 'AST_RATIO_sm_cmax12_diff',
 'OREB_PCT_sm_cmax12_diff',
 'DREB_PCT_sm_cmax12_diff',
 'REB_PCT_sm_cmax12_diff',
 'E_TM_TOV_PCT_sm_cmax12_diff',
 'TM_TOV_PCT_sm_cmax12_diff',
 'EFG_PCT_sm_cmax12_diff',
 'TS_PCT_sm_cmax12_diff',
 'USG_PCT_sm_cmax12_diff',
 'E_USG_PCT_sm_cmax12_diff',
 'E_PACE_sm_cmax12_diff',
 'PACE_sm_cmax12_diff',
 'PACE_PER40_sm_cmax12_diff',
 'POSS_sm_cmax12_diff',
 'PIE_sm_cmax12_diff',
 'duration_minutes_sm_cmax12_diff',
 'w_pct_sm_cmax12_diff',
 'min_sm_cmax12_diff',
 'fgm_sm_cmax12_diff',
 'fga_sm_cmax12_diff',
 'fg_pct_sm_cmax12_diff',
 'fg3m_sm_cmax12_diff',
 'fg3a_sm_cmax12_diff',
 'fg3_pct_sm_cmax12_diff',
 'ftm_sm_cmax12_diff',
 'fta_sm_cmax12_diff',
 'ft_pct_sm_cmax12_diff',
 'oreb_sm_cmax12_diff',
 'dreb_sm_cmax12_diff',
 'reb_sm_cmax12_diff',
 'ast_sm_cmax12_diff',
 'stl_sm_cmax12_diff',
 'blk_sm_cmax12_diff',
 'tov_sm_cmax12_diff',
 'pf_sm_cmax12_diff',
 'pts_sm_cmax12_diff',
 'spread_sm_cmax12_diff',
 'away_home_sm_cmax12_diff',
 'E_OFF_RATING_cma_sm_cmax12_diff',
 'OFF_RATING_cma_sm_cmax12_diff',
 'E_DEF_RATING_cma_sm_cmax12_diff',
 'DEF_RATING_cma_sm_cmax12_diff',
 'E_NET_RATING_cma_sm_cmax12_diff',
 'NET_RATING_cma_sm_cmax12_diff',
 'AST_PCT_cma_sm_cmax12_diff',
 'AST_TOV_cma_sm_cmax12_diff',
 'AST_RATIO_cma_sm_cmax12_diff',
 'OREB_PCT_cma_sm_cmax12_diff',
 'DREB_PCT_cma_sm_cmax12_diff',
 'REB_PCT_cma_sm_cmax12_diff',
 'E_TM_TOV_PCT_cma_sm_cmax12_diff',
 'TM_TOV_PCT_cma_sm_cmax12_diff',
 'EFG_PCT_cma_sm_cmax12_diff',
 'TS_PCT_cma_sm_cmax12_diff',
 'USG_PCT_cma_sm_cmax12_diff',
 'E_USG_PCT_cma_sm_cmax12_diff',
 'E_PACE_cma_sm_cmax12_diff',
 'PACE_cma_sm_cmax12_diff',
 'PACE_PER40_cma_sm_cmax12_diff',
 'POSS_cma_sm_cmax12_diff',
 'PIE_cma_sm_cmax12_diff',
 'duration_minutes_cma_sm_cmax12_diff',
 'w_pct_cma_sm_cmax12_diff',
 'min_cma_sm_cmax12_diff',
 'fgm_cma_sm_cmax12_diff',
 'fga_cma_sm_cmax12_diff',
 'fg_pct_cma_sm_cmax12_diff',
 'fg3m_cma_sm_cmax12_diff',
 'fg3a_cma_sm_cmax12_diff',
 'fg3_pct_cma_sm_cmax12_diff',
 'ftm_cma_sm_cmax12_diff',
 'fta_cma_sm_cmax12_diff',
 'ft_pct_cma_sm_cmax12_diff',
 'oreb_cma_sm_cmax12_diff',
 'dreb_cma_sm_cmax12_diff',
 'reb_cma_sm_cmax12_diff',
 'ast_cma_sm_cmax12_diff',
 'stl_cma_sm_cmax12_diff',
 'blk_cma_sm_cmax12_diff',
 'tov_cma_sm_cmax12_diff',
 'pf_cma_sm_cmax12_diff',
 'pts_cma_sm_cmax12_diff',
 'spread_cma_sm_cmax12_diff',
 'away_home_cma_sm_cmax12_diff',
 'spread_a']

## 4.6 Get Indicator Variables<a id='4.6 Get_Indicator_Variables'></a>

In [9]:
df_stat_season_matchup_cma12_diff.select_dtypes('object')

,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,season,season_type,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b
0,BOS,MIA,2010-11,Regular Season,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA
1,PHX,POR,2010-11,Regular Season,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR
2,HOU,LAL,2010-11,Regular Season,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL
3,BOS,CLE,2010-11,Regular Season,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE
4,DET,NJN,2010-11,Regular Season,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,GSW,HOU,2017-18,Playoffs,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU
10262,CLE,GSW,2017-18,Playoffs,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW
10263,CLE,GSW,2017-18,Playoffs,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW
10264,CLE,GSW,2017-18,Playoffs,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW
10265,CLE,GSW,2017-18,Playoffs,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW

In [10]:
column_names_categorical_list = list(df_stat_season_matchup_cma12_diff.select_dtypes('object').columns) + ['team_id_a', 'team_id_b']
pl(column_names_categorical_list)

22

['TEAM_ABBREVIATION_a',
 'TEAM_ABBREVIATION_b',
 'season',
 'season_type',
 'TEAM_NAME_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'team_id_a',
 'team_id_b']

In [11]:
df_indicator_variables = pd.get_dummies(df_stat_season_matchup_cma12_diff[column_names_categorical_list])
p(df_indicator_variables)

(10266, 1330)

,team_id_a,team_id_b,TEAM_ABBREVIATION_a_ATL,TEAM_ABBREVIATION_a_BKN,TEAM_ABBREVIATION_a_BOS,TEAM_ABBREVIATION_a_CHA,TEAM_ABBREVIATION_a_CHI,TEAM_ABBREVIATION_a_CLE,TEAM_ABBREVIATION_a_DAL,TEAM_ABBREVIATION_a_DEN,TEAM_ABBREVIATION_a_DET,TEAM_ABBREVIATION_a_GSW,TEAM_ABBREVIATION_a_HOU,TEAM_ABBREVIATION_a_IND,TEAM_ABBREVIATION_a_LAC,TEAM_ABBREVIATION_a_LAL,TEAM_ABBREVIATION_a_MEM,TEAM_ABBREVIATION_a_MIA,TEAM_ABBREVIATION_a_MIL,TEAM_ABBREVIATION_a_MIN,TEAM_ABBREVIATION_a_NJN,TEAM_ABBREVIATION_a_NOH,TEAM_ABBREVIATION_a_NOP,TEAM_ABBREVIATION_a_NYK,TEAM_ABBREVIATION_a_OKC,TEAM_ABBREVIATION_a_ORL,TEAM_ABBREVIATION_a_PHI,TEAM_ABBREVIATION_a_PHX,TEAM_ABBREVIATION_a_POR,TEAM_ABBREVIATION_a_SAC,TEAM_ABBREVIATION_a_SAS,TEAM_ABBREVIATION_a_TOR,TEAM_ABBREVIATION_a_UTA,TEAM_ABBREVIATION_b_BKN,TEAM_ABBREVIATION_b_BOS,TEAM_ABBREVIATION_b_CHA,TEAM_ABBREVIATION_b_CHI,TEAM_ABBREVIATION_b_CLE,TEAM_ABBREVIATION_b_DAL,TEAM_ABBREVIATION_b_DEN,TEAM_ABBREVIATION_b_DET,TEAM_ABBREVIATION_b_GSW,TEAM_ABBREVIATION_b_HOU,TEAM_ABBREVIATION_b_IND,TEAM_ABBREVIATION_b_LAC,TEAM_ABBREVIATION_b_LAL,TEAM_ABBREVIATION_b_MEM,TEAM_ABBREVIATION_b_MIA,TEAM_ABBREVIATION_b_MIL,TEAM_ABBREVIATION_b_MIN,TEAM_ABBREVIATION_b_NJN,TEAM_ABBREVIATION_b_NOH,TEAM_ABBREVIATION_b_NOP,TEAM_ABBREVIATION_b_NYK,TEAM_ABBREVIATION_b_OKC,TEAM_ABBREVIATION_b_ORL,TEAM_ABBREVIATION_b_PHI,TEAM_ABBREVIATION_b_PHX,TEAM_ABBREVIATION_b_POR,TEAM_ABBREVIATION_b_SAC,TEAM_ABBREVIATION_b_SAS,TEAM_ABBREVIATION_b_TOR,TEAM_ABBREVIATION_b_UTA,TEAM_ABBREVIATION_b_WAS,season_2010-11,season_2011-12,season_2012-13,season_2013-14,season_2014-15,season_2015-16,season_2016-17,season_2017-18,season_type_Playoffs,season_type_Regular Season,TEAM_NAME_a_76ers,TEAM_NAME_a_Bobcats,TEAM_NAME_a_Bucks,TEAM_NAME_a_Bulls,TEAM_NAME_a_Cavaliers,TEAM_NAME_a_Celtics,TEAM_NAME_a_Clippers,TEAM_NAME_a_Grizzlies,TEAM_NAME_a_Hawks,TEAM_NAME_a_Heat,TEAM_NAME_a_Hornets,TEAM_NAME_a_Jazz,TEAM_NAME_a_Kings,TEAM_NAME_a_Knicks,TEAM_NAME_a_Lakers,TEAM_NAME_a_Magic,TEAM_NAME_a_Mavericks,TEAM_NAME_a_Nets,TEAM_NAME_a_Nuggets,TEAM_NAME_a_Pacers,TEAM_NAME_a_Pelicans,TEAM_NAME_a_Pistons,TEAM_NAME_a_Raptors,TEAM_NAME_a_Rockets,TEAM_NAME_a_Spurs,TEAM_NAME_a_Suns,TEAM_NAME_a_Thunder,TEAM_NAME_a_Timberwolves,TEAM_NAME_a_Trail Blazers,TEAM_NAME_a_Warriors,TEAM_CITY_a_Atlanta,TEAM_CITY_a_Boston,TEAM_CITY_a_Brooklyn,TEAM_CITY_a_Charlotte,TEAM_CITY_a_Chicago,TEAM_CITY_a_Cleveland,TEAM_CITY_a_Dallas,TEAM_CITY_a_Denver,TEAM_CITY_a_Detroit,TEAM_CITY_a_Golden State,TEAM_CITY_a_Houston,TEAM_CITY_a_Indiana,TEAM_CITY_a_Los Angeles,TEAM_CITY_a_Memphis,TEAM_CITY_a_Miami,TEAM_CITY_a_Milwaukee,TEAM_CITY_a_Minnesota,TEAM_CITY_a_New Jersey,TEAM_CITY_a_New Orleans,TEAM_CITY_a_New York,TEAM_CITY_a_Oklahoma City,TEAM_CITY_a_Orlando,TEAM_CITY_a_Philadelphia,TEAM_CITY_a_Phoenix,TEAM_CITY_a_Portland,TEAM_CITY_a_Sacramento,TEAM_CITY_a_San Antonio,TEAM_CITY_a_Toronto,TEAM_CITY_a_Utah,MIN_a_239:56,MIN_a_240:00,MIN_a_265:00,MIN_a_290:00,MIN_a_315:00,MIN_a_340:00,duration_a_0 days 03:59:56,duration_a_0 days 04:00:00,duration_a_0 days 04:25:00,duration_a_0 days 04:50:00,duration_a_0 days 05:15:00,duration_a_0 days 05:40:00,wl_a_L,wl_a_W,matchup_a_ATL vs. BKN,matchup_a_ATL vs. BOS,matchup_a_ATL vs. CHA,matchup_a_ATL vs. CHI,matchup_a_ATL vs. CLE,matchup_a_ATL vs. DAL,matchup_a_ATL vs. DEN,matchup_a_ATL vs. DET,matchup_a_ATL vs. GSW,matchup_a_ATL vs. HOU,matchup_a_ATL vs. IND,matchup_a_ATL vs. LAC,matchup_a_ATL vs. LAL,matchup_a_ATL vs. MEM,matchup_a_ATL vs. MIA,matchup_a_ATL vs. MIL,matchup_a_ATL vs. MIN,matchup_a_ATL vs. NJN,matchup_a_ATL vs. NOH,matchup_a_ATL vs. NOP,matchup_a_ATL vs. NYK,matchup_a_ATL vs. OKC,matchup_a_ATL vs. ORL,matchup_a_ATL vs. PHI,matchup_a_ATL vs. PHX,matchup_a_ATL vs. POR,matchup_a_ATL vs. SAC,matchup_a_ATL vs. SAS,matchup_a_ATL vs. TOR,matchup_a_ATL vs. UTA,matchup_a_ATL vs. WAS,matchup_a_BKN vs. BOS,matchup_a_BKN vs. CHA,matchup_a_BKN vs. CHI,matchup_a_BKN vs. CLE,matchup_a_BKN vs. DAL,matchup_a_BKN vs. DEN,matchup_a_BKN vs. DET,matchup_a_BKN vs. GSW,matchup_a_BKN vs. HOU,matchup_a_BKN vs. IND,matchup_a_BKN vs. LAC,matchup_a_BKN vs. LAL,matchup_a_BKN vs. MEM,matchup_a_BKN vs. MIA,matchup_a_BKN vs. MIL,matchup_a_BKN vs. MIN,matchup_a_BKN vs. NOH,matchup_a_BKN vs. NOP,matchup_a_BKN vs. NYK,matchup_a_BKN vs. OKC,matchup_a_BKN vs. ORL,matchup_a_BKN vs. PHI,matchup_a_BKN vs. PHX,matchup_a_BKN vs. POR,matchup_a_BKN vs. SAC,matchup_a_BKN vs. SAS,matchup_a_BKN vs. TOR,matchup_a_BKN vs. UTA,matchup_a_BKN vs. WAS,matchup_a_BOS vs. CHA,matchup_a_BOS vs. CHI,matchup_a_BOS vs. CLE,matchup_a_BOS vs. DAL,matchup_a_BOS vs. DEN,matchup_a_BOS vs. DET,matchup_a_BOS vs. GSW,matchup_a_BOS vs. HOU,matchup_a_BOS vs. IND,matchup_a_BOS vs. LAC,matchup_a_BOS vs. LAL,matchup_a_BOS vs. MEM,matchup_a_BOS vs. MIA,matchup_a_BOS vs. MIL,matchup_a_BOS vs. MIN,matchup_a_BOS vs. NJN,matchup_a_BOS vs. NOH,matchup_a_BOS vs. NOP,matchup_a_BOS vs. NYK,matchup_a_BOS vs. OKC,matchup_a_BOS vs. ORL,matchup_a_BOS vs. PHI,matchup_a_BOS vs. PHX,matchup_a_BOS vs. POR,matchup_a_BOS vs. SAC,matchup_a_BOS vs. SAS,matchup_a_BOS vs. TOR,matchup_a_BOS vs. UTA,matchup_a_BOS vs. WAS,matchup_a_CHA vs. CHI,matchup_a_CHA vs. CLE,matchup_a_CHA vs. DAL,matchup_a_CHA vs. DEN,matchup_a_CHA vs. DET,matchup_a_CHA vs. GSW,matchup_a_CHA vs. HOU,matchup_a_CHA vs. IND,matchup_a_CHA vs. LAC,matchup_a_CHA vs. LAL,matchup_a_CHA vs. MEM,matchup_a_CHA vs. MIA,matchup_a_CHA vs. MIL,matchup_a_CHA vs. MIN,matchup_a_CHA vs. NJN,matchup_a_CHA vs. NOH,matchup_a_CHA vs. NOP,matchup_a_CHA vs. NYK,matchup_a_CHA vs. OKC,matchup_a_CHA vs. ORL,matchup_a_CHA vs. PHI,matchup_a_CHA vs. PHX,matchup_a_CHA vs. POR,matchup_a_CHA vs. SAC,matchup_a_CHA vs. SAS,matchup_a_CHA vs. TOR,matchup_a_CHA vs. UTA,matchup_a_CHA vs. WAS,matchup_a_CHI vs. CLE,matchup_a_CHI vs. DAL,matchup_a_CHI vs. DEN,matchup_a_CHI vs. DET,matchup_a_CHI vs. GSW,matchup_a_CHI vs. HOU,matchup_a_CHI vs. IND,matchup_a_CHI vs. LAC,matchup_a_CHI vs. LAL,matchup_a_CHI vs. MEM,matchup_a_CHI vs. MIA,matchup_a_CHI vs. MIL,matchup_a_CHI vs. MIN,matchup_a_CHI vs. NJN,matchup_a_CHI vs. NOH,matchup_a_CHI vs. NOP,matchup_a_CHI vs. NYK,matchup_a_CHI vs. OKC,matchup_a_CHI vs. ORL,matchup_a_CHI vs. PHI,matchup_a_CHI vs. PHX,matchup_a_CHI vs. POR,matchup_a_CHI vs. SAC,matchup_a_CHI vs. SAS,matchup_a_CHI vs. TOR,matchup_a_CHI vs. UTA,matchup_a_CHI vs. WAS,matchup_a_CLE vs. DAL,matchup_a_CLE vs. DEN,matchup_a_CLE vs. DET,matchup_a_CLE vs. GSW,matchup_a_CLE vs. HOU,matchup_a_CLE vs. IND,matchup_a_CLE vs. LAC,matchup_a_CLE vs. LAL,matchup_a_CLE vs. MEM,matchup_a_CLE vs. MIA,matchup_a_CLE vs. MIL,matchup_a_CLE vs. MIN,matchup_a_CLE vs. NJN,matchup_a_CLE vs. NOH,matchup_a_CLE vs. NOP,matchup_a_CLE vs. NYK,matchup_a_CLE vs. OKC,matchup_a_CLE vs. ORL,matchup_a_CLE vs. PHI,matchup_a_CLE vs. PHX,matchup_a_CLE vs. POR,matchup_a_CLE vs. SAC,matchup_a_CLE vs. SAS,matchup_a_CLE vs. TOR,matchup_a_CLE vs. UTA,matchup_a_CLE vs. WAS,matchup_a_DAL vs. DEN,matchup_a_DAL vs. DET,matchup_a_DAL vs. GSW,matchup_a_DAL vs. HOU,matchup_a_DAL vs. IND,matchup_a_DAL vs. LAC,matchup_a_DAL vs. LAL,matchup_a_DAL vs. MEM,matchup_a_DAL vs. MIA,matchup_a_DAL vs. MIL,matchup_a_DAL vs. MIN,matchup_a_DAL vs. NJN,matchup_a_DAL vs. NOH,matchup_a_DAL vs. NOP,matchup_a_DAL vs. NYK,matchup_a_DAL vs. OKC,matchup_a_DAL vs. ORL,matchup_a_DAL vs. PHI,matchup_a_DAL vs. PHX,matchup_a_DAL vs. POR,matchup_a_DAL vs. SAC,matchup_a_DAL vs. SAS,matchup_a_DAL vs. TOR,matchup_a_DAL vs. UTA,matchup_a_DAL vs. WAS,matchup_a_DEN vs. DET,matchup_a_DEN vs. GSW,matchup_a_DEN vs. HOU,matchup_a_DEN vs. IND,matchup_a_DEN vs. LAC,matchup_a_DEN vs. LAL,matchup_a_DEN vs. MEM,matchup_a_DEN vs. MIA,matchup_a_DEN vs. MIL,matchup_a_DEN vs. MIN,matchup_a_DEN vs. NJN,matchup_a_DEN vs. NOH,matchup_a_DEN vs. NOP,matchup_a_DEN vs. NYK,matchup_a_DEN vs. OKC,matchup_a_DEN vs. ORL,matchup_a_DEN vs. PHI,matchup_a_DEN vs. PHX,matchup_a_DEN vs. POR,matchup_a_DEN vs. SAC,matchup_a_DEN vs. SAS,matchup_a_DEN vs. TOR,matchup_a_DEN vs. UTA,matchup_a_DEN vs. WAS,matchup_a_DET vs. GSW,matchup_a_DET vs. HOU,matchup_a_DET vs. IND,matchup_a_DET vs. LAC,matchup_a_DET vs. LAL,matchup_a_DET vs. MEM,matchup_a_DET vs. MIA,matchup_a_DET vs. MIL,matchup_a_DET vs. MIN,matchup_a_DET vs. NJN,matchup_a_DET vs. NOH,matchup_a_DET vs. NOP,matchup_a_DET vs. NYK,matchup_a_DET vs. OKC,matchup_a_DET vs. ORL,matchup_a_DET vs. PHI,matchup_a_DET vs. PHX,matchup_a_DET vs. POR,matchup_a_DET vs. SAC,matchup_a_DET vs. SAS,matchup_a_DET vs. TOR,matchup_a_DET vs. UTA,matchup_a_DET vs. WAS,matchup_a_GSW vs. HOU,matchup_a_GSW vs. IND,matchup_a_GSW vs. LAC,matchup_a_GSW vs. LAL,matchup_a_GSW vs. MEM,matchup_a_GSW vs. MIA,matchup_a_GSW vs. MIL,matchup_a_GSW vs. MIN,matchup_a_GSW vs. NJN,matchup_a_GSW vs. NOH,matchup_a_GSW vs. NOP,matchup_a_GSW vs. NYK,matchup_a_GSW vs. OKC,matchup_a_GSW vs. ORL,matchup_a_GSW vs. PHI,matchup_a_GSW vs. PHX,matchup_a_GSW vs. POR,matchup_a_GSW vs. SAC,matchup_a_GSW vs. SAS,matchup_a_GSW vs. TOR,matchup_a_GSW vs. UTA,matchup_a_GSW vs. WAS,matchup_a_HOU vs. IND,matchup_a_HOU vs. LAC,matchup_a_HOU vs. LAL,matchup_a_HOU vs. MEM,matchup_a_HOU vs. MIA,matchup_a_HOU vs. MIL,matchup_a_HOU vs. MIN,matchup_a_HOU vs. NJN,matchup_a_HOU vs. NOH,matchup_a_HOU vs. NOP,matchup_a_HOU vs. NYK,matchup_a_HOU vs. OKC,matchup_a_HOU vs. ORL,matchup_a_HOU vs. PHI,matchup_a_HOU vs. PHX,matchup_a_HOU vs. POR,matchup_a_HOU vs. SAC,matchup_a_HOU vs. SAS,matchup_a_HOU vs. TOR,matchup_a_HOU vs. UTA,matchup_a_HOU vs. WAS,matchup_a_IND vs. LAC,matchup_a_IND vs. LAL,matchup_a_IND vs. MEM,matchup_a_IND vs. MIA,matchup_a_IND vs. MIL,matchup_a_IND vs. MIN,matchup_a_IND vs. NJN,matchup_a_IND vs. NOH,matchup_a_IND vs. NOP,matchup_a_IND vs. NYK,matchup_a_IND vs. OKC,matchup_a_IND vs. ORL,matchup_a_IND vs. PHI,matchup_a_IND vs. PHX,matchup_a_IND vs. POR,matchup_a_IND vs. SAC,matchup_a_IND vs. SAS,matchup_a_IND vs. TOR,matchup_a_IND vs. UTA,matchup_a_IND vs. WAS,matchup_a_LAC vs. LAL,matchup_a_LAC vs. MEM,matchup_a_LAC vs. MIA,matchup_a_LAC vs. MIL,matchup_a_LAC vs. MIN,matchup_a_LAC vs. NJN,matchup_a_LAC vs. NOH,matchup_a_LAC vs. NOP,matchup_a_LAC vs. NYK,matchup_a_LAC vs. OKC,matchup_a_LAC vs. ORL,matchup_a_LAC vs. PHI,matchup_a_LAC vs. PHX,matchup_a_LAC vs. POR,matchup_a_LAC vs. SAC,matchup_a_LAC vs. SAS,matchup_a_LAC vs. TOR,matchup_a_LAC vs. UTA,matchup_a_LAC vs. WAS,matchup_a_LAL vs. MEM,matchup_a_LAL vs. MIA,matchup_a_LAL vs. MIL,matchup_a_LAL vs. MIN,matchup_a_LAL vs. NJN,matchup_a_LAL vs. NOH,matchup_a_LAL vs. NOP,matchup_a_LAL vs. NYK,matchup_a_LAL vs. OKC,matchup_a_LAL vs. ORL,matchup_a_LAL vs. PHI,matchup_a_LAL vs. PHX,matchup_a_LAL vs. POR,matchup_a_LAL vs. SAC,matchup_a_LAL vs. SAS,matchup_a_LAL vs. TOR,matchup_a_LAL vs. UTA,matchup_a_LAL vs. WAS,matchup_a_MEM vs. MIA,matchup_a_MEM vs. MIL,matchup_a_MEM vs. MIN,matchup_a_MEM vs. NJN,matchup_a_MEM vs. NOH,matchup_a_MEM vs. NOP,matchup_a_MEM vs. NYK,matchup_a_MEM vs. OKC,matchup_a_MEM vs. ORL,matchup_a_MEM vs. PHI,...,matchup_b_BKN vs. SAS,matchup_b_BKN vs. TOR,matchup_b_BKN vs. UTA,matchup_b_BKN vs. WAS,matchup_b_BOS vs. CHA,matchup_b_BOS vs. CHI,matchup_b_BOS vs. CLE,matchup_b_BOS vs. DAL,matchup_b_BOS vs. DEN,matchup_b_BOS vs. DET,matchup_b_BOS vs. GSW,matchup_b_BOS vs. HOU,matchup_b_BOS vs. IND,matchup_b_BOS vs. LAC,matchup_b_BOS vs. LAL,matchup_b_BOS vs. MEM,matchup_b_BOS vs. MIA,matchup_b_BOS vs. MIL,matchup_b_BOS vs. MIN,matchup_b_BOS vs. NJN,matchup_b_BOS vs. NOH,matchup_b_BOS vs. NOP,matchup_b_BOS vs. NYK,matchup_b_BOS vs. OKC,matchup_b_BOS vs. ORL,matchup_b_BOS vs. PHI,matchup_b_BOS vs. PHX,matchup_b_BOS vs. POR,matchup_b_BOS vs. SAC,matchup_b_BOS vs. SAS,matchup_b_BOS vs. TOR,matchup_b_BOS vs. UTA,matchup_b_BOS vs. WAS,matchup_b_CHA vs. CHI,matchup_b_CHA vs. CLE,matchup_b_CHA vs. DAL,matchup_b_CHA vs. DEN,matchup_b_CHA vs. DET,matchup_b_CHA vs. GSW,matchup_b_CHA vs. HOU,matchup_b_CHA vs. IND,matchup_b_CHA vs. LAC,matchup_b_CHA vs. LAL,matchup_b_CHA vs. MEM,matchup_b_CHA vs. MIA,matchup_b_CHA vs. MIL,matchup_b_CHA vs. MIN,matchup_b_CHA vs. NJN,matchup_b_CHA vs. NOH,matchup_b_CHA vs. NOP,matchup_b_CHA vs. NYK,matchup_b_CHA vs. OKC,matchup_b_CHA vs. ORL,matchup_b_CHA vs. PHI,matchup_b_CHA vs. PHX,matchup_b_CHA vs. POR,matchup_b_CHA vs. SAC,matchup_b_CHA vs. SAS,matchup_b_CHA vs. TOR,matchup_b_CHA vs. UTA,matchup_b_CHA vs. WAS,matchup_b_CHI vs. CLE,matchup_b_CHI vs. DAL,matchup_b_CHI vs. DEN,matchup_b_CHI vs. DET,matchup_b_CHI vs. GSW,matchup_b_CHI vs. HOU,matchup_b_CHI vs. IND,matchup_b_CHI vs. LAC,matchup_b_CHI vs. LAL,matchup_b_CHI vs. MEM,matchup_b_CHI vs. MIA,matchup_b_CHI vs. MIL,matchup_b_CHI vs. MIN,matchup_b_CHI vs. NJN,matchup_b_CHI vs. NOH,matchup_b_CHI vs. NOP,matchup_b_CHI vs. NYK,matchup_b_CHI vs. OKC,matchup_b_CHI vs. ORL,matchup_b_CHI vs. PHI,matchup_b_CHI vs. PHX,matchup_b_CHI vs. POR,matchup_b_CHI vs. SAC,matchup_b_CHI vs. SAS,matchup_b_CHI vs. TOR,matchup_b_CHI vs. UTA,matchup_b_CHI vs. WAS,matchup_b_CLE vs. DAL,matchup_b_CLE vs. DEN,matchup_b_CLE vs. DET,matchup_b_CLE vs. GSW,matchup_b_CLE vs. HOU,matchup_b_CLE vs. IND,matchup_b_CLE vs. LAC,matchup_b_CLE vs. LAL,matchup_b_CLE vs. MEM,matchup_b_CLE vs. MIA,matchup_b_CLE vs. MIL,matchup_b_CLE vs. MIN,matchup_b_CLE vs. NJN,matchup_b_CLE vs. NOH,matchup_b_CLE vs. NOP,matchup_b_CLE vs. NYK,matchup_b_CLE vs. OKC,matchup_b_CLE vs. ORL,matchup_b_CLE vs. PHI,matchup_b_CLE vs. PHX,matchup_b_CLE vs. POR,matchup_b_CLE vs. SAC,matchup_b_CLE vs. SAS,matchup_b_CLE vs. TOR,matchup_b_CLE vs. UTA,matchup_b_CLE vs. WAS,matchup_b_DAL vs. DEN,matchup_b_DAL vs. DET,matchup_b_DAL vs. GSW,matchup_b_DAL vs. HOU,matchup_b_DAL vs. IND,matchup_b_DAL vs. LAC,matchup_b_DAL vs. LAL,matchup_b_DAL vs. MEM,matchup_b_DAL vs. MIA,matchup_b_DAL vs. MIL,matchup_b_DAL vs. MIN,matchup_b_DAL vs. NJN,matchup_b_DAL vs. NOH,matchup_b_DAL vs. NOP,matchup_b_DAL vs. NYK,matchup_b_DAL vs. OKC,matchup_b_DAL vs. ORL,matchup_b_DAL vs. PHI,matchup_b_DAL vs. PHX,matchup_b_DAL vs. POR,matchup_b_DAL vs. SAC,matchup_b_DAL vs. SAS,matchup_b_DAL vs. TOR,matchup_b_DAL vs. UTA,matchup_b_DAL vs. WAS,matchup_b_DEN vs. DET,matchup_b_DEN vs. GSW,matchup_b_DEN vs. HOU,matchup_b_DEN vs. IND,matchup_b_DEN vs. LAC,matchup_b_DEN vs. LAL,matchup_b_DEN vs. MEM,matchup_b_DEN vs. MIA,matchup_b_DEN vs. MIL,matchup_b_DEN vs. MIN,matchup_b_DEN vs. NJN,matchup_b_DEN vs. NOH,matchup_b_DEN vs. NOP,matchup_b_DEN vs. NYK,matchup_b_DEN vs. OKC,matchup_b_DEN vs. ORL,matchup_b_DEN vs. PHI,matchup_b_DEN vs. PHX,matchup_b_DEN vs. POR,matchup_b_DEN vs. SAC,matchup_b_DEN vs. SAS,matchup_b_DEN vs. TOR,matchup_b_DEN vs. UTA,matchup_b_DEN vs. WAS,matchup_b_DET vs. GSW,matchup_b_DET vs. HOU,matchup_b_DET vs. IND,matchup_b_DET vs. LAC,matchup_b_DET vs. LAL,matchup_b_DET vs. MEM,matchup_b_DET vs. MIA,matchup_b_DET vs. MIL,matchup_b_DET vs. MIN,matchup_b_DET vs. NJN,matchup_b_DET vs. NOH,matchup_b_DET vs. NOP,matchup_b_DET vs. NYK,matchup_b_DET vs. OKC,matchup_b_DET vs. ORL,matchup_b_DET vs. PHI,matchup_b_DET vs. PHX,matchup_b_DET vs. POR,matchup_b_DET vs. SAC,matchup_b_DET vs. SAS,matchup_b_DET vs. TOR,matchup_b_DET vs. UTA,matchup_b_DET vs. WAS,matchup_b_GSW vs. HOU,matchup_b_GSW vs. IND,matchup_b_GSW vs. LAC,matchup_b_GSW vs. LAL,matchup_b_GSW vs. MEM,matchup_b_GSW vs. MIA,matchup_b_GSW vs. MIL,matchup_b_GSW vs. MIN,matchup_b_GSW vs. NJN,matchup_b_GSW vs. NOH,matchup_b_GSW vs. NOP,matchup_b_GSW vs. NYK,matchup_b_GSW vs. OKC,matchup_b_GSW vs. ORL,matchup_b_GSW vs. PHI,matchup_b_GSW vs. PHX,matchup_b_GSW vs. POR,matchup_b_GSW vs. SAC,matchup_b_GSW vs. SAS,matchup_b_GSW vs. TOR,matchup_b_GSW vs. UTA,matchup_b_GSW vs. WAS,matchup_b_HOU vs. IND,matchup_b_HOU vs. LAC,matchup_b_HOU vs. LAL,matchup_b_HOU vs. MEM,matchup_b_HOU vs. MIA,matchup_b_HOU vs. MIL,matchup_b_HOU vs. MIN,matchup_b_HOU vs. NJN,matchup_b_HOU vs. NOH,matchup_b_HOU vs. NOP,matchup_b_HOU vs. NYK,matchup_b_HOU vs. OKC,matchup_b_HOU vs. ORL,matchup_b_HOU vs. PHI,matchup_b_HOU vs. PHX,matchup_b_HOU vs. POR,matchup_b_HOU vs. SAC,matchup_b_HOU vs. SAS,matchup_b_HOU vs. TOR,matchup_b_HOU vs. UTA,matchup_b_HOU vs. WAS,matchup_b_IND vs. LAC,matchup_b_IND vs. LAL,matchup_b_IND vs. MEM,matchup_b_IND vs. MIA,matchup_b_IND vs. MIL,matchup_b_IND vs. MIN,matchup_b_IND vs. NJN,matchup_b_IND vs. NOH,matchup_b_IND vs. NOP,matchup_b_IND vs. NYK,matchup_b_IND vs. OKC,matchup_b_IND vs. ORL,matchup_b_IND vs. PHI,matchup_b_IND vs. PHX,matchup_b_IND vs. POR,matchup_b_IND vs. SAC,matchup_b_IND vs. SAS,matchup_b_IND vs. TOR,matchup_b_IND vs. UTA,matchup_b_IND vs. WAS,matchup_b_LAC vs. LAL,matchup_b_LAC vs. MEM,matchup_b_LAC vs. MIA,matchup_b_LAC vs. MIL,matchup_b_LAC vs. MIN,matchup_b_LAC vs. NJN,matchup_b_LAC vs. NOH,matchup_b_LAC vs. NOP,matchup_b_LAC vs. NYK,matchup_b_LAC vs. OKC,matchup_b_LAC vs. ORL,matchup_b_LAC vs. PHI,matchup_b_LAC vs. PHX,matchup_b_LAC vs. POR,matchup_b_LAC vs. SAC,matchup_b_LAC vs. SAS,matchup_b_LAC vs. TOR,matchup_b_LAC vs. UTA,matchup_b_LAC vs. WAS,matchup_b_LAL vs. MEM,matchup_b_LAL vs. MIA,matchup_b_LAL vs. MIL,matchup_b_LAL vs. MIN,matchup_b_LAL vs. NJN,matchup_b_LAL vs. NOH,matchup_b_LAL vs. NOP,matchup_b_LAL vs. NYK,matchup_b_LAL vs. OKC,matchup_b_LAL vs. ORL,matchup_b_LAL vs. PHI,matchup_b_LAL vs. PHX,matchup_b_LAL vs. POR,matchup_b_LAL vs. SAC,matchup_b_LAL vs. SAS,matchup_b_LAL vs. TOR,matchup_b_LAL vs. UTA,matchup_b_LAL vs. WAS,matchup_b_MEM vs. MIA,matchup_b_MEM vs. MIL,matchup_b_MEM vs. MIN,matchup_b_MEM vs. NJN,matchup_b_MEM vs. NOH,matchup_b_MEM vs. NOP,matchup_b_MEM vs. NYK,matchup_b_MEM vs. OKC,matchup_b_MEM vs. ORL,matchup_b_MEM vs. PHI,matchup_b_MEM vs. PHX,matchup_b_MEM vs. POR,matchup_b_MEM vs. SAC,matchup_b_MEM vs. SAS,matchup_b_MEM vs. TOR,matchup_b_MEM vs. UTA,matchup_b_MEM vs. WAS,matchup_b_MIA vs. MIL,matchup_b_MIA vs. MIN,matchup_b_MIA vs. NJN,matchup_b_MIA vs. NOH,matchup_b_MIA vs. NOP,matchup_b_MIA vs. NYK,matchup_b_MIA vs. OKC,matchup_b_MIA vs. ORL,matchup_b_MIA vs. PHI,matchup_b_MIA vs. PHX,matchup_b_MIA vs. POR,matchup_b_MIA vs. SAC,matchup_b_MIA vs. SAS,matchup_b_MIA vs. TOR,matchup_b_MIA vs. UTA,matchup_b_MIA vs. WAS,matchup_b_MIL vs. MIN,matchup_b_MIL vs. NJN,matchup_b_MIL vs. NOH,matchup_b_MIL vs. NOP,matchup_b_MIL vs. NYK,matchup_b_MIL vs. OKC,matchup_b_MIL vs. ORL,matchup_b_MIL vs. PHI,matchup_b_MIL vs. PHX,matchup_b_MIL vs. POR,matchup_b_MIL vs. SAC,matchup_b_MIL vs. SAS,matchup_b_MIL vs. TOR,matchup_b_MIL vs. UTA,matchup_b_MIL vs. WAS,matchup_b_MIN vs. NJN,matchup_b_MIN vs. NOH,matchup_b_MIN vs. NOP,matchup_b_MIN vs. NYK,matchup_b_MIN vs. OKC,matchup_b_MIN vs. ORL,matchup_b_MIN vs. PHI,matchup_b_MIN vs. PHX,matchup_b_MIN vs. POR,matchup_b_MIN vs. SAC,matchup_b_MIN vs. SAS,matchup_b_MIN vs. TOR,matchup_b_MIN vs. UTA,matchup_b_MIN vs. WAS,matchup_b_NJN vs. NOH,matchup_b_NJN vs. NYK,matchup_b_NJN vs. OKC,matchup_b_NJN vs. ORL,matchup_b_NJN vs. PHI,matchup_b_NJN vs. PHX,matchup_b_NJN vs. POR,matchup_b_NJN vs. SAC,matchup_b_NJN vs. SAS,matchup_b_NJN vs. TOR,matchup_b_NJN vs. UTA,matchup_b_NJN vs. WAS,matchup_b_NOH vs. NYK,matchup_b_NOH vs. OKC,matchup_b_NOH vs. ORL,matchup_b_NOH vs. PHI,matchup_b_NOH vs. PHX,matchup_b_NOH vs. POR,matchup_b_NOH vs. SAC,matchup_b_NOH vs. SAS,matchup_b_NOH vs. TOR,matchup_b_NOH vs. UTA,matchup_b_NOH vs. WAS,matchup_b_NOP vs. NYK,matchup_b_NOP vs. OKC,matchup_b_NOP vs. ORL,matchup_b_NOP vs. PHI,matchup_b_NOP vs. PHX,matchup_b_NOP vs. POR,matchup_b_NOP vs. SAC,matchup_b_NOP vs. SAS,matchup_b_NOP vs. TOR,matchup_b_NOP vs. UTA,matchup_b_NOP vs. WAS,matchup_b_NYK vs. OKC,matchup_b_NYK vs. ORL,matchup_b_NYK vs. PHI,matchup_b_NYK vs. PHX,matchup_b_NYK vs. POR,matchup_b_NYK vs. SAC,matchup_b_NYK vs. SAS,matchup_b_NYK vs. TOR,matchup_b_NYK vs. UTA,matchup_b_NYK vs. WAS,matchup_b_OKC vs. ORL,matchup_b_OKC vs. PHI,matchup_b_OKC vs. PHX,matchup_b_OKC vs. POR,matchup_b_OKC vs. SAC,matchup_b_OKC vs. SAS,matchup_b_OKC vs. TOR,matchup_b_OKC vs. UTA,matchup_b_OKC vs. WAS,matchup_b_ORL vs. PHI,matchup_b_ORL vs. PHX,matchup_b_ORL vs. POR,matchup_b_ORL vs. SAC,matchup_b_ORL vs. SAS,matchup_b_ORL vs. TOR,matchup_b_ORL vs. UTA,matchup_b_ORL vs. WAS,matchup_b_PHI vs. PHX,matchup_b_PHI vs. POR,matchup_b_PHI vs. SAC,matchup_b_PHI vs. SAS,matchup_b_PHI vs. TOR,match

In [12]:
#cat drop
df_stat_season_matchup_cma12_diff = df_stat_season_matchup_cma12_diff.drop(columns=column_names_categorical_list)
p(df_stat_season_matchup_cma12_diff)

(10266, 142)

,game_id,game_date,season_year,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
0,21000001,2010-10-26,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,-8
1,21000002,2010-10-26,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,14
2,21000003,2010-10-26,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,2
3,21000004,2010-10-27,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,8
4,21000005,2010-10-27,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,3
10261,41700317,2018-05-28,2017,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,7.7,5.3,-7.7,-5.3,24.1,24.6,0.195,0.54,5.2,0.022,-0.080,-0.011,-2.597,-3.6,0.036,0.042,0.0,0.003,0.0,0.0,0.0,-1.0,0.121,0.0,0.000,0.0,1.0,-5.0,0.041,0.0,-12.0,0.148,-5.0,-7.0,0.092593,4.0,2.0,2.0,7.0,-3.0,1.0,-2.0,1.0,-1.0,-19.0,0.0,4.8,4.341667,-1.091667,0.325000,1.858333,0.991667,0.138250,0.127500,5.841667,-0.029333,-0.010333,0.005583,1.6335,1.641667,0.043583,0.035917,0.0,0.00125,1.653333,1.111667,0.925833,-0.916667,0.033583,-2.083333,0.067583,-2.083333,4.916667,-1.416667,0.068167,-4.250000,-13.50,0.036083,-3.416667,-5.333333,0.029458,-1.166667,1.833333,3.000000,8.916667,0.000000,1.750000,1.333333,-1.416667,3.000000,0.00,0.083333,-9
10262,41700401,2018-05-31,2017,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,-14.3,-9.7,14.3,9.7,-21.1,-18.2,-0.200,-0.21,-4.3,0.017,0.054,-0.001,-1.740,-1.8,-0.058,-0.080,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.094,0.0,2.0,9.0,-0.025,3.0,-1.0,0.042,-3.0,-5.0,0.040000,6.0,-6.0,2.0,-7.0,1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-3.650000,-1.950000,-0.059667,-0.265000,-1.658333,-0.028250,0.023667,-0.023000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.461667,-2.125000,-1.770000,-2.666667,-0.051583,-4.166667,-0.078667,-4.166667,-2.666667,-0.833333,-0.008500,3.666667,6.00,0.049583,1.416667,2.250000,-0.010437,0.500000,-3.333333,-2.833333,-4.250000,-0.583333,-4.833333,-2.833333,-1.333333,-2.833333,10.75,0.000000,10
10263,41700402,2018-06-03,2017,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,-8.5,-12.4,8.5,12.4,-21.1,-20.9,-0.200,-2.15,-4.5,0.071,0.126,0.059,-1.740,-1.8,-0.088,-0.104,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-2.0,9.0,-0.054,2.0,0.0,0.042,-3.0,-5.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,-0.000167,-0.009833,0.002167,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,-2.083333,-0.078667,-2.083333,-2.666667,-3.083333,-0.008500,2.583333,2.00,0.049583,1.416667,2.750000,-0.010437,-0.250000,-3.083333,-4.166667,-4.250000,-1.333333,-3.583333,-2.833333,0.666667,-2.833333,10.75,0.000000,19
10264,41700403,2018-06-06,2017,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,0.002667,0.001917,0.007250,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.416667,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,0.500000,-2.833333,10.75,0.000000,8
10265,41700404,2018-06-08,2017,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.341667,-2.608333,-0.059667,-0.098333,-1.658333,0.006750,0.009083,0.011000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.250000,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,-0.083333,-2.833333,10.75,0.000000,23

In [13]:
df_stat_season_matchup_cma12_diff.drop(columns=['game_id', 'game_date'], inplace=True)

In [14]:
df_features = df_stat_season_matchup_cma12_diff.drop(columns='spread_a')
p(df_features)

(10266, 139)

,season_year,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
0,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
1,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
2,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
3,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
4,2010,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
10261,2017,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,7.7,5.3,-7.7,-5.3,24.1,24.6,0.195,0.54,5.2,0.022,-0.080,-0.011,-2.597,-3.6,0.036,0.042,0.0,0.003,0.0,0.0,0.0,-1.0,0.121,0.0,0.000,0.0,1.0,-5.0,0.041,0.0,-12.0,0.148,-5.0,-7.0,0.092593,4.0,2.0,2.0,7.0,-3.0,1.0,-2.0,1.0,-1.0,-19.0,0.0,4.8,4.341667,-1.091667,0.325000,1.858333,0.991667,0.138250,0.127500,5.841667,-0.029333,-0.010333,0.005583,1.6335,1.641667,0.043583,0.035917,0.0,0.00125,1.653333,1.111667,0.925833,-0.916667,0.033583,-2.083333,0.067583,-2.083333,4.916667,-1.416667,0.068167,-4.250000,-13.50,0.036083,-3.416667,-5.333333,0.029458,-1.166667,1.833333,3.000000,8.916667,0.000000,1.750000,1.333333,-1.416667,3.000000,0.00,0.083333
10262,2017,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,-14.3,-9.7,14.3,9.7,-21.1,-18.2,-0.200,-0.21,-4.3,0.017,0.054,-0.001,-1.740,-1.8,-0.058,-0.080,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.094,0.0,2.0,9.0,-0.025,3.0,-1.0,0.042,-3.0,-5.0,0.040000,6.0,-6.0,2.0,-7.0,1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-3.650000,-1.950000,-0.059667,-0.265000,-1.658333,-0.028250,0.023667,-0.023000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.461667,-2.125000,-1.770000,-2.666667,-0.051583,-4.166667,-0.078667,-4.166667,-2.666667,-0.833333,-0.008500,3.666667,6.00,0.049583,1.416667,2.250000,-0.010437,0.500000,-3.333333,-2.833333,-4.250000,-0.583333,-4.833333,-2.833333,-1.333333,-2.833333,10.75,0.000000
10263,2017,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,-8.5,-12.4,8.5,12.4,-21.1,-20.9,-0.200,-2.15,-4.5,0.071,0.126,0.059,-1.740,-1.8,-0.088,-0.104,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-2.0,9.0,-0.054,2.0,0.0,0.042,-3.0,-5.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,-0.000167,-0.009833,0.002167,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,-2.083333,-0.078667,-2.083333,-2.666667,-3.083333,-0.008500,2.583333,2.00,0.049583,1.416667,2.750000,-0.010437,-0.250000,-3.083333,-4.166667,-4.250000,-1.333333,-3.583333,-2.833333,0.666667,-2.833333,10.75,0.000000
10264,2017,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,0.002667,0.001917,0.007250,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.416667,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,0.500000,-2.833333,10.75,0.000000
10265,2017,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.341667,-2.608333,-0.059667,-0.098333,-1.658333,0.006750,0.009083,0.011000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.250000,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,-0.083333,-2.833333,10.75,0.000000

In [15]:
df_target = df_stat_season_matchup_cma12_diff[['spread_a']]
p(df_target)

(10266, 1)

       spread_a
0            -8
1            14
2             2
3             8
4             3
10261        -9
10262        10
10263        19
10264         8
10265        23

In [16]:
scaler = StandardScaler() 
scaler

StandardScaler()

In [17]:
# Fitting data to the scaler object
scaled_df_features = scaler.fit_transform(df_features) 
scaled_df_features

array([[-1.55738154, -0.02327366, -0.01936746, ..., -0.03779848,
         0.02487811,  0.00926609],
       [-1.55738154, -0.02327366, -0.01936746, ..., -0.03779848,
         0.02487811,  0.00926609],
       [-1.55738154, -0.02327366, -0.01936746, ..., -0.03779848,
         0.02487811,  0.00926609],
       ...,
       [ 1.50706227, -0.98376816, -1.05047868, ..., -0.37025826,
         1.56371021,  0.00926609],
       [ 1.50706227, -1.22874276, -1.38912795, ..., -0.37025826,
         1.56371021,  0.00926609],
       [ 1.50706227, -1.23990002, -1.30926738, ..., -0.37025826,
         1.56371021,  0.00926609]])

In [18]:
scaled_df_features = pd.DataFrame(scaled_df_features, columns=df_features.columns)
p(scaled_df_features)

(10266, 139)

,season_year,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
0,-1.557382,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
1,-1.557382,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
2,-1.557382,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
3,-1.557382,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
4,-1.557382,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266
10261,1.507062,0.840201,0.609633,-0.840201,-0.609633,0.840175,0.608484,1.164395,0.907171,1.417319,-0.288811,-0.143012,-0.011805,-0.176285,-0.256164,0.675948,0.768273,0.0,0.943579,0.0,0.0,0.0,0.132146,0.748246,0.0,0.072510,0.0,0.881443,-0.035734,0.905581,-0.370994,-1.434929,0.581158,-0.103748,-0.561630,1.199043,-0.133895,0.171958,0.053459,1.357131,-0.061020,0.920512,0.031533,0.472812,0.620813,-0.620813,-0.179844,0.673034,0.482904,-0.673034,-0.482904,1.143292,1.217268,1.870269,0.645706,1.502512,0.207403,-0.354602,-0.133597,-0.647672,-0.877638,0.486925,0.615574,0.0,1.338612,0.0,0.0,0.0,-1.231547,0.854925,0.0,-0.037072,0.0,0.229841,-0.684975,0.669136,-0.022872,-1.819577,1.340842,-0.881936,-1.013953,0.915199,0.993895,0.369183,0.308449,1.337268,-0.976195,0.394453,-0.523221,0.318642,-0.115415,-0.973938,0.002594,0.569073,0.517499,-0.138970,0.044261,0.202575,0.099402,1.890425,0.297136,2.714383,-0.474334,-0.125273,0.055757,0.817850,0.806375,0.963759,0.784759,-0.008342,0.097182,0.225064,0.140253,0.140141,-0.171040,0.522909,-0.148751,0.232659,-0.148751,1.504447,-0.242662,1.823106,-2.083465,-2.820183,0.713933,-1.012678,-1.254073,0.464261,-0.493600,0.527516,0.701707,2.711386,-0.004867,1.243186,0.644915,-0.450186,0.314218,0.024878,0.499158
10262,1.507062,-1.051682,-0.939280,1.051682,0.939280,-1.046895,-0.939374,-2.606462,-0.952191,-2.483513,0.326985,0.164912,0.012572,-0.487261,-0.426682,-1.436277,-1.449085,0.0,-0.037623,0.0,0.0,0.0,0.691910,-1.530749,0.0,-0.560973,0.0,-0.911040,1.253970,-1.578943,-0.024410,-0.433500,0.104323,-0.134750,-0.055161,-0.206624,1.101403,-1.037052,-0.143490,-2.422656,0.391022,-1.550447,-0.288889,0.080810,-0.916020,0.916020,0.001245,-1.319151,-0.931464,1.319151,0.931464,-1.037826,-0.928042,-1.962345,-0.260237,-1.289491,0.162842,0.285790,0.017690,-0.431195,-0.433663,-0.877342,-1.286772,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-1.518107,0.0,-0.382288,0.0,0.445660,1.395573,-0.453452,0.821732,-0.175494,0.376972,-0.542722,-0.739183,0.403503,1.472307,-1.152155,0.308449,-1.378844,0.354609,-0.658812,-0.261598,-0.176017,-1.008367,0.905832,0.002594,0.182150,0.171594,0.526061,0.470538,-0.527310,-0.308651,-1.020234,-0.891042,-0.918388,-0.455756,0.240855,-0.277735,-0.884331,-0.895547,0.356787,0.297719,-0.008342,-0.054374,-0.409344,-0.369260,-0.369107,-0.443067,-0.923091,-0.293852,-0.351671,-0.293852,-0.831903,-0.147193,-0.242158,1.585399,1.055021,0.979662,0.412951,0.498137,-0.138977,0.255431,-1.115093,-0.701943,-1.476897,-0.356959,-3.229028,-1.337517,-0.419064,-0.370258,1.563710,0.009266
10263,1.507062,-0.983768,-1.050479,0.983768,1.050479,-0.980597,-1.050577,-2.643719,-1.863845,-2.649801,0.879028,0.440957,1.008280,0.045007,0.057948,-1.428425,-1.561262,0.0,0.272231,0.0,0.0,0.0,1.411606,-1.489224,0.0,-1.625597,0.0,-0.757399,1.334021,-1.469152,-0.336335,-0.247394,-0.231105,-0.289764,0.046133,-0.882978,2.071994,-0.694879,0.715924,-2.527327,-0.348684,-1.418074,0.191744,0.080810,-0.968611,0.968611,-0.542023,-0.793939,-1.186050,0.793939,1.186050,-1.037826,-1.063377,-1.962345,-2.603609,-1.348270,0.644108,0.629881,0.925410,-0.431195,-0.433663,-1.312746,-1.661003,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-1.518107,0.0,-1.116792,0.0,-0.417615,1.395573,-0.946710,0.540198,-0.026031,0.376972,-0.542722,-0.739183,-1.055912,1.472307,-0.581653,0.752626,-1.378844,-0.310793,-0.658812,-0.261598,-0.176017,-1.008367,0.905832,0.002594,0.182150,0.171594,0.526061,0.470538,-0.591355,-0.308651,-1.020234,-0.386508,-0.918388,0.025842,-0.119889,0.015893,-0.884331,-0.895547,0.356787,0.297719,-0.008342,-0.054374,-0.418080,-0.546357,-0.546360,-0.533743,-0.882060,-0.148751,-0.351671,-0.148751,-0.831903,-0.515433,-0.242158,1.083343,0.260107,0.979662,0.412951,0.613667,-0.138977,-0.081633,-1.035612,-1.022778,-1.476897,-0.809650,-2.379873,-1.337517,0.327867,-0.370258,1.563710,0.009266
10264,1.507062,-1.228743,-1.389128,1.228743,1.389128,-1.226385,-1.389241,-1.785962,-1.423470,-2.234082,0.865987,0.434436,0.898584,-0.038861,-0.056479,-1.879923,-1.857128,0.0,-0.153817,0.0,0.0,0.0,2.131302,-1.362206,0.0,-2.157909,0.0,-1.141502,1.334021,-1.848845,-0.726242,-0.553140,-0.381555,0.097771,0.210735,-0.281362,2.160229,-0.934400,0.581641,-2.056307,0.298559,-1.451167,-0.000510,-0.597655,-1.231567,1.231567,-0.813658,-1.355373,-1.610361,1.355373,1.610361,-1.317704,-1.624766,-1.273445,-1.951330,-1.289491,0.644108,0.629881,0.925410,-0.431195,-0.433663,-2.502851,-2.300316,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-1.518107,0.0,-1.116792,0.0,-0.633434,1.395573,-2.001262,-0.022872,-0.026031,-0.004939,-0.542722,-0.601798,-1.055912,1.472307,-0.581653,0.752626,-1.378844,-0.310793,-1.009900,-0.261598,-0.670675,-1.008367,1.375775,0.002594,0.182150,0.171594,0.526061,0.470538,-0.591355,-0.308651,-1.020234,-0.386508,-0.918388,0.074431,0.006641,0.075202,-0.884331,-0.895547,0.356787,0.297719,-0.008342,-0.054374,-0.418080,-0.546357,-0.546360,-0.533743,-0.882060,-0.003650,-0.351671,-0.003650,-0.831903,-0.515433,-0.242158,1.006104,0.111061,0.979662,0.412951,0.613667,-0.156992,-0.081633,-0.903143,-0.862360,-1.476897,-0.910248,-2.379873,-1.337517,0.265623,-0.370258,1.563710,0.009266
10265,1.507062,-1.239900,-1.309267,1.239900,1.309267,-1.238027,-1.311399,-1.724488,-1.455918,-2.177960,1.033773,0.518336,1.183795,0.110339,0.117180,-1.792764,-1.836095,0.0,-0.316490,0.0,0.0,0.0,1.987363,-1.297720,0.0,-2.477296,0.0,-1.003225,1.430081,-1.791205,-0.585875,-0.289932,-0.416578,-0.078945,0.096780,-0.485340,2.213171,-0.708566,0.791123,-1.941169,0.243081,-1.232752,0.172518,-0.570516,-1.157940,1.157940,-0.324716,-1.355373,-1.610361,1.355373,1.610361,-1.317704,-1.624766,-1.273445,-1.951330,-1.289491,0.644108,0.629881,0.925410,-0.431195,-0.433663,-2.502851,-2.300316,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-1.518107,0.0,-1.116792,0.0,-0.633434,1.395573,-2.001262,-0.022872,-0.026031,-0.004939,-0.542722,-0.601798,-1.055912,1.472307,-0.581653,0.752626,-1.378844,-0.310793,-1.009900,-0.261598,-0.670675,-1.008367,1.375775,0.002594,0.182150,0.171594,0.526061,0.470538,-0.618960,-0.399972,-1.020234,-0.386508,-0.918388,0.144455,0.083815,0.118955,-0.884331,-0.895547,0.356787,0.297719,-0.008342,-0.054374,-0.418080,-0.546357,-0.546360,-0.533743,-0.882060,-0.003650,-0.351671,-0.003650,-0.831903,-0.515433,-0.242158,0.928865,0.111061,0.979662,0.412951,0.613667,-0.156992,-0.081633,-0.903143,-0.862360,-1.476897,-0.910248,-2.379873,-1.337517,0.047768,-0.370258,1.563710,0.009266

In [19]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df_features, 
                                                    df_target, test_size=0.3, 
                                                    random_state=random_state_2909)

In [20]:
X_train.shape

(7186, 139)

In [21]:
y_train.shape

(7186, 1)

In [22]:
X_test.shape

(3080, 139)

In [23]:
y_test.shape

(3080, 1)

In [24]:
#export dataframes

#https://stackoverflow.com/questions/30829748/multiple-pandas-dataframe-to-one-csv-file

In [25]:
df_train = pd.concat([X_train, y_train], axis=1)
p(df_train)

(7186, 140)

,season_year,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
3134,-0.681826,-4.263032,-4.992963,4.263032,4.992963,-4.272863,-4.993233,-2.596301,-1.585713,-3.855387,-2.659261,3.018823,0.029448,-0.682127,-0.911312,-4.223786,-4.376896,0.0,1.356717,0.0,0.0,0.0,1.411606,-4.469262,0.0,-0.760009,0.0,-3.907047,0.213312,-4.085831,-2.207885,-0.832299,-2.056232,-0.785809,-0.207102,-1.404932,0.571990,-3.911303,-2.721733,-3.992721,2.240288,-1.153329,-0.865649,-0.461962,-4.755181,4.755181,-1.628561,-3.981436,-4.655967,3.981436,4.655967,-4.246772,-4.947991,-2.476594,-1.238655,-3.640650,-2.733670,3.334818,0.032819,-0.619381,-0.828307,-3.910659,-4.062325,0.0,1.338612,0.0,0.0,0.0,1.175509,-4.437082,0.0,-0.753213,0.0,-3.654897,0.206688,-3.804206,-1.993614,-0.773342,-1.896306,-0.712329,-0.189644,-1.350872,0.515483,-3.624329,-2.504673,-3.706941,2.018114,-1.009900,-0.784845,-0.423346,-4.480961,4.717589,-1.661774,-1.468510,-1.269155,-0.204190,-0.284216,-1.358783,-1.107417,-1.452850,-0.406689,-1.761999,2.210899,-0.200653,1.696963,-1.287297,-1.136422,-1.995950,-2.200508,-0.008342,-0.177062,0.210675,0.120576,0.120779,0.217572,-1.111270,0.141450,-0.528802,0.141450,-0.318420,1.516707,-1.773147,-1.195214,-0.369199,-2.022094,-1.086418,-0.483871,-1.234956,1.416430,-0.452751,0.420977,-1.423881,0.850215,0.337421,-1.297868,-0.045599,-0.976508,1.146198,0.499158,22
8383,1.507062,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,21
7423,1.069285,-0.071783,-0.231655,0.071783,0.231655,-0.071828,-0.231718,-0.889254,-0.905836,-1.329892,0.270477,0.136656,0.704505,0.339717,0.300262,-0.878775,0.115779,0.0,2.751056,0.0,0.0,0.0,-0.027786,0.264601,0.0,-0.860457,0.0,-1.602427,-2.188205,-0.188260,-2.831736,-2.108456,-1.927980,3.864612,3.591419,0.888369,-0.222130,0.400073,0.178790,-1.480617,0.391022,0.832263,0.576250,-2.361663,-0.232334,0.232334,1.631052,-0.069508,-0.214851,0.069508,0.214851,-0.067904,-0.226305,-0.846521,-0.707169,-1.260101,0.269790,0.166314,0.637965,0.317760,0.281630,-0.819288,0.101005,0.0,2.716276,0.0,0.0,0.0,-0.028019,0.265306,0.0,-0.852370,0.0,-1.496709,-2.022471,-0.181309,-2.556683,-1.969039,-1.778096,3.527841,3.244978,0.862533,-0.202134,0.369183,0.160390,-1.378844,0.354609,0.745541,0.523272,-2.154651,-0.214632,0.227027,1.666962,0.012612,0.003316,0.193545,0.037883,-0.202671,-0.043937,0.631795,-0.568140,0.163370,-0.994518,0.749666,-0.022998,0.413268,0.395703,0.031142,0.267160,-0.008342,-0.076025,-0.096122,-0.003785,-0.004369,-0.171040,-0.323185,-0.148751,-0.583739,-0.148751,-0.857577,-1.129166,0.029469,-0.268343,-0.319517,-0.086535,1.519042,1.730460,-0.569035,-0.793212,-1.406523,-1.483977,0.007558,0.498122,-0.851395,0.208780,0.296745,-0.116024,0.096452,-0.970517,4
2528,-0.681826,-0.168803,0.597277,0.168803,-0.597277,-0.168850,0.587142,-0.848610,-0.720415,-0.893387,1.174609,0.588760,2.139001,0.474402,0.784892,-0.030744,0.166258,0.0,-0.967182,0.0,0.0,0.0,1.411606,0.572375,0.0,3.685742,0.0,0.010808,-0.106890,0.086217,-0.336335,-0.513260,0.104323,1.446393,1.768129,-0.295599,-0.222130,1.015984,0.662211,-0.643248,-0.718537,0.038026,0.864630,-3.175821,0.714309,-0.714309,1.631052,-0.160061,0.558337,0.160061,-0.558337,-0.164414,0.585705,-0.807709,-0.562218,-0.848648,1.196673,0.663334,1.923903,0.441281,0.725605,-0.035560,0.147784,0.0,-0.957494,0.0,0.0,0.0,1.175509,0.571035,0.0,3.635445,0.0,0.014022,-0.090533,0.073825,-0.304406,-0.474418,0.095085,1.322953,1.596360,-0.280187,-0.202134,0.939685,0.604567,-0.602812,-0.643494,0.043364,0.784896,-2.896638,0.678321,-0.712859,1.666962,-11.675148,-12.077372,-12.149096,-12.613281,0.141843,0.267016,-8.157781,-5.537802,-6.944753,0.028700,-7.358110,-0.009386,-5.116376,-5.183917,-9.200606,-10.191776,-17.135358,-17.418394,-14.629691,-14.359884,-14.359177,-14.174002,-7.789471,-16.719248,-0.037365,-16.719249,-10.177303,-14.904070,-9.791757,-2.894477,-3.515733,-6.944644,-4.724229,-4.411900,-12.714182,-6.710558,-8.639299,-10.126453,-5.850737,-7.247912,-5.380219,-4.747300,-6.643490,-10.363608,-0.261416,-5.869434,-6
10064,0.631507,-1.248147,-0.964553,1.248147,0.964553,-1.245789,-0.967175,0.142086,-0.789947,-0.441293,-0.101174,-0.049185,-0.637171,0.325532,0.434882,-1.090783,-1.057869,0.0,-0.502402,0.0,0.0,0.0,-1.467179,-1.091072,0.0,-1.343165,0.0,-0.853425,0.293363,-0.979668,-0.804223,-0.234101,-0.679988,-0.041742,-0.207102,-0.095543,0.108753,-1.242356,-0.908906,-0.381571,-0.163757,0.038026,0.359965,0.623582,-1.073794,1.073794,-0.813658,-1.400650,-1.054043,1.400650,1.054043,-1.071605,-0.772657,-0.429299,-1.878855,-1.113154,0.260877,-0.220789,-0.284884,-0.022996,0.084308,-0.819288,-1.395922,0.0,-0.957494,0.0,0.0,0.0,-0.028019,-0.913930,0.0,-1.506078,0.0,-0.417615,-0.387754,-0.606532,-1.149010,-0.623880,-0.832412,0.474919,-0.739183,-0.135358,0.993895,-0.581653,-1.320200,-0.408804,0.354609,0.043364,0.000025,1.060630,-0.214632,0.905832,0.002594,-0.676984,-0.678105,-0.796518,-0.811481,0.010442,-0.010414,0.335214,0.713376,0.312718,-0.910203,0.085609,-0.668591,0.119787,0.162725,-0.496827,-0.479634,-0.008342,0.003362,0.907265,0.809809,0.809955,0.774581,0.039022,-0.003650,-0.252452,-0.003650,0.143715,0.411987,-0.165833,-0.809018,-0.634171,-0.841075,-0.299864,-0.868972,0.657172,-1.017921,0.712971,-0.040222,0.431688,1.906492,2.262171,0.327726,0.047768,-0.076911,0.370817,0.989049,25
3378,-0.681826,-0.828537,-0.656230,0.828537,0.656230,-0.828596,-0.656311,-0.198307,-0.195055,-0.176272,0.513897,0.258376,0.670752,0.491203,0.623349,-0.030744,-0.843331,0.0,1.356717,0.0,0.0,0.0,-1.467179,-1.494110,0.0,-1.481746,0.0,0.241270,0.853717,-0.243155,0.599440,-0.194221,1.623618,-2.087927,-0.966806,-2.044703,0.836696,-0.215838,0.339931,-0.015222,-1.088390,-0.756210,0.576250,0.623582,-0.758246,0.758246,1.631052,-0.775828,-0.610874,0.775828,0.610874,-0.820679,-0.647347,-0.186729,-0.151524,-0.172690,0.519335,0.300127,0.607708,0.456689,0.577613,-0.035560,-0.787796,0.0,1.338612,0.0,0.0,0.0,-1.231547,-1.481711,0.0,-1.465681,0.0,0.229841,0.801131,-0.232336,0.540198,-0.175494,1.495425,-1.899576,-0.876568,-1.968354,0.754689,-0.201319,0.308449,-0.020788,-0.976195,-0.658812,0.523272,0.565971,-0.710717,0.749185,1.666962,-0.626241,-1.042485,0.556456,0.531510,-1.252069,-1.746579,-1.239693,-1.151057,-1.265520,-0.776992,1.300141,1.028382,0.286878,0.099544,-0.627855,-0.690821,-0.008342,-0.086850,-0.039025,0.191939,0.192235,0.365614,-0.825566,0.245094,-0.646810,0.245094,-0.406445,0.053489,-0.524528,-0.618678,0.217523,-1.811080,-0.357802,-0.083641,-0.842181,0.480141,-0.072377,0.207565,-1.272406,0.016690,1.849725,-0.014952,-0.181202,-0.607730,1.737532,0.429173,19
1965,-1.119604,-1.701714,-1.788431,1.701714,1.788431,-1.692089,-1.788561,0.106523,-2.744595,-0.768671,1.070286,0.540942,1.514573,1.483575,1.457988,-1.506946,-1.634177,0.0,-0.967182,0.0,0.0,0.0,1.411606,-1.288927,0.0,-1.128318,0.0,-0.911040,0.853717,-1.377660,-0.960185,-0.034701,-2.125290,-0.785809,-0.814865,-0.057660,1.895523,1.015984,1.951332,-0.433906,-0.348684,-0.756210,1.441390,0.894967,-1.599706,1.599706,1.631052,-1.590813,-1.666936,1.590813,1.666936,-1.679615,-1.770126,0.104356,-2.144598,-0.731090,1.089725,0.610764,1.364142,1.366803,1.342237,-1.399827,-1.520666,0.0,-0.957494,0.0,0.0,0.0,1.175509,-1.277892,0.0,-1.116792,0.0,-0.849253,0.801131,-1.286888,-0.867475,-0.026031,-1.959958,-0.712329,-0.739183,-0.050537,1.711513,0.939685,1.789040,-0.408804,-0.310793,-0.658812,1.308143,0.813300,-1.504452,1.584638,1.666962,-0.526167,-0.394526,0.853231,0.986109,-1.446016,-1.518938,-0.473643,-4.932361,-1.374503,2.626760,0.161886,2.270607,3.528192,3.538928,-0.188524,0.064704,-0.008342,-0.018289,0.868722,0.730968,0.730931,0.722767,-1.572518,-0.003650,-1.217679,-0.003650,-0.600836,-0.215385,-0.343176,0.272331,0.624443,-0.788585,1.519042,1.653439,0.293752,1.566236,-0.982624,0.100143,-0.681654,0.196329,0.167590,3.301374,1.230409,0.216435,1.444421,-1.460409,18
1161,-1.557382,-1.168105,-1.212222,1.168105,1.212222,-1.168172,-1.215697,-0.940059,-1.101558,-0.591991,-0.659737,1.120563,0.456984,0.982018,1.000283,-0.774080,-0.882593,0.0,-0.192549,0.0,0.0,0.0,0.931809,-1.088629,0.0,-1.311852,0.0,0.318091,0.693616,-0.151663,-1.791985,-2.640188,-0.517206,-1.281854,-1.827804,1.095440,0.395518,-0.010534,0.232504,-0.503687,0.144454,-1.020956,1.153010,2.251897,-1.038733,1.038733,-0.542023,-1.273875,-1.591503,1.273875,1.591503,-1.004048,-1.133550,-0.468111,-1.588953,-0.554753,-0.229301,0.070733,0.607708,0.828262,0.898262,-1.022476,-0.943726,0.0,0.420170,0.0,0.0,0.0,2.379036,-1.168704,0.0,-1.355505,0.0,0.229841,0.503909,-0.623541,-1.149010,-2.417425,0.386065,-1.221149,-1.975647,0.751404,0.993895,0.559350,0.308449,-0.602812,0.687310,0.043364,0.784896,1.802617,-1.206801,0.905832,0.002594,-0.349348,-0.230403,0.797420,0.766061,-1.953954,-1.731634,0.840872,0.897531,0.470138,-1.881688,0.473275,-0.367379,1.889567,1.743815,-0.453664,-0.038434,-0.008342,-0.089015,-0.684793,-0.618507,-0.618615,-0.676234,-1.784749,-0.438953,-1.232995,-0.438952,-0.626510,-1.006419,0.081101,-1.782232,-2.171004,-0.119341,0.044254,-0.907482,1.356198,-1.467340,-2.360296,-2.306115,-0.151491,-1.191922,-0.353225,1.128629,-0.014477,-0.820057,1.411020,-0.970517,9
2771,-0.681826,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,18
9937,-0.244048,-1.182658,-1.306572,1.182658,1.306572,-1.182725,-1.304996,-1.456576,-0.990820,-1.428626,-1.177005,1.586434,-0.639983,0.565477,0.538090,-0.708645,-0.770417,0.0,-0.657329,0.0,0.0,0.0,0.931809,-1.293812,0.0,-1.191563,0.0,-0.642168,-0.080206,-0.685368,-0.388323,-0.406914,-0.129161,-0.785809,-0.916159,0.321963,-0.354484,-0.694879,-0.761194,-1.445726,-0.040473,-0.359092,0.383997,1.166353,-1.161446,1.161446,0.001245,-0.304948,-0.610874,0.304948,0.610874,-0.675915,-0.797719,-0.167323,-0.441425,-0.202079,-0.327337,-0.063080,-1.767493,-0.294034,-0.162345,-0.746720,-0.491529,0.0,0.420170,0.0,0.0,0.0,1.175509,-1.037677,0.0,-1.032324,0.0,0.661478,-0.387754,-0.249345,-0.304406,0.422355,-0.405036,-1.221149,-1.151338,1.024690,-0.919752,-0.771820,-1.024082,-0.408804,0.687310,0.043364,-0.523221,0.318642,0.182236,0.644753,0.002594,0.208153,0.285857,1.013608,0.930831,-0.568166,-0.478577,-1.186907,-0.868338,-1.330102,-0.868759,-0.180911,-0.070640,-0.365009,-0.326923,-0.175035,-0.059443,-0.008342,-0.097676,-0.775882,-0.699316,-0.699370,-0.805771,-0.467502,0.141450,-0.424921,0.141450,-0.369768,-1.306467,-0.181547,-0.229724,0.028258,-1.197021,-0.250704,0.305586,-0.971011,-0.568503,-1.830422,-1.423821,-1.503405,0.649019,-0.738175,-0.663490,0.545722,-0.370258,0.466249,-1.460409,17

In [26]:
df_test = pd.concat([X_test, y_test], axis=1)
p(df_test)

(3080, 140)

,season_year,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
2583,-0.681826,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,1
9370,1.507062,-0.537478,-0.666339,0.537478,0.666339,-0.547234,-0.666421,-0.096697,-1.075805,-0.269808,-0.520640,-0.258936,-0.578103,1.258274,1.215674,-0.062153,0.183085,0.0,1.821496,0.0,0.0,0.0,-1.467179,-0.570787,0.0,-0.034551,0.0,-0.680578,-0.907396,-0.041872,-0.336335,0.603377,-1.207795,-0.041742,-0.662924,1.392031,-0.486837,0.605377,0.178790,-0.433906,-0.348684,-1.550447,1.441390,1.709125,-0.758246,0.758246,-1.628561,-0.504166,-0.620303,0.504166,0.620303,-0.540801,-0.657372,-0.089701,-0.840040,-0.260858,-0.541233,-0.268579,-0.511814,1.160177,1.120250,-0.064587,0.163377,0.0,1.797834,0.0,0.0,0.0,-1.231547,-0.564527,0.0,-0.037072,0.0,-0.633434,-0.833586,-0.045238,-0.304406,0.571817,-1.114299,-0.033902,-0.601798,1.348648,-0.441340,0.559350,0.160390,-0.408804,-0.310793,-1.360988,1.308143,1.555288,-0.710717,0.749185,-1.661774,-0.266139,-0.251178,-0.659662,-0.615883,0.389187,0.382611,-1.125630,-0.373895,-1.544032,0.250207,-0.032844,0.090759,-0.440289,-0.441438,-0.824398,-0.435705,-0.008342,-0.039940,-0.182457,-0.224959,-0.225384,-0.158086,0.389911,-0.003650,0.679813,-0.003650,-1.165667,-0.338132,-0.917858,-0.268343,0.376032,-0.759060,1.469882,1.383869,0.130241,0.217980,0.209591,0.280612,-1.609438,0.196329,0.733693,-0.425598,-0.201209,-0.370258,-0.464208,0.009266,18
5655,0.193729,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,16
7258,1.069285,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,-10
2386,-0.681826,-1.313635,-1.060588,1.313635,1.060588,-1.313704,-1.060686,0.269099,-1.616617,-0.051556,2.626438,-3.032424,0.029448,2.885512,3.046496,-0.140674,-0.035660,0.0,-1.431962,0.0,0.0,0.0,-0.027786,-0.966496,0.0,-1.273409,0.0,-0.450116,-0.427092,-0.206559,-0.024410,0.922416,-0.773710,-1.157843,-2.334273,1.878037,-0.486837,1.837198,1.145631,-0.015222,-2.937656,-0.359092,3.171670,1.980511,-1.073794,1.073794,-1.628561,-1.228598,-0.988039,1.228598,0.988039,-1.303228,-1.048339,0.259601,-1.262814,-0.055132,2.685035,-3.317608,0.032819,2.652530,2.797489,-0.137154,-0.039332,0.0,-1.416715,0.0,0.0,0.0,-0.028019,-0.957606,0.0,-1.260020,0.0,-0.417615,-0.387754,-0.198318,-0.022872,0.870741,-0.714202,-1.051542,-2.113032,1.817722,-0.441340,1.700354,1.048744,-0.020788,-2.639701,-0.307724,2.877884,1.802617,-1.008367,1.062480,-1.661774,-0.402810,-0.003747,1.424388,1.513161,-1.906694,-1.658347,-0.422170,-0.980849,0.091522,-0.480051,-0.951576,-0.723427,0.667273,0.830858,0.302834,0.172426,-0.008342,-0.063034,0.739785,0.468997,0.469239,0.479237,-1.238042,-0.003650,-1.062590,-0.003650,1.098795,0.109212,1.103855,-2.122085,-2.336611,0.472152,0.250724,0.917897,-1.640045,-0.598464,0.410943,-0.004129,0.383973,-1.131563,1.594169,1.342731,2.792739,0.400266,1.532695,-0.382647,-3
8109,1.069285,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,9
9743,-1.119604,-1.104073,-1.024195,1.104073,1.024195,-1.106078,-1.024293,-0.293820,-1.455918,-0.693842,-0.345029,1.567741,0.657251,0.827778,0.881818,-1.010691,-0.991405,0.0,-0.595358,0.0,0.0,0.0,-1.179300,-0.975290,0.0,-1.155848,0.0,-0.772763,0.245333,-0.901900,-0.710645,-0.800395,-0.475771,-0.116149,-0.055161,0.226144,0.995520,-0.174777,0.468843,-0.475775,-0.792508,-1.788718,0.460898,-0.570516,-1.010684,1.010684,-0.324716,-2.686515,-2.628706,2.686515,2.628706,-1.037826,-1.223774,0.094653,-3.630345,-0.231469,-0.068879,0.816263,0.789252,0.351861,0.700940,-1.443367,-1.707782,0.0,-0.039051,0.0,0.0,0.0,-1.231547,-0.877534,0.0,-1.392230,0.0,-0.633434,0.801131,-1.695102,-0.304406,-1.371190,0.186016,0.474919,1.458975,0.709285,1.472307,0.369183,1.937099,0.561236,-0.310793,-0.658812,-0.523221,-1.412663,-0.512283,1.114696,0.002594,-0.668663,-0.578385,0.929143,0.761809,-0.824344,-0.862355,1.804637,0.667968,1.172474,0.627483,0.160092,-0.219398,-0.288879,-0.394052,-1.136555,-0.869266,-0.008342,-0.011072,-0.491310,-0.397202,-0.397442,-0.261715,-0.354312,0.141450,-0.648332,0.141450,-0.575161,0.821142,-0.796636,-1.079355,-0.733535,-0.937853,-0.029486,0.305586,-0.738472,1.828397,0.659984,0.962385,1.279947,-1.010846,-0.908006,-0.504896,-2.193025,-0.780944,1.372847,-1.460409,-3
4546,-0.244048,2.159668,2.285469,-2.159668,-2.285469,2.149966,2.285517,1.793248,1.365573,2.162149,-2.833133,2.931880,0.029448,-0.697000,-0.722845,1.885177,1.747949,0.0,-1.896741,0.0,0.0,0.0,-1.467179,1.920720,0.0,0.910403,0.0,1.854505,-0.427092,1.787973,1.223290,1.560495,-0.004198,0.516309,1.160366,-1.390151,-0.222130,-0.010534,-0.143490,2.287540,1.130729,0.435145,-0.577269,-0.733348,2.397229,-2.397229,-1.628561,2.013232,2.133000,-2.013232,-2.133000,2.142167,2.269873,1.715024,1.068480,2.031523,-2.911917,3.239237,0.032819,-0.633022,-0.655650,1.735085,1.613526,0.0,-1.875936,0.0,0.0,0.0,-1.231547,1.910415,0.0,0.895747,0.0,1.740572,-0.387754,1.655653,1.103267,1.468590,-0.004939,0.474919,1.046820,-1.336606,-0.202134,-0.011151,-0.135728,2.113301,1.020011,0.394453,-0.523221,-0.670675,2.265792,-2.383766,-1.661774,-0.024832,-0.190930,-1.574882,-1.437608,1.591676,1.344368,0.433257,0.834465,0.147225,0.313086,-0.323593,0.329939,-0.940408,-0.986369,-0.789714,-0.475814,-0.008342,0.053881,0.537386,0.525930,0.525816,0.282340,0.998306,-0.293852,0.814992,-0.293852,-0.138700,0.439264,-0.533989,-0.963496,-0.899142,-0.283372,1.052026,0.632922,0.981265,0.592495,0.898427,1.002489,0.219623,0.598720,1.639458,-0.623841,-0.170087,0.069762,-1.335020,0.989049,5
4962,0.193729,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,12
5706,0.193729,-2.099494,-2.233224,2.099494,2.233224,-2.099579,-2.233374,-0.299917,-0.612252,-0.831029,-0.355461,-0.176340,-1.151902,0.336411,0.327186,-1.585467,-2.004360,0.0,0.427157,0.0,0.0,0.0,-1.467179,-2.241562,0.0,-1.760768,0.0,-1.141502,0.373414,-1.267869,-1.584035,-1.310858,-0.892097,-1.343860,-0.814865,-1.670562,0.571990,-1.037052,-0.465770,-0.852590,-1.458244,0.038026,0.287870,2.794669,-2.335983,2.335983,1.631052,-1.962084,-2.081817,1.962084,2.081817,-2.084956,-2.211217,-0.283757,-0.477663,-0.789869,-0.371899,-0.177777,-1.026188,0.314729,0.306295,-1.472394,-1.863712,0.0,0.420170,0.0,0.0,0.0,-1.231547,-2.224193,0.0,-1.741119,0.0,-1.065072,0.355299,-1.184834,-1.430545,-1.221728,-0.823319,-1.221149,-0.739183,-1.607247,0.515483,-0.961988,-0.431846,-0.796820,-1.308897,0.043364,0.261649,2.544605,-2.198971,2.315660,1.666962,-0.169408,-0.152497,1.558891,1.466600,-1.801573,-1.773249,-0.509183,-0.373895,-0.284671,1.034770,0.877991,1.794190,-0.153439,-0.137382,-0.250184,-0.401326,-0.008342,0.075532,0.555244,0.627728,0.627508,0.632091,-1.166450,-0.003650,-0.926014,-0.003650,0.811244,1.080274,-0.102977,-0.345582,0.376032,-0.921450,-0.422763,-0.291320,-0.347343,1.004462,-0.770675,-0.040222,0.166606,-0.256362,-1.304278,0.288077,0.670210,0.363109,1.742644,0.989049,12

In [27]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '158C_train_split.csv')
if not os.path.exists(datapath_df):
    df_train.to_csv(datapath_df, index=True)

In [28]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '158C_test_split.csv')
if not os.path.exists(datapath_df):
    df_test.to_csv(datapath_df, index=True)

In [29]:
df_train_readback = rcp('158C_train_split.csv', None, 0)
p(df_train_readback)

(7186, 140)

,season_year,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
3134,-0.681826,-4.263032,-4.992963,4.263032,4.992963,-4.272863,-4.993233,-2.596301,-1.585713,-3.855387,-2.659261,3.018823,0.029448,-0.682127,-0.911312,-4.223786,-4.376896,0.0,1.356717,0.0,0.0,0.0,1.411606,-4.469262,0.0,-0.760009,0.0,-3.907047,0.213312,-4.085831,-2.207885,-0.832299,-2.056232,-0.785809,-0.207102,-1.404932,0.571990,-3.911303,-2.721733,-3.992721,2.240288,-1.153329,-0.865649,-0.461962,-4.755181,4.755181,-1.628561,-3.981436,-4.655967,3.981436,4.655967,-4.246772,-4.947991,-2.476594,-1.238655,-3.640650,-2.733670,3.334818,0.032819,-0.619381,-0.828307,-3.910659,-4.062325,0.0,1.338612,0.0,0.0,0.0,1.175509,-4.437082,0.0,-0.753213,0.0,-3.654897,0.206688,-3.804206,-1.993614,-0.773342,-1.896306,-0.712329,-0.189644,-1.350872,0.515483,-3.624329,-2.504673,-3.706941,2.018114,-1.009900,-0.784845,-0.423346,-4.480961,4.717589,-1.661774,-1.468510,-1.269155,-0.204190,-0.284216,-1.358783,-1.107417,-1.452850,-0.406689,-1.761999,2.210899,-0.200653,1.696963,-1.287297,-1.136422,-1.995950,-2.200508,-0.008342,-0.177062,0.210675,0.120576,0.120779,0.217572,-1.111270,0.141450,-0.528802,0.141450,-0.318420,1.516707,-1.773147,-1.195214,-0.369199,-2.022094,-1.086418,-0.483871,-1.234956,1.416430,-0.452751,0.420977,-1.423881,0.850215,0.337421,-1.297868,-0.045599,-0.976508,1.146198,0.499158,22
8383,1.507062,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,21
7423,1.069285,-0.071783,-0.231655,0.071783,0.231655,-0.071828,-0.231718,-0.889254,-0.905836,-1.329892,0.270477,0.136656,0.704505,0.339717,0.300262,-0.878775,0.115779,0.0,2.751056,0.0,0.0,0.0,-0.027786,0.264601,0.0,-0.860457,0.0,-1.602427,-2.188205,-0.188260,-2.831736,-2.108456,-1.927980,3.864612,3.591419,0.888369,-0.222130,0.400073,0.178790,-1.480617,0.391022,0.832263,0.576250,-2.361663,-0.232334,0.232334,1.631052,-0.069508,-0.214851,0.069508,0.214851,-0.067904,-0.226305,-0.846521,-0.707169,-1.260101,0.269790,0.166314,0.637965,0.317760,0.281630,-0.819288,0.101005,0.0,2.716276,0.0,0.0,0.0,-0.028019,0.265306,0.0,-0.852370,0.0,-1.496709,-2.022471,-0.181309,-2.556683,-1.969039,-1.778096,3.527841,3.244978,0.862533,-0.202134,0.369183,0.160390,-1.378844,0.354609,0.745541,0.523272,-2.154651,-0.214632,0.227027,1.666962,0.012612,0.003316,0.193545,0.037883,-0.202671,-0.043937,0.631795,-0.568140,0.163370,-0.994518,0.749666,-0.022998,0.413268,0.395703,0.031142,0.267160,-0.008342,-0.076025,-0.096122,-0.003785,-0.004369,-0.171040,-0.323185,-0.148751,-0.583739,-0.148751,-0.857577,-1.129166,0.029469,-0.268343,-0.319517,-0.086535,1.519042,1.730460,-0.569035,-0.793212,-1.406523,-1.483977,0.007558,0.498122,-0.851395,0.208780,0.296745,-0.116024,0.096452,-0.970517,4
2528,-0.681826,-0.168803,0.597277,0.168803,-0.597277,-0.168850,0.587142,-0.848610,-0.720415,-0.893387,1.174609,0.588760,2.139001,0.474402,0.784892,-0.030744,0.166258,0.0,-0.967182,0.0,0.0,0.0,1.411606,0.572375,0.0,3.685742,0.0,0.010808,-0.106890,0.086217,-0.336335,-0.513260,0.104323,1.446393,1.768129,-0.295599,-0.222130,1.015984,0.662211,-0.643248,-0.718537,0.038026,0.864630,-3.175821,0.714309,-0.714309,1.631052,-0.160061,0.558337,0.160061,-0.558337,-0.164414,0.585705,-0.807709,-0.562218,-0.848648,1.196673,0.663334,1.923903,0.441281,0.725605,-0.035560,0.147784,0.0,-0.957494,0.0,0.0,0.0,1.175509,0.571035,0.0,3.635445,0.0,0.014022,-0.090533,0.073825,-0.304406,-0.474418,0.095085,1.322953,1.596360,-0.280187,-0.202134,0.939685,0.604567,-0.602812,-0.643494,0.043364,0.784896,-2.896638,0.678321,-0.712859,1.666962,-11.675148,-12.077372,-12.149096,-12.613281,0.141843,0.267016,-8.157781,-5.537802,-6.944753,0.028700,-7.358110,-0.009386,-5.116376,-5.183917,-9.200606,-10.191776,-17.135358,-17.418394,-14.629691,-14.359884,-14.359177,-14.174002,-7.789471,-16.719248,-0.037365,-16.719249,-10.177303,-14.904070,-9.791757,-2.894477,-3.515733,-6.944644,-4.724229,-4.411900,-12.714182,-6.710558,-8.639299,-10.126453,-5.850737,-7.247912,-5.380219,-4.747300,-6.643490,-10.363608,-0.261416,-5.869434,-6
10064,0.631507,-1.248147,-0.964553,1.248147,0.964553,-1.245789,-0.967175,0.142086,-0.789947,-0.441293,-0.101174,-0.049185,-0.637171,0.325532,0.434882,-1.090783,-1.057869,0.0,-0.502402,0.0,0.0,0.0,-1.467179,-1.091072,0.0,-1.343165,0.0,-0.853425,0.293363,-0.979668,-0.804223,-0.234101,-0.679988,-0.041742,-0.207102,-0.095543,0.108753,-1.242356,-0.908906,-0.381571,-0.163757,0.038026,0.359965,0.623582,-1.073794,1.073794,-0.813658,-1.400650,-1.054043,1.400650,1.054043,-1.071605,-0.772657,-0.429299,-1.878855,-1.113154,0.260877,-0.220789,-0.284884,-0.022996,0.084308,-0.819288,-1.395922,0.0,-0.957494,0.0,0.0,0.0,-0.028019,-0.913930,0.0,-1.506078,0.0,-0.417615,-0.387754,-0.606532,-1.149010,-0.623880,-0.832412,0.474919,-0.739183,-0.135358,0.993895,-0.581653,-1.320200,-0.408804,0.354609,0.043364,0.000025,1.060630,-0.214632,0.905832,0.002594,-0.676984,-0.678105,-0.796518,-0.811481,0.010442,-0.010414,0.335214,0.713376,0.312718,-0.910203,0.085609,-0.668591,0.119787,0.162725,-0.496827,-0.479634,-0.008342,0.003362,0.907265,0.809809,0.809955,0.774581,0.039022,-0.003650,-0.252452,-0.003650,0.143715,0.411987,-0.165833,-0.809018,-0.634171,-0.841075,-0.299864,-0.868972,0.657172,-1.017921,0.712971,-0.040222,0.431688,1.906492,2.262171,0.327726,0.047768,-0.076911,0.370817,0.989049,25
3378,-0.681826,-0.828537,-0.656230,0.828537,0.656230,-0.828596,-0.656311,-0.198307,-0.195055,-0.176272,0.513897,0.258376,0.670752,0.491203,0.623349,-0.030744,-0.843331,0.0,1.356717,0.0,0.0,0.0,-1.467179,-1.494110,0.0,-1.481746,0.0,0.241270,0.853717,-0.243155,0.599440,-0.194221,1.623618,-2.087927,-0.966806,-2.044703,0.836696,-0.215838,0.339931,-0.015222,-1.088390,-0.756210,0.576250,0.623582,-0.758246,0.758246,1.631052,-0.775828,-0.610874,0.775828,0.610874,-0.820679,-0.647347,-0.186729,-0.151524,-0.172690,0.519335,0.300127,0.607708,0.456689,0.577613,-0.035560,-0.787796,0.0,1.338612,0.0,0.0,0.0,-1.231547,-1.481711,0.0,-1.465681,0.0,0.229841,0.801131,-0.232336,0.540198,-0.175494,1.495425,-1.899576,-0.876568,-1.968354,0.754689,-0.201319,0.308449,-0.020788,-0.976195,-0.658812,0.523272,0.565971,-0.710717,0.749185,1.666962,-0.626241,-1.042485,0.556456,0.531510,-1.252069,-1.746579,-1.239693,-1.151057,-1.265520,-0.776992,1.300141,1.028382,0.286878,0.099544,-0.627855,-0.690821,-0.008342,-0.086850,-0.039025,0.191939,0.192235,0.365614,-0.825566,0.245094,-0.646810,0.245094,-0.406445,0.053489,-0.524528,-0.618678,0.217523,-1.811080,-0.357802,-0.083641,-0.842181,0.480141,-0.072377,0.207565,-1.272406,0.016690,1.849725,-0.014952,-0.181202,-0.607730,1.737532,0.429173,19
1965,-1.119604,-1.701714,-1.788431,1.701714,1.788431,-1.692089,-1.788561,0.106523,-2.744595,-0.768671,1.070286,0.540942,1.514573,1.483575,1.457988,-1.506946,-1.634177,0.0,-0.967182,0.0,0.0,0.0,1.411606,-1.288927,0.0,-1.128318,0.0,-0.911040,0.853717,-1.377660,-0.960185,-0.034701,-2.125290,-0.785809,-0.814865,-0.057660,1.895523,1.015984,1.951332,-0.433906,-0.348684,-0.756210,1.441390,0.894967,-1.599706,1.599706,1.631052,-1.590813,-1.666936,1.590813,1.666936,-1.679615,-1.770126,0.104356,-2.144598,-0.731090,1.089725,0.610764,1.364142,1.366803,1.342237,-1.399827,-1.520666,0.0,-0.957494,0.0,0.0,0.0,1.175509,-1.277892,0.0,-1.116792,0.0,-0.849253,0.801131,-1.286888,-0.867475,-0.026031,-1.959958,-0.712329,-0.739183,-0.050537,1.711513,0.939685,1.789040,-0.408804,-0.310793,-0.658812,1.308143,0.813300,-1.504452,1.584638,1.666962,-0.526167,-0.394526,0.853231,0.986109,-1.446016,-1.518938,-0.473643,-4.932361,-1.374503,2.626760,0.161886,2.270607,3.528192,3.538928,-0.188524,0.064704,-0.008342,-0.018289,0.868722,0.730968,0.730931,0.722767,-1.572518,-0.003650,-1.217679,-0.003650,-0.600836,-0.215385,-0.343176,0.272331,0.624443,-0.788585,1.519042,1.653439,0.293752,1.566236,-0.982624,0.100143,-0.681654,0.196329,0.167590,3.301374,1.230409,0.216435,1.444421,-1.460409,18
1161,-1.557382,-1.168105,-1.212222,1.168105,1.212222,-1.168172,-1.215697,-0.940059,-1.101558,-0.591991,-0.659737,1.120563,0.456984,0.982018,1.000283,-0.774080,-0.882593,0.0,-0.192549,0.0,0.0,0.0,0.931809,-1.088629,0.0,-1.311852,0.0,0.318091,0.693616,-0.151663,-1.791985,-2.640188,-0.517206,-1.281854,-1.827804,1.095440,0.395518,-0.010534,0.232504,-0.503687,0.144454,-1.020956,1.153010,2.251897,-1.038733,1.038733,-0.542023,-1.273875,-1.591503,1.273875,1.591503,-1.004048,-1.133550,-0.468111,-1.588953,-0.554753,-0.229301,0.070733,0.607708,0.828262,0.898262,-1.022476,-0.943726,0.0,0.420170,0.0,0.0,0.0,2.379036,-1.168704,0.0,-1.355505,0.0,0.229841,0.503909,-0.623541,-1.149010,-2.417425,0.386065,-1.221149,-1.975647,0.751404,0.993895,0.559350,0.308449,-0.602812,0.687310,0.043364,0.784896,1.802617,-1.206801,0.905832,0.002594,-0.349348,-0.230403,0.797420,0.766061,-1.953954,-1.731634,0.840872,0.897531,0.470138,-1.881688,0.473275,-0.367379,1.889567,1.743815,-0.453664,-0.038434,-0.008342,-0.089015,-0.684793,-0.618507,-0.618615,-0.676234,-1.784749,-0.438953,-1.232995,-0.438952,-0.626510,-1.006419,0.081101,-1.782232,-2.171004,-0.119341,0.044254,-0.907482,1.356198,-1.467340,-2.360296,-2.306115,-0.151491,-1.191922,-0.353225,1.128629,-0.014477,-0.820057,1.411020,-0.970517,9
2771,-0.681826,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,18
9937,-0.244048,-1.182658,-1.306572,1.182658,1.306572,-1.182725,-1.304996,-1.456576,-0.990820,-1.428626,-1.177005,1.586434,-0.639983,0.565477,0.538090,-0.708645,-0.770417,0.0,-0.657329,0.0,0.0,0.0,0.931809,-1.293812,0.0,-1.191563,0.0,-0.642168,-0.080206,-0.685368,-0.388323,-0.406914,-0.129161,-0.785809,-0.916159,0.321963,-0.354484,-0.694879,-0.761194,-1.445726,-0.040473,-0.359092,0.383997,1.166353,-1.161446,1.161446,0.001245,-0.304948,-0.610874,0.304948,0.610874,-0.675915,-0.797719,-0.167323,-0.441425,-0.202079,-0.327337,-0.063080,-1.767493,-0.294034,-0.162345,-0.746720,-0.491529,0.0,0.420170,0.0,0.0,0.0,1.175509,-1.037677,0.0,-1.032324,0.0,0.661478,-0.387754,-0.249345,-0.304406,0.422355,-0.405036,-1.221149,-1.151338,1.024690,-0.919752,-0.771820,-1.024082,-0.408804,0.687310,0.043364,-0.523221,0.318642,0.182236,0.644753,0.002594,0.208153,0.285857,1.013608,0.930831,-0.568166,-0.478577,-1.186907,-0.868338,-1.330102,-0.868759,-0.180911,-0.070640,-0.365009,-0.326923,-0.175035,-0.059443,-0.008342,-0.097676,-0.775882,-0.699316,-0.699370,-0.805771,-0.467502,0.141450,-0.424921,0.141450,-0.369768,-1.306467,-0.181547,-0.229724,0.028258,-1.197021,-0.250704,0.305586,-0.971011,-0.568503,-1.830422,-1.423821,-1.503405,0.649019,-0.738175,-0.663490,0.545722,-0.370258,0.466249,-1.460409,17

In [30]:
df_test_readback = rcp('158C_test_split.csv', None, 0)
p(df_test_readback)

(3080, 140)

,season_year,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff,spread_a
2583,-0.681826,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,1
9370,1.507062,-0.537478,-0.666339,0.537478,0.666339,-0.547234,-0.666421,-0.096697,-1.075805,-0.269808,-0.520640,-0.258936,-0.578103,1.258274,1.215674,-0.062153,0.183085,0.0,1.821496,0.0,0.0,0.0,-1.467179,-0.570787,0.0,-0.034551,0.0,-0.680578,-0.907396,-0.041872,-0.336335,0.603377,-1.207795,-0.041742,-0.662924,1.392031,-0.486837,0.605377,0.178790,-0.433906,-0.348684,-1.550447,1.441390,1.709125,-0.758246,0.758246,-1.628561,-0.504166,-0.620303,0.504166,0.620303,-0.540801,-0.657372,-0.089701,-0.840040,-0.260858,-0.541233,-0.268579,-0.511814,1.160177,1.120250,-0.064587,0.163377,0.0,1.797834,0.0,0.0,0.0,-1.231547,-0.564527,0.0,-0.037072,0.0,-0.633434,-0.833586,-0.045238,-0.304406,0.571817,-1.114299,-0.033902,-0.601798,1.348648,-0.441340,0.559350,0.160390,-0.408804,-0.310793,-1.360988,1.308143,1.555288,-0.710717,0.749185,-1.661774,-0.266139,-0.251178,-0.659662,-0.615883,0.389187,0.382611,-1.125630,-0.373895,-1.544032,0.250207,-0.032844,0.090759,-0.440289,-0.441438,-0.824398,-0.435705,-0.008342,-0.039940,-0.182457,-0.224959,-0.225384,-0.158086,0.389911,-0.003650,0.679813,-0.003650,-1.165667,-0.338132,-0.917858,-0.268343,0.376032,-0.759060,1.469882,1.383869,0.130241,0.217980,0.209591,0.280612,-1.609438,0.196329,0.733693,-0.425598,-0.201209,-0.370258,-0.464208,0.009266,18
5655,0.193729,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,16
7258,1.069285,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,-10
2386,-0.681826,-1.313635,-1.060588,1.313635,1.060588,-1.313704,-1.060686,0.269099,-1.616617,-0.051556,2.626438,-3.032424,0.029448,2.885512,3.046496,-0.140674,-0.035660,0.0,-1.431962,0.0,0.0,0.0,-0.027786,-0.966496,0.0,-1.273409,0.0,-0.450116,-0.427092,-0.206559,-0.024410,0.922416,-0.773710,-1.157843,-2.334273,1.878037,-0.486837,1.837198,1.145631,-0.015222,-2.937656,-0.359092,3.171670,1.980511,-1.073794,1.073794,-1.628561,-1.228598,-0.988039,1.228598,0.988039,-1.303228,-1.048339,0.259601,-1.262814,-0.055132,2.685035,-3.317608,0.032819,2.652530,2.797489,-0.137154,-0.039332,0.0,-1.416715,0.0,0.0,0.0,-0.028019,-0.957606,0.0,-1.260020,0.0,-0.417615,-0.387754,-0.198318,-0.022872,0.870741,-0.714202,-1.051542,-2.113032,1.817722,-0.441340,1.700354,1.048744,-0.020788,-2.639701,-0.307724,2.877884,1.802617,-1.008367,1.062480,-1.661774,-0.402810,-0.003747,1.424388,1.513161,-1.906694,-1.658347,-0.422170,-0.980849,0.091522,-0.480051,-0.951576,-0.723427,0.667273,0.830858,0.302834,0.172426,-0.008342,-0.063034,0.739785,0.468997,0.469239,0.479237,-1.238042,-0.003650,-1.062590,-0.003650,1.098795,0.109212,1.103855,-2.122085,-2.336611,0.472152,0.250724,0.917897,-1.640045,-0.598464,0.410943,-0.004129,0.383973,-1.131563,1.594169,1.342731,2.792739,0.400266,1.532695,-0.382647,-3
8109,1.069285,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,9
9743,-1.119604,-1.104073,-1.024195,1.104073,1.024195,-1.106078,-1.024293,-0.293820,-1.455918,-0.693842,-0.345029,1.567741,0.657251,0.827778,0.881818,-1.010691,-0.991405,0.0,-0.595358,0.0,0.0,0.0,-1.179300,-0.975290,0.0,-1.155848,0.0,-0.772763,0.245333,-0.901900,-0.710645,-0.800395,-0.475771,-0.116149,-0.055161,0.226144,0.995520,-0.174777,0.468843,-0.475775,-0.792508,-1.788718,0.460898,-0.570516,-1.010684,1.010684,-0.324716,-2.686515,-2.628706,2.686515,2.628706,-1.037826,-1.223774,0.094653,-3.630345,-0.231469,-0.068879,0.816263,0.789252,0.351861,0.700940,-1.443367,-1.707782,0.0,-0.039051,0.0,0.0,0.0,-1.231547,-0.877534,0.0,-1.392230,0.0,-0.633434,0.801131,-1.695102,-0.304406,-1.371190,0.186016,0.474919,1.458975,0.709285,1.472307,0.369183,1.937099,0.561236,-0.310793,-0.658812,-0.523221,-1.412663,-0.512283,1.114696,0.002594,-0.668663,-0.578385,0.929143,0.761809,-0.824344,-0.862355,1.804637,0.667968,1.172474,0.627483,0.160092,-0.219398,-0.288879,-0.394052,-1.136555,-0.869266,-0.008342,-0.011072,-0.491310,-0.397202,-0.397442,-0.261715,-0.354312,0.141450,-0.648332,0.141450,-0.575161,0.821142,-0.796636,-1.079355,-0.733535,-0.937853,-0.029486,0.305586,-0.738472,1.828397,0.659984,0.962385,1.279947,-1.010846,-0.908006,-0.504896,-2.193025,-0.780944,1.372847,-1.460409,-3
4546,-0.244048,2.159668,2.285469,-2.159668,-2.285469,2.149966,2.285517,1.793248,1.365573,2.162149,-2.833133,2.931880,0.029448,-0.697000,-0.722845,1.885177,1.747949,0.0,-1.896741,0.0,0.0,0.0,-1.467179,1.920720,0.0,0.910403,0.0,1.854505,-0.427092,1.787973,1.223290,1.560495,-0.004198,0.516309,1.160366,-1.390151,-0.222130,-0.010534,-0.143490,2.287540,1.130729,0.435145,-0.577269,-0.733348,2.397229,-2.397229,-1.628561,2.013232,2.133000,-2.013232,-2.133000,2.142167,2.269873,1.715024,1.068480,2.031523,-2.911917,3.239237,0.032819,-0.633022,-0.655650,1.735085,1.613526,0.0,-1.875936,0.0,0.0,0.0,-1.231547,1.910415,0.0,0.895747,0.0,1.740572,-0.387754,1.655653,1.103267,1.468590,-0.004939,0.474919,1.046820,-1.336606,-0.202134,-0.011151,-0.135728,2.113301,1.020011,0.394453,-0.523221,-0.670675,2.265792,-2.383766,-1.661774,-0.024832,-0.190930,-1.574882,-1.437608,1.591676,1.344368,0.433257,0.834465,0.147225,0.313086,-0.323593,0.329939,-0.940408,-0.986369,-0.789714,-0.475814,-0.008342,0.053881,0.537386,0.525930,0.525816,0.282340,0.998306,-0.293852,0.814992,-0.293852,-0.138700,0.439264,-0.533989,-0.963496,-0.899142,-0.283372,1.052026,0.632922,0.981265,0.592495,0.898427,1.002489,0.219623,0.598720,1.639458,-0.623841,-0.170087,0.069762,-1.335020,0.989049,5
4962,0.193729,-0.023274,-0.019367,0.023274,0.019367,-0.023317,-0.019421,-0.025570,-0.009633,-0.020377,0.018363,0.010588,0.029448,0.002315,0.004100,-0.030744,-0.035660,0.0,-0.037623,0.0,0.0,0.0,-0.027786,-0.028518,0.0,-0.034551,0.0,0.010808,0.053211,-0.023574,-0.024410,-0.034701,-0.004198,-0.041742,-0.055161,0.009544,0.042576,-0.010534,0.017650,-0.015222,0.021169,0.038026,-0.000510,0.080810,-0.021969,0.021969,0.001245,-0.024231,-0.016839,0.024231,0.016839,-0.019649,-0.015784,-0.021781,-0.006573,-0.025742,0.011332,0.027721,0.032819,0.008327,0.010312,-0.035560,-0.039332,0.0,-0.039051,0.0,0.0,0.0,-0.028019,-0.025863,0.0,-0.037072,0.0,0.014022,0.058078,-0.028229,-0.022872,-0.026031,-0.004939,-0.033902,-0.052259,0.014326,0.037072,-0.011151,0.012331,-0.020788,0.021908,0.043364,0.000025,0.071313,-0.016198,0.018163,0.002594,-0.030033,-0.023691,0.001093,0.002803,-0.043664,-0.038157,-0.142747,-0.088833,-0.115142,0.028700,-0.013999,-0.009386,0.025342,0.028467,-0.044007,-0.038434,-0.008342,-0.011072,-0.029829,-0.034745,-0.034751,-0.028549,-0.047285,-0.003650,-0.037365,-0.003650,-0.010330,-0.010807,-0.013183,-0.113865,-0.137349,0.003681,-0.004906,-0.021750,0.018836,0.030722,-0.055345,-0.020170,-0.124983,-0.004867,0.054369,0.010537,0.078890,-0.037798,0.024878,0.009266,12
5706,0.193729,-2.099494,-2.233224,2.099494,2.233224,-2.099579,-2.233374,-0.299917,-0.612252,-0.831029,-0.355461,-0.176340,-1.151902,0.336411,0.327186,-1.585467,-2.004360,0.0,0.427157,0.0,0.0,0.0,-1.467179,-2.241562,0.0,-1.760768,0.0,-1.141502,0.373414,-1.267869,-1.584035,-1.310858,-0.892097,-1.343860,-0.814865,-1.670562,0.571990,-1.037052,-0.465770,-0.852590,-1.458244,0.038026,0.287870,2.794669,-2.335983,2.335983,1.631052,-1.962084,-2.081817,1.962084,2.081817,-2.084956,-2.211217,-0.283757,-0.477663,-0.789869,-0.371899,-0.177777,-1.026188,0.314729,0.306295,-1.472394,-1.863712,0.0,0.420170,0.0,0.0,0.0,-1.231547,-2.224193,0.0,-1.741119,0.0,-1.065072,0.355299,-1.184834,-1.430545,-1.221728,-0.823319,-1.221149,-0.739183,-1.607247,0.515483,-0.961988,-0.431846,-0.796820,-1.308897,0.043364,0.261649,2.544605,-2.198971,2.315660,1.666962,-0.169408,-0.152497,1.558891,1.466600,-1.801573,-1.773249,-0.509183,-0.373895,-0.284671,1.034770,0.877991,1.794190,-0.153439,-0.137382,-0.250184,-0.401326,-0.008342,0.075532,0.555244,0.627728,0.627508,0.632091,-1.166450,-0.003650,-0.926014,-0.003650,0.811244,1.080274,-0.102977,-0.345582,0.376032,-0.921450,-0.422763,-0.291320,-0.347343,1.004462,-0.770675,-0.040222,0.166606,-0.256362,-1.304278,0.288077,0.670210,0.363109,1.742644,0.989049,12