In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

pd.set_option('display.max_colwidth', None)

In [3]:
os.getcwd()

'C:\\Users\\Paul\\sb\\DSCapstone2\\02_Data_Wrangling'

In [4]:
filenames = ['nba_games_all.csv', 'injuries_2010-2020.csv', 'nba_teams_all.csv',
             'nba_players_all.csv', 'nba_teams.csv', 'teams.csv', 'games.csv']

In [5]:
dataframes = [pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\raw_data\\' + f) for f in filenames]   
df = dataframes[0]
df2 = dataframes[1]
df3 = dataframes[2]
df4 = dataframes[3]
df5 = dataframes[4]
df6 = dataframes[5]
df7 = dataframes[6]

In [6]:
df[df.matchup.str.contains(' CHA')]

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
38,20801205,2009-04-13,NJN vs. CHA,1610612766,f,L,35.0,46.0,0.432,240,33.0,73.0,0.452,0.0,6.0,0.000,21.0,27.0,1.0,8.0,25.0,33,17.0,11.0,7.0,14.0,19.0,87,1610612751,2008,Regular Season,2008-09
39,20801192,2009-04-11,CHI vs. CHA,1610612766,f,L,35.0,45.0,0.438,240,38.0,76.0,0.500,9.0,15.0,0.600,21.0,30.0,1.0,14.0,26.0,40,25.0,3.0,4.0,15.0,21.0,106,1610612741,2008,Regular Season,2008-09
44,20801104,2009-03-31,LAL @ CHA,1610612766,t,W,34.0,40.0,0.459,240,35.0,68.0,0.515,7.0,17.0,0.412,17.0,22.0,1.0,6.0,34.0,40,25.0,6.0,9.0,16.0,12.0,94,1610612747,2008,Regular Season,2008-09
45,20801074,2009-03-27,PHI vs. CHA,1610612766,f,W,32.0,40.0,0.444,240,37.0,72.0,0.514,6.0,18.0,0.333,20.0,29.0,1.0,13.0,28.0,41,21.0,8.0,3.0,17.0,25.0,100,1610612755,2008,Regular Season,2008-09
46,20801064,2009-03-25,WAS vs. CHA,1610612766,f,L,31.0,40.0,0.437,240,35.0,75.0,0.467,4.0,18.0,0.222,19.0,30.0,1.0,13.0,28.0,41,24.0,15.0,6.0,18.0,17.0,93,1610612764,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125121,20700384,2007-12-21,NYK @ CHA,1610612766,t,W,10.0,14.0,0.417,240,37.0,74.0,0.500,7.0,17.0,0.412,24.0,35.0,1.0,9.0,32.0,41,27.0,10.0,8.0,13.0,20.0,105,1610612752,2007,Regular Season,2007-08
125122,20700296,2007-12-09,DET vs. CHA,1610612766,f,L,7.0,12.0,0.368,240,34.0,79.0,0.430,6.0,20.0,0.300,11.0,14.0,1.0,8.0,21.0,29,22.0,5.0,3.0,11.0,27.0,85,1610612765,2007,Regular Season,2007-08
125123,20700206,2007-11-27,MIA vs. CHA,1610612766,f,L,6.0,8.0,0.429,240,34.0,74.0,0.459,4.0,16.0,0.250,18.0,24.0,1.0,10.0,21.0,31,20.0,6.0,6.0,18.0,23.0,90,1610612748,2007,Regular Season,2007-08
125124,20700132,2007-11-17,SEA @ CHA,1610612766,t,W,5.0,4.0,0.556,240,39.0,89.0,0.438,10.0,21.0,0.476,12.0,20.0,1.0,17.0,43.0,60,23.0,6.0,6.0,15.0,25.0,100,1610612760,2007,Regular Season,2007-08
125125,10700060,NaN,ATL @ CHA,1610612766,t,L,2.0,3.0,0.400,240,38.0,73.0,0.521,6.0,13.0,0.462,16.0,23.0,1.0,4.0,25.0,29,18.0,5.0,6.0,20.0,32.0,98,1610612737,2007,Pre Season,2007-08

In [7]:
df[df.matchup.str.contains(' CHA')].team_id.value_counts()

1610612766    1239
Name: team_id, dtype: int64

In [8]:
df[df.matchup.str.contains(' CHA')]['season'].value_counts().to_frame().sort_index()

         season
2004-05      82
2005-06      89
2006-07      90
2007-08      89
2008-09      90
2009-10      94
2010-11      90
2011-12      68
2012-13      90
2013-14      94
2014-15      90
2015-16      97
2016-17      89
2017-18      87

In [9]:
df2

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

In [10]:
df3

    league_id     team_id  min_year  max_year abbreviation
0           0  1610612737    1949.0    2018.0          ATL
1           0  1610612738    1946.0    2018.0          BOS
2           0  1610612739    1970.0    2018.0          CLE
3           0  1610612740    2002.0    2018.0          NOP
4           0  1610612741    1966.0    2018.0          CHI
5           0  1610612742    1980.0    2018.0          DAL
6           0  1610612743    1976.0    2018.0          DEN
7           0  1610612744    1946.0    2018.0          GSW
8           0  1610612745    1967.0    2018.0          HOU
9           0  1610612746    1970.0    2018.0          LAC
10          0  1610612747    1948.0    2018.0          LAL
11          0  1610612748    1988.0    2018.0          MIA
12          0  1610612749    1968.0    2018.0          MIL
13          0  1610612750    1989.0    2018.0          MIN
14          0  1610612751    1976.0    2018.0          BKN
15          0  1610612752    1946.0    2018.0          NYK
16          0  1610612753    1989.0    2018.0          ORL
17          0  1610616834       NaN       NaN          NaN
18          0  1610616833       NaN       NaN          NaN
19          0       12306       NaN       NaN          NaN
20          0       12303       NaN       NaN          NaN
21          0       12313       NaN       NaN          NaN
22          0       12316       NaN       NaN          NaN
23          0          45       NaN       NaN          NaN
24          0       12308       NaN       NaN          NaN
25          0       12304       NaN       NaN          NaN
26          0       12320       NaN       NaN          NaN
27          0       12315       NaN       NaN          NaN
28          0          94       NaN       NaN          NaN
29          0       12321       NaN       NaN          NaN
30          0       12324       NaN       NaN          NaN
31          0          93       NaN       NaN          NaN
32          0          41       NaN       NaN          NaN
33          0       12325       NaN       NaN          NaN
34          0       12323       NaN       NaN          NaN
35          0       12330       NaN       NaN          NaN
36          0       15015       NaN       NaN          NaN
37          0       15018       NaN       NaN          NaN
38          0       12329       NaN       NaN          NaN
39          0       15016       NaN       NaN          NaN
40          0       15017       NaN       NaN          NaN
41          0  1610612754    1976.0    2018.0          IND
42          0  1610612755    1949.0    2018.0          PHI
43          0  1610612756    1968.0    2018.0          PHX
44          0  1610612757    1970.0    2018.0          POR
45          0  1610612758    1948.0    2018.0          SAC
46          0  1610612759    1976.0    2018.0          SAS
47          0  1610612760    1967.0    2018.0          OKC
48          0  1610612761    1995.0    2018.0          TOR
49          0  1610612762    1974.0    2018.0          UTA
50          0  1610612763    1995.0    2018.0          MEM
51          0  1610612764    1961.0    2018.0          WAS
52          0  1610612765    1948.0    2018.0          DET
53          0  1610612766    1988.0    2018.0          CHA
54          0  1610610029    1948.0    1948.0          NaN
55          0  1610610025    1946.0    1949.0          NaN
56          0  1610610034    1946.0    1949.0          NaN
57          0  1610610036    1946.0    1950.0          NaN
58          0  1610610024    1947.0    1954.0          NaN
59          0  1610610031    1946.0    1946.0          NaN
60          0  1610610027    1949.0    1949.0          NaN
61          0  1610610030    1949.0    1952.0          NaN
62          0  1610610033    1949.0    1949.0          NaN
63          0  1610610037    1949.0    1949.0          NaN
64          0  1610610023    1949.0    1949.0          NaN
65          0  1610610026    1946.0    1946.0          NaN
66          0  1610610028    1946.0    1946.0          NaN
67          0  1610610032    1946.0    1948.0          NaN
68          0  1610610035    1946.0    1946.0          NaN

In [11]:
df3[['team_id', 'abbreviation']]

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610616834          NaN
18  1610616833          NaN
19       12306          NaN
20       12303          NaN
21       12313          NaN
22       12316          NaN
23          45          NaN
24       12308          NaN
25       12304          NaN
26       12320          NaN
27       12315          NaN
28          94          NaN
29       12321          NaN
30       12324          NaN
31          93          NaN
32          41          NaN
33       12325          NaN
34       12323          NaN
35       12330          NaN
36       15015          NaN
37       15018          NaN
38       12329          NaN
39       15016          NaN
40       15017          NaN
41  1610612754          IND
42  1610612755          PHI
43  1610612756          PHX
44  1610612757          POR
45  1610612758          SAC
46  1610612759          SAS
47  1610612760          OKC
48  1610612761          TOR
49  1610612762          UTA
50  1610612763          MEM
51  1610612764          WAS
52  1610612765          DET
53  1610612766          CHA
54  1610610029          NaN
55  1610610025          NaN
56  1610610034          NaN
57  1610610036          NaN
58  1610610024          NaN
59  1610610031          NaN
60  1610610027          NaN
61  1610610030          NaN
62  1610610033          NaN
63  1610610037          NaN
64  1610610023          NaN
65  1610610026          NaN
66  1610610028          NaN
67  1610610032          NaN
68  1610610035          NaN

In [40]:
team_id_abbreviation_df = df3[['team_id', 'abbreviation']].dropna().reset_index().drop('index', axis=1)
team_id_abbreviation_df

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610612754          IND
18  1610612755          PHI
19  1610612756          PHX
20  1610612757          POR
21  1610612758          SAC
22  1610612759          SAS
23  1610612760          OKC
24  1610612761          TOR
25  1610612762          UTA
26  1610612763          MEM
27  1610612764          WAS
28  1610612765          DET
29  1610612766          CHA

In [49]:
df3[['team_id', 'abbreviation']].dropna().shape

(30, 2)

In [48]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '0team_id_abbreviation_df.csv')
if not os.path.exists(datapath_df):
    df3[['team_id', 'abbreviation']].dropna().to_csv(datapath_df, index=False)

#datapath_df2 = os.path.join(datapath, 'df2.csv')
#if not os.path.exists(datapath_df2):
#    df2.to_csv(datapath_df2, index=False)

In [39]:
df

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125619,20801131,2009-04-03,MIN @ UTA,1610612762,t,L,46.0,30.0,0.605,240,36.0,75.0,0.480,5.0,11.0,0.455,25.0,29.0,1.0,4.0,24.0,28,22.0,11.0,4.0,10.0,16.0,102,1610612750,2008,Regular Season,2008-09
125620,20801058,2009-03-24,HOU @ UTA,1610612762,t,W,44.0,26.0,0.629,240,38.0,85.0,0.447,4.0,14.0,0.286,19.0,25.0,1.0,3.0,39.0,42,23.0,6.0,12.0,8.0,17.0,99,1610612745,2008,Regular Season,2008-09
125621,20801029,2009-03-20,OKC vs. UTA,1610612762,f,W,43.0,26.0,0.623,240,41.0,84.0,0.488,1.0,7.0,0.143,18.0,26.0,1.0,11.0,30.0,41,24.0,8.0,3.0,10.0,13.0,101,1610612760,2008,Regular Season,2008-09
125622,20800839,2009-02-23,ATL @ UTA,1610612762,t,W,34.0,23.0,0.596,240,44.0,88.0,0.500,6.0,13.0,0.462,14.0,17.0,1.0,14.0,29.0,43,30.0,11.0,6.0,15.0,19.0,108,1610612737,2008,Regular Season,2008-09
125623,20800810,2009-02-19,BOS @ UTA,1610612762,t,W,32.0,23.0,0.582,240,32.0,77.0,0.416,2.0,10.0,0.200,24.0,31.0,1.0,7.0,28.0,35,16.0,7.0,6.0,11.0,18.0,90,1610612738,2008,Regular Season,2008-09

In [12]:
df7

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2021-03-21,22000645,Final,1610612748,1610612754,2020,1610612748,106.0,0.402,0.826,0.243,27.0,51.0,1610612754,109.0,0.388,0.900,0.333,27.0,50.0,0
1,2021-03-21,22000016,Final,1610612745,1610612760,2020,1610612745,112.0,0.494,0.741,0.368,22.0,38.0,1610612760,114.0,0.462,0.680,0.333,22.0,52.0,0
2,2021-03-21,22000646,Final,1610612743,1610612740,2020,1610612743,108.0,0.500,0.800,0.353,30.0,37.0,1610612740,113.0,0.482,0.767,0.286,26.0,45.0,0
3,2021-03-21,22000167,Final,1610612738,1610612753,2020,1610612738,112.0,0.455,1.000,0.426,27.0,45.0,1610612753,96.0,0.381,0.700,0.324,20.0,44.0,1
4,2021-03-21,22000647,Final,1610612751,1610612764,2020,1610612751,113.0,0.489,0.727,0.310,24.0,35.0,1610612764,106.0,0.532,0.789,0.333,24.0,43.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24190,2014-10-06,11400007,Final,1610612737,1610612740,2014,1610612737,93.0,0.419,0.821,0.421,24.0,50.0,1610612740,87.0,0.366,0.643,0.375,17.0,43.0,1
24191,2014-10-06,11400004,Final,1610612741,1610612764,2014,1610612741,81.0,0.338,0.719,0.381,18.0,40.0,1610612764,85.0,0.411,0.636,0.267,17.0,47.0,0
24192,2014-10-06,11400005,Final,1610612747,1610612743,2014,1610612747,98.0,0.448,0.682,0.500,29.0,45.0,1610612743,95.0,0.387,0.659,0.500,19.0,43.0,1
24193,2014-10-05,11400002,Final,1610612761,1610612758,2014,1610612761,99.0,0.440,0.771,0.333,21.0,30.0,1610612758,94.0,0.469,0.725,0.385,18.0,45.0,1
24194,2014-10-04,11400001,Final,1610612748,1610612740,2014,1610612748,86.0,0.431,0.679,0.333,18.0,42.0,1610612740,98.0,0.462,0.706,0.438,19.0,42.0,0

In [14]:
df7.GAME_STATUS_TEXT.value_counts()

Final    24195
Name: GAME_STATUS_TEXT, dtype: int64

In [19]:
pd.to_datetime(df7.GAME_DATE_EST)

0       2021-03-21
1       2021-03-21
2       2021-03-21
3       2021-03-21
4       2021-03-21
           ...
24190   2014-10-06
24191   2014-10-06
24192   2014-10-06
24193   2014-10-05
24194   2014-10-04
Name: GAME_DATE_EST, Length: 24195, dtype: datetime64[ns]

In [30]:
pd.to_datetime(df7.GAME_DATE_EST).dt.year.value_counts().to_frame().sort_index()

      GAME_DATE_EST
2003            564
2004           1295
2005           1435
2006           1451
2007           1404
2008           1442
2009           1428
2010           1432
2011            915
2012           1580
2013           1432
2014           1441
2015           1419
2016           1429
2017           1417
2018           1382
2019           1332
2020            830
2021            567