In [1]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    print(df_.shape)
    return pd.concat([df_.head(), df_.tail()])


#read_csv
def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
#add PLAYER_ID using df_5bsa1018
df_ina_pip = pd.read_csv(os.path.join('..','processed_data','A11inactive_game_id_team_id_player_id_2010_2018.csv'))[['PLAYER_ID', 'player', 'TEAM_ID', 'TEAM_NAME', 'season']].drop_duplicates().reset_index(drop=True)
print(df_ina_pip.shape)
p(df_ina_pip)

(2884, 5)
(2884, 5)

      PLAYER_ID            player     TEAM_ID TEAM_NAME   season
0        202376    Luke Harangody  1610612738   Celtics  2010-11
1          2570  Kendrick Perkins  1610612738   Celtics  2010-11
2        202340     Avery Bradley  1610612738   Celtics  2010-11
3        202354    Dexter Pittman  1610612748      Heat  2010-11
4          2034       Mike Miller  1610612748      Heat  2010-11
2879    1626144   Emmanuel Mudiay  1610612752    Knicks  2017-18
2880     204065    David Stockton  1610612762      Jazz  2017-18
2881     203083    Andre Drummond  1610612765   Pistons  2017-18
2882     201152    Thaddeus Young  1610612754    Pacers  2017-18
2883     203498  Shabazz Muhammad  1610612749     Bucks  2017-18

In [6]:
df_bsa_piptis1018 = pd.read_csv(os.path.join('..','processed_data','A12bsa_game_id_team_id_player_id_2010_2018.csv'))[['PLAYER_ID', 'PLAYER_NAME', 'team_id', 'season']].drop_duplicates().reset_index(drop=True)
print(df_bsa_piptis1018.shape)
p(df_bsa_piptis1018)

(3763, 4)
(3763, 4)

      PLAYER_ID      PLAYER_NAME     team_id   season
0      201623.0      Semih Erden  1610612738  2010-11
1      101144.0        Von Wafer  1610612738  2010-11
2        2753.0     Delonte West  1610612738  2010-11
3      201596.0   Mario Chalmers  1610612748  2010-11
4         436.0     Juwan Howard  1610612748  2010-11
3758  1626145.0       Tyus Jones  1610612750  2017-18
3759  1626204.0  Larry Nance Jr.  1610612739  2017-18
3760  1627751.0     Jakob Poeltl  1610612761  2017-18
3761   203903.0  Jordan Clarkson  1610612739  2017-18
3762     2561.0       David West  1610612744  2017-18

In [7]:
df_tist1018 = pd.read_csv(os.path.join('..', 'processed_data', '10team_id_season_team_2010_2018.csv'))
print(df_tist1018.shape)
p(df_tist1018)

(240, 3)
(240, 3)

        TEAM_ID   season      Team
0    1610612748  2010-11      Heat
1    1610612749  2010-11     Bucks
2    1610612765  2010-11   Pistons
3    1610612753  2010-11     Magic
4    1610612737  2010-11     Hawks
235  1610612752  2017-18    Knicks
236  1610612758  2017-18     Kings
237  1610612744  2017-18  Warriors
238  1610612765  2017-18   Pistons
239  1610612746  2017-18  Clippers

In [8]:
df_bsa_piptist1018 = pd.merge(df_bsa_piptis1018, df_tist1018.rename(columns={'TEAM_ID':'team_id'}), on=['team_id', 'season'], indicator=True)
print(df_bsa_piptist1018.shape)
p(df_bsa_piptist1018)

(3763, 6)
(3763, 6)

      PLAYER_ID       PLAYER_NAME     team_id   season     Team _merge
0      201623.0       Semih Erden  1610612738  2010-11  Celtics   both
1      101144.0         Von Wafer  1610612738  2010-11  Celtics   both
2        2753.0      Delonte West  1610612738  2010-11  Celtics   both
3      202376.0    Luke Harangody  1610612738  2010-11  Celtics   both
4         406.0  Shaquille O'Neal  1610612738  2010-11  Celtics   both
3758   202695.0     Kawhi Leonard  1610612759  2017-18    Spurs   both
3759     2200.0         Pau Gasol  1610612759  2017-18    Spurs   both
3760  1626199.0   Darrun Hilliard  1610612759  2017-18    Spurs   both
3761  1627749.0   Dejounte Murray  1610612759  2017-18    Spurs   both
3762  1627854.0       Bryn Forbes  1610612759  2017-18    Spurs   both

In [9]:
df_bsa_piptist1018.value_counts('_merge')

_merge
both          3763
right_only       0
left_only        0
dtype: int64

In [10]:
df_bsa_piptist1018.drop(columns='_merge', inplace=True)

In [11]:
print(df_bsa_piptist1018.shape)
p(df_bsa_piptist1018)

(3763, 5)
(3763, 5)

      PLAYER_ID       PLAYER_NAME     team_id   season     Team
0      201623.0       Semih Erden  1610612738  2010-11  Celtics
1      101144.0         Von Wafer  1610612738  2010-11  Celtics
2        2753.0      Delonte West  1610612738  2010-11  Celtics
3      202376.0    Luke Harangody  1610612738  2010-11  Celtics
4         406.0  Shaquille O'Neal  1610612738  2010-11  Celtics
3758   202695.0     Kawhi Leonard  1610612759  2017-18    Spurs
3759     2200.0         Pau Gasol  1610612759  2017-18    Spurs
3760  1626199.0   Darrun Hilliard  1610612759  2017-18    Spurs
3761  1627749.0   Dejounte Murray  1610612759  2017-18    Spurs
3762  1627854.0       Bryn Forbes  1610612759  2017-18    Spurs

In [12]:
#add df_ina_pip by concat and then drop duplicates

In [13]:
df = pd.concat([df_ina_pip.rename(columns={'TEAM_NAME':'Team', 'TEAM_ID':'team_id'}), df_bsa_piptist1018.rename(columns={'PLAYER_NAME':'player'})]).drop_duplicates()
df

      PLAYER_ID             player     team_id     Team   season
0      202376.0     Luke Harangody  1610612738  Celtics  2010-11
1        2570.0   Kendrick Perkins  1610612738  Celtics  2010-11
2      202340.0      Avery Bradley  1610612738  Celtics  2010-11
3      202354.0     Dexter Pittman  1610612748     Heat  2010-11
4        2034.0        Mike Miller  1610612748     Heat  2010-11
...         ...                ...         ...      ...      ...
3730  1626195.0  Willy Hernangomez  1610612752   Knicks  2017-18
3738   203504.0         Trey Burke  1610612752   Knicks  2017-18
3748   202722.0      Davis Bertans  1610612759    Spurs  2017-18
3761  1627749.0    Dejounte Murray  1610612759    Spurs  2017-18
3762  1627854.0        Bryn Forbes  1610612759    Spurs  2017-18

[4262 rows x 5 columns]

In [14]:
df.value_counts('player')

player
LaMarcus Aldridge     12
Jameer Nelson         12
Ish Smith             12
Brandan Wright        11
Luke Babbitt          11
                      ..
Daniel Hamilton        1
Daniel Ochefu          1
Kyle Wiltjer           1
Daniel Theis           1
Zydrunas Ilgauskas     1
Length: 1077, dtype: int64

In [15]:
df2 = df[['PLAYER_ID', 'player']].drop_duplicates().reset_index(drop=True)
df2

      PLAYER_ID               player
0      202376.0       Luke Harangody
1        2570.0     Kendrick Perkins
2      202340.0        Avery Bradley
3      202354.0       Dexter Pittman
4        2034.0          Mike Miller
...         ...                  ...
1076  1626220.0        Royce O'Neale
1077  1628378.0     Donovan Mitchell
1078  1628513.0      Naz Mitrou-Long
1079  1628414.0  Sindarius Thornwell
1080  1627982.0            Josh Gray

[1081 rows x 2 columns]

In [16]:
df2.value_counts('player')

player
Mike James            2
Chris Johnson         2
Chris Wright          2
Tony Mitchell         2
Zydrunas Ilgauskas    1
                     ..
Marquis Daniels       1
Marquese Chriss       1
Markieff Morris       1
Markelle Fultz        1
AJ Hammons            1
Length: 1077, dtype: int64

In [17]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '14player_id_player_team_id_season_team_2010_2018.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=False)

In [18]:
df_read = rcp('14player_id_player_team_id_season_team_2010_2018.csv')
p(df_read)

(4262, 5)

      PLAYER_ID             player     team_id     Team   season
0      202376.0     Luke Harangody  1610612738  Celtics  2010-11
1        2570.0   Kendrick Perkins  1610612738  Celtics  2010-11
2      202340.0      Avery Bradley  1610612738  Celtics  2010-11
3      202354.0     Dexter Pittman  1610612748     Heat  2010-11
4        2034.0        Mike Miller  1610612748     Heat  2010-11
4257  1626195.0  Willy Hernangomez  1610612752   Knicks  2017-18
4258   203504.0         Trey Burke  1610612752   Knicks  2017-18
4259   202722.0      Davis Bertans  1610612759    Spurs  2017-18
4260  1627749.0    Dejounte Murray  1610612759    Spurs  2017-18
4261  1627854.0        Bryn Forbes  1610612759    Spurs  2017-18