In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [54]:
#from IPython.core.display import display, HTML
#display(HTML("<style>.container { width:100% !important; }</style>"))

In [55]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [56]:
df = pd.read_csv(os.path.join('..', 'raw_data', 'injuries_2010-2020.csv'), parse_dates=['Date'])
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

<font color='red'> </font>

In [57]:
df2 = pd.read_csv(os.path.join('..', 'processed_data', '3game_date_home_away.csv'), parse_dates=['game_date'])
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [58]:
df = df[(df.Date >= df2.game_date.min()) & (df.Date <= df2.game_date.max())]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [59]:
df.Team.value_counts().shape

(32,)

(32,)

<font color='red'>  </font>

In [60]:
path = os.path.join('..', 'processed_data', '0team_id_abbreviation_df.csv')
df3 = pd.read_csv(path)
df3

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610612754          IND
18  1610612755          PHI
19  1610612756          PHX
20  1610612757          POR
21  1610612758          SAC
22  1610612759          SAS
23  1610612760          OKC
24  1610612761          TOR
25  1610612762          UTA
26  1610612763          MEM
27  1610612764          WAS
28  1610612765          DET
29  1610612766          CHA

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610612754          IND
18  1610612755          PHI
19  1610612756          PHX
20  1610612757          POR
21  1610612758          SAC
22  1610612759          SAS
23  1610612760          OKC
24  1610612761          TOR
25  1610612762          UTA
26  1610612763          MEM
27  1610612764          WAS
28  1610612765          DET
29  1610612766          CHA

In [61]:
#charlotte
    #bobcats 04-14
    #hornets 14-present
    #charlotte ---> 06-18

In [62]:
path = os.path.join('..', 'raw_data', 'nba_teams.csv')
df4 = pd.read_csv(path)
df4

,id,full_name,abbreviation,nickname,city,state,year_founded,url
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949,https://content.sportslogos.net/logos/6/220/full/kqhjtzl2ik3gnxsnwsn8yf002.gif
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946,https://content.sportslogos.net/logos/6/213/full/slhg02hbef3j1ov4lsnwyol5o.png
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970,https://cdn.statmuse.com/img/nba/players/old_nba_cavs_1995_2003--dba8iauk.png
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002,NaN
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966,https://cdn.mos.cms.futurecdn.net/8227s5kMEx84YEHWLbxCb4-1200-80.jpg
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980,https://cdn.statmuse.com/img/nba/players/old_nba_dal_1981_2001--1nfqfd2j.png
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976,https://1000logos.net/wp-content/uploads/2018/06/Denver-Rockets-Logo-2008.jpg
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946,https://i.pinimg.com/originals/1d/95/43/1d95432d0a10768054755095f6a4427b.png
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967,https://content.sportslogos.net/logos/6/230/full/vr7yd7ghightk5f9g3jh5ltnc.png
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970,https://content.sportslogos.net/logos/6/236/full/ioxjye9im9phdgfyfxvj1xb71.png
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948,https://images.homedepot-static.com/productImages/ce8be48f-a86e-4b96-a365-d97d33cc02e3/svn/purple-applied-icon-wall-decals-nbop1401-64_600.jpg
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988,https://logovtor.com/wp-content/uploads/2020/06/miami-heat-logo-vector.png
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968,https://pm1.narvii.com/6493/f62ac7896462df0e3771e962787cf8754336d1b7_00.jpg
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989,https://www.nbateamslist.com/wp-content/uploads/2013/04/wolves.jpg
14,1610612751,Brooklyn Nets,NJN,Nets,Brooklyn,New York,1976,https://content.sportslogos.net/logos/6/215/full/2hh70mg3h40yl41tzfpn3gha2.gif
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946,https://images.homedepot-static.com/productImages/46d9d86f-e257-4ac6-8d71-2a3e120c7be7/svn/orange-applied-icon-wall-decals-nbop2003-64_1000.jpg
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989,https://www.michael-weinstein.com/wp-content/uploads/2015/12/orlando_magic_logo-2000-2010.png
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976,https://images.homedepot-static.com/productImages/5a5042bb-b9cd-4786-aaac-accdeea8dde9/svn/fanmats-other-interior-auto-accessories-22217-64_1000.jpg
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949,https://i.pinimg.com/736x/b6/af/a0/b6afa094187bb5ad27cd316ed4addd6c.jpg
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiCALqbXwR29WVCXIzQdL7SCpk2wP6nf8hOA&usqp=CAU
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970,https://logonoid.com/images/portland-trail-blazers-logo.gif
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948,https://www.nba.com/kings/sites/kings/files/10_-_sacramento.png
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976,https://content.sportslogos.net/logos/6/233/full/e04ylwkfdofkr2ctlerjov26s.png
23,1610612760,Oklahoma City Thunder,SEA,Thunder,Oklahoma City,Oklahoma,1967,https://external-preview.redd.it/qX9powo5lVgvv_WBWX5lbgfJma-CtTsKpn6-Kh1YBuU.jpg?auto=webp&s=412bbf79803684a2cf70be6d424c210bc60eb9f6
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995,https://images8.alphacoders.com/105/1055875.jpg
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974,https://content.sportslogos.net/logos/6/234/full/8316e7nrg5xuouqqo21bjgem9.png
26,1610612763,Memphis Grizzlies,VAN,Grizzlies,Memphis,Tennessee,1995,https://www.pngkit.com/png/detail/200-2000557_memphis-grizzlies-logo.png
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961,https://www.michael-weinstein.com/wp-content/uploads/2011/05/bullets2.jpg
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948,https://content.sportslogos.net/logos/6/223/full/enfhamkfyk1vfvdjuzg67fpeg.gif
29,1610612766,Charlotte Hornets,CHH,Hornets,Charlotte,North Carolina,1988,https://images-na.ssl-images-amazon.com/images/I/41JP%2BcUJ22L._AC_.jpg

,id,full_name,abbreviation,nickname,city,state,year_founded,url
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949,https://content.sportslogos.net/logos/6/220/full/kqhjtzl2ik3gnxsnwsn8yf002.gif
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946,https://content.sportslogos.net/logos/6/213/full/slhg02hbef3j1ov4lsnwyol5o.png
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970,https://cdn.statmuse.com/img/nba/players/old_nba_cavs_1995_2003--dba8iauk.png
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002,NaN
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966,https://cdn.mos.cms.futurecdn.net/8227s5kMEx84YEHWLbxCb4-1200-80.jpg
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980,https://cdn.statmuse.com/img/nba/players/old_nba_dal_1981_2001--1nfqfd2j.png
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976,https://1000logos.net/wp-content/uploads/2018/06/Denver-Rockets-Logo-2008.jpg
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946,https://i.pinimg.com/originals/1d/95/43/1d95432d0a10768054755095f6a4427b.png
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967,https://content.sportslogos.net/logos/6/230/full/vr7yd7ghightk5f9g3jh5ltnc.png
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970,https://content.sportslogos.net/logos/6/236/full/ioxjye9im9phdgfyfxvj1xb71.png
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948,https://images.homedepot-static.com/productImages/ce8be48f-a86e-4b96-a365-d97d33cc02e3/svn/purple-applied-icon-wall-decals-nbop1401-64_600.jpg
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988,https://logovtor.com/wp-content/uploads/2020/06/miami-heat-logo-vector.png
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968,https://pm1.narvii.com/6493/f62ac7896462df0e3771e962787cf8754336d1b7_00.jpg
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989,https://www.nbateamslist.com/wp-content/uploads/2013/04/wolves.jpg
14,1610612751,Brooklyn Nets,NJN,Nets,Brooklyn,New York,1976,https://content.sportslogos.net/logos/6/215/full/2hh70mg3h40yl41tzfpn3gha2.gif
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946,https://images.homedepot-static.com/productImages/46d9d86f-e257-4ac6-8d71-2a3e120c7be7/svn/orange-applied-icon-wall-decals-nbop2003-64_1000.jpg
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989,https://www.michael-weinstein.com/wp-content/uploads/2015/12/orlando_magic_logo-2000-2010.png
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976,https://images.homedepot-static.com/productImages/5a5042bb-b9cd-4786-aaac-accdeea8dde9/svn/fanmats-other-interior-auto-accessories-22217-64_1000.jpg
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949,https://i.pinimg.com/736x/b6/af/a0/b6afa094187bb5ad27cd316ed4addd6c.jpg
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiCALqbXwR29WVCXIzQdL7SCpk2wP6nf8hOA&usqp=CAU
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970,https://logonoid.com/images/portland-trail-blazers-logo.gif
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948,https://www.nba.com/kings/sites/kings/files/10_-_sacramento.png
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976,https://content.sportslogos.net/logos/6/233/full/e04ylwkfdofkr2ctlerjov26s.png
23,1610612760,Oklahoma City Thunder,SEA,Thunder,Oklahoma City,Oklahoma,1967,https://external-preview.redd.it/qX9powo5lVgvv_WBWX5lbgfJma-CtTsKpn6-Kh1YBuU.jpg?auto=webp&s=412bbf79803684a2cf70be6d424c210bc60eb9f6
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995,https://images8.alphacoders.com/105/1055875.jpg
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974,https://content.sportslogos.net/logos/6/234/full/8316e7nrg5xuouqqo21bjgem9.png
26,1610612763,Memphis Grizzlies,VAN,Grizzlies,Memphis,Tennessee,1995,https://www.pngkit.com/png/detail/200-2000557_memphis-grizzlies-logo.png
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961,https://www.michael-weinstein.com/wp-content/uploads/2011/05/bullets2.jpg
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948,https://content.sportslogos.net/logos/6/223/full/enfhamkfyk1vfvdjuzg67fpeg.gif
29,1610612766,Charlotte Hornets,CHH,Hornets,Charlotte,North Carolina,1988,https://images-na.ssl-images-amazon.com/images/I/41JP%2BcUJ22L._AC_.jpg

In [63]:
set3 = set(df3.abbreviation)
set3

{'ATL',
 'BKN',
 'BOS',
 'CHA',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS'}

{'ATL',
 'BKN',
 'BOS',
 'CHA',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS'}

In [64]:
set4 = set(df4.abbreviation)
set4

{'ATL',
 'BOS',
 'CHH',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MIA',
 'MIL',
 'MIN',
 'NJN',
 'NOP',
 'NYK',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'SEA',
 'TOR',
 'UTA',
 'VAN',
 'WAS'}

{'ATL',
 'BOS',
 'CHH',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MIA',
 'MIL',
 'MIN',
 'NJN',
 'NOP',
 'NYK',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'SEA',
 'TOR',
 'UTA',
 'VAN',
 'WAS'}

In [65]:
set4 - set3

{'CHH', 'NJN', 'SEA', 'VAN'}

{'CHH', 'NJN', 'SEA', 'VAN'}

In [66]:
set3 - set4

{'BKN', 'CHA', 'MEM', 'OKC'}

{'BKN', 'CHA', 'MEM', 'OKC'}

In [67]:
#CHA as CHH
#BKN as NJN
#OKC as SEA
#MEM as VAN

In [68]:
df4[['abbreviation', 'nickname']]

   abbreviation       nickname
0           ATL          Hawks
1           BOS        Celtics
2           CLE      Cavaliers
3           NOP       Pelicans
4           CHI          Bulls
5           DAL      Mavericks
6           DEN        Nuggets
7           GSW       Warriors
8           HOU        Rockets
9           LAC       Clippers
10          LAL         Lakers
11          MIA           Heat
12          MIL          Bucks
13          MIN   Timberwolves
14          NJN           Nets
15          NYK         Knicks
16          ORL          Magic
17          IND         Pacers
18          PHI          76ers
19          PHX           Suns
20          POR  Trail Blazers
21          SAC          Kings
22          SAS          Spurs
23          SEA        Thunder
24          TOR        Raptors
25          UTA           Jazz
26          VAN      Grizzlies
27          WAS        Wizards
28          DET        Pistons
29          CHH        Hornets

   abbreviation       nickname
0           ATL          Hawks
1           BOS        Celtics
2           CLE      Cavaliers
3           NOP       Pelicans
4           CHI          Bulls
5           DAL      Mavericks
6           DEN        Nuggets
7           GSW       Warriors
8           HOU        Rockets
9           LAC       Clippers
10          LAL         Lakers
11          MIA           Heat
12          MIL          Bucks
13          MIN   Timberwolves
14          NJN           Nets
15          NYK         Knicks
16          ORL          Magic
17          IND         Pacers
18          PHI          76ers
19          PHX           Suns
20          POR  Trail Blazers
21          SAC          Kings
22          SAS          Spurs
23          SEA        Thunder
24          TOR        Raptors
25          UTA           Jazz
26          VAN      Grizzlies
27          WAS        Wizards
28          DET        Pistons
29          CHH        Hornets

In [69]:
df4 = df4[['id','abbreviation', 'nickname']].replace({'CHH':'CHA', 'NJN':'BKN',
                                           'SEA':'OKC', 'VAN':'MEM'})
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [70]:
#df.reset_index().drop(columns='index', inplace=True)
df.reset_index(drop=True)
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [71]:
df[df.Team.isnull()]

,Date,Team,Acquired,Relinquished,Notes
13007,2015-09-02,NaN,NaN,Glen Davis,surgery on left ankle to repair torn ligaments (out indefinitely)
13009,2015-09-03,NaN,NaN,Landry Fields,surgery on hip to repair torn labrum (out indefinitely)

,Date,Team,Acquired,Relinquished,Notes
13007,2015-09-02,NaN,NaN,Glen Davis,surgery on left ankle to repair torn ligaments (out indefinitely)
13009,2015-09-03,NaN,NaN,Landry Fields,surgery on hip to repair torn labrum (out indefinitely)

In [72]:
df.iloc[13009,:]['Team']

nan

nan

In [73]:
df.iloc[13009,:]

Date                                                2015-09-03 00:00:00
Team                                                                NaN
Acquired                                                            NaN
Relinquished                                              Landry Fields
Notes           surgery on hip to repair torn labrum (out indefinitely)
Name: 13009, dtype: object

Date                                                2015-09-03 00:00:00
Team                                                                NaN
Acquired                                                            NaN
Relinquished                                              Landry Fields
Notes           surgery on hip to repair torn labrum (out indefinitely)
Name: 13009, dtype: object

In [74]:
print(df.Team.value_counts().shape)
df.Team.value_counts()

(32,)

Spurs           1070
Nuggets          860
Rockets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Knicks           783
Celtics          783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Bullets            1
Name: Team, dtype: int64

(32,)

Spurs           1070
Nuggets          860
Rockets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Knicks           783
Celtics          783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Bullets            1
Name: Team, dtype: int64

In [75]:
df = df[df.Team.notnull()]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [76]:
df.reset_index(inplace=True)

In [77]:
df.drop(columns='index', inplace=True)
df

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [78]:
set0 = set(df.Team)
set0

{'76ers',
 'Blazers',
 'Bobcats',
 'Bucks',
 'Bullets',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Warriors',
 'Wizards'}

{'76ers',
 'Blazers',
 'Bobcats',
 'Bucks',
 'Bullets',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Warriors',
 'Wizards'}

In [79]:
set4 = set(df4.nickname)
set4

{'76ers',
 'Bucks',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Trail Blazers',
 'Warriors',
 'Wizards'}

{'76ers',
 'Bucks',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Trail Blazers',
 'Warriors',
 'Wizards'}

In [80]:
df[df.Team == 'Bullets']

            Date     Team        Acquired Relinquished              Notes
19375 2017-11-05  Bullets  Marion Hillard          NaN  activated from IL

            Date     Team        Acquired Relinquished              Notes
19375 2017-11-05  Bullets  Marion Hillard          NaN  activated from IL

In [81]:
df = df[df.Team != 'Bullets']
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [82]:
df = df.reset_index().drop(columns='index')
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [83]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [84]:
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [85]:
df[df.Acquired.notnull() & df.Relinquished.notnull()].Acquired

21687    John Collins
Name: Acquired, dtype: object

21687    John Collins
Name: Acquired, dtype: object

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22254 entries, 0 to 22253
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          22254 non-null  datetime64[ns]
 1   Team          22254 non-null  object
 2   Acquired      7492 non-null   object
 3   Relinquished  14763 non-null  object
 4   Notes         22254 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 869.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22254 entries, 0 to 22253
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          22254 non-null  datetime64[ns]
 1   Team          22254 non-null  object
 2   Acquired      7492 non-null   object
 3   Relinquished  14763 non-null  object
 4   Notes         22254 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 869.4+ KB

In [87]:
df.head()

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)

In [88]:
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [89]:
set(df.Team) - set(df4.nickname)

{'Blazers', 'Bobcats'}

{'Blazers', 'Bobcats'}

In [90]:
set(df4.nickname) - set(df.Team)

{'Trail Blazers'}

{'Trail Blazers'}

In [91]:
df4.nickname.replace({'Trail Blazers': 'Blazers'}, inplace=True)

In [92]:
set(df.Team) - set(df4.nickname)

{'Bobcats'}

{'Bobcats'}

In [93]:
set(df4.nickname) - set(df.Team)

set()

set()

In [94]:
df4.iloc[29].to_frame().T

            id abbreviation nickname
29  1610612766          CHA  Hornets

            id abbreviation nickname
29  1610612766          CHA  Hornets

In [95]:
bobcats = df4.iloc[29].to_frame().T
bobcats['nickname'][29] = 'Bobcats'
df4 = pd.concat([df4, bobcats])
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
29  1610612766          CHA       Bobcats

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
29  1610612766          CHA       Bobcats

In [96]:
df4 = df4.reset_index().drop(columns='index')
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

In [97]:
NOH = df4.iloc[3,:].to_frame().T
NOH

           id abbreviation  nickname
3  1610612740          NOP  Pelicans

           id abbreviation  nickname
3  1610612740          NOP  Pelicans

In [98]:
NOH['abbreviation'] = 'NOH'

In [99]:
NOH['nickname'] = 'Hornets'

In [100]:
NOH

           id abbreviation nickname
3  1610612740          NOH  Hornets

           id abbreviation nickname
3  1610612740          NOH  Hornets

In [101]:
df4 = pd.concat([df4, NOH]).reset_index(drop=True)
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats
31  1610612740          NOH       Hornets

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats
31  1610612740          NOH       Hornets

In [ ]:
#https://www.reddit.com/r/nba/comments/6xw0li/can_someone_explain_the_whole_bobcats_hornets/
'''
Charlotte Hornets were a team. They then moved to New Orleans, becoming the New Orleans Hornets. Charlotte
got a new team named the Charlotte Bobcats, as there was already a Hornets team. When Tom Benson bought the
New Orleans Hornets he decided to change the name to Pelicans. This allowed Charlotte, still fond of their
Hornets name that was originally theirs, to drop the Bobcats name and become the Charlotte Hornets again.
'''

In [102]:
set(df4.nickname) - set(df.Team)

set()

set()

In [103]:
set(df.Team) - set(df4.nickname)

set()

set()

In [104]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '6team_id_abbreviation_nickname.csv')
if not os.path.exists(datapath_df):
    df4.to_csv(datapath_df, index=False)