In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
df = pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\raw_data\\injuries_2010-2020.csv', parse_dates=['Date'])
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

In [3]:
#fill nulls with something that makes sense

#df = df[~(df.Acquired.isnull() & df.Relinquished.isnull())]
#df

<font color='red'> </font>

In [4]:
df2 = pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\3game_date_home_away.csv', parse_dates=['game_date'])
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [5]:
#keep 2005-2006 season dates in case of player out before season starts <<<<<<<<<<<<<<<<<<<<<<<===============<<<<<<<<<<<<<<<==
df = df[(df.Date >= df2.game_date.min()) & (df.Date <= df2.game_date.max())]

In [6]:
df.Team.value_counts().shape

(32,)

<font color='red'>  </font>

In [7]:
path = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\0team_id_abbreviation_df.csv'
df3 = pd.read_csv(path)
df3

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610612754          IND
18  1610612755          PHI
19  1610612756          PHX
20  1610612757          POR
21  1610612758          SAC
22  1610612759          SAS
23  1610612760          OKC
24  1610612761          TOR
25  1610612762          UTA
26  1610612763          MEM
27  1610612764          WAS
28  1610612765          DET
29  1610612766          CHA

In [8]:
#charlotte
    #bobcats 04-14
    #horrnets 14-present
    #charlotte ---> 06-18

In [9]:
path = 'C:\\Users\\Paul\\sb\\DSCapstone2\\raw_data\\nba_teams.csv'
df4 = pd.read_csv(path)
df4

,id,full_name,abbreviation,nickname,city,state,year_founded,url
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949,https://content.sportslogos.net/logos/6/220/full/kqhjtzl2ik3gnxsnwsn8yf002.gif
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946,https://content.sportslogos.net/logos/6/213/full/slhg02hbef3j1ov4lsnwyol5o.png
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970,https://cdn.statmuse.com/img/nba/players/old_nba_cavs_1995_2003--dba8iauk.png
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002,NaN
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966,https://cdn.mos.cms.futurecdn.net/8227s5kMEx84YEHWLbxCb4-1200-80.jpg
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980,https://cdn.statmuse.com/img/nba/players/old_nba_dal_1981_2001--1nfqfd2j.png
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976,https://1000logos.net/wp-content/uploads/2018/06/Denver-Rockets-Logo-2008.jpg
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946,https://i.pinimg.com/originals/1d/95/43/1d95432d0a10768054755095f6a4427b.png
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967,https://content.sportslogos.net/logos/6/230/full/vr7yd7ghightk5f9g3jh5ltnc.png
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970,https://content.sportslogos.net/logos/6/236/full/ioxjye9im9phdgfyfxvj1xb71.png
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948,https://images.homedepot-static.com/productImages/ce8be48f-a86e-4b96-a365-d97d33cc02e3/svn/purple-applied-icon-wall-decals-nbop1401-64_600.jpg
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988,https://logovtor.com/wp-content/uploads/2020/06/miami-heat-logo-vector.png
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968,https://pm1.narvii.com/6493/f62ac7896462df0e3771e962787cf8754336d1b7_00.jpg
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989,https://www.nbateamslist.com/wp-content/uploads/2013/04/wolves.jpg
14,1610612751,Brooklyn Nets,NJN,Nets,Brooklyn,New York,1976,https://content.sportslogos.net/logos/6/215/full/2hh70mg3h40yl41tzfpn3gha2.gif
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946,https://images.homedepot-static.com/productImages/46d9d86f-e257-4ac6-8d71-2a3e120c7be7/svn/orange-applied-icon-wall-decals-nbop2003-64_1000.jpg
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989,https://www.michael-weinstein.com/wp-content/uploads/2015/12/orlando_magic_logo-2000-2010.png
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976,https://images.homedepot-static.com/productImages/5a5042bb-b9cd-4786-aaac-accdeea8dde9/svn/fanmats-other-interior-auto-accessories-22217-64_1000.jpg
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949,https://i.pinimg.com/736x/b6/af/a0/b6afa094187bb5ad27cd316ed4addd6c.jpg
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiCALqbXwR29WVCXIzQdL7SCpk2wP6nf8hOA&usqp=CAU
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970,https://logonoid.com/images/portland-trail-blazers-logo.gif
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948,https://www.nba.com/kings/sites/kings/files/10_-_sacramento.png
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976,https://content.sportslogos.net/logos/6/233/full/e04ylwkfdofkr2ctlerjov26s.png
23,1610612760,Oklahoma City Thunder,SEA,Thunder,Oklahoma City,Oklahoma,1967,https://external-preview.redd.it/qX9powo5lVgvv_WBWX5lbgfJma-CtTsKpn6-Kh1YBuU.jpg?auto=webp&s=412bbf79803684a2cf70be6d424c210bc60eb9f6
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995,https://images8.alphacoders.com/105/1055875.jpg
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974,https://content.sportslogos.net/logos/6/234/full/8316e7nrg5xuouqqo21bjgem9.png
26,1610612763,Memphis Grizzlies,VAN,Grizzlies,Memphis,Tennessee,1995,https://www.pngkit.com/png/detail/200-2000557_memphis-grizzlies-logo.png
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961,https://www.michael-weinstein.com/wp-content/uploads/2011/05/bullets2.jpg
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948,https://content.sportslogos.net/logos/6/223/full/enfhamkfyk1vfvdjuzg67fpeg.gif
29,1610612766,Charlotte Hornets,CHH,Hornets,Charlotte,North Carolina,1988,https://images-na.ssl-images-amazon.com/images/I/41JP%2BcUJ22L._AC_.jpg

In [10]:
set3 = set(df3.abbreviation)
set3

{'ATL',
 'BKN',
 'BOS',
 'CHA',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS'}

In [11]:
set4 = set(df4.abbreviation)
set4

{'ATL',
 'BOS',
 'CHH',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MIA',
 'MIL',
 'MIN',
 'NJN',
 'NOP',
 'NYK',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'SEA',
 'TOR',
 'UTA',
 'VAN',
 'WAS'}

In [12]:
set4 - set3

{'CHH', 'NJN', 'SEA', 'VAN'}

In [13]:
set3 - set4

{'BKN', 'CHA', 'MEM', 'OKC'}

In [14]:
#CHA as CHH
#BKN as NJN
#OKC as SEA
#MEM as VAN

In [15]:
df4[['abbreviation', 'nickname']]

   abbreviation       nickname
0           ATL          Hawks
1           BOS        Celtics
2           CLE      Cavaliers
3           NOP       Pelicans
4           CHI          Bulls
5           DAL      Mavericks
6           DEN        Nuggets
7           GSW       Warriors
8           HOU        Rockets
9           LAC       Clippers
10          LAL         Lakers
11          MIA           Heat
12          MIL          Bucks
13          MIN   Timberwolves
14          NJN           Nets
15          NYK         Knicks
16          ORL          Magic
17          IND         Pacers
18          PHI          76ers
19          PHX           Suns
20          POR  Trail Blazers
21          SAC          Kings
22          SAS          Spurs
23          SEA        Thunder
24          TOR        Raptors
25          UTA           Jazz
26          VAN      Grizzlies
27          WAS        Wizards
28          DET        Pistons
29          CHH        Hornets

In [16]:
df4 = df4[['id','abbreviation', 'nickname']].replace({'CHH':'CHA', 'NJN':'BKN',
                                           'SEA':'OKC', 'VAN':'MEM'})
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [17]:
df.reset_index().drop(columns='index', inplace=True)
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [18]:
df.iloc[13009,:]['Team'] = 'LAC'

C:\Users\Paul\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [19]:
df = df[df.Team.notnull()]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [20]:
df.reset_index(inplace=True)

In [21]:
df.drop(columns='index', inplace=True)
df

C:\Users\Paul\anaconda3\lib\site-packages\pandas\core\frame.py:4167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [22]:
set0 = set(df.Team)
set0

{'76ers',
 'Blazers',
 'Bobcats',
 'Bucks',
 'Bullets',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Warriors',
 'Wizards'}

In [23]:
set4 = set(df4.nickname)
set4

{'76ers',
 'Bucks',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Trail Blazers',
 'Warriors',
 'Wizards'}

In [24]:
df[df.Team == 'Bullets']

            Date     Team        Acquired Relinquished              Notes
19375 2017-11-05  Bullets  Marion Hillard          NaN  activated from IL

In [25]:
df = df[df.Team != 'Bullets']
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [26]:
df = df.reset_index().drop(columns='index')
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [27]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [28]:
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [29]:
df[df.Acquired.notnull() & df.Relinquished.notnull()].Acquired

21687    John Collins
Name: Acquired, dtype: object

In [30]:
df[df.Acquired.notnull() & df.Relinquished.notnull()]

            Date   Team       Acquired   Relinquished               Notes
21687 2018-03-23  Hawks  John Collins   John Collins   returned to lineup

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22254 entries, 0 to 22253
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          22254 non-null  datetime64[ns]
 1   Team          22254 non-null  object
 2   Acquired      7492 non-null   object
 3   Relinquished  14763 non-null  object
 4   Notes         22254 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 869.4+ KB

In [32]:
df.head()

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)

In [33]:
df = df[(~df.Acquired.isnull()) | (~df.Relinquished.isnull())]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [34]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [35]:
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [36]:
set(df.Team) - set(df4.nickname)

{'Blazers', 'Bobcats'}

In [37]:
set(df4.nickname) - set(df.Team)

{'Trail Blazers'}

In [38]:
df4.nickname.replace({'Trail Blazers': 'Blazers'}, inplace=True)

In [39]:
set(df.Team) - set(df4.nickname)

{'Bobcats'}

In [40]:
set(df4.nickname) - set(df.Team)

set()

In [41]:
df4.iloc[29].to_frame().T

            id abbreviation nickname
29  1610612766          CHA  Hornets

In [42]:
bobcats = df4.iloc[29].to_frame().T
bobcats['nickname'][29] = 'Bobcats'
df4 = pd.concat([df4, bobcats])
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
29  1610612766          CHA       Bobcats

In [43]:
df4 = df4.reset_index().drop(columns='index')
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

In [44]:
set(df4.nickname) - set(df.Team)

set()

In [45]:
set(df.Team) - set(df4.nickname)

set()

In [46]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [47]:
df_injuries = pd.merge(df, df4[['id', 'nickname']], left_on=['Team'], right_on=['nickname'], 
                       how='left').drop(columns='nickname')
df_injuries

,Date,Team,Acquired,Relinquished,Notes,id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [48]:
df_injuries.rename(columns={'id':'team_id'})

,Date,Team,Acquired,Relinquished,Notes,team_id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [49]:
df_injuries.Team.value_counts()

Spurs           1070
Nuggets          860
Rockets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Celtics          783
Knicks           783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Name: Team, dtype: int64

In [50]:
df_injuries = df_injuries.rename(columns={'id':'team_id'})
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [51]:
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [52]:
# df_injuries - team_id, player
# df2 - game_id, team_id, home and away stats
# nba_api player ratings/stats

In [53]:
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

In [54]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [55]:
df[df.Acquired.notnull() & df.Relinquished.notnull()]

            Date   Team       Acquired   Relinquished               Notes
21687 2018-03-23  Hawks  John Collins   John Collins   returned to lineup

In [56]:
df_injuries['AR'] = df_injuries.Acquired + df_injuries.Relinquished

In [57]:
df_injuries.Acquired = df_injuries.Acquired.fillna('')

In [58]:
df_injuries.Relinquished = df_injuries.Relinquished.fillna('')

In [59]:
df_injuries['AR'] = df_injuries.Acquired + df_injuries.Relinquished

In [60]:
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,AR
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala

In [61]:
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,AR
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala

In [62]:
df_injuries['A'] = 0

In [63]:
df_injuries['A'][df_injuries['Acquired'] != ''] = 1

C:\Users\Paul\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [64]:
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,AR,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [65]:
df_injuries = df_injuries.rename(columns={'AR':'player'})
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [66]:
path = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\5boxscoreadvancedv2_2010_2018.csv'
df_or1018 = pd.read_csv(path)

In [67]:
df_or1018

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [68]:
df_or1018

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [69]:
path = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\5boxscoreadvancedv2_2009_2010.csv'
df_or0910 = pd.read_csv(path)
df_or0910

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1610612738,BOS,Boston,1718,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76,0.189
1,20900001,1610612738,BOS,Boston,708,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66,0.147
2,20900001,1610612738,BOS,Boston,2570,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47,0.030
3,20900001,1610612738,BOS,Boston,951,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80,0.051
4,20900001,1610612738,BOS,Boston,200765,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31476,40900407,1610612747,LAL,Los Angeles,2756,Sasha Vujacic,NaN,NaN,4:41,97.8,100.0,0.0,0.0,97.8,100.0,0.000,0.00,0.0,0.000,0.143,0.067,0.0,0.000,0.347,0.231,0.246,77.95,87.18,72.65,9,0.250
31477,40900407,1610612747,LAL,Los Angeles,200769,Shannon Brown,NaN,NaN,5:25,71.7,63.6,82.0,72.7,-10.2,-9.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.077,0.085,86.49,97.48,81.23,11,-0.444
31478,40900407,1610612747,LAL,Los Angeles,2694,Josh Powell,NaN,NaN,0:34,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,84.46,126.69,105.57,2,0.000
31479,40900407,1610612747,LAL,Los Angeles,2788,DJ Mbenga,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
31480,40900407,1610612747,LAL,Los Angeles,2575,Luke Walton,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

<font color='red'> increase in the number of players in the nba over the 2010s????????</font>

In [70]:
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [71]:
#df2 and df_injuries merge to get, e.g. 2010-11 season injuries
df_games1011 = df2[df2.season == '2010-11']
df_games1011

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
4920,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
4921,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
4922,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
4923,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4924,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14928,41000402,2011-06-02,1610612748,0.765,240,34.0,73.0,0.466,9.0,30.0,0.300,16.0,24.0,1.0,6.0,24.0,30,13.0,15.0,6.0,12.0,17.0,93,2010.0,1610612742,0.765,240,36.0,75.0,0.480,6.0,17.0,0.353,17.0,21.0,1.0,11.0,30.0,41,18.0,8.0,2.0,18.0,20.0,95,Playoffs,2010-11
14929,41000403,2011-06-05,1610612742,0.722,240,28.0,70.0,0.400,8.0,21.0,0.381,22.0,27.0,1.0,12.0,30.0,42,18.0,3.0,8.0,14.0,14.0,86,2010.0,1610612748,0.778,240,34.0,78.0,0.436,8.0,19.0,0.421,12.0,15.0,1.0,9.0,27.0,36,20.0,8.0,5.0,10.0,27.0,88,Playoffs,2010-11
14930,41000404,2011-06-07,1610612742,0.737,240,29.0,73.0,0.397,4.0,19.0,0.211,24.0,30.0,1.0,12.0,29.0,41,13.0,7.0,2.0,11.0,18.0,86,2010.0,1610612748,0.737,240,32.0,75.0,0.427,2.0,14.0,0.143,17.0,24.0,1.0,15.0,29.0,44,19.0,8.0,5.0,13.0,23.0,83,Playoffs,2010-11
14931,41000405,2011-06-09,1610612742,0.750,240,39.0,69.0,0.565,13.0,19.0,0.684,21.0,27.0,1.0,4.0,22.0,26,23.0,8.0,3.0,11.0,20.0,112,2010.0,1610612748,0.700,240,37.0,70.0,0.529,8.0,20.0,0.400,21.0,26.0,1.0,9.0,27.0,36,25.0,5.0,4.0,16.0,26.0,103,Playoffs,2010-11
14932,41000406,2011-06-12,1610612748,0.667,240,34.0,72.0,0.472,7.0,23.0,0.304,20.0,33.0,1.0,9.0,30.0,39,20.0,7.0,3.0,16.0,14.0,95,2010.0,1610612742,0.762,240,41.0,82.0,0.500,11.0,26.0,0.423,12.0,18.0,1.0,10.0,30.0,40,19.0,11.0,1.0,14.0,24.0,105,Playoffs,2010-11

In [72]:
df_injuries.rename(columns={'Date':'game_date'})

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [73]:
#df_games1011[['game_id', 'game_date']]
pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011.game_date, on='game_date', how='right')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0.0
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0.0
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,1610612757,Joel Przybilla,0.0
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,1610612738,Avery Bradley,0.0
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,1610612738,Kendrick Perkins,0.0
...,...,...,...,...,...,...,...,...
23072,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,0.0
23073,2011-06-07,Mavericks,Brendan Haywood,,activated from IL,1610612742,Brendan Haywood,1.0
23074,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,0.0
23075,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1.0
23076,2011-06-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011.game_date, on='game_date', how='left')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
42720,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
42721,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
42722,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
42723,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
42724,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [75]:
df_injuries1011 = pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011[['game_date', 'game_id']], on='game_date', how='inner')
df_injuries1011

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000002
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000003
3,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0,21000001
4,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0,21000002
...,...,...,...,...,...,...,...,...,...
23043,2011-06-05,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000403
23044,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,0,41000404
23045,2011-06-07,Mavericks,Brendan Haywood,,activated from IL,1610612742,Brendan Haywood,1,41000404
23046,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,0,41000405
23047,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405

In [76]:
pd.merge(df_injuries1011, df_or1018.rename(columns={'GAME_ID':'game_id'})[['game_id', 'E_OFF_RATING']], how='left', on='game_id')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id,E_OFF_RATING
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,91.3
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,86.7
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,49.1
3,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,81.9
4,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,73.9
...,...,...,...,...,...,...,...,...,...,...
552292,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,115.3
552293,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,137.7
552294,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552295,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552296,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN

In [77]:
#filtered for games we have offensive rating
df_injuries1011_or = pd.merge(df_injuries1011, df_or1018.rename(columns={'GAME_ID':'game_id'})[['game_id', 'E_OFF_RATING']], how='inner', on='game_id')
df_injuries1011_or

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id,E_OFF_RATING
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,91.3
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,86.7
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,49.1
3,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,81.9
4,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,73.9
...,...,...,...,...,...,...,...,...,...,...
552292,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,115.3
552293,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,137.7
552294,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552295,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552296,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN

In [78]:
df_injuries1011_or.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 552297 entries, 0 to 552296
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   game_date     552297 non-null  datetime64[ns]
 1   Team          552297 non-null  object
 2   Acquired      552297 non-null  object
 3   Relinquished  552297 non-null  object
 4   Notes         552297 non-null  object
 5   team_id       552297 non-null  object
 6   player        552297 non-null  object
 7   A             552297 non-null  int64
 8   game_id       552297 non-null  int64
 9   E_OFF_RATING  469724 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 46.4+ MB

In [79]:
552297 - 469724

82573

In [80]:
#injury dataset for 2010-2018

#get average offensive rating per play for the 2009-2010 season for edge case: DataFrame w/ 'Player', 'Offensive Rating'

#injury dataset add a column for (average) offensive rating (for this season so far or previous season if data for this
#season if lacking
    #merge injury dataset with offensive rating data by date and player.
    
    #what does offensive rating look like for player not playing due to injury or just not playing?



#offensive rating

In [81]:

#Get game_date range for 2010-11 season by game dataset

#Get game_ids for 2010-11 season

#Get offensive rating per player per game by merge on game_id

#///

#From injuries df, want only player relinquished dates

#//

#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

#——->get player game_id, game_date for that season by merge relinquished players of df_injuries on df_or1011

In [82]:
#Get game_date range for 2010-11 season by game dataset

In [84]:
df2[df2.season == '2010-11']

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
4920,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
4921,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
4922,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
4923,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4924,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14928,41000402,2011-06-02,1610612748,0.765,240,34.0,73.0,0.466,9.0,30.0,0.300,16.0,24.0,1.0,6.0,24.0,30,13.0,15.0,6.0,12.0,17.0,93,2010.0,1610612742,0.765,240,36.0,75.0,0.480,6.0,17.0,0.353,17.0,21.0,1.0,11.0,30.0,41,18.0,8.0,2.0,18.0,20.0,95,Playoffs,2010-11
14929,41000403,2011-06-05,1610612742,0.722,240,28.0,70.0,0.400,8.0,21.0,0.381,22.0,27.0,1.0,12.0,30.0,42,18.0,3.0,8.0,14.0,14.0,86,2010.0,1610612748,0.778,240,34.0,78.0,0.436,8.0,19.0,0.421,12.0,15.0,1.0,9.0,27.0,36,20.0,8.0,5.0,10.0,27.0,88,Playoffs,2010-11
14930,41000404,2011-06-07,1610612742,0.737,240,29.0,73.0,0.397,4.0,19.0,0.211,24.0,30.0,1.0,12.0,29.0,41,13.0,7.0,2.0,11.0,18.0,86,2010.0,1610612748,0.737,240,32.0,75.0,0.427,2.0,14.0,0.143,17.0,24.0,1.0,15.0,29.0,44,19.0,8.0,5.0,13.0,23.0,83,Playoffs,2010-11
14931,41000405,2011-06-09,1610612742,0.750,240,39.0,69.0,0.565,13.0,19.0,0.684,21.0,27.0,1.0,4.0,22.0,26,23.0,8.0,3.0,11.0,20.0,112,2010.0,1610612748,0.700,240,37.0,70.0,0.529,8.0,20.0,0.400,21.0,26.0,1.0,9.0,27.0,36,25.0,5.0,4.0,16.0,26.0,103,Playoffs,2010-11
14932,41000406,2011-06-12,1610612748,0.667,240,34.0,72.0,0.472,7.0,23.0,0.304,20.0,33.0,1.0,9.0,30.0,39,20.0,7.0,3.0,16.0,14.0,95,2010.0,1610612742,0.762,240,41.0,82.0,0.500,11.0,26.0,0.423,12.0,18.0,1.0,10.0,30.0,40,19.0,11.0,1.0,14.0,24.0,105,Playoffs,2010-11

In [87]:
startdate_1011 = df2[df2.season == '2010-11'].game_date.min() 
startdate_1011

Timestamp('2010-10-26 00:00:00')

In [88]:
enddate_1011 = df2[df2.season == '2010-11'].game_date.max()
enddate_1011

Timestamp('2011-06-12 00:00:00')

In [89]:
#Get game_ids for 2010-11 season
game_ids_1011 = df2[df2.season == '2010-11'].game_id
game_ids_1011

4920     21000001
4921     21000002
4922     21000003
4923     21000004
4924     21000005
           ...
14928    41000402
14929    41000403
14930    41000404
14931    41000405
14932    41000406
Name: game_id, Length: 1311, dtype: int64

In [ ]:
#Get offensive rating per player per game by merge on game_id

In [97]:
#pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')
pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')[['game_id', 'TEAM_ID',
                                                                                        'PLAYER_NAME', 'E_OFF_RATING']]

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [107]:
df_or1011 = pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')[['game_id', 'PLAYER_NAME',
                                                                                        'E_OFF_RATING']]
df_or1011

        game_id    PLAYER_NAME  E_OFF_RATING
0      21000001   LeBron James          91.3
1      21000001     Chris Bosh          86.7
2      21000001   Joel Anthony          49.1
3      21000001    Dwyane Wade          81.9
4      21000001  Carlos Arroyo          73.9
...         ...            ...           ...
31414  41000406   Juwan Howard          85.0
31415  41000406    Eddie House          99.2
31416  41000406     Mike Bibby           NaN
31417  41000406  Erick Dampier           NaN
31418  41000406    James Jones           NaN

[31419 rows x 3 columns]

In [105]:
#From injuries df, want only player relinquished dates
df_injuries[df_injuries.Relinquished.notnull() & (df_injuries.Relinquished != '')]

,Date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin,0
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George,0
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala,0
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0

In [ ]:
#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

In [ ]:
#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

In [110]:
df_or1011

        game_id    PLAYER_NAME  E_OFF_RATING
0      21000001   LeBron James          91.3
1      21000001     Chris Bosh          86.7
2      21000001   Joel Anthony          49.1
3      21000001    Dwyane Wade          81.9
4      21000001  Carlos Arroyo          73.9
...         ...            ...           ...
31414  41000406   Juwan Howard          85.0
31415  41000406    Eddie House          99.2
31416  41000406     Mike Bibby           NaN
31417  41000406  Erick Dampier           NaN
31418  41000406    James Jones           NaN

[31419 rows x 3 columns]

In [114]:
df2[df2.season == '2010-11'][['game_id', 'game_date']]

        game_id  game_date
4920   21000001 2010-10-26
4921   21000002 2010-10-26
4922   21000003 2010-10-26
4923   21000004 2010-10-27
4924   21000005 2010-10-27
...         ...        ...
14928  41000402 2011-06-02
14929  41000403 2011-06-05
14930  41000404 2011-06-07
14931  41000405 2011-06-09
14932  41000406 2011-06-12

[1311 rows x 2 columns]

In [115]:
pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner')

        game_id    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001   LeBron James          91.3 2010-10-26
1      21000001     Chris Bosh          86.7 2010-10-26
2      21000001   Joel Anthony          49.1 2010-10-26
3      21000001    Dwyane Wade          81.9 2010-10-26
4      21000001  Carlos Arroyo          73.9 2010-10-26
...         ...            ...           ...        ...
31414  41000406   Juwan Howard          85.0 2011-06-12
31415  41000406    Eddie House          99.2 2011-06-12
31416  41000406     Mike Bibby           NaN 2011-06-12
31417  41000406  Erick Dampier           NaN 2011-06-12
31418  41000406    James Jones           NaN 2011-06-12

[31419 rows x 4 columns]

<font color='red'>this dataframe include player never injuried also??? -yes</font>

In [116]:
pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   PLAYER_NAME   31419 non-null  object
 2   E_OFF_RATING  26769 non-null  float64
 3   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 1.2+ MB

In [ ]:


#——->get player game_id, game_date for that season by merge relinquished players of df_injuries on df_or1011