In [1]:
#!jupyter notebook --NotebookApp.max_buffer_size=1610612736

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [3]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [4]:
df = pd.read_csv(os.path.join('..', 'raw_data', 'injuries_2010-2020.csv'), parse_dates=['Date'])
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

<font color='red'> </font>

In [5]:
df2 = pd.read_csv(os.path.join('..', 'processed_data', '3game_date_home_away.csv'), parse_dates=['game_date'])
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [6]:
df = df[(df.Date >= df2.game_date.min()) & (df.Date <= df2.game_date.max())]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [7]:
df.Team.value_counts().shape

(32,)

<font color='red'>  </font>

In [8]:
df.reset_index(drop=True)
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [9]:
print(df.Team.value_counts().shape)
df.Team.value_counts()

(32,)

Spurs           1070
Rockets          860
Nuggets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Knicks           783
Celtics          783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Bullets            1
Name: Team, dtype: int64

In [10]:
#Bullets and Hillard not in the nba
df = df[df.Team != 'Bullets']
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [11]:
df[df.Team.isnull()]

,Date,Team,Acquired,Relinquished,Notes
13007,2015-09-02,NaN,NaN,Glen Davis,surgery on left ankle to repair torn ligaments (out indefinitely)
13009,2015-09-03,NaN,NaN,Landry Fields,surgery on hip to repair torn labrum (out indefinitely)

In [12]:
#remove injured players not on a team. note: Davis & Fields do not return to an nba player roster
df = df[df.Team.notnull()]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [13]:
df.reset_index(drop=True)

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [14]:
df4 = pd.read_csv(os.path.join('..', 'processed_data', '6team_id_abbreviation_nickname.csv'))
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

In [15]:
df.shape

(22254, 5)

In [16]:
df_injuries = pd.merge(df, df4[['id', 'nickname']], left_on=['Team'], right_on=['nickname'], 
                       how='left').drop(columns='nickname')
df_injuries

,Date,Team,Acquired,Relinquished,Notes,id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [17]:
df_injuries.rename(columns={'id':'team_id'}, inplace=True)

In [18]:
print(df_injuries.shape)
df_injuries.head()

(22254, 6)

,Date,Team,Acquired,Relinquished,Notes,team_id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751

In [19]:
df_injuries.Team.value_counts()

Spurs           1070
Rockets          860
Nuggets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Celtics          783
Knicks           783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Name: Team, dtype: int64

In [82]:
print(df2.shape)
df2.head()

(15519, 47)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.0,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.0,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.0,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.0,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.0,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.0,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.0,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.0,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.0,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.5,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07

In [22]:
# df_injuries - team_id, player
# df2 - game_id, team_id, home and away stats
# nba_api player ratings/stats

In [23]:
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

In [24]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [25]:
df[df.Acquired.notnull() & df.Relinquished.notnull()]

            Date   Team       Acquired   Relinquished               Notes
21690 2018-03-23  Hawks  John Collins   John Collins   returned to lineup

In [26]:
df_injuries.Acquired = df_injuries.Acquired.fillna('')

In [27]:
df_injuries.Relinquished = df_injuries.Relinquished.fillna('')

In [28]:
df_injuries['player'] = df_injuries.Acquired + df_injuries.Relinquished

In [84]:
print(df_injuries.shape)
df_injuries.head()

(22254, 7)

,Date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy

In [86]:
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [32]:
#df2 and df_injuries merge to get, e.g. 2010-11 season injuries
df_games1011 = df2[df2.season == '2010-11']
df_games1011

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
4920,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
4921,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
4922,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
4923,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4924,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14928,41000402,2011-06-02,1610612748,0.765,240,34.0,73.0,0.466,9.0,30.0,0.300,16.0,24.0,1.0,6.0,24.0,30,13.0,15.0,6.0,12.0,17.0,93,2010.0,1610612742,0.765,240,36.0,75.0,0.480,6.0,17.0,0.353,17.0,21.0,1.0,11.0,30.0,41,18.0,8.0,2.0,18.0,20.0,95,Playoffs,2010-11
14929,41000403,2011-06-05,1610612742,0.722,240,28.0,70.0,0.400,8.0,21.0,0.381,22.0,27.0,1.0,12.0,30.0,42,18.0,3.0,8.0,14.0,14.0,86,2010.0,1610612748,0.778,240,34.0,78.0,0.436,8.0,19.0,0.421,12.0,15.0,1.0,9.0,27.0,36,20.0,8.0,5.0,10.0,27.0,88,Playoffs,2010-11
14930,41000404,2011-06-07,1610612742,0.737,240,29.0,73.0,0.397,4.0,19.0,0.211,24.0,30.0,1.0,12.0,29.0,41,13.0,7.0,2.0,11.0,18.0,86,2010.0,1610612748,0.737,240,32.0,75.0,0.427,2.0,14.0,0.143,17.0,24.0,1.0,15.0,29.0,44,19.0,8.0,5.0,13.0,23.0,83,Playoffs,2010-11
14931,41000405,2011-06-09,1610612742,0.750,240,39.0,69.0,0.565,13.0,19.0,0.684,21.0,27.0,1.0,4.0,22.0,26,23.0,8.0,3.0,11.0,20.0,112,2010.0,1610612748,0.700,240,37.0,70.0,0.529,8.0,20.0,0.400,21.0,26.0,1.0,9.0,27.0,36,25.0,5.0,4.0,16.0,26.0,103,Playoffs,2010-11
14932,41000406,2011-06-12,1610612748,0.667,240,34.0,72.0,0.472,7.0,23.0,0.304,20.0,33.0,1.0,9.0,30.0,39,20.0,7.0,3.0,16.0,14.0,95,2010.0,1610612742,0.762,240,41.0,82.0,0.500,11.0,26.0,0.423,12.0,18.0,1.0,10.0,30.0,40,19.0,11.0,1.0,14.0,24.0,105,Playoffs,2010-11

In [33]:
df_injuries.rename(columns={'Date':'game_date'})

,game_date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala

In [34]:
#df_games1011[['game_id', 'game_date']]
pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011.game_date, on='game_date', how='right')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1.610613e+09,Elliot Williams
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1.610613e+09,Greg Oden
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,1.610613e+09,Joel Przybilla
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,1.610613e+09,Avery Bradley
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,1.610613e+09,Kendrick Perkins
...,...,...,...,...,...,...,...
23072,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1.610613e+09,Rodrigue Beaubois
23073,2011-06-07,Mavericks,Brendan Haywood,,activated from IL,1.610613e+09,Brendan Haywood
23074,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1.610613e+09,Brendan Haywood
23075,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1.610613e+09,Rodrigue Beaubois
23076,2011-06-12,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011.game_date, on='game_date', how='left')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
42720,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
42721,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love
42722,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw
42723,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love
42724,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala

In [36]:
df_injuries1011 = pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011[['game_date', 'game_id']], on='game_date', how='inner')
df_injuries1011

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000002
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000003
3,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,21000001
4,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,21000002
...,...,...,...,...,...,...,...,...
23043,2011-06-05,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000403
23044,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,41000404
23045,2011-06-07,Mavericks,Brendan Haywood,,activated from IL,1610612742,Brendan Haywood,41000404
23046,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,41000405
23047,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405

In [37]:
df_or1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2010_2018.csv'))
df_or1018

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [38]:
df_or1018[df_or1018.PLAYER_NAME.fillna('').str.contains('Hillard')]

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, TEAM_ABBREVIATION, TEAM_CITY, PLAYER_ID, PLAYER_NAME, START_POSITION, COMMENT, MIN, E_OFF_RATING, OFF_RATING, E_DEF_RATING, DEF_RATING, E_NET_RATING, NET_RATING, AST_PCT, AST_TOV, AST_RATIO, OREB_PCT, DREB_PCT, REB_PCT, TM_TOV_PCT, EFG_PCT, TS_PCT, USG_PCT, E_USG_PCT, E_PACE, PACE, PACE_PER40, POSS, PIE]
Index: []

In [39]:
df_or1018.PLAYER_NAME.fillna('')

0              Paul Pierce
1            Kevin Garnett
2         Kendrick Perkins
3                Ray Allen
4              Rajon Rondo
                ...
291638     Larry Nance Jr.
291639          Cedi Osman
291640       Jose Calderon
291641          Ante Zizic
291642     Jordan Clarkson
Name: PLAYER_NAME, Length: 291643, dtype: object

In [40]:
df_or1018[df_or1018.PLAYER_NAME.fillna('').str.contains('Perkins')]

         GAME_ID       TEAM_ID TEAM_ABBREVIATION      TEAM_CITY  PLAYER_ID  \
2       20900001  1.610613e+09               BOS         Boston     2570.0
182     20900008  1.610613e+09               BOS         Boston     2570.0
516     20900022  1.610613e+09               BOS         Boston     2570.0
948     20900040  1.610613e+09               BOS         Boston     2570.0
1247    20900053  1.610613e+09               BOS         Boston     2570.0
1534    20900065  1.610613e+09               BOS         Boston     2570.0
1809    20900076  1.610613e+09               BOS         Boston     2570.0
2037    20900086  1.610613e+09               BOS         Boston     2570.0
2645    20900111  1.610613e+09               BOS         Boston     2570.0
3029    20900127  1.610613e+09               BOS         Boston     2570.0
3208    20900135  1.610613e+09               BOS         Boston     2570.0
3891    20900163  1.610613e+09               BOS         Boston     2570.0
4225    20900177  1.610613e+09               BOS         Boston     2570.0
4597    20900193  1.610613e+09               BOS         Boston     2570.0
5017    20900210  1.610613e+09               BOS         Boston     2570.0
5376    20900225  1.610613e+09               BOS         Boston     2570.0
5772    20900242  1.610613e+09               BOS         Boston     2570.0
6036    20900253  1.610613e+09               BOS         Boston     2570.0
6419    20900269  1.610613e+09               BOS         Boston     2570.0
6658    20900279  1.610613e+09               BOS         Boston     2570.0
7221    20900302  1.610613e+09               BOS         Boston     2570.0
7591    20900318  1.610613e+09               BOS         Boston     2570.0
7950    20900333  1.610613e+09               BOS         Boston     2570.0
8261    20900346  1.610613e+09               BOS         Boston     2570.0
8969    20900375  1.610613e+09               BOS         Boston     2570.0
9449    20900395  1.610613e+09               BOS         Boston     2570.0
9737    20900407  1.610613e+09               BOS         Boston     2570.0
10155   20900425  1.610613e+09               BOS         Boston     2570.0
10613   20900444  1.610613e+09               BOS         Boston     2570.0
10783   20900451  1.610613e+09               BOS         Boston     2570.0
11143   20900466  1.610613e+09               BOS         Boston     2570.0
11517   20900481  1.610613e+09               BOS         Boston     2570.0
12203   20900510  1.610613e+09               BOS         Boston     2570.0
12442   20900520  1.610613e+09               BOS         Boston     2570.0
12873   20900538  1.610613e+09               BOS         Boston     2570.0
13077   20900546  1.610613e+09               BOS         Boston     2570.0
13424   20900561  1.610613e+09               BOS         Boston     2570.0
13628   20900569  1.610613e+09               BOS         Boston     2570.0
14472   20900604  1.610613e+09               BOS         Boston     2570.0
14675   20900613  1.610613e+09               BOS         Boston     2570.0
15045   20900628  1.610613e+09               BOS         Boston     2570.0
15573   20900650  1.610613e+09               BOS         Boston     2570.0
16162   20900675  1.610613e+09               BOS         Boston     2570.0
16258   20900679  1.610613e+09               BOS         Boston     2570.0
16678   20900696  1.610613e+09               BOS         Boston     2570.0
16859   20900704  1.610613e+09               BOS         Boston     2570.0
17303   20900722  1.610613e+09               BOS         Boston     2570.0
17567   20900733  1.610613e+09               BOS         Boston     2570.0
18072   20900754  1.610613e+09               BOS         Boston     2570.0
18565   20900775  1.610613e+09               BOS         Boston     2570.0
18905   20900789  1.610613e+09               BOS         Boston     2570.0
19243   20900803  1.610613e+09               BOS         Boston     2570.0
19530   20900815  1.610613e+09               BOS         Boston     2570.0
19744   20900824  1.610613e+09               BOS         Boston     2570.0
20091   20900838  1.610613e+09               BOS         Boston     2570.0
20548   20900857  1.610613e+09               BOS         Boston     2570.0
20884   20900871  1.610613e+09               BOS         Boston     2570.0
21604   20900901  1.610613e+09               BOS         Boston     2570.0
21952   20900916  1.610613e+09               BOS         Boston     2570.0
22468   20900937  1.610613e+09               BOS         Boston     2570.0
22768   20900950  1.610613e+09               BOS         Boston     2570.0
22876   20900954  1.610613e+09               BOS         Boston     2570.0
23164   20900966  1.610613e+09               BOS         Boston     2570.0
23584   20900984  1.610613e+09               BOS         Boston     2570.0
23789   20900992  1.610613e+09               BOS         Boston     2570.0
24197   20901009  1.610613e+09               BOS         Boston     2570.0
24521   20901023  1.610613e+09               BOS         Boston     2570.0
24761   20901033  1.610613e+09               BOS         Boston     2570.0
25170   20901050  1.610613e+09               BOS         Boston     2570.0
25374   20901058  1.610613e+09               BOS         Boston     2570.0
26647   20901111  1.610613e+09               BOS         Boston     2570.0
26983   20901125  1.610613e+09               BOS         Boston     2570.0
27367   20901141  1.610613e+09               BOS         Boston     2570.0
27643   20901153  1.610613e+09               BOS         Boston     2570.0
27787   20901159  1.610613e+09               BOS         Boston     2570.0
28231   20901177  1.610613e+09               BOS         Boston     2570.0
28555   20901191  1.610613e+09               BOS         Boston     2570.0
29083   20901213  1.610613e+09               BOS         Boston     2570.0
29223   20901218  1.610613e+09               BOS         Boston     2570.0
45421   21000664  1.610613e+09               BOS         Boston     2570.0
45793   21000680  1.610613e+09               BOS         Boston     2570.0
46033   21000690  1.610613e+09               BOS         Boston     2570.0
46322   21000702  1.610613e+09               BOS         Boston     2570.0
46682   21000717  1.610613e+09               BOS         Boston     2570.0
47243   21000740  1.610613e+09               BOS         Boston     2570.0
47650   21000757  1.610613e+09               BOS         Boston     2570.0
47662   21000758  1.610613e+09               BOS         Boston     2570.0
48271   21000783  1.610613e+09               BOS         Boston     2570.0
48774   21000804  1.610613e+09               BOS         Boston     2570.0
49300   21000826  1.610613e+09               BOS         Boston     2570.0
49744   21000845  1.610613e+09               BOS         Boston     2570.0
50111   21000860  1.610613e+09               BOS         Boston     2570.0
53259   21000992  1.610613e+09               OKC  Oklahoma City     2570.0
53595   21001006  1.610613e+09               OKC  Oklahoma City     2570.0
53991   21001022  1.610613e+09               OKC  Oklahoma City     2570.0
54447   21001041  1.610613e+09               OKC  Oklahoma City     2570.0
54926   21001061  1.610613e+09               OKC  Oklahoma City     2570.0
55262   21001075  1.610613e+09               OKC  Oklahoma City     2570.0
55668   21001092  1.610613e+09               OKC  Oklahoma City     2570.0
55932   21001103  1.610613e+09               OKC  Oklahoma City     2570.0
56232   21001116  1.610613e+09               OKC  Oklahoma City     2570.0
56568   21001130  1.610613e+09               OKC  Oklahoma City     2570.0
56736   21001137  1.610613e+09               OKC  Oklahoma City     2570.0
57263   21001159  1.610613e+09               OKC  Oklahoma City     2570.0
57539   21001170  1.610613e+09               OKC  Oklahoma City     2570.0
57899   21001185  1.610613e+09               OKC  Oklahoma City     2570.0
58270   21001201  1.610613e+09               OKC  Oklahoma City     2570.0
58534   21001212  1.610613e+09               OKC  Oklahoma City     2570.0
58858   21001225  1.610613e+09               OKC  Oklahoma City     2570.0
59081   21100004  1.610613e+09               OKC  Oklahoma City     2570.0
59248   21100011  1.610613e+09               OKC  Oklahoma City     2570.0
59660   21100027  1.610613e+09               OKC  Oklahoma City     2570.0
59878   21100035  1.610613e+09               OKC  Oklahoma City     2570.0
60339   21100053  1.610613e+09               OKC  Oklahoma City     2570.0
60841   21100073  1.610613e+09               OKC  Oklahoma City     2570.0
61009   21100079  1.610613e+09               OKC  Oklahoma City     2570.0
61676   21100105  1.610613e+09               OKC  Oklahoma City     2570.0
61920   21100115  1.610613e+09               OKC  Oklahoma City     2570.0
62111   21100122  1.610613e+09               OKC  Oklahoma City     2570.0
62482   21100137  1.610613e+09               OKC  Oklahoma City     2570.0
62766   21100148  1.610613e+09               OKC  Oklahoma City     2570.0
63528   21100177  1.610613e+09               OKC  Oklahoma City     2570.0
63903   21100192  1.610613e+09               OKC  Oklahoma City     2570.0
64187   21100203  1.610613e+09               OKC  Oklahoma City     2570.0
64906   21100231  1.610613e+09               OKC  Oklahoma City     2570.0
65329   21100247  1.610613e+09               OKC  Oklahoma City     2570.0
65743   21100263  1.610613e+09               OKC  Oklahoma City     2570.0
66272   21100284  1.610613e+09               OKC  Oklahoma City     2570.0
66865   21100307  1.610613e+09               OKC  Oklahoma City     2570.0
67226   21100321  1.610613e+09               OKC  Oklahoma City     2570.0
67701   21100339  1.610613e+09               OKC  Oklahoma City     2570.0
67972   21100350  1.610613e+09               OKC  Oklahoma City     2570.0
68383   21100366  1.610613e+09               OKC  Oklahoma City     2570.0
68537   21100372  1.610613e+09               OKC  Oklahoma City     2570.0
68922   21100387  1.610613e+09               OKC  Oklahoma City     2570.0
69232   21100399  1.610613e+09               OKC  Oklahoma City     2570.0
69912   21100425  1.610613e+09               OKC  Oklahoma City     2570.0
70181   21100436  1.610613e+09               OKC  Oklahoma City     2570.0
70641   21100453  1.610613e+09               OKC  Oklahoma City     2570.0
71017   21100468  1.610613e+09               OKC  Oklahoma City     2570.0
71195   21100475  1.610613e+09               OKC  Oklahoma City     2570.0
71579   21100490  1.610613e+09               OKC  Oklahoma City     2570.0
71886   21100502  1.610613e+09               OKC  Oklahoma City     2570.0
72132   21100512  1.610613e+09               OKC  Oklahoma City     2570.0
72440   21100524  1.610613e+09               OKC  Oklahoma City     2570.0
72852   21100540  1.610613e+09               OKC  Oklahoma City     2570.0
73353   21100559  1.610613e+09               OKC  Oklahoma City     2570.0
73794   21100576  1.610613e+09               OKC  Oklahoma City     2570.0
74103   21100588  1.610613e+09               OKC  Oklahoma City     2570.0
74387   21100599  1.610613e+09               OKC  Oklahoma City     2570.0
74979   21100622  1.610613e+09               OKC  Oklahoma City     2570.0
75427   21100640  1.610613e+09               OKC  Oklahoma City     2570.0
75667   21100649  1.610613e+09               OKC  Oklahoma City     2570.0
76151   21100668  1.610613e+09               OKC  Oklahoma City     2570.0
76446   21100680  1.610613e+09               OKC  Oklahoma City     2570.0
76687   21100689  1.610613e+09               OKC  Oklahoma City     2570.0
77123   21100706  1.610613e+09               OKC  Oklahoma City     2570.0
77582   21100724  1.610613e+09               OKC  Oklahoma City     2570.0
78004   21100741  1.610613e+09               OKC  Oklahoma City     2570.0
78387   21100756  1.610613e+09               OKC  Oklahoma City     2570.0
78939   21100777  1.610613e+09               OKC  Oklahoma City     2570.0
79194   21100787  1.610613e+09               OKC  Oklahoma City     2570.0
79593   21100803  1.610613e+09               OKC  Oklahoma City     2570.0
79904   21100815  1.610613e+09               OKC  Oklahoma City     2570.0
80560   21100840  1.610613e+09               OKC  Oklahoma City     2570.0
80676   21100845  1.610613e+09               OKC  Oklahoma City     2570.0
81205   21100865  1.610613e+09               OKC  Oklahoma City     2570.0
81667   21100883  1.610613e+09               OKC  Oklahoma City     2570.0
81834   21100890  1.610613e+09               OKC  Oklahoma City     2570.0
82376   21100911  1.610613e+09               OKC  Oklahoma City     2570.0
82816   21100928  1.610613e+09               OKC  Oklahoma City     2570.0
83178   21100942  1.610613e+09               OKC  Oklahoma City     2570.0
83439   21100952  1.610613e+09               OKC  Oklahoma City     2570.0
83865   21100968  1.610613e+09               OKC  Oklahoma City     2570.0
84073   21100976  1.610613e+09               OKC  Oklahoma City     2570.0
84778   21200014  1.610613e+09               OKC  Oklahoma City     2570.0
84998   21200022  1.610613e+09               OKC  Oklahoma City     2570.0
85461   21200040  1.610613e+09               OKC  Oklahoma City     2570.0
85744   21200051  1.610613e+09               OKC  Oklahoma City     2570.0
86119   21200066  1.610613e+09               OKC  Oklahoma City     2570.0
86362   21200075  1.610613e+09               OKC  Oklahoma City     2570.0
86827   21200093  1.610613e+09               OKC  Oklahoma City     2570.0
86917   21200097  1.610613e+09               OKC  Oklahoma City     2570.0
87340   21200113  1.610613e+09               OKC  Oklahoma City     2570.0
87633   21200125  1.610613e+09               OKC  Oklahoma City     2570.0
88106   21200143  1.610613e+09               OKC  Oklahoma City     2570.0
88639   21200164  1.610613e+09               OKC  Oklahoma City     2570.0
88856   21200173  1.610613e+09               OKC  Oklahoma City     2570.0
89107   21200183  1.610613e+09               OKC  Oklahoma City     2570.0
89577   21200201  1.610613e+09               OKC  Oklahoma City     2570.0
90006   21200218  1.610613e+09               OKC  Oklahoma City     2570.0
90287   21200229  1.610613e+09               OKC  Oklahoma City     2570.0
90451   21200236  1.610613e+09               OKC  Oklahoma City     2570.0
90883   21200253  1.610613e+09               OKC  Oklahoma City     2570.0
91576   21200280  1.610613e+09               OKC  Oklahoma City     2570.0
91928   21200294  1.610613e+09               OKC  Oklahoma City     2570.0
92534   21200318  1.610613e+09               OKC  Oklahoma City     2570.0
92914   21200333  1.610613e+09               OKC  Oklahoma City     2570.0
93443   21200354  1.610613e+09               OKC  Oklahoma City     2570.0
93867   21200371  1.610613e+09               OKC  Oklahoma City     2570.0
94018   21200377  1.610613e+09               OKC  Oklahoma City     2570.0
94783   21200407  1.610613e+09               OKC  Oklahoma City     2570.0
95202   21200423  1.610613e+09               OKC  Oklahoma City     2570.0
95697   21200443  1.610613e+09               OKC  Oklahoma City     2570.0
96039   21200456  1.610613e+09               OKC  Oklahoma City     2570.0
96450   21200472  1.610613e+09               OKC  Oklahoma City     2570.0
96780   21200485  1.610613e+09               OKC  Oklahoma City     2570.0
97121   21200499  1.610613e+09               OKC  Oklahoma City     2570.0
97246   21200504  1.610613e+09               OKC  Oklahoma City     2570.0
97739   21200523  1.610613e+09               OKC  Oklahoma City     2570.0
98133   21200539  1.610613e+09               OKC  Oklahoma City     2570.0
98519   21200554  1.610613e+09               OKC  Oklahoma City     2570.0
98723   21200562  1.610613e+09               OKC  Oklahoma City     2570.0
99045   21200574  1.610613e+09               OKC  Oklahoma City     2570.0
99495   21200592  1.610613e+09               OKC  Oklahoma City     2570.0
99802   21200604  1.610613e+09               OKC  Oklahoma City     2570.0
100133  21200617  1.610613e+09               OKC  Oklahoma City     2570.0
100409  21200628  1.610613e+09               OKC  Oklahoma City     2570.0
100714  21200640  1.610613e+09               OKC  Oklahoma City     2570.0
101047  21200653  1.610613e+09               OKC  Oklahoma City     2570.0
101802  21200682  1.610613e+09               OKC  Oklahoma City     2570.0
102200  21200698  1.610613e+09               OKC  Oklahoma City     2570.0
102574  21200712  1.610613e+09               OKC  Oklahoma City     2570.0
103011  21200729  1.610613e+09               OKC  Oklahoma City     2570.0
103396  21200744  1.610613e+09               OKC  Oklahoma City     2570.0
103766  21200759  1.610613e+09               OKC  Oklahoma City     2570.0
104098  21200772  1.610613e+09               OKC  Oklahoma City     2570.0
104492  21200787  1.610613e+09               OKC  Oklahoma City     2570.0
105304  21200819  1.610613e+09               OKC  Oklahoma City     2570.0
105782  21200838  1.610613e+09               OKC  Oklahoma City     2570.0
106268  21200857  1.610613e+09               OKC  Oklahoma City     2570.0
106716  21200875  1.610613e+09               OKC  Oklahoma City     2570.0
106867  21200881  1.610613e+09               OKC  Oklahoma City     2570.0
107289  21200897  1.610613e+09               OKC  Oklahoma City     2570.0
107686  21200913  1.610613e+09               OKC  Oklahoma City     2570.0
107738  21200915  1.610613e+09               OKC  Oklahoma City     2570.0
108237  21200934  1.610613e+09               OKC  Oklahoma City     2570.0
108479  21200944  1.610613e+09               OKC  Oklahoma City     2570.0
108952  21200962  1.610613e+09               OKC  Oklahoma City     2570.0
109259  21200974  1.610613e+09               OKC  Oklahoma City     2570.0
109652  21200990  1.610613e+09               OKC  Oklahoma City     2570.0
110070  21201006  1.610613e+09               OKC  Oklahoma City     2570.0
110212  21201012  1.610613e+09               OKC  Oklahoma City     2570.0
110494  21201023  1.610613e+09               OKC  Oklahoma City     2570.0
111018  21201043  1.610613e+09               OKC  Oklahoma City     2570.0
111580  21201065  1.610613e+09               OKC  Oklahoma City     2570.0
111979  21201081  1.610613e+09               OKC  Oklahoma City     2570.0
112212  21201090  1.610613e+09               OKC  Oklahoma City     2570.0
113119  21201125  1.610613e+09               OKC  Oklahoma City     2570.0
113234  21201130  1.610613e+09               OKC  Oklahoma City     2570.0
113631  21201145  1.610613e+09               OKC  Oklahoma City     2570.0
114028  21201161  1.610613e+09               OKC  Oklahoma City     2570.0
114385  21201175  1.610613e+09               OKC  Oklahoma City     2570.0
114724  21201188  1.610613e+09               OKC  Oklahoma City     2570.0
115679  21201226  1.610613e+09               OKC  Oklahoma City     2570.0
116120  21300014  1.610613e+09               OKC  Oklahoma City     2570.0
116454  21300027  1.610613e+09               OKC  Oklahoma City     2570.0
116905  21300044  1.610613e+09               OKC  Oklahoma City     2570.0
117549  21300069  1.610613e+09               OKC  Oklahoma City     2570.0
117769  21300078  1.610613e+09               OKC  Oklahoma City     2570.0
118219  21300095  1.610613e+09               OKC  Oklahoma City     2570.0
119469  21300144  1.610613e+09               OKC  Oklahoma City     2570.0
119687  21300152  1.610613e+09               OKC  Oklahoma City     2570.0
120254  21300174  1.610613e+09               OKC  Oklahoma City     2570.0
120922  21300200  1.610613e+09               OKC  Oklahoma City     2570.0

In [41]:
pd.merge(df_injuries1011, df_or1018.rename(columns={'GAME_ID':'game_id'})[['game_id', 'E_OFF_RATING']], how='left', on='game_id')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id,E_OFF_RATING
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,91.3
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,86.7
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,49.1
3,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,81.9
4,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,73.9
...,...,...,...,...,...,...,...,...,...
552292,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,115.3
552293,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,137.7
552294,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN
552295,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN
552296,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN

In [42]:
#filtered for games we have offensive rating
df_injuries1011_or = pd.merge(df_injuries1011, df_or1018.rename(columns={'GAME_ID':'game_id'})[['game_id', 'E_OFF_RATING']], how='inner', on='game_id')
df_injuries1011_or

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id,E_OFF_RATING
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,91.3
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,86.7
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,49.1
3,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,81.9
4,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,73.9
...,...,...,...,...,...,...,...,...,...
552292,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,115.3
552293,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,137.7
552294,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN
552295,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN
552296,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN

In [43]:
df_injuries1011_or.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 552297 entries, 0 to 552296
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   game_date     552297 non-null  datetime64[ns]
 1   Team          552297 non-null  object
 2   Acquired      552297 non-null  object
 3   Relinquished  552297 non-null  object
 4   Notes         552297 non-null  object
 5   team_id       552297 non-null  int64
 6   player        552297 non-null  object
 7   game_id       552297 non-null  int64
 8   E_OFF_RATING  469724 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 42.1+ MB

In [44]:
552297 - 469724

82573

In [45]:
#injury dataset for 2010-2018

#get average offensive rating per play for the 2009-2010 season for edge case: DataFrame w/ 'Player', 'Offensive Rating'

#injury dataset add a column for (average) offensive rating (for this season so far or previous season if data for this
#season if lacking
    #merge injury dataset with offensive rating data by date and player.
    
    #what does offensive rating look like for player not playing due to injury or just not playing?



#offensive rating

In [46]:

#Get game_date range for 2010-11 season by game dataset

#Get game_ids for 2010-11 season

#Get offensive rating per player per game by merge on game_id

#///

#From injuries df, want only player relinquished dates

#//

#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

#——->get player game_id, game_date for that season by merge relinquished players of df_injuries on df_or1011

In [47]:
#Get game_date range for 2010-11 season by game dataset

In [48]:
df2[df2.season == '2010-11']

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
4920,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
4921,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
4922,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
4923,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4924,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14928,41000402,2011-06-02,1610612748,0.765,240,34.0,73.0,0.466,9.0,30.0,0.300,16.0,24.0,1.0,6.0,24.0,30,13.0,15.0,6.0,12.0,17.0,93,2010.0,1610612742,0.765,240,36.0,75.0,0.480,6.0,17.0,0.353,17.0,21.0,1.0,11.0,30.0,41,18.0,8.0,2.0,18.0,20.0,95,Playoffs,2010-11
14929,41000403,2011-06-05,1610612742,0.722,240,28.0,70.0,0.400,8.0,21.0,0.381,22.0,27.0,1.0,12.0,30.0,42,18.0,3.0,8.0,14.0,14.0,86,2010.0,1610612748,0.778,240,34.0,78.0,0.436,8.0,19.0,0.421,12.0,15.0,1.0,9.0,27.0,36,20.0,8.0,5.0,10.0,27.0,88,Playoffs,2010-11
14930,41000404,2011-06-07,1610612742,0.737,240,29.0,73.0,0.397,4.0,19.0,0.211,24.0,30.0,1.0,12.0,29.0,41,13.0,7.0,2.0,11.0,18.0,86,2010.0,1610612748,0.737,240,32.0,75.0,0.427,2.0,14.0,0.143,17.0,24.0,1.0,15.0,29.0,44,19.0,8.0,5.0,13.0,23.0,83,Playoffs,2010-11
14931,41000405,2011-06-09,1610612742,0.750,240,39.0,69.0,0.565,13.0,19.0,0.684,21.0,27.0,1.0,4.0,22.0,26,23.0,8.0,3.0,11.0,20.0,112,2010.0,1610612748,0.700,240,37.0,70.0,0.529,8.0,20.0,0.400,21.0,26.0,1.0,9.0,27.0,36,25.0,5.0,4.0,16.0,26.0,103,Playoffs,2010-11
14932,41000406,2011-06-12,1610612748,0.667,240,34.0,72.0,0.472,7.0,23.0,0.304,20.0,33.0,1.0,9.0,30.0,39,20.0,7.0,3.0,16.0,14.0,95,2010.0,1610612742,0.762,240,41.0,82.0,0.500,11.0,26.0,0.423,12.0,18.0,1.0,10.0,30.0,40,19.0,11.0,1.0,14.0,24.0,105,Playoffs,2010-11

In [49]:
startdate_1011 = df2[df2.season == '2010-11'].game_date.min() 
startdate_1011

Timestamp('2010-10-26 00:00:00')

In [50]:
enddate_1011 = df2[df2.season == '2010-11'].game_date.max()
enddate_1011

Timestamp('2011-06-12 00:00:00')

In [51]:
#Get game_ids for 2010-11 season
game_ids_1011 = df2[df2.season == '2010-11'].game_id
game_ids_1011

4920     21000001
4921     21000002
4922     21000003
4923     21000004
4924     21000005
           ...
14928    41000402
14929    41000403
14930    41000404
14931    41000405
14932    41000406
Name: game_id, Length: 1311, dtype: int64

In [52]:
#Get offensive rating per player per game by merge on game_id

In [53]:
#pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')
pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')[['game_id', 'TEAM_ID',
                                                                                        'PLAYER_NAME', 'E_OFF_RATING']]

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [54]:
df_or1011 = pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')[['game_id', 'TEAM_ID','PLAYER_NAME',
                                                                                        'E_OFF_RATING']]
df_or1011

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [55]:
#From injuries df, want only player relinquished dates
df_inj = df_injuries[df_injuries.Relinquished.notnull() & (df_injuries.Relinquished != '')]
df_inj

,Date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love

In [56]:
#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

In [57]:
#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

In [58]:
df_or1011

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [59]:
df2[df2.season == '2010-11'][['game_id', 'game_date']]

        game_id  game_date
4920   21000001 2010-10-26
4921   21000002 2010-10-26
4922   21000003 2010-10-26
4923   21000004 2010-10-27
4924   21000005 2010-10-27
...         ...        ...
14928  41000402 2011-06-02
14929  41000403 2011-06-05
14930  41000404 2011-06-07
14931  41000405 2011-06-09
14932  41000406 2011-06-12

[1311 rows x 2 columns]

In [60]:
pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner')

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1.610613e+09   LeBron James          91.3 2010-10-26
1      21000001  1.610613e+09     Chris Bosh          86.7 2010-10-26
2      21000001  1.610613e+09   Joel Anthony          49.1 2010-10-26
3      21000001  1.610613e+09    Dwyane Wade          81.9 2010-10-26
4      21000001  1.610613e+09  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1.610613e+09   Juwan Howard          85.0 2011-06-12
31415  41000406  1.610613e+09    Eddie House          99.2 2011-06-12
31416  41000406  1.610613e+09     Mike Bibby           NaN 2011-06-12
31417  41000406  1.610613e+09  Erick Dampier           NaN 2011-06-12
31418  41000406  1.610613e+09    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

<font color='red'>this dataframe include player never injuried also??? -yes</font>

In [61]:
df_or1011a = pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner')
df_or1011a

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1.610613e+09   LeBron James          91.3 2010-10-26
1      21000001  1.610613e+09     Chris Bosh          86.7 2010-10-26
2      21000001  1.610613e+09   Joel Anthony          49.1 2010-10-26
3      21000001  1.610613e+09    Dwyane Wade          81.9 2010-10-26
4      21000001  1.610613e+09  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1.610613e+09   Juwan Howard          85.0 2011-06-12
31415  41000406  1.610613e+09    Eddie House          99.2 2011-06-12
31416  41000406  1.610613e+09     Mike Bibby           NaN 2011-06-12
31417  41000406  1.610613e+09  Erick Dampier           NaN 2011-06-12
31418  41000406  1.610613e+09    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

In [62]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  float64
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 1.4+ MB

In [63]:
df_or1011a.TEAM_ID = df_or1011a.TEAM_ID.astype(str)
df_or1011a

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1610612748.0   LeBron James          91.3 2010-10-26
1      21000001  1610612748.0     Chris Bosh          86.7 2010-10-26
2      21000001  1610612748.0   Joel Anthony          49.1 2010-10-26
3      21000001  1610612748.0    Dwyane Wade          81.9 2010-10-26
4      21000001  1610612748.0  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1610612748.0   Juwan Howard          85.0 2011-06-12
31415  41000406  1610612748.0    Eddie House          99.2 2011-06-12
31416  41000406  1610612748.0     Mike Bibby           NaN 2011-06-12
31417  41000406  1610612748.0  Erick Dampier           NaN 2011-06-12
31418  41000406  1610612748.0    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

In [64]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  object
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 1.4+ MB

In [65]:
df_or1011a['cma1'] = df_or1011a.E_OFF_RATING.expanding(min_periods=1).mean()
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451

In [66]:
df_or1011a['cma2'] = df_or1011a.groupby('PLAYER_NAME')['E_OFF_RATING'].transform(lambda x: x.expanding(min_periods=1).mean())
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000,73.900000
...,...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451,108.415054

In [67]:
df_or1011a[df_or1011a.PLAYER_NAME == 'LeBron James']

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000,91.300000
120,21000006,1610612748.0,LeBron James,97.9,2010-10-27,97.423000,94.600000
588,21000025,1610612748.0,LeBron James,109.5,2010-10-29,98.944595,99.566667
936,21000040,1610612748.0,LeBron James,115.5,2010-10-31,98.244417,103.550000
1188,21000050,1610612748.0,LeBron James,135.6,2010-11-02,98.431947,109.960000
1776,21000075,1610612748.0,LeBron James,97.9,2010-11-05,99.656023,107.950000
1956,21000082,1610612748.0,LeBron James,109.3,2010-11-06,99.492496,108.142857
2460,21000103,1610612748.0,LeBron James,112.9,2010-11-09,99.999164,108.737500
2819,21000118,1610612748.0,LeBron James,116.5,2010-11-11,100.054251,109.600000
3179,21000133,1610612748.0,LeBron James,118.7,2010-11-13,100.456531,110.510000
3779,21000158,1610612748.0,LeBron James,132.4,2010-11-17,100.808953,112.500000
4187,21000175,1610612748.0,LeBron James,103.1,2010-11-19,100.528282,111.716667
4415,21000185,1610612748.0,LeBron James,109.9,2010-11-20,100.655033,111.576923
4690,21000196,1610612748.0,LeBron James,83.5,2010-11-22,100.741624,109.571429
5086,21000213,1610612748.0,LeBron James,98.5,2010-11-24,100.608179,108.833333
5410,21000226,1610612748.0,LeBron James,107.6,2010-11-26,100.812274,108.756250
5710,21000239,1610612748.0,LeBron James,97.4,2010-11-27,100.963869,108.088235
5985,21000250,1610612748.0,LeBron James,110.5,2010-11-29,101.140108,108.222222
6346,21000265,1610612748.0,LeBron James,109.8,2010-12-01,101.204079,108.305263
6526,21000273,1610612748.0,LeBron James,136.2,2010-12-02,101.254411,109.700000
6898,21000288,1610612748.0,LeBron James,102.4,2010-12-04,101.220636,109.352381
7318,21000306,1610612748.0,LeBron James,103.9,2010-12-06,101.326615,109.104545
7750,21000324,1610612748.0,LeBron James,118.6,2010-12-08,101.318427,109.517391
8134,21000340,1610612748.0,LeBron James,128.2,2010-12-10,101.331410,110.295833
8326,21000348,1610612748.0,LeBron James,112.2,2010-12-11,101.296403,110.372000
8506,21000355,1610612748.0,LeBron James,114.3,2010-12-13,101.232012,110.523077
8890,21000371,1610612748.0,LeBron James,102.4,2010-12-15,101.230628,110.222222
9143,21000382,1610612748.0,LeBron James,121.2,2010-12-17,101.305925,110.614286
9406,21000393,1610612748.0,LeBron James,101.7,2010-12-18,101.180762,110.306897
9825,21000410,1610612748.0,LeBron James,92.7,2010-12-20,101.157191,109.720000
10340,21000432,1610612748.0,LeBron James,101.1,2010-12-23,101.206552,109.441935
10412,21000435,1610612748.0,LeBron James,109.8,2010-12-25,101.143344,109.453125
10952,21000457,1610612748.0,LeBron James,122.6,2010-12-28,100.997697,109.851515
11228,21000469,1610612748.0,LeBron James,126.3,2010-12-29,100.947278,110.335294
11648,21000486,1610612748.0,LeBron James,117.4,2011-01-01,100.904211,110.537143
11948,21000499,1610612748.0,LeBron James,119.5,2011-01-03,100.797021,110.786111
12104,21000505,1610612748.0,LeBron James,112.2,2011-01-04,100.804437,110.824324
12736,21000532,1610612748.0,LeBron James,91.2,2011-01-07,100.995800,110.307895
13138,21000549,1610612748.0,LeBron James,112.6,2011-01-09,101.037891,110.366667
13686,21000572,1610612748.0,LeBron James,111.4,2011-01-12,101.183273,110.392500
13769,21000575,1610612748.0,LeBron James,NaN,2011-01-13,101.239732,110.392500
14631,21000611,1610612748.0,LeBron James,94.8,2011-01-18,101.372566,110.012195
15399,21000643,1610612748.0,LeBron James,125.8,2011-01-22,101.373155,110.388095
16227,21000678,1610612748.0,LeBron James,101.6,2011-01-27,101.495515,110.183721
16431,21000686,1610612748.0,LeBron James,104.9,2011-01-28,101.512691,110.063636
16779,21000701,1610612748.0,LeBron James,115.2,2011-01-30,101.475827,110.177778
17007,21000710,1610612748.0,LeBron James,119.8,2011-01-31,101.524787,110.386957
17477,21000730,1610612748.0,LeBron James,114.9,2011-02-03,101.586616,110.482979
17549,21000733,1610612748.0,LeBron James,114.4,2011-02-04,101.603101,110.564583
18063,21000754,1610612748.0,LeBron James,105.2,2011-02-06,101.688236,110.455102
18421,21000769,1610612748.0,LeBron James,126.3,2011-02-08,101.763839,110.772000
18959,21000792,1610612748.0,LeBron James,119.0,2011-02-11,101.826023,110.933333
19247,21000804,1610612748.0,LeBron James,90.7,2011-02-13,101.810369,110.544231
19581,21000818,1610612748.0,LeBron James,107.2,2011-02-15,101.808042,110.481132
19749,21000825,1610612748.0,LeBron James,112.0,2011-02-16,101.795509,110.509259
20145,21000841,1610612748.0,LeBron James,120.1,2011-02-22,101.860216,110.683636
20564,21000859,1610612748.0,LeBron James,100.0,2011-02-24,101.914983,110.492857
20743,21000866,1610612748.0,LeBron James,112.4,2011-02-25,101.894412,110.526316
21244,21000887,1610612748.0,LeBron James,88.0,2011-02-27,101.908537,110.137931
21843,21000912,1610612748.0,LeBron James,108.7,2011-03-03,101.928584,110.113559
22095,21000923,1610612748.0,LeBron James,104.9,2011-03-04,101.996614,110.026667
22298,21000931,1610612748.0,LeBron James,99.7,2011-03-06,101.983445,109.857377
22776,21000951,1610612748.0,LeBron James,112.2,2011-03-08,101.973516,109.895161
23088,21000964,1610612748.0,LeBron James,107.3,2011-03-10,102.024994,109.853968
23374,21000976,1610612748.0,LeBron James,114.7,2011-03-12,102.077608,109.929687
23780,21000993,1610612748.0,LeBron James,115.3,2011-03-14,102.071467,110.012308
24092,21001006,1610612748.0,LeBron James,96.8,2011-03-16,102.098252,109.812121
24416,21001020,1610612748.0,LeBron James,128.5,2011-03-18,102.064198,110.091045
24668,21001030,1610612748.0,LeBron James,119.0,2011-03-19,102.042092,110.222059
25327,21001058,1610612748.0,LeBron James,113.1,2011-03-23,102.043279,110.263768
25675,21001072,1610612748.0,LeBron James,118.5,2011-03-25,102.105035,110.381429
26082,21001089,1610612748.0,LeBron James,129.1,2011-03-27,102.101063,110.645070
26357,21001101,1610612748.0,LeBron James,94.5,2011-03-29,102.112362,110.420833
26573,21001110,1610612748.0,LeBron James,133.1,2011-03-30,102.135588,110.731507
26957,21001126,1610612748.0,LeBron James,116.5,2011-04-01,102.147503,110.809459
27340,21001142,1610612748.0,LeBron James,116.2,2011-04-03,102.111436,110.881333
27880,21001164,1610612748.0,LeBron James,88.0,2011-04-06,102.148018,110.580263
28312,21001182,1610612748.0,LeBron James,116.8,2011-04-08,102.193953,110.661039
28599,21001194,1610612748.0,LeBron James,115.4,2011-04-10,102.211460,110.721795
28779,21001202,1610612748.0,LeBron James,111.9,2011-04-11,102.248782,110.736709
29246,21001221,1610612748.0,LeBron James,NaN,2011-04-13,102.263070,110.736709
29607,41000111,1610612748.0,LeBron James,105.1,2011-04-16,102.257935,110.666250
29631,41000112,1610612748.0,LeBron James,114.5,2011-04-18,102.249905,110.713580
29643,41000113,1610612748.0,LeBron James,121.8,2011-04-21,102.247621,110.848780
29667,41000114,1610612748.0,LeBron James,93.4,2011-04-24,102.252438,110.638554
29703,41000115,1610612748.0,LeBron James,118.5,2011-04-27,102.245391,110.732143
30663,41000211,1610612748.0,LeBron James,102.2,2011-05-01,102.189662,110.631765
30687,41000212,1610612748.0,LeBron James,115.7,2011-05-03,102.190995,110.690698
30699,41000213,1610612748.0,LeBron James,91.3,2011-05-07,102.192915,110.467816
30724,41000214,1610612748.0,LeBron James,98.5,2011-05-09,102.190047,110.331818
30759,41000215,1610612748.0,LeBron James,107.2,2011-05-11,102.188708,110.296629
31035,41000301,1610612748.0,LeBron James,101.8,2011-05-15,102.207806,110.202222
31059,41000302,1610612748.0,LeBron James,100.3,2011-05-18,102.205013,110.093407
31095,41000303,1610612748.0,LeBron James,110.3,2011-05-22,102.196011,110.095652
31119,41000304,1610612748.0,LeBron James,101.1,2011-05-24,102.189671,109.998925
31131,41000305,1610612748.0,LeBron James,95.9,2011-05-26,102.189271,109.848936
31287,41000401,1610612748.0,LeBron James,107.8,2011-05-31,102.203251,109.827368
31311,41000402,1610612748.0,LeBron James,111.0,2011-06-02,102.198329,109.839583
31323,41000403,1610612748.0,LeBron James,101.7,2011-06-05,102.198412,109.755670
31347,41000404,1610612748.0,LeBron James,95.6,2011-06-07,102.192674,109.611224
31371,41000405,1610612748.0,LeBron James,111.1,2011-06-09,102.193409,109.626263
31407,41000406,1610612748.0,LeBron James,93.2,2011-06-12,102.210059,109.462000

In [68]:
(91.3 + 97.9)/2

94.6

In [69]:
df_or1011a[df_or1011a.cma2 != df_or1011a.cma1]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1,cma2
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000,73.900000
5,21000001,1610612748.0,James Jones,86.5,2010-10-26,78.233333,86.500000
...,...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451,108.415054

In [70]:
df_or1011a.drop(columns='cma1', inplace=True)
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,73.900000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,108.415054

In [71]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  object
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
 5   cma2          31259 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 1.7+ MB

In [72]:
df_inj.rename(columns={'Date':'game_date'})

,game_date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love

In [73]:
df_or1011a.rename(columns={'PLAYER_NAME':'player'})

,game_id,TEAM_ID,player,E_OFF_RATING,game_date,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,73.900000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,108.415054

In [74]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_date', 'player'], how='left')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id,TEAM_ID,E_OFF_RATING,cma2
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,NaN,NaN,NaN,NaN
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,NaN,NaN,NaN,NaN
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,NaN,NaN,NaN,NaN
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,NaN,NaN,NaN,NaN
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
14758,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin,NaN,NaN,NaN,NaN
14759,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George,NaN,NaN,NaN,NaN
14760,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala,NaN,NaN,NaN,NaN
14761,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,NaN,NaN,NaN,NaN
14762,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,NaN,NaN,NaN,NaN

In [75]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_date', 'player'], how='left').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14763 entries, 0 to 14762
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     14763 non-null  datetime64[ns]
 1   Team          14763 non-null  object
 2   Acquired      14763 non-null  object
 3   Relinquished  14763 non-null  object
 4   Notes         14763 non-null  object
 5   team_id       14763 non-null  int64
 6   player        14763 non-null  object
 7   game_id       628 non-null    float64
 8   TEAM_ID       628 non-null    object
 9   E_OFF_RATING  24 non-null     float64
 10  cma2          624 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 1.4+ MB

In [76]:
df_inj

,Date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love

In [77]:
df_gamess1011 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])
df_gamess1011 = df_gamess1011[(df_gamess1011.season_type == 'Regular Season') 
                              | (df_gamess1011.season_type == 'Playoffs')][(df_gamess1011.season == '2010-11')][['game_id', 'game_date','team_id']]
df_gamess1011

        game_id  game_date     team_id
9840   21000001 2010-10-26  1610612738
9841   21000001 2010-10-26  1610612748
9842   21000002 2010-10-26  1610612757
9843   21000002 2010-10-26  1610612756
9844   21000003 2010-10-26  1610612745
...         ...        ...         ...
29861  41000404 2011-06-07  1610612748
29862  41000405 2011-06-09  1610612742
29863  41000405 2011-06-09  1610612748
29864  41000406 2011-06-12  1610612748
29865  41000406 2011-06-12  1610612742

[2622 rows x 3 columns]

In [78]:
df_gamess1011.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2622 entries, 9840 to 29865
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_id    2622 non-null   int64
 1   game_date  2622 non-null   datetime64[ns]
 2   team_id    2622 non-null   int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 81.9 KB

In [79]:
df_inj2 = pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_gamess1011, on=['game_date', 'team_id'], how='inner')
df_inj2

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000002
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,21000002
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,1610612757,Joel Przybilla,21000002
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,1610612738,Avery Bradley,21000001
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,1610612738,Kendrick Perkins,21000001
...,...,...,...,...,...,...,...,...
1673,2011-05-26,Bulls,,Omer Asik,placed on IL with stress fracture in left fibula (out for season),1610612741,Omer Asik,41000305
1674,2011-05-31,Heat,,Zydrunas Ilgauskas,placed on IL,1610612748,Zydrunas Ilgauskas,41000401
1675,2011-06-05,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor,1610612742,Brendan Haywood,41000403
1676,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,41000404
1677,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,41000405

In [80]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_gamess1011, on=['game_date', 'team_id'], how='inner').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1678 entries, 0 to 1677
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     1678 non-null   datetime64[ns]
 1   Team          1678 non-null   object
 2   Acquired      1678 non-null   object
 3   Relinquished  1678 non-null   object
 4   Notes         1678 non-null   object
 5   team_id       1678 non-null   int64
 6   player        1678 non-null   object
 7   game_id       1678 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 118.0+ KB

In [81]:
df_inj3 = df_inj2.drop(columns=['A', 'Notes', 'Acquired', 'Relinquished'])

KeyError: "['A'] not found in axis"

In [ ]:
df_inj3

In [ ]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '6injuries_2010-11.csv')
if not os.path.exists(datapath_df):
    df_inj3.to_csv(datapath_df, index=False)

In [ ]:
set(df_inj3.player)

In [ ]:
len(set(df_inj3.player))

In [ ]:
#check player (name) similarity with player of df_inj3


#check for player (name) similiarty with player of df_or1011a

In [ ]:
#check player (name) similarity with player of df_inj3
import numpy as np

In [ ]:
unique_player = df_inj3.player.unique().tolist()
sorted(unique_player)[:20]

In [ ]:
unique_player2 = df_or1011a['PLAYER_NAME'].unique().tolist()
sorted(unique_player2)[:20]

In [ ]:
df_inj3[df_inj3.player == 'J.J. Hickson']

In [ ]:
df_inj3[df_inj3.player == 'J.J. Redick']

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME == 'J.J. Redick']

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('J.J. Redick')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('JJ Redick')].sort_values(by='game_date')

In [ ]:
#<>><><><><><><><><><><<><><><><><><><><><<><><><><><><><><><<><><><><><><><><><<><><><><><><><><><><><><<><><><><><><><><><<><><><><><><><><>

<font color='red'> will go with no dots version of name as in nba_api<font>

In [ ]:
df_inj3[df_inj3.player == 'J.J. Redick']

In [ ]:
df_inj3.player.replace({'J.J. Redick':'JJ Redick'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('J.J. Redick')]

In [ ]:
df_inj3[df_inj3.player.str.contains('JJ Redick')]

In [ ]:
#names with space(s) in the front

#names with space(s) in the back

#?remove periods?

#?remove apostrophes?

'''
*****************************************
A.J. Price
('AJ Price', 94)
0
*****************************************
Alex Ajinca
('Alexis Ajinca', 92)
1
*****************************************
C.J. Miles
('CJ Miles', 94)
2
*****************************************
D.J. White
('DJ White', 94)
3
*****************************************
Hamady N'Diaye
('Hamady Ndiaye', 89)
4
*****************************************
J.J. Hickson
('JJ Hickson', 95)
5
*****************************************
J.J. Redick
('JJ Redick', 94)
6
*****************************************
John Wallace
('John Wall', 86)
7
*****************************************
Jose Barea 
('J.J. Barea', 83)
8
*****************************************
Wes Johnson
('Wesley Johnson', 88)
9
'''

In [ ]:
'''
*****************************************
A.J. Price
('AJ Price', 94)
0
'''

df_inj3

In [ ]:
df_inj3[df_inj3.player == 'A.J. Price']

In [ ]:
df_inj3[df_inj3.player == 'A.J. Price'].shape

In [ ]:
df_inj3[df_inj3.player.str.contains('A.J. Price')]

In [ ]:
df_inj3[df_inj3.player.str.contains('A.J. Price')].shape

In [ ]:
df_inj3.player.replace({'A.J. Price': 'AJ Price'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('A.J. Price')]

In [ ]:
df_inj3[df_inj3.player.str.contains('AJ Price')]

In [ ]:
'''
*****************************************
Alex Ajinca
('Alexis Ajinca', 92)
1
'''

In [ ]:
df_inj3[df_inj3.player == 'Alex Ajinca']

In [ ]:
df_inj3[df_inj3.player == 'Alex Ajinca'].shape

In [ ]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')].shape

In [ ]:
df_inj3[df_inj3.player == 'Alexis Ajinca']

In [ ]:
df_inj3.player.replace({'Alex Ajinca':'Alexis Ajinca'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Alexis Ajinca')]

In [ ]:
'''
*****************************************
C.J. Miles
('CJ Miles', 94)
2
'''

In [ ]:
print(df_inj3[df_inj3.player == 'C.J. Miles'].shape)
df_inj3[df_inj3.player == 'C.J. Miles']

In [ ]:
print(df_inj3[df_inj3.player.str.contains('C.J. Miles')].shape)
df_inj3[df_inj3.player.str.contains('C.J. Miles')]

In [ ]:
print(df_inj3[df_inj3.player == 'CJ Miles'].shape)
df_inj3[df_inj3.player == 'CJ Miles']

In [ ]:
print(df_inj3[df_inj3.player.str.contains('CJ Miles')].shape)
df_inj3[df_inj3.player.str.contains('CJ Miles')]

In [ ]:
df_inj3.player.replace({'C.J. Miles': 'CJ Miles'}, inplace=True)

In [ ]:
print(df_inj3[df_inj3.player.str.contains('Miles')].shape)
df_inj3[df_inj3.player.str.contains('Miles')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Miles')]

In [ ]:
'''
*****************************************
D.J. White
('DJ White', 94)
3
'''

In [ ]:
df_inj3[df_inj3.player == 'D.J. White']

In [ ]:
df_inj3[df_inj3.player.str.contains('D.J. White')]

In [ ]:
df_inj3.player.replace({'D.J. White': 'DJ White'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('D.J. White')]

In [ ]:
df_inj3[df_inj3.player.str.contains('DJ White')]

In [ ]:
'''
*****************************************
Hamady N'Diaye
('Hamady Ndiaye', 89)
4
'''

In [ ]:
print(df_inj3[df_inj3.player.str.contains('Hamady')].shape)
df_inj3[df_inj3.player.str.contains('Hamady')]

In [ ]:
df_inj3.player.replace({"Hamady N'Diaye" : 'Hamady Ndiaye'}, inplace=True)

In [ ]:
print(df_inj3[df_inj3.player.str.contains('Hamady')].shape)
df_inj3[df_inj3.player.str.contains('Hamady')]

In [ ]:
print(df_or1011a[df_or1011a.PLAYER_NAME == 'Hamady Ndiaye'].shape)
df_or1011a[df_or1011a.PLAYER_NAME == 'Hamady Ndiaye']

In [ ]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady Ndiaye')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady Ndiaye')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady')].sort_values(by='game_date')

In [ ]:
df_inj3[df_inj3.player.str.contains('Hamady')]

In [ ]:
'''
*****************************************
J.J. Hickson
('JJ Hickson', 95)
5
'''

In [ ]:
print(df_inj3[df_inj3.player.str.contains('Hickson')].shape)
df_inj3[df_inj3.player.str.contains('Hickson')]

In [ ]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hickson')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hickson')]

In [ ]:
#df_injuries[df_injuries.player == 'J.J. Hickson']
df_inj3.player.replace({'J.J. Hickson': 'JJ Hickson'}, inplace=True)

In [ ]:
print(df_inj3[df_inj3.player.str.contains('Hickson')].shape)
df_inj3[df_inj3.player.str.contains('Hickson')]

In [ ]:
'''
*****************************************
J.J. Redick
('JJ Redick', 94)
6
'''

In [ ]:
df_inj3[df_inj3.player.str.contains('Redick')]

In [ ]:
'''
*****************************************
John Wallace
('John Wall', 86)
7
'''

In [ ]:
df_inj3[df_inj3.player.str.contains('John Wall')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Wallace')]

In [ ]:
df_inj3.player.replace({'John Wallace' : 'John Wall'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('John Wall')]

In [ ]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('John Wall')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('John Wall')]

In [ ]:
df_injuries[df_injuries.player.str.contains('John Wall')].drop(columns=['A'])

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains(' Wall')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains(' Wall')][['TEAM_ID', 'PLAYER_NAME']].value_counts()

In [ ]:
'''
*****************************************
Jose Barea 
('J.J. Barea', 83)
8
'''

In [ ]:
df_inj3[df_inj3.player.str.contains('Barea')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Barea')].player.value_counts().index.values[0]

In [ ]:
df_inj3.player.replace({'Jose Barea ' : 'J.J. Barea'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('Barea')]

In [ ]:
print(df_inj3[df_inj3.player.str.contains('Barea')].player)

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Barea')]

In [ ]:
'''
*****************************************
Wes Johnson
('Wesley Johnson', 88)
9
'''

In [ ]:
df_inj3[df_inj3.player.str.contains('Johnson')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Wes ')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Wesley Johnson')]

In [ ]:
df_inj3.player.replace({'Wes Johnson':'Wesley Johnson'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('Wes ')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Wesley')]

<font color='red'> PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP</font>

In [ ]:
df_inj3.player.replace({' Tony Parker' : 'Tony Parker'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('Mullens')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Mullens')]

In [ ]:
df_inj3.player.replace({'B.J. Mullens':'Byron Mullens'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('Mullens')]

In [ ]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

In [ ]:
df_inj3['player'] = df_inj3.player.str.strip()

In [ ]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

In [ ]:
#Bill Walker
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Walker')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Walker')]

In [ ]:
df_inj3.player.replace({'Bill Walker':'Henry Walker'}, inplace=True)
#"Previously known as Bill Walker" by "https://en.wikipedia.org/wiki/Henry_Walker_(basketball)"

In [ ]:
df_inj3[df_inj3.player.str.contains('Walker')]

In [ ]:
#Da'Sean Butler
df_inj3[df_inj3.player.str.contains('Butler')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Butler')]

In [ ]:
#df_inj2[df_inj2.player.str.contains("Da'Sean Butler")]
df_inj3[df_inj3.player.str.contains("Da'Sean Butler")]

In [ ]:
df_inj3[~df_inj3.player.str.contains("Da'Sean Butler")]

In [ ]:
#no play data for Da'Sean Butler -> will be assigned lowest offensive rating in offensive rating lost per team summary statistic

In [ ]:
# 'Daniel Orton'
df_inj3[df_inj3.player.str.contains('Daniel Orton')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Orton')]

In [ ]:
df_injuries[df_injuries.player.str.contains('Daniel Orton')]

In [ ]:
# 'Daniel Orton' out of the 2010-11 season due to injury but returns in 2011-12 season

In [ ]:
# 'Didier Mbenga'
df_inj3[df_inj3.player.str.contains('Mbenga')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Mbenga')]

<font color='red'> RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR </font>

In [ ]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

In [ ]:
set(df_or1011a.PLAYER_NAME) - set(df_inj3.player)

In [ ]:
# 'Gerald Henderson'
df_inj3[df_inj3.player.str.contains('Gerald Henderson')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Henderson')]

In [ ]:
df_inj3.player.replace({'Gerald Henderson Jr.':'Gerald Henderson'}, inplace=True)

In [ ]:
'''
Compare these two access methods:

In [357]: dfmi['one']['second']
Out[357]: 
0    b
1    f
2    j
3    n
Name: second, dtype: object
In [358]: dfmi.loc[:, ('one', 'second')]
Out[358]: 
0    b
1    f
2    j
3    n
Name: (one, second), dtype: object
These both yield the same results, so which should you use? It is instructive to understand the order of operations on these and why method 2 (.loc)
is much preferred over method 1 (chained []).

dfmi['one'] selects the first level of the columns and returns a DataFrame that is singly-indexed. Then another Python operation dfmi_with_one['second']
selects the series indexed by 'second'. This is indicated by the variable dfmi_with_one because pandas sees these operations as separate events. e.g.
separate calls to __getitem__, so it has to treat them as linear operations, they happen one after another.

Contrast this to df.loc[:,('one','second')] which passes a nested tuple of (slice(None),('one','second')) to a single call to __getitem__.
This allows pandas to deal with this as a single entity. Furthermore this order of operations can be significantly faster, and allows one to
index both axes if so desired.
'''

In [ ]:
df_inj3[df_inj3.player.str.contains('Gerald Henderson')]

In [ ]:
print(df_inj3[df_inj3.player.str.contains('Gerald Henderson')].player)

In [ ]:
#'Jianlian Yi'

df_inj3[df_inj3.player.str.contains('Jianlian Yi')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Jianlian')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Yi')]

In [ ]:
df_inj3.player.replace({'Jianlian Yi':'Yi Jianlian'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('Yi')]

In [ ]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Yi')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Yi')]

In [ ]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Jianlian')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Jianlian')]

In [ ]:
# 'Mike Conley'
df_inj3[df_inj3.player.str.contains('Mike Conley')]

In [ ]:
df_inj3.player.replace({'Mike Conley Jr.':'Mike Conley'}, inplace=True)

In [ ]:
df_inj3[df_inj3.player.str.contains('Mike Conley')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Conley')]

In [ ]:
df_inj3[df_inj3.player.str.contains('Mike')]

In [ ]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Conley')]

<font color='red'>QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ</font>

In [ ]:


#——->get player game_id, game_date for that season by merge relinquished players of df_injuries on df_or1011