In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [2]:
path = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\5boxscoreadvancedv2_2006_2018.csv'
df = pd.read_csv(path)

In [3]:
df

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20600001,1610612741,CHI,Chicago,2736,Luol Deng,F,NaN,24:07,102.3,102.1,86.6,87.0,15.7,15.2,0.083,0.33,6.3,0.040,0.056,0.047,18.8,0.444,0.515,0.263,0.273,92.67,92.55,77.13,47,0.064
1,20600001,1610612741,CHI,Chicago,136,P.J. Brown,F,NaN,18:23,104.2,108.1,69.3,65.8,34.9,42.3,0.077,0.50,16.7,0.000,0.200,0.086,33.3,0.500,0.694,0.111,0.113,97.24,97.91,81.60,37,0.088
2,20600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,NaN,28:29,98.0,103.7,77.0,76.8,21.0,26.9,0.059,0.00,16.7,0.194,0.192,0.193,0.0,0.400,0.460,0.077,0.077,95.18,92.69,77.24,54,0.152
3,20600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,NaN,22:56,86.6,91.1,75.4,73.9,11.1,17.2,0.167,1.00,13.3,0.000,0.050,0.020,13.3,0.111,0.268,0.232,0.235,96.77,95.26,79.38,45,-0.096
4,20600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,NaN,34:38,108.3,113.6,77.3,76.5,31.0,37.2,0.167,0.00,13.6,0.000,0.133,0.065,0.0,0.639,0.658,0.241,0.237,94.60,92.86,77.38,66,0.296
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386106,21400531,1610612750,MIN,Minnesota,203897,Zach LaVine,NaN,NaN,12:38,90.4,92.9,122.2,125.0,-31.8,-32.1,0.222,0.50,18.2,0.000,0.067,0.034,36.4,0.500,0.615,0.273,0.275,109.12,106.46,88.71,28,0.041
386107,21400531,1610612750,MIN,Minnesota,201978,Chase Budinger,NaN,NaN,24:07,121.0,119.6,126.6,130.8,-5.6,-11.2,0.053,1.00,11.1,0.100,0.115,0.109,11.1,0.714,0.714,0.136,0.139,103.62,102.50,85.42,51,0.090
386108,21400531,1610612750,MIN,Minnesota,203133,Robbie Hummel,NaN,NaN,7:11,92.9,92.9,108.4,106.7,-15.5,-13.8,0.000,0.00,0.0,0.000,0.111,0.077,0.0,0.000,0.000,0.000,0.000,96.09,96.89,80.74,14,-0.042
386109,21400531,1610612750,MIN,Minnesota,203584,Troy Daniels,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
386110,21400531,1610612750,MIN,Minnesota,203922,Glenn Robinson III,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [4]:
#regular season and playoff games for 2009-10 season?

In [5]:
path = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data\\3game_date_home_away.csv'
df2 = pd.read_csv(path)
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [6]:
#df2.info()

In [7]:
#df2[(df2.season == '2009-10')][(df2.season_type == 'Regular Season') | (df2.season_type == 'Playoffs')].reset_index(drop=True)
df2 = df2[(df2.season == '2009-10')].reset_index(drop=True)
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20900001,2009-10-27,1610612739,0.000,240,29.0,70.0,0.414,6.0,17.0,0.353,25.0,32.0,1.0,6.0,26.0,32,17.0,7.0,9.0,13.0,22.0,89,2009.0,1610612738,1.000,240,32.0,72.0,0.444,9.0,19.0,0.474,22.0,26.0,1.0,6.0,32.0,38,20.0,9.0,8.0,14.0,27.0,95,Regular Season,2009-10
1,20900002,2009-10-27,1610612742,0.000,240,30.0,76.0,0.395,4.0,18.0,0.222,27.0,34.0,1.0,11.0,31.0,42,16.0,6.0,9.0,9.0,20.0,91,2009.0,1610612764,1.000,240,39.0,84.0,0.464,4.0,13.0,0.308,20.0,24.0,1.0,9.0,37.0,46,19.0,6.0,4.0,9.0,29.0,102,Regular Season,2009-10
2,20900003,2009-10-27,1610612757,1.000,240,33.0,77.0,0.429,10.0,21.0,0.476,20.0,22.0,1.0,12.0,39.0,51,23.0,9.0,12.0,26.0,27.0,96,2009.0,1610612745,0.000,240,30.0,81.0,0.370,5.0,18.0,0.278,22.0,29.0,1.0,10.0,23.0,33,18.0,12.0,2.0,16.0,26.0,87,Regular Season,2009-10
3,20900004,2009-10-27,1610612747,1.000,240,35.0,85.0,0.412,4.0,17.0,0.235,25.0,37.0,1.0,17.0,30.0,47,17.0,13.0,4.0,16.0,15.0,99,2009.0,1610612746,0.000,240,39.0,87.0,0.448,3.0,15.0,0.200,11.0,16.0,1.0,15.0,36.0,51,27.0,10.0,4.0,20.0,27.0,92,Regular Season,2009-10
4,20900005,2009-10-28,1610612737,1.000,240,46.0,87.0,0.529,7.0,12.0,0.583,21.0,29.0,1.0,8.0,27.0,35,30.0,16.0,6.0,10.0,25.0,120,2009.0,1610612754,0.000,240,39.0,73.0,0.534,10.0,18.0,0.556,21.0,25.0,1.0,6.0,34.0,40,23.0,1.0,4.0,25.0,26.0,109,Regular Season,2009-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1307,40900403,2010-06-08,1610612738,0.650,240,32.0,73.0,0.438,4.0,18.0,0.222,16.0,24.0,1.0,8.0,27.0,35,20.0,4.0,2.0,10.0,27.0,84,2009.0,1610612747,0.737,240,34.0,76.0,0.447,2.0,15.0,0.133,21.0,24.0,1.0,11.0,32.0,43,13.0,2.0,7.0,8.0,20.0,91,Playoffs,2009-10
1308,40900404,2010-06-10,1610612738,0.667,240,37.0,83.0,0.446,3.0,12.0,0.250,19.0,23.0,1.0,16.0,25.0,41,15.0,12.0,2.0,12.0,21.0,96,2009.0,1610612747,0.700,240,32.0,71.0,0.451,7.0,20.0,0.350,18.0,22.0,1.0,8.0,26.0,34,13.0,6.0,3.0,15.0,23.0,89,Playoffs,2009-10
1309,40900405,2010-06-13,1610612738,0.682,240,40.0,71.0,0.563,3.0,12.0,0.250,9.0,13.0,1.0,7.0,28.0,35,21.0,8.0,7.0,16.0,23.0,92,2009.0,1610612747,0.667,240,31.0,78.0,0.397,7.0,19.0,0.368,17.0,26.0,1.0,16.0,18.0,34,12.0,9.0,1.0,13.0,22.0,86,Playoffs,2009-10
1310,40900406,2010-06-15,1610612747,0.682,240,33.0,79.0,0.418,6.0,19.0,0.316,17.0,19.0,1.0,12.0,40.0,52,17.0,13.0,8.0,13.0,17.0,89,2009.0,1610612738,0.652,240,28.0,84.0,0.333,5.0,23.0,0.217,6.0,10.0,1.0,11.0,28.0,39,17.0,8.0,4.0,14.0,21.0,67,Playoffs,2009-10
1311,40900407,2010-06-17,1610612747,0.696,240,27.0,83.0,0.325,4.0,20.0,0.200,25.0,37.0,1.0,23.0,30.0,53,11.0,7.0,3.0,11.0,19.0,83,2009.0,1610612738,0.625,240,29.0,71.0,0.408,6.0,16.0,0.375,15.0,17.0,1.0,8.0,32.0,40,18.0,6.0,7.0,14.0,25.0,79,Playoffs,2009-10

In [8]:
df2.season.value_counts()

2009-10    1312
Name: season, dtype: int64

In [9]:
df.rename(columns={'GAME_ID':'game_id'}, inplace=True)
df

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20600001,1610612741,CHI,Chicago,2736,Luol Deng,F,NaN,24:07,102.3,102.1,86.6,87.0,15.7,15.2,0.083,0.33,6.3,0.040,0.056,0.047,18.8,0.444,0.515,0.263,0.273,92.67,92.55,77.13,47,0.064
1,20600001,1610612741,CHI,Chicago,136,P.J. Brown,F,NaN,18:23,104.2,108.1,69.3,65.8,34.9,42.3,0.077,0.50,16.7,0.000,0.200,0.086,33.3,0.500,0.694,0.111,0.113,97.24,97.91,81.60,37,0.088
2,20600001,1610612741,CHI,Chicago,1112,Ben Wallace,C,NaN,28:29,98.0,103.7,77.0,76.8,21.0,26.9,0.059,0.00,16.7,0.194,0.192,0.193,0.0,0.400,0.460,0.077,0.077,95.18,92.69,77.24,54,0.152
3,20600001,1610612741,CHI,Chicago,2732,Ben Gordon,G,NaN,22:56,86.6,91.1,75.4,73.9,11.1,17.2,0.167,1.00,13.3,0.000,0.050,0.020,13.3,0.111,0.268,0.232,0.235,96.77,95.26,79.38,45,-0.096
4,20600001,1610612741,CHI,Chicago,2550,Kirk Hinrich,G,NaN,34:38,108.3,113.6,77.3,76.5,31.0,37.2,0.167,0.00,13.6,0.000,0.133,0.065,0.0,0.639,0.658,0.241,0.237,94.60,92.86,77.38,66,0.296
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386106,21400531,1610612750,MIN,Minnesota,203897,Zach LaVine,NaN,NaN,12:38,90.4,92.9,122.2,125.0,-31.8,-32.1,0.222,0.50,18.2,0.000,0.067,0.034,36.4,0.500,0.615,0.273,0.275,109.12,106.46,88.71,28,0.041
386107,21400531,1610612750,MIN,Minnesota,201978,Chase Budinger,NaN,NaN,24:07,121.0,119.6,126.6,130.8,-5.6,-11.2,0.053,1.00,11.1,0.100,0.115,0.109,11.1,0.714,0.714,0.136,0.139,103.62,102.50,85.42,51,0.090
386108,21400531,1610612750,MIN,Minnesota,203133,Robbie Hummel,NaN,NaN,7:11,92.9,92.9,108.4,106.7,-15.5,-13.8,0.000,0.00,0.0,0.000,0.111,0.077,0.0,0.000,0.000,0.000,0.000,96.09,96.89,80.74,14,-0.042
386109,21400531,1610612750,MIN,Minnesota,203584,Troy Daniels,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
386110,21400531,1610612750,MIN,Minnesota,203922,Glenn Robinson III,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [10]:
df = pd.merge(df, df2.game_id, how='right', on='game_id').rename(columns={'game_id':'GAME_ID'})
df

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1610612738,BOS,Boston,1718,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76,0.189
1,20900001,1610612738,BOS,Boston,708,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66,0.147
2,20900001,1610612738,BOS,Boston,2570,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47,0.030
3,20900001,1610612738,BOS,Boston,951,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80,0.051
4,20900001,1610612738,BOS,Boston,200765,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31476,40900407,1610612747,LAL,Los Angeles,2756,Sasha Vujacic,NaN,NaN,4:41,97.8,100.0,0.0,0.0,97.8,100.0,0.000,0.00,0.0,0.000,0.143,0.067,0.0,0.000,0.347,0.231,0.246,77.95,87.18,72.65,9,0.250
31477,40900407,1610612747,LAL,Los Angeles,200769,Shannon Brown,NaN,NaN,5:25,71.7,63.6,82.0,72.7,-10.2,-9.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.077,0.085,86.49,97.48,81.23,11,-0.444
31478,40900407,1610612747,LAL,Los Angeles,2694,Josh Powell,NaN,NaN,0:34,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,84.46,126.69,105.57,2,0.000
31479,40900407,1610612747,LAL,Los Angeles,2788,DJ Mbenga,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
31480,40900407,1610612747,LAL,Los Angeles,2575,Luke Walton,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [12]:
set1=  set(df.GAME_ID)

In [13]:
set2 = set(df2.game_id)

In [14]:
set2 - set1

set()

In [15]:
set1  - set2

set()

In [11]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '5boxscoreadvancedv2_2009_2010.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=False)