In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
def drop_rows(df_):
    df_ = df_[df_.PLAYER_ID != 1626194] #10-day cav contract Marcus Thornton. dob '93. no nba games played

    return df_

def edit_player_id(df_):
    df_.at[df_[df_.PLAYER_ID == 27596].index.values[0], 'PLAYER_ID'] = 1740 #Rashard Lewis single game PLAYER_ID write
    
    df_.at[df_[df_.PLAYER_ID == 6274].index.values[0], 'PLAYER_ID'] = 1882 #Elton brand single game PLAYER_ID write
    
    
    
    return df_
    
def replace_player(df_):
    df_.player.replace({'Jianlian Yi':'Yi Jianlian'}, inplace=True)

    df_.player.replace({'Nene Hilario': 'Nene'}, inplace=True)

    df_.player.replace({'Ming Yao': 'Yao Ming'}, inplace=True)

    return df_   
    
    
    
    
    
    

#return first 5 and last 5 rows of dataframe
def p(df_):
    return pd.concat([df_.head(), df_.tail()])

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
#AAA. On the 2011-01-22 nba game Wade was NWT due to a migraine (by the nba.com boxscore) during this Heat vs. Raptors
# game. Was Wade inactive for this game according to the inactive player game-by-game dataframe df_ina1018?

path = os.path.join('..', 'raw_data','basketball.sqlite')
path
con = sqlite3.connect(path)
cursor = con.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('Player',), ('Team',), ('Team_Attributes',), ('Team_History',), ('Player_Attributes',), ('Game_Officials',), ('Game_Inactive_Players',), ('Team_Salary',), ('Player_Salary',), ('Draft',), ('Draft_Combine',), ('Player_Photos',), ('Player_Bios',), ('Game',), ('News',), ('News_Missing',)]

In [6]:
df_ina = pd.read_sql_query("SELECT * from Game_Inactive_Players", con)
df_ina['player'] = df_ina.FIRST_NAME + " " + df_ina.LAST_NAME
df_ina.player = df_ina.player.str.strip()
print(df_ina.shape)
p(df_ina)

(97937, 10)

,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,GAME_ID,player
0,184,Bobby,Phills,14,1610612739,Cleveland,Cavaliers,CLE,0029600034,Bobby Phills
1,781,Will,Perdue,41,1610612759,San Antonio,Spurs,SAS,0029600034,Will Perdue
2,120,Steven,Smith,8,1610612737,Atlanta,Hawks,ATL,0029600132,Steven Smith
3,698,Eddie,Johnson,8,1610612754,Indiana,Pacers,IND,0029600203,Eddie Johnson
4,32,Clifford,Rozier,44,1610612753,Orlando,Magic,ORL,0029600213,Clifford Rozier
97932,2544,LeBron,James,23,1610612747,Los Angeles,Lakers,LAL,0022000982,LeBron James
97933,203115,Will,Barton,5,1610612743,Denver,Nuggets,DEN,0022000982,Will Barton
97934,1627750,Jamal,Murray,27,1610612743,Denver,Nuggets,DEN,0022000982,Jamal Murray
97935,1630192,Zeke,Nnaji,22,1610612743,Denver,Nuggets,DEN,0022000982,Zeke Nnaji
97936,1628420,Monte,Morris,11,1610612743,Denver,Nuggets,DEN,0022000982,Monte Morris

In [7]:
print(df_ina.drop_duplicates().shape)
p(df_ina.drop_duplicates())

(97937, 10)

,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,GAME_ID,player
0,184,Bobby,Phills,14,1610612739,Cleveland,Cavaliers,CLE,0029600034,Bobby Phills
1,781,Will,Perdue,41,1610612759,San Antonio,Spurs,SAS,0029600034,Will Perdue
2,120,Steven,Smith,8,1610612737,Atlanta,Hawks,ATL,0029600132,Steven Smith
3,698,Eddie,Johnson,8,1610612754,Indiana,Pacers,IND,0029600203,Eddie Johnson
4,32,Clifford,Rozier,44,1610612753,Orlando,Magic,ORL,0029600213,Clifford Rozier
97932,2544,LeBron,James,23,1610612747,Los Angeles,Lakers,LAL,0022000982,LeBron James
97933,203115,Will,Barton,5,1610612743,Denver,Nuggets,DEN,0022000982,Will Barton
97934,1627750,Jamal,Murray,27,1610612743,Denver,Nuggets,DEN,0022000982,Jamal Murray
97935,1630192,Zeke,Nnaji,22,1610612743,Denver,Nuggets,DEN,0022000982,Zeke Nnaji
97936,1628420,Monte,Morris,11,1610612743,Denver,Nuggets,DEN,0022000982,Monte Morris

In [8]:
df_ina.GAME_ID = df_ina.GAME_ID.astype(int)
print(df_ina.GAME_ID.shape)
p(df_ina.GAME_ID)

(97937,)

0        29600034
1        29600034
2        29600132
3        29600203
4        29600213
97932    22000982
97933    22000982
97934    22000982
97935    22000982
97936    22000982
Name: GAME_ID, dtype: int64

In [9]:
df_ina.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97937 entries, 0 to 97936
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          97937 non-null  object
 1   FIRST_NAME         97937 non-null  object
 2   LAST_NAME          97937 non-null  object
 3   JERSEY_NUM         97937 non-null  object
 4   TEAM_ID            97937 non-null  object
 5   TEAM_CITY          97937 non-null  object
 6   TEAM_NAME          97937 non-null  object
 7   TEAM_ABBREVIATION  97937 non-null  object
 8   GAME_ID            97937 non-null  int64
 9   player             97937 non-null  object
dtypes: int64(1), object(9)
memory usage: 7.5+ MB

In [10]:
#stick a date for game_id: get (game_id, game_date, team_id) dataframe df_3gigdti1018
path = os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv')
path
df_3gigdti = pd.read_csv(path)
df_3gigdti1018 = df_3gigdti[(df_3gigdti.season == '2010-11') |
                            (df_3gigdti.season == '2011-12') |
                            (df_3gigdti.season == '2012-13') |
                            (df_3gigdti.season == '2013-14') |
                            (df_3gigdti.season == '2014-15') |
                            (df_3gigdti.season == '2015-16') |
                            (df_3gigdti.season == '2016-17') |
                            (df_3gigdti.season == '2017-18')]
print(df_3gigdti1018.shape)
p(df_3gigdti1018)

(20534, 27)

,game_id,game_date,team_id,is_home,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
9840,21000001,2010-10-26,1610612738,t,1.0,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010,Regular Season,2010-11
9841,21000001,2010-10-26,1610612748,f,0.0,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,2010,Regular Season,2010-11
9842,21000002,2010-10-26,1610612757,t,1.0,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010,Regular Season,2010-11
9843,21000002,2010-10-26,1610612756,f,0.0,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,2010,Regular Season,2010-11
9844,21000003,2010-10-26,1610612745,f,0.0,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,2010,Regular Season,2010-11
31033,41700402,2018-06-03,1610612744,t,1.0,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017,Playoffs,2017-18
31034,41700403,2018-06-06,1610612744,f,1.0,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,2017,Playoffs,2017-18
31035,41700403,2018-06-06,1610612739,t,0.0,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017,Playoffs,2017-18
31036,41700404,2018-06-08,1610612739,t,0.0,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017,Playoffs,2017-18
31037,41700404,2018-06-08,1610612744,f,1.0,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,2017,Playoffs,2017-18

In [11]:
df_3gigdti1018[['game_id', 'game_date', 'team_id', 'season']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20534 entries, 9840 to 31037
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_id    20534 non-null  int64
 1   game_date  20534 non-null  object
 2   team_id    20534 non-null  int64
 3   season     20534 non-null  object
dtypes: int64(2), object(2)
memory usage: 802.1+ KB

In [12]:
df_ina.TEAM_ID = df_ina.TEAM_ID.astype(int)

In [13]:
df_ina.rename(columns={'GAME_ID':'game_id'}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97937 entries, 0 to 97936
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PLAYER_ID          97937 non-null  object
 1   FIRST_NAME         97937 non-null  object
 2   LAST_NAME          97937 non-null  object
 3   JERSEY_NUM         97937 non-null  object
 4   TEAM_ID            97937 non-null  int64
 5   TEAM_CITY          97937 non-null  object
 6   TEAM_NAME          97937 non-null  object
 7   TEAM_ABBREVIATION  97937 non-null  object
 8   game_id            97937 non-null  int64
 9   player             97937 non-null  object
dtypes: int64(2), object(8)
memory usage: 7.5+ MB

In [14]:
print(pd.merge(df_3gigdti1018[['game_id', 'game_date', 'season', 'team_id']], df_ina.rename(columns={'GAME_ID':'game_id', 'TEAM_ID':'team_id'}), on=['game_id', 'team_id'], how='inner').reset_index(drop=True).drop_duplicates().shape)
p(pd.merge(df_3gigdti1018[['game_id', 'game_date', 'season', 'team_id']], df_ina.rename(columns={'GAME_ID':'game_id', 'TEAM_ID':'team_id'}), on=['game_id', 'team_id'], how='inner').reset_index(drop=True).drop_duplicates())

(43131, 12)

,game_id,game_date,season,team_id,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
0,21000001,2010-10-26,2010-11,1610612738,202376,Luke,Harangody,55,Boston,Celtics,BOS,Luke Harangody
1,21000001,2010-10-26,2010-11,1610612738,2570,Kendrick,Perkins,43,Boston,Celtics,BOS,Kendrick Perkins
2,21000001,2010-10-26,2010-11,1610612738,202340,Avery,Bradley,0,Boston,Celtics,BOS,Avery Bradley
3,21000001,2010-10-26,2010-11,1610612748,202354,Dexter,Pittman,45,Miami,Heat,MIA,Dexter Pittman
4,21000001,2010-10-26,2010-11,1610612748,2034,Mike,Miller,13,Miami,Heat,MIA,Mike Miller
43126,21701230,2018-04-11,2017-18,1610612745,201601,Luc,Mbah a Moute,12,Houston,Rockets,HOU,Luc Mbah a Moute
43127,21701230,2018-04-11,2017-18,1610612758,1628385,Harry,Giles III,20,Sacramento,Kings,SAC,Harry Giles III
43128,21701230,2018-04-11,2017-18,1610612758,1628412,Frank,Mason,10,Sacramento,Kings,SAC,Frank Mason
43129,21701230,2018-04-11,2017-18,1610612758,1627746,Skal,Labissiere,7,Sacramento,Kings,SAC,Skal Labissiere
43130,21701230,2018-04-11,2017-18,1610612758,202697,Iman,Shumpert,4,Sacramento,Kings,SAC,Iman Shumpert

In [15]:
#stick a date for game_id: merge
df_ina1018 = pd.merge(df_3gigdti1018[['game_id', 'game_date', 'season']].drop_duplicates(), df_ina.rename(columns={'GAME_ID':'game_id'}), on=['game_id'], how='inner').reset_index(drop=True)
print(df_ina1018.shape)
p(df_ina1018)

(43131, 12)

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
0,21000001,2010-10-26,2010-11,202376,Luke,Harangody,55,1610612738,Boston,Celtics,BOS,Luke Harangody
1,21000001,2010-10-26,2010-11,2570,Kendrick,Perkins,43,1610612738,Boston,Celtics,BOS,Kendrick Perkins
2,21000001,2010-10-26,2010-11,202340,Avery,Bradley,0,1610612738,Boston,Celtics,BOS,Avery Bradley
3,21000001,2010-10-26,2010-11,202354,Dexter,Pittman,45,1610612748,Miami,Heat,MIA,Dexter Pittman
4,21000001,2010-10-26,2010-11,2034,Mike,Miller,13,1610612748,Miami,Heat,MIA,Mike Miller
43126,21701230,2018-04-11,2017-18,202697,Iman,Shumpert,4,1610612758,Sacramento,Kings,SAC,Iman Shumpert
43127,21701230,2018-04-11,2017-18,203900,Markel,Brown,26,1610612745,Houston,Rockets,HOU,Markel Brown
43128,21701230,2018-04-11,2017-18,201583,Ryan,Anderson,33,1610612745,Houston,Rockets,HOU,Ryan Anderson
43129,21701230,2018-04-11,2017-18,2772,Trevor,Ariza,1,1610612745,Houston,Rockets,HOU,Trevor Ariza
43130,21701230,2018-04-11,2017-18,201601,Luc,Mbah a Moute,12,1610612745,Houston,Rockets,HOU,Luc Mbah a Moute

<font color='red'> how is it that about half the rows disappeared post merge??</font> -games before the 2010-11 season?

In [16]:
df_ina1018.PLAYER_ID = df_ina1018.PLAYER_ID.astype(int)
print(df_ina1018.PLAYER_ID.shape)
p(df_ina1018.PLAYER_ID)

(43131,)

0        202376
1          2570
2        202340
3        202354
4          2034
43126    202697
43127    203900
43128    201583
43129      2772
43130    201601
Name: PLAYER_ID, dtype: int64

In [17]:
df_ina1018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43131 entries, 0 to 43130
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            43131 non-null  int64
 1   game_date          43131 non-null  object
 2   season             43131 non-null  object
 3   PLAYER_ID          43131 non-null  int64
 4   FIRST_NAME         43131 non-null  object
 5   LAST_NAME          43131 non-null  object
 6   JERSEY_NUM         43131 non-null  object
 7   TEAM_ID            43131 non-null  int64
 8   TEAM_CITY          43131 non-null  object
 9   TEAM_NAME          43131 non-null  object
 10  TEAM_ABBREVIATION  43131 non-null  object
 11  player             43131 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.9+ MB

In [18]:
df_ina1018_pip = df_ina1018[['PLAYER_ID', 'player']].drop_duplicates().reset_index(drop=True)
print(df_ina1018_pip.shape)
p(df_ina1018_pip)

(993, 2)

     PLAYER_ID            player
0       202376    Luke Harangody
1         2570  Kendrick Perkins
2       202340     Avery Bradley
3       202354    Dexter Pittman
4         2034       Mike Miller
988    1626198     Le'Bryan Nash
989    1628389       Bam Adebayo
990    1627748        Thon Maker
991    1628369      Jayson Tatum
992     204065    David Stockton

In [19]:
print(df_ina1018_pip.value_counts('PLAYER_ID').shape)
p(df_ina1018_pip.value_counts('PLAYER_ID'))

(993,)

PLAYER_ID
1628575    1
201585     1
201603     1
201601     1
201600     1
203503     1
203502     1
203501     1
203500     1
255        1
dtype: int64

In [20]:
print(df_ina1018_pip.value_counts('player').shape)
p(df_ina1018_pip.value_counts('player'))

(990,)

player
Marcus Thornton         2
Rashard Lewis           2
Elton Brand             2
Fred VanVleet           1
Georgios Papagiannis    1
Marquis Daniels         1
Marquese Chriss         1
Markieff Morris         1
Markelle Fultz          1
AJ Hammons              1
dtype: int64

In [21]:
df_ina1018_pip.value_counts('player')[df_ina1018_pip.value_counts('player') > 1]

player
Marcus Thornton    2
Rashard Lewis      2
Elton Brand        2
dtype: int64

In [22]:
playerl = list(df_ina1018_pip.value_counts('player')[df_ina1018_pip.value_counts('player') > 1].reset_index().player)
playerl

['Marcus Thornton', 'Rashard Lewis', 'Elton Brand']

In [23]:
df_ina1018[df_ina1018.player.str.contains(playerl[0])]

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
679,21000136,2010-11-13,2010-11,201977,Marcus,Thornton,5,1610612740,New Orleans,Hornets,NOH,Marcus Thornton
726,21000146,2010-11-15,2010-11,201977,Marcus,Thornton,5,1610612740,New Orleans,Hornets,NOH,Marcus Thornton
811,21000163,2010-11-17,2010-11,201977,Marcus,Thornton,5,1610612740,New Orleans,Hornets,NOH,Marcus Thornton
883,21000177,2010-11-19,2010-11,201977,Marcus,Thornton,5,1610612740,New Orleans,Hornets,NOH,Marcus Thornton
11020,21200509,2013-01-07,2012-13,201977,Marcus,Thornton,23,1610612758,Sacramento,Kings,SAC,Marcus Thornton
11943,21200785,2013-02-13,2012-13,201977,Marcus,Thornton,23,1610612758,Sacramento,Kings,SAC,Marcus Thornton
16294,21300743,2014-02-07,2013-14,201977,Marcus,Thornton,23,1610612758,Sacramento,Kings,SAC,Marcus Thornton
16546,21300808,2014-02-19,2013-14,201977,Marcus,Thornton,10,1610612751,Brooklyn,Nets,BKN,Marcus Thornton
18691,21400111,2014-11-12,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
19692,21400357,2014-12-15,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
19749,21400371,2014-12-17,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
19888,21400404,2014-12-21,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
19943,21400418,2014-12-23,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
19997,21400432,2014-12-26,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
20050,21400445,2014-12-27,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
20174,21400475,2014-12-31,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
20222,21400486,2015-01-02,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
20264,21400496,2015-01-03,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
20324,21400510,2015-01-05,2014-15,201977,Marcus,Thornton,4,1610612738,Boston,Celtics,BOS,Marcus Thornton
22485,21401072,2015-03-25,2014-15,201977,Marcus,Thornton,23,1610612756,Phoenix,Suns,PHX,Marcus Thornton
22540,21401086,2015-03-27,2014-15,201977,Marcus,Thornton,23,1610612756,Phoenix,Suns,PHX,Marcus Thornton
22599,21401100,2015-03-29,2014-15,201977,Marcus,Thornton,23,1610612756,Phoenix,Suns,PHX,Marcus Thornton
23029,21401200,2015-04-12,2014-15,201977,Marcus,Thornton,23,1610612756,Phoenix,Suns,PHX,Marcus Thornton
26635,21500843,2016-02-23,2015-16,201977,Marcus,Thornton,10,1610612745,Houston,Rockets,HOU,Marcus Thornton
26692,21500859,2016-02-25,2015-16,201977,Marcus,Thornton,10,1610612745,Houston,Rockets,HOU,Marcus Thornton
40259,21700869,2018-02-22,2017-18,1626194,Marcus,Thornton,52,1610612739,Cleveland,Cavaliers,CLE,Marcus Thornton
40323,21700878,2018-02-23,2017-18,1626194,Marcus,Thornton,99,1610612739,Cleveland,Cavaliers,CLE,Marcus Thornton
40453,21700894,2018-02-25,2017-18,1626194,Marcus,Thornton,52,1610612739,Cleveland,Cavaliers,CLE,Marcus Thornton
40562,21700908,2018-02-27,2017-18,1626194,Marcus,Thornton,52,1610612739,Cleveland,Cavaliers,CLE,Marcus Thornton
40678,21700923,2018-03-01,2017-18,1626194,Marcus,Thornton,52,1610612739,Cleveland,Cavaliers,CLE,Marcus Thornton
40780,21700937,2018-03-03,2017-18,1626194,Marcus,Thornton,52,1610612739,Cleveland,Cavaliers,CLE,Marcus Thornton

In [24]:
print(df_ina1018.shape)
p(df_ina1018)

(43131, 12)

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
0,21000001,2010-10-26,2010-11,202376,Luke,Harangody,55,1610612738,Boston,Celtics,BOS,Luke Harangody
1,21000001,2010-10-26,2010-11,2570,Kendrick,Perkins,43,1610612738,Boston,Celtics,BOS,Kendrick Perkins
2,21000001,2010-10-26,2010-11,202340,Avery,Bradley,0,1610612738,Boston,Celtics,BOS,Avery Bradley
3,21000001,2010-10-26,2010-11,202354,Dexter,Pittman,45,1610612748,Miami,Heat,MIA,Dexter Pittman
4,21000001,2010-10-26,2010-11,2034,Mike,Miller,13,1610612748,Miami,Heat,MIA,Mike Miller
43126,21701230,2018-04-11,2017-18,202697,Iman,Shumpert,4,1610612758,Sacramento,Kings,SAC,Iman Shumpert
43127,21701230,2018-04-11,2017-18,203900,Markel,Brown,26,1610612745,Houston,Rockets,HOU,Markel Brown
43128,21701230,2018-04-11,2017-18,201583,Ryan,Anderson,33,1610612745,Houston,Rockets,HOU,Ryan Anderson
43129,21701230,2018-04-11,2017-18,2772,Trevor,Ariza,1,1610612745,Houston,Rockets,HOU,Trevor Ariza
43130,21701230,2018-04-11,2017-18,201601,Luc,Mbah a Moute,12,1610612745,Houston,Rockets,HOU,Luc Mbah a Moute

In [25]:
'''print(df_ina1018[df_ina1018.PLAYER_ID != '1626194'].shape)
p(df_ina1018[df_ina1018.PLAYER_ID != '1626194'])'''
df_ina1018 = drop_rows(df_ina1018).reset_index(drop=True)
df_ina1018 = edit_player_id(df_ina1018)
print(df_ina1018.shape)
p(df_ina1018)

(43125, 12)

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
0,21000001,2010-10-26,2010-11,202376,Luke,Harangody,55,1610612738,Boston,Celtics,BOS,Luke Harangody
1,21000001,2010-10-26,2010-11,2570,Kendrick,Perkins,43,1610612738,Boston,Celtics,BOS,Kendrick Perkins
2,21000001,2010-10-26,2010-11,202340,Avery,Bradley,0,1610612738,Boston,Celtics,BOS,Avery Bradley
3,21000001,2010-10-26,2010-11,202354,Dexter,Pittman,45,1610612748,Miami,Heat,MIA,Dexter Pittman
4,21000001,2010-10-26,2010-11,2034,Mike,Miller,13,1610612748,Miami,Heat,MIA,Mike Miller
43120,21701230,2018-04-11,2017-18,202697,Iman,Shumpert,4,1610612758,Sacramento,Kings,SAC,Iman Shumpert
43121,21701230,2018-04-11,2017-18,203900,Markel,Brown,26,1610612745,Houston,Rockets,HOU,Markel Brown
43122,21701230,2018-04-11,2017-18,201583,Ryan,Anderson,33,1610612745,Houston,Rockets,HOU,Ryan Anderson
43123,21701230,2018-04-11,2017-18,2772,Trevor,Ariza,1,1610612745,Houston,Rockets,HOU,Trevor Ariza
43124,21701230,2018-04-11,2017-18,201601,Luc,Mbah a Moute,12,1610612745,Houston,Rockets,HOU,Luc Mbah a Moute

In [26]:
df_ina1018[df_ina1018.player.str.contains(playerl[1])]

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
1956,21000393,2010-12-18,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
2036,21000409,2010-12-20,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
3878,21000798,2011-02-12,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
3917,21000806,2011-02-13,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4003,21000824,2011-02-16,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4571,21000950,2011-03-08,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4708,21000978,2011-03-12,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4777,21000992,2011-03-14,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4818,21001001,2011-03-15,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4905,21001019,2011-03-18,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4987,21001035,2011-03-20,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5072,21001052,2011-03-22,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5134,21001065,2011-03-23,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5187,21001076,2011-03-25,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5273,21001093,2011-03-27,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5308,21001100,2011-03-28,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5361,21001110,2011-03-30,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5425,21001123,2011-04-01,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5512,21001141,2011-04-03,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5575,21001153,2011-04-05,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5623,21001163,2011-04-06,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5707,21001179,2011-04-08,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5754,21001188,2011-04-09,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5843,21001205,2011-04-11,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5913,21001218,2011-04-13,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
7853,21100594,2012-03-10,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
7908,21100614,2012-03-12,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
7935,21100623,2012-03-13,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8057,21100664,2012-03-18,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8120,21100686,2012-03-21,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8142,21100693,2012-03-22,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8198,21100711,2012-03-24,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8230,21100721,2012-03-25,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8252,21100728,2012-03-26,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8336,21100753,2012-03-29,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8351,21100758,2012-03-30,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8420,21100779,2012-04-01,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8444,21100785,2012-04-02,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8487,21100800,2012-04-04,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8526,21100812,2012-04-05,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8544,21100817,2012-04-06,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8621,21100842,2012-04-09,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8654,21100852,2012-04-10,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8741,21100878,2012-04-13,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8773,21100887,2012-04-14,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8842,21100907,2012-04-16,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8879,21100918,2012-04-18,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8966,21100945,2012-04-21,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
9022,21100960,2012-04-23,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
9064,21100972,2012-04-25,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
9094,21100981,2012-04-26,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis

<font color='red'> just one instance of a different PLAYER_ID for Rashard Lewis???</font>

In [27]:
df_ina1018[df_ina1018.PLAYER_ID == 27596]

Empty DataFrame
Columns: [game_id, game_date, season, PLAYER_ID, FIRST_NAME, LAST_NAME, JERSEY_NUM, TEAM_ID, TEAM_CITY, TEAM_NAME, TEAM_ABBREVIATION, player]
Index: []

In [28]:
df_ina1018[df_ina1018.PLAYER_ID == 27596].index

Int64Index([], dtype='int64')

In [29]:

#df_ina1018.at[1956, 'PLAYER_ID'] = 1740

In [30]:
df_ina1018[df_ina1018.player.str.contains(playerl[1])]

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
1956,21000393,2010-12-18,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
2036,21000409,2010-12-20,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
3878,21000798,2011-02-12,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
3917,21000806,2011-02-13,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4003,21000824,2011-02-16,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4571,21000950,2011-03-08,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4708,21000978,2011-03-12,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4777,21000992,2011-03-14,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4818,21001001,2011-03-15,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4905,21001019,2011-03-18,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
4987,21001035,2011-03-20,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5072,21001052,2011-03-22,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5134,21001065,2011-03-23,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5187,21001076,2011-03-25,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5273,21001093,2011-03-27,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5308,21001100,2011-03-28,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5361,21001110,2011-03-30,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5425,21001123,2011-04-01,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5512,21001141,2011-04-03,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5575,21001153,2011-04-05,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5623,21001163,2011-04-06,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5707,21001179,2011-04-08,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5754,21001188,2011-04-09,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5843,21001205,2011-04-11,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
5913,21001218,2011-04-13,2010-11,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
7853,21100594,2012-03-10,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
7908,21100614,2012-03-12,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
7935,21100623,2012-03-13,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8057,21100664,2012-03-18,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8120,21100686,2012-03-21,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8142,21100693,2012-03-22,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8198,21100711,2012-03-24,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8230,21100721,2012-03-25,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8252,21100728,2012-03-26,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8336,21100753,2012-03-29,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8351,21100758,2012-03-30,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8420,21100779,2012-04-01,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8444,21100785,2012-04-02,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8487,21100800,2012-04-04,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8526,21100812,2012-04-05,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8544,21100817,2012-04-06,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8621,21100842,2012-04-09,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8654,21100852,2012-04-10,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8741,21100878,2012-04-13,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8773,21100887,2012-04-14,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8842,21100907,2012-04-16,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8879,21100918,2012-04-18,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
8966,21100945,2012-04-21,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
9022,21100960,2012-04-23,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
9064,21100972,2012-04-25,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis
9094,21100981,2012-04-26,2011-12,1740,Rashard,Lewis,9,1610612764,Washington,Wizards,WAS,Rashard Lewis

In [31]:
df_ina1018[df_ina1018.player.str.contains(playerl[2])]

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
7092,21100343,2012-02-04,2011-12,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
7136,21100357,2012-02-06,2011-12,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
9072,21100975,2012-04-25,2011-12,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
9082,21100978,2012-04-26,2011-12,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
14256,21300190,2013-11-23,2013-14,1882,Elton,Brand,42,1610612737,Atlanta,Hawks,ATL,Elton Brand
14339,21300213,2013-11-26,2013-14,1882,Elton,Brand,42,1610612737,Atlanta,Hawks,ATL,Elton Brand
25260,21500512,2016-01-04,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25363,21500536,2016-01-07,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25441,21500554,2016-01-09,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25461,21500559,2016-01-10,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25578,21500587,2016-01-14,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25657,21500606,2016-01-16,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25695,21500615,2016-01-18,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25752,21500629,2016-01-20,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
25867,21500656,2016-01-24,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
26077,21500707,2016-01-30,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
26201,21500736,2016-02-03,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
26375,21500777,2016-02-08,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
26432,21500791,2016-02-10,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
26513,21500811,2016-02-19,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand
26587,21500830,2016-02-21,2015-16,1882,Elton,Brand,42,1610612755,Philadelphia,76ers,PHI,Elton Brand

In [32]:
for i in range(len(playerl)):
    print(df_ina1018[df_ina1018.player.str.contains(playerl[i])][['PLAYER_ID', 'player']].value_counts('PLAYER_ID'))
    print()

PLAYER_ID
201977    25
dtype: int64

PLAYER_ID
1740    51
dtype: int64

PLAYER_ID
1882    21
dtype: int64

In [33]:
df_ina1018_pip = df_ina1018[['PLAYER_ID', 'player']].drop_duplicates().reset_index(drop=True)
print(df_ina1018_pip.shape)
p(df_ina1018_pip)

(990, 2)

     PLAYER_ID            player
0       202376    Luke Harangody
1         2570  Kendrick Perkins
2       202340     Avery Bradley
3       202354    Dexter Pittman
4         2034       Mike Miller
985    1626198     Le'Bryan Nash
986    1628389       Bam Adebayo
987    1627748        Thon Maker
988    1628369      Jayson Tatum
989     204065    David Stockton

In [34]:
print(df_ina1018_pip.value_counts('PLAYER_ID').shape)
p(df_ina1018_pip.value_counts('PLAYER_ID'))

(990,)

PLAYER_ID
1628575    1
201611     1
201604     1
201603     1
201601     1
203504     1
203503     1
203502     1
203501     1
255        1
dtype: int64

In [35]:
print(df_ina1018_pip.value_counts('player').shape)
p(df_ina1018_pip.value_counts('player'))

(990,)

player
Zydrunas Ilgauskas      1
Gerald Wallace          1
Gerald Green            1
Georgios Papagiannis    1
Georges Niang           1
Marquis Daniels         1
Marquese Chriss         1
Markieff Morris         1
Markelle Fultz          1
AJ Hammons              1
dtype: int64

In [36]:
df_ina1018_pip.value_counts('player')[df_ina1018_pip.value_counts('player') > 1]

Series([], dtype: int64)

In [37]:
replace_player(df_ina1018)

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
0,21000001,2010-10-26,2010-11,202376,Luke,Harangody,55,1610612738,Boston,Celtics,BOS,Luke Harangody
1,21000001,2010-10-26,2010-11,2570,Kendrick,Perkins,43,1610612738,Boston,Celtics,BOS,Kendrick Perkins
2,21000001,2010-10-26,2010-11,202340,Avery,Bradley,0,1610612738,Boston,Celtics,BOS,Avery Bradley
3,21000001,2010-10-26,2010-11,202354,Dexter,Pittman,45,1610612748,Miami,Heat,MIA,Dexter Pittman
4,21000001,2010-10-26,2010-11,2034,Mike,Miller,13,1610612748,Miami,Heat,MIA,Mike Miller
...,...,...,...,...,...,...,...,...,...,...,...,...
43120,21701230,2018-04-11,2017-18,202697,Iman,Shumpert,4,1610612758,Sacramento,Kings,SAC,Iman Shumpert
43121,21701230,2018-04-11,2017-18,203900,Markel,Brown,26,1610612745,Houston,Rockets,HOU,Markel Brown
43122,21701230,2018-04-11,2017-18,201583,Ryan,Anderson,33,1610612745,Houston,Rockets,HOU,Ryan Anderson
43123,21701230,2018-04-11,2017-18,2772,Trevor,Ariza,1,1610612745,Houston,Rockets,HOU,Trevor Ariza
43124,21701230,2018-04-11,2017-18,201601,Luc,Mbah a Moute,12,1610612745,Houston,Rockets,HOU,Luc Mbah a Moute

In [38]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 'A11inactive_game_id_team_id_player_id_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_ina1018.to_csv(datapath_df, index=False)