In [1]:

####################################
#add game_date

#add team_id_away and team_id_home: df_empty_tiah

##############################################/////////////////
#get _away nba advanced boxscores into a dataframe

#filter for away games from 'df_tbsa1018_tiah'

#rename columns of away games 

#filter for numerics and save dataframe: df_away_gin

#filter for away non-numerics and save dataframe: df_away_ginn

#################################################//////////////////////
#get _home nba advanced boxscores into a dataframe

#filter for home games

#rename columns of home games

#filter for numerics and save dataframe: df_home_gin

#filter for home non-numerics and sae dataframe: df_home_ginn


#############################################///////////////////////////

#create list of columns from df_away_gin: col_away_ngin

#create list of columns from df_home_gin: col_home_ngin

#add 'col_home_ngin' column names to 'df_away_gin' with value 0

#add 'col_away_ngin' column names to 'df_home_gin' with value 0

############################################////////////////////////////

#concat the two dataframes 'df_away_gin' and 'df_home_gin': df_away_home_gin

#groupby 'game_id' and sum()


########################?/////////////////////////////////
#add 'df_away_ginn' and 'df_home_ginn' to 'df_away_home_gin': df_away_home

#sort each dataframe 'df_away_ginn', 'df_home_ginn', and 'df_away_home_gin' by game_id

#check for game_id equal between all three as all True

#concat the three dataframes

#drop extra game_id's and save dataframe: df_away_home

#######################################////////////////////////////////////////

#check for consistency between 'TEAM_NAME_away' and 'team_id_away'

#check for consistency between 'TEAM_NAME_home' and 'team_id_home'

#########################################//////////////////////

#get matchups

#concat abbreviations, e.g. GSWMIA and check and change/reverse non-alphabetic orderings

#add vs. in between, e.g. GSW vs. MIA

In [2]:
'''from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))'''

'from IPython.core.display import display, HTML\ndisplay(HTML("<style>.container { width:90% !important; }</style>"))'

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import numpy as np


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [4]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [5]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [6]:
df_tbsa0618 = rcp('19boxscoreadvancedv2_team_2006_2018.csv')
p(df_tbsa0618)

(31036, 31)

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration,duration_minutes
0,21000961,1610612740,Hornets,NOH,New Orleans,240:00,102.5,106.9,102.1,105.7,0.3,1.1,0.382,1.44,11.5,0.319,NaN,NaN,9.916,10.3,0.462,0.512,1.0,0.198,90.42,87.0,72.50,87,0.479,0 days 04:00:00,240.0
1,21000961,1610612742,Mavericks,DAL,Dallas,240:00,102.1,105.7,102.5,106.9,-0.3,-1.1,0.710,2.00,19.0,NaN,0.681,NaN,12.211,12.6,0.493,0.554,1.0,0.191,90.42,87.0,72.50,87,0.521,0 days 04:00:00,240.0
2,21000962,1610612759,Spurs,SAS,San Antonio,240:00,125.0,124.7,110.9,118.2,14.1,6.5,0.467,1.40,18.3,0.222,0.556,0.444,16.892,16.9,0.686,0.704,1.0,0.198,91.30,88.5,73.75,89,0.610,0 days 04:00:00,240.0
3,21000962,1610612765,Pistons,DET,Detroit,240:00,110.9,118.2,125.0,124.7,-14.1,-6.5,0.524,1.83,16.2,0.444,0.778,0.556,12.793,13.6,0.484,0.511,1.0,0.197,91.30,88.5,73.75,88,0.390,0 days 04:00:00,240.0
4,21000963,1610612758,Kings,SAC,Sacramento,240:00,97.0,101.0,104.9,106.0,-7.9,-5.0,0.529,0.86,12.9,0.370,0.841,0.582,19.970,20.8,0.440,0.509,1.0,0.196,103.12,100.5,83.75,101,0.478,0 days 04:00:00,240.0
31031,21700898,1610612738,Celtics,BOS,Boston,240:00,112.5,111.2,100.9,101.0,11.6,10.2,0.641,3.13,19.1,0.231,0.830,0.515,8.258,8.2,0.523,0.557,1.0,0.200,96.98,97.5,81.25,98,0.529,0 days 04:00:00,240.0
31032,21700899,1610612741,Bulls,CHI,Chicago,240:00,85.2,87.0,102.4,104.0,-17.2,-17.0,0.515,1.21,12.7,0.297,0.840,0.535,13.709,14.0,0.387,0.422,1.0,0.198,101.82,100.0,83.33,100,0.408,0 days 04:00:00,240.0
31033,21700899,1610612751,Nets,BKN,Brooklyn,240:00,102.4,104.0,85.2,87.0,17.2,17.0,0.775,2.07,22.2,0.160,0.703,0.465,14.775,15.0,0.533,0.556,1.0,0.195,101.82,100.0,83.33,100,0.592,0 days 04:00:00,240.0
31034,21700900,1610612752,Knicks,NYK,New York,240:00,106.8,109.9,124.5,121.4,-17.7,-11.5,0.596,2.00,19.7,0.265,0.762,0.495,13.467,13.9,0.542,0.555,1.0,0.200,102.20,102.0,85.00,101,0.421,0 days 04:00:00,240.0
31035,21700900,1610612744,Warriors,GSW,Golden State,240:00,124.5,121.4,106.8,109.9,17.7,11.5,0.705,2.58,22.2,0.238,0.735,0.505,11.947,11.7,0.606,0.648,1.0,0.201,102.20,102.0,85.00,103,0.579,0 days 04:00:00,240.0

In [7]:
df_game1018 = rcp('18game_id_team_id_home_away_2010_2018.csv', ['game_date'])
p(df_game1018)

(10267, 51)

,game_id,game_date,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000002,2010-10-26,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
1,21000001,2010-10-26,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
2,21000003,2010-10-26,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
3,21000005,2010-10-27,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,Regular Season,2010-11,2010,L,W,-3,3
4,21000004,2010-10-27,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010,L,W,-8,8
10262,41700317,2018-05-28,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10263,41700401,2018-05-31,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10264,41700402,2018-06-03,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10265,41700403,2018-06-06,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10266,41700404,2018-06-08,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [8]:
#add game_date

#add team_id_away and team_id_home: df_empty_tiah


df_tbsa1018_tiah = pd.merge(df_game1018[['game_id', 'game_date', 'team_id_away', 'team_id_home']], df_tbsa0618.rename(columns={'GAME_ID':'game_id'}),
         on=['game_id'], how='inner')
p(df_tbsa1018_tiah)

(20532, 34)

,game_id,game_date,team_id_away,team_id_home,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration,duration_minutes
0,21000002,2010-10-26,1610612756,1610612757,1610612757,Trail Blazers,POR,Portland,240:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,0 days 04:00:00,240.0
1,21000002,2010-10-26,1610612756,1610612757,1610612756,Suns,PHX,Phoenix,240:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,0 days 04:00:00,240.0
2,21000001,2010-10-26,1610612748,1610612738,1610612748,Heat,MIA,Miami,240:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,0 days 04:00:00,240.0
3,21000001,2010-10-26,1610612748,1610612738,1610612738,Celtics,BOS,Boston,240:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,0 days 04:00:00,240.0
4,21000003,2010-10-26,1610612745,1610612747,1610612747,Lakers,LAL,Los Angeles,240:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,0 days 04:00:00,240.0
20527,41700402,2018-06-03,1610612739,1610612744,1610612739,Cavaliers,CLE,Cleveland,240:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.5,79.58,97,0.435,0 days 04:00:00,240.0
20528,41700403,2018-06-06,1610612744,1610612739,1610612744,Warriors,GSW,Golden State,240:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,0 days 04:00:00,240.0
20529,41700403,2018-06-06,1610612744,1610612739,1610612739,Cavaliers,CLE,Cleveland,240:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,0 days 04:00:00,240.0
20530,41700404,2018-06-08,1610612744,1610612739,1610612744,Warriors,GSW,Golden State,240:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,0 days 04:00:00,240.0
20531,41700404,2018-06-08,1610612744,1610612739,1610612739,Cavaliers,CLE,Cleveland,240:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,0 days 04:00:00,240.0

In [9]:
20532/2

10266.0

In [10]:
#get _away nba advanced boxscores into a dataframe

#filter for away games from 'df_tbsa1018_tiah'

#rename columns of away games

In [11]:
#get _away nba advanced boxscores into a dataframe

#filter for away games from 'df_tbsa1018_tiah'
df_away = df_tbsa1018_tiah[df_tbsa1018_tiah.TEAM_ID == df_tbsa1018_tiah.team_id_away].drop(
    columns=['team_id_away', 'team_id_home'])
df_away = df_away.sort_values('game_date').reset_index(drop=True)
p(df_away)

(10266, 32)

,game_id,game_date,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration,duration_minutes
0,21000002,2010-10-26,1610612756,Suns,PHX,Phoenix,240:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,0 days 04:00:00,240.0
1,21000001,2010-10-26,1610612748,Heat,MIA,Miami,240:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,0 days 04:00:00,240.0
2,21000003,2010-10-26,1610612745,Rockets,HOU,Houston,240:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,0 days 04:00:00,240.0
3,21000011,2010-10-27,1610612741,Bulls,CHI,Chicago,240:00,92.5,94.1,104.2,107.1,-11.7,-13.0,0.525,1.40,15.1,0.379,0.755,0.551,14.608,14.9,0.441,0.463,1.0,0.201,102.18,100.00,83.33,101,0.397,0 days 04:00:00,240.0
4,21000007,2010-10-27,1610612752,Knicks,NYK,New York,240:00,99.5,100.0,88.9,93.9,10.6,6.1,0.316,0.75,9.7,0.275,0.644,0.473,16.247,16.3,0.472,0.513,1.0,0.197,101.52,98.50,82.08,98,0.522,0 days 04:00:00,240.0
10261,41700317,2018-05-28,1610612744,Warriors,GSW,Golden State,240:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,0 days 04:00:00,240.0
10262,41700401,2018-05-31,1610612739,Cavaliers,CLE,Cleveland,265:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,0 days 04:25:00,265.0
10263,41700402,2018-06-03,1610612739,Cavaliers,CLE,Cleveland,240:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,0 days 04:00:00,240.0
10264,41700403,2018-06-06,1610612744,Warriors,GSW,Golden State,240:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,0 days 04:00:00,240.0
10265,41700404,2018-06-08,1610612744,Warriors,GSW,Golden State,240:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,0 days 04:00:00,240.0

In [12]:
#rename columns of away games

In [13]:
away_cols = list(df_away.columns)
print(away_cols)

['game_id', 'game_date', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'MIN', 'E_OFF_RATING', 'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT', 'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'E_TM_TOV_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE', 'duration', 'duration_minutes']

In [14]:
away_home_cols = [k for k in away_cols if k not in ['game_id', 'game_date']]
away_home_cols

['TEAM_ID',
 'TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration',
 'duration_minutes']

In [15]:
for column in away_home_cols:
    df_away.rename(columns={column:(column+'_away')}, inplace=True)

In [16]:
#filter for numerics and save dataframe: df_away_gin

#filter for away non-numerics and save dataframe: df_away_ginn

In [17]:
#filter for numerics and save dataframe: df_away_gin

In [18]:
p(df_away)

(10266, 32)

,game_id,game_date,TEAM_ID_away,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_away,duration_minutes_away
0,21000002,2010-10-26,1610612756,Suns,PHX,Phoenix,240:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,0 days 04:00:00,240.0
1,21000001,2010-10-26,1610612748,Heat,MIA,Miami,240:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,0 days 04:00:00,240.0
2,21000003,2010-10-26,1610612745,Rockets,HOU,Houston,240:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,0 days 04:00:00,240.0
3,21000011,2010-10-27,1610612741,Bulls,CHI,Chicago,240:00,92.5,94.1,104.2,107.1,-11.7,-13.0,0.525,1.40,15.1,0.379,0.755,0.551,14.608,14.9,0.441,0.463,1.0,0.201,102.18,100.00,83.33,101,0.397,0 days 04:00:00,240.0
4,21000007,2010-10-27,1610612752,Knicks,NYK,New York,240:00,99.5,100.0,88.9,93.9,10.6,6.1,0.316,0.75,9.7,0.275,0.644,0.473,16.247,16.3,0.472,0.513,1.0,0.197,101.52,98.50,82.08,98,0.522,0 days 04:00:00,240.0
10261,41700317,2018-05-28,1610612744,Warriors,GSW,Golden State,240:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,0 days 04:00:00,240.0
10262,41700401,2018-05-31,1610612739,Cavaliers,CLE,Cleveland,265:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,0 days 04:25:00,265.0
10263,41700402,2018-06-03,1610612739,Cavaliers,CLE,Cleveland,240:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,0 days 04:00:00,240.0
10264,41700403,2018-06-06,1610612744,Warriors,GSW,Golden State,240:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,0 days 04:00:00,240.0
10265,41700404,2018-06-08,1610612744,Warriors,GSW,Golden State,240:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,0 days 04:00:00,240.0

In [19]:
away_cols_n = list(df_away.select_dtypes('number').columns)
away_cols_n

['game_id',
 'TEAM_ID_away',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away']

In [20]:
df_away_gin = pd.DataFrame({})
df_away_gin = df_away[away_cols_n]
p(df_away_gin)

(10266, 26)

,game_id,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away
0,21000002,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0
1,21000001,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0
2,21000003,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0
3,21000011,1610612741,92.5,94.1,104.2,107.1,-11.7,-13.0,0.525,1.40,15.1,0.379,0.755,0.551,14.608,14.9,0.441,0.463,1.0,0.201,102.18,100.00,83.33,101,0.397,240.0
4,21000007,1610612752,99.5,100.0,88.9,93.9,10.6,6.1,0.316,0.75,9.7,0.275,0.644,0.473,16.247,16.3,0.472,0.513,1.0,0.197,101.52,98.50,82.08,98,0.522,240.0
10261,41700317,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0
10262,41700401,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0
10263,41700402,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0
10264,41700403,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0
10265,41700404,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0

In [21]:
#filter for away non-numerics and save dataframe: df_away_ginn

In [22]:
away_cols_n.remove('game_id')
away_cols_ngin = away_cols_n
away_cols_ngin

['TEAM_ID_away',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away']

In [23]:
away_cols_ginn = [k for k in df_away.columns if k not in away_cols_ngin]
away_cols_ginn

['game_id',
 'game_date',
 'TEAM_NAME_away',
 'TEAM_ABBREVIATION_away',
 'TEAM_CITY_away',
 'MIN_away',
 'duration_away']

In [24]:
df_away_ginn = df_away[away_cols_ginn]
p(df_away_ginn)

(10266, 7)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away
0,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00
1,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00
3,21000011,2010-10-27,Bulls,CHI,Chicago,240:00,0 days 04:00:00
4,21000007,2010-10-27,Knicks,NYK,New York,240:00,0 days 04:00:00
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00

In [25]:
df_away_ginn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10266 entries, 0 to 10265
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 10266 non-null  int64
 1   game_date               10266 non-null  datetime64[ns]
 2   TEAM_NAME_away          10266 non-null  object
 3   TEAM_ABBREVIATION_away  10266 non-null  object
 4   TEAM_CITY_away          10266 non-null  object
 5   MIN_away                10266 non-null  object
 6   duration_away           10266 non-null  object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 561.5+ KB

In [26]:
#get _home nba advanced boxscores into a dataframe

#filter for home games

#rename columns of home games

#filter for numerics and save dataframe: df_home_gin

#filter for home non-numerics and sae dataframe: df_home_ginn

In [27]:
#get _home nba advanced boxscores into a dataframe

#filter for home games

In [28]:
df_home = df_tbsa1018_tiah[df_tbsa1018_tiah.TEAM_ID == df_tbsa1018_tiah.team_id_home].drop(
    columns=['team_id_away', 'team_id_home'])
df_home = df_home.sort_values('game_date').reset_index(drop=True)
p(df_home)

(10266, 32)

,game_id,game_date,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration,duration_minutes
0,21000002,2010-10-26,1610612757,Trail Blazers,POR,Portland,240:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,0 days 04:00:00,240.0
1,21000001,2010-10-26,1610612738,Celtics,BOS,Boston,240:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,0 days 04:00:00,240.0
2,21000003,2010-10-26,1610612747,Lakers,LAL,Los Angeles,240:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,0 days 04:00:00,240.0
3,21000011,2010-10-27,1610612760,Thunder,OKC,Oklahoma City,240:00,104.2,107.1,92.5,94.1,11.7,13.0,0.531,1.42,13.3,0.245,0.621,0.449,11.802,12.1,0.436,0.537,1.0,0.201,102.18,100.00,83.33,99,0.603,0 days 04:00:00,240.0
4,21000007,2010-10-27,1610612761,Raptors,TOR,Toronto,240:00,88.9,93.9,99.5,100.0,-10.6,-6.1,0.556,1.67,14.6,0.356,0.725,0.527,11.477,12.1,0.399,0.445,1.0,0.199,101.52,98.50,82.08,99,0.478,0 days 04:00:00,240.0
10261,41700317,2018-05-28,1610612745,Rockets,HOU,Houston,240:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,0 days 04:00:00,240.0
10262,41700401,2018-05-31,1610612744,Warriors,GSW,Golden State,265:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,0 days 04:25:00,265.0
10263,41700402,2018-06-03,1610612744,Warriors,GSW,Golden State,240:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,0 days 04:00:00,240.0
10264,41700403,2018-06-06,1610612739,Cavaliers,CLE,Cleveland,240:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,0 days 04:00:00,240.0
10265,41700404,2018-06-08,1610612739,Cavaliers,CLE,Cleveland,240:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,0 days 04:00:00,240.0

In [29]:
#rename columns of home games

In [30]:
away_home_cols

['TEAM_ID',
 'TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration',
 'duration_minutes']

In [31]:
for column in away_home_cols:
    df_home.rename(columns={column:(column+'_home')}, inplace=True)

In [32]:
p(df_home)

(10266, 32)

,game_id,game_date,TEAM_ID_home,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_home,duration_minutes_home
0,21000002,2010-10-26,1610612757,Trail Blazers,POR,Portland,240:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,0 days 04:00:00,240.0
1,21000001,2010-10-26,1610612738,Celtics,BOS,Boston,240:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,0 days 04:00:00,240.0
2,21000003,2010-10-26,1610612747,Lakers,LAL,Los Angeles,240:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,0 days 04:00:00,240.0
3,21000011,2010-10-27,1610612760,Thunder,OKC,Oklahoma City,240:00,104.2,107.1,92.5,94.1,11.7,13.0,0.531,1.42,13.3,0.245,0.621,0.449,11.802,12.1,0.436,0.537,1.0,0.201,102.18,100.00,83.33,99,0.603,0 days 04:00:00,240.0
4,21000007,2010-10-27,1610612761,Raptors,TOR,Toronto,240:00,88.9,93.9,99.5,100.0,-10.6,-6.1,0.556,1.67,14.6,0.356,0.725,0.527,11.477,12.1,0.399,0.445,1.0,0.199,101.52,98.50,82.08,99,0.478,0 days 04:00:00,240.0
10261,41700317,2018-05-28,1610612745,Rockets,HOU,Houston,240:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,0 days 04:00:00,240.0
10262,41700401,2018-05-31,1610612744,Warriors,GSW,Golden State,265:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,0 days 04:25:00,265.0
10263,41700402,2018-06-03,1610612744,Warriors,GSW,Golden State,240:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,0 days 04:00:00,240.0
10264,41700403,2018-06-06,1610612739,Cavaliers,CLE,Cleveland,240:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,0 days 04:00:00,240.0
10265,41700404,2018-06-08,1610612739,Cavaliers,CLE,Cleveland,240:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,0 days 04:00:00,240.0

In [33]:
#filter for numerics and save dataframe: df_home_gin

#filter for home non-numerics and sae dataframe: df_home_ginn

In [34]:
#filter for numerics and save dataframe: df_home_gin

In [35]:
home_cols_n = list(df_home.select_dtypes('number').columns)
home_cols_n

['game_id',
 'TEAM_ID_home',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home']

In [36]:
df_home_gin = pd.DataFrame({})
df_home_gin = df_home[home_cols_n]
p(df_home_gin)

(10266, 26)

,game_id,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000002,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
1,21000001,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
2,21000003,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000011,1610612760,104.2,107.1,92.5,94.1,11.7,13.0,0.531,1.42,13.3,0.245,0.621,0.449,11.802,12.1,0.436,0.537,1.0,0.201,102.18,100.00,83.33,99,0.603,240.0
4,21000007,1610612761,88.9,93.9,99.5,100.0,-10.6,-6.1,0.556,1.67,14.6,0.356,0.725,0.527,11.477,12.1,0.399,0.445,1.0,0.199,101.52,98.50,82.08,99,0.478,240.0
10261,41700317,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [37]:
#filter for home non-numerics and sae dataframe: df_home_ginn

In [38]:
home_cols_n.remove('game_id')
home_cols_ngin = home_cols_n
home_cols_ngin

['TEAM_ID_home',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home']

In [39]:
home_cols_ginn = [k for k in df_home.columns if k not in home_cols_ngin]
home_cols_ginn

['game_id',
 'game_date',
 'TEAM_NAME_home',
 'TEAM_ABBREVIATION_home',
 'TEAM_CITY_home',
 'MIN_home',
 'duration_home']

In [40]:
df_home_ginn = df_home[home_cols_ginn]
p(df_home_ginn)

(10266, 7)

,game_id,game_date,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home
0,21000002,2010-10-26,Trail Blazers,POR,Portland,240:00,0 days 04:00:00
1,21000001,2010-10-26,Celtics,BOS,Boston,240:00,0 days 04:00:00
2,21000003,2010-10-26,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00
3,21000011,2010-10-27,Thunder,OKC,Oklahoma City,240:00,0 days 04:00:00
4,21000007,2010-10-27,Raptors,TOR,Toronto,240:00,0 days 04:00:00
10261,41700317,2018-05-28,Rockets,HOU,Houston,240:00,0 days 04:00:00
10262,41700401,2018-05-31,Warriors,GSW,Golden State,265:00,0 days 04:25:00
10263,41700402,2018-06-03,Warriors,GSW,Golden State,240:00,0 days 04:00:00
10264,41700403,2018-06-06,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00
10265,41700404,2018-06-08,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00

In [41]:
#create list of columns from df_away_gin: col_away_ngin

#create list of columns from df_home_gin: col_home_ngin

#add 'col_home_ngin' column names to 'df_away_gin' with value 0

#add 'col_away_ngin' column names to 'df_home_gin' with value 0

In [42]:
#create list of columns from df_away_gin: col_away_ngin


col_away_gin = list(df_away_gin.columns)
col_away_gin.remove('game_id')
col_away_ngin = col_away_gin
col_away_ngin

['TEAM_ID_away',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away']

In [43]:
#create list of columns from df_home_gin: col_home_ngin

col_home_gin = list(df_home_gin.columns)
col_home_gin.remove('game_id')
col_home_ngin = col_home_gin
col_home_ngin

['TEAM_ID_home',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home']

In [44]:
#add 'col_home_ngin' column names to 'df_away_gin' with value 0

df_away_gin.loc[:, col_home_ngin] = 0
p(df_away_gin)

(10266, 51)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:659: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[k] = np.nan

,game_id,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000002,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,21000001,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,21000003,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,21000011,1610612741,92.5,94.1,104.2,107.1,-11.7,-13.0,0.525,1.40,15.1,0.379,0.755,0.551,14.608,14.9,0.441,0.463,1.0,0.201,102.18,100.00,83.33,101,0.397,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,21000007,1610612752,99.5,100.0,88.9,93.9,10.6,6.1,0.316,0.75,9.7,0.275,0.644,0.473,16.247,16.3,0.472,0.513,1.0,0.197,101.52,98.50,82.08,98,0.522,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10261,41700317,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10262,41700401,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10263,41700402,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10264,41700403,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10265,41700404,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [45]:
#add 'col_away_ngin' column names to 'df_home_gin' with value 0

df_home_gin.loc[:, col_away_ngin] = 0
p(df_home_gin)

(10266, 51)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:659: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[k] = np.nan

,game_id,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away
0,21000002,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,21000001,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,21000003,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,21000011,1610612760,104.2,107.1,92.5,94.1,11.7,13.0,0.531,1.42,13.3,0.245,0.621,0.449,11.802,12.1,0.436,0.537,1.0,0.201,102.18,100.00,83.33,99,0.603,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,21000007,1610612761,88.9,93.9,99.5,100.0,-10.6,-6.1,0.556,1.67,14.6,0.356,0.725,0.527,11.477,12.1,0.399,0.445,1.0,0.199,101.52,98.50,82.08,99,0.478,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10261,41700317,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10262,41700401,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10263,41700402,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10264,41700403,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10265,41700404,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [46]:
#concat the two dataframes 'df_away_gin' and 'df_home_gin'

#groupby 'game_id' and sum()

In [47]:
#concat the two dataframes 'df_away_gin' and 'df_home_gin'

In [48]:
df_away_home_gin = pd.concat([df_away_gin, df_home_gin])
p(df_away_home_gin)

(20532, 51)

,game_id,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000002,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.00,0.00,0,0.000,0.0
1,21000001,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.00,0.00,0,0.000,0.0
2,21000003,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.00,0.00,0,0.000,0.0
3,21000011,1610612741,92.5,94.1,104.2,107.1,-11.7,-13.0,0.525,1.40,15.1,0.379,0.755,0.551,14.608,14.9,0.441,0.463,1.0,0.201,102.18,100.0,83.33,101,0.397,240.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.00,0.00,0,0.000,0.0
4,21000007,1610612752,99.5,100.0,88.9,93.9,10.6,6.1,0.316,0.75,9.7,0.275,0.644,0.473,16.247,16.3,0.472,0.513,1.0,0.197,101.52,98.5,82.08,98,0.522,240.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.00,0.00,0,0.000,0.0
10261,41700317,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0,0.000,0.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0,0.000,0.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0,0.000,0.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0,0.000,0.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0,0.000,0.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [49]:
df_away_home_gin = df_away_home_gin.groupby('game_id').sum()
df_away_home_gin.reset_index(inplace=True)
p(df_away_home_gin)

(10266, 51)

,game_id,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000001,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
1,21000002,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
2,21000003,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000004,1610612738,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612739,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0
4,21000005,1610612765,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612751,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0
10261,41700317,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [50]:
#concat 'df_away_ginn' and 'df_home_ginn'
pd.concat([df_away_home_gin, df_away_ginn, df_home_ginn], axis=1)

,game_id,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,game_id,game_date,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home
0,21000001,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,21000002,2010-10-26,Trail Blazers,POR,Portland,240:00,0 days 04:00:00
1,21000002,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,21000001,2010-10-26,Celtics,BOS,Boston,240:00,0 days 04:00:00
2,21000003,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,21000003,2010-10-26,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00
3,21000004,1610612738,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612739,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,21000011,2010-10-27,Bulls,CHI,Chicago,240:00,0 days 04:00:00,21000011,2010-10-27,Thunder,OKC,Oklahoma City,240:00,0 days 04:00:00
4,21000005,1610612765,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612751,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,21000007,2010-10-27,Knicks,NYK,New York,240:00,0 days 04:00:00,21000007,2010-10-27,Raptors,TOR,Toronto,240:00,0 days 04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,41700317,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,41700317,2018-05-28,Rockets,HOU,Houston,240:00,0 days 04:00:00
10262,41700401,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,41700401,2018-05-31,Warriors,GSW,Golden State,265:00,0 days 04:25:00
10263,41700402,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,41700402,2018-06-03,Warriors,GSW,Golden State,240:00,0 days 04:00:00
10264,41700403,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,41700403,2018-06-06,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00
10265,41700404,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,41700404,2018-06-08,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00

In [51]:
#add 'df_away_ginn' and 'df_home_ginn' to 'df_away_home_gin': df_away_home

#sort each dataframe 'df_away_ginn', 'df_home_ginn', and 'df_away_home_gin' by game_id

#check for game_id equal between all three as all True

#concat the three dataframes

#drop extra game_id's and save dataframe: df_away_home

In [52]:
#sort each dataframe 'df_away_ginn', 'df_home_ginn', and 'df_away_home_gin' by game_id

df_away_ginn = df_away_ginn.sort_values('game_id').reset_index(drop=True)
p(df_away_ginn)

(10266, 7)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00
3,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00
4,21000005,2010-10-27,Pistons,DET,Detroit,240:00,0 days 04:00:00
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00

In [53]:
df_home_ginn = df_home_ginn.sort_values('game_id').reset_index(drop=True)
p(df_home_ginn)

(10266, 7)

,game_id,game_date,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home
0,21000001,2010-10-26,Celtics,BOS,Boston,240:00,0 days 04:00:00
1,21000002,2010-10-26,Trail Blazers,POR,Portland,240:00,0 days 04:00:00
2,21000003,2010-10-26,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00
3,21000004,2010-10-27,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00
4,21000005,2010-10-27,Nets,NJN,New Jersey,240:00,0 days 04:00:00
10261,41700317,2018-05-28,Rockets,HOU,Houston,240:00,0 days 04:00:00
10262,41700401,2018-05-31,Warriors,GSW,Golden State,265:00,0 days 04:25:00
10263,41700402,2018-06-03,Warriors,GSW,Golden State,240:00,0 days 04:00:00
10264,41700403,2018-06-06,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00
10265,41700404,2018-06-08,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00

In [54]:
df_away_home_gin = df_away_home_gin.sort_values('game_id').reset_index(drop=True)
p(df_away_home_gin)

(10266, 51)

,game_id,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000001,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
1,21000002,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
2,21000003,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000004,1610612738,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612739,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0
4,21000005,1610612765,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612751,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0
10261,41700317,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [55]:
#check for game_id equal between all three as all True

In [56]:
(df_away_ginn.game_id - df_home_ginn.game_id).value_counts()

0    10266
Name: game_id, dtype: int64

In [57]:
(df_home_ginn.game_id - df_away_home_gin.game_id).value_counts()

0    10266
Name: game_id, dtype: int64

In [58]:
(df_away_ginn.game_id - df_away_home_gin.game_id).value_counts()

0    10266
Name: game_id, dtype: int64

In [59]:
#concat the three dataframes

df_away_home = pd.concat([df_away_ginn, df_home_ginn, df_away_home_gin], axis=1)
p(df_away_home)

(10266, 65)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,game_id,game_date,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,game_id,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,21000001,2010-10-26,Celtics,BOS,Boston,240:00,0 days 04:00:00,21000001,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,21000002,2010-10-26,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,21000002,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,21000003,2010-10-26,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,21000003,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,21000004,2010-10-27,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,21000004,1610612738,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612739,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0
4,21000005,2010-10-27,Pistons,DET,Detroit,240:00,0 days 04:00:00,21000005,2010-10-27,Nets,NJN,New Jersey,240:00,0 days 04:00:00,21000005,1610612765,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612751,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,41700317,2018-05-28,Rockets,HOU,Houston,240:00,0 days 04:00:00,41700317,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,41700401,2018-05-31,Warriors,GSW,Golden State,265:00,0 days 04:25:00,41700401,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,41700402,2018-06-03,Warriors,GSW,Golden State,240:00,0 days 04:00:00,41700402,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,41700403,2018-06-06,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,41700403,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,41700404,2018-06-08,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,41700404,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [60]:
#drop extra game_id's and save dataframe: df_away_home

In [61]:
df_away_home = df_away_home.loc[:,~df_away_home.columns.duplicated()]
p(df_away_home)

(10266, 62)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612738,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612739,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0
4,21000005,2010-10-27,Pistons,DET,Detroit,240:00,0 days 04:00:00,Nets,NJN,New Jersey,240:00,0 days 04:00:00,1610612765,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612751,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

<font color='red'> why are there 3 dropped columns instead of the 2 extra game_id's??? game_date???</font>

In [62]:
df_away_home = df_away_home.sort_values('game_date').reset_index(drop=True)
p(df_away_home)

(10266, 62)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612745,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612744,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0
4,21000014,2010-10-27,Jazz,UTA,Utah,240:00,0 days 04:00:00,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612762,88.1,86.3,107.8,108.9,-19.7,-22.6,0.778,0.95,15.9,0.260,0.740,0.500,22.018,21.6,0.407,0.495,1.0,0.202,100.98,101.50,84.58,102,0.371,240.0,1610612743,107.8,108.9,88.1,86.3,19.7,22.6,0.657,1.44,16.8,0.260,0.740,0.500,15.680,15.8,0.475,0.561,1.0,0.198,100.98,101.50,84.58,101,0.629,240.0
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [63]:
#check for consistency between 'TEAM_NAME_away' and 'team_id_away'

#check for consistency between 'TEAM_NAME_home' and 'team_id_home'

In [64]:
#check for consistency between 'TEAM_NAME_away' and 'team_id_away'

In [65]:
df_away_home[['TEAM_NAME_away', 'TEAM_ID_away']].value_counts()

TEAM_NAME_away  TEAM_ID_away
Spurs           1610612759      371
Heat            1610612748      370
Warriors        1610612744      368
Thunder         1610612760      367
Cavaliers       1610612739      362
Celtics         1610612738      359
Pacers          1610612754      356
Grizzlies       1610612763      352
Hawks           1610612737      352
Rockets         1610612745      349
Bulls           1610612741      348
Clippers        1610612746      348
Raptors         1610612761      344
Trail Blazers   1610612757      342
Mavericks       1610612742      342
Wizards         1610612764      341
76ers           1610612755      335
Jazz            1610612762      334
Nets            1610612751      333
Lakers          1610612747      333
Bucks           1610612749      332
Knicks          1610612752      331
Nuggets         1610612743      330
Magic           1610612753      326
Timberwolves    1610612750      323
Pistons         1610612765      322
Kings           1610612758      320
Suns            1610612756      320
Pelicans        1610612740      212
Hornets         1610612766      168
Bobcats         1610612766      158
Hornets         1610612740      118
dtype: int64

In [66]:
#check for consistency between 'TEAM_NAME_home' and 'team_id_home'

df_away_home[['TEAM_NAME_home', 'TEAM_ID_home']].value_counts()

TEAM_NAME_home  TEAM_ID_home
Heat            1610612748      376
Warriors        1610612744      374
Spurs           1610612759      371
Thunder         1610612760      369
Celtics         1610612738      362
Cavaliers       1610612739      359
Pacers          1610612754      355
Rockets         1610612745      353
Grizzlies       1610612763      351
Hawks           1610612737      351
Bulls           1610612741      349
Clippers        1610612746      349
Raptors         1610612761      347
Mavericks       1610612742      340
Wizards         1610612764      339
Trail Blazers   1610612757      339
Lakers          1610612747      333
76ers           1610612755      333
Jazz            1610612762      332
Nets            1610612751      332
Bucks           1610612749      331
Knicks          1610612752      330
Nuggets         1610612743      328
Magic           1610612753      325
Pistons         1610612765      322
Timberwolves    1610612750      322
Kings           1610612758      320
Suns            1610612756      320
Pelicans        1610612740      211
Hornets         1610612766      167
Bobcats         1610612766      158
Hornets         1610612740      118
dtype: int64

In [67]:
#get matchups
#concat abbreviations, e.g. GSWMIA and check and change/reverse non-alphabetic orderings
#add vs. in between, e.g. GSW vs. MIA

p(df_away_home)

(10266, 62)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612745,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612744,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0
4,21000014,2010-10-27,Jazz,UTA,Utah,240:00,0 days 04:00:00,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612762,88.1,86.3,107.8,108.9,-19.7,-22.6,0.778,0.95,15.9,0.260,0.740,0.500,22.018,21.6,0.407,0.495,1.0,0.202,100.98,101.50,84.58,102,0.371,240.0,1610612743,107.8,108.9,88.1,86.3,19.7,22.6,0.657,1.44,16.8,0.260,0.740,0.500,15.680,15.8,0.475,0.561,1.0,0.198,100.98,101.50,84.58,101,0.629,240.0
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [68]:
df_away_home['matchup'] = df_away_home['TEAM_ABBREVIATION_away'] + df_away_home['TEAM_ABBREVIATION_home']
p(df_away_home.matchup)

(10266,)

0        MIABOS
1        PHXPOR
2        HOULAL
3        HOUGSW
4        UTADEN
10261    GSWHOU
10262    CLEGSW
10263    CLEGSW
10264    GSWCLE
10265    GSWCLE
Name: matchup, dtype: object

In [69]:
abbreviations_list = list(set(df_away_home.matchup))
abbreviations_list[0:10]

['PORBOS',
 'NYKSAS',
 'INDLAL',
 'LALORL',
 'MILUTA',
 'MEMDET',
 'TORATL',
 'SASHOU',
 'LALMIN',
 'ATLNYK']

In [70]:
len(abbreviations_list)

986

In [71]:
#build dictionary where if team first > team second, then add to dictinary the concatenated string (as the key)
# mapped to the reverse concatenated key

In [72]:
reverse_abbreviation_dict = {}
for i in abbreviations_list:
    if (i[0:3] > i[3:6]):
        reverse_abbreviation_dict[i[0:3] + i[3:6]] = i[3:6] + i[0:3]
    else:
        print()

In [73]:
reverse_abbreviation_dict

{'PORBOS': 'BOSPOR',
 'MEMDET': 'DETMEM',
 'TORATL': 'ATLTOR',
 'SASHOU': 'HOUSAS',
 'HOUATL': 'ATLHOU',
 'LALDEN': 'DENLAL',
 'PHIGSW': 'GSWPHI',
 'TORMIN': 'MINTOR',
 'SACOKC': 'OKCSAC',
 'ORLCHI': 'CHIORL',
 'PORNOP': 'NOPPOR',
 'PHIHOU': 'HOUPHI',
 'NOPMIA': 'MIANOP',
 'PHICHI': 'CHIPHI',
 'PHXCLE': 'CLEPHX',
 'UTAATL': 'ATLUTA',
 'NYKMIN': 'MINNYK',
 'MEMLAC': 'LACMEM',
 'WASUTA': 'UTAWAS',
 'PORBKN': 'BKNPOR',
 'SACNYK': 'NYKSAC',
 'CHIATL': 'ATLCHI',
 'ORLDAL': 'DALORL',
 'UTAOKC': 'OKCUTA',
 'MILDET': 'DETMIL',
 'WASNYK': 'NYKWAS',
 'MILMIA': 'MIAMIL',
 'ORLMIA': 'MIAORL',
 'ORLGSW': 'GSWORL',
 'NOPHOU': 'HOUNOP',
 'NYKCHA': 'CHANYK',
 'NYKGSW': 'GSWNYK',
 'SASMIL': 'MILSAS',
 'INDDET': 'DETIND',
 'PORGSW': 'GSWPOR',
 'GSWDET': 'DETGSW',
 'INDHOU': 'HOUIND',
 'WASPHX': 'PHXWAS',
 'WASPHI': 'PHIWAS',
 'WASGSW': 'GSWWAS',
 'NOPMIN': 'MINNOP',
 'PORNOH': 'NOHPOR',
 'PHXLAL': 'LALPHX',
 'UTACHI': 'CHIUTA',
 'LALCLE': 'CLELAL',
 'CHABKN': 'BKNCHA',
 'PHXBKN': 'BKNPHX',
 'MEMBKN': 'BKNMEM',
 'SASNOH': 'NOHSAS',
 'DENBOS': 'BOSDEN',
 'MEMBOS': 'BOSMEM',
 'ORLNJN': 'NJNORL',
 'PHXHOU': 'HOUPHX',
 'UTAMIL': 'MILUTA',
 'MININD': 'INDMIN',
 'SASORL': 'ORLSAS',
 'TORMIA': 'MIATOR',
 'ORLCLE': 'CLEORL',
 'MINMEM': 'MEMMIN',
 'OKCBKN': 'BKNOKC',
 'SACNOH': 'NOHSAC',
 'MINBOS': 'BOSMIN',
 'BOSATL': 'ATLBOS',
 'UTANOP': 'NOPUTA',
 'PHXORL': 'ORLPHX',
 'LALHOU': 'HOULAL',
 'MEMDEN': 'DENMEM',
 'CLEBKN': 'BKNCLE',
 'SASGSW': 'GSWSAS',
 'MIAMEM': 'MEMMIA',
 'DETBOS': 'BOSDET',
 'PHXOKC': 'OKCPHX',
 'ORLIND': 'INDORL',
 'ORLBOS': 'BOSORL',
 'SASATL': 'ATLSAS',
 'NOHIND': 'INDNOH',
 'SASMIN': 'MINSAS',
 'HOUBKN': 'BKNHOU',
 'PHIORL': 'ORLPHI',
 'NJNDAL': 'DALNJN',
 'ORLMIN': 'MINORL',
 'PHINYK': 'NYKPHI',
 'TORMIL': 'MILTOR',
 'MINHOU': 'HOUMIN',
 'OKCIND': 'INDOKC',
 'UTACHA': 'CHAUTA',
 'SASSAC': 'SACSAS',
 'OKCATL': 'ATLOKC',
 'WASCLE': 'CLEWAS',
 'NOPGSW': 'GSWNOP',
 'UTAIND': 'INDUTA',
 'MINBKN': 'BKNMIN',
 'DENBKN': 'BKNDEN',
 'SASPHI': 'PHISAS',
 'TORIND': 'INDTOR',
 'DETATL': 'ATLDET',
 'ORLHOU': 'HOUORL',
 'WASIND': 'INDWAS',
 'UTAPOR': 'PORUTA',
 'LALLAC': 'LACLAL',
 'SASDEN': 'DENSAS',
 'MILCHA': 'CHAMIL',
 'NJNCLE': 'CLENJN',
 'MILBKN': 'BKNMIL',
 'SACNJN': 'NJNSAC',
 'LACATL': 'ATLLAC',
 'TORPOR': 'PORTOR',
 'INDCLE': 'CLEIND',
 'MINATL': 'ATLMIN',
 'MILCLE': 'CLEMIL',
 'UTADAL': 'DALUTA',
 'PHINOH': 'NOHPHI',
 'LALGSW': 'GSWLAL',
 'UTAORL': 'ORLUTA',
 'MIACHA': 'CHAMIA',
 'PHXNOP': 'NOPPHX',
 'ORLBKN': 'BKNORL',
 'SASBOS': 'BOSSAS',
 'TORBKN': 'BKNTOR',
 'NOPMIL': 'MILNOP',
 'PHIBOS': 'BOSPHI',
 'INDDAL': 'DALIND',
 'NJNCHI': 'CHINJN',
 'MIAATL': 'ATLMIA',
 'DETDAL': 'DALDET',
 'SACDAL': 'DALSAC',
 'OKCMIA': 'MIAOKC',
 'MIABKN': 'BKNMIA',
 'NOHMEM': 'MEMNOH',
 'PHXPHI': 'PHIPHX',
 'TORPHI': 'PHITOR',
 'CHAATL': 'ATLCHA',
 'NYKLAL': 'LALNYK',
 'SACGSW': 'GSWSAC',
 'MEMLAL': 'LALMEM',
 'OKCMEM': 'MEMOKC',
 'WASLAC': 'LACWAS',
 'SACLAC': 'LACSAC',
 'NJNHOU': 'HOUNJN',
 'UTASAS': 'SASUTA',
 'HOUCLE': 'CLEHOU',
 'NYKCHI': 'CHINYK',
 'TORDAL': 'DALTOR',
 'GSWBKN': 'BKNGSW',
 'NOHHOU': 'HOUNOH',
 'MILLAL': 'LALMIL',
 'ORLDEN': 'DENORL',
 'LALCHA': 'CHALAL',
 'MILIND': 'INDMIL',
 'LACIND': 'INDLAC',
 'NYKDAL': 'DALNYK',
 'WASOKC': 'OKCWAS',
 'SACIND': 'INDSAC',
 'TORCHI': 'CHITOR',
 'OKCDAL': 'DALOKC',
 'WASNOP': 'NOPWAS',
 'NYKNJN': 'NJNNYK',
 'OKCCHA': 'CHAOKC',
 'TORNYK': 'NYKTOR',
 'OKCCLE': 'CLEOKC',
 'UTACLE': 'CLEUTA',
 'NJNDEN': 'DENNJN',
 'MIALAL': 'LALMIA',
 'PORCHI': 'CHIPOR',
 'OKCMIN': 'MINOKC',
 'PHXMIA': 'MIAPHX',
 'SACMEM': 'MEMSAC',
 'PHIDEN': 'DENPHI',
 'NYKBOS': 'BOSNYK',
 'MINCLE': 'CLEMIN',
 'PHXDET': 'DETPHX',
 'CLECHA': 'CHACLE',
 'PORMIN': 'MINPOR',
 'SACBOS': 'BOSSAC',
 'PORNJN': 'NJNPOR',
 'TORBOS': 'BOSTOR',
 'UTANOH': 'NOHUTA',
 'SASMIA': 'MIASAS',
 'PHXNJN': 'NJNPHX',
 'SASLAC': 'LACSAS',
 'NOPMEM': 'MEMNOP',
 'MILBOS': 'BOSMIL',
 'MINCHI': 'CHIMIN',
 'MEMATL': 'ATLMEM',
 'SACHOU': 'HOUSAC',
 'SACMIN': 'MINSAC',
 'OKCNYK': 'NYKOKC',
 'PHIMIL': 'MILPHI',
 'WASDET': 'DETWAS',
 'ORLLAC': 'LACORL',
 'TORDET': 'DETTOR',
 'INDBKN': 'BKNIND',
 'DALCHA': 'CHADAL',
 'UTATOR': 'TORUTA',
 'NJNIND': 'INDNJN',
 'OKCNJN': 'NJNOKC',
 'PORPHX': 'PHXPOR',
 'OKCNOP': 'NOPOKC',
 'DALBOS': 'BOSDAL',
 'SASPHX': 'PHXSAS',
 'NJNDET': 'DETNJN',
 'PORORL': 'ORLPOR',
 'GSWCLE': 'CLEGSW',
 'PORLAC': 'LACPOR',
 'PHILAC': 'LACPHI',
 'NOHCHA': 'CHANOH',
 'SASNYK': 'NYKSAS',
 'MILGSW': 'GSWMIL',
 'MEMGSW': 'GSWMEM',
 'LACDET': 'DETLAC',
 'NOHATL': 'ATLNOH',
 'PHXNOH': 'NOHPHX',
 'OKCGSW': 'GSWOKC',
 'OKCCHI': 'CHIOKC',
 'PORDEN': 'DENPOR',
 'NJNCHA': 'CHANJN',
 'INDCHI': 'CHIIND',
 'NYKNOP': 'NOPNYK',
 'MEMCLE': 'CLEMEM',
 'SACDEN': 'DENSAC',
 'NYKMIA': 'MIANYK',
 'NOHCHI': 'CHINOH',
 'LACDEN': 'DENLAC',
 'PHXGSW': 'GSWPHX',
 'MIACHI': 'CHIMIA',
 'SACLAL': 'LALSAC',
 'WASDAL': 'DALWAS',
 'NYKBKN': 'BKNNYK',
 'LACDAL': 'DALLAC',
 'LACBKN': 'BKNLAC',
 'WASTOR': 'TORWAS',
 'NJNLAC': 'LACNJN',
 'PHIDET': 'DETPHI',
 'SASPOR': 'PORSAS',
 'UTAMIN': 'MINUTA',
 'WASPOR': 'PORWAS',
 'MILATL': 'ATLMIL',
 'ORLMIL': 'MILORL',
 'PHXATL': 'ATLPHX',
 'PHXBOS': 'BOSPHX',
 'NJNMIL': 'MILNJN',
 'GSWCHI': 'CHIGSW',
 'PHIMIA': 'MIAPHI',
 'DENCLE': 'CLEDEN',
 'PORCHA': 'CHAPOR',
 'HOUDAL': 'DALHOU',
 'CHICHA': 'CHACHI',
 'NJNATL': 'ATLNJN',
 'INDDEN': 'DENIND',
 'SASOKC': 'OKCSAS',
 'NYKMEM': 'MEMNYK',
 'LACGSW': 'GSWLAC',
 'TORMEM': 'MEMTOR',
 'SACORL': 'ORLSAC',
 'TORSAC': 'SACTOR',
 'MINDEN': 'DENMIN',
 'MIABOS': 'BOSMIA',
 'PHIBKN': 'BKNPHI',
 'NOHDEN': 'DENNOH',
 'PORMIA': 'MIAPOR',
 'PORMEM': 'MEMPOR',
 'SASDAL': 'DALSAS',
 'POROKC': 'OKCPOR',
 'MIADAL': 'DALMIA',
 'MIAIND': 'INDMIA',
 'PHILAL': 'LALPHI',
 'LALBKN': 'BKNLAL',
 'SACMIA': 'MIASAC',
 'NJNMIN': 'MINNJN',
 'NJNMIA': 'MIANJN',
 'HOUGSW': 'GSWHOU',
 'SASLAL': 'LALSAS',
 'UTAHOU': 'HOUUTA',
 'ORLNYK': 'NYKORL',
 'MINDAL': 'DALMIN',
 'PHIIND': 'INDPHI',
 'INDGSW': 'GSWIND',
 'LALDET': 'DETLAL',
 'DALCHI': 'CHIDAL',
 'DETCHA': 'CHADET',
 'LALBOS': 'BOSLAL',
 'WASNOH': 'NOHWAS',
 'OKCLAL': 'LALOKC',
 'ORLDET': 'DETORL',
 'UTALAL': 'LALUTA',
 'TORNOP': 'NOPTOR',
 'WASMIN': 'MINWAS',
 'LALDAL': 'DALLAL',
 'PHIATL': 'ATLPHI',
 'WASMIL': 'MILWAS',
 'PHICLE': 'CLEPHI',
 'NOPDAL': 'DALNOP',
 'TOROKC': 'OKCTOR',
 'BKNATL': 'ATLBKN',
 'NOHMIA': 'MIANOH',
 'PHXCHA': 'CHAPHX',
 'HOUCHI': 'CHIHOU',
 'PHINOP': 'NOPPHI',
 'PORPHI': 'PHIPOR',
 'NOHMIL': 'MILNOH',
 'UTADEN': 'DENUTA',
 'MIAHOU': 'HOUMIA',
 'MEMDAL': 'DALMEM',
 'SASIND': 'INDSAS',
 'UTAPHX': 'PHXUTA',
 'SACDET': 'DETSAC',
 'NYKATL': 'ATLNYK',
 'MEMHOU': 'HOUMEM',
 'PORDET': 'DETPOR',
 'CLEBOS': 'BOSCLE',
 'CHABOS': 'BOSCHA',
 'NOPIND': 'INDNOP',
 'NYKDEN': 'DENNYK',
 'NOPLAL': 'LALNOP',
 'MIACLE': 'CLEMIA',
 'PHIMIN': 'MINPHI',
 'WASMEM': 'MEMWAS',
 'WASBKN': 'BKNWAS',
 'NOPLAC': 'LACNOP',
 'CHIBOS': 'BOSCHI',
 'WASNJN': 'NJNWAS',
 'MILMEM': 'MEMMIL',
 'BOSBKN': 'BKNBOS',
 'DETBKN': 'BKNDET',
 'SACCLE': 'CLESAC',
 'PHICHA': 'CHAPHI',
 'NOHNJN': 'NJNNOH',
 'CLECHI': 'CHICLE',
 'GSWDAL': 'DALGSW',
 'TORDEN': 'DENTOR',
 'SASNJN': 'NJNSAS',
 'SASNOP': 'NOPSAS',
 'MEMIND': 'INDMEM',
 'TORGSW': 'GSWTOR',
 'DENDAL': 'DALDEN',
 'WASATL': 'ATLWAS',
 'LALATL': 'ATLLAL',
 'OKCLAC': 'LACOKC',
 'MIAGSW': 'GSWMIA',
 'WASSAS': 'SASWAS',
 'MEMCHA': 'CHAMEM',
 'SACMIL': 'MILSAC',
 'UTABKN': 'BKNUTA',
 'UTANJN': 'NJNUTA',
 'WASHOU': 'HOUWAS',
 'DALBKN': 'BKNDAL',
 'CHIBKN': 'BKNCHI',
 'WASCHA': 'CHAWAS',
 'NOHMIN': 'MINNOH',
 'MILHOU': 'HOUMIL',
 'NYKDET': 'DETNYK',
 'PHXIND': 'INDPHX',
 'UTAGSW': 'GSWUTA',
 'OKCHOU': 'HOUOKC',
 'PHXMEM': 'MEMPHX',
 'NOHDET': 'DETNOH',
 'SASDET': 'DETSAS',
 'NJNBOS': 'BOSNJN',
 'PORNYK': 'NYKPOR',
 'NOPDET': 'DETNOP',
 'GSWCHA': 'CHAGSW',
 'PORATL': 'ATLPOR',
 'LALIND': 'INDLAL',
 'PORIND': 'INDPOR',
 'SASCHA': 'CHASAS',
 'ORLNOP': 'NOPORL',
 'MINGSW': 'GSWMIN',
 'PHXDEN': 'DENPHX',
 'NOPCHA': 'CHANOP',
 'WASCHI': 'CHIWAS',
 'NOHBOS': 'BOSNOH',
 'TORPHX': 'PHXTOR',
 'NYKMIL': 'MILNYK',
 'WASBOS': 'BOSWAS',
 'PHXCHI': 'CHIPHX',
 'HOUDET': 'DETHOU',
 'ORLOKC': 'OKCORL',
 'ORLNOH': 'NOHORL',
 'TORNOH': 'NOHTOR',
 'TORORL': 'ORLTOR',
 'MIADET': 'DETMIA',
 'NOPCLE': 'CLENOP',
 'NJNMEM': 'MEMNJN',
 'LACCHA': 'CHALAC',
 'INDCHA': 'CHAIND',
 'NOPATL': 'ATLNOP',
 'OKCDET': 'DETOKC',
 'PORHOU': 'HOUPOR',
 'NYKLAC': 'LACNYK',
 'MIADEN': 'DENMIA',
 'SASCHI': 'CHISAS',
 'LACCLE': 'CLELAC',
 'MINMIL': 'MILMIN',
 'DETCHI': 'CHIDET',
 'TORCHA': 'CHATOR',
 'PHIMEM': 'MEMPHI',
 'DETDEN': 'DENDET',
 'UTAMIA': 'MIAUTA',
 'ORLATL': 'ATLORL',
 'NYKCLE': 'CLENYK',
 'NOPDEN': 'DENNOP',
 'UTANYK': 'NYKUTA',
 'SACPHX': 'PHXSAC',
 'NOPCHI': 'CHINOP',
 'NYKIND': 'INDNYK',
 'LACCHI': 'CHILAC',
 'INDATL': 'ATLIND',
 'PHIOKC': 'OKCPHI',
 'UTAMEM': 'MEMUTA',
 'PORCLE': 'CLEPOR',
 'ORLCHA': 'CHAORL',
 'DALCLE': 'CLEDAL',
 'TORSAS': 'SASTOR',
 'SASMEM': 'MEMSAS',
 'TORLAC': 'LACTOR',
 'PHXMIN': 'MINPHX',
 'TORLAL': 'LALTOR',
 'PHINJN': 'NJNPHI',
 'SACBKN': 'BKNSAC',
 'MILCHI': 'CHIMIL',
 'NOHDAL': 'DALNOH',
 'OKCMIL': 'MILOKC',
 'HOUCHA': 'CHAHOU',
 'NOPBKN': 'BKNNOP',
 'NJNGSW': 'GSWNJN',
 'PHXNYK': 'NYKPHX',
 'TORCLE': 'CLETOR',
 'HOUDEN': 'DENHOU',
 'SACCHI': 'CHISAC',
 'INDBOS': 'BOSIND',
 'UTASAC': 'SACUTA',
 'DENCHA': 'CHADEN',
 'OKCDEN': 'DENOKC',
 'WASSAC': 'SACWAS',
 'UTABOS': 'BOSUTA',
 'MINLAL': 'LALMIN',
 'ORLMEM': 'MEMORL',
 'WASMIA': 'MIAWAS',
 'NOHCLE': 'CLENOH',
 'PHIDAL': 'DALPHI',
 'GSWATL': 'ATLGSW',
 'LALCHI': 'CHILAL',
 'MINDET': 'DETMIN',
 'PORMIL': 'MILPOR',
 'DALATL': 'ATLDAL',
 'PORDAL': 'DALPOR',
 'PORLAL': 'LALPOR',
 'WASORL': 'ORLWAS',
 'MINCHA': 'CHAMIN',
 'CLEATL': 'ATLCLE',
 'PHXLAC': 'LACPHX',
 'MEMCHI': 'CHIMEM',
 'DENCHI': 'CHIDEN',
 'GSWBOS': 'BOSGSW',
 'NJNLAL': 'LALNJN',
 'MILDAL': 'DALMIL',
 'NOHLAL': 'LALNOH',
 'PHXDAL': 'DALPHX',
 'LACHOU': 'HOULAC',
 'NOPBOS': 'BOSNOP',
 'SACNOP': 'NOPSAC',
 'SACPOR': 'PORSAC',
 'NOHGSW': 'GSWNOH',
 'NYKNOH': 'NOHNYK',
 'ORLLAL': 'LALORL',
 'MILDEN': 'DENMIL',
 'MIALAC': 'LACMIA',
 'DENATL': 'ATLDEN',
 'SACPHI': 'PHISAC',
 'WASLAL': 'LALWAS',
 'MINMIA': 'MIAMIN',
 'GSWDEN': 'DENGSW',
 'MINLAC': 'LACMIN',
 'TORNJN': 'NJNTOR',
 'OKCNOH': 'NOHOKC',
 'UTADET': 'DETUTA',
 'PHXMIL': 'MILPHX',
 'SACATL': 'ATLSAC',
 'SASCLE': 'CLESAS',
 'MILLAC': 'LACMIL',
 'SACCHA': 'CHASAC',
 'LACBOS': 'BOSLAC',
 'WASDEN': 'DENWAS',
 'UTALAC': 'LACUTA',
 'DETCLE': 'CLEDET',
 'NOHLAC': 'LACNOH',
 'HOUBOS': 'BOSHOU',
 'NYKHOU': 'HOUNYK',
 'OKCBOS': 'BOSOKC',
 'UTAPHI': 'PHIUTA',
 'SASBKN': 'BKNSAS',
 'TORHOU': 'HOUTOR',
 'NOHBKN': 'BKNNOH'}

In [74]:
df_away_home.matchup.replace(reverse_abbreviation_dict, inplace=True)

In [75]:
abbreviations_list_alphabetical = list(set(df_away_home.matchup))
abbreviations_list_alphabetical[0:10]

['NYKSAS',
 'INDLAL',
 'MILUTA',
 'LALMIN',
 'INDOKC',
 'ATLNYK',
 'BKNHOU',
 'DENLAC',
 'NOPPHX',
 'ATLDAL']

In [76]:
abbreviations_alphabetical_dict = {}
for i in abbreviations_list_alphabetical:
    abbreviations_alphabetical_dict[i] = i[0:3] + ' vs. ' + i[3:6]

In [77]:
abbreviations_alphabetical_dict

{'NYKSAS': 'NYK vs. SAS',
 'INDLAL': 'IND vs. LAL',
 'MILUTA': 'MIL vs. UTA',
 'LALMIN': 'LAL vs. MIN',
 'INDOKC': 'IND vs. OKC',
 'ATLNYK': 'ATL vs. NYK',
 'BKNHOU': 'BKN vs. HOU',
 'DENLAC': 'DEN vs. LAC',
 'NOPPHX': 'NOP vs. PHX',
 'ATLDAL': 'ATL vs. DAL',
 'SASTOR': 'SAS vs. TOR',
 'PHISAS': 'PHI vs. SAS',
 'NOPORL': 'NOP vs. ORL',
 'DALWAS': 'DAL vs. WAS',
 'OKCUTA': 'OKC vs. UTA',
 'HOUPOR': 'HOU vs. POR',
 'CLEHOU': 'CLE vs. HOU',
 'MILNJN': 'MIL vs. NJN',
 'MEMMIA': 'MEM vs. MIA',
 'CHAOKC': 'CHA vs. OKC',
 'CHIUTA': 'CHI vs. UTA',
 'HOULAC': 'HOU vs. LAC',
 'DENMIA': 'DEN vs. MIA',
 'INDMIN': 'IND vs. MIN',
 'GSWPHX': 'GSW vs. PHX',
 'PHIUTA': 'PHI vs. UTA',
 'GSWNYK': 'GSW vs. NYK',
 'LALUTA': 'LAL vs. UTA',
 'DALNOP': 'DAL vs. NOP',
 'BKNCHI': 'BKN vs. CHI',
 'DETHOU': 'DET vs. HOU',
 'INDORL': 'IND vs. ORL',
 'NYKWAS': 'NYK vs. WAS',
 'BKNNYK': 'BKN vs. NYK',
 'CHANOP': 'CHA vs. NOP',
 'GSWNOP': 'GSW vs. NOP',
 'BOSNOP': 'BOS vs. NOP',
 'ORLSAC': 'ORL vs. SAC',
 'CLELAC': 'CLE vs. LAC',
 'CHIDEN': 'CHI vs. DEN',
 'DALTOR': 'DAL vs. TOR',
 'PORSAS': 'POR vs. SAS',
 'MINORL': 'MIN vs. ORL',
 'DETLAC': 'DET vs. LAC',
 'MEMNOH': 'MEM vs. NOH',
 'BOSHOU': 'BOS vs. HOU',
 'BOSPOR': 'BOS vs. POR',
 'NJNPHX': 'NJN vs. PHX',
 'NOHTOR': 'NOH vs. TOR',
 'CHIIND': 'CHI vs. IND',
 'DALMIA': 'DAL vs. MIA',
 'CHINJN': 'CHI vs. NJN',
 'MILOKC': 'MIL vs. OKC',
 'DETORL': 'DET vs. ORL',
 'LALNYK': 'LAL vs. NYK',
 'BOSOKC': 'BOS vs. OKC',
 'HOULAL': 'HOU vs. LAL',
 'BOSNOH': 'BOS vs. NOH',
 'BKNDAL': 'BKN vs. DAL',
 'MEMNYK': 'MEM vs. NYK',
 'LACNJN': 'LAC vs. NJN',
 'CLEDEN': 'CLE vs. DEN',
 'LACMEM': 'LAC vs. MEM',
 'MINUTA': 'MIN vs. UTA',
 'CHISAC': 'CHI vs. SAC',
 'MIAMIN': 'MIA vs. MIN',
 'DETGSW': 'DET vs. GSW',
 'GSWPOR': 'GSW vs. POR',
 'INDNYK': 'IND vs. NYK',
 'DETPHI': 'DET vs. PHI',
 'DALPHX': 'DAL vs. PHX',
 'NOHSAS': 'NOH vs. SAS',
 'CHASAC': 'CHA vs. SAC',
 'NOPTOR': 'NOP vs. TOR',
 'CHAWAS': 'CHA vs. WAS',
 'BOSDAL': 'BOS vs. DAL',
 'CHADET': 'CHA vs. DET',
 'CHIPHI': 'CHI vs. PHI',
 'BOSNJN': 'BOS vs. NJN',
 'MEMSAC': 'MEM vs. SAC',
 'LACPHI': 'LAC vs. PHI',
 'HOUSAC': 'HOU vs. SAC',
 'BKNMIL': 'BKN vs. MIL',
 'CHINOP': 'CHI vs. NOP',
 'INDSAS': 'IND vs. SAS',
 'MEMORL': 'MEM vs. ORL',
 'DENORL': 'DEN vs. ORL',
 'LALMIL': 'LAL vs. MIL',
 'HOUMEM': 'HOU vs. MEM',
 'LALNOP': 'LAL vs. NOP',
 'CHINYK': 'CHI vs. NYK',
 'BKNCLE': 'BKN vs. CLE',
 'LALNJN': 'LAL vs. NJN',
 'MINOKC': 'MIN vs. OKC',
 'CHILAL': 'CHI vs. LAL',
 'INDPHX': 'IND vs. PHX',
 'PHXPOR': 'PHX vs. POR',
 'PHXWAS': 'PHX vs. WAS',
 'SASUTA': 'SAS vs. UTA',
 'GSWMIA': 'GSW vs. MIA',
 'LALORL': 'LAL vs. ORL',
 'NYKORL': 'NYK vs. ORL',
 'MIAOKC': 'MIA vs. OKC',
 'NOPOKC': 'NOP vs. OKC',
 'SACTOR': 'SAC vs. TOR',
 'ORLTOR': 'ORL vs. TOR',
 'LACWAS': 'LAC vs. WAS',
 'DETMIA': 'DET vs. MIA',
 'DALSAC': 'DAL vs. SAC',
 'MILNYK': 'MIL vs. NYK',
 'MEMPHI': 'MEM vs. PHI',
 'INDMIL': 'IND vs. MIL',
 'HOUWAS': 'HOU vs. WAS',
 'DALGSW': 'DAL vs. GSW',
 'ATLNOP': 'ATL vs. NOP',
 'HOUMIN': 'HOU vs. MIN',
 'MEMUTA': 'MEM vs. UTA',
 'ATLLAL': 'ATL vs. LAL',
 'CHAUTA': 'CHA vs. UTA',
 'ORLPHI': 'ORL vs. PHI',
 'DENPHI': 'DEN vs. PHI',
 'DETMIL': 'DET vs. MIL',
 'ORLUTA': 'ORL vs. UTA',
 'ATLUTA': 'ATL vs. UTA',
 'DENHOU': 'DEN vs. HOU',
 'INDWAS': 'IND vs. WAS',
 'NOPSAC': 'NOP vs. SAC',
 'BKNCHA': 'BKN vs. CHA',
 'GSWMIN': 'GSW vs. MIN',
 'DALLAL': 'DAL vs. LAL',
 'CHAPOR': 'CHA vs. POR',
 'NJNWAS': 'NJN vs. WAS',
 'BOSPHX': 'BOS vs. PHX',
 'BOSTOR': 'BOS vs. TOR',
 'PORSAC': 'POR vs. SAC',
 'BOSCHI': 'BOS vs. CHI',
 'ATLNOH': 'ATL vs. NOH',
 'CHIORL': 'CHI vs. ORL',
 'DALPOR': 'DAL vs. POR',
 'MILTOR': 'MIL vs. TOR',
 'DALMIN': 'DAL vs. MIN',
 'SASWAS': 'SAS vs. WAS',
 'DENSAC': 'DEN vs. SAC',
 'BOSPHI': 'BOS vs. PHI',
 'BOSMIA': 'BOS vs. MIA',
 'MIAUTA': 'MIA vs. UTA',
 'CHIMIA': 'CHI vs. MIA',
 'GSWIND': 'GSW vs. IND',
 'HOUPHI': 'HOU vs. PHI',
 'LACOKC': 'LAC vs. OKC',
 'MEMSAS': 'MEM vs. SAS',
 'MEMOKC': 'MEM vs. OKC',
 'OKCPOR': 'OKC vs. POR',
 'BKNDEN': 'BKN vs. DEN',
 'DETPHX': 'DET vs. PHX',
 'HOUTOR': 'HOU vs. TOR',
 'CLENYK': 'CLE vs. NYK',
 'GSWUTA': 'GSW vs. UTA',
 'HOUNOP': 'HOU vs. NOP',
 'HOUNYK': 'HOU vs. NYK',
 'CLEPHX': 'CLE vs. PHX',
 'CHASAS': 'CHA vs. SAS',
 'NYKOKC': 'NYK vs. OKC',
 'ATLBOS': 'ATL vs. BOS',
 'MILNOH': 'MIL vs. NOH',
 'ATLCHI': 'ATL vs. CHI',
 'ATLTOR': 'ATL vs. TOR',
 'NOHPHI': 'NOH vs. PHI',
 'DETTOR': 'DET vs. TOR',
 'NYKTOR': 'NYK vs. TOR',
 'PHXSAC': 'PHX vs. SAC',
 'BOSMIL': 'BOS vs. MIL',
 'GSWWAS': 'GSW vs. WAS',
 'MIANOH': 'MIA vs. NOH',
 'HOUUTA': 'HOU vs. UTA',
 'BOSNYK': 'BOS vs. NYK',
 'LACMIN': 'LAC vs. MIN',
 'BKNLAL': 'BKN vs. LAL',
 'ATLCLE': 'ATL vs. CLE',
 'SACWAS': 'SAC vs. WAS',
 'CLEDET': 'CLE vs. DET',
 'NOPWAS': 'NOP vs. WAS',
 'INDLAC': 'IND vs. LAC',
 'CHIWAS': 'CHI vs. WAS',
 'MINNJN': 'MIN vs. NJN',
 'TORWAS': 'TOR vs. WAS',
 'DENIND': 'DEN vs. IND',
 'CLESAS': 'CLE vs. SAS',
 'HOUOKC': 'HOU vs. OKC',
 'GSWORL': 'GSW vs. ORL',
 'CHAPHX': 'CHA vs. PHX',
 'ATLNJN': 'ATL vs. NJN',
 'MINNYK': 'MIN vs. NYK',
 'NOHUTA': 'NOH vs. UTA',
 'BOSORL': 'BOS vs. ORL',
 'ORLWAS': 'ORL vs. WAS',
 'CHANJN': 'CHA vs. NJN',
 'HOUORL': 'HOU vs. ORL',
 'MEMMIN': 'MEM vs. MIN',
 'DALMEM': 'DAL vs. MEM',
 'NOHSAC': 'NOH vs. SAC',
 'BOSCHA': 'BOS vs. CHA',
 'LACMIL': 'LAC vs. MIL',
 'BKNNOP': 'BKN vs. NOP',
 'INDNOH': 'IND vs. NOH',
 'CHAGSW': 'CHA vs. GSW',
 'CLESAC': 'CLE vs. SAC',
 'MEMNJN': 'MEM vs. NJN',
 'MINWAS': 'MIN vs. WAS',
 'PHISAC': 'PHI vs. SAC',
 'CHIGSW': 'CHI vs. GSW',
 'NOHPHX': 'NOH vs. PHX',
 'BOSDET': 'BOS vs. DET',
 'CHICLE': 'CHI vs. CLE',
 'BOSMEM': 'BOS vs. MEM',
 'CHADEN': 'CHA vs. DEN',
 'HOUNOH': 'HOU vs. NOH',
 'CHAPHI': 'CHA vs. PHI',
 'DENSAS': 'DEN vs. SAS',
 'CHACLE': 'CHA vs. CLE',
 'ATLMEM': 'ATL vs. MEM',
 'DALUTA': 'DAL vs. UTA',
 'INDMIA': 'IND vs. MIA',
 'NOPSAS': 'NOP vs. SAS',
 'GSWLAC': 'GSW vs. LAC',
 'MILMIN': 'MIL vs. MIN',
 'DALDEN': 'DAL vs. DEN',
 'GSWHOU': 'GSW vs. HOU',
 'LACLAL': 'LAC vs. LAL',
 'NYKPHI': 'NYK vs. PHI',
 'DENMEM': 'DEN vs. MEM',
 'BOSSAC': 'BOS vs. SAC',
 'CHIPHX': 'CHI vs. PHX',
 'CHISAS': 'CHI vs. SAS',
 'NOHNYK': 'NOH vs. NYK',
 'CHITOR': 'CHI vs. TOR',
 'DALOKC': 'DAL vs. OKC',
 'INDPHI': 'IND vs. PHI',
 'CLEDAL': 'CLE vs. DAL',
 'CHALAL': 'CHA vs. LAL',
 'PHIWAS': 'PHI vs. WAS',
 'MINNOP': 'MIN vs. NOP',
 'MILPHX': 'MIL vs. PHX',
 'BKNPOR': 'BKN vs. POR',
 'MIANOP': 'MIA vs. NOP',
 'CHAHOU': 'CHA vs. HOU',
 'BKNORL': 'BKN vs. ORL',
 'NJNSAS': 'NJN vs. SAS',
 'GSWSAS': 'GSW vs. SAS',
 'NJNNOH': 'NJN vs. NOH',
 'BOSGSW': 'BOS vs. GSW',
 'NJNSAC': 'NJN vs. SAC',
 'LACNOH': 'LAC vs. NOH',
 'HOUMIA': 'HOU vs. MIA',
 'BOSCLE': 'BOS vs. CLE',
 'MEMTOR': 'MEM vs. TOR',
 'DETUTA': 'DET vs. UTA',
 'LACSAC': 'LAC vs. SAC',
 'DETSAC': 'DET vs. SAC',
 'TORUTA': 'TOR vs. UTA',
 'OKCTOR': 'OKC vs. TOR',
 'CLEOKC': 'CLE vs. OKC',
 'DALPHI': 'DAL vs. PHI',
 'DENPHX': 'DEN vs. PHX',
 'NYKUTA': 'NYK vs. UTA',
 'MIATOR': 'MIA vs. TOR',
 'ATLSAC': 'ATL vs. SAC',
 'ORLPHX': 'ORL vs. PHX',
 'OKCSAC': 'OKC vs. SAC',
 'BKNDET': 'BKN vs. DET',
 'NOPNYK': 'NOP vs. NYK',
 'LALSAS': 'LAL vs. SAS',
 'LALTOR': 'LAL vs. TOR',
 'CHIDET': 'CHI vs. DET',
 'CLETOR': 'CLE vs. TOR',
 'MEMPHX': 'MEM vs. PHX',
 'CLEMIL': 'CLE vs. MIL',
 'PORTOR': 'POR vs. TOR',
 'LALSAC': 'LAL vs. SAC',
 'NOHWAS': 'NOH vs. WAS',
 'NOHORL': 'NOH vs. ORL',
 'MILWAS': 'MIL vs. WAS',
 'MINPOR': 'MIN vs. POR',
 'ATLHOU': 'ATL vs. HOU',
 'LALMEM': 'LAL vs. MEM',
 'PHXUTA': 'PHX vs. UTA',
 'BOSIND': 'BOS vs. IND',
 'CHAMIA': 'CHA vs. MIA',
 'INDMEM': 'IND vs. MEM',
 'NYKSAC': 'NYK vs. SAC',
 'CLEPOR': 'CLE vs. POR',
 'NJNTOR': 'NJN vs. TOR',
 'ATLORL': 'ATL vs. ORL',
 'LALPOR': 'LAL vs. POR',
 'BKNMEM': 'BKN vs. MEM',
 'LACNYK': 'LAC vs. NYK',
 'MINPHI': 'MIN vs. PHI',
 'CLEGSW': 'CLE vs. GSW',
 'PORWAS': 'POR vs. WAS',
 'NJNOKC': 'NJN vs. OKC',
 'SACSAS': 'SAC vs. SAS',
 'HOUPHX': 'HOU vs. PHX',
 'DETIND': 'DET vs. IND',
 'CLEUTA': 'CLE vs. UTA',
 'CLENOH': 'CLE vs. NOH',
 'CLEMIN': 'CLE vs. MIN',
 'CHACHI': 'CHA vs. CHI',
 'NJNUTA': 'NJN vs. UTA',
 'DENNYK': 'DEN vs. NYK',
 'LACSAS': 'LAC vs. SAS',
 'NJNPOR': 'NJN vs. POR',
 'MIAPHX': 'MIA vs. PHX',
 'INDSAC': 'IND vs. SAC',
 'LALOKC': 'LAL vs. OKC',
 'CHIMIN': 'CHI vs. MIN',
 'ATLPOR': 'ATL vs. POR',
 'NJNORL': 'NJN vs. ORL',
 'MINSAC': 'MIN vs. SAC',
 'CHIDAL': 'CHI vs. DAL',
 'DETWAS': 'DET vs. WAS',
 'GSWSAC': 'GSW vs. SAC',
 'ATLBKN': 'ATL vs. BKN',
 'DENOKC': 'DEN vs. OKC',
 'CHIOKC': 'CHI vs. OKC',
 'MIANJN': 'MIA vs. NJN',
 'BKNNOH': 'BKN vs. NOH',
 'DENUTA': 'DEN vs. UTA',
 'BOSLAL': 'BOS vs. LAL',
 'CLEIND': 'CLE vs. IND',
 'ATLSAS': 'ATL vs. SAS',
 'LACORL': 'LAC vs. ORL',
 'MEMMIL': 'MEM vs. MIL',
 'ATLDEN': 'ATL vs. DEN',
 'DETNYK': 'DET vs. NYK',
 'DENNOP': 'DEN vs. NOP',
 'BOSDEN': 'BOS vs. DEN',
 'MIAWAS': 'MIA vs. WAS',
 'CHILAC': 'CHI vs. LAC',
 'OKCPHI': 'OKC vs. PHI',
 'GSWOKC': 'GSW vs. OKC',
 'DENNOH': 'DEN vs. NOH',
 'INDNJN': 'IND vs. NJN',
 'DENPOR': 'DEN vs. POR',
 'MILSAC': 'MIL vs. SAC',
 'LALWAS': 'LAL vs. WAS',
 'BKNPHX': 'BKN vs. PHX',
 'BOSWAS': 'BOS vs. WAS',
 'CHIMEM': 'CHI vs. MEM',
 'CHIHOU': 'CHI vs. HOU',
 'LACPHX': 'LAC vs. PHX',
 'LALPHI': 'LAL vs. PHI',
 'DENDET': 'DEN vs. DET',
 'GSWMIL': 'GSW vs. MIL',
 'MINNOH': 'MIN vs. NOH',
 'DENGSW': 'DEN vs. GSW',
 'ATLPHI': 'ATL vs. PHI',
 'DALNJN': 'DAL vs. NJN',
 'NOPPHI': 'NOP vs. PHI',
 'MIAORL': 'MIA vs. ORL',
 'CLEWAS': 'CLE vs. WAS',
 'DETOKC': 'DET vs. OKC',
 'DALSAS': 'DAL vs. SAS',
 'CHAIND': 'CHA vs. IND',
 'MEMNOP': 'MEM vs. NOP',
 'OKCPHX': 'OKC vs. PHX',
 'NOPPOR': 'NOP vs. POR',
 'MIAPHI': 'MIA vs. PHI',
 'CHANYK': 'CHA vs. NYK',
 'INDTOR': 'IND vs. TOR',
 'MEMPOR': 'MEM vs. POR',
 'BKNUTA': 'BKN vs. UTA',
 'MILPHI': 'MIL vs. PHI',
 'ATLIND': 'ATL vs. IND',
 'ATLGSW': 'ATL vs. GSW',
 'BOSLAC': 'BOS vs. LAC',
 'MILPOR': 'MIL vs. POR',
 'LALNOH': 'LAL vs. NOH',
 'MIAMIL': 'MIA vs. MIL',
 'CHADAL': 'CHA vs. DAL',
 'DENLAL': 'DEN vs. LAL',
 'MILORL': 'MIL vs. ORL',
 'MEMWAS': 'MEM vs. WAS',
 'UTAWAS': 'UTA vs. WAS',
 'CLEPHI': 'CLE vs. PHI',
 'MILSAS': 'MIL vs. SAS',
 'NJNPHI': 'NJN vs. PHI',
 'NYKPHX': 'NYK vs. PHX',
 'BKNMIN': 'BKN vs. MIN',
 'NOHPOR': 'NOH vs. POR',
 'BKNSAS': 'BKN vs. SAS',
 'PHXTOR': 'PHX vs. TOR',
 'LACPOR': 'LAC vs. POR',
 'PHXSAS': 'PHX vs. SAS',
 'ORLPOR': 'ORL vs. POR',
 'ATLMIN': 'ATL vs. MIN',
 'DALHOU': 'DAL vs. HOU',
 'OKCSAS': 'OKC vs. SAS',
 'DENMIN': 'DEN vs. MIN',
 'GSWMEM': 'GSW vs. MEM',
 'CHAMIN': 'CHA vs. MIN',
 'BKNOKC': 'BKN vs. OKC',
 'OKCWAS': 'OKC vs. WAS',
 'LACTOR': 'LAC vs. TOR',
 'DALMIL': 'DAL vs. MIL',
 'LACMIA': 'LAC vs. MIA',
 'ATLMIA': 'ATL vs. MIA',
 'MILNOP': 'MIL vs. NOP',
 'DETLAL': 'DET vs. LAL',
 'CHIPOR': 'CHI vs. POR',
 'MIANYK': 'MIA vs. NYK',
 'LACUTA': 'LAC vs. UTA',
 'BKNPHI': 'BKN vs. PHI',
 'BKNWAS': 'BKN vs. WAS',
 'BOSUTA': 'BOS vs. UTA',
 'DALNYK': 'DAL vs. NYK',
 'NJNNYK': 'NJN vs. NYK',
 'ATLOKC': 'ATL vs. OKC',
 'GSWNJN': 'GSW vs. NJN',
 'DENTOR': 'DEN vs. TOR',
 'ORLSAS': 'ORL vs. SAS',
 'GSWLAL': 'GSW vs. LAL',
 'GSWPHI': 'GSW vs. PHI',
 'DALLAC': 'DAL vs. LAC',
 'NOPUTA': 'NOP vs. UTA',
 'NOHOKC': 'NOH vs. OKC',
 'DETMIN': 'DET vs. MIN',
 'CLEMEM': 'CLE vs. MEM',
 'MINPHX': 'MIN vs. PHX',
 'CHAORL': 'CHA vs. ORL',
 'ATLPHX': 'ATL vs. PHX',
 'MINSAS': 'MIN vs. SAS',
 'ATLLAC': 'ATL vs. LAC',
 'CLELAL': 'CLE vs. LAL',
 'CLENJN': 'CLE vs. NJN',
 'HOUMIL': 'HOU vs. MIL',
 'BKNMIA': 'BKN vs. MIA',
 'INDPOR': 'IND vs. POR',
 'DALIND': 'DAL vs. IND',
 'MINTOR': 'MIN vs. TOR',
 'ATLWAS': 'ATL vs. WAS',
 'ATLDET': 'ATL vs. DET',
 'BKNBOS': 'BKN vs. BOS',
 'HOUNJN': 'HOU vs. NJN',
 'DALORL': 'DAL vs. ORL',
 'DETNOP': 'DET vs. NOP',
 'BKNTOR': 'BKN vs. TOR',
 'DETNJN': 'DET vs. NJN',
 'GSWNOH': 'GSW vs. NOH',
 'HOUSAS': 'HOU vs. SAS',
 'HOUIND': 'HOU vs. IND',
 'DALDET': 'DAL vs. DET',
 'CLEORL': 'CLE vs. ORL',
 'CHAMIL': 'CHA vs. MIL',
 'PORUTA': 'POR vs. UTA',
 'DENWAS': 'DEN vs. WAS',
 'LACNOP': 'LAC vs. NOP',
 'OKCORL': 'OKC vs. ORL',
 'BKNIND': 'BKN vs. IND',
 'PHITOR': 'PHI vs. TOR',
 'DETSAS': 'DET vs. SAS',
 'CLENOP': 'CLE vs. NOP',
 'BOSSAS': 'BOS vs. SAS',
 'CHIMIL': 'CHI vs. MIL',
 'INDUTA': 'IND vs. UTA',
 'CHAMEM': 'CHA vs. MEM',
 'DETNOH': 'DET vs. NOH',
 'LALMIA': 'LAL vs. MIA',
 'CLEMIA': 'CLE vs. MIA',
 'MIASAC': 'MIA vs. SAC',
 'CHANOH': 'CHA vs. NOH',
 'GSWTOR': 'GSW vs. TOR',
 'BKNSAC': 'BKN vs. SAC',
 'DENNJN': 'DEN vs. NJN',
 'BKNGSW': 'BKN vs. GSW',
 'ATLCHA': 'ATL vs. CHA',
 'NYKPOR': 'NYK vs. POR',
 'DALNOH': 'DAL vs. NOH',
 'MIASAS': 'MIA vs. SAS',
 'CHALAC': 'CHA vs. LAC',
 'CHATOR': 'CHA vs. TOR',
 'BKNLAC': 'BKN vs. LAC',
 'BOSMIN': 'BOS vs. MIN',
 'CHINOH': 'CHI vs. NOH',
 'DETMEM': 'DET vs. MEM',
 'DENMIL': 'DEN vs. MIL',
 'MIAPOR': 'MIA vs. POR',
 'SACUTA': 'SAC vs. UTA',
 'ATLMIL': 'ATL vs. MIL',
 'LALPHX': 'LAL vs. PHX',
 'DETPOR': 'DET vs. POR',
 'INDNOP': 'IND vs. NOP',
 'PHIPOR': 'PHI vs. POR',
 'PHIPHX': 'PHI vs. PHX'}

In [78]:
df_away_home.matchup.replace(abbreviations_alphabetical_dict, inplace=True)

In [79]:
p(df_away_home.matchup)

(10266,)

0        BOS vs. MIA
1        PHX vs. POR
2        HOU vs. LAL
3        GSW vs. HOU
4        DEN vs. UTA
10261    GSW vs. HOU
10262    CLE vs. GSW
10263    CLE vs. GSW
10264    CLE vs. GSW
10265    CLE vs. GSW
Name: matchup, dtype: object

In [80]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '20boxscoreadvancedv2_team_away_home_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_away_home.to_csv(datapath_df, index=False)

In [81]:
rcp('20boxscoreadvancedv2_team_away_home_2010_2018.csv')

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL
3,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612745,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612744,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU
4,21000014,2010-10-27,Jazz,UTA,Utah,240:00,0 days 04:00:00,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612762,88.1,86.3,107.8,108.9,-19.7,-22.6,0.778,0.95,15.9,0.260,0.740,0.500,22.018,21.6,0.407,0.495,1.0,0.202,100.98,101.50,84.58,102,0.371,240.0,1610612743,107.8,108.9,88.1,86.3,19.7,22.6,0.657,1.44,16.8,0.260,0.740,0.500,15.680,15.8,0.475,0.561,1.0,0.198,100.98,101.50,84.58,101,0.629,240.0,DEN vs. UTA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW