In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
#from IPython.core.display import display, HTML
#display(HTML("<style>.container { width:100% !important; }</style>"))

In [3]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [4]:
df = pd.read_csv(os.path.join('..', 'raw_data', 'injuries_2010-2020.csv'), parse_dates=['Date'])
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

In [5]:
#fill nulls with something that makes sense

#df = df[~(df.Acquired.isnull() & df.Relinquished.isnull())]
#df

<font color='red'> </font>

In [6]:
df2 = pd.read_csv(os.path.join('..', 'processed_data', '3game_date_home_away.csv'), parse_dates=['game_date'])
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [7]:
#keep 2005-2006 season dates in case of player out before season starts <<<<<<<<<<<<<<<<<<<<<<<===============<<<<<<<<<<<<<<<==
df = df[(df.Date >= df2.game_date.min()) & (df.Date <= df2.game_date.max())]

In [259]:
print("beginning: " + str(df2.game_date.min()) + ", end: " + str(df2.game_date.max()))

beginning: 2006-10-31 00:00:00, end: 2018-06-08 00:00:00

In [8]:
df.Team.value_counts().shape

(32,)

<font color='red'>  </font>

In [9]:
path = os.path.join('..', 'processed_data', '0team_id_abbreviation_df.csv')
df3 = pd.read_csv(path)
df3

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610612754          IND
18  1610612755          PHI
19  1610612756          PHX
20  1610612757          POR
21  1610612758          SAC
22  1610612759          SAS
23  1610612760          OKC
24  1610612761          TOR
25  1610612762          UTA
26  1610612763          MEM
27  1610612764          WAS
28  1610612765          DET
29  1610612766          CHA

In [10]:
#charlotte
    #bobcats 04-14
    #horrnets 14-present
    #charlotte ---> 06-18

In [11]:
path = os.path.join('..', 'raw_data', 'nba_teams.csv')
df4 = pd.read_csv(path)
df4

,id,full_name,abbreviation,nickname,city,state,year_founded,url
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949,https://content.sportslogos.net/logos/6/220/full/kqhjtzl2ik3gnxsnwsn8yf002.gif
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946,https://content.sportslogos.net/logos/6/213/full/slhg02hbef3j1ov4lsnwyol5o.png
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970,https://cdn.statmuse.com/img/nba/players/old_nba_cavs_1995_2003--dba8iauk.png
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002,NaN
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966,https://cdn.mos.cms.futurecdn.net/8227s5kMEx84YEHWLbxCb4-1200-80.jpg
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980,https://cdn.statmuse.com/img/nba/players/old_nba_dal_1981_2001--1nfqfd2j.png
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976,https://1000logos.net/wp-content/uploads/2018/06/Denver-Rockets-Logo-2008.jpg
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946,https://i.pinimg.com/originals/1d/95/43/1d95432d0a10768054755095f6a4427b.png
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967,https://content.sportslogos.net/logos/6/230/full/vr7yd7ghightk5f9g3jh5ltnc.png
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970,https://content.sportslogos.net/logos/6/236/full/ioxjye9im9phdgfyfxvj1xb71.png
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948,https://images.homedepot-static.com/productImages/ce8be48f-a86e-4b96-a365-d97d33cc02e3/svn/purple-applied-icon-wall-decals-nbop1401-64_600.jpg
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988,https://logovtor.com/wp-content/uploads/2020/06/miami-heat-logo-vector.png
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968,https://pm1.narvii.com/6493/f62ac7896462df0e3771e962787cf8754336d1b7_00.jpg
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989,https://www.nbateamslist.com/wp-content/uploads/2013/04/wolves.jpg
14,1610612751,Brooklyn Nets,NJN,Nets,Brooklyn,New York,1976,https://content.sportslogos.net/logos/6/215/full/2hh70mg3h40yl41tzfpn3gha2.gif
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946,https://images.homedepot-static.com/productImages/46d9d86f-e257-4ac6-8d71-2a3e120c7be7/svn/orange-applied-icon-wall-decals-nbop2003-64_1000.jpg
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989,https://www.michael-weinstein.com/wp-content/uploads/2015/12/orlando_magic_logo-2000-2010.png
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976,https://images.homedepot-static.com/productImages/5a5042bb-b9cd-4786-aaac-accdeea8dde9/svn/fanmats-other-interior-auto-accessories-22217-64_1000.jpg
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949,https://i.pinimg.com/736x/b6/af/a0/b6afa094187bb5ad27cd316ed4addd6c.jpg
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968,https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiCALqbXwR29WVCXIzQdL7SCpk2wP6nf8hOA&usqp=CAU
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970,https://logonoid.com/images/portland-trail-blazers-logo.gif
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948,https://www.nba.com/kings/sites/kings/files/10_-_sacramento.png
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976,https://content.sportslogos.net/logos/6/233/full/e04ylwkfdofkr2ctlerjov26s.png
23,1610612760,Oklahoma City Thunder,SEA,Thunder,Oklahoma City,Oklahoma,1967,https://external-preview.redd.it/qX9powo5lVgvv_WBWX5lbgfJma-CtTsKpn6-Kh1YBuU.jpg?auto=webp&s=412bbf79803684a2cf70be6d424c210bc60eb9f6
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995,https://images8.alphacoders.com/105/1055875.jpg
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974,https://content.sportslogos.net/logos/6/234/full/8316e7nrg5xuouqqo21bjgem9.png
26,1610612763,Memphis Grizzlies,VAN,Grizzlies,Memphis,Tennessee,1995,https://www.pngkit.com/png/detail/200-2000557_memphis-grizzlies-logo.png
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961,https://www.michael-weinstein.com/wp-content/uploads/2011/05/bullets2.jpg
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948,https://content.sportslogos.net/logos/6/223/full/enfhamkfyk1vfvdjuzg67fpeg.gif
29,1610612766,Charlotte Hornets,CHH,Hornets,Charlotte,North Carolina,1988,https://images-na.ssl-images-amazon.com/images/I/41JP%2BcUJ22L._AC_.jpg

In [12]:
set3 = set(df3.abbreviation)
set3

{'ATL',
 'BKN',
 'BOS',
 'CHA',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS'}

In [13]:
set4 = set(df4.abbreviation)
set4

{'ATL',
 'BOS',
 'CHH',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MIA',
 'MIL',
 'MIN',
 'NJN',
 'NOP',
 'NYK',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'SEA',
 'TOR',
 'UTA',
 'VAN',
 'WAS'}

In [14]:
set4 - set3

{'CHH', 'NJN', 'SEA', 'VAN'}

In [15]:
set3 - set4

{'BKN', 'CHA', 'MEM', 'OKC'}

In [16]:
#CHA as CHH
#BKN as NJN
#OKC as SEA
#MEM as VAN

In [17]:
df4[['abbreviation', 'nickname']]

   abbreviation       nickname
0           ATL          Hawks
1           BOS        Celtics
2           CLE      Cavaliers
3           NOP       Pelicans
4           CHI          Bulls
5           DAL      Mavericks
6           DEN        Nuggets
7           GSW       Warriors
8           HOU        Rockets
9           LAC       Clippers
10          LAL         Lakers
11          MIA           Heat
12          MIL          Bucks
13          MIN   Timberwolves
14          NJN           Nets
15          NYK         Knicks
16          ORL          Magic
17          IND         Pacers
18          PHI          76ers
19          PHX           Suns
20          POR  Trail Blazers
21          SAC          Kings
22          SAS          Spurs
23          SEA        Thunder
24          TOR        Raptors
25          UTA           Jazz
26          VAN      Grizzlies
27          WAS        Wizards
28          DET        Pistons
29          CHH        Hornets

In [18]:
df4 = df4[['id','abbreviation', 'nickname']].replace({'CHH':'CHA', 'NJN':'BKN',
                                           'SEA':'OKC', 'VAN':'MEM'})
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [19]:
df.reset_index().drop(columns='index', inplace=True)
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [20]:
df[df.Team.isnull()]

,Date,Team,Acquired,Relinquished,Notes
13007,2015-09-02,NaN,NaN,Glen Davis,surgery on left ankle to repair torn ligaments (out indefinitely)
13009,2015-09-03,NaN,NaN,Landry Fields,surgery on hip to repair torn labrum (out indefinitely)

In [21]:
df.iloc[13009,:]['Team'] = 'LAC'

<ipython-input-21-6330db2052e9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[13009,:]['Team'] = 'LAC'

In [22]:
df[df.Team.isnull()]

,Date,Team,Acquired,Relinquished,Notes
13007,2015-09-02,NaN,NaN,Glen Davis,surgery on left ankle to repair torn ligaments (out indefinitely)
13009,2015-09-03,NaN,NaN,Landry Fields,surgery on hip to repair torn labrum (out indefinitely)

In [23]:
df = df[df.Team.notnull()]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [24]:
df.reset_index(inplace=True)

In [25]:
df.drop(columns='index', inplace=True)
df

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [26]:
set0 = set(df.Team)
set0

{'76ers',
 'Blazers',
 'Bobcats',
 'Bucks',
 'Bullets',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Warriors',
 'Wizards'}

In [27]:
set4 = set(df4.nickname)
set4

{'76ers',
 'Bucks',
 'Bulls',
 'Cavaliers',
 'Celtics',
 'Clippers',
 'Grizzlies',
 'Hawks',
 'Heat',
 'Hornets',
 'Jazz',
 'Kings',
 'Knicks',
 'Lakers',
 'Magic',
 'Mavericks',
 'Nets',
 'Nuggets',
 'Pacers',
 'Pelicans',
 'Pistons',
 'Raptors',
 'Rockets',
 'Spurs',
 'Suns',
 'Thunder',
 'Timberwolves',
 'Trail Blazers',
 'Warriors',
 'Wizards'}

In [28]:
df[df.Team == 'Bullets']

            Date     Team        Acquired Relinquished              Notes
19375 2017-11-05  Bullets  Marion Hillard          NaN  activated from IL

In [29]:
df = df[df.Team != 'Bullets']
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22250,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22251,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22252,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22253,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22254,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [30]:
df = df.reset_index().drop(columns='index')
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [31]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [32]:
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [33]:
df[df.Acquired.notnull() & df.Relinquished.notnull()].Acquired

21687    John Collins
Name: Acquired, dtype: object

In [34]:
df[df.Acquired.notnull() & df.Relinquished.notnull()]

            Date   Team       Acquired   Relinquished               Notes
21687 2018-03-23  Hawks  John Collins   John Collins   returned to lineup

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22254 entries, 0 to 22253
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          22254 non-null  datetime64[ns]
 1   Team          22254 non-null  object
 2   Acquired      7492 non-null   object
 3   Relinquished  14763 non-null  object
 4   Notes         22254 non-null  object
dtypes: datetime64[ns](1), object(4)
memory usage: 869.4+ KB

In [36]:
df.head()

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)

In [37]:
df = df[(~df.Acquired.isnull()) | (~df.Relinquished.isnull())]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [38]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [39]:
df4

            id abbreviation       nickname
0   1610612737          ATL          Hawks
1   1610612738          BOS        Celtics
2   1610612739          CLE      Cavaliers
3   1610612740          NOP       Pelicans
4   1610612741          CHI          Bulls
5   1610612742          DAL      Mavericks
6   1610612743          DEN        Nuggets
7   1610612744          GSW       Warriors
8   1610612745          HOU        Rockets
9   1610612746          LAC       Clippers
10  1610612747          LAL         Lakers
11  1610612748          MIA           Heat
12  1610612749          MIL          Bucks
13  1610612750          MIN   Timberwolves
14  1610612751          BKN           Nets
15  1610612752          NYK         Knicks
16  1610612753          ORL          Magic
17  1610612754          IND         Pacers
18  1610612755          PHI          76ers
19  1610612756          PHX           Suns
20  1610612757          POR  Trail Blazers
21  1610612758          SAC          Kings
22  1610612759          SAS          Spurs
23  1610612760          OKC        Thunder
24  1610612761          TOR        Raptors
25  1610612762          UTA           Jazz
26  1610612763          MEM      Grizzlies
27  1610612764          WAS        Wizards
28  1610612765          DET        Pistons
29  1610612766          CHA        Hornets

In [40]:
set(df.Team) - set(df4.nickname)

{'Blazers', 'Bobcats'}

In [41]:
set(df4.nickname) - set(df.Team)

{'Trail Blazers'}

In [42]:
df4.nickname.replace({'Trail Blazers': 'Blazers'}, inplace=True)

In [43]:
set(df.Team) - set(df4.nickname)

{'Bobcats'}

In [44]:
set(df4.nickname) - set(df.Team)

set()

In [45]:
df4.iloc[29].to_frame().T

            id abbreviation nickname
29  1610612766          CHA  Hornets

In [46]:
bobcats = df4.iloc[29].to_frame().T
bobcats['nickname'][29] = 'Bobcats'
df4 = pd.concat([df4, bobcats])
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
29  1610612766          CHA       Bobcats

In [47]:
df4 = df4.reset_index().drop(columns='index')
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

In [48]:
set(df4.nickname) - set(df.Team)

set()

In [49]:
set(df.Team) - set(df4.nickname)

set()

In [50]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [51]:
df_injuries = pd.merge(df, df4[['id', 'nickname']], left_on=['Team'], right_on=['nickname'], 
                       how='left').drop(columns='nickname')
df_injuries

,Date,Team,Acquired,Relinquished,Notes,id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [52]:
df_injuries.rename(columns={'id':'team_id'})

,Date,Team,Acquired,Relinquished,Notes,team_id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [53]:
df_injuries.Team.value_counts()

Spurs           1070
Nuggets          860
Rockets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Knicks           783
Celtics          783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Name: Team, dtype: int64

In [54]:
df_injuries = df_injuries.rename(columns={'id':'team_id'})
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [55]:
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [56]:
# df_injuries - team_id, player
# df2 - game_id, team_id, home and away stats
# nba_api player ratings/stats

In [57]:
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats

In [58]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [59]:
df[df.Acquired.notnull() & df.Relinquished.notnull()]

            Date   Team       Acquired   Relinquished               Notes
21687 2018-03-23  Hawks  John Collins   John Collins   returned to lineup

In [60]:
df_injuries['AR'] = df_injuries.Acquired + df_injuries.Relinquished

In [61]:
df_injuries.Acquired = df_injuries.Acquired.fillna('')

In [62]:
df_injuries.Relinquished = df_injuries.Relinquished.fillna('')

In [63]:
df_injuries['AR'] = df_injuries.Acquired + df_injuries.Relinquished

In [64]:
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,AR
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala

In [65]:
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,AR
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala

In [66]:
df_injuries['A'] = 0

In [67]:
df_injuries['A'][df_injuries['Acquired'] != ''] = 1

<ipython-input-67-b0b726d48026>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_injuries['A'][df_injuries['Acquired'] != ''] = 1

In [68]:
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,AR,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [69]:
df_injuries = df_injuries.rename(columns={'AR':'player'})
df_injuries

,Date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [70]:
path = os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2010_2018.csv')
df_or1018 = pd.read_csv(path)

In [71]:
df_or1018

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [72]:
df_or1018

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [73]:
path = os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2010.csv')
df_or0910 = pd.read_csv(path)
df_or0910

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1610612738,BOS,Boston,1718,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76,0.189
1,20900001,1610612738,BOS,Boston,708,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66,0.147
2,20900001,1610612738,BOS,Boston,2570,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47,0.030
3,20900001,1610612738,BOS,Boston,951,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80,0.051
4,20900001,1610612738,BOS,Boston,200765,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31476,40900407,1610612747,LAL,Los Angeles,2756,Sasha Vujacic,NaN,NaN,4:41,97.8,100.0,0.0,0.0,97.8,100.0,0.000,0.00,0.0,0.000,0.143,0.067,0.0,0.000,0.347,0.231,0.246,77.95,87.18,72.65,9,0.250
31477,40900407,1610612747,LAL,Los Angeles,200769,Shannon Brown,NaN,NaN,5:25,71.7,63.6,82.0,72.7,-10.2,-9.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.077,0.085,86.49,97.48,81.23,11,-0.444
31478,40900407,1610612747,LAL,Los Angeles,2694,Josh Powell,NaN,NaN,0:34,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,84.46,126.69,105.57,2,0.000
31479,40900407,1610612747,LAL,Los Angeles,2788,DJ Mbenga,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
31480,40900407,1610612747,LAL,Los Angeles,2575,Luke Walton,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

<font color='red'> increase in the number of players in the nba over the 2010s????????</font>

In [74]:
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [75]:
#df2 and df_injuries merge to get, e.g. 2010-11 season injuries
df_games1011 = df2[df2.season == '2010-11']
df_games1011

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
4920,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
4921,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
4922,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
4923,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4924,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14928,41000402,2011-06-02,1610612748,0.765,240,34.0,73.0,0.466,9.0,30.0,0.300,16.0,24.0,1.0,6.0,24.0,30,13.0,15.0,6.0,12.0,17.0,93,2010.0,1610612742,0.765,240,36.0,75.0,0.480,6.0,17.0,0.353,17.0,21.0,1.0,11.0,30.0,41,18.0,8.0,2.0,18.0,20.0,95,Playoffs,2010-11
14929,41000403,2011-06-05,1610612742,0.722,240,28.0,70.0,0.400,8.0,21.0,0.381,22.0,27.0,1.0,12.0,30.0,42,18.0,3.0,8.0,14.0,14.0,86,2010.0,1610612748,0.778,240,34.0,78.0,0.436,8.0,19.0,0.421,12.0,15.0,1.0,9.0,27.0,36,20.0,8.0,5.0,10.0,27.0,88,Playoffs,2010-11
14930,41000404,2011-06-07,1610612742,0.737,240,29.0,73.0,0.397,4.0,19.0,0.211,24.0,30.0,1.0,12.0,29.0,41,13.0,7.0,2.0,11.0,18.0,86,2010.0,1610612748,0.737,240,32.0,75.0,0.427,2.0,14.0,0.143,17.0,24.0,1.0,15.0,29.0,44,19.0,8.0,5.0,13.0,23.0,83,Playoffs,2010-11
14931,41000405,2011-06-09,1610612742,0.750,240,39.0,69.0,0.565,13.0,19.0,0.684,21.0,27.0,1.0,4.0,22.0,26,23.0,8.0,3.0,11.0,20.0,112,2010.0,1610612748,0.700,240,37.0,70.0,0.529,8.0,20.0,0.400,21.0,26.0,1.0,9.0,27.0,36,25.0,5.0,4.0,16.0,26.0,103,Playoffs,2010-11
14932,41000406,2011-06-12,1610612748,0.667,240,34.0,72.0,0.472,7.0,23.0,0.304,20.0,33.0,1.0,9.0,30.0,39,20.0,7.0,3.0,16.0,14.0,95,2010.0,1610612742,0.762,240,41.0,82.0,0.500,11.0,26.0,0.423,12.0,18.0,1.0,10.0,30.0,40,19.0,11.0,1.0,14.0,24.0,105,Playoffs,2010-11

In [76]:
df_injuries.rename(columns={'Date':'game_date'})

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [77]:
#df_games1011[['game_id', 'game_date']]
pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011.game_date, on='game_date', how='right')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0.0
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0.0
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,1610612757,Joel Przybilla,0.0
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,1610612738,Avery Bradley,0.0
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,1610612738,Kendrick Perkins,0.0
...,...,...,...,...,...,...,...,...
23072,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,0.0
23073,2011-06-07,Mavericks,Brendan Haywood,,activated from IL,1610612742,Brendan Haywood,1.0
23074,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,0.0
23075,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1.0
23076,2011-06-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011.game_date, on='game_date', how='left')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
42720,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
42721,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0
42722,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw,1
42723,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love,1
42724,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala,1

In [79]:
df_injuries1011 = pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011[['game_date', 'game_id']], on='game_date', how='inner')
df_injuries1011

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000002
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000003
3,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0,21000001
4,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0,21000002
...,...,...,...,...,...,...,...,...,...
23043,2011-06-05,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000403
23044,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,0,41000404
23045,2011-06-07,Mavericks,Brendan Haywood,,activated from IL,1610612742,Brendan Haywood,1,41000404
23046,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,0,41000405
23047,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405

In [80]:
pd.merge(df_injuries1011, df_or1018.rename(columns={'GAME_ID':'game_id'})[['game_id', 'E_OFF_RATING']], how='left', on='game_id')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id,E_OFF_RATING
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,91.3
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,86.7
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,49.1
3,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,81.9
4,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,73.9
...,...,...,...,...,...,...,...,...,...,...
552292,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,115.3
552293,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,137.7
552294,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552295,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552296,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN

In [81]:
#filtered for games we have offensive rating
df_injuries1011_or = pd.merge(df_injuries1011, df_or1018.rename(columns={'GAME_ID':'game_id'})[['game_id', 'E_OFF_RATING']], how='inner', on='game_id')
df_injuries1011_or

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id,E_OFF_RATING
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,91.3
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,86.7
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,49.1
3,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,81.9
4,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000001,73.9
...,...,...,...,...,...,...,...,...,...,...
552292,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,115.3
552293,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,137.7
552294,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552295,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN
552296,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,1,41000405,NaN

In [82]:
df_injuries1011_or.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 552297 entries, 0 to 552296
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   game_date     552297 non-null  datetime64[ns]
 1   Team          552297 non-null  object
 2   Acquired      552297 non-null  object
 3   Relinquished  552297 non-null  object
 4   Notes         552297 non-null  object
 5   team_id       552297 non-null  object
 6   player        552297 non-null  object
 7   A             552297 non-null  int64
 8   game_id       552297 non-null  int64
 9   E_OFF_RATING  469724 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 46.4+ MB

In [83]:
552297 - 469724

82573

In [84]:
#injury dataset for 2010-2018

#get average offensive rating per play for the 2009-2010 season for edge case: DataFrame w/ 'Player', 'Offensive Rating'

#injury dataset add a column for (average) offensive rating (for this season so far or previous season if data for this
#season if lacking
    #merge injury dataset with offensive rating data by date and player.
    
    #what does offensive rating look like for player not playing due to injury or just not playing?



#offensive rating

In [85]:

#Get game_date range for 2010-11 season by game dataset

#Get game_ids for 2010-11 season

#Get offensive rating per player per game by merge on game_id

#///

#From injuries df, want only player relinquished dates

#//

#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

#——->get player game_id, game_date for that season by merge relinquished players of df_injuries on df_or1011

In [86]:
#Get game_date range for 2010-11 season by game dataset

In [87]:
df2[df2.season == '2010-11']

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
4920,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
4921,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
4922,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
4923,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4924,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14928,41000402,2011-06-02,1610612748,0.765,240,34.0,73.0,0.466,9.0,30.0,0.300,16.0,24.0,1.0,6.0,24.0,30,13.0,15.0,6.0,12.0,17.0,93,2010.0,1610612742,0.765,240,36.0,75.0,0.480,6.0,17.0,0.353,17.0,21.0,1.0,11.0,30.0,41,18.0,8.0,2.0,18.0,20.0,95,Playoffs,2010-11
14929,41000403,2011-06-05,1610612742,0.722,240,28.0,70.0,0.400,8.0,21.0,0.381,22.0,27.0,1.0,12.0,30.0,42,18.0,3.0,8.0,14.0,14.0,86,2010.0,1610612748,0.778,240,34.0,78.0,0.436,8.0,19.0,0.421,12.0,15.0,1.0,9.0,27.0,36,20.0,8.0,5.0,10.0,27.0,88,Playoffs,2010-11
14930,41000404,2011-06-07,1610612742,0.737,240,29.0,73.0,0.397,4.0,19.0,0.211,24.0,30.0,1.0,12.0,29.0,41,13.0,7.0,2.0,11.0,18.0,86,2010.0,1610612748,0.737,240,32.0,75.0,0.427,2.0,14.0,0.143,17.0,24.0,1.0,15.0,29.0,44,19.0,8.0,5.0,13.0,23.0,83,Playoffs,2010-11
14931,41000405,2011-06-09,1610612742,0.750,240,39.0,69.0,0.565,13.0,19.0,0.684,21.0,27.0,1.0,4.0,22.0,26,23.0,8.0,3.0,11.0,20.0,112,2010.0,1610612748,0.700,240,37.0,70.0,0.529,8.0,20.0,0.400,21.0,26.0,1.0,9.0,27.0,36,25.0,5.0,4.0,16.0,26.0,103,Playoffs,2010-11
14932,41000406,2011-06-12,1610612748,0.667,240,34.0,72.0,0.472,7.0,23.0,0.304,20.0,33.0,1.0,9.0,30.0,39,20.0,7.0,3.0,16.0,14.0,95,2010.0,1610612742,0.762,240,41.0,82.0,0.500,11.0,26.0,0.423,12.0,18.0,1.0,10.0,30.0,40,19.0,11.0,1.0,14.0,24.0,105,Playoffs,2010-11

In [88]:
startdate_1011 = df2[df2.season == '2010-11'].game_date.min() 
startdate_1011

Timestamp('2010-10-26 00:00:00')

In [89]:
enddate_1011 = df2[df2.season == '2010-11'].game_date.max()
enddate_1011

Timestamp('2011-06-12 00:00:00')

In [90]:
#Get game_ids for 2010-11 season
game_ids_1011 = df2[df2.season == '2010-11'].game_id
game_ids_1011

4920     21000001
4921     21000002
4922     21000003
4923     21000004
4924     21000005
           ...
14928    41000402
14929    41000403
14930    41000404
14931    41000405
14932    41000406
Name: game_id, Length: 1311, dtype: int64

In [91]:
#Get offensive rating per player per game by merge on game_id

In [92]:
#pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')
pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')[['game_id', 'TEAM_ID',
                                                                                        'PLAYER_NAME', 'E_OFF_RATING']]

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [93]:
df_or1011 = pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')[['game_id', 'TEAM_ID','PLAYER_NAME',
                                                                                        'E_OFF_RATING']]
df_or1011

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [94]:
#From injuries df, want only player relinquished dates
df_inj = df_injuries[df_injuries.Relinquished.notnull() & (df_injuries.Relinquished != '')]
df_inj

,Date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin,0
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George,0
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala,0
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0

In [95]:
#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

In [96]:
#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

In [97]:
df_or1011

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [98]:
df2[df2.season == '2010-11'][['game_id', 'game_date']]

        game_id  game_date
4920   21000001 2010-10-26
4921   21000002 2010-10-26
4922   21000003 2010-10-26
4923   21000004 2010-10-27
4924   21000005 2010-10-27
...         ...        ...
14928  41000402 2011-06-02
14929  41000403 2011-06-05
14930  41000404 2011-06-07
14931  41000405 2011-06-09
14932  41000406 2011-06-12

[1311 rows x 2 columns]

In [99]:
pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner')

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1.610613e+09   LeBron James          91.3 2010-10-26
1      21000001  1.610613e+09     Chris Bosh          86.7 2010-10-26
2      21000001  1.610613e+09   Joel Anthony          49.1 2010-10-26
3      21000001  1.610613e+09    Dwyane Wade          81.9 2010-10-26
4      21000001  1.610613e+09  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1.610613e+09   Juwan Howard          85.0 2011-06-12
31415  41000406  1.610613e+09    Eddie House          99.2 2011-06-12
31416  41000406  1.610613e+09     Mike Bibby           NaN 2011-06-12
31417  41000406  1.610613e+09  Erick Dampier           NaN 2011-06-12
31418  41000406  1.610613e+09    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

<font color='red'>this dataframe include player never injuried also??? -yes</font>

In [100]:
df_or1011a = pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner')
df_or1011a

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1.610613e+09   LeBron James          91.3 2010-10-26
1      21000001  1.610613e+09     Chris Bosh          86.7 2010-10-26
2      21000001  1.610613e+09   Joel Anthony          49.1 2010-10-26
3      21000001  1.610613e+09    Dwyane Wade          81.9 2010-10-26
4      21000001  1.610613e+09  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1.610613e+09   Juwan Howard          85.0 2011-06-12
31415  41000406  1.610613e+09    Eddie House          99.2 2011-06-12
31416  41000406  1.610613e+09     Mike Bibby           NaN 2011-06-12
31417  41000406  1.610613e+09  Erick Dampier           NaN 2011-06-12
31418  41000406  1.610613e+09    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

In [101]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  float64
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 1.4+ MB

In [102]:
df_or1011a.TEAM_ID = df_or1011a.TEAM_ID.astype(str)
df_or1011a

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1610612748.0   LeBron James          91.3 2010-10-26
1      21000001  1610612748.0     Chris Bosh          86.7 2010-10-26
2      21000001  1610612748.0   Joel Anthony          49.1 2010-10-26
3      21000001  1610612748.0    Dwyane Wade          81.9 2010-10-26
4      21000001  1610612748.0  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1610612748.0   Juwan Howard          85.0 2011-06-12
31415  41000406  1610612748.0    Eddie House          99.2 2011-06-12
31416  41000406  1610612748.0     Mike Bibby           NaN 2011-06-12
31417  41000406  1610612748.0  Erick Dampier           NaN 2011-06-12
31418  41000406  1610612748.0    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

In [103]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  object
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 1.4+ MB

In [104]:
df_or1011a['cma1'] = df_or1011a.E_OFF_RATING.expanding(min_periods=1).mean()
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451

In [105]:
df_or1011a['cma2'] = df_or1011a.groupby('PLAYER_NAME')['E_OFF_RATING'].transform(lambda x: x.expanding(min_periods=1).mean())
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000,73.900000
...,...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451,108.415054

In [106]:
df_or1011a[df_or1011a.PLAYER_NAME == 'LeBron James']

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000,91.300000
120,21000006,1610612748.0,LeBron James,97.9,2010-10-27,97.423000,94.600000
588,21000025,1610612748.0,LeBron James,109.5,2010-10-29,98.944595,99.566667
936,21000040,1610612748.0,LeBron James,115.5,2010-10-31,98.244417,103.550000
1188,21000050,1610612748.0,LeBron James,135.6,2010-11-02,98.431947,109.960000
1776,21000075,1610612748.0,LeBron James,97.9,2010-11-05,99.656023,107.950000
1956,21000082,1610612748.0,LeBron James,109.3,2010-11-06,99.492496,108.142857
2460,21000103,1610612748.0,LeBron James,112.9,2010-11-09,99.999164,108.737500
2819,21000118,1610612748.0,LeBron James,116.5,2010-11-11,100.054251,109.600000
3179,21000133,1610612748.0,LeBron James,118.7,2010-11-13,100.456531,110.510000
3779,21000158,1610612748.0,LeBron James,132.4,2010-11-17,100.808953,112.500000
4187,21000175,1610612748.0,LeBron James,103.1,2010-11-19,100.528282,111.716667
4415,21000185,1610612748.0,LeBron James,109.9,2010-11-20,100.655033,111.576923
4690,21000196,1610612748.0,LeBron James,83.5,2010-11-22,100.741624,109.571429
5086,21000213,1610612748.0,LeBron James,98.5,2010-11-24,100.608179,108.833333
5410,21000226,1610612748.0,LeBron James,107.6,2010-11-26,100.812274,108.756250
5710,21000239,1610612748.0,LeBron James,97.4,2010-11-27,100.963869,108.088235
5985,21000250,1610612748.0,LeBron James,110.5,2010-11-29,101.140108,108.222222
6346,21000265,1610612748.0,LeBron James,109.8,2010-12-01,101.204079,108.305263
6526,21000273,1610612748.0,LeBron James,136.2,2010-12-02,101.254411,109.700000
6898,21000288,1610612748.0,LeBron James,102.4,2010-12-04,101.220636,109.352381
7318,21000306,1610612748.0,LeBron James,103.9,2010-12-06,101.326615,109.104545
7750,21000324,1610612748.0,LeBron James,118.6,2010-12-08,101.318427,109.517391
8134,21000340,1610612748.0,LeBron James,128.2,2010-12-10,101.331410,110.295833
8326,21000348,1610612748.0,LeBron James,112.2,2010-12-11,101.296403,110.372000
8506,21000355,1610612748.0,LeBron James,114.3,2010-12-13,101.232012,110.523077
8890,21000371,1610612748.0,LeBron James,102.4,2010-12-15,101.230628,110.222222
9143,21000382,1610612748.0,LeBron James,121.2,2010-12-17,101.305925,110.614286
9406,21000393,1610612748.0,LeBron James,101.7,2010-12-18,101.180762,110.306897
9825,21000410,1610612748.0,LeBron James,92.7,2010-12-20,101.157191,109.720000
10340,21000432,1610612748.0,LeBron James,101.1,2010-12-23,101.206552,109.441935
10412,21000435,1610612748.0,LeBron James,109.8,2010-12-25,101.143344,109.453125
10952,21000457,1610612748.0,LeBron James,122.6,2010-12-28,100.997697,109.851515
11228,21000469,1610612748.0,LeBron James,126.3,2010-12-29,100.947278,110.335294
11648,21000486,1610612748.0,LeBron James,117.4,2011-01-01,100.904211,110.537143
11948,21000499,1610612748.0,LeBron James,119.5,2011-01-03,100.797021,110.786111
12104,21000505,1610612748.0,LeBron James,112.2,2011-01-04,100.804437,110.824324
12736,21000532,1610612748.0,LeBron James,91.2,2011-01-07,100.995800,110.307895
13138,21000549,1610612748.0,LeBron James,112.6,2011-01-09,101.037891,110.366667
13686,21000572,1610612748.0,LeBron James,111.4,2011-01-12,101.183273,110.392500
13769,21000575,1610612748.0,LeBron James,NaN,2011-01-13,101.239732,110.392500
14631,21000611,1610612748.0,LeBron James,94.8,2011-01-18,101.372566,110.012195
15399,21000643,1610612748.0,LeBron James,125.8,2011-01-22,101.373155,110.388095
16227,21000678,1610612748.0,LeBron James,101.6,2011-01-27,101.495515,110.183721
16431,21000686,1610612748.0,LeBron James,104.9,2011-01-28,101.512691,110.063636
16779,21000701,1610612748.0,LeBron James,115.2,2011-01-30,101.475827,110.177778
17007,21000710,1610612748.0,LeBron James,119.8,2011-01-31,101.524787,110.386957
17477,21000730,1610612748.0,LeBron James,114.9,2011-02-03,101.586616,110.482979
17549,21000733,1610612748.0,LeBron James,114.4,2011-02-04,101.603101,110.564583
18063,21000754,1610612748.0,LeBron James,105.2,2011-02-06,101.688236,110.455102
18421,21000769,1610612748.0,LeBron James,126.3,2011-02-08,101.763839,110.772000
18959,21000792,1610612748.0,LeBron James,119.0,2011-02-11,101.826023,110.933333
19247,21000804,1610612748.0,LeBron James,90.7,2011-02-13,101.810369,110.544231
19581,21000818,1610612748.0,LeBron James,107.2,2011-02-15,101.808042,110.481132
19749,21000825,1610612748.0,LeBron James,112.0,2011-02-16,101.795509,110.509259
20145,21000841,1610612748.0,LeBron James,120.1,2011-02-22,101.860216,110.683636
20564,21000859,1610612748.0,LeBron James,100.0,2011-02-24,101.914983,110.492857
20743,21000866,1610612748.0,LeBron James,112.4,2011-02-25,101.894412,110.526316
21244,21000887,1610612748.0,LeBron James,88.0,2011-02-27,101.908537,110.137931
21843,21000912,1610612748.0,LeBron James,108.7,2011-03-03,101.928584,110.113559
22095,21000923,1610612748.0,LeBron James,104.9,2011-03-04,101.996614,110.026667
22298,21000931,1610612748.0,LeBron James,99.7,2011-03-06,101.983445,109.857377
22776,21000951,1610612748.0,LeBron James,112.2,2011-03-08,101.973516,109.895161
23088,21000964,1610612748.0,LeBron James,107.3,2011-03-10,102.024994,109.853968
23374,21000976,1610612748.0,LeBron James,114.7,2011-03-12,102.077608,109.929687
23780,21000993,1610612748.0,LeBron James,115.3,2011-03-14,102.071467,110.012308
24092,21001006,1610612748.0,LeBron James,96.8,2011-03-16,102.098252,109.812121
24416,21001020,1610612748.0,LeBron James,128.5,2011-03-18,102.064198,110.091045
24668,21001030,1610612748.0,LeBron James,119.0,2011-03-19,102.042092,110.222059
25327,21001058,1610612748.0,LeBron James,113.1,2011-03-23,102.043279,110.263768
25675,21001072,1610612748.0,LeBron James,118.5,2011-03-25,102.105035,110.381429
26082,21001089,1610612748.0,LeBron James,129.1,2011-03-27,102.101063,110.645070
26357,21001101,1610612748.0,LeBron James,94.5,2011-03-29,102.112362,110.420833
26573,21001110,1610612748.0,LeBron James,133.1,2011-03-30,102.135588,110.731507
26957,21001126,1610612748.0,LeBron James,116.5,2011-04-01,102.147503,110.809459
27340,21001142,1610612748.0,LeBron James,116.2,2011-04-03,102.111436,110.881333
27880,21001164,1610612748.0,LeBron James,88.0,2011-04-06,102.148018,110.580263
28312,21001182,1610612748.0,LeBron James,116.8,2011-04-08,102.193953,110.661039
28599,21001194,1610612748.0,LeBron James,115.4,2011-04-10,102.211460,110.721795
28779,21001202,1610612748.0,LeBron James,111.9,2011-04-11,102.248782,110.736709
29246,21001221,1610612748.0,LeBron James,NaN,2011-04-13,102.263070,110.736709
29607,41000111,1610612748.0,LeBron James,105.1,2011-04-16,102.257935,110.666250
29631,41000112,1610612748.0,LeBron James,114.5,2011-04-18,102.249905,110.713580
29643,41000113,1610612748.0,LeBron James,121.8,2011-04-21,102.247621,110.848780
29667,41000114,1610612748.0,LeBron James,93.4,2011-04-24,102.252438,110.638554
29703,41000115,1610612748.0,LeBron James,118.5,2011-04-27,102.245391,110.732143
30663,41000211,1610612748.0,LeBron James,102.2,2011-05-01,102.189662,110.631765
30687,41000212,1610612748.0,LeBron James,115.7,2011-05-03,102.190995,110.690698
30699,41000213,1610612748.0,LeBron James,91.3,2011-05-07,102.192915,110.467816
30724,41000214,1610612748.0,LeBron James,98.5,2011-05-09,102.190047,110.331818
30759,41000215,1610612748.0,LeBron James,107.2,2011-05-11,102.188708,110.296629
31035,41000301,1610612748.0,LeBron James,101.8,2011-05-15,102.207806,110.202222
31059,41000302,1610612748.0,LeBron James,100.3,2011-05-18,102.205013,110.093407
31095,41000303,1610612748.0,LeBron James,110.3,2011-05-22,102.196011,110.095652
31119,41000304,1610612748.0,LeBron James,101.1,2011-05-24,102.189671,109.998925
31131,41000305,1610612748.0,LeBron James,95.9,2011-05-26,102.189271,109.848936
31287,41000401,1610612748.0,LeBron James,107.8,2011-05-31,102.203251,109.827368
31311,41000402,1610612748.0,LeBron James,111.0,2011-06-02,102.198329,109.839583
31323,41000403,1610612748.0,LeBron James,101.7,2011-06-05,102.198412,109.755670
31347,41000404,1610612748.0,LeBron James,95.6,2011-06-07,102.192674,109.611224
31371,41000405,1610612748.0,LeBron James,111.1,2011-06-09,102.193409,109.626263
31407,41000406,1610612748.0,LeBron James,93.2,2011-06-12,102.210059,109.462000

In [107]:
(91.3 + 97.9)/2

94.6

In [108]:
df_or1011a[df_or1011a.cma2 != df_or1011a.cma1]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1,cma2
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000,73.900000
5,21000001,1610612748.0,James Jones,86.5,2010-10-26,78.233333,86.500000
...,...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451,108.415054

In [109]:
df_or1011a.drop(columns='cma1', inplace=True)
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,73.900000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,108.415054

In [110]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  object
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
 5   cma2          31259 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 1.7+ MB

In [111]:
df_inj.rename(columns={'Date':'game_date'})

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin,0
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George,0
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala,0
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0

In [112]:
df_or1011a.rename(columns={'PLAYER_NAME':'player'})

,game_id,TEAM_ID,player,E_OFF_RATING,game_date,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,73.900000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,108.415054

In [113]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_date', 'player'], how='left')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id,TEAM_ID,E_OFF_RATING,cma2
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0,NaN,NaN,NaN,NaN
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0,NaN,NaN,NaN,NaN
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0,NaN,NaN,NaN,NaN
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0,NaN,NaN,NaN,NaN
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
14758,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin,0,NaN,NaN,NaN,NaN
14759,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George,0,NaN,NaN,NaN,NaN
14760,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala,0,NaN,NaN,NaN,NaN
14761,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0,NaN,NaN,NaN,NaN
14762,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0,NaN,NaN,NaN,NaN

In [114]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_date', 'player'], how='left').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14763 entries, 0 to 14762
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     14763 non-null  datetime64[ns]
 1   Team          14763 non-null  object
 2   Acquired      14763 non-null  object
 3   Relinquished  14763 non-null  object
 4   Notes         14763 non-null  object
 5   team_id       14763 non-null  object
 6   player        14763 non-null  object
 7   A             14763 non-null  int64
 8   game_id       628 non-null    float64
 9   TEAM_ID       628 non-null    object
 10  E_OFF_RATING  24 non-null     float64
 11  cma2          624 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 1.5+ MB

In [115]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_date', 'player'], how='inner')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id,TEAM_ID,E_OFF_RATING,cma2
0,2010-10-26,Heat,,Mario Chalmers,sprained ankle (out indefinitely),1610612748,Mario Chalmers,0,21000001,1610612748.0,NaN,NaN
1,2010-10-27,Bucks,,Jon Brockman,sprained left ankle (DNP),1610612749,Jon Brockman,0,21000010,1610612749.0,NaN,NaN
2,2010-10-27,Bucks,,Luc Mbah a Moute,sprained right ankle (DNP),1610612749,Luc Mbah a Moute,0,21000010,1610612749.0,NaN,NaN
3,2010-10-29,Pistons,,Will Bynum,sore right hamstring (DNP),1610612765,Will Bynum,0,21000024,1610612765.0,NaN,100.400000
4,2010-10-30,Pistons,,Will Bynum,sore right hamstring (DNP),1610612765,Will Bynum,0,21000035,1610612765.0,NaN,100.400000
5,2010-11-02,Pistons,,Richard Hamilton,sore right foot (DNP),1610612765,Richard Hamilton,0,21000049,1610612765.0,NaN,87.500000
6,2010-11-02,Pistons,,Will Bynum,sore right hamstring (DNP),1610612765,Will Bynum,0,21000049,1610612765.0,NaN,100.400000
7,2010-11-03,Hawks,,Jamal Crawford,turf toe (DNP),1610612737,Jamal Crawford,0,21000054,1610612737.0,NaN,109.625000
8,2010-11-03,Jazz,,Jeremy Evans,sprained right wrist (DNP),1610612762,Jeremy Evans,0,21000061,1610612762.0,NaN,106.650000
9,2010-11-03,Jazz,,Kyrylo Fesenko,stomach illness (DNP),1610612762,Kyrylo Fesenko,0,21000061,1610612762.0,NaN,99.900000
10,2010-11-03,Pistons,,Richard Hamilton,sore right foot (DNP),1610612765,Richard Hamilton,0,21000054,1610612765.0,NaN,87.500000
11,2010-11-03,Pistons,,Will Bynum,sore right hamstring (DNP),1610612765,Will Bynum,0,21000054,1610612765.0,NaN,100.400000
12,2010-11-03,Warriors,,Brandan Wright,stomach virus (DTD),1610612744,Brandan Wright,0,21000063,1610612744.0,NaN,102.766667
13,2010-11-05,Bucks,,Andrew Bogut,migraine headache (DNP),1610612749,Andrew Bogut,0,21000068,1610612749.0,NaN,97.440000
14,2010-11-05,Hawks,,Marvin Williams,bone bruise in right knee (DNP),1610612737,Marvin Williams,0,21000074,1610612737.0,NaN,110.460000
15,2010-11-05,Jazz,,Jeremy Evans,sprained right ankle (DNP),1610612762,Jeremy Evans,0,21000078,1610612762.0,NaN,106.650000
16,2010-11-06,Blazers,,Rudy Fernandez,back injury (DNP),1610612757,Rudy Fernandez,0,21000087,1610612757.0,NaN,93.740000
17,2010-11-07,Hawks,,Marvin Williams,bone bruise in right knee (DNP),1610612737,Marvin Williams,0,21000090,1610612737.0,NaN,110.460000
18,2010-11-08,Hawks,,Marvin Williams,bone bruise in right knee (DNP),1610612737,Marvin Williams,0,21000096,1610612737.0,NaN,110.460000
19,2010-11-08,Magic,,Mickael Pietrus,DNP,1610612753,Mickael Pietrus,0,21000096,1610612753.0,NaN,90.440000
20,2010-11-09,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000104,1610612749.0,NaN,89.842857
21,2010-11-10,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000108,1610612749.0,NaN,89.842857
22,2010-11-10,Clippers,,Chris Kaman,sprained left ankle (DNP),1610612746,Chris Kaman,0,21000116,1610612746.0,NaN,89.925000
23,2010-11-10,Hawks,,Marvin Williams,bone bruise in right knee (DNP),1610612737,Marvin Williams,0,21000108,1610612737.0,NaN,110.460000
24,2010-11-10,Timberwolves,,Wayne Ellington,thigh injury (DTD),1610612750,Wayne Ellington,0,21000117,1610612750.0,NaN,83.857143
25,2010-11-10,Wizards,,Kevin Seraphin,placed on IL,1610612764,Kevin Seraphin,0,21000111,1610612764.0,NaN,NaN
26,2010-11-11,Celtics,,Jermaine O'Neal,sore left knee (DNP),1610612738,Jermaine O'Neal,0,21000118,1610612738.0,NaN,94.971429
27,2010-11-12,Clippers,,Randy Foye,strained left hamstring (DNP),1610612746,Randy Foye,0,21000129,1610612746.0,NaN,96.000000
28,2010-11-13,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000137,1610612749.0,NaN,89.842857
29,2010-11-13,Celtics,,Jermaine O'Neal,sore left knee (DNP),1610612738,Jermaine O'Neal,0,21000135,1610612738.0,NaN,94.971429
30,2010-11-13,Raptors,,Reggie Evans,flu-like symptoms (DNP),1610612761,Reggie Evans,0,21000133,1610612761.0,NaN,96.155556
31,2010-11-14,Rockets,,Chase Budinger,sprained left ankle (DNP),1610612745,Chase Budinger,0,21000142,1610612745.0,NaN,104.712500
32,2010-11-14,Timberwolves,,Nikola Pekovic,sprained left ankle (DNP),1610612750,Nikola Pekovic,0,21000139,1610612750.0,NaN,103.070000
33,2010-11-14,Timberwolves,,Wayne Ellington,bruised left thigh (DNP),1610612750,Wayne Ellington,0,21000139,1610612750.0,NaN,83.857143
34,2010-11-15,Clippers,,Randy Foye,strained left hamstring (DNP),1610612746,Randy Foye,0,21000150,1610612746.0,NaN,96.000000
35,2010-11-15,Jazz,,Raja Bell,strained left abductor (DNP),1610612762,Raja Bell,0,21000148,1610612762.0,NaN,99.310000
36,2010-11-15,Timberwolves,,Nikola Pekovic,left foot injury (DNP),1610612750,Nikola Pekovic,0,21000144,1610612750.0,NaN,103.070000
37,2010-11-15,Timberwolves,,Wayne Ellington,bruised left thigh (DNP),1610612750,Wayne Ellington,0,21000144,1610612750.0,NaN,83.857143
38,2010-11-16,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000154,1610612757.0,NaN,108.063636
39,2010-11-16,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000155,1610612749.0,NaN,89.842857
40,2010-11-17,Clippers,,Randy Foye,strained left hamstring (DNP),1610612746,Randy Foye,0,21000162,1610612746.0,NaN,96.000000
41,2010-11-17,Jazz,,Kyrylo Fesenko,dizziness (DNP),1610612762,Kyrylo Fesenko,0,21000165,1610612762.0,NaN,114.188889
42,2010-11-17,Rockets,,Chase Budinger,sprained left ankle (DNP),1610612745,Chase Budinger,0,21000164,1610612745.0,NaN,104.712500
43,2010-11-18,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000170,1610612757.0,NaN,108.063636
44,2010-11-18,Magic,,Jason Williams,foot injury (DTD),1610612753,Jason Williams,0,21000169,1610612753.0,NaN,102.380000
45,2010-11-19,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000172,1610612749.0,NaN,89.842857
46,2010-11-19,Heat,,Juwan Howard,broken nose (DNP),1610612748,Juwan Howard,0,21000175,1610612748.0,NaN,109.533333
47,2010-11-19,Knicks,,Timofey Mozgov,left calf injury (DNP),1610612752,Timofey Mozgov,0,21000181,1610612752.0,NaN,104.566667
48,2010-11-19,Warriors,,Brandan Wright,strained lower back (DNP),1610612744,Brandan Wright,0,21000181,1610612744.0,NaN,90.175000
49,2010-11-20,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000189,1610612757.0,NaN,108.063636
50,2010-11-20,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000186,1610612749.0,NaN,89.842857
51,2010-11-20,Suns,,Steve Nash,strained groin (DNP),1610612756,Steve Nash,0,21000182,1610612756.0,NaN,111.945455
52,2010-11-22,Warriors,,Brandan Wright,strained lower back (DNP),1610612744,Brandan Wright,0,21000201,1610612744.0,NaN,90.175000
53,2010-11-24,Bucks,,Andrew Bogut,sore back (DNP),1610612749,Andrew Bogut,0,21000210,1610612749.0,NaN,98.208333
54,2010-11-24,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000210,1610612749.0,NaN,89.842857
55,2010-11-24,Bulls,,Taj Gibson,right ankle/foot injury (DNP),1610612741,Taj Gibson,0,21000218,1610612741.0,NaN,103.300000
56,2010-11-24,Celtics,,Delonte West,broken right wrist (out indefinitely),1610612738,Delonte West,0,21000212,1610612738.0,66.7,89.300000
57,2010-11-24,Warriors,,Brandan Wright,strained lower back (DNP),1610612744,Brandan Wright,0,21000217,1610612744.0,NaN,90.175000
58,2010-11-26,Bucks,,Andrew Bogut,sore back (DNP),1610612749,Andrew Bogut,0,21000225,1610612749.0,NaN,98.208333
59,2010-11-26,Bucks,,Carlos Delfino,strained neck (DNP),1610612749,Carlos Delfino,0,21000225,1610612749.0,NaN,89.842857
60,2010-11-26,Raptors,,Reggie Evans,broken right foot (out indefinitely),1610612761,Reggie Evans,0,21000224,1610612761.0,82.8,95.280000
61,2010-11-26,Warriors,,Brandan Wright,strained lower back (DNP),1610612744,Brandan Wright,0,21000232,1610612744.0,NaN,90.175000
62,2010-11-27,Bucks,,Andrew Bogut,sore back (DNP),1610612749,Andrew Bogut,0,21000240,1610612749.0,NaN,98.208333
63,2010-11-27,Bucks,,Corey Maggette,sore left ankle (DNP),1610612749,Corey Maggette,0,21000240,1610612749.0,NaN,95.660000
64,2010-11-27,Bucks,,Drew Gooden,plantar fasciitis in left foot (DNP),1610612749,Drew Gooden,0,21000240,1610612749.0,NaN,92.273333
65,2010-11-28,Blazers,,Sean Marks,sprained right ankle (DNP),1610612757,Sean Marks,0,21000246,1610612757.0,NaN,106.742857
66,2010-11-28,Clippers,,Randy Foye,strained left hamstring (DNP),1610612746,Randy Foye,0,21000245,1610612746.0,NaN,106.671429
67,2010-11-28,Knicks,,Toney Douglas,bruised right quadriceps (DNP),1610612752,Toney Douglas,0,21000243,1610612752.0,NaN,105.211111
68,2010-11-28,Lakers,,Devin Ebanks,gastroenteritis (DNP),1610612747,Devin Ebanks,0,21000249,1610612747.0,NaN,84.000000
69,2010-11-28,Raptors,,Peja Stojakovic,swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000242,1610612761.0,NaN,105.662500
70,2010-11-29,Bucks,,Andrew Bogut,sore back (DNP),1610612749,Andrew Bogut,0,21000253,1610612749.0,NaN,98.208333
71,2010-11-29,Bucks,,Corey Maggette,illness (DNP),1610612749,Corey Maggette,0,21000253,1610612749.0,NaN,95.660000
72,2010-11-29,Bucks,,Drew Gooden,left foot injury (DNP),1610612749,Drew Gooden,0,21000253,1610612749.0,NaN,92.273333
73,2010-12-01,Bucks,,Andrew Bogut,sore back (DNP),1610612749,Andrew Bogut,0,21000270,1610612749.0,NaN,98.208333
74,2010-12-01,Raptors,,Peja Stojakovic,swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000263,1610612761.0,NaN,105.662500
75,2010-12-03,Hornets,,David West,stomach virus (DNP),1610612766,David West,0,21000282,1610612740.0,NaN,108.161111
76,2010-12-03,Magic,,Dwight Howard,stomach virus (DNP),1610612753,Dwight Howard,0,21000279,1610612753.0,NaN,108.494737
77,2010-12-03,Magic,,Jameer Nelson,stomach virus (DNP),1610612753,Jameer Nelson,0,21000279,1610612753.0,NaN,110.862500
78,2010-12-03,Raptors,,Peja Stojakovic,swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000276,1610612761.0,NaN,105.662500
79,2010-12-04,Magic,,Dwight Howard,stomach virus (DNP),1610612753,Dwight Howard,0,21000292,1610612753.0,NaN,108.494737
80,2010-12-04,Magic,,Jameer Nelson,stomach virus (DNP),1610612753,Jameer Nelson,0,21000292,1610612753.0,NaN,110.862500
81,2010-12-04,Magic,,Ryan Anderson,sprained right foot (DNP),1610612753,Ryan Anderson,0,21000292,1610612753.0,NaN,93.272727
82,2010-12-04,Timberwolves,,Michael Beasley,sprained right ankle (DNP),1610612750,Michael Beasley,0,21000291,1610612750.0,NaN,101.661111
83,2010-12-05,Celtics,,Rajon Rondo,strained hamstring (DNP),1610612738,Rajon Rondo,0,21000294,1610612738.0,NaN,111.106250
84,2010-12-05,Raptors,,Peja Stojakovic,sore/swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000295,1610612761.0,NaN,105.662500
85,2010-12-05,Warriors,,Rodney Carney,sprained left foot (DTD),1610612744,Rodney Carney,0,21000297,1610612744.0,NaN,94.494737
86,2010-12-06,Magic,,Jameer Nelson,stomach flu (DNP),1610612753,Jameer Nelson,0,21000303,1610612753.0,NaN,110.862500
87,2010-12-06,Bucks,,Drew Gooden,patella tendinitis in left foot (DNP),1610612749,Drew Gooden,0,21000306,1610612749.0,NaN,91.518750
88,2010-12-08,Jazz,,Kyrylo Fesenko,sprained left ankle (DNP),1610612762,Kyrylo Fesenko,0,21000324,1610612762.0,NaN,102.833333
89,2010-12-08,Nuggets,,Carmelo Anthony,right knee inflammation (DNP),1610612743,Carmelo Anthony,0,21000316,1610612743.0,NaN,105.928571
90,2010-12-08,Raptors,,Peja Stojakovic,swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000318,1610612761.0,NaN,105.662500
91,2010-12-08,Timberwolves,,Darko Milicic,bruised right quadriceps (DNP),1610612750,Darko Milicic,0,21000320,1610612750.0,NaN,99.780952
92,2010-12-09,Celtics,,Shaquille O'Neal,sore right calf (P) / sore left knee (CBC) (DNP),1610612738,Shaquille O'Neal,0,21000327,1610612738.0,NaN,118.206250
93,2010-12-10,Jazz,,Raja Bell,groin injury (DTD),1610612762,Raja Bell,0,21000339,1610612762.0,NaN,102.536364
94,2010-12-11,Bulls,,Kurt Thomas,placed on IL,1610612741,Kurt Thomas,0,21000345,1610612741.0,116.3,57.780000
95,2010-12-11,Cavaliers,,Ryan Hollins,stomach virus (DTD),1610612739,Ryan Hollins,0,21000347,1610612739.0,NaN,100.822727
96,2010-12-11,Hawks,,Zaza Pachulia,placed on IL with illness,1610612737,Zaza Pachulia,0,21000342,1610612737.0,107.8,102.370833
97,2010-12-11,Jazz,,Kyrylo Fesenko,sprained left ankle (DNP),1610612762,Kyrylo Fesenko,0,21000346,1610612762.0,NaN,102.833333
98,2010-12-11,Jazz,,Raja Bell,strained right abductor (DNP),1610612762,Raja Bell,0,21000346,1610612762.0,NaN,102.536364
99,2010-12-11,Pacers,,Jeff Foster,placed on IL,1610612754,Jeff Foster,0,21000342,1610612754.0,114.2,112.300000
100,2010-12-11,Raptors,,Peja Stojakovic,swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000344,1610612761.0,NaN,105.662500
101,2010-12-12,Magic,,Chris Duhon,strained lower back (DNP),1610612753,Chris Duhon,0,21000354,1610612753.0,NaN,102.591304
102,2010-12-13,Jazz,,Raja Bell,strained right abductor (DNP),1610612762,Raja Bell,0,21000359,1610612762.0,NaN,102.536364
103,2010-12-14,Kings,,Tyreke Evans,left foot injury (DTD),1610612758,Tyreke Evans,0,21000364,1610612758.0,NaN,99.760000
104,2010-12-14,Magic,,Mickael Pietrus,sprained left knee (DNP),1610612753,Mickael Pietrus,0,21000365,1610612753.0,NaN,99.647368
105,2010-12-14,Magic,,Quentin Richardson,sore left elbow (DNP),1610612753,Quentin Richardson,0,21000365,1610612753.0,NaN,102.660870
106,2010-12-14,Nuggets,,Chauncey Billups,sprained right wrist (DNP),1610612743,Chauncey Billups,0,21000365,1610612743.0,NaN,107.881818
107,2010-12-14,Raptors,,Peja Stojakovic,swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000360,1610612761.0,NaN,105.662500
108,2010-12-15,Bulls,,Joakim Noah,torn ligament in right thumb (out indefinitely),1610612741,Joakim Noah,0,21000370,1610612741.0,124.7,105.537500
109,2010-12-15,Celtics,,Shaquille O'Neal,sore right calf (DNP),1610612738,Shaquille O'Neal,0,21000368,1610612738.0,NaN,118.206250
110,2010-12-15,Raptors,,Andrea Bargnani,sore left knee (DNP),1610612761,Andrea Bargnani,0,21000370,1610612761.0,NaN,103.128000
111,2010-12-15,Raptors,,Peja Stojakovic,swollen left knee (DNP),1610612761,Peja Stojakovic,0,21000370,1610612761.0,NaN,105.662500
112,2010-12-16,Celtics,,Rajon Rondo,sprained left ankle (DNP),1610612738,Rajon Rondo,0,21000379,1610612738.0,NaN,111.475000
113,2010-12-16,Celtics,,Shaquille O'Neal,sore right calf (DNP),1610612738,Shaquille O'Neal,0,21000379,1610612738.0,NaN,118.206250
114,2010-12-16,Nets,,Anthony Morrow,strained right hamstring (DNP),1610612751,Anthony Morrow,0,21000378,1610612751.0,NaN,98.484000
115,2010-12-16,Nuggets,,Chauncey Billups,torn ligament in right wrist (DNP),1610612743,Chauncey Billups,0,21000380,1610612743.0,NaN,107.881818
116,2010-12-16,Spurs,,Tiago Splitter,strained right adductor (DTD),1610612759,Tiago Splitter,0,21000380,1610612759.0,NaN,105.140000
117,2010-12-17,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000391,1610612757.0,NaN,105.652174
118,2010-12-17,Raptors,,Sonny Weems,sore lower back (DNP),1610612761,Sonny Weems,0,21000384,1610612761.0,NaN,100.644000
119,2010-12-18,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000399,1610612757.0,NaN,105.652174
120,2010-12-18,Blazers,,Marcus Camby,sore right shoulder (DNP),1610612757,Marcus Camby,0,21000399,1610612757.0,NaN,102.877778
121,2010-12-18,Blazers,,Nicolas Batum,sore right shoulder (DNP),1610612757,Nicolas Batum,0,21000399,1610612757.0,NaN,99.796296
122,2010-12-18,Nuggets,,Chauncey Billups,torn ligament in right wrist (DNP),1610612743,Chauncey Billups,0,21000398,1610612743.0,NaN,107.881818
123,2010-12-18,Spurs,,George Hill,sprained right big toe (DNP),1610612759,George Hill,0,21000397,1610612759.0,NaN,112.050000
124,2010-12-19,Celtics,,Rajon Rondo,sprained left ankle (DNP),1610612738,Rajon Rondo,0,21000400,1610612738.0,NaN,111.475000
125,2010-12-19,Nets,,Quinton Ross,bruised lower back (DNP),1610612751,Quinton Ross,0,21000401,1610612751.0,NaN,82.485714
126,2010-12-19,Pistons,,Richard Hamilton,upset stomach (DNP),1610612765,Richard Hamilton,0,21000403,1610612765.0,NaN,96.896000
127,2010-12-19,Pistons,,Rodney Stuckey,sore left big toe (DNP),1610612765,Rodney Stuckey,0,21000403,1610612765.0,NaN,103.046154
128,2010-12-19,Raptors,,Andrea Bargnani,sore right ankle (DNP),1610612761,Andrea Bargnani,0,21000402,1610612761.0,NaN,103.288462
129,2010-12-19,Raptors,,Sonny Weems,back spasms (DNP),1610612761,Sonny Weems,0,21000402,1610612761.0,NaN,100.644000
130,2010-12-20,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000412,1610612757.0,NaN,105.652174
131,2010-12-20,Blazers,,Marcus Camby,strained right shoulder (DNP),1610612757,Marcus Camby,0,21000412,1610612757.0,NaN,102.877778
132,2010-12-20,Clippers,,Craig Smith,back injury (out indefinitely),1610612746,Craig Smith,0,21000414,1610612746.0,NaN,91.691667
133,2010-12-20,Spurs,,George Hill,sprained right big toe (DNP),1610612759,George Hill,0,21000411,1610612759.0,NaN,112.050000
134,2010-12-20,Warriors,,Dan Gadzuric,strained left groin (DNP),1610612744,Dan Gadzuric,0,21000413,1610612744.0,NaN,95.831818
135,2010-12-20,Bucks,,Carlos Delfino,concussion (DNP),1610612749,Carlos Delfino,0,21000412,1610612749.0,NaN,89.842857
136,2010-12-21,Magic,,Malik Allen,sprained left ankle (DNP),1610612753,Malik Allen,0,21000416,1610612753.0,NaN,96.925000
137,2010-12-21,Nets,,Quinton Ross,bruised lower back (DNP),1610612751,Quinton Ross,0,21000418,1610612751.0,NaN,82.485714
138,2010-12-21,Warriors,,Dan Gadzuric,strained left groin (DNP),1610612744,Dan Gadzuric,0,21000419,1610612744.0,NaN,95.831818
139,2010-12-22,Celtics,,Rajon Rondo,sprained left ankle (DNP),1610612738,Rajon Rondo,0,21000424,1610612738.0,NaN,111.475000
140,2010-12-22,Nets,,Quinton Ross,bruised lower back (DNP),1610612751,Quinton Ross,0,21000427,1610612751.0,NaN,82.485714
141,2010-12-22,Raptors,,Jerryd Bayless,food poisoning (DNP),1610612761,Jerryd Bayless,0,21000422,1610612761.0,NaN,101.536000
142,2010-12-22,Raptors,,Sonny Weems,back spasms (DNP),1610612761,Sonny Weems,0,21000422,1610612761.0,NaN,100.644000
143,2010-12-22,Spurs,,George Hill,sprained right big toe (DNP),1610612759,George Hill,0,21000428,1610612759.0,NaN,112.050000
144,2010-12-23,Spurs,,George Hill,sprained right big toe (DNP),1610612759,George Hill,0,21000430,1610612759.0,NaN,112.050000
145,2010-12-25,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000437,1610612757.0,NaN,105.652174
146,2010-12-25,Celtics,,Semih Erden,stomach virus (DTD),1610612738,Semih Erden,0,21000434,1610612738.0,NaN,93.508333
147,2010-12-25,Magic,,Jason Williams,sore left foot (DNP),1610612753,Jason Williams,0,21000434,1610612753.0,NaN,101.840000
148,2010-12-27,76ers,,Andre Iguodala,right Achilles tendinitis (DNP),1610612755,Andre Iguodala,0,21000454,1610612755.0,NaN,99.496000
149,2010-12-27,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000452,1610612757.0,NaN,105.652174
150,2010-12-27,Bucks,,Drew Gooden,sore left foot (DNP),1610612749,Drew Gooden,0,21000448,1610612749.0,NaN,94.565000
151,2010-12-27,Magic,,Jason Williams,sore left foot (DNP),1610612753,Jason Williams,0,21000446,1610612753.0,NaN,101.840000
152,2010-12-27,Raptors,,Sonny Weems,back spasms (DNP),1610612761,Sonny Weems,0,21000447,1610612761.0,NaN,100.644000
153,2010-12-28,Blazers,,Brandon Roy,sore left knee (DNP),1610612757,Brandon Roy,0,21000461,1610612757.0,NaN,105.652174
154,2010-12-28,Blazers,,Marcus Camby,sprained right ankle (P) / left ankle (CBC) (DNP),1610612757,Marcus Camby,0,21000461,1610612757.0,NaN,103.562069
155,2010-12-28,Bucks,,Drew Gooden,plantar fasciitis in left foot (DNP),1610612749,Drew Gooden,0,21000458,1610612749.0,NaN,94.565000
156,2010-12-28,Magic,,Jason Williams,sore left foot (DNP),1610612753,Jason Williams,0,21000455,1610612753.0,NaN,101.840000
157,2010-12-28,Magic,,Quentin Richardson,flu-like symptoms (DNP),1610612753,Quentin Richardson,0,21000455,1610612753.0,NaN,99.166667
158,2010-12-28,Raptors,,Jose Calderon,sore ankle (DNP),1610612761,Jose Calderon,0,21000459,1610612761.0,NaN,102.376923
159,2010-12-28,Raptors,,Sonny Weems,back spasms (DNP),1610612761,Sonny Weems,0,21000459,1610612761.0,NaN,100.644000

In [116]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_date', 'player'], how='inner').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 628 entries, 0 to 627
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     628 non-null    datetime64[ns]
 1   Team          628 non-null    object
 2   Acquired      628 non-null    object
 3   Relinquished  628 non-null    object
 4   Notes         628 non-null    object
 5   team_id       628 non-null    object
 6   player        628 non-null    object
 7   A             628 non-null    int64
 8   game_id       628 non-null    int64
 9   TEAM_ID       628 non-null    object
 10  E_OFF_RATING  24 non-null     float64
 11  cma2          624 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(7)
memory usage: 63.8+ KB

# how do the player names match up?

# how many rows were lost due to players names not matching up?

In [117]:
df_inj

,Date,Team,Acquired,Relinquished,Notes,team_id,player,A
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer,0
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko,0
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White,0
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres,0
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy,0
...,...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin,0
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George,0
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala,0
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul,0
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love,0

# how of the df_inj rows line up with an nba game date?

In [118]:
df_gamess1011 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])
df_gamess1011 = df_gamess1011[(df_gamess1011.season_type == 'Regular Season') 
                              | (df_gamess1011.season_type == 'Playoffs')][(df_gamess1011.season == '2010-11')][['game_id', 'game_date','team_id']]
df_gamess1011

        game_id  game_date     team_id
9840   21000001 2010-10-26  1610612738
9841   21000001 2010-10-26  1610612748
9842   21000002 2010-10-26  1610612757
9843   21000002 2010-10-26  1610612756
9844   21000003 2010-10-26  1610612745
...         ...        ...         ...
29861  41000404 2011-06-07  1610612748
29862  41000405 2011-06-09  1610612742
29863  41000405 2011-06-09  1610612748
29864  41000406 2011-06-12  1610612748
29865  41000406 2011-06-12  1610612742

[2622 rows x 3 columns]

In [119]:
df_gamess1011.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2622 entries, 9840 to 29865
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_id    2622 non-null   int64
 1   game_date  2622 non-null   datetime64[ns]
 2   team_id    2622 non-null   int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 81.9 KB

In [120]:
df_inj2 = pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_gamess1011, on=['game_date', 'team_id'], how='inner')
df_inj2

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000002
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0,21000002
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,1610612757,Joel Przybilla,0,21000002
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,1610612738,Avery Bradley,0,21000001
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,1610612738,Kendrick Perkins,0,21000001
...,...,...,...,...,...,...,...,...,...
1673,2011-05-26,Bulls,,Omer Asik,placed on IL with stress fracture in left fibula (out for season),1610612741,Omer Asik,0,41000305
1674,2011-05-31,Heat,,Zydrunas Ilgauskas,placed on IL,1610612748,Zydrunas Ilgauskas,0,41000401
1675,2011-06-05,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor,1610612742,Brendan Haywood,0,41000403
1676,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,0,41000404
1677,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,0,41000405

In [121]:
pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_gamess1011, on=['game_date', 'team_id'], how='inner').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1678 entries, 0 to 1677
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     1678 non-null   datetime64[ns]
 1   Team          1678 non-null   object
 2   Acquired      1678 non-null   object
 3   Relinquished  1678 non-null   object
 4   Notes         1678 non-null   object
 5   team_id       1678 non-null   object
 6   player        1678 non-null   object
 7   A             1678 non-null   int64
 8   game_id       1678 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 131.1+ KB

In [122]:
df_inj3 = df_inj2.drop(columns=['A', 'Notes', 'Acquired', 'Relinquished'])

In [123]:
df_inj3

      game_date       Team     team_id              player   game_id
0    2010-10-26    Blazers  1610612757     Elliot Williams  21000002
1    2010-10-26    Blazers  1610612757           Greg Oden  21000002
2    2010-10-26    Blazers  1610612757      Joel Przybilla  21000002
3    2010-10-26    Celtics  1610612738       Avery Bradley  21000001
4    2010-10-26    Celtics  1610612738    Kendrick Perkins  21000001
...         ...        ...         ...                 ...       ...
1673 2011-05-26      Bulls  1610612741           Omer Asik  41000305
1674 2011-05-31       Heat  1610612748  Zydrunas Ilgauskas  41000401
1675 2011-06-05  Mavericks  1610612742     Brendan Haywood  41000403
1676 2011-06-07  Mavericks  1610612742   Rodrigue Beaubois  41000404
1677 2011-06-09  Mavericks  1610612742     Brendan Haywood  41000405

[1678 rows x 5 columns]

In [124]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '6injuries_2010-11.csv')
if not os.path.exists(datapath_df):
    df_inj3.to_csv(datapath_df, index=False)

In [125]:
set(df_inj3.player)

{' Tony Parker',
 'A.J. Price',
 'Aaron Brooks',
 'Aaron Gray',
 'Acie Law',
 'Al Harrington',
 'Al Horford',
 'Al Thornton',
 'Alex Ajinca',
 'Alonzo Gee',
 "Amar'e Stoudemire",
 'Amir Johnson',
 'Anderson Varejao',
 'Andray Blatche',
 'Andre Iguodala',
 'Andrea Bargnani',
 'Andrei Kirilenko',
 'Andres Nocioni',
 'Andrew Bogut',
 'Andrew Bynum',
 'Andris Biedrins',
 'Andy Rautins',
 'Antawn Jamison',
 'Anthony Carter',
 'Anthony Morrow',
 'Anthony Parker',
 'Anthony Randolph',
 'Anthony Tolliver',
 'Antoine Wright',
 'Antonio McDyess',
 'Armon Johnson',
 'Arron Afflalo',
 'Austin Daye',
 'Avery Bradley',
 'B.J. Mullens',
 'Baron Davis',
 'Ben Uzoh',
 'Ben Wallace',
 'Beno Udrih',
 'Bill Walker',
 'Brad Miller',
 'Brandan Wright',
 'Brandon Bass',
 'Brandon Jennings',
 'Brandon Roy',
 'Brandon Rush',
 'Brendan Haywood',
 'Brian Cardinal',
 'Brian Cook',
 'Brian Scalabrine',
 'Brian Skinner',
 'C.J. Miles',
 'Carlos Arroyo',
 'Carlos Boozer',
 'Carlos Delfino',
 'Carmelo Anthony',
 'Caron Butler',
 'Cartier Martin',
 'Channing Frye',
 'Charlie Bell',
 'Charlie Villanueva',
 'Chase Budinger',
 'Chauncey Billups',
 'Chris Andersen',
 'Chris Bosh',
 'Chris Douglas-Roberts',
 'Chris Duhon',
 'Chris Kaman',
 'Chris Paul',
 'Chris Quinn',
 'Chris Wilcox',
 'Christian Eyenga',
 'Chuck Hayes',
 'Cole Aldrich',
 'Corey Brewer',
 'Corey Maggette',
 'Courtney Lee',
 'Craig Brackins',
 'Craig Smith',
 'D.J. White',
 "Da'Sean Butler",
 'DaJuan Summers',
 'Daequan Cook',
 'Dahntay Jones',
 'Damien Wilkins',
 'Damion James',
 'Dan Gadzuric',
 'Daniel Gibson',
 'Daniel Orton',
 'Danilo Gallinari',
 'Danny Granger',
 'Danny Green',
 'Dante Cunningham',
 'Darius Songaila',
 'Darko Milicic',
 'Darrell Arthur',
 'Darren Collison',
 'David Andersen',
 'David Lee',
 'David West',
 'DeAndre Jordan',
 'DeJuan Blair',
 'DeMarre Carroll',
 'DeSagana Diop',
 'Delonte West',
 'Deron Williams',
 'Derrick Brown',
 'Derrick Caracter',
 'Derrick Favors',
 'Derrick Rose',
 'Devin Ebanks',
 'Devin Harris',
 'Dexter Pittman',
 'Didier Mbenga ',
 'Dirk Nowitzki',
 'Dominic McGuire',
 'Dominique Jones',
 'Drew Gooden',
 'Dwight Howard',
 'Dwyane Wade',
 'Ed Davis ',
 'Eddy Curry',
 'Eduardo Najera',
 'Ekpe Udoh',
 'Elliot Williams',
 'Eric Gordon',
 'Erick Dampier',
 'Ersan Ilyasova',
 'Etan Thomas',
 'Francisco Elson',
 'Francisco Garcia',
 'Gani Lawal',
 'Garret Siler',
 'Garrett Temple',
 'Gary Neal',
 'George Hill',
 'Gerald Henderson Jr.',
 'Gerald Wallace',
 'Gilbert Arenas',
 'Glen Davis',
 'Goran Dragic',
 'Gordon Hayward',
 'Grant Hill',
 'Greg Oden',
 'Greivis Vasquez',
 "Hamady N'Diaye",
 'Hamed Haddadi',
 'Hasheem Thabeet',
 'Hassan Whiteside',
 'Hilton Armstrong',
 'Ian Mahinmi',
 'Ish Smith',
 'J.J. Hickson',
 'J.J. Redick',
 'JaVale McGee',
 'Jamaal Magloire',
 'Jamal Crawford',
 'Jamario Moon',
 'Jameer Nelson',
 'James Anderson',
 'James Posey',
 'Jannero Pargo',
 'Jared Jeffries',
 'Jason Collins',
 'Jason Kapono',
 'Jason Kidd',
 'Jason Maxiell',
 'Jason Richardson',
 'Jason Smith',
 'Jason Thompson',
 'Jason Williams',
 'Jeff Adrien',
 'Jeff Foster',
 'Jeff Green',
 'Jeremy Evans',
 'Jeremy Lin',
 "Jermaine O'Neal",
 'Jermaine Taylor',
 'Jerry Stackhouse',
 'Jerryd Bayless',
 'Jianlian Yi',
 'Joakim Noah',
 'Jodie Meeks',
 'Joe Alexander',
 'Joe Johnson',
 'Joe Smith ',
 'Joel Przybilla',
 'Joey Dorsey',
 'Joey Graham',
 'John Lucas III',
 'John Salmons',
 'John Wall ',
 'John Wallace',
 'Jon Brockman',
 'Jonas Jerebko',
 'Jonny Flynn',
 'Jordan Crawford',
 'Jordan Farmar',
 'Jordan Hill',
 'Jose Barea ',
 'Jose Calderon',
 'Josh Howard',
 'Josh McRoberts',
 'Josh Powell',
 'Josh Smith',
 'Julian Wright',
 'Juwan Howard',
 'Kelenna Azubuike',
 'Kendrick Perkins',
 'Kenyon Martin',
 'Kevin Durant',
 'Kevin Garnett',
 'Kevin Love',
 'Kevin Martin',
 'Kevin Seraphin',
 'Keyon Dooling',
 'Kirk Hinrich',
 'Kosta Koufos',
 'Kris Humphries',
 'Kurt Thomas',
 'Kwame Brown',
 'Kyle Lowry',
 'Kyrylo Fesenko',
 'LaMarcus Aldridge',
 'Lance Stephenson',
 'Larry Sanders ',
 'Lazar Hayward',
 'LeBron James',
 'Leandro Barbosa',
 'Leon Powe',
 'Lester Hudson',
 'Linas Kleiza',
 'Lou Amundson',
 'Lou Williams',
 'Luc Mbah a Moute',
 'Luis Scola',
 'Luke Babbitt',
 'Luke Harangody',
 'Luke Ridnour',
 'Luke Walton',
 'Luther Head',
 'Magnum Rolle',
 'Malik Allen',
 'Manny Harris',
 'Manu Ginobili',
 'Marc Gasol',
 'Marco Belinelli',
 'Marcus Banks',
 'Marcus Camby',
 'Marcus Thornton ',
 'Mario Chalmers',
 'Mario West',
 'Marquis Daniels',
 'Martell Webster',
 'Marvin Williams',
 'Matt Barnes',
 'Matt Bonner',
 'Matt Carroll',
 'Matt Janning',
 'Maurice Ager',
 'Maurice Evans',
 'Mehmet Okur',
 'Melvin Ely',
 'Michael Beasley',
 'Michael Redd',
 'Mickael Pietrus',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Mike Miller',
 'Mo Williams',
 'Monta Ellis',
 'Morris Peterson',
 'Mustafa Shakur',
 'Nate Robinson',
 'Nazr Mohammed',
 'Nenad Krstic',
 'Nene Hilario ',
 'Nick Collison',
 'Nick Young',
 'Nicolas Batum',
 'Nikola Pekovic',
 'O.J. Mayo',
 'Omer Asik',
 'Omri Casspi',
 'Orien Greene',
 'Othyus Jeffers',
 'Pape Sy',
 'Patrick Patterson',
 'Patty Mills',
 'Paul George',
 'Paul Millsap',
 'Paul Pierce',
 'Peja Stojakovic',
 'Pooh Jeter',
 'Pops Mensah-Bonsu',
 'Quentin Richardson',
 'Quincy Pondexter',
 'Quinton Ross',
 'Raja Bell',
 'Rajon Rondo',
 'Randy Foye',
 'Rashard Lewis',
 'Rasual Butler',
 'Ray Allen',
 'Raymond Felton',
 'Reggie Evans',
 'Reggie Williams',
 'Renaldo Balkman',
 'Richard Hamilton',
 'Robert Vaden',
 'Robin Lopez',
 'Rodney Carney',
 'Rodney Stuckey',
 'Rodrigue Beaubois',
 'Roger Mason Jr.',
 'Ronnie Brewer',
 'Ronnie Price',
 'Ronny Turiaf',
 'Roy Hibbert',
 'Rudy Fernandez',
 'Rudy Gay',
 'Ryan Anderson',
 'Ryan Gomes',
 'Ryan Hollins',
 'Samardo Samuels',
 'Samuel Dalembert',
 'Sasha Vujacic',
 'Sean Marks',
 'Sebastian Telfair',
 'Semih Erden',
 "Shaquille O'Neal",
 'Shaun Livingston',
 'Shawn Marion',
 'Shawne Williams',
 'Shelden Williams',
 'Sherron Collins',
 'Solomon Alabi',
 'Solomon Jones',
 'Sonny Weems',
 'Spencer Hawes',
 'Stephen Curry',
 'Stephen Graham',
 'Stephen Jackson',
 'Steve Blake',
 'Steve Nash',
 'Steve Novak',
 'Sundiata Gaines',
 'T.J. Ford',
 'Taj Gibson',
 'Tayshaun Prince',
 'Terrence Williams',
 'Terrico White',
 'Thabo Sefolosha',
 'Theo Ratliff',
 'Tiago Splitter',
 'Tim Duncan',
 'Timofey Mozgov',
 'Toney Douglas',
 'Tony Allen',
 'Tony Battie',
 'Tracy McGrady',
 'Trevor Ariza',
 'Trevor Booker',
 'Trey Johnson',
 'Troy Murphy',
 'Ty Lawson',
 'Tyler Hansbrough',
 'Tyreke Evans',
 'Tyrus Thomas',
 'Tyson Chandler',
 'Udonis Haslem',
 'Vince Carter',
 'Von Wafer',
 'Wayne Ellington',
 'Wes Johnson',
 'Will Bynum',
 'Willie Warren',
 'Wilson Chandler',
 'Xavier Henry',
 'Yao Ming',
 'Zabian Dowdell',
 'Zach Randolph',
 'Zaza Pachulia',
 'Zydrunas Ilgauskas'}

In [126]:
len(set(df_inj3.player))

384

In [127]:
#check player (name) similarity with player of df_inj3


#check for player (name) similiarty with player of df_or1011a

In [128]:
#check player (name) similarity with player of df_inj3
import numpy as np
from fuzzywuzzy import process, fuzz

In [129]:
unique_player = df_inj3.player.unique().tolist()
sorted(unique_player)[:20]

[' Tony Parker',
 'A.J. Price',
 'Aaron Brooks',
 'Aaron Gray',
 'Acie Law',
 'Al Harrington',
 'Al Horford',
 'Al Thornton',
 'Alex Ajinca',
 'Alonzo Gee',
 "Amar'e Stoudemire",
 'Amir Johnson',
 'Anderson Varejao',
 'Andray Blatche',
 'Andre Iguodala',
 'Andrea Bargnani',
 'Andrei Kirilenko',
 'Andres Nocioni',
 'Andrew Bogut',
 'Andrew Bynum']

In [130]:
unique_player2 = df_or1011a['PLAYER_NAME'].unique().tolist()
sorted(unique_player2)[:20]

['AJ Price',
 'Aaron Brooks',
 'Aaron Gray',
 'Acie Law',
 'Al Harrington',
 'Al Horford',
 'Al Jefferson',
 'Al Thornton',
 'Al-Farouq Aminu',
 'Alexis Ajinca',
 'Alonzo Gee',
 "Amar'e Stoudemire",
 'Amir Johnson',
 'Anderson Varejao',
 'Andray Blatche',
 'Andre Iguodala',
 'Andre Miller',
 'Andrea Bargnani',
 'Andrei Kirilenko',
 'Andres Nocioni']

In [131]:
for player_ in sorted(unique_player):
    print(player_)
    print(process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[:2])

 Tony Parker
[('Tony Parker', 100), ('Anthony Parker', 88)]
A.J. Price
[('AJ Price', 94), ('Ronnie Price', 71)]
Aaron Brooks
[('Aaron Brooks', 100), ('Aaron Gray', 67)]
Aaron Gray
[('Aaron Gray', 100), ('Aaron Brooks', 67)]
Acie Law
[('Acie Law', 100), ('Gani Lawal', 67)]
Al Harrington
[('Al Harrington', 100), ('Al Thornton', 75)]
Al Horford
[('Al Horford', 100), ('Al Thornton', 67)]
Al Thornton
[('Al Thornton', 100), ('Marcus Thornton', 84)]
Alex Ajinca
[('Alexis Ajinca', 92), ('Austin Daye', 55)]
Alonzo Gee
[('Alonzo Gee', 100), ('Danny Green', 57)]
Amar'e Stoudemire
[("Amar'e Stoudemire", 100), ('Lamar Odom', 59)]
Amir Johnson
[('Amir Johnson', 100), ('Armon Johnson', 80)]
Anderson Varejao
[('Anderson Varejao', 100), ('Ryan Anderson', 76)]
Andray Blatche
[('Andray Blatche', 100), ('Luther Head', 56)]
Andre Iguodala
[('Andre Iguodala', 100), ('DeAndre Jordan', 64)]
Andrea Bargnani
[('Andrea Bargnani', 100), ('Andres Nocioni', 62)]
Andrei Kirilenko
[('Andrei Kirilenko', 100), ('Andris Biedrins', 65)]
Andres Nocioni
[('Andres Nocioni', 100), ('Andrea Bargnani', 62)]
Andrew Bogut
[('Andrew Bogut', 100), ('Andrew Bynum', 75)]
Andrew Bynum
[('Andrew Bynum', 100), ('Andrew Bogut', 75)]
Andris Biedrins
[('Andris Biedrins', 100), ('Andrei Kirilenko', 65)]
Andy Rautins
[('Andy Rautins', 100), ('Andris Biedrins', 59)]
Antawn Jamison
[('Antawn Jamison', 100), ('Dahntay Jones', 59)]
Anthony Carter
[('Anthony Carter', 100), ('Anthony Parker', 86)]
Anthony Morrow
[('Anthony Morrow', 100), ('Joel Anthony', 74)]
Anthony Parker
[('Anthony Parker', 100), ('Tony Parker', 88)]
Anthony Randolph
[('Anthony Randolph', 100), ('Zach Randolph', 76)]
Anthony Tolliver
[('Anthony Tolliver', 100), ('Joel Anthony', 74)]
Antoine Wright
[('Antoine Wright', 100), ('Brandan Wright', 71)]
Antonio McDyess
[('Antonio McDyess', 100), ('Antonio Daniels', 73)]
Armon Johnson
[('Armon Johnson', 100), ('Amir Johnson', 80)]
Arron Afflalo
[('Arron Afflalo', 100), ('Al Harrington', 62)]
Austin Daye
[('Austin Daye', 100), ('D.J. Augustin', 70)]
Avery Bradley
[('Avery Bradley', 100), ('Rodney Carney', 62)]
B.J. Mullens
[('Byron Mullens', 78), ('CJ Miles', 63)]
Baron Davis
[('Baron Davis', 100), ('Ed Davis', 77)]
Ben Uzoh
[('Ben Uzoh', 100), ('Beno Udrih', 67)]
Ben Wallace
[('Ben Wallace', 100), ('Gerald Wallace', 78)]
Beno Udrih
[('Beno Udrih', 100), ('Ben Uzoh', 67)]
Bill Walker
[('Henry Walker', 71), ('Charlie Bell', 61)]
Brad Miller
[('Brad Miller', 100), ('Andre Miller', 78)]
Brandan Wright
[('Brandan Wright', 100), ('Antoine Wright', 71)]
Brandon Bass
[('Brandon Bass', 100), ('Brandon Roy', 78)]
Brandon Jennings
[('Brandon Jennings', 100), ('Brandon Roy', 78)]
Brandon Roy
[('Brandon Roy', 100), ('Brandon Jennings', 78)]
Brandon Rush
[('Brandon Rush', 100), ('Brandon Roy', 78)]
Brendan Haywood
[('Brendan Haywood', 100), ('Gordon Hayward', 62)]
Brian Cardinal
[('Brian Cardinal', 100), ('Brian Scalabrine', 73)]
Brian Cook
[('Brian Cook', 100), ('Brian Scalabrine', 67)]
Brian Scalabrine
[('Brian Scalabrine', 100), ('Brian Cardinal', 73)]
Brian Skinner
[('Brian Skinner', 100), ('Brian Scalabrine', 69)]
C.J. Miles
[('CJ Miles', 94), ('C.J. Watson', 53)]
Carlos Arroyo
[('Carlos Arroyo', 100), ('Carlos Boozer', 69)]
Carlos Boozer
[('Carlos Boozer', 100), ('Carlos Arroyo', 69)]
Carlos Delfino
[('Carlos Delfino', 100), ('Carlos Arroyo', 63)]
Carmelo Anthony
[('Carmelo Anthony', 100), ('Anthony Carter', 83)]
Caron Butler
[('Caron Butler', 100), ('Rasual Butler', 67)]
Cartier Martin
[('Cartier Martin', 100), ('Vince Carter', 69)]
Channing Frye
[('Channing Frye', 100), ('Dante Cunningham', 55)]
Charlie Bell
[('Charlie Bell', 100), ('Charlie Villanueva', 74)]
Charlie Villanueva
[('Charlie Villanueva', 100), ('Charlie Bell', 74)]
Chase Budinger
[('Chase Budinger', 100), ('Shane Battier', 59)]
Chauncey Billups
[('Chauncey Billups', 100), ('Charlie Bell', 57)]
Chris Andersen
[('Chris Andersen', 100), ('David Andersen', 73)]
Chris Bosh
[('Chris Bosh', 100), ('Chris Johnson', 70)]
Chris Douglas-Roberts
[('Chris Douglas-Roberts', 100), ('Toney Douglas', 70)]
Chris Duhon
[('Chris Duhon', 100), ('Chris Johnson', 75)]
Chris Kaman
[('Chris Kaman', 100), ('Manny Harris', 70)]
Chris Paul
[('Chris Paul', 100), ('Chris Bosh', 67)]
Chris Quinn
[('Chris Quinn', 100), ('Chris Duhon', 73)]
Chris Wilcox
[('Chris Wilcox', 100), ('Chris Bosh', 67)]
Christian Eyenga
[('Christian Eyenga', 100), ('Chris Quinn', 59)]
Chuck Hayes
[('Chuck Hayes', 100), ('Austin Daye', 45)]
Cole Aldrich
[('Cole Aldrich', 100), ('Derrick Rose', 58)]
Corey Brewer
[('Corey Brewer', 100), ('Ronnie Brewer', 72)]
Corey Maggette
[('Corey Maggette', 100), ('Courtney Lee', 62)]
Courtney Lee
[('Courtney Lee', 100), ('Corey Maggette', 62)]
Craig Brackins
[('Craig Brackins', 100), ('Craig Smith', 62)]
Craig Smith
[('Craig Smith', 100), ('JR Smith', 77)]
D.J. White
[('DJ White', 94), ('T.J. Ford', 59)]
Da'Sean Butler
[('Rasual Butler', 74), ('Caron Butler', 69)]
DaJuan Summers
[('DaJuan Summers', 100), ('Damion James', 54)]
Daequan Cook
[('Daequan Cook', 100), ('Brian Cook', 64)]
Dahntay Jones
[('Dahntay Jones', 100), ('Joel Anthony', 64)]
Damien Wilkins
[('Damien Wilkins', 100), ('Deron Williams', 64)]
Damion James
[('Damion James', 100), ('James Jones', 70)]
Dan Gadzuric
[('Dan Gadzuric', 100), ('Maurice Evans', 64)]
Daniel Gibson
[('Daniel Gibson', 100), ('Taj Gibson', 75)]
Daniel Orton
[('Daniel Gibson', 72), ('Al Thornton', 70)]
Danilo Gallinari
[('Danilo Gallinari', 100), ('Daniel Gibson', 62)]
Danny Granger
[('Danny Granger', 100), ('Danny Green', 75)]
Danny Green
[('Danny Green', 100), ('Danny Granger', 75)]
Dante Cunningham
[('Dante Cunningham', 100), ('Channing Frye', 55)]
Darius Songaila
[('Darius Songaila', 100), ('Glen Davis', 56)]
Darko Milicic
[('Darko Milicic', 100), ('Deron Williams', 52)]
Darrell Arthur
[('Darrell Arthur', 100), ('DeMarre Carroll', 62)]
Darren Collison
[('Darren Collison', 100), ('Jarron Collins', 76)]
David Andersen
[('David Andersen', 100), ('Chris Andersen', 73)]
David Lee
[('David Lee', 100), ('Glen Davis', 74)]
David West
[('David West', 100), ('David Lee', 74)]
DeAndre Jordan
[('DeAndre Jordan', 100), ('Jordan Hill', 71)]
DeJuan Blair
[('DeJuan Blair', 100), ('Juwan Howard', 58)]
DeMarre Carroll
[('DeMarre Carroll', 100), ('Matt Carroll', 74)]
DeSagana Diop
[('DeSagana Diop', 100), ('David Andersen', 52)]
Delonte West
[('Delonte West', 100), ('Donte Greene', 58)]
Deron Williams
[('Deron Williams', 100), ('Mo Williams', 84)]
Derrick Brown
[('Derrick Brown', 100), ('Derrick Rose', 80)]
Derrick Caracter
[('Derrick Caracter', 100), ('Derrick Rose', 74)]
Derrick Favors
[('Derrick Favors', 100), ('Derrick Rose', 77)]
Derrick Rose
[('Derrick Rose', 100), ('Derrick Brown', 80)]
Devin Ebanks
[('Devin Ebanks', 100), ('Devin Harris', 67)]
Devin Harris
[('Devin Harris', 100), ('Mike Harris', 71)]
Dexter Pittman
[('Dexter Pittman', 100), ('Quincy Pondexter', 60)]
Didier Mbenga
[('DJ Mbenga', 80), ('Eddie House', 50)]
Dirk Nowitzki
[('Dirk Nowitzki', 100), ('Andres Nocioni', 52)]
Dominic McGuire
[('Dominic McGuire', 100), ('Dominique Jones', 53)]
Dominique Jones
[('Dominique Jones', 100), ('Solomon Jones', 64)]
Drew Gooden
[('Drew Gooden', 100), ('Greg Oden', 70)]
Dwight Howard
[('Dwight Howard', 100), ('Josh Howard', 71)]
Dwyane Wade
[('Dwyane Wade', 100), ('Kwame Brown', 55)]
Ed Davis
[('Ed Davis', 100), ('Glen Davis', 78)]
Eddy Curry
[('Stephen Curry', 67), ('Courtney Lee', 55)]
Eduardo Najera
[('Eduardo Najera', 100), ('DeMar DeRozan', 52)]
Ekpe Udoh
[('Ekpe Udoh', 100), ('Ben Uzoh', 59)]
Elliot Williams
[('Elliot Williams', 100), ('Mo Williams', 84)]
Eric Gordon
[('Eric Gordon', 100), ('Ben Gordon', 76)]
Erick Dampier
[('Erick Dampier', 100), ('Derrick Caracter', 62)]
Ersan Ilyasova
[('Ersan Ilyasova', 100), ('Deron Williams', 57)]
Etan Thomas
[('Etan Thomas', 100), ('Kurt Thomas', 73)]
Francisco Elson
[('Francisco Elson', 100), ('Francisco Garcia', 75)]
Francisco Garcia
[('Francisco Garcia', 100), ('Francisco Elson', 75)]
Gani Lawal
[('Gani Lawal', 100), ('Acie Law', 67)]
Garret Siler
[('Garret Siler', 100), ('Garrett Temple', 69)]
Garrett Temple
[('Garrett Temple', 100), ('Garret Siler', 69)]
Gary Neal
[('Gary Neal', 100), ('Earl Clark', 63)]
George Hill
[('George Hill', 100), ('Paul George', 73)]
Gerald Henderson Jr.
[('Gerald Henderson', 100), ('Ryan Anderson', 62)]
Gerald Wallace

[('Gerald Wallace', 100), ('Ben Wallace', 78)]
Gilbert Arenas
[('Gilbert Arenas', 100), ('Garret Siler', 62)]
Glen Davis
[('Glen Davis', 100), ('Ed Davis', 78)]
Goran Dragic
[('Goran Dragic', 100), ('Eric Gordon', 70)]
Gordon Hayward
[('Gordon Hayward', 100), ('Ben Gordon', 75)]
Grant Hill
[('Grant Hill', 100), ('Jordan Hill', 76)]
Greg Oden
[('Greg Oden', 100), ('Greg Monroe', 70)]
Greivis Vasquez
[('Greivis Vasquez', 100), ('Maurice Evans', 50)]
Hamady N'Diaye
[('Hamady Ndiaye', 89), ('Hamed Haddadi', 52)]
Hamed Haddadi
[('Hamed Haddadi', 100), ('Ed Davis', 57)]
Hasheem Thabeet
[('Hasheem Thabeet', 100), ('Steve Nash', 56)]
Hassan Whiteside
[('Hassan Whiteside', 100), ('Wesley Johnson', 53)]
Hilton Armstrong
[('Hilton Armstrong', 100), ('Armon Johnson', 62)]
Ian Mahinmi
[('Ian Mahinmi', 100), ('Kevin Martin', 61)]
Ish Smith
[('Ish Smith', 100), ('Josh Smith', 84)]
J.J. Hickson
[('JJ Hickson', 95), ('Taj Gibson', 63)]
J.J. Redick
[('JJ Redick', 94), ('AJ Price', 62)]
JaVale McGee
[('JaVale McGee', 100), ('Jamaal Magloire', 59)]
Jamaal Magloire
[('Jamaal Magloire', 100), ('JaVale McGee', 59)]
Jamal Crawford
[('Jamal Crawford', 100), ('Jordan Crawford', 76)]
Jamario Moon
[('Jamario Moon', 100), ('Lamar Odom', 64)]
Jameer Nelson
[('Jameer Nelson', 100), ('James Johnson', 69)]
James Anderson
[('James Anderson', 100), ('LeBron James', 77)]
James Posey
[('James Posey', 100), ('James Jones', 73)]
Jannero Pargo
[('Anderson Varejao', 62), ('Johan Petro', 58)]
Jared Jeffries
[('Jared Jeffries', 100), ('Jeff Adrien', 64)]
Jason Collins
[('Jason Collins', 100), ('Jarron Collins', 89)]
Jason Kapono
[('Jason Kapono', 100), ('Jason Thompson', 69)]
Jason Kidd
[('Jason Kidd', 100), ('Jason Richardson', 67)]
Jason Maxiell
[('Jason Maxiell', 100), ('Jason Smith', 67)]
Jason Richardson
[('Jason Richardson', 100), ('Quentin Richardson', 77)]
Jason Smith
[('Jason Smith', 100), ('Joe Smith', 80)]
Jason Thompson
[('Jason Thompson', 100), ('Jason Kapono', 69)]
Jason Williams
[('Jason Williams', 100), ('Mo Williams', 84)]
Jeff Adrien
[('Jeff Adrien', 100), ('Jeff Green', 76)]
Jeff Foster
[('Jeff Foster', 100), ('Jeff Teague', 64)]
Jeff Green
[('Jeff Green', 100), ('Jeff Adrien', 76)]
Jeremy Evans
[('Jeremy Evans', 100), ('Jeremy Lin', 75)]
Jeremy Lin
[('Jeremy Lin', 100), ('Jeremy Evans', 75)]
Jermaine O'Neal
[("Jermaine O'Neal", 100), ('Jermaine Taylor', 80)]
Jermaine Taylor
[('Jermaine Taylor', 100), ("Jermaine O'Neal", 80)]
Jerry Stackhouse
[('Jerry Stackhouse', 100), ('Derrick Rose', 57)]
Jerryd Bayless
[('Jerryd Bayless', 100), ('Jason Terry', 56)]
Jianlian Yi
[('Yi Jianlian', 100), ('Julian Wright', 58)]
Joakim Noah
[('Joakim Noah', 100), ('Hakim Warrick', 50)]
Jodie Meeks
[('Jodie Meeks', 100), ('CJ Miles', 53)]
Joe Alexander
[('Jose Calderon', 69), ('James Anderson', 59)]
Joe Johnson
[('Joe Johnson', 100), ('James Johnson', 83)]
Joe Smith
[('Joe Smith', 100), ('Josh Smith', 84)]
Joel Przybilla
[('Joel Przybilla', 100), ('Zabian Dowdell', 57)]
Joey Dorsey
[('Joey Dorsey', 100), ('Toney Douglas', 58)]
Joey Graham
[('Joey Graham', 100), ('Stephen Graham', 71)]
John Lucas III
[('John Lucas III', 100), ('John Wall', 62)]
John Salmons
[('John Salmons', 100), ('Solomon Jones', 72)]
John Wall
[('John Wall', 100), ('Josh Powell', 70)]
John Wallace
[('John Wall', 86), ('Ben Wallace', 78)]
Jon Brockman
[('Jon Brockman', 100), ('Elton Brand', 61)]
Jonas Jerebko
[('James Jones', 58), ('Joe Johnson', 58)]
Jonny Flynn
[('Jonny Flynn', 100), ('Tony Allen', 57)]
Jordan Crawford
[('Jordan Crawford', 100), ('Jamal Crawford', 76)]
Jordan Farmar
[('Jordan Farmar', 100), ('Jordan Hill', 71)]
Jordan Hill
[('Jordan Hill', 100), ('Grant Hill', 76)]
Jose Barea
[('J.J. Barea', 83), ('Jose Calderon', 61)]
Jose Calderon
[('Jose Calderon', 100), ('James Anderson', 67)]
Josh Howard
[('Josh Howard', 100), ('Juwan Howard', 71)]
Josh McRoberts
[('Josh McRoberts', 100), ('Josh Childress', 64)]
Josh Powell
[('Josh Powell', 100), ('John Wall', 70)]
Josh Smith
[('Josh Smith', 100), ('Ish Smith', 84)]
Julian Wright
[('Julian Wright', 100), ('Brandan Wright', 67)]
Juwan Howard
[('Juwan Howard', 100), ('Josh Howard', 71)]
Kelenna Azubuike
[('Acie Law', 50), ('Glen Davis', 46)]
Kendrick Perkins
[('Kendrick Perkins', 100), ('Andris Biedrins', 65)]
Kenyon Martin
[('Kenyon Martin', 100), ('Kevin Martin', 80)]
Kevin Durant
[('Kevin Durant', 100), ('Kevin Garnett', 72)]
Kevin Garnett
[('Kevin Garnett', 100), ('Kevin Martin', 72)]
Kevin Love
[('Kevin Love', 100), ('Kevin Garnett', 67)]
Kevin Martin
[('Kevin Martin', 100), ('Kenyon Martin', 80)]
Kevin Seraphin
[('Kevin Seraphin', 100), ('Kevin Martin', 69)]
Keyon Dooling
[('Keyon Dooling', 100), ('Yao Ming', 57)]
Kirk Hinrich
[('Kirk Hinrich', 100), ('Richard Hamilton', 57)]
Kosta Koufos
[('Kosta Koufos', 100), ('Jerry Stackhouse', 50)]
Kris Humphries
[('Kris Humphries', 100), ('Ronnie Price', 54)]
Kurt Thomas
[('Kurt Thomas', 100), ('Etan Thomas', 73)]
Kwame Brown
[('Kwame Brown', 100), ('Shannon Brown', 62)]
Kyle Lowry
[('Kyle Lowry', 100), ('Kyle Korver', 67)]
Kyrylo Fesenko
[('Kyrylo Fesenko', 100), ('Raymond Felton', 50)]
LaMarcus Aldridge
[('LaMarcus Aldridge', 100), ('Marquis Daniels', 56)]
Lance Stephenson
[('Lance Stephenson', 100), ('DeShawn Stevenson', 67)]
Larry Sanders
[('Larry Sanders', 100), ('Larry Owens', 67)]
Lazar Hayward
[('Lazar Hayward', 100), ('Gordon Hayward', 70)]
LeBron James
[('LeBron James', 100), ('James Anderson', 77)]
Leandro Barbosa
[('Leandro Barbosa', 100), ('Carl Landry', 62)]
Leon Powe
[('Leon Powe', 100), ('Jose Calderon', 64)]
Lester Hudson
[('Lester Hudson', 100), ('Wesley Johnson', 59)]
Linas Kleiza
[('Linas Kleiza', 100), ('Robin Lopez', 52)]
Lou Amundson
[('Lou Amundson', 100), ('Brandon Roy', 61)]
Lou Williams
[('Lou Williams', 100), ('Mo Williams', 87)]
Luc Mbah a Moute
[('Luc Mbah a Moute', 100), ('Cole Aldrich', 50)]
Luis Scola
[('Luis Scola', 100), ('Monta Ellis', 57)]
Luke Babbitt
[('Luke Babbitt', 100), ('Luke Walton', 61)]
Luke Harangody
[('Luke Harangody', 100), ('Luke Ridnour', 62)]
Luke Ridnour
[('Luke Ridnour', 100), ('Luke Harangody', 62)]
Luke Walton
[('Luke Walton', 100), ('Earl Watson', 64)]
Luther Head
[('Luther Head', 100), ('Lester Hudson', 58)]
Magnum Rolle
[('Will Bynum', 55), ('Roger Mason Jr.', 54)]
Malik Allen
[('Malik Allen', 100), ('Ray Allen', 71)]
Manny Harris
[('Manny Harris', 100), ('Mike Harris', 71)]
Manu Ginobili
[('Manu Ginobili', 100), ('Pau Gasol', 55)]
Marc Gasol
[('Marc Gasol', 100), ('Pau Gasol', 74)]
Marco Belinelli
[('Marco Belinelli', 100), ('Marqus Blakely', 55)]
Marcus Banks
[('Marcus Banks', 100), ('Marqus Blakely', 69)]
Marcus Camby
[('Marcus Camby', 100), ('Marcus Thornton', 67)]
Marcus Thornton
[('Marcus Thornton', 100), ('Al Thornton', 84)]
Mario Chalmers
[('Mario Chalmers', 100), ('Mario West', 67)]
Mario West
[('Mario West', 100), ('David West', 70)]
Marquis Daniels
[('Marquis Daniels', 100), ('Marqus Blakely', 69)]
Martell Webster
[('Martell Webster', 100), ('Mario West', 64)]
Marvin Williams
[('Marvin Williams', 100), ('Mo Williams', 84)]
Matt Barnes
[('Matt Barnes', 100), ('Matt Bonner', 73)]
Matt Bonner
[('Matt Bonner', 100), ('Matt Barnes', 73)]
Matt Carroll
[('Matt Carroll', 100), ('DeMarre Carroll', 74)]
Matt Janning
[('Matt Barnes', 61), ('Matt Bonner', 61)]
Maurice Ager
[('Maurice Ager', 100), ('Maurice Evans', 74)]
Maurice Evans
[('Maurice Evans', 100), ('Maurice Ager', 74)]
Mehmet Okur
[('Mehmet Okur', 100), ('Emeka Okafor', 61)]
Melvin Ely
[('Melvin Ely', 100), ('Jeremy Lin', 60)]
Michael Beasley
[('Michael Beasley', 100), ('Michael Redd', 74)]
Michael Redd
[('Michael Redd', 100), ('Michael Beasley', 74)]
Mickael Pietrus
[('Mickael Pietrus', 100), ('Mike Miller', 62)]
Mike Conley Jr.
[('Mike Conley', 100), ('Mike Dunleavy', 67)]
Mike Dunleavy Jr.
[('Mike Dunleavy', 100), ('Mike Conley', 67)]
Mike Miller
[('Mike Miller', 100), ('Andre Miller', 71)]
Mo Williams
[('Mo Williams', 100), ('Lou Williams', 87)]
Monta Ellis
[('Monta Ellis', 100), ('Jason Collins', 58)]
Morris Peterson
[('Morris Peterson', 100), ('Patrick Patterson', 62)]
Mustafa Shakur
[('Mustafa Shakur', 100), ('Samardo Samuels', 48)]
Nate Robinson
[('Nate Robinson', 100), ('James Johnson', 62)]
Nazr Mohammed
[('Nazr Mohammed', 100), ('Lazar Hayward', 54)]
Nenad Krstic
[('Nenad Krstic', 100), ('Christian Eyenga', 57)]
Nene Hilario
[('Nene', 100), ('Manny Harris', 58)]
Nick Collison
[('Nick Collison', 100), ('Darren Collison', 76)]
Nick Young
[('Nick Young', 100), ('Sam Young', 71)]
Nicolas Batum

[('Nicolas Batum', 100), ('Luis Scola', 52)]
Nikola Pekovic
[('Nikola Pekovic', 100), ('Kendrick Perkins', 53)]
O.J. Mayo
[('O.J. Mayo', 100), ('Roger Mason Jr.', 64)]
Omer Asik
[('Omer Asik', 100), ('Omri Casspi', 70)]
Omri Casspi
[('Omri Casspi', 100), ('Omer Asik', 70)]
Orien Greene
[('Orien Greene', 100), ('Donte Greene', 75)]
Othyus Jeffers
[('Othyus Jeffers', 100), ('Al Jefferson', 62)]
Pape Sy
[('Pape Sy', 100), ('James Posey', 56)]
Patrick Patterson
[('Patrick Patterson', 100), ('Patrick Ewing', 70)]
Patty Mills
[('Patty Mills', 100), ('Paul Millsap', 70)]
Paul George
[('Paul George', 100), ('Paul Pierce', 73)]
Paul Millsap
[('Paul Millsap', 100), ('Patty Mills', 70)]
Paul Pierce
[('Paul Pierce', 100), ('Paul George', 73)]
Peja Stojakovic
[('Peja Stojakovic', 100), ('Nikola Pekovic', 48)]
Pooh Jeter
[('Pooh Jeter', 100), ('Othyus Jeffers', 58)]
Pops Mensah-Bonsu
[('Pops Mensah-Bonsu', 100), ('Byron Mullens', 53)]
Quentin Richardson
[('Quentin Richardson', 100), ('Jason Richardson', 77)]
Quincy Pondexter
[('Quincy Pondexter', 100), ('Dexter Pittman', 60)]
Quinton Ross
[('Quinton Ross', 100), ('Anthony Morrow', 54)]
Raja Bell
[('Raja Bell', 100), ('Charlie Bell', 62)]
Rajon Rondo
[('Rajon Rondo', 100), ('Brandon Roy', 64)]
Randy Foye
[('Randy Foye', 100), ('Landry Fields', 61)]
Rashard Lewis
[('Rashard Lewis', 100), ('Rasual Butler', 54)]
Rasual Butler
[('Rasual Butler', 100), ('Caron Butler', 67)]
Ray Allen
[('Ray Allen', 100), ('Tony Allen', 74)]
Raymond Felton
[('Raymond Felton', 100), ('Wayne Ellington', 62)]
Reggie Evans
[('Reggie Evans', 100), ('Tyreke Evans', 75)]
Reggie Williams
[('Reggie Williams', 100), ('Mo Williams', 84)]
Renaldo Balkman
[('Renaldo Balkman', 100), ('Brian Cardinal', 55)]
Richard Hamilton
[('Richard Hamilton', 100), ('Jason Richardson', 69)]
Robert Vaden
[('Greg Oden', 57), ('Elton Brand', 52)]
Robin Lopez
[('Robin Lopez', 100), ('Brook Lopez', 73)]
Rodney Carney
[('Rodney Carney', 100), ('Rodney Stuckey', 74)]
Rodney Stuckey
[('Rodney Stuckey', 100), ('Rodney Carney', 74)]
Rodrigue Beaubois
[('Rodrigue Beaubois', 100), ('Beno Udrih', 52)]
Roger Mason Jr.
[('Roger Mason Jr.', 100), ('Greg Monroe', 64)]
Ronnie Brewer
[('Ronnie Brewer', 100), ('Corey Brewer', 72)]
Ronnie Price
[('Ronnie Price', 100), ('AJ Price', 77)]
Ronny Turiaf
[('Ronny Turiaf', 100), ('Aaron Gray', 55)]
Roy Hibbert
[('Roy Hibbert', 100), ('Royal Ivey', 57)]
Rudy Fernandez
[('Rudy Fernandez', 100), ('Rudy Gay', 67)]
Rudy Gay
[('Rudy Gay', 100), ('Rudy Fernandez', 67)]
Ryan Anderson
[('Ryan Anderson', 100), ('Anderson Varejao', 76)]
Ryan Gomes
[('Ryan Gomes', 100), ('Ryan Hollins', 64)]
Ryan Hollins
[('Ryan Hollins', 100), ('Jason Collins', 72)]
Samardo Samuels
[('Samardo Samuels', 100), ('Samuel Dalembert', 65)]
Samuel Dalembert
[('Samuel Dalembert', 100), ('Samardo Samuels', 65)]
Sasha Vujacic
[('Sasha Vujacic', 100), ('Sasha Pavlovic', 67)]
Sean Marks
[('Sean Marks', 100), ('Shawn Marion', 64)]
Sebastian Telfair
[('Sebastian Telfair', 100), ('Austin Daye', 50)]
Semih Erden
[('Semih Erden', 100), ('JR Smith', 63)]
Shaquille O'Neal
[("Shaquille O'Neal", 100), ("Jermaine O'Neal", 65)]
Shaun Livingston
[('Shaun Livingston', 100), ('Wayne Ellington', 65)]
Shawn Marion
[('Shawn Marion', 100), ('Shannon Brown', 64)]
Shawne Williams
[('Shawne Williams', 100), ('Mo Williams', 84)]
Shelden Williams
[('Shelden Williams', 100), ('Mo Williams', 84)]
Sherron Collins
[('Sherron Collins', 100), ('Jarron Collins', 83)]
Solomon Alabi
[('Solomon Alabi', 100), ('Solomon Jones', 70)]
Solomon Jones
[('Solomon Jones', 100), ('John Salmons', 72)]
Sonny Weems
[('Sonny Weems', 100), ('Wesley Johnson', 56)]
Spencer Hawes
[('Spencer Hawes', 100), ('Steve Nash', 52)]
Stephen Curry
[('Stephen Curry', 100), ('Stephen Graham', 70)]
Stephen Graham
[('Stephen Graham', 100), ('Joey Graham', 71)]
Stephen Jackson
[('Stephen Jackson', 100), ('Stephen Curry', 70)]
Steve Blake
[('Steve Blake', 100), ('Steve Novak', 73)]
Steve Nash
[('Steve Nash', 100), ('Steve Novak', 76)]
Steve Novak
[('Steve Novak', 100), ('Steve Nash', 76)]
Sundiata Gaines
[('Sundiata Gaines', 100), ('Andre Iguodala', 55)]
T.J. Ford
[('T.J. Ford', 100), ('Jamal Crawford', 55)]
Taj Gibson
[('Taj Gibson', 100), ('Daniel Gibson', 75)]
Tayshaun Prince
[('Tayshaun Prince', 100), ('Shawn Marion', 59)]
Terrence Williams
[('Terrence Williams', 100), ('Mo Williams', 84)]
Terrico White
[('DJ White', 77), ('Derrick Rose', 56)]
Thabo Sefolosha
[('Thabo Sefolosha', 100), ('Josh Smith', 48)]
Theo Ratliff
[('Theo Ratliff', 100), ('Tony Battie', 52)]
Tiago Splitter
[('Tiago Splitter', 100), ('Tony Battie', 48)]
Tim Duncan
[('Tim Duncan', 100), ('Kevin Durant', 55)]
Timofey Mozgov
[('Timofey Mozgov', 100), ('Toney Douglas', 52)]
Toney Douglas
[('Toney Douglas', 100), ('Chris Douglas-Roberts', 70)]
Tony Allen
[('Tony Allen', 100), ('Ray Allen', 74)]
Tony Battie
[('Tony Battie', 100), ('Shane Battier', 67)]
Tracy McGrady
[('Tracy McGrady', 100), ('Troy Murphy', 58)]
Trevor Ariza
[('Trevor Ariza', 100), ('Trevor Booker', 67)]
Trevor Booker
[('Trevor Booker', 100), ('Trevor Ariza', 67)]
Trey Johnson
[('Trey Johnson', 100), ('Joe Johnson', 78)]
Troy Murphy
[('Troy Murphy', 100), ('Tracy McGrady', 58)]
Ty Lawson
[('Ty Lawson', 100), ('Jason Terry', 70)]
Tyler Hansbrough
[('Tyler Hansbrough', 100), ('Jason Terry', 52)]
Tyreke Evans
[('Tyreke Evans', 100), ('Reggie Evans', 75)]
Tyrus Thomas
[('Tyrus Thomas', 100), ('Kurt Thomas', 71)]
Tyson Chandler
[('Tyson Chandler', 100), ('Wilson Chandler', 83)]
Udonis Haslem
[('Udonis Haslem', 100), ('John Salmons', 56)]
Vince Carter
[('Vince Carter', 100), ('Cartier Martin', 69)]
Von Wafer
[('Von Wafer', 100), ('Kwame Brown', 60)]
Wayne Ellington
[('Wayne Ellington', 100), ('Shaun Livingston', 65)]
Wes Johnson
[('Wesley Johnson', 88), ('James Johnson', 83)]
Will Bynum
[('Will Bynum', 100), ('Andrew Bynum', 67)]
Willie Warren
[('Willie Warren', 100), ('Willie Green', 80)]
Wilson Chandler
[('Wilson Chandler', 100), ('Tyson Chandler', 83)]
Xavier Henry
[('Xavier Henry', 100), ('Henry Walker', 75)]
Yao Ming
[('Yao Ming', 100), ('Keyon Dooling', 57)]
Zabian Dowdell
[('Zabian Dowdell', 100), ('Joel Przybilla', 57)]
Zach Randolph
[('Zach Randolph', 100), ('Anthony Randolph', 76)]
Zaza Pachulia
[('Zaza Pachulia', 100), ('Sasha Pavlovic', 52)]
Zydrunas Ilgauskas
[('Zydrunas Ilgauskas', 100), ('DeMarcus Cousins', 47)]

In [132]:
i = 0
for player_ in sorted(unique_player):
    print(player_)
    if((process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] != 100) & (process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] > 90)):
        print('*****************************************')
        print(i)
        i = i + 1
    print(process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][:2])

print(i - 1)

 Tony Parker
('Tony Parker', 100)
A.J. Price
*****************************************
0
('AJ Price', 94)
Aaron Brooks
('Aaron Brooks', 100)
Aaron Gray
('Aaron Gray', 100)
Acie Law
('Acie Law', 100)
Al Harrington
('Al Harrington', 100)
Al Horford
('Al Horford', 100)
Al Thornton
('Al Thornton', 100)
Alex Ajinca
*****************************************
1
('Alexis Ajinca', 92)
Alonzo Gee
('Alonzo Gee', 100)
Amar'e Stoudemire
("Amar'e Stoudemire", 100)
Amir Johnson
('Amir Johnson', 100)
Anderson Varejao
('Anderson Varejao', 100)
Andray Blatche
('Andray Blatche', 100)
Andre Iguodala
('Andre Iguodala', 100)
Andrea Bargnani
('Andrea Bargnani', 100)
Andrei Kirilenko
('Andrei Kirilenko', 100)
Andres Nocioni
('Andres Nocioni', 100)
Andrew Bogut
('Andrew Bogut', 100)
Andrew Bynum
('Andrew Bynum', 100)
Andris Biedrins
('Andris Biedrins', 100)
Andy Rautins
('Andy Rautins', 100)
Antawn Jamison
('Antawn Jamison', 100)
Anthony Carter
('Anthony Carter', 100)
Anthony Morrow
('Anthony Morrow', 100)
Anthony Parker
('Anthony Parker', 100)
Anthony Randolph
('Anthony Randolph', 100)
Anthony Tolliver
('Anthony Tolliver', 100)
Antoine Wright
('Antoine Wright', 100)
Antonio McDyess
('Antonio McDyess', 100)
Armon Johnson
('Armon Johnson', 100)
Arron Afflalo
('Arron Afflalo', 100)
Austin Daye
('Austin Daye', 100)
Avery Bradley
('Avery Bradley', 100)
B.J. Mullens
('Byron Mullens', 78)
Baron Davis
('Baron Davis', 100)
Ben Uzoh
('Ben Uzoh', 100)
Ben Wallace
('Ben Wallace', 100)
Beno Udrih
('Beno Udrih', 100)
Bill Walker
('Henry Walker', 71)
Brad Miller
('Brad Miller', 100)
Brandan Wright
('Brandan Wright', 100)
Brandon Bass
('Brandon Bass', 100)
Brandon Jennings
('Brandon Jennings', 100)
Brandon Roy
('Brandon Roy', 100)
Brandon Rush
('Brandon Rush', 100)
Brendan Haywood
('Brendan Haywood', 100)
Brian Cardinal
('Brian Cardinal', 100)
Brian Cook
('Brian Cook', 100)
Brian Scalabrine
('Brian Scalabrine', 100)
Brian Skinner
('Brian Skinner', 100)
C.J. Miles
*****************************************
2
('CJ Miles', 94)
Carlos Arroyo
('Carlos Arroyo', 100)
Carlos Boozer
('Carlos Boozer', 100)
Carlos Delfino
('Carlos Delfino', 100)
Carmelo Anthony
('Carmelo Anthony', 100)
Caron Butler
('Caron Butler', 100)
Cartier Martin
('Cartier Martin', 100)
Channing Frye
('Channing Frye', 100)
Charlie Bell
('Charlie Bell', 100)
Charlie Villanueva
('Charlie Villanueva', 100)
Chase Budinger
('Chase Budinger', 100)
Chauncey Billups
('Chauncey Billups', 100)
Chris Andersen
('Chris Andersen', 100)
Chris Bosh
('Chris Bosh', 100)
Chris Douglas-Roberts
('Chris Douglas-Roberts', 100)
Chris Duhon
('Chris Duhon', 100)
Chris Kaman
('Chris Kaman', 100)
Chris Paul
('Chris Paul', 100)
Chris Quinn
('Chris Quinn', 100)
Chris Wilcox
('Chris Wilcox', 100)
Christian Eyenga
('Christian Eyenga', 100)
Chuck Hayes
('Chuck Hayes', 100)
Cole Aldrich
('Cole Aldrich', 100)
Corey Brewer
('Corey Brewer', 100)
Corey Maggette
('Corey Maggette', 100)
Courtney Lee
('Courtney Lee', 100)
Craig Brackins
('Craig Brackins', 100)
Craig Smith
('Craig Smith', 100)
D.J. White
*****************************************
3
('DJ White', 94)
Da'Sean Butler
('Rasual Butler', 74)
DaJuan Summers
('DaJuan Summers', 100)
Daequan Cook
('Daequan Cook', 100)
Dahntay Jones
('Dahntay Jones', 100)
Damien Wilkins
('Damien Wilkins', 100)
Damion James
('Damion James', 100)
Dan Gadzuric
('Dan Gadzuric', 100)
Daniel Gibson
('Daniel Gibson', 100)
Daniel Orton
('Daniel Gibson', 72)
Danilo Gallinari
('Danilo Gallinari', 100)
Danny Granger
('Danny Granger', 100)
Danny Green
('Danny Green', 100)
Dante Cunningham
('Dante Cunningham', 100)
Darius Songaila
('Darius Songaila', 100)
Darko Milicic
('Darko Milicic', 100)
Darrell Arthur
('Darrell Arthur', 100)
Darren Collison
('Darren Collison', 100)
David Andersen
('David Andersen', 100)
David Lee
('David Lee', 100)
David West
('David West', 100)
DeAndre Jordan
('DeAndre Jordan', 100)
DeJuan Blair
('DeJuan Blair', 100)
DeMarre Carroll
('DeMarre Carroll', 100)
DeSagana Diop
('DeSagana Diop', 100)
Delonte West
('Delonte West', 100)
Deron Williams
('Deron Williams', 100)
Derrick Brown
('Derrick Brown', 100)
Derrick Caracter
('Derrick Caracter', 100)
Derrick Favors
('Derrick Favors', 100)
Derrick Rose
('Derrick Rose', 100)
Devin Ebanks
('Devin Ebanks', 100)
Devin Harris
('Devin Harris', 100)
Dexter Pittman
('Dexter Pittman', 100)
Didier Mbenga
('DJ Mbenga', 80)
Dirk Nowitzki
('Dirk Nowitzki', 100)
Dominic McGuire
('Dominic McGuire', 100)
Dominique Jones
('Dominique Jones', 100)
Drew Gooden
('Drew Gooden', 100)
Dwight Howard
('Dwight Howard', 100)
Dwyane Wade
('Dwyane Wade', 100)
Ed Davis
('Ed Davis', 100)
Eddy Curry
('Stephen Curry', 67)
Eduardo Najera
('Eduardo Najera', 100)
Ekpe Udoh
('Ekpe Udoh', 100)
Elliot Williams
('Elliot Williams', 100)
Eric Gordon
('Eric Gordon', 100)
Erick Dampier
('Erick Dampier', 100)
Ersan Ilyasova
('Ersan Ilyasova', 100)
Etan Thomas
('Etan Thomas', 100)
Francisco Elson
('Francisco Elson', 100)
Francisco Garcia
('Francisco Garcia', 100)
Gani Lawal
('Gani Lawal', 100)
Garret Siler
('Garret Siler', 100)
Garrett Temple
('Garrett Temple', 100)
Gary Neal
('Gary Neal', 100)
George Hill
('George Hill', 100)
Gerald Henderson Jr.
('Gerald Henderson', 100)
Gerald Wallace
('Gerald Wallace', 100)
Gilbert Arenas
('Gilbert Arenas', 100)
Glen Davis
('Glen Davis', 100)
Goran Dragic
('Goran Dragic', 100)
Gordon Hayward
('Gordon Hayward', 100)
Grant Hill
('Grant Hill', 100)
Greg Oden
('Greg Oden', 100)
Greivis Vasquez
('Greivis Vasquez', 100)
Hamady N'Diaye
('Hamady Ndiaye', 89)
Hamed Haddadi
('Hamed Haddadi', 100)
Hasheem Thabeet
('Hasheem Thabeet', 100)
Hassan Whiteside
('Hassan Whiteside', 100)
Hilton Armstrong
('Hilton Armstrong', 100)
Ian Mahinmi
('Ian Mahinmi', 100)
Ish Smith
('Ish Smith', 100)
J.J. Hickson
*****************************************
4
('JJ Hickson', 95)
J.J. Redick
*****************************************
5
('JJ Redick', 94)
JaVale McGee
('JaVale McGee', 100)
Jamaal Magloire
('Jamaal Magloire', 100)
Jamal Crawford
('Jamal Crawford', 100)
Jamario Moon
('Jamario Moon', 100)
Jameer Nelson
('Jameer Nelson', 100)
James Anderson
('James Anderson', 100)
James Posey
('James Posey', 100)
Jannero Pargo
('Anderson Varejao', 62)
Jared Jeffries
('Jared Jeffries', 100)
Jason Collins
('Jason Collins', 100)
Jason Kapono
('Jason Kapono', 100)
Jason Kidd
('Jason Kidd', 100)
Jason Maxiell
('Jason Maxiell', 100)
Jason Richardson
('Jason Richardson', 100)
Jason Smith
('Jason Smith', 100)
Jason Thompson
('Jason Thompson', 100)
Jason Williams
('Jason Williams', 100)
Jeff Adrien
('Jeff Adrien', 100)
Jeff Foster
('Jeff Foster', 100)
Jeff Green
('Jeff Green', 100)
Jeremy Evans
('Jeremy Evans', 100)
Jeremy Lin
('Jeremy Lin', 100)
Jermaine O'Neal
("Jermaine O'Neal", 100)
Jermaine Taylor
('Jermaine Taylor', 100)
Jerry Stackhouse
('Jerry Stackhouse', 100)
Jerryd Bayless
('Jerryd Bayless', 100)
Jianlian Yi
('Yi Jianlian', 100)
Joakim Noah
('Joakim Noah', 100)
Jodie Meeks
('Jodie Meeks', 100)
Joe Alexander
('Jose Calderon', 69)
Joe Johnson
('Joe Johnson', 100)
Joe Smith
('Joe Smith', 100)
Joel Przybilla
('Joel Przybilla', 100)
Joey Dorsey
('Joey Dorsey', 100)
Joey Graham
('Joey Graham', 100)
John Lucas III
('John Lucas III', 100)
John Salmons
('John Salmons', 100)
John Wall
('John Wall', 100)
John Wallace
('John Wall', 86)
Jon Brockman
('Jon Brockman', 100)
Jonas Jerebko
('James Jones', 58)
Jonny Flynn
('Jonny Flynn', 100)
Jordan Crawford
('Jordan Crawford', 100)
Jordan Farmar
('Jordan Farmar', 100)
Jordan Hill
('Jordan Hill', 100)
Jose Barea
('J.J. Barea', 83)
Jose Calderon
('Jose Calderon', 100)
Josh Howard
('Josh Howard', 100)
Josh McRoberts
('Josh McRoberts', 100)
Josh Powell
('Josh Powell', 100)
Josh Smith
('Josh Smith', 100)
Julian Wright
('Julian Wright', 100)
Juwan Howard
('Juwan Howard', 100)
Kelenna Azubuike
('Acie Law', 50)
Kendrick Perkins
('Kendrick Perkins', 100)
Kenyon Martin
('Kenyon Martin', 100)
Kevin Durant
('Kevin Durant', 100)
Kevin Garnett
('Kevin Garnett', 100)
Kevin Love
('Kevin Love', 100)
Kevin Martin
('Kevin Martin', 100)
Kevin Seraphin
('Kevin Seraphin', 100)
Keyon Dooling
('Keyon Dooling', 100)
Kirk Hinrich
('Kirk Hinrich', 100)
Kosta Koufos
('Kosta Koufos', 100)
Kris Humphries
('Kris Humphries', 100)
Kurt Thomas
('Kurt Thomas', 100)
Kwame Brown

('Kwame Brown', 100)
Kyle Lowry
('Kyle Lowry', 100)
Kyrylo Fesenko
('Kyrylo Fesenko', 100)
LaMarcus Aldridge
('LaMarcus Aldridge', 100)
Lance Stephenson
('Lance Stephenson', 100)
Larry Sanders
('Larry Sanders', 100)
Lazar Hayward
('Lazar Hayward', 100)
LeBron James
('LeBron James', 100)
Leandro Barbosa
('Leandro Barbosa', 100)
Leon Powe
('Leon Powe', 100)
Lester Hudson
('Lester Hudson', 100)
Linas Kleiza
('Linas Kleiza', 100)
Lou Amundson
('Lou Amundson', 100)
Lou Williams
('Lou Williams', 100)
Luc Mbah a Moute
('Luc Mbah a Moute', 100)
Luis Scola
('Luis Scola', 100)
Luke Babbitt
('Luke Babbitt', 100)
Luke Harangody
('Luke Harangody', 100)
Luke Ridnour
('Luke Ridnour', 100)
Luke Walton
('Luke Walton', 100)
Luther Head
('Luther Head', 100)
Magnum Rolle
('Will Bynum', 55)
Malik Allen
('Malik Allen', 100)
Manny Harris
('Manny Harris', 100)
Manu Ginobili
('Manu Ginobili', 100)
Marc Gasol
('Marc Gasol', 100)
Marco Belinelli
('Marco Belinelli', 100)
Marcus Banks
('Marcus Banks', 100)
Marcus Camby
('Marcus Camby', 100)
Marcus Thornton
('Marcus Thornton', 100)
Mario Chalmers
('Mario Chalmers', 100)
Mario West
('Mario West', 100)
Marquis Daniels
('Marquis Daniels', 100)
Martell Webster
('Martell Webster', 100)
Marvin Williams
('Marvin Williams', 100)
Matt Barnes
('Matt Barnes', 100)
Matt Bonner
('Matt Bonner', 100)
Matt Carroll
('Matt Carroll', 100)
Matt Janning
('Matt Barnes', 61)
Maurice Ager
('Maurice Ager', 100)
Maurice Evans
('Maurice Evans', 100)
Mehmet Okur
('Mehmet Okur', 100)
Melvin Ely
('Melvin Ely', 100)
Michael Beasley
('Michael Beasley', 100)
Michael Redd
('Michael Redd', 100)
Mickael Pietrus
('Mickael Pietrus', 100)
Mike Conley Jr.
('Mike Conley', 100)
Mike Dunleavy Jr.
('Mike Dunleavy', 100)
Mike Miller
('Mike Miller', 100)
Mo Williams
('Mo Williams', 100)
Monta Ellis
('Monta Ellis', 100)
Morris Peterson
('Morris Peterson', 100)
Mustafa Shakur
('Mustafa Shakur', 100)
Nate Robinson
('Nate Robinson', 100)
Nazr Mohammed
('Nazr Mohammed', 100)
Nenad Krstic
('Nenad Krstic', 100)
Nene Hilario
('Nene', 100)
Nick Collison
('Nick Collison', 100)
Nick Young
('Nick Young', 100)
Nicolas Batum
('Nicolas Batum', 100)
Nikola Pekovic
('Nikola Pekovic', 100)
O.J. Mayo
('O.J. Mayo', 100)
Omer Asik
('Omer Asik', 100)
Omri Casspi
('Omri Casspi', 100)
Orien Greene
('Orien Greene', 100)
Othyus Jeffers
('Othyus Jeffers', 100)
Pape Sy
('Pape Sy', 100)
Patrick Patterson
('Patrick Patterson', 100)
Patty Mills
('Patty Mills', 100)
Paul George
('Paul George', 100)
Paul Millsap
('Paul Millsap', 100)
Paul Pierce
('Paul Pierce', 100)
Peja Stojakovic
('Peja Stojakovic', 100)
Pooh Jeter
('Pooh Jeter', 100)
Pops Mensah-Bonsu
('Pops Mensah-Bonsu', 100)
Quentin Richardson
('Quentin Richardson', 100)
Quincy Pondexter
('Quincy Pondexter', 100)
Quinton Ross
('Quinton Ross', 100)
Raja Bell
('Raja Bell', 100)
Rajon Rondo
('Rajon Rondo', 100)
Randy Foye
('Randy Foye', 100)
Rashard Lewis
('Rashard Lewis', 100)
Rasual Butler
('Rasual Butler', 100)
Ray Allen
('Ray Allen', 100)
Raymond Felton
('Raymond Felton', 100)
Reggie Evans
('Reggie Evans', 100)
Reggie Williams
('Reggie Williams', 100)
Renaldo Balkman
('Renaldo Balkman', 100)
Richard Hamilton
('Richard Hamilton', 100)
Robert Vaden
('Greg Oden', 57)
Robin Lopez
('Robin Lopez', 100)
Rodney Carney
('Rodney Carney', 100)
Rodney Stuckey
('Rodney Stuckey', 100)
Rodrigue Beaubois
('Rodrigue Beaubois', 100)
Roger Mason Jr.
('Roger Mason Jr.', 100)
Ronnie Brewer
('Ronnie Brewer', 100)
Ronnie Price
('Ronnie Price', 100)
Ronny Turiaf
('Ronny Turiaf', 100)
Roy Hibbert
('Roy Hibbert', 100)
Rudy Fernandez
('Rudy Fernandez', 100)
Rudy Gay
('Rudy Gay', 100)
Ryan Anderson
('Ryan Anderson', 100)
Ryan Gomes
('Ryan Gomes', 100)
Ryan Hollins
('Ryan Hollins', 100)
Samardo Samuels
('Samardo Samuels', 100)
Samuel Dalembert
('Samuel Dalembert', 100)
Sasha Vujacic
('Sasha Vujacic', 100)
Sean Marks
('Sean Marks', 100)
Sebastian Telfair
('Sebastian Telfair', 100)
Semih Erden
('Semih Erden', 100)
Shaquille O'Neal
("Shaquille O'Neal", 100)
Shaun Livingston
('Shaun Livingston', 100)
Shawn Marion
('Shawn Marion', 100)
Shawne Williams
('Shawne Williams', 100)
Shelden Williams
('Shelden Williams', 100)
Sherron Collins
('Sherron Collins', 100)
Solomon Alabi
('Solomon Alabi', 100)
Solomon Jones
('Solomon Jones', 100)
Sonny Weems
('Sonny Weems', 100)
Spencer Hawes
('Spencer Hawes', 100)
Stephen Curry
('Stephen Curry', 100)
Stephen Graham
('Stephen Graham', 100)
Stephen Jackson
('Stephen Jackson', 100)
Steve Blake
('Steve Blake', 100)
Steve Nash
('Steve Nash', 100)
Steve Novak
('Steve Novak', 100)
Sundiata Gaines
('Sundiata Gaines', 100)
T.J. Ford
('T.J. Ford', 100)
Taj Gibson
('Taj Gibson', 100)
Tayshaun Prince
('Tayshaun Prince', 100)
Terrence Williams
('Terrence Williams', 100)
Terrico White
('DJ White', 77)
Thabo Sefolosha
('Thabo Sefolosha', 100)
Theo Ratliff
('Theo Ratliff', 100)
Tiago Splitter
('Tiago Splitter', 100)
Tim Duncan
('Tim Duncan', 100)
Timofey Mozgov
('Timofey Mozgov', 100)
Toney Douglas
('Toney Douglas', 100)
Tony Allen
('Tony Allen', 100)
Tony Battie
('Tony Battie', 100)
Tracy McGrady
('Tracy McGrady', 100)
Trevor Ariza
('Trevor Ariza', 100)
Trevor Booker
('Trevor Booker', 100)
Trey Johnson
('Trey Johnson', 100)
Troy Murphy
('Troy Murphy', 100)
Ty Lawson
('Ty Lawson', 100)
Tyler Hansbrough
('Tyler Hansbrough', 100)
Tyreke Evans
('Tyreke Evans', 100)
Tyrus Thomas
('Tyrus Thomas', 100)
Tyson Chandler
('Tyson Chandler', 100)
Udonis Haslem
('Udonis Haslem', 100)
Vince Carter
('Vince Carter', 100)
Von Wafer
('Von Wafer', 100)
Wayne Ellington
('Wayne Ellington', 100)
Wes Johnson
('Wesley Johnson', 88)
Will Bynum
('Will Bynum', 100)
Willie Warren
('Willie Warren', 100)
Wilson Chandler
('Wilson Chandler', 100)
Xavier Henry
('Xavier Henry', 100)
Yao Ming
('Yao Ming', 100)
Zabian Dowdell
('Zabian Dowdell', 100)
Zach Randolph
('Zach Randolph', 100)
Zaza Pachulia
('Zaza Pachulia', 100)
Zydrunas Ilgauskas
('Zydrunas Ilgauskas', 100)
5

In [133]:
df_inj3[df_inj3.player == 'J.J. Hickson']

     game_date       Team     team_id        player   game_id
338 2010-12-04  Cavaliers  1610612739  J.J. Hickson  21000291

In [134]:
df_inj3[df_inj3.player == 'J.J. Redick']

      game_date   Team     team_id       player   game_id
206  2010-11-15  Magic  1610612753  J.J. Redick  21000145
314  2010-12-01  Magic  1610612753  J.J. Redick  21000266
331  2010-12-03  Magic  1610612753  J.J. Redick  21000279
341  2010-12-04  Magic  1610612753  J.J. Redick  21000292
870  2011-01-31  Magic  1610612753  J.J. Redick  21000711
1210 2011-03-11  Magic  1610612753  J.J. Redick  21000975
1254 2011-03-16  Magic  1610612753  J.J. Redick  21001007
1262 2011-03-18  Magic  1610612753  J.J. Redick  21001018
1293 2011-03-21  Magic  1610612753  J.J. Redick  21001044
1306 2011-03-23  Magic  1610612753  J.J. Redick  21001059
1325 2011-03-25  Magic  1610612753  J.J. Redick  21001069
1356 2011-03-28  Magic  1610612753  J.J. Redick  21000051
1378 2011-03-30  Magic  1610612753  J.J. Redick  21001105
1405 2011-04-01  Magic  1610612753  J.J. Redick  21001121
1428 2011-04-03  Magic  1610612753  J.J. Redick  21001144
1452 2011-04-05  Magic  1610612753  J.J. Redick  21001152
1467 2011-04-06  Magic  1610612753  J.J. Redick  21001162
1523 2011-04-10  Magic  1610612753  J.J. Redick  21001193
1549 2011-04-11  Magic  1610612753  J.J. Redick  21001204
1613 2011-04-13  Magic  1610612753  J.J. Redick  21001219

In [135]:
df_or1011a[df_or1011a.PLAYER_NAME == 'J.J. Redick']

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [136]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('J.J. Redick')]

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [137]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('JJ Redick')].sort_values(by='game_date')

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
402    21000017  1610612753.0   JJ Redick          95.4 2010-10-28   95.400000
581    21000025  1610612753.0   JJ Redick          90.3 2010-10-29   92.850000
1341   21000056  1610612753.0   JJ Redick         142.8 2010-11-03  109.500000
1653   21000069  1610612753.0   JJ Redick         107.5 2010-11-05  109.000000
1905   21000080  1610612753.0   JJ Redick          61.5 2010-11-06   99.500000
2299   21000096  1610612753.0   JJ Redick          94.1 2010-11-08   98.600000
2613   21000109  1610612753.0   JJ Redick          58.9 2010-11-10   92.928571
2944   21000123  1610612753.0   JJ Redick         103.5 2010-11-12   94.250000
3128   21000131  1610612753.0   JJ Redick          88.0 2010-11-13   93.555556
4376   21000183  1610612753.0   JJ Redick          82.6 2010-11-20   92.460000
4755   21000199  1610612753.0   JJ Redick         113.4 2010-11-22   94.363636
5101   21000213  1610612753.0   JJ Redick         115.4 2010-11-24   96.116667
5341   21000223  1610612753.0   JJ Redick         112.6 2010-11-26   97.384615
5617   21000235  1610612753.0   JJ Redick         120.2 2010-11-27   99.014286
6113   21000255  1610612753.0   JJ Redick         121.3 2010-11-30  100.500000
6681   21000279  1610612753.0   JJ Redick           NaN 2010-12-03  100.500000
6993   21000292  1610612753.0   JJ Redick           NaN 2010-12-04  100.500000
7264   21000303  1610612753.0   JJ Redick          86.7 2010-12-06   99.637500
7878   21000329  1610612753.0   JJ Redick          95.2 2010-12-09   99.376471
8117   21000339  1610612753.0   JJ Redick         105.8 2010-12-10   99.733333
8478   21000354  1610612753.0   JJ Redick         103.4 2010-12-12   99.926316
8740   21000365  1610612753.0   JJ Redick         104.2 2010-12-14  100.140000
9397   21000392  1610612753.0   JJ Redick          92.0 2010-12-18   99.752381
9725   21000406  1610612753.0   JJ Redick          56.6 2010-12-20   97.790909
9971   21000416  1610612753.0   JJ Redick         123.1 2010-12-21   98.891304
10309  21000430  1610612753.0   JJ Redick         107.3 2010-12-23   99.241667
10406  21000434  1610612753.0   JJ Redick         103.8 2010-12-25   99.424000
10682  21000446  1610612753.0   JJ Redick         114.1 2010-12-27   99.988462
10898  21000455  1610612753.0   JJ Redick         104.1 2010-12-28  100.140741
11342  21000473  1610612753.0   JJ Redick         122.0 2010-12-30  100.921429
11989  21000500  1610612753.0   JJ Redick         117.6 2011-01-03  101.496552
12326  21000514  1610612753.0   JJ Redick         102.1 2011-01-05  101.516667
12681  21000529  1610612753.0   JJ Redick          98.4 2011-01-07  101.416129
12978  21000542  1610612753.0   JJ Redick         106.6 2011-01-08  101.578125
13571  21000567  1610612753.0   JJ Redick          89.3 2011-01-12  101.206061
13741  21000574  1610612753.0   JJ Redick         145.3 2011-01-13  102.502941
14193  21000593  1610612753.0   JJ Redick          97.3 2011-01-15  102.354286
14553  21000608  1610612753.0   JJ Redick         117.3 2011-01-17  102.769444
14734  21000615  1610612753.0   JJ Redick         103.4 2011-01-19  102.786486
15092  21000630  1610612753.0   JJ Redick         123.5 2011-01-21  103.331579
15513  21000648  1610612753.0   JJ Redick         117.9 2011-01-22  103.705128
15670  21000654  1610612753.0   JJ Redick         116.4 2011-01-24  104.022500
15993  21000668  1610612753.0   JJ Redick         119.0 2011-01-26  104.387805
16449  21000687  1610612753.0   JJ Redick          96.9 2011-01-28  104.209524
16844  21000703  1610612753.0   JJ Redick         105.0 2011-01-30  104.227907
17030  21000711  1610612753.0   JJ Redick           NaN 2011-01-31  104.227907
17497  21000730  1610612753.0   JJ Redick          91.9 2011-02-03  103.947727
17650  21000737  1610612753.0   JJ Redick          91.7 2011-02-04  103.675556
18128  21000757  1610612753.0   JJ Redick          76.4 2011-02-06  103.082609
18378  21000767  1610612753.0   JJ Redick         116.5 2011-02-08  103.368085
18583  21000776  1610612753.0   JJ Redick         100.1 2011-02-09  103.300000
18881  21000788  1610612753.0   JJ Redick          85.2 2011-02-11  102.930612
19290  21000805  1610612753.0   JJ Redick          91.9 2011-02-13  102.710000
19743  21000824  1610612753.0   JJ Redick         114.5 2011-02-16  102.941176
20344  21000849  1610612753.0   JJ Redick         106.0 2011-02-23  103.000000
20772  21000867  1610612753.0   JJ Redick         120.7 2011-02-25  103.333962
21155  21000883  1610612753.0   JJ Redick         119.9 2011-02-27  103.640741
21440  21000895  1610612753.0   JJ Redick         106.9 2011-03-01  103.700000
21837  21000912  1610612753.0   JJ Redick          98.0 2011-03-03  103.598214
21923  21000915  1610612753.0   JJ Redick          94.4 2011-03-04  103.436842
22544  21000941  1610612753.0   JJ Redick          98.3 2011-03-07  103.348276
23058  21000963  1610612753.0   JJ Redick          80.6 2011-03-09  102.962712
23349  21000975  1610612753.0   JJ Redick           NaN 2011-03-11  102.962712
23635  21000987  1610612753.0   JJ Redick           NaN 2011-03-13  102.962712
23923  21000999  1610612753.0   JJ Redick           NaN 2011-03-14  102.962712
24115  21001007  1610612753.0   JJ Redick           NaN 2011-03-16  102.962712
24391  21001018  1610612753.0   JJ Redick           NaN 2011-03-18  102.962712
25003  21001044  1610612753.0   JJ Redick           NaN 2011-03-21  102.962712
25362  21001059  1610612753.0   JJ Redick           NaN 2011-03-23  102.962712
25613  21001069  1610612753.0   JJ Redick           NaN 2011-03-25  102.962712
1210   21000051  1610612753.0   JJ Redick           NaN 2011-03-28   92.850000
26463  21001105  1610612753.0   JJ Redick           NaN 2011-03-30  102.962712
26860  21001121  1610612753.0   JJ Redick           NaN 2011-04-01  102.962712
27399  21001144  1610612753.0   JJ Redick           NaN 2011-04-03  102.962712
27603  21001152  1610612753.0   JJ Redick           NaN 2011-04-05  102.962712
27830  21001162  1610612753.0   JJ Redick           NaN 2011-04-06  102.962712
28585  21001193  1610612753.0   JJ Redick           NaN 2011-04-10  102.962712
28837  21001204  1610612753.0   JJ Redick           NaN 2011-04-11  102.962712
29210  21001219  1610612753.0   JJ Redick           NaN 2011-04-13  102.962712
29830  41000131  1610612753.0   JJ Redick         141.0 2011-04-16  103.596667
29855  41000132  1610612753.0   JJ Redick         119.9 2011-04-19  103.863934
29864  41000133  1610612753.0   JJ Redick          96.4 2011-04-22  103.743548
29888  41000134  1610612753.0   JJ Redick          89.5 2011-04-24  103.517460
29926  41000135  1610612753.0   JJ Redick         115.1 2011-04-26  103.698437
29937  41000136  1610612753.0   JJ Redick          92.5 2011-04-28  103.526154

In [138]:
#<>><><><><><><><><><><<><><><><><><><><><<><><><><><><><><><<><><><><><><><><><<><><><><><><><><><><><><<><><><><><><><><><<><><><><><><><><>

<font color='red'> will go with no dots version of name as in nba_api<font>

In [139]:
df_inj3[df_inj3.player == 'J.J. Redick']

      game_date   Team     team_id       player   game_id
206  2010-11-15  Magic  1610612753  J.J. Redick  21000145
314  2010-12-01  Magic  1610612753  J.J. Redick  21000266
331  2010-12-03  Magic  1610612753  J.J. Redick  21000279
341  2010-12-04  Magic  1610612753  J.J. Redick  21000292
870  2011-01-31  Magic  1610612753  J.J. Redick  21000711
1210 2011-03-11  Magic  1610612753  J.J. Redick  21000975
1254 2011-03-16  Magic  1610612753  J.J. Redick  21001007
1262 2011-03-18  Magic  1610612753  J.J. Redick  21001018
1293 2011-03-21  Magic  1610612753  J.J. Redick  21001044
1306 2011-03-23  Magic  1610612753  J.J. Redick  21001059
1325 2011-03-25  Magic  1610612753  J.J. Redick  21001069
1356 2011-03-28  Magic  1610612753  J.J. Redick  21000051
1378 2011-03-30  Magic  1610612753  J.J. Redick  21001105
1405 2011-04-01  Magic  1610612753  J.J. Redick  21001121
1428 2011-04-03  Magic  1610612753  J.J. Redick  21001144
1452 2011-04-05  Magic  1610612753  J.J. Redick  21001152
1467 2011-04-06  Magic  1610612753  J.J. Redick  21001162
1523 2011-04-10  Magic  1610612753  J.J. Redick  21001193
1549 2011-04-11  Magic  1610612753  J.J. Redick  21001204
1613 2011-04-13  Magic  1610612753  J.J. Redick  21001219

In [140]:
df_inj3.player.replace({'J.J. Redick':'JJ Redick'}, inplace=True)

In [141]:
df_inj3[df_inj3.player.str.contains('J.J. Redick')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [142]:
df_inj3[df_inj3.player.str.contains('JJ Redick')]

      game_date   Team     team_id     player   game_id
206  2010-11-15  Magic  1610612753  JJ Redick  21000145
314  2010-12-01  Magic  1610612753  JJ Redick  21000266
331  2010-12-03  Magic  1610612753  JJ Redick  21000279
341  2010-12-04  Magic  1610612753  JJ Redick  21000292
870  2011-01-31  Magic  1610612753  JJ Redick  21000711
1210 2011-03-11  Magic  1610612753  JJ Redick  21000975
1254 2011-03-16  Magic  1610612753  JJ Redick  21001007
1262 2011-03-18  Magic  1610612753  JJ Redick  21001018
1293 2011-03-21  Magic  1610612753  JJ Redick  21001044
1306 2011-03-23  Magic  1610612753  JJ Redick  21001059
1325 2011-03-25  Magic  1610612753  JJ Redick  21001069
1356 2011-03-28  Magic  1610612753  JJ Redick  21000051
1378 2011-03-30  Magic  1610612753  JJ Redick  21001105
1405 2011-04-01  Magic  1610612753  JJ Redick  21001121
1428 2011-04-03  Magic  1610612753  JJ Redick  21001144
1452 2011-04-05  Magic  1610612753  JJ Redick  21001152
1467 2011-04-06  Magic  1610612753  JJ Redick  21001162
1523 2011-04-10  Magic  1610612753  JJ Redick  21001193
1549 2011-04-11  Magic  1610612753  JJ Redick  21001204
1613 2011-04-13  Magic  1610612753  JJ Redick  21001219

In [143]:
i = 0
for player_ in sorted(unique_player):
    print(player_)
    if((process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] != 100) & (process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] > 85)):
        print('*****************************************')
        print(i)
        i = i + 1
    print(process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][:2])

print(i - 1)

 Tony Parker
('Tony Parker', 100)
A.J. Price
*****************************************
0
('AJ Price', 94)
Aaron Brooks
('Aaron Brooks', 100)
Aaron Gray
('Aaron Gray', 100)
Acie Law
('Acie Law', 100)
Al Harrington
('Al Harrington', 100)
Al Horford
('Al Horford', 100)
Al Thornton
('Al Thornton', 100)
Alex Ajinca
*****************************************
1
('Alexis Ajinca', 92)
Alonzo Gee
('Alonzo Gee', 100)
Amar'e Stoudemire
("Amar'e Stoudemire", 100)
Amir Johnson
('Amir Johnson', 100)
Anderson Varejao
('Anderson Varejao', 100)
Andray Blatche
('Andray Blatche', 100)
Andre Iguodala
('Andre Iguodala', 100)
Andrea Bargnani
('Andrea Bargnani', 100)
Andrei Kirilenko
('Andrei Kirilenko', 100)
Andres Nocioni
('Andres Nocioni', 100)
Andrew Bogut
('Andrew Bogut', 100)
Andrew Bynum
('Andrew Bynum', 100)
Andris Biedrins
('Andris Biedrins', 100)
Andy Rautins
('Andy Rautins', 100)
Antawn Jamison
('Antawn Jamison', 100)
Anthony Carter
('Anthony Carter', 100)
Anthony Morrow
('Anthony Morrow', 100)
Anthony Parker
('Anthony Parker', 100)
Anthony Randolph
('Anthony Randolph', 100)
Anthony Tolliver
('Anthony Tolliver', 100)
Antoine Wright
('Antoine Wright', 100)
Antonio McDyess
('Antonio McDyess', 100)
Armon Johnson
('Armon Johnson', 100)
Arron Afflalo
('Arron Afflalo', 100)
Austin Daye
('Austin Daye', 100)
Avery Bradley
('Avery Bradley', 100)
B.J. Mullens
('Byron Mullens', 78)
Baron Davis
('Baron Davis', 100)
Ben Uzoh
('Ben Uzoh', 100)
Ben Wallace
('Ben Wallace', 100)
Beno Udrih
('Beno Udrih', 100)
Bill Walker
('Henry Walker', 71)
Brad Miller
('Brad Miller', 100)
Brandan Wright
('Brandan Wright', 100)
Brandon Bass
('Brandon Bass', 100)
Brandon Jennings
('Brandon Jennings', 100)
Brandon Roy
('Brandon Roy', 100)
Brandon Rush
('Brandon Rush', 100)
Brendan Haywood
('Brendan Haywood', 100)
Brian Cardinal
('Brian Cardinal', 100)
Brian Cook
('Brian Cook', 100)
Brian Scalabrine
('Brian Scalabrine', 100)
Brian Skinner
('Brian Skinner', 100)
C.J. Miles
*****************************************
2
('CJ Miles', 94)
Carlos Arroyo
('Carlos Arroyo', 100)
Carlos Boozer
('Carlos Boozer', 100)
Carlos Delfino
('Carlos Delfino', 100)
Carmelo Anthony
('Carmelo Anthony', 100)
Caron Butler
('Caron Butler', 100)
Cartier Martin
('Cartier Martin', 100)
Channing Frye
('Channing Frye', 100)
Charlie Bell
('Charlie Bell', 100)
Charlie Villanueva
('Charlie Villanueva', 100)
Chase Budinger
('Chase Budinger', 100)
Chauncey Billups
('Chauncey Billups', 100)
Chris Andersen
('Chris Andersen', 100)
Chris Bosh
('Chris Bosh', 100)
Chris Douglas-Roberts
('Chris Douglas-Roberts', 100)
Chris Duhon
('Chris Duhon', 100)
Chris Kaman
('Chris Kaman', 100)
Chris Paul
('Chris Paul', 100)
Chris Quinn
('Chris Quinn', 100)
Chris Wilcox
('Chris Wilcox', 100)
Christian Eyenga
('Christian Eyenga', 100)
Chuck Hayes
('Chuck Hayes', 100)
Cole Aldrich
('Cole Aldrich', 100)
Corey Brewer
('Corey Brewer', 100)
Corey Maggette
('Corey Maggette', 100)
Courtney Lee
('Courtney Lee', 100)
Craig Brackins
('Craig Brackins', 100)
Craig Smith
('Craig Smith', 100)
D.J. White
*****************************************
3
('DJ White', 94)
Da'Sean Butler
('Rasual Butler', 74)
DaJuan Summers
('DaJuan Summers', 100)
Daequan Cook
('Daequan Cook', 100)
Dahntay Jones
('Dahntay Jones', 100)
Damien Wilkins
('Damien Wilkins', 100)
Damion James
('Damion James', 100)
Dan Gadzuric
('Dan Gadzuric', 100)
Daniel Gibson
('Daniel Gibson', 100)
Daniel Orton
('Daniel Gibson', 72)
Danilo Gallinari
('Danilo Gallinari', 100)
Danny Granger
('Danny Granger', 100)
Danny Green
('Danny Green', 100)
Dante Cunningham
('Dante Cunningham', 100)
Darius Songaila
('Darius Songaila', 100)
Darko Milicic
('Darko Milicic', 100)
Darrell Arthur
('Darrell Arthur', 100)
Darren Collison
('Darren Collison', 100)
David Andersen
('David Andersen', 100)
David Lee
('David Lee', 100)
David West
('David West', 100)
DeAndre Jordan
('DeAndre Jordan', 100)
DeJuan Blair
('DeJuan Blair', 100)
DeMarre Carroll
('DeMarre Carroll', 100)
DeSagana Diop
('DeSagana Diop', 100)
Delonte West
('Delonte West', 100)
Deron Williams
('Deron Williams', 100)
Derrick Brown
('Derrick Brown', 100)
Derrick Caracter
('Derrick Caracter', 100)
Derrick Favors
('Derrick Favors', 100)
Derrick Rose
('Derrick Rose', 100)
Devin Ebanks
('Devin Ebanks', 100)
Devin Harris
('Devin Harris', 100)
Dexter Pittman
('Dexter Pittman', 100)
Didier Mbenga
('DJ Mbenga', 80)
Dirk Nowitzki
('Dirk Nowitzki', 100)
Dominic McGuire
('Dominic McGuire', 100)
Dominique Jones
('Dominique Jones', 100)
Drew Gooden
('Drew Gooden', 100)
Dwight Howard
('Dwight Howard', 100)
Dwyane Wade
('Dwyane Wade', 100)
Ed Davis
('Ed Davis', 100)
Eddy Curry
('Stephen Curry', 67)
Eduardo Najera
('Eduardo Najera', 100)
Ekpe Udoh
('Ekpe Udoh', 100)
Elliot Williams
('Elliot Williams', 100)
Eric Gordon
('Eric Gordon', 100)
Erick Dampier
('Erick Dampier', 100)
Ersan Ilyasova
('Ersan Ilyasova', 100)
Etan Thomas
('Etan Thomas', 100)
Francisco Elson
('Francisco Elson', 100)
Francisco Garcia
('Francisco Garcia', 100)
Gani Lawal
('Gani Lawal', 100)
Garret Siler
('Garret Siler', 100)
Garrett Temple
('Garrett Temple', 100)
Gary Neal
('Gary Neal', 100)
George Hill
('George Hill', 100)
Gerald Henderson Jr.
('Gerald Henderson', 100)
Gerald Wallace
('Gerald Wallace', 100)
Gilbert Arenas
('Gilbert Arenas', 100)
Glen Davis
('Glen Davis', 100)
Goran Dragic
('Goran Dragic', 100)
Gordon Hayward
('Gordon Hayward', 100)
Grant Hill
('Grant Hill', 100)
Greg Oden
('Greg Oden', 100)
Greivis Vasquez
('Greivis Vasquez', 100)
Hamady N'Diaye
*****************************************
4
('Hamady Ndiaye', 89)
Hamed Haddadi
('Hamed Haddadi', 100)
Hasheem Thabeet
('Hasheem Thabeet', 100)
Hassan Whiteside
('Hassan Whiteside', 100)
Hilton Armstrong
('Hilton Armstrong', 100)
Ian Mahinmi
('Ian Mahinmi', 100)
Ish Smith
('Ish Smith', 100)
J.J. Hickson
*****************************************
5
('JJ Hickson', 95)
J.J. Redick
*****************************************
6
('JJ Redick', 94)
JaVale McGee
('JaVale McGee', 100)
Jamaal Magloire
('Jamaal Magloire', 100)
Jamal Crawford
('Jamal Crawford', 100)
Jamario Moon
('Jamario Moon', 100)
Jameer Nelson
('Jameer Nelson', 100)
James Anderson
('James Anderson', 100)
James Posey
('James Posey', 100)
Jannero Pargo
('Anderson Varejao', 62)
Jared Jeffries
('Jared Jeffries', 100)
Jason Collins
('Jason Collins', 100)
Jason Kapono
('Jason Kapono', 100)
Jason Kidd
('Jason Kidd', 100)
Jason Maxiell
('Jason Maxiell', 100)
Jason Richardson
('Jason Richardson', 100)
Jason Smith
('Jason Smith', 100)
Jason Thompson
('Jason Thompson', 100)
Jason Williams
('Jason Williams', 100)
Jeff Adrien
('Jeff Adrien', 100)
Jeff Foster
('Jeff Foster', 100)
Jeff Green
('Jeff Green', 100)
Jeremy Evans
('Jeremy Evans', 100)
Jeremy Lin
('Jeremy Lin', 100)
Jermaine O'Neal
("Jermaine O'Neal", 100)
Jermaine Taylor
('Jermaine Taylor', 100)
Jerry Stackhouse
('Jerry Stackhouse', 100)
Jerryd Bayless
('Jerryd Bayless', 100)
Jianlian Yi
('Yi Jianlian', 100)
Joakim Noah
('Joakim Noah', 100)
Jodie Meeks
('Jodie Meeks', 100)
Joe Alexander
('Jose Calderon', 69)
Joe Johnson
('Joe Johnson', 100)
Joe Smith
('Joe Smith', 100)
Joel Przybilla
('Joel Przybilla', 100)
Joey Dorsey
('Joey Dorsey', 100)
Joey Graham
('Joey Graham', 100)
John Lucas III
('John Lucas III', 100)
John Salmons
('John Salmons', 100)
John Wall
('John Wall', 100)
John Wallace
*****************************************
7
('John Wall', 86)
Jon Brockman
('Jon Brockman', 100)
Jonas Jerebko
('James Jones', 58)
Jonny Flynn
('Jonny Flynn', 100)
Jordan Crawford
('Jordan Crawford', 100)
Jordan Farmar
('Jordan Farmar', 100)
Jordan Hill
('Jordan Hill', 100)
Jose Barea
('J.J. Barea', 83)
Jose Calderon
('Jose Calderon', 100)
Josh Howard
('Josh Howard', 100)
Josh McRoberts
('Josh McRoberts', 100)
Josh Powell
('Josh Powell', 100)
Josh Smith
('Josh Smith', 100)
Julian Wright
('Julian Wright', 100)
Juwan Howard
('Juwan Howard', 100)
Kelenna Azubuike
('Acie Law', 50)
Kendrick Perkins
('Kendrick Perkins', 100)
Kenyon Martin
('Kenyon Martin', 100)
Kevin Durant
('Kevin Durant', 100)
Kevin Garnett
('Kevin Garnett', 100)
Kevin Love
('Kevin Love', 100)
Kevin Martin
('Kevin Martin', 100)
Kevin Seraphin
('Kevin Seraphin', 100)
Keyon Dooling
('Keyon Dooling', 100)
Kirk Hinrich
('Kirk Hinrich', 100)
Kosta Koufos
('Kosta Koufos', 100)
Kris Humphries
('Kris Humphries', 100)
Kurt Thomas
('Kurt Thomas', 100)
Kwame Brown
('Kwame Brown', 100)
Kyle Lowry
('Kyle Lowry', 100)
Kyrylo Fesenko
('Kyrylo Fesenko', 100)
LaMarcus Aldridge
('LaMarcus Aldridge', 100)
Lance Stephenson

('Lance Stephenson', 100)
Larry Sanders
('Larry Sanders', 100)
Lazar Hayward
('Lazar Hayward', 100)
LeBron James
('LeBron James', 100)
Leandro Barbosa
('Leandro Barbosa', 100)
Leon Powe
('Leon Powe', 100)
Lester Hudson
('Lester Hudson', 100)
Linas Kleiza
('Linas Kleiza', 100)
Lou Amundson
('Lou Amundson', 100)
Lou Williams
('Lou Williams', 100)
Luc Mbah a Moute
('Luc Mbah a Moute', 100)
Luis Scola
('Luis Scola', 100)
Luke Babbitt
('Luke Babbitt', 100)
Luke Harangody
('Luke Harangody', 100)
Luke Ridnour
('Luke Ridnour', 100)
Luke Walton
('Luke Walton', 100)
Luther Head
('Luther Head', 100)
Magnum Rolle
('Will Bynum', 55)
Malik Allen
('Malik Allen', 100)
Manny Harris
('Manny Harris', 100)
Manu Ginobili
('Manu Ginobili', 100)
Marc Gasol
('Marc Gasol', 100)
Marco Belinelli
('Marco Belinelli', 100)
Marcus Banks
('Marcus Banks', 100)
Marcus Camby
('Marcus Camby', 100)
Marcus Thornton
('Marcus Thornton', 100)
Mario Chalmers
('Mario Chalmers', 100)
Mario West
('Mario West', 100)
Marquis Daniels
('Marquis Daniels', 100)
Martell Webster
('Martell Webster', 100)
Marvin Williams
('Marvin Williams', 100)
Matt Barnes
('Matt Barnes', 100)
Matt Bonner
('Matt Bonner', 100)
Matt Carroll
('Matt Carroll', 100)
Matt Janning
('Matt Barnes', 61)
Maurice Ager
('Maurice Ager', 100)
Maurice Evans
('Maurice Evans', 100)
Mehmet Okur
('Mehmet Okur', 100)
Melvin Ely
('Melvin Ely', 100)
Michael Beasley
('Michael Beasley', 100)
Michael Redd
('Michael Redd', 100)
Mickael Pietrus
('Mickael Pietrus', 100)
Mike Conley Jr.
('Mike Conley', 100)
Mike Dunleavy Jr.
('Mike Dunleavy', 100)
Mike Miller
('Mike Miller', 100)
Mo Williams
('Mo Williams', 100)
Monta Ellis
('Monta Ellis', 100)
Morris Peterson
('Morris Peterson', 100)
Mustafa Shakur
('Mustafa Shakur', 100)
Nate Robinson
('Nate Robinson', 100)
Nazr Mohammed
('Nazr Mohammed', 100)
Nenad Krstic
('Nenad Krstic', 100)
Nene Hilario
('Nene', 100)
Nick Collison
('Nick Collison', 100)
Nick Young
('Nick Young', 100)
Nicolas Batum
('Nicolas Batum', 100)
Nikola Pekovic
('Nikola Pekovic', 100)
O.J. Mayo
('O.J. Mayo', 100)
Omer Asik
('Omer Asik', 100)
Omri Casspi
('Omri Casspi', 100)
Orien Greene
('Orien Greene', 100)
Othyus Jeffers
('Othyus Jeffers', 100)
Pape Sy
('Pape Sy', 100)
Patrick Patterson
('Patrick Patterson', 100)
Patty Mills
('Patty Mills', 100)
Paul George
('Paul George', 100)
Paul Millsap
('Paul Millsap', 100)
Paul Pierce
('Paul Pierce', 100)
Peja Stojakovic
('Peja Stojakovic', 100)
Pooh Jeter
('Pooh Jeter', 100)
Pops Mensah-Bonsu
('Pops Mensah-Bonsu', 100)
Quentin Richardson
('Quentin Richardson', 100)
Quincy Pondexter
('Quincy Pondexter', 100)
Quinton Ross
('Quinton Ross', 100)
Raja Bell
('Raja Bell', 100)
Rajon Rondo
('Rajon Rondo', 100)
Randy Foye
('Randy Foye', 100)
Rashard Lewis
('Rashard Lewis', 100)
Rasual Butler
('Rasual Butler', 100)
Ray Allen
('Ray Allen', 100)
Raymond Felton
('Raymond Felton', 100)
Reggie Evans
('Reggie Evans', 100)
Reggie Williams
('Reggie Williams', 100)
Renaldo Balkman
('Renaldo Balkman', 100)
Richard Hamilton
('Richard Hamilton', 100)
Robert Vaden
('Greg Oden', 57)
Robin Lopez
('Robin Lopez', 100)
Rodney Carney
('Rodney Carney', 100)
Rodney Stuckey
('Rodney Stuckey', 100)
Rodrigue Beaubois
('Rodrigue Beaubois', 100)
Roger Mason Jr.
('Roger Mason Jr.', 100)
Ronnie Brewer
('Ronnie Brewer', 100)
Ronnie Price
('Ronnie Price', 100)
Ronny Turiaf
('Ronny Turiaf', 100)
Roy Hibbert
('Roy Hibbert', 100)
Rudy Fernandez
('Rudy Fernandez', 100)
Rudy Gay
('Rudy Gay', 100)
Ryan Anderson
('Ryan Anderson', 100)
Ryan Gomes
('Ryan Gomes', 100)
Ryan Hollins
('Ryan Hollins', 100)
Samardo Samuels
('Samardo Samuels', 100)
Samuel Dalembert
('Samuel Dalembert', 100)
Sasha Vujacic
('Sasha Vujacic', 100)
Sean Marks
('Sean Marks', 100)
Sebastian Telfair
('Sebastian Telfair', 100)
Semih Erden
('Semih Erden', 100)
Shaquille O'Neal
("Shaquille O'Neal", 100)
Shaun Livingston
('Shaun Livingston', 100)
Shawn Marion
('Shawn Marion', 100)
Shawne Williams
('Shawne Williams', 100)
Shelden Williams
('Shelden Williams', 100)
Sherron Collins
('Sherron Collins', 100)
Solomon Alabi
('Solomon Alabi', 100)
Solomon Jones
('Solomon Jones', 100)
Sonny Weems
('Sonny Weems', 100)
Spencer Hawes
('Spencer Hawes', 100)
Stephen Curry
('Stephen Curry', 100)
Stephen Graham
('Stephen Graham', 100)
Stephen Jackson
('Stephen Jackson', 100)
Steve Blake
('Steve Blake', 100)
Steve Nash
('Steve Nash', 100)
Steve Novak
('Steve Novak', 100)
Sundiata Gaines
('Sundiata Gaines', 100)
T.J. Ford
('T.J. Ford', 100)
Taj Gibson
('Taj Gibson', 100)
Tayshaun Prince
('Tayshaun Prince', 100)
Terrence Williams
('Terrence Williams', 100)
Terrico White
('DJ White', 77)
Thabo Sefolosha
('Thabo Sefolosha', 100)
Theo Ratliff
('Theo Ratliff', 100)
Tiago Splitter
('Tiago Splitter', 100)
Tim Duncan
('Tim Duncan', 100)
Timofey Mozgov
('Timofey Mozgov', 100)
Toney Douglas
('Toney Douglas', 100)
Tony Allen
('Tony Allen', 100)
Tony Battie
('Tony Battie', 100)
Tracy McGrady
('Tracy McGrady', 100)
Trevor Ariza
('Trevor Ariza', 100)
Trevor Booker
('Trevor Booker', 100)
Trey Johnson
('Trey Johnson', 100)
Troy Murphy
('Troy Murphy', 100)
Ty Lawson
('Ty Lawson', 100)
Tyler Hansbrough
('Tyler Hansbrough', 100)
Tyreke Evans
('Tyreke Evans', 100)
Tyrus Thomas
('Tyrus Thomas', 100)
Tyson Chandler
('Tyson Chandler', 100)
Udonis Haslem
('Udonis Haslem', 100)
Vince Carter
('Vince Carter', 100)
Von Wafer
('Von Wafer', 100)
Wayne Ellington
('Wayne Ellington', 100)
Wes Johnson
*****************************************
8
('Wesley Johnson', 88)
Will Bynum
('Will Bynum', 100)
Willie Warren
('Willie Warren', 100)
Wilson Chandler
('Wilson Chandler', 100)
Xavier Henry
('Xavier Henry', 100)
Yao Ming
('Yao Ming', 100)
Zabian Dowdell
('Zabian Dowdell', 100)
Zach Randolph
('Zach Randolph', 100)
Zaza Pachulia
('Zaza Pachulia', 100)
Zydrunas Ilgauskas
('Zydrunas Ilgauskas', 100)
8

In [144]:
i = 0
for player_ in sorted(unique_player):
    print(player_)
    if((process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] != 100) & (process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] > 80)):
        print('*****************************************')
        print(i)
        i = i + 1
    print(process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][:2])

print(i - 1)

 Tony Parker
('Tony Parker', 100)
A.J. Price
*****************************************
0
('AJ Price', 94)
Aaron Brooks
('Aaron Brooks', 100)
Aaron Gray
('Aaron Gray', 100)
Acie Law
('Acie Law', 100)
Al Harrington
('Al Harrington', 100)
Al Horford
('Al Horford', 100)
Al Thornton
('Al Thornton', 100)
Alex Ajinca
*****************************************
1
('Alexis Ajinca', 92)
Alonzo Gee
('Alonzo Gee', 100)
Amar'e Stoudemire
("Amar'e Stoudemire", 100)
Amir Johnson
('Amir Johnson', 100)
Anderson Varejao
('Anderson Varejao', 100)
Andray Blatche
('Andray Blatche', 100)
Andre Iguodala
('Andre Iguodala', 100)
Andrea Bargnani
('Andrea Bargnani', 100)
Andrei Kirilenko
('Andrei Kirilenko', 100)
Andres Nocioni
('Andres Nocioni', 100)
Andrew Bogut
('Andrew Bogut', 100)
Andrew Bynum
('Andrew Bynum', 100)
Andris Biedrins
('Andris Biedrins', 100)
Andy Rautins
('Andy Rautins', 100)
Antawn Jamison
('Antawn Jamison', 100)
Anthony Carter
('Anthony Carter', 100)
Anthony Morrow
('Anthony Morrow', 100)
Anthony Parker
('Anthony Parker', 100)
Anthony Randolph
('Anthony Randolph', 100)
Anthony Tolliver
('Anthony Tolliver', 100)
Antoine Wright
('Antoine Wright', 100)
Antonio McDyess
('Antonio McDyess', 100)
Armon Johnson
('Armon Johnson', 100)
Arron Afflalo
('Arron Afflalo', 100)
Austin Daye
('Austin Daye', 100)
Avery Bradley
('Avery Bradley', 100)
B.J. Mullens
('Byron Mullens', 78)
Baron Davis
('Baron Davis', 100)
Ben Uzoh
('Ben Uzoh', 100)
Ben Wallace
('Ben Wallace', 100)
Beno Udrih
('Beno Udrih', 100)
Bill Walker
('Henry Walker', 71)
Brad Miller
('Brad Miller', 100)
Brandan Wright
('Brandan Wright', 100)
Brandon Bass
('Brandon Bass', 100)
Brandon Jennings
('Brandon Jennings', 100)
Brandon Roy
('Brandon Roy', 100)
Brandon Rush
('Brandon Rush', 100)
Brendan Haywood
('Brendan Haywood', 100)
Brian Cardinal
('Brian Cardinal', 100)
Brian Cook
('Brian Cook', 100)
Brian Scalabrine
('Brian Scalabrine', 100)
Brian Skinner
('Brian Skinner', 100)
C.J. Miles
*****************************************
2
('CJ Miles', 94)
Carlos Arroyo
('Carlos Arroyo', 100)
Carlos Boozer
('Carlos Boozer', 100)
Carlos Delfino
('Carlos Delfino', 100)
Carmelo Anthony
('Carmelo Anthony', 100)
Caron Butler
('Caron Butler', 100)
Cartier Martin
('Cartier Martin', 100)
Channing Frye
('Channing Frye', 100)
Charlie Bell
('Charlie Bell', 100)
Charlie Villanueva
('Charlie Villanueva', 100)
Chase Budinger
('Chase Budinger', 100)
Chauncey Billups
('Chauncey Billups', 100)
Chris Andersen
('Chris Andersen', 100)
Chris Bosh
('Chris Bosh', 100)
Chris Douglas-Roberts
('Chris Douglas-Roberts', 100)
Chris Duhon
('Chris Duhon', 100)
Chris Kaman
('Chris Kaman', 100)
Chris Paul
('Chris Paul', 100)
Chris Quinn
('Chris Quinn', 100)
Chris Wilcox
('Chris Wilcox', 100)
Christian Eyenga
('Christian Eyenga', 100)
Chuck Hayes
('Chuck Hayes', 100)
Cole Aldrich
('Cole Aldrich', 100)
Corey Brewer
('Corey Brewer', 100)
Corey Maggette
('Corey Maggette', 100)
Courtney Lee
('Courtney Lee', 100)
Craig Brackins
('Craig Brackins', 100)
Craig Smith
('Craig Smith', 100)
D.J. White
*****************************************
3
('DJ White', 94)
Da'Sean Butler
('Rasual Butler', 74)
DaJuan Summers
('DaJuan Summers', 100)
Daequan Cook
('Daequan Cook', 100)
Dahntay Jones
('Dahntay Jones', 100)
Damien Wilkins
('Damien Wilkins', 100)
Damion James
('Damion James', 100)
Dan Gadzuric
('Dan Gadzuric', 100)
Daniel Gibson
('Daniel Gibson', 100)
Daniel Orton
('Daniel Gibson', 72)
Danilo Gallinari
('Danilo Gallinari', 100)
Danny Granger
('Danny Granger', 100)
Danny Green
('Danny Green', 100)
Dante Cunningham
('Dante Cunningham', 100)
Darius Songaila
('Darius Songaila', 100)
Darko Milicic
('Darko Milicic', 100)
Darrell Arthur
('Darrell Arthur', 100)
Darren Collison
('Darren Collison', 100)
David Andersen
('David Andersen', 100)
David Lee
('David Lee', 100)
David West
('David West', 100)
DeAndre Jordan
('DeAndre Jordan', 100)
DeJuan Blair
('DeJuan Blair', 100)
DeMarre Carroll
('DeMarre Carroll', 100)
DeSagana Diop
('DeSagana Diop', 100)
Delonte West
('Delonte West', 100)
Deron Williams
('Deron Williams', 100)
Derrick Brown
('Derrick Brown', 100)
Derrick Caracter
('Derrick Caracter', 100)
Derrick Favors
('Derrick Favors', 100)
Derrick Rose
('Derrick Rose', 100)
Devin Ebanks
('Devin Ebanks', 100)
Devin Harris
('Devin Harris', 100)
Dexter Pittman
('Dexter Pittman', 100)
Didier Mbenga
('DJ Mbenga', 80)
Dirk Nowitzki
('Dirk Nowitzki', 100)
Dominic McGuire
('Dominic McGuire', 100)
Dominique Jones
('Dominique Jones', 100)
Drew Gooden
('Drew Gooden', 100)
Dwight Howard
('Dwight Howard', 100)
Dwyane Wade
('Dwyane Wade', 100)
Ed Davis
('Ed Davis', 100)
Eddy Curry
('Stephen Curry', 67)
Eduardo Najera
('Eduardo Najera', 100)
Ekpe Udoh
('Ekpe Udoh', 100)
Elliot Williams
('Elliot Williams', 100)
Eric Gordon
('Eric Gordon', 100)
Erick Dampier
('Erick Dampier', 100)
Ersan Ilyasova
('Ersan Ilyasova', 100)
Etan Thomas
('Etan Thomas', 100)
Francisco Elson
('Francisco Elson', 100)
Francisco Garcia
('Francisco Garcia', 100)
Gani Lawal
('Gani Lawal', 100)
Garret Siler
('Garret Siler', 100)
Garrett Temple
('Garrett Temple', 100)
Gary Neal
('Gary Neal', 100)
George Hill
('George Hill', 100)
Gerald Henderson Jr.
('Gerald Henderson', 100)
Gerald Wallace
('Gerald Wallace', 100)
Gilbert Arenas
('Gilbert Arenas', 100)
Glen Davis
('Glen Davis', 100)
Goran Dragic
('Goran Dragic', 100)
Gordon Hayward
('Gordon Hayward', 100)
Grant Hill
('Grant Hill', 100)
Greg Oden
('Greg Oden', 100)
Greivis Vasquez
('Greivis Vasquez', 100)
Hamady N'Diaye
*****************************************
4
('Hamady Ndiaye', 89)
Hamed Haddadi
('Hamed Haddadi', 100)
Hasheem Thabeet
('Hasheem Thabeet', 100)
Hassan Whiteside
('Hassan Whiteside', 100)
Hilton Armstrong
('Hilton Armstrong', 100)
Ian Mahinmi
('Ian Mahinmi', 100)
Ish Smith
('Ish Smith', 100)
J.J. Hickson
*****************************************
5
('JJ Hickson', 95)
J.J. Redick
*****************************************
6
('JJ Redick', 94)
JaVale McGee
('JaVale McGee', 100)
Jamaal Magloire
('Jamaal Magloire', 100)
Jamal Crawford
('Jamal Crawford', 100)
Jamario Moon
('Jamario Moon', 100)
Jameer Nelson
('Jameer Nelson', 100)
James Anderson
('James Anderson', 100)
James Posey
('James Posey', 100)
Jannero Pargo
('Anderson Varejao', 62)
Jared Jeffries
('Jared Jeffries', 100)
Jason Collins
('Jason Collins', 100)
Jason Kapono
('Jason Kapono', 100)
Jason Kidd
('Jason Kidd', 100)
Jason Maxiell
('Jason Maxiell', 100)
Jason Richardson
('Jason Richardson', 100)
Jason Smith
('Jason Smith', 100)
Jason Thompson
('Jason Thompson', 100)
Jason Williams
('Jason Williams', 100)
Jeff Adrien
('Jeff Adrien', 100)
Jeff Foster
('Jeff Foster', 100)
Jeff Green
('Jeff Green', 100)
Jeremy Evans
('Jeremy Evans', 100)
Jeremy Lin
('Jeremy Lin', 100)
Jermaine O'Neal
("Jermaine O'Neal", 100)
Jermaine Taylor
('Jermaine Taylor', 100)
Jerry Stackhouse
('Jerry Stackhouse', 100)
Jerryd Bayless
('Jerryd Bayless', 100)
Jianlian Yi
('Yi Jianlian', 100)
Joakim Noah
('Joakim Noah', 100)
Jodie Meeks
('Jodie Meeks', 100)
Joe Alexander
('Jose Calderon', 69)
Joe Johnson
('Joe Johnson', 100)
Joe Smith
('Joe Smith', 100)
Joel Przybilla
('Joel Przybilla', 100)
Joey Dorsey
('Joey Dorsey', 100)
Joey Graham
('Joey Graham', 100)
John Lucas III
('John Lucas III', 100)
John Salmons
('John Salmons', 100)
John Wall
('John Wall', 100)
John Wallace
*****************************************
7
('John Wall', 86)
Jon Brockman
('Jon Brockman', 100)
Jonas Jerebko
('James Jones', 58)
Jonny Flynn
('Jonny Flynn', 100)
Jordan Crawford
('Jordan Crawford', 100)
Jordan Farmar
('Jordan Farmar', 100)
Jordan Hill
('Jordan Hill', 100)
Jose Barea
*****************************************
8
('J.J. Barea', 83)
Jose Calderon
('Jose Calderon', 100)
Josh Howard
('Josh Howard', 100)
Josh McRoberts
('Josh McRoberts', 100)
Josh Powell
('Josh Powell', 100)
Josh Smith
('Josh Smith', 100)
Julian Wright
('Julian Wright', 100)
Juwan Howard
('Juwan Howard', 100)
Kelenna Azubuike
('Acie Law', 50)
Kendrick Perkins
('Kendrick Perkins', 100)
Kenyon Martin
('Kenyon Martin', 100)
Kevin Durant
('Kevin Durant', 100)
Kevin Garnett
('Kevin Garnett', 100)
Kevin Love
('Kevin Love', 100)
Kevin Martin
('Kevin Martin', 100)
Kevin Seraphin
('Kevin Seraphin', 100)
Keyon Dooling
('Keyon Dooling', 100)
Kirk Hinrich
('Kirk Hinrich', 100)
Kosta Koufos
('Kosta Koufos', 100)
Kris Humphries
('Kris Humphries', 100)
Kurt Thomas
('Kurt Thomas', 100)
Kwame Brown
('Kwame Brown', 100)
Kyle Lowry

('Kyle Lowry', 100)
Kyrylo Fesenko
('Kyrylo Fesenko', 100)
LaMarcus Aldridge
('LaMarcus Aldridge', 100)
Lance Stephenson
('Lance Stephenson', 100)
Larry Sanders
('Larry Sanders', 100)
Lazar Hayward
('Lazar Hayward', 100)
LeBron James
('LeBron James', 100)
Leandro Barbosa
('Leandro Barbosa', 100)
Leon Powe
('Leon Powe', 100)
Lester Hudson
('Lester Hudson', 100)
Linas Kleiza
('Linas Kleiza', 100)
Lou Amundson
('Lou Amundson', 100)
Lou Williams
('Lou Williams', 100)
Luc Mbah a Moute
('Luc Mbah a Moute', 100)
Luis Scola
('Luis Scola', 100)
Luke Babbitt
('Luke Babbitt', 100)
Luke Harangody
('Luke Harangody', 100)
Luke Ridnour
('Luke Ridnour', 100)
Luke Walton
('Luke Walton', 100)
Luther Head
('Luther Head', 100)
Magnum Rolle
('Will Bynum', 55)
Malik Allen
('Malik Allen', 100)
Manny Harris
('Manny Harris', 100)
Manu Ginobili
('Manu Ginobili', 100)
Marc Gasol
('Marc Gasol', 100)
Marco Belinelli
('Marco Belinelli', 100)
Marcus Banks
('Marcus Banks', 100)
Marcus Camby
('Marcus Camby', 100)
Marcus Thornton
('Marcus Thornton', 100)
Mario Chalmers
('Mario Chalmers', 100)
Mario West
('Mario West', 100)
Marquis Daniels
('Marquis Daniels', 100)
Martell Webster
('Martell Webster', 100)
Marvin Williams
('Marvin Williams', 100)
Matt Barnes
('Matt Barnes', 100)
Matt Bonner
('Matt Bonner', 100)
Matt Carroll
('Matt Carroll', 100)
Matt Janning
('Matt Barnes', 61)
Maurice Ager
('Maurice Ager', 100)
Maurice Evans
('Maurice Evans', 100)
Mehmet Okur
('Mehmet Okur', 100)
Melvin Ely
('Melvin Ely', 100)
Michael Beasley
('Michael Beasley', 100)
Michael Redd
('Michael Redd', 100)
Mickael Pietrus
('Mickael Pietrus', 100)
Mike Conley Jr.
('Mike Conley', 100)
Mike Dunleavy Jr.
('Mike Dunleavy', 100)
Mike Miller
('Mike Miller', 100)
Mo Williams
('Mo Williams', 100)
Monta Ellis
('Monta Ellis', 100)
Morris Peterson
('Morris Peterson', 100)
Mustafa Shakur
('Mustafa Shakur', 100)
Nate Robinson
('Nate Robinson', 100)
Nazr Mohammed
('Nazr Mohammed', 100)
Nenad Krstic
('Nenad Krstic', 100)
Nene Hilario
('Nene', 100)
Nick Collison
('Nick Collison', 100)
Nick Young
('Nick Young', 100)
Nicolas Batum
('Nicolas Batum', 100)
Nikola Pekovic
('Nikola Pekovic', 100)
O.J. Mayo
('O.J. Mayo', 100)
Omer Asik
('Omer Asik', 100)
Omri Casspi
('Omri Casspi', 100)
Orien Greene
('Orien Greene', 100)
Othyus Jeffers
('Othyus Jeffers', 100)
Pape Sy
('Pape Sy', 100)
Patrick Patterson
('Patrick Patterson', 100)
Patty Mills
('Patty Mills', 100)
Paul George
('Paul George', 100)
Paul Millsap
('Paul Millsap', 100)
Paul Pierce
('Paul Pierce', 100)
Peja Stojakovic
('Peja Stojakovic', 100)
Pooh Jeter
('Pooh Jeter', 100)
Pops Mensah-Bonsu
('Pops Mensah-Bonsu', 100)
Quentin Richardson
('Quentin Richardson', 100)
Quincy Pondexter
('Quincy Pondexter', 100)
Quinton Ross
('Quinton Ross', 100)
Raja Bell
('Raja Bell', 100)
Rajon Rondo
('Rajon Rondo', 100)
Randy Foye
('Randy Foye', 100)
Rashard Lewis
('Rashard Lewis', 100)
Rasual Butler
('Rasual Butler', 100)
Ray Allen
('Ray Allen', 100)
Raymond Felton
('Raymond Felton', 100)
Reggie Evans
('Reggie Evans', 100)
Reggie Williams
('Reggie Williams', 100)
Renaldo Balkman
('Renaldo Balkman', 100)
Richard Hamilton
('Richard Hamilton', 100)
Robert Vaden
('Greg Oden', 57)
Robin Lopez
('Robin Lopez', 100)
Rodney Carney
('Rodney Carney', 100)
Rodney Stuckey
('Rodney Stuckey', 100)
Rodrigue Beaubois
('Rodrigue Beaubois', 100)
Roger Mason Jr.
('Roger Mason Jr.', 100)
Ronnie Brewer
('Ronnie Brewer', 100)
Ronnie Price
('Ronnie Price', 100)
Ronny Turiaf
('Ronny Turiaf', 100)
Roy Hibbert
('Roy Hibbert', 100)
Rudy Fernandez
('Rudy Fernandez', 100)
Rudy Gay
('Rudy Gay', 100)
Ryan Anderson
('Ryan Anderson', 100)
Ryan Gomes
('Ryan Gomes', 100)
Ryan Hollins
('Ryan Hollins', 100)
Samardo Samuels
('Samardo Samuels', 100)
Samuel Dalembert
('Samuel Dalembert', 100)
Sasha Vujacic
('Sasha Vujacic', 100)
Sean Marks
('Sean Marks', 100)
Sebastian Telfair
('Sebastian Telfair', 100)
Semih Erden
('Semih Erden', 100)
Shaquille O'Neal
("Shaquille O'Neal", 100)
Shaun Livingston
('Shaun Livingston', 100)
Shawn Marion
('Shawn Marion', 100)
Shawne Williams
('Shawne Williams', 100)
Shelden Williams
('Shelden Williams', 100)
Sherron Collins
('Sherron Collins', 100)
Solomon Alabi
('Solomon Alabi', 100)
Solomon Jones
('Solomon Jones', 100)
Sonny Weems
('Sonny Weems', 100)
Spencer Hawes
('Spencer Hawes', 100)
Stephen Curry
('Stephen Curry', 100)
Stephen Graham
('Stephen Graham', 100)
Stephen Jackson
('Stephen Jackson', 100)
Steve Blake
('Steve Blake', 100)
Steve Nash
('Steve Nash', 100)
Steve Novak
('Steve Novak', 100)
Sundiata Gaines
('Sundiata Gaines', 100)
T.J. Ford
('T.J. Ford', 100)
Taj Gibson
('Taj Gibson', 100)
Tayshaun Prince
('Tayshaun Prince', 100)
Terrence Williams
('Terrence Williams', 100)
Terrico White
('DJ White', 77)
Thabo Sefolosha
('Thabo Sefolosha', 100)
Theo Ratliff
('Theo Ratliff', 100)
Tiago Splitter
('Tiago Splitter', 100)
Tim Duncan
('Tim Duncan', 100)
Timofey Mozgov
('Timofey Mozgov', 100)
Toney Douglas
('Toney Douglas', 100)
Tony Allen
('Tony Allen', 100)
Tony Battie
('Tony Battie', 100)
Tracy McGrady
('Tracy McGrady', 100)
Trevor Ariza
('Trevor Ariza', 100)
Trevor Booker
('Trevor Booker', 100)
Trey Johnson
('Trey Johnson', 100)
Troy Murphy
('Troy Murphy', 100)
Ty Lawson
('Ty Lawson', 100)
Tyler Hansbrough
('Tyler Hansbrough', 100)
Tyreke Evans
('Tyreke Evans', 100)
Tyrus Thomas
('Tyrus Thomas', 100)
Tyson Chandler
('Tyson Chandler', 100)
Udonis Haslem
('Udonis Haslem', 100)
Vince Carter
('Vince Carter', 100)
Von Wafer
('Von Wafer', 100)
Wayne Ellington
('Wayne Ellington', 100)
Wes Johnson
*****************************************
9
('Wesley Johnson', 88)
Will Bynum
('Will Bynum', 100)
Willie Warren
('Willie Warren', 100)
Wilson Chandler
('Wilson Chandler', 100)
Xavier Henry
('Xavier Henry', 100)
Yao Ming
('Yao Ming', 100)
Zabian Dowdell
('Zabian Dowdell', 100)
Zach Randolph
('Zach Randolph', 100)
Zaza Pachulia
('Zaza Pachulia', 100)
Zydrunas Ilgauskas
('Zydrunas Ilgauskas', 100)
9

In [145]:
i = 0
for player_ in sorted(unique_player):
    #print(player_)
    if((process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] != 100) & (process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] > 80)):
        print('*****************************************')
        print(player_)
        print(process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][:2])
        print(i)
        i = i + 1
    #print(process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][:2])

print(i - 1)

*****************************************
A.J. Price
('AJ Price', 94)
0
*****************************************
Alex Ajinca
('Alexis Ajinca', 92)
1
*****************************************
C.J. Miles
('CJ Miles', 94)
2
*****************************************
D.J. White
('DJ White', 94)
3
*****************************************
Hamady N'Diaye
('Hamady Ndiaye', 89)
4
*****************************************
J.J. Hickson
('JJ Hickson', 95)
5
*****************************************
J.J. Redick
('JJ Redick', 94)
6
*****************************************
John Wallace
('John Wall', 86)
7
*****************************************
Jose Barea
('J.J. Barea', 83)
8
*****************************************
Wes Johnson
('Wesley Johnson', 88)
9
9

In [146]:
#names with space(s) in the front

#names with space(s) in the back

#?remove periods?

#?remove apostrophes?

'''
*****************************************
A.J. Price
('AJ Price', 94)
0
*****************************************
Alex Ajinca
('Alexis Ajinca', 92)
1
*****************************************
C.J. Miles
('CJ Miles', 94)
2
*****************************************
D.J. White
('DJ White', 94)
3
*****************************************
Hamady N'Diaye
('Hamady Ndiaye', 89)
4
*****************************************
J.J. Hickson
('JJ Hickson', 95)
5
*****************************************
J.J. Redick
('JJ Redick', 94)
6
*****************************************
John Wallace
('John Wall', 86)
7
*****************************************
Jose Barea 
('J.J. Barea', 83)
8
*****************************************
Wes Johnson
('Wesley Johnson', 88)
9
'''

"\n*****************************************\nA.J. Price\n('AJ Price', 94)\n0\n*****************************************\nAlex Ajinca\n('Alexis Ajinca', 92)\n1\n*****************************************\nC.J. Miles\n('CJ Miles', 94)\n2\n*****************************************\nD.J. White\n('DJ White', 94)\n3\n*****************************************\nHamady N'Diaye\n('Hamady Ndiaye', 89)\n4\n*****************************************\nJ.J. Hickson\n('JJ Hickson', 95)\n5\n*****************************************\nJ.J. Redick\n('JJ Redick', 94)\n6\n*****************************************\nJohn Wallace\n('John Wall', 86)\n7\n*****************************************\nJose Barea \n('J.J. Barea', 83)\n8\n*****************************************\nWes Johnson\n('Wesley Johnson', 88)\n9\n"

In [147]:
'''
*****************************************
A.J. Price
('AJ Price', 94)
0
'''

df_inj3

      game_date       Team     team_id              player   game_id
0    2010-10-26    Blazers  1610612757     Elliot Williams  21000002
1    2010-10-26    Blazers  1610612757           Greg Oden  21000002
2    2010-10-26    Blazers  1610612757      Joel Przybilla  21000002
3    2010-10-26    Celtics  1610612738       Avery Bradley  21000001
4    2010-10-26    Celtics  1610612738    Kendrick Perkins  21000001
...         ...        ...         ...                 ...       ...
1673 2011-05-26      Bulls  1610612741           Omer Asik  41000305
1674 2011-05-31       Heat  1610612748  Zydrunas Ilgauskas  41000401
1675 2011-06-05  Mavericks  1610612742     Brendan Haywood  41000403
1676 2011-06-07  Mavericks  1610612742   Rodrigue Beaubois  41000404
1677 2011-06-09  Mavericks  1610612742     Brendan Haywood  41000405

[1678 rows x 5 columns]

In [148]:
df_inj3[df_inj3.player == 'A.J. Price']

     game_date    Team     team_id      player   game_id
54  2010-10-27  Pacers  1610612754  A.J. Price  21000013
256 2010-11-22  Pacers  1610612754  A.J. Price  21000196
408 2010-12-13  Pacers  1610612754  A.J. Price  21000356
534 2010-12-26  Pacers  1610612754  A.J. Price  21000441
612 2011-01-02  Pacers  1610612754  A.J. Price  21000492
714 2011-01-14  Pacers  1610612754  A.J. Price  21000576

In [149]:
df_inj3[df_inj3.player == 'A.J. Price'].shape

(6, 5)

In [150]:
df_inj3[df_inj3.player.str.contains('A.J. Price')]

     game_date    Team     team_id      player   game_id
54  2010-10-27  Pacers  1610612754  A.J. Price  21000013
256 2010-11-22  Pacers  1610612754  A.J. Price  21000196
408 2010-12-13  Pacers  1610612754  A.J. Price  21000356
534 2010-12-26  Pacers  1610612754  A.J. Price  21000441
612 2011-01-02  Pacers  1610612754  A.J. Price  21000492
714 2011-01-14  Pacers  1610612754  A.J. Price  21000576

In [151]:
df_inj3[df_inj3.player.str.contains('A.J. Price')].shape

(6, 5)

In [152]:
df_inj3.player.replace({'A.J. Price': 'AJ Price'}, inplace=True)

In [153]:
df_inj3[df_inj3.player.str.contains('A.J. Price')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [154]:
df_inj3[df_inj3.player.str.contains('AJ Price')]

     game_date    Team     team_id    player   game_id
54  2010-10-27  Pacers  1610612754  AJ Price  21000013
256 2010-11-22  Pacers  1610612754  AJ Price  21000196
408 2010-12-13  Pacers  1610612754  AJ Price  21000356
534 2010-12-26  Pacers  1610612754  AJ Price  21000441
612 2011-01-02  Pacers  1610612754  AJ Price  21000492
714 2011-01-14  Pacers  1610612754  AJ Price  21000576

In [155]:
'''
*****************************************
Alex Ajinca
('Alexis Ajinca', 92)
1
'''

"\n*****************************************\nAlex Ajinca\n('Alexis Ajinca', 92)\n1\n"

In [156]:
df_inj3[df_inj3.player == 'Alex Ajinca']

      game_date       Team     team_id       player   game_id
46   2010-10-27  Mavericks  1610612742  Alex Ajinca  21000012
289  2010-11-27  Mavericks  1610612742  Alex Ajinca  21000239
381  2010-12-09  Mavericks  1610612742  Alex Ajinca  21000328
407  2010-12-13  Mavericks  1610612742  Alex Ajinca  21000358
764  2011-01-19  Mavericks  1610612742  Alex Ajinca  21000621
814  2011-01-24    Raptors  1610612761  Alex Ajinca  21000656
944  2011-02-08    Raptors  1610612761  Alex Ajinca  21000770
976  2011-02-11    Raptors  1610612761  Alex Ajinca  21000790
1199 2011-03-09    Raptors  1610612761  Alex Ajinca  21000956
1213 2011-03-11    Raptors  1610612761  Alex Ajinca  21000970

In [157]:
df_inj3[df_inj3.player == 'Alex Ajinca'].shape

(10, 5)

In [158]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')]

      game_date       Team     team_id       player   game_id
46   2010-10-27  Mavericks  1610612742  Alex Ajinca  21000012
289  2010-11-27  Mavericks  1610612742  Alex Ajinca  21000239
381  2010-12-09  Mavericks  1610612742  Alex Ajinca  21000328
407  2010-12-13  Mavericks  1610612742  Alex Ajinca  21000358
764  2011-01-19  Mavericks  1610612742  Alex Ajinca  21000621
814  2011-01-24    Raptors  1610612761  Alex Ajinca  21000656
944  2011-02-08    Raptors  1610612761  Alex Ajinca  21000770
976  2011-02-11    Raptors  1610612761  Alex Ajinca  21000790
1199 2011-03-09    Raptors  1610612761  Alex Ajinca  21000956
1213 2011-03-11    Raptors  1610612761  Alex Ajinca  21000970

In [159]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')].shape

(10, 5)

In [160]:
df_inj3[df_inj3.player == 'Alexis Ajinca']

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [161]:
df_inj3.player.replace({'Alex Ajinca':'Alexis Ajinca'}, inplace=True)

In [162]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [163]:
df_inj3[df_inj3.player.str.contains('Alexis Ajinca')]

      game_date       Team     team_id         player   game_id
46   2010-10-27  Mavericks  1610612742  Alexis Ajinca  21000012
289  2010-11-27  Mavericks  1610612742  Alexis Ajinca  21000239
381  2010-12-09  Mavericks  1610612742  Alexis Ajinca  21000328
407  2010-12-13  Mavericks  1610612742  Alexis Ajinca  21000358
764  2011-01-19  Mavericks  1610612742  Alexis Ajinca  21000621
814  2011-01-24    Raptors  1610612761  Alexis Ajinca  21000656
944  2011-02-08    Raptors  1610612761  Alexis Ajinca  21000770
976  2011-02-11    Raptors  1610612761  Alexis Ajinca  21000790
1199 2011-03-09    Raptors  1610612761  Alexis Ajinca  21000956
1213 2011-03-11    Raptors  1610612761  Alexis Ajinca  21000970

In [164]:
'''
*****************************************
C.J. Miles
('CJ Miles', 94)
2
'''

"\n*****************************************\nC.J. Miles\n('CJ Miles', 94)\n2\n"

In [165]:
print(df_inj3[df_inj3.player == 'C.J. Miles'].shape)
df_inj3[df_inj3.player == 'C.J. Miles']

(4, 5)

      game_date  Team     team_id      player   game_id
570  2010-12-29  Jazz  1610612762  C.J. Miles  21000472
579  2010-12-30  Jazz  1610612762  C.J. Miles  21000475
600  2011-01-01  Jazz  1610612762  C.J. Miles  21000491
1605 2011-04-13  Jazz  1610612762  C.J. Miles  21001226

In [166]:
print(df_inj3[df_inj3.player.str.contains('C.J. Miles')].shape)
df_inj3[df_inj3.player.str.contains('C.J. Miles')]

(4, 5)

      game_date  Team     team_id      player   game_id
570  2010-12-29  Jazz  1610612762  C.J. Miles  21000472
579  2010-12-30  Jazz  1610612762  C.J. Miles  21000475
600  2011-01-01  Jazz  1610612762  C.J. Miles  21000491
1605 2011-04-13  Jazz  1610612762  C.J. Miles  21001226

In [167]:
print(df_inj3[df_inj3.player == 'CJ Miles'].shape)
df_inj3[df_inj3.player == 'CJ Miles']

(0, 5)

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [168]:
print(df_inj3[df_inj3.player.str.contains('CJ Miles')].shape)
df_inj3[df_inj3.player.str.contains('CJ Miles')]

(0, 5)

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [169]:
df_inj3.player.replace({'C.J. Miles': 'CJ Miles'}, inplace=True)

In [170]:
print(df_inj3[df_inj3.player.str.contains('Miles')].shape)
df_inj3[df_inj3.player.str.contains('Miles')]

(4, 5)

      game_date  Team     team_id    player   game_id
570  2010-12-29  Jazz  1610612762  CJ Miles  21000472
579  2010-12-30  Jazz  1610612762  CJ Miles  21000475
600  2011-01-01  Jazz  1610612762  CJ Miles  21000491
1605 2011-04-13  Jazz  1610612762  CJ Miles  21001226

In [171]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Miles')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
317    21000014  1610612762.0    CJ Miles          84.1 2010-10-27   84.100000
425    21000018  1610612762.0    CJ Miles          86.9 2010-10-28   85.500000
991    21000042  1610612762.0    CJ Miles         132.9 2010-10-31  101.300000
1457   21000061  1610612762.0    CJ Miles         118.4 2010-11-03  105.575000
1854   21000078  1610612762.0    CJ Miles          79.9 2010-11-05  100.440000
2057   21000086  1610612762.0    CJ Miles          92.3 2010-11-06   99.083333
2453   21000103  1610612762.0    CJ Miles         124.4 2010-11-09  102.700000
2597   21000109  1610612762.0    CJ Miles         126.8 2010-11-10  105.712500
2884   21000121  1610612762.0    CJ Miles         109.6 2010-11-12  106.144444
3100   21000130  1610612762.0    CJ Miles         137.7 2010-11-13  109.300000
3544   21000148  1610612762.0    CJ Miles         104.4 2010-11-15  108.854545
3952   21000165  1610612762.0    CJ Miles          87.2 2010-11-17  107.050000
4264   21000178  1610612762.0    CJ Miles         101.6 2010-11-19  106.630769
4516   21000189  1610612762.0    CJ Miles         105.2 2010-11-20  106.528571
4792   21000200  1610612762.0    CJ Miles         107.0 2010-11-22  106.560000
5247   21000219  1610612762.0    CJ Miles         123.2 2010-11-24  107.600000
5535   21000231  1610612762.0    CJ Miles         114.4 2010-11-26  108.000000
5859   21000245  1610612762.0    CJ Miles         130.3 2010-11-28  109.238889
6063   21000253  1610612762.0    CJ Miles         113.9 2010-11-29  109.484211
6495   21000271  1610612762.0    CJ Miles         109.3 2010-12-01  109.475000
6855   21000286  1610612762.0    CJ Miles          76.2 2010-12-03  107.890476
7360   21000307  1610612762.0    CJ Miles         105.4 2010-12-06  107.777273
7768   21000324  1610612762.0    CJ Miles          90.1 2010-12-08  107.008696
8127   21000339  1610612762.0    CJ Miles         116.3 2010-12-10  107.395833
8284   21000346  1610612762.0    CJ Miles         124.4 2010-12-11  108.076000
8608   21000359  1610612762.0    CJ Miles         112.4 2010-12-13  108.242308
9268   21000387  1610612762.0    CJ Miles          55.0 2010-12-17  106.270370
9483   21000396  1610612762.0    CJ Miles         111.9 2010-12-18  106.471429
9746   21000407  1610612762.0    CJ Miles         122.7 2010-12-20  107.031034
10201  21000426  1610612762.0    CJ Miles         121.2 2010-12-22  107.503333
10839  21000452  1610612762.0    CJ Miles          93.5 2010-12-27  107.051613
11311  21000472  1610612762.0    CJ Miles           NaN 2010-12-29  107.051613
11382  21000475  1610612762.0    CJ Miles           NaN 2010-12-30  107.051613
11779  21000491  1610612762.0    CJ Miles           NaN 2011-01-01  107.051613
12086  21000504  1610612762.0    CJ Miles         121.8 2011-01-03  107.512500
12468  21000520  1610612762.0    CJ Miles          83.8 2011-01-05  106.793939
12695  21000530  1610612762.0    CJ Miles          89.5 2011-01-07  106.285294
13001  21000543  1610612762.0    CJ Miles          88.8 2011-01-08  105.785714
13656  21000570  1610612762.0    CJ Miles         130.1 2011-01-12  106.461111
13965  21000583  1610612762.0    CJ Miles         137.9 2011-01-14  107.310811
14337  21000599  1610612762.0    CJ Miles         106.7 2011-01-17  107.294737
14696  21000614  1610612762.0    CJ Miles         106.8 2011-01-19  107.282051
15129  21000632  1610612762.0    CJ Miles         108.4 2011-01-21  107.310000
15417  21000644  1610612762.0    CJ Miles          55.7 2011-01-22  106.051220
15963  21000667  1610612762.0    CJ Miles          94.6 2011-01-25  105.778571
16196  21000676  1610612762.0    CJ Miles         107.4 2011-01-26  105.816279
16508  21000689  1610612762.0    CJ Miles         107.5 2011-01-28  105.854545
16928  21000707  1610612762.0    CJ Miles          68.6 2011-01-30  105.026667
17086  21000713  1610612762.0    CJ Miles          95.7 2011-01-31  104.823913
17447  21000728  1610612762.0    CJ Miles         101.5 2011-02-02  104.753191
17817  21000744  1610612762.0    CJ Miles         106.6 2011-02-04  104.791667
18023  21000752  1610612762.0    CJ Miles          91.3 2011-02-05  104.516327
18295  21000764  1610612762.0    CJ Miles         105.5 2011-02-07  104.536000
18690  21000780  1610612762.0    CJ Miles          81.6 2011-02-09  104.086275
19046  21000795  1610612762.0    CJ Miles          93.0 2011-02-11  103.873077
19677  21000822  1610612762.0    CJ Miles          99.3 2011-02-15  103.786792
19977  21000834  1610612762.0    CJ Miles         111.6 2011-02-16  103.931481
20498  21000856  1610612762.0    CJ Miles         105.2 2011-02-23  103.954545
20641  21000862  1610612762.0    CJ Miles         104.8 2011-02-25  103.969643
20929  21000874  1610612762.0    CJ Miles          87.2 2011-02-26  103.675439
21368  21000892  1610612762.0    CJ Miles          92.9 2011-02-28  103.489655
21873  21000913  1610612762.0    CJ Miles         105.3 2011-03-03  103.520339
22233  21000928  1610612762.0    CJ Miles          92.5 2011-03-05  103.336667
22555  21000942  1610612762.0    CJ Miles         104.8 2011-03-07  103.360656
22884  21000956  1610612762.0    CJ Miles         116.8 2011-03-09  103.577419
23273  21000972  1610612762.0    CJ Miles         103.4 2011-03-11  103.574603
23441  21000979  1610612762.0    CJ Miles         121.5 2011-03-12  103.854688
23879  21000997  1610612762.0    CJ Miles         108.8 2011-03-14  103.930769
24191  21001010  1610612762.0    CJ Miles         123.6 2011-03-16  104.228788
24899  21001040  1610612762.0    CJ Miles         113.7 2011-03-20  104.370149
25091  21001048  1610612762.0    CJ Miles          99.5 2011-03-21  104.298529
25402  21001061  1610612762.0    CJ Miles         108.6 2011-03-23  104.360870
25555  21001067  1610612762.0    CJ Miles         113.4 2011-03-24  104.490000
25986  21001085  1610612762.0    CJ Miles          76.4 2011-03-26  104.094366
26345  21001100  1610612762.0    CJ Miles          92.4 2011-03-28  103.931944
27116  21001132  1610612762.0    CJ Miles         106.0 2011-04-01  103.960274
27412  21001145  1610612762.0    CJ Miles          98.8 2011-04-03  103.890541
27799  21001161  1610612762.0    CJ Miles          81.7 2011-04-05  103.594667
28144  21001175  1610612762.0    CJ Miles          91.7 2011-04-07  103.438158
28515  21001191  1610612762.0    CJ Miles          98.0 2011-04-09  103.367532
28923  21001208  1610612762.0    CJ Miles         101.0 2011-04-11  103.337179
29377  21001226  1610612762.0    CJ Miles           NaN 2011-04-13  103.337179

In [172]:
'''
*****************************************
D.J. White
('DJ White', 94)
3
'''

"\n*****************************************\nD.J. White\n('DJ White', 94)\n3\n"

In [173]:
df_inj3[df_inj3.player == 'D.J. White']

      game_date     Team     team_id      player   game_id
352  2010-12-05  Thunder  1610612760  D.J. White  21000297
1047 2011-02-25  Bobcats  1610612766  D.J. White  21000861

In [174]:
df_inj3[df_inj3.player.str.contains('D.J. White')]

      game_date     Team     team_id      player   game_id
352  2010-12-05  Thunder  1610612760  D.J. White  21000297
1047 2011-02-25  Bobcats  1610612766  D.J. White  21000861

In [175]:
df_inj3.player.replace({'D.J. White': 'DJ White'}, inplace=True)

In [176]:
df_inj3[df_inj3.player.str.contains('D.J. White')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [177]:
df_inj3[df_inj3.player.str.contains('DJ White')]

      game_date     Team     team_id    player   game_id
352  2010-12-05  Thunder  1610612760  DJ White  21000297
1047 2011-02-25  Bobcats  1610612766  DJ White  21000861

In [178]:
'''
*****************************************
Hamady N'Diaye
('Hamady Ndiaye', 89)
4
'''

"\n*****************************************\nHamady N'Diaye\n('Hamady Ndiaye', 89)\n4\n"

In [179]:
print(df_inj3[df_inj3.player.str.contains('Hamady')].shape)
df_inj3[df_inj3.player.str.contains('Hamady')]

(12, 5)

      game_date     Team     team_id          player   game_id
252  2010-11-21  Wizards  1610612764  Hamady N'Diaye  21000192
320  2010-12-01  Wizards  1610612764  Hamady N'Diaye  21000263
514  2010-12-22  Wizards  1610612764  Hamady N'Diaye  21000423
549  2010-12-27  Wizards  1610612764  Hamady N'Diaye  21000451
1000 2011-02-13  Wizards  1610612764  Hamady N'Diaye  21000806
1164 2011-03-06  Wizards  1610612764  Hamady N'Diaye  21000934
1436 2011-04-03  Wizards  1610612764  Hamady N'Diaye  21001141
1461 2011-04-05  Wizards  1610612764  Hamady N'Diaye  21001153
1478 2011-04-06  Wizards  1610612764  Hamady N'Diaye  21001163
1503 2011-04-08  Wizards  1610612764  Hamady N'Diaye  21001179
1516 2011-04-09  Wizards  1610612764  Hamady N'Diaye  21001188
1570 2011-04-11  Wizards  1610612764  Hamady N'Diaye  21001205

In [180]:
df_inj3.player.replace({"Hamady N'Diaye" : 'Hamady Ndiaye'}, inplace=True)

In [181]:
print(df_inj3[df_inj3.player.str.contains('Hamady')].shape)
df_inj3[df_inj3.player.str.contains('Hamady')]

(12, 5)

      game_date     Team     team_id         player   game_id
252  2010-11-21  Wizards  1610612764  Hamady Ndiaye  21000192
320  2010-12-01  Wizards  1610612764  Hamady Ndiaye  21000263
514  2010-12-22  Wizards  1610612764  Hamady Ndiaye  21000423
549  2010-12-27  Wizards  1610612764  Hamady Ndiaye  21000451
1000 2011-02-13  Wizards  1610612764  Hamady Ndiaye  21000806
1164 2011-03-06  Wizards  1610612764  Hamady Ndiaye  21000934
1436 2011-04-03  Wizards  1610612764  Hamady Ndiaye  21001141
1461 2011-04-05  Wizards  1610612764  Hamady Ndiaye  21001153
1478 2011-04-06  Wizards  1610612764  Hamady Ndiaye  21001163
1503 2011-04-08  Wizards  1610612764  Hamady Ndiaye  21001179
1516 2011-04-09  Wizards  1610612764  Hamady Ndiaye  21001188
1570 2011-04-11  Wizards  1610612764  Hamady Ndiaye  21001205

In [182]:
print(df_or1011a[df_or1011a.PLAYER_NAME == 'Hamady Ndiaye'].shape)
df_or1011a[df_or1011a.PLAYER_NAME == 'Hamady Ndiaye']

(35, 6)

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
395,21000017,1610612764.0,Hamady Ndiaye,98.0,2010-10-28,98.000000
3670,21000153,1610612764.0,Hamady Ndiaye,50.0,2010-11-16,74.000000
3826,21000160,1610612764.0,Hamady Ndiaye,NaN,2010-11-17,74.000000
4173,21000174,1610612764.0,Hamady Ndiaye,NaN,2010-11-19,74.000000
5265,21000220,1610612764.0,Hamady Ndiaye,130.8,2010-11-25,92.933333
5636,21000235,1610612764.0,Hamady Ndiaye,NaN,2010-11-27,92.933333
5983,21000250,1610612764.0,Hamady Ndiaye,NaN,2010-11-29,92.933333
8685,21000362,1610612764.0,Hamady Ndiaye,NaN,2010-12-14,92.933333
9055,21000378,1610612764.0,Hamady Ndiaye,51.0,2010-12-16,82.450000
9428,21000393,1610612764.0,Hamady Ndiaye,NaN,2010-12-18,82.450000
9812,21000409,1610612764.0,Hamady Ndiaye,NaN,2010-12-20,82.450000
10615,21000443,1610612764.0,Hamady Ndiaye,NaN,2010-12-26,82.450000
19126,21000798,1610612764.0,Hamady Ndiaye,NaN,2011-02-12,82.450000
20360,21000850,1610612764.0,Hamady Ndiaye,NaN,2011-02-23,82.450000
22190,21000926,1610612764.0,Hamady Ndiaye,NaN,2011-03-05,82.450000
22761,21000950,1610612764.0,Hamady Ndiaye,56.3,2011-03-08,77.220000
23430,21000978,1610612764.0,Hamady Ndiaye,107.9,2011-03-12,82.333333
23766,21000992,1610612764.0,Hamady Ndiaye,101.2,2011-03-14,85.028571
23968,21001001,1610612764.0,Hamady Ndiaye,200.0,2011-03-15,99.400000
24397,21001019,1610612764.0,Hamady Ndiaye,112.6,2011-03-18,100.866667
24797,21001035,1610612764.0,Hamady Ndiaye,NaN,2011-03-20,100.866667
25192,21001052,1610612764.0,Hamady Ndiaye,88.8,2011-03-22,99.660000
25503,21001065,1610612764.0,Hamady Ndiaye,52.1,2011-03-23,95.336364
25768,21001076,1610612764.0,Hamady Ndiaye,115.3,2011-03-25,97.000000
26175,21001093,1610612764.0,Hamady Ndiaye,NaN,2011-03-27,97.000000
26339,21001100,1610612764.0,Hamady Ndiaye,46.6,2011-03-28,93.123077
26593,21001110,1610612764.0,Hamady Ndiaye,0.0,2011-03-30,86.471429
26906,21001123,1610612764.0,Hamady Ndiaye,0.0,2011-04-01,80.706667
27325,21001141,1610612764.0,Hamady Ndiaye,NaN,2011-04-03,80.706667
27626,21001153,1610612764.0,Hamady Ndiaye,NaN,2011-04-05,80.706667
27854,21001163,1610612764.0,Hamady Ndiaye,NaN,2011-04-06,80.706667
28237,21001179,1610612764.0,Hamady Ndiaye,NaN,2011-04-08,80.706667
28466,21001188,1610612764.0,Hamady Ndiaye,NaN,2011-04-09,80.706667
28872,21001205,1610612764.0,Hamady Ndiaye,NaN,2011-04-11,80.706667
29172,21001218,1610612764.0,Hamady Ndiaye,62.3,2011-04-13,79.556250

In [183]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady Ndiaye')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady Ndiaye')]

(35, 6)

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
395,21000017,1610612764.0,Hamady Ndiaye,98.0,2010-10-28,98.000000
3670,21000153,1610612764.0,Hamady Ndiaye,50.0,2010-11-16,74.000000
3826,21000160,1610612764.0,Hamady Ndiaye,NaN,2010-11-17,74.000000
4173,21000174,1610612764.0,Hamady Ndiaye,NaN,2010-11-19,74.000000
5265,21000220,1610612764.0,Hamady Ndiaye,130.8,2010-11-25,92.933333
5636,21000235,1610612764.0,Hamady Ndiaye,NaN,2010-11-27,92.933333
5983,21000250,1610612764.0,Hamady Ndiaye,NaN,2010-11-29,92.933333
8685,21000362,1610612764.0,Hamady Ndiaye,NaN,2010-12-14,92.933333
9055,21000378,1610612764.0,Hamady Ndiaye,51.0,2010-12-16,82.450000
9428,21000393,1610612764.0,Hamady Ndiaye,NaN,2010-12-18,82.450000
9812,21000409,1610612764.0,Hamady Ndiaye,NaN,2010-12-20,82.450000
10615,21000443,1610612764.0,Hamady Ndiaye,NaN,2010-12-26,82.450000
19126,21000798,1610612764.0,Hamady Ndiaye,NaN,2011-02-12,82.450000
20360,21000850,1610612764.0,Hamady Ndiaye,NaN,2011-02-23,82.450000
22190,21000926,1610612764.0,Hamady Ndiaye,NaN,2011-03-05,82.450000
22761,21000950,1610612764.0,Hamady Ndiaye,56.3,2011-03-08,77.220000
23430,21000978,1610612764.0,Hamady Ndiaye,107.9,2011-03-12,82.333333
23766,21000992,1610612764.0,Hamady Ndiaye,101.2,2011-03-14,85.028571
23968,21001001,1610612764.0,Hamady Ndiaye,200.0,2011-03-15,99.400000
24397,21001019,1610612764.0,Hamady Ndiaye,112.6,2011-03-18,100.866667
24797,21001035,1610612764.0,Hamady Ndiaye,NaN,2011-03-20,100.866667
25192,21001052,1610612764.0,Hamady Ndiaye,88.8,2011-03-22,99.660000
25503,21001065,1610612764.0,Hamady Ndiaye,52.1,2011-03-23,95.336364
25768,21001076,1610612764.0,Hamady Ndiaye,115.3,2011-03-25,97.000000
26175,21001093,1610612764.0,Hamady Ndiaye,NaN,2011-03-27,97.000000
26339,21001100,1610612764.0,Hamady Ndiaye,46.6,2011-03-28,93.123077
26593,21001110,1610612764.0,Hamady Ndiaye,0.0,2011-03-30,86.471429
26906,21001123,1610612764.0,Hamady Ndiaye,0.0,2011-04-01,80.706667
27325,21001141,1610612764.0,Hamady Ndiaye,NaN,2011-04-03,80.706667
27626,21001153,1610612764.0,Hamady Ndiaye,NaN,2011-04-05,80.706667
27854,21001163,1610612764.0,Hamady Ndiaye,NaN,2011-04-06,80.706667
28237,21001179,1610612764.0,Hamady Ndiaye,NaN,2011-04-08,80.706667
28466,21001188,1610612764.0,Hamady Ndiaye,NaN,2011-04-09,80.706667
28872,21001205,1610612764.0,Hamady Ndiaye,NaN,2011-04-11,80.706667
29172,21001218,1610612764.0,Hamady Ndiaye,62.3,2011-04-13,79.556250

In [184]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady')].sort_values(by='game_date')

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
395,21000017,1610612764.0,Hamady Ndiaye,98.0,2010-10-28,98.000000
3670,21000153,1610612764.0,Hamady Ndiaye,50.0,2010-11-16,74.000000
3826,21000160,1610612764.0,Hamady Ndiaye,NaN,2010-11-17,74.000000
4173,21000174,1610612764.0,Hamady Ndiaye,NaN,2010-11-19,74.000000
5265,21000220,1610612764.0,Hamady Ndiaye,130.8,2010-11-25,92.933333
5636,21000235,1610612764.0,Hamady Ndiaye,NaN,2010-11-27,92.933333
5983,21000250,1610612764.0,Hamady Ndiaye,NaN,2010-11-29,92.933333
8685,21000362,1610612764.0,Hamady Ndiaye,NaN,2010-12-14,92.933333
9055,21000378,1610612764.0,Hamady Ndiaye,51.0,2010-12-16,82.450000
9428,21000393,1610612764.0,Hamady Ndiaye,NaN,2010-12-18,82.450000
9812,21000409,1610612764.0,Hamady Ndiaye,NaN,2010-12-20,82.450000
10615,21000443,1610612764.0,Hamady Ndiaye,NaN,2010-12-26,82.450000
19126,21000798,1610612764.0,Hamady Ndiaye,NaN,2011-02-12,82.450000
20360,21000850,1610612764.0,Hamady Ndiaye,NaN,2011-02-23,82.450000
22190,21000926,1610612764.0,Hamady Ndiaye,NaN,2011-03-05,82.450000
22761,21000950,1610612764.0,Hamady Ndiaye,56.3,2011-03-08,77.220000
23430,21000978,1610612764.0,Hamady Ndiaye,107.9,2011-03-12,82.333333
23766,21000992,1610612764.0,Hamady Ndiaye,101.2,2011-03-14,85.028571
23968,21001001,1610612764.0,Hamady Ndiaye,200.0,2011-03-15,99.400000
24397,21001019,1610612764.0,Hamady Ndiaye,112.6,2011-03-18,100.866667
24797,21001035,1610612764.0,Hamady Ndiaye,NaN,2011-03-20,100.866667
25192,21001052,1610612764.0,Hamady Ndiaye,88.8,2011-03-22,99.660000
25503,21001065,1610612764.0,Hamady Ndiaye,52.1,2011-03-23,95.336364
25768,21001076,1610612764.0,Hamady Ndiaye,115.3,2011-03-25,97.000000
26175,21001093,1610612764.0,Hamady Ndiaye,NaN,2011-03-27,97.000000
26339,21001100,1610612764.0,Hamady Ndiaye,46.6,2011-03-28,93.123077
26593,21001110,1610612764.0,Hamady Ndiaye,0.0,2011-03-30,86.471429
26906,21001123,1610612764.0,Hamady Ndiaye,0.0,2011-04-01,80.706667
27325,21001141,1610612764.0,Hamady Ndiaye,NaN,2011-04-03,80.706667
27626,21001153,1610612764.0,Hamady Ndiaye,NaN,2011-04-05,80.706667
27854,21001163,1610612764.0,Hamady Ndiaye,NaN,2011-04-06,80.706667
28237,21001179,1610612764.0,Hamady Ndiaye,NaN,2011-04-08,80.706667
28466,21001188,1610612764.0,Hamady Ndiaye,NaN,2011-04-09,80.706667
28872,21001205,1610612764.0,Hamady Ndiaye,NaN,2011-04-11,80.706667
29172,21001218,1610612764.0,Hamady Ndiaye,62.3,2011-04-13,79.556250

In [185]:
df_inj3[df_inj3.player.str.contains('Hamady')]

      game_date     Team     team_id         player   game_id
252  2010-11-21  Wizards  1610612764  Hamady Ndiaye  21000192
320  2010-12-01  Wizards  1610612764  Hamady Ndiaye  21000263
514  2010-12-22  Wizards  1610612764  Hamady Ndiaye  21000423
549  2010-12-27  Wizards  1610612764  Hamady Ndiaye  21000451
1000 2011-02-13  Wizards  1610612764  Hamady Ndiaye  21000806
1164 2011-03-06  Wizards  1610612764  Hamady Ndiaye  21000934
1436 2011-04-03  Wizards  1610612764  Hamady Ndiaye  21001141
1461 2011-04-05  Wizards  1610612764  Hamady Ndiaye  21001153
1478 2011-04-06  Wizards  1610612764  Hamady Ndiaye  21001163
1503 2011-04-08  Wizards  1610612764  Hamady Ndiaye  21001179
1516 2011-04-09  Wizards  1610612764  Hamady Ndiaye  21001188
1570 2011-04-11  Wizards  1610612764  Hamady Ndiaye  21001205

In [186]:
'''
*****************************************
J.J. Hickson
('JJ Hickson', 95)
5
'''

"\n*****************************************\nJ.J. Hickson\n('JJ Hickson', 95)\n5\n"

In [187]:
print(df_inj3[df_inj3.player.str.contains('Hickson')].shape)
df_inj3[df_inj3.player.str.contains('Hickson')]

(1, 5)

     game_date       Team     team_id        player   game_id
338 2010-12-04  Cavaliers  1610612739  J.J. Hickson  21000291

In [188]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hickson')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hickson')]

(81, 6)

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
85     21000004  1610612739.0  JJ Hickson         102.1 2010-10-27  102.100000
505    21000022  1610612739.0  JJ Hickson          52.2 2010-10-29   77.150000
757    21000032  1610612739.0  JJ Hickson         107.7 2010-10-30   87.333333
1117   21000047  1610612739.0  JJ Hickson         100.1 2010-11-02   90.525000
1657   21000070  1610612739.0  JJ Hickson         118.5 2010-11-05   96.120000
1921   21000081  1610612739.0  JJ Hickson         104.8 2010-11-06   97.566667
2425   21000102  1610612739.0  JJ Hickson         102.0 2010-11-09   98.200000
2677   21000112  1610612739.0  JJ Hickson          96.6 2010-11-10   98.000000
3156   21000132  1610612739.0  JJ Hickson          85.0 2010-11-13   96.555556
3612   21000151  1610612739.0  JJ Hickson         109.8 2010-11-16   97.880000
4224   21000177  1610612739.0  JJ Hickson          76.1 2010-11-19   95.900000
4464   21000187  1610612739.0  JJ Hickson          82.8 2010-11-20   94.808333
4847   21000203  1610612739.0  JJ Hickson          72.3 2010-11-23   93.076923
5027   21000210  1610612739.0  JJ Hickson          95.8 2010-11-24   93.271429
5327   21000223  1610612739.0  JJ Hickson          99.1 2010-11-26   93.660000
5651   21000236  1610612739.0  JJ Hickson         108.2 2010-11-27   94.568750
6082   21000254  1610612739.0  JJ Hickson          97.1 2010-11-30   94.717647
6539   21000273  1610612739.0  JJ Hickson          80.8 2010-12-02   93.944444
7079   21000296  1610612739.0  JJ Hickson         103.9 2010-12-05   94.468421
7439   21000311  1610612739.0  JJ Hickson          96.7 2010-12-07   94.580000
7601   21000317  1610612739.0  JJ Hickson          72.7 2010-12-08   93.538095
8308   21000347  1610612739.0  JJ Hickson          88.9 2010-12-11   93.327273
8427   21000352  1610612739.0  JJ Hickson          62.5 2010-12-12   91.986957
8883   21000371  1610612739.0  JJ Hickson          95.1 2010-12-15   92.116667
9123   21000381  1610612739.0  JJ Hickson          92.1 2010-12-17   92.116000
9448   21000394  1610612739.0  JJ Hickson         104.6 2010-12-18   92.596154
9759   21000407  1610612739.0  JJ Hickson         106.2 2010-12-20   93.100000
10081  21000421  1610612739.0  JJ Hickson          77.6 2010-12-22   92.546429
10527  21000439  1610612739.0  JJ Hickson          85.4 2010-12-26   92.300000
10909  21000455  1610612739.0  JJ Hickson         103.7 2010-12-28   92.680000
11091  21000463  1610612739.0  JJ Hickson          96.7 2010-12-29   92.809677
11618  21000485  1610612739.0  JJ Hickson          92.4 2011-01-01   92.796875
11869  21000495  1610612739.0  JJ Hickson          86.7 2011-01-02   92.612121
12282  21000512  1610612739.0  JJ Hickson           NaN 2011-01-05   92.612121
12787  21000534  1610612739.0  JJ Hickson          99.3 2011-01-07   92.808824
13092  21000547  1610612739.0  JJ Hickson         105.3 2011-01-09   93.165714
13402  21000560  1610612739.0  JJ Hickson          51.0 2011-01-11   91.994444
13950  21000583  1610612739.0  JJ Hickson         110.0 2011-01-14   92.481081
14214  21000594  1610612739.0  JJ Hickson          96.0 2011-01-15   92.573684
14681  21000613  1610612739.0  JJ Hickson          97.5 2011-01-19   92.700000
15161  21000633  1610612739.0  JJ Hickson          91.4 2011-01-21   92.667500
15437  21000645  1610612739.0  JJ Hickson          70.8 2011-01-22   92.134146
15629  21000653  1610612739.0  JJ Hickson          88.1 2011-01-24   92.038095
15893  21000664  1610612739.0  JJ Hickson          95.7 2011-01-25   92.123256
16409  21000685  1610612739.0  JJ Hickson         114.5 2011-01-28   92.631818
16829  21000703  1610612739.0  JJ Hickson          70.3 2011-01-30   92.135556
16997  21000710  1610612739.0  JJ Hickson         106.1 2011-01-31   92.439130
17250  21000720  1610612739.0  JJ Hickson         102.6 2011-02-02   92.655319
17742  21000741  1610612739.0  JJ Hickson         101.7 2011-02-04   92.843750
17898  21000747  1610612739.0  JJ Hickson         101.0 2011-02-05   93.010204
18221  21000761  1610612739.0  JJ Hickson         102.3 2011-02-07   93.196000
18519  21000773  1610612739.0  JJ Hickson         113.3 2011-02-09   93.590196
18949  21000791  1610612739.0  JJ Hickson         109.0 2011-02-11   93.886538
19309  21000806  1610612739.0  JJ Hickson          94.8 2011-02-13   93.903774
19811  21000827  1610612739.0  JJ Hickson         103.8 2011-02-16   94.087037
20291  21000847  1610612739.0  JJ Hickson         110.9 2011-02-23   94.392727
20721  21000865  1610612739.0  JJ Hickson         110.3 2011-02-25   94.676786
21102  21000881  1610612739.0  JJ Hickson          95.9 2011-02-27   94.698246
21629  21000903  1610612739.0  JJ Hickson          90.6 2011-03-02   94.627586
22001  21000919  1610612739.0  JJ Hickson         129.7 2011-03-04   95.222034
22420  21000936  1610612739.0  JJ Hickson          87.5 2011-03-06   95.093333
22707  21000948  1610612739.0  JJ Hickson          76.5 2011-03-08   94.788525
22958  21000959  1610612739.0  JJ Hickson          88.3 2011-03-09   94.683871
23590  21000985  1610612739.0  JJ Hickson          98.8 2011-03-13   94.749206
24202  21001011  1610612739.0  JJ Hickson         106.1 2011-03-16   94.926563
24322  21001016  1610612739.0  JJ Hickson          71.5 2011-03-17   94.566154
24634  21001029  1610612739.0  JJ Hickson         102.1 2011-03-19   94.680303
25006  21001044  1610612739.0  JJ Hickson          82.2 2011-03-21   94.494030
25268  21001055  1610612739.0  JJ Hickson          97.1 2011-03-23   94.532353
25652  21001071  1610612739.0  JJ Hickson         115.3 2011-03-25   94.833333
26059  21001088  1610612739.0  JJ Hickson          81.9 2011-03-27   94.648571
26370  21001101  1610612739.0  JJ Hickson         109.5 2011-03-29   94.857746
26478  21001106  1610612739.0  JJ Hickson         115.7 2011-03-30   95.147222
26886  21001123  1610612739.0  JJ Hickson         112.9 2011-04-01   95.390411
27365  21001143  1610612739.0  JJ Hickson         110.9 2011-04-03   95.600000
27545  21001150  1610612739.0  JJ Hickson          98.6 2011-04-05   95.640000
27917  21001166  1610612739.0  JJ Hickson         122.9 2011-04-06   95.998684
28265  21001180  1610612739.0  JJ Hickson          89.7 2011-04-08   95.916883
28492  21001190  1610612739.0  JJ Hickson         116.0 2011-04-09   96.174359
28876  21001206  1610612739.0  JJ Hickson         108.9 2011-04-11   96.335443
29176  21001218  1610612739.0  JJ Hickson         100.8 2011-04-13   96.391250

In [189]:
#df_injuries[df_injuries.player == 'J.J. Hickson']
df_inj3.player.replace({'J.J. Hickson': 'JJ Hickson'}, inplace=True)

In [190]:
print(df_inj3[df_inj3.player.str.contains('Hickson')].shape)
df_inj3[df_inj3.player.str.contains('Hickson')]

(1, 5)

     game_date       Team     team_id      player   game_id
338 2010-12-04  Cavaliers  1610612739  JJ Hickson  21000291

In [191]:
'''
*****************************************
J.J. Redick
('JJ Redick', 94)
6
'''

"\n*****************************************\nJ.J. Redick\n('JJ Redick', 94)\n6\n"

In [192]:
df_inj3[df_inj3.player.str.contains('Redick')]

      game_date   Team     team_id     player   game_id
206  2010-11-15  Magic  1610612753  JJ Redick  21000145
314  2010-12-01  Magic  1610612753  JJ Redick  21000266
331  2010-12-03  Magic  1610612753  JJ Redick  21000279
341  2010-12-04  Magic  1610612753  JJ Redick  21000292
870  2011-01-31  Magic  1610612753  JJ Redick  21000711
1210 2011-03-11  Magic  1610612753  JJ Redick  21000975
1254 2011-03-16  Magic  1610612753  JJ Redick  21001007
1262 2011-03-18  Magic  1610612753  JJ Redick  21001018
1293 2011-03-21  Magic  1610612753  JJ Redick  21001044
1306 2011-03-23  Magic  1610612753  JJ Redick  21001059
1325 2011-03-25  Magic  1610612753  JJ Redick  21001069
1356 2011-03-28  Magic  1610612753  JJ Redick  21000051
1378 2011-03-30  Magic  1610612753  JJ Redick  21001105
1405 2011-04-01  Magic  1610612753  JJ Redick  21001121
1428 2011-04-03  Magic  1610612753  JJ Redick  21001144
1452 2011-04-05  Magic  1610612753  JJ Redick  21001152
1467 2011-04-06  Magic  1610612753  JJ Redick  21001162
1523 2011-04-10  Magic  1610612753  JJ Redick  21001193
1549 2011-04-11  Magic  1610612753  JJ Redick  21001204
1613 2011-04-13  Magic  1610612753  JJ Redick  21001219

In [193]:
'''
*****************************************
John Wallace
('John Wall', 86)
7
'''

"\n*****************************************\nJohn Wallace\n('John Wall', 86)\n7\n"

In [194]:
df_inj3[df_inj3.player.str.contains('John Wall')]

     game_date     Team     team_id        player   game_id
221 2010-11-16  Wizards  1610612764    John Wall   21000153
253 2010-11-21  Wizards  1610612764    John Wall   21000192
291 2010-11-27  Wizards  1610612764    John Wall   21000235
306 2010-11-29  Wizards  1610612764    John Wall   21000250
378 2010-12-08  Wizards  1610612764    John Wall   21000325
422 2010-12-14  Wizards  1610612764    John Wall   21000362
441 2010-12-16  Wizards  1610612764  John Wallace  21000378
468 2010-12-18  Wizards  1610612764  John Wallace  21000393

In [195]:
df_inj3[df_inj3.player.str.contains('Wallace')]

      game_date     Team     team_id          player   game_id
423  2010-12-15  Bobcats  1610612766  Gerald Wallace  21000372
441  2010-12-16  Wizards  1610612764    John Wallace  21000378
468  2010-12-18  Wizards  1610612764    John Wallace  21000393
617  2011-01-03  Bobcats  1610612766  Gerald Wallace  21000499
692  2011-01-12  Pistons  1610612765     Ben Wallace  21000565
1046 2011-02-25  Blazers  1610612757  Gerald Wallace  21000872
1309 2011-03-23  Pistons  1610612765     Ben Wallace  21001058
1310 2011-03-23  Pistons  1610612765     Ben Wallace  21001058
1474 2011-04-06  Pistons  1610612765     Ben Wallace  21001167
1582 2011-04-13  Blazers  1610612757  Gerald Wallace  21001227

In [196]:
df_inj3.player.replace({'John Wallace' : 'John Wall'}, inplace=True)

In [197]:
df_inj3[df_inj3.player.str.contains('John Wall')]

     game_date     Team     team_id      player   game_id
221 2010-11-16  Wizards  1610612764  John Wall   21000153
253 2010-11-21  Wizards  1610612764  John Wall   21000192
291 2010-11-27  Wizards  1610612764  John Wall   21000235
306 2010-11-29  Wizards  1610612764  John Wall   21000250
378 2010-12-08  Wizards  1610612764  John Wall   21000325
422 2010-12-14  Wizards  1610612764  John Wall   21000362
441 2010-12-16  Wizards  1610612764   John Wall  21000378
468 2010-12-18  Wizards  1610612764   John Wall  21000393

In [198]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('John Wall')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('John Wall')]

(75, 6)

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date       cma2
388    21000017  1610612764.0   John Wall          75.8 2010-10-28  75.800000
724    21000031  1610612764.0   John Wall         102.1 2010-10-30  88.950000
1144   21000048  1610612764.0   John Wall         102.5 2010-11-02  93.466667
1708   21000072  1610612764.0   John Wall          89.4 2010-11-05  92.450000
1936   21000081  1610612764.0   John Wall         101.3 2010-11-06  94.220000
2656   21000111  1610612764.0   John Wall         103.8 2010-11-10  95.816667
2967   21000124  1610612764.0   John Wall          88.4 2010-11-12  94.757143
3195   21000134  1610612764.0   John Wall          88.7 2010-11-13  94.000000
4593   21000192  1610612764.0   John Wall           NaN 2010-11-21  94.000000
4912   21000205  1610612764.0   John Wall         117.0 2010-11-23  96.555556
5258   21000220  1610612764.0   John Wall          84.7 2010-11-25  95.370000
5637   21000235  1610612764.0   John Wall           NaN 2010-11-27  95.370000
5984   21000250  1610612764.0   John Wall           NaN 2010-11-29  95.370000
6292   21000263  1610612764.0   John Wall         106.5 2010-12-01  96.381818
6637   21000277  1610612764.0   John Wall          91.0 2010-12-03  95.933333
7178   21000300  1610612764.0   John Wall         114.3 2010-12-05  97.346154
7538   21000315  1610612764.0   John Wall         106.5 2010-12-07  98.000000
7785   21000325  1610612764.0   John Wall           NaN 2010-12-08  98.000000
7958   21000332  1610612764.0   John Wall          95.4 2010-12-10  97.826667
9057   21000378  1610612764.0   John Wall           NaN 2010-12-16  97.826667
10611  21000443  1610612764.0   John Wall          77.0 2010-12-26  96.525000
10802  21000451  1610612764.0   John Wall          96.1 2010-12-27  96.500000
11127  21000464  1610612764.0   John Wall         111.9 2010-12-29  97.355556
11448  21000478  1610612764.0   John Wall          88.7 2010-12-31  96.900000
11604  21000484  1610612764.0   John Wall         101.7 2011-01-01  97.140000
12336  21000515  1610612764.0   John Wall         112.6 2011-01-05  97.876190
12633  21000527  1610612764.0   John Wall         100.6 2011-01-07  98.000000
12858  21000537  1610612764.0   John Wall         101.9 2011-01-08  98.169565
13322  21000556  1610612764.0   John Wall         127.6 2011-01-11  99.395833
13714  21000573  1610612764.0   John Wall          93.3 2011-01-13  99.152000
14108  21000589  1610612764.0   John Wall          91.7 2011-01-15  98.865385
14348  21000599  1610612764.0   John Wall         122.8 2011-01-17  99.751852
14767  21000617  1610612764.0   John Wall          96.4 2011-01-19  99.632143
15187  21000634  1610612764.0   John Wall          86.2 2011-01-21  99.168966
15355  21000641  1610612764.0   John Wall          91.0 2011-01-22  98.896667
15726  21000657  1610612764.0   John Wall          88.3 2011-01-24  98.554839
15883  21000663  1610612764.0   John Wall         107.1 2011-01-25  98.821875
16471  21000688  1610612764.0   John Wall         100.4 2011-01-28  98.869697
16615  21000694  1610612764.0   John Wall          94.8 2011-01-29  98.750000
17047  21000712  1610612764.0   John Wall          93.6 2011-01-31  98.602857
17119  21000715  1610612764.0   John Wall          94.0 2011-02-01  98.475000
17661  21000737  1610612764.0   John Wall         101.9 2011-02-04  98.567568
17876  21000746  1610612764.0   John Wall         103.6 2011-02-05  98.700000
18641  21000778  1610612764.0   John Wall         110.0 2011-02-09  98.989744
19119  21000798  1610612764.0   John Wall          81.7 2011-02-12  98.557500
19299  21000806  1610612764.0   John Wall         126.8 2011-02-13  99.246341
19729  21000824  1610612764.0   John Wall          72.6 2011-02-16  98.611905
20101  21000839  1610612764.0   John Wall          74.6 2011-02-22  98.053488
20353  21000850  1610612764.0   John Wall          98.6 2011-02-23  98.065909
20735  21000866  1610612764.0   John Wall         119.4 2011-02-25  98.540000
20913  21000873  1610612764.0   John Wall          93.1 2011-02-26  98.421739
21320  21000890  1610612764.0   John Wall          91.0 2011-02-28  98.263830
21655  21000904  1610612764.0   John Wall         101.1 2011-03-02  98.322917
22183  21000926  1610612764.0   John Wall         103.0 2011-03-05  98.418367
22362  21000934  1610612764.0   John Wall         105.2 2011-03-06  98.554000
22757  21000950  1610612764.0   John Wall          82.9 2011-03-08  98.247059
23425  21000978  1610612764.0   John Wall          90.8 2011-03-12  98.103846
23760  21000992  1610612764.0   John Wall          88.6 2011-03-14  97.924528
23964  21001001  1610612764.0   John Wall          88.8 2011-03-15  97.755556
24396  21001019  1610612764.0   John Wall         112.7 2011-03-18  98.027273
24792  21001035  1610612764.0   John Wall         105.4 2011-03-20  98.158929
25188  21001052  1610612764.0   John Wall          90.4 2011-03-22  98.022807
25499  21001065  1610612764.0   John Wall         100.6 2011-03-23  98.067241
25763  21001076  1610612764.0   John Wall         100.6 2011-03-25  98.110169
26169  21001093  1610612764.0   John Wall          97.4 2011-03-27  98.098333
26337  21001100  1610612764.0   John Wall          97.1 2011-03-28  98.081967
26589  21001110  1610612764.0   John Wall         120.8 2011-03-30  98.448387
26907  21001123  1610612764.0   John Wall           NaN 2011-04-01  98.448387
27320  21001141  1610612764.0   John Wall         104.8 2011-04-03  98.549206
27620  21001153  1610612764.0   John Wall         107.7 2011-04-05  98.692188
27848  21001163  1610612764.0   John Wall         105.9 2011-04-06  98.803077
28232  21001179  1610612764.0   John Wall          83.9 2011-04-08  98.577273
28460  21001188  1610612764.0   John Wall         120.2 2011-04-09  98.900000
28867  21001205  1610612764.0   John Wall          85.2 2011-04-11  98.698529
29167  21001218  1610612764.0   John Wall         116.1 2011-04-13  98.950725

In [199]:
df_injuries[df_injuries.player.str.contains('John Wall')].drop(columns=['A'])

,Date,Team,Acquired,Relinquished,Notes,team_id,player
347,2010-11-16,Wizards,,John Wall,placed on IL with sprained left foot,1610612764,John Wall
400,2010-11-21,Wizards,John Wall,,activated from IL,1610612764,John Wall
401,2010-11-21,Wizards,,John Wall,sprained left foot (DNP),1610612764,John Wall
468,2010-11-27,Wizards,,John Wall,bruised right knee (P) / sore left knee (CBC) (DNP),1610612764,John Wall
491,2010-11-29,Wizards,,John Wall,bruised right knee (P) (DNP),1610612764,John Wall
617,2010-12-08,Wizards,,John Wall,sore left foot (DNP),1610612764,John Wall
696,2010-12-14,Wizards,,John Wall,placed on IL with right knee tendinitis (P) / sore left foot (CBC),1610612764,John Wall
729,2010-12-16,Wizards,,John Wallace,right knee tendinitis (DNP),1610612764,John Wallace
731,2010-12-16,Wizards,John Wallace,,activated,1610612764,John Wallace
773,2010-12-18,Wizards,,John Wallace,placed on IL with right knee tendinitis,1610612764,John Wallace
884,2010-12-26,Wizards,John Wallace,,activated from IL,1610612764,John Wallace
5031,2012-09-28,Wizards,,John Wall,stress fracture in left kneecap (out indefinitely),1610612764,John Wall
5055,2012-10-30,Wizards,,John Wall,placed on IL with strained left knee,1610612764,John Wall
6029,2013-01-12,Wizards,John Wall,,activated from IL,1610612764,John Wall
12727,2015-04-08,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
12795,2015-04-12,Wizards,John Wall,,activated from IL,1610612764,John Wall
12872,2015-04-15,Wizards,,John Wall,rest (DTD),1610612764,John Wall
12889,2015-04-18,Wizards,John Wall,,returned to lineup,1610612764,John Wall
12961,2015-05-05,Wizards,,John Wall,placed on IL with fractured left hand/wrist,1610612764,John Wall
12976,2015-05-13,Wizards,John Wall,,activated from IL,1610612764,John Wall
15471,2016-04-06,Wizards,,John Wall,placed on IL with sore/swollen right knee (out for season),1610612764,John Wall
15784,2016-05-05,Wizards,,John Wall,surgery on left knee to remove calcium deposits (out indefinitely),1610612764,John Wall
16102,2016-11-05,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
16127,2016-11-07,Wizards,John Wall,,activated from IL,1610612764,John Wall
16195,2016-11-12,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
16260,2016-11-16,Wizards,John Wall,,activated from IL,1610612764,John Wall
18691,2017-04-10,Wizards,,John Wall,rest / quadriceps injury (DTD),1610612764,John Wall
18786,2017-04-12,Wizards,John Wall,,activated from IL,1610612764,John Wall
18791,2017-04-12,Wizards,,John Wall,rest (DTD),1610612764,John Wall
18837,2017-04-16,Wizards,John Wall,,returned to lineup,1610612764,John Wall
19383,2017-11-05,Wizards,,John Wall,placed on IL with sprained left shoulder,1610612764,John Wall
19408,2017-11-07,Wizards,John Wall,,activated from IL,1610612764,John Wall
19626,2017-11-19,Wizards,,John Wall,sore left knee / left knee inflammation (DTD),1610612764,John Wall
19643,2017-11-20,Wizards,John Wall,,returned to lineup,1610612764,John Wall
19718,2017-11-25,Wizards,,John Wall,placed on IL with sore left knee / left knee inflammation,1610612764,John Wall
20063,2017-12-13,Wizards,John Wall,,activated from IL,1610612764,John Wall
20826,2018-01-27,Wizards,,John Wall,placed on IL with sore left knee,1610612764,John Wall
20909,2018-01-31,Wizards,,John Wall,arthroscopic surgery on left knee (out indefinitely),1610612764,John Wall
21875,2018-03-31,Wizards,John Wall,,activated from IL,1610612764,John Wall
21910,2018-04-01,Wizards,,John Wall,rest (DTD),1610612764,John Wall
22033,2018-04-06,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
22119,2018-04-10,Wizards,John Wall,,activated from IL,1610612764,John Wall
22155,2018-04-11,Wizards,,John Wall,placed on IL for rest (out for season),1610612764,John Wall

In [200]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains(' Wall')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
98,21000005,1610612765.0,Ben Wallace,102.3,2010-10-27,102.300000
264,21000012,1610612766.0,Gerald Wallace,86.8,2010-10-27,86.800000
388,21000017,1610612764.0,John Wall,75.8,2010-10-28,75.800000
444,21000019,1610612766.0,Gerald Wallace,110.7,2010-10-29,98.750000
566,21000024,1610612765.0,Ben Wallace,94.5,2010-10-29,98.400000
724,21000031,1610612764.0,John Wall,102.1,2010-10-30,88.950000
818,21000035,1610612765.0,Ben Wallace,80.4,2010-10-30,92.400000
888,21000038,1610612766.0,Gerald Wallace,103.7,2010-10-30,100.400000
1144,21000048,1610612764.0,John Wall,102.5,2010-11-02,93.466667
1166,21000049,1610612765.0,Ben Wallace,103.7,2010-11-02,95.225000
1274,21000054,1610612765.0,Ben Wallace,95.2,2010-11-03,95.220000
1296,21000055,1610612766.0,Gerald Wallace,107.3,2010-11-03,102.125000
1680,21000071,1610612766.0,Gerald Wallace,113.1,2010-11-05,104.320000
1694,21000071,1610612765.0,Ben Wallace,105.6,2010-11-05,96.950000
1708,21000072,1610612764.0,John Wall,89.4,2010-11-05,92.450000
1908,21000080,1610612766.0,Gerald Wallace,90.2,2010-11-06,101.966667
1936,21000081,1610612764.0,John Wall,101.3,2010-11-06,94.220000
2174,21000091,1610612765.0,Ben Wallace,98.0,2010-11-07,97.100000
2268,21000095,1610612766.0,Gerald Wallace,95.1,2010-11-08,100.985714
2522,21000106,1610612765.0,Ben Wallace,90.3,2010-11-09,96.250000
2616,21000110,1610612766.0,Gerald Wallace,118.6,2010-11-10,103.187500
2656,21000111,1610612764.0,John Wall,103.8,2010-11-10,95.816667
2951,21000124,1610612766.0,Gerald Wallace,111.8,2010-11-12,104.144444
2967,21000124,1610612764.0,John Wall,88.4,2010-11-12,94.757143
3073,21000129,1610612765.0,Ben Wallace,80.0,2010-11-12,94.444444
3107,21000130,1610612766.0,Gerald Wallace,105.5,2010-11-13,104.280000
3195,21000134,1610612764.0,John Wall,88.7,2010-11-13,94.000000
3337,21000140,1610612765.0,Ben Wallace,107.9,2010-11-14,95.790000
3443,21000144,1610612766.0,Gerald Wallace,117.1,2010-11-15,105.445455
3553,21000149,1610612765.0,Ben Wallace,103.0,2010-11-15,96.445455
3853,21000161,1610612765.0,Ben Wallace,86.0,2010-11-17,95.575000
4175,21000175,1610612766.0,Gerald Wallace,91.7,2010-11-19,104.300000
4355,21000182,1610612766.0,Gerald Wallace,112.8,2010-11-20,104.953846
4593,21000192,1610612764.0,John Wall,NaN,2010-11-21,94.000000
4596,21000192,1610612765.0,Ben Wallace,105.0,2010-11-21,96.300000
4912,21000205,1610612764.0,John Wall,117.0,2010-11-23,96.555556
4919,21000206,1610612766.0,Gerald Wallace,109.3,2010-11-23,105.264286
4944,21000207,1610612765.0,Ben Wallace,84.5,2010-11-23,95.457143
5002,21000209,1610612766.0,Gerald Wallace,109.6,2010-11-24,105.553333
5112,21000214,1610612765.0,Ben Wallace,87.4,2010-11-24,94.920000
5258,21000220,1610612764.0,John Wall,84.7,2010-11-25,95.370000
5314,21000222,1610612766.0,Gerald Wallace,97.4,2010-11-26,105.043750
5388,21000225,1610612765.0,Ben Wallace,129.5,2010-11-26,97.081250
5637,21000235,1610612764.0,John Wall,NaN,2010-11-27,95.370000
5734,21000240,1610612766.0,Gerald Wallace,114.2,2010-11-27,105.582353
5819,21000243,1610612765.0,Ben Wallace,117.4,2010-11-28,98.276471
5984,21000250,1610612764.0,John Wall,NaN,2010-11-29,95.370000
6095,21000255,1610612765.0,Ben Wallace,87.1,2010-11-30,97.655556
6292,21000263,1610612764.0,John Wall,106.5,2010-12-01,96.381818
6336,21000265,1610612765.0,Ben Wallace,59.8,2010-12-01,95.663158
6382,21000267,1610612766.0,Gerald Wallace,81.2,2010-12-01,104.227778
6586,21000275,1610612766.0,Gerald Wallace,86.2,2010-12-03,103.278947
6637,21000277,1610612764.0,John Wall,91.0,2010-12-03,95.933333
6684,21000279,1610612765.0,Ben Wallace,109.6,2010-12-03,96.360000
6910,21000289,1610612766.0,Gerald Wallace,86.9,2010-12-04,102.460000
7092,21000296,1610612765.0,Ben Wallace,140.0,2010-12-05,98.438095
7178,21000300,1610612764.0,John Wall,114.3,2010-12-05,97.346154
7426,21000310,1610612766.0,Gerald Wallace,102.5,2010-12-07,102.461905
7488,21000313,1610612765.0,Ben Wallace,87.3,2010-12-07,97.931818
7538,21000315,1610612764.0,John Wall,106.5,2010-12-07,98.000000
7680,21000321,1610612765.0,Ben Wallace,90.8,2010-12-08,97.621739
7785,21000325,1610612764.0,John Wall,NaN,2010-12-08,98.000000
7894,21000330,1610612766.0,Gerald Wallace,103.3,2010-12-10,102.500000
7958,21000332,1610612764.0,John Wall,95.4,2010-12-10,97.826667
8001,21000334,1610612765.0,Ben Wallace,NaN,2010-12-10,97.621739
8218,21000343,1610612766.0,Gerald Wallace,71.1,2010-12-11,101.134783
8244,21000344,1610612765.0,Ben Wallace,119.1,2010-12-11,98.516667
8626,21000360,1610612766.0,Gerald Wallace,106.0,2010-12-14,101.337500
8700,21000363,1610612765.0,Ben Wallace,105.6,2010-12-14,98.800000
9057,21000378,1610612764.0,John Wall,NaN,2010-12-16,97.826667
9252,21000386,1610612765.0,Ben Wallace,65.1,2010-12-17,97.503846
9660,21000403,1610612765.0,Ben Wallace,107.7,2010-12-19,97.881481
10102,21000422,1610612765.0,Ben Wallace,102.6,2010-12-22,98.050000
10546,21000440,1610612765.0,Ben Wallace,96.3,2010-12-26,97.989655
10611,21000443,1610612764.0,John Wall,77.0,2010-12-26,96.525000
10654,21000445,1610612765.0,Ben Wallace,133.0,2010-12-27,99.156667
10802,21000451,1610612764.0,John Wall,96.1,2010-12-27,96.500000
11096,21000463,1610612766.0,Gerald Wallace,117.2,2010-12-29,101.972000
11127,21000464,1610612764.0,John Wall,111.9,2010-12-29,97.355556
11146,21000465,1610612765.0,Ben Wallace,126.6,2010-12-29,100.041935
11432,21000477,1610612766.0,Gerald Wallace,103.3,2010-12-31,102.023077
11448,21000478,1610612764.0,John Wall,88.7,2010-12-31,96.900000
11542,21000482,1610612765.0,Ben Wallace,98.0,2010-12-31,99.978125
11604,21000484,1610612764.0,John Wall,101.7,2011-01-01,97.140000
12070,21000504,1610612765.0,Ben Wallace,116.3,2011-01-03,100.472727
12238,21000511,1610612765.0,Ben Wallace,86.1,2011-01-04,100.050000
12336,21000515,1610612764.0,John Wall,112.6,2011-01-05,97.876190
12633,21000527,1610612764.0,John Wall,100.6,2011-01-07,98.000000
12858,21000537,1610612764.0,John Wall,101.9,2011-01-08,98.169565
12915,21000539,1610612765.0,Ben Wallace,106.8,2011-01-08,100.242857
13236,21000553,1610612765.0,Ben Wallace,75.0,2011-01-10,99.541667
13322,21000556,1610612764.0,John Wall,127.6,2011-01-11,99.395833
13437,21000561,1610612766.0,Gerald Wallace,113.3,2011-01-12,102.440741
13714,21000573,1610612764.0,John Wall,93.3,2011-01-13,99.152000
13853,21000579,1610612766.0,Gerald Wallace,99.8,2011-01-14,102.346429
14080,21000588,1610612766.0,Gerald Wallace,93.4,2011-01-15,102.037931
14108,21000589,1610612764.0,John Wall,91.7,2011-01-15,98.865385
14348,21000599,1610612764.0,John Wall,122.8,2011-01-17,99.751852
14380,21000601,1610612766.0,Gerald Wallace,95.4,2011-01-17,101.816667
14643,21000612,1610612766.0,Gerald Wallace,84.8,2011-01-18,101.267742
14767,21000617,1610612764.0,John Wall,96.4,2011-01-19,99.632143
14991,21000626,1610612766.0,Gerald Wallace,117.7,2011-01-20,101.781250
15187,21000634,1610612764.0,John Wall,86.2,2011-01-21,99.168966
15303,21000639,1610612766.0,Gerald Wallace,109.0,2011-01-22,102.000000
15355,21000641,1610612764.0,John Wall,91.0,2011-01-22,98.896667
15381,21000642,1610612765.0,Ben Wallace,95.1,2011-01-22,99.421622
15656,21000654,1610612765.0,Ben Wallace,88.5,2011-01-24,99.134211
15726,21000657,1610612764.0,John Wall,88.3,2011-01-24,98.554839
15883,21000663,1610612764.0,John Wall,107.1,2011-01-25,98.821875
15939,21000666,1610612766.0,Gerald Wallace,103.8,2011-01-25,102.052941
16078,21000671,1610612765.0,Ben Wallace,102.5,2011-01-26,99.220513
16155,21000675,1610612766.0,Gerald Wallace,130.5,2011-01-26,102.865714
16430,21000686,1610612765.0,Ben Wallace,NaN,2011-01-28,99.220513
16471,21000688,1610612764.0,John Wall,100.4,2011-01-28,98.869697
16539,21000691,1610612766.0,Gerald Wallace,121.9,2011-01-28,103.394444
16615,21000694,1610612764.0,John Wall,94.8,2011-01-29,98.750000
16755,21000700,1610612766.0,Gerald Wallace,81.6,2011-01-29,102.805405
16886,21000705,1610612765.0,Ben Wallace,NaN,2011-01-30,99.220513
17047,21000712,1610612764.0,John Wall,93.6,2011-01-31,98.602857
17067,21000713,1610612766.0,Gerald Wallace,94.5,2011-01-31,102.586842
17119,21000715,1610612764.0,John Wall,94.0,2011-02-01,98.475000
17284,21000722,1610612766.0,Gerald Wallace,105.1,2011-02-02,102.651282
17301,21000722,1610612765.0,Ben Wallace,60.3,2011-02-02,98.247500
17561,21000733,1610612766.0,Gerald Wallace,108.3,2011-02-04,102.792500
17661,21000737,1610612764.0,John Wall,101.9,2011-02-04,98.567568
17706,21000739,1610612765.0,Ben Wallace,106.4,2011-02-04,98.446341
17848,21000745,1610612766.0,Gerald Wallace,99.7,2011-02-05,102.717073
17876,21000746,1610612764.0,John Wall,103.6,2011-02-05,98.700000
17957,21000750,1610612765.0,Ben Wallace,84.2,2011-02-05,98.107143
18159,21000758,1610612766.0,Gerald Wallace,95.0,2011-02-07,102.533333
18399,21000768,1610612765.0,Ben Wallace,79.7,2011-02-08,97.679070
18506,21000773,1610612765.0,Ben Wallace,103.5,2011-02-09,97.811364
18529,21000774,1610612766.0,Gerald Wallace,110.2,2011-02-09,102.711628
18641,21000778,1610612764.0,John Wall,110.0,2011-02-09,98.989744
18828,21000786,1610612766.0,Gerald Wallace,103.0,2011-02-11,102.718182
18973,21000792,1610612765.0,Ben Wallace,94.4,2011-02-11,97.735556
19056,21000796,1610612766.0,Gerald Wallace,101.9,2011-02-12,102.700000
19119,21000798,1610612764.0,John Wall,81.7,2011-02-12,98.557500
19299,21000806,1610612764.0,John Wall,126.8,2011-02-13,99.246341
19333,21000807,1610612765.0,Ben Wallace,108.7,2011-02-13,97.973913
19450,21000812,1610612766.0,Gerald Wallace,121.3,2011-02-14,103.104348
19500,21000814,1610612765.0,Ben Wallace,113.0,2011-02-14,98.293617
19605,21000819,1610612766.0,Gerald Wallace,98.1,2011-02-15,102.997872
19729,21000824,1610612764.0,John Wall,72.6,2011-02-16,98.611905
19835,21000828,1610612765.0,Ben Wallace,110.0,2011-02-16,98.537500
20073,21000838,1610612766.0,Gerald Wallace,124.1,2011-02-22,103.437500
20101,21000839,1610612764.0,John Wall,74.6,2011-02-22,98.053488
20123,21000840,1610612765.0,Ben Wallace,114.4,2011-02-22,98.861224
20303,21000848,1610612765.0,Ben Wallace,125.6,2011-02-23,99.396000
20353,21000850,1610612764.0,John Wall,98.6,2011-02-23,98.065909
20669,21000863,1610612765.0,Ben Wallace,NaN,2011-02-25,99.396000
20735,21000866,1610612764.0,John Wall,119.4,2011-02-25,98.540000
20913,21000873,1610612764.0,John Wall,93.1,2011-02-26,98.421739
20944,21000874,1610612765.0,Ben Wallace,NaN,2011-02-26,99.396000
21273,21000888,1610612757.0,Gerald Wallace,103.9,2011-02-27,103.446939
21320,21000890,1610612764.0,John Wall,91.0,2011-02-28,98.263830
21584,21000901,1610612757.0,Gerald Wallace,94.4,2011-03-01,103.266000
21655,21000904,1610612764.0,John Wall,101.1,2011-03-02,98.322917
21788,21000910,1610612757.0,Gerald Wallace,127.2,2011-03-02,103.735294
22183,21000926,1610612764.0,John Wall,103.0,2011-03-05,98.418367
22256,21000929,1610612757.0,Gerald Wallace,114.8,2011-03-05,103.948077
22362,21000934,1610612764.0,John Wall,105.2,2011-03-06,98.554000
22531,21000941,1610612757.0,Gerald Wallace,100.3,2011-03-07,103.879245
22757,21000950,1610612764.0,John Wall,82.9,2011-03-08,98.247059
22770,21000951,1610612757.0,Gerald Wallace,125.5,2011-03-08,104.279630
23153,21000967,1610612757.0,Gerald Wallace,96.6,2011-03-11,104.140000
23302,21000973,1610612765.0,Ben Wallace,NaN,2011-03-11,99.396000
23391,21000977,1610612757.0,Gerald Wallace,96.5,2011-03-12,104.003571
23425,21000978,1610612764.0,John Wall,90.8,2011-03-12,98.103846
23564,21000984,1610612765.0,Ben Wallace,NaN,2011-03-12,99.396000
23760,21000992,1610612764.0,John Wall,88.6,2011-03-14,97.924528
23964,21001001,1610612764.0,John Wall,88.8,2011-03-15,97.755556
23998,21001002,1610612757.0,Gerald Wallace,111.5,2011-03-15,104.135088
24070,21001005,1610612765.0,Ben Wallace,132.5,2011-03-16,100.045098
24333,21001016,1610612757.0,Gerald Wallace,138.4,2011-03-17,104.725862
24396,21001019,1610612764.0,John Wall,112.7,2011-03-18,98.027273
24454,21001021,1610612765.0,Ben Wallace,85.6,2011-03-18,99.767308
24765,21001034,1610612757.0,Gerald Wallace,119.4,2011-03-19,104.974576
24792,21001035,1610612764.0,John Wall,105.4,2011-03-20,98.158929
24802,21001036,1610612765.0,Ben Wallace,81.2,2011-03-20,99.416981
24969,21001043,1610612757.0,Gerald Wallace,94.0,2011-03-20,104.791667
25188,21001052,1610612764.0,John Wall,90.4,2011-03-22,98.022807
25197,21001052,1610612757.0,Gerald Wallace,117.0,2011-03-22,104.991803
25499,21001065,1610612764.0,John Wall,100.6,2011-03-23,98.067241
25763,21001076,1610612764.0,John Wall,100.6,2011-03-25,98.110169
25820,21001078,1610612757.0,Gerald Wallace,110.2,2011-03-25,105.075806
26143,21001092,1610612757.0,Gerald Wallace,106.4,2011-03-27,105.096825
26169,21001093,1610612764.0,John Wall,97.4,2011-03-27,98.098333
26310,21001099,1610612757.0,Gerald Wallace,113.8,2011-03-28,105.232812
26337,21001100,1610612764.0,John Wall,97.1,2011-03-28,98.081967
26589,21001110,1610612764.0,John Wall,120.8,2011-03-30,98.448387
26670,21001114,1610612757.0,Gerald Wallace,115.1,2011-03-30,105.384615
26907,21001123,1610612764.0,John Wall,NaN,2011-04-01,98.448387
26932,21001124,1610612765.0,Ben Wallace,NaN,2011-04-01,99.416981
27065,21001130,1610612757.0,Gerald Wallace,117.0,2011-04-01,105.560606
27303,21001140,1610612765.0,Ben Wallace,NaN,2011-04-03,99.416981
27320,21001141,1610612764.0,John Wall,104.8,2011-04-03,98.549206
27496,21001148,1610612757.0,Gerald Wallace,116.3,2011-04-03,105.720896
27610,21001153,1610612765.0,Ben Wallace,92.6,2011-04-05,99.290741
27620,21001153,1610612764.0,John Wall,107.7,2011-04-05,98.692188
27784,21001160,1610612757.0,Gerald Wallace,106.2,2011-04-05,105.727941
27848,21001163,1610612764.0,John Wall,105.9,2011-04-06,98.803077
28133,21001175,1610612757.0,Gerald Wallace,121.5,2011-04-07,105.956522
28232,21001179,1610612764.0,John Wall,83.9,2011-04-08,98.577273
28433,21001187,1610612757.0,Gerald Wallace,119.2,2011-04-08,106.145714
28460,21001188,1610612764.0,John Wall,120.2,2011-04-09,98.900000
28867,21001205,1610612764.0,John Wall,85.2,2011-04-11,98.698529
29079,21001214,1610612757.0,Gerald Wallace,112.4,2011-04-12,106.233803
29167,21001218,1610612764.0,John Wall,116.1,2011-04-13,98.950725
29390,21001227,1610612757.0,Gerald Wallace,NaN,2011-04-13,106.233803
30243,41000161,1610612757.0,Gerald Wallace,100.9,2011-04-16,106.159722
30267,41000162,1610612757.0,Gerald Wallace,104.1,2011-04-19,106.131507
30303,41000163,1610612757.0,Gerald Wallace,108.5,2011-04-21,106.163514
30327,41000164,1610612757.0,Gerald Wallace,102.4,2011-04-23,106.113333
30339,41000165,1610612757.0,Gerald Wallace,94.3,2011-04-25,105.957895
30375,41000166,1610612757.0,Gerald Wallace,120.0,2011-04-28,106.140260

In [201]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains(' Wall')][['TEAM_ID', 'PLAYER_NAME']].value_counts()

TEAM_ID       PLAYER_NAME
1610612764.0  John Wall         75
1610612765.0  Ben Wallace       63
1610612766.0  Gerald Wallace    48
1610612757.0  Gerald Wallace    30
dtype: int64

In [202]:
'''
*****************************************
Jose Barea 
('J.J. Barea', 83)
8
'''

"\n*****************************************\nJose Barea \n('J.J. Barea', 83)\n8\n"

In [203]:
df_inj3[df_inj3.player.str.contains('Barea')]

      game_date       Team     team_id       player   game_id
1031 2011-02-17  Mavericks  1610612742  Jose Barea   21000837

In [204]:
df_inj3[df_inj3.player.str.contains('Barea')].player.value_counts().index.values[0]

'Jose Barea '

In [205]:
df_inj3.player.replace({'Jose Barea ' : 'J.J. Barea'}, inplace=True)

In [206]:
df_inj3[df_inj3.player.str.contains('Barea')]

      game_date       Team     team_id      player   game_id
1031 2011-02-17  Mavericks  1610612742  J.J. Barea  21000837

In [207]:
print(df_inj3[df_inj3.player.str.contains('Barea')].player)

1031    J.J. Barea
Name: player, dtype: object

In [208]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Barea')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
281    21000012  1610612742.0  J.J. Barea          53.6 2010-10-27   53.600000
668    21000028  1610612742.0  J.J. Barea          91.7 2010-10-29   72.650000
968    21000041  1610612742.0  J.J. Barea          84.0 2010-10-31   76.433333
1424   21000060  1610612742.0  J.J. Barea          83.4 2010-11-03   78.175000
2034   21000085  1610612742.0  J.J. Barea          76.6 2010-11-06   77.860000
2396   21000100  1610612742.0  J.J. Barea         108.7 2010-11-08   83.000000
2720   21000114  1610612742.0  J.J. Barea          94.9 2010-11-10   84.700000
3019   21000126  1610612742.0  J.J. Barea         119.4 2010-11-12   89.037500
3499   21000146  1610612742.0  J.J. Barea         114.9 2010-11-15   91.911111
3895   21000163  1610612742.0  J.J. Barea         113.4 2010-11-17   94.060000
4291   21000179  1610612742.0  J.J. Barea          88.9 2010-11-19   93.590909
4399   21000184  1610612742.0  J.J. Barea         124.6 2010-11-20   96.175000
4962   21000207  1610612742.0  J.J. Barea          70.4 2010-11-23   94.192308
5166   21000216  1610612742.0  J.J. Barea         100.6 2010-11-24   94.650000
5454   21000228  1610612742.0  J.J. Barea         116.4 2010-11-26   96.100000
5730   21000239  1610612742.0  J.J. Barea          99.7 2010-11-27   96.325000
6041   21000252  1610612742.0  J.J. Barea          96.7 2010-11-29   96.347059
6427   21000268  1610612742.0  J.J. Barea          92.3 2010-12-01   96.122222
6846   21000286  1610612742.0  J.J. Barea         102.8 2010-12-03   96.473684
7014   21000293  1610612742.0  J.J. Barea         114.2 2010-12-04   97.360000
7482   21000312  1610612742.0  J.J. Barea         105.0 2010-12-07   97.723810
7866   21000328  1610612742.0  J.J. Barea         109.5 2010-12-09   98.259091
8298   21000346  1610612742.0  J.J. Barea          94.2 2010-12-11   98.082609
8586   21000358  1610612742.0  J.J. Barea         111.6 2010-12-13   98.645833
9041   21000377  1610612742.0  J.J. Barea         106.4 2010-12-15   98.956000
9354   21000390  1610612742.0  J.J. Barea         106.0 2010-12-17   99.226923
9821   21000410  1610612742.0  J.J. Barea          95.6 2010-12-20   99.092593
9964   21000416  1610612742.0  J.J. Barea         103.3 2010-12-21   99.242857
10780  21000450  1610612742.0  J.J. Barea         103.2 2010-12-27   99.379310
11008  21000459  1610612742.0  J.J. Barea         106.3 2010-12-28   99.610000
11368  21000474  1610612742.0  J.J. Barea          90.4 2010-12-30   99.312903
11713  21000489  1610612742.0  J.J. Barea          98.1 2011-01-01   99.275000
11858  21000495  1610612742.0  J.J. Barea          99.8 2011-01-02   99.290909
12205  21000509  1610612742.0  J.J. Barea         100.9 2011-01-04   99.338235
12540  21000523  1610612742.0  J.J. Barea         114.7 2011-01-06   99.777143
12990  21000542  1610612742.0  J.J. Barea         112.3 2011-01-08  100.125000
13456  21000562  1610612742.0  J.J. Barea         106.2 2011-01-12  100.289189
13910  21000581  1610612742.0  J.J. Barea         117.8 2011-01-14  100.750000
14172  21000592  1610612742.0  J.J. Barea          75.7 2011-01-15  100.107692
14459  21000604  1610612742.0  J.J. Barea         122.0 2011-01-17  100.655000
14880  21000621  1610612742.0  J.J. Barea         118.6 2011-01-19  101.092683
15011  21000627  1610612742.0  J.J. Barea          66.4 2011-01-20  100.266667
15323  21000640  1610612742.0  J.J. Barea          91.6 2011-01-22  100.065116
15934  21000665  1610612742.0  J.J. Barea         127.2 2011-01-25  100.681818
16270  21000679  1610612742.0  J.J. Barea         106.9 2011-01-27  100.820000
16679  21000696  1610612742.0  J.J. Barea         111.0 2011-01-29  101.041304
17063  21000712  1610612742.0  J.J. Barea         144.1 2011-01-31  101.957447
17316  21000723  1610612742.0  J.J. Barea         118.3 2011-02-02  102.297917
17719  21000740  1610612742.0  J.J. Barea         110.8 2011-02-04  102.471429
17839  21000745  1610612742.0  J.J. Barea          96.1 2011-02-05  102.344000
18236  21000761  1610612742.0  J.J. Barea         121.1 2011-02-07  102.711765
18704  21000781  1610612742.0  J.J. Barea         122.8 2011-02-09  103.098077
18800  21000785  1610612742.0  J.J. Barea         140.7 2011-02-10  103.807547
19183  21000801  1610612742.0  J.J. Barea         129.7 2011-02-12  104.287037
19914  21000831  1610612742.0  J.J. Barea         104.0 2011-02-16  104.281818
20046  21000837  1610612742.0  J.J. Barea           NaN 2011-02-17  104.281818
20513  21000856  1610612742.0  J.J. Barea         153.6 2011-02-23  105.162500
20905  21000873  1610612742.0  J.J. Barea         116.8 2011-02-26  105.366667
21168  21000884  1610612742.0  J.J. Barea         141.1 2011-02-27  105.982759
21455  21000896  1610612742.0  J.J. Barea          83.7 2011-03-01  105.605085
22068  21000921  1610612742.0  J.J. Barea         110.9 2011-03-04  105.693333
22475  21000938  1610612742.0  J.J. Barea         124.8 2011-03-06  106.006557
22630  21000945  1610612742.0  J.J. Barea         106.0 2011-03-07  106.006452
23013  21000961  1610612742.0  J.J. Barea         114.4 2011-03-09  106.139683
23120  21000965  1610612742.0  J.J. Barea         131.3 2011-03-10  106.532813
23525  21000982  1610612742.0  J.J. Barea         109.5 2011-03-12  106.578462
23991  21001002  1610612742.0  J.J. Barea         101.7 2011-03-15  106.504545
24231  21001012  1610612742.0  J.J. Barea         120.0 2011-03-16  106.705970
24508  21001023  1610612742.0  J.J. Barea          96.0 2011-03-18  106.548529
24961  21001042  1610612742.0  J.J. Barea          96.4 2011-03-20  106.401449
25536  21001066  1610612742.0  J.J. Barea          98.0 2011-03-24  106.281429
25979  21001085  1610612742.0  J.J. Barea         118.7 2011-03-26  106.456338
26221  21001095  1610612742.0  J.J. Barea         108.3 2011-03-27  106.481944
26750  21001117  1610612742.0  J.J. Barea         115.7 2011-03-30  106.608219
26797  21001119  1610612742.0  J.J. Barea          71.6 2011-03-31  106.135135
27206  21001136  1610612742.0  J.J. Barea          96.2 2011-04-02  106.002667
27492  21001148  1610612742.0  J.J. Barea         131.9 2011-04-03  106.343421
28078  21001172  1610612742.0  J.J. Barea         110.2 2011-04-06  106.393506
28413  21001186  1610612742.0  J.J. Barea         105.9 2011-04-08  106.387179
28727  21001199  1610612742.0  J.J. Barea         130.4 2011-04-10  106.691139
28955  21001209  1610612742.0  J.J. Barea          92.2 2011-04-11  106.510000
29303  21001223  1610612742.0  J.J. Barea         134.4 2011-04-13  106.854321
30262  41000161  1610612742.0  J.J. Barea          74.9 2011-04-16  106.464634
30287  41000162  1610612742.0  J.J. Barea         119.4 2011-04-19  106.620482
30299  41000163  1610612742.0  J.J. Barea         125.0 2011-04-21  106.839286
30321  41000164  1610612742.0  J.J. Barea          83.1 2011-04-23  106.560000
30358  41000165  1610612742.0  J.J. Barea          60.3 2011-04-25  106.022093
30368  41000166  1610612742.0  J.J. Barea         136.7 2011-04-28  106.374713
30947  41000231  1610612742.0  J.J. Barea         119.6 2011-05-02  106.525000
30971  41000232  1610612742.0  J.J. Barea         112.6 2011-05-04  106.593258
31008  41000233  1610612742.0  J.J. Barea         112.6 2011-05-06  106.660000
31030  41000234  1610612742.0  J.J. Barea         157.6 2011-05-08  107.219780
31176  41000311  1610612742.0  J.J. Barea         126.8 2011-05-17  107.432609
31198  41000312  1610612742.0  J.J. Barea         112.1 2011-05-19  107.482796
31211  41000313  1610612742.0  J.J. Barea         119.8 2011-05-21  107.613830
31235  41000314  1610612742.0  J.J. Barea         109.9 2011-05-23  107.637895
31271  41000315  1610612742.0  J.J. Barea         114.8 2011-05-25  107.712500
31282  41000401  1610612742.0  J.J. Barea          87.1 2011-05-31  107.500000
31307  41000402  1610612742.0  J.J. Barea          75.7 2011-06-02  107.175510
31343  41000403  1610612742.0  J.J. Barea          97.3 2011-06-05  107.075758
31362  41000404  1610612742.0  J.J. Barea         104.5 2011-06-07  107.050000
31386  41000405  1610612742.0  J.J. Barea         129.1 2011-06-09  107.268317
31399  41000406  1610612742.0  J.J. Barea         110.6 2011-06-12  107.300980

In [209]:
'''
*****************************************
Wes Johnson
('Wesley Johnson', 88)
9
'''

"\n*****************************************\nWes Johnson\n('Wesley Johnson', 88)\n9\n"

In [210]:
df_inj3[df_inj3.player.str.contains('Johnson')]

      game_date          Team     team_id         player   game_id
313  2010-12-01         Hawks  1610612737    Joe Johnson  21000261
977  2011-02-11       Raptors  1610612761   Amir Johnson  21000790
1145 2011-03-04  Timberwolves  1610612750    Wes Johnson  21000916
1152 2011-03-05  Timberwolves  1610612750    Wes Johnson  21000926
1214 2011-03-11       Raptors  1610612761   Amir Johnson  21000970
1273 2011-03-19       Blazers  1610612757  Armon Johnson  21001034
1330 2011-03-25       Raptors  1610612761   Amir Johnson  21001079
1346 2011-03-27         Hawks  1610612737    Joe Johnson  21001088
1475 2011-04-06       Raptors  1610612761   Amir Johnson  21001166
1530 2011-04-10       Raptors  1610612761   Amir Johnson  21001196
1561 2011-04-11       Raptors  1610612761   Amir Johnson  21001207
1625 2011-04-13       Raptors  1610612761   Amir Johnson  21001221
1659 2011-04-20        Lakers  1610612747   Trey Johnson  41000152

In [211]:
df_inj3[df_inj3.player.str.contains('Wes ')]

      game_date          Team     team_id       player   game_id
1145 2011-03-04  Timberwolves  1610612750  Wes Johnson  21000916
1152 2011-03-05  Timberwolves  1610612750  Wes Johnson  21000926

In [212]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Wesley Johnson')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
213,21000009,1610612750.0,Wesley Johnson,133.2,2010-10-27,133.200000
619,21000026,1610612750.0,Wesley Johnson,90.2,2010-10-29,111.700000
846,21000036,1610612750.0,Wesley Johnson,94.1,2010-10-30,105.833333
1184,21000050,1610612750.0,Wesley Johnson,90.0,2010-11-02,101.875000
1320,21000056,1610612750.0,Wesley Johnson,100.0,2010-11-03,101.500000
1767,21000074,1610612750.0,Wesley Johnson,108.8,2010-11-05,102.716667
2187,21000092,1610612750.0,Wesley Johnson,102.1,2010-11-07,102.628571
2547,21000107,1610612750.0,Wesley Johnson,97.5,2010-11-09,101.987500
2786,21000117,1610612750.0,Wesley Johnson,97.2,2010-11-10,101.455556
2990,21000125,1610612750.0,Wesley Johnson,113.8,2010-11-12,102.690000
3314,21000139,1610612750.0,Wesley Johnson,112.8,2010-11-14,103.609091
3434,21000144,1610612750.0,Wesley Johnson,94.4,2010-11-15,102.841667
3878,21000162,1610612750.0,Wesley Johnson,133.4,2010-11-17,105.192308
4214,21000176,1610612750.0,Wesley Johnson,85.9,2010-11-19,103.814286
4705,21000197,1610612750.0,Wesley Johnson,103.9,2010-11-22,103.820000
5149,21000215,1610612750.0,Wesley Johnson,109.9,2010-11-24,104.200000
5701,21000238,1610612750.0,Wesley Johnson,91.0,2010-11-27,103.423529
6409,21000268,1610612750.0,Wesley Johnson,96.1,2010-12-01,103.016667
6769,21000283,1610612750.0,Wesley Johnson,95.5,2010-12-03,102.621053
6970,21000291,1610612750.0,Wesley Johnson,129.3,2010-12-04,103.955000
7273,21000304,1610612750.0,Wesley Johnson,104.7,2010-12-06,103.990476
7666,21000320,1610612750.0,Wesley Johnson,101.5,2010-12-08,103.877273
8005,21000334,1610612750.0,Wesley Johnson,109.4,2010-12-10,104.117391
8257,21000345,1610612750.0,Wesley Johnson,93.8,2010-12-11,103.687500
8761,21000366,1610612750.0,Wesley Johnson,112.3,2010-12-14,104.032000
9001,21000376,1610612750.0,Wesley Johnson,112.1,2010-12-15,104.342308
9361,21000391,1610612750.0,Wesley Johnson,101.0,2010-12-17,104.218519
9529,21000398,1610612750.0,Wesley Johnson,96.2,2010-12-18,103.932143
9911,21000414,1610612750.0,Wesley Johnson,93.6,2010-12-20,103.575862
10211,21000426,1610612750.0,Wesley Johnson,95.1,2010-12-22,103.293333
10511,21000439,1610612750.0,Wesley Johnson,90.2,2010-12-26,102.870968
10763,21000449,1610612750.0,Wesley Johnson,131.2,2010-12-27,103.756250
11171,21000466,1610612750.0,Wesley Johnson,114.6,2010-12-29,104.084848
11675,21000487,1610612750.0,Wesley Johnson,113.5,2011-01-01,104.361765
11999,21000501,1610612750.0,Wesley Johnson,120.5,2011-01-03,104.822857
12394,21000517,1610612750.0,Wesley Johnson,99.6,2011-01-05,104.677778
12727,21000531,1610612750.0,Wesley Johnson,87.7,2011-01-07,104.218919
13073,21000546,1610612750.0,Wesley Johnson,112.8,2011-01-09,104.444737
13349,21000557,1610612750.0,Wesley Johnson,84.5,2011-01-11,103.933333
13722,21000573,1610612750.0,Wesley Johnson,121.7,2011-01-13,104.377500
14200,21000593,1610612750.0,Wesley Johnson,130.4,2011-01-15,105.012195
14581,21000609,1610612750.0,Wesley Johnson,NaN,2011-01-17,105.012195
14962,21000625,1610612750.0,Wesley Johnson,106.8,2011-01-19,105.054762
15788,21000659,1610612750.0,Wesley Johnson,112.8,2011-01-24,105.234884
16124,21000673,1610612750.0,Wesley Johnson,101.3,2011-01-26,105.145455
16496,21000689,1610612750.0,Wesley Johnson,108.7,2011-01-28,105.224444
16652,21000695,1610612750.0,Wesley Johnson,115.7,2011-01-29,105.452174
17350,21000724,1610612750.0,Wesley Johnson,80.1,2011-02-02,104.912766
17626,21000736,1610612750.0,Wesley Johnson,112.3,2011-02-04,105.066667
17998,21000751,1610612750.0,Wesley Johnson,94.5,2011-02-05,104.851020
18201,21000760,1610612750.0,Wesley Johnson,115.8,2011-02-07,105.070000
18481,21000772,1610612750.0,Wesley Johnson,112.6,2011-02-08,105.217647
18840,21000787,1610612750.0,Wesley Johnson,90.1,2011-02-11,104.926923
19139,21000799,1610612750.0,Wesley Johnson,88.2,2011-02-12,104.611321
19545,21000816,1610612750.0,Wesley Johnson,32.3,2011-02-14,103.272222
19889,21000830,1610612750.0,Wesley Johnson,93.5,2011-02-16,103.094545
20160,21000842,1610612750.0,Wesley Johnson,101.0,2011-02-22,103.057143
20436,21000853,1610612750.0,Wesley Johnson,92.0,2011-02-23,102.863158
20793,21000868,1610612750.0,Wesley Johnson,91.1,2011-02-25,102.660345
21127,21000882,1610612750.0,Wesley Johnson,127.6,2011-02-27,103.083051
21558,21000900,1610612750.0,Wesley Johnson,89.3,2011-03-01,102.853333
21690,21000906,1610612750.0,Wesley Johnson,100.7,2011-03-02,102.818033
21936,21000916,1610612750.0,Wesley Johnson,NaN,2011-03-04,102.818033
22176,21000926,1610612750.0,Wesley Johnson,NaN,2011-03-05,102.818033
22636,21000945,1610612750.0,Wesley Johnson,122.0,2011-03-07,103.127419
22995,21000960,1610612750.0,Wesley Johnson,77.5,2011-03-09,102.720635
23282,21000972,1610612750.0,Wesley Johnson,133.1,2011-03-11,103.195313
23699,21000990,1610612750.0,Wesley Johnson,67.4,2011-03-13,102.644615
24179,21001010,1610612750.0,Wesley Johnson,103.0,2011-03-16,102.650000
24611,21001028,1610612750.0,Wesley Johnson,95.9,2011-03-18,102.549254
24863,21001038,1610612750.0,Wesley Johnson,89.7,2011-03-20,102.360294
25522,21001066,1610612750.0,Wesley Johnson,89.2,2011-03-24,102.169565
25738,21001075,1610612750.0,Wesley Johnson,101.8,2011-03-25,102.164286
26133,21001091,1610612750.0,Wesley Johnson,92.6,2011-03-27,102.029577
26660,21001113,1610612750.0,Wesley Johnson,66.9,2011-03-30,101.541667
26972,21001126,1610612750.0,Wesley Johnson,70.1,2011-04-01,101.110959
27149,21001134,1610612750.0,Wesley Johnson,98.9,2011-04-02,101.081081
27556,21001151,1610612750.0,Wesley Johnson,100.6,2011-04-05,101.074667
27979,21001168,1610612750.0,Wesley Johnson,90.1,2011-04-06,100.930263
28542,21001192,1610612750.0,Wesley Johnson,79.4,2011-04-09,100.650649
28998,21001211,1610612750.0,Wesley Johnson,124.6,2011-04-11,100.957692
29322,21001224,1610612750.0,Wesley Johnson,112.4,2011-04-13,101.102532

In [213]:
df_inj3.player.replace({'Wes Johnson':'Wesley Johnson'}, inplace=True)

In [214]:
df_inj3[df_inj3.player.str.contains('Wes ')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [215]:
df_inj3[df_inj3.player.str.contains('Wesley')]

      game_date          Team     team_id          player   game_id
1145 2011-03-04  Timberwolves  1610612750  Wesley Johnson  21000916
1152 2011-03-05  Timberwolves  1610612750  Wesley Johnson  21000926

<font color='red'> PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP</font>

In [216]:
df_inj3.player.replace({' Tony Parker' : 'Tony Parker'}, inplace=True)

In [217]:
df_inj3[df_inj3.player.str.contains('Mullens')]

      game_date     Team     team_id        player   game_id
66   2010-10-27  Thunder  1610612760  B.J. Mullens  21000011
199  2010-11-14  Thunder  1610612760  B.J. Mullens  21000141
270  2010-11-24  Thunder  1610612760  B.J. Mullens  21000216
305  2010-11-29  Thunder  1610612760  B.J. Mullens  21000251
803  2011-01-22  Thunder  1610612760  B.J. Mullens  21000647
893  2011-02-02  Thunder  1610612760  B.J. Mullens  21000725
1096 2011-02-27  Thunder  1610612760  B.J. Mullens  21000880
1238 2011-03-14  Thunder  1610612760  B.J. Mullens  21000992
1655 2011-04-17  Thunder  1610612760  B.J. Mullens  41000171

In [218]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Mullens')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
3069,21000128,1610612760.0,Byron Mullens,NaN,2010-11-12,NaN
3932,21000164,1610612760.0,Byron Mullens,120.0,2010-11-17,120.000000
4090,21000171,1610612760.0,Byron Mullens,NaN,2010-11-19,120.000000
4449,21000186,1610612760.0,Byron Mullens,NaN,2010-11-20,120.000000
4724,21000197,1610612760.0,Byron Mullens,NaN,2010-11-22,120.000000
5431,21000227,1610612760.0,Byron Mullens,119.5,2010-11-26,119.750000
5911,21000247,1610612760.0,Byron Mullens,NaN,2010-11-28,119.750000
6271,21000262,1610612760.0,Byron Mullens,102.0,2010-12-01,113.833333
6609,21000276,1610612760.0,Byron Mullens,112.6,2010-12-03,113.525000
7124,21000297,1610612760.0,Byron Mullens,NaN,2010-12-05,113.525000
7303,21000305,1610612760.0,Byron Mullens,0.0,2010-12-06,90.820000
7664,21000320,1610612760.0,Byron Mullens,NaN,2010-12-08,90.820000
8444,21000352,1610612760.0,Byron Mullens,88.1,2010-12-12,90.366667
8972,21000374,1610612760.0,Byron Mullens,82.9,2010-12-15,89.300000
9307,21000388,1610612760.0,Byron Mullens,77.3,2010-12-17,87.800000
9716,21000405,1610612760.0,Byron Mullens,NaN,2010-12-19,87.800000
9939,21000415,1610612760.0,Byron Mullens,93.6,2010-12-21,88.444444
10182,21000425,1610612760.0,Byron Mullens,101.0,2010-12-22,89.700000
10458,21000436,1610612760.0,Byron Mullens,NaN,2010-12-25,89.700000
10794,21000450,1610612760.0,Byron Mullens,NaN,2010-12-27,89.700000
11227,21000468,1610612760.0,Byron Mullens,112.8,2010-12-29,91.800000
11538,21000481,1610612760.0,Byron Mullens,NaN,2010-12-31,91.800000
11695,21000488,1610612760.0,Byron Mullens,81.3,2011-01-01,90.925000
12174,21000508,1610612760.0,Byron Mullens,NaN,2011-01-04,90.925000
12533,21000523,1610612760.0,Byron Mullens,NaN,2011-01-06,90.925000
12971,21000541,1610612760.0,Byron Mullens,NaN,2011-01-08,90.925000
13600,21000568,1610612760.0,Byron Mullens,NaN,2011-01-12,90.925000
13756,21000574,1610612760.0,Byron Mullens,NaN,2011-01-13,90.925000
14605,21000610,1610612760.0,Byron Mullens,NaN,2011-01-17,90.925000
14893,21000622,1610612760.0,Byron Mullens,NaN,2011-01-19,90.925000
16489,21000688,1610612760.0,Byron Mullens,NaN,2011-01-28,90.925000
16801,21000701,1610612760.0,Byron Mullens,NaN,2011-01-30,90.925000
20765,21000867,1610612760.0,Byron Mullens,NaN,2011-02-25,90.925000
21962,21000917,1610612760.0,Byron Mullens,NaN,2011-03-04,90.925000
22453,21000937,1610612760.0,Byron Mullens,NaN,2011-03-06,90.925000
22608,21000944,1610612760.0,Byron Mullens,NaN,2011-03-07,90.925000
22871,21000955,1610612760.0,Byron Mullens,NaN,2011-03-09,90.925000
29351,21001225,1610612760.0,Byron Mullens,90.1,2011-04-13,90.861538

In [219]:
df_inj3.player.replace({'B.J. Mullens':'Byron Mullens'}, inplace=True)

In [220]:
df_inj3[df_inj3.player.str.contains('Mullens')]

      game_date     Team     team_id         player   game_id
66   2010-10-27  Thunder  1610612760  Byron Mullens  21000011
199  2010-11-14  Thunder  1610612760  Byron Mullens  21000141
270  2010-11-24  Thunder  1610612760  Byron Mullens  21000216
305  2010-11-29  Thunder  1610612760  Byron Mullens  21000251
803  2011-01-22  Thunder  1610612760  Byron Mullens  21000647
893  2011-02-02  Thunder  1610612760  Byron Mullens  21000725
1096 2011-02-27  Thunder  1610612760  Byron Mullens  21000880
1238 2011-03-14  Thunder  1610612760  Byron Mullens  21000992
1655 2011-04-17  Thunder  1610612760  Byron Mullens  41000171

In [221]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

{'Bill Walker',
 "Da'Sean Butler",
 'Daniel Orton',
 'Didier Mbenga ',
 'Ed Davis ',
 'Eddy Curry',
 'Gerald Henderson Jr.',
 'Jannero Pargo',
 'Jianlian Yi',
 'Joe Alexander',
 'Joe Smith ',
 'John Wall ',
 'Jonas Jerebko',
 'Kelenna Azubuike',
 'Larry Sanders ',
 'Magnum Rolle',
 'Marcus Thornton ',
 'Matt Janning',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Nene Hilario ',
 'Robert Vaden',
 'Terrico White'}

In [222]:
df_inj3['player'] = df_inj3.player.str.strip()

In [223]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

{'Bill Walker',
 "Da'Sean Butler",
 'Daniel Orton',
 'Didier Mbenga',
 'Eddy Curry',
 'Gerald Henderson Jr.',
 'Jannero Pargo',
 'Jianlian Yi',
 'Joe Alexander',
 'Jonas Jerebko',
 'Kelenna Azubuike',
 'Magnum Rolle',
 'Matt Janning',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Nene Hilario',
 'Robert Vaden',
 'Terrico White'}

In [224]:
#Bill Walker
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Walker')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
152,21000007,1610612752.0,Henry Walker,104.0,2010-10-27,104.000000
535,21000023,1610612752.0,Henry Walker,107.9,2010-10-29,105.950000
787,21000033,1610612752.0,Henry Walker,89.3,2010-10-30,100.400000
1220,21000051,1610612752.0,Henry Walker,115.8,2011-03-28,104.250000
1567,21000066,1610612752.0,Henry Walker,146.1,2010-11-04,112.620000
1724,21000072,1610612752.0,Henry Walker,118.6,2010-11-05,113.616667
2131,21000089,1610612752.0,Henry Walker,88.0,2010-11-07,109.957143
2481,21000104,1610612752.0,Henry Walker,75.3,2010-11-09,105.625000
2708,21000113,1610612752.0,Henry Walker,112.1,2010-11-10,106.344444
2985,21000125,1610612752.0,Henry Walker,NaN,2010-11-12,106.344444
3405,21000142,1610612752.0,Henry Walker,NaN,2010-11-14,106.344444
3753,21000157,1610612752.0,Henry Walker,171.6,2010-11-16,112.870000
3988,21000167,1610612752.0,Henry Walker,96.9,2010-11-17,111.418182
4326,21000181,1610612752.0,Henry Walker,132.0,2010-11-19,113.133333
4543,21000190,1610612752.0,Henry Walker,103.1,2010-11-20,112.361538
4938,21000206,1610612752.0,Henry Walker,78.1,2010-11-23,109.914286
4998,21000209,1610612752.0,Henry Walker,96.6,2010-11-24,109.026667
5609,21000234,1610612752.0,Henry Walker,87.3,2010-11-27,107.668750
5811,21000243,1610612752.0,Henry Walker,93.4,2010-11-28,106.829412
6159,21000257,1610612752.0,Henry Walker,117.0,2010-11-30,107.394444
6748,21000282,1610612752.0,Henry Walker,37.5,2010-12-03,103.715789
7065,21000295,1610612752.0,Henry Walker,NaN,2010-12-05,103.715789
7629,21000318,1610612752.0,Henry Walker,NaN,2010-12-08,103.715789
7953,21000332,1610612752.0,Henry Walker,NaN,2010-12-10,103.715789
8370,21000349,1610612752.0,Henry Walker,173.1,2010-12-12,107.185000
8829,21000368,1610612752.0,Henry Walker,NaN,2010-12-15,107.185000
9162,21000382,1610612752.0,Henry Walker,60.0,2010-12-17,104.938095
9441,21000394,1610612752.0,Henry Walker,NaN,2010-12-18,104.938095
10194,21000425,1610612752.0,Henry Walker,0.0,2010-12-22,100.168182
10387,21000433,1610612752.0,Henry Walker,NaN,2010-12-25,100.168182
10948,21000457,1610612752.0,Henry Walker,122.2,2010-12-28,101.126087
11332,21000473,1610612752.0,Henry Walker,46.0,2010-12-30,98.829167
11800,21000492,1610612752.0,Henry Walker,116.1,2011-01-02,99.520000
12135,21000506,1610612752.0,Henry Walker,117.3,2011-01-04,100.203846
12765,21000533,1610612752.0,Henry Walker,120.7,2011-01-07,100.962963
13167,21000550,1610612752.0,Henry Walker,95.8,2011-01-09,100.778571
13382,21000559,1610612752.0,Henry Walker,106.9,2011-01-11,100.989655
13644,21000570,1610612752.0,Henry Walker,120.3,2011-01-12,101.633333
13896,21000580,1610612752.0,Henry Walker,83.9,2011-01-14,101.061290
14327,21000598,1610612752.0,Henry Walker,115.5,2011-01-17,101.512500
14818,21000619,1610612752.0,Henry Walker,105.6,2011-01-19,101.636364
15227,21000636,1610612752.0,Henry Walker,109.1,2011-01-21,101.855882
15490,21000647,1610612752.0,Henry Walker,68.4,2011-01-22,100.900000
15742,21000657,1610612752.0,Henry Walker,120.2,2011-01-24,101.436111
16247,21000678,1610612752.0,Henry Walker,60.7,2011-01-27,100.335135
16378,21000684,1610612752.0,Henry Walker,86.8,2011-01-28,99.978947
16895,21000705,1610612752.0,Henry Walker,134.3,2011-01-30,100.858974
17328,21000723,1610612752.0,Henry Walker,88.5,2011-02-02,100.550000
17605,21000735,1610612752.0,Henry Walker,0.0,2011-02-04,98.097561
18122,21000756,1610612752.0,Henry Walker,NaN,2011-02-06,98.097561
18671,21000779,1610612752.0,Henry Walker,NaN,2011-02-09,98.097561
19006,21000793,1610612752.0,Henry Walker,NaN,2011-02-11,98.097561
19087,21000797,1610612752.0,Henry Walker,112.6,2011-02-12,98.442857
19863,21000829,1610612752.0,Henry Walker,135.1,2011-02-16,99.295349
20416,21000852,1610612752.0,Henry Walker,118.6,2011-02-23,99.734091
20714,21000865,1610612752.0,Henry Walker,112.2,2011-02-25,100.011111
21241,21000887,1610612752.0,Henry Walker,105.2,2011-02-27,100.123913
21431,21000895,1610612752.0,Henry Walker,93.8,2011-03-01,99.989362
21729,21000907,1610612752.0,Henry Walker,108.8,2011-03-02,100.172917
22017,21000919,1610612752.0,Henry Walker,109.0,2011-03-04,100.353061
22942,21000958,1610612752.0,Henry Walker,NaN,2011-03-09,100.353061
23109,21000965,1610612752.0,Henry Walker,88.3,2011-03-10,100.112000
23693,21000989,1610612752.0,Henry Walker,111.5,2011-03-13,100.335294
23945,21001000,1610612752.0,Henry Walker,68.0,2011-03-15,99.713462
24318,21001015,1610612752.0,Henry Walker,NaN,2011-03-17,99.713462
24450,21001021,1610612752.0,Henry Walker,NaN,2011-03-18,99.713462
24835,21001037,1610612752.0,Henry Walker,NaN,2011-03-20,99.713462
25062,21001046,1610612752.0,Henry Walker,NaN,2011-03-21,99.713462
25373,21001059,1610612752.0,Henry Walker,NaN,2011-03-23,99.713462
25912,21001082,1610612752.0,Henry Walker,82.0,2011-03-26,99.379245
26617,21001111,1610612752.0,Henry Walker,81.0,2011-03-30,99.038889
27385,21001143,1610612752.0,Henry Walker,141.4,2011-04-03,99.809091
27672,21001155,1610612752.0,Henry Walker,133.7,2011-04-05,100.414286
27901,21001165,1610612752.0,Henry Walker,87.3,2011-04-06,100.184211
28186,21001177,1610612752.0,Henry Walker,105.8,2011-04-08,100.281034
28692,21001198,1610612752.0,Henry Walker,103.2,2011-04-10,100.330508
29062,21001213,1610612752.0,Henry Walker,108.3,2011-04-12,100.463333
29115,21001216,1610612752.0,Henry Walker,106.7,2011-04-13,100.565574
29720,41000121,1610612752.0,Henry Walker,95.4,2011-04-17,100.482258
29745,41000122,1610612752.0,Henry Walker,121.5,2011-04-19,100.815873
29781,41000123,1610612752.0,Henry Walker,111.3,2011-04-22,100.979688
29805,41000124,1610612752.0,Henry Walker,94.7,2011-04-24,100.883077

In [225]:
df_inj3[df_inj3.player.str.contains('Walker')]

      game_date    Team     team_id       player   game_id
361  2010-12-06  Knicks  1610612752  Bill Walker  21000304
1161 2011-03-06  Knicks  1610612752  Bill Walker  21000933
1324 2011-03-25  Knicks  1610612752  Bill Walker  21001073

In [226]:
df_inj3.player.replace({'Bill Walker':'Henry Walker'}, inplace=True)

In [227]:
df_inj3[df_inj3.player.str.contains('Walker')]

      game_date    Team     team_id        player   game_id
361  2010-12-06  Knicks  1610612752  Henry Walker  21000304
1161 2011-03-06  Knicks  1610612752  Henry Walker  21000933
1324 2011-03-25  Knicks  1610612752  Henry Walker  21001073

In [228]:
#Da'Sean Butler
df_inj3[df_inj3.player.str.contains('Butler')]

      game_date       Team     team_id          player   game_id
165  2010-11-10  Mavericks  1610612742    Caron Butler  21000114
611  2011-01-02  Mavericks  1610612742    Caron Butler  21000495
627  2011-01-04  Mavericks  1610612742    Caron Butler  21000509
1128 2011-03-04      Bulls  1610612741   Rasual Butler  21000915
1333 2011-03-25      Spurs  1610612759  Da'Sean Butler  21001078

In [229]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Butler')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
276,21000012,1610612742.0,Caron Butler,125.5,2010-10-27,125.500000
378,21000016,1610612746.0,Rasual Butler,104.8,2010-10-27,104.800000
660,21000028,1610612742.0,Caron Butler,94.2,2010-10-29,109.850000
680,21000029,1610612746.0,Rasual Butler,101.7,2010-10-29,103.250000
960,21000041,1610612742.0,Caron Butler,114.2,2010-10-31,111.300000
980,21000041,1610612746.0,Rasual Butler,93.8,2010-10-31,100.100000
1097,21000046,1610612746.0,Rasual Butler,63.1,2010-11-01,90.850000
1416,21000060,1610612742.0,Caron Butler,111.8,2010-11-03,111.425000
1529,21000064,1610612746.0,Rasual Butler,114.2,2010-11-03,95.520000
1829,21000077,1610612746.0,Rasual Butler,100.9,2010-11-05,96.416667
2028,21000085,1610612742.0,Caron Butler,106.8,2010-11-06,110.500000
2045,21000086,1610612746.0,Rasual Butler,89.2,2010-11-06,95.385714
2388,21000100,1610612742.0,Caron Butler,87.0,2010-11-08,106.583333
2499,21000105,1610612746.0,Rasual Butler,73.6,2010-11-09,92.662500
2763,21000116,1610612746.0,Rasual Butler,101.1,2010-11-10,93.600000
3088,21000129,1610612746.0,Rasual Butler,90.8,2010-11-12,93.320000
3594,21000150,1610612746.0,Rasual Butler,104.2,2010-11-15,94.309091
3870,21000162,1610612746.0,Rasual Butler,81.9,2010-11-17,93.275000
3887,21000163,1610612742.0,Caron Butler,108.0,2010-11-17,106.785714
4016,21000168,1610612746.0,Rasual Butler,78.5,2010-11-18,92.138462
4283,21000179,1610612742.0,Caron Butler,103.4,2010-11-19,106.362500
4391,21000184,1610612742.0,Caron Butler,114.2,2010-11-20,107.233333
4554,21000190,1610612746.0,Rasual Butler,100.4,2010-11-20,92.728571
4842,21000202,1610612746.0,Rasual Butler,82.0,2010-11-22,92.013333
4954,21000207,1610612742.0,Caron Butler,109.1,2010-11-23,107.420000
5158,21000216,1610612742.0,Caron Butler,110.1,2010-11-24,107.663636
5300,21000221,1610612746.0,Rasual Butler,53.0,2010-11-25,89.575000
5446,21000228,1610612742.0,Caron Butler,98.4,2010-11-26,106.891667
5503,21000230,1610612746.0,Rasual Butler,112.6,2010-11-26,90.929412
5722,21000239,1610612742.0,Caron Butler,110.1,2010-11-27,107.138462
5872,21000245,1610612746.0,Rasual Butler,70.3,2010-11-28,89.783333
6033,21000252,1610612742.0,Caron Butler,120.4,2010-11-29,108.085714
6418,21000268,1610612742.0,Caron Butler,87.6,2010-12-01,106.720000
6522,21000272,1610612746.0,Rasual Butler,88.9,2010-12-01,89.736842
6798,21000284,1610612746.0,Rasual Butler,96.3,2010-12-03,90.065000
6838,21000286,1610612742.0,Caron Butler,101.9,2010-12-03,106.418750
7006,21000293,1610612742.0,Caron Butler,108.5,2010-12-04,106.541176
7206,21000301,1610612746.0,Rasual Butler,109.5,2010-12-05,90.990476
7387,21000308,1610612746.0,Rasual Butler,107.8,2010-12-06,91.754545
7474,21000312,1610612742.0,Caron Butler,105.0,2010-12-07,106.455556
7819,21000326,1610612746.0,Rasual Butler,69.8,2010-12-08,90.800000
7858,21000328,1610612742.0,Caron Butler,106.9,2010-12-09,106.478947
8178,21000341,1610612746.0,Rasual Butler,69.2,2010-12-11,89.900000
8290,21000346,1610612742.0,Caron Butler,126.0,2010-12-11,107.455000
8488,21000354,1610612746.0,Rasual Butler,98.9,2010-12-12,90.260000
8578,21000358,1610612742.0,Caron Butler,101.7,2010-12-13,107.180952
8837,21000369,1610612746.0,Rasual Butler,110.5,2010-12-15,91.038462
9034,21000377,1610612742.0,Caron Butler,115.6,2010-12-15,107.563636
9246,21000386,1610612746.0,Rasual Butler,87.5,2010-12-17,90.907407
9346,21000390,1610612742.0,Caron Butler,112.4,2010-12-17,107.773913
9461,21000395,1610612746.0,Rasual Butler,100.3,2010-12-18,91.242857
9813,21000410,1610612742.0,Caron Butler,96.2,2010-12-20,107.291667
9927,21000414,1610612746.0,Rasual Butler,105.0,2010-12-20,91.717241
9956,21000416,1610612742.0,Caron Butler,119.2,2010-12-21,107.768000
10285,21000429,1610612746.0,Rasual Butler,88.9,2010-12-22,91.623333
10506,21000438,1610612746.0,Rasual Butler,NaN,2010-12-26,91.623333
10772,21000450,1610612742.0,Caron Butler,105.8,2010-12-27,107.692308
10853,21000453,1610612746.0,Rasual Butler,133.3,2010-12-27,92.967742
11000,21000459,1610612742.0,Caron Butler,96.4,2010-12-28,107.274074
11321,21000472,1610612746.0,Rasual Butler,NaN,2010-12-29,92.967742
11360,21000474,1610612742.0,Caron Butler,101.1,2010-12-30,107.053571
11708,21000489,1610612742.0,Caron Butler,100.7,2011-01-01,106.834483
11825,21000493,1610612746.0,Rasual Butler,NaN,2011-01-02,92.967742
12520,21000522,1610612746.0,Rasual Butler,NaN,2011-01-05,92.967742
13065,21000545,1610612746.0,Rasual Butler,NaN,2011-01-09,92.967742
13708,21000572,1610612746.0,Rasual Butler,NaN,2011-01-12,92.967742
14006,21000585,1610612746.0,Rasual Butler,NaN,2011-01-14,92.967742
14281,21000596,1610612746.0,Rasual Butler,NaN,2011-01-16,92.967742
14496,21000605,1610612746.0,Rasual Butler,NaN,2011-01-17,92.967742
14978,21000625,1610612746.0,Rasual Butler,NaN,2011-01-19,92.967742
15036,21000628,1610612746.0,Rasual Butler,NaN,2011-01-20,92.967742
15600,21000651,1610612746.0,Rasual Butler,NaN,2011-01-22,92.967742
15922,21000665,1610612746.0,Rasual Butler,92.9,2011-01-25,92.965625
16138,21000674,1610612746.0,Rasual Butler,93.7,2011-01-26,92.987879
16776,21000700,1610612746.0,Rasual Butler,103.1,2011-01-29,93.285294
17111,21000714,1610612746.0,Rasual Butler,90.7,2011-01-31,93.211429
17473,21000729,1610612746.0,Rasual Butler,112.7,2011-02-02,93.752778
17678,21000738,1610612746.0,Rasual Butler,NaN,2011-02-04,93.752778
18061,21000754,1610612746.0,Rasual Butler,NaN,2011-02-06,93.752778
18371,21000767,1610612746.0,Rasual Butler,64.4,2011-02-08,92.959459
18657,21000779,1610612746.0,Rasual Butler,NaN,2011-02-09,92.959459
18944,21000791,1610612746.0,Rasual Butler,NaN,2011-02-11,92.959459
19352,21000808,1610612746.0,Rasual Butler,NaN,2011-02-13,92.959459
19519,21000815,1610612746.0,Rasual Butler,0.0,2011-02-14,90.513158
19879,21000830,1610612746.0,Rasual Butler,NaN,2011-02-16,90.513158
20191,21000843,1610612746.0,Rasual Butler,118.0,2011-02-22,91.217949
20452,21000854,1610612746.0,Rasual Butler,86.9,2011-02-23,91.110000
20857,21000871,1610612746.0,Rasual Butler,99.1,2011-02-25,91.304878
21037,21000878,1610612746.0,Rasual Butler,NaN,2011-02-26,91.304878
23265,21000971,1610612741.0,Rasual Butler,100.0,2011-03-11,91.511905
23455,21000979,1610612741.0,Rasual Butler,NaN,2011-03-12,91.511905
23982,21001001,1610612741.0,Rasual Butler,69.4,2011-03-15,90.997674
24282,21001014,1610612741.0,Rasual Butler,NaN,2011-03-17,90.997674
24354,21001017,1610612741.0,Rasual Butler,NaN,2011-03-18,90.997674
25086,21001047,1610612741.0,Rasual Butler,170.0,2011-03-21,92.793182
25171,21001051,1610612741.0,Rasual Butler,0.0,2011-03-22,90.731111
25734,21001074,1610612741.0,Rasual Butler,NaN,2011-03-25,90.731111
25961,21001084,1610612741.0,Rasual Butler,NaN,2011-03-26,90.731111
26307,21001098,1610612741.0,Rasual Butler,NaN,2011-03-28,90.731111
26655,21001113,1610612741.0,Rasual Butler,NaN,2011-03-30,90.731111
26919,21001124,1610612741.0,Rasual Butler,NaN,2011-04-01,90.731111
27147,21001133,1610612741.0,Rasual Butler,NaN,2011-04-02,90.731111
27699,21001156,1610612741.0,Rasual Butler,NaN,2011-04-05,90.731111
28131,21001174,1610612741.0,Rasual Butler,300.0,2011-04-07,95.280435
28263,21001180,1610612741.0,Rasual Butler,NaN,2011-04-08,95.280435
28573,21001193,1610612741.0,Rasual Butler,NaN,2011-04-10,95.280435
29053,21001213,1610612741.0,Rasual Butler,NaN,2011-04-12,95.280435
29281,21001222,1610612741.0,Rasual Butler,134.3,2011-04-13,96.110638
29498,41000101,1610612741.0,Rasual Butler,NaN,2011-04-16,96.110638
29522,41000102,1610612741.0,Rasual Butler,NaN,2011-04-18,96.110638
29534,41000103,1610612741.0,Rasual Butler,NaN,2011-04-21,96.110638
29558,41000104,1610612741.0,Rasual Butler,NaN,2011-04-23,96.110638
29593,41000105,1610612741.0,Rasual Butler,101.5,2011-04-26,96.222917
30530,41000201,1610612741.0,Rasual Butler,NaN,2011-05-02,96.222917
30554,41000202,1610612741.0,Rasual Butler,NaN,2011-05-04,96.222917
30565,41000203,1610612741.0,Rasual Butler,51.5,2011-05-06,95.310204
30589,41000204,1610612741.0,Rasual Butler,NaN,2011-05-08,95.310204
30625,41000205,1610612741.0,Rasual Butler,200.0,2011-05-10,97.404000
30637,41000206,1610612741.0,Rasual Butler,NaN,2011-05-12,97.404000
31057,41000301,1610612741.0,Rasual Butler,NaN,2011-05-15,97.404000
31081,41000302,1610612741.0,Rasual Butler,NaN,2011-05-18,97.404000
31093,41000303,1610612741.0,Rasual Butler,NaN,2011-05-22,97.404000
31117,41000304,1610612741.0,Rasual Butler,NaN,2011-05-24,97.404000
31153,41000305,1610612741.0,Rasual Butler,NaN,2011-05-26,97.404000

In [230]:
#df_inj2[df_inj2.player.str.contains("Da'Sean Butler")]
df_inj3[df_inj3.player.str.contains("Da'Sean Butler")]

      game_date   Team     team_id          player   game_id
1333 2011-03-25  Spurs  1610612759  Da'Sean Butler  21001078

In [231]:
df_inj3[~df_inj3.player.str.contains("Da'Sean Butler")]

      game_date       Team     team_id              player   game_id
0    2010-10-26    Blazers  1610612757     Elliot Williams  21000002
1    2010-10-26    Blazers  1610612757           Greg Oden  21000002
2    2010-10-26    Blazers  1610612757      Joel Przybilla  21000002
3    2010-10-26    Celtics  1610612738       Avery Bradley  21000001
4    2010-10-26    Celtics  1610612738    Kendrick Perkins  21000001
...         ...        ...         ...                 ...       ...
1673 2011-05-26      Bulls  1610612741           Omer Asik  41000305
1674 2011-05-31       Heat  1610612748  Zydrunas Ilgauskas  41000401
1675 2011-06-05  Mavericks  1610612742     Brendan Haywood  41000403
1676 2011-06-07  Mavericks  1610612742   Rodrigue Beaubois  41000404
1677 2011-06-09  Mavericks  1610612742     Brendan Haywood  41000405

[1677 rows x 5 columns]

In [232]:
#dj_inj4 is the start of a row drop bc of no play data for Da'Sean Butler
df_inj4 = df_inj3[~df_inj3.player.str.contains("Da'Sean Butler")]

In [233]:
# 'Daniel Orton'
df_inj4[df_inj4.player.str.contains('Daniel Orton')]

      game_date   Team     team_id        player   game_id
75   2010-10-28  Magic  1610612753  Daniel Orton  21000017
518  2010-12-23  Magic  1610612753  Daniel Orton  21000430
1644 2011-04-16  Magic  1610612753  Daniel Orton  41000131

In [234]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Orton')]

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [235]:
df_injuries[df_injuries.player.str.contains('Daniel Orton')]

,Date,Team,Acquired,Relinquished,Notes,team_id,player,A
95,2010-10-28,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
850,2010-12-23,Magic,,Daniel Orton,arthroscopic surgery on left knee (out for season),1610612753,Daniel Orton,0
2554,2011-04-16,Magic,,Daniel Orton,placed on IL with surgery on left knee (out for season),1610612753,Daniel Orton,0
2650,2011-12-25,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
2720,2011-12-30,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
2738,2012-01-01,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
2828,2012-01-06,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
2944,2012-01-12,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
3054,2012-01-18,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
3153,2012-01-23,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
3210,2012-01-26,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
3439,2012-02-08,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
3573,2012-02-17,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
3597,2012-02-19,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
3668,2012-02-22,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
4152,2012-03-21,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
4190,2012-03-23,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
4294,2012-03-28,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,0
4337,2012-03-30,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton,1
5090,2012-11-01,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
5204,2012-11-09,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
5234,2012-11-12,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
5523,2012-12-07,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
5609,2012-12-14,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
5679,2012-12-19,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
5749,2012-12-25,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
6046,2013-01-13,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
6076,2013-01-16,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
6313,2013-02-04,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
6553,2013-02-27,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
6583,2013-03-01,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
6622,2013-03-05,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
6821,2013-03-20,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
6878,2013-03-24,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
7093,2013-04-05,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
7129,2013-04-07,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
7157,2013-04-09,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
7380,2013-04-21,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton,0
7432,2013-05-01,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton,1
7694,2013-11-08,76ers,,Daniel Orton,sore right knee (DNP),1610612755,Daniel Orton,0
7714,2013-11-09,76ers,,Daniel Orton,sore right knee (DNP),1610612755,Daniel Orton,0
7739,2013-11-11,76ers,,Daniel Orton,sore right knee (DNP),1610612755,Daniel Orton,0

In [236]:
# 'Daniel Orton' out of the 2010-11 season due to injury but returns in 2011-12 season

In [237]:
# 'Didier Mbenga'
df_inj4[df_inj4.player.str.contains('Mbenga')]

      game_date     Team     team_id         player   game_id
743  2011-01-17  Hornets  1610612766  Didier Mbenga  21000601
1088 2011-02-27  Hornets  1610612766  Didier Mbenga  21000883
1370 2011-03-30  Hornets  1610612766  Didier Mbenga  21001106

In [238]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Mbenga')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
233    21000010  1610612740.0   DJ Mbenga          95.6 2010-10-27   95.600000
647    21000027  1610612740.0   DJ Mbenga         167.3 2010-10-29  131.450000
917    21000039  1610612740.0   DJ Mbenga          71.3 2010-10-30  111.400000
1399   21000059  1610612740.0   DJ Mbenga          91.1 2010-11-03  106.325000
1796   21000075  1610612740.0   DJ Mbenga          58.7 2010-11-05   96.800000
1979   21000083  1610612740.0   DJ Mbenga           NaN 2010-11-06   96.800000
2517   21000105  1610612740.0   DJ Mbenga          66.7 2010-11-09   91.783333
3261   21000136  1610612740.0   DJ Mbenga           NaN 2010-11-13   91.783333
3488   21000146  1610612740.0   DJ Mbenga         138.5 2010-11-15   98.457143
3910   21000163  1610612740.0   DJ Mbenga           NaN 2010-11-17   98.457143
4245   21000177  1610612740.0   DJ Mbenga         185.2 2010-11-19  109.300000
4615   21000193  1610612740.0   DJ Mbenga          48.8 2010-11-21  102.577778
4832   21000202  1610612740.0   DJ Mbenga         147.8 2010-11-22  107.100000
5235   21000219  1610612740.0   DJ Mbenga         103.2 2010-11-24  106.745455
5574   21000233  1610612740.0   DJ Mbenga          76.7 2010-11-26  104.241667
5849   21000244  1610612740.0   DJ Mbenga         123.9 2010-11-28  105.753846
6002   21000251  1610612740.0   DJ Mbenga          58.0 2010-11-29  102.342857
6401   21000267  1610612740.0   DJ Mbenga          60.7 2010-12-01   99.566667
6762   21000282  1610612740.0   DJ Mbenga         113.4 2010-12-03  100.431250
7700   21000321  1610612740.0   DJ Mbenga           NaN 2010-12-08  100.431250
8031   21000335  1610612740.0   DJ Mbenga          97.6 2010-12-10  100.264706
8384   21000350  1610612740.0   DJ Mbenga         100.4 2010-12-12  100.272222
8949   21000373  1610612740.0   DJ Mbenga           NaN 2010-12-15  100.272222
9283   21000387  1610612740.0   DJ Mbenga         150.0 2010-12-17  102.889474
9655   21000403  1610612740.0   DJ Mbenga         133.1 2010-12-19  104.400000
9775   21000408  1610612740.0   DJ Mbenga           NaN 2010-12-20  104.400000
10241  21000427  1610612740.0   DJ Mbenga         127.6 2010-12-22  105.504762
10599  21000442  1610612740.0   DJ Mbenga         126.5 2010-12-26  106.459091
10757  21000449  1610612740.0   DJ Mbenga         102.5 2010-12-27  106.286957
11200  21000467  1610612740.0   DJ Mbenga         104.3 2010-12-29  106.204167
11406  21000476  1610612740.0   DJ Mbenga          41.0 2010-12-31  103.596000
13589  21000567  1610612740.0   DJ Mbenga           NaN 2011-01-12  103.596000
13935  21000582  1610612740.0   DJ Mbenga           NaN 2011-01-14  103.596000
14079  21000588  1610612740.0   DJ Mbenga           NaN 2011-01-15  103.596000
15106  21000631  1610612740.0   DJ Mbenga          98.5 2011-01-21  103.400000
15478  21000646  1610612740.0   DJ Mbenga          81.0 2011-01-22  102.570370
15816  21000660  1610612740.0   DJ Mbenga         111.2 2011-01-24  102.878571
16211  21000677  1610612740.0   DJ Mbenga          48.7 2011-01-26  101.010345
16740  21000699  1610612740.0   DJ Mbenga          28.6 2011-01-29   98.596667
16910  21000706  1610612740.0   DJ Mbenga         100.0 2011-01-30   98.641935
17137  21000715  1610612740.0   DJ Mbenga          87.2 2011-02-01   98.284375
17362  21000725  1610612740.0   DJ Mbenga          78.7 2011-02-02   97.690909
17926  21000748  1610612740.0   DJ Mbenga         103.8 2011-02-05   97.870588
18216  21000760  1610612740.0   DJ Mbenga         104.2 2011-02-07   98.051429
18561  21000775  1610612740.0   DJ Mbenga           0.0 2011-02-09   95.327778
18869  21000788  1610612740.0   DJ Mbenga         113.6 2011-02-11   95.821622
19173  21000800  1610612740.0   DJ Mbenga          66.7 2011-02-12   95.055263
19711  21000823  1610612740.0   DJ Mbenga          60.1 2011-02-15   94.158974
19999  21000835  1610612740.0   DJ Mbenga           NaN 2011-02-16   94.158974
20467  21000854  1610612740.0   DJ Mbenga           NaN 2011-02-23   94.158974
20789  21000868  1610612740.0   DJ Mbenga           NaN 2011-02-25   94.158974
25794  21001077  1610612740.0   DJ Mbenga           NaN 2011-03-25   94.158974
26200  21001094  1610612740.0   DJ Mbenga           NaN 2011-03-27   94.158974
27483  21001147  1610612740.0   DJ Mbenga           NaN 2011-04-03   94.158974
28010  21001169  1610612740.0   DJ Mbenga           NaN 2011-04-06   94.158974
28371  21001184  1610612740.0   DJ Mbenga           NaN 2011-04-08   94.158974
28669  21001197  1610612740.0   DJ Mbenga          96.6 2011-04-10   94.220000
28946  21001208  1610612740.0   DJ Mbenga           NaN 2011-04-11   94.220000
29293  21001223  1610612740.0   DJ Mbenga          80.6 2011-04-13   93.887805
30107  41000151  1610612740.0   DJ Mbenga         106.0 2011-04-17   94.176190
30132  41000152  1610612740.0   DJ Mbenga          83.3 2011-04-20   93.923256
30169  41000153  1610612740.0   DJ Mbenga          90.4 2011-04-22   93.843182
30192  41000154  1610612740.0   DJ Mbenga         138.9 2011-04-24   94.844444
30206  41000155  1610612740.0   DJ Mbenga           NaN 2011-04-26   94.844444
30240  41000156  1610612740.0   DJ Mbenga         133.2 2011-04-28   95.678261

<font color='red'> RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR </font>

In [239]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

{"Da'Sean Butler",
 'Daniel Orton',
 'Didier Mbenga',
 'Eddy Curry',
 'Gerald Henderson Jr.',
 'Jannero Pargo',
 'Jianlian Yi',
 'Joe Alexander',
 'Jonas Jerebko',
 'Kelenna Azubuike',
 'Magnum Rolle',
 'Matt Janning',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Nene Hilario',
 'Robert Vaden',
 'Terrico White'}

In [240]:
set(df_or1011a.PLAYER_NAME) - set(df_inj3.player)

{'Al Jefferson',
 'Al-Farouq Aminu',
 'Andre Miller',
 'Antonio Daniels',
 'Ben Gordon',
 'Blake Griffin',
 'Bobby Simmons',
 'Boris Diaw',
 'Brook Lopez',
 'C.J. Watson',
 'Carl Landry',
 'Chris Johnson',
 'D.J. Augustin',
 'DJ Mbenga',
 'Darnell Jackson',
 'DeMar DeRozan',
 'DeMarcus Cousins',
 'DeShawn Stevenson',
 'Derek Fisher',
 'Donte Greene',
 'Dorell Wright',
 'Earl Barron',
 'Earl Boykins',
 'Earl Clark',
 'Earl Watson',
 'Eddie House',
 'Elton Brand',
 'Emeka Okafor',
 'Eric Bledsoe',
 'Eric Maynor',
 'Evan Turner',
 'Fabricio Oberto',
 'Gary Forbes',
 'Gerald Henderson',
 'Greg Monroe',
 'Hakim Warrick',
 'Hedo Turkoglu',
 'Ike Diogu',
 'Ime Udoka',
 'JR Smith',
 'James Harden',
 'James Johnson',
 'James Jones',
 'Jared Dudley',
 'Jarrett Jack',
 'Jarron Collins',
 'Jason Terry',
 'Jawad Williams',
 'Jeff Teague',
 'Jerel McNeal',
 'Joel Anthony',
 'Johan Petro',
 'Josh Childress',
 'Jrue Holiday',
 'Keith Bogans',
 'Kobe Bryant',
 'Kyle Korver',
 'Kyle Weaver',
 'Lamar Odom',
 'Landry Fields',
 'Larry Owens',
 'Luol Deng',
 'Marcin Gortat',
 'Marcus Cousin',
 'Marqus Blakely',
 'Marreese Speights',
 'Metta World Peace',
 'Mike Bibby',
 'Mike Conley',
 'Mike Dunleavy',
 'Mike Harris',
 'Nene',
 'Patrick Ewing',
 'Pau Gasol',
 'Ramon Sessions',
 'Richard Jefferson',
 'Ronald Dupree',
 'Royal Ivey',
 'Russell Westbrook',
 'Sam Young',
 'Sasha Pavlovic',
 'Serge Ibaka',
 'Shane Battier',
 'Shannon Brown',
 'Thaddeus Young',
 'Travis Outlaw',
 'Vladimir Radmanovic',
 'Wesley Matthews',
 'Willie Green',
 'Yi Jianlian'}

<font color='red'>QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ</font>

In [241]:
df_inj3.player

0          Elliot Williams
1                Greg Oden
2           Joel Przybilla
3            Avery Bradley
4         Kendrick Perkins
               ...
1673             Omer Asik
1674    Zydrunas Ilgauskas
1675       Brendan Haywood
1676     Rodrigue Beaubois
1677       Brendan Haywood
Name: player, Length: 1678, dtype: object

In [242]:
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,73.900000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,108.415054

In [243]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Price')][~df_or1011a.PLAYER_NAME.str.contains('Ronnie')]

<ipython-input-243-6b89c6307d51>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Price')][~df_or1011a.PLAYER_NAME.str.contains('Ronnie')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
3643   21000152  1610612754.0    AJ Price          90.6 2010-11-16   90.600000
4026   21000168  1610612754.0    AJ Price         119.8 2010-11-18  105.200000
4385   21000183  1610612754.0    AJ Price          94.6 2010-11-20  101.666667
6825   21000285  1610612754.0    AJ Price           NaN 2010-12-03  101.666667
7245   21000302  1610612754.0    AJ Price         130.9 2010-12-06  108.975000
7641   21000319  1610612754.0    AJ Price           NaN 2010-12-08  108.975000
7917   21000330  1610612754.0    AJ Price           NaN 2010-12-10  108.975000
8193   21000342  1610612754.0    AJ Price         103.6 2010-12-11  107.900000
9585   21000400  1610612754.0    AJ Price           NaN 2010-12-19  107.900000
9788   21000408  1610612754.0    AJ Price           NaN 2010-12-20  107.900000
11119  21000464  1610612754.0    AJ Price          60.0 2010-12-29   99.916667
11467  21000478  1610612754.0    AJ Price           NaN 2010-12-31   99.916667
12841  21000536  1610612754.0    AJ Price         110.5 2011-01-08  101.428571
13472  21000562  1610612754.0    AJ Price           NaN 2011-01-12  101.428571
14939  21000624  1610612754.0    AJ Price         120.8 2011-01-19  103.850000
15564  21000650  1610612754.0    AJ Price          97.2 2011-01-22  103.111111
15609  21000652  1610612754.0    AJ Price         126.4 2011-01-23  105.440000
16007  21000668  1610612754.0    AJ Price          87.3 2011-01-26  103.790909
16320  21000681  1610612754.0    AJ Price         126.1 2011-01-28  105.650000
16594  21000693  1610612754.0    AJ Price          72.4 2011-01-29  103.092308
16968  21000708  1610612754.0    AJ Price          94.6 2011-01-31  102.485714
17245  21000720  1610612754.0    AJ Price         123.3 2011-02-02  103.873333
17594  21000734  1610612754.0    AJ Price          80.6 2011-02-04  102.418750
18084  21000755  1610612754.0    AJ Price         116.2 2011-02-06  103.229412
18417  21000769  1610612754.0    AJ Price         131.8 2011-02-08  104.816667
18550  21000774  1610612754.0    AJ Price         109.3 2011-02-09  105.052632
18861  21000787  1610612754.0    AJ Price         128.7 2011-02-11  106.235000
19208  21000802  1610612754.0    AJ Price          78.4 2011-02-12  104.909524
19602  21000818  1610612754.0    AJ Price         126.1 2011-02-15  105.872727
19827  21000828  1610612754.0    AJ Price         114.2 2011-02-16  106.234783
20095  21000839  1610612754.0    AJ Price          95.1 2011-02-22  105.770833
20322  21000848  1610612754.0    AJ Price          93.7 2011-02-23  105.288000
20656  21000862  1610612754.0    AJ Price         111.2 2011-02-25  105.515385
21062  21000879  1610612754.0    AJ Price          94.9 2011-02-27  105.122222
21421  21000894  1610612754.0    AJ Price          78.8 2011-03-01  104.182143
21745  21000908  1610612754.0    AJ Price          87.5 2011-03-02  103.606897
22057  21000921  1610612754.0    AJ Price          79.4 2011-03-04  102.800000
22201  21000927  1610612754.0    AJ Price         121.9 2011-03-05  103.416129
22737  21000949  1610612754.0    AJ Price         122.4 2011-03-08  104.009375
22988  21000960  1610612754.0    AJ Price          86.1 2011-03-09  103.466667
23226  21000970  1610612754.0    AJ Price         128.2 2011-03-11  104.194118
23681  21000989  1610612754.0    AJ Price          88.5 2011-03-13  103.745714
23956  21001000  1610612754.0    AJ Price          87.2 2011-03-15  103.286111
24040  21001004  1610612754.0    AJ Price          68.1 2011-03-16  102.335135
24365  21001017  1610612754.0    AJ Price          80.5 2011-03-18  101.760526
24688  21001031  1610612754.0    AJ Price          89.9 2011-03-19  101.456410
25027  21001045  1610612754.0    AJ Price           NaN 2011-03-21  101.456410
25239  21001054  1610612754.0    AJ Price         100.8 2011-03-23  101.440000
25587  21001068  1610612754.0    AJ Price          98.9 2011-03-25  101.378049
25933  21001083  1610612754.0    AJ Price         125.4 2011-03-26  101.950000
26281  21001097  1610612754.0    AJ Price         123.0 2011-03-28  102.439535
26521  21001107  1610612754.0    AJ Price         102.7 2011-03-30  102.445455
26834  21001120  1610612754.0    AJ Price         128.0 2011-04-01  103.013333
27467  21001147  1610612754.0    AJ Price         118.6 2011-04-03  103.352174
27865  21001163  1610612754.0    AJ Price          96.5 2011-04-06  103.206383
28176  21001176  1610612754.0    AJ Price         100.5 2011-04-08  103.150000
28704  21001198  1610612754.0    AJ Price         130.8 2011-04-10  103.714286
29196  21001219  1610612754.0    AJ Price         102.9 2011-04-13  103.698000
29484  41000101  1610612754.0    AJ Price         103.2 2011-04-16  103.688235
29508  41000102  1610612754.0    AJ Price          82.3 2011-04-18  103.276923
29543  41000103  1610612754.0    AJ Price          93.6 2011-04-21  103.094340
29567  41000104  1610612754.0    AJ Price         121.6 2011-04-23  103.437037
29581  41000105  1610612754.0    AJ Price          94.0 2011-04-26  103.265455

In [244]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Price')][~df_or1011a.PLAYER_NAME.str.contains('Ronnie')].shape

<ipython-input-244-117f6c86c365>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Price')][~df_or1011a.PLAYER_NAME.str.contains('Ronnie')].shape

(63, 6)

In [245]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('AJ Price')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
3643   21000152  1610612754.0    AJ Price          90.6 2010-11-16   90.600000
4026   21000168  1610612754.0    AJ Price         119.8 2010-11-18  105.200000
4385   21000183  1610612754.0    AJ Price          94.6 2010-11-20  101.666667
6825   21000285  1610612754.0    AJ Price           NaN 2010-12-03  101.666667
7245   21000302  1610612754.0    AJ Price         130.9 2010-12-06  108.975000
7641   21000319  1610612754.0    AJ Price           NaN 2010-12-08  108.975000
7917   21000330  1610612754.0    AJ Price           NaN 2010-12-10  108.975000
8193   21000342  1610612754.0    AJ Price         103.6 2010-12-11  107.900000
9585   21000400  1610612754.0    AJ Price           NaN 2010-12-19  107.900000
9788   21000408  1610612754.0    AJ Price           NaN 2010-12-20  107.900000
11119  21000464  1610612754.0    AJ Price          60.0 2010-12-29   99.916667
11467  21000478  1610612754.0    AJ Price           NaN 2010-12-31   99.916667
12841  21000536  1610612754.0    AJ Price         110.5 2011-01-08  101.428571
13472  21000562  1610612754.0    AJ Price           NaN 2011-01-12  101.428571
14939  21000624  1610612754.0    AJ Price         120.8 2011-01-19  103.850000
15564  21000650  1610612754.0    AJ Price          97.2 2011-01-22  103.111111
15609  21000652  1610612754.0    AJ Price         126.4 2011-01-23  105.440000
16007  21000668  1610612754.0    AJ Price          87.3 2011-01-26  103.790909
16320  21000681  1610612754.0    AJ Price         126.1 2011-01-28  105.650000
16594  21000693  1610612754.0    AJ Price          72.4 2011-01-29  103.092308
16968  21000708  1610612754.0    AJ Price          94.6 2011-01-31  102.485714
17245  21000720  1610612754.0    AJ Price         123.3 2011-02-02  103.873333
17594  21000734  1610612754.0    AJ Price          80.6 2011-02-04  102.418750
18084  21000755  1610612754.0    AJ Price         116.2 2011-02-06  103.229412
18417  21000769  1610612754.0    AJ Price         131.8 2011-02-08  104.816667
18550  21000774  1610612754.0    AJ Price         109.3 2011-02-09  105.052632
18861  21000787  1610612754.0    AJ Price         128.7 2011-02-11  106.235000
19208  21000802  1610612754.0    AJ Price          78.4 2011-02-12  104.909524
19602  21000818  1610612754.0    AJ Price         126.1 2011-02-15  105.872727
19827  21000828  1610612754.0    AJ Price         114.2 2011-02-16  106.234783
20095  21000839  1610612754.0    AJ Price          95.1 2011-02-22  105.770833
20322  21000848  1610612754.0    AJ Price          93.7 2011-02-23  105.288000
20656  21000862  1610612754.0    AJ Price         111.2 2011-02-25  105.515385
21062  21000879  1610612754.0    AJ Price          94.9 2011-02-27  105.122222
21421  21000894  1610612754.0    AJ Price          78.8 2011-03-01  104.182143
21745  21000908  1610612754.0    AJ Price          87.5 2011-03-02  103.606897
22057  21000921  1610612754.0    AJ Price          79.4 2011-03-04  102.800000
22201  21000927  1610612754.0    AJ Price         121.9 2011-03-05  103.416129
22737  21000949  1610612754.0    AJ Price         122.4 2011-03-08  104.009375
22988  21000960  1610612754.0    AJ Price          86.1 2011-03-09  103.466667
23226  21000970  1610612754.0    AJ Price         128.2 2011-03-11  104.194118
23681  21000989  1610612754.0    AJ Price          88.5 2011-03-13  103.745714
23956  21001000  1610612754.0    AJ Price          87.2 2011-03-15  103.286111
24040  21001004  1610612754.0    AJ Price          68.1 2011-03-16  102.335135
24365  21001017  1610612754.0    AJ Price          80.5 2011-03-18  101.760526
24688  21001031  1610612754.0    AJ Price          89.9 2011-03-19  101.456410
25027  21001045  1610612754.0    AJ Price           NaN 2011-03-21  101.456410
25239  21001054  1610612754.0    AJ Price         100.8 2011-03-23  101.440000
25587  21001068  1610612754.0    AJ Price          98.9 2011-03-25  101.378049
25933  21001083  1610612754.0    AJ Price         125.4 2011-03-26  101.950000
26281  21001097  1610612754.0    AJ Price         123.0 2011-03-28  102.439535
26521  21001107  1610612754.0    AJ Price         102.7 2011-03-30  102.445455
26834  21001120  1610612754.0    AJ Price         128.0 2011-04-01  103.013333
27467  21001147  1610612754.0    AJ Price         118.6 2011-04-03  103.352174
27865  21001163  1610612754.0    AJ Price          96.5 2011-04-06  103.206383
28176  21001176  1610612754.0    AJ Price         100.5 2011-04-08  103.150000
28704  21001198  1610612754.0    AJ Price         130.8 2011-04-10  103.714286
29196  21001219  1610612754.0    AJ Price         102.9 2011-04-13  103.698000
29484  41000101  1610612754.0    AJ Price         103.2 2011-04-16  103.688235
29508  41000102  1610612754.0    AJ Price          82.3 2011-04-18  103.276923
29543  41000103  1610612754.0    AJ Price          93.6 2011-04-21  103.094340
29567  41000104  1610612754.0    AJ Price         121.6 2011-04-23  103.437037
29581  41000105  1610612754.0    AJ Price          94.0 2011-04-26  103.265455

In [246]:
df_inj2.head()

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,A,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,0,21000002
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,0,21000002
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,1610612757,Joel Przybilla,0,21000002
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,1610612738,Avery Bradley,0,21000001
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,1610612738,Kendrick Perkins,0,21000001

In [247]:
df_inj2.shape

(1678, 9)

In [248]:
df_or1011a.head()

    game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date  cma2
0  21000001  1610612748.0   LeBron James          91.3 2010-10-26  91.3
1  21000001  1610612748.0     Chris Bosh          86.7 2010-10-26  86.7
2  21000001  1610612748.0   Joel Anthony          49.1 2010-10-26  49.1
3  21000001  1610612748.0    Dwyane Wade          81.9 2010-10-26  81.9
4  21000001  1610612748.0  Carlos Arroyo          73.9 2010-10-26  73.9

In [249]:
df_or1011a.shape

(31419, 6)

In [250]:
pd.merge(df_inj3, df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_id', 'player'], how='inner')

,game_date_x,Team,team_id,player,game_id,TEAM_ID,E_OFF_RATING,game_date_y,cma2
0,2010-10-26,Heat,1610612748,Mario Chalmers,21000001,1610612748.0,NaN,2010-10-26,NaN
1,2010-10-27,Bucks,1610612749,Jon Brockman,21000010,1610612749.0,NaN,2010-10-27,NaN
2,2010-10-27,Bucks,1610612749,Luc Mbah a Moute,21000010,1610612749.0,NaN,2010-10-27,NaN
3,2010-10-29,Pistons,1610612765,Will Bynum,21000024,1610612765.0,NaN,2010-10-29,100.400000
4,2010-10-30,Pistons,1610612765,Will Bynum,21000035,1610612765.0,NaN,2010-10-30,100.400000
5,2010-11-02,Pistons,1610612765,Richard Hamilton,21000049,1610612765.0,NaN,2010-11-02,87.500000
6,2010-11-02,Pistons,1610612765,Will Bynum,21000049,1610612765.0,NaN,2010-11-02,100.400000
7,2010-11-03,Hawks,1610612737,Jamal Crawford,21000054,1610612737.0,NaN,2010-11-03,109.625000
8,2010-11-03,Jazz,1610612762,Jeremy Evans,21000061,1610612762.0,NaN,2010-11-03,106.650000
9,2010-11-03,Jazz,1610612762,Kyrylo Fesenko,21000061,1610612762.0,NaN,2010-11-03,99.900000
10,2010-11-03,Pistons,1610612765,Richard Hamilton,21000054,1610612765.0,NaN,2010-11-03,87.500000
11,2010-11-03,Pistons,1610612765,Will Bynum,21000054,1610612765.0,NaN,2010-11-03,100.400000
12,2010-11-03,Warriors,1610612744,Brandan Wright,21000063,1610612744.0,NaN,2010-11-03,102.766667
13,2010-11-05,Bucks,1610612749,Andrew Bogut,21000068,1610612749.0,NaN,2010-11-05,97.440000
14,2010-11-05,Hawks,1610612737,Marvin Williams,21000074,1610612737.0,NaN,2010-11-05,110.460000
15,2010-11-05,Jazz,1610612762,Jeremy Evans,21000078,1610612762.0,NaN,2010-11-05,106.650000
16,2010-11-06,Blazers,1610612757,Rudy Fernandez,21000087,1610612757.0,NaN,2010-11-06,93.740000
17,2010-11-07,Hawks,1610612737,Marvin Williams,21000090,1610612737.0,NaN,2010-11-07,110.460000
18,2010-11-08,Hawks,1610612737,Marvin Williams,21000096,1610612737.0,NaN,2010-11-08,110.460000
19,2010-11-08,Magic,1610612753,Mickael Pietrus,21000096,1610612753.0,NaN,2010-11-08,90.440000
20,2010-11-09,Bucks,1610612749,Carlos Delfino,21000104,1610612749.0,NaN,2010-11-09,89.842857
21,2010-11-10,Bucks,1610612749,Carlos Delfino,21000108,1610612749.0,NaN,2010-11-10,89.842857
22,2010-11-10,Clippers,1610612746,Chris Kaman,21000116,1610612746.0,NaN,2010-11-10,89.925000
23,2010-11-10,Hawks,1610612737,Marvin Williams,21000108,1610612737.0,NaN,2010-11-10,110.460000
24,2010-11-10,Timberwolves,1610612750,Wayne Ellington,21000117,1610612750.0,NaN,2010-11-10,83.857143
25,2010-11-10,Wizards,1610612764,Kevin Seraphin,21000111,1610612764.0,NaN,2010-11-10,NaN
26,2010-11-11,Celtics,1610612738,Jermaine O'Neal,21000118,1610612738.0,NaN,2010-11-11,94.971429
27,2010-11-12,Clippers,1610612746,Randy Foye,21000129,1610612746.0,NaN,2010-11-12,96.000000
28,2010-11-13,Bucks,1610612749,Carlos Delfino,21000137,1610612749.0,NaN,2010-11-13,89.842857
29,2010-11-13,Celtics,1610612738,Jermaine O'Neal,21000135,1610612738.0,NaN,2010-11-13,94.971429
30,2010-11-13,Raptors,1610612761,Reggie Evans,21000133,1610612761.0,NaN,2010-11-13,96.155556
31,2010-11-14,Rockets,1610612745,Chase Budinger,21000142,1610612745.0,NaN,2010-11-14,104.712500
32,2010-11-14,Timberwolves,1610612750,Nikola Pekovic,21000139,1610612750.0,NaN,2010-11-14,103.070000
33,2010-11-14,Timberwolves,1610612750,Wayne Ellington,21000139,1610612750.0,NaN,2010-11-14,83.857143
34,2010-11-15,Clippers,1610612746,Randy Foye,21000150,1610612746.0,NaN,2010-11-15,96.000000
35,2010-11-15,Jazz,1610612762,Raja Bell,21000148,1610612762.0,NaN,2010-11-15,99.310000
36,2010-11-15,Timberwolves,1610612750,Nikola Pekovic,21000144,1610612750.0,NaN,2010-11-15,103.070000
37,2010-11-15,Timberwolves,1610612750,Wayne Ellington,21000144,1610612750.0,NaN,2010-11-15,83.857143
38,2010-11-16,Blazers,1610612757,Brandon Roy,21000154,1610612757.0,NaN,2010-11-16,108.063636
39,2010-11-16,Bucks,1610612749,Carlos Delfino,21000155,1610612749.0,NaN,2010-11-16,89.842857
40,2010-11-17,Clippers,1610612746,Randy Foye,21000162,1610612746.0,NaN,2010-11-17,96.000000
41,2010-11-17,Jazz,1610612762,Kyrylo Fesenko,21000165,1610612762.0,NaN,2010-11-17,114.188889
42,2010-11-17,Rockets,1610612745,Chase Budinger,21000164,1610612745.0,NaN,2010-11-17,104.712500
43,2010-11-18,Blazers,1610612757,Brandon Roy,21000170,1610612757.0,NaN,2010-11-18,108.063636
44,2010-11-18,Magic,1610612753,Jason Williams,21000169,1610612753.0,NaN,2010-11-18,102.380000
45,2010-11-19,Bucks,1610612749,Carlos Delfino,21000172,1610612749.0,NaN,2010-11-19,89.842857
46,2010-11-19,Heat,1610612748,Juwan Howard,21000175,1610612748.0,NaN,2010-11-19,109.533333
47,2010-11-19,Knicks,1610612752,Timofey Mozgov,21000181,1610612752.0,NaN,2010-11-19,104.566667
48,2010-11-19,Warriors,1610612744,Brandan Wright,21000181,1610612744.0,NaN,2010-11-19,90.175000
49,2010-11-20,Blazers,1610612757,Brandon Roy,21000189,1610612757.0,NaN,2010-11-20,108.063636
50,2010-11-20,Bucks,1610612749,Carlos Delfino,21000186,1610612749.0,NaN,2010-11-20,89.842857
51,2010-11-20,Suns,1610612756,Steve Nash,21000182,1610612756.0,NaN,2010-11-20,111.945455
52,2010-11-21,Wizards,1610612764,John Wall,21000192,1610612764.0,NaN,2010-11-21,94.000000
53,2010-11-22,Warriors,1610612744,Brandan Wright,21000201,1610612744.0,NaN,2010-11-22,90.175000
54,2010-11-24,Bucks,1610612749,Andrew Bogut,21000210,1610612749.0,NaN,2010-11-24,98.208333
55,2010-11-24,Bucks,1610612749,Carlos Delfino,21000210,1610612749.0,NaN,2010-11-24,89.842857
56,2010-11-24,Bulls,1610612741,Taj Gibson,21000218,1610612741.0,NaN,2010-11-24,103.300000
57,2010-11-24,Celtics,1610612738,Delonte West,21000212,1610612738.0,66.7,2010-11-24,89.300000
58,2010-11-24,Warriors,1610612744,Brandan Wright,21000217,1610612744.0,NaN,2010-11-24,90.175000
59,2010-11-26,Bucks,1610612749,Andrew Bogut,21000225,1610612749.0,NaN,2010-11-26,98.208333
60,2010-11-26,Bucks,1610612749,Carlos Delfino,21000225,1610612749.0,NaN,2010-11-26,89.842857
61,2010-11-26,Raptors,1610612761,Reggie Evans,21000224,1610612761.0,82.8,2010-11-26,95.280000
62,2010-11-26,Warriors,1610612744,Brandan Wright,21000232,1610612744.0,NaN,2010-11-26,90.175000
63,2010-11-27,Bucks,1610612749,Andrew Bogut,21000240,1610612749.0,NaN,2010-11-27,98.208333
64,2010-11-27,Bucks,1610612749,Corey Maggette,21000240,1610612749.0,NaN,2010-11-27,95.660000
65,2010-11-27,Bucks,1610612749,Drew Gooden,21000240,1610612749.0,NaN,2010-11-27,92.273333
66,2010-11-27,Wizards,1610612764,John Wall,21000235,1610612764.0,NaN,2010-11-27,95.370000
67,2010-11-28,Blazers,1610612757,Sean Marks,21000246,1610612757.0,NaN,2010-11-28,106.742857
68,2010-11-28,Clippers,1610612746,Randy Foye,21000245,1610612746.0,NaN,2010-11-28,106.671429
69,2010-11-28,Knicks,1610612752,Toney Douglas,21000243,1610612752.0,NaN,2010-11-28,105.211111
70,2010-11-28,Lakers,1610612747,Devin Ebanks,21000249,1610612747.0,NaN,2010-11-28,84.000000
71,2010-11-28,Raptors,1610612761,Peja Stojakovic,21000242,1610612761.0,NaN,2010-11-28,105.662500
72,2010-11-29,Bucks,1610612749,Andrew Bogut,21000253,1610612749.0,NaN,2010-11-29,98.208333
73,2010-11-29,Bucks,1610612749,Corey Maggette,21000253,1610612749.0,NaN,2010-11-29,95.660000
74,2010-11-29,Bucks,1610612749,Drew Gooden,21000253,1610612749.0,NaN,2010-11-29,92.273333
75,2010-11-29,Wizards,1610612764,John Wall,21000250,1610612764.0,NaN,2010-11-29,95.370000
76,2010-12-01,Bucks,1610612749,Andrew Bogut,21000270,1610612749.0,NaN,2010-12-01,98.208333
77,2010-12-01,Raptors,1610612761,Peja Stojakovic,21000263,1610612761.0,NaN,2010-12-01,105.662500
78,2010-12-03,Magic,1610612753,Dwight Howard,21000279,1610612753.0,NaN,2010-12-03,108.494737
79,2010-12-03,Magic,1610612753,Jameer Nelson,21000279,1610612753.0,NaN,2010-12-03,110.862500
80,2010-12-03,Magic,1610612753,JJ Redick,21000279,1610612753.0,NaN,2010-12-03,100.500000
81,2010-12-03,Raptors,1610612761,Peja Stojakovic,21000276,1610612761.0,NaN,2010-12-03,105.662500
82,2010-12-04,Magic,1610612753,Dwight Howard,21000292,1610612753.0,NaN,2010-12-04,108.494737
83,2010-12-04,Magic,1610612753,JJ Redick,21000292,1610612753.0,NaN,2010-12-04,100.500000
84,2010-12-04,Magic,1610612753,Jameer Nelson,21000292,1610612753.0,NaN,2010-12-04,110.862500
85,2010-12-04,Magic,1610612753,Ryan Anderson,21000292,1610612753.0,NaN,2010-12-04,93.272727
86,2010-12-04,Timberwolves,1610612750,Michael Beasley,21000291,1610612750.0,NaN,2010-12-04,101.661111
87,2010-12-05,Celtics,1610612738,Rajon Rondo,21000294,1610612738.0,NaN,2010-12-05,111.106250
88,2010-12-05,Raptors,1610612761,Peja Stojakovic,21000295,1610612761.0,NaN,2010-12-05,105.662500
89,2010-12-05,Thunder,1610612760,DJ White,21000297,1610612760.0,NaN,2010-12-05,110.583333
90,2010-12-05,Warriors,1610612744,Rodney Carney,21000297,1610612744.0,NaN,2010-12-05,94.494737
91,2010-12-06,Bucks,1610612749,Drew Gooden,21000306,1610612749.0,NaN,2010-12-06,91.518750
92,2010-12-06,Magic,1610612753,Jameer Nelson,21000303,1610612753.0,NaN,2010-12-06,110.862500
93,2010-12-08,Jazz,1610612762,Kyrylo Fesenko,21000324,1610612762.0,NaN,2010-12-08,102.833333
94,2010-12-08,Nuggets,1610612743,Carmelo Anthony,21000316,1610612743.0,NaN,2010-12-08,105.928571
95,2010-12-08,Raptors,1610612761,Peja Stojakovic,21000318,1610612761.0,NaN,2010-12-08,105.662500
96,2010-12-08,Timberwolves,1610612750,Darko Milicic,21000320,1610612750.0,NaN,2010-12-08,99.780952
97,2010-12-08,Wizards,1610612764,John Wall,21000325,1610612764.0,NaN,2010-12-08,98.000000
98,2010-12-09,Celtics,1610612738,Shaquille O'Neal,21000327,1610612738.0,NaN,2010-12-09,118.206250
99,2010-12-10,Jazz,1610612762,Raja Bell,21000339,1610612762.0,NaN,2010-12-10,102.536364
100,2010-12-11,Bulls,1610612741,Kurt Thomas,21000345,1610612741.0,116.3,2010-12-11,57.780000
101,2010-12-11,Cavaliers,1610612739,Ryan Hollins,21000347,1610612739.0,NaN,2010-12-11,100.822727
102,2010-12-11,Hawks,1610612737,Zaza Pachulia,21000342,1610612737.0,107.8,2010-12-11,102.370833
103,2010-12-11,Jazz,1610612762,Kyrylo Fesenko,21000346,1610612762.0,NaN,2010-12-11,102.833333
104,2010-12-11,Jazz,1610612762,Raja Bell,21000346,1610612762.0,NaN,2010-12-11,102.536364
105,2010-12-11,Pacers,1610612754,Jeff Foster,21000342,1610612754.0,114.2,2010-12-11,112.300000
106,2010-12-11,Raptors,1610612761,Peja Stojakovic,21000344,1610612761.0,NaN,2010-12-11,105.662500
107,2010-12-12,Magic,1610612753,Chris Duhon,21000354,1610612753.0,NaN,2010-12-12,102.591304
108,2010-12-13,Jazz,1610612762,Raja Bell,21000359,1610612762.0,NaN,2010-12-13,102.536364
109,2010-12-14,Kings,1610612758,Tyreke Evans,21000364,1610612758.0,NaN,2010-12-14,99.760000
110,2010-12-14,Magic,1610612753,Mickael Pietrus,21000365,1610612753.0,NaN,2010-12-14,99.647368
111,2010-12-14,Magic,1610612753,Quentin Richardson,21000365,1610612753.0,NaN,2010-12-14,102.660870
112,2010-12-14,Nuggets,1610612743,Chauncey Billups,21000365,1610612743.0,NaN,2010-12-14,107.881818
113,2010-12-14,Raptors,1610612761,Peja Stojakovic,21000360,1610612761.0,NaN,2010-12-14,105.662500
114,2010-12-15,Bulls,1610612741,Joakim Noah,21000370,1610612741.0,124.7,2010-12-15,105.537500
115,2010-12-15,Celtics,1610612738,Shaquille O'Neal,21000368,1610612738.0,NaN,2010-12-15,118.206250
116,2010-12-15,Raptors,1610612761,Andrea Bargnani,21000370,1610612761.0,NaN,2010-12-15,103.128000
117,2010-12-15,Raptors,1610612761,Peja Stojakovic,21000370,1610612761.0,NaN,2010-12-15,105.662500
118,2010-12-16,Celtics,1610612738,Rajon Rondo,21000379,1610612738.0,NaN,2010-12-16,111.475000
119,2010-12-16,Celtics,1610612738,Shaquille O'Neal,21000379,1610612738.0,NaN,2010-12-16,118.206250
120,2010-12-16,Nets,1610612751,Anthony Morrow,21000378,1610612751.0,NaN,2010-12-16,98.484000
121,2010-12-16,Nuggets,1610612743,Chauncey Billups,21000380,1610612743.0,NaN,2010-12-16,107.881818
122,2010-12-16,Spurs,1610612759,Tiago Splitter,21000380,1610612759.0,NaN,2010-12-16,105.140000
123,2010-12-16,Wizards,1610612764,John Wall,21000378,1610612764.0,NaN,2010-12-16,97.826667
124,2010-12-17,Blazers,1610612757,Brandon Roy,21000391,1610612757.0,NaN,2010-12-17,105.652174
125,2010-12-17,Raptors,1610612761,Sonny Weems,21000384,1610612761.0,NaN,2010-12-17,100.644000
126,2010-12-18,Blazers,1610612757,Brandon Roy,21000399,1610612757.0,NaN,2010-12-18,105.652174
127,2010-12-18,Blazers,1610612757,Marcus Camby,21000399,1610612757.0,NaN,2010-12-18,102.877778
128,2010-12-18,Blazers,1610612757,Nicolas Batum,21000399,1610612757.0,NaN,2010-12-18,99.796296
129,2010-12-18,Nuggets,1610612743,Chauncey Billups,21000398,1610612743.0,NaN,2010-12-18,107.881818
130,2010-12-18,Spurs,1610612759,George Hill,21000397,1610612759.0,NaN,2010-12-18,112.050000
131,2010-12-19,Celtics,1610612738,Rajon Rondo,21000400,1610612738.0,NaN,2010-12-19,111.475000
132,2010-12-19,Nets,1610612751,Quinton Ross,21000401,1610612751.0,NaN,2010-12-19,82.485714
133,2010-12-19,Pistons,1610612765,Richard Hamilton,21000403,1610612765.0,NaN,2010-12-19,96.896000
134,2010-12-19,Pistons,1610612765,Rodney Stuckey,21000403,1610612765.0,NaN,2010-12-19,103.046154
135,2010-12-19,Raptors,1610612761,Andrea Bargnani,21000402,1610612761.0,NaN,2010-12-19,103.288462
136,2010-12-19,Raptors,1610612761,Sonny Weems,21000402,1610612761.0,NaN,2010-12-19,100.644000
137,2010-12-20,Blazers,1610612757,Brandon Roy,21000412,1610612757.0,NaN,2010-12-20,105.652174
138,2010-12-20,Blazers,1610612757,Marcus Camby,21000412,1610612757.0,NaN,2010-12-20,102.877778
139,2010-12-20,Bucks,1610612749,Carlos Delfino,21000412,1610612749.0,NaN,2010-12-20,89.842857
140,2010-12-20,Clippers,1610612746,Craig Smith,21000414,1610612746.0,NaN,2010-12-20,91.691667
141,2010-12-20,Spurs,1610612759,George Hill,21000411,1610612759.0,NaN,2010-12-20,112.050000
142,2010-12-20,Warriors,1610612744,Dan Gadzuric,21000413,1610612744.0,NaN,2010-12-20,95.831818
143,2010-12-21,Magic,1610612753,Malik Allen,21000416,1610612753.0,NaN,2010-12-21,96.925000
144,2010-12-21,Nets,1610612751,Quinton Ross,21000418,1610612751.0,NaN,2010-12-21,82.485714
145,2010-12-21,Warriors,1610612744,Dan Gadzuric,21000419,1610612744.0,NaN,2010-12-21,95.831818
146,2010-12-22,Celtics,1610612738,Rajon Rondo,21000424,1610612738.0,NaN,2010-12-22,111.475000
147,2010-12-22,Nets,1610612751,Quinton Ross,21000427,1610612751.0,NaN,2010-12-22,82.485714
148,2010-12-22,Raptors,1610612761,Jerryd Bayless,21000422,1610612761.0,NaN,2010-12-22,101.536000
149,2010-12-22,Raptors,1610612761,Sonny Weems,21000422,1610612761.0,NaN,2010-12-22,100.644000
150,2010-12-22,Spurs,1610612759,George Hill,21000428,1610612759.0,NaN,2010-12-22,112.050000
151,2010-12-23,Spurs,1610612759,George Hill,21000430,1610612759.0,NaN,2010-12-23,112.050000
152,2010-12-25,Blazers,1610612757,Brandon Roy,21000437,1610612757.0,NaN,2010-12-25,105.652174
153,2010-12-25,Celtics,1610612738,Semih Erden,21000434,1610612738.0,NaN,2010-12-25,93.508333
154,2010-12-25,Magic,1610612753,Jason Williams,21000434,1610612753.0,NaN,2010-12-25,101.840000
155,2010-12-27,76ers,1610612755,Andre Iguodala,21000454,1610612755.0,NaN,2010-12-27,99.496000
156,2010-12-27,Blazers,1610612757,Brandon Roy,21000452,1610612757.0,NaN,2010-12-27,105.652174
157,2010-12-27,Bucks,1610612749,Drew Gooden,21000448,1610612749.0,NaN,2010-12-27,94.565000
158,2010-12-27,Magic,1610612753,Jason Williams,21000446,1610612753.0,NaN,2010-12-27,101.840000
159,2010-12-27,Raptors,1610612761,Sonny Weems,21000447,1610612761.0,NaN,2010-12-27,100.644000
160,2010-12-28,Blazers,1610612757,Brandon Roy,21000461,1610612757.0,NaN,2010-12-28,105.652174
161,2010-12-28,Blazers,1610612757,Marcus Camby,21000461,1610612757.0,NaN,2010-12-28,103.562069
162,2010-12-28,Bucks,1610612749,Drew Gooden,21000458,1610612749.0,NaN,2010-12-28,94.565000
163,2010-12-28,Magic,1610612753,Jason Williams,21000455,1610612753.0,NaN,2010-12-28,101.840000
164,2010-12-28,Magic,1610612753,Quentin Richardson,21000455,1610612753.0,NaN,2010-12-28,99.166667
165,2010-12-28,Raptors,1610612761,Jose Calderon,21000459,1610612761.0,NaN,2010-12-28,102.376923
166,2010-12-28,Raptors,1610612761,Sonny Weems,21000459,1610612761.0,NaN,2010-12-28,100.644000
167,2010-12-29,Cavaliers,1610612739,Mo Williams,21000463,1610612739.0,NaN,2010-12-29,94.261538
168,2010-12-29,Celtics,1610612738,Semih Erden,21000465,1610612738.0,NaN,2010-12-29,93.508333
169,2010-12-29,Jazz,1610612762,CJ Miles,21000472,1610612762.0,NaN,2010-12-29,107.051613
170,2010-12-29,Nuggets,1610612743,Kenyon Martin,21000466,1610612743.0,NaN,2010-12-29,126.625000
171,2010-12-30,Jazz,1610612762,CJ Miles,21000475,1610612762.0,NaN,2010-12-30,107.051613
172,2010-12-30,Jazz,1610612762,Mehmet Okur,21000475,1610612762.0,NaN,2010-12-30,91.150000
173,2010-12-30,Magic,1610612753,Jason Williams,21000473,1610612753.0,NaN,2010-12-30,101.840000
174,2010-12-30,Magic,1610612753,Quentin Richardson,21000473,1610612753.0,NaN,2010-12-30,99.166667
175,2010-12-31,Celtics,1610612738,Rajon Rondo,21000476,1610612738.0,NaN,2010-12-31,111.475000
176,2010-12-31,Nets,1610612751,Jordan Farmar,21000479,1610612751.0,NaN,2010-12-31,97.084375
177,2010-12-31,Nets,1610612751,Troy Murphy,21000479,1610612751.0,NaN,2010-12-31,91.952941
178,2010-12-31,Raptors,1610612761,Sonny Weems,21000480,1610612761.0,NaN,2010-12-31,100.644000
179,2010-12-31,Warriors,1610612744,Brandan Wright,21000477,1610612744.0,NaN,2010-12-31,88.611111
180,2011-01-01,Bucks,1610612749,Drew Gooden,21000489,1610612749.0,NaN,2011-01-01,94.565000
181,2011-01-01,Cavaliers,1610612739,Daniel Gibson,21000485,1610612739.0,NaN,2011-01-01,101.035484
182,2011-01-01,Cavaliers,1610612739,Mo Williams,21000485,1610612739.0,NaN,2011-01-01,94.261538
183,2011-01-01,Grizzlies,1610612763,Rudy Gay,21000491,1610612763.0,NaN,2011-01-01,104.058065
184,2011-01-01,Grizzlies,1610612763,Xavier Henry,21000491,1610612763.0,NaN,2011-01-01,97.596429
185,2011-01-01,Jazz,1610612762,CJ Miles,21000491,1610612762.0,NaN,2011-01-01,107.051613
186,2011-01-01,Mavericks,1610612742,Shawn Marion,21000489,1610612742.0,NaN,2011-01-01,100.151613
187,2011-01-01,Nets,1610612751,Jordan Farmar,21000487,1610612751.0,NaN,2011-01-01,97.084375
188,2011-01-02,Blazers,1610612757,Brandon Roy,21000496,1610612757.0,NaN,2011-01-02,105.652174
189,2011-01-02,Knicks,1610612752,Timofey Mozgov,21000492,1610612752.0,NaN,2011-01-02,91.687500
190,2011-01-02,Raptors,1610612761,Jerryd Bayless,21000494,1610612761.0,NaN,2011-01-02,100.342857
191,2011-01-02,Raptors,1610612761,Sonny Weems,21000494,1610612761.0,NaN,2011-01-02,100.644000
192,2011-01-03,76ers,1610612755,Spencer Hawes,21000502,1610612755.0,NaN,2011-01-03,97.451515
193,2011-01-04,Grizzlies,1610612763,O.J. Mayo,21000508,1610612763.0,NaN,2011-01-04,104.597059
194,2011-01-04,Grizzlies,1610612763,Xavier Henry,21000508,1610612763.0,NaN,2011-01-04,97.596429
195,2011-01-05,76ers,1610612755,Tony Battie,21000515,1610612755.0,NaN,2011-01-05,92.069565
196,2011-01-05,Bobcats,1610612766,Stephen Jackson,21000517,1610612766.0,NaN,2011-01-05,98.606452
197,2011-01-05,Bucks,1610612749,Brandon Jennings,21000514,1610612749.0,NaN,2011-01-05,96.808000
198,2011-01-05,Jazz,1610612762,Paul Millsap,21000520,1610612762.0,NaN,2011-01-05,108.057143
199,2011-01-07,Cavaliers,1610612739,Anderson Varejao,21000534,1610612739.0,NaN,2011-01-07,96.912903
200,2011-01-07,Cavaliers,1610612739,Anthony Parker,21000534,1610612739.0,NaN,2011-01-07,97.017647
201,2011-01-07,Raptors,1610612761,Jerryd Bayless,21000528,1610612761.0,NaN,2011-01-07,100.351724
202,2011-01-07,Raptors,1610612761,Sonny Weems,21000528,1610612761.0,NaN,2011-01-07,100.644000
203,2011-01-08,Bucks,1610612749,Andrew Bogut,21000538,1610612749.0,NaN,2011-01-08,96.932143
204,2011-01-08,Nets,1610612751,Devin Harris,21000538,1610612751.0,NaN,2011-01-08,101.982353
205,2011-01-09,Cavaliers,1610612739,Anthony Parker,21000547,1610612739.0,NaN,2011-01-09,97.017647
206,2011-01-09,Nuggets,1610612743,Ty Lawson,21000548,1610612743.0,NaN,2011-01-09,106.260000
207,2011-01-09,Raptors,1610612761,Sonny Weems,21000544,1610612761.0,NaN,2011-01-09,100.644000
208,2011-01-10,Rockets,1610612745,Brad Miller,21000552,1610612745.0,NaN,2011-01-10,106.163889
209,2011-01-11,Cavaliers,1610612739,Anderson Varejao,21000560,1610612739.0,NaN,2011-01-11,96.912903
210,2011-01-11,Cavaliers,1610612739,Anthony Parker,21000560,1610612739.0,NaN,2011-01-11,97.017647
211,2011-01-11,Knicks,1610612752,Anthony Randolph,21000559,1610612752.0,NaN,2011-01-11,89.571429

In [251]:
pd.merge(df_inj3, df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_id', 'player'], how='inner').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 666 entries, 0 to 665
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date_x   666 non-null    datetime64[ns]
 1   Team          666 non-null    object
 2   team_id       666 non-null    object
 3   player        666 non-null    object
 4   game_id       666 non-null    int64
 5   TEAM_ID       666 non-null    object
 6   E_OFF_RATING  23 non-null     float64
 7   game_date_y   666 non-null    datetime64[ns]
 8   cma2          662 non-null    float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(4)
memory usage: 52.0+ KB

In [252]:
pd.merge(df_inj3, df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_id', 'player','game_date'], how='inner')

,game_date,Team,team_id,player,game_id,TEAM_ID,E_OFF_RATING,cma2
0,2010-10-26,Heat,1610612748,Mario Chalmers,21000001,1610612748.0,NaN,NaN
1,2010-10-27,Bucks,1610612749,Jon Brockman,21000010,1610612749.0,NaN,NaN
2,2010-10-27,Bucks,1610612749,Luc Mbah a Moute,21000010,1610612749.0,NaN,NaN
3,2010-10-29,Pistons,1610612765,Will Bynum,21000024,1610612765.0,NaN,100.400000
4,2010-10-30,Pistons,1610612765,Will Bynum,21000035,1610612765.0,NaN,100.400000
5,2010-11-02,Pistons,1610612765,Richard Hamilton,21000049,1610612765.0,NaN,87.500000
6,2010-11-02,Pistons,1610612765,Will Bynum,21000049,1610612765.0,NaN,100.400000
7,2010-11-03,Hawks,1610612737,Jamal Crawford,21000054,1610612737.0,NaN,109.625000
8,2010-11-03,Jazz,1610612762,Jeremy Evans,21000061,1610612762.0,NaN,106.650000
9,2010-11-03,Jazz,1610612762,Kyrylo Fesenko,21000061,1610612762.0,NaN,99.900000
10,2010-11-03,Pistons,1610612765,Richard Hamilton,21000054,1610612765.0,NaN,87.500000
11,2010-11-03,Pistons,1610612765,Will Bynum,21000054,1610612765.0,NaN,100.400000
12,2010-11-03,Warriors,1610612744,Brandan Wright,21000063,1610612744.0,NaN,102.766667
13,2010-11-05,Bucks,1610612749,Andrew Bogut,21000068,1610612749.0,NaN,97.440000
14,2010-11-05,Hawks,1610612737,Marvin Williams,21000074,1610612737.0,NaN,110.460000
15,2010-11-05,Jazz,1610612762,Jeremy Evans,21000078,1610612762.0,NaN,106.650000
16,2010-11-06,Blazers,1610612757,Rudy Fernandez,21000087,1610612757.0,NaN,93.740000
17,2010-11-07,Hawks,1610612737,Marvin Williams,21000090,1610612737.0,NaN,110.460000
18,2010-11-08,Hawks,1610612737,Marvin Williams,21000096,1610612737.0,NaN,110.460000
19,2010-11-08,Magic,1610612753,Mickael Pietrus,21000096,1610612753.0,NaN,90.440000
20,2010-11-09,Bucks,1610612749,Carlos Delfino,21000104,1610612749.0,NaN,89.842857
21,2010-11-10,Bucks,1610612749,Carlos Delfino,21000108,1610612749.0,NaN,89.842857
22,2010-11-10,Clippers,1610612746,Chris Kaman,21000116,1610612746.0,NaN,89.925000
23,2010-11-10,Hawks,1610612737,Marvin Williams,21000108,1610612737.0,NaN,110.460000
24,2010-11-10,Timberwolves,1610612750,Wayne Ellington,21000117,1610612750.0,NaN,83.857143
25,2010-11-10,Wizards,1610612764,Kevin Seraphin,21000111,1610612764.0,NaN,NaN
26,2010-11-11,Celtics,1610612738,Jermaine O'Neal,21000118,1610612738.0,NaN,94.971429
27,2010-11-12,Clippers,1610612746,Randy Foye,21000129,1610612746.0,NaN,96.000000
28,2010-11-13,Bucks,1610612749,Carlos Delfino,21000137,1610612749.0,NaN,89.842857
29,2010-11-13,Celtics,1610612738,Jermaine O'Neal,21000135,1610612738.0,NaN,94.971429
30,2010-11-13,Raptors,1610612761,Reggie Evans,21000133,1610612761.0,NaN,96.155556
31,2010-11-14,Rockets,1610612745,Chase Budinger,21000142,1610612745.0,NaN,104.712500
32,2010-11-14,Timberwolves,1610612750,Nikola Pekovic,21000139,1610612750.0,NaN,103.070000
33,2010-11-14,Timberwolves,1610612750,Wayne Ellington,21000139,1610612750.0,NaN,83.857143
34,2010-11-15,Clippers,1610612746,Randy Foye,21000150,1610612746.0,NaN,96.000000
35,2010-11-15,Jazz,1610612762,Raja Bell,21000148,1610612762.0,NaN,99.310000
36,2010-11-15,Timberwolves,1610612750,Nikola Pekovic,21000144,1610612750.0,NaN,103.070000
37,2010-11-15,Timberwolves,1610612750,Wayne Ellington,21000144,1610612750.0,NaN,83.857143
38,2010-11-16,Blazers,1610612757,Brandon Roy,21000154,1610612757.0,NaN,108.063636
39,2010-11-16,Bucks,1610612749,Carlos Delfino,21000155,1610612749.0,NaN,89.842857
40,2010-11-17,Clippers,1610612746,Randy Foye,21000162,1610612746.0,NaN,96.000000
41,2010-11-17,Jazz,1610612762,Kyrylo Fesenko,21000165,1610612762.0,NaN,114.188889
42,2010-11-17,Rockets,1610612745,Chase Budinger,21000164,1610612745.0,NaN,104.712500
43,2010-11-18,Blazers,1610612757,Brandon Roy,21000170,1610612757.0,NaN,108.063636
44,2010-11-18,Magic,1610612753,Jason Williams,21000169,1610612753.0,NaN,102.380000
45,2010-11-19,Bucks,1610612749,Carlos Delfino,21000172,1610612749.0,NaN,89.842857
46,2010-11-19,Heat,1610612748,Juwan Howard,21000175,1610612748.0,NaN,109.533333
47,2010-11-19,Knicks,1610612752,Timofey Mozgov,21000181,1610612752.0,NaN,104.566667
48,2010-11-19,Warriors,1610612744,Brandan Wright,21000181,1610612744.0,NaN,90.175000
49,2010-11-20,Blazers,1610612757,Brandon Roy,21000189,1610612757.0,NaN,108.063636
50,2010-11-20,Bucks,1610612749,Carlos Delfino,21000186,1610612749.0,NaN,89.842857
51,2010-11-20,Suns,1610612756,Steve Nash,21000182,1610612756.0,NaN,111.945455
52,2010-11-21,Wizards,1610612764,John Wall,21000192,1610612764.0,NaN,94.000000
53,2010-11-22,Warriors,1610612744,Brandan Wright,21000201,1610612744.0,NaN,90.175000
54,2010-11-24,Bucks,1610612749,Andrew Bogut,21000210,1610612749.0,NaN,98.208333
55,2010-11-24,Bucks,1610612749,Carlos Delfino,21000210,1610612749.0,NaN,89.842857
56,2010-11-24,Bulls,1610612741,Taj Gibson,21000218,1610612741.0,NaN,103.300000
57,2010-11-24,Celtics,1610612738,Delonte West,21000212,1610612738.0,66.7,89.300000
58,2010-11-24,Warriors,1610612744,Brandan Wright,21000217,1610612744.0,NaN,90.175000
59,2010-11-26,Bucks,1610612749,Andrew Bogut,21000225,1610612749.0,NaN,98.208333
60,2010-11-26,Bucks,1610612749,Carlos Delfino,21000225,1610612749.0,NaN,89.842857
61,2010-11-26,Raptors,1610612761,Reggie Evans,21000224,1610612761.0,82.8,95.280000
62,2010-11-26,Warriors,1610612744,Brandan Wright,21000232,1610612744.0,NaN,90.175000
63,2010-11-27,Bucks,1610612749,Andrew Bogut,21000240,1610612749.0,NaN,98.208333
64,2010-11-27,Bucks,1610612749,Corey Maggette,21000240,1610612749.0,NaN,95.660000
65,2010-11-27,Bucks,1610612749,Drew Gooden,21000240,1610612749.0,NaN,92.273333
66,2010-11-27,Wizards,1610612764,John Wall,21000235,1610612764.0,NaN,95.370000
67,2010-11-28,Blazers,1610612757,Sean Marks,21000246,1610612757.0,NaN,106.742857
68,2010-11-28,Clippers,1610612746,Randy Foye,21000245,1610612746.0,NaN,106.671429
69,2010-11-28,Knicks,1610612752,Toney Douglas,21000243,1610612752.0,NaN,105.211111
70,2010-11-28,Lakers,1610612747,Devin Ebanks,21000249,1610612747.0,NaN,84.000000
71,2010-11-28,Raptors,1610612761,Peja Stojakovic,21000242,1610612761.0,NaN,105.662500
72,2010-11-29,Bucks,1610612749,Andrew Bogut,21000253,1610612749.0,NaN,98.208333
73,2010-11-29,Bucks,1610612749,Corey Maggette,21000253,1610612749.0,NaN,95.660000
74,2010-11-29,Bucks,1610612749,Drew Gooden,21000253,1610612749.0,NaN,92.273333
75,2010-11-29,Wizards,1610612764,John Wall,21000250,1610612764.0,NaN,95.370000
76,2010-12-01,Bucks,1610612749,Andrew Bogut,21000270,1610612749.0,NaN,98.208333
77,2010-12-01,Raptors,1610612761,Peja Stojakovic,21000263,1610612761.0,NaN,105.662500
78,2010-12-03,Magic,1610612753,Dwight Howard,21000279,1610612753.0,NaN,108.494737
79,2010-12-03,Magic,1610612753,Jameer Nelson,21000279,1610612753.0,NaN,110.862500
80,2010-12-03,Magic,1610612753,JJ Redick,21000279,1610612753.0,NaN,100.500000
81,2010-12-03,Raptors,1610612761,Peja Stojakovic,21000276,1610612761.0,NaN,105.662500
82,2010-12-04,Magic,1610612753,Dwight Howard,21000292,1610612753.0,NaN,108.494737
83,2010-12-04,Magic,1610612753,JJ Redick,21000292,1610612753.0,NaN,100.500000
84,2010-12-04,Magic,1610612753,Jameer Nelson,21000292,1610612753.0,NaN,110.862500
85,2010-12-04,Magic,1610612753,Ryan Anderson,21000292,1610612753.0,NaN,93.272727
86,2010-12-04,Timberwolves,1610612750,Michael Beasley,21000291,1610612750.0,NaN,101.661111
87,2010-12-05,Celtics,1610612738,Rajon Rondo,21000294,1610612738.0,NaN,111.106250
88,2010-12-05,Raptors,1610612761,Peja Stojakovic,21000295,1610612761.0,NaN,105.662500
89,2010-12-05,Thunder,1610612760,DJ White,21000297,1610612760.0,NaN,110.583333
90,2010-12-05,Warriors,1610612744,Rodney Carney,21000297,1610612744.0,NaN,94.494737
91,2010-12-06,Bucks,1610612749,Drew Gooden,21000306,1610612749.0,NaN,91.518750
92,2010-12-06,Magic,1610612753,Jameer Nelson,21000303,1610612753.0,NaN,110.862500
93,2010-12-08,Jazz,1610612762,Kyrylo Fesenko,21000324,1610612762.0,NaN,102.833333
94,2010-12-08,Nuggets,1610612743,Carmelo Anthony,21000316,1610612743.0,NaN,105.928571
95,2010-12-08,Raptors,1610612761,Peja Stojakovic,21000318,1610612761.0,NaN,105.662500
96,2010-12-08,Timberwolves,1610612750,Darko Milicic,21000320,1610612750.0,NaN,99.780952
97,2010-12-08,Wizards,1610612764,John Wall,21000325,1610612764.0,NaN,98.000000
98,2010-12-09,Celtics,1610612738,Shaquille O'Neal,21000327,1610612738.0,NaN,118.206250
99,2010-12-10,Jazz,1610612762,Raja Bell,21000339,1610612762.0,NaN,102.536364
100,2010-12-11,Bulls,1610612741,Kurt Thomas,21000345,1610612741.0,116.3,57.780000
101,2010-12-11,Cavaliers,1610612739,Ryan Hollins,21000347,1610612739.0,NaN,100.822727
102,2010-12-11,Hawks,1610612737,Zaza Pachulia,21000342,1610612737.0,107.8,102.370833
103,2010-12-11,Jazz,1610612762,Kyrylo Fesenko,21000346,1610612762.0,NaN,102.833333
104,2010-12-11,Jazz,1610612762,Raja Bell,21000346,1610612762.0,NaN,102.536364
105,2010-12-11,Pacers,1610612754,Jeff Foster,21000342,1610612754.0,114.2,112.300000
106,2010-12-11,Raptors,1610612761,Peja Stojakovic,21000344,1610612761.0,NaN,105.662500
107,2010-12-12,Magic,1610612753,Chris Duhon,21000354,1610612753.0,NaN,102.591304
108,2010-12-13,Jazz,1610612762,Raja Bell,21000359,1610612762.0,NaN,102.536364
109,2010-12-14,Kings,1610612758,Tyreke Evans,21000364,1610612758.0,NaN,99.760000
110,2010-12-14,Magic,1610612753,Mickael Pietrus,21000365,1610612753.0,NaN,99.647368
111,2010-12-14,Magic,1610612753,Quentin Richardson,21000365,1610612753.0,NaN,102.660870
112,2010-12-14,Nuggets,1610612743,Chauncey Billups,21000365,1610612743.0,NaN,107.881818
113,2010-12-14,Raptors,1610612761,Peja Stojakovic,21000360,1610612761.0,NaN,105.662500
114,2010-12-15,Bulls,1610612741,Joakim Noah,21000370,1610612741.0,124.7,105.537500
115,2010-12-15,Celtics,1610612738,Shaquille O'Neal,21000368,1610612738.0,NaN,118.206250
116,2010-12-15,Raptors,1610612761,Andrea Bargnani,21000370,1610612761.0,NaN,103.128000
117,2010-12-15,Raptors,1610612761,Peja Stojakovic,21000370,1610612761.0,NaN,105.662500
118,2010-12-16,Celtics,1610612738,Rajon Rondo,21000379,1610612738.0,NaN,111.475000
119,2010-12-16,Celtics,1610612738,Shaquille O'Neal,21000379,1610612738.0,NaN,118.206250
120,2010-12-16,Nets,1610612751,Anthony Morrow,21000378,1610612751.0,NaN,98.484000
121,2010-12-16,Nuggets,1610612743,Chauncey Billups,21000380,1610612743.0,NaN,107.881818
122,2010-12-16,Spurs,1610612759,Tiago Splitter,21000380,1610612759.0,NaN,105.140000
123,2010-12-16,Wizards,1610612764,John Wall,21000378,1610612764.0,NaN,97.826667
124,2010-12-17,Blazers,1610612757,Brandon Roy,21000391,1610612757.0,NaN,105.652174
125,2010-12-17,Raptors,1610612761,Sonny Weems,21000384,1610612761.0,NaN,100.644000
126,2010-12-18,Blazers,1610612757,Brandon Roy,21000399,1610612757.0,NaN,105.652174
127,2010-12-18,Blazers,1610612757,Marcus Camby,21000399,1610612757.0,NaN,102.877778
128,2010-12-18,Blazers,1610612757,Nicolas Batum,21000399,1610612757.0,NaN,99.796296
129,2010-12-18,Nuggets,1610612743,Chauncey Billups,21000398,1610612743.0,NaN,107.881818
130,2010-12-18,Spurs,1610612759,George Hill,21000397,1610612759.0,NaN,112.050000
131,2010-12-19,Celtics,1610612738,Rajon Rondo,21000400,1610612738.0,NaN,111.475000
132,2010-12-19,Nets,1610612751,Quinton Ross,21000401,1610612751.0,NaN,82.485714
133,2010-12-19,Pistons,1610612765,Richard Hamilton,21000403,1610612765.0,NaN,96.896000
134,2010-12-19,Pistons,1610612765,Rodney Stuckey,21000403,1610612765.0,NaN,103.046154
135,2010-12-19,Raptors,1610612761,Andrea Bargnani,21000402,1610612761.0,NaN,103.288462
136,2010-12-19,Raptors,1610612761,Sonny Weems,21000402,1610612761.0,NaN,100.644000
137,2010-12-20,Blazers,1610612757,Brandon Roy,21000412,1610612757.0,NaN,105.652174
138,2010-12-20,Blazers,1610612757,Marcus Camby,21000412,1610612757.0,NaN,102.877778
139,2010-12-20,Bucks,1610612749,Carlos Delfino,21000412,1610612749.0,NaN,89.842857
140,2010-12-20,Clippers,1610612746,Craig Smith,21000414,1610612746.0,NaN,91.691667
141,2010-12-20,Spurs,1610612759,George Hill,21000411,1610612759.0,NaN,112.050000
142,2010-12-20,Warriors,1610612744,Dan Gadzuric,21000413,1610612744.0,NaN,95.831818
143,2010-12-21,Magic,1610612753,Malik Allen,21000416,1610612753.0,NaN,96.925000
144,2010-12-21,Nets,1610612751,Quinton Ross,21000418,1610612751.0,NaN,82.485714
145,2010-12-21,Warriors,1610612744,Dan Gadzuric,21000419,1610612744.0,NaN,95.831818
146,2010-12-22,Celtics,1610612738,Rajon Rondo,21000424,1610612738.0,NaN,111.475000
147,2010-12-22,Nets,1610612751,Quinton Ross,21000427,1610612751.0,NaN,82.485714
148,2010-12-22,Raptors,1610612761,Jerryd Bayless,21000422,1610612761.0,NaN,101.536000
149,2010-12-22,Raptors,1610612761,Sonny Weems,21000422,1610612761.0,NaN,100.644000
150,2010-12-22,Spurs,1610612759,George Hill,21000428,1610612759.0,NaN,112.050000
151,2010-12-23,Spurs,1610612759,George Hill,21000430,1610612759.0,NaN,112.050000
152,2010-12-25,Blazers,1610612757,Brandon Roy,21000437,1610612757.0,NaN,105.652174
153,2010-12-25,Celtics,1610612738,Semih Erden,21000434,1610612738.0,NaN,93.508333
154,2010-12-25,Magic,1610612753,Jason Williams,21000434,1610612753.0,NaN,101.840000
155,2010-12-27,76ers,1610612755,Andre Iguodala,21000454,1610612755.0,NaN,99.496000
156,2010-12-27,Blazers,1610612757,Brandon Roy,21000452,1610612757.0,NaN,105.652174
157,2010-12-27,Bucks,1610612749,Drew Gooden,21000448,1610612749.0,NaN,94.565000
158,2010-12-27,Magic,1610612753,Jason Williams,21000446,1610612753.0,NaN,101.840000
159,2010-12-27,Raptors,1610612761,Sonny Weems,21000447,1610612761.0,NaN,100.644000
160,2010-12-28,Blazers,1610612757,Brandon Roy,21000461,1610612757.0,NaN,105.652174
161,2010-12-28,Blazers,1610612757,Marcus Camby,21000461,1610612757.0,NaN,103.562069
162,2010-12-28,Bucks,1610612749,Drew Gooden,21000458,1610612749.0,NaN,94.565000
163,2010-12-28,Magic,1610612753,Jason Williams,21000455,1610612753.0,NaN,101.840000
164,2010-12-28,Magic,1610612753,Quentin Richardson,21000455,1610612753.0,NaN,99.166667
165,2010-12-28,Raptors,1610612761,Jose Calderon,21000459,1610612761.0,NaN,102.376923
166,2010-12-28,Raptors,1610612761,Sonny Weems,21000459,1610612761.0,NaN,100.644000
167,2010-12-29,Cavaliers,1610612739,Mo Williams,21000463,1610612739.0,NaN,94.261538
168,2010-12-29,Celtics,1610612738,Semih Erden,21000465,1610612738.0,NaN,93.508333
169,2010-12-29,Jazz,1610612762,CJ Miles,21000472,1610612762.0,NaN,107.051613
170,2010-12-29,Nuggets,1610612743,Kenyon Martin,21000466,1610612743.0,NaN,126.625000
171,2010-12-30,Jazz,1610612762,CJ Miles,21000475,1610612762.0,NaN,107.051613
172,2010-12-30,Jazz,1610612762,Mehmet Okur,21000475,1610612762.0,NaN,91.150000
173,2010-12-30,Magic,1610612753,Jason Williams,21000473,1610612753.0,NaN,101.840000
174,2010-12-30,Magic,1610612753,Quentin Richardson,21000473,1610612753.0,NaN,99.166667
175,2010-12-31,Celtics,1610612738,Rajon Rondo,21000476,1610612738.0,NaN,111.475000
176,2010-12-31,Nets,1610612751,Jordan Farmar,21000479,1610612751.0,NaN,97.084375
177,2010-12-31,Nets,1610612751,Troy Murphy,21000479,1610612751.0,NaN,91.952941
178,2010-12-31,Raptors,1610612761,Sonny Weems,21000480,1610612761.0,NaN,100.644000
179,2010-12-31,Warriors,1610612744,Brandan Wright,21000477,1610612744.0,NaN,88.611111
180,2011-01-01,Bucks,1610612749,Drew Gooden,21000489,1610612749.0,NaN,94.565000
181,2011-01-01,Cavaliers,1610612739,Daniel Gibson,21000485,1610612739.0,NaN,101.035484
182,2011-01-01,Cavaliers,1610612739,Mo Williams,21000485,1610612739.0,NaN,94.261538
183,2011-01-01,Grizzlies,1610612763,Rudy Gay,21000491,1610612763.0,NaN,104.058065
184,2011-01-01,Grizzlies,1610612763,Xavier Henry,21000491,1610612763.0,NaN,97.596429
185,2011-01-01,Jazz,1610612762,CJ Miles,21000491,1610612762.0,NaN,107.051613
186,2011-01-01,Mavericks,1610612742,Shawn Marion,21000489,1610612742.0,NaN,100.151613
187,2011-01-01,Nets,1610612751,Jordan Farmar,21000487,1610612751.0,NaN,97.084375
188,2011-01-02,Blazers,1610612757,Brandon Roy,21000496,1610612757.0,NaN,105.652174
189,2011-01-02,Knicks,1610612752,Timofey Mozgov,21000492,1610612752.0,NaN,91.687500
190,2011-01-02,Raptors,1610612761,Jerryd Bayless,21000494,1610612761.0,NaN,100.342857
191,2011-01-02,Raptors,1610612761,Sonny Weems,21000494,1610612761.0,NaN,100.644000
192,2011-01-03,76ers,1610612755,Spencer Hawes,21000502,1610612755.0,NaN,97.451515
193,2011-01-04,Grizzlies,1610612763,O.J. Mayo,21000508,1610612763.0,NaN,104.597059
194,2011-01-04,Grizzlies,1610612763,Xavier Henry,21000508,1610612763.0,NaN,97.596429
195,2011-01-05,76ers,1610612755,Tony Battie,21000515,1610612755.0,NaN,92.069565
196,2011-01-05,Bobcats,1610612766,Stephen Jackson,21000517,1610612766.0,NaN,98.606452
197,2011-01-05,Bucks,1610612749,Brandon Jennings,21000514,1610612749.0,NaN,96.808000
198,2011-01-05,Jazz,1610612762,Paul Millsap,21000520,1610612762.0,NaN,108.057143
199,2011-01-07,Cavaliers,1610612739,Anderson Varejao,21000534,1610612739.0,NaN,96.912903
200,2011-01-07,Cavaliers,1610612739,Anthony Parker,21000534,1610612739.0,NaN,97.017647
201,2011-01-07,Raptors,1610612761,Jerryd Bayless,21000528,1610612761.0,NaN,100.351724
202,2011-01-07,Raptors,1610612761,Sonny Weems,21000528,1610612761.0,NaN,100.644000
203,2011-01-08,Bucks,1610612749,Andrew Bogut,21000538,1610612749.0,NaN,96.932143
204,2011-01-08,Nets,1610612751,Devin Harris,21000538,1610612751.0,NaN,101.982353
205,2011-01-09,Cavaliers,1610612739,Anthony Parker,21000547,1610612739.0,NaN,97.017647
206,2011-01-09,Nuggets,1610612743,Ty Lawson,21000548,1610612743.0,NaN,106.260000
207,2011-01-09,Raptors,1610612761,Sonny Weems,21000544,1610612761.0,NaN,100.644000
208,2011-01-10,Rockets,1610612745,Brad Miller,21000552,1610612745.0,NaN,106.163889
209,2011-01-11,Cavaliers,1610612739,Anderson Varejao,21000560,1610612739.0,NaN,96.912903
210,2011-01-11,Cavaliers,1610612739,Anthony Parker,21000560,1610612739.0,NaN,97.017647
211,2011-01-11,Knicks,1610612752,Anthony Randolph,21000559,1610612752.0,NaN,89.571429
212,2011-01-12,Celtics,1610612738,Jermaine O'Neal,21000564,1610612738.0,NaN,96.664706
213,2011-01-12,Grizzlies,1610612763,Tony Allen,21000565,1610612763.0,NaN,89.797059
214,2011-01-12,Nets,1610612751,Anthony Morrow,21000569,1610612751.0,NaN,98.484000
215,2011-01-12,Warriors,1610612744,Reggie Williams,21000571,1610612744.0,NaN,101.227027
216,2011-01-13,Heat,1610612748,LeBron James,21000575,1610612748.0,NaN,110.392500
217,2011-01-13,Wizards,1610612764,Andray Blatche,21000573,1610612764.0,NaN,98.016129
218,2011-01-14,Cavaliers,1610612739,Christian Eyenga,21000583,1610612739.0,NaN,92.620000
219,2011-01-14,Cavaliers,1610612739,Daniel Gibson,21000583,1610612739.0,NaN,101.462500
220,2011-01-14,Cavaliers,1610612739,Joey Graham,21000583,1610612739.0,NaN,97.575000
221,2011-01-14,Celtics,1610612738,Jermaine O'Neal,21000579,1610612738.0,NaN,96.664706
222,2011-01-14,Celtics,1610612738,Kevin Garnett,21000579,1610612738.0,NaN,109.670000
223,2011-01-14,Knicks,1610612752,Ronny Turiaf,21000580,1610612752.0,88.3,101.234375
224,2011-01-14,Raptors,1610612761,Leandro Barbosa,21000578,1610612761.0,119.6,105.236364
225,2011-01-14,Spurs,1610612759,Matt Bonner,21000581,1610612759.0,133.2,112.382353
226,2011-01-14,Warriors,1610612744,Brandan Wright,21000585,1610612744.0,NaN,85.616667
227,2011-01-15,Cavaliers,1610612739,Christian Eyenga,21000594,1610612739.0,NaN,92.620000
228,2011-01-15,Cavaliers,1610612739,Daniel Gibson,21000594,1610612739.0,NaN,101.462500
229,2011-01-15,Cavaliers,1610612739,Joey Graham,21000594,1610612739.0,NaN,97.575000
230,2011-01-15,Grizzlies,1610612763,Tony Allen,21000592,1610612763.0,NaN,89.797059
231,2011-01-15,Nets,1610612751,Anthony Morrow,21000595,1610612751.0,NaN,98.484000
232,2011-01-15,Raptors,1610612761,Jerryd Bayless,21000589,1610612761.0,NaN,100.131250
233,2011-01-15,Raptors,1610612761,Leandro Barbosa,21000589,1610612761.0,NaN,105.236364
234,2011-01-16,Spurs,1610612759,Matt Bonner,21000597,1610612759.0,NaN,112.382353
235,2011-01-17,Bulls,1610612741,Carlos Boozer,21000600,1610612741.0,NaN,106.796000
236,2011-01-17,Celtics,1610612738,Jermaine O'Neal,21000608,1610612738.0,NaN,96.664706
237,2011-01-17,Grizzlies,1610612763,Tony Allen,21000600,1610612763.0,NaN,89.797059
238,2011-01-17,Nets,1610612751,Anthony Morrow,21000607,1610612751.0,NaN,98.484000

In [253]:
pd.merge(df_inj3, df_or1011a.rename(columns={'PLAYER_NAME':'player'}), on=['game_id', 'player','game_date'], how='inner').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 666 entries, 0 to 665
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     666 non-null    datetime64[ns]
 1   Team          666 non-null    object
 2   team_id       666 non-null    object
 3   player        666 non-null    object
 4   game_id       666 non-null    int64
 5   TEAM_ID       666 non-null    object
 6   E_OFF_RATING  23 non-null     float64
 7   cma2          662 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 46.8+ KB

In [254]:
i = 0
for player_ in sorted(unique_player):
    print(player_)
    if((process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] != 100) & (process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][1] > 70)):
        print('*****************************************')
        print(i)
        i = i + 1
    print(process.extract(player_, unique_player2, scorer=fuzz.token_set_ratio)[0][:2])

print(i - 1)

 Tony Parker
('Tony Parker', 100)
A.J. Price
*****************************************
0
('AJ Price', 94)
Aaron Brooks
('Aaron Brooks', 100)
Aaron Gray
('Aaron Gray', 100)
Acie Law
('Acie Law', 100)
Al Harrington
('Al Harrington', 100)
Al Horford
('Al Horford', 100)
Al Thornton
('Al Thornton', 100)
Alex Ajinca
*****************************************
1
('Alexis Ajinca', 92)
Alonzo Gee
('Alonzo Gee', 100)
Amar'e Stoudemire
("Amar'e Stoudemire", 100)
Amir Johnson
('Amir Johnson', 100)
Anderson Varejao
('Anderson Varejao', 100)
Andray Blatche
('Andray Blatche', 100)
Andre Iguodala
('Andre Iguodala', 100)
Andrea Bargnani
('Andrea Bargnani', 100)
Andrei Kirilenko
('Andrei Kirilenko', 100)
Andres Nocioni
('Andres Nocioni', 100)
Andrew Bogut
('Andrew Bogut', 100)
Andrew Bynum
('Andrew Bynum', 100)
Andris Biedrins
('Andris Biedrins', 100)
Andy Rautins
('Andy Rautins', 100)
Antawn Jamison
('Antawn Jamison', 100)
Anthony Carter
('Anthony Carter', 100)
Anthony Morrow
('Anthony Morrow', 100)
Anthony Parker
('Anthony Parker', 100)
Anthony Randolph
('Anthony Randolph', 100)
Anthony Tolliver
('Anthony Tolliver', 100)
Antoine Wright
('Antoine Wright', 100)
Antonio McDyess
('Antonio McDyess', 100)
Armon Johnson
('Armon Johnson', 100)
Arron Afflalo
('Arron Afflalo', 100)
Austin Daye
('Austin Daye', 100)
Avery Bradley
('Avery Bradley', 100)
B.J. Mullens
*****************************************
2
('Byron Mullens', 78)
Baron Davis
('Baron Davis', 100)
Ben Uzoh
('Ben Uzoh', 100)
Ben Wallace
('Ben Wallace', 100)
Beno Udrih
('Beno Udrih', 100)
Bill Walker
*****************************************
3
('Henry Walker', 71)
Brad Miller
('Brad Miller', 100)
Brandan Wright
('Brandan Wright', 100)
Brandon Bass
('Brandon Bass', 100)
Brandon Jennings
('Brandon Jennings', 100)
Brandon Roy
('Brandon Roy', 100)
Brandon Rush
('Brandon Rush', 100)
Brendan Haywood
('Brendan Haywood', 100)
Brian Cardinal
('Brian Cardinal', 100)
Brian Cook
('Brian Cook', 100)
Brian Scalabrine
('Brian Scalabrine', 100)
Brian Skinner
('Brian Skinner', 100)
C.J. Miles
*****************************************
4
('CJ Miles', 94)
Carlos Arroyo
('Carlos Arroyo', 100)
Carlos Boozer
('Carlos Boozer', 100)
Carlos Delfino
('Carlos Delfino', 100)
Carmelo Anthony
('Carmelo Anthony', 100)
Caron Butler
('Caron Butler', 100)
Cartier Martin
('Cartier Martin', 100)
Channing Frye
('Channing Frye', 100)
Charlie Bell
('Charlie Bell', 100)
Charlie Villanueva
('Charlie Villanueva', 100)
Chase Budinger
('Chase Budinger', 100)
Chauncey Billups
('Chauncey Billups', 100)
Chris Andersen
('Chris Andersen', 100)
Chris Bosh
('Chris Bosh', 100)
Chris Douglas-Roberts
('Chris Douglas-Roberts', 100)
Chris Duhon
('Chris Duhon', 100)
Chris Kaman
('Chris Kaman', 100)
Chris Paul
('Chris Paul', 100)
Chris Quinn
('Chris Quinn', 100)
Chris Wilcox
('Chris Wilcox', 100)
Christian Eyenga
('Christian Eyenga', 100)
Chuck Hayes
('Chuck Hayes', 100)
Cole Aldrich
('Cole Aldrich', 100)
Corey Brewer
('Corey Brewer', 100)
Corey Maggette
('Corey Maggette', 100)
Courtney Lee
('Courtney Lee', 100)
Craig Brackins
('Craig Brackins', 100)
Craig Smith
('Craig Smith', 100)
D.J. White
*****************************************
5
('DJ White', 94)
Da'Sean Butler
*****************************************
6
('Rasual Butler', 74)
DaJuan Summers
('DaJuan Summers', 100)
Daequan Cook
('Daequan Cook', 100)
Dahntay Jones
('Dahntay Jones', 100)
Damien Wilkins
('Damien Wilkins', 100)
Damion James
('Damion James', 100)
Dan Gadzuric
('Dan Gadzuric', 100)
Daniel Gibson
('Daniel Gibson', 100)
Daniel Orton
*****************************************
7
('Daniel Gibson', 72)
Danilo Gallinari
('Danilo Gallinari', 100)
Danny Granger
('Danny Granger', 100)
Danny Green
('Danny Green', 100)
Dante Cunningham
('Dante Cunningham', 100)
Darius Songaila
('Darius Songaila', 100)
Darko Milicic
('Darko Milicic', 100)
Darrell Arthur
('Darrell Arthur', 100)
Darren Collison
('Darren Collison', 100)
David Andersen
('David Andersen', 100)
David Lee
('David Lee', 100)
David West
('David West', 100)
DeAndre Jordan
('DeAndre Jordan', 100)
DeJuan Blair
('DeJuan Blair', 100)
DeMarre Carroll
('DeMarre Carroll', 100)
DeSagana Diop
('DeSagana Diop', 100)
Delonte West
('Delonte West', 100)
Deron Williams
('Deron Williams', 100)
Derrick Brown
('Derrick Brown', 100)
Derrick Caracter
('Derrick Caracter', 100)
Derrick Favors
('Derrick Favors', 100)
Derrick Rose
('Derrick Rose', 100)
Devin Ebanks
('Devin Ebanks', 100)
Devin Harris
('Devin Harris', 100)
Dexter Pittman
('Dexter Pittman', 100)
Didier Mbenga
*****************************************
8
('DJ Mbenga', 80)
Dirk Nowitzki
('Dirk Nowitzki', 100)
Dominic McGuire
('Dominic McGuire', 100)
Dominique Jones
('Dominique Jones', 100)
Drew Gooden
('Drew Gooden', 100)
Dwight Howard
('Dwight Howard', 100)
Dwyane Wade
('Dwyane Wade', 100)
Ed Davis
('Ed Davis', 100)
Eddy Curry
('Stephen Curry', 67)
Eduardo Najera
('Eduardo Najera', 100)
Ekpe Udoh
('Ekpe Udoh', 100)
Elliot Williams
('Elliot Williams', 100)
Eric Gordon
('Eric Gordon', 100)
Erick Dampier
('Erick Dampier', 100)
Ersan Ilyasova
('Ersan Ilyasova', 100)
Etan Thomas
('Etan Thomas', 100)
Francisco Elson
('Francisco Elson', 100)
Francisco Garcia
('Francisco Garcia', 100)
Gani Lawal
('Gani Lawal', 100)
Garret Siler
('Garret Siler', 100)
Garrett Temple
('Garrett Temple', 100)
Gary Neal
('Gary Neal', 100)
George Hill
('George Hill', 100)
Gerald Henderson Jr.
('Gerald Henderson', 100)
Gerald Wallace
('Gerald Wallace', 100)
Gilbert Arenas
('Gilbert Arenas', 100)
Glen Davis
('Glen Davis', 100)
Goran Dragic
('Goran Dragic', 100)
Gordon Hayward
('Gordon Hayward', 100)
Grant Hill
('Grant Hill', 100)
Greg Oden
('Greg Oden', 100)
Greivis Vasquez
('Greivis Vasquez', 100)
Hamady N'Diaye
*****************************************
9
('Hamady Ndiaye', 89)
Hamed Haddadi
('Hamed Haddadi', 100)
Hasheem Thabeet
('Hasheem Thabeet', 100)
Hassan Whiteside
('Hassan Whiteside', 100)
Hilton Armstrong
('Hilton Armstrong', 100)
Ian Mahinmi
('Ian Mahinmi', 100)
Ish Smith
('Ish Smith', 100)
J.J. Hickson
*****************************************
10
('JJ Hickson', 95)
J.J. Redick
*****************************************
11
('JJ Redick', 94)
JaVale McGee
('JaVale McGee', 100)
Jamaal Magloire
('Jamaal Magloire', 100)
Jamal Crawford
('Jamal Crawford', 100)
Jamario Moon
('Jamario Moon', 100)
Jameer Nelson
('Jameer Nelson', 100)
James Anderson
('James Anderson', 100)
James Posey
('James Posey', 100)
Jannero Pargo
('Anderson Varejao', 62)
Jared Jeffries
('Jared Jeffries', 100)
Jason Collins
('Jason Collins', 100)
Jason Kapono
('Jason Kapono', 100)
Jason Kidd
('Jason Kidd', 100)
Jason Maxiell
('Jason Maxiell', 100)
Jason Richardson
('Jason Richardson', 100)
Jason Smith
('Jason Smith', 100)
Jason Thompson
('Jason Thompson', 100)
Jason Williams
('Jason Williams', 100)
Jeff Adrien
('Jeff Adrien', 100)
Jeff Foster
('Jeff Foster', 100)
Jeff Green
('Jeff Green', 100)
Jeremy Evans
('Jeremy Evans', 100)
Jeremy Lin
('Jeremy Lin', 100)
Jermaine O'Neal
("Jermaine O'Neal", 100)
Jermaine Taylor
('Jermaine Taylor', 100)
Jerry Stackhouse
('Jerry Stackhouse', 100)
Jerryd Bayless
('Jerryd Bayless', 100)
Jianlian Yi
('Yi Jianlian', 100)
Joakim Noah
('Joakim Noah', 100)
Jodie Meeks
('Jodie Meeks', 100)
Joe Alexander
('Jose Calderon', 69)
Joe Johnson
('Joe Johnson', 100)
Joe Smith
('Joe Smith', 100)
Joel Przybilla
('Joel Przybilla', 100)
Joey Dorsey
('Joey Dorsey', 100)
Joey Graham
('Joey Graham', 100)
John Lucas III
('John Lucas III', 100)
John Salmons
('John Salmons', 100)
John Wall
('John Wall', 100)
John Wallace
*****************************************
12
('John Wall', 86)
Jon Brockman
('Jon Brockman', 100)
Jonas Jerebko
('James Jones', 58)
Jonny Flynn
('Jonny Flynn', 100)
Jordan Crawford
('Jordan Crawford', 100)
Jordan Farmar
('Jordan Farmar', 100)
Jordan Hill
('Jordan Hill', 100)
Jose Barea
*****************************************
13
('J.J. Barea', 83)
Jose Calderon
('Jose Calderon', 100)
Josh Howard
('Josh Howard', 100)
Josh McRoberts
('Josh McRoberts', 100)
Josh Powell
('Josh Powell', 100)
Josh Smith
('Josh Smith', 100)
Julian Wright
('Julian Wright', 100)
Juwan Howard
('Juwan Howard', 100)
Kelenna Azubuike
('Acie Law', 50)
Kendrick Perkins
('Kendrick Perkins', 100)
Kenyon Martin

('Kenyon Martin', 100)
Kevin Durant
('Kevin Durant', 100)
Kevin Garnett
('Kevin Garnett', 100)
Kevin Love
('Kevin Love', 100)
Kevin Martin
('Kevin Martin', 100)
Kevin Seraphin
('Kevin Seraphin', 100)
Keyon Dooling
('Keyon Dooling', 100)
Kirk Hinrich
('Kirk Hinrich', 100)
Kosta Koufos
('Kosta Koufos', 100)
Kris Humphries
('Kris Humphries', 100)
Kurt Thomas
('Kurt Thomas', 100)
Kwame Brown
('Kwame Brown', 100)
Kyle Lowry
('Kyle Lowry', 100)
Kyrylo Fesenko
('Kyrylo Fesenko', 100)
LaMarcus Aldridge
('LaMarcus Aldridge', 100)
Lance Stephenson
('Lance Stephenson', 100)
Larry Sanders
('Larry Sanders', 100)
Lazar Hayward
('Lazar Hayward', 100)
LeBron James
('LeBron James', 100)
Leandro Barbosa
('Leandro Barbosa', 100)
Leon Powe
('Leon Powe', 100)
Lester Hudson
('Lester Hudson', 100)
Linas Kleiza
('Linas Kleiza', 100)
Lou Amundson
('Lou Amundson', 100)
Lou Williams
('Lou Williams', 100)
Luc Mbah a Moute
('Luc Mbah a Moute', 100)
Luis Scola
('Luis Scola', 100)
Luke Babbitt
('Luke Babbitt', 100)
Luke Harangody
('Luke Harangody', 100)
Luke Ridnour
('Luke Ridnour', 100)
Luke Walton
('Luke Walton', 100)
Luther Head
('Luther Head', 100)
Magnum Rolle
('Will Bynum', 55)
Malik Allen
('Malik Allen', 100)
Manny Harris
('Manny Harris', 100)
Manu Ginobili
('Manu Ginobili', 100)
Marc Gasol
('Marc Gasol', 100)
Marco Belinelli
('Marco Belinelli', 100)
Marcus Banks
('Marcus Banks', 100)
Marcus Camby
('Marcus Camby', 100)
Marcus Thornton
('Marcus Thornton', 100)
Mario Chalmers
('Mario Chalmers', 100)
Mario West
('Mario West', 100)
Marquis Daniels
('Marquis Daniels', 100)
Martell Webster
('Martell Webster', 100)
Marvin Williams
('Marvin Williams', 100)
Matt Barnes
('Matt Barnes', 100)
Matt Bonner
('Matt Bonner', 100)
Matt Carroll
('Matt Carroll', 100)
Matt Janning
('Matt Barnes', 61)
Maurice Ager
('Maurice Ager', 100)
Maurice Evans
('Maurice Evans', 100)
Mehmet Okur
('Mehmet Okur', 100)
Melvin Ely
('Melvin Ely', 100)
Michael Beasley
('Michael Beasley', 100)
Michael Redd
('Michael Redd', 100)
Mickael Pietrus
('Mickael Pietrus', 100)
Mike Conley Jr.
('Mike Conley', 100)
Mike Dunleavy Jr.
('Mike Dunleavy', 100)
Mike Miller
('Mike Miller', 100)
Mo Williams
('Mo Williams', 100)
Monta Ellis
('Monta Ellis', 100)
Morris Peterson
('Morris Peterson', 100)
Mustafa Shakur
('Mustafa Shakur', 100)
Nate Robinson
('Nate Robinson', 100)
Nazr Mohammed
('Nazr Mohammed', 100)
Nenad Krstic
('Nenad Krstic', 100)
Nene Hilario
('Nene', 100)
Nick Collison
('Nick Collison', 100)
Nick Young
('Nick Young', 100)
Nicolas Batum
('Nicolas Batum', 100)
Nikola Pekovic
('Nikola Pekovic', 100)
O.J. Mayo
('O.J. Mayo', 100)
Omer Asik
('Omer Asik', 100)
Omri Casspi
('Omri Casspi', 100)
Orien Greene
('Orien Greene', 100)
Othyus Jeffers
('Othyus Jeffers', 100)
Pape Sy
('Pape Sy', 100)
Patrick Patterson
('Patrick Patterson', 100)
Patty Mills
('Patty Mills', 100)
Paul George
('Paul George', 100)
Paul Millsap
('Paul Millsap', 100)
Paul Pierce
('Paul Pierce', 100)
Peja Stojakovic
('Peja Stojakovic', 100)
Pooh Jeter
('Pooh Jeter', 100)
Pops Mensah-Bonsu
('Pops Mensah-Bonsu', 100)
Quentin Richardson
('Quentin Richardson', 100)
Quincy Pondexter
('Quincy Pondexter', 100)
Quinton Ross
('Quinton Ross', 100)
Raja Bell
('Raja Bell', 100)
Rajon Rondo
('Rajon Rondo', 100)
Randy Foye
('Randy Foye', 100)
Rashard Lewis
('Rashard Lewis', 100)
Rasual Butler
('Rasual Butler', 100)
Ray Allen
('Ray Allen', 100)
Raymond Felton
('Raymond Felton', 100)
Reggie Evans
('Reggie Evans', 100)
Reggie Williams
('Reggie Williams', 100)
Renaldo Balkman
('Renaldo Balkman', 100)
Richard Hamilton
('Richard Hamilton', 100)
Robert Vaden
('Greg Oden', 57)
Robin Lopez
('Robin Lopez', 100)
Rodney Carney
('Rodney Carney', 100)
Rodney Stuckey
('Rodney Stuckey', 100)
Rodrigue Beaubois
('Rodrigue Beaubois', 100)
Roger Mason Jr.
('Roger Mason Jr.', 100)
Ronnie Brewer
('Ronnie Brewer', 100)
Ronnie Price
('Ronnie Price', 100)
Ronny Turiaf
('Ronny Turiaf', 100)
Roy Hibbert
('Roy Hibbert', 100)
Rudy Fernandez
('Rudy Fernandez', 100)
Rudy Gay
('Rudy Gay', 100)
Ryan Anderson
('Ryan Anderson', 100)
Ryan Gomes
('Ryan Gomes', 100)
Ryan Hollins
('Ryan Hollins', 100)
Samardo Samuels
('Samardo Samuels', 100)
Samuel Dalembert
('Samuel Dalembert', 100)
Sasha Vujacic
('Sasha Vujacic', 100)
Sean Marks
('Sean Marks', 100)
Sebastian Telfair
('Sebastian Telfair', 100)
Semih Erden
('Semih Erden', 100)
Shaquille O'Neal
("Shaquille O'Neal", 100)
Shaun Livingston
('Shaun Livingston', 100)
Shawn Marion
('Shawn Marion', 100)
Shawne Williams
('Shawne Williams', 100)
Shelden Williams
('Shelden Williams', 100)
Sherron Collins
('Sherron Collins', 100)
Solomon Alabi
('Solomon Alabi', 100)
Solomon Jones
('Solomon Jones', 100)
Sonny Weems
('Sonny Weems', 100)
Spencer Hawes
('Spencer Hawes', 100)
Stephen Curry
('Stephen Curry', 100)
Stephen Graham
('Stephen Graham', 100)
Stephen Jackson
('Stephen Jackson', 100)
Steve Blake
('Steve Blake', 100)
Steve Nash
('Steve Nash', 100)
Steve Novak
('Steve Novak', 100)
Sundiata Gaines
('Sundiata Gaines', 100)
T.J. Ford
('T.J. Ford', 100)
Taj Gibson
('Taj Gibson', 100)
Tayshaun Prince
('Tayshaun Prince', 100)
Terrence Williams
('Terrence Williams', 100)
Terrico White
*****************************************
14
('DJ White', 77)
Thabo Sefolosha
('Thabo Sefolosha', 100)
Theo Ratliff
('Theo Ratliff', 100)
Tiago Splitter
('Tiago Splitter', 100)
Tim Duncan
('Tim Duncan', 100)
Timofey Mozgov
('Timofey Mozgov', 100)
Toney Douglas
('Toney Douglas', 100)
Tony Allen
('Tony Allen', 100)
Tony Battie
('Tony Battie', 100)
Tracy McGrady
('Tracy McGrady', 100)
Trevor Ariza
('Trevor Ariza', 100)
Trevor Booker
('Trevor Booker', 100)
Trey Johnson
('Trey Johnson', 100)
Troy Murphy
('Troy Murphy', 100)
Ty Lawson
('Ty Lawson', 100)
Tyler Hansbrough
('Tyler Hansbrough', 100)
Tyreke Evans
('Tyreke Evans', 100)
Tyrus Thomas
('Tyrus Thomas', 100)
Tyson Chandler
('Tyson Chandler', 100)
Udonis Haslem
('Udonis Haslem', 100)
Vince Carter
('Vince Carter', 100)
Von Wafer
('Von Wafer', 100)
Wayne Ellington
('Wayne Ellington', 100)
Wes Johnson
*****************************************
15
('Wesley Johnson', 88)
Will Bynum
('Will Bynum', 100)
Willie Warren
('Willie Warren', 100)
Wilson Chandler
('Wilson Chandler', 100)
Xavier Henry
('Xavier Henry', 100)
Yao Ming
('Yao Ming', 100)
Zabian Dowdell
('Zabian Dowdell', 100)
Zach Randolph
('Zach Randolph', 100)
Zaza Pachulia
('Zaza Pachulia', 100)
Zydrunas Ilgauskas
('Zydrunas Ilgauskas', 100)
15

In [255]:
pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner').info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  float64
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 1.4+ MB

In [256]:


#——->get player game_id, game_date for that season by merge relinquished players of df_injuries on df_or1011