In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

pd.set_option('display.max_colwidth', None)

In [3]:
os.getcwd()

'C:\\Users\\Paul\\sb\\DSCapstone2\\02_Data_Wrangling'

In [4]:
filenames = ['nba_teams_all.csv']

In [5]:
dataframes = [pd.read_csv('C:\\Users\\Paul\\sb\\DSCapstone2\\raw_data\\' + f) for f in filenames]   
df = dataframes[0]

In [6]:
df[['team_id', 'abbreviation']]

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610616834          NaN
18  1610616833          NaN
19       12306          NaN
20       12303          NaN
21       12313          NaN
22       12316          NaN
23          45          NaN
24       12308          NaN
25       12304          NaN
26       12320          NaN
27       12315          NaN
28          94          NaN
29       12321          NaN
30       12324          NaN
31          93          NaN
32          41          NaN
33       12325          NaN
34       12323          NaN
35       12330          NaN
36       15015          NaN
37       15018          NaN
38       12329          NaN
39       15016          NaN
40       15017          NaN
41  1610612754          IND
42  1610612755          PHI
43  1610612756          PHX
44  1610612757          POR
45  1610612758          SAC
46  1610612759          SAS
47  1610612760          OKC
48  1610612761          TOR
49  1610612762          UTA
50  1610612763          MEM
51  1610612764          WAS
52  1610612765          DET
53  1610612766          CHA
54  1610610029          NaN
55  1610610025          NaN
56  1610610034          NaN
57  1610610036          NaN
58  1610610024          NaN
59  1610610031          NaN
60  1610610027          NaN
61  1610610030          NaN
62  1610610033          NaN
63  1610610037          NaN
64  1610610023          NaN
65  1610610026          NaN
66  1610610028          NaN
67  1610610032          NaN
68  1610610035          NaN

In [7]:
team_id_abbreviation_df = df[['team_id', 'abbreviation']].dropna().reset_index().drop('index', axis=1)
team_id_abbreviation_df

       team_id abbreviation
0   1610612737          ATL
1   1610612738          BOS
2   1610612739          CLE
3   1610612740          NOP
4   1610612741          CHI
5   1610612742          DAL
6   1610612743          DEN
7   1610612744          GSW
8   1610612745          HOU
9   1610612746          LAC
10  1610612747          LAL
11  1610612748          MIA
12  1610612749          MIL
13  1610612750          MIN
14  1610612751          BKN
15  1610612752          NYK
16  1610612753          ORL
17  1610612754          IND
18  1610612755          PHI
19  1610612756          PHX
20  1610612757          POR
21  1610612758          SAC
22  1610612759          SAS
23  1610612760          OKC
24  1610612761          TOR
25  1610612762          UTA
26  1610612763          MEM
27  1610612764          WAS
28  1610612765          DET
29  1610612766          CHA

In [8]:
df[['team_id', 'abbreviation']].dropna().shape

(30, 2)

In [9]:
datapath = 'C:\\Users\\Paul\\sb\\DSCapstone2\\processed_data'

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '0team_id_abbreviation_df.csv')
if not os.path.exists(datapath_df):
    df[['team_id', 'abbreviation']].dropna().to_csv(datapath_df, index=False)