In [26]:
#output betting total

#output betting spread

#output betting money line
##################################

#output betting total, betting spread, betting money line

In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [28]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [29]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [30]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [31]:
df_betting_totals = rcr('nba_betting_totals.csv')
p(df_betting_totals)

(131386, 9)

,game_id,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,21100131,Pinnacle Sports,238,1610612740,1610612743,192.0,192.0,-105.0,-105.0
1,21100131,5Dimes,19,1610612740,1610612743,192.0,192.0,-105.0,-105.0
2,21100131,Bookmaker,93,1610612740,1610612743,192.0,192.0,-110.0,-110.0
3,21100131,BetOnline,1096,1610612740,1610612743,191.5,191.5,-110.0,-110.0
4,21100131,Bovada,999996,1610612740,1610612743,192.0,192.0,-110.0,-110.0
131381,41700215,Heritage,169,1610612755,1610612738,204.5,204.5,-105.0,-105.0
131382,41700215,Intertops,180,1610612755,1610612738,205.0,205.0,-110.0,-110.0
131383,41700215,YouWager,139,1610612755,1610612738,204.5,204.5,-110.0,-110.0
131384,41700215,JustBet,1275,1610612755,1610612738,204.0,204.0,-110.0,-110.0
131385,41700215,Sportsbetting,999991,1610612755,1610612738,204.5,204.5,-110.0,-110.0

In [32]:
#get at least one row for each game_id
df_betting_totals = df_betting_totals.iloc[df_betting_totals.game_id.drop_duplicates().index].reset_index(drop=True)
p(df_betting_totals)

(14918, 9)

,game_id,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,21100131,Pinnacle Sports,238,1610612740,1610612743,192.0,192.0,-105.0,-105.0
1,21100137,Pinnacle Sports,238,1610612760,1610612763,193.5,193.5,-105.0,-105.0
2,21100148,Pinnacle Sports,238,1610612760,1610612740,183.5,183.5,-105.0,-105.0
3,21100149,Pinnacle Sports,238,1610612745,1610612759,198.5,198.5,-105.0,-105.0
4,21100152,Pinnacle Sports,238,1610612753,1610612757,186.0,186.0,-107.0,-103.0
14913,41700212,Pinnacle Sports,238,1610612755,1610612738,206.5,206.5,-103.0,-107.0
14914,41700233,Pinnacle Sports,238,1610612744,1610612740,233.5,233.5,-103.0,-107.0
14915,41700213,Pinnacle Sports,238,1610612738,1610612755,206.5,206.5,-103.0,-107.0
14916,41700234,Pinnacle Sports,238,1610612744,1610612740,231.0,231.0,-103.0,-107.0
14917,41700215,Pinnacle Sports,238,1610612755,1610612738,204.5,204.5,-106.0,-104.0

In [33]:
df_game = rcp('3game_date_home_away.csv', ['game_date'])
#filter for seasons 2010-11 thru 2017-18
df_game1018 = df_game[(df_game.season == '2010-11') | 
                      (df_game.season == '2011-12') | 
                      (df_game.season == '2012-13') | 
                      (df_game.season == '2013-14') | 
                      (df_game.season == '2014-15') | 
                      (df_game.season == '2015-16') | 
                      (df_game.season == '2016-17') | 
                      (df_game.season == '2017-18')].reset_index(drop=True)
p(df_game1018)

(10267, 47)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
1,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
2,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
3,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
10262,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
10263,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
10264,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
10265,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
10266,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [34]:
#df_merge = pd.merge(df_game1018, df_betting, on='game_id', how='outer', indicator=True)
df_merge = pd.merge(df_game1018, df_betting_totals, on=['game_id'], how='inner')
p(df_merge)

(9922, 55)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,team_id,a_team_id,total1,total2,price1,price2
0,21000044,2010-11-01,1610612741,0.667,240,43.0,71.0,0.606,5.0,13.0,0.385,19.0,32.0,1.0,9.0,27.0,36,27.0,4.0,4.0,15.0,33.0,110,2010.0,1610612757,0.750,240,33.0,80.0,0.413,0.0,14.0,0.000,32.0,41.0,1.0,16.0,19.0,35,15.0,9.0,2.0,10.0,27.0,98,Regular Season,2010-11,Pinnacle Sports,238,1610612757,1610612741,187.0,187.0,-105.0,-105.0
1,21000045,2010-11-01,1610612758,0.750,240,42.0,88.0,0.477,5.0,12.0,0.417,22.0,27.0,1.0,16.0,24.0,40,15.0,5.0,4.0,11.0,24.0,111,2010.0,1610612761,0.333,240,39.0,85.0,0.459,9.0,21.0,0.429,21.0,29.0,1.0,17.0,25.0,42,19.0,3.0,3.0,14.0,26.0,108,Regular Season,2010-11,Pinnacle Sports,238,1610612761,1610612758,208.0,208.0,100.0,-110.0
2,21000046,2010-11-01,1610612746,0.000,240,38.0,82.0,0.463,4.0,13.0,0.308,8.0,16.0,0.0,10.0,30.0,40,26.0,10.0,6.0,17.0,18.0,88,2010.0,1610612759,0.667,240,38.0,79.0,0.481,9.0,21.0,0.429,12.0,15.0,1.0,7.0,32.0,39,28.0,11.0,3.0,18.0,21.0,97,Regular Season,2010-11,Pinnacle Sports,238,1610612759,1610612746,193.5,193.5,-102.0,-108.0
3,21000047,2010-11-02,1610612739,0.250,240,32.0,74.0,0.432,5.0,17.0,0.294,19.0,26.0,1.0,10.0,34.0,44,15.0,2.0,4.0,14.0,22.0,88,2010.0,1610612737,1.000,240,37.0,84.0,0.440,5.0,17.0,0.294,21.0,30.0,1.0,14.0,29.0,43,26.0,7.0,7.0,7.0,17.0,100,Regular Season,2010-11,Pinnacle Sports,238,1610612737,1610612739,190.0,190.0,101.0,-111.0
4,21000048,2010-11-02,1610612764,0.333,265,37.0,78.0,0.474,6.0,12.0,0.500,36.0,43.0,1.0,9.0,27.0,36,24.0,15.0,2.0,21.0,24.0,116,2010.0,1610612755,0.000,265,44.0,80.0,0.550,4.0,15.0,0.267,23.0,29.0,1.0,7.0,28.0,35,34.0,10.0,3.0,22.0,30.0,115,Regular Season,2010-11,Pinnacle Sports,238,1610612755,1610612764,192.0,192.0,-105.0,-105.0
9917,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18,Pinnacle Sports,238,1610612744,1610612745,208.5,208.5,-105.0,-105.0
9918,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18,Pinnacle Sports,238,1610612739,1610612744,217.5,217.5,-106.0,-104.0
9919,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18,Pinnacle Sports,238,1610612739,1610612744,216.5,216.5,103.0,-114.0
9920,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18,Pinnacle Sports,238,1610612744,1610612739,215.5,215.5,-113.0,102.0
9921,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18,Pinnacle Sports,238,1610612744,1610612739,216.5,216.5,-107.0,-103.0

In [35]:
#proportion of data without betting data for the 2010-11 thru 2017-18 seasons
(10267 - 9922) / 10267

0.0336028051037304

In [36]:
d = {'a_team_id':'team_id_home', 'team_id':'team_id_away'}
d

{'a_team_id': 'team_id_home', 'team_id': 'team_id_away'}

In [37]:
df_game_betting_totals1018 = pd.merge(df_game1018, df_betting_totals.rename(columns=d), on=['game_id', 'team_id_home', 'team_id_away'], how='inner')
p(df_game_betting_totals1018)

(9922, 53)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,total1,total2,price1,price2
0,21000044,2010-11-01,1610612741,0.667,240,43.0,71.0,0.606,5.0,13.0,0.385,19.0,32.0,1.0,9.0,27.0,36,27.0,4.0,4.0,15.0,33.0,110,2010.0,1610612757,0.750,240,33.0,80.0,0.413,0.0,14.0,0.000,32.0,41.0,1.0,16.0,19.0,35,15.0,9.0,2.0,10.0,27.0,98,Regular Season,2010-11,Pinnacle Sports,238,187.0,187.0,-105.0,-105.0
1,21000045,2010-11-01,1610612758,0.750,240,42.0,88.0,0.477,5.0,12.0,0.417,22.0,27.0,1.0,16.0,24.0,40,15.0,5.0,4.0,11.0,24.0,111,2010.0,1610612761,0.333,240,39.0,85.0,0.459,9.0,21.0,0.429,21.0,29.0,1.0,17.0,25.0,42,19.0,3.0,3.0,14.0,26.0,108,Regular Season,2010-11,Pinnacle Sports,238,208.0,208.0,100.0,-110.0
2,21000046,2010-11-01,1610612746,0.000,240,38.0,82.0,0.463,4.0,13.0,0.308,8.0,16.0,0.0,10.0,30.0,40,26.0,10.0,6.0,17.0,18.0,88,2010.0,1610612759,0.667,240,38.0,79.0,0.481,9.0,21.0,0.429,12.0,15.0,1.0,7.0,32.0,39,28.0,11.0,3.0,18.0,21.0,97,Regular Season,2010-11,Pinnacle Sports,238,193.5,193.5,-102.0,-108.0
3,21000047,2010-11-02,1610612739,0.250,240,32.0,74.0,0.432,5.0,17.0,0.294,19.0,26.0,1.0,10.0,34.0,44,15.0,2.0,4.0,14.0,22.0,88,2010.0,1610612737,1.000,240,37.0,84.0,0.440,5.0,17.0,0.294,21.0,30.0,1.0,14.0,29.0,43,26.0,7.0,7.0,7.0,17.0,100,Regular Season,2010-11,Pinnacle Sports,238,190.0,190.0,101.0,-111.0
4,21000048,2010-11-02,1610612764,0.333,265,37.0,78.0,0.474,6.0,12.0,0.500,36.0,43.0,1.0,9.0,27.0,36,24.0,15.0,2.0,21.0,24.0,116,2010.0,1610612755,0.000,265,44.0,80.0,0.550,4.0,15.0,0.267,23.0,29.0,1.0,7.0,28.0,35,34.0,10.0,3.0,22.0,30.0,115,Regular Season,2010-11,Pinnacle Sports,238,192.0,192.0,-105.0,-105.0
9917,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18,Pinnacle Sports,238,208.5,208.5,-105.0,-105.0
9918,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18,Pinnacle Sports,238,217.5,217.5,-106.0,-104.0
9919,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18,Pinnacle Sports,238,216.5,216.5,103.0,-114.0
9920,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18,Pinnacle Sports,238,215.5,215.5,-113.0,102.0
9921,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18,Pinnacle Sports,238,216.5,216.5,-107.0,-103.0

In [38]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '4game_id_team_stats_betting_totals_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_game_betting_totals1018.to_csv(datapath_df, index=False)

In [39]:
rcp('4game_id_team_stats_betting_totals_2010_2018.csv')

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,total1,total2,price1,price2
0,21000044,2010-11-01,1610612741,0.667,240,43.0,71.0,0.606,5.0,13.0,0.385,19.0,32.0,1.0,9.0,27.0,36,27.0,4.0,4.0,15.0,33.0,110,2010.0,1610612757,0.750,240,33.0,80.0,0.413,0.0,14.0,0.000,32.0,41.0,1.0,16.0,19.0,35,15.0,9.0,2.0,10.0,27.0,98,Regular Season,2010-11,Pinnacle Sports,238,187.0,187.0,-105.0,-105.0
1,21000045,2010-11-01,1610612758,0.750,240,42.0,88.0,0.477,5.0,12.0,0.417,22.0,27.0,1.0,16.0,24.0,40,15.0,5.0,4.0,11.0,24.0,111,2010.0,1610612761,0.333,240,39.0,85.0,0.459,9.0,21.0,0.429,21.0,29.0,1.0,17.0,25.0,42,19.0,3.0,3.0,14.0,26.0,108,Regular Season,2010-11,Pinnacle Sports,238,208.0,208.0,100.0,-110.0
2,21000046,2010-11-01,1610612746,0.000,240,38.0,82.0,0.463,4.0,13.0,0.308,8.0,16.0,0.0,10.0,30.0,40,26.0,10.0,6.0,17.0,18.0,88,2010.0,1610612759,0.667,240,38.0,79.0,0.481,9.0,21.0,0.429,12.0,15.0,1.0,7.0,32.0,39,28.0,11.0,3.0,18.0,21.0,97,Regular Season,2010-11,Pinnacle Sports,238,193.5,193.5,-102.0,-108.0
3,21000047,2010-11-02,1610612739,0.250,240,32.0,74.0,0.432,5.0,17.0,0.294,19.0,26.0,1.0,10.0,34.0,44,15.0,2.0,4.0,14.0,22.0,88,2010.0,1610612737,1.000,240,37.0,84.0,0.440,5.0,17.0,0.294,21.0,30.0,1.0,14.0,29.0,43,26.0,7.0,7.0,7.0,17.0,100,Regular Season,2010-11,Pinnacle Sports,238,190.0,190.0,101.0,-111.0
4,21000048,2010-11-02,1610612764,0.333,265,37.0,78.0,0.474,6.0,12.0,0.500,36.0,43.0,1.0,9.0,27.0,36,24.0,15.0,2.0,21.0,24.0,116,2010.0,1610612755,0.000,265,44.0,80.0,0.550,4.0,15.0,0.267,23.0,29.0,1.0,7.0,28.0,35,34.0,10.0,3.0,22.0,30.0,115,Regular Season,2010-11,Pinnacle Sports,238,192.0,192.0,-105.0,-105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9917,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18,Pinnacle Sports,238,208.5,208.5,-105.0,-105.0
9918,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18,Pinnacle Sports,238,217.5,217.5,-106.0,-104.0
9919,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18,Pinnacle Sports,238,216.5,216.5,103.0,-114.0
9920,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18,Pinnacle Sports,238,215.5,215.5,-113.0,102.0
9921,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18,Pinnacle Sports,238,216.5,216.5,-107.0,-103.0

In [40]:
df_betting_spread = rcr('nba_betting_spread.csv')
p(df_betting_spread)

(131690, 9)

,game_id,book_name,book_id,team_id,a_team_id,spread1,spread2,price1,price2
0,21000358,Pinnacle Sports,238,1610612749,1610612742,7.5,-7.5,-106.0,-104.0
1,21000358,5Dimes,19,1610612749,1610612742,7.5,-7.5,-110.0,-110.0
2,21000358,Bookmaker,93,1610612749,1610612742,7.5,-7.5,-110.0,-110.0
3,21000358,BetOnline,1096,1610612749,1610612742,7.5,-7.5,-110.0,-110.0
4,21000358,Bovada,999996,1610612749,1610612742,8.0,-8.0,-115.0,-105.0
131685,21501153,BetOnline,1096,1610612738,1610612747,-9.0,9.0,-110.0,-110.0
131686,21501153,Bovada,999996,1610612738,1610612747,-9.5,9.5,-110.0,-110.0
131687,21501153,Heritage,169,1610612738,1610612747,-9.5,9.5,-105.0,-105.0
131688,21501153,Intertops,180,1610612738,1610612747,-9.5,9.5,-110.0,-110.0
131689,21501153,YouWager,139,1610612738,1610612747,-9.0,9.0,-110.0,-110.0

In [41]:
#get at least one row for each game_id
df_betting_spread = df_betting_spread.iloc[df_betting_spread.game_id.drop_duplicates().index].reset_index(drop=True)
p(df_betting_spread)

(14914, 9)

,game_id,book_name,book_id,team_id,a_team_id,spread1,spread2,price1,price2
0,21000358,Pinnacle Sports,238,1610612749,1610612742,7.5,-7.5,-106.0,-104.0
1,21000361,Pinnacle Sports,238,1610612755,1610612751,-1.5,1.5,-102.0,-108.0
2,21000362,Pinnacle Sports,238,1610612747,1610612764,-10.5,10.5,102.0,-112.0
3,21000367,Pinnacle Sports,238,1610612747,1610612754,-3.5,3.5,-110.0,100.0
4,21000372,Pinnacle Sports,238,1610612766,1610612763,8.5,-8.5,-108.0,-102.0
14909,21501126,Pinnacle Sports,238,1610612746,1610612760,16.5,-16.5,102.0,-113.0
14910,21501139,Pinnacle Sports,238,1610612765,1610612741,3.0,-3.0,-106.0,-104.0
14911,21501150,Pinnacle Sports,238,1610612741,1610612749,-1.0,1.0,100.0,-110.0
14912,21501151,Pinnacle Sports,238,1610612754,1610612752,-7.0,7.0,100.0,-110.0
14913,21501152,Pinnacle Sports,238,1610612757,1610612744,11.5,-11.5,102.0,-113.0

In [42]:
p(df_game1018)

(10267, 47)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
1,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
2,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
3,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
10262,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
10263,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
10264,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
10265,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
10266,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [43]:
df_games_betting_spread_2010_2018 = pd.merge(df_game1018, df_betting_spread.rename(columns=d), on=['game_id', 'team_id_home', 'team_id_away'], how='inner')
p(df_games_betting_spread_2010_2018)

(9920, 53)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,spread1,spread2,price1,price2
0,21000044,2010-11-01,1610612741,0.667,240,43.0,71.0,0.606,5.0,13.0,0.385,19.0,32.0,1.0,9.0,27.0,36,27.0,4.0,4.0,15.0,33.0,110,2010.0,1610612757,0.750,240,33.0,80.0,0.413,0.0,14.0,0.000,32.0,41.0,1.0,16.0,19.0,35,15.0,9.0,2.0,10.0,27.0,98,Regular Season,2010-11,Pinnacle Sports,238,-1.0,1.0,-106.0,-104.0
1,21000045,2010-11-01,1610612758,0.750,240,42.0,88.0,0.477,5.0,12.0,0.417,22.0,27.0,1.0,16.0,24.0,40,15.0,5.0,4.0,11.0,24.0,111,2010.0,1610612761,0.333,240,39.0,85.0,0.459,9.0,21.0,0.429,21.0,29.0,1.0,17.0,25.0,42,19.0,3.0,3.0,14.0,26.0,108,Regular Season,2010-11,Pinnacle Sports,238,5.5,-5.5,103.0,-114.0
2,21000046,2010-11-01,1610612746,0.000,240,38.0,82.0,0.463,4.0,13.0,0.308,8.0,16.0,0.0,10.0,30.0,40,26.0,10.0,6.0,17.0,18.0,88,2010.0,1610612759,0.667,240,38.0,79.0,0.481,9.0,21.0,0.429,12.0,15.0,1.0,7.0,32.0,39,28.0,11.0,3.0,18.0,21.0,97,Regular Season,2010-11,Pinnacle Sports,238,-8.0,8.0,100.0,-110.0
3,21000047,2010-11-02,1610612739,0.250,240,32.0,74.0,0.432,5.0,17.0,0.294,19.0,26.0,1.0,10.0,34.0,44,15.0,2.0,4.0,14.0,22.0,88,2010.0,1610612737,1.000,240,37.0,84.0,0.440,5.0,17.0,0.294,21.0,30.0,1.0,14.0,29.0,43,26.0,7.0,7.0,7.0,17.0,100,Regular Season,2010-11,Pinnacle Sports,238,-3.0,3.0,-105.0,-105.0
4,21000048,2010-11-02,1610612764,0.333,265,37.0,78.0,0.474,6.0,12.0,0.500,36.0,43.0,1.0,9.0,27.0,36,24.0,15.0,2.0,21.0,24.0,116,2010.0,1610612755,0.000,265,44.0,80.0,0.550,4.0,15.0,0.267,23.0,29.0,1.0,7.0,28.0,35,34.0,10.0,3.0,22.0,30.0,115,Regular Season,2010-11,Pinnacle Sports,238,3.0,-3.0,-113.0,102.0
9915,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18,Pinnacle Sports,238,-5.5,5.5,-113.0,102.0
9916,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18,Pinnacle Sports,238,13.0,-13.0,-105.0,-105.0
9917,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18,Pinnacle Sports,238,11.5,-11.5,-110.0,-100.0
9918,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18,Pinnacle Sports,238,-3.5,3.5,-100.0,-110.0
9919,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18,Pinnacle Sports,238,-4.0,4.0,-106.0,-104.0

In [44]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '4game_id_team_stats_betting_spread_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_games_betting_spread_2010_2018.to_csv(datapath_df, index=False)

In [45]:
rcp('4game_id_team_stats_betting_spread_2010_2018.csv')

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,spread1,spread2,price1,price2
0,21000044,2010-11-01,1610612741,0.667,240,43.0,71.0,0.606,5.0,13.0,0.385,19.0,32.0,1.0,9.0,27.0,36,27.0,4.0,4.0,15.0,33.0,110,2010.0,1610612757,0.750,240,33.0,80.0,0.413,0.0,14.0,0.000,32.0,41.0,1.0,16.0,19.0,35,15.0,9.0,2.0,10.0,27.0,98,Regular Season,2010-11,Pinnacle Sports,238,-1.0,1.0,-106.0,-104.0
1,21000045,2010-11-01,1610612758,0.750,240,42.0,88.0,0.477,5.0,12.0,0.417,22.0,27.0,1.0,16.0,24.0,40,15.0,5.0,4.0,11.0,24.0,111,2010.0,1610612761,0.333,240,39.0,85.0,0.459,9.0,21.0,0.429,21.0,29.0,1.0,17.0,25.0,42,19.0,3.0,3.0,14.0,26.0,108,Regular Season,2010-11,Pinnacle Sports,238,5.5,-5.5,103.0,-114.0
2,21000046,2010-11-01,1610612746,0.000,240,38.0,82.0,0.463,4.0,13.0,0.308,8.0,16.0,0.0,10.0,30.0,40,26.0,10.0,6.0,17.0,18.0,88,2010.0,1610612759,0.667,240,38.0,79.0,0.481,9.0,21.0,0.429,12.0,15.0,1.0,7.0,32.0,39,28.0,11.0,3.0,18.0,21.0,97,Regular Season,2010-11,Pinnacle Sports,238,-8.0,8.0,100.0,-110.0
3,21000047,2010-11-02,1610612739,0.250,240,32.0,74.0,0.432,5.0,17.0,0.294,19.0,26.0,1.0,10.0,34.0,44,15.0,2.0,4.0,14.0,22.0,88,2010.0,1610612737,1.000,240,37.0,84.0,0.440,5.0,17.0,0.294,21.0,30.0,1.0,14.0,29.0,43,26.0,7.0,7.0,7.0,17.0,100,Regular Season,2010-11,Pinnacle Sports,238,-3.0,3.0,-105.0,-105.0
4,21000048,2010-11-02,1610612764,0.333,265,37.0,78.0,0.474,6.0,12.0,0.500,36.0,43.0,1.0,9.0,27.0,36,24.0,15.0,2.0,21.0,24.0,116,2010.0,1610612755,0.000,265,44.0,80.0,0.550,4.0,15.0,0.267,23.0,29.0,1.0,7.0,28.0,35,34.0,10.0,3.0,22.0,30.0,115,Regular Season,2010-11,Pinnacle Sports,238,3.0,-3.0,-113.0,102.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9915,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18,Pinnacle Sports,238,-5.5,5.5,-113.0,102.0
9916,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18,Pinnacle Sports,238,13.0,-13.0,-105.0,-105.0
9917,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18,Pinnacle Sports,238,11.5,-11.5,-110.0,-100.0
9918,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18,Pinnacle Sports,238,-3.5,3.5,-100.0,-110.0
9919,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18,Pinnacle Sports,238,-4.0,4.0,-106.0,-104.0

In [46]:
df_betting_money_line = rcr('nba_betting_money_line.csv')
p(df_betting_money_line)

(125286, 7)

,game_id,book_name,book_id,team_id,a_team_id,price1,price2
0,41100314,Pinnacle Sports,238,1610612759,1610612760,165.0,-183.0
1,41100314,5Dimes,19,1610612759,1610612760,165.0,-175.0
2,41100314,Bookmaker,93,1610612759,1610612760,160.0,-190.0
3,41100314,BetOnline,1096,1610612759,1610612760,165.0,-190.0
4,41100314,Bovada,999996,1610612759,1610612760,155.0,-175.0
125281,41700215,Heritage,169,1610612755,1610612738,105.0,-125.0
125282,41700215,Intertops,180,1610612755,1610612738,100.0,-120.0
125283,41700215,YouWager,139,1610612755,1610612738,105.0,-125.0
125284,41700215,JustBet,1275,1610612755,1610612738,100.0,-120.0
125285,41700215,Sportsbetting,999991,1610612755,1610612738,105.0,-125.0

In [47]:
#get at least one row for each game_id
df_betting_money_line = df_betting_money_line.iloc[df_betting_money_line.game_id.drop_duplicates().index].reset_index(drop=True)
p(df_betting_money_line)

(14906, 7)

,game_id,book_name,book_id,team_id,a_team_id,price1,price2
0,41100314,Pinnacle Sports,238,1610612759,1610612760,165.0,-183.0
1,41100304,Pinnacle Sports,238,1610612748,1610612738,-128.0,116.0
2,41100315,Pinnacle Sports,238,1610612760,1610612759,188.0,-210.0
3,41100307,Pinnacle Sports,238,1610612738,1610612748,367.0,-427.0
4,21200015,Pinnacle Sports,238,1610612754,1610612766,-275.0,244.0
14901,41700212,Pinnacle Sports,238,1610612755,1610612738,-163.0,147.0
14902,41700233,Pinnacle Sports,238,1610612744,1610612740,-210.0,188.0
14903,41700213,Pinnacle Sports,238,1610612738,1610612755,450.0,-535.0
14904,41700234,Pinnacle Sports,238,1610612744,1610612740,-248.0,221.0
14905,41700215,Pinnacle Sports,238,1610612755,1610612738,103.0,-113.0

In [48]:
p(df_game1018)

(10267, 47)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
1,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
2,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
3,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
10262,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
10263,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
10264,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
10265,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
10266,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [49]:
df_game_betting_money_line1018 = pd.merge(df_game1018, df_betting_money_line.rename(columns=d), on=['game_id', 'team_id_home', 'team_id_away'], how='inner')
p(df_game_betting_money_line1018)

(9911, 51)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season,book_name,book_id,price1,price2
0,21000044,2010-11-01,1610612741,0.667,240,43.0,71.0,0.606,5.0,13.0,0.385,19.0,32.0,1.0,9.0,27.0,36,27.0,4.0,4.0,15.0,33.0,110,2010.0,1610612757,0.750,240,33.0,80.0,0.413,0.0,14.0,0.000,32.0,41.0,1.0,16.0,19.0,35,15.0,9.0,2.0,10.0,27.0,98,Regular Season,2010-11,Pinnacle Sports,238,-110.0,100.0
1,21000045,2010-11-01,1610612758,0.750,240,42.0,88.0,0.477,5.0,12.0,0.417,22.0,27.0,1.0,16.0,24.0,40,15.0,5.0,4.0,11.0,24.0,111,2010.0,1610612761,0.333,240,39.0,85.0,0.459,9.0,21.0,0.429,21.0,29.0,1.0,17.0,25.0,42,19.0,3.0,3.0,14.0,26.0,108,Regular Season,2010-11,Pinnacle Sports,238,214.0,-240.0
2,21000046,2010-11-01,1610612746,0.000,240,38.0,82.0,0.463,4.0,13.0,0.308,8.0,16.0,0.0,10.0,30.0,40,26.0,10.0,6.0,17.0,18.0,88,2010.0,1610612759,0.667,240,38.0,79.0,0.481,9.0,21.0,0.429,12.0,15.0,1.0,7.0,32.0,39,28.0,11.0,3.0,18.0,21.0,97,Regular Season,2010-11,Pinnacle Sports,238,-355.0,310.0
3,21000047,2010-11-02,1610612739,0.250,240,32.0,74.0,0.432,5.0,17.0,0.294,19.0,26.0,1.0,10.0,34.0,44,15.0,2.0,4.0,14.0,22.0,88,2010.0,1610612737,1.000,240,37.0,84.0,0.440,5.0,17.0,0.294,21.0,30.0,1.0,14.0,29.0,43,26.0,7.0,7.0,7.0,17.0,100,Regular Season,2010-11,Pinnacle Sports,238,-143.0,129.0
4,21000048,2010-11-02,1610612764,0.333,265,37.0,78.0,0.474,6.0,12.0,0.500,36.0,43.0,1.0,9.0,27.0,36,24.0,15.0,2.0,21.0,24.0,116,2010.0,1610612755,0.000,265,44.0,80.0,0.550,4.0,15.0,0.267,23.0,29.0,1.0,7.0,28.0,35,34.0,10.0,3.0,22.0,30.0,115,Regular Season,2010-11,Pinnacle Sports,238,126.0,-139.0
9906,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18,Pinnacle Sports,238,-269.0,239.0
9907,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18,Pinnacle Sports,238,656.0,-827.0
9908,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18,Pinnacle Sports,238,444.0,-527.0
9909,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18,Pinnacle Sports,238,-147.0,133.0
9910,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18,Pinnacle Sports,238,-166.0,150.0

In [50]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)
    
datapath_df = os.path.join(datapath, '4game_id_team_stats_betting_money_line_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_game_betting_money_line1018.to_csv(datapath_df, index=False)