In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
#return first 5 and last 5 rows of dataframe
def p(df_):
    return pd.concat([df_.head(), df_.tail()])

In [4]:
def get_df_ts_check():
    #get injury report for 2010-11 thru 2017-18 sesasons (for player relinquished): df_inj1018r
    df_inj1018r = pd.read_csv(os.path.join('..', 'processed_data', 'A9injury_game_date_team_relinquished_player_2010_2018.csv'), parse_dates=['game_date'])

    
    #read in nba boxscore advanced data for seasons 2009-10 thru 2017-18: df_5bsa1018
    df_3gdgiti0618 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])
    df_3gdgi0618 = df_3gdgiti0618[['game_date', 'game_id']].drop_duplicates()

    df_5bsa1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
    df_5bsa1018.PLAYER_NAME = df_5bsa1018.PLAYER_NAME.fillna('')
    df_5bsa1018 = pd.merge(df_3gdgi0618, df_5bsa1018.rename(columns={'GAME_ID':'game_id'}), on='game_id', how='inner')
    df_5bsa1018.MIN = df_5bsa1018.MIN.fillna('00:00')
    df_5bsa1018.MIN = pd.to_timedelta('00:' + df_5bsa1018.MIN).astype('timedelta64[s]').astype('float64') / 60
    df_5bsa1018.TEAM_ID = df_5bsa1018.TEAM_ID.fillna(0).astype('int64')
    
    df_gdinj1018 = pd.merge(df_inj1018r, df_5bsa1018.rename(columns={'PLAYER_NAME':'player'}), how='inner', on=['game_date', 'player'])
    
    df_gdinj1018[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']] = df_gdinj1018[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']].fillna(0)
    
    df_gdinj1018['ig_player_injury'] = 0
    df_gdinj1018.loc[df_gdinj1018.MIN != 0, 'ig_player_injury'] = 1
    
    
    df_3gdgiti0618 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])
    
    df_ts_check = pd.merge(df_3gdgiti0618[['game_id', 'season']].drop_duplicates().reset_index(drop=True), df_gdinj1018, on=['game_id', 'season'], how='inner')
    
    return df_ts_check

In [5]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [6]:
df_ts_check = get_df_ts_check()[['TEAM_ID', 'season', 'Team']].drop_duplicates().reset_index(drop=True)
print(df_ts_check.shape)
df_ts_check

(240, 3)

        TEAM_ID   season          Team
0    1610612748  2010-11          Heat
1    1610612749  2010-11         Bucks
2    1610612765  2010-11       Pistons
3    1610612753  2010-11         Magic
4    1610612737  2010-11         Hawks
5    1610612743  2010-11       Nuggets
6    1610612762  2010-11          Jazz
7    1610612744  2010-11      Warriors
8    1610612757  2010-11       Blazers
9    1610612764  2010-11       Wizards
10   1610612746  2010-11      Clippers
11   1610612750  2010-11  Timberwolves
12   1610612738  2010-11       Celtics
13   1610612761  2010-11       Raptors
14   1610612745  2010-11       Rockets
15   1610612752  2010-11        Knicks
16   1610612756  2010-11          Suns
17   1610612740  2010-11       Hornets
18   1610612741  2010-11         Bulls
19   1610612747  2010-11        Lakers
20   1610612760  2010-11       Thunder
21   1610612754  2010-11        Pacers
22   1610612739  2010-11     Cavaliers
23   1610612758  2010-11         Kings
24   1610612751  2010-11          Nets
25   1610612759  2010-11         Spurs
26   1610612755  2010-11         76ers
27   1610612742  2010-11     Mavericks
28   1610612763  2010-11     Grizzlies
29   1610612766  2010-11       Bobcats
30   1610612752  2011-12        Knicks
31   1610612746  2011-12      Clippers
32   1610612766  2011-12       Bobcats
33   1610612749  2011-12         Bucks
34   1610612750  2011-12  Timberwolves
35   1610612755  2011-12         76ers
36   1610612747  2011-12        Lakers
37   1610612738  2011-12       Celtics
38   1610612740  2011-12       Hornets
39   1610612737  2011-12         Hawks
40   1610612763  2011-12     Grizzlies
41   1610612762  2011-12          Jazz
42   1610612761  2011-12       Raptors
43   1610612741  2011-12         Bulls
44   1610612748  2011-12          Heat
45   1610612759  2011-12         Spurs
46   1610612751  2011-12          Nets
47   1610612758  2011-12         Kings
48   1610612765  2011-12       Pistons
49   1610612754  2011-12        Pacers
50   1610612745  2011-12       Rockets
51   1610612743  2011-12       Nuggets
52   1610612742  2011-12     Mavericks
53   1610612764  2011-12       Wizards
54   1610612744  2011-12      Warriors
55   1610612757  2011-12       Blazers
56   1610612756  2011-12          Suns
57   1610612760  2011-12       Thunder
58   1610612739  2011-12     Cavaliers
59   1610612753  2011-12         Magic
60   1610612738  2012-13       Celtics
61   1610612742  2012-13     Mavericks
62   1610612755  2012-13         76ers
63   1610612743  2012-13       Nuggets
64   1610612758  2012-13         Kings
65   1610612744  2012-13      Warriors
66   1610612752  2012-13        Knicks
67   1610612753  2012-13         Magic
68   1610612740  2012-13       Hornets
69   1610612737  2012-13         Hawks
70   1610612756  2012-13          Suns
71   1610612747  2012-13        Lakers
72   1610612750  2012-13  Timberwolves
73   1610612762  2012-13          Jazz
74   1610612759  2012-13         Spurs
75   1610612745  2012-13       Rockets
76   1610612739  2012-13     Cavaliers
77   1610612748  2012-13          Heat
78   1610612746  2012-13      Clippers
79   1610612766  2012-13       Bobcats
80   1610612757  2012-13       Blazers
81   1610612764  2012-13       Wizards
82   1610612763  2012-13     Grizzlies
83   1610612761  2012-13       Raptors
84   1610612765  2012-13       Pistons
85   1610612749  2012-13         Bucks
86   1610612754  2012-13        Pacers
87   1610612741  2012-13         Bulls
88   1610612760  2012-13       Thunder
89   1610612751  2012-13          Nets
90   1610612753  2013-14         Magic
91   1610612755  2013-14         76ers
92   1610612749  2013-14         Bucks
93   1610612752  2013-14        Knicks
94   1610612766  2013-14       Bobcats
95   1610612745  2013-14       Rockets
96   1610612762  2013-14          Jazz
97   1610612747  2013-14        Lakers
98   1610612744  2013-14      Warriors
99   1610612764  2013-14       Wizards
100  1610612761  2013-14       Raptors
101  1610612750  2013-14  Timberwolves
102  1610612757  2013-14       Blazers
103  1610612759  2013-14         Spurs
104  1610612756  2013-14          Suns
105  1610612754  2013-14        Pacers
106  1610612743  2013-14       Nuggets
107  1610612746  2013-14      Clippers
108  1610612763  2013-14     Grizzlies
109  1610612742  2013-14     Mavericks
110  1610612738  2013-14       Celtics
111  1610612740  2013-14      Pelicans
112  1610612741  2013-14         Bulls
113  1610612748  2013-14          Heat
114  1610612751  2013-14          Nets
115  1610612758  2013-14         Kings
116  1610612765  2013-14       Pistons
117  1610612739  2013-14     Cavaliers
118  1610612737  2013-14         Hawks
119  1610612760  2013-14       Thunder
120  1610612747  2014-15        Lakers
121  1610612755  2014-15         76ers
122  1610612754  2014-15        Pacers
123  1610612748  2014-15          Heat
124  1610612764  2014-15       Wizards
125  1610612750  2014-15  Timberwolves
126  1610612760  2014-15       Thunder
127  1610612758  2014-15         Kings
128  1610612741  2014-15         Bulls
129  1610612746  2014-15      Clippers
130  1610612740  2014-15      Pelicans
131  1610612765  2014-15       Pistons
132  1610612759  2014-15         Spurs
133  1610612752  2014-15        Knicks
134  1610612745  2014-15       Rockets
135  1610612753  2014-15         Magic
136  1610612744  2014-15      Warriors
137  1610612749  2014-15         Bucks
138  1610612766  2014-15       Hornets
139  1610612763  2014-15     Grizzlies
140  1610612743  2014-15       Nuggets
141  1610612742  2014-15     Mavericks
142  1610612762  2014-15          Jazz
143  1610612751  2014-15          Nets
144  1610612739  2014-15     Cavaliers
145  1610612737  2014-15         Hawks
146  1610612761  2014-15       Raptors
147  1610612738  2014-15       Celtics
148  1610612757  2014-15       Blazers
149  1610612756  2014-15          Suns
150  1610612740  2015-16      Pelicans
151  1610612755  2015-16         76ers
152  1610612766  2015-16       Hornets
153  1610612754  2015-16        Pacers
154  1610612760  2015-16       Thunder
155  1610612742  2015-16     Mavericks
156  1610612749  2015-16         Bucks
157  1610612745  2015-16       Rockets
158  1610612737  2015-16         Hawks
159  1610612743  2015-16       Nuggets
160  1610612747  2015-16        Lakers
161  1610612753  2015-16         Magic
162  1610612764  2015-16       Wizards
163  1610612758  2015-16         Kings
164  1610612746  2015-16      Clippers
165  1610612739  2015-16     Cavaliers
166  1610612741  2015-16         Bulls
167  1610612763  2015-16     Grizzlies
168  1610612750  2015-16  Timberwolves
169  1610612757  2015-16       Blazers
170  1610612762  2015-16          Jazz
171  1610612756  2015-16          Suns
172  1610612744  2015-16      Warriors
173  1610612761  2015-16       Raptors
174  1610612752  2015-16        Knicks
175  1610612751  2015-16          Nets
176  1610612748  2015-16          Heat
177  1610612765  2015-16       Pistons
178  1610612738  2015-16       Celtics
179  1610612759  2015-16         Spurs
180  1610612754  2016-17        Pacers
181  1610612761  2016-17       Raptors
182  1610612763  2016-17     Grizzlies
183  1610612757  2016-17       Blazers
184  1610612766  2016-17       Hornets
185  1610612751  2016-17          Nets
186  1610612759  2016-17         Spurs
187  1610612742  2016-17     Mavericks
188  1610612762  2016-17          Jazz
189  1610612755  2016-17         76ers
190  1610612740  2016-17      Pelicans
191  1610612738  2016-17       Celtics
192  1610612758  2016-17         Kings
193  1610612765  2016-17       Pistons
194  1610612743  2016-17       Nuggets
195  1610612764  2016-17       Wizards
196  1610612752  2016-17        Knicks
197  1610612741  2016-17         Bulls
198  1610612750  2016-17  Timberwolves
199  1610612748  2016-17          Heat
200  1610612739  2016-17     Cavaliers
201  1610612737  2016-17         Hawks
202  1610612756  2016-17          Suns
203  1610612760  2016-17       Thunder
204  1610612745  2016-17       Rockets
205  1610612747  2016-17        Lakers
206  1610612744  2016-17      Warriors
207  1610612746  2016-17      Clippers
208  1610612749  2016-17         Bucks
209  1610612753  2016-17         Magic
210  1610612738  2017-18       Celtics
211  1610612751  2017-18          Nets
212  1610612754  2017-18        Pacers
213  1610612755  2017-18         76ers
214  1610612757  2017-18       Blazers
215  1610612745  2017-18       Rockets
216  1610612766  2017-18       Hornets
217  1610612739  2017-18     Cavaliers
218  1610612761  2017-18       Raptors
219  1610612737  2017-18         Hawks
220  1610612750  2017-18  Timberwolves
221  1610612763  2017-18     Grizzlies
222  1610612741  2017-18         Bulls
223  1610612742  2017-18     Mavericks
224  1610612740  2017-18      Pelicans
225  1610612759  2017-18         Spurs
226  1610612748  2017-18          Heat
227  1610612747  2017-18        Lakers
228  1610612756  2017-18          Suns
229  1610612753  2017-18         Magic
230  1610612762  2017-18          Jazz
231  1610612760  2017-18       Thunder
232  1610612764  2017-18       Wizards
233  1610612743  2017-18       Nuggets
234  1610612749  2017-18         Bucks
235  1610612752  2017-18        Knicks
236  1610612758  2017-18         Kings
237  1610612744  2017-18      Warriors
238  1610612765  2017-18       Pistons
239  1610612746  2017-18      Clippers

In [7]:
seasons = set(df_ts_check['season'])
seasonsl = list(seasons)
seasonsl
seasonsl.sort(key = str)
df_seasons_adjacent = pd.DataFrame({'s': seasonsl[0:7], 'e':seasonsl[1:8]})
df_seasons_adjacent

         s        e
0  2010-11  2011-12
1  2011-12  2012-13
2  2012-13  2013-14
3  2013-14  2014-15
4  2014-15  2015-16
5  2015-16  2016-17
6  2016-17  2017-18

In [8]:
for row in range(7):
    start_ = df_seasons_adjacent.iloc[row,:]['s']
    end_ = df_seasons_adjacent.iloc[row,:]['e']
    print(start_ + ' and ' + end_ + ' ' +
          str(set(df_ts_check.Team[df_ts_check.season == start_]) - set(df_ts_check.Team[df_ts_check.season == end_])))




#Hornets not in 2013-14 season?
#Bobcats not in 2014-15 season?

2010-11 and 2011-12 set()
2011-12 and 2012-13 set()
2012-13 and 2013-14 {'Hornets'}
2013-14 and 2014-15 {'Bobcats'}
2014-15 and 2015-16 set()
2015-16 and 2016-17 set()
2016-17 and 2017-18 set()

In [9]:
for row in range(7):
    start_ = df_seasons_adjacent.iloc[row,:]['s']
    end_ = df_seasons_adjacent.iloc[row,:]['e']
    print(end_ + ' and ' + start_ + ' ' +
          str(set(df_ts_check.Team[df_ts_check.season == end_]) - set(df_ts_check.Team[df_ts_check.season == start_])))



#Pelicans appear in 2013-14 season
#Hornets arrive in 2014-15 season

2011-12 and 2010-11 set()
2012-13 and 2011-12 set()
2013-14 and 2012-13 {'Pelicans'}
2014-15 and 2013-14 {'Hornets'}
2015-16 and 2014-15 set()
2016-17 and 2015-16 set()
2017-18 and 2016-17 set()

In [10]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '10team_id_season_team_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_ts_check.to_csv(datapath_df, index=False)

In [11]:
df = pd.read_csv(os.path.join('..', 'processed_data', '10team_id_season_team_2010_2018.csv'))
print(df.shape)
df

(240, 3)

        TEAM_ID   season          Team
0    1610612748  2010-11          Heat
1    1610612749  2010-11         Bucks
2    1610612765  2010-11       Pistons
3    1610612753  2010-11         Magic
4    1610612737  2010-11         Hawks
5    1610612743  2010-11       Nuggets
6    1610612762  2010-11          Jazz
7    1610612744  2010-11      Warriors
8    1610612757  2010-11       Blazers
9    1610612764  2010-11       Wizards
10   1610612746  2010-11      Clippers
11   1610612750  2010-11  Timberwolves
12   1610612738  2010-11       Celtics
13   1610612761  2010-11       Raptors
14   1610612745  2010-11       Rockets
15   1610612752  2010-11        Knicks
16   1610612756  2010-11          Suns
17   1610612740  2010-11       Hornets
18   1610612741  2010-11         Bulls
19   1610612747  2010-11        Lakers
20   1610612760  2010-11       Thunder
21   1610612754  2010-11        Pacers
22   1610612739  2010-11     Cavaliers
23   1610612758  2010-11         Kings
24   1610612751  2010-11          Nets
25   1610612759  2010-11         Spurs
26   1610612755  2010-11         76ers
27   1610612742  2010-11     Mavericks
28   1610612763  2010-11     Grizzlies
29   1610612766  2010-11       Bobcats
30   1610612752  2011-12        Knicks
31   1610612746  2011-12      Clippers
32   1610612766  2011-12       Bobcats
33   1610612749  2011-12         Bucks
34   1610612750  2011-12  Timberwolves
35   1610612755  2011-12         76ers
36   1610612747  2011-12        Lakers
37   1610612738  2011-12       Celtics
38   1610612740  2011-12       Hornets
39   1610612737  2011-12         Hawks
40   1610612763  2011-12     Grizzlies
41   1610612762  2011-12          Jazz
42   1610612761  2011-12       Raptors
43   1610612741  2011-12         Bulls
44   1610612748  2011-12          Heat
45   1610612759  2011-12         Spurs
46   1610612751  2011-12          Nets
47   1610612758  2011-12         Kings
48   1610612765  2011-12       Pistons
49   1610612754  2011-12        Pacers
50   1610612745  2011-12       Rockets
51   1610612743  2011-12       Nuggets
52   1610612742  2011-12     Mavericks
53   1610612764  2011-12       Wizards
54   1610612744  2011-12      Warriors
55   1610612757  2011-12       Blazers
56   1610612756  2011-12          Suns
57   1610612760  2011-12       Thunder
58   1610612739  2011-12     Cavaliers
59   1610612753  2011-12         Magic
60   1610612738  2012-13       Celtics
61   1610612742  2012-13     Mavericks
62   1610612755  2012-13         76ers
63   1610612743  2012-13       Nuggets
64   1610612758  2012-13         Kings
65   1610612744  2012-13      Warriors
66   1610612752  2012-13        Knicks
67   1610612753  2012-13         Magic
68   1610612740  2012-13       Hornets
69   1610612737  2012-13         Hawks
70   1610612756  2012-13          Suns
71   1610612747  2012-13        Lakers
72   1610612750  2012-13  Timberwolves
73   1610612762  2012-13          Jazz
74   1610612759  2012-13         Spurs
75   1610612745  2012-13       Rockets
76   1610612739  2012-13     Cavaliers
77   1610612748  2012-13          Heat
78   1610612746  2012-13      Clippers
79   1610612766  2012-13       Bobcats
80   1610612757  2012-13       Blazers
81   1610612764  2012-13       Wizards
82   1610612763  2012-13     Grizzlies
83   1610612761  2012-13       Raptors
84   1610612765  2012-13       Pistons
85   1610612749  2012-13         Bucks
86   1610612754  2012-13        Pacers
87   1610612741  2012-13         Bulls
88   1610612760  2012-13       Thunder
89   1610612751  2012-13          Nets
90   1610612753  2013-14         Magic
91   1610612755  2013-14         76ers
92   1610612749  2013-14         Bucks
93   1610612752  2013-14        Knicks
94   1610612766  2013-14       Bobcats
95   1610612745  2013-14       Rockets
96   1610612762  2013-14          Jazz
97   1610612747  2013-14        Lakers
98   1610612744  2013-14      Warriors
99   1610612764  2013-14       Wizards
100  1610612761  2013-14       Raptors
101  1610612750  2013-14  Timberwolves
102  1610612757  2013-14       Blazers
103  1610612759  2013-14         Spurs
104  1610612756  2013-14          Suns
105  1610612754  2013-14        Pacers
106  1610612743  2013-14       Nuggets
107  1610612746  2013-14      Clippers
108  1610612763  2013-14     Grizzlies
109  1610612742  2013-14     Mavericks
110  1610612738  2013-14       Celtics
111  1610612740  2013-14      Pelicans
112  1610612741  2013-14         Bulls
113  1610612748  2013-14          Heat
114  1610612751  2013-14          Nets
115  1610612758  2013-14         Kings
116  1610612765  2013-14       Pistons
117  1610612739  2013-14     Cavaliers
118  1610612737  2013-14         Hawks
119  1610612760  2013-14       Thunder
120  1610612747  2014-15        Lakers
121  1610612755  2014-15         76ers
122  1610612754  2014-15        Pacers
123  1610612748  2014-15          Heat
124  1610612764  2014-15       Wizards
125  1610612750  2014-15  Timberwolves
126  1610612760  2014-15       Thunder
127  1610612758  2014-15         Kings
128  1610612741  2014-15         Bulls
129  1610612746  2014-15      Clippers
130  1610612740  2014-15      Pelicans
131  1610612765  2014-15       Pistons
132  1610612759  2014-15         Spurs
133  1610612752  2014-15        Knicks
134  1610612745  2014-15       Rockets
135  1610612753  2014-15         Magic
136  1610612744  2014-15      Warriors
137  1610612749  2014-15         Bucks
138  1610612766  2014-15       Hornets
139  1610612763  2014-15     Grizzlies
140  1610612743  2014-15       Nuggets
141  1610612742  2014-15     Mavericks
142  1610612762  2014-15          Jazz
143  1610612751  2014-15          Nets
144  1610612739  2014-15     Cavaliers
145  1610612737  2014-15         Hawks
146  1610612761  2014-15       Raptors
147  1610612738  2014-15       Celtics
148  1610612757  2014-15       Blazers
149  1610612756  2014-15          Suns
150  1610612740  2015-16      Pelicans
151  1610612755  2015-16         76ers
152  1610612766  2015-16       Hornets
153  1610612754  2015-16        Pacers
154  1610612760  2015-16       Thunder
155  1610612742  2015-16     Mavericks
156  1610612749  2015-16         Bucks
157  1610612745  2015-16       Rockets
158  1610612737  2015-16         Hawks
159  1610612743  2015-16       Nuggets
160  1610612747  2015-16        Lakers
161  1610612753  2015-16         Magic
162  1610612764  2015-16       Wizards
163  1610612758  2015-16         Kings
164  1610612746  2015-16      Clippers
165  1610612739  2015-16     Cavaliers
166  1610612741  2015-16         Bulls
167  1610612763  2015-16     Grizzlies
168  1610612750  2015-16  Timberwolves
169  1610612757  2015-16       Blazers
170  1610612762  2015-16          Jazz
171  1610612756  2015-16          Suns
172  1610612744  2015-16      Warriors
173  1610612761  2015-16       Raptors
174  1610612752  2015-16        Knicks
175  1610612751  2015-16          Nets
176  1610612748  2015-16          Heat
177  1610612765  2015-16       Pistons
178  1610612738  2015-16       Celtics
179  1610612759  2015-16         Spurs
180  1610612754  2016-17        Pacers
181  1610612761  2016-17       Raptors
182  1610612763  2016-17     Grizzlies
183  1610612757  2016-17       Blazers
184  1610612766  2016-17       Hornets
185  1610612751  2016-17          Nets
186  1610612759  2016-17         Spurs
187  1610612742  2016-17     Mavericks
188  1610612762  2016-17          Jazz
189  1610612755  2016-17         76ers
190  1610612740  2016-17      Pelicans
191  1610612738  2016-17       Celtics
192  1610612758  2016-17         Kings
193  1610612765  2016-17       Pistons
194  1610612743  2016-17       Nuggets
195  1610612764  2016-17       Wizards
196  1610612752  2016-17        Knicks
197  1610612741  2016-17         Bulls
198  1610612750  2016-17  Timberwolves
199  1610612748  2016-17          Heat
200  1610612739  2016-17     Cavaliers
201  1610612737  2016-17         Hawks
202  1610612756  2016-17          Suns
203  1610612760  2016-17       Thunder
204  1610612745  2016-17       Rockets
205  1610612747  2016-17        Lakers
206  1610612744  2016-17      Warriors
207  1610612746  2016-17      Clippers
208  1610612749  2016-17         Bucks
209  1610612753  2016-17         Magic
210  1610612738  2017-18       Celtics
211  1610612751  2017-18          Nets
212  1610612754  2017-18        Pacers
213  1610612755  2017-18         76ers
214  1610612757  2017-18       Blazers
215  1610612745  2017-18       Rockets
216  1610612766  2017-18       Hornets
217  1610612739  2017-18     Cavaliers
218  1610612761  2017-18       Raptors
219  1610612737  2017-18         Hawks
220  1610612750  2017-18  Timberwolves
221  1610612763  2017-18     Grizzlies
222  1610612741  2017-18         Bulls
223  1610612742  2017-18     Mavericks
224  1610612740  2017-18      Pelicans
225  1610612759  2017-18         Spurs
226  1610612748  2017-18          Heat
227  1610612747  2017-18        Lakers
228  1610612756  2017-18          Suns
229  1610612753  2017-18         Magic
230  1610612762  2017-18          Jazz
231  1610612760  2017-18       Thunder
232  1610612764  2017-18       Wizards
233  1610612743  2017-18       Nuggets
234  1610612749  2017-18         Bucks
235  1610612752  2017-18        Knicks
236  1610612758  2017-18         Kings
237  1610612744  2017-18      Warriors
238  1610612765  2017-18       Pistons
239  1610612746  2017-18      Clippers