In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
def replace_player(df_):
    df_.player.replace({'J.J. Redick':'JJ Redick'}, inplace=True)
    
    df_.player.replace({'A.J. Price': 'AJ Price'}, inplace=True)
    
    df_.player.replace({'Alex Ajinca':'Alexis Ajinca'}, inplace=True)
    
    df_.player.replace({'C.J. Miles': 'CJ Miles'}, inplace=True)
    
    df_.player.replace({'D.J. White': 'DJ White'}, inplace=True)
    
    df_.player.replace({"Hamady N'Diaye" : 'Hamady Ndiaye'}, inplace=True)
    
    df_.player.replace({'J.J. Hickson': 'JJ Hickson'}, inplace=True)
    
    df_.player.replace({'John Wallace' : 'John Wall'}, inplace=True)
    
    df_.player.replace({'Jose Barea' : 'J.J. Barea'}, inplace=True)
    
    df_.player.replace({'Wes Johnson':'Wesley Johnson'}, inplace=True)
    
    df_.player.replace({'B.J. Mullens':'Byron Mullens'}, inplace=True)
    
    df_.player.replace({'Bill Walker':'Henry Walker'}, inplace=True)
    
    df_.player.replace({'Gerald Henderson Jr.':'Gerald Henderson'}, inplace=True)
    
    df_.player.replace({'Jianlian Yi':'Yi Jianlian'}, inplace=True)
    
    df_.player.replace({'Mike Conley Jr.':'Mike Conley'}, inplace=True)
    
    df_.player.replace({'Mike Dunleavy Jr.':'Mike Dunleavy'}, inplace=True)
    
    df_.player.replace({'Nene Hilario': 'Nene'}, inplace=True)
    
    df_.player.replace({'Didier Mbenga':'DJ Mbenga'}, inplace=True)
    
    df_.player.replace({'A.J. Hammons':'AJ Hammons'}, inplace=True)
    
    df_.player.replace({'C.J. McCollum':'CJ McCollum'}, inplace=True)
    
    df_.player.replace({'D.J. Augustine':'D.J. Augustin'}, inplace=True)
    
    df_.player.replace({'DeAndre Bembry':"DeAndre' Bembry"}, inplace=True)
    
    df_.player.replace({'Giorgios Papagiannis':'Georgios Papagiannis'}, inplace=True)
    
    df_.player.replace({'Glen Rice Jr.':'Glen Rice'}, inplace=True)
    
    df_.player.replace({'J.R. Smith':'JR Smith'}, inplace=True)
    
    df_.player.replace({'James Ennis':'James Ennis III'}, inplace=True)
    
    df_.player.replace({'John Collins  John Collins':'John Collins'}, inplace=True)
    
    df_.player.replace({'Juan Hernangomez':'Juancho Hernangomez'}, inplace=True)
    
    df_.player.replace({'Billy Ouattara':'Yakuba Ouattara'}, inplace=True)
    
    df_.player.replace({'Courtney Simpson':'Diamon Simpson'}, inplace=True)
    
    df_.player.replace({'Danuel House':'Danuel House Jr.'}, inplace=True)
    
    df_.player.replace({'Domas Sabonis':'Domantas Sabonis'}, inplace=True)
    
    df_.player.replace({'Jake Wiley':'Jacob Wiley'}, inplace=True)
    
    df_.player.replace({'James McAdoo':'James Michael McAdoo'}, inplace=True)
    
    df_.player.replace({'Jeff Pendergraph':'Jeff Ayres'}, inplace=True)
    
    df_.player.replace({'Jeff Taylor':'Jeffery Taylor'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'Malcom Lee':'Malcolm Lee'}, inplace=True)
    
    df_.player.replace({'Marcus Morris':'Marcus Morris Sr.'}, inplace=True)
    
    df_.player.replace({'Matt Williams':'Matt Williams Jr.'}, inplace=True)
    
    df_.player.replace({"Maurice N'dour":'Maurice Ndour'}, inplace=True)
    
    df_.player.replace({'Milos Tedosic':'Milos Teodosic'}, inplace=True)
    
    df_.player.replace({'Moe Harkless':'Maurice Harkless'}, inplace=True)
    
    df_.player.replace({'O.G. Anunoby':'OG Anunoby'}, inplace=True)
    
    df_.player.replace({'Ognen Kuzmic':'Ognjen Kuzmic'}, inplace=True)
    
    df_.player.replace({'P.J. Dozier':'PJ Dozier'}, inplace=True)
    
    df_.player.replace({'P.J. Hairston':'PJ Hairston'}, inplace=True)
    
    df_.player.replace({'Qi Zhou':'Zhou Qi'}, inplace=True)
    
    df_.player.replace({'R.J. Hunter':'RJ Hunter'}, inplace=True)
    
    df_.player.replace({'Ray McCallum Jr.':'Ray McCallum'}, inplace=True)
    
    df_.player.replace({'Ron Artest':'Metta World Peace'}, inplace=True)
    
    df_.player.replace({'Roy Marble':'Devyn Marble'}, inplace=True)
    
    df_.player.replace({'Stephen Zimmerman Jr.':'Stephen Zimmerman'}, inplace=True)
    
    df_.player.replace({'Tony Wroten Jr.':'Tony Wroten'}, inplace=True)
    
    df_.player.replace({'Toure Murry':"Toure' Murry"}, inplace=True)
    
    df_.player.replace({'Viacheslav Kravstov':'Viacheslav Kravtsov'}, inplace=True)
    
    df_.player.replace({'Vince Hunter':'Vincent Hunter'}, inplace=True)
    
    df_.player.replace({'Walker Russell Jr.':'Walker Russell'}, inplace=True)
    
    df_.player.replace({'Wayne Selden Jr.':'Wayne Selden'}, inplace=True)
    
    df_.player.replace({'Wes Matthews Jr.':'Wesley Matthews'}, inplace=True)
    
    return df_

#names dropped from Injury Report dataframe df_inj1018 for the following reasons:
#a. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons.
#b. player did not play an nba regular season or playoff game between the 2009-10 and 2017-18 seasons.
#c. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons. Player plays in nba games
#   following the 2017-18 season.
#d. this is the injury of a coach, not a player. coaches do not have boxscore advanced stats


def drop_player(df_):
    df_.drop(df_[df_.player.str.contains('Marion Hillard')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Matt Janning')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains("Da'Sean Butler")].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Eric Griffin')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Harry Giles')].index, inplace = True) #c
    
    df_.drop(df_[df_.player.str.contains('Magnum Rolle')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Robert Vaden')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Steve Clifford')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Steve Kerr')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Terrico White')].index, inplace = True)#a
    
    df_.drop(df_[df_.player.str.contains('Tyronn Lue')].index, inplace = True) #d
    
    return df_

def df_inj1020_fix_Date_Team(df_):
    df_.loc[5923, ['Team']] = 'Pacers'
    return df_

def manual_not_the_actual_game_date_drop(df_):
    df_.drop(21307, inplace=True) #df_[(df_.game_date == '2013-05-10') & (df_.player == 'Eric Gordon')]
    df_.reset_index(drop=True, inplace=True)
    return df_

'''def manual_not_the_game_date_drop2(df_):
    df_ = df_.drop(14084) #df_[(df_.game_date == '2013-05-10') & (df_.player == 'Eric Gordon')]
    df_ = df_.reset_index(drop=True)
    return df_'''


def get_5bsa1018_inj1018_player_diff():
    print(len(set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME)))
    print(set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME))
    print()
    
    print(len(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player)))
    print(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player))
    return 0
    
    
#get injury data for player
def gi(player_):
    return df_inj1018[df_inj1018.player.str.contains(player_)] 

#get boxscore advance for player
def gb(player_):
    return df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(player_)]

#get inactive player game-by-game
def gia(player_):
    return df_ina1018[df_ina1018.player.str.contains(player_)]

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    return pd.concat([df_.head(), df_.tail()])

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
#get injury report for 2010-11 thru 2017-18 sesasons: df_inj1018

#last game_date of 2017-18 season
path = os.path.join('..', 'processed_data', '7season_first_game_date_last_game_date.csv')
df_7sfgdlgd = pd.read_csv(path, parse_dates=['first', 'last'])
last_game_date_s1718 = df_7sfgdlgd.iloc[8]['last']
last_game_date_s1718

Timestamp('2018-06-08 00:00:00')

In [6]:
#read in raw injury report
path = os.path.join('..', 'raw_data', 'injuries_2010-2020.csv')
df_inj1020 = pd.read_csv(path, parse_dates=['Date'])
print(df_inj1020.shape)
p(df_inj1020)

(27105, 5)

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

In [7]:
#preprocess player & Date
df_inj1020.Acquired.fillna('', inplace=True)
df_inj1020.Relinquished.fillna('', inplace=True)
df_inj1020['player'] = df_inj1020.Relinquished + ' ' + df_inj1020.Acquired
df_inj1020.player = df_inj1020.player.str.strip()
df_inj1020 = df_inj1020_fix_Date_Team(df_inj1020)
print(df_inj1020.shape)
p(df_inj1020)

(27105, 6)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
27100,2020-09-30,Lakers,Dion Waiters,,activated from IL,Dion Waiters
27101,2020-10-02,Heat,,Bam Adebayo,strained neck (DTD),Bam Adebayo
27102,2020-10-02,Heat,,Goran Dragic,placed on IL with torn plantar fascia in left foot,Goran Dragic
27103,2020-10-02,Heat,Chris Silva,,activated from IL,Chris Silva
27104,2020-10-06,Heat,Bam Adebayo,,returned to lineup,Bam Adebayo

In [8]:
#bound last game date and make new dateframe: df_inj1018
df_inj1018 = df_inj1020.loc[df_inj1020['Date'] <= last_game_date_s1718]
print(df_inj1018.shape)
p(df_inj1018)

(22257, 6)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [9]:
#fix player (name)
df_inj1018 = replace_player(df_inj1018)
df_inj1018 = drop_player(df_inj1018)
print(df_inj1018.shape)
p(df_inj1018)

(22232, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4563: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [10]:
#filter Date to game_date
df_3gdgiti0618 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])
df_3gds0618 = df_3gdgiti0618[['game_date', 'season']].drop_duplicates()
df_3gds0618 = df_3gds0618.drop_duplicates()
df_inj1018 = pd.merge(df_3gds0618.drop_duplicates(), df_inj1018.rename(columns={'Date':'game_date'}), on='game_date', how='inner')

manual_not_the_actual_game_date_drop(df_inj1018) #inplace=True
print(df_inj1018.shape)
p(df_inj1018)

(21920, 7)

,game_date,season,Team,Acquired,Relinquished,Notes,player
0,2010-10-26,2010-11,Blazers,,Elliot Williams,placed on IL,Elliot Williams
1,2010-10-26,2010-11,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden
2,2010-10-26,2010-11,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla
3,2010-10-26,2010-11,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,Avery Bradley
4,2010-10-26,2010-11,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,Kendrick Perkins
21915,2018-05-22,2017-18,Warriors,,Andre Iguodala,bruised left leg (DTD),Andre Iguodala
21916,2018-05-26,2017-18,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
21917,2018-05-26,2017-18,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
21918,2018-05-31,2017-18,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
21919,2018-06-06,2017-18,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [11]:
df_inj1018[(df_inj1018.game_date == '2013-05-10') & (df_inj1018.player == 'Eric Gordon')]

Empty DataFrame
Columns: [game_date, season, Team, Acquired, Relinquished, Notes, player]
Index: []

In [12]:
df_inj1018[(df_inj1018.game_date == '2013-05-10') & (df_inj1018.player == 'Eric Gordon')]

Empty DataFrame
Columns: [game_date, season, Team, Acquired, Relinquished, Notes, player]
Index: []

In [13]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '9injury_game_date_team_acquired_relinquished_player_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_inj1018.to_csv(datapath_df, index=False)

In [14]:
print(df_inj1018.shape)
p(df_inj1018)

(21920, 7)

,game_date,season,Team,Acquired,Relinquished,Notes,player
0,2010-10-26,2010-11,Blazers,,Elliot Williams,placed on IL,Elliot Williams
1,2010-10-26,2010-11,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden
2,2010-10-26,2010-11,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla
3,2010-10-26,2010-11,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,Avery Bradley
4,2010-10-26,2010-11,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,Kendrick Perkins
21915,2018-05-22,2017-18,Warriors,,Andre Iguodala,bruised left leg (DTD),Andre Iguodala
21916,2018-05-26,2017-18,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
21917,2018-05-26,2017-18,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
21918,2018-05-31,2017-18,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
21919,2018-06-06,2017-18,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [15]:
#get Relinquished player's and drop 'Acquired' column
df_inj1018r = df_inj1018[df_inj1018.Relinquished != ''].drop(columns=['Acquired']).reset_index(drop=True)
print(df_inj1018r.shape)
p(df_inj1018r)

(14448, 6)

,game_date,season,Team,Relinquished,Notes,player
0,2010-10-26,2010-11,Blazers,Elliot Williams,placed on IL,Elliot Williams
1,2010-10-26,2010-11,Blazers,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden
2,2010-10-26,2010-11,Blazers,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla
3,2010-10-26,2010-11,Celtics,Avery Bradley,placed on IL recovering from surgery on left ankle,Avery Bradley
4,2010-10-26,2010-11,Celtics,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,Kendrick Perkins
14443,2018-05-09,2017-18,Thunder,Paul George,arthroscopic surgery on right knee (out indefinitely),Paul George
14444,2018-05-08,2017-18,Jazz,Dante Exum,placed on IL with strained left hamstring (out for season),Dante Exum
14445,2018-05-25,2017-18,Rockets,Chris Paul,strained right hamstring (out for season),Chris Paul
14446,2018-05-22,2017-18,Warriors,Andre Iguodala,bruised left leg (DTD),Andre Iguodala
14447,2018-05-26,2017-18,Cavaliers,Kevin Love,concussion (DTD),Kevin Love

In [16]:
df_bsa1018 =  pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
print(df_bsa1018.shape)
p(df_bsa1018)

(291643, 31)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [17]:
df_right = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])[['game_id', 'game_date']]
df_right

        game_id  game_date
0      20600001 2006-10-31
1      20600001 2006-10-31
2      20600002 2006-10-31
3      20600002 2006-10-31
4      20600003 2006-11-01
...         ...        ...
31033  41700402 2018-06-03
31034  41700403 2018-06-06
31035  41700403 2018-06-06
31036  41700404 2018-06-08
31037  41700404 2018-06-08

[31038 rows x 2 columns]

In [18]:
df_bsa1018 = pd.merge(df_bsa1018.rename(columns={'GAME_ID':'game_id'}), df_right, on='game_id', how='inner')
df_bsa1018

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,game_date
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189,2009-10-27
1,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189,2009-10-27
2,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147,2009-10-27
3,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147,2009-10-27
4,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030,2009-10-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583281,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174,2018-06-08
583282,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250,2018-06-08
583283,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250,2018-06-08
583284,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN,2018-06-08
583285,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN,2018-06-08

In [19]:
df_inj1018

,game_date,season,Team,Acquired,Relinquished,Notes,player
0,2010-10-26,2010-11,Blazers,,Elliot Williams,placed on IL,Elliot Williams
1,2010-10-26,2010-11,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden
2,2010-10-26,2010-11,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla
3,2010-10-26,2010-11,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,Avery Bradley
4,2010-10-26,2010-11,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,Kendrick Perkins
...,...,...,...,...,...,...,...
21915,2018-05-22,2017-18,Warriors,,Andre Iguodala,bruised left leg (DTD),Andre Iguodala
21916,2018-05-26,2017-18,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
21917,2018-05-26,2017-18,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
21918,2018-05-31,2017-18,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
21919,2018-06-06,2017-18,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [20]:
df_inj1018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21920 entries, 0 to 21919
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     21920 non-null  datetime64[ns]
 1   season        21920 non-null  object
 2   Team          21920 non-null  object
 3   Acquired      21920 non-null  object
 4   Relinquished  21920 non-null  object
 5   Notes         21920 non-null  object
 6   player        21920 non-null  object
dtypes: datetime64[ns](1), object(6)
memory usage: 1.2+ MB

In [21]:
df_bsa1018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 583286 entries, 0 to 583285
Data columns (total 32 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   game_id            583286 non-null  int64
 1   TEAM_ID            583284 non-null  float64
 2   TEAM_ABBREVIATION  583284 non-null  object
 3   TEAM_CITY          583284 non-null  object
 4   PLAYER_ID          583284 non-null  float64
 5   PLAYER_NAME        583284 non-null  object
 6   START_POSITION     231560 non-null  object
 7   COMMENT            99022 non-null   object
 8   MIN                484288 non-null  object
 9   E_OFF_RATING       484288 non-null  float64
 10  OFF_RATING         583284 non-null  float64
 11  E_DEF_RATING       484288 non-null  float64
 12  DEF_RATING         583284 non-null  float64
 13  E_NET_RATING       484288 non-null  float64
 14  NET_RATING         583284 non-null  float64
 15  AST_PCT            484288 non-null  float64
 16  AST_TOV            484288 non-null  float64
 17  AST_RATIO          484288 non-null  float64
 18  OREB_PCT           583284 non-null  float64
 19  DREB_PCT           583284 non-null  float64
 20  REB_PCT            583284 non-null  float64
 21  TM_TOV_PCT         484288 non-null  float64
 22  EFG_PCT            484288 non-null  float64
 23  TS_PCT             484288 non-null  float64
 24  USG_PCT            583284 non-null  float64
 25  E_USG_PCT          583284 non-null  float64
 26  E_PACE             484288 non-null  float64
 27  PACE               484288 non-null  float64
 28  PACE_PER40         484288 non-null  float64
 29  POSS               583284 non-null  float64
 30  PIE                484288 non-null  float64
 31  game_date          583286 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(24), int64(1), object(6)
memory usage: 146.9+ MB

In [22]:
pd.merge(df_bsa1018.rename(columns={'PLAYER_NAME':'player'}), df_inj1018, on=['game_date', 'player'])

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,player,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,game_date,season,Team,Acquired,Relinquished,Notes
0,21000001,1.610613e+09,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN,2010-10-26,2010-11,Heat,,Mario Chalmers,sprained ankle (out indefinitely)
1,21000001,1.610613e+09,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN,2010-10-26,2010-11,Heat,,Mario Chalmers,sprained ankle (out indefinitely)
2,21000006,1.610613e+09,MIA,Miami,711.0,Jerry Stackhouse,NaN,NaN,5:07,131.6,130.0,121.5,120.0,10.1,10.0,0.250,0.0,33.3,0.000,0.500,0.143,0.0,0.000,0.532,0.200,0.202,92.69,93.81,78.18,10.0,0.120,2010-10-27,2010-11,Heat,Jerry Stackhouse,,activated from IL
3,21000006,1.610613e+09,MIA,Miami,711.0,Jerry Stackhouse,NaN,NaN,5:07,131.6,130.0,121.5,120.0,10.1,10.0,0.250,0.0,33.3,0.000,0.500,0.143,0.0,0.000,0.532,0.200,0.202,92.69,93.81,78.18,10.0,0.120,2010-10-27,2010-11,Heat,Jerry Stackhouse,,activated from IL
4,21000010,1.610613e+09,MIL,Milwaukee,201972.0,Jon Brockman,NaN,DND - left ankle injury,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN,2010-10-27,2010-11,Bucks,,Jon Brockman,sprained left ankle (DNP)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27767,41700316,1.610613e+09,GSW,Golden State,1627775.0,Patrick McCaw,NaN,NaN,4:28,128.6,112.5,63.5,62.5,65.1,50.0,0.000,0.0,0.0,0.000,0.400,0.286,0.0,0.500,0.500,0.222,0.250,79.95,85.97,71.64,8.0,0.261,2018-05-26,2017-18,Warriors,Patrick McCaw,,activated from IL
27768,41700401,1.610613e+09,CLE,Cleveland,201567.0,Kevin Love,F,NaN,39:04,108.7,109.2,126.4,133.3,-17.7,-24.1,0.048,1.0,4.5,0.045,0.379,0.178,4.5,0.475,0.503,0.223,0.230,93.57,90.91,75.76,76.0,0.127,2018-05-31,2017-18,Cavaliers,Kevin Love,,returned to lineup
27769,41700401,1.610613e+09,CLE,Cleveland,201567.0,Kevin Love,F,NaN,39:04,108.7,109.2,126.4,133.3,-17.7,-24.1,0.048,1.0,4.5,0.045,0.379,0.178,4.5,0.475,0.503,0.223,0.230,93.57,90.91,75.76,76.0,0.127,2018-05-31,2017-18,Cavaliers,Kevin Love,,returned to lineup
27770,41700403,1.610613e+09,GSW,Golden State,2738.0,Andre Iguodala,NaN,NaN,21:53,142.3,138.5,100.9,105.3,41.3,33.2,0.059,1.0,14.3,0.000,0.087,0.056,14.3,0.750,0.820,0.143,0.150,85.14,84.48,70.40,39.0,0.087,2018-06-06,2017-18,Warriors,Andre Iguodala,,returned to lineup
27771,41700403,1.610613e+09,GSW,Golden State,2738.0,Andre Iguodala,NaN,NaN,21:53,142.3,138.5,100.9,105.3,41.3,33.2,0.059,1.0,14.3,0.000,0.087,0.056,14.3,0.750,0.820,0.143,0.150,85.14,84.48,70.40,39.0,0.087,2018-06-06,2017-18,Warriors,Andre Iguodala,,returned to lineup

In [23]:
df_merged = pd.merge(df_bsa1018.rename(columns={'PLAYER_NAME':'player'}), df_inj1018r, on=['game_date', 'player'], how='inner')
df_merged

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,player,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,game_date,season,Team,Relinquished,Notes
0,21000001,1.610613e+09,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-26,2010-11,Heat,Mario Chalmers,sprained ankle (out indefinitely)
1,21000001,1.610613e+09,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-26,2010-11,Heat,Mario Chalmers,sprained ankle (out indefinitely)
2,21000010,1.610613e+09,MIL,Milwaukee,201972.0,Jon Brockman,NaN,DND - left ankle injury,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-27,2010-11,Bucks,Jon Brockman,sprained left ankle (DNP)
3,21000010,1.610613e+09,MIL,Milwaukee,201972.0,Jon Brockman,NaN,DND - left ankle injury,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-27,2010-11,Bucks,Jon Brockman,sprained left ankle (DNP)
4,21000010,1.610613e+09,MIL,Milwaukee,201601.0,Luc Mbah a Moute,NaN,DND - right ankle injury,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-27,2010-11,Bucks,Luc Mbah a Moute,sprained right ankle (DNP)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13331,41700144,1.610613e+09,MIN,Minnesota,1626145.0,Tyus Jones,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-04-23,2017-18,Timberwolves,Tyus Jones,sore right knee (DTD)
13332,41700211,1.610613e+09,BOS,Boston,1627759.0,Jaylen Brown,NaN,DND - Injury/Illness,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-04-30,2017-18,Celtics,Jaylen Brown,strained right hamstring (DTD)
13333,41700211,1.610613e+09,BOS,Boston,1627759.0,Jaylen Brown,NaN,DND - Injury/Illness,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-04-30,2017-18,Celtics,Jaylen Brown,strained right hamstring (DTD)
13334,41700215,1.610613e+09,BOS,Boston,203499.0,Shane Larkin,NaN,DND - Injury/Illness,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-05-09,2017-18,Celtics,Shane Larkin,sprained left shoulder (out for season)
13335,41700215,1.610613e+09,BOS,Boston,203499.0,Shane Larkin,NaN,DND - Injury/Illness,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-05-09,2017-18,Celtics,Shane Larkin,sprained left shoulder (out for season)

In [24]:
df_merged.MIN.fillna('00:00')

0        00:00
1        00:00
2        00:00
3        00:00
4        00:00
         ...
13331    00:00
13332    00:00
13333    00:00
13334    00:00
13335    00:00
Name: MIN, Length: 13336, dtype: object

In [25]:
df_merged.MIN = df_merged.MIN.fillna('00:00')

In [26]:
df_merged.MIN = pd.to_timedelta('00:' + df_merged.MIN).astype('timedelta64[s]').astype('float64') / 60
df_merged

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,player,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,game_date,season,Team,Relinquished,Notes
0,21000001,1.610613e+09,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-26,2010-11,Heat,Mario Chalmers,sprained ankle (out indefinitely)
1,21000001,1.610613e+09,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-26,2010-11,Heat,Mario Chalmers,sprained ankle (out indefinitely)
2,21000010,1.610613e+09,MIL,Milwaukee,201972.0,Jon Brockman,NaN,DND - left ankle injury,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-27,2010-11,Bucks,Jon Brockman,sprained left ankle (DNP)
3,21000010,1.610613e+09,MIL,Milwaukee,201972.0,Jon Brockman,NaN,DND - left ankle injury,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-27,2010-11,Bucks,Jon Brockman,sprained left ankle (DNP)
4,21000010,1.610613e+09,MIL,Milwaukee,201601.0,Luc Mbah a Moute,NaN,DND - right ankle injury,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2010-10-27,2010-11,Bucks,Luc Mbah a Moute,sprained right ankle (DNP)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13331,41700144,1.610613e+09,MIN,Minnesota,1626145.0,Tyus Jones,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-04-23,2017-18,Timberwolves,Tyus Jones,sore right knee (DTD)
13332,41700211,1.610613e+09,BOS,Boston,1627759.0,Jaylen Brown,NaN,DND - Injury/Illness,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-04-30,2017-18,Celtics,Jaylen Brown,strained right hamstring (DTD)
13333,41700211,1.610613e+09,BOS,Boston,1627759.0,Jaylen Brown,NaN,DND - Injury/Illness,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-04-30,2017-18,Celtics,Jaylen Brown,strained right hamstring (DTD)
13334,41700215,1.610613e+09,BOS,Boston,203499.0,Shane Larkin,NaN,DND - Injury/Illness,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-05-09,2017-18,Celtics,Shane Larkin,sprained left shoulder (out for season)
13335,41700215,1.610613e+09,BOS,Boston,203499.0,Shane Larkin,NaN,DND - Injury/Illness,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,2018-05-09,2017-18,Celtics,Shane Larkin,sprained left shoulder (out for season)

In [48]:
df_merged = df_merged[df_merged.MIN != 0].drop_duplicates().reset_index(drop=True)
df_merged

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,player,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,game_date,season,Team,Relinquished,Notes
0,21000212,1.610613e+09,BOS,Boston,2753.0,Delonte West,NaN,NaN,11.916667,66.7,66.7,117.0,104.3,-50.3,-37.7,0.400,0.00,33.3,0.000,0.000,0.000,0.0,0.500,0.500,0.160,0.167,83.62,88.62,73.85,21.0,0.154,2010-11-24,2010-11,Celtics,Delonte West,broken right wrist (out indefinitely)
1,21000224,1.610613e+09,TOR,Toronto,2501.0,Reggie Evans,F,NaN,20.216667,82.8,78.6,129.5,130.0,-46.7,-51.4,0.000,0.00,0.0,0.130,0.273,0.176,16.7,0.667,0.673,0.122,0.128,94.97,97.35,81.12,42.0,0.094,2010-11-26,2010-11,Raptors,Reggie Evans,broken right foot (out indefinitely)
2,21000342,1.610613e+09,IND,Indiana,1902.0,Jeff Foster,NaN,NaN,3.483333,114.2,150.0,111.1,114.3,3.1,35.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.500,0.500,0.250,0.254,104.15,89.78,74.82,6.0,0.100,2010-12-11,2010-11,Pacers,Jeff Foster,placed on IL
3,21000342,1.610613e+09,ATL,Atlanta,2585.0,Zaza Pachulia,NaN,NaN,5.883333,107.8,110.0,108.7,127.3,-0.9,-17.3,0.333,1.00,50.0,0.200,0.167,0.182,50.0,0.000,0.000,0.083,0.082,94.15,85.67,71.39,10.0,0.057,2010-12-11,2010-11,Hawks,Zaza Pachulia,placed on IL with illness
4,21000345,1.610613e+09,CHI,Chicago,703.0,Kurt Thomas,NaN,NaN,3.333333,116.3,100.0,88.8,85.7,27.5,14.3,0.500,0.00,50.0,0.000,0.167,0.143,0.0,1.000,1.000,0.125,0.145,98.21,108.00,90.00,8.0,0.333,2010-12-11,2010-11,Bulls,Kurt Thomas,placed on IL
5,21000370,1.610613e+09,CHI,Chicago,201149.0,Joakim Noah,C,NaN,26.216667,124.7,129.2,81.7,78.0,43.0,51.2,0.000,0.00,0.0,0.143,0.258,0.212,20.0,0.667,0.709,0.175,0.173,89.24,89.71,74.76,48.0,0.169,2010-12-15,2010-11,Bulls,Joakim Noah,torn ligament in right thumb (out indefinitely)
6,21000578,1.610613e+09,TOR,Toronto,2571.0,Leandro Barbosa,NaN,NaN,9.466667,119.6,115.8,131.0,130.0,-11.5,-14.2,0.200,1.00,14.3,0.000,0.111,0.050,14.3,0.250,0.205,0.250,0.256,96.96,98.89,82.41,19.0,-0.087,2011-01-14,2010-11,Raptors,Leandro Barbosa,strained right hamstring (DTD)
7,21000580,1.610613e+09,NYK,New York,101142.0,Ronny Turiaf,C,NaN,15.933333,88.3,87.9,82.4,82.4,6.0,5.5,0.000,0.00,0.0,0.053,0.174,0.119,0.0,0.333,0.333,0.081,0.081,100.68,100.92,84.10,33.0,0.120,2011-01-14,2010-11,Knicks,Ronny Turiaf,right hip pointer (DTD)
8,21000581,1.610613e+09,SAS,San Antonio,2588.0,Matt Bonner,NaN,NaN,7.900000,133.2,123.5,75.6,76.5,57.7,47.1,0.000,0.00,0.0,0.000,0.182,0.111,0.0,1.500,1.500,0.105,0.113,100.13,103.29,86.08,17.0,0.262,2011-01-14,2010-11,Spurs,Matt Bonner,sore right knee (DTD)
9,21000629,1.610613e+09,DET,Detroit,101111.0,Charlie Villanueva,NaN,NaN,10.250000,95.7,89.5,90.1,94.1,5.6,-4.6,0.000,0.00,0.0,0.000,0.167,0.083,0.0,0.000,0.000,0.130,0.145,83.17,84.29,70.24,19.0,-0.087,2011-01-21,2010-11,Pistons,Charlie Villanueva,sprained left ankle (DTD)
10,21000630,1.610613e+09,TOR,Toronto,201595.0,Joey Dorsey,F,NaN,15.066667,68.7,67.9,108.1,111.1,-39.3,-43.3,0.000,0.00,0.0,0.050,0.294,0.162,0.0,0.000,0.000,0.065,0.065,88.27,87.63,73.03,28.0,0.026,2011-01-21,2010-11,Raptors,Joey Dorsey,sore right knee (DTD)
11,21000632,1.610613e+09,BOS,Boston,406.0,Shaquille O'Neal,C,NaN,6.316667,144.6,141.7,92.9,83.3,51.6,58.3,0.200,0.00,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.083,0.085,85.56,91.19,75.99,12.0,0.107,2011-01-21,2010-11,Celtics,Shaquille O'Neal,hip injury (DTD)
12,21000634,1.610613e+09,WAS,Washington,2550.0,Kirk Hinrich,NaN,NaN,12.883333,105.0,100.0,81.9,89.3,23.1,10.7,0.286,1.00,22.2,0.000,0.125,0.069,22.2,0.800,0.800,0.233,0.243,103.03,100.65,83.87,26.0,0.148,2011-01-21,2010-11,Wizards,Kirk Hinrich,sprained elbow (DTD)
13,21000646,1.610613e+09,SAS,San Antonio,201588.0,George Hill,NaN,NaN,19.416667,69.1,69.7,100.7,100.0,-31.6,-30.3,0.000,0.00,0.0,0.000,0.053,0.027,12.5,0.417,0.515,0.222,0.227,82.86,82.82,69.01,33.0,0.107,2011-01-22,2010-11,Spurs,George Hill,sprained right thumb (DNP)
14,21000646,1.610613e+09,NOH,New Orleans,2772.0,Trevor Ariza,F,NaN,25.933333,109.2,108.5,53.9,54.3,55.3,54.2,0.071,0.50,8.3,0.000,0.276,0.136,16.7,0.875,0.805,0.193,0.194,86.18,86.07,71.72,47.0,0.288,2011-01-22,2010-11,Hornets,Trevor Ariza,right knee tendinitis (DNP)
15,21000689,1.610613e+09,UTA,Utah,2246.0,Mehmet Okur,NaN,NaN,8.783333,137.5,128.6,134.1,140.0,3.4,-11.4,0.125,0.00,25.0,0.143,0.400,0.250,0.0,0.333,0.333,0.130,0.139,110.72,112.03,93.36,21.0,0.078,2011-01-28,2010-11,Jazz,Mehmet Okur,strained lower back (DTD)
16,21000736,1.610613e+09,MIN,Minnesota,201563.0,Michael Beasley,F,NaN,12.633333,101.2,103.4,133.0,139.3,-31.8,-35.8,0.100,1.00,11.1,0.083,0.000,0.045,11.1,0.286,0.286,0.229,0.238,112.01,108.28,90.24,29.0,-0.020,2011-02-04,2010-11,Timberwolves,Michael Beasley,left ankle injury (DTD)
17,21000747,1.610613e+09,POR,Portland,201967.0,Dante Cunningham,C,NaN,13.216667,109.0,108.0,121.2,115.4,-12.1,-7.4,0.000,0.00,0.0,0.077,0.100,0.087,0.0,0.429,0.429,0.250,0.252,89.92,92.61,77.18,25.0,0.061,2011-02-05,2010-11,Blazers,Dante Cunningham,facial injury (DNP)
18,21000757,1.610613e+09,BOS,Boston,2605.0,Marquis Daniels,NaN,NaN,3.716667,68.0,50.0,44.4,57.1,23.6,-7.1,0.000,0.00,0.0,0.000,0.143,0.111,0.0,0.000,0.000,0.000,0.000,96.09,96.86,80.72,8.0,0.667,2011-02-06,2010-11,Celtics,Marquis Daniels,bruised spinal cord (out indefinitely)
19,21000881,1.610613e+09,CLE,Cleveland,1712.0,Antawn Jamison,F,NaN,29.700000,86.1,86.2,104.0,107.0,-17.9,-20.8,0.000,0.00,0.0,0.000,0.138,0.068,16.7,0.500,0.538,0.281,0.286,94.27,92.91,77.42,58.0,0.093,2011-02-27,2010-11,Cavaliers,Antawn Jamison,broken left little finger (out indefinitely)
20,21001049,1.610613e+09,SAS,San Antonio,1495.0,Tim Duncan,F,NaN,4.216667,161.9,160.0,70.9,70.0,91.1,90.0,0.000,0.00,0.0,0.000,0.429,0.375,0.0,1.000,1.000,0.200,0.202,112.47,113.83,94.86,10.0,0.288,2011-03-21,2010-11,Spurs,Tim Duncan,sprained left ankle (out indefinitely)
21,21001061,1.610613e+09,UTA,Utah,1905.0,Andrei Kirilenko,F,NaN,13.700000,83.4,85.7,117.7,103.6,-34.2,-17.9,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.300,0.300,0.161,0.163,93.57,98.13,81.77,28.0,0.019,2011-03-23,2010-11,Jazz,Andrei Kirilenko,bruised left knee (DTD)
22,21001144,1.610613e+09,ORL,Orlando,201583.0,Ryan Anderson,NaN,NaN,19.083333,108.3,115.8,125.0,118.9,-16.7,-3.1,0.067,0.00,20.0,0.000,0.200,0.081,0.0,0.750,0.750,0.095,0.094,95.40,94.35,78.62,38.0,0.125,2011-04-03,2010-11,Magic,Ryan Anderson,placed on IL (out for season)
23,21001215,1.610613e+09,LAL,Los Angeles,101115.0,Andrew Bynum,C,NaN,13.066667,96.0,96.3,93.2,88.9,2.8,7.4,0.000,0.00,0.0,0.000,0.250,0.129,0.0,0.667,0.667,0.107,0.111,97.05,99.18,82.65,27.0,0.163,2011-04-12,2010-11,Lakers,Andrew Bynum,hyperextended right knee (left game)
24,21100001,1.610613e+09,NYK,New York,202697.0,Iman Shumpert,NaN,NaN,22.033333,92.4,93.8,119.8,119.6,-27.4,-25.8,0.077,0.50,5.6,0.045,0.167,0.100,11.1,0.231,0.362,0.309,0.322,103.06,102.37,85.31,48.0,0.020,2011-12-25,2011-12,Knicks,Iman Shumpert,sprained MCL in right knee (out indefinitely)
25,21100072,1.610613e+09,SAS,San Antonio,1938.0,Manu Ginobili,G,NaN,12.666667,135.7,126.9,153.5,152.0,-17.8,-25.1,0.200,0.00,25.0,0.000,0.286,0.105,0.0,0.583,0.621,0.207,0.220,92.99,96.63,80.53,26.0,0.122,2012-01-02,2011-12,Spurs,Manu Ginobili,broken bone in left hand (out indefinitely)
26,21100112,1.610613e+09,MIA,Miami,2544.0,LeBron James,F,NaN,37.383333,104.8,103.9,91.1,92.4,13.7,11.5,0.474,1.13,23.1,0.000,0.140,0.089,20.5,0.647,0.718,0.361,0.364,100.46,100.15,83.46,77.0,0.256,2012-01-07,2011-12,Heat,LeBron James,sprained left ankle (DNP)
27,21100589,1.610613e+09,MIN,Minnesota,201937.0,Ricky Rubio,G,NaN,38.983333,112.3,116.4,107.6,109.3,4.8,7.1,0.400,2.50,35.7,0.029,0.077,0.054,14.3,0.458,0.528,0.209,0.213,93.55,91.13,75.94,73.0,0.113,2012-03-09,2011-12,Timberwolves,Ricky Rubio,torn ACL in left knee (out for season)
28,21100600,1.610613e+09,MIN,Minnesota,201567.0,Kevin Love,F,NaN,41.216667,96.4,92.6,101.0,105.0,-4.6,-12.4,0.000,0.00,0.0,0.116,0.282,0.195,6.7,0.478,0.566,0.316,0.327,93.73,93.76,78.13,81.0,0.208,2012-03-10,2011-12,Timberwolves,Kevin Love,back spasms (DNP)
29,21100674,1.610613e+09,DEN,Denver,201568.0,Danilo Gallinari,F,NaN,22.950000,100.8,100.0,119.1,121.3,-18.4,-21.3,0.389,2.33,38.9,0.111,0.190,0.154,16.7,0.143,0.254,0.216,0.222,98.80,98.30,81.92,47.0,0.047,2012-03-19,2011-12,Nuggets,Danilo Gallinari,fractured right thumb (DTD)
30,21200152,1.610613e+09,SAS,San Antonio,1536.0,Stephen Jackson,F,NaN,10.650000,104.9,104.3,73.5,66.7,31.4,37.7,0.000,0.00,0.0,0.000,0.133,0.077,0.0,0.333,0.333,0.120,0.121,100.68,106.00,88.33,23.0,0.029,2012-11-19,2012-13,Spurs,Stephen Jackson,fractured right pinky finger (out indefinitely)
31,21200238,1.610613e+09,MIL,Milwaukee,202327.0,Ekpe Udoh,C,NaN,15.133333,66.2,66.7,112.6,109.4,-46.4,-42.7,0.000,0.00,0.0,0.000,0.111,0.042,20.0,0.667,0.644,0.167,0.166,97.18,98.33,81.94,30.0,0.018,2012-12-01,2012-13,Bucks,Ekpe Udoh,placed on IL
32,21200380,1.610613e+09,TOR,Toronto,202685.0,Jonas Valanciunas,C,NaN,4.483333,40.0,33.3,66.7,66.7,-26.7,-33.3,0.000,0.00,0.0,0.200,0.000,0.100,0.0,0.000,0.000,0.000,0.000,58.88,64.24,53.53,6.0,0.250,2012-12-21,2012-13,Raptors,Jonas Valanciunas,fractured right ring finger (out indefinitely)
33,21200673,1.610613e+09,ORL,Orlando,201175.0,Glen Davis,F,NaN,4.333333,175.0,175.0,112.5,100.0,62.5,75.0,0.600,0.00,60.0,0.000,0.000,0.000,0.0,0.500,0.500,0.250,0.250,88.62,94.15,78.46,8.0,0.131,2013-01-30,2012-13,Magic,Glen Davis,fractured left foot (out indefinitely)
34,21200781,1.610613e+09,WAS,Washington,202344.0,Trevor Booker,NaN,NaN,0.050000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,1.000,1.000,533.33,533.33,444.44,1.0,1.000,2013-02-13,2012-13,Wizards,Trevor Booker,sore left wrist (DNP)
35,21200799,1.610613e+09,CHA,Charlotte,2732.0,Ben Gordon,NaN,NaN,10.500000,123.4,121.1,126.4,127.8,-3.0,-6.7,0.167,0.00,12.5,0.000,0.111,0.048,0.0,0.357,0.357,0.280,0.296,84.18,84.54,70.45,19.0,0.026,2013-02-20,2012-13,Bobcats,Ben Gordon,sore right knee (DNP)
36,21200990,1.610613e+09,DAL,Dallas,201958.0,Rodrigue Beaubois,NaN,NaN,6.616667,97.0,100.0,110.2,114.3,-13.2,-14.3,0.000,0.00,0.0,0.000,0.000,0.000,75.0,0.000,0.000,0.286,0.277,105.04,101.56,84.63,14.0,-0.244,2013-03-17,2012-13,Mavericks,Rodrigue Beaubois,fractured left hand (out indefinitely)
37,21201068,1.610613e+09,UTA,Utah,202683.0,Enes Kanter,NaN,NaN,3.483333,140.0,140.0,83.3,83.3,56.7,56.7,0.000,0.00,0.0,0.000,0.333,0.200,50.0,0.000,0.000,0.333,0.333,75.79,75.79,63.16,5.0,-0.118,2013-03-27,2012-13,Jazz,Enes Kanter,dislocated left shoulder (out indefinitely)
38,21201189,1.610613e+09,LAL,Los Angeles,977.0,Kobe Bryant,G,NaN,44.900000,121.8,121.1,123.6,122.5,-1.8,-1.4,0.174,0.80,10.5,0.000,0.104,0.060,13.2,0.524,0.606,0.351,0.368,94.95,95.68,79.73,90.0,0.102,2013-04-12,2012-13,Lakers,Kobe Bryant,torn left Achilles tendon (out indefinitely)
39,21201209,1.610613e+09,SAC,Sacramento,201936.0,Tyreke Evans,G,NaN,10.000000,73.5,80.0,101.7,100.0,-28.2,-20.0,0.333,0.00,16.7,0.000,0.000,0.000,0.0,0.800,0.800,0.217,0.220,101.76,98.40,82.00,20.0,0.302,2013-04-15,2012-13,Kings,Tyreke Evans,sore left shoulder (DNP)
40,21300025,1.610613e+09,HOU,Houston,201956.0,Omri Casspi,NaN,NaN,21.233333,127.3,125.0,89.1,91.5,38.3,33.5,0.133,2.00,16.7,0.038,0.032,0.035,8.3,0.688,0.676,0.167,0.172,107.83,107.38,89.48,48.0,0.114,2013-11-01,2013-14,Rockets,Omri Casspi,sprained left ankle (DNP)
41,21300027,1.610613e+09,MIN,Minnesota,101142.0,Ronny Turiaf,NaN,NaN,3.116667,156.2,112.5,116.3,114.3,40.0,-1.8,0.333,0.00,100.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,97.33,115.51,96.26,8.0,0.000,2013-11-01,2013-14,Timberwolves,Ronny Turiaf,fractured right elbow (out indefinitely)
42,21300029,1.610613e+09,POR,Portland,201964.0,Victor Claver,NaN,NaN,1.366667,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,70.24,87.80,73.17,3.0,0.000,2013-11-01,2013-14,Blazers,Victor Claver,placed on IL
43,21300254,1.610613e+09,NOP,New Orleans,203076.0,Anthony Davis,F,NaN,10.450000,75.5,84.2,100.0,94.7,-24.5,-10.5,0.000,0.00,0.0,0.071,0.333,0.174,12.5,0.333,0.478,0.333,0.331,90.03,87.27,72.73,19.0,0.177,2013-12-01,2013-14,Pelicans,Anthony Davis,fractured left hand (out indefinitely)
44,21300361,1.610613e+09,NYK,New York,203143.0,Pablo Prigioni,G,NaN,18.333333,71.5,73.0,116.4,116.7,-44.9,-43.7,0.273,3.00,42.9,0.000,0.071,0.026,14.3,0.000,0.000,0.098,0.098,96.66,95.56,79.64,37.0,0.000,2013-12-16,2013-14,Knicks,Pablo Prigioni,fractured right toe (out indefinitely)
45,21300396,1.610613e+09,HOU,Houston,201976.0,Patrick Beverley,G,NaN,14.583333,117.2,118.2,98.8,97.0,18.4,21.2,0.182,2.00,18.2,0.000,0.214,0.111,9.1,0.500,0.644,0.243,0.248,108.09,108.62,90.51,33.0,0.161,2013-12-21,2013-14,Rockets,Patrick Beverley,fractured right hand (out indefinitely)
46,21300486,1.610613e+09,LAC,Los Angeles,101108.0,Chris Paul,G,NaN,21.816667,128.8,124.4,109.5,108.9,19.3,15.6,0.462,6.00,35.3,0.000,0.150,0.075,5.9,0.938,0.973,0.220,0.227,97.09,99.02,82.52,45.0,0.233,2014-01-03,2013-14,Clippers,Chris Paul,separated right shoulder (out indefinitely)
47,21300630,1.610613e+09,SAS,San Antonio,202695.0,Kawhi Leonard,F,NaN,15.083333,104.0,103.2,113.8,106.3,-9.8,-3.0,0.083,0.50,20.0,0.071,0.000,0.043,40.0,0.750,0.750,0.114,0.115,96.49,100.24,83.54,31.0,0.023,2014-01-22,2013-14,Spurs,Kawhi Leonard,fractured right hand (out indefinitely)
48,21300641,1.610613e+09,LAC,Los Angeles,2584.0,Willie Green,NaN,NaN,5.683333,100.0,90.0,88.9,88.9,11.1,1.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.667,0.667,0.300,0.333,76.01,80.23,66.86,10.0,0.171,2014-01-24,2013-14,Clippers,Willie Green,placed on IL (P)
49,21400003,1.610613e+09,LAL,Los Angeles,203944.0,Julius Randle,NaN,NaN,13.566667,58.3,60.0,132.4,126.9,-74.1,-66.9,0.000,0.00,0.0,0.000,0.000,0.000,20.0,0.333,0.258,0.172,0.174,89.58,90.22,75.18,25.0,-0.242,2014-10-28,2014-15,Lakers,Julius Randle,fractured tibia in right leg (out for season)
50,21400020,1.610613e+09,OKC,Oklahoma City,201566.0,Russell Westbrook,G,NaN,8.716667,84.0,90.0,113.4,110.5,-29.4,-20.5,0.500,1.33,40.0,0.000,0.000,0.000,30.0,0.333,0.333,0.261,0.256,110.02,107.38,89.48,20.0,0.000,2014-10-30,2014-15,Thunder,Russell Westbrook,fractured right hand (DTD)
51,21400271,1.610613e+09,UTA,Utah,203504.0,Trey Burke,G,NaN,33.900000,122.6,126.6,136.6,139.4,-14.0,-12.8,0.286,8.00,33.3,0.029,0.077,0.049,4.2,0.500,0.500,0.216,0.213,94.49,92.05,76.71,64.0,0.084,2014-12-03,2014-15,Jazz,Trey Burke,placed on IL
52,21400653,1.610613e+09,DET,Detroit,201943.0,Brandon Jennings,G,NaN,26.133333,86.5,87.3,103.3,105.7,-16.9,-18.4,0.308,0.80,16.7,0.030,0.042,0.035,20.8,0.464,0.508,0.303,0.305,100.76,99.18,82.65,55.0,0.073,2015-01-24,2014-15,Pistons,Brandon Jennings,torn left Achilles (out for season)
53,21400661,1.610613e+09,MIN,Minnesota,203133.0,Robbie Hummel,NaN,NaN,22.733333,115.0,111.4,127.6,136.4,-12.5,-25.0,0.077,1.00,11.1,0.000,0.211,0.095,11.1,0.583,0.654,0.154,0.158,94.63,92.90,77.42,44.0,0.090,2015-01-25,2014-15,Timberwolves,Robbie Hummel,fractured right hand (out indefinitely)
54,21400699,1.610613e+09,TOR,Toronto,101161.0,Amir Johnson,F,NaN,34.566667,130.2,129.0,107.1,105.8,23.1,23.2,0.000,0.00,0.0,0.143,0.071,0.100,13.3,0.909,0.940,0.195,0.196,94.79,95.81,79.85,69.0,0.150,2015-01-30,2014-15,Raptors,Amir Johnson,placed on IL
55,21500054,1.610613e+09,IND,Indiana,101133.0,Ian Mahinmi,C,NaN,5.483333,91.7,84.6,116.5,115.4,-24.8,-30.8,0.000,0.00,0.0,0.000,0.000,0.000,100.0,0.000,0.000,0.071,0.077,108.90,113.80,94.83,13.0,-0.085,2015-11-03,2015-16,Pacers,Ian Mahinmi,sore lower back (DTD)
56,21500064,1.610613e+09,ORL,Orlando,202696.0,Nikola Vucevic,C,NaN,16.750000,130.7,131.4,124.6,126.5,6.1,5.0,0.125,0.00,25.0,0.000,0.133,0.083,0.0,0.500,0.500,0.162,0.166,99.90,98.87,82.39,35.0,0.075,2015-11-04,2015-16,Magic,Nikola Vucevic,sprained right knee (DTD)
57,21500064,1.610613e+09,HOU,Houston,201976.0,Patrick Beverley,NaN,NaN,12.016667,115.6,120.0,106.4,111.1,9.2,8.9,0.000,0.00,0.0,0.000,0.143,0.083,0.0,0.375,0.375,0.143,0.138,108.17,103.86,86.55,25.0,0.019,2015-11-04,2015-16,Rockets,Patrick Beverley,concussion (DTD)
58,21500099,1.610613e+09,IND,Indiana,201155.0,Rodney Stuckey,NaN,NaN,17.816667,92.2,94.4,92.1,97.3,0.1,-2.9,0.364,0.00,33.3,0.000,0.105,0.053,0.0,0.375,0.375,0.205,0.201,102.32,98.33,81.95,36.0,0.129,2015-11-09,2015-16,Pacers,Rodney Stuckey,sore right ankle (DTD)
59,21500123,1.610613e+09,POR,Portland,203086.0,Meyers Leonard,F,NaN,23.933333,112.3,114.6,108.3,106.3,4.0,8.3,0.105,0.00,33.3,0.000,0.227,0.109,0.0,0.875,0.875,0.077,0.077,96.31,96.27,80.22,48.0,0.114,2015-11-11,2015-16,Blazers,Meyers Leonard,dislocated left shoulder (out indefinitely)
60,21500147,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,9.466667,140.8,138.9,111.9,111.1,28.9,27.8,0.000,0.00,0.0,0.143,0.000,0.071,0.0,0.500,0.500,0.100,0.101,90.35,91.27,76.06,18.0,0.060,2015-11-15,2015-16,Hornets,P.J. Hairston,placed on IL with bruised right quadricep
61,21500153,1.610613e+09,CHI,Chicago,201565.0,Derrick Rose,G,NaN,33.216667,93.0,94.1,83.3,84.3,9.7,9.8,0.400,0.00,23.1,0.024,0.022,0.023,0.0,0.556,0.582,0.260,0.260,100.89,99.71,83.09,68.0,0.179,2015-11-16,2015-16,Bulls,Derrick Rose,sprained left ankle (DTD)
62,21500176,1.610613e+09,CLE,Cleveland,202389.0,Timofey Mozgov,C,NaN,11.250000,166.0,165.0,97.0,100.0,69.0,65.0,0.000,0.00,0.0,0.000,0.000,0.000,33.3,0.500,0.500,0.143,0.144,88.58,87.47,72.89,20.0,-0.038,2015-11-19,2015-16,Cavaliers,Timofey Mozgov,strained right shoulder (DTD)
63,21500191,1.610613e+09,ATL,Atlanta,201168.0,Tiago Splitter,NaN,NaN,9.466667,68.4,68.4,117.4,110.5,-49.0,-42.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,1.000,1.000,0.105,0.105,93.50,96.34,80.28,19.0,0.086,2015-11-21,2015-16,Hawks,Tiago Splitter,sore right hip (DTD)
64,21500204,1.610613e+09,MIA,Miami,2736.0,Luol Deng,F,NaN,31.133333,94.7,94.9,97.4,100.0,-2.7,-5.1,0.000,0.00,0.0,0.028,0.061,0.043,10.0,0.500,0.500,0.145,0.145,92.32,90.96,75.80,59.0,0.060,2015-11-23,2015-16,Heat,Luol Deng,sore hamstring (DTD)
65,21500215,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,16.200000,100.8,94.1,109.9,109.1,-9.1,-15.0,0.182,2.00,25.0,0.000,0.143,0.077,12.5,0.375,0.512,0.154,0.163,95.59,99.26,82.72,34.0,0.045,2015-11-25,2015-16,Hornets,P.J. Hairston,placed on IL
66,21500282,1.610613e+09,SAC,Sacramento,1626161.0,Willie Cauley-Stein,F,NaN,17.666667,123.9,125.6,94.9,97.4,29.0,28.2,0.091,1.00,14.3,0.077,0.174,0.139,14.3,1.000,0.862,0.143,0.144,108.11,105.93,88.28,39.0,0.130,2015-12-03,2015-16,Kings,Willie Cauley-Stein,dislocated right index finger (out indefinitely)
67,21500372,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,21.950000,100.1,102.3,125.9,131.8,-25.8,-29.5,0.000,0.00,0.0,0.050,0.077,0.061,15.4,0.591,0.612,0.271,0.266,98.45,95.13,79.27,43.0,0.072,2015-12-16,2015-16,Hornets,P.J. Hairston,placed on IL
68,21500399,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,18.666667,86.0,89.5,109.1,107.3,-23.1,-17.8,0.250,2.00,20.0,0.115,0.176,0.140,10.0,0.667,0.727,0.170,0.168,102.65,101.57,84.64,38.0,0.160,2015-12-19,2015-16,Hornets,P.J. Hairston,placed on IL
69,21500414,1.610613e+09,CHI,Chicago,201149.0,Joakim Noah,NaN,NaN,15.933333,108.0,109.1,108.3,109.4,-0.2,-0.3,0.615,0.00,66.7,0.143,0.313,0.216,0.0,0.500,0.500,0.098,0.099,98.92,97.96,81.63,33.0,0.203,2015-12-21,2015-16,Bulls,Joakim Noah,sprained left shoulder (DTD)
70,21500421,1.610613e+09,DAL,Dallas,101114.0,Deron Williams,G,NaN,23.333333,82.4,86.7,111.4,104.3,-29.0,-17.7,0.462,0.00,42.9,0.000,0.095,0.042,0.0,0.286,0.421,0.170,0.169,92.98,93.60,78.00,45.0,0.123,2015-12-22,2015-16,Mavericks,Deron Williams,strained left hamstring (DTD)
71,21500451,1.610613e+09,PHX,Phoenix,202339.0,Eric Bledsoe,G,NaN,8.150000,47.1,47.1,83.9,83.3,-36.8,-36.3,0.000,0.00,0.0,0.000,0.286,0.118,33.3,0.500,0.500,0.353,0.353,102.71,103.07,85.89,17.0,0.000,2015-12-26,2015-16,Suns,Eric Bledsoe,sprained left knee (out for season)

In [49]:
df_merged[['game_date', 'player']]

     game_date               player
0   2010-11-24         Delonte West
1   2010-11-26         Reggie Evans
2   2010-12-11          Jeff Foster
3   2010-12-11        Zaza Pachulia
4   2010-12-11          Kurt Thomas
5   2010-12-15          Joakim Noah
6   2011-01-14      Leandro Barbosa
7   2011-01-14         Ronny Turiaf
8   2011-01-14          Matt Bonner
9   2011-01-21   Charlie Villanueva
10  2011-01-21          Joey Dorsey
11  2011-01-21     Shaquille O'Neal
12  2011-01-21         Kirk Hinrich
13  2011-01-22          George Hill
14  2011-01-22         Trevor Ariza
15  2011-01-28          Mehmet Okur
16  2011-02-04      Michael Beasley
17  2011-02-05     Dante Cunningham
18  2011-02-06      Marquis Daniels
19  2011-02-27       Antawn Jamison
20  2011-03-21           Tim Duncan
21  2011-03-23     Andrei Kirilenko
22  2011-04-03        Ryan Anderson
23  2011-04-12         Andrew Bynum
24  2011-12-25        Iman Shumpert
25  2012-01-02        Manu Ginobili
26  2012-01-07         LeBron James
27  2012-03-09          Ricky Rubio
28  2012-03-10           Kevin Love
29  2012-03-19     Danilo Gallinari
30  2012-11-19      Stephen Jackson
31  2012-12-01            Ekpe Udoh
32  2012-12-21    Jonas Valanciunas
33  2013-01-30           Glen Davis
34  2013-02-13        Trevor Booker
35  2013-02-20           Ben Gordon
36  2013-03-17    Rodrigue Beaubois
37  2013-03-27          Enes Kanter
38  2013-04-12          Kobe Bryant
39  2013-04-15         Tyreke Evans
40  2013-11-01          Omri Casspi
41  2013-11-01         Ronny Turiaf
42  2013-11-01        Victor Claver
43  2013-12-01        Anthony Davis
44  2013-12-16       Pablo Prigioni
45  2013-12-21     Patrick Beverley
46  2014-01-03           Chris Paul
47  2014-01-22        Kawhi Leonard
48  2014-01-24         Willie Green
49  2014-10-28        Julius Randle
50  2014-10-30    Russell Westbrook
51  2014-12-03           Trey Burke
52  2015-01-24     Brandon Jennings
53  2015-01-25        Robbie Hummel
54  2015-01-30         Amir Johnson
55  2015-11-03          Ian Mahinmi
56  2015-11-04       Nikola Vucevic
57  2015-11-04     Patrick Beverley
58  2015-11-09       Rodney Stuckey
59  2015-11-11       Meyers Leonard
60  2015-11-15          PJ Hairston
61  2015-11-16         Derrick Rose
62  2015-11-19       Timofey Mozgov
63  2015-11-21       Tiago Splitter
64  2015-11-23            Luol Deng
65  2015-11-25          PJ Hairston
66  2015-12-03  Willie Cauley-Stein
67  2015-12-16          PJ Hairston
68  2015-12-19          PJ Hairston
69  2015-12-21          Joakim Noah
70  2015-12-22       Deron Williams
71  2015-12-26         Eric Bledsoe
72  2016-01-01         Devin Harris
73  2016-01-02        Avery Bradley
74  2016-01-04          Mike Conley
75  2016-01-07          Rodney Hood
76  2016-01-08        Anthony Davis
77  2016-01-08     D'Angelo Russell
78  2016-01-09          Jeff Teague
79  2016-01-12       Rodney Stuckey
80  2016-01-15          Joakim Noah
81  2016-01-19          Eric Gordon
82  2016-01-20     Hassan Whiteside
83  2016-01-21          P.J. Tucker
84  2016-01-25        Anthony Davis
85  2016-01-27        Cameron Payne
86  2016-01-27           Jeremy Lin
87  2016-01-28         Paul Millsap
88  2016-01-30     DeMarcus Cousins
89  2016-02-01       Deron Williams
90  2016-02-03          PJ Hairston
91  2016-02-03        Jahlil Okafor
92  2016-02-05        Tobias Harris
93  2016-02-08           Marc Gasol
94  2016-02-29           Kevin Love
95  2016-02-29     Luc Mbah a Moute
96  2016-03-09       Mario Chalmers
97  2016-03-14          PJ Hairston
98  2016-03-17        E'Twaun Moore
99  2016-03-18    Patrick Patterson
100 2016-03-18     Chandler Parsons
101 2016-03-19           Jeff Green
102 2016-03-23        Kawhi Leonard
103 2016-03-24          Paul George
104 2016-03-30        Jose Calderon
105 2016-10-28       Rodney Stuckey
106 2016-10-29          Jeremy Lamb
107 2016-10-29      Greivis Vasquez
108 2016-11-02           Jeremy Lin
109 2016-11-02     Dante Cunningham
110 2016-11-02        Jarell Martin
111 2016-11-02          Jae Crowder
112 2016-11-02      Wesley Matthews
113 2016-11-04        Dirk Nowitzki
114 2016-11-09         Bradley Beal
115 2016-11-12         Lance Thomas
116 2016-11-12       Doug McDermott
117 2016-11-18          T.J. Warren
118 2016-11-18             CJ Miles
119 2016-11-18       Semaj Christon
120 2016-11-30         Courtney Lee
121 2016-12-02     Robert Covington
122 2016-12-05             JR Smith
123 2016-12-07         Jamal Murray
124 2016-12-07      Rodney McGruder
125 2016-12-12       Darrell Arthur
126 2016-12-21     Tim Hardaway Jr.
127 2016-12-28         Bradley Beal
128 2016-12-29    Patrick Patterson
129 2017-01-01          Aron Baynes
130 2017-01-02         JaVale McGee
131 2017-01-15         Mike Muscala
132 2017-01-16          Gary Harris
133 2017-01-18          Jodie Meeks
134 2017-01-18           David West
135 2017-01-18             Rudy Gay
136 2017-01-20          Joel Embiid
137 2017-01-20           J.J. Barea
138 2017-01-22        Dragan Bender
139 2017-01-22        DeMar DeRozan
140 2017-01-25       Deron Williams
141 2017-01-26          Enes Kanter
142 2017-02-01          Rodney Hood
143 2017-02-03          Zach LaVine
144 2017-02-07          Evan Turner
145 2017-02-08       Kenneth Faried
146 2017-02-08        Jabari Parker
147 2017-02-15        Manu Ginobili
148 2017-02-15          C.J. Watson
149 2017-02-23          Omri Casspi
150 2017-02-23   Kristaps Porzingis
151 2017-03-01       Thaddeus Young
152 2017-03-15      Nemanja Bjelica
153 2017-03-15     Lance Stephenson
154 2017-03-15          Dwyane Wade
155 2017-03-18       Wesley Johnson
156 2017-03-20      Markieff Morris
157 2017-03-31           Seth Curry
158 2017-10-17       Gordon Hayward
159 2017-10-18           Jeremy Lin
160 2017-10-20         Derrick Rose
161 2017-10-21    Jonas Valanciunas
162 2017-10-30          Okaro White
163 2017-11-04          David Nwaba
164 2017-11-19         Paul Millsap
165 2017-11-26        Trevor Booker
166 2017-11-29   Kristaps Porzingis
167 2017-11-29       Lucas Nogueira
168 2017-11-30         Nikola Jokic
169 2017-12-02  Willie Cauley-Stein
170 2017-12-02       JaKarr Sampson
171 2017-12-15         Tyreke Evans
172 2017-12-21           Marc Gasol
173 2017-12-23       Nikola Vucevic
174 2017-12-30          Noah Vonleh
175 2018-01-07      Marquese Chriss
176 2018-01-26     DeMarcus Cousins
177 2018-01-27       Andre Roberson
178 2018-01-30           Kevin Love
179 2018-01-31        Isaiah Canaan
180 2018-02-06   Kristaps Porzingis
181 2018-02-07         Derrick Rose
182 2018-03-02          Jason Smith
183 2018-03-08           Davon Reed
184 2018-03-09        Mason Plumlee
185 2018-03-17         Devin Harris
186 2018-03-23         John Collins
187 2018-04-10         Ike Anigbogu
188 2018-04-10     Luc Mbah a Moute
189 2012-04-28         Derrick Rose
190 2012-04-28        Iman Shumpert
191 2012-04-30    Amar'e Stoudemire
192 2012-05-06          Baron Davis
193 2012-04-29         Caron Butler
194 2013-04-20         Willie Green
195 2014-04-19          Jeff Teague
196 2015-05-08          Joakim Noah
197 2015-05-08          Matt Barnes
198 2016-04-20        Nicolas Batum
199 2016-04-16        Stephen Curry
200 2016-04-25           Chris Paul
201 2016-05-07    Jonas Valanciunas
202 2016-05-07     Hassan Whiteside
203 2016-06-05           Kevin Love
204 2017-04-15  Matthew Dellavedova
205 2017-04-23       Gordon Hayward
206 2017-05-14        Kawhi Leonard
207 2017-05-14       Andre Iguodala
208 2018-04-20       Thaddeus Young

In [50]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '9inj_bsa_nzm_209.csv')
if not os.path.exists(datapath_df):
    df_merged.to_csv(datapath_df, index=False)

In [29]:
df_tist1018 = pd.read_csv(os.path.join('..', 'processed_data', '10team_id_season_team_2010_2018.csv'))
df_tist1018

        TEAM_ID   season          Team
0    1610612748  2010-11          Heat
1    1610612749  2010-11         Bucks
2    1610612765  2010-11       Pistons
3    1610612753  2010-11         Magic
4    1610612737  2010-11         Hawks
5    1610612743  2010-11       Nuggets
6    1610612762  2010-11          Jazz
7    1610612744  2010-11      Warriors
8    1610612757  2010-11       Blazers
9    1610612764  2010-11       Wizards
10   1610612746  2010-11      Clippers
11   1610612750  2010-11  Timberwolves
12   1610612738  2010-11       Celtics
13   1610612761  2010-11       Raptors
14   1610612745  2010-11       Rockets
15   1610612752  2010-11        Knicks
16   1610612756  2010-11          Suns
17   1610612740  2010-11       Hornets
18   1610612741  2010-11         Bulls
19   1610612747  2010-11        Lakers
20   1610612760  2010-11       Thunder
21   1610612754  2010-11        Pacers
22   1610612739  2010-11     Cavaliers
23   1610612758  2010-11         Kings
24   1610612751  2010-11          Nets
25   1610612759  2010-11         Spurs
26   1610612755  2010-11         76ers
27   1610612742  2010-11     Mavericks
28   1610612763  2010-11     Grizzlies
29   1610612766  2010-11       Bobcats
30   1610612752  2011-12        Knicks
31   1610612746  2011-12      Clippers
32   1610612766  2011-12       Bobcats
33   1610612749  2011-12         Bucks
34   1610612750  2011-12  Timberwolves
35   1610612755  2011-12         76ers
36   1610612747  2011-12        Lakers
37   1610612738  2011-12       Celtics
38   1610612740  2011-12       Hornets
39   1610612737  2011-12         Hawks
40   1610612763  2011-12     Grizzlies
41   1610612762  2011-12          Jazz
42   1610612761  2011-12       Raptors
43   1610612741  2011-12         Bulls
44   1610612748  2011-12          Heat
45   1610612759  2011-12         Spurs
46   1610612751  2011-12          Nets
47   1610612758  2011-12         Kings
48   1610612765  2011-12       Pistons
49   1610612754  2011-12        Pacers
50   1610612745  2011-12       Rockets
51   1610612743  2011-12       Nuggets
52   1610612742  2011-12     Mavericks
53   1610612764  2011-12       Wizards
54   1610612744  2011-12      Warriors
55   1610612757  2011-12       Blazers
56   1610612756  2011-12          Suns
57   1610612760  2011-12       Thunder
58   1610612739  2011-12     Cavaliers
59   1610612753  2011-12         Magic
60   1610612738  2012-13       Celtics
61   1610612742  2012-13     Mavericks
62   1610612755  2012-13         76ers
63   1610612743  2012-13       Nuggets
64   1610612758  2012-13         Kings
65   1610612744  2012-13      Warriors
66   1610612752  2012-13        Knicks
67   1610612753  2012-13         Magic
68   1610612740  2012-13       Hornets
69   1610612737  2012-13         Hawks
70   1610612756  2012-13          Suns
71   1610612747  2012-13        Lakers
72   1610612750  2012-13  Timberwolves
73   1610612762  2012-13          Jazz
74   1610612759  2012-13         Spurs
75   1610612745  2012-13       Rockets
76   1610612739  2012-13     Cavaliers
77   1610612748  2012-13          Heat
78   1610612746  2012-13      Clippers
79   1610612766  2012-13       Bobcats
80   1610612757  2012-13       Blazers
81   1610612764  2012-13       Wizards
82   1610612763  2012-13     Grizzlies
83   1610612761  2012-13       Raptors
84   1610612765  2012-13       Pistons
85   1610612749  2012-13         Bucks
86   1610612754  2012-13        Pacers
87   1610612741  2012-13         Bulls
88   1610612760  2012-13       Thunder
89   1610612751  2012-13          Nets
90   1610612753  2013-14         Magic
91   1610612755  2013-14         76ers
92   1610612749  2013-14         Bucks
93   1610612752  2013-14        Knicks
94   1610612766  2013-14       Bobcats
95   1610612745  2013-14       Rockets
96   1610612762  2013-14          Jazz
97   1610612747  2013-14        Lakers
98   1610612744  2013-14      Warriors
99   1610612764  2013-14       Wizards
100  1610612761  2013-14       Raptors
101  1610612750  2013-14  Timberwolves
102  1610612757  2013-14       Blazers
103  1610612759  2013-14         Spurs
104  1610612756  2013-14          Suns
105  1610612754  2013-14        Pacers
106  1610612743  2013-14       Nuggets
107  1610612746  2013-14      Clippers
108  1610612763  2013-14     Grizzlies
109  1610612742  2013-14     Mavericks
110  1610612738  2013-14       Celtics
111  1610612740  2013-14      Pelicans
112  1610612741  2013-14         Bulls
113  1610612748  2013-14          Heat
114  1610612751  2013-14          Nets
115  1610612758  2013-14         Kings
116  1610612765  2013-14       Pistons
117  1610612739  2013-14     Cavaliers
118  1610612737  2013-14         Hawks
119  1610612760  2013-14       Thunder
120  1610612747  2014-15        Lakers
121  1610612755  2014-15         76ers
122  1610612754  2014-15        Pacers
123  1610612748  2014-15          Heat
124  1610612764  2014-15       Wizards
125  1610612750  2014-15  Timberwolves
126  1610612760  2014-15       Thunder
127  1610612758  2014-15         Kings
128  1610612741  2014-15         Bulls
129  1610612746  2014-15      Clippers
130  1610612740  2014-15      Pelicans
131  1610612765  2014-15       Pistons
132  1610612759  2014-15         Spurs
133  1610612752  2014-15        Knicks
134  1610612745  2014-15       Rockets
135  1610612753  2014-15         Magic
136  1610612744  2014-15      Warriors
137  1610612749  2014-15         Bucks
138  1610612766  2014-15       Hornets
139  1610612763  2014-15     Grizzlies
140  1610612743  2014-15       Nuggets
141  1610612742  2014-15     Mavericks
142  1610612762  2014-15          Jazz
143  1610612751  2014-15          Nets
144  1610612739  2014-15     Cavaliers
145  1610612737  2014-15         Hawks
146  1610612761  2014-15       Raptors
147  1610612738  2014-15       Celtics
148  1610612757  2014-15       Blazers
149  1610612756  2014-15          Suns
150  1610612740  2015-16      Pelicans
151  1610612755  2015-16         76ers
152  1610612766  2015-16       Hornets
153  1610612754  2015-16        Pacers
154  1610612760  2015-16       Thunder
155  1610612742  2015-16     Mavericks
156  1610612749  2015-16         Bucks
157  1610612745  2015-16       Rockets
158  1610612737  2015-16         Hawks
159  1610612743  2015-16       Nuggets
160  1610612747  2015-16        Lakers
161  1610612753  2015-16         Magic
162  1610612764  2015-16       Wizards
163  1610612758  2015-16         Kings
164  1610612746  2015-16      Clippers
165  1610612739  2015-16     Cavaliers
166  1610612741  2015-16         Bulls
167  1610612763  2015-16     Grizzlies
168  1610612750  2015-16  Timberwolves
169  1610612757  2015-16       Blazers
170  1610612762  2015-16          Jazz
171  1610612756  2015-16          Suns
172  1610612744  2015-16      Warriors
173  1610612761  2015-16       Raptors
174  1610612752  2015-16        Knicks
175  1610612751  2015-16          Nets
176  1610612748  2015-16          Heat
177  1610612765  2015-16       Pistons
178  1610612738  2015-16       Celtics
179  1610612759  2015-16         Spurs
180  1610612754  2016-17        Pacers
181  1610612761  2016-17       Raptors
182  1610612763  2016-17     Grizzlies
183  1610612757  2016-17       Blazers
184  1610612766  2016-17       Hornets
185  1610612751  2016-17          Nets
186  1610612759  2016-17         Spurs
187  1610612742  2016-17     Mavericks
188  1610612762  2016-17          Jazz
189  1610612755  2016-17         76ers
190  1610612740  2016-17      Pelicans
191  1610612738  2016-17       Celtics
192  1610612758  2016-17         Kings
193  1610612765  2016-17       Pistons
194  1610612743  2016-17       Nuggets
195  1610612764  2016-17       Wizards
196  1610612752  2016-17        Knicks
197  1610612741  2016-17         Bulls
198  1610612750  2016-17  Timberwolves
199  1610612748  2016-17          Heat
200  1610612739  2016-17     Cavaliers
201  1610612737  2016-17         Hawks
202  1610612756  2016-17          Suns
203  1610612760  2016-17       Thunder
204  1610612745  2016-17       Rockets
205  1610612747  2016-17        Lakers
206  1610612744  2016-17      Warriors
207  1610612746  2016-17      Clippers
208  1610612749  2016-17         Bucks
209  1610612753  2016-17         Magic
210  1610612738  2017-18       Celtics
211  1610612751  2017-18          Nets
212  1610612754  2017-18        Pacers
213  1610612755  2017-18         76ers
214  1610612757  2017-18       Blazers
215  1610612745  2017-18       Rockets
216  1610612766  2017-18       Hornets
217  1610612739  2017-18     Cavaliers
218  1610612761  2017-18       Raptors
219  1610612737  2017-18         Hawks
220  1610612750  2017-18  Timberwolves
221  1610612763  2017-18     Grizzlies
222  1610612741  2017-18         Bulls
223  1610612742  2017-18     Mavericks
224  1610612740  2017-18      Pelicans
225  1610612759  2017-18         Spurs
226  1610612748  2017-18          Heat
227  1610612747  2017-18        Lakers
228  1610612756  2017-18          Suns
229  1610612753  2017-18         Magic
230  1610612762  2017-18          Jazz
231  1610612760  2017-18       Thunder
232  1610612764  2017-18       Wizards
233  1610612743  2017-18       Nuggets
234  1610612749  2017-18         Bucks
235  1610612752  2017-18        Knicks
236  1610612758  2017-18         Kings
237  1610612744  2017-18      Warriors
238  1610612765  2017-18       Pistons
239  1610612746  2017-18      Clippers

In [30]:
df_inj1018r = pd.merge(df_inj1018r, df_tist1018, on=['Team', 'season'], how='outer', indicator=True)
print(df_inj1018r.shape)
p(df_inj1018r)

(14448, 8)

,game_date,season,Team,Relinquished,Notes,player,TEAM_ID,_merge
0,2010-10-26,2010-11,Blazers,Elliot Williams,placed on IL,Elliot Williams,1610612757,both
1,2010-10-26,2010-11,Blazers,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden,1610612757,both
2,2010-10-26,2010-11,Blazers,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla,1610612757,both
3,2010-11-02,2010-11,Blazers,Patty Mills,placed on IL,Patty Mills,1610612757,both
4,2010-11-04,2010-11,Blazers,Elliot Williams,"dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,both
14443,2018-03-13,2017-18,Thunder,Steven Adams,placed on IL with bruised left hip,Steven Adams,1610612760,both
14444,2018-03-16,2017-18,Thunder,Daniel Hamilton,placed on IL,Daniel Hamilton,1610612760,both
14445,2018-04-10,2017-18,Thunder,Alex Abrines,concussion (DTD),Alex Abrines,1610612760,both
14446,2018-04-11,2017-18,Thunder,Alex Abrines,placed on IL with concussion,Alex Abrines,1610612760,both
14447,2018-05-09,2017-18,Thunder,Paul George,arthroscopic surgery on right knee (out indefinitely),Paul George,1610612760,both

In [31]:
df_inj1018r.value_counts('_merge')

_merge
both          14448
right_only        0
left_only         0
dtype: int64

In [32]:
df_inj1018r.drop(columns=['_merge'], inplace=True)
print(df_inj1018r.shape)
p(df_inj1018r)

(14448, 7)

,game_date,season,Team,Relinquished,Notes,player,TEAM_ID
0,2010-10-26,2010-11,Blazers,Elliot Williams,placed on IL,Elliot Williams,1610612757
1,2010-10-26,2010-11,Blazers,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden,1610612757
2,2010-10-26,2010-11,Blazers,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla,1610612757
3,2010-11-02,2010-11,Blazers,Patty Mills,placed on IL,Patty Mills,1610612757
4,2010-11-04,2010-11,Blazers,Elliot Williams,"dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757
14443,2018-03-13,2017-18,Thunder,Steven Adams,placed on IL with bruised left hip,Steven Adams,1610612760
14444,2018-03-16,2017-18,Thunder,Daniel Hamilton,placed on IL,Daniel Hamilton,1610612760
14445,2018-04-10,2017-18,Thunder,Alex Abrines,concussion (DTD),Alex Abrines,1610612760
14446,2018-04-11,2017-18,Thunder,Alex Abrines,placed on IL with concussion,Alex Abrines,1610612760
14447,2018-05-09,2017-18,Thunder,Paul George,arthroscopic surgery on right knee (out indefinitely),Paul George,1610612760

In [33]:
#add player_id

df_piptist1018 = pd.read_csv(os.path.join('..', 'processed_data', '14player_id_player_team_id_season_team_2010_2018.csv'))
print(df_piptist1018.shape)
p(df_piptist1018)

(3763, 5)

      PLAYER_ID       PLAYER_NAME     team_id   season     Team
0      201623.0       Semih Erden  1610612738  2010-11  Celtics
1      101144.0         Von Wafer  1610612738  2010-11  Celtics
2        2753.0      Delonte West  1610612738  2010-11  Celtics
3      202376.0    Luke Harangody  1610612738  2010-11  Celtics
4         406.0  Shaquille O'Neal  1610612738  2010-11  Celtics
3758   202695.0     Kawhi Leonard  1610612759  2017-18    Spurs
3759     2200.0         Pau Gasol  1610612759  2017-18    Spurs
3760  1626199.0   Darrun Hilliard  1610612759  2017-18    Spurs
3761  1627749.0   Dejounte Murray  1610612759  2017-18    Spurs
3762  1627854.0       Bryn Forbes  1610612759  2017-18    Spurs

In [34]:
df_injury_piptist1018 = pd.merge(df_inj1018r.rename(columns={'TEAM_ID':'team_id'}), df_piptist1018.rename(columns={'PLAYER_NAME':'player'}), on=['player', 'Team', 'team_id', 'season'])
print(df_injury_piptist1018.shape)
p(df_injury_piptist1018)

(13667, 8)

,game_date,season,Team,Relinquished,Notes,player,team_id,PLAYER_ID
0,2010-10-26,2010-11,Blazers,Elliot Williams,placed on IL,Elliot Williams,1610612757,202343.0
1,2010-11-04,2010-11,Blazers,Elliot Williams,"dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0
2,2010-11-06,2010-11,Blazers,Elliot Williams,"placed on IL with dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0
3,2010-10-26,2010-11,Blazers,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden,1610612757,201141.0
4,2010-11-19,2010-11,Blazers,Greg Oden,mircofracture surgery on left knee (out for season),Greg Oden,1610612757,201141.0
13662,2018-01-03,2017-18,Thunder,Alex Abrines,placed on IL with strained right groin,Alex Abrines,1610612760,203518.0
13663,2018-04-10,2017-18,Thunder,Alex Abrines,concussion (DTD),Alex Abrines,1610612760,203518.0
13664,2018-04-11,2017-18,Thunder,Alex Abrines,placed on IL with concussion,Alex Abrines,1610612760,203518.0
13665,2018-03-09,2017-18,Thunder,Terrance Ferguson,concussion (out indefinitely),Terrance Ferguson,1610612760,1628390.0
13666,2018-03-10,2017-18,Thunder,Terrance Ferguson,placed on IL with concussion,Terrance Ferguson,1610612760,1628390.0

In [35]:
#filter game_date with team_id
df_gdtigi0618 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])[['game_date', 'team_id', 'game_id']]
print(df_gdtigi0618.shape)
p(df_gdtigi0618)

(31038, 3)

       game_date     team_id   game_id
0     2006-10-31  1610612748  20600001
1     2006-10-31  1610612741  20600001
2     2006-10-31  1610612747  20600002
3     2006-10-31  1610612756  20600002
4     2006-11-01  1610612755  20600003
31033 2018-06-03  1610612744  41700402
31034 2018-06-06  1610612744  41700403
31035 2018-06-06  1610612739  41700403
31036 2018-06-08  1610612739  41700404
31037 2018-06-08  1610612744  41700404

In [36]:
df_gdtigi0618.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31038 entries, 0 to 31037
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_date  31038 non-null  datetime64[ns]
 1   team_id    31038 non-null  int64
 2   game_id    31038 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 727.6 KB

In [37]:
df_injury_piptist1018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13667 entries, 0 to 13666
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_date     13667 non-null  datetime64[ns]
 1   season        13667 non-null  object
 2   Team          13667 non-null  object
 3   Relinquished  13667 non-null  object
 4   Notes         13667 non-null  object
 5   player        13667 non-null  object
 6   team_id       13667 non-null  int64
 7   PLAYER_ID     13667 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 961.0+ KB

In [38]:
df_inj_gitipi1018 = pd.merge(df_injury_piptist1018, df_gdtigi0618, on=['game_date', 'team_id'], how='inner', indicator=True)
#df_inj_gitipi1018 = df_inj_gitipi1018[['game_date', 'game_id', 'Team', 'team_id',  'season', 'player','PLAYER_ID', 'Relinquished', 'Notes']]#rearrange and drop columns
print(df_inj_gitipi1018.shape)
p(df_inj_gitipi1018)

(13034, 10)

,game_date,season,Team,Relinquished,Notes,player,team_id,PLAYER_ID,game_id,_merge
0,2010-10-26,2010-11,Blazers,Elliot Williams,placed on IL,Elliot Williams,1610612757,202343.0,21000002,both
1,2010-10-26,2010-11,Blazers,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden,1610612757,201141.0,21000002,both
2,2010-10-26,2010-11,Blazers,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla,1610612757,2038.0,21000002,both
3,2010-11-04,2010-11,Blazers,Elliot Williams,"dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0,21000067,both
4,2010-11-06,2010-11,Blazers,Elliot Williams,"placed on IL with dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0,21000087,both
13029,2018-03-03,2017-18,Thunder,Carmelo Anthony,placed on IL for rest,Carmelo Anthony,1610612760,2546.0,21700941,both
13030,2017-12-03,2017-18,Thunder,Dakari Johnson,placed on IL,Dakari Johnson,1610612760,1626177.0,21700337,both
13031,2018-01-03,2017-18,Thunder,Alex Abrines,placed on IL with strained right groin,Alex Abrines,1610612760,203518.0,21700565,both
13032,2018-04-11,2017-18,Thunder,Alex Abrines,placed on IL with concussion,Alex Abrines,1610612760,203518.0,21701227,both
13033,2018-03-10,2017-18,Thunder,Terrance Ferguson,placed on IL with concussion,Terrance Ferguson,1610612760,1628390.0,21700990,both

In [39]:
df_inj_gitipi1018.value_counts('_merge')

_merge
both          13034
right_only        0
left_only         0
dtype: int64

In [40]:
df_inj_gitipi1018.drop(columns='_merge', inplace=True)

In [41]:
print(df_inj_gitipi1018.shape)
p(df_inj_gitipi1018)

(13034, 9)

,game_date,season,Team,Relinquished,Notes,player,team_id,PLAYER_ID,game_id
0,2010-10-26,2010-11,Blazers,Elliot Williams,placed on IL,Elliot Williams,1610612757,202343.0,21000002
1,2010-10-26,2010-11,Blazers,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden,1610612757,201141.0,21000002
2,2010-10-26,2010-11,Blazers,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla,1610612757,2038.0,21000002
3,2010-11-04,2010-11,Blazers,Elliot Williams,"dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0,21000067
4,2010-11-06,2010-11,Blazers,Elliot Williams,"placed on IL with dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0,21000087
13029,2018-03-03,2017-18,Thunder,Carmelo Anthony,placed on IL for rest,Carmelo Anthony,1610612760,2546.0,21700941
13030,2017-12-03,2017-18,Thunder,Dakari Johnson,placed on IL,Dakari Johnson,1610612760,1626177.0,21700337
13031,2018-01-03,2017-18,Thunder,Alex Abrines,placed on IL with strained right groin,Alex Abrines,1610612760,203518.0,21700565
13032,2018-04-11,2017-18,Thunder,Alex Abrines,placed on IL with concussion,Alex Abrines,1610612760,203518.0,21701227
13033,2018-03-10,2017-18,Thunder,Terrance Ferguson,placed on IL with concussion,Terrance Ferguson,1610612760,1628390.0,21700990

In [42]:
#game_date's dropped by merge on game_date and team_id
print(df_injury_piptist1018.shape[0])
print(df_inj_gitipi1018.shape[0])
print('rows dropped: '+ str(df_injury_piptist1018.shape[0] - df_inj_gitipi1018.shape[0]))
print('percentage dropped: '+ str("{:.2f}".format(((df_injury_piptist1018.shape[0] - df_inj_gitipi1018.shape[0]) / df_injury_piptist1018.shape[0]) * 100)) + '%')

13667
13034
rows dropped: 633
percentage dropped: 4.63%

In [43]:
df_inj_gitipi1018.columns

Index(['game_date', 'season', 'Team', 'Relinquished', 'Notes', 'player',
       'team_id', 'PLAYER_ID', 'game_id'],
      dtype='object')

In [44]:
df_inj_gdgitistpip1018 = df_inj_gitipi1018[['game_date', 'game_id', 'team_id', 'season', 'Team',  'PLAYER_ID', 'player']]
print(df_inj_gdgitistpip1018.shape)
p(df_inj_gdgitistpip1018)

(13034, 7)

,game_date,game_id,team_id,season,Team,PLAYER_ID,player
0,2010-10-26,21000002,1610612757,2010-11,Blazers,202343.0,Elliot Williams
1,2010-10-26,21000002,1610612757,2010-11,Blazers,201141.0,Greg Oden
2,2010-10-26,21000002,1610612757,2010-11,Blazers,2038.0,Joel Przybilla
3,2010-11-04,21000067,1610612757,2010-11,Blazers,202343.0,Elliot Williams
4,2010-11-06,21000087,1610612757,2010-11,Blazers,202343.0,Elliot Williams
13029,2018-03-03,21700941,1610612760,2017-18,Thunder,2546.0,Carmelo Anthony
13030,2017-12-03,21700337,1610612760,2017-18,Thunder,1626177.0,Dakari Johnson
13031,2018-01-03,21700565,1610612760,2017-18,Thunder,203518.0,Alex Abrines
13032,2018-04-11,21701227,1610612760,2017-18,Thunder,203518.0,Alex Abrines
13033,2018-03-10,21700990,1610612760,2017-18,Thunder,1628390.0,Terrance Ferguson

In [45]:
df_inj_gdgitistpip1018

,game_date,game_id,team_id,season,Team,PLAYER_ID,player
0,2010-10-26,21000002,1610612757,2010-11,Blazers,202343.0,Elliot Williams
1,2010-10-26,21000002,1610612757,2010-11,Blazers,201141.0,Greg Oden
2,2010-10-26,21000002,1610612757,2010-11,Blazers,2038.0,Joel Przybilla
3,2010-11-04,21000067,1610612757,2010-11,Blazers,202343.0,Elliot Williams
4,2010-11-06,21000087,1610612757,2010-11,Blazers,202343.0,Elliot Williams
...,...,...,...,...,...,...,...
13029,2018-03-03,21700941,1610612760,2017-18,Thunder,2546.0,Carmelo Anthony
13030,2017-12-03,21700337,1610612760,2017-18,Thunder,1626177.0,Dakari Johnson
13031,2018-01-03,21700565,1610612760,2017-18,Thunder,203518.0,Alex Abrines
13032,2018-04-11,21701227,1610612760,2017-18,Thunder,203518.0,Alex Abrines
13033,2018-03-10,21700990,1610612760,2017-18,Thunder,1628390.0,Terrance Ferguson

In [46]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 'A9injury_game_id_team_id_player_id_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_inj_gdgitistpip1018.to_csv(datapath_df, index=False)

In [47]:
df = pd.read_csv(os.path.join('..', 'processed_data', 'A9injury_game_id_team_id_player_id_2010_2018.csv'))
print(df.shape)
p(df)

(13034, 9)

,game_date,season,Team,Relinquished,Notes,player,team_id,PLAYER_ID,game_id
0,2010-10-26,2010-11,Blazers,Elliot Williams,placed on IL,Elliot Williams,1610612757,202343.0,21000002
1,2010-10-26,2010-11,Blazers,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden,1610612757,201141.0,21000002
2,2010-10-26,2010-11,Blazers,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla,1610612757,2038.0,21000002
3,2010-11-04,2010-11,Blazers,Elliot Williams,"dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0,21000067
4,2010-11-06,2010-11,Blazers,Elliot Williams,"placed on IL with dislocated patella in right knee (surgery, out for season)",Elliot Williams,1610612757,202343.0,21000087
13029,2018-03-03,2017-18,Thunder,Carmelo Anthony,placed on IL for rest,Carmelo Anthony,1610612760,2546.0,21700941
13030,2017-12-03,2017-18,Thunder,Dakari Johnson,placed on IL,Dakari Johnson,1610612760,1626177.0,21700337
13031,2018-01-03,2017-18,Thunder,Alex Abrines,placed on IL with strained right groin,Alex Abrines,1610612760,203518.0,21700565
13032,2018-04-11,2017-18,Thunder,Alex Abrines,placed on IL with concussion,Alex Abrines,1610612760,203518.0,21701227
13033,2018-03-10,2017-18,Thunder,Terrance Ferguson,placed on IL with concussion,Terrance Ferguson,1610612760,1628390.0,21700990