In [1]:
#get team boxscores advance and team boxscore for the 2010-11 thru 2017-18 seasons

#merge 'df_tbsa1018' and 'df_tbs1018'

#drop duplicate columns

###########################################################//////////////////////////

#check for equality between team_id_away and TEAM_ID_away

#check for equality between team_id_home and TEAM_ID_home

#drop TEAM_ID_away if equal to team_id_away

#drop TEAM_ID_home if equal to team_id_home


################################################///////////////////////////////////////

In [2]:
#data definition...

#data types

#####################///////////////////////

#description of the columns

#counts of the columns

#ranges of values of the columns

#get mean, median, standard deviation, and range if not done already


###########################################//////////////////////////

#percentage unique values of the columns

######################################///////////////////////////////////////

#get mode and number of unique value if not done already

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import numpy as np


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [5]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [6]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [7]:
df_tbsa1018 = rcp('20boxscoreadvancedv2_team_away_home_2010_2018.csv')
p(df_tbsa1018)

(10266, 62)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0
3,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612745,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612744,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0
4,21000014,2010-10-27,Jazz,UTA,Utah,240:00,0 days 04:00:00,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612762,88.1,86.3,107.8,108.9,-19.7,-22.6,0.778,0.95,15.9,0.260,0.740,0.500,22.018,21.6,0.407,0.495,1.0,0.202,100.98,101.50,84.58,102,0.371,240.0,1610612743,107.8,108.9,88.1,86.3,19.7,22.6,0.657,1.44,16.8,0.260,0.740,0.500,15.680,15.8,0.475,0.561,1.0,0.198,100.98,101.50,84.58,101,0.629,240.0
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0

In [8]:
df_tbs1018 = rcp('18game_id_team_id_home_away_2010_2018.csv')
p(df_tbs1018)

(10267, 49)

,game_id,game_date,team_id_away,wl_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year
0,21000002,2010-10-26,1610612756,L,0.000,240,36,74,0.486,9,19,0.474,11,16,1.0,7,23,30,15,3,4,19,19,92,W,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,1.0,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010
1,21000001,2010-10-26,1610612748,L,0.000,240,27,74,0.365,8,20,0.400,18,25,1.0,11,28,39,15,10,6,17,21,80,W,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,1.0,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010
2,21000003,2010-10-26,1610612745,L,0.000,240,38,91,0.418,8,20,0.400,26,28,1.0,16,37,53,25,6,7,20,25,110,W,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,1.0,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010
3,21000005,2010-10-27,1610612765,L,0.000,240,37,83,0.446,8,19,0.421,16,30,1.0,10,27,37,21,7,3,6,19,98,W,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,1.0,9,35,44,17,4,4,11,23,101,Regular Season,2010-11,2010
4,21000004,2010-10-27,1610612738,L,0.500,240,34,72,0.472,3,12,0.250,16,21,1.0,6,32,38,24,8,1,19,24,87,W,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,1.0,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010
10262,41700317,2018-05-28,1610612744,W,0.571,240,39,80,0.488,16,39,0.410,7,14,0.0,11,31,42,25,9,7,16,22,101,L,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,1.0,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017
10263,41700401,2018-05-31,1610612739,L,0.000,265,44,99,0.444,10,37,0.270,16,22,1.0,19,34,53,18,5,3,11,18,114,W,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,1.0,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017
10264,41700402,2018-06-03,1610612739,L,0.000,240,37,90,0.411,9,27,0.333,20,26,1.0,16,26,42,25,9,4,10,15,103,W,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,1.0,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017
10265,41700403,2018-06-06,1610612744,W,1.000,240,42,81,0.519,9,26,0.346,17,19,1.0,6,31,37,27,6,5,10,20,110,L,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,1.0,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017
10266,41700404,2018-06-08,1610612744,W,1.000,240,39,86,0.453,14,38,0.368,16,16,1.0,10,34,44,25,7,13,8,24,108,L,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,1.0,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017

In [9]:
df_tbsatbs1018 = pd.merge(df_tbsa1018, df_tbs1018, on=['game_id', 'game_date'], how='inner')
p(df_tbsatbs1018)

(10266, 109)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,wl_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612748,L,0.000,240,27,74,0.365,8,20,0.400,18,25,1.0,11,28,39,15,10,6,17,21,80,W,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,1.0,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612756,L,0.000,240,36,74,0.486,9,19,0.474,11,16,1.0,7,23,30,15,3,4,19,19,92,W,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,1.0,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612745,L,0.000,240,38,91,0.418,8,20,0.400,26,28,1.0,16,37,53,25,6,7,20,25,110,W,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,1.0,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010
3,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612745,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612744,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612745,L,0.000,240,41,87,0.471,4,16,0.250,42,52,1.0,15,24,39,24,9,2,9,20,128,W,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,1.0,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010
4,21000014,2010-10-27,Jazz,UTA,Utah,240:00,0 days 04:00:00,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612762,88.1,86.3,107.8,108.9,-19.7,-22.6,0.778,0.95,15.9,0.260,0.740,0.500,22.018,21.6,0.407,0.495,1.0,0.202,100.98,101.50,84.58,102,0.371,240.0,1610612743,107.8,108.9,88.1,86.3,19.7,22.6,0.657,1.44,16.8,0.260,0.740,0.500,15.680,15.8,0.475,0.561,1.0,0.198,100.98,101.50,84.58,101,0.629,240.0,1610612762,L,0.000,240,27,70,0.386,3,13,0.231,31,43,1.0,11,33,44,21,7,4,22,30,88,W,1610612743,1.000,240,35,80,0.438,6,20,0.300,34,41,1.0,12,34,46,23,9,2,15,31,110,Regular Season,2010-11,2010
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612744,W,0.571,240,39,80,0.488,16,39,0.410,7,14,0.0,11,31,42,25,9,7,16,22,101,L,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,1.0,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,L,0.000,265,44,99,0.444,10,37,0.270,16,22,1.0,19,34,53,18,5,3,11,18,114,W,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,1.0,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,L,0.000,240,37,90,0.411,9,27,0.333,20,26,1.0,16,26,42,25,9,4,10,15,103,W,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,1.0,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,W,1.000,240,42,81,0.519,9,26,0.346,17,19,1.0,6,31,37,27,6,5,10,20,110,L,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,1.0,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,W,1.000,240,39,86,0.453,14,38,0.368,16,16,1.0,10,34,44,25,7,13,8,24,108,L,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,1.0,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017

In [10]:
list(df_tbsatbs1018.columns)

['game_id',
 'game_date',
 'TEAM_NAME_away',
 'TEAM_ABBREVIATION_away',
 'TEAM_CITY_away',
 'MIN_away',
 'duration_away',
 'TEAM_NAME_home',
 'TEAM_ABBREVIATION_home',
 'TEAM_CITY_home',
 'MIN_home',
 'duration_home',
 'TEAM_ID_away',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'TEAM_ID_home',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_away',
 'wl_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'wl_home',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'season_type',
 'season',
 'season_year']

In [11]:
df_tbsatbs1018 = df_tbsatbs1018.sort_values('game_date').reset_index(drop=True)
p(df_tbsatbs1018)

(10266, 109)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,TEAM_ID_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,TEAM_ID_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,wl_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612748,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612738,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612748,L,0.000,240,27,74,0.365,8,20,0.400,18,25,1.0,11,28,39,15,10,6,17,21,80,W,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,1.0,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612756,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612757,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612756,L,0.000,240,36,74,0.486,9,19,0.474,11,16,1.0,7,23,30,15,3,4,19,19,92,W,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,1.0,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612745,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612747,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612745,L,0.000,240,38,91,0.418,8,20,0.400,26,28,1.0,16,37,53,25,6,7,20,25,110,W,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,1.0,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010
3,21000016,2010-10-27,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,1610612757,107.6,108.9,94.4,97.8,13.1,11.1,0.472,1.21,13.2,0.446,0.627,0.533,15.364,15.6,0.455,0.499,1.0,0.198,92.16,90.00,75.00,90,0.551,240.0,1610612746,94.4,97.8,107.6,108.9,-13.1,-11.1,0.594,1.27,15.1,0.373,0.554,0.467,16.094,16.7,0.437,0.477,1.0,0.200,92.16,90.00,75.00,90,0.449,240.0,1610612757,W,1.000,240,36,88,0.409,8,20,0.400,18,23,1.0,21,30,51,17,9,6,12,23,98,L,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,1.0,14,27,41,19,8,8,15,20,88,Regular Season,2010-11,2010
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612738,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612739,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612738,L,0.500,240,34,72,0.472,3,12,0.250,16,21,1.0,6,32,38,24,8,1,19,24,87,W,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,1.0,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612744,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612745,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612744,W,0.571,240,39,80,0.488,16,39,0.410,7,14,0.0,11,31,42,25,9,7,16,22,101,L,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,1.0,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612739,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612744,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,L,0.000,265,44,99,0.444,10,37,0.270,16,22,1.0,19,34,53,18,5,3,11,18,114,W,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,1.0,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612739,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612744,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,L,0.000,240,37,90,0.411,9,27,0.333,20,26,1.0,16,26,42,25,9,4,10,15,103,W,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,1.0,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612739,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,W,1.000,240,42,81,0.519,9,26,0.346,17,19,1.0,6,31,37,27,6,5,10,20,110,L,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,1.0,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612744,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612739,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,W,1.000,240,39,86,0.453,14,38,0.368,16,16,1.0,10,34,44,25,7,13,8,24,108,L,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,1.0,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017

In [12]:
#check for equality between team_id_away and TEAM_ID_away

#check for equality between team_id_home and TEAM_ID_home

#drop TEAM_ID_away if equal to team_id_away

#drop TEAM_ID_home if equal to team_id_home

In [13]:
#check for equality between team_id_away and TEAM_ID_away

(df_tbsatbs1018['team_id_away'] - df_tbsatbs1018['TEAM_ID_away']).value_counts()

0    10266
dtype: int64

In [14]:
#check for equality between team_id_home and TEAM_ID_home

In [15]:
(df_tbsatbs1018['team_id_home'] - df_tbsatbs1018['TEAM_ID_home']).value_counts()

0    10266
dtype: int64

In [16]:
#drop TEAM_ID_away if equal to team_id_away

df_tbsatbs1018.drop(columns=['TEAM_ID_away'], inplace=True)

#drop TEAM_ID_home if equal to team_id_home

df_tbsatbs1018.drop(columns=['TEAM_ID_home'], inplace=True)

In [17]:
p(df_tbsatbs1018)

(10266, 107)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,wl_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612748,L,0.000,240,27,74,0.365,8,20,0.400,18,25,1.0,11,28,39,15,10,6,17,21,80,W,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,1.0,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612756,L,0.000,240,36,74,0.486,9,19,0.474,11,16,1.0,7,23,30,15,3,4,19,19,92,W,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,1.0,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612745,L,0.000,240,38,91,0.418,8,20,0.400,26,28,1.0,16,37,53,25,6,7,20,25,110,W,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,1.0,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010
3,21000016,2010-10-27,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,107.6,108.9,94.4,97.8,13.1,11.1,0.472,1.21,13.2,0.446,0.627,0.533,15.364,15.6,0.455,0.499,1.0,0.198,92.16,90.00,75.00,90,0.551,240.0,94.4,97.8,107.6,108.9,-13.1,-11.1,0.594,1.27,15.1,0.373,0.554,0.467,16.094,16.7,0.437,0.477,1.0,0.200,92.16,90.00,75.00,90,0.449,240.0,1610612757,W,1.000,240,36,88,0.409,8,20,0.400,18,23,1.0,21,30,51,17,9,6,12,23,98,L,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,1.0,14,27,41,19,8,8,15,20,88,Regular Season,2010-11,2010
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612738,L,0.500,240,34,72,0.472,3,12,0.250,16,21,1.0,6,32,38,24,8,1,19,24,87,W,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,1.0,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612744,W,0.571,240,39,80,0.488,16,39,0.410,7,14,0.0,11,31,42,25,9,7,16,22,101,L,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,1.0,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,L,0.000,265,44,99,0.444,10,37,0.270,16,22,1.0,19,34,53,18,5,3,11,18,114,W,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,1.0,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,L,0.000,240,37,90,0.411,9,27,0.333,20,26,1.0,16,26,42,25,9,4,10,15,103,W,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,1.0,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,W,1.000,240,42,81,0.519,9,26,0.346,17,19,1.0,6,31,37,27,6,5,10,20,110,L,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,1.0,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,W,1.000,240,39,86,0.453,14,38,0.368,16,16,1.0,10,34,44,25,7,13,8,24,108,L,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,1.0,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017

In [18]:
#data definition...

#data types

#description of the columns

#counts of the columns

#ranges of values of the columns

###########################////////////////////////////

#percentage unique values of the columns

###############///////////////////////////////////////

#

In [19]:
#data types
pd.options.display.max_info_columns = 999

df_tbsatbs1018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10266 entries, 0 to 10265
Data columns (total 107 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 10266 non-null  int64
 1   game_date               10266 non-null  object
 2   TEAM_NAME_away          10266 non-null  object
 3   TEAM_ABBREVIATION_away  10266 non-null  object
 4   TEAM_CITY_away          10266 non-null  object
 5   MIN_away                10266 non-null  object
 6   duration_away           10266 non-null  object
 7   TEAM_NAME_home          10266 non-null  object
 8   TEAM_ABBREVIATION_home  10266 non-null  object
 9   TEAM_CITY_home          10266 non-null  object
 10  MIN_home                10266 non-null  object
 11  duration_home           10266 non-null  object
 12  E_OFF_RATING_away       10266 non-null  float64
 13  OFF_RATING_away         10266 non-null  float64
 14  E_DEF_RATING_away       10266 non-null  float64
 15  DEF_RATING_away         10266 non-null  float64
 16  E_NET_RATING_away       10266 non-null  float64
 17  NET_RATING_away         10266 non-null  float64
 18  AST_PCT_away            10266 non-null  float64
 19  AST_TOV_away            10266 non-null  float64
 20  AST_RATIO_away          10266 non-null  float64
 21  OREB_PCT_away           10266 non-null  float64
 22  DREB_PCT_away           10266 non-null  float64
 23  REB_PCT_away            10266 non-null  float64
 24  E_TM_TOV_PCT_away       10266 non-null  float64
 25  TM_TOV_PCT_away         10266 non-null  float64
 26  EFG_PCT_away            10266 non-null  float64
 27  TS_PCT_away             10266 non-null  float64
 28  USG_PCT_away            10266 non-null  float64
 29  E_USG_PCT_away          10266 non-null  float64
 30  E_PACE_away             10266 non-null  float64
 31  PACE_away               10266 non-null  float64
 32  PACE_PER40_away         10266 non-null  float64
 33  POSS_away               10266 non-null  int64
 34  PIE_away                10266 non-null  float64
 35  duration_minutes_away   10266 non-null  float64
 36  E_OFF_RATING_home       10266 non-null  float64
 37  OFF_RATING_home         10266 non-null  float64
 38  E_DEF_RATING_home       10266 non-null  float64
 39  DEF_RATING_home         10266 non-null  float64
 40  E_NET_RATING_home       10266 non-null  float64
 41  NET_RATING_home         10266 non-null  float64
 42  AST_PCT_home            10266 non-null  float64
 43  AST_TOV_home            10266 non-null  float64
 44  AST_RATIO_home          10266 non-null  float64
 45  OREB_PCT_home           10266 non-null  float64
 46  DREB_PCT_home           10266 non-null  float64
 47  REB_PCT_home            10266 non-null  float64
 48  E_TM_TOV_PCT_home       10266 non-null  float64
 49  TM_TOV_PCT_home         10266 non-null  float64
 50  EFG_PCT_home            10266 non-null  float64
 51  TS_PCT_home             10266 non-null  float64
 52  USG_PCT_home            10266 non-null  float64
 53  E_USG_PCT_home          10266 non-null  float64
 54  E_PACE_home             10266 non-null  float64
 55  PACE_home               10266 non-null  float64
 56  PACE_PER40_home         10266 non-null  float64
 57  POSS_home               10266 non-null  int64
 58  PIE_home                10266 non-null  float64
 59  duration_minutes_home   10266 non-null  float64
 60  team_id_away            10266 non-null  int64
 61  wl_away                 10266 non-null  object
 62  w_pct_away              10266 non-null  float64
 63  min_away                10266 non-null  int64
 64  fgm_away                10266 non-null  int64
 65  fga_away                10266 non-null  int64
 66  fg_pct_away             10266 non-null  float64
 67  fg3m_away               10266 non-null  int64
 68  fg3a_away               10266 non-null  int64
 69  fg3_pct_away            10266 non-null  float64
 70  ftm_away                10266 non-null  int64
 71  fta_away                10266 non-null  int64
 72  ft_pct_away             10266 non-null  float64
 73  oreb_away               10266 non-null  int64
 74  dreb_away               10266 non-null  int64
 75  reb_away                10266 non-null  int64
 76  ast_away                10266 non-null  int64
 77  stl_away                10266 non-null  int64
 78  blk_away                10266 non-null  int64
 79  tov_away                10266 non-null  int64
 80  pf_away                 10266 non-null  int64
 81  pts_away                10266 non-null  int64
 82  wl_home                 10266 non-null  object
 83  team_id_home            10266 non-null  int64
 84  w_pct_home              10266 non-null  float64
 85  min_home                10266 non-null  int64
 86  fgm_home                10266 non-null  int64
 87  fga_home                10266 non-null  int64
 88  fg_pct_home             10266 non-null  float64
 89  fg3m_home               10266 non-null  int64
 90  fg3a_home               10266 non-null  int64
 91  fg3_pct_home            10266 non-null  float64
 92  ftm_home                10266 non-null  int64
 93  fta_home                10266 non-null  int64
 94  ft_pct_home             10266 non-null  float64
 95  oreb_home               10266 non-null  int64
 96  dreb_home               10266 non-null  int64
 97  reb_home                10266 non-null  int64
 98  ast_home                10266 non-null  int64
 99  stl_home                10266 non-null  int64
 100 blk_home                10266 non-null  int64
 101 tov_home                10266 non-null  int64
 102 pf_home                 10266 non-null  int64
 103 pts_home                10266 non-null  int64
 104 season_type             10266 non-null  object
 105 season                  10266 non-null  object
 106 season_year             10266 non-null  int64
dtypes: float64(54), int64(38), object(15)
memory usage: 8.4+ MB

<font color='red'> object vs string use????</font>

In [20]:
#description of the columns

#counts of the columns

#ranges of values of the columns

#get mean, median, standard deviation, and range if not done already

pd.set_option('display.float_format', lambda x: '%.3f' % x)
df_tbsatbs1018.describe().T

,count,mean,std,min,25%,50%,75%,max
game_id,10266.000,22655759.071,4932983.875,21000001.000,21200347.250,21400454.500,21600560.750,41700404.000
E_OFF_RATING_away,10266.000,102.681,11.281,60.700,95.100,102.700,110.300,147.600
OFF_RATING_away,10266.000,104.441,11.170,60.900,96.900,104.400,111.800,144.300
E_DEF_RATING_away,10266.000,105.768,11.146,65.700,98.200,105.700,113.300,151.600
DEF_RATING_away,10266.000,107.396,10.968,68.100,100.000,107.300,114.700,152.200
E_NET_RATING_away,10266.000,-3.088,14.529,-58.300,-12.800,-4.300,7.400,62.300
NET_RATING_away,10266.000,-2.955,13.962,-63.100,-12.000,-4.100,6.600,57.300
AST_PCT_away,10266.000,0.572,0.104,0.167,0.500,0.575,0.643,0.966
AST_TOV_away,10266.000,1.613,0.676,0.290,1.150,1.500,1.920,8.330
AST_RATIO_away,10266.000,16.468,3.242,3.700,14.300,16.500,18.600,29.100
OREB_PCT_away,10266.000,0.248,0.117,0.000,0.205,0.269,0.326,0.571
DREB_PCT_away,10266.000,0.611,0.253,0.000,0.623,0.694,0.750,0.941
REB_PCT_away,10266.000,0.374,0.217,0.000,0.376,0.474,0.516,0.695
E_TM_TOV_PCT_away,10266.000,14.870,3.868,3.048,12.147,14.755,17.442,31.183
TM_TOV_PCT_away,10266.000,15.135,3.958,3.100,12.400,15.000,17.800,32.200
EFG_PCT_away,10266.000,0.497,0.065,0.267,0.453,0.494,0.539,0.750
TS_PCT_away,10266.000,0.536,0.061,0.319,0.495,0.535,0.576,0.788
USG_PCT_away,10266.000,1.000,0.000,1.000,1.000,1.000,1.000,1.000
E_USG_PCT_away,10266.000,0.198,0.002,0.186,0.197,0.199,0.200,0.205
E_PACE_away,10266.000,96.393,5.306,78.860,92.700,96.200,99.900,119.120
PACE_away,10266.000,94.812,5.231,77.500,91.000,94.500,98.500,120.000
PACE_PER40_away,10266.000,79.010,4.359,64.580,75.830,78.750,82.080,100.000
POSS_away,10266.000,95.500,5.913,77.000,91.000,95.000,99.000,136.000
PIE_away,10266.000,0.478,0.095,0.022,0.414,0.473,0.547,0.890
duration_minutes_away,10266.000,241.817,7.692,239.933,240.000,240.000,240.000,340.000
E_OFF_RATING_home,10266.000,105.768,11.146,65.700,98.200,105.700,113.300,151.600
OFF_RATING_home,10266.000,107.396,10.968,68.100,100.000,107.300,114.700,152.200
E_DEF_RATING_home,10266.000,102.681,11.281,60.700,95.100,102.700,110.300,147.600
DEF_RATING_home,10266.000,104.441,11.170,60.900,96.900,104.400,111.800,144.300
E_NET_RATING_home,10266.000,3.088,14.529,-62.300,-7.400,4.300,12.800,58.300
NET_RATING_home,10266.000,2.955,13.962,-57.300,-6.600,4.100,12.000,63.100
AST_PCT_home,10266.000,0.590,0.101,0.237,0.525,0.591,0.659,0.933
AST_TOV_home,10266.000,1.748,0.734,0.400,1.250,1.620,2.080,10.000
AST_RATIO_home,10266.000,17.261,3.241,6.800,15.000,17.200,19.400,30.100
OREB_PCT_home,10266.000,0.252,0.122,0.000,0.211,0.277,0.333,0.595
DREB_PCT_home,10266.000,0.624,0.249,0.000,0.635,0.702,0.759,0.976
REB_PCT_home,10266.000,0.382,0.221,0.000,0.385,0.485,0.527,0.684
E_TM_TOV_PCT_home,10266.000,14.561,3.798,2.115,11.900,14.463,17.074,29.907
TM_TOV_PCT_home,10266.000,14.796,3.880,2.100,12.100,14.700,17.300,30.300
EFG_PCT_home,10266.000,0.510,0.066,0.270,0.464,0.506,0.554,0.759
TS_PCT_home,10266.000,0.549,0.061,0.350,0.506,0.548,0.590,0.776
USG_PCT_home,10266.000,1.000,0.000,1.000,1.000,1.000,1.000,1.000
E_USG_PCT_home,10266.000,0.199,0.002,0.187,0.197,0.199,0.200,0.206
E_PACE_home,10266.000,96.393,5.306,78.860,92.700,96.200,99.900,119.120
PACE_home,10266.000,94.812,5.231,77.500,91.000,94.500,98.500,120.000
PACE_PER40_home,10266.000,79.010,4.359,64.580,75.830,78.750,82.080,100.000
POSS_home,10266.000,95.539,5.929,78.000,91.000,95.000,99.000,134.000
PIE_home,10266.000,0.522,0.095,0.110,0.453,0.527,0.586,0.978
duration_minutes_home,10266.000,241.817,7.692,239.933,240.000,240.000,240.000,340.000
team_id_away,10266.000,1610612751.401,8.675,1610612737.000,1610612744.000,1610612751.000,1610612759.000,1610612766.000
w_pct_away,10266.000,0.495,0.199,0.000,0.362,0.500,0.625,1.000
min_away,10266.000,241.817,7.692,240.000,240.000,240.000,240.000,340.000
fgm_away,10266.000,37.332,5.027,16.000,34.000,37.000,41.000,58.000
fga_away,10266.000,83.348,7.390,59.000,78.000,83.000,88.000,129.000
fg_pct_away,10266.000,0.449,0.055,0.246,0.412,0.448,0.486,0.667
fg3m_away,10266.000,7.997,3.572,0.000,5.000,8.000,10.000,25.000
fg3a_away,10266.000,22.729,7.287,3.000,17.000,22.000,27.000,57.000
fg3_pct_away,10266.000,0.349,0.105,0.000,0.278,0.348,0.419,0.778
ftm_away,10266.000,17.076,5.955,1.000,13.000,17.000,21.000,52.000
fta_away,10266.000,22.519,7.271,1.000,17.000,22.000,27.000,64.000
ft_pct_away,10266.000,0.981,0.136,0.000,1.000,1.000,1.000,1.000
oreb_away,10266.000,10.543,3.855,0.000,8.000,10.000,13.000,38.000
dreb_away,10266.000,31.674,5.286,12.000,28.000,32.000,35.000,56.000
reb_away,10266.000,42.217,6.412,20.000,38.000,42.000,46.000,81.000
ast_away,10266.000,21.375,4.990,4.000,18.000,21.000,25.000,46.000
stl_away,10266.000,7.631,2.884,0.000,6.000,7.000,9.000,20.000
blk_away,10266.000,4.650,2.498,0.000,3.000,4.000,6.000,17.000
tov_away,10266.000,13.837,3.835,3.000,11.000,14.000,16.000,28.000
pf_away,10266.000,20.599,4.411,5.000,18.000,20.000,23.000,42.000
pts_away,10266.000,99.737,12.288,56.000,91.000,99.000,108.000,148.000
team_id_home,10266.000,1610612751.391,8.673,1610612737.000,1610612744.000,1610612751.000,1610612759.000,1610612766.000
w_pct_home,10266.000,0.509,0.200,0.000,0.371,0.507,0.634,1.000
min_home,10266.000,241.817,7.692,240.000,240.000,240.000,240.000,340.000
fgm_home,10266.000,38.267,5.078,19.000,35.000,38.000,42.000,60.000
fga_home,10266.000,83.297,7.341,59.000,78.000,83.000,88.000,125.000
fg_pct_home,10266.000,0.461,0.056,0.257,0.422,0.459,0.500,0.684
fg3m_home,10266.000,8.177,3.591,0.000,6.000,8.000,10.000,25.000
fg3a_home,10266.000,22.695,7.288,3.000,17.000,22.000,27.000,61.000
fg3_pct_home,10266.000,0.357,0.107,0.000,0.286,0.357,0.429,0.833
ftm_home,10266.000,17.888,6.095,1.000,14.000,17.000,22.000,45.000
fta_home,10266.000,23.556,7.574,1.000,18.000,23.000,28.000,64.000
ft_pct_home,10266.000,0.985,0.120,0.000,1.000,1.000,1.000,1.000
oreb_home,10266.000,10.759,3.935,1.000,8.000,10.000,13.000,30.000
dreb_home,10266.000,32.601,5.391,14.000,29.000,32.000,36.000,55.000
reb_home,10266.000,43.360,6.537,17.000,39.000,43.000,48.000,72.000
ast_home,10266.000,22.627,5.075,8.000,19.000,22.000,26.000,47.000
stl_home,10266.000,7.688,2.924,0.000,6.000,8.000,10.000,22.000
blk_home,10266.000,5.131,2.629,0.000,3.000,5.000,7.000,18.000
tov_home,10266.000,13.544,3.800,2.000,11.000,13.000,16.000,29.000
pf_home,10266.000,19.859,4.243,7.000,17.000,20.000,23.000,41.000
pts_home,10266.000,102.600,12.193,59.000,94.000,102.000,111.000,149.000
season_year,10266.000,2013.557,2.284,2010.000,2012.000,2014.000,2016.000,2017.000

<font color='red'> why are we getting floats for game_id????</font>

<font color='red'> why are we unable to see the last digit of the game_id's here??????</font>

In [21]:
#percentage unique values of the columns

############ ###///////////////////////////////////////

#get mode and number of unique value if not done already

In [22]:
list(df_tbsatbs1018.columns)

['game_id',
 'game_date',
 'TEAM_NAME_away',
 'TEAM_ABBREVIATION_away',
 'TEAM_CITY_away',
 'MIN_away',
 'duration_away',
 'TEAM_NAME_home',
 'TEAM_ABBREVIATION_home',
 'TEAM_CITY_home',
 'MIN_home',
 'duration_home',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_away',
 'wl_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'wl_home',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'season_type',
 'season',
 'season_year']

In [23]:
#percentage unique values of the columns

df_tbsatbs1018.TEAM_NAME_away.value_counts(normalize=True).head()

Spurs       0.036
Heat        0.036
Warriors    0.036
Thunder     0.036
Cavaliers   0.035
Name: TEAM_NAME_away, dtype: float64

In [24]:
number = 0

In [25]:
from IPython.display import display, HTML

CSS = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(CSS))

In [26]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

21600253   0.000
21300754   0.000
21200205   0.000
21400907   0.000
21300554   0.000
Name: game_id, dtype: float64

2011-04-13   0.001
2014-04-16   0.001
2016-11-25   0.001
2013-04-17   0.001
2012-04-18   0.001
Name: game_date, dtype: float64

Spurs       0.036
Heat        0.036
Warriors    0.036
Thunder     0.036
Cavaliers   0.035
Name: TEAM_NAME_away, dtype: float64

In [27]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

SAS   0.036
MIA   0.036
GSW   0.036
OKC   0.036
CLE   0.035
Name: TEAM_ABBREVIATION_away, dtype: float64

Los Angeles     0.054
San Antonio     0.036
Miami           0.036
Golden State    0.036
Oklahoma City   0.036
Name: TEAM_CITY_away, dtype: float64

240:00   0.938
265:00   0.053
290:00   0.007
315:00   0.002
340:00   0.000
Name: MIN_away, dtype: float64

In [28]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0 days 04:00:00   0.938
0 days 04:25:00   0.053
0 days 04:50:00   0.007
0 days 05:15:00   0.002
0 days 05:40:00   0.000
Name: duration_away, dtype: float64

Heat       0.037
Warriors   0.036
Spurs      0.036
Thunder    0.036
Celtics    0.035
Name: TEAM_NAME_home, dtype: float64

MIA   0.037
GSW   0.036
SAS   0.036
OKC   0.036
BOS   0.035
Name: TEAM_ABBREVIATION_home, dtype: float64

In [29]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

Los Angeles     0.054
Miami           0.037
Golden State    0.036
San Antonio     0.036
Oklahoma City   0.036
Name: TEAM_CITY_home, dtype: float64

240:00   0.938
265:00   0.053
290:00   0.007
315:00   0.002
340:00   0.000
Name: MIN_home, dtype: float64

0 days 04:00:00   0.938
0 days 04:25:00   0.053
0 days 04:50:00   0.007
0 days 05:15:00   0.002
0 days 05:40:00   0.000
Name: duration_home, dtype: float64

In [30]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

100.000   0.005
107.200   0.005
104.300   0.005
105.600   0.005
105.900   0.005
Name: E_OFF_RATING_away, dtype: float64

100.000   0.031
98.900    0.019
101.100   0.018
99.000    0.014
101.000   0.012
Name: OFF_RATING_away, dtype: float64

109.600   0.006
108.700   0.005
103.600   0.005
109.100   0.005
111.500   0.004
Name: E_DEF_RATING_away, dtype: float64

In [31]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

100.000   0.033
101.100   0.019
98.900    0.014
101.000   0.012
99.000    0.011
Name: DEF_RATING_away, dtype: float64

-8.100   0.004
-6.300   0.004
-7.300   0.004
-6.600   0.004
-7.000   0.004
Name: E_NET_RATING_away, dtype: float64

-5.300   0.006
-4.300   0.006
-2.100   0.006
-4.200   0.006
2.200    0.006
Name: NET_RATING_away, dtype: float64

In [32]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.500   0.041
0.667   0.025
0.600   0.020
0.571   0.016
0.514   0.015
Name: AST_PCT_away, dtype: float64

1.000   0.036
2.000   0.033
1.500   0.024
1.060   0.017
1.330   0.017
Name: AST_TOV_away, dtype: float64

16.700   0.015
15.900   0.014
16.900   0.014
15.500   0.014
16.400   0.013
Name: AST_RATIO_away, dtype: float64

In [33]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.000   0.128
0.333   0.027
0.250   0.023
0.255   0.013
0.286   0.013
Name: OREB_PCT_away, dtype: float64

0.000   0.137
0.667   0.025
0.750   0.020
0.714   0.013
0.660   0.012
Name: DREB_PCT_away, dtype: float64

0.000   0.244
0.500   0.035
0.495   0.023
0.505   0.022
0.490   0.011
Name: REB_PCT_away, dtype: float64

In [34]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

15.823   0.001
14.368   0.001
17.241   0.001
15.158   0.001
16.667   0.001
Name: E_TM_TOV_PCT_away, dtype: float64

16.500   0.017
16.300   0.016
14.900   0.016
14.300   0.015
16.700   0.015
Name: TM_TOV_PCT_away, dtype: float64

0.500   0.038
0.494   0.026
0.506   0.024
0.488   0.013
0.512   0.011
Name: EFG_PCT_away, dtype: float64

In [35]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.523   0.010
0.518   0.008
0.551   0.008
0.537   0.008
0.532   0.008
Name: TS_PCT_away, dtype: float64

1.000   1.000
Name: USG_PCT_away, dtype: float64

0.199   0.175
0.200   0.170
0.198   0.161
0.197   0.126
0.201   0.117
Name: E_USG_PCT_away, dtype: float64

In [36]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

93.460   0.002
95.520   0.002
95.600   0.002
98.680   0.002
95.100   0.002
Name: E_PACE_away, dtype: float64

94.000   0.037
95.000   0.036
96.000   0.036
94.500   0.035
93.000   0.034
Name: PACE_away, dtype: float64

78.330   0.037
79.170   0.036
80.000   0.036
78.750   0.035
77.500   0.034
Name: PACE_PER40_away, dtype: float64

In [37]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

94   0.078
95   0.070
96   0.069
97   0.066
92   0.064
Name: POSS_away, dtype: float64

0.453   0.006
0.438   0.006
0.443   0.006
0.429   0.005
0.447   0.005
Name: PIE_away, dtype: float64

240.000   0.938
265.000   0.053
290.000   0.007
315.000   0.002
340.000   0.000
Name: duration_minutes_away, dtype: float64

In [38]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

109.600   0.006
108.700   0.005
103.600   0.005
109.100   0.005
111.500   0.004
Name: E_OFF_RATING_home, dtype: float64

100.000   0.033
101.100   0.019
98.900    0.014
101.000   0.012
99.000    0.011
Name: OFF_RATING_home, dtype: float64

100.000   0.005
107.200   0.005
104.300   0.005
105.600   0.005
105.900   0.005
Name: E_DEF_RATING_home, dtype: float64

In [39]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

100.000   0.031
98.900    0.019
101.100   0.018
99.000    0.014
101.000   0.012
Name: DEF_RATING_home, dtype: float64

8.100   0.004
6.300   0.004
7.300   0.004
6.600   0.004
7.000   0.004
Name: E_NET_RATING_home, dtype: float64

5.300    0.006
4.300    0.006
2.100    0.006
4.200    0.006
-2.200   0.006
Name: NET_RATING_home, dtype: float64

In [40]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.500   0.034
0.667   0.027
0.600   0.021
0.571   0.015
0.605   0.014
Name: AST_PCT_home, dtype: float64

2.000   0.036
1.000   0.027
1.500   0.021
1.670   0.016
1.330   0.016
Name: AST_TOV_home, dtype: float64

18.100   0.014
17.600   0.013
16.000   0.013
16.800   0.013
17.000   0.013
Name: AST_RATIO_home, dtype: float64

In [41]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.000   0.137
0.333   0.025
0.250   0.020
0.286   0.013
0.340   0.012
Name: OREB_PCT_home, dtype: float64

0.000   0.128
0.667   0.027
0.750   0.023
0.745   0.013
0.714   0.013
Name: DREB_PCT_home, dtype: float64

0.000   0.245
0.500   0.035
0.505   0.023
0.495   0.022
0.510   0.011
Name: REB_PCT_home, dtype: float64

In [42]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

14.286   0.001
16.088   0.001
13.233   0.001
13.777   0.001
16.779   0.001
Name: E_TM_TOV_PCT_home, dtype: float64

16.300   0.018
14.300   0.016
16.500   0.016
15.200   0.015
14.000   0.015
Name: TM_TOV_PCT_home, dtype: float64

0.500   0.033
0.494   0.027
0.506   0.026
0.488   0.013
0.512   0.013
Name: EFG_PCT_home, dtype: float64

In [43]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.538   0.008
0.541   0.008
0.564   0.008
0.550   0.008
0.542   0.008
Name: TS_PCT_home, dtype: float64

1.000   1.000
Name: USG_PCT_home, dtype: float64

0.199   0.184
0.200   0.168
0.198   0.165
0.201   0.120
0.197   0.115
Name: E_USG_PCT_home, dtype: float64

In [44]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

93.460   0.002
95.520   0.002
95.600   0.002
98.680   0.002
95.100   0.002
Name: E_PACE_home, dtype: float64

94.000   0.037
95.000   0.036
96.000   0.036
94.500   0.035
93.000   0.034
Name: PACE_home, dtype: float64

78.330   0.037
79.170   0.036
80.000   0.036
78.750   0.035
77.500   0.034
Name: PACE_PER40_home, dtype: float64

In [45]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

95   0.073
94   0.070
93   0.069
96   0.068
92   0.067
Name: POSS_home, dtype: float64

0.547   0.006
0.557   0.006
0.571   0.005
0.553   0.005
0.563   0.005
Name: PIE_home, dtype: float64

240.000   0.938
265.000   0.053
290.000   0.007
315.000   0.002
340.000   0.000
Name: duration_minutes_home, dtype: float64

In [46]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

1610612759   0.036
1610612748   0.036
1610612744   0.036
1610612760   0.036
1610612739   0.035
Name: team_id_away, dtype: float64

L   0.592
W   0.408
Name: wl_away, dtype: float64

0.500   0.051
0.000   0.030
0.333   0.027
0.667   0.024
1.000   0.020
Name: w_pct_away, dtype: float64

In [47]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

240   0.938
265   0.053
290   0.007
315   0.002
340   0.000
Name: min_away, dtype: float64

37   0.086
39   0.078
36   0.075
35   0.073
38   0.073
Name: fgm_away, dtype: float64

84   0.058
83   0.058
80   0.055
82   0.054
81   0.051
Name: fga_away, dtype: float64

In [48]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.500   0.029
0.494   0.020
0.506   0.019
0.488   0.015
0.481   0.012
Name: fg_pct_away, dtype: float64

7   0.117
6   0.111
8   0.106
5   0.099
9   0.096
Name: fg3m_away, dtype: float64

21   0.056
20   0.054
23   0.053
19   0.052
22   0.052
Name: fg3a_away, dtype: float64

In [49]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.333   0.060
0.250   0.031
0.500   0.031
0.400   0.030
0.375   0.022
Name: fg3_pct_away, dtype: float64

16   0.067
15   0.067
14   0.066
17   0.066
18   0.062
Name: ftm_away, dtype: float64

20   0.061
22   0.056
21   0.055
18   0.053
19   0.052
Name: fta_away, dtype: float64

In [50]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

1.000   0.981
0.000   0.019
Name: ft_pct_away, dtype: float64

9    0.108
10   0.103
11   0.101
8    0.096
12   0.084
Name: oreb_away, dtype: float64

32   0.075
30   0.073
31   0.071
33   0.070
29   0.068
Name: dreb_away, dtype: float64

In [51]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

43   0.064
41   0.063
42   0.062
44   0.062
40   0.061
Name: reb_away, dtype: float64

20   0.081
19   0.079
21   0.079
22   0.077
23   0.071
Name: ast_away, dtype: float64

7   0.140
8   0.138
6   0.130
9   0.111
5   0.102
Name: stl_away, dtype: float64

In [52]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

4   0.170
3   0.154
5   0.152
2   0.118
6   0.116
Name: blk_away, dtype: float64

14   0.102
13   0.101
12   0.099
15   0.092
16   0.088
Name: tov_away, dtype: float64

20   0.096
21   0.090
19   0.089
22   0.085
18   0.076
Name: pf_away, dtype: float64

In [53]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

98    0.036
95    0.034
103   0.033
99    0.033
100   0.032
Name: pts_away, dtype: float64

W   0.592
L   0.408
Name: wl_home, dtype: float64

1610612748   0.037
1610612744   0.036
1610612759   0.036
1610612760   0.036
1610612738   0.035
Name: team_id_home, dtype: float64

In [54]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

0.500   0.054
1.000   0.030
0.333   0.025
0.667   0.024
0.000   0.021
Name: w_pct_home, dtype: float64

240   0.938
265   0.053
290   0.007
315   0.002
340   0.000
Name: min_home, dtype: float64

38   0.080
37   0.079
39   0.076
36   0.072
40   0.070
Name: fgm_home, dtype: float64

In [55]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

81   0.059
83   0.058
82   0.057
84   0.052
80   0.052
Name: fga_home, dtype: float64

0.500   0.032
0.494   0.022
0.506   0.019
0.488   0.017
0.481   0.012
Name: fg_pct_home, dtype: float64

7   0.112
8   0.108
6   0.105
9   0.105
5   0.090
Name: fg3m_home, dtype: float64

In [56]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

20   0.057
22   0.054
21   0.053
25   0.052
19   0.052
Name: fg3a_home, dtype: float64

0.333   0.061
0.500   0.034
0.400   0.034
0.250   0.027
0.375   0.024
Name: fg3_pct_home, dtype: float64

17   0.067
15   0.064
18   0.063
16   0.062
14   0.061
Name: ftm_home, dtype: float64

In [57]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

21   0.057
23   0.054
24   0.052
25   0.051
22   0.051
Name: fta_home, dtype: float64

1.000   0.985
0.000   0.015
Name: ft_pct_home, dtype: float64

11   0.102
9    0.100
10   0.099
12   0.087
8    0.086
Name: oreb_home, dtype: float64

In [58]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

32   0.074
34   0.072
33   0.069
31   0.069
35   0.068
Name: dreb_home, dtype: float64

42   0.063
43   0.062
45   0.059
44   0.059
41   0.057
Name: reb_home, dtype: float64

23   0.081
22   0.081
21   0.076
24   0.074
20   0.070
Name: ast_home, dtype: float64

In [59]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

7   0.136
8   0.136
6   0.124
9   0.113
5   0.106
Name: stl_home, dtype: float64

4   0.162
5   0.153
3   0.134
6   0.125
7   0.099
Name: blk_home, dtype: float64

12   0.104
13   0.104
14   0.100
15   0.095
11   0.093
Name: tov_home, dtype: float64

In [60]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

19   0.099
20   0.093
18   0.091
21   0.085
17   0.081
Name: pf_home, dtype: float64

99    0.034
102   0.034
101   0.034
103   0.034
104   0.033
Name: pts_home, dtype: float64

Regular Season   0.935
Playoffs         0.065
Name: season_type, dtype: float64

In [61]:
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1
display(df_tbsatbs1018.iloc[:,number].value_counts(normalize=True).head())
number = number + 1

2013-14   0.128
2015-16   0.128
2012-13   0.128
2017-18   0.128
2014-15   0.128
Name: season, dtype: float64

2013   0.128
2015   0.128
2012   0.128
2017   0.128
2014   0.128
Name: season_year, dtype: float64

In [62]:
#df_tbsatbs1018.mode(axis=0)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,wl_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year
0,21000001,2011-04-13,Spurs,SAS,Los Angeles,240:00,0 days 04:00:00,Heat,MIA,Los Angeles,240:00,0 days 04:00:00,100.000,100.000,109.600,100.000,-8.100,-5.300,0.500,1.000,16.700,0.000,0.000,0.000,14.368,16.500,0.500,0.523,1.000,0.199,93.460,94.000,78.330,94.000,0.453,240.000,109.600,100.000,100.000,100.000,8.100,5.300,0.500,2.000,18.100,0.000,0.000,0.000,14.286,16.300,0.500,0.538,1.000,0.199,93.460,94.000,78.330,95.000,0.547,240.000,1610612759.000,L,0.500,240.000,37.000,84.000,0.500,7.000,21.000,0.333,16.000,20.000,1.000,9.000,32.000,43.000,20.000,7.000,4.000,14.000,20.000,98.000,W,1610612748.000,0.500,240.000,38.000,81.000,0.500,7.000,20.000,0.333,17.000,21.000,1.000,11.000,32.000,42.000,23.000,7.000,4.000,12.000,19.000,99.000,Regular Season,2013-14,2013.000
1,21000002,2013-04-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,15.823,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,102.000,NaN,NaN,nan
2,21000003,2014-04-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan
3,21000004,2016-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan
4,21000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,41700317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan
10262,41700401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan
10263,41700402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan
10264,41700403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan
10265,41700404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,nan

In [63]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_tbsatbs1018.to_csv(datapath_df, index=False)

In [64]:
df_e = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv')
p(df_e)

(10266, 107)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,wl_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.900,87.900,95.700,95.700,-7.700,-7.700,0.556,0.880,12.800,0.250,0.732,0.472,18.681,18.700,0.419,0.471,1.000,0.200,91.500,91.500,76.250,91,0.401,240.000,95.700,95.700,87.900,87.900,7.700,7.700,0.781,1.250,20.000,0.268,0.750,0.528,21.739,21.700,0.522,0.550,1.000,0.196,91.500,91.500,76.250,92,0.599,240.000,1610612748,L,0.000,240,27,74,0.365,8,20,0.400,18,25,1.000,11,28,39,15,10,6,17,21,80,W,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,1.000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.900,102.200,109.700,117.800,-10.800,-15.600,0.417,0.790,13.000,0.244,0.510,0.391,20.421,21.100,0.547,0.568,1.000,0.196,94.820,90.000,75.000,90,0.375,240.000,109.700,117.800,98.900,102.200,10.800,15.600,0.721,2.070,21.300,0.490,0.756,0.609,15.528,16.700,0.516,0.532,1.000,0.192,94.820,90.000,75.000,90,0.625,240.000,1610612756,L,0.000,240,36,74,0.486,9,19,0.474,11,16,1.000,7,23,30,15,3,4,19,19,92,W,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,1.000,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.600,106.800,105.300,107.700,-3.800,-0.900,0.658,1.190,16.700,0.396,0.695,0.554,19.387,20.400,0.462,0.532,1.000,0.196,107.320,103.500,86.250,103,0.507,240.000,105.300,107.700,101.600,106.800,3.800,0.900,0.525,1.750,14.900,0.305,0.604,0.446,11.287,11.500,0.464,0.517,1.000,0.198,107.320,103.500,86.250,104,0.493,240.000,1610612745,L,0.000,240,38,91,0.418,8,20,0.400,26,28,1.000,16,37,53,25,6,7,20,25,110,W,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,1.000,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010
3,21000016,2010-10-27,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,107.600,108.900,94.400,97.800,13.100,11.100,0.472,1.210,13.200,0.446,0.627,0.533,15.364,15.600,0.455,0.499,1.000,0.198,92.160,90.000,75.000,90,0.551,240.000,94.400,97.800,107.600,108.900,-13.100,-11.100,0.594,1.270,15.100,0.373,0.554,0.467,16.094,16.700,0.437,0.477,1.000,0.200,92.160,90.000,75.000,90,0.449,240.000,1610612757,W,1.000,240,36,88,0.409,8,20,0.400,18,23,1.000,21,30,51,17,9,6,12,23,98,L,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,1.000,14,27,41,19,8,8,15,20,88,Regular Season,2010-11,2010
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.300,94.600,97.700,103.300,-5.400,-8.700,0.706,1.260,19.300,0.225,0.708,0.489,20.161,20.700,0.493,0.535,1.000,0.198,95.740,92.000,76.670,92,0.477,240.000,97.700,103.300,92.300,94.600,5.400,8.700,0.667,1.600,18.600,0.292,0.775,0.511,15.426,16.300,0.481,0.526,1.000,0.196,95.740,92.000,76.670,92,0.523,240.000,1610612738,L,0.500,240,34,72,0.472,3,12,0.250,16,21,1.000,6,32,38,24,8,1,19,24,87,W,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,1.000,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.600,111.000,97.200,101.100,12.400,9.900,0.641,1.470,19.500,0.341,0.633,0.510,18.446,18.700,0.588,0.586,1.000,0.200,93.420,91.000,75.830,91,0.568,240.000,97.200,101.100,109.600,111.000,-12.400,-9.900,0.472,1.420,13.200,0.367,0.659,0.490,12.674,13.200,0.439,0.461,1.000,0.201,93.420,91.000,75.830,91,0.432,240.000,1610612744,W,0.571,240,39,80,0.488,16,39,0.410,7,14,0.000,11,31,42,25,9,7,16,22,101,L,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,1.000,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.100,112.900,120.600,125.300,-8.500,-12.400,0.409,1.500,13.000,0.404,0.822,0.588,11.802,11.900,0.495,0.524,1.000,0.197,92.590,90.570,75.470,101,0.406,265.000,120.600,125.300,112.100,112.900,8.500,12.400,0.674,3.880,22.500,0.178,0.596,0.412,7.782,8.100,0.583,0.628,1.000,0.195,92.590,90.570,75.470,99,0.594,265.000,1610612739,L,0.000,265,44,99,0.444,10,37,0.270,16,22,1.000,19,34,53,18,5,3,11,18,114,W,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,1.000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.800,106.200,126.800,129.800,-20.000,-23.600,0.676,2.270,18.200,0.382,0.711,0.516,11.406,11.300,0.461,0.508,1.000,0.197,96.340,95.500,79.580,97,0.435,240.000,126.800,129.800,106.800,106.200,20.000,23.600,0.596,2.330,21.300,0.289,0.618,0.484,12.469,12.800,0.665,0.669,1.000,0.200,96.340,95.500,79.580,94,0.565,240.000,1610612739,L,0.000,240,37,90,0.411,9,27,0.333,20,26,1.000,16,26,42,25,9,4,10,15,103,W,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,1.000,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.600,117.000,103.600,107.400,13.000,9.700,0.643,2.450,21.200,0.195,0.611,0.432,11.657,11.700,0.574,0.615,1.000,0.199,96.420,94.500,78.750,94,0.569,240.000,103.600,107.400,116.600,117.000,-13.000,-9.700,0.500,1.430,15.000,0.389,0.805,0.568,14.216,14.700,0.484,0.513,1.000,0.197,96.420,94.500,78.750,95,0.431,240.000,1610612744,W,1.000,240,42,81,0.519,9,26,0.346,17,19,1.000,6,31,37,27,6,5,10,20,110,L,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,1.000,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.100,118.700,92.400,94.400,23.700,24.200,0.641,2.500,19.500,0.319,0.667,0.514,10.748,11.000,0.535,0.580,1.000,0.196,92.520,90.500,75.420,91,0.672,240.000,92.400,94.400,116.100,118.700,-23.700,-24.200,0.700,1.910,16.200,0.333,0.681,0.486,11.957,12.200,0.391,0.434,1.000,0.198,92.520,90.500,75.420,90,0.328,240.000,1610612744,W,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000,10,34,44,25,7,13,8,24,108,L,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,1.000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017