In [1]:
#!jupyter notebook --NotebookApp.max_buffer_size=1610612736

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
df = pd.read_csv(os.path.join('..', 'raw_data', 'injuries_2010-2020.csv'), parse_dates=['Date'])
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

<font color='red'> </font>

In [6]:
df2 = pd.read_csv(os.path.join('..', 'processed_data', '3game_date_home_away.csv'), parse_dates=['game_date'])
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [7]:
df = df[(df.Date >= df2.game_date.min()) & (df.Date <= df2.game_date.max())]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [8]:
df.Team.value_counts().shape

(32,)

<font color='red'>  </font>

In [9]:
df.reset_index(drop=True)
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [10]:
print(df.Team.value_counts().shape)
df.Team.value_counts()

(32,)

Spurs           1070
Nuggets          860
Rockets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Celtics          783
Knicks           783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Bullets            1
Name: Team, dtype: int64

In [11]:
#Bullets and Hillard not in the nba
df = df[df.Team != 'Bullets']
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [12]:
df[df.Team.isnull()]

,Date,Team,Acquired,Relinquished,Notes
13007,2015-09-02,NaN,NaN,Glen Davis,surgery on left ankle to repair torn ligaments (out indefinitely)
13009,2015-09-03,NaN,NaN,Landry Fields,surgery on hip to repair torn labrum (out indefinitely)

In [13]:
#remove injured players not on a team. note: Davis & Fields do not return to an nba player roster
df = df[df.Team.notnull()]
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [14]:
df.reset_index(drop=True)

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [15]:
df4 = pd.read_csv(os.path.join('..', 'processed_data', '6team_id_abbreviation_nickname.csv'))
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats
31  1610612740          NOH       Hornets

In [16]:
df.shape

(22254, 5)

In [17]:
df_injuries = pd.merge(df, df4[['id', 'nickname']].drop([29]), left_on=['Team'], right_on=['nickname'], 
                       how='left').drop(columns='nickname')
df_injuries

,Date,Team,Acquired,Relinquished,Notes,id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751
...,...,...,...,...,...,...
22249,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season),1610612745
22250,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD),1610612739
22251,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL,1610612744
22252,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup,1610612739
22253,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup,1610612744

In [18]:
df_injuries.rename(columns={'id':'team_id'}, inplace=True)

In [19]:
print(df_injuries.shape)
df_injuries.head()

(22254, 6)

,Date,Team,Acquired,Relinquished,Notes,team_id
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely),1610612751

In [20]:
df_injuries.Team.value_counts()

Spurs           1070
Nuggets          860
Rockets          860
Nets             856
Cavaliers        852
Warriors         849
Bucks            834
Raptors          833
Heat             820
Lakers           809
Mavericks        794
Hawks            791
Celtics          783
Knicks           783
Wizards          738
Timberwolves     721
Magic            708
76ers            699
Grizzlies        689
Jazz             687
Bulls            680
Pacers           666
Kings            629
Hornets          607
Clippers         596
Suns             582
Thunder          579
Blazers          554
Pistons          533
Pelicans         423
Bobcats          369
Name: Team, dtype: int64

In [21]:
print(df2.shape)
df2.head()

(15519, 47)

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.0,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.0,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.0,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.0,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.0,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.0,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.0,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.0,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.0,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.5,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07

In [22]:
# df_injuries - team_id, player
# df2 - game_id, team_id, home and away stats
# nba_api player ratings/stats

In [23]:
df4

            id abbreviation      nickname
0   1610612737          ATL         Hawks
1   1610612738          BOS       Celtics
2   1610612739          CLE     Cavaliers
3   1610612740          NOP      Pelicans
4   1610612741          CHI         Bulls
5   1610612742          DAL     Mavericks
6   1610612743          DEN       Nuggets
7   1610612744          GSW      Warriors
8   1610612745          HOU       Rockets
9   1610612746          LAC      Clippers
10  1610612747          LAL        Lakers
11  1610612748          MIA          Heat
12  1610612749          MIL         Bucks
13  1610612750          MIN  Timberwolves
14  1610612751          BKN          Nets
15  1610612752          NYK        Knicks
16  1610612753          ORL         Magic
17  1610612754          IND        Pacers
18  1610612755          PHI         76ers
19  1610612756          PHX          Suns
20  1610612757          POR       Blazers
21  1610612758          SAC         Kings
22  1610612759          SAS         Spurs
23  1610612760          OKC       Thunder
24  1610612761          TOR       Raptors
25  1610612762          UTA          Jazz
26  1610612763          MEM     Grizzlies
27  1610612764          WAS       Wizards
28  1610612765          DET       Pistons
29  1610612766          CHA       Hornets
30  1610612766          CHA       Bobcats
31  1610612740          NOH       Hornets

In [24]:
df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
22252,2018-05-25,Rockets,NaN,Chris Paul,strained right hamstring (out for season)
22253,2018-05-26,Cavaliers,NaN,Kevin Love,concussion (DTD)
22254,2018-05-26,Warriors,Patrick McCaw,NaN,activated from IL
22255,2018-05-31,Cavaliers,Kevin Love,NaN,returned to lineup
22256,2018-06-06,Warriors,Andre Iguodala,NaN,returned to lineup

In [25]:
df[df.Acquired.notnull() & df.Relinquished.notnull()]

            Date   Team       Acquired   Relinquished               Notes
21690 2018-03-23  Hawks  John Collins   John Collins   returned to lineup

In [26]:
df_injuries.Acquired = df_injuries.Acquired.fillna('')

In [27]:
df_injuries.Relinquished = df_injuries.Relinquished.fillna('')

In [28]:
df_injuries['player'] = df_injuries.Acquired + df_injuries.Relinquished

In [29]:
print(df_injuries.shape)
df_injuries.head()

(22254, 7)

,Date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy

In [30]:
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [31]:
#df2 and df_injuries merge to get, e.g. 2010-11 season injuries
df_games1011 = df2[df2.season == '2010-11']
df_games1011

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
4920,21000001,2010-10-26,1610612738,1.000,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010.0,1610612748,0.000,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,Regular Season,2010-11
4921,21000002,2010-10-26,1610612757,1.000,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010.0,1610612756,0.000,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,Regular Season,2010-11
4922,21000003,2010-10-26,1610612747,1.000,240,40.0,96.0,0.417,9.0,21.0,0.429,23.0,28.0,1.0,14.0,30.0,44,21.0,11.0,4.0,12.0,24.0,112,2010.0,1610612745,0.000,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,Regular Season,2010-11
4923,21000004,2010-10-27,1610612739,1.000,240,36.0,81.0,0.444,6.0,20.0,0.300,17.0,21.0,1.0,8.0,29.0,37,24.0,5.0,4.0,14.0,20.0,95,2010.0,1610612738,0.500,240,34.0,72.0,0.472,3.0,12.0,0.250,16.0,21.0,1.0,6.0,32.0,38,24.0,8.0,1.0,19.0,24.0,87,Regular Season,2010-11
4924,21000005,2010-10-27,1610612751,1.000,240,39.0,80.0,0.488,6.0,14.0,0.429,17.0,24.0,1.0,9.0,35.0,44,17.0,4.0,4.0,11.0,23.0,101,2010.0,1610612765,0.000,240,37.0,83.0,0.446,8.0,19.0,0.421,16.0,30.0,1.0,10.0,27.0,37,21.0,7.0,3.0,6.0,19.0,98,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14928,41000402,2011-06-02,1610612748,0.765,240,34.0,73.0,0.466,9.0,30.0,0.300,16.0,24.0,1.0,6.0,24.0,30,13.0,15.0,6.0,12.0,17.0,93,2010.0,1610612742,0.765,240,36.0,75.0,0.480,6.0,17.0,0.353,17.0,21.0,1.0,11.0,30.0,41,18.0,8.0,2.0,18.0,20.0,95,Playoffs,2010-11
14929,41000403,2011-06-05,1610612742,0.722,240,28.0,70.0,0.400,8.0,21.0,0.381,22.0,27.0,1.0,12.0,30.0,42,18.0,3.0,8.0,14.0,14.0,86,2010.0,1610612748,0.778,240,34.0,78.0,0.436,8.0,19.0,0.421,12.0,15.0,1.0,9.0,27.0,36,20.0,8.0,5.0,10.0,27.0,88,Playoffs,2010-11
14930,41000404,2011-06-07,1610612742,0.737,240,29.0,73.0,0.397,4.0,19.0,0.211,24.0,30.0,1.0,12.0,29.0,41,13.0,7.0,2.0,11.0,18.0,86,2010.0,1610612748,0.737,240,32.0,75.0,0.427,2.0,14.0,0.143,17.0,24.0,1.0,15.0,29.0,44,19.0,8.0,5.0,13.0,23.0,83,Playoffs,2010-11
14931,41000405,2011-06-09,1610612742,0.750,240,39.0,69.0,0.565,13.0,19.0,0.684,21.0,27.0,1.0,4.0,22.0,26,23.0,8.0,3.0,11.0,20.0,112,2010.0,1610612748,0.700,240,37.0,70.0,0.529,8.0,20.0,0.400,21.0,26.0,1.0,9.0,27.0,36,25.0,5.0,4.0,16.0,26.0,103,Playoffs,2010-11
14932,41000406,2011-06-12,1610612748,0.667,240,34.0,72.0,0.472,7.0,23.0,0.304,20.0,33.0,1.0,9.0,30.0,39,20.0,7.0,3.0,16.0,14.0,95,2010.0,1610612742,0.762,240,41.0,82.0,0.500,11.0,26.0,0.423,12.0,18.0,1.0,10.0,30.0,40,19.0,11.0,1.0,14.0,24.0,105,Playoffs,2010-11

In [32]:
print(df_games1011.game_date.min())
print()
print(df_games1011.game_date.max())

2010-10-26 00:00:00

2011-06-12 00:00:00

In [33]:
df_injuries.rename(columns={'Date':'game_date'})

,game_date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love
22251,2018-05-26,Warriors,Patrick McCaw,,activated from IL,1610612744,Patrick McCaw
22252,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,1610612739,Kevin Love
22253,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,1610612744,Andre Iguodala

In [34]:
df_injuries1011 = pd.merge(df_injuries.rename(columns={'Date':'game_date'}), df_games1011[['game_date', 'game_id']], on='game_date', how='inner')
df_injuries1011

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000002
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000003
3,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,21000001
4,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,21000002
...,...,...,...,...,...,...,...,...
23043,2011-06-05,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000403
23044,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,41000404
23045,2011-06-07,Mavericks,Brendan Haywood,,activated from IL,1610612742,Brendan Haywood,41000404
23046,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,41000405
23047,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405

In [35]:
df_or1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2010_2018.csv'))
df_or1018

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [36]:
#filtered for games we have offensive rating
df_injuries1011_or = pd.merge(df_injuries1011, df_or1018.rename(columns={'GAME_ID':'game_id'})[['game_id', 'E_OFF_RATING']], how='inner', on='game_id')
df_injuries1011_or

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id,E_OFF_RATING
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,91.3
1,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,86.7
2,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,49.1
3,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,81.9
4,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000001,73.9
...,...,...,...,...,...,...,...,...,...
552292,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,115.3
552293,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,137.7
552294,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN
552295,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN
552296,2011-06-09,Mavericks,Rodrigue Beaubois,,activated from IL,1610612742,Rodrigue Beaubois,41000405,NaN

In [37]:
df_injuries1011_or.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 552297 entries, 0 to 552296
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   game_date     552297 non-null  datetime64[ns]
 1   Team          552297 non-null  object
 2   Acquired      552297 non-null  object
 3   Relinquished  552297 non-null  object
 4   Notes         552297 non-null  object
 5   team_id       552297 non-null  int64
 6   player        552297 non-null  object
 7   game_id       552297 non-null  int64
 8   E_OFF_RATING  469724 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 42.1+ MB

In [38]:
552297 - 469724

82573

In [39]:
#injury dataset for 2010-2018

#get average offensive rating per play for the 2009-2010 season for edge case: DataFrame w/ 'Player', 'Offensive Rating'

#injury dataset add a column for (average) offensive rating (for this season so far or previous season if data for this
#season if lacking
    #merge injury dataset with offensive rating data by date and player.
    
    #what does offensive rating look like for player not playing due to injury or just not playing?



#offensive rating

In [40]:

#Get game_date range for 2010-11 season by game dataset

#Get game_ids for 2010-11 season

#Get offensive rating per player per game by merge on game_id

#///

#From injuries df, want only player relinquished dates

#//

#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

#——->get player game_id, game_date for that season by merge relinquished players of df_injuries on df_or1011

In [41]:
#Get game_date range for 2010-11 season by game dataset

In [42]:
startdate_1011 = df2[df2.season == '2010-11'].game_date.min() 
startdate_1011

Timestamp('2010-10-26 00:00:00')

In [43]:
enddate_1011 = df2[df2.season == '2010-11'].game_date.max()
enddate_1011

Timestamp('2011-06-12 00:00:00')

In [44]:
startdate_1011 = df2[df2.season == '2011-12'].game_date.min() 
startdate_1011

Timestamp('2011-12-25 00:00:00')

In [45]:
enddate_1011 = df2[df2.season == '2011-12'].game_date.max()
enddate_1011

Timestamp('2012-06-21 00:00:00')

In [46]:
#Get game_ids for 2010-11 season
game_ids_1011 = df2[df2.season == '2010-11'].game_id
game_ids_1011

4920     21000001
4921     21000002
4922     21000003
4923     21000004
4924     21000005
           ...
14928    41000402
14929    41000403
14930    41000404
14931    41000405
14932    41000406
Name: game_id, Length: 1311, dtype: int64

In [47]:
#Get offensive rating per player per game by merge on game_id

In [48]:
df_or1011 = pd.merge(df_or1018.rename(columns={'GAME_ID':'game_id'}), game_ids_1011, on='game_id')[['game_id', 'TEAM_ID','PLAYER_NAME',
                                                                                        'E_OFF_RATING']]
df_or1011

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING
0      21000001  1.610613e+09   LeBron James          91.3
1      21000001  1.610613e+09     Chris Bosh          86.7
2      21000001  1.610613e+09   Joel Anthony          49.1
3      21000001  1.610613e+09    Dwyane Wade          81.9
4      21000001  1.610613e+09  Carlos Arroyo          73.9
...         ...           ...            ...           ...
31414  41000406  1.610613e+09   Juwan Howard          85.0
31415  41000406  1.610613e+09    Eddie House          99.2
31416  41000406  1.610613e+09     Mike Bibby           NaN
31417  41000406  1.610613e+09  Erick Dampier           NaN
31418  41000406  1.610613e+09    James Jones           NaN

[31419 rows x 4 columns]

In [49]:
#From injuries df, want only player relinquished dates
df_inj = df_injuries[df_injuries.Relinquished.notnull() & (df_injuries.Relinquished != '')]
df_inj

,Date,Team,Acquired,Relinquished,Notes,team_id,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),1610612741,Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),1610612765,Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),1610612765,Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),1610612757,Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),1610612751,Troy Murphy
...,...,...,...,...,...,...,...
22246,2018-05-09,Celtics,,Shane Larkin,sprained left shoulder (out for season),1610612738,Shane Larkin
22247,2018-05-09,Thunder,,Paul George,arthroscopic surgery on right knee (out indefinitely),1610612760,Paul George
22248,2018-05-22,Warriors,,Andre Iguodala,bruised left leg (DTD),1610612744,Andre Iguodala
22249,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),1610612745,Chris Paul
22250,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),1610612739,Kevin Love

In [50]:
#Create new data frame with all game_id, game_date for 2010-11 season. Add column offensive_rating_lost

In [51]:
#—>get offensive rating for player for that season preceding relinquish date (assuming not acquired on the same date)
#  by the df_or1011 dataframe

<font color='red'>this dataframe include player never injuried also??? -yes</font>

In [52]:
df_or1011a = pd.merge(df_or1011 , df2[df2.season == '2010-11'][['game_id', 'game_date']], on='game_id', how='inner')
df_or1011a

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1.610613e+09   LeBron James          91.3 2010-10-26
1      21000001  1.610613e+09     Chris Bosh          86.7 2010-10-26
2      21000001  1.610613e+09   Joel Anthony          49.1 2010-10-26
3      21000001  1.610613e+09    Dwyane Wade          81.9 2010-10-26
4      21000001  1.610613e+09  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1.610613e+09   Juwan Howard          85.0 2011-06-12
31415  41000406  1.610613e+09    Eddie House          99.2 2011-06-12
31416  41000406  1.610613e+09     Mike Bibby           NaN 2011-06-12
31417  41000406  1.610613e+09  Erick Dampier           NaN 2011-06-12
31418  41000406  1.610613e+09    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

In [53]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  float64
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 1.4+ MB

In [54]:
df_or1011a.TEAM_ID = df_or1011a.TEAM_ID.astype(str)
df_or1011a

        game_id       TEAM_ID    PLAYER_NAME  E_OFF_RATING  game_date
0      21000001  1610612748.0   LeBron James          91.3 2010-10-26
1      21000001  1610612748.0     Chris Bosh          86.7 2010-10-26
2      21000001  1610612748.0   Joel Anthony          49.1 2010-10-26
3      21000001  1610612748.0    Dwyane Wade          81.9 2010-10-26
4      21000001  1610612748.0  Carlos Arroyo          73.9 2010-10-26
...         ...           ...            ...           ...        ...
31414  41000406  1610612748.0   Juwan Howard          85.0 2011-06-12
31415  41000406  1610612748.0    Eddie House          99.2 2011-06-12
31416  41000406  1610612748.0     Mike Bibby           NaN 2011-06-12
31417  41000406  1610612748.0  Erick Dampier           NaN 2011-06-12
31418  41000406  1610612748.0    James Jones           NaN 2011-06-12

[31419 rows x 5 columns]

In [55]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  object
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 1.4+ MB

In [56]:
df_or1011a['cma1'] = df_or1011a.E_OFF_RATING.expanding(min_periods=1).mean()
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451

In [57]:
df_or1011a['cma2'] = df_or1011a.groupby('PLAYER_NAME')['E_OFF_RATING'].transform(lambda x: x.expanding(min_periods=1).mean())
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma1,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,89.000000,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,75.700000,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,77.250000,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,76.580000,73.900000
...,...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,102.209564,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,102.209451,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,102.209451,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,102.209451,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,102.209451,108.415054

In [58]:
df_or1011a.drop(columns='cma1', inplace=True)
df_or1011a

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
0,21000001,1610612748.0,LeBron James,91.3,2010-10-26,91.300000
1,21000001,1610612748.0,Chris Bosh,86.7,2010-10-26,86.700000
2,21000001,1610612748.0,Joel Anthony,49.1,2010-10-26,49.100000
3,21000001,1610612748.0,Dwyane Wade,81.9,2010-10-26,81.900000
4,21000001,1610612748.0,Carlos Arroyo,73.9,2010-10-26,73.900000
...,...,...,...,...,...,...
31414,41000406,1610612748.0,Juwan Howard,85.0,2011-06-12,101.564706
31415,41000406,1610612748.0,Eddie House,99.2,2011-06-12,101.053968
31416,41000406,1610612748.0,Mike Bibby,NaN,2011-06-12,104.171000
31417,41000406,1610612748.0,Erick Dampier,NaN,2011-06-12,103.958824
31418,41000406,1610612748.0,James Jones,NaN,2011-06-12,108.415054

In [59]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  object
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
 5   cma2          31259 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 1.7+ MB

In [60]:
df_gamess1011 = pd.read_csv(os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv'), parse_dates=['game_date'])
df_gamess1011 = df_gamess1011[(df_gamess1011.season_type == 'Regular Season') 
                              | (df_gamess1011.season_type == 'Playoffs')][(df_gamess1011.season == '2010-11')][['game_id', 'game_date','team_id']]
df_gamess1011

        game_id  game_date     team_id
9840   21000001 2010-10-26  1610612738
9841   21000001 2010-10-26  1610612748
9842   21000002 2010-10-26  1610612757
9843   21000002 2010-10-26  1610612756
9844   21000003 2010-10-26  1610612745
...         ...        ...         ...
29861  41000404 2011-06-07  1610612748
29862  41000405 2011-06-09  1610612742
29863  41000405 2011-06-09  1610612748
29864  41000406 2011-06-12  1610612748
29865  41000406 2011-06-12  1610612742

[2622 rows x 3 columns]

In [61]:
df_gamess1011.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2622 entries, 9840 to 29865
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_id    2622 non-null   int64
 1   game_date  2622 non-null   datetime64[ns]
 2   team_id    2622 non-null   int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 81.9 KB

In [62]:
df_inj2 = pd.merge(df_inj.rename(columns={'Date':'game_date'}), df_gamess1011, on=['game_date', 'team_id'], how='inner')
df_inj2

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
0,2010-10-26,Blazers,,Elliot Williams,placed on IL,1610612757,Elliot Williams,21000002
1,2010-10-26,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),1610612757,Greg Oden,21000002
2,2010-10-26,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,1610612757,Joel Przybilla,21000002
3,2010-10-26,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,1610612738,Avery Bradley,21000001
4,2010-10-26,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,1610612738,Kendrick Perkins,21000001
...,...,...,...,...,...,...,...,...
1688,2011-05-26,Bulls,,Omer Asik,placed on IL with stress fracture in left fibula (out for season),1610612741,Omer Asik,41000305
1689,2011-05-31,Heat,,Zydrunas Ilgauskas,placed on IL,1610612748,Zydrunas Ilgauskas,41000401
1690,2011-06-05,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor,1610612742,Brendan Haywood,41000403
1691,2011-06-07,Mavericks,,Rodrigue Beaubois,placed on IL,1610612742,Rodrigue Beaubois,41000404
1692,2011-06-09,Mavericks,,Brendan Haywood,placed on IL with strained right hip flexor (out for season),1610612742,Brendan Haywood,41000405

In [63]:
df_inj3 = df_inj2.drop(columns=['Notes', 'Acquired', 'Relinquished'])

In [64]:
df_inj3

      game_date       Team     team_id              player   game_id
0    2010-10-26    Blazers  1610612757     Elliot Williams  21000002
1    2010-10-26    Blazers  1610612757           Greg Oden  21000002
2    2010-10-26    Blazers  1610612757      Joel Przybilla  21000002
3    2010-10-26    Celtics  1610612738       Avery Bradley  21000001
4    2010-10-26    Celtics  1610612738    Kendrick Perkins  21000001
...         ...        ...         ...                 ...       ...
1688 2011-05-26      Bulls  1610612741           Omer Asik  41000305
1689 2011-05-31       Heat  1610612748  Zydrunas Ilgauskas  41000401
1690 2011-06-05  Mavericks  1610612742     Brendan Haywood  41000403
1691 2011-06-07  Mavericks  1610612742   Rodrigue Beaubois  41000404
1692 2011-06-09  Mavericks  1610612742     Brendan Haywood  41000405

[1693 rows x 5 columns]

In [65]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '6injuries_2010-11.csv')
if not os.path.exists(datapath_df):
    df_inj3.to_csv(datapath_df, index=False)

In [66]:
set(df_inj3.player)

{' Tony Parker',
 'A.J. Price',
 'Aaron Brooks',
 'Aaron Gray',
 'Acie Law',
 'Al Harrington',
 'Al Horford',
 'Al Thornton',
 'Alex Ajinca',
 'Alonzo Gee',
 "Amar'e Stoudemire",
 'Amir Johnson',
 'Anderson Varejao',
 'Andray Blatche',
 'Andre Iguodala',
 'Andrea Bargnani',
 'Andrei Kirilenko',
 'Andres Nocioni',
 'Andrew Bogut',
 'Andrew Bynum',
 'Andris Biedrins',
 'Andy Rautins',
 'Antawn Jamison',
 'Anthony Carter',
 'Anthony Morrow',
 'Anthony Parker',
 'Anthony Randolph',
 'Anthony Tolliver',
 'Antoine Wright',
 'Antonio McDyess',
 'Armon Johnson',
 'Arron Afflalo',
 'Austin Daye',
 'Avery Bradley',
 'B.J. Mullens',
 'Baron Davis',
 'Ben Uzoh',
 'Ben Wallace',
 'Beno Udrih',
 'Bill Walker',
 'Brad Miller',
 'Brandan Wright',
 'Brandon Bass',
 'Brandon Jennings',
 'Brandon Roy',
 'Brandon Rush',
 'Brendan Haywood',
 'Brian Cardinal',
 'Brian Cook',
 'Brian Scalabrine',
 'Brian Skinner',
 'C.J. Miles',
 'Carlos Arroyo',
 'Carlos Boozer',
 'Carlos Delfino',
 'Carmelo Anthony',
 'Caron Butler',
 'Cartier Martin',
 'Channing Frye',
 'Charlie Bell',
 'Charlie Villanueva',
 'Chase Budinger',
 'Chauncey Billups',
 'Chris Andersen',
 'Chris Bosh',
 'Chris Douglas-Roberts',
 'Chris Duhon',
 'Chris Kaman',
 'Chris Paul',
 'Chris Quinn',
 'Chris Wilcox',
 'Christian Eyenga',
 'Chuck Hayes',
 'Cole Aldrich',
 'Corey Brewer',
 'Corey Maggette',
 'Courtney Lee',
 'Craig Brackins',
 'Craig Smith',
 'D.J. White',
 "Da'Sean Butler",
 'DaJuan Summers',
 'Daequan Cook',
 'Dahntay Jones',
 'Damien Wilkins',
 'Damion James',
 'Dan Gadzuric',
 'Daniel Gibson',
 'Daniel Orton',
 'Danilo Gallinari',
 'Danny Granger',
 'Danny Green',
 'Dante Cunningham',
 'Darius Songaila',
 'Darko Milicic',
 'Darrell Arthur',
 'Darren Collison',
 'David Andersen',
 'David Lee',
 'David West',
 'DeAndre Jordan',
 'DeJuan Blair',
 'DeMarre Carroll',
 'DeSagana Diop',
 'Delonte West',
 'Deron Williams',
 'Derrick Brown',
 'Derrick Caracter',
 'Derrick Favors',
 'Derrick Rose',
 'Devin Ebanks',
 'Devin Harris',
 'Dexter Pittman',
 'Didier Mbenga ',
 'Dirk Nowitzki',
 'Dominic McGuire',
 'Dominique Jones',
 'Drew Gooden',
 'Dwight Howard',
 'Dwyane Wade',
 'Ed Davis ',
 'Eddy Curry',
 'Eduardo Najera',
 'Ekpe Udoh',
 'Elliot Williams',
 'Emeka Okafor',
 'Eric Gordon',
 'Erick Dampier',
 'Ersan Ilyasova',
 'Etan Thomas',
 'Francisco Elson',
 'Francisco Garcia',
 'Gani Lawal',
 'Garret Siler',
 'Garrett Temple',
 'Gary Neal',
 'George Hill',
 'Gerald Henderson Jr.',
 'Gerald Wallace',
 'Gilbert Arenas',
 'Glen Davis',
 'Goran Dragic',
 'Gordon Hayward',
 'Grant Hill',
 'Greg Oden',
 'Greivis Vasquez',
 "Hamady N'Diaye",
 'Hamed Haddadi',
 'Hasheem Thabeet',
 'Hassan Whiteside',
 'Hilton Armstrong',
 'Ian Mahinmi',
 'Ish Smith',
 'J.J. Hickson',
 'J.J. Redick',
 'JaVale McGee',
 'Jamaal Magloire',
 'Jamal Crawford',
 'Jamario Moon',
 'Jameer Nelson',
 'James Anderson',
 'James Posey',
 'Jannero Pargo',
 'Jared Jeffries',
 'Jason Collins',
 'Jason Kapono',
 'Jason Kidd',
 'Jason Maxiell',
 'Jason Richardson',
 'Jason Smith',
 'Jason Thompson',
 'Jason Williams',
 'Jeff Adrien',
 'Jeff Foster',
 'Jeff Green',
 'Jerel McNeal',
 'Jeremy Evans',
 'Jeremy Lin',
 "Jermaine O'Neal",
 'Jermaine Taylor',
 'Jerry Stackhouse',
 'Jerryd Bayless',
 'Jianlian Yi',
 'Joakim Noah',
 'Jodie Meeks',
 'Joe Alexander',
 'Joe Johnson',
 'Joe Smith ',
 'Joel Przybilla',
 'Joey Dorsey',
 'Joey Graham',
 'John Lucas III',
 'John Salmons',
 'John Wall ',
 'John Wallace',
 'Jon Brockman',
 'Jonas Jerebko',
 'Jonny Flynn',
 'Jordan Crawford',
 'Jordan Farmar',
 'Jordan Hill',
 'Jose Barea ',
 'Jose Calderon',
 'Josh Howard',
 'Josh McRoberts',
 'Josh Powell',
 'Josh Smith',
 'Julian Wright',
 'Juwan Howard',
 'Kelenna Azubuike',
 'Kendrick Perkins',
 'Kenyon Martin',
 'Kevin Durant',
 'Kevin Garnett',
 'Kevin Love',
 'Kevin Martin',
 'Kevin Seraphin',
 'Keyon Dooling',
 'Kirk Hinrich',
 'Kosta Koufos',
 'Kris Humphries',
 'Kurt Thomas',
 'Kwame Brown',
 'Kyle Lowry',
 'Kyrylo Fesenko',
 'LaMarcus Aldridge',
 'Lance Stephenson',
 'Larry Sanders ',
 'Lazar Hayward',
 'LeBron James',
 'Leandro Barbosa',
 'Leon Powe',
 'Lester Hudson',
 'Linas Kleiza',
 'Lou Amundson',
 'Lou Williams',
 'Luc Mbah a Moute',
 'Luis Scola',
 'Luke Babbitt',
 'Luke Harangody',
 'Luke Ridnour',
 'Luke Walton',
 'Luther Head',
 'Magnum Rolle',
 'Malik Allen',
 'Manny Harris',
 'Manu Ginobili',
 'Marc Gasol',
 'Marco Belinelli',
 'Marcus Banks',
 'Marcus Camby',
 'Marcus Thornton ',
 'Mario Chalmers',
 'Mario West',
 'Marquis Daniels',
 'Martell Webster',
 'Marvin Williams',
 'Matt Barnes',
 'Matt Bonner',
 'Matt Carroll',
 'Matt Janning',
 'Maurice Ager',
 'Maurice Evans',
 'Mehmet Okur',
 'Melvin Ely',
 'Michael Beasley',
 'Michael Redd',
 'Mickael Pietrus',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Mike Miller',
 'Mo Williams',
 'Monta Ellis',
 'Morris Peterson',
 'Mustafa Shakur',
 'Nate Robinson',
 'Nazr Mohammed',
 'Nenad Krstic',
 'Nene Hilario ',
 'Nick Collison',
 'Nick Young',
 'Nicolas Batum',
 'Nikola Pekovic',
 'O.J. Mayo',
 'Omer Asik',
 'Omri Casspi',
 'Orien Greene',
 'Othyus Jeffers',
 'Pape Sy',
 'Patrick Patterson',
 'Patty Mills',
 'Paul George',
 'Paul Millsap',
 'Paul Pierce',
 'Peja Stojakovic',
 'Pooh Jeter',
 'Pops Mensah-Bonsu',
 'Quentin Richardson',
 'Quincy Pondexter',
 'Quinton Ross',
 'Raja Bell',
 'Rajon Rondo',
 'Randy Foye',
 'Rashard Lewis',
 'Rasual Butler',
 'Ray Allen',
 'Raymond Felton',
 'Reggie Evans',
 'Reggie Williams',
 'Renaldo Balkman',
 'Richard Hamilton',
 'Robert Vaden',
 'Robin Lopez',
 'Rodney Carney',
 'Rodney Stuckey',
 'Rodrigue Beaubois',
 'Roger Mason Jr.',
 'Ronnie Brewer',
 'Ronnie Price',
 'Ronny Turiaf',
 'Roy Hibbert',
 'Rudy Fernandez',
 'Rudy Gay',
 'Ryan Anderson',
 'Ryan Gomes',
 'Ryan Hollins',
 'Samardo Samuels',
 'Samuel Dalembert',
 'Sasha Vujacic',
 'Sean Marks',
 'Sebastian Telfair',
 'Semih Erden',
 "Shaquille O'Neal",
 'Shaun Livingston',
 'Shawn Marion',
 'Shawne Williams',
 'Shelden Williams',
 'Sherron Collins',
 'Solomon Alabi',
 'Solomon Jones',
 'Sonny Weems',
 'Spencer Hawes',
 'Stephen Curry',
 'Stephen Graham',
 'Stephen Jackson',
 'Steve Blake',
 'Steve Nash',
 'Steve Novak',
 'Sundiata Gaines',
 'T.J. Ford',
 'Taj Gibson',
 'Tayshaun Prince',
 'Terrence Williams',
 'Terrico White',
 'Thabo Sefolosha',
 'Theo Ratliff',
 'Tiago Splitter',
 'Tim Duncan',
 'Timofey Mozgov',
 'Toney Douglas',
 'Tony Allen',
 'Tony Battie',
 'Tracy McGrady',
 'Trevor Ariza',
 'Trevor Booker',
 'Trey Johnson',
 'Troy Murphy',
 'Ty Lawson',
 'Tyler Hansbrough',
 'Tyreke Evans',
 'Tyrus Thomas',
 'Tyson Chandler',
 'Udonis Haslem',
 'Vince Carter',
 'Von Wafer',
 'Wayne Ellington',
 'Wes Johnson',
 'Will Bynum',
 'Willie Warren',
 'Wilson Chandler',
 'Xavier Henry',
 'Yao Ming',
 'Zabian Dowdell',
 'Zach Randolph',
 'Zaza Pachulia',
 'Zydrunas Ilgauskas'}

In [67]:
len(set(df_inj3.player))

386

In [68]:
#check player (name) similarity with player of df_inj3


#check for player (name) similiarty with player of df_or1011a

In [69]:
#check player (name) similarity with player of df_inj3
import numpy as np

In [70]:
unique_player = df_inj3.player.unique().tolist()
sorted(unique_player)[:20]

[' Tony Parker',
 'A.J. Price',
 'Aaron Brooks',
 'Aaron Gray',
 'Acie Law',
 'Al Harrington',
 'Al Horford',
 'Al Thornton',
 'Alex Ajinca',
 'Alonzo Gee',
 "Amar'e Stoudemire",
 'Amir Johnson',
 'Anderson Varejao',
 'Andray Blatche',
 'Andre Iguodala',
 'Andrea Bargnani',
 'Andrei Kirilenko',
 'Andres Nocioni',
 'Andrew Bogut',
 'Andrew Bynum']

In [71]:
unique_player2 = df_or1011a['PLAYER_NAME'].unique().tolist()
sorted(unique_player2)[:20]

['AJ Price',
 'Aaron Brooks',
 'Aaron Gray',
 'Acie Law',
 'Al Harrington',
 'Al Horford',
 'Al Jefferson',
 'Al Thornton',
 'Al-Farouq Aminu',
 'Alexis Ajinca',
 'Alonzo Gee',
 "Amar'e Stoudemire",
 'Amir Johnson',
 'Anderson Varejao',
 'Andray Blatche',
 'Andre Iguodala',
 'Andre Miller',
 'Andrea Bargnani',
 'Andrei Kirilenko',
 'Andres Nocioni']

In [72]:
df_inj3[df_inj3.player == 'J.J. Hickson']

     game_date       Team     team_id        player   game_id
342 2010-12-04  Cavaliers  1610612739  J.J. Hickson  21000291

In [73]:
df_inj3[df_inj3.player == 'J.J. Redick']

      game_date   Team     team_id       player   game_id
206  2010-11-15  Magic  1610612753  J.J. Redick  21000145
318  2010-12-01  Magic  1610612753  J.J. Redick  21000266
335  2010-12-03  Magic  1610612753  J.J. Redick  21000279
345  2010-12-04  Magic  1610612753  J.J. Redick  21000292
880  2011-01-31  Magic  1610612753  J.J. Redick  21000711
1222 2011-03-11  Magic  1610612753  J.J. Redick  21000975
1268 2011-03-16  Magic  1610612753  J.J. Redick  21001007
1276 2011-03-18  Magic  1610612753  J.J. Redick  21001018
1307 2011-03-21  Magic  1610612753  J.J. Redick  21001044
1320 2011-03-23  Magic  1610612753  J.J. Redick  21001059
1339 2011-03-25  Magic  1610612753  J.J. Redick  21001069
1371 2011-03-28  Magic  1610612753  J.J. Redick  21000051
1393 2011-03-30  Magic  1610612753  J.J. Redick  21001105
1420 2011-04-01  Magic  1610612753  J.J. Redick  21001121
1443 2011-04-03  Magic  1610612753  J.J. Redick  21001144
1467 2011-04-05  Magic  1610612753  J.J. Redick  21001152
1482 2011-04-06  Magic  1610612753  J.J. Redick  21001162
1538 2011-04-10  Magic  1610612753  J.J. Redick  21001193
1564 2011-04-11  Magic  1610612753  J.J. Redick  21001204
1628 2011-04-13  Magic  1610612753  J.J. Redick  21001219

In [74]:
df_or1011a[df_or1011a.PLAYER_NAME == 'J.J. Redick']

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [75]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('J.J. Redick')]

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [76]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('JJ Redick')].sort_values(by='game_date')

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
402    21000017  1610612753.0   JJ Redick          95.4 2010-10-28   95.400000
581    21000025  1610612753.0   JJ Redick          90.3 2010-10-29   92.850000
1341   21000056  1610612753.0   JJ Redick         142.8 2010-11-03  109.500000
1653   21000069  1610612753.0   JJ Redick         107.5 2010-11-05  109.000000
1905   21000080  1610612753.0   JJ Redick          61.5 2010-11-06   99.500000
2299   21000096  1610612753.0   JJ Redick          94.1 2010-11-08   98.600000
2613   21000109  1610612753.0   JJ Redick          58.9 2010-11-10   92.928571
2944   21000123  1610612753.0   JJ Redick         103.5 2010-11-12   94.250000
3128   21000131  1610612753.0   JJ Redick          88.0 2010-11-13   93.555556
4376   21000183  1610612753.0   JJ Redick          82.6 2010-11-20   92.460000
4755   21000199  1610612753.0   JJ Redick         113.4 2010-11-22   94.363636
5101   21000213  1610612753.0   JJ Redick         115.4 2010-11-24   96.116667
5341   21000223  1610612753.0   JJ Redick         112.6 2010-11-26   97.384615
5617   21000235  1610612753.0   JJ Redick         120.2 2010-11-27   99.014286
6113   21000255  1610612753.0   JJ Redick         121.3 2010-11-30  100.500000
6681   21000279  1610612753.0   JJ Redick           NaN 2010-12-03  100.500000
6993   21000292  1610612753.0   JJ Redick           NaN 2010-12-04  100.500000
7264   21000303  1610612753.0   JJ Redick          86.7 2010-12-06   99.637500
7878   21000329  1610612753.0   JJ Redick          95.2 2010-12-09   99.376471
8117   21000339  1610612753.0   JJ Redick         105.8 2010-12-10   99.733333
8478   21000354  1610612753.0   JJ Redick         103.4 2010-12-12   99.926316
8740   21000365  1610612753.0   JJ Redick         104.2 2010-12-14  100.140000
9397   21000392  1610612753.0   JJ Redick          92.0 2010-12-18   99.752381
9725   21000406  1610612753.0   JJ Redick          56.6 2010-12-20   97.790909
9971   21000416  1610612753.0   JJ Redick         123.1 2010-12-21   98.891304
10309  21000430  1610612753.0   JJ Redick         107.3 2010-12-23   99.241667
10406  21000434  1610612753.0   JJ Redick         103.8 2010-12-25   99.424000
10682  21000446  1610612753.0   JJ Redick         114.1 2010-12-27   99.988462
10898  21000455  1610612753.0   JJ Redick         104.1 2010-12-28  100.140741
11342  21000473  1610612753.0   JJ Redick         122.0 2010-12-30  100.921429
11989  21000500  1610612753.0   JJ Redick         117.6 2011-01-03  101.496552
12326  21000514  1610612753.0   JJ Redick         102.1 2011-01-05  101.516667
12681  21000529  1610612753.0   JJ Redick          98.4 2011-01-07  101.416129
12978  21000542  1610612753.0   JJ Redick         106.6 2011-01-08  101.578125
13571  21000567  1610612753.0   JJ Redick          89.3 2011-01-12  101.206061
13741  21000574  1610612753.0   JJ Redick         145.3 2011-01-13  102.502941
14193  21000593  1610612753.0   JJ Redick          97.3 2011-01-15  102.354286
14553  21000608  1610612753.0   JJ Redick         117.3 2011-01-17  102.769444
14734  21000615  1610612753.0   JJ Redick         103.4 2011-01-19  102.786486
15092  21000630  1610612753.0   JJ Redick         123.5 2011-01-21  103.331579
15513  21000648  1610612753.0   JJ Redick         117.9 2011-01-22  103.705128
15670  21000654  1610612753.0   JJ Redick         116.4 2011-01-24  104.022500
15993  21000668  1610612753.0   JJ Redick         119.0 2011-01-26  104.387805
16449  21000687  1610612753.0   JJ Redick          96.9 2011-01-28  104.209524
16844  21000703  1610612753.0   JJ Redick         105.0 2011-01-30  104.227907
17030  21000711  1610612753.0   JJ Redick           NaN 2011-01-31  104.227907
17497  21000730  1610612753.0   JJ Redick          91.9 2011-02-03  103.947727
17650  21000737  1610612753.0   JJ Redick          91.7 2011-02-04  103.675556
18128  21000757  1610612753.0   JJ Redick          76.4 2011-02-06  103.082609
18378  21000767  1610612753.0   JJ Redick         116.5 2011-02-08  103.368085
18583  21000776  1610612753.0   JJ Redick         100.1 2011-02-09  103.300000
18881  21000788  1610612753.0   JJ Redick          85.2 2011-02-11  102.930612
19290  21000805  1610612753.0   JJ Redick          91.9 2011-02-13  102.710000
19743  21000824  1610612753.0   JJ Redick         114.5 2011-02-16  102.941176
20344  21000849  1610612753.0   JJ Redick         106.0 2011-02-23  103.000000
20772  21000867  1610612753.0   JJ Redick         120.7 2011-02-25  103.333962
21155  21000883  1610612753.0   JJ Redick         119.9 2011-02-27  103.640741
21440  21000895  1610612753.0   JJ Redick         106.9 2011-03-01  103.700000
21837  21000912  1610612753.0   JJ Redick          98.0 2011-03-03  103.598214
21923  21000915  1610612753.0   JJ Redick          94.4 2011-03-04  103.436842
22544  21000941  1610612753.0   JJ Redick          98.3 2011-03-07  103.348276
23058  21000963  1610612753.0   JJ Redick          80.6 2011-03-09  102.962712
23349  21000975  1610612753.0   JJ Redick           NaN 2011-03-11  102.962712
23635  21000987  1610612753.0   JJ Redick           NaN 2011-03-13  102.962712
23923  21000999  1610612753.0   JJ Redick           NaN 2011-03-14  102.962712
24115  21001007  1610612753.0   JJ Redick           NaN 2011-03-16  102.962712
24391  21001018  1610612753.0   JJ Redick           NaN 2011-03-18  102.962712
25003  21001044  1610612753.0   JJ Redick           NaN 2011-03-21  102.962712
25362  21001059  1610612753.0   JJ Redick           NaN 2011-03-23  102.962712
25613  21001069  1610612753.0   JJ Redick           NaN 2011-03-25  102.962712
1210   21000051  1610612753.0   JJ Redick           NaN 2011-03-28   92.850000
26463  21001105  1610612753.0   JJ Redick           NaN 2011-03-30  102.962712
26860  21001121  1610612753.0   JJ Redick           NaN 2011-04-01  102.962712
27399  21001144  1610612753.0   JJ Redick           NaN 2011-04-03  102.962712
27603  21001152  1610612753.0   JJ Redick           NaN 2011-04-05  102.962712
27830  21001162  1610612753.0   JJ Redick           NaN 2011-04-06  102.962712
28585  21001193  1610612753.0   JJ Redick           NaN 2011-04-10  102.962712
28837  21001204  1610612753.0   JJ Redick           NaN 2011-04-11  102.962712
29210  21001219  1610612753.0   JJ Redick           NaN 2011-04-13  102.962712
29830  41000131  1610612753.0   JJ Redick         141.0 2011-04-16  103.596667
29855  41000132  1610612753.0   JJ Redick         119.9 2011-04-19  103.863934
29864  41000133  1610612753.0   JJ Redick          96.4 2011-04-22  103.743548
29888  41000134  1610612753.0   JJ Redick          89.5 2011-04-24  103.517460
29926  41000135  1610612753.0   JJ Redick         115.1 2011-04-26  103.698437
29937  41000136  1610612753.0   JJ Redick          92.5 2011-04-28  103.526154

In [77]:
#<>><><><><><><><><><><<><><><><><><><><><<><><><><><><><><><<><><><><><><><><><<><><><><><><><><><><><><<><><><><><><><><><<><><><><><><><><>

<font color='red'> will go with no dots version of name as in nba_api<font>

In [78]:
df_inj3[df_inj3.player == 'J.J. Redick']

      game_date   Team     team_id       player   game_id
206  2010-11-15  Magic  1610612753  J.J. Redick  21000145
318  2010-12-01  Magic  1610612753  J.J. Redick  21000266
335  2010-12-03  Magic  1610612753  J.J. Redick  21000279
345  2010-12-04  Magic  1610612753  J.J. Redick  21000292
880  2011-01-31  Magic  1610612753  J.J. Redick  21000711
1222 2011-03-11  Magic  1610612753  J.J. Redick  21000975
1268 2011-03-16  Magic  1610612753  J.J. Redick  21001007
1276 2011-03-18  Magic  1610612753  J.J. Redick  21001018
1307 2011-03-21  Magic  1610612753  J.J. Redick  21001044
1320 2011-03-23  Magic  1610612753  J.J. Redick  21001059
1339 2011-03-25  Magic  1610612753  J.J. Redick  21001069
1371 2011-03-28  Magic  1610612753  J.J. Redick  21000051
1393 2011-03-30  Magic  1610612753  J.J. Redick  21001105
1420 2011-04-01  Magic  1610612753  J.J. Redick  21001121
1443 2011-04-03  Magic  1610612753  J.J. Redick  21001144
1467 2011-04-05  Magic  1610612753  J.J. Redick  21001152
1482 2011-04-06  Magic  1610612753  J.J. Redick  21001162
1538 2011-04-10  Magic  1610612753  J.J. Redick  21001193
1564 2011-04-11  Magic  1610612753  J.J. Redick  21001204
1628 2011-04-13  Magic  1610612753  J.J. Redick  21001219

In [79]:
df_inj3.player.replace({'J.J. Redick':'JJ Redick'}, inplace=True)

In [80]:
df_inj3[df_inj3.player.str.contains('J.J. Redick')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [81]:
df_inj3[df_inj3.player.str.contains('JJ Redick')]

      game_date   Team     team_id     player   game_id
206  2010-11-15  Magic  1610612753  JJ Redick  21000145
318  2010-12-01  Magic  1610612753  JJ Redick  21000266
335  2010-12-03  Magic  1610612753  JJ Redick  21000279
345  2010-12-04  Magic  1610612753  JJ Redick  21000292
880  2011-01-31  Magic  1610612753  JJ Redick  21000711
1222 2011-03-11  Magic  1610612753  JJ Redick  21000975
1268 2011-03-16  Magic  1610612753  JJ Redick  21001007
1276 2011-03-18  Magic  1610612753  JJ Redick  21001018
1307 2011-03-21  Magic  1610612753  JJ Redick  21001044
1320 2011-03-23  Magic  1610612753  JJ Redick  21001059
1339 2011-03-25  Magic  1610612753  JJ Redick  21001069
1371 2011-03-28  Magic  1610612753  JJ Redick  21000051
1393 2011-03-30  Magic  1610612753  JJ Redick  21001105
1420 2011-04-01  Magic  1610612753  JJ Redick  21001121
1443 2011-04-03  Magic  1610612753  JJ Redick  21001144
1467 2011-04-05  Magic  1610612753  JJ Redick  21001152
1482 2011-04-06  Magic  1610612753  JJ Redick  21001162
1538 2011-04-10  Magic  1610612753  JJ Redick  21001193
1564 2011-04-11  Magic  1610612753  JJ Redick  21001204
1628 2011-04-13  Magic  1610612753  JJ Redick  21001219

In [82]:
#names with space(s) in the front

#names with space(s) in the back

#?remove periods?

#?remove apostrophes?

'''
*****************************************
A.J. Price
('AJ Price', 94)
0
*****************************************
Alex Ajinca
('Alexis Ajinca', 92)
1
*****************************************
C.J. Miles
('CJ Miles', 94)
2
*****************************************
D.J. White
('DJ White', 94)
3
*****************************************
Hamady N'Diaye
('Hamady Ndiaye', 89)
4
*****************************************
J.J. Hickson
('JJ Hickson', 95)
5
*****************************************
J.J. Redick
('JJ Redick', 94)
6
*****************************************
John Wallace
('John Wall', 86)
7
*****************************************
Jose Barea 
('J.J. Barea', 83)
8
*****************************************
Wes Johnson
('Wesley Johnson', 88)
9
'''

"\n*****************************************\nA.J. Price\n('AJ Price', 94)\n0\n*****************************************\nAlex Ajinca\n('Alexis Ajinca', 92)\n1\n*****************************************\nC.J. Miles\n('CJ Miles', 94)\n2\n*****************************************\nD.J. White\n('DJ White', 94)\n3\n*****************************************\nHamady N'Diaye\n('Hamady Ndiaye', 89)\n4\n*****************************************\nJ.J. Hickson\n('JJ Hickson', 95)\n5\n*****************************************\nJ.J. Redick\n('JJ Redick', 94)\n6\n*****************************************\nJohn Wallace\n('John Wall', 86)\n7\n*****************************************\nJose Barea \n('J.J. Barea', 83)\n8\n*****************************************\nWes Johnson\n('Wesley Johnson', 88)\n9\n"

In [83]:
'''
*****************************************
A.J. Price
('AJ Price', 94)
0
'''

df_inj3

      game_date       Team     team_id              player   game_id
0    2010-10-26    Blazers  1610612757     Elliot Williams  21000002
1    2010-10-26    Blazers  1610612757           Greg Oden  21000002
2    2010-10-26    Blazers  1610612757      Joel Przybilla  21000002
3    2010-10-26    Celtics  1610612738       Avery Bradley  21000001
4    2010-10-26    Celtics  1610612738    Kendrick Perkins  21000001
...         ...        ...         ...                 ...       ...
1688 2011-05-26      Bulls  1610612741           Omer Asik  41000305
1689 2011-05-31       Heat  1610612748  Zydrunas Ilgauskas  41000401
1690 2011-06-05  Mavericks  1610612742     Brendan Haywood  41000403
1691 2011-06-07  Mavericks  1610612742   Rodrigue Beaubois  41000404
1692 2011-06-09  Mavericks  1610612742     Brendan Haywood  41000405

[1693 rows x 5 columns]

In [84]:
df_inj3[df_inj3.player == 'A.J. Price']

     game_date    Team     team_id      player   game_id
54  2010-10-27  Pacers  1610612754  A.J. Price  21000013
259 2010-11-22  Pacers  1610612754  A.J. Price  21000196
415 2010-12-13  Pacers  1610612754  A.J. Price  21000356
541 2010-12-26  Pacers  1610612754  A.J. Price  21000441
620 2011-01-02  Pacers  1610612754  A.J. Price  21000492
722 2011-01-14  Pacers  1610612754  A.J. Price  21000576

In [85]:
df_inj3[df_inj3.player == 'A.J. Price'].shape

(6, 5)

In [86]:
df_inj3[df_inj3.player.str.contains('A.J. Price')]

     game_date    Team     team_id      player   game_id
54  2010-10-27  Pacers  1610612754  A.J. Price  21000013
259 2010-11-22  Pacers  1610612754  A.J. Price  21000196
415 2010-12-13  Pacers  1610612754  A.J. Price  21000356
541 2010-12-26  Pacers  1610612754  A.J. Price  21000441
620 2011-01-02  Pacers  1610612754  A.J. Price  21000492
722 2011-01-14  Pacers  1610612754  A.J. Price  21000576

In [87]:
df_inj3[df_inj3.player.str.contains('A.J. Price')].shape

(6, 5)

In [88]:
df_inj3.player.replace({'A.J. Price': 'AJ Price'}, inplace=True)

In [89]:
df_inj3[df_inj3.player.str.contains('A.J. Price')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [90]:
df_inj3[df_inj3.player.str.contains('AJ Price')]

     game_date    Team     team_id    player   game_id
54  2010-10-27  Pacers  1610612754  AJ Price  21000013
259 2010-11-22  Pacers  1610612754  AJ Price  21000196
415 2010-12-13  Pacers  1610612754  AJ Price  21000356
541 2010-12-26  Pacers  1610612754  AJ Price  21000441
620 2011-01-02  Pacers  1610612754  AJ Price  21000492
722 2011-01-14  Pacers  1610612754  AJ Price  21000576

In [91]:
'''
*****************************************
Alex Ajinca
('Alexis Ajinca', 92)
1
'''

"\n*****************************************\nAlex Ajinca\n('Alexis Ajinca', 92)\n1\n"

In [92]:
df_inj3[df_inj3.player == 'Alex Ajinca']

      game_date       Team     team_id       player   game_id
46   2010-10-27  Mavericks  1610612742  Alex Ajinca  21000012
292  2010-11-27  Mavericks  1610612742  Alex Ajinca  21000239
387  2010-12-09  Mavericks  1610612742  Alex Ajinca  21000328
414  2010-12-13  Mavericks  1610612742  Alex Ajinca  21000358
772  2011-01-19  Mavericks  1610612742  Alex Ajinca  21000621
824  2011-01-24    Raptors  1610612761  Alex Ajinca  21000656
955  2011-02-08    Raptors  1610612761  Alex Ajinca  21000770
987  2011-02-11    Raptors  1610612761  Alex Ajinca  21000790
1211 2011-03-09    Raptors  1610612761  Alex Ajinca  21000956
1225 2011-03-11    Raptors  1610612761  Alex Ajinca  21000970

In [93]:
df_inj3[df_inj3.player == 'Alex Ajinca'].shape

(10, 5)

In [94]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')]

      game_date       Team     team_id       player   game_id
46   2010-10-27  Mavericks  1610612742  Alex Ajinca  21000012
292  2010-11-27  Mavericks  1610612742  Alex Ajinca  21000239
387  2010-12-09  Mavericks  1610612742  Alex Ajinca  21000328
414  2010-12-13  Mavericks  1610612742  Alex Ajinca  21000358
772  2011-01-19  Mavericks  1610612742  Alex Ajinca  21000621
824  2011-01-24    Raptors  1610612761  Alex Ajinca  21000656
955  2011-02-08    Raptors  1610612761  Alex Ajinca  21000770
987  2011-02-11    Raptors  1610612761  Alex Ajinca  21000790
1211 2011-03-09    Raptors  1610612761  Alex Ajinca  21000956
1225 2011-03-11    Raptors  1610612761  Alex Ajinca  21000970

In [95]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')].shape

(10, 5)

In [96]:
df_inj3[df_inj3.player == 'Alexis Ajinca']

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [97]:
df_inj3.player.replace({'Alex Ajinca':'Alexis Ajinca'}, inplace=True)

In [98]:
df_inj3[df_inj3.player.str.contains('Alex Ajinca')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [99]:
df_inj3[df_inj3.player.str.contains('Alexis Ajinca')]

      game_date       Team     team_id         player   game_id
46   2010-10-27  Mavericks  1610612742  Alexis Ajinca  21000012
292  2010-11-27  Mavericks  1610612742  Alexis Ajinca  21000239
387  2010-12-09  Mavericks  1610612742  Alexis Ajinca  21000328
414  2010-12-13  Mavericks  1610612742  Alexis Ajinca  21000358
772  2011-01-19  Mavericks  1610612742  Alexis Ajinca  21000621
824  2011-01-24    Raptors  1610612761  Alexis Ajinca  21000656
955  2011-02-08    Raptors  1610612761  Alexis Ajinca  21000770
987  2011-02-11    Raptors  1610612761  Alexis Ajinca  21000790
1211 2011-03-09    Raptors  1610612761  Alexis Ajinca  21000956
1225 2011-03-11    Raptors  1610612761  Alexis Ajinca  21000970

In [100]:
'''
*****************************************
C.J. Miles
('CJ Miles', 94)
2
'''

"\n*****************************************\nC.J. Miles\n('CJ Miles', 94)\n2\n"

In [101]:
print(df_inj3[df_inj3.player == 'C.J. Miles'].shape)
df_inj3[df_inj3.player == 'C.J. Miles']

(4, 5)

      game_date  Team     team_id      player   game_id
577  2010-12-29  Jazz  1610612762  C.J. Miles  21000472
586  2010-12-30  Jazz  1610612762  C.J. Miles  21000475
608  2011-01-01  Jazz  1610612762  C.J. Miles  21000491
1620 2011-04-13  Jazz  1610612762  C.J. Miles  21001226

In [102]:
print(df_inj3[df_inj3.player.str.contains('C.J. Miles')].shape)
df_inj3[df_inj3.player.str.contains('C.J. Miles')]

(4, 5)

      game_date  Team     team_id      player   game_id
577  2010-12-29  Jazz  1610612762  C.J. Miles  21000472
586  2010-12-30  Jazz  1610612762  C.J. Miles  21000475
608  2011-01-01  Jazz  1610612762  C.J. Miles  21000491
1620 2011-04-13  Jazz  1610612762  C.J. Miles  21001226

In [103]:
print(df_inj3[df_inj3.player == 'CJ Miles'].shape)
df_inj3[df_inj3.player == 'CJ Miles']

(0, 5)

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [104]:
print(df_inj3[df_inj3.player.str.contains('CJ Miles')].shape)
df_inj3[df_inj3.player.str.contains('CJ Miles')]

(0, 5)

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [105]:
df_inj3.player.replace({'C.J. Miles': 'CJ Miles'}, inplace=True)

In [106]:
print(df_inj3[df_inj3.player.str.contains('Miles')].shape)
df_inj3[df_inj3.player.str.contains('Miles')]

(4, 5)

      game_date  Team     team_id    player   game_id
577  2010-12-29  Jazz  1610612762  CJ Miles  21000472
586  2010-12-30  Jazz  1610612762  CJ Miles  21000475
608  2011-01-01  Jazz  1610612762  CJ Miles  21000491
1620 2011-04-13  Jazz  1610612762  CJ Miles  21001226

In [107]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Miles')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
317    21000014  1610612762.0    CJ Miles          84.1 2010-10-27   84.100000
425    21000018  1610612762.0    CJ Miles          86.9 2010-10-28   85.500000
991    21000042  1610612762.0    CJ Miles         132.9 2010-10-31  101.300000
1457   21000061  1610612762.0    CJ Miles         118.4 2010-11-03  105.575000
1854   21000078  1610612762.0    CJ Miles          79.9 2010-11-05  100.440000
2057   21000086  1610612762.0    CJ Miles          92.3 2010-11-06   99.083333
2453   21000103  1610612762.0    CJ Miles         124.4 2010-11-09  102.700000
2597   21000109  1610612762.0    CJ Miles         126.8 2010-11-10  105.712500
2884   21000121  1610612762.0    CJ Miles         109.6 2010-11-12  106.144444
3100   21000130  1610612762.0    CJ Miles         137.7 2010-11-13  109.300000
3544   21000148  1610612762.0    CJ Miles         104.4 2010-11-15  108.854545
3952   21000165  1610612762.0    CJ Miles          87.2 2010-11-17  107.050000
4264   21000178  1610612762.0    CJ Miles         101.6 2010-11-19  106.630769
4516   21000189  1610612762.0    CJ Miles         105.2 2010-11-20  106.528571
4792   21000200  1610612762.0    CJ Miles         107.0 2010-11-22  106.560000
5247   21000219  1610612762.0    CJ Miles         123.2 2010-11-24  107.600000
5535   21000231  1610612762.0    CJ Miles         114.4 2010-11-26  108.000000
5859   21000245  1610612762.0    CJ Miles         130.3 2010-11-28  109.238889
6063   21000253  1610612762.0    CJ Miles         113.9 2010-11-29  109.484211
6495   21000271  1610612762.0    CJ Miles         109.3 2010-12-01  109.475000
6855   21000286  1610612762.0    CJ Miles          76.2 2010-12-03  107.890476
7360   21000307  1610612762.0    CJ Miles         105.4 2010-12-06  107.777273
7768   21000324  1610612762.0    CJ Miles          90.1 2010-12-08  107.008696
8127   21000339  1610612762.0    CJ Miles         116.3 2010-12-10  107.395833
8284   21000346  1610612762.0    CJ Miles         124.4 2010-12-11  108.076000
8608   21000359  1610612762.0    CJ Miles         112.4 2010-12-13  108.242308
9268   21000387  1610612762.0    CJ Miles          55.0 2010-12-17  106.270370
9483   21000396  1610612762.0    CJ Miles         111.9 2010-12-18  106.471429
9746   21000407  1610612762.0    CJ Miles         122.7 2010-12-20  107.031034
10201  21000426  1610612762.0    CJ Miles         121.2 2010-12-22  107.503333
10839  21000452  1610612762.0    CJ Miles          93.5 2010-12-27  107.051613
11311  21000472  1610612762.0    CJ Miles           NaN 2010-12-29  107.051613
11382  21000475  1610612762.0    CJ Miles           NaN 2010-12-30  107.051613
11779  21000491  1610612762.0    CJ Miles           NaN 2011-01-01  107.051613
12086  21000504  1610612762.0    CJ Miles         121.8 2011-01-03  107.512500
12468  21000520  1610612762.0    CJ Miles          83.8 2011-01-05  106.793939
12695  21000530  1610612762.0    CJ Miles          89.5 2011-01-07  106.285294
13001  21000543  1610612762.0    CJ Miles          88.8 2011-01-08  105.785714
13656  21000570  1610612762.0    CJ Miles         130.1 2011-01-12  106.461111
13965  21000583  1610612762.0    CJ Miles         137.9 2011-01-14  107.310811
14337  21000599  1610612762.0    CJ Miles         106.7 2011-01-17  107.294737
14696  21000614  1610612762.0    CJ Miles         106.8 2011-01-19  107.282051
15129  21000632  1610612762.0    CJ Miles         108.4 2011-01-21  107.310000
15417  21000644  1610612762.0    CJ Miles          55.7 2011-01-22  106.051220
15963  21000667  1610612762.0    CJ Miles          94.6 2011-01-25  105.778571
16196  21000676  1610612762.0    CJ Miles         107.4 2011-01-26  105.816279
16508  21000689  1610612762.0    CJ Miles         107.5 2011-01-28  105.854545
16928  21000707  1610612762.0    CJ Miles          68.6 2011-01-30  105.026667
17086  21000713  1610612762.0    CJ Miles          95.7 2011-01-31  104.823913
17447  21000728  1610612762.0    CJ Miles         101.5 2011-02-02  104.753191
17817  21000744  1610612762.0    CJ Miles         106.6 2011-02-04  104.791667
18023  21000752  1610612762.0    CJ Miles          91.3 2011-02-05  104.516327
18295  21000764  1610612762.0    CJ Miles         105.5 2011-02-07  104.536000
18690  21000780  1610612762.0    CJ Miles          81.6 2011-02-09  104.086275
19046  21000795  1610612762.0    CJ Miles          93.0 2011-02-11  103.873077
19677  21000822  1610612762.0    CJ Miles          99.3 2011-02-15  103.786792
19977  21000834  1610612762.0    CJ Miles         111.6 2011-02-16  103.931481
20498  21000856  1610612762.0    CJ Miles         105.2 2011-02-23  103.954545
20641  21000862  1610612762.0    CJ Miles         104.8 2011-02-25  103.969643
20929  21000874  1610612762.0    CJ Miles          87.2 2011-02-26  103.675439
21368  21000892  1610612762.0    CJ Miles          92.9 2011-02-28  103.489655
21873  21000913  1610612762.0    CJ Miles         105.3 2011-03-03  103.520339
22233  21000928  1610612762.0    CJ Miles          92.5 2011-03-05  103.336667
22555  21000942  1610612762.0    CJ Miles         104.8 2011-03-07  103.360656
22884  21000956  1610612762.0    CJ Miles         116.8 2011-03-09  103.577419
23273  21000972  1610612762.0    CJ Miles         103.4 2011-03-11  103.574603
23441  21000979  1610612762.0    CJ Miles         121.5 2011-03-12  103.854688
23879  21000997  1610612762.0    CJ Miles         108.8 2011-03-14  103.930769
24191  21001010  1610612762.0    CJ Miles         123.6 2011-03-16  104.228788
24899  21001040  1610612762.0    CJ Miles         113.7 2011-03-20  104.370149
25091  21001048  1610612762.0    CJ Miles          99.5 2011-03-21  104.298529
25402  21001061  1610612762.0    CJ Miles         108.6 2011-03-23  104.360870
25555  21001067  1610612762.0    CJ Miles         113.4 2011-03-24  104.490000
25986  21001085  1610612762.0    CJ Miles          76.4 2011-03-26  104.094366
26345  21001100  1610612762.0    CJ Miles          92.4 2011-03-28  103.931944
27116  21001132  1610612762.0    CJ Miles         106.0 2011-04-01  103.960274
27412  21001145  1610612762.0    CJ Miles          98.8 2011-04-03  103.890541
27799  21001161  1610612762.0    CJ Miles          81.7 2011-04-05  103.594667
28144  21001175  1610612762.0    CJ Miles          91.7 2011-04-07  103.438158
28515  21001191  1610612762.0    CJ Miles          98.0 2011-04-09  103.367532
28923  21001208  1610612762.0    CJ Miles         101.0 2011-04-11  103.337179
29377  21001226  1610612762.0    CJ Miles           NaN 2011-04-13  103.337179

In [108]:
'''
*****************************************
D.J. White
('DJ White', 94)
3
'''

"\n*****************************************\nD.J. White\n('DJ White', 94)\n3\n"

In [109]:
df_inj3[df_inj3.player == 'D.J. White']

      game_date     Team     team_id      player   game_id
357  2010-12-05  Thunder  1610612760  D.J. White  21000297
1058 2011-02-25  Bobcats  1610612766  D.J. White  21000861

In [110]:
df_inj3[df_inj3.player.str.contains('D.J. White')]

      game_date     Team     team_id      player   game_id
357  2010-12-05  Thunder  1610612760  D.J. White  21000297
1058 2011-02-25  Bobcats  1610612766  D.J. White  21000861

In [111]:
df_inj3.player.replace({'D.J. White': 'DJ White'}, inplace=True)

In [112]:
df_inj3[df_inj3.player.str.contains('D.J. White')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [113]:
df_inj3[df_inj3.player.str.contains('DJ White')]

      game_date     Team     team_id    player   game_id
357  2010-12-05  Thunder  1610612760  DJ White  21000297
1058 2011-02-25  Bobcats  1610612766  DJ White  21000861

In [114]:
'''
*****************************************
Hamady N'Diaye
('Hamady Ndiaye', 89)
4
'''

"\n*****************************************\nHamady N'Diaye\n('Hamady Ndiaye', 89)\n4\n"

In [115]:
print(df_inj3[df_inj3.player.str.contains('Hamady')].shape)
df_inj3[df_inj3.player.str.contains('Hamady')]

(12, 5)

      game_date     Team     team_id          player   game_id
252  2010-11-21  Wizards  1610612764  Hamady N'Diaye  21000192
324  2010-12-01  Wizards  1610612764  Hamady N'Diaye  21000263
521  2010-12-22  Wizards  1610612764  Hamady N'Diaye  21000423
556  2010-12-27  Wizards  1610612764  Hamady N'Diaye  21000451
1011 2011-02-13  Wizards  1610612764  Hamady N'Diaye  21000806
1176 2011-03-06  Wizards  1610612764  Hamady N'Diaye  21000934
1451 2011-04-03  Wizards  1610612764  Hamady N'Diaye  21001141
1476 2011-04-05  Wizards  1610612764  Hamady N'Diaye  21001153
1493 2011-04-06  Wizards  1610612764  Hamady N'Diaye  21001163
1518 2011-04-08  Wizards  1610612764  Hamady N'Diaye  21001179
1531 2011-04-09  Wizards  1610612764  Hamady N'Diaye  21001188
1585 2011-04-11  Wizards  1610612764  Hamady N'Diaye  21001205

In [116]:
df_inj3.player.replace({"Hamady N'Diaye" : 'Hamady Ndiaye'}, inplace=True)

In [117]:
print(df_inj3[df_inj3.player.str.contains('Hamady')].shape)
df_inj3[df_inj3.player.str.contains('Hamady')]

(12, 5)

      game_date     Team     team_id         player   game_id
252  2010-11-21  Wizards  1610612764  Hamady Ndiaye  21000192
324  2010-12-01  Wizards  1610612764  Hamady Ndiaye  21000263
521  2010-12-22  Wizards  1610612764  Hamady Ndiaye  21000423
556  2010-12-27  Wizards  1610612764  Hamady Ndiaye  21000451
1011 2011-02-13  Wizards  1610612764  Hamady Ndiaye  21000806
1176 2011-03-06  Wizards  1610612764  Hamady Ndiaye  21000934
1451 2011-04-03  Wizards  1610612764  Hamady Ndiaye  21001141
1476 2011-04-05  Wizards  1610612764  Hamady Ndiaye  21001153
1493 2011-04-06  Wizards  1610612764  Hamady Ndiaye  21001163
1518 2011-04-08  Wizards  1610612764  Hamady Ndiaye  21001179
1531 2011-04-09  Wizards  1610612764  Hamady Ndiaye  21001188
1585 2011-04-11  Wizards  1610612764  Hamady Ndiaye  21001205

In [118]:
print(df_or1011a[df_or1011a.PLAYER_NAME == 'Hamady Ndiaye'].shape)
df_or1011a[df_or1011a.PLAYER_NAME == 'Hamady Ndiaye']

(35, 6)

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
395,21000017,1610612764.0,Hamady Ndiaye,98.0,2010-10-28,98.000000
3670,21000153,1610612764.0,Hamady Ndiaye,50.0,2010-11-16,74.000000
3826,21000160,1610612764.0,Hamady Ndiaye,NaN,2010-11-17,74.000000
4173,21000174,1610612764.0,Hamady Ndiaye,NaN,2010-11-19,74.000000
5265,21000220,1610612764.0,Hamady Ndiaye,130.8,2010-11-25,92.933333
5636,21000235,1610612764.0,Hamady Ndiaye,NaN,2010-11-27,92.933333
5983,21000250,1610612764.0,Hamady Ndiaye,NaN,2010-11-29,92.933333
8685,21000362,1610612764.0,Hamady Ndiaye,NaN,2010-12-14,92.933333
9055,21000378,1610612764.0,Hamady Ndiaye,51.0,2010-12-16,82.450000
9428,21000393,1610612764.0,Hamady Ndiaye,NaN,2010-12-18,82.450000
9812,21000409,1610612764.0,Hamady Ndiaye,NaN,2010-12-20,82.450000
10615,21000443,1610612764.0,Hamady Ndiaye,NaN,2010-12-26,82.450000
19126,21000798,1610612764.0,Hamady Ndiaye,NaN,2011-02-12,82.450000
20360,21000850,1610612764.0,Hamady Ndiaye,NaN,2011-02-23,82.450000
22190,21000926,1610612764.0,Hamady Ndiaye,NaN,2011-03-05,82.450000
22761,21000950,1610612764.0,Hamady Ndiaye,56.3,2011-03-08,77.220000
23430,21000978,1610612764.0,Hamady Ndiaye,107.9,2011-03-12,82.333333
23766,21000992,1610612764.0,Hamady Ndiaye,101.2,2011-03-14,85.028571
23968,21001001,1610612764.0,Hamady Ndiaye,200.0,2011-03-15,99.400000
24397,21001019,1610612764.0,Hamady Ndiaye,112.6,2011-03-18,100.866667
24797,21001035,1610612764.0,Hamady Ndiaye,NaN,2011-03-20,100.866667
25192,21001052,1610612764.0,Hamady Ndiaye,88.8,2011-03-22,99.660000
25503,21001065,1610612764.0,Hamady Ndiaye,52.1,2011-03-23,95.336364
25768,21001076,1610612764.0,Hamady Ndiaye,115.3,2011-03-25,97.000000
26175,21001093,1610612764.0,Hamady Ndiaye,NaN,2011-03-27,97.000000
26339,21001100,1610612764.0,Hamady Ndiaye,46.6,2011-03-28,93.123077
26593,21001110,1610612764.0,Hamady Ndiaye,0.0,2011-03-30,86.471429
26906,21001123,1610612764.0,Hamady Ndiaye,0.0,2011-04-01,80.706667
27325,21001141,1610612764.0,Hamady Ndiaye,NaN,2011-04-03,80.706667
27626,21001153,1610612764.0,Hamady Ndiaye,NaN,2011-04-05,80.706667
27854,21001163,1610612764.0,Hamady Ndiaye,NaN,2011-04-06,80.706667
28237,21001179,1610612764.0,Hamady Ndiaye,NaN,2011-04-08,80.706667
28466,21001188,1610612764.0,Hamady Ndiaye,NaN,2011-04-09,80.706667
28872,21001205,1610612764.0,Hamady Ndiaye,NaN,2011-04-11,80.706667
29172,21001218,1610612764.0,Hamady Ndiaye,62.3,2011-04-13,79.556250

In [119]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady Ndiaye')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady Ndiaye')]

(35, 6)

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
395,21000017,1610612764.0,Hamady Ndiaye,98.0,2010-10-28,98.000000
3670,21000153,1610612764.0,Hamady Ndiaye,50.0,2010-11-16,74.000000
3826,21000160,1610612764.0,Hamady Ndiaye,NaN,2010-11-17,74.000000
4173,21000174,1610612764.0,Hamady Ndiaye,NaN,2010-11-19,74.000000
5265,21000220,1610612764.0,Hamady Ndiaye,130.8,2010-11-25,92.933333
5636,21000235,1610612764.0,Hamady Ndiaye,NaN,2010-11-27,92.933333
5983,21000250,1610612764.0,Hamady Ndiaye,NaN,2010-11-29,92.933333
8685,21000362,1610612764.0,Hamady Ndiaye,NaN,2010-12-14,92.933333
9055,21000378,1610612764.0,Hamady Ndiaye,51.0,2010-12-16,82.450000
9428,21000393,1610612764.0,Hamady Ndiaye,NaN,2010-12-18,82.450000
9812,21000409,1610612764.0,Hamady Ndiaye,NaN,2010-12-20,82.450000
10615,21000443,1610612764.0,Hamady Ndiaye,NaN,2010-12-26,82.450000
19126,21000798,1610612764.0,Hamady Ndiaye,NaN,2011-02-12,82.450000
20360,21000850,1610612764.0,Hamady Ndiaye,NaN,2011-02-23,82.450000
22190,21000926,1610612764.0,Hamady Ndiaye,NaN,2011-03-05,82.450000
22761,21000950,1610612764.0,Hamady Ndiaye,56.3,2011-03-08,77.220000
23430,21000978,1610612764.0,Hamady Ndiaye,107.9,2011-03-12,82.333333
23766,21000992,1610612764.0,Hamady Ndiaye,101.2,2011-03-14,85.028571
23968,21001001,1610612764.0,Hamady Ndiaye,200.0,2011-03-15,99.400000
24397,21001019,1610612764.0,Hamady Ndiaye,112.6,2011-03-18,100.866667
24797,21001035,1610612764.0,Hamady Ndiaye,NaN,2011-03-20,100.866667
25192,21001052,1610612764.0,Hamady Ndiaye,88.8,2011-03-22,99.660000
25503,21001065,1610612764.0,Hamady Ndiaye,52.1,2011-03-23,95.336364
25768,21001076,1610612764.0,Hamady Ndiaye,115.3,2011-03-25,97.000000
26175,21001093,1610612764.0,Hamady Ndiaye,NaN,2011-03-27,97.000000
26339,21001100,1610612764.0,Hamady Ndiaye,46.6,2011-03-28,93.123077
26593,21001110,1610612764.0,Hamady Ndiaye,0.0,2011-03-30,86.471429
26906,21001123,1610612764.0,Hamady Ndiaye,0.0,2011-04-01,80.706667
27325,21001141,1610612764.0,Hamady Ndiaye,NaN,2011-04-03,80.706667
27626,21001153,1610612764.0,Hamady Ndiaye,NaN,2011-04-05,80.706667
27854,21001163,1610612764.0,Hamady Ndiaye,NaN,2011-04-06,80.706667
28237,21001179,1610612764.0,Hamady Ndiaye,NaN,2011-04-08,80.706667
28466,21001188,1610612764.0,Hamady Ndiaye,NaN,2011-04-09,80.706667
28872,21001205,1610612764.0,Hamady Ndiaye,NaN,2011-04-11,80.706667
29172,21001218,1610612764.0,Hamady Ndiaye,62.3,2011-04-13,79.556250

In [120]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hamady')].sort_values(by='game_date')

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
395,21000017,1610612764.0,Hamady Ndiaye,98.0,2010-10-28,98.000000
3670,21000153,1610612764.0,Hamady Ndiaye,50.0,2010-11-16,74.000000
3826,21000160,1610612764.0,Hamady Ndiaye,NaN,2010-11-17,74.000000
4173,21000174,1610612764.0,Hamady Ndiaye,NaN,2010-11-19,74.000000
5265,21000220,1610612764.0,Hamady Ndiaye,130.8,2010-11-25,92.933333
5636,21000235,1610612764.0,Hamady Ndiaye,NaN,2010-11-27,92.933333
5983,21000250,1610612764.0,Hamady Ndiaye,NaN,2010-11-29,92.933333
8685,21000362,1610612764.0,Hamady Ndiaye,NaN,2010-12-14,92.933333
9055,21000378,1610612764.0,Hamady Ndiaye,51.0,2010-12-16,82.450000
9428,21000393,1610612764.0,Hamady Ndiaye,NaN,2010-12-18,82.450000
9812,21000409,1610612764.0,Hamady Ndiaye,NaN,2010-12-20,82.450000
10615,21000443,1610612764.0,Hamady Ndiaye,NaN,2010-12-26,82.450000
19126,21000798,1610612764.0,Hamady Ndiaye,NaN,2011-02-12,82.450000
20360,21000850,1610612764.0,Hamady Ndiaye,NaN,2011-02-23,82.450000
22190,21000926,1610612764.0,Hamady Ndiaye,NaN,2011-03-05,82.450000
22761,21000950,1610612764.0,Hamady Ndiaye,56.3,2011-03-08,77.220000
23430,21000978,1610612764.0,Hamady Ndiaye,107.9,2011-03-12,82.333333
23766,21000992,1610612764.0,Hamady Ndiaye,101.2,2011-03-14,85.028571
23968,21001001,1610612764.0,Hamady Ndiaye,200.0,2011-03-15,99.400000
24397,21001019,1610612764.0,Hamady Ndiaye,112.6,2011-03-18,100.866667
24797,21001035,1610612764.0,Hamady Ndiaye,NaN,2011-03-20,100.866667
25192,21001052,1610612764.0,Hamady Ndiaye,88.8,2011-03-22,99.660000
25503,21001065,1610612764.0,Hamady Ndiaye,52.1,2011-03-23,95.336364
25768,21001076,1610612764.0,Hamady Ndiaye,115.3,2011-03-25,97.000000
26175,21001093,1610612764.0,Hamady Ndiaye,NaN,2011-03-27,97.000000
26339,21001100,1610612764.0,Hamady Ndiaye,46.6,2011-03-28,93.123077
26593,21001110,1610612764.0,Hamady Ndiaye,0.0,2011-03-30,86.471429
26906,21001123,1610612764.0,Hamady Ndiaye,0.0,2011-04-01,80.706667
27325,21001141,1610612764.0,Hamady Ndiaye,NaN,2011-04-03,80.706667
27626,21001153,1610612764.0,Hamady Ndiaye,NaN,2011-04-05,80.706667
27854,21001163,1610612764.0,Hamady Ndiaye,NaN,2011-04-06,80.706667
28237,21001179,1610612764.0,Hamady Ndiaye,NaN,2011-04-08,80.706667
28466,21001188,1610612764.0,Hamady Ndiaye,NaN,2011-04-09,80.706667
28872,21001205,1610612764.0,Hamady Ndiaye,NaN,2011-04-11,80.706667
29172,21001218,1610612764.0,Hamady Ndiaye,62.3,2011-04-13,79.556250

In [121]:
df_inj3[df_inj3.player.str.contains('Hamady')]

      game_date     Team     team_id         player   game_id
252  2010-11-21  Wizards  1610612764  Hamady Ndiaye  21000192
324  2010-12-01  Wizards  1610612764  Hamady Ndiaye  21000263
521  2010-12-22  Wizards  1610612764  Hamady Ndiaye  21000423
556  2010-12-27  Wizards  1610612764  Hamady Ndiaye  21000451
1011 2011-02-13  Wizards  1610612764  Hamady Ndiaye  21000806
1176 2011-03-06  Wizards  1610612764  Hamady Ndiaye  21000934
1451 2011-04-03  Wizards  1610612764  Hamady Ndiaye  21001141
1476 2011-04-05  Wizards  1610612764  Hamady Ndiaye  21001153
1493 2011-04-06  Wizards  1610612764  Hamady Ndiaye  21001163
1518 2011-04-08  Wizards  1610612764  Hamady Ndiaye  21001179
1531 2011-04-09  Wizards  1610612764  Hamady Ndiaye  21001188
1585 2011-04-11  Wizards  1610612764  Hamady Ndiaye  21001205

In [122]:
'''
*****************************************
J.J. Hickson
('JJ Hickson', 95)
5
'''

"\n*****************************************\nJ.J. Hickson\n('JJ Hickson', 95)\n5\n"

In [123]:
print(df_inj3[df_inj3.player.str.contains('Hickson')].shape)
df_inj3[df_inj3.player.str.contains('Hickson')]

(1, 5)

     game_date       Team     team_id        player   game_id
342 2010-12-04  Cavaliers  1610612739  J.J. Hickson  21000291

In [124]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hickson')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Hickson')]

(81, 6)

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
85     21000004  1610612739.0  JJ Hickson         102.1 2010-10-27  102.100000
505    21000022  1610612739.0  JJ Hickson          52.2 2010-10-29   77.150000
757    21000032  1610612739.0  JJ Hickson         107.7 2010-10-30   87.333333
1117   21000047  1610612739.0  JJ Hickson         100.1 2010-11-02   90.525000
1657   21000070  1610612739.0  JJ Hickson         118.5 2010-11-05   96.120000
1921   21000081  1610612739.0  JJ Hickson         104.8 2010-11-06   97.566667
2425   21000102  1610612739.0  JJ Hickson         102.0 2010-11-09   98.200000
2677   21000112  1610612739.0  JJ Hickson          96.6 2010-11-10   98.000000
3156   21000132  1610612739.0  JJ Hickson          85.0 2010-11-13   96.555556
3612   21000151  1610612739.0  JJ Hickson         109.8 2010-11-16   97.880000
4224   21000177  1610612739.0  JJ Hickson          76.1 2010-11-19   95.900000
4464   21000187  1610612739.0  JJ Hickson          82.8 2010-11-20   94.808333
4847   21000203  1610612739.0  JJ Hickson          72.3 2010-11-23   93.076923
5027   21000210  1610612739.0  JJ Hickson          95.8 2010-11-24   93.271429
5327   21000223  1610612739.0  JJ Hickson          99.1 2010-11-26   93.660000
5651   21000236  1610612739.0  JJ Hickson         108.2 2010-11-27   94.568750
6082   21000254  1610612739.0  JJ Hickson          97.1 2010-11-30   94.717647
6539   21000273  1610612739.0  JJ Hickson          80.8 2010-12-02   93.944444
7079   21000296  1610612739.0  JJ Hickson         103.9 2010-12-05   94.468421
7439   21000311  1610612739.0  JJ Hickson          96.7 2010-12-07   94.580000
7601   21000317  1610612739.0  JJ Hickson          72.7 2010-12-08   93.538095
8308   21000347  1610612739.0  JJ Hickson          88.9 2010-12-11   93.327273
8427   21000352  1610612739.0  JJ Hickson          62.5 2010-12-12   91.986957
8883   21000371  1610612739.0  JJ Hickson          95.1 2010-12-15   92.116667
9123   21000381  1610612739.0  JJ Hickson          92.1 2010-12-17   92.116000
9448   21000394  1610612739.0  JJ Hickson         104.6 2010-12-18   92.596154
9759   21000407  1610612739.0  JJ Hickson         106.2 2010-12-20   93.100000
10081  21000421  1610612739.0  JJ Hickson          77.6 2010-12-22   92.546429
10527  21000439  1610612739.0  JJ Hickson          85.4 2010-12-26   92.300000
10909  21000455  1610612739.0  JJ Hickson         103.7 2010-12-28   92.680000
11091  21000463  1610612739.0  JJ Hickson          96.7 2010-12-29   92.809677
11618  21000485  1610612739.0  JJ Hickson          92.4 2011-01-01   92.796875
11869  21000495  1610612739.0  JJ Hickson          86.7 2011-01-02   92.612121
12282  21000512  1610612739.0  JJ Hickson           NaN 2011-01-05   92.612121
12787  21000534  1610612739.0  JJ Hickson          99.3 2011-01-07   92.808824
13092  21000547  1610612739.0  JJ Hickson         105.3 2011-01-09   93.165714
13402  21000560  1610612739.0  JJ Hickson          51.0 2011-01-11   91.994444
13950  21000583  1610612739.0  JJ Hickson         110.0 2011-01-14   92.481081
14214  21000594  1610612739.0  JJ Hickson          96.0 2011-01-15   92.573684
14681  21000613  1610612739.0  JJ Hickson          97.5 2011-01-19   92.700000
15161  21000633  1610612739.0  JJ Hickson          91.4 2011-01-21   92.667500
15437  21000645  1610612739.0  JJ Hickson          70.8 2011-01-22   92.134146
15629  21000653  1610612739.0  JJ Hickson          88.1 2011-01-24   92.038095
15893  21000664  1610612739.0  JJ Hickson          95.7 2011-01-25   92.123256
16409  21000685  1610612739.0  JJ Hickson         114.5 2011-01-28   92.631818
16829  21000703  1610612739.0  JJ Hickson          70.3 2011-01-30   92.135556
16997  21000710  1610612739.0  JJ Hickson         106.1 2011-01-31   92.439130
17250  21000720  1610612739.0  JJ Hickson         102.6 2011-02-02   92.655319
17742  21000741  1610612739.0  JJ Hickson         101.7 2011-02-04   92.843750
17898  21000747  1610612739.0  JJ Hickson         101.0 2011-02-05   93.010204
18221  21000761  1610612739.0  JJ Hickson         102.3 2011-02-07   93.196000
18519  21000773  1610612739.0  JJ Hickson         113.3 2011-02-09   93.590196
18949  21000791  1610612739.0  JJ Hickson         109.0 2011-02-11   93.886538
19309  21000806  1610612739.0  JJ Hickson          94.8 2011-02-13   93.903774
19811  21000827  1610612739.0  JJ Hickson         103.8 2011-02-16   94.087037
20291  21000847  1610612739.0  JJ Hickson         110.9 2011-02-23   94.392727
20721  21000865  1610612739.0  JJ Hickson         110.3 2011-02-25   94.676786
21102  21000881  1610612739.0  JJ Hickson          95.9 2011-02-27   94.698246
21629  21000903  1610612739.0  JJ Hickson          90.6 2011-03-02   94.627586
22001  21000919  1610612739.0  JJ Hickson         129.7 2011-03-04   95.222034
22420  21000936  1610612739.0  JJ Hickson          87.5 2011-03-06   95.093333
22707  21000948  1610612739.0  JJ Hickson          76.5 2011-03-08   94.788525
22958  21000959  1610612739.0  JJ Hickson          88.3 2011-03-09   94.683871
23590  21000985  1610612739.0  JJ Hickson          98.8 2011-03-13   94.749206
24202  21001011  1610612739.0  JJ Hickson         106.1 2011-03-16   94.926563
24322  21001016  1610612739.0  JJ Hickson          71.5 2011-03-17   94.566154
24634  21001029  1610612739.0  JJ Hickson         102.1 2011-03-19   94.680303
25006  21001044  1610612739.0  JJ Hickson          82.2 2011-03-21   94.494030
25268  21001055  1610612739.0  JJ Hickson          97.1 2011-03-23   94.532353
25652  21001071  1610612739.0  JJ Hickson         115.3 2011-03-25   94.833333
26059  21001088  1610612739.0  JJ Hickson          81.9 2011-03-27   94.648571
26370  21001101  1610612739.0  JJ Hickson         109.5 2011-03-29   94.857746
26478  21001106  1610612739.0  JJ Hickson         115.7 2011-03-30   95.147222
26886  21001123  1610612739.0  JJ Hickson         112.9 2011-04-01   95.390411
27365  21001143  1610612739.0  JJ Hickson         110.9 2011-04-03   95.600000
27545  21001150  1610612739.0  JJ Hickson          98.6 2011-04-05   95.640000
27917  21001166  1610612739.0  JJ Hickson         122.9 2011-04-06   95.998684
28265  21001180  1610612739.0  JJ Hickson          89.7 2011-04-08   95.916883
28492  21001190  1610612739.0  JJ Hickson         116.0 2011-04-09   96.174359
28876  21001206  1610612739.0  JJ Hickson         108.9 2011-04-11   96.335443
29176  21001218  1610612739.0  JJ Hickson         100.8 2011-04-13   96.391250

In [125]:
#df_injuries[df_injuries.player == 'J.J. Hickson']
df_inj3.player.replace({'J.J. Hickson': 'JJ Hickson'}, inplace=True)

In [126]:
print(df_inj3[df_inj3.player.str.contains('Hickson')].shape)
df_inj3[df_inj3.player.str.contains('Hickson')]

(1, 5)

     game_date       Team     team_id      player   game_id
342 2010-12-04  Cavaliers  1610612739  JJ Hickson  21000291

In [127]:
'''
*****************************************
J.J. Redick
('JJ Redick', 94)
6
'''

"\n*****************************************\nJ.J. Redick\n('JJ Redick', 94)\n6\n"

In [128]:
df_inj3[df_inj3.player.str.contains('Redick')]

      game_date   Team     team_id     player   game_id
206  2010-11-15  Magic  1610612753  JJ Redick  21000145
318  2010-12-01  Magic  1610612753  JJ Redick  21000266
335  2010-12-03  Magic  1610612753  JJ Redick  21000279
345  2010-12-04  Magic  1610612753  JJ Redick  21000292
880  2011-01-31  Magic  1610612753  JJ Redick  21000711
1222 2011-03-11  Magic  1610612753  JJ Redick  21000975
1268 2011-03-16  Magic  1610612753  JJ Redick  21001007
1276 2011-03-18  Magic  1610612753  JJ Redick  21001018
1307 2011-03-21  Magic  1610612753  JJ Redick  21001044
1320 2011-03-23  Magic  1610612753  JJ Redick  21001059
1339 2011-03-25  Magic  1610612753  JJ Redick  21001069
1371 2011-03-28  Magic  1610612753  JJ Redick  21000051
1393 2011-03-30  Magic  1610612753  JJ Redick  21001105
1420 2011-04-01  Magic  1610612753  JJ Redick  21001121
1443 2011-04-03  Magic  1610612753  JJ Redick  21001144
1467 2011-04-05  Magic  1610612753  JJ Redick  21001152
1482 2011-04-06  Magic  1610612753  JJ Redick  21001162
1538 2011-04-10  Magic  1610612753  JJ Redick  21001193
1564 2011-04-11  Magic  1610612753  JJ Redick  21001204
1628 2011-04-13  Magic  1610612753  JJ Redick  21001219

In [129]:
'''
*****************************************
John Wallace
('John Wall', 86)
7
'''

"\n*****************************************\nJohn Wallace\n('John Wall', 86)\n7\n"

In [130]:
df_inj3[df_inj3.player.str.contains('John Wall')]

     game_date     Team     team_id        player   game_id
221 2010-11-16  Wizards  1610612764    John Wall   21000153
253 2010-11-21  Wizards  1610612764    John Wall   21000192
294 2010-11-27  Wizards  1610612764    John Wall   21000235
310 2010-11-29  Wizards  1610612764    John Wall   21000250
384 2010-12-08  Wizards  1610612764    John Wall   21000325
429 2010-12-14  Wizards  1610612764    John Wall   21000362
448 2010-12-16  Wizards  1610612764  John Wallace  21000378
475 2010-12-18  Wizards  1610612764  John Wallace  21000393

In [131]:
df_inj3[df_inj3.player.str.contains('Wallace')]

      game_date     Team     team_id          player   game_id
430  2010-12-15  Bobcats  1610612766  Gerald Wallace  21000372
448  2010-12-16  Wizards  1610612764    John Wallace  21000378
475  2010-12-18  Wizards  1610612764    John Wallace  21000393
625  2011-01-03  Bobcats  1610612766  Gerald Wallace  21000499
700  2011-01-12  Pistons  1610612765     Ben Wallace  21000565
1057 2011-02-25  Blazers  1610612757  Gerald Wallace  21000872
1323 2011-03-23  Pistons  1610612765     Ben Wallace  21001058
1324 2011-03-23  Pistons  1610612765     Ben Wallace  21001058
1489 2011-04-06  Pistons  1610612765     Ben Wallace  21001167
1597 2011-04-13  Blazers  1610612757  Gerald Wallace  21001227

In [132]:
df_inj3.player.replace({'John Wallace' : 'John Wall'}, inplace=True)

In [133]:
df_inj3[df_inj3.player.str.contains('John Wall')]

     game_date     Team     team_id      player   game_id
221 2010-11-16  Wizards  1610612764  John Wall   21000153
253 2010-11-21  Wizards  1610612764  John Wall   21000192
294 2010-11-27  Wizards  1610612764  John Wall   21000235
310 2010-11-29  Wizards  1610612764  John Wall   21000250
384 2010-12-08  Wizards  1610612764  John Wall   21000325
429 2010-12-14  Wizards  1610612764  John Wall   21000362
448 2010-12-16  Wizards  1610612764   John Wall  21000378
475 2010-12-18  Wizards  1610612764   John Wall  21000393

In [134]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('John Wall')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('John Wall')]

(75, 6)

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date       cma2
388    21000017  1610612764.0   John Wall          75.8 2010-10-28  75.800000
724    21000031  1610612764.0   John Wall         102.1 2010-10-30  88.950000
1144   21000048  1610612764.0   John Wall         102.5 2010-11-02  93.466667
1708   21000072  1610612764.0   John Wall          89.4 2010-11-05  92.450000
1936   21000081  1610612764.0   John Wall         101.3 2010-11-06  94.220000
2656   21000111  1610612764.0   John Wall         103.8 2010-11-10  95.816667
2967   21000124  1610612764.0   John Wall          88.4 2010-11-12  94.757143
3195   21000134  1610612764.0   John Wall          88.7 2010-11-13  94.000000
4593   21000192  1610612764.0   John Wall           NaN 2010-11-21  94.000000
4912   21000205  1610612764.0   John Wall         117.0 2010-11-23  96.555556
5258   21000220  1610612764.0   John Wall          84.7 2010-11-25  95.370000
5637   21000235  1610612764.0   John Wall           NaN 2010-11-27  95.370000
5984   21000250  1610612764.0   John Wall           NaN 2010-11-29  95.370000
6292   21000263  1610612764.0   John Wall         106.5 2010-12-01  96.381818
6637   21000277  1610612764.0   John Wall          91.0 2010-12-03  95.933333
7178   21000300  1610612764.0   John Wall         114.3 2010-12-05  97.346154
7538   21000315  1610612764.0   John Wall         106.5 2010-12-07  98.000000
7785   21000325  1610612764.0   John Wall           NaN 2010-12-08  98.000000
7958   21000332  1610612764.0   John Wall          95.4 2010-12-10  97.826667
9057   21000378  1610612764.0   John Wall           NaN 2010-12-16  97.826667
10611  21000443  1610612764.0   John Wall          77.0 2010-12-26  96.525000
10802  21000451  1610612764.0   John Wall          96.1 2010-12-27  96.500000
11127  21000464  1610612764.0   John Wall         111.9 2010-12-29  97.355556
11448  21000478  1610612764.0   John Wall          88.7 2010-12-31  96.900000
11604  21000484  1610612764.0   John Wall         101.7 2011-01-01  97.140000
12336  21000515  1610612764.0   John Wall         112.6 2011-01-05  97.876190
12633  21000527  1610612764.0   John Wall         100.6 2011-01-07  98.000000
12858  21000537  1610612764.0   John Wall         101.9 2011-01-08  98.169565
13322  21000556  1610612764.0   John Wall         127.6 2011-01-11  99.395833
13714  21000573  1610612764.0   John Wall          93.3 2011-01-13  99.152000
14108  21000589  1610612764.0   John Wall          91.7 2011-01-15  98.865385
14348  21000599  1610612764.0   John Wall         122.8 2011-01-17  99.751852
14767  21000617  1610612764.0   John Wall          96.4 2011-01-19  99.632143
15187  21000634  1610612764.0   John Wall          86.2 2011-01-21  99.168966
15355  21000641  1610612764.0   John Wall          91.0 2011-01-22  98.896667
15726  21000657  1610612764.0   John Wall          88.3 2011-01-24  98.554839
15883  21000663  1610612764.0   John Wall         107.1 2011-01-25  98.821875
16471  21000688  1610612764.0   John Wall         100.4 2011-01-28  98.869697
16615  21000694  1610612764.0   John Wall          94.8 2011-01-29  98.750000
17047  21000712  1610612764.0   John Wall          93.6 2011-01-31  98.602857
17119  21000715  1610612764.0   John Wall          94.0 2011-02-01  98.475000
17661  21000737  1610612764.0   John Wall         101.9 2011-02-04  98.567568
17876  21000746  1610612764.0   John Wall         103.6 2011-02-05  98.700000
18641  21000778  1610612764.0   John Wall         110.0 2011-02-09  98.989744
19119  21000798  1610612764.0   John Wall          81.7 2011-02-12  98.557500
19299  21000806  1610612764.0   John Wall         126.8 2011-02-13  99.246341
19729  21000824  1610612764.0   John Wall          72.6 2011-02-16  98.611905
20101  21000839  1610612764.0   John Wall          74.6 2011-02-22  98.053488
20353  21000850  1610612764.0   John Wall          98.6 2011-02-23  98.065909
20735  21000866  1610612764.0   John Wall         119.4 2011-02-25  98.540000
20913  21000873  1610612764.0   John Wall          93.1 2011-02-26  98.421739
21320  21000890  1610612764.0   John Wall          91.0 2011-02-28  98.263830
21655  21000904  1610612764.0   John Wall         101.1 2011-03-02  98.322917
22183  21000926  1610612764.0   John Wall         103.0 2011-03-05  98.418367
22362  21000934  1610612764.0   John Wall         105.2 2011-03-06  98.554000
22757  21000950  1610612764.0   John Wall          82.9 2011-03-08  98.247059
23425  21000978  1610612764.0   John Wall          90.8 2011-03-12  98.103846
23760  21000992  1610612764.0   John Wall          88.6 2011-03-14  97.924528
23964  21001001  1610612764.0   John Wall          88.8 2011-03-15  97.755556
24396  21001019  1610612764.0   John Wall         112.7 2011-03-18  98.027273
24792  21001035  1610612764.0   John Wall         105.4 2011-03-20  98.158929
25188  21001052  1610612764.0   John Wall          90.4 2011-03-22  98.022807
25499  21001065  1610612764.0   John Wall         100.6 2011-03-23  98.067241
25763  21001076  1610612764.0   John Wall         100.6 2011-03-25  98.110169
26169  21001093  1610612764.0   John Wall          97.4 2011-03-27  98.098333
26337  21001100  1610612764.0   John Wall          97.1 2011-03-28  98.081967
26589  21001110  1610612764.0   John Wall         120.8 2011-03-30  98.448387
26907  21001123  1610612764.0   John Wall           NaN 2011-04-01  98.448387
27320  21001141  1610612764.0   John Wall         104.8 2011-04-03  98.549206
27620  21001153  1610612764.0   John Wall         107.7 2011-04-05  98.692188
27848  21001163  1610612764.0   John Wall         105.9 2011-04-06  98.803077
28232  21001179  1610612764.0   John Wall          83.9 2011-04-08  98.577273
28460  21001188  1610612764.0   John Wall         120.2 2011-04-09  98.900000
28867  21001205  1610612764.0   John Wall          85.2 2011-04-11  98.698529
29167  21001218  1610612764.0   John Wall         116.1 2011-04-13  98.950725

In [135]:
df_injuries[df_injuries.player.str.contains('John Wall')]

,Date,Team,Acquired,Relinquished,Notes,team_id,player
347,2010-11-16,Wizards,,John Wall,placed on IL with sprained left foot,1610612764,John Wall
400,2010-11-21,Wizards,John Wall,,activated from IL,1610612764,John Wall
401,2010-11-21,Wizards,,John Wall,sprained left foot (DNP),1610612764,John Wall
468,2010-11-27,Wizards,,John Wall,bruised right knee (P) / sore left knee (CBC) (DNP),1610612764,John Wall
491,2010-11-29,Wizards,,John Wall,bruised right knee (P) (DNP),1610612764,John Wall
617,2010-12-08,Wizards,,John Wall,sore left foot (DNP),1610612764,John Wall
696,2010-12-14,Wizards,,John Wall,placed on IL with right knee tendinitis (P) / sore left foot (CBC),1610612764,John Wall
729,2010-12-16,Wizards,,John Wallace,right knee tendinitis (DNP),1610612764,John Wallace
731,2010-12-16,Wizards,John Wallace,,activated,1610612764,John Wallace
773,2010-12-18,Wizards,,John Wallace,placed on IL with right knee tendinitis,1610612764,John Wallace
884,2010-12-26,Wizards,John Wallace,,activated from IL,1610612764,John Wallace
5031,2012-09-28,Wizards,,John Wall,stress fracture in left kneecap (out indefinitely),1610612764,John Wall
5055,2012-10-30,Wizards,,John Wall,placed on IL with strained left knee,1610612764,John Wall
6029,2013-01-12,Wizards,John Wall,,activated from IL,1610612764,John Wall
12727,2015-04-08,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
12795,2015-04-12,Wizards,John Wall,,activated from IL,1610612764,John Wall
12872,2015-04-15,Wizards,,John Wall,rest (DTD),1610612764,John Wall
12889,2015-04-18,Wizards,John Wall,,returned to lineup,1610612764,John Wall
12961,2015-05-05,Wizards,,John Wall,placed on IL with fractured left hand/wrist,1610612764,John Wall
12976,2015-05-13,Wizards,John Wall,,activated from IL,1610612764,John Wall
15471,2016-04-06,Wizards,,John Wall,placed on IL with sore/swollen right knee (out for season),1610612764,John Wall
15784,2016-05-05,Wizards,,John Wall,surgery on left knee to remove calcium deposits (out indefinitely),1610612764,John Wall
16102,2016-11-05,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
16127,2016-11-07,Wizards,John Wall,,activated from IL,1610612764,John Wall
16195,2016-11-12,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
16260,2016-11-16,Wizards,John Wall,,activated from IL,1610612764,John Wall
18691,2017-04-10,Wizards,,John Wall,rest / quadriceps injury (DTD),1610612764,John Wall
18786,2017-04-12,Wizards,John Wall,,activated from IL,1610612764,John Wall
18791,2017-04-12,Wizards,,John Wall,rest (DTD),1610612764,John Wall
18837,2017-04-16,Wizards,John Wall,,returned to lineup,1610612764,John Wall
19383,2017-11-05,Wizards,,John Wall,placed on IL with sprained left shoulder,1610612764,John Wall
19408,2017-11-07,Wizards,John Wall,,activated from IL,1610612764,John Wall
19626,2017-11-19,Wizards,,John Wall,sore left knee / left knee inflammation (DTD),1610612764,John Wall
19643,2017-11-20,Wizards,John Wall,,returned to lineup,1610612764,John Wall
19718,2017-11-25,Wizards,,John Wall,placed on IL with sore left knee / left knee inflammation,1610612764,John Wall
20063,2017-12-13,Wizards,John Wall,,activated from IL,1610612764,John Wall
20826,2018-01-27,Wizards,,John Wall,placed on IL with sore left knee,1610612764,John Wall
20909,2018-01-31,Wizards,,John Wall,arthroscopic surgery on left knee (out indefinitely),1610612764,John Wall
21875,2018-03-31,Wizards,John Wall,,activated from IL,1610612764,John Wall
21910,2018-04-01,Wizards,,John Wall,rest (DTD),1610612764,John Wall
22033,2018-04-06,Wizards,,John Wall,placed on IL for rest,1610612764,John Wall
22119,2018-04-10,Wizards,John Wall,,activated from IL,1610612764,John Wall
22155,2018-04-11,Wizards,,John Wall,placed on IL for rest (out for season),1610612764,John Wall

In [136]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains(' Wall')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
98,21000005,1610612765.0,Ben Wallace,102.3,2010-10-27,102.300000
264,21000012,1610612766.0,Gerald Wallace,86.8,2010-10-27,86.800000
388,21000017,1610612764.0,John Wall,75.8,2010-10-28,75.800000
444,21000019,1610612766.0,Gerald Wallace,110.7,2010-10-29,98.750000
566,21000024,1610612765.0,Ben Wallace,94.5,2010-10-29,98.400000
724,21000031,1610612764.0,John Wall,102.1,2010-10-30,88.950000
818,21000035,1610612765.0,Ben Wallace,80.4,2010-10-30,92.400000
888,21000038,1610612766.0,Gerald Wallace,103.7,2010-10-30,100.400000
1144,21000048,1610612764.0,John Wall,102.5,2010-11-02,93.466667
1166,21000049,1610612765.0,Ben Wallace,103.7,2010-11-02,95.225000
1274,21000054,1610612765.0,Ben Wallace,95.2,2010-11-03,95.220000
1296,21000055,1610612766.0,Gerald Wallace,107.3,2010-11-03,102.125000
1680,21000071,1610612766.0,Gerald Wallace,113.1,2010-11-05,104.320000
1694,21000071,1610612765.0,Ben Wallace,105.6,2010-11-05,96.950000
1708,21000072,1610612764.0,John Wall,89.4,2010-11-05,92.450000
1908,21000080,1610612766.0,Gerald Wallace,90.2,2010-11-06,101.966667
1936,21000081,1610612764.0,John Wall,101.3,2010-11-06,94.220000
2174,21000091,1610612765.0,Ben Wallace,98.0,2010-11-07,97.100000
2268,21000095,1610612766.0,Gerald Wallace,95.1,2010-11-08,100.985714
2522,21000106,1610612765.0,Ben Wallace,90.3,2010-11-09,96.250000
2616,21000110,1610612766.0,Gerald Wallace,118.6,2010-11-10,103.187500
2656,21000111,1610612764.0,John Wall,103.8,2010-11-10,95.816667
2951,21000124,1610612766.0,Gerald Wallace,111.8,2010-11-12,104.144444
2967,21000124,1610612764.0,John Wall,88.4,2010-11-12,94.757143
3073,21000129,1610612765.0,Ben Wallace,80.0,2010-11-12,94.444444
3107,21000130,1610612766.0,Gerald Wallace,105.5,2010-11-13,104.280000
3195,21000134,1610612764.0,John Wall,88.7,2010-11-13,94.000000
3337,21000140,1610612765.0,Ben Wallace,107.9,2010-11-14,95.790000
3443,21000144,1610612766.0,Gerald Wallace,117.1,2010-11-15,105.445455
3553,21000149,1610612765.0,Ben Wallace,103.0,2010-11-15,96.445455
3853,21000161,1610612765.0,Ben Wallace,86.0,2010-11-17,95.575000
4175,21000175,1610612766.0,Gerald Wallace,91.7,2010-11-19,104.300000
4355,21000182,1610612766.0,Gerald Wallace,112.8,2010-11-20,104.953846
4593,21000192,1610612764.0,John Wall,NaN,2010-11-21,94.000000
4596,21000192,1610612765.0,Ben Wallace,105.0,2010-11-21,96.300000
4912,21000205,1610612764.0,John Wall,117.0,2010-11-23,96.555556
4919,21000206,1610612766.0,Gerald Wallace,109.3,2010-11-23,105.264286
4944,21000207,1610612765.0,Ben Wallace,84.5,2010-11-23,95.457143
5002,21000209,1610612766.0,Gerald Wallace,109.6,2010-11-24,105.553333
5112,21000214,1610612765.0,Ben Wallace,87.4,2010-11-24,94.920000
5258,21000220,1610612764.0,John Wall,84.7,2010-11-25,95.370000
5314,21000222,1610612766.0,Gerald Wallace,97.4,2010-11-26,105.043750
5388,21000225,1610612765.0,Ben Wallace,129.5,2010-11-26,97.081250
5637,21000235,1610612764.0,John Wall,NaN,2010-11-27,95.370000
5734,21000240,1610612766.0,Gerald Wallace,114.2,2010-11-27,105.582353
5819,21000243,1610612765.0,Ben Wallace,117.4,2010-11-28,98.276471
5984,21000250,1610612764.0,John Wall,NaN,2010-11-29,95.370000
6095,21000255,1610612765.0,Ben Wallace,87.1,2010-11-30,97.655556
6292,21000263,1610612764.0,John Wall,106.5,2010-12-01,96.381818
6336,21000265,1610612765.0,Ben Wallace,59.8,2010-12-01,95.663158
6382,21000267,1610612766.0,Gerald Wallace,81.2,2010-12-01,104.227778
6586,21000275,1610612766.0,Gerald Wallace,86.2,2010-12-03,103.278947
6637,21000277,1610612764.0,John Wall,91.0,2010-12-03,95.933333
6684,21000279,1610612765.0,Ben Wallace,109.6,2010-12-03,96.360000
6910,21000289,1610612766.0,Gerald Wallace,86.9,2010-12-04,102.460000
7092,21000296,1610612765.0,Ben Wallace,140.0,2010-12-05,98.438095
7178,21000300,1610612764.0,John Wall,114.3,2010-12-05,97.346154
7426,21000310,1610612766.0,Gerald Wallace,102.5,2010-12-07,102.461905
7488,21000313,1610612765.0,Ben Wallace,87.3,2010-12-07,97.931818
7538,21000315,1610612764.0,John Wall,106.5,2010-12-07,98.000000
7680,21000321,1610612765.0,Ben Wallace,90.8,2010-12-08,97.621739
7785,21000325,1610612764.0,John Wall,NaN,2010-12-08,98.000000
7894,21000330,1610612766.0,Gerald Wallace,103.3,2010-12-10,102.500000
7958,21000332,1610612764.0,John Wall,95.4,2010-12-10,97.826667
8001,21000334,1610612765.0,Ben Wallace,NaN,2010-12-10,97.621739
8218,21000343,1610612766.0,Gerald Wallace,71.1,2010-12-11,101.134783
8244,21000344,1610612765.0,Ben Wallace,119.1,2010-12-11,98.516667
8626,21000360,1610612766.0,Gerald Wallace,106.0,2010-12-14,101.337500
8700,21000363,1610612765.0,Ben Wallace,105.6,2010-12-14,98.800000
9057,21000378,1610612764.0,John Wall,NaN,2010-12-16,97.826667
9252,21000386,1610612765.0,Ben Wallace,65.1,2010-12-17,97.503846
9660,21000403,1610612765.0,Ben Wallace,107.7,2010-12-19,97.881481
10102,21000422,1610612765.0,Ben Wallace,102.6,2010-12-22,98.050000
10546,21000440,1610612765.0,Ben Wallace,96.3,2010-12-26,97.989655
10611,21000443,1610612764.0,John Wall,77.0,2010-12-26,96.525000
10654,21000445,1610612765.0,Ben Wallace,133.0,2010-12-27,99.156667
10802,21000451,1610612764.0,John Wall,96.1,2010-12-27,96.500000
11096,21000463,1610612766.0,Gerald Wallace,117.2,2010-12-29,101.972000
11127,21000464,1610612764.0,John Wall,111.9,2010-12-29,97.355556
11146,21000465,1610612765.0,Ben Wallace,126.6,2010-12-29,100.041935
11432,21000477,1610612766.0,Gerald Wallace,103.3,2010-12-31,102.023077
11448,21000478,1610612764.0,John Wall,88.7,2010-12-31,96.900000
11542,21000482,1610612765.0,Ben Wallace,98.0,2010-12-31,99.978125
11604,21000484,1610612764.0,John Wall,101.7,2011-01-01,97.140000
12070,21000504,1610612765.0,Ben Wallace,116.3,2011-01-03,100.472727
12238,21000511,1610612765.0,Ben Wallace,86.1,2011-01-04,100.050000
12336,21000515,1610612764.0,John Wall,112.6,2011-01-05,97.876190
12633,21000527,1610612764.0,John Wall,100.6,2011-01-07,98.000000
12858,21000537,1610612764.0,John Wall,101.9,2011-01-08,98.169565
12915,21000539,1610612765.0,Ben Wallace,106.8,2011-01-08,100.242857
13236,21000553,1610612765.0,Ben Wallace,75.0,2011-01-10,99.541667
13322,21000556,1610612764.0,John Wall,127.6,2011-01-11,99.395833
13437,21000561,1610612766.0,Gerald Wallace,113.3,2011-01-12,102.440741
13714,21000573,1610612764.0,John Wall,93.3,2011-01-13,99.152000
13853,21000579,1610612766.0,Gerald Wallace,99.8,2011-01-14,102.346429
14080,21000588,1610612766.0,Gerald Wallace,93.4,2011-01-15,102.037931
14108,21000589,1610612764.0,John Wall,91.7,2011-01-15,98.865385
14348,21000599,1610612764.0,John Wall,122.8,2011-01-17,99.751852
14380,21000601,1610612766.0,Gerald Wallace,95.4,2011-01-17,101.816667
14643,21000612,1610612766.0,Gerald Wallace,84.8,2011-01-18,101.267742
14767,21000617,1610612764.0,John Wall,96.4,2011-01-19,99.632143
14991,21000626,1610612766.0,Gerald Wallace,117.7,2011-01-20,101.781250
15187,21000634,1610612764.0,John Wall,86.2,2011-01-21,99.168966
15303,21000639,1610612766.0,Gerald Wallace,109.0,2011-01-22,102.000000
15355,21000641,1610612764.0,John Wall,91.0,2011-01-22,98.896667
15381,21000642,1610612765.0,Ben Wallace,95.1,2011-01-22,99.421622
15656,21000654,1610612765.0,Ben Wallace,88.5,2011-01-24,99.134211
15726,21000657,1610612764.0,John Wall,88.3,2011-01-24,98.554839
15883,21000663,1610612764.0,John Wall,107.1,2011-01-25,98.821875
15939,21000666,1610612766.0,Gerald Wallace,103.8,2011-01-25,102.052941
16078,21000671,1610612765.0,Ben Wallace,102.5,2011-01-26,99.220513
16155,21000675,1610612766.0,Gerald Wallace,130.5,2011-01-26,102.865714
16430,21000686,1610612765.0,Ben Wallace,NaN,2011-01-28,99.220513
16471,21000688,1610612764.0,John Wall,100.4,2011-01-28,98.869697
16539,21000691,1610612766.0,Gerald Wallace,121.9,2011-01-28,103.394444
16615,21000694,1610612764.0,John Wall,94.8,2011-01-29,98.750000
16755,21000700,1610612766.0,Gerald Wallace,81.6,2011-01-29,102.805405
16886,21000705,1610612765.0,Ben Wallace,NaN,2011-01-30,99.220513
17047,21000712,1610612764.0,John Wall,93.6,2011-01-31,98.602857
17067,21000713,1610612766.0,Gerald Wallace,94.5,2011-01-31,102.586842
17119,21000715,1610612764.0,John Wall,94.0,2011-02-01,98.475000
17284,21000722,1610612766.0,Gerald Wallace,105.1,2011-02-02,102.651282
17301,21000722,1610612765.0,Ben Wallace,60.3,2011-02-02,98.247500
17561,21000733,1610612766.0,Gerald Wallace,108.3,2011-02-04,102.792500
17661,21000737,1610612764.0,John Wall,101.9,2011-02-04,98.567568
17706,21000739,1610612765.0,Ben Wallace,106.4,2011-02-04,98.446341
17848,21000745,1610612766.0,Gerald Wallace,99.7,2011-02-05,102.717073
17876,21000746,1610612764.0,John Wall,103.6,2011-02-05,98.700000
17957,21000750,1610612765.0,Ben Wallace,84.2,2011-02-05,98.107143
18159,21000758,1610612766.0,Gerald Wallace,95.0,2011-02-07,102.533333
18399,21000768,1610612765.0,Ben Wallace,79.7,2011-02-08,97.679070
18506,21000773,1610612765.0,Ben Wallace,103.5,2011-02-09,97.811364
18529,21000774,1610612766.0,Gerald Wallace,110.2,2011-02-09,102.711628
18641,21000778,1610612764.0,John Wall,110.0,2011-02-09,98.989744
18828,21000786,1610612766.0,Gerald Wallace,103.0,2011-02-11,102.718182
18973,21000792,1610612765.0,Ben Wallace,94.4,2011-02-11,97.735556
19056,21000796,1610612766.0,Gerald Wallace,101.9,2011-02-12,102.700000
19119,21000798,1610612764.0,John Wall,81.7,2011-02-12,98.557500
19299,21000806,1610612764.0,John Wall,126.8,2011-02-13,99.246341
19333,21000807,1610612765.0,Ben Wallace,108.7,2011-02-13,97.973913
19450,21000812,1610612766.0,Gerald Wallace,121.3,2011-02-14,103.104348
19500,21000814,1610612765.0,Ben Wallace,113.0,2011-02-14,98.293617
19605,21000819,1610612766.0,Gerald Wallace,98.1,2011-02-15,102.997872
19729,21000824,1610612764.0,John Wall,72.6,2011-02-16,98.611905
19835,21000828,1610612765.0,Ben Wallace,110.0,2011-02-16,98.537500
20073,21000838,1610612766.0,Gerald Wallace,124.1,2011-02-22,103.437500
20101,21000839,1610612764.0,John Wall,74.6,2011-02-22,98.053488
20123,21000840,1610612765.0,Ben Wallace,114.4,2011-02-22,98.861224
20303,21000848,1610612765.0,Ben Wallace,125.6,2011-02-23,99.396000
20353,21000850,1610612764.0,John Wall,98.6,2011-02-23,98.065909
20669,21000863,1610612765.0,Ben Wallace,NaN,2011-02-25,99.396000
20735,21000866,1610612764.0,John Wall,119.4,2011-02-25,98.540000
20913,21000873,1610612764.0,John Wall,93.1,2011-02-26,98.421739
20944,21000874,1610612765.0,Ben Wallace,NaN,2011-02-26,99.396000
21273,21000888,1610612757.0,Gerald Wallace,103.9,2011-02-27,103.446939
21320,21000890,1610612764.0,John Wall,91.0,2011-02-28,98.263830
21584,21000901,1610612757.0,Gerald Wallace,94.4,2011-03-01,103.266000
21655,21000904,1610612764.0,John Wall,101.1,2011-03-02,98.322917
21788,21000910,1610612757.0,Gerald Wallace,127.2,2011-03-02,103.735294
22183,21000926,1610612764.0,John Wall,103.0,2011-03-05,98.418367
22256,21000929,1610612757.0,Gerald Wallace,114.8,2011-03-05,103.948077
22362,21000934,1610612764.0,John Wall,105.2,2011-03-06,98.554000
22531,21000941,1610612757.0,Gerald Wallace,100.3,2011-03-07,103.879245
22757,21000950,1610612764.0,John Wall,82.9,2011-03-08,98.247059
22770,21000951,1610612757.0,Gerald Wallace,125.5,2011-03-08,104.279630
23153,21000967,1610612757.0,Gerald Wallace,96.6,2011-03-11,104.140000
23302,21000973,1610612765.0,Ben Wallace,NaN,2011-03-11,99.396000
23391,21000977,1610612757.0,Gerald Wallace,96.5,2011-03-12,104.003571
23425,21000978,1610612764.0,John Wall,90.8,2011-03-12,98.103846
23564,21000984,1610612765.0,Ben Wallace,NaN,2011-03-12,99.396000
23760,21000992,1610612764.0,John Wall,88.6,2011-03-14,97.924528
23964,21001001,1610612764.0,John Wall,88.8,2011-03-15,97.755556
23998,21001002,1610612757.0,Gerald Wallace,111.5,2011-03-15,104.135088
24070,21001005,1610612765.0,Ben Wallace,132.5,2011-03-16,100.045098
24333,21001016,1610612757.0,Gerald Wallace,138.4,2011-03-17,104.725862
24396,21001019,1610612764.0,John Wall,112.7,2011-03-18,98.027273
24454,21001021,1610612765.0,Ben Wallace,85.6,2011-03-18,99.767308
24765,21001034,1610612757.0,Gerald Wallace,119.4,2011-03-19,104.974576
24792,21001035,1610612764.0,John Wall,105.4,2011-03-20,98.158929
24802,21001036,1610612765.0,Ben Wallace,81.2,2011-03-20,99.416981
24969,21001043,1610612757.0,Gerald Wallace,94.0,2011-03-20,104.791667
25188,21001052,1610612764.0,John Wall,90.4,2011-03-22,98.022807
25197,21001052,1610612757.0,Gerald Wallace,117.0,2011-03-22,104.991803
25499,21001065,1610612764.0,John Wall,100.6,2011-03-23,98.067241
25763,21001076,1610612764.0,John Wall,100.6,2011-03-25,98.110169
25820,21001078,1610612757.0,Gerald Wallace,110.2,2011-03-25,105.075806
26143,21001092,1610612757.0,Gerald Wallace,106.4,2011-03-27,105.096825
26169,21001093,1610612764.0,John Wall,97.4,2011-03-27,98.098333
26310,21001099,1610612757.0,Gerald Wallace,113.8,2011-03-28,105.232812
26337,21001100,1610612764.0,John Wall,97.1,2011-03-28,98.081967
26589,21001110,1610612764.0,John Wall,120.8,2011-03-30,98.448387
26670,21001114,1610612757.0,Gerald Wallace,115.1,2011-03-30,105.384615
26907,21001123,1610612764.0,John Wall,NaN,2011-04-01,98.448387
26932,21001124,1610612765.0,Ben Wallace,NaN,2011-04-01,99.416981
27065,21001130,1610612757.0,Gerald Wallace,117.0,2011-04-01,105.560606
27303,21001140,1610612765.0,Ben Wallace,NaN,2011-04-03,99.416981
27320,21001141,1610612764.0,John Wall,104.8,2011-04-03,98.549206
27496,21001148,1610612757.0,Gerald Wallace,116.3,2011-04-03,105.720896
27610,21001153,1610612765.0,Ben Wallace,92.6,2011-04-05,99.290741
27620,21001153,1610612764.0,John Wall,107.7,2011-04-05,98.692188
27784,21001160,1610612757.0,Gerald Wallace,106.2,2011-04-05,105.727941
27848,21001163,1610612764.0,John Wall,105.9,2011-04-06,98.803077
28133,21001175,1610612757.0,Gerald Wallace,121.5,2011-04-07,105.956522
28232,21001179,1610612764.0,John Wall,83.9,2011-04-08,98.577273
28433,21001187,1610612757.0,Gerald Wallace,119.2,2011-04-08,106.145714
28460,21001188,1610612764.0,John Wall,120.2,2011-04-09,98.900000
28867,21001205,1610612764.0,John Wall,85.2,2011-04-11,98.698529
29079,21001214,1610612757.0,Gerald Wallace,112.4,2011-04-12,106.233803
29167,21001218,1610612764.0,John Wall,116.1,2011-04-13,98.950725
29390,21001227,1610612757.0,Gerald Wallace,NaN,2011-04-13,106.233803
30243,41000161,1610612757.0,Gerald Wallace,100.9,2011-04-16,106.159722
30267,41000162,1610612757.0,Gerald Wallace,104.1,2011-04-19,106.131507
30303,41000163,1610612757.0,Gerald Wallace,108.5,2011-04-21,106.163514
30327,41000164,1610612757.0,Gerald Wallace,102.4,2011-04-23,106.113333
30339,41000165,1610612757.0,Gerald Wallace,94.3,2011-04-25,105.957895
30375,41000166,1610612757.0,Gerald Wallace,120.0,2011-04-28,106.140260

In [137]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains(' Wall')][['TEAM_ID', 'PLAYER_NAME']].value_counts()

TEAM_ID       PLAYER_NAME
1610612764.0  John Wall         75
1610612765.0  Ben Wallace       63
1610612766.0  Gerald Wallace    48
1610612757.0  Gerald Wallace    30
dtype: int64

In [138]:
'''
*****************************************
Jose Barea 
('J.J. Barea', 83)
8
'''

"\n*****************************************\nJose Barea \n('J.J. Barea', 83)\n8\n"

In [139]:
df_inj3[df_inj3.player.str.contains('Barea')]

      game_date       Team     team_id       player   game_id
1042 2011-02-17  Mavericks  1610612742  Jose Barea   21000837

In [140]:
df_inj3[df_inj3.player.str.contains('Barea')].player.value_counts().index.values[0]

'Jose Barea '

In [141]:
df_inj3.player.replace({'Jose Barea ' : 'J.J. Barea'}, inplace=True)

In [142]:
df_inj3[df_inj3.player.str.contains('Barea')]

      game_date       Team     team_id      player   game_id
1042 2011-02-17  Mavericks  1610612742  J.J. Barea  21000837

In [143]:
print(df_inj3[df_inj3.player.str.contains('Barea')].player)

1042    J.J. Barea
Name: player, dtype: object

In [144]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Barea')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
281    21000012  1610612742.0  J.J. Barea          53.6 2010-10-27   53.600000
668    21000028  1610612742.0  J.J. Barea          91.7 2010-10-29   72.650000
968    21000041  1610612742.0  J.J. Barea          84.0 2010-10-31   76.433333
1424   21000060  1610612742.0  J.J. Barea          83.4 2010-11-03   78.175000
2034   21000085  1610612742.0  J.J. Barea          76.6 2010-11-06   77.860000
2396   21000100  1610612742.0  J.J. Barea         108.7 2010-11-08   83.000000
2720   21000114  1610612742.0  J.J. Barea          94.9 2010-11-10   84.700000
3019   21000126  1610612742.0  J.J. Barea         119.4 2010-11-12   89.037500
3499   21000146  1610612742.0  J.J. Barea         114.9 2010-11-15   91.911111
3895   21000163  1610612742.0  J.J. Barea         113.4 2010-11-17   94.060000
4291   21000179  1610612742.0  J.J. Barea          88.9 2010-11-19   93.590909
4399   21000184  1610612742.0  J.J. Barea         124.6 2010-11-20   96.175000
4962   21000207  1610612742.0  J.J. Barea          70.4 2010-11-23   94.192308
5166   21000216  1610612742.0  J.J. Barea         100.6 2010-11-24   94.650000
5454   21000228  1610612742.0  J.J. Barea         116.4 2010-11-26   96.100000
5730   21000239  1610612742.0  J.J. Barea          99.7 2010-11-27   96.325000
6041   21000252  1610612742.0  J.J. Barea          96.7 2010-11-29   96.347059
6427   21000268  1610612742.0  J.J. Barea          92.3 2010-12-01   96.122222
6846   21000286  1610612742.0  J.J. Barea         102.8 2010-12-03   96.473684
7014   21000293  1610612742.0  J.J. Barea         114.2 2010-12-04   97.360000
7482   21000312  1610612742.0  J.J. Barea         105.0 2010-12-07   97.723810
7866   21000328  1610612742.0  J.J. Barea         109.5 2010-12-09   98.259091
8298   21000346  1610612742.0  J.J. Barea          94.2 2010-12-11   98.082609
8586   21000358  1610612742.0  J.J. Barea         111.6 2010-12-13   98.645833
9041   21000377  1610612742.0  J.J. Barea         106.4 2010-12-15   98.956000
9354   21000390  1610612742.0  J.J. Barea         106.0 2010-12-17   99.226923
9821   21000410  1610612742.0  J.J. Barea          95.6 2010-12-20   99.092593
9964   21000416  1610612742.0  J.J. Barea         103.3 2010-12-21   99.242857
10780  21000450  1610612742.0  J.J. Barea         103.2 2010-12-27   99.379310
11008  21000459  1610612742.0  J.J. Barea         106.3 2010-12-28   99.610000
11368  21000474  1610612742.0  J.J. Barea          90.4 2010-12-30   99.312903
11713  21000489  1610612742.0  J.J. Barea          98.1 2011-01-01   99.275000
11858  21000495  1610612742.0  J.J. Barea          99.8 2011-01-02   99.290909
12205  21000509  1610612742.0  J.J. Barea         100.9 2011-01-04   99.338235
12540  21000523  1610612742.0  J.J. Barea         114.7 2011-01-06   99.777143
12990  21000542  1610612742.0  J.J. Barea         112.3 2011-01-08  100.125000
13456  21000562  1610612742.0  J.J. Barea         106.2 2011-01-12  100.289189
13910  21000581  1610612742.0  J.J. Barea         117.8 2011-01-14  100.750000
14172  21000592  1610612742.0  J.J. Barea          75.7 2011-01-15  100.107692
14459  21000604  1610612742.0  J.J. Barea         122.0 2011-01-17  100.655000
14880  21000621  1610612742.0  J.J. Barea         118.6 2011-01-19  101.092683
15011  21000627  1610612742.0  J.J. Barea          66.4 2011-01-20  100.266667
15323  21000640  1610612742.0  J.J. Barea          91.6 2011-01-22  100.065116
15934  21000665  1610612742.0  J.J. Barea         127.2 2011-01-25  100.681818
16270  21000679  1610612742.0  J.J. Barea         106.9 2011-01-27  100.820000
16679  21000696  1610612742.0  J.J. Barea         111.0 2011-01-29  101.041304
17063  21000712  1610612742.0  J.J. Barea         144.1 2011-01-31  101.957447
17316  21000723  1610612742.0  J.J. Barea         118.3 2011-02-02  102.297917
17719  21000740  1610612742.0  J.J. Barea         110.8 2011-02-04  102.471429
17839  21000745  1610612742.0  J.J. Barea          96.1 2011-02-05  102.344000
18236  21000761  1610612742.0  J.J. Barea         121.1 2011-02-07  102.711765
18704  21000781  1610612742.0  J.J. Barea         122.8 2011-02-09  103.098077
18800  21000785  1610612742.0  J.J. Barea         140.7 2011-02-10  103.807547
19183  21000801  1610612742.0  J.J. Barea         129.7 2011-02-12  104.287037
19914  21000831  1610612742.0  J.J. Barea         104.0 2011-02-16  104.281818
20046  21000837  1610612742.0  J.J. Barea           NaN 2011-02-17  104.281818
20513  21000856  1610612742.0  J.J. Barea         153.6 2011-02-23  105.162500
20905  21000873  1610612742.0  J.J. Barea         116.8 2011-02-26  105.366667
21168  21000884  1610612742.0  J.J. Barea         141.1 2011-02-27  105.982759
21455  21000896  1610612742.0  J.J. Barea          83.7 2011-03-01  105.605085
22068  21000921  1610612742.0  J.J. Barea         110.9 2011-03-04  105.693333
22475  21000938  1610612742.0  J.J. Barea         124.8 2011-03-06  106.006557
22630  21000945  1610612742.0  J.J. Barea         106.0 2011-03-07  106.006452
23013  21000961  1610612742.0  J.J. Barea         114.4 2011-03-09  106.139683
23120  21000965  1610612742.0  J.J. Barea         131.3 2011-03-10  106.532813
23525  21000982  1610612742.0  J.J. Barea         109.5 2011-03-12  106.578462
23991  21001002  1610612742.0  J.J. Barea         101.7 2011-03-15  106.504545
24231  21001012  1610612742.0  J.J. Barea         120.0 2011-03-16  106.705970
24508  21001023  1610612742.0  J.J. Barea          96.0 2011-03-18  106.548529
24961  21001042  1610612742.0  J.J. Barea          96.4 2011-03-20  106.401449
25536  21001066  1610612742.0  J.J. Barea          98.0 2011-03-24  106.281429
25979  21001085  1610612742.0  J.J. Barea         118.7 2011-03-26  106.456338
26221  21001095  1610612742.0  J.J. Barea         108.3 2011-03-27  106.481944
26750  21001117  1610612742.0  J.J. Barea         115.7 2011-03-30  106.608219
26797  21001119  1610612742.0  J.J. Barea          71.6 2011-03-31  106.135135
27206  21001136  1610612742.0  J.J. Barea          96.2 2011-04-02  106.002667
27492  21001148  1610612742.0  J.J. Barea         131.9 2011-04-03  106.343421
28078  21001172  1610612742.0  J.J. Barea         110.2 2011-04-06  106.393506
28413  21001186  1610612742.0  J.J. Barea         105.9 2011-04-08  106.387179
28727  21001199  1610612742.0  J.J. Barea         130.4 2011-04-10  106.691139
28955  21001209  1610612742.0  J.J. Barea          92.2 2011-04-11  106.510000
29303  21001223  1610612742.0  J.J. Barea         134.4 2011-04-13  106.854321
30262  41000161  1610612742.0  J.J. Barea          74.9 2011-04-16  106.464634
30287  41000162  1610612742.0  J.J. Barea         119.4 2011-04-19  106.620482
30299  41000163  1610612742.0  J.J. Barea         125.0 2011-04-21  106.839286
30321  41000164  1610612742.0  J.J. Barea          83.1 2011-04-23  106.560000
30358  41000165  1610612742.0  J.J. Barea          60.3 2011-04-25  106.022093
30368  41000166  1610612742.0  J.J. Barea         136.7 2011-04-28  106.374713
30947  41000231  1610612742.0  J.J. Barea         119.6 2011-05-02  106.525000
30971  41000232  1610612742.0  J.J. Barea         112.6 2011-05-04  106.593258
31008  41000233  1610612742.0  J.J. Barea         112.6 2011-05-06  106.660000
31030  41000234  1610612742.0  J.J. Barea         157.6 2011-05-08  107.219780
31176  41000311  1610612742.0  J.J. Barea         126.8 2011-05-17  107.432609
31198  41000312  1610612742.0  J.J. Barea         112.1 2011-05-19  107.482796
31211  41000313  1610612742.0  J.J. Barea         119.8 2011-05-21  107.613830
31235  41000314  1610612742.0  J.J. Barea         109.9 2011-05-23  107.637895
31271  41000315  1610612742.0  J.J. Barea         114.8 2011-05-25  107.712500
31282  41000401  1610612742.0  J.J. Barea          87.1 2011-05-31  107.500000
31307  41000402  1610612742.0  J.J. Barea          75.7 2011-06-02  107.175510
31343  41000403  1610612742.0  J.J. Barea          97.3 2011-06-05  107.075758
31362  41000404  1610612742.0  J.J. Barea         104.5 2011-06-07  107.050000
31386  41000405  1610612742.0  J.J. Barea         129.1 2011-06-09  107.268317
31399  41000406  1610612742.0  J.J. Barea         110.6 2011-06-12  107.300980

In [145]:
'''
*****************************************
Wes Johnson
('Wesley Johnson', 88)
9
'''

"\n*****************************************\nWes Johnson\n('Wesley Johnson', 88)\n9\n"

In [146]:
df_inj3[df_inj3.player.str.contains('Johnson')]

      game_date          Team     team_id         player   game_id
317  2010-12-01         Hawks  1610612737    Joe Johnson  21000261
988  2011-02-11       Raptors  1610612761   Amir Johnson  21000790
1156 2011-03-04  Timberwolves  1610612750    Wes Johnson  21000916
1163 2011-03-05  Timberwolves  1610612750    Wes Johnson  21000926
1226 2011-03-11       Raptors  1610612761   Amir Johnson  21000970
1287 2011-03-19       Blazers  1610612757  Armon Johnson  21001034
1344 2011-03-25       Raptors  1610612761   Amir Johnson  21001079
1360 2011-03-27         Hawks  1610612737    Joe Johnson  21001088
1490 2011-04-06       Raptors  1610612761   Amir Johnson  21001166
1545 2011-04-10       Raptors  1610612761   Amir Johnson  21001196
1576 2011-04-11       Raptors  1610612761   Amir Johnson  21001207
1640 2011-04-13       Raptors  1610612761   Amir Johnson  21001221
1674 2011-04-20        Lakers  1610612747   Trey Johnson  41000152

In [147]:
df_inj3[df_inj3.player.str.contains('Wes ')]

      game_date          Team     team_id       player   game_id
1156 2011-03-04  Timberwolves  1610612750  Wes Johnson  21000916
1163 2011-03-05  Timberwolves  1610612750  Wes Johnson  21000926

In [148]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Wesley Johnson')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
213,21000009,1610612750.0,Wesley Johnson,133.2,2010-10-27,133.200000
619,21000026,1610612750.0,Wesley Johnson,90.2,2010-10-29,111.700000
846,21000036,1610612750.0,Wesley Johnson,94.1,2010-10-30,105.833333
1184,21000050,1610612750.0,Wesley Johnson,90.0,2010-11-02,101.875000
1320,21000056,1610612750.0,Wesley Johnson,100.0,2010-11-03,101.500000
1767,21000074,1610612750.0,Wesley Johnson,108.8,2010-11-05,102.716667
2187,21000092,1610612750.0,Wesley Johnson,102.1,2010-11-07,102.628571
2547,21000107,1610612750.0,Wesley Johnson,97.5,2010-11-09,101.987500
2786,21000117,1610612750.0,Wesley Johnson,97.2,2010-11-10,101.455556
2990,21000125,1610612750.0,Wesley Johnson,113.8,2010-11-12,102.690000
3314,21000139,1610612750.0,Wesley Johnson,112.8,2010-11-14,103.609091
3434,21000144,1610612750.0,Wesley Johnson,94.4,2010-11-15,102.841667
3878,21000162,1610612750.0,Wesley Johnson,133.4,2010-11-17,105.192308
4214,21000176,1610612750.0,Wesley Johnson,85.9,2010-11-19,103.814286
4705,21000197,1610612750.0,Wesley Johnson,103.9,2010-11-22,103.820000
5149,21000215,1610612750.0,Wesley Johnson,109.9,2010-11-24,104.200000
5701,21000238,1610612750.0,Wesley Johnson,91.0,2010-11-27,103.423529
6409,21000268,1610612750.0,Wesley Johnson,96.1,2010-12-01,103.016667
6769,21000283,1610612750.0,Wesley Johnson,95.5,2010-12-03,102.621053
6970,21000291,1610612750.0,Wesley Johnson,129.3,2010-12-04,103.955000
7273,21000304,1610612750.0,Wesley Johnson,104.7,2010-12-06,103.990476
7666,21000320,1610612750.0,Wesley Johnson,101.5,2010-12-08,103.877273
8005,21000334,1610612750.0,Wesley Johnson,109.4,2010-12-10,104.117391
8257,21000345,1610612750.0,Wesley Johnson,93.8,2010-12-11,103.687500
8761,21000366,1610612750.0,Wesley Johnson,112.3,2010-12-14,104.032000
9001,21000376,1610612750.0,Wesley Johnson,112.1,2010-12-15,104.342308
9361,21000391,1610612750.0,Wesley Johnson,101.0,2010-12-17,104.218519
9529,21000398,1610612750.0,Wesley Johnson,96.2,2010-12-18,103.932143
9911,21000414,1610612750.0,Wesley Johnson,93.6,2010-12-20,103.575862
10211,21000426,1610612750.0,Wesley Johnson,95.1,2010-12-22,103.293333
10511,21000439,1610612750.0,Wesley Johnson,90.2,2010-12-26,102.870968
10763,21000449,1610612750.0,Wesley Johnson,131.2,2010-12-27,103.756250
11171,21000466,1610612750.0,Wesley Johnson,114.6,2010-12-29,104.084848
11675,21000487,1610612750.0,Wesley Johnson,113.5,2011-01-01,104.361765
11999,21000501,1610612750.0,Wesley Johnson,120.5,2011-01-03,104.822857
12394,21000517,1610612750.0,Wesley Johnson,99.6,2011-01-05,104.677778
12727,21000531,1610612750.0,Wesley Johnson,87.7,2011-01-07,104.218919
13073,21000546,1610612750.0,Wesley Johnson,112.8,2011-01-09,104.444737
13349,21000557,1610612750.0,Wesley Johnson,84.5,2011-01-11,103.933333
13722,21000573,1610612750.0,Wesley Johnson,121.7,2011-01-13,104.377500
14200,21000593,1610612750.0,Wesley Johnson,130.4,2011-01-15,105.012195
14581,21000609,1610612750.0,Wesley Johnson,NaN,2011-01-17,105.012195
14962,21000625,1610612750.0,Wesley Johnson,106.8,2011-01-19,105.054762
15788,21000659,1610612750.0,Wesley Johnson,112.8,2011-01-24,105.234884
16124,21000673,1610612750.0,Wesley Johnson,101.3,2011-01-26,105.145455
16496,21000689,1610612750.0,Wesley Johnson,108.7,2011-01-28,105.224444
16652,21000695,1610612750.0,Wesley Johnson,115.7,2011-01-29,105.452174
17350,21000724,1610612750.0,Wesley Johnson,80.1,2011-02-02,104.912766
17626,21000736,1610612750.0,Wesley Johnson,112.3,2011-02-04,105.066667
17998,21000751,1610612750.0,Wesley Johnson,94.5,2011-02-05,104.851020
18201,21000760,1610612750.0,Wesley Johnson,115.8,2011-02-07,105.070000
18481,21000772,1610612750.0,Wesley Johnson,112.6,2011-02-08,105.217647
18840,21000787,1610612750.0,Wesley Johnson,90.1,2011-02-11,104.926923
19139,21000799,1610612750.0,Wesley Johnson,88.2,2011-02-12,104.611321
19545,21000816,1610612750.0,Wesley Johnson,32.3,2011-02-14,103.272222
19889,21000830,1610612750.0,Wesley Johnson,93.5,2011-02-16,103.094545
20160,21000842,1610612750.0,Wesley Johnson,101.0,2011-02-22,103.057143
20436,21000853,1610612750.0,Wesley Johnson,92.0,2011-02-23,102.863158
20793,21000868,1610612750.0,Wesley Johnson,91.1,2011-02-25,102.660345
21127,21000882,1610612750.0,Wesley Johnson,127.6,2011-02-27,103.083051
21558,21000900,1610612750.0,Wesley Johnson,89.3,2011-03-01,102.853333
21690,21000906,1610612750.0,Wesley Johnson,100.7,2011-03-02,102.818033
21936,21000916,1610612750.0,Wesley Johnson,NaN,2011-03-04,102.818033
22176,21000926,1610612750.0,Wesley Johnson,NaN,2011-03-05,102.818033
22636,21000945,1610612750.0,Wesley Johnson,122.0,2011-03-07,103.127419
22995,21000960,1610612750.0,Wesley Johnson,77.5,2011-03-09,102.720635
23282,21000972,1610612750.0,Wesley Johnson,133.1,2011-03-11,103.195313
23699,21000990,1610612750.0,Wesley Johnson,67.4,2011-03-13,102.644615
24179,21001010,1610612750.0,Wesley Johnson,103.0,2011-03-16,102.650000
24611,21001028,1610612750.0,Wesley Johnson,95.9,2011-03-18,102.549254
24863,21001038,1610612750.0,Wesley Johnson,89.7,2011-03-20,102.360294
25522,21001066,1610612750.0,Wesley Johnson,89.2,2011-03-24,102.169565
25738,21001075,1610612750.0,Wesley Johnson,101.8,2011-03-25,102.164286
26133,21001091,1610612750.0,Wesley Johnson,92.6,2011-03-27,102.029577
26660,21001113,1610612750.0,Wesley Johnson,66.9,2011-03-30,101.541667
26972,21001126,1610612750.0,Wesley Johnson,70.1,2011-04-01,101.110959
27149,21001134,1610612750.0,Wesley Johnson,98.9,2011-04-02,101.081081
27556,21001151,1610612750.0,Wesley Johnson,100.6,2011-04-05,101.074667
27979,21001168,1610612750.0,Wesley Johnson,90.1,2011-04-06,100.930263
28542,21001192,1610612750.0,Wesley Johnson,79.4,2011-04-09,100.650649
28998,21001211,1610612750.0,Wesley Johnson,124.6,2011-04-11,100.957692
29322,21001224,1610612750.0,Wesley Johnson,112.4,2011-04-13,101.102532

In [149]:
df_inj3.player.replace({'Wes Johnson':'Wesley Johnson'}, inplace=True)

In [150]:
df_inj3[df_inj3.player.str.contains('Wes ')]

Empty DataFrame
Columns: [game_date, Team, team_id, player, game_id]
Index: []

In [151]:
df_inj3[df_inj3.player.str.contains('Wesley')]

      game_date          Team     team_id          player   game_id
1156 2011-03-04  Timberwolves  1610612750  Wesley Johnson  21000916
1163 2011-03-05  Timberwolves  1610612750  Wesley Johnson  21000926

<font color='red'> PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP</font>

In [152]:
df_inj3.player.replace({' Tony Parker' : 'Tony Parker'}, inplace=True)

In [153]:
df_inj3[df_inj3.player.str.contains('Mullens')]

      game_date     Team     team_id        player   game_id
66   2010-10-27  Thunder  1610612760  B.J. Mullens  21000011
199  2010-11-14  Thunder  1610612760  B.J. Mullens  21000141
273  2010-11-24  Thunder  1610612760  B.J. Mullens  21000216
309  2010-11-29  Thunder  1610612760  B.J. Mullens  21000251
813  2011-01-22  Thunder  1610612760  B.J. Mullens  21000647
904  2011-02-02  Thunder  1610612760  B.J. Mullens  21000725
1107 2011-02-27  Thunder  1610612760  B.J. Mullens  21000880
1252 2011-03-14  Thunder  1610612760  B.J. Mullens  21000992
1670 2011-04-17  Thunder  1610612760  B.J. Mullens  41000171

In [154]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Mullens')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
3069,21000128,1610612760.0,Byron Mullens,NaN,2010-11-12,NaN
3932,21000164,1610612760.0,Byron Mullens,120.0,2010-11-17,120.000000
4090,21000171,1610612760.0,Byron Mullens,NaN,2010-11-19,120.000000
4449,21000186,1610612760.0,Byron Mullens,NaN,2010-11-20,120.000000
4724,21000197,1610612760.0,Byron Mullens,NaN,2010-11-22,120.000000
5431,21000227,1610612760.0,Byron Mullens,119.5,2010-11-26,119.750000
5911,21000247,1610612760.0,Byron Mullens,NaN,2010-11-28,119.750000
6271,21000262,1610612760.0,Byron Mullens,102.0,2010-12-01,113.833333
6609,21000276,1610612760.0,Byron Mullens,112.6,2010-12-03,113.525000
7124,21000297,1610612760.0,Byron Mullens,NaN,2010-12-05,113.525000
7303,21000305,1610612760.0,Byron Mullens,0.0,2010-12-06,90.820000
7664,21000320,1610612760.0,Byron Mullens,NaN,2010-12-08,90.820000
8444,21000352,1610612760.0,Byron Mullens,88.1,2010-12-12,90.366667
8972,21000374,1610612760.0,Byron Mullens,82.9,2010-12-15,89.300000
9307,21000388,1610612760.0,Byron Mullens,77.3,2010-12-17,87.800000
9716,21000405,1610612760.0,Byron Mullens,NaN,2010-12-19,87.800000
9939,21000415,1610612760.0,Byron Mullens,93.6,2010-12-21,88.444444
10182,21000425,1610612760.0,Byron Mullens,101.0,2010-12-22,89.700000
10458,21000436,1610612760.0,Byron Mullens,NaN,2010-12-25,89.700000
10794,21000450,1610612760.0,Byron Mullens,NaN,2010-12-27,89.700000
11227,21000468,1610612760.0,Byron Mullens,112.8,2010-12-29,91.800000
11538,21000481,1610612760.0,Byron Mullens,NaN,2010-12-31,91.800000
11695,21000488,1610612760.0,Byron Mullens,81.3,2011-01-01,90.925000
12174,21000508,1610612760.0,Byron Mullens,NaN,2011-01-04,90.925000
12533,21000523,1610612760.0,Byron Mullens,NaN,2011-01-06,90.925000
12971,21000541,1610612760.0,Byron Mullens,NaN,2011-01-08,90.925000
13600,21000568,1610612760.0,Byron Mullens,NaN,2011-01-12,90.925000
13756,21000574,1610612760.0,Byron Mullens,NaN,2011-01-13,90.925000
14605,21000610,1610612760.0,Byron Mullens,NaN,2011-01-17,90.925000
14893,21000622,1610612760.0,Byron Mullens,NaN,2011-01-19,90.925000
16489,21000688,1610612760.0,Byron Mullens,NaN,2011-01-28,90.925000
16801,21000701,1610612760.0,Byron Mullens,NaN,2011-01-30,90.925000
20765,21000867,1610612760.0,Byron Mullens,NaN,2011-02-25,90.925000
21962,21000917,1610612760.0,Byron Mullens,NaN,2011-03-04,90.925000
22453,21000937,1610612760.0,Byron Mullens,NaN,2011-03-06,90.925000
22608,21000944,1610612760.0,Byron Mullens,NaN,2011-03-07,90.925000
22871,21000955,1610612760.0,Byron Mullens,NaN,2011-03-09,90.925000
29351,21001225,1610612760.0,Byron Mullens,90.1,2011-04-13,90.861538

In [155]:
df_inj3.player.replace({'B.J. Mullens':'Byron Mullens'}, inplace=True)

In [156]:
df_inj3[df_inj3.player.str.contains('Mullens')]

      game_date     Team     team_id         player   game_id
66   2010-10-27  Thunder  1610612760  Byron Mullens  21000011
199  2010-11-14  Thunder  1610612760  Byron Mullens  21000141
273  2010-11-24  Thunder  1610612760  Byron Mullens  21000216
309  2010-11-29  Thunder  1610612760  Byron Mullens  21000251
813  2011-01-22  Thunder  1610612760  Byron Mullens  21000647
904  2011-02-02  Thunder  1610612760  Byron Mullens  21000725
1107 2011-02-27  Thunder  1610612760  Byron Mullens  21000880
1252 2011-03-14  Thunder  1610612760  Byron Mullens  21000992
1670 2011-04-17  Thunder  1610612760  Byron Mullens  41000171

In [157]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

{'Bill Walker',
 "Da'Sean Butler",
 'Daniel Orton',
 'Didier Mbenga ',
 'Ed Davis ',
 'Eddy Curry',
 'Gerald Henderson Jr.',
 'Jannero Pargo',
 'Jianlian Yi',
 'Joe Alexander',
 'Joe Smith ',
 'John Wall ',
 'Jonas Jerebko',
 'Kelenna Azubuike',
 'Larry Sanders ',
 'Magnum Rolle',
 'Marcus Thornton ',
 'Matt Janning',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Nene Hilario ',
 'Robert Vaden',
 'Terrico White'}

In [158]:
df_inj3['player'] = df_inj3.player.str.strip()

In [159]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

{'Bill Walker',
 "Da'Sean Butler",
 'Daniel Orton',
 'Didier Mbenga',
 'Eddy Curry',
 'Gerald Henderson Jr.',
 'Jannero Pargo',
 'Jianlian Yi',
 'Joe Alexander',
 'Jonas Jerebko',
 'Kelenna Azubuike',
 'Magnum Rolle',
 'Matt Janning',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Nene Hilario',
 'Robert Vaden',
 'Terrico White'}

In [160]:
#Bill Walker
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Walker')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
152,21000007,1610612752.0,Henry Walker,104.0,2010-10-27,104.000000
535,21000023,1610612752.0,Henry Walker,107.9,2010-10-29,105.950000
787,21000033,1610612752.0,Henry Walker,89.3,2010-10-30,100.400000
1220,21000051,1610612752.0,Henry Walker,115.8,2011-03-28,104.250000
1567,21000066,1610612752.0,Henry Walker,146.1,2010-11-04,112.620000
1724,21000072,1610612752.0,Henry Walker,118.6,2010-11-05,113.616667
2131,21000089,1610612752.0,Henry Walker,88.0,2010-11-07,109.957143
2481,21000104,1610612752.0,Henry Walker,75.3,2010-11-09,105.625000
2708,21000113,1610612752.0,Henry Walker,112.1,2010-11-10,106.344444
2985,21000125,1610612752.0,Henry Walker,NaN,2010-11-12,106.344444
3405,21000142,1610612752.0,Henry Walker,NaN,2010-11-14,106.344444
3753,21000157,1610612752.0,Henry Walker,171.6,2010-11-16,112.870000
3988,21000167,1610612752.0,Henry Walker,96.9,2010-11-17,111.418182
4326,21000181,1610612752.0,Henry Walker,132.0,2010-11-19,113.133333
4543,21000190,1610612752.0,Henry Walker,103.1,2010-11-20,112.361538
4938,21000206,1610612752.0,Henry Walker,78.1,2010-11-23,109.914286
4998,21000209,1610612752.0,Henry Walker,96.6,2010-11-24,109.026667
5609,21000234,1610612752.0,Henry Walker,87.3,2010-11-27,107.668750
5811,21000243,1610612752.0,Henry Walker,93.4,2010-11-28,106.829412
6159,21000257,1610612752.0,Henry Walker,117.0,2010-11-30,107.394444
6748,21000282,1610612752.0,Henry Walker,37.5,2010-12-03,103.715789
7065,21000295,1610612752.0,Henry Walker,NaN,2010-12-05,103.715789
7629,21000318,1610612752.0,Henry Walker,NaN,2010-12-08,103.715789
7953,21000332,1610612752.0,Henry Walker,NaN,2010-12-10,103.715789
8370,21000349,1610612752.0,Henry Walker,173.1,2010-12-12,107.185000
8829,21000368,1610612752.0,Henry Walker,NaN,2010-12-15,107.185000
9162,21000382,1610612752.0,Henry Walker,60.0,2010-12-17,104.938095
9441,21000394,1610612752.0,Henry Walker,NaN,2010-12-18,104.938095
10194,21000425,1610612752.0,Henry Walker,0.0,2010-12-22,100.168182
10387,21000433,1610612752.0,Henry Walker,NaN,2010-12-25,100.168182
10948,21000457,1610612752.0,Henry Walker,122.2,2010-12-28,101.126087
11332,21000473,1610612752.0,Henry Walker,46.0,2010-12-30,98.829167
11800,21000492,1610612752.0,Henry Walker,116.1,2011-01-02,99.520000
12135,21000506,1610612752.0,Henry Walker,117.3,2011-01-04,100.203846
12765,21000533,1610612752.0,Henry Walker,120.7,2011-01-07,100.962963
13167,21000550,1610612752.0,Henry Walker,95.8,2011-01-09,100.778571
13382,21000559,1610612752.0,Henry Walker,106.9,2011-01-11,100.989655
13644,21000570,1610612752.0,Henry Walker,120.3,2011-01-12,101.633333
13896,21000580,1610612752.0,Henry Walker,83.9,2011-01-14,101.061290
14327,21000598,1610612752.0,Henry Walker,115.5,2011-01-17,101.512500
14818,21000619,1610612752.0,Henry Walker,105.6,2011-01-19,101.636364
15227,21000636,1610612752.0,Henry Walker,109.1,2011-01-21,101.855882
15490,21000647,1610612752.0,Henry Walker,68.4,2011-01-22,100.900000
15742,21000657,1610612752.0,Henry Walker,120.2,2011-01-24,101.436111
16247,21000678,1610612752.0,Henry Walker,60.7,2011-01-27,100.335135
16378,21000684,1610612752.0,Henry Walker,86.8,2011-01-28,99.978947
16895,21000705,1610612752.0,Henry Walker,134.3,2011-01-30,100.858974
17328,21000723,1610612752.0,Henry Walker,88.5,2011-02-02,100.550000
17605,21000735,1610612752.0,Henry Walker,0.0,2011-02-04,98.097561
18122,21000756,1610612752.0,Henry Walker,NaN,2011-02-06,98.097561
18671,21000779,1610612752.0,Henry Walker,NaN,2011-02-09,98.097561
19006,21000793,1610612752.0,Henry Walker,NaN,2011-02-11,98.097561
19087,21000797,1610612752.0,Henry Walker,112.6,2011-02-12,98.442857
19863,21000829,1610612752.0,Henry Walker,135.1,2011-02-16,99.295349
20416,21000852,1610612752.0,Henry Walker,118.6,2011-02-23,99.734091
20714,21000865,1610612752.0,Henry Walker,112.2,2011-02-25,100.011111
21241,21000887,1610612752.0,Henry Walker,105.2,2011-02-27,100.123913
21431,21000895,1610612752.0,Henry Walker,93.8,2011-03-01,99.989362
21729,21000907,1610612752.0,Henry Walker,108.8,2011-03-02,100.172917
22017,21000919,1610612752.0,Henry Walker,109.0,2011-03-04,100.353061
22942,21000958,1610612752.0,Henry Walker,NaN,2011-03-09,100.353061
23109,21000965,1610612752.0,Henry Walker,88.3,2011-03-10,100.112000
23693,21000989,1610612752.0,Henry Walker,111.5,2011-03-13,100.335294
23945,21001000,1610612752.0,Henry Walker,68.0,2011-03-15,99.713462
24318,21001015,1610612752.0,Henry Walker,NaN,2011-03-17,99.713462
24450,21001021,1610612752.0,Henry Walker,NaN,2011-03-18,99.713462
24835,21001037,1610612752.0,Henry Walker,NaN,2011-03-20,99.713462
25062,21001046,1610612752.0,Henry Walker,NaN,2011-03-21,99.713462
25373,21001059,1610612752.0,Henry Walker,NaN,2011-03-23,99.713462
25912,21001082,1610612752.0,Henry Walker,82.0,2011-03-26,99.379245
26617,21001111,1610612752.0,Henry Walker,81.0,2011-03-30,99.038889
27385,21001143,1610612752.0,Henry Walker,141.4,2011-04-03,99.809091
27672,21001155,1610612752.0,Henry Walker,133.7,2011-04-05,100.414286
27901,21001165,1610612752.0,Henry Walker,87.3,2011-04-06,100.184211
28186,21001177,1610612752.0,Henry Walker,105.8,2011-04-08,100.281034
28692,21001198,1610612752.0,Henry Walker,103.2,2011-04-10,100.330508
29062,21001213,1610612752.0,Henry Walker,108.3,2011-04-12,100.463333
29115,21001216,1610612752.0,Henry Walker,106.7,2011-04-13,100.565574
29720,41000121,1610612752.0,Henry Walker,95.4,2011-04-17,100.482258
29745,41000122,1610612752.0,Henry Walker,121.5,2011-04-19,100.815873
29781,41000123,1610612752.0,Henry Walker,111.3,2011-04-22,100.979688
29805,41000124,1610612752.0,Henry Walker,94.7,2011-04-24,100.883077

In [161]:
df_inj3[df_inj3.player.str.contains('Walker')]

      game_date    Team     team_id       player   game_id
366  2010-12-06  Knicks  1610612752  Bill Walker  21000304
1173 2011-03-06  Knicks  1610612752  Bill Walker  21000933
1338 2011-03-25  Knicks  1610612752  Bill Walker  21001073

In [162]:
df_inj3.player.replace({'Bill Walker':'Henry Walker'}, inplace=True)
#"Previously known as Bill Walker" by "https://en.wikipedia.org/wiki/Henry_Walker_(basketball)"

In [163]:
df_inj3[df_inj3.player.str.contains('Walker')]

      game_date    Team     team_id        player   game_id
366  2010-12-06  Knicks  1610612752  Henry Walker  21000304
1173 2011-03-06  Knicks  1610612752  Henry Walker  21000933
1338 2011-03-25  Knicks  1610612752  Henry Walker  21001073

In [164]:
#Da'Sean Butler
df_inj3[df_inj3.player.str.contains('Butler')]

      game_date       Team     team_id          player   game_id
165  2010-11-10  Mavericks  1610612742    Caron Butler  21000114
619  2011-01-02  Mavericks  1610612742    Caron Butler  21000495
635  2011-01-04  Mavericks  1610612742    Caron Butler  21000509
1138 2011-03-04      Bulls  1610612741   Rasual Butler  21000915
1347 2011-03-25      Spurs  1610612759  Da'Sean Butler  21001078

In [165]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Butler')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
276,21000012,1610612742.0,Caron Butler,125.5,2010-10-27,125.500000
378,21000016,1610612746.0,Rasual Butler,104.8,2010-10-27,104.800000
660,21000028,1610612742.0,Caron Butler,94.2,2010-10-29,109.850000
680,21000029,1610612746.0,Rasual Butler,101.7,2010-10-29,103.250000
960,21000041,1610612742.0,Caron Butler,114.2,2010-10-31,111.300000
980,21000041,1610612746.0,Rasual Butler,93.8,2010-10-31,100.100000
1097,21000046,1610612746.0,Rasual Butler,63.1,2010-11-01,90.850000
1416,21000060,1610612742.0,Caron Butler,111.8,2010-11-03,111.425000
1529,21000064,1610612746.0,Rasual Butler,114.2,2010-11-03,95.520000
1829,21000077,1610612746.0,Rasual Butler,100.9,2010-11-05,96.416667
2028,21000085,1610612742.0,Caron Butler,106.8,2010-11-06,110.500000
2045,21000086,1610612746.0,Rasual Butler,89.2,2010-11-06,95.385714
2388,21000100,1610612742.0,Caron Butler,87.0,2010-11-08,106.583333
2499,21000105,1610612746.0,Rasual Butler,73.6,2010-11-09,92.662500
2763,21000116,1610612746.0,Rasual Butler,101.1,2010-11-10,93.600000
3088,21000129,1610612746.0,Rasual Butler,90.8,2010-11-12,93.320000
3594,21000150,1610612746.0,Rasual Butler,104.2,2010-11-15,94.309091
3870,21000162,1610612746.0,Rasual Butler,81.9,2010-11-17,93.275000
3887,21000163,1610612742.0,Caron Butler,108.0,2010-11-17,106.785714
4016,21000168,1610612746.0,Rasual Butler,78.5,2010-11-18,92.138462
4283,21000179,1610612742.0,Caron Butler,103.4,2010-11-19,106.362500
4391,21000184,1610612742.0,Caron Butler,114.2,2010-11-20,107.233333
4554,21000190,1610612746.0,Rasual Butler,100.4,2010-11-20,92.728571
4842,21000202,1610612746.0,Rasual Butler,82.0,2010-11-22,92.013333
4954,21000207,1610612742.0,Caron Butler,109.1,2010-11-23,107.420000
5158,21000216,1610612742.0,Caron Butler,110.1,2010-11-24,107.663636
5300,21000221,1610612746.0,Rasual Butler,53.0,2010-11-25,89.575000
5446,21000228,1610612742.0,Caron Butler,98.4,2010-11-26,106.891667
5503,21000230,1610612746.0,Rasual Butler,112.6,2010-11-26,90.929412
5722,21000239,1610612742.0,Caron Butler,110.1,2010-11-27,107.138462
5872,21000245,1610612746.0,Rasual Butler,70.3,2010-11-28,89.783333
6033,21000252,1610612742.0,Caron Butler,120.4,2010-11-29,108.085714
6418,21000268,1610612742.0,Caron Butler,87.6,2010-12-01,106.720000
6522,21000272,1610612746.0,Rasual Butler,88.9,2010-12-01,89.736842
6798,21000284,1610612746.0,Rasual Butler,96.3,2010-12-03,90.065000
6838,21000286,1610612742.0,Caron Butler,101.9,2010-12-03,106.418750
7006,21000293,1610612742.0,Caron Butler,108.5,2010-12-04,106.541176
7206,21000301,1610612746.0,Rasual Butler,109.5,2010-12-05,90.990476
7387,21000308,1610612746.0,Rasual Butler,107.8,2010-12-06,91.754545
7474,21000312,1610612742.0,Caron Butler,105.0,2010-12-07,106.455556
7819,21000326,1610612746.0,Rasual Butler,69.8,2010-12-08,90.800000
7858,21000328,1610612742.0,Caron Butler,106.9,2010-12-09,106.478947
8178,21000341,1610612746.0,Rasual Butler,69.2,2010-12-11,89.900000
8290,21000346,1610612742.0,Caron Butler,126.0,2010-12-11,107.455000
8488,21000354,1610612746.0,Rasual Butler,98.9,2010-12-12,90.260000
8578,21000358,1610612742.0,Caron Butler,101.7,2010-12-13,107.180952
8837,21000369,1610612746.0,Rasual Butler,110.5,2010-12-15,91.038462
9034,21000377,1610612742.0,Caron Butler,115.6,2010-12-15,107.563636
9246,21000386,1610612746.0,Rasual Butler,87.5,2010-12-17,90.907407
9346,21000390,1610612742.0,Caron Butler,112.4,2010-12-17,107.773913
9461,21000395,1610612746.0,Rasual Butler,100.3,2010-12-18,91.242857
9813,21000410,1610612742.0,Caron Butler,96.2,2010-12-20,107.291667
9927,21000414,1610612746.0,Rasual Butler,105.0,2010-12-20,91.717241
9956,21000416,1610612742.0,Caron Butler,119.2,2010-12-21,107.768000
10285,21000429,1610612746.0,Rasual Butler,88.9,2010-12-22,91.623333
10506,21000438,1610612746.0,Rasual Butler,NaN,2010-12-26,91.623333
10772,21000450,1610612742.0,Caron Butler,105.8,2010-12-27,107.692308
10853,21000453,1610612746.0,Rasual Butler,133.3,2010-12-27,92.967742
11000,21000459,1610612742.0,Caron Butler,96.4,2010-12-28,107.274074
11321,21000472,1610612746.0,Rasual Butler,NaN,2010-12-29,92.967742
11360,21000474,1610612742.0,Caron Butler,101.1,2010-12-30,107.053571
11708,21000489,1610612742.0,Caron Butler,100.7,2011-01-01,106.834483
11825,21000493,1610612746.0,Rasual Butler,NaN,2011-01-02,92.967742
12520,21000522,1610612746.0,Rasual Butler,NaN,2011-01-05,92.967742
13065,21000545,1610612746.0,Rasual Butler,NaN,2011-01-09,92.967742
13708,21000572,1610612746.0,Rasual Butler,NaN,2011-01-12,92.967742
14006,21000585,1610612746.0,Rasual Butler,NaN,2011-01-14,92.967742
14281,21000596,1610612746.0,Rasual Butler,NaN,2011-01-16,92.967742
14496,21000605,1610612746.0,Rasual Butler,NaN,2011-01-17,92.967742
14978,21000625,1610612746.0,Rasual Butler,NaN,2011-01-19,92.967742
15036,21000628,1610612746.0,Rasual Butler,NaN,2011-01-20,92.967742
15600,21000651,1610612746.0,Rasual Butler,NaN,2011-01-22,92.967742
15922,21000665,1610612746.0,Rasual Butler,92.9,2011-01-25,92.965625
16138,21000674,1610612746.0,Rasual Butler,93.7,2011-01-26,92.987879
16776,21000700,1610612746.0,Rasual Butler,103.1,2011-01-29,93.285294
17111,21000714,1610612746.0,Rasual Butler,90.7,2011-01-31,93.211429
17473,21000729,1610612746.0,Rasual Butler,112.7,2011-02-02,93.752778
17678,21000738,1610612746.0,Rasual Butler,NaN,2011-02-04,93.752778
18061,21000754,1610612746.0,Rasual Butler,NaN,2011-02-06,93.752778
18371,21000767,1610612746.0,Rasual Butler,64.4,2011-02-08,92.959459
18657,21000779,1610612746.0,Rasual Butler,NaN,2011-02-09,92.959459
18944,21000791,1610612746.0,Rasual Butler,NaN,2011-02-11,92.959459
19352,21000808,1610612746.0,Rasual Butler,NaN,2011-02-13,92.959459
19519,21000815,1610612746.0,Rasual Butler,0.0,2011-02-14,90.513158
19879,21000830,1610612746.0,Rasual Butler,NaN,2011-02-16,90.513158
20191,21000843,1610612746.0,Rasual Butler,118.0,2011-02-22,91.217949
20452,21000854,1610612746.0,Rasual Butler,86.9,2011-02-23,91.110000
20857,21000871,1610612746.0,Rasual Butler,99.1,2011-02-25,91.304878
21037,21000878,1610612746.0,Rasual Butler,NaN,2011-02-26,91.304878
23265,21000971,1610612741.0,Rasual Butler,100.0,2011-03-11,91.511905
23455,21000979,1610612741.0,Rasual Butler,NaN,2011-03-12,91.511905
23982,21001001,1610612741.0,Rasual Butler,69.4,2011-03-15,90.997674
24282,21001014,1610612741.0,Rasual Butler,NaN,2011-03-17,90.997674
24354,21001017,1610612741.0,Rasual Butler,NaN,2011-03-18,90.997674
25086,21001047,1610612741.0,Rasual Butler,170.0,2011-03-21,92.793182
25171,21001051,1610612741.0,Rasual Butler,0.0,2011-03-22,90.731111
25734,21001074,1610612741.0,Rasual Butler,NaN,2011-03-25,90.731111
25961,21001084,1610612741.0,Rasual Butler,NaN,2011-03-26,90.731111
26307,21001098,1610612741.0,Rasual Butler,NaN,2011-03-28,90.731111
26655,21001113,1610612741.0,Rasual Butler,NaN,2011-03-30,90.731111
26919,21001124,1610612741.0,Rasual Butler,NaN,2011-04-01,90.731111
27147,21001133,1610612741.0,Rasual Butler,NaN,2011-04-02,90.731111
27699,21001156,1610612741.0,Rasual Butler,NaN,2011-04-05,90.731111
28131,21001174,1610612741.0,Rasual Butler,300.0,2011-04-07,95.280435
28263,21001180,1610612741.0,Rasual Butler,NaN,2011-04-08,95.280435
28573,21001193,1610612741.0,Rasual Butler,NaN,2011-04-10,95.280435
29053,21001213,1610612741.0,Rasual Butler,NaN,2011-04-12,95.280435
29281,21001222,1610612741.0,Rasual Butler,134.3,2011-04-13,96.110638
29498,41000101,1610612741.0,Rasual Butler,NaN,2011-04-16,96.110638
29522,41000102,1610612741.0,Rasual Butler,NaN,2011-04-18,96.110638
29534,41000103,1610612741.0,Rasual Butler,NaN,2011-04-21,96.110638
29558,41000104,1610612741.0,Rasual Butler,NaN,2011-04-23,96.110638
29593,41000105,1610612741.0,Rasual Butler,101.5,2011-04-26,96.222917
30530,41000201,1610612741.0,Rasual Butler,NaN,2011-05-02,96.222917
30554,41000202,1610612741.0,Rasual Butler,NaN,2011-05-04,96.222917
30565,41000203,1610612741.0,Rasual Butler,51.5,2011-05-06,95.310204
30589,41000204,1610612741.0,Rasual Butler,NaN,2011-05-08,95.310204
30625,41000205,1610612741.0,Rasual Butler,200.0,2011-05-10,97.404000
30637,41000206,1610612741.0,Rasual Butler,NaN,2011-05-12,97.404000
31057,41000301,1610612741.0,Rasual Butler,NaN,2011-05-15,97.404000
31081,41000302,1610612741.0,Rasual Butler,NaN,2011-05-18,97.404000
31093,41000303,1610612741.0,Rasual Butler,NaN,2011-05-22,97.404000
31117,41000304,1610612741.0,Rasual Butler,NaN,2011-05-24,97.404000
31153,41000305,1610612741.0,Rasual Butler,NaN,2011-05-26,97.404000

In [166]:
#df_inj2[df_inj2.player.str.contains("Da'Sean Butler")]
df_inj3[df_inj3.player.str.contains("Da'Sean Butler")]

      game_date   Team     team_id          player   game_id
1347 2011-03-25  Spurs  1610612759  Da'Sean Butler  21001078

In [167]:
df_inj3[~df_inj3.player.str.contains("Da'Sean Butler")]

      game_date       Team     team_id              player   game_id
0    2010-10-26    Blazers  1610612757     Elliot Williams  21000002
1    2010-10-26    Blazers  1610612757           Greg Oden  21000002
2    2010-10-26    Blazers  1610612757      Joel Przybilla  21000002
3    2010-10-26    Celtics  1610612738       Avery Bradley  21000001
4    2010-10-26    Celtics  1610612738    Kendrick Perkins  21000001
...         ...        ...         ...                 ...       ...
1688 2011-05-26      Bulls  1610612741           Omer Asik  41000305
1689 2011-05-31       Heat  1610612748  Zydrunas Ilgauskas  41000401
1690 2011-06-05  Mavericks  1610612742     Brendan Haywood  41000403
1691 2011-06-07  Mavericks  1610612742   Rodrigue Beaubois  41000404
1692 2011-06-09  Mavericks  1610612742     Brendan Haywood  41000405

[1692 rows x 5 columns]

In [168]:
#no play data for Da'Sean Butler -> will be assigned lowest offensive rating in offensive rating lost per team summary statistic

In [169]:
# 'Daniel Orton'
df_inj3[df_inj3.player.str.contains('Daniel Orton')]

      game_date   Team     team_id        player   game_id
75   2010-10-28  Magic  1610612753  Daniel Orton  21000017
525  2010-12-23  Magic  1610612753  Daniel Orton  21000430
1659 2011-04-16  Magic  1610612753  Daniel Orton  41000131

In [170]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Orton')]

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [171]:
df_injuries[df_injuries.player.str.contains('Daniel Orton')]

,Date,Team,Acquired,Relinquished,Notes,team_id,player
95,2010-10-28,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
850,2010-12-23,Magic,,Daniel Orton,arthroscopic surgery on left knee (out for season),1610612753,Daniel Orton
2554,2011-04-16,Magic,,Daniel Orton,placed on IL with surgery on left knee (out for season),1610612753,Daniel Orton
2650,2011-12-25,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
2720,2011-12-30,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
2738,2012-01-01,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
2828,2012-01-06,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
2944,2012-01-12,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
3054,2012-01-18,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
3153,2012-01-23,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
3210,2012-01-26,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
3439,2012-02-08,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
3573,2012-02-17,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
3597,2012-02-19,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
3668,2012-02-22,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
4152,2012-03-21,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
4190,2012-03-23,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
4294,2012-03-28,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton
4337,2012-03-30,Magic,Daniel Orton,,activated from IL,1610612753,Daniel Orton
5090,2012-11-01,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
5204,2012-11-09,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
5234,2012-11-12,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
5523,2012-12-07,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
5609,2012-12-14,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
5679,2012-12-19,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
5749,2012-12-25,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
6046,2013-01-13,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
6076,2013-01-16,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
6313,2013-02-04,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
6553,2013-02-27,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
6583,2013-03-01,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
6622,2013-03-05,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
6821,2013-03-20,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
6878,2013-03-24,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
7093,2013-04-05,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
7129,2013-04-07,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
7157,2013-04-09,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
7380,2013-04-21,Thunder,,Daniel Orton,placed on IL,1610612760,Daniel Orton
7432,2013-05-01,Thunder,Daniel Orton,,activated from IL,1610612760,Daniel Orton
7694,2013-11-08,76ers,,Daniel Orton,sore right knee (DNP),1610612755,Daniel Orton
7714,2013-11-09,76ers,,Daniel Orton,sore right knee (DNP),1610612755,Daniel Orton
7739,2013-11-11,76ers,,Daniel Orton,sore right knee (DNP),1610612755,Daniel Orton

In [172]:
# 'Daniel Orton' out of the 2010-11 season due to injury but returns in 2011-12 season

In [173]:
# 'Didier Mbenga'
df_inj3[df_inj3.player.str.contains('Mbenga')]

      game_date     Team     team_id         player   game_id
353  2010-12-05  Hornets  1610612740  Didier Mbenga  21000298
412  2010-12-13  Hornets  1610612740  Didier Mbenga  21000355
607  2011-01-01  Hornets  1610612740  Didier Mbenga  21000484
751  2011-01-17  Hornets  1610612740  Didier Mbenga  21000603
1102 2011-02-27  Hornets  1610612740  Didier Mbenga  21000885
1390 2011-03-30  Hornets  1610612740  Didier Mbenga  21001114

In [174]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Mbenga')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
233    21000010  1610612740.0   DJ Mbenga          95.6 2010-10-27   95.600000
647    21000027  1610612740.0   DJ Mbenga         167.3 2010-10-29  131.450000
917    21000039  1610612740.0   DJ Mbenga          71.3 2010-10-30  111.400000
1399   21000059  1610612740.0   DJ Mbenga          91.1 2010-11-03  106.325000
1796   21000075  1610612740.0   DJ Mbenga          58.7 2010-11-05   96.800000
1979   21000083  1610612740.0   DJ Mbenga           NaN 2010-11-06   96.800000
2517   21000105  1610612740.0   DJ Mbenga          66.7 2010-11-09   91.783333
3261   21000136  1610612740.0   DJ Mbenga           NaN 2010-11-13   91.783333
3488   21000146  1610612740.0   DJ Mbenga         138.5 2010-11-15   98.457143
3910   21000163  1610612740.0   DJ Mbenga           NaN 2010-11-17   98.457143
4245   21000177  1610612740.0   DJ Mbenga         185.2 2010-11-19  109.300000
4615   21000193  1610612740.0   DJ Mbenga          48.8 2010-11-21  102.577778
4832   21000202  1610612740.0   DJ Mbenga         147.8 2010-11-22  107.100000
5235   21000219  1610612740.0   DJ Mbenga         103.2 2010-11-24  106.745455
5574   21000233  1610612740.0   DJ Mbenga          76.7 2010-11-26  104.241667
5849   21000244  1610612740.0   DJ Mbenga         123.9 2010-11-28  105.753846
6002   21000251  1610612740.0   DJ Mbenga          58.0 2010-11-29  102.342857
6401   21000267  1610612740.0   DJ Mbenga          60.7 2010-12-01   99.566667
6762   21000282  1610612740.0   DJ Mbenga         113.4 2010-12-03  100.431250
7700   21000321  1610612740.0   DJ Mbenga           NaN 2010-12-08  100.431250
8031   21000335  1610612740.0   DJ Mbenga          97.6 2010-12-10  100.264706
8384   21000350  1610612740.0   DJ Mbenga         100.4 2010-12-12  100.272222
8949   21000373  1610612740.0   DJ Mbenga           NaN 2010-12-15  100.272222
9283   21000387  1610612740.0   DJ Mbenga         150.0 2010-12-17  102.889474
9655   21000403  1610612740.0   DJ Mbenga         133.1 2010-12-19  104.400000
9775   21000408  1610612740.0   DJ Mbenga           NaN 2010-12-20  104.400000
10241  21000427  1610612740.0   DJ Mbenga         127.6 2010-12-22  105.504762
10599  21000442  1610612740.0   DJ Mbenga         126.5 2010-12-26  106.459091
10757  21000449  1610612740.0   DJ Mbenga         102.5 2010-12-27  106.286957
11200  21000467  1610612740.0   DJ Mbenga         104.3 2010-12-29  106.204167
11406  21000476  1610612740.0   DJ Mbenga          41.0 2010-12-31  103.596000
13589  21000567  1610612740.0   DJ Mbenga           NaN 2011-01-12  103.596000
13935  21000582  1610612740.0   DJ Mbenga           NaN 2011-01-14  103.596000
14079  21000588  1610612740.0   DJ Mbenga           NaN 2011-01-15  103.596000
15106  21000631  1610612740.0   DJ Mbenga          98.5 2011-01-21  103.400000
15478  21000646  1610612740.0   DJ Mbenga          81.0 2011-01-22  102.570370
15816  21000660  1610612740.0   DJ Mbenga         111.2 2011-01-24  102.878571
16211  21000677  1610612740.0   DJ Mbenga          48.7 2011-01-26  101.010345
16740  21000699  1610612740.0   DJ Mbenga          28.6 2011-01-29   98.596667
16910  21000706  1610612740.0   DJ Mbenga         100.0 2011-01-30   98.641935
17137  21000715  1610612740.0   DJ Mbenga          87.2 2011-02-01   98.284375
17362  21000725  1610612740.0   DJ Mbenga          78.7 2011-02-02   97.690909
17926  21000748  1610612740.0   DJ Mbenga         103.8 2011-02-05   97.870588
18216  21000760  1610612740.0   DJ Mbenga         104.2 2011-02-07   98.051429
18561  21000775  1610612740.0   DJ Mbenga           0.0 2011-02-09   95.327778
18869  21000788  1610612740.0   DJ Mbenga         113.6 2011-02-11   95.821622
19173  21000800  1610612740.0   DJ Mbenga          66.7 2011-02-12   95.055263
19711  21000823  1610612740.0   DJ Mbenga          60.1 2011-02-15   94.158974
19999  21000835  1610612740.0   DJ Mbenga           NaN 2011-02-16   94.158974
20467  21000854  1610612740.0   DJ Mbenga           NaN 2011-02-23   94.158974
20789  21000868  1610612740.0   DJ Mbenga           NaN 2011-02-25   94.158974
25794  21001077  1610612740.0   DJ Mbenga           NaN 2011-03-25   94.158974
26200  21001094  1610612740.0   DJ Mbenga           NaN 2011-03-27   94.158974
27483  21001147  1610612740.0   DJ Mbenga           NaN 2011-04-03   94.158974
28010  21001169  1610612740.0   DJ Mbenga           NaN 2011-04-06   94.158974
28371  21001184  1610612740.0   DJ Mbenga           NaN 2011-04-08   94.158974
28669  21001197  1610612740.0   DJ Mbenga          96.6 2011-04-10   94.220000
28946  21001208  1610612740.0   DJ Mbenga           NaN 2011-04-11   94.220000
29293  21001223  1610612740.0   DJ Mbenga          80.6 2011-04-13   93.887805
30107  41000151  1610612740.0   DJ Mbenga         106.0 2011-04-17   94.176190
30132  41000152  1610612740.0   DJ Mbenga          83.3 2011-04-20   93.923256
30169  41000153  1610612740.0   DJ Mbenga          90.4 2011-04-22   93.843182
30192  41000154  1610612740.0   DJ Mbenga         138.9 2011-04-24   94.844444
30206  41000155  1610612740.0   DJ Mbenga           NaN 2011-04-26   94.844444
30240  41000156  1610612740.0   DJ Mbenga         133.2 2011-04-28   95.678261

<font color='red'> RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR </font>

In [175]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

{"Da'Sean Butler",
 'Daniel Orton',
 'Didier Mbenga',
 'Eddy Curry',
 'Gerald Henderson Jr.',
 'Jannero Pargo',
 'Jianlian Yi',
 'Joe Alexander',
 'Jonas Jerebko',
 'Kelenna Azubuike',
 'Magnum Rolle',
 'Matt Janning',
 'Mike Conley Jr.',
 'Mike Dunleavy Jr.',
 'Nene Hilario',
 'Robert Vaden',
 'Terrico White'}

In [176]:
set(df_or1011a.PLAYER_NAME) - set(df_inj3.player)

{'Al Jefferson',
 'Al-Farouq Aminu',
 'Andre Miller',
 'Antonio Daniels',
 'Ben Gordon',
 'Blake Griffin',
 'Bobby Simmons',
 'Boris Diaw',
 'Brook Lopez',
 'C.J. Watson',
 'Carl Landry',
 'Chris Johnson',
 'D.J. Augustin',
 'DJ Mbenga',
 'Darnell Jackson',
 'DeMar DeRozan',
 'DeMarcus Cousins',
 'DeShawn Stevenson',
 'Derek Fisher',
 'Donte Greene',
 'Dorell Wright',
 'Earl Barron',
 'Earl Boykins',
 'Earl Clark',
 'Earl Watson',
 'Eddie House',
 'Elton Brand',
 'Eric Bledsoe',
 'Eric Maynor',
 'Evan Turner',
 'Fabricio Oberto',
 'Gary Forbes',
 'Gerald Henderson',
 'Greg Monroe',
 'Hakim Warrick',
 'Hedo Turkoglu',
 'Ike Diogu',
 'Ime Udoka',
 'JR Smith',
 'James Harden',
 'James Johnson',
 'James Jones',
 'Jared Dudley',
 'Jarrett Jack',
 'Jarron Collins',
 'Jason Terry',
 'Jawad Williams',
 'Jeff Teague',
 'Joel Anthony',
 'Johan Petro',
 'Josh Childress',
 'Jrue Holiday',
 'Keith Bogans',
 'Kobe Bryant',
 'Kyle Korver',
 'Kyle Weaver',
 'Lamar Odom',
 'Landry Fields',
 'Larry Owens',
 'Luol Deng',
 'Marcin Gortat',
 'Marcus Cousin',
 'Marqus Blakely',
 'Marreese Speights',
 'Metta World Peace',
 'Mike Bibby',
 'Mike Conley',
 'Mike Dunleavy',
 'Mike Harris',
 'Nene',
 'Patrick Ewing',
 'Pau Gasol',
 'Ramon Sessions',
 'Richard Jefferson',
 'Ronald Dupree',
 'Royal Ivey',
 'Russell Westbrook',
 'Sam Young',
 'Sasha Pavlovic',
 'Serge Ibaka',
 'Shane Battier',
 'Shannon Brown',
 'Thaddeus Young',
 'Travis Outlaw',
 'Vladimir Radmanovic',
 'Wesley Matthews',
 'Willie Green',
 'Yi Jianlian'}

In [177]:
# 'Gerald Henderson'
df_inj3[df_inj3.player.str.contains('Gerald Henderson')]

     game_date     Team     team_id                player   game_id
203 2010-11-15  Bobcats  1610612766  Gerald Henderson Jr.  21000144

In [178]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Henderson')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
270,21000012,1610612766.0,Gerald Henderson,106.4,2010-10-27,106.400000
449,21000019,1610612766.0,Gerald Henderson,131.2,2010-10-29,118.800000
897,21000038,1610612766.0,Gerald Henderson,117.1,2010-10-30,118.233333
1303,21000055,1610612766.0,Gerald Henderson,62.0,2010-11-03,104.175000
1689,21000071,1610612766.0,Gerald Henderson,83.3,2010-11-05,100.000000
1916,21000080,1610612766.0,Gerald Henderson,92.4,2010-11-06,98.733333
2274,21000095,1610612766.0,Gerald Henderson,111.4,2010-11-08,100.542857
2623,21000110,1610612766.0,Gerald Henderson,101.6,2010-11-10,100.675000
2958,21000124,1610612766.0,Gerald Henderson,80.0,2010-11-12,98.377778
3118,21000130,1610612766.0,Gerald Henderson,NaN,2010-11-13,98.377778
8635,21000360,1610612766.0,Gerald Henderson,85.0,2010-12-14,97.040000
8912,21000372,1610612766.0,Gerald Henderson,93.4,2010-12-15,96.709091
9220,21000385,1610612766.0,Gerald Henderson,96.2,2010-12-17,96.666667
9797,21000409,1610612766.0,Gerald Henderson,64.1,2010-12-20,94.161538
9951,21000415,1610612766.0,Gerald Henderson,91.7,2010-12-21,93.985714
10667,21000445,1610612766.0,Gerald Henderson,113.0,2010-12-27,95.253333
11102,21000463,1610612766.0,Gerald Henderson,38.1,2010-12-29,91.681250
11440,21000477,1610612766.0,Gerald Henderson,107.4,2010-12-31,92.605882
11963,21000499,1610612766.0,Gerald Henderson,77.4,2011-01-03,91.761111
12382,21000517,1610612766.0,Gerald Henderson,97.5,2011-01-05,92.063158
12869,21000537,1610612766.0,Gerald Henderson,113.9,2011-01-08,93.155000
13201,21000551,1610612766.0,Gerald Henderson,105.8,2011-01-10,93.757143
13442,21000561,1610612766.0,Gerald Henderson,53.0,2011-01-12,91.904545
13860,21000579,1610612766.0,Gerald Henderson,110.1,2011-01-14,92.695652
14086,21000588,1610612766.0,Gerald Henderson,93.8,2011-01-15,92.741667
14386,21000601,1610612766.0,Gerald Henderson,57.4,2011-01-17,91.328000
14649,21000612,1610612766.0,Gerald Henderson,91.3,2011-01-18,91.326923
14996,21000626,1610612766.0,Gerald Henderson,134.8,2011-01-20,92.937037
15309,21000639,1610612766.0,Gerald Henderson,104.3,2011-01-22,93.342857
15946,21000666,1610612766.0,Gerald Henderson,115.2,2011-01-25,94.096552
16160,21000675,1610612766.0,Gerald Henderson,134.4,2011-01-26,95.440000
16545,21000691,1610612766.0,Gerald Henderson,128.3,2011-01-28,96.500000
16761,21000700,1610612766.0,Gerald Henderson,101.2,2011-01-29,96.646875
17073,21000713,1610612766.0,Gerald Henderson,76.0,2011-01-31,96.021212
17290,21000722,1610612766.0,Gerald Henderson,101.1,2011-02-02,96.170588
17568,21000733,1610612766.0,Gerald Henderson,107.5,2011-02-04,96.494286
17856,21000745,1610612766.0,Gerald Henderson,93.5,2011-02-05,96.411111
18164,21000758,1610612766.0,Gerald Henderson,99.2,2011-02-07,96.486486
18534,21000774,1610612766.0,Gerald Henderson,108.0,2011-02-09,96.789474
18834,21000786,1610612766.0,Gerald Henderson,91.5,2011-02-11,96.653846
19063,21000796,1610612766.0,Gerald Henderson,42.9,2011-02-12,95.310000
19457,21000812,1610612766.0,Gerald Henderson,138.8,2011-02-14,96.370732
19611,21000819,1610612766.0,Gerald Henderson,112.5,2011-02-15,96.754762
20079,21000838,1610612766.0,Gerald Henderson,105.9,2011-02-22,96.967442
20627,21000861,1610612766.0,Gerald Henderson,116.8,2011-02-25,97.418182
21139,21000883,1610612766.0,Gerald Henderson,96.2,2011-02-27,97.391111
21762,21000909,1610612766.0,Gerald Henderson,84.2,2011-03-02,97.104348
22122,21000924,1610612766.0,Gerald Henderson,84.1,2011-03-04,96.827660
22241,21000929,1610612766.0,Gerald Henderson,77.3,2011-03-05,96.420833
22517,21000940,1610612766.0,Gerald Henderson,96.2,2011-03-07,96.416327
22827,21000953,1610612766.0,Gerald Henderson,99.4,2011-03-09,96.476000
23162,21000967,1610612766.0,Gerald Henderson,81.6,2011-03-11,96.184314
23603,21000986,1610612766.0,Gerald Henderson,112.8,2011-03-13,96.503846
24155,21001009,1610612766.0,Gerald Henderson,87.2,2011-03-16,96.328302
24467,21001022,1610612766.0,Gerald Henderson,68.4,2011-03-18,95.811111
24731,21001033,1610612766.0,Gerald Henderson,98.0,2011-03-19,95.850909
25246,21001054,1610612766.0,Gerald Henderson,93.2,2011-03-23,95.803571
25618,21001070,1610612766.0,Gerald Henderson,103.1,2011-03-25,95.931579
25917,21001082,1610612766.0,Gerald Henderson,121.5,2011-03-26,96.372414
26252,21001096,1610612766.0,Gerald Henderson,97.3,2011-03-28,96.388136
26492,21001106,1610612766.0,Gerald Henderson,134.9,2011-03-30,97.030000
26840,21001121,1610612766.0,Gerald Henderson,90.8,2011-04-01,96.927869
27331,21001141,1610612766.0,Gerald Henderson,91.3,2011-04-03,96.837097
27535,21001150,1610612766.0,Gerald Henderson,93.9,2011-04-05,96.790476
27835,21001162,1610612766.0,Gerald Henderson,98.2,2011-04-06,96.812500
28303,21001182,1610612766.0,Gerald Henderson,115.1,2011-04-08,97.093846
28626,21001195,1610612766.0,Gerald Henderson,131.4,2011-04-10,97.613636
28806,21001203,1610612766.0,Gerald Henderson,123.7,2011-04-11,98.002985
29154,21001217,1610612766.0,Gerald Henderson,106.1,2011-04-13,98.122059

In [179]:
df_inj3.player.replace({'Gerald Henderson Jr.':'Gerald Henderson'}, inplace=True)

In [180]:
'''
Compare these two access methods:

In [357]: dfmi['one']['second']
Out[357]: 
0    b
1    f
2    j
3    n
Name: second, dtype: object
In [358]: dfmi.loc[:, ('one', 'second')]
Out[358]: 
0    b
1    f
2    j
3    n
Name: (one, second), dtype: object
These both yield the same results, so which should you use? It is instructive to understand the order of operations on these and why method 2 (.loc)
is much preferred over method 1 (chained []).

dfmi['one'] selects the first level of the columns and returns a DataFrame that is singly-indexed. Then another Python operation dfmi_with_one['second']
selects the series indexed by 'second'. This is indicated by the variable dfmi_with_one because pandas sees these operations as separate events. e.g.
separate calls to __getitem__, so it has to treat them as linear operations, they happen one after another.

Contrast this to df.loc[:,('one','second')] which passes a nested tuple of (slice(None),('one','second')) to a single call to __getitem__.
This allows pandas to deal with this as a single entity. Furthermore this order of operations can be significantly faster, and allows one to
index both axes if so desired.
'''

"\nCompare these two access methods:\n\nIn [357]: dfmi['one']['second']\nOut[357]: \n0    b\n1    f\n2    j\n3    n\nName: second, dtype: object\nIn [358]: dfmi.loc[:, ('one', 'second')]\nOut[358]: \n0    b\n1    f\n2    j\n3    n\nName: (one, second), dtype: object\nThese both yield the same results, so which should you use? It is instructive to understand the order of operations on these and why method 2 (.loc)\nis much preferred over method 1 (chained []).\n\ndfmi['one'] selects the first level of the columns and returns a DataFrame that is singly-indexed. Then another Python operation dfmi_with_one['second']\nselects the series indexed by 'second'. This is indicated by the variable dfmi_with_one because pandas sees these operations as separate events. e.g.\nseparate calls to __getitem__, so it has to treat them as linear operations, they happen one after another.\n\nContrast this to df.loc[:,('one','second')] which passes a nested tuple of (slice(None),('one','second')) to a single call to __getitem__.\nThis allows pandas to deal with this as a single entity. Furthermore this order of operations can be significantly faster, and allows one to\nindex both axes if so desired.\n"

In [181]:
df_inj3[df_inj3.player.str.contains('Gerald Henderson')]

     game_date     Team     team_id            player   game_id
203 2010-11-15  Bobcats  1610612766  Gerald Henderson  21000144

In [182]:
print(df_inj3[df_inj3.player.str.contains('Gerald Henderson')].player)

203    Gerald Henderson
Name: player, dtype: object

In [183]:
#'Jianlian Yi'

df_inj3[df_inj3.player.str.contains('Jianlian Yi')]

     game_date     Team     team_id       player   game_id
222 2010-11-16  Wizards  1610612764  Jianlian Yi  21000153
449 2010-12-16  Wizards  1610612764  Jianlian Yi  21000378
970 2011-02-09  Wizards  1610612764  Jianlian Yi  21000778

In [184]:
df_inj3[df_inj3.player.str.contains('Jianlian')]

     game_date     Team     team_id       player   game_id
222 2010-11-16  Wizards  1610612764  Jianlian Yi  21000153
449 2010-12-16  Wizards  1610612764  Jianlian Yi  21000378
970 2011-02-09  Wizards  1610612764  Jianlian Yi  21000778

In [185]:
df_inj3[df_inj3.player.str.contains('Yi')]

     game_date     Team     team_id       player   game_id
222 2010-11-16  Wizards  1610612764  Jianlian Yi  21000153
449 2010-12-16  Wizards  1610612764  Jianlian Yi  21000378
970 2011-02-09  Wizards  1610612764  Jianlian Yi  21000778

In [186]:
df_inj3.player.replace({'Jianlian Yi':'Yi Jianlian'}, inplace=True)

In [187]:
df_inj3[df_inj3.player.str.contains('Yi')]

     game_date     Team     team_id       player   game_id
222 2010-11-16  Wizards  1610612764  Yi Jianlian  21000153
449 2010-12-16  Wizards  1610612764  Yi Jianlian  21000378
970 2011-02-09  Wizards  1610612764  Yi Jianlian  21000778

In [188]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Yi')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Yi')]

(66, 6)

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
391,21000017,1610612764.0,Yi Jianlian,75.7,2010-10-28,75.700000
725,21000031,1610612764.0,Yi Jianlian,120.2,2010-10-30,97.950000
1148,21000048,1610612764.0,Yi Jianlian,114.5,2010-11-02,103.466667
1713,21000072,1610612764.0,Yi Jianlian,85.8,2010-11-05,99.050000
1939,21000081,1610612764.0,Yi Jianlian,90.9,2010-11-06,97.420000
2657,21000111,1610612764.0,Yi Jianlian,104.5,2010-11-10,98.600000
2968,21000124,1610612764.0,Yi Jianlian,105.0,2010-11-12,99.514286
3196,21000134,1610612764.0,Yi Jianlian,110.8,2010-11-13,100.925000
6642,21000277,1610612764.0,Yi Jianlian,78.7,2010-12-03,98.455556
7180,21000300,1610612764.0,Yi Jianlian,106.6,2010-12-05,99.270000
7535,21000315,1610612764.0,Yi Jianlian,87.0,2010-12-07,98.154545
7781,21000325,1610612764.0,Yi Jianlian,87.5,2010-12-08,97.266667
7961,21000332,1610612764.0,Yi Jianlian,95.2,2010-12-10,97.107692
8675,21000362,1610612764.0,Yi Jianlian,88.9,2010-12-14,96.521429
11454,21000478,1610612764.0,Yi Jianlian,133.3,2010-12-31,98.973333
11611,21000484,1610612764.0,Yi Jianlian,NaN,2011-01-01,98.973333
12343,21000515,1610612764.0,Yi Jianlian,NaN,2011-01-05,98.973333
12635,21000527,1610612764.0,Yi Jianlian,119.0,2011-01-07,100.225000
12864,21000537,1610612764.0,Yi Jianlian,115.1,2011-01-08,101.100000
13323,21000556,1610612764.0,Yi Jianlian,93.5,2011-01-11,100.677778
13716,21000573,1610612764.0,Yi Jianlian,97.0,2011-01-13,100.484211
14111,21000589,1610612764.0,Yi Jianlian,109.3,2011-01-15,100.925000
14351,21000599,1610612764.0,Yi Jianlian,101.3,2011-01-17,100.942857
14774,21000617,1610612764.0,Yi Jianlian,75.4,2011-01-19,99.781818
15191,21000634,1610612764.0,Yi Jianlian,81.8,2011-01-21,99.000000
15358,21000641,1610612764.0,Yi Jianlian,98.2,2011-01-22,98.966667
15732,21000657,1610612764.0,Yi Jianlian,66.7,2011-01-24,97.676000
15890,21000663,1610612764.0,Yi Jianlian,119.6,2011-01-25,98.519231
16472,21000688,1610612764.0,Yi Jianlian,91.0,2011-01-28,98.240741
16618,21000694,1610612764.0,Yi Jianlian,103.7,2011-01-29,98.435714
17050,21000712,1610612764.0,Yi Jianlian,97.6,2011-01-31,98.406897
17122,21000715,1610612764.0,Yi Jianlian,77.8,2011-02-01,97.720000
17665,21000737,1610612764.0,Yi Jianlian,89.6,2011-02-04,97.458065
17877,21000746,1610612764.0,Yi Jianlian,78.3,2011-02-05,96.859375
18648,21000778,1610612764.0,Yi Jianlian,NaN,2011-02-09,96.859375
19122,21000798,1610612764.0,Yi Jianlian,103.8,2011-02-12,97.069697
19304,21000806,1610612764.0,Yi Jianlian,115.8,2011-02-13,97.620588
19732,21000824,1610612764.0,Yi Jianlian,99.2,2011-02-16,97.665714
20107,21000839,1610612764.0,Yi Jianlian,74.7,2011-02-22,97.027778
20354,21000850,1610612764.0,Yi Jianlian,67.9,2011-02-23,96.240541
20740,21000866,1610612764.0,Yi Jianlian,142.6,2011-02-25,97.460526
20919,21000873,1610612764.0,Yi Jianlian,144.4,2011-02-26,98.664103
21326,21000890,1610612764.0,Yi Jianlian,150.0,2011-02-28,99.947500
21662,21000904,1610612764.0,Yi Jianlian,95.8,2011-03-02,99.846341
22189,21000926,1610612764.0,Yi Jianlian,82.0,2011-03-05,99.421429
22368,21000934,1610612764.0,Yi Jianlian,69.4,2011-03-06,98.723256
22763,21000950,1610612764.0,Yi Jianlian,68.7,2011-03-08,98.040909
23426,21000978,1610612764.0,Yi Jianlian,31.5,2011-03-12,96.562222
23763,21000992,1610612764.0,Yi Jianlian,93.9,2011-03-14,96.504348
23960,21001001,1610612764.0,Yi Jianlian,83.6,2011-03-15,96.229787
24393,21001019,1610612764.0,Yi Jianlian,114.1,2011-03-18,96.602083
24789,21001035,1610612764.0,Yi Jianlian,104.2,2011-03-20,96.757143
25185,21001052,1610612764.0,Yi Jianlian,75.5,2011-03-22,96.332000
25496,21001065,1610612764.0,Yi Jianlian,105.1,2011-03-23,96.503922
25760,21001076,1610612764.0,Yi Jianlian,111.1,2011-03-25,96.784615
26166,21001093,1610612764.0,Yi Jianlian,112.9,2011-03-27,97.088679
26334,21001100,1610612764.0,Yi Jianlian,80.6,2011-03-28,96.783333
26586,21001110,1610612764.0,Yi Jianlian,99.2,2011-03-30,96.827273
26905,21001123,1610612764.0,Yi Jianlian,116.1,2011-04-01,97.171429
27321,21001141,1610612764.0,Yi Jianlian,112.2,2011-04-03,97.435088
27623,21001153,1610612764.0,Yi Jianlian,100.5,2011-04-05,97.487931
27850,21001163,1610612764.0,Yi Jianlian,104.0,2011-04-06,97.598305
28235,21001179,1610612764.0,Yi Jianlian,103.6,2011-04-08,97.698333
28465,21001188,1610612764.0,Yi Jianlian,129.1,2011-04-09,98.213115
28871,21001205,1610612764.0,Yi Jianlian,87.5,2011-04-11,98.040323
29169,21001218,1610612764.0,Yi Jianlian,76.0,2011-04-13,97.690476

In [189]:
print(df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Jianlian')].shape)
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Jianlian')]

(66, 6)

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
391,21000017,1610612764.0,Yi Jianlian,75.7,2010-10-28,75.700000
725,21000031,1610612764.0,Yi Jianlian,120.2,2010-10-30,97.950000
1148,21000048,1610612764.0,Yi Jianlian,114.5,2010-11-02,103.466667
1713,21000072,1610612764.0,Yi Jianlian,85.8,2010-11-05,99.050000
1939,21000081,1610612764.0,Yi Jianlian,90.9,2010-11-06,97.420000
2657,21000111,1610612764.0,Yi Jianlian,104.5,2010-11-10,98.600000
2968,21000124,1610612764.0,Yi Jianlian,105.0,2010-11-12,99.514286
3196,21000134,1610612764.0,Yi Jianlian,110.8,2010-11-13,100.925000
6642,21000277,1610612764.0,Yi Jianlian,78.7,2010-12-03,98.455556
7180,21000300,1610612764.0,Yi Jianlian,106.6,2010-12-05,99.270000
7535,21000315,1610612764.0,Yi Jianlian,87.0,2010-12-07,98.154545
7781,21000325,1610612764.0,Yi Jianlian,87.5,2010-12-08,97.266667
7961,21000332,1610612764.0,Yi Jianlian,95.2,2010-12-10,97.107692
8675,21000362,1610612764.0,Yi Jianlian,88.9,2010-12-14,96.521429
11454,21000478,1610612764.0,Yi Jianlian,133.3,2010-12-31,98.973333
11611,21000484,1610612764.0,Yi Jianlian,NaN,2011-01-01,98.973333
12343,21000515,1610612764.0,Yi Jianlian,NaN,2011-01-05,98.973333
12635,21000527,1610612764.0,Yi Jianlian,119.0,2011-01-07,100.225000
12864,21000537,1610612764.0,Yi Jianlian,115.1,2011-01-08,101.100000
13323,21000556,1610612764.0,Yi Jianlian,93.5,2011-01-11,100.677778
13716,21000573,1610612764.0,Yi Jianlian,97.0,2011-01-13,100.484211
14111,21000589,1610612764.0,Yi Jianlian,109.3,2011-01-15,100.925000
14351,21000599,1610612764.0,Yi Jianlian,101.3,2011-01-17,100.942857
14774,21000617,1610612764.0,Yi Jianlian,75.4,2011-01-19,99.781818
15191,21000634,1610612764.0,Yi Jianlian,81.8,2011-01-21,99.000000
15358,21000641,1610612764.0,Yi Jianlian,98.2,2011-01-22,98.966667
15732,21000657,1610612764.0,Yi Jianlian,66.7,2011-01-24,97.676000
15890,21000663,1610612764.0,Yi Jianlian,119.6,2011-01-25,98.519231
16472,21000688,1610612764.0,Yi Jianlian,91.0,2011-01-28,98.240741
16618,21000694,1610612764.0,Yi Jianlian,103.7,2011-01-29,98.435714
17050,21000712,1610612764.0,Yi Jianlian,97.6,2011-01-31,98.406897
17122,21000715,1610612764.0,Yi Jianlian,77.8,2011-02-01,97.720000
17665,21000737,1610612764.0,Yi Jianlian,89.6,2011-02-04,97.458065
17877,21000746,1610612764.0,Yi Jianlian,78.3,2011-02-05,96.859375
18648,21000778,1610612764.0,Yi Jianlian,NaN,2011-02-09,96.859375
19122,21000798,1610612764.0,Yi Jianlian,103.8,2011-02-12,97.069697
19304,21000806,1610612764.0,Yi Jianlian,115.8,2011-02-13,97.620588
19732,21000824,1610612764.0,Yi Jianlian,99.2,2011-02-16,97.665714
20107,21000839,1610612764.0,Yi Jianlian,74.7,2011-02-22,97.027778
20354,21000850,1610612764.0,Yi Jianlian,67.9,2011-02-23,96.240541
20740,21000866,1610612764.0,Yi Jianlian,142.6,2011-02-25,97.460526
20919,21000873,1610612764.0,Yi Jianlian,144.4,2011-02-26,98.664103
21326,21000890,1610612764.0,Yi Jianlian,150.0,2011-02-28,99.947500
21662,21000904,1610612764.0,Yi Jianlian,95.8,2011-03-02,99.846341
22189,21000926,1610612764.0,Yi Jianlian,82.0,2011-03-05,99.421429
22368,21000934,1610612764.0,Yi Jianlian,69.4,2011-03-06,98.723256
22763,21000950,1610612764.0,Yi Jianlian,68.7,2011-03-08,98.040909
23426,21000978,1610612764.0,Yi Jianlian,31.5,2011-03-12,96.562222
23763,21000992,1610612764.0,Yi Jianlian,93.9,2011-03-14,96.504348
23960,21001001,1610612764.0,Yi Jianlian,83.6,2011-03-15,96.229787
24393,21001019,1610612764.0,Yi Jianlian,114.1,2011-03-18,96.602083
24789,21001035,1610612764.0,Yi Jianlian,104.2,2011-03-20,96.757143
25185,21001052,1610612764.0,Yi Jianlian,75.5,2011-03-22,96.332000
25496,21001065,1610612764.0,Yi Jianlian,105.1,2011-03-23,96.503922
25760,21001076,1610612764.0,Yi Jianlian,111.1,2011-03-25,96.784615
26166,21001093,1610612764.0,Yi Jianlian,112.9,2011-03-27,97.088679
26334,21001100,1610612764.0,Yi Jianlian,80.6,2011-03-28,96.783333
26586,21001110,1610612764.0,Yi Jianlian,99.2,2011-03-30,96.827273
26905,21001123,1610612764.0,Yi Jianlian,116.1,2011-04-01,97.171429
27321,21001141,1610612764.0,Yi Jianlian,112.2,2011-04-03,97.435088
27623,21001153,1610612764.0,Yi Jianlian,100.5,2011-04-05,97.487931
27850,21001163,1610612764.0,Yi Jianlian,104.0,2011-04-06,97.598305
28235,21001179,1610612764.0,Yi Jianlian,103.6,2011-04-08,97.698333
28465,21001188,1610612764.0,Yi Jianlian,129.1,2011-04-09,98.213115
28871,21001205,1610612764.0,Yi Jianlian,87.5,2011-04-11,98.040323
29169,21001218,1610612764.0,Yi Jianlian,76.0,2011-04-13,97.690476

In [190]:
# 'Mike Conley'
df_inj3[df_inj3.player.str.contains('Mike Conley')]

      game_date       Team     team_id           player   game_id
1612 2011-04-13  Grizzlies  1610612763  Mike Conley Jr.  21001228

In [191]:
df_inj3.player.replace({'Mike Conley Jr.':'Mike Conley'}, inplace=True)

In [192]:
df_inj3[df_inj3.player.str.contains('Mike Conley')]

      game_date       Team     team_id       player   game_id
1612 2011-04-13  Grizzlies  1610612763  Mike Conley  21001228

In [193]:
df_inj3[df_inj3.player.str.contains('Conley')]

      game_date       Team     team_id       player   game_id
1612 2011-04-13  Grizzlies  1610612763  Mike Conley  21001228

In [194]:
df_inj3[df_inj3.player.str.contains('Mike')]

      game_date       Team     team_id             player   game_id
9    2010-10-26       Heat  1610612748        Mike Miller  21000001
1031 2011-02-16       Heat  1610612748        Mike Miller  21000825
1052 2011-02-23     Pacers  1610612754  Mike Dunleavy Jr.  21000848
1379 2011-03-29       Heat  1610612748        Mike Miller  21001101
1389 2011-03-30       Heat  1610612748        Mike Miller  21001110
1414 2011-04-01       Heat  1610612748        Mike Miller  21001126
1612 2011-04-13  Grizzlies  1610612763        Mike Conley  21001228
1619 2011-04-13       Heat  1610612748        Mike Miller  21001221

In [195]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Conley')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
184,21000008,1610612763.0,Mike Conley,123.2,2010-10-27,123.200000
652,21000028,1610612763.0,Mike Conley,105.7,2010-10-29,114.450000
856,21000036,1610612763.0,Mike Conley,104.6,2010-10-30,111.166667
1252,21000053,1610612763.0,Mike Conley,113.0,2010-11-02,111.625000
1492,21000063,1610612763.0,Mike Conley,106.1,2010-11-03,110.520000
1804,21000076,1610612763.0,Mike Conley,106.5,2010-11-05,109.850000
2092,21000088,1610612763.0,Mike Conley,107.0,2010-11-06,109.442857
2368,21000099,1610612763.0,Mike Conley,116.1,2010-11-08,110.275000
2728,21000114,1610612763.0,Mike Conley,105.7,2010-11-10,109.766667
3231,21000135,1610612763.0,Mike Conley,106.8,2010-11-13,109.470000
3459,21000145,1610612763.0,Mike Conley,89.1,2010-11-15,107.618182
3687,21000154,1610612763.0,Mike Conley,112.0,2010-11-16,107.983333
4155,21000174,1610612763.0,Mike Conley,90.9,2010-11-19,106.669231
4431,21000185,1610612763.0,Mike Conley,104.8,2010-11-20,106.535714
5126,21000214,1610612763.0,Mike Conley,123.5,2010-11-24,107.666667
5558,21000232,1610612763.0,Mike Conley,131.7,2010-11-26,109.168750
5642,21000236,1610612763.0,Mike Conley,85.3,2010-11-27,107.764706
6181,21000258,1610612763.0,Mike Conley,112.6,2010-11-30,108.033333
6242,21000261,1610612763.0,Mike Conley,112.6,2010-12-01,108.273684
6734,21000281,1610612763.0,Mike Conley,119.6,2010-12-03,108.840000
7154,21000299,1610612763.0,Mike Conley,114.1,2010-12-05,109.090476
7346,21000307,1610612763.0,Mike Conley,99.5,2010-12-06,108.654545
7730,21000323,1610612763.0,Mike Conley,115.5,2010-12-08,108.952174
8162,21000341,1610612763.0,Mike Conley,94.3,2010-12-11,108.341667
8558,21000357,1610612763.0,Mike Conley,82.5,2010-12-13,107.308000
8918,21000372,1610612763.0,Mike Conley,107.2,2010-12-15,107.303846
9314,21000389,1610612763.0,Mike Conley,85.5,2010-12-17,106.496296
9506,21000397,1610612763.0,Mike Conley,107.3,2010-12-18,106.525000
10020,21000418,1610612763.0,Mike Conley,97.8,2010-12-21,106.224138
10560,21000441,1610612763.0,Mike Conley,105.5,2010-12-26,106.200000
10716,21000447,1610612763.0,Mike Conley,108.4,2010-12-27,106.270968
11280,21000471,1610612763.0,Mike Conley,91.4,2010-12-29,105.806250
11760,21000491,1610612763.0,Mike Conley,99.7,2011-01-01,105.621212
11928,21000498,1610612763.0,Mike Conley,105.0,2011-01-02,105.602941
12180,21000508,1610612763.0,Mike Conley,109.8,2011-01-04,105.722857
12704,21000530,1610612763.0,Mike Conley,107.6,2011-01-07,105.775000
12953,21000541,1610612763.0,Mike Conley,106.5,2011-01-08,105.794595
13190,21000551,1610612763.0,Mike Conley,91.9,2011-01-10,105.428947
13524,21000565,1610612763.0,Mike Conley,109.8,2011-01-12,105.541026
14180,21000592,1610612763.0,Mike Conley,110.2,2011-01-15,105.657500
14372,21000600,1610612763.0,Mike Conley,95.0,2011-01-17,105.397561
14791,21000618,1610612763.0,Mike Conley,105.0,2011-01-19,105.388095
15211,21000635,1610612763.0,Mike Conley,116.3,2011-01-21,105.641860
15535,21000649,1610612763.0,Mike Conley,108.0,2011-01-22,105.695455
15703,21000656,1610612763.0,Mike Conley,102.0,2011-01-24,105.613333
16015,21000669,1610612763.0,Mike Conley,99.2,2011-01-26,105.473913
16327,21000682,1610612763.0,Mike Conley,108.1,2011-01-28,105.529787
16627,21000694,1610612763.0,Mike Conley,114.2,2011-01-29,105.710417
17035,21000711,1610612763.0,Mike Conley,108.0,2011-01-31,105.757143
17336,21000724,1610612763.0,Mike Conley,103.4,2011-02-02,105.710000
17756,21000741,1610612763.0,Mike Conley,121.4,2011-02-04,106.017647
17936,21000749,1610612763.0,Mike Conley,87.8,2011-02-05,105.667308
18187,21000759,1610612763.0,Mike Conley,90.9,2011-02-07,105.388679
18461,21000771,1610612763.0,Mike Conley,113.3,2011-02-08,105.535185
19023,21000794,1610612763.0,Mike Conley,106.2,2011-02-11,105.547273
19382,21000809,1610612763.0,Mike Conley,122.1,2011-02-13,105.842857
19645,21000820,1610612763.0,Mike Conley,96.4,2011-02-15,105.677193
20209,21000844,1610612763.0,Mike Conley,93.2,2011-02-22,105.462069
20425,21000853,1610612763.0,Mike Conley,106.6,2011-02-23,105.481356
20961,21000875,1610612763.0,Mike Conley,125.5,2011-02-26,105.815000
21212,21000886,1610612763.0,Mike Conley,99.5,2011-02-27,105.711475
21511,21000898,1610612763.0,Mike Conley,117.0,2011-03-01,105.893548
22039,21000920,1610612763.0,Mike Conley,102.6,2011-03-04,105.841270
22458,21000938,1610612763.0,Mike Conley,120.7,2011-03-06,106.073437
22613,21000944,1610612763.0,Mike Conley,132.3,2011-03-07,106.476923
22948,21000958,1610612763.0,Mike Conley,120.7,2011-03-09,106.692424
23366,21000976,1610612763.0,Mike Conley,77.9,2011-03-12,106.262687
23808,21000994,1610612763.0,Mike Conley,112.8,2011-03-14,106.358824
24300,21001015,1610612763.0,Mike Conley,116.2,2011-03-17,106.501449
24696,21001031,1610612763.0,Mike Conley,111.9,2011-03-19,106.578571
25104,21001048,1610612763.0,Mike Conley,118.5,2011-03-21,106.746479
25307,21001057,1610612763.0,Mike Conley,90.1,2011-03-23,106.515278
25715,21001074,1610612763.0,Mike Conley,108.6,2011-03-25,106.543836
26110,21001090,1610612763.0,Mike Conley,128.6,2011-03-27,106.841892
26637,21001112,1610612763.0,Mike Conley,122.0,2011-03-30,107.044000
26985,21001127,1610612763.0,Mike Conley,117.2,2011-04-01,107.177632
27165,21001134,1610612763.0,Mike Conley,117.4,2011-04-02,107.310390
27716,21001157,1610612763.0,Mike Conley,88.8,2011-04-05,107.073077
28340,21001183,1610612763.0,Mike Conley,106.4,2011-04-08,107.064557
28675,21001197,1610612763.0,Mike Conley,114.9,2011-04-10,107.162500
29071,21001214,1610612763.0,Mike Conley,111.9,2011-04-12,107.220988
29413,21001228,1610612763.0,Mike Conley,NaN,2011-04-13,107.220988
29959,41000141,1610612763.0,Mike Conley,108.1,2011-04-17,107.231707
29983,41000142,1610612763.0,Mike Conley,86.6,2011-04-20,106.983133
30019,41000143,1610612763.0,Mike Conley,93.7,2011-04-23,106.825000
30043,41000144,1610612763.0,Mike Conley,108.7,2011-04-25,106.847059
30055,41000145,1610612763.0,Mike Conley,103.2,2011-04-27,106.804651
30091,41000146,1610612763.0,Mike Conley,125.0,2011-04-29,107.013793
30775,41000221,1610612763.0,Mike Conley,120.5,2011-05-01,107.167045
30799,41000222,1610612763.0,Mike Conley,109.2,2011-05-03,107.189888
30835,41000223,1610612763.0,Mike Conley,101.6,2011-05-07,107.127778
30859,41000224,1610612763.0,Mike Conley,114.3,2011-05-09,107.206593
30871,41000225,1610612763.0,Mike Conley,63.5,2011-05-11,106.731522
30907,41000226,1610612763.0,Mike Conley,106.6,2011-05-13,106.730108
30919,41000227,1610612763.0,Mike Conley,94.1,2011-05-15,106.595745

In [196]:
# 'Mike Dunleavy Jr.',
df_inj3[df_inj3.player.str.contains('Mike Dunleavy')]

      game_date    Team     team_id             player   game_id
1052 2011-02-23  Pacers  1610612754  Mike Dunleavy Jr.  21000848

In [197]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Mike Dunleavy')].head()

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
291,21000013,1610612754.0,Mike Dunleavy,110.8,2010-10-27,110.800000
435,21000019,1610612754.0,Mike Dunleavy,126.2,2010-10-29,118.500000
807,21000034,1610612754.0,Mike Dunleavy,104.0,2010-10-30,113.666667
1347,21000057,1610612754.0,Mike Dunleavy,76.1,2010-11-03,104.275000
1623,21000068,1610612754.0,Mike Dunleavy,84.3,2010-11-05,100.280000

In [198]:
df_inj3.player.replace({'Mike Dunleavy Jr.':'Mike Dunleavy'}, inplace=True)

In [199]:
df_inj3[df_inj3.player.str.contains('Mike Dunleavy')]

      game_date    Team     team_id         player   game_id
1052 2011-02-23  Pacers  1610612754  Mike Dunleavy  21000848

In [200]:
# 'Nene Hilario',
df_inj3[df_inj3.player.str.contains('Nene')]

      game_date     Team     team_id        player   game_id
114  2010-11-03  Nuggets  1610612743  Nene Hilario  21000060
128  2010-11-05  Nuggets  1610612743  Nene Hilario  21000077
135  2010-11-06  Nuggets  1610612743  Nene Hilario  21000085
579  2010-12-29  Nuggets  1610612743  Nene Hilario  21000466
841  2011-01-26  Nuggets  1610612743  Nene Hilario  21000671
945  2011-02-07  Nuggets  1610612743  Nene Hilario  21000762
1635 2011-04-13  Nuggets  1610612743  Nene Hilario  21001226

In [201]:
df_inj3.player.replace({'Nene Hilario': 'Nene'}, inplace=True)

In [202]:
df_inj3[df_inj3.player.str.contains('Nene')]

      game_date     Team     team_id player   game_id
114  2010-11-03  Nuggets  1610612743   Nene  21000060
128  2010-11-05  Nuggets  1610612743   Nene  21000077
135  2010-11-06  Nuggets  1610612743   Nene  21000085
579  2010-12-29  Nuggets  1610612743   Nene  21000466
841  2011-01-26  Nuggets  1610612743   Nene  21000671
945  2011-02-07  Nuggets  1610612743   Nene  21000762
1635 2011-04-13  Nuggets  1610612743   Nene  21001226

In [203]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Nene')]

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
326    21000014  1610612743.0        Nene         104.4 2010-10-27  104.400000
626    21000027  1610612743.0        Nene         105.2 2010-10-29  104.800000
866    21000037  1610612743.0        Nene         104.3 2010-10-30  104.633333
1439   21000060  1610612743.0        Nene           NaN 2010-11-03  104.633333
1847   21000077  1610612743.0        Nene           NaN 2010-11-05  104.633333
2027   21000085  1610612743.0        Nene           NaN 2010-11-06  104.633333
2330   21000098  1610612743.0        Nene          92.0 2010-11-08  101.475000
2402   21000101  1610612743.0        Nene         105.4 2010-11-09  102.260000
2869   21000120  1610612743.0        Nene         120.5 2010-11-11  105.300000
3505   21000147  1610612743.0        Nene          72.8 2010-11-15  100.657143
3757   21000157  1610612743.0        Nene          95.9 2010-11-16  100.062500
4057   21000170  1610612743.0        Nene         103.5 2010-11-18  100.444444
4501   21000188  1610612743.0        Nene         110.2 2010-11-20  101.420000
4800   21000201  1610612743.0        Nene         115.8 2010-11-22  102.727273
5484   21000229  1610612743.0        Nene         119.5 2010-11-26  104.125000
5939   21000248  1610612743.0        Nene         142.6 2010-11-28  107.084615
6468   21000270  1610612743.0        Nene         112.1 2010-12-01  107.442857
6804   21000284  1610612743.0        Nene         119.9 2010-12-03  108.273333
7164   21000299  1610612743.0        Nene         117.0 2010-12-05  108.818750
7416   21000310  1610612743.0        Nene         108.2 2010-12-07  108.782353
7560   21000316  1610612743.0        Nene          85.8 2010-12-08  107.505556
7920   21000331  1610612743.0        Nene         123.4 2010-12-10  108.342105
8352   21000349  1610612743.0        Nene         118.3 2010-12-12  108.840000
8748   21000365  1610612743.0        Nene         123.3 2010-12-14  109.528571
9108   21000380  1610612743.0        Nene         115.0 2010-12-16  109.777273
9540   21000398  1610612743.0        Nene         102.5 2010-12-18  109.460870
10246  21000428  1610612743.0        Nene         119.1 2010-12-22  109.862500
10438  21000436  1610612743.0        Nene         117.8 2010-12-25  110.180000
10642  21000444  1610612743.0        Nene          94.4 2010-12-26  109.573077
11050  21000461  1610612743.0        Nene         132.6 2010-12-28  110.425926
11167  21000466  1610612743.0        Nene           NaN 2010-12-29  110.425926
11746  21000490  1610612743.0        Nene          86.6 2011-01-01  109.575000
12058  21000503  1610612743.0        Nene         130.5 2011-01-03  110.296552
12501  21000522  1610612743.0        Nene          97.9 2011-01-05  109.883333
12548  21000524  1610612743.0        Nene         117.0 2011-01-06  110.112903
13128  21000548  1610612743.0        Nene          89.8 2011-01-09  109.478125
13367  21000558  1610612743.0        Nene         151.6 2011-01-11  110.754545
13772  21000575  1610612743.0        Nene         142.8 2011-01-13  111.697059
14226  21000594  1610612743.0        Nene         141.3 2011-01-15  112.542857
14286  21000597  1610612743.0        Nene          98.9 2011-01-16  112.163889
14897  21000622  1610612743.0        Nene         116.2 2011-01-19  112.272973
15257  21000637  1610612743.0        Nene         118.9 2011-01-21  112.447368
15617  21000652  1610612743.0        Nene         107.3 2011-01-23  112.315385
15869  21000663  1610612743.0        Nene         114.8 2011-01-25  112.377500
16397  21000685  1610612743.0        Nene         140.1 2011-01-28  113.053659
16853  21000704  1610612743.0        Nene         129.2 2011-01-30  113.438095
16973  21000709  1610612743.0        Nene         104.7 2011-01-31  113.234884
17395  21000726  1610612743.0        Nene         112.5 2011-02-02  113.218182
17826  21000744  1610612743.0        Nene         109.4 2011-02-04  113.133333
17982  21000751  1610612743.0        Nene         115.6 2011-02-05  113.186957
18722  21000782  1610612743.0        Nene         105.1 2011-02-09  113.014894
18806  21000785  1610612743.0        Nene         126.4 2011-02-10  113.293750
19368  21000809  1610612743.0        Nene         106.4 2011-02-13  113.153061
19559  21000817  1610612743.0        Nene          80.4 2011-02-14  112.498000
19943  21000833  1610612743.0        Nene         102.3 2011-02-16  112.298039
20219  21000844  1610612743.0        Nene         121.4 2011-02-22  112.473077
20602  21000860  1610612743.0        Nene          89.8 2011-02-24  112.045283
20876  21000872  1610612743.0        Nene         102.6 2011-02-25  111.870370
21342  21000891  1610612743.0        Nene         100.8 2011-02-28  111.669091
21773  21000909  1610612743.0        Nene         131.8 2011-03-02  112.028571
21857  21000913  1610612743.0        Nene         117.3 2011-03-03  112.121053
22264  21000930  1610612743.0        Nene          97.6 2011-03-05  111.870690
23126  21000966  1610612743.0        Nene         117.9 2011-03-10  111.972881
23567  21000984  1610612743.0        Nene         128.1 2011-03-12  112.241667
23818  21000995  1610612743.0        Nene         116.1 2011-03-14  112.304918
24010  21001003  1610612743.0        Nene         121.3 2011-03-16  112.450000
24370  21001018  1610612743.0        Nene          94.9 2011-03-18  112.171429
24658  21001030  1610612743.0        Nene          92.9 2011-03-19  111.870313
25150  21001050  1610612743.0        Nene         120.2 2011-03-21  111.998462
25485  21001064  1610612743.0        Nene         118.0 2011-03-23  112.089394
25773  21001076  1610612743.0        Nene         121.2 2011-03-25  112.225373
26707  21001115  1610612743.0        Nene         106.3 2011-03-30  112.138235
27079  21001131  1610612743.0        Nene          94.8 2011-04-01  111.886957
27270  21001139  1610612743.0        Nene          85.4 2011-04-03  111.508571
27762  21001159  1610612743.0        Nene          94.2 2011-04-05  111.264789
28062  21001172  1610612743.0        Nene         106.1 2011-04-06  111.193056
28374  21001185  1610612743.0        Nene          93.0 2011-04-08  110.943836
28553  21001192  1610612743.0        Nene         131.5 2011-04-09  111.221622
28985  21001210  1610612743.0        Nene         103.0 2011-04-11  111.112000
30389  41000171  1610612743.0        Nene         102.6 2011-04-17  111.000000
30413  41000172  1610612743.0        Nene         102.0 2011-04-20  110.883117
30449  41000173  1610612743.0        Nene          92.5 2011-04-23  110.647436
30473  41000174  1610612743.0        Nene         104.9 2011-04-25  110.574684
30485  41000175  1610612743.0        Nene          90.3 2011-04-27  110.321250

In [204]:
set(df_inj3.player) - set(df_or1011a.PLAYER_NAME)

{"Da'Sean Butler",
 'Daniel Orton',
 'Didier Mbenga',
 'Eddy Curry',
 'Jannero Pargo',
 'Joe Alexander',
 'Jonas Jerebko',
 'Kelenna Azubuike',
 'Magnum Rolle',
 'Matt Janning',
 'Robert Vaden',
 'Terrico White'}

In [205]:
set(df_or1011a.PLAYER_NAME) - set(df_inj3.player)

{'Al Jefferson',
 'Al-Farouq Aminu',
 'Andre Miller',
 'Antonio Daniels',
 'Ben Gordon',
 'Blake Griffin',
 'Bobby Simmons',
 'Boris Diaw',
 'Brook Lopez',
 'C.J. Watson',
 'Carl Landry',
 'Chris Johnson',
 'D.J. Augustin',
 'DJ Mbenga',
 'Darnell Jackson',
 'DeMar DeRozan',
 'DeMarcus Cousins',
 'DeShawn Stevenson',
 'Derek Fisher',
 'Donte Greene',
 'Dorell Wright',
 'Earl Barron',
 'Earl Boykins',
 'Earl Clark',
 'Earl Watson',
 'Eddie House',
 'Elton Brand',
 'Eric Bledsoe',
 'Eric Maynor',
 'Evan Turner',
 'Fabricio Oberto',
 'Gary Forbes',
 'Greg Monroe',
 'Hakim Warrick',
 'Hedo Turkoglu',
 'Ike Diogu',
 'Ime Udoka',
 'JR Smith',
 'James Harden',
 'James Johnson',
 'James Jones',
 'Jared Dudley',
 'Jarrett Jack',
 'Jarron Collins',
 'Jason Terry',
 'Jawad Williams',
 'Jeff Teague',
 'Joel Anthony',
 'Johan Petro',
 'Josh Childress',
 'Jrue Holiday',
 'Keith Bogans',
 'Kobe Bryant',
 'Kyle Korver',
 'Kyle Weaver',
 'Lamar Odom',
 'Landry Fields',
 'Larry Owens',
 'Luol Deng',
 'Marcin Gortat',
 'Marcus Cousin',
 'Marqus Blakely',
 'Marreese Speights',
 'Metta World Peace',
 'Mike Bibby',
 'Mike Harris',
 'Patrick Ewing',
 'Pau Gasol',
 'Ramon Sessions',
 'Richard Jefferson',
 'Ronald Dupree',
 'Royal Ivey',
 'Russell Westbrook',
 'Sam Young',
 'Sasha Pavlovic',
 'Serge Ibaka',
 'Shane Battier',
 'Shannon Brown',
 'Thaddeus Young',
 'Travis Outlaw',
 'Vladimir Radmanovic',
 'Wesley Matthews',
 'Willie Green'}

In [206]:
#{"Da'Sean Butler"??? <---no offensive rating stats for butler. played 37 games in the G-league the following 2011-12 season
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Butler')]

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
276,21000012,1610612742.0,Caron Butler,125.5,2010-10-27,125.500000
378,21000016,1610612746.0,Rasual Butler,104.8,2010-10-27,104.800000
660,21000028,1610612742.0,Caron Butler,94.2,2010-10-29,109.850000
680,21000029,1610612746.0,Rasual Butler,101.7,2010-10-29,103.250000
960,21000041,1610612742.0,Caron Butler,114.2,2010-10-31,111.300000
980,21000041,1610612746.0,Rasual Butler,93.8,2010-10-31,100.100000
1097,21000046,1610612746.0,Rasual Butler,63.1,2010-11-01,90.850000
1416,21000060,1610612742.0,Caron Butler,111.8,2010-11-03,111.425000
1529,21000064,1610612746.0,Rasual Butler,114.2,2010-11-03,95.520000
1829,21000077,1610612746.0,Rasual Butler,100.9,2010-11-05,96.416667
2028,21000085,1610612742.0,Caron Butler,106.8,2010-11-06,110.500000
2045,21000086,1610612746.0,Rasual Butler,89.2,2010-11-06,95.385714
2388,21000100,1610612742.0,Caron Butler,87.0,2010-11-08,106.583333
2499,21000105,1610612746.0,Rasual Butler,73.6,2010-11-09,92.662500
2763,21000116,1610612746.0,Rasual Butler,101.1,2010-11-10,93.600000
3088,21000129,1610612746.0,Rasual Butler,90.8,2010-11-12,93.320000
3594,21000150,1610612746.0,Rasual Butler,104.2,2010-11-15,94.309091
3870,21000162,1610612746.0,Rasual Butler,81.9,2010-11-17,93.275000
3887,21000163,1610612742.0,Caron Butler,108.0,2010-11-17,106.785714
4016,21000168,1610612746.0,Rasual Butler,78.5,2010-11-18,92.138462
4283,21000179,1610612742.0,Caron Butler,103.4,2010-11-19,106.362500
4391,21000184,1610612742.0,Caron Butler,114.2,2010-11-20,107.233333
4554,21000190,1610612746.0,Rasual Butler,100.4,2010-11-20,92.728571
4842,21000202,1610612746.0,Rasual Butler,82.0,2010-11-22,92.013333
4954,21000207,1610612742.0,Caron Butler,109.1,2010-11-23,107.420000
5158,21000216,1610612742.0,Caron Butler,110.1,2010-11-24,107.663636
5300,21000221,1610612746.0,Rasual Butler,53.0,2010-11-25,89.575000
5446,21000228,1610612742.0,Caron Butler,98.4,2010-11-26,106.891667
5503,21000230,1610612746.0,Rasual Butler,112.6,2010-11-26,90.929412
5722,21000239,1610612742.0,Caron Butler,110.1,2010-11-27,107.138462
5872,21000245,1610612746.0,Rasual Butler,70.3,2010-11-28,89.783333
6033,21000252,1610612742.0,Caron Butler,120.4,2010-11-29,108.085714
6418,21000268,1610612742.0,Caron Butler,87.6,2010-12-01,106.720000
6522,21000272,1610612746.0,Rasual Butler,88.9,2010-12-01,89.736842
6798,21000284,1610612746.0,Rasual Butler,96.3,2010-12-03,90.065000
6838,21000286,1610612742.0,Caron Butler,101.9,2010-12-03,106.418750
7006,21000293,1610612742.0,Caron Butler,108.5,2010-12-04,106.541176
7206,21000301,1610612746.0,Rasual Butler,109.5,2010-12-05,90.990476
7387,21000308,1610612746.0,Rasual Butler,107.8,2010-12-06,91.754545
7474,21000312,1610612742.0,Caron Butler,105.0,2010-12-07,106.455556
7819,21000326,1610612746.0,Rasual Butler,69.8,2010-12-08,90.800000
7858,21000328,1610612742.0,Caron Butler,106.9,2010-12-09,106.478947
8178,21000341,1610612746.0,Rasual Butler,69.2,2010-12-11,89.900000
8290,21000346,1610612742.0,Caron Butler,126.0,2010-12-11,107.455000
8488,21000354,1610612746.0,Rasual Butler,98.9,2010-12-12,90.260000
8578,21000358,1610612742.0,Caron Butler,101.7,2010-12-13,107.180952
8837,21000369,1610612746.0,Rasual Butler,110.5,2010-12-15,91.038462
9034,21000377,1610612742.0,Caron Butler,115.6,2010-12-15,107.563636
9246,21000386,1610612746.0,Rasual Butler,87.5,2010-12-17,90.907407
9346,21000390,1610612742.0,Caron Butler,112.4,2010-12-17,107.773913
9461,21000395,1610612746.0,Rasual Butler,100.3,2010-12-18,91.242857
9813,21000410,1610612742.0,Caron Butler,96.2,2010-12-20,107.291667
9927,21000414,1610612746.0,Rasual Butler,105.0,2010-12-20,91.717241
9956,21000416,1610612742.0,Caron Butler,119.2,2010-12-21,107.768000
10285,21000429,1610612746.0,Rasual Butler,88.9,2010-12-22,91.623333
10506,21000438,1610612746.0,Rasual Butler,NaN,2010-12-26,91.623333
10772,21000450,1610612742.0,Caron Butler,105.8,2010-12-27,107.692308
10853,21000453,1610612746.0,Rasual Butler,133.3,2010-12-27,92.967742
11000,21000459,1610612742.0,Caron Butler,96.4,2010-12-28,107.274074
11321,21000472,1610612746.0,Rasual Butler,NaN,2010-12-29,92.967742
11360,21000474,1610612742.0,Caron Butler,101.1,2010-12-30,107.053571
11708,21000489,1610612742.0,Caron Butler,100.7,2011-01-01,106.834483
11825,21000493,1610612746.0,Rasual Butler,NaN,2011-01-02,92.967742
12520,21000522,1610612746.0,Rasual Butler,NaN,2011-01-05,92.967742
13065,21000545,1610612746.0,Rasual Butler,NaN,2011-01-09,92.967742
13708,21000572,1610612746.0,Rasual Butler,NaN,2011-01-12,92.967742
14006,21000585,1610612746.0,Rasual Butler,NaN,2011-01-14,92.967742
14281,21000596,1610612746.0,Rasual Butler,NaN,2011-01-16,92.967742
14496,21000605,1610612746.0,Rasual Butler,NaN,2011-01-17,92.967742
14978,21000625,1610612746.0,Rasual Butler,NaN,2011-01-19,92.967742
15036,21000628,1610612746.0,Rasual Butler,NaN,2011-01-20,92.967742
15600,21000651,1610612746.0,Rasual Butler,NaN,2011-01-22,92.967742
15922,21000665,1610612746.0,Rasual Butler,92.9,2011-01-25,92.965625
16138,21000674,1610612746.0,Rasual Butler,93.7,2011-01-26,92.987879
16776,21000700,1610612746.0,Rasual Butler,103.1,2011-01-29,93.285294
17111,21000714,1610612746.0,Rasual Butler,90.7,2011-01-31,93.211429
17473,21000729,1610612746.0,Rasual Butler,112.7,2011-02-02,93.752778
17678,21000738,1610612746.0,Rasual Butler,NaN,2011-02-04,93.752778
18061,21000754,1610612746.0,Rasual Butler,NaN,2011-02-06,93.752778
18371,21000767,1610612746.0,Rasual Butler,64.4,2011-02-08,92.959459
18657,21000779,1610612746.0,Rasual Butler,NaN,2011-02-09,92.959459
18944,21000791,1610612746.0,Rasual Butler,NaN,2011-02-11,92.959459
19352,21000808,1610612746.0,Rasual Butler,NaN,2011-02-13,92.959459
19519,21000815,1610612746.0,Rasual Butler,0.0,2011-02-14,90.513158
19879,21000830,1610612746.0,Rasual Butler,NaN,2011-02-16,90.513158
20191,21000843,1610612746.0,Rasual Butler,118.0,2011-02-22,91.217949
20452,21000854,1610612746.0,Rasual Butler,86.9,2011-02-23,91.110000
20857,21000871,1610612746.0,Rasual Butler,99.1,2011-02-25,91.304878
21037,21000878,1610612746.0,Rasual Butler,NaN,2011-02-26,91.304878
23265,21000971,1610612741.0,Rasual Butler,100.0,2011-03-11,91.511905
23455,21000979,1610612741.0,Rasual Butler,NaN,2011-03-12,91.511905
23982,21001001,1610612741.0,Rasual Butler,69.4,2011-03-15,90.997674
24282,21001014,1610612741.0,Rasual Butler,NaN,2011-03-17,90.997674
24354,21001017,1610612741.0,Rasual Butler,NaN,2011-03-18,90.997674
25086,21001047,1610612741.0,Rasual Butler,170.0,2011-03-21,92.793182
25171,21001051,1610612741.0,Rasual Butler,0.0,2011-03-22,90.731111
25734,21001074,1610612741.0,Rasual Butler,NaN,2011-03-25,90.731111
25961,21001084,1610612741.0,Rasual Butler,NaN,2011-03-26,90.731111
26307,21001098,1610612741.0,Rasual Butler,NaN,2011-03-28,90.731111
26655,21001113,1610612741.0,Rasual Butler,NaN,2011-03-30,90.731111
26919,21001124,1610612741.0,Rasual Butler,NaN,2011-04-01,90.731111
27147,21001133,1610612741.0,Rasual Butler,NaN,2011-04-02,90.731111
27699,21001156,1610612741.0,Rasual Butler,NaN,2011-04-05,90.731111
28131,21001174,1610612741.0,Rasual Butler,300.0,2011-04-07,95.280435
28263,21001180,1610612741.0,Rasual Butler,NaN,2011-04-08,95.280435
28573,21001193,1610612741.0,Rasual Butler,NaN,2011-04-10,95.280435
29053,21001213,1610612741.0,Rasual Butler,NaN,2011-04-12,95.280435
29281,21001222,1610612741.0,Rasual Butler,134.3,2011-04-13,96.110638
29498,41000101,1610612741.0,Rasual Butler,NaN,2011-04-16,96.110638
29522,41000102,1610612741.0,Rasual Butler,NaN,2011-04-18,96.110638
29534,41000103,1610612741.0,Rasual Butler,NaN,2011-04-21,96.110638
29558,41000104,1610612741.0,Rasual Butler,NaN,2011-04-23,96.110638
29593,41000105,1610612741.0,Rasual Butler,101.5,2011-04-26,96.222917
30530,41000201,1610612741.0,Rasual Butler,NaN,2011-05-02,96.222917
30554,41000202,1610612741.0,Rasual Butler,NaN,2011-05-04,96.222917
30565,41000203,1610612741.0,Rasual Butler,51.5,2011-05-06,95.310204
30589,41000204,1610612741.0,Rasual Butler,NaN,2011-05-08,95.310204
30625,41000205,1610612741.0,Rasual Butler,200.0,2011-05-10,97.404000
30637,41000206,1610612741.0,Rasual Butler,NaN,2011-05-12,97.404000
31057,41000301,1610612741.0,Rasual Butler,NaN,2011-05-15,97.404000
31081,41000302,1610612741.0,Rasual Butler,NaN,2011-05-18,97.404000
31093,41000303,1610612741.0,Rasual Butler,NaN,2011-05-22,97.404000
31117,41000304,1610612741.0,Rasual Butler,NaN,2011-05-24,97.404000
31153,41000305,1610612741.0,Rasual Butler,NaN,2011-05-26,97.404000

In [207]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Butler')][df_or1011a.TEAM_ID == '1610612759.0']

<ipython-input-207-bf24ea8394ed>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Butler')][df_or1011a.TEAM_ID == '1610612759.0']

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [208]:
df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Da')][df_or1011a.TEAM_ID == '1610612759.0']

<ipython-input-208-007e77e36a6f>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_or1011a[df_or1011a.PLAYER_NAME.str.contains('Da')][df_or1011a.TEAM_ID == '1610612759.0']

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
3980,21000166,1610612759.0,Danny Green,0.0,2010-11-17,0.000000
4256,21000178,1610612759.0,Danny Green,NaN,2010-11-19,0.000000
4484,21000187,1610612759.0,Danny Green,123.0,2010-11-20,61.500000
4772,21000199,1610612759.0,Danny Green,NaN,2010-11-22,61.500000
24751,21001033,1610612759.0,Danny Green,114.3,2011-03-19,79.100000
25134,21001049,1610612759.0,Danny Green,200.0,2011-03-21,109.325000
25481,21001064,1610612759.0,Danny Green,NaN,2011-03-23,109.325000
25818,21001078,1610612759.0,Danny Green,NaN,2011-03-25,109.325000
26105,21001090,1610612759.0,Danny Green,NaN,2011-03-27,109.325000
26328,21001099,1610612759.0,Danny Green,111.9,2011-03-28,109.840000
27517,21001149,1610612759.0,Danny Green,NaN,2011-04-05,109.840000
28056,21001171,1610612759.0,Danny Green,126.9,2011-04-06,112.683333
28538,21001191,1610612759.0,Danny Green,NaN,2011-04-09,112.683333
29098,21001215,1610612759.0,Danny Green,76.7,2011-04-12,107.542857
29436,21001229,1610612759.0,Danny Green,123.2,2011-04-13,109.500000
29975,41000141,1610612759.0,Danny Green,0.0,2011-04-17,97.333333
30000,41000142,1610612759.0,Danny Green,106.4,2011-04-20,98.240000
30012,41000143,1610612759.0,Danny Green,NaN,2011-04-23,98.240000
30036,41000144,1610612759.0,Danny Green,101.0,2011-04-25,98.490909
30073,41000145,1610612759.0,Danny Green,NaN,2011-04-27,98.490909
30084,41000146,1610612759.0,Danny Green,150.0,2011-04-29,102.783333

In [209]:
df_or1011a.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31419 entries, 0 to 31418
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   game_id       31419 non-null  int64
 1   TEAM_ID       31419 non-null  object
 2   PLAYER_NAME   31419 non-null  object
 3   E_OFF_RATING  26769 non-null  float64
 4   game_date     31419 non-null  datetime64[ns]
 5   cma2          31259 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 2.9+ MB

In [210]:
df_inj3[df_inj3.player.str.contains("Da'Sean Butler")]

      game_date   Team     team_id          player   game_id
1347 2011-03-25  Spurs  1610612759  Da'Sean Butler  21001078

In [211]:
def gi(name_):
    return df_inj3[df_inj3.player.str.contains(name_)]

In [212]:
def gi2(name_):
    return df_inj2[df_inj2.player.str.contains(name_)]

In [213]:
def go(name_):
    return df_or1011a[df_or1011a.PLAYER_NAME.str.contains(name_)]

In [214]:
df_or1018.PLAYER_NAME.fillna('', inplace=True)

In [215]:
def go2(name_):
    return df_or1018[df_or1018.PLAYER_NAME.str.contains(name_)]

In [216]:
# 'Daniel Orton'??? <------ out for the 2010-11 season. bball ref no record of 2009-10 season
gi('Daniel Orton')

      game_date   Team     team_id        player   game_id
75   2010-10-28  Magic  1610612753  Daniel Orton  21000017
525  2010-12-23  Magic  1610612753  Daniel Orton  21000430
1659 2011-04-16  Magic  1610612753  Daniel Orton  41000131

In [217]:
gi2('Daniel Orton')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
75,2010-10-28,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,21000017
525,2010-12-23,Magic,,Daniel Orton,arthroscopic surgery on left knee (out for season),1610612753,Daniel Orton,21000430
1659,2011-04-16,Magic,,Daniel Orton,placed on IL with surgery on left knee (out for season),1610612753,Daniel Orton,41000131

In [218]:
df_inj2[df_inj2.player.str.contains('Daniel Orton')]

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
75,2010-10-28,Magic,,Daniel Orton,placed on IL,1610612753,Daniel Orton,21000017
525,2010-12-23,Magic,,Daniel Orton,arthroscopic surgery on left knee (out for season),1610612753,Daniel Orton,21000430
1659,2011-04-16,Magic,,Daniel Orton,placed on IL with surgery on left knee (out for season),1610612753,Daniel Orton,41000131

In [219]:
# 'Didier Mbenga'??? <-----

In [220]:
gi('Didier Mbenga')

      game_date     Team     team_id         player   game_id
353  2010-12-05  Hornets  1610612740  Didier Mbenga  21000298
412  2010-12-13  Hornets  1610612740  Didier Mbenga  21000355
607  2011-01-01  Hornets  1610612740  Didier Mbenga  21000484
751  2011-01-17  Hornets  1610612740  Didier Mbenga  21000603
1102 2011-02-27  Hornets  1610612740  Didier Mbenga  21000885
1390 2011-03-30  Hornets  1610612740  Didier Mbenga  21001114

In [221]:
gi2('Didier Mbenga')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
353,2010-12-05,Hornets,,Didier Mbenga,placed on IL with illness,1610612740,Didier Mbenga,21000298
412,2010-12-13,Hornets,,Didier Mbenga,placed on IL,1610612740,Didier Mbenga,21000355
607,2011-01-01,Hornets,,Didier Mbenga,placed on IL,1610612740,Didier Mbenga,21000484
751,2011-01-17,Hornets,,Didier Mbenga,placed on IL,1610612740,Didier Mbenga,21000603
1102,2011-02-27,Hornets,,Didier Mbenga,placed on IL,1610612740,Didier Mbenga,21000885
1390,2011-03-30,Hornets,,Didier Mbenga,placed on IL,1610612740,Didier Mbenga,21001114

In [222]:
go('Mbenga')

        game_id       TEAM_ID PLAYER_NAME  E_OFF_RATING  game_date        cma2
233    21000010  1610612740.0   DJ Mbenga          95.6 2010-10-27   95.600000
647    21000027  1610612740.0   DJ Mbenga         167.3 2010-10-29  131.450000
917    21000039  1610612740.0   DJ Mbenga          71.3 2010-10-30  111.400000
1399   21000059  1610612740.0   DJ Mbenga          91.1 2010-11-03  106.325000
1796   21000075  1610612740.0   DJ Mbenga          58.7 2010-11-05   96.800000
1979   21000083  1610612740.0   DJ Mbenga           NaN 2010-11-06   96.800000
2517   21000105  1610612740.0   DJ Mbenga          66.7 2010-11-09   91.783333
3261   21000136  1610612740.0   DJ Mbenga           NaN 2010-11-13   91.783333
3488   21000146  1610612740.0   DJ Mbenga         138.5 2010-11-15   98.457143
3910   21000163  1610612740.0   DJ Mbenga           NaN 2010-11-17   98.457143
4245   21000177  1610612740.0   DJ Mbenga         185.2 2010-11-19  109.300000
4615   21000193  1610612740.0   DJ Mbenga          48.8 2010-11-21  102.577778
4832   21000202  1610612740.0   DJ Mbenga         147.8 2010-11-22  107.100000
5235   21000219  1610612740.0   DJ Mbenga         103.2 2010-11-24  106.745455
5574   21000233  1610612740.0   DJ Mbenga          76.7 2010-11-26  104.241667
5849   21000244  1610612740.0   DJ Mbenga         123.9 2010-11-28  105.753846
6002   21000251  1610612740.0   DJ Mbenga          58.0 2010-11-29  102.342857
6401   21000267  1610612740.0   DJ Mbenga          60.7 2010-12-01   99.566667
6762   21000282  1610612740.0   DJ Mbenga         113.4 2010-12-03  100.431250
7700   21000321  1610612740.0   DJ Mbenga           NaN 2010-12-08  100.431250
8031   21000335  1610612740.0   DJ Mbenga          97.6 2010-12-10  100.264706
8384   21000350  1610612740.0   DJ Mbenga         100.4 2010-12-12  100.272222
8949   21000373  1610612740.0   DJ Mbenga           NaN 2010-12-15  100.272222
9283   21000387  1610612740.0   DJ Mbenga         150.0 2010-12-17  102.889474
9655   21000403  1610612740.0   DJ Mbenga         133.1 2010-12-19  104.400000
9775   21000408  1610612740.0   DJ Mbenga           NaN 2010-12-20  104.400000
10241  21000427  1610612740.0   DJ Mbenga         127.6 2010-12-22  105.504762
10599  21000442  1610612740.0   DJ Mbenga         126.5 2010-12-26  106.459091
10757  21000449  1610612740.0   DJ Mbenga         102.5 2010-12-27  106.286957
11200  21000467  1610612740.0   DJ Mbenga         104.3 2010-12-29  106.204167
11406  21000476  1610612740.0   DJ Mbenga          41.0 2010-12-31  103.596000
13589  21000567  1610612740.0   DJ Mbenga           NaN 2011-01-12  103.596000
13935  21000582  1610612740.0   DJ Mbenga           NaN 2011-01-14  103.596000
14079  21000588  1610612740.0   DJ Mbenga           NaN 2011-01-15  103.596000
15106  21000631  1610612740.0   DJ Mbenga          98.5 2011-01-21  103.400000
15478  21000646  1610612740.0   DJ Mbenga          81.0 2011-01-22  102.570370
15816  21000660  1610612740.0   DJ Mbenga         111.2 2011-01-24  102.878571
16211  21000677  1610612740.0   DJ Mbenga          48.7 2011-01-26  101.010345
16740  21000699  1610612740.0   DJ Mbenga          28.6 2011-01-29   98.596667
16910  21000706  1610612740.0   DJ Mbenga         100.0 2011-01-30   98.641935
17137  21000715  1610612740.0   DJ Mbenga          87.2 2011-02-01   98.284375
17362  21000725  1610612740.0   DJ Mbenga          78.7 2011-02-02   97.690909
17926  21000748  1610612740.0   DJ Mbenga         103.8 2011-02-05   97.870588
18216  21000760  1610612740.0   DJ Mbenga         104.2 2011-02-07   98.051429
18561  21000775  1610612740.0   DJ Mbenga           0.0 2011-02-09   95.327778
18869  21000788  1610612740.0   DJ Mbenga         113.6 2011-02-11   95.821622
19173  21000800  1610612740.0   DJ Mbenga          66.7 2011-02-12   95.055263
19711  21000823  1610612740.0   DJ Mbenga          60.1 2011-02-15   94.158974
19999  21000835  1610612740.0   DJ Mbenga           NaN 2011-02-16   94.158974
20467  21000854  1610612740.0   DJ Mbenga           NaN 2011-02-23   94.158974
20789  21000868  1610612740.0   DJ Mbenga           NaN 2011-02-25   94.158974
25794  21001077  1610612740.0   DJ Mbenga           NaN 2011-03-25   94.158974
26200  21001094  1610612740.0   DJ Mbenga           NaN 2011-03-27   94.158974
27483  21001147  1610612740.0   DJ Mbenga           NaN 2011-04-03   94.158974
28010  21001169  1610612740.0   DJ Mbenga           NaN 2011-04-06   94.158974
28371  21001184  1610612740.0   DJ Mbenga           NaN 2011-04-08   94.158974
28669  21001197  1610612740.0   DJ Mbenga          96.6 2011-04-10   94.220000
28946  21001208  1610612740.0   DJ Mbenga           NaN 2011-04-11   94.220000
29293  21001223  1610612740.0   DJ Mbenga          80.6 2011-04-13   93.887805
30107  41000151  1610612740.0   DJ Mbenga         106.0 2011-04-17   94.176190
30132  41000152  1610612740.0   DJ Mbenga          83.3 2011-04-20   93.923256
30169  41000153  1610612740.0   DJ Mbenga          90.4 2011-04-22   93.843182
30192  41000154  1610612740.0   DJ Mbenga         138.9 2011-04-24   94.844444
30206  41000155  1610612740.0   DJ Mbenga           NaN 2011-04-26   94.844444
30240  41000156  1610612740.0   DJ Mbenga         133.2 2011-04-28   95.678261

In [223]:
df_inj3.player.replace({'Didier Mbenga':'DJ Mbenga'}, inplace=True)

In [224]:
df_inj3[df_inj3.player.str.contains('Mbenga')]

      game_date     Team     team_id     player   game_id
353  2010-12-05  Hornets  1610612740  DJ Mbenga  21000298
412  2010-12-13  Hornets  1610612740  DJ Mbenga  21000355
607  2011-01-01  Hornets  1610612740  DJ Mbenga  21000484
751  2011-01-17  Hornets  1610612740  DJ Mbenga  21000603
1102 2011-02-27  Hornets  1610612740  DJ Mbenga  21000885
1390 2011-03-30  Hornets  1610612740  DJ Mbenga  21001114

In [225]:
#'Eddy Curry' <---- does not play this 2010-11 seaon and gets traded from the nyn to the min
gi('Eddy Curry')

      game_date          Team     team_id      player   game_id
44   2010-10-27        Knicks  1610612752  Eddy Curry  21000007
1056 2011-02-23  Timberwolves  1610612750  Eddy Curry  21000853

In [226]:
gi2('Eddy Curry')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
44,2010-10-27,Knicks,,Eddy Curry,placed on IL with strained right hamstring,1610612752,Eddy Curry,21000007
1056,2011-02-23,Timberwolves,,Eddy Curry,placed on IL,1610612750,Eddy Curry,21000853

In [227]:
go('Eddy Curry')

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [228]:
go2('Eddy Curry')

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
3790,20900159,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,NaN,11:44,123.0,111.1,78.9,77.8,44.0,33.3,0.0,0.0,0.0,0.333,0.091,0.200,27.3,0.750,0.665,0.367,0.401,104.32,110.45,92.05,27.0,0.016
4363,20900183,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,NaN,12:29,64.6,66.7,105.3,103.8,-40.7,-37.2,0.0,0.0,0.0,0.000,0.167,0.067,37.5,0.200,0.276,0.250,0.251,102.90,101.90,84.91,27.0,-0.102
4614,20900193,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,NaN,15:50,93.5,90.9,94.7,93.9,-1.2,-3.0,0.0,0.0,0.0,0.053,0.158,0.105,20.0,0.333,0.387,0.270,0.277,98.22,100.04,83.37,33.0,0.014
4938,20900207,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,NaN,5:54,76.9,71.4,92.3,92.3,-15.4,-20.9,0.0,0.0,0.0,0.000,0.000,0.000,50.0,0.333,0.333,0.429,0.462,105.76,109.83,91.53,14.0,-0.270
7107,20900297,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
7811,20900327,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,NaN,6:34,111.6,100.0,124.2,123.1,-12.6,-23.1,0.0,0.0,0.0,0.000,0.143,0.083,50.0,1.000,1.000,0.133,0.149,96.19,102.34,85.28,15.0,0.000
8386,20900351,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,NaN,5:58,57.5,56.3,102.5,100.0,-44.9,-43.8,0.0,0.0,0.0,0.000,0.167,0.100,0.0,0.000,1.136,0.063,0.064,121.80,124.69,103.91,16.0,0.147
8841,20900370,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,NaN,3:32,13.7,14.3,121.5,171.4,-107.8,-157.1,0.0,0.0,0.0,0.000,0.333,0.100,25.0,0.000,0.174,0.500,0.481,116.83,95.09,79.25,7.0,-0.667
9095,20900380,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
9551,20900399,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
9767,20900408,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
10149,20900424,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
10583,20900442,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
10862,20900454,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
11078,20900463,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
11343,20900474,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
12388,20900517,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
12832,20900536,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
13121,20900548,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
23016,20900960,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
23232,20900969,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DND - Sore Right Calf,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
23472,20900979,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DND - Sore Right Calf,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
23761,20900991,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DND - Sore Right Calf,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
26811,20901118,1.610613e+09,NYK,New York,2201.0,Eddy Curry,NaN,DND - torn myofascial band in right calf,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
64461,21100213,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,6:06,117.8,116.7,170.1,166.7,-52.2,-50.0,0.0,0.0,0.0,0.286,0.333,0.300,20.0,0.667,0.773,0.333,0.336,93.01,94.43,78.69,12.0,0.119
64876,21100229,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
65152,21100240,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,5:45,80.0,80.0,50.6,50.0,29.4,30.0,0.0,0.0,0.0,0.000,0.143,0.077,100.0,0.000,0.000,0.083,0.083,82.98,83.48,69.57,10.0,-0.444
65518,21100254,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
65657,21100260,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,8:45,107.9,106.3,125.0,133.3,-17.1,-27.1,0.0,0.0,0.0,0.000,0.000,0.000,33.3,0.000,0.000,0.176,0.179,87.11,85.03,70.86,16.0,-0.109
66085,21100276,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
66471,21100291,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,2:03,82.0,80.0,143.4,175.0,-61.5,-95.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,114.26,105.37,87.80,5.0,-0.250
66732,21100301,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,4:00,50.0,50.0,145.3,187.5,-95.3,-137.5,0.0,0.0,0.0,0.250,0.000,0.125,25.0,0.667,0.667,0.444,0.444,109.92,96.00,80.00,8.0,-0.033
67181,21100319,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
67543,21100333,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
68147,21100356,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
68479,21100369,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
68648,21100376,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
69009,21100390,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
69550,21100411,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,2:49,120.0,100.0,166.7,166.7,-46.7,-66.7,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.167,0.200,93.73,102.25,85.21,6.0,-0.051
69678,21100416,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,4:16,56.3,62.5,84.7,88.9,-28.4,-26.4,1.0,1.0,50.0,0.000,0.125,0.071,50.0,0.000,0.000,0.100,0.101,103.05,95.63,79.69,8.0,-0.125
69808,21100421,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,3:27,68.0,57.1,167.4,214.3,-99.4,-157.1,0.0,0.0,0.0,0.000,0.000,0.000,100.0,0.000,0.000,0.125,0.145,103.23,97.39,81.16,7.0,-0.667
70527,21100449,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,2:49,208.3,180.0,50.0,50.0,158.3,130.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,70.89,76.69,63.91,5.0,0.000
70845,21100461,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
71410,21100483,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
71817,21100499,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
72525,21100527,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
72754,21100536,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
73041,21100547,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
73545,21100566,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,5:56,75.0,75.0,128.7,127.3,-53.7,-52.3,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.500,0.500,0.143,0.154,92.55,93.03,77.53,12.0,0.043
73724,21100573,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
74291,21100595,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
74872,21100618,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
75156,21100629,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
75512,21100643,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NWT - Personal Reasons,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
76109,21100666,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
76413,21100678,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,4:42,90.0,90.0,171.2,166.7,-81.2,-76.7,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.500,0.500,0.167,0.182,95.80,97.02,80.85,10.0,0.020
77066,21100704,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
77577,21100724,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
77731,21100730,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
78358,21100754,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
78420,21100757,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
79383,21100794,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
81572,21100879,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,4:20,66.7,75.0,126.9,125.0,-60.2,-50.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.300,0.300,93.49,88.62,73.85,8.0,-0.080
82254,21100906,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
82709,21100923,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,NaN,3:30,75.0,85.7,51.0,37.5,24.0,48.2,0.0,0.0,0.0,0.000,0.333,0.222,0.0,0.667,0.667,0.375,0.375,95.18,102.86,85.71,7.0,0.714
82993,21100934,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
83280,21100945,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
83512,21100954,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
83834,21100967,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
84188,21100981,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,C,NaN,24:08,69.3,68.0,110.3,110.2,-41.0,-42.2,0.0,0.0,0.0,0.043,0.136,0.089,28.6,0.429,0.519,0.264,0.269,97.46,98.45,82.04,50.0,0.030
84500,21200003,1.610613e+09,DAL,Dallas,2201.0,Eddy Curry,NaN,NaN,16:44,117.0,121.2,106.1,103.0,10.8,18.2,0.0,0.0,0.0,0.143,0.095,0.114,11.1,0.429,0.444,0.243,0.242,95.01,94.66,78.88,33.0,0.000
84655,21200009,1.610613e+09,DAL,Dallas,2201.0,Eddy Curry,NaN,NaN,8:01,69.7,70.0,75.6,70.0,-5.9,0.0,0.0,0.0,0.0,0.000,0.000,0.000,50.0,1.000,0.532,0.200,0.199,115.56,119.75,99.79,20.0,-0.250
277734,41100206,1.610613e+09,MIA,Miami,2201.0,Eddy Curry,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [229]:
go(' Curry')

,game_id,TEAM_ID,PLAYER_NAME,E_OFF_RATING,game_date,cma2
352,21000015,1610612744.0,Stephen Curry,131.8,2010-10-27,131.800000
688,21000029,1610612744.0,Stephen Curry,120.0,2010-10-29,125.900000
1864,21000078,1610612744.0,Stephen Curry,92.7,2010-11-05,114.833333
2164,21000091,1610612744.0,Stephen Curry,99.7,2010-11-07,111.050000
2308,21000097,1610612744.0,Stephen Curry,121.2,2010-11-08,113.080000
2691,21000113,1610612744.0,Stephen Curry,114.8,2010-11-10,113.366667
2835,21000119,1610612744.0,Stephen Curry,94.2,2010-11-11,110.628571
3267,21000137,1610612744.0,Stephen Curry,71.0,2010-11-13,105.675000
3567,21000149,1610612744.0,Stephen Curry,109.8,2010-11-15,106.133333
4335,21000181,1610612744.0,Stephen Curry,122.1,2010-11-19,107.730000
4634,21000194,1610612744.0,Stephen Curry,87.0,2010-11-21,105.845455
4814,21000201,1610612744.0,Stephen Curry,93.4,2010-11-22,104.808333
5186,21000217,1610612744.0,Stephen Curry,97.2,2010-11-24,104.223077
5546,21000232,1610612744.0,Stephen Curry,128.2,2010-11-26,105.935714
5690,21000238,1610612744.0,Stephen Curry,137.8,2010-11-27,108.060000
6230,21000260,1610612744.0,Stephen Curry,98.0,2010-11-30,107.431250
6566,21000274,1610612744.0,Stephen Curry,106.5,2010-12-02,107.376471
7106,21000297,1610612744.0,Stephen Curry,105.7,2010-12-05,107.283333
7466,21000312,1610612744.0,Stephen Curry,101.3,2010-12-07,106.968421
7706,21000322,1610612744.0,Stephen Curry,61.2,2010-12-08,104.680000
10476,21000437,1610612744.0,Stephen Curry,111.4,2010-12-25,105.000000
10884,21000454,1610612744.0,Stephen Curry,132.2,2010-12-27,106.236364
11064,21000462,1610612744.0,Stephen Curry,108.2,2010-12-29,106.321739
11424,21000477,1610612744.0,Stephen Curry,115.5,2010-12-31,106.704167
11640,21000486,1610612744.0,Stephen Curry,103.5,2011-01-01,106.576000
11976,21000500,1610612744.0,Stephen Curry,85.4,2011-01-03,105.761538
12407,21000518,1610612744.0,Stephen Curry,122.4,2011-01-05,106.377778
12798,21000534,1610612744.0,Stephen Curry,121.5,2011-01-07,106.917857
13047,21000545,1610612744.0,Stephen Curry,77.8,2011-01-09,105.913793
13678,21000571,1610612744.0,Stephen Curry,118.1,2011-01-12,106.320000
14012,21000585,1610612744.0,Stephen Curry,121.5,2011-01-14,106.809677
14539,21000607,1610612744.0,Stephen Curry,124.2,2011-01-17,107.353125
14947,21000624,1610612744.0,Stephen Curry,125.2,2011-01-19,107.893939
15283,21000638,1610612744.0,Stephen Curry,105.4,2011-01-21,107.820588
15583,21000651,1610612744.0,Stephen Curry,122.1,2011-01-22,108.228571
15859,21000662,1610612744.0,Stephen Curry,113.4,2011-01-24,108.372222
16219,21000677,1610612744.0,Stephen Curry,108.5,2011-01-26,108.375676
16555,21000691,1610612744.0,Stephen Curry,114.1,2011-01-28,108.526316
16939,21000707,1610612744.0,Stephen Curry,111.6,2011-01-30,108.605128
17517,21000731,1610612744.0,Stephen Curry,107.8,2011-02-03,108.585000
18044,21000753,1610612744.0,Stephen Curry,107.6,2011-02-05,108.560976
18330,21000765,1610612744.0,Stephen Curry,97.1,2011-02-07,108.288095
18736,21000782,1610612744.0,Stephen Curry,113.4,2011-02-09,108.406977
18772,21000784,1610612744.0,Stephen Curry,77.1,2011-02-10,107.695455
19430,21000811,1610612744.0,Stephen Curry,119.5,2011-02-13,107.957778
19717,21000823,1610612744.0,Stephen Curry,118.6,2011-02-15,108.189130
19969,21000834,1610612744.0,Stephen Curry,108.8,2011-02-16,108.202128
20245,21000845,1610612744.0,Stephen Curry,90.7,2011-02-22,107.837500
20842,21000870,1610612744.0,Stephen Curry,70.4,2011-02-25,107.073469
21116,21000882,1610612744.0,Stephen Curry,124.3,2011-02-27,107.418000
21403,21000894,1610612744.0,Stephen Curry,94.7,2011-03-01,107.168627
21643,21000904,1610612744.0,Stephen Curry,100.6,2011-03-02,107.042308
21979,21000918,1610612744.0,Stephen Curry,98.7,2011-03-04,106.884906
22386,21000935,1610612744.0,Stephen Curry,106.5,2011-03-06,106.877778
22697,21000948,1610612744.0,Stephen Curry,108.9,2011-03-08,106.914545
22840,21000954,1610612744.0,Stephen Curry,85.1,2011-03-09,106.525000
23354,21000975,1610612744.0,Stephen Curry,117.3,2011-03-11,106.714035
23712,21000990,1610612744.0,Stephen Curry,101.7,2011-03-13,106.627586
23892,21000998,1610612744.0,Stephen Curry,106.6,2011-03-14,106.627119
24240,21001012,1610612744.0,Stephen Curry,101.1,2011-03-16,106.535000
24564,21001026,1610612744.0,Stephen Curry,91.2,2011-03-18,106.283607
24948,21001042,1610612744.0,Stephen Curry,85.6,2011-03-20,105.950000
25116,21001049,1610612744.0,Stephen Curry,83.0,2011-03-21,105.585714
25427,21001062,1610612744.0,Stephen Curry,111.6,2011-03-23,105.679688
25846,21001079,1610612744.0,Stephen Curry,150.6,2011-03-25,106.370769
26181,21001093,1610612744.0,Stephen Curry,109.4,2011-03-27,106.416667
26408,21001103,1610612744.0,Stephen Curry,95.5,2011-03-29,106.253731
26625,21001112,1610612744.0,Stephen Curry,87.4,2011-03-30,105.976471
27213,21001136,1610612744.0,Stephen Curry,112.3,2011-04-02,106.068116
27776,21001160,1610612744.0,Stephen Curry,119.1,2011-04-05,106.254286
28100,21001173,1610612744.0,Stephen Curry,102.0,2011-04-06,106.194366
28747,21001200,1610612744.0,Stephen Curry,95.1,2011-04-10,106.040278
28975,21001210,1610612744.0,Stephen Curry,116.0,2011-04-11,106.176712
29395,21001227,1610612744.0,Stephen Curry,134.5,2011-04-13,106.559459

In [230]:
# 'Jannero Pargo' <---out of the season due to knee surgery recovery
#https://www.basketball-reference.com/players/p/pargoja01.html
gi('Jannero Pargo')

      game_date   Team     team_id         player   game_id
1304 2011-03-21  Bulls  1610612741  Jannero Pargo  21001047
1656 2011-04-16  Bulls  1610612741  Jannero Pargo  41000101

In [231]:
gi2('Jannero Pargo')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
1304,2011-03-21,Bulls,,Jannero Pargo,placed on IL,1610612741,Jannero Pargo,21001047
1656,2011-04-16,Bulls,,Jannero Pargo,placed on IL,1610612741,Jannero Pargo,41000101

In [232]:
go('Jannero Pargo')

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [233]:
go2('Jannero Pargo')

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
404,20900017,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,7:23,110.0,107.1,106.5,100.0,3.4,7.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.176,0.180,90.06,94.22,78.52,14.0,-0.212
511,20900022,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,21:30,118.9,117.5,131.6,129.3,-12.7,-11.8,0.000,0.00,0.0,0.000,0.071,0.030,14.3,0.542,0.542,0.298,0.308,89.08,90.42,75.35,40.0,0.068
966,20900041,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,5:43,50.0,60.0,85.9,90.9,-35.9,-30.9,0.333,0.00,33.3,0.000,0.000,0.000,0.0,0.000,0.000,0.143,0.143,99.25,88.16,73.47,10.0,-0.200
1336,20900056,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,14:22,137.9,142.3,71.0,65.5,66.9,76.8,0.111,0.00,16.7,0.000,0.067,0.034,0.0,1.000,1.000,0.156,0.157,89.54,91.88,76.57,26.0,0.259
1660,20900070,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,11:02,116.7,110.5,96.6,90.0,20.1,20.5,0.100,0.00,20.0,0.000,0.063,0.043,0.0,0.000,0.000,0.182,0.200,79.70,84.83,70.69,19.0,-0.090
2078,20900087,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,4:01,71.4,71.4,140.0,140.0,-68.6,-68.6,0.000,0.00,0.0,0.000,0.000,0.000,50.0,0.000,0.000,0.200,0.200,71.73,71.73,59.78,7.0,-0.500
2508,20900105,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,9:29,73.4,75.0,125.4,127.3,-52.1,-52.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.167,0.233,0.250,0.245,108.14,106.22,88.51,20.0,-0.109
2614,20900110,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,11:05,124.1,117.4,76.1,78.3,47.9,39.1,0.111,1.00,16.7,0.000,0.231,0.130,16.7,0.500,0.500,0.192,0.202,98.31,99.61,83.01,23.0,0.118
3324,20900139,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
3716,20900156,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,14:35,118.4,117.1,94.2,97.0,24.1,20.2,0.182,1.00,16.7,0.000,0.000,0.000,16.7,0.750,0.750,0.278,0.281,112.90,111.91,93.26,35.0,0.103
4099,20900172,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,7:15,95.2,93.8,85.5,76.5,9.7,17.3,0.250,0.50,14.3,0.000,0.200,0.125,28.6,0.250,0.250,0.375,0.381,102.56,109.32,91.10,16.0,-0.044
4506,20900189,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,8:56,115.4,110.5,130.6,131.3,-15.2,-20.7,0.143,0.00,25.0,0.000,0.125,0.059,0.0,0.667,0.667,0.136,0.142,92.15,94.08,78.40,19.0,0.119
4770,20900200,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,13:43,88.7,92.6,123.5,113.8,-34.9,-21.2,0.400,0.00,15.4,0.056,0.167,0.083,0.0,0.556,0.670,0.367,0.364,96.09,97.98,81.65,27.0,0.243
5271,20900221,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,22:48,90.6,88.6,119.7,115.9,-29.1,-27.3,0.100,1.00,9.1,0.000,0.045,0.020,9.1,0.389,0.389,0.185,0.200,90.15,92.63,77.19,44.0,0.029
5944,20900249,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,10:50,94.7,85.7,103.8,104.8,-9.0,-19.0,0.111,1.00,20.0,0.000,0.111,0.059,20.0,0.000,0.000,0.182,0.200,89.06,93.05,77.54,21.0,-0.082
6317,20900264,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,10:55,111.8,105.6,114.9,111.1,-3.2,-5.6,0.143,0.00,14.3,0.100,0.091,0.095,0.0,0.417,0.417,0.273,0.286,75.63,79.15,65.95,18.0,0.019
6544,20900274,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,12:00,137.1,136.8,135.9,125.0,1.3,11.8,0.400,1.00,25.0,0.000,0.231,0.136,25.0,1.000,1.014,0.273,0.273,74.72,78.00,65.00,19.0,0.209
6773,20900283,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,21:22,84.4,88.1,116.0,114.6,-31.6,-26.5,0.222,1.00,10.0,0.000,0.000,0.000,10.0,0.367,0.398,0.391,0.393,94.73,93.21,77.67,42.0,0.026
7249,20900303,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,15:28,65.5,65.6,107.0,103.1,-41.5,-37.5,0.000,0.00,0.0,0.000,0.000,0.000,10.0,0.125,0.225,0.270,0.270,97.60,99.28,82.73,32.0,-0.128
7358,20900308,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,12:00,111.7,113.0,131.8,134.8,-20.1,-21.7,0.000,0.00,0.0,0.000,0.111,0.048,20.0,0.000,0.000,0.185,0.190,93.60,92.00,76.67,23.0,-0.115
7754,20900324,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
7969,20900333,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,8:50,83.9,93.8,106.1,112.5,-22.2,-18.8,0.000,0.00,0.0,0.000,0.222,0.077,0.0,0.563,0.619,0.346,0.362,94.66,86.94,72.45,16.0,0.326
8469,20900354,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,7:14,107.1,100.0,158.5,157.1,-51.4,-57.1,0.286,0.00,33.3,0.100,0.250,0.143,0.0,0.000,0.000,0.200,0.211,92.51,96.22,80.18,15.0,-0.036
8857,20900370,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
9265,20900387,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
9622,20900402,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,0:06,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,261.82,523.64,436.37,1.0,0.000
9755,20900408,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,6:33,81.8,84.6,108.7,107.7,-26.9,-23.1,0.200,1.00,33.3,0.000,0.000,0.000,33.3,0.000,0.000,0.143,0.139,96.44,95.27,79.39,13.0,-0.100
10342,20900432,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,1:55,66.7,50.0,100.0,100.0,-33.3,-50.0,0.000,0.00,0.0,0.000,0.500,0.333,0.0,0.500,0.500,0.500,0.667,87.65,100.17,83.48,4.0,0.333
10900,20900455,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
11224,20900469,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
11550,20900482,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
11862,20900495,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
11923,20900498,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
12547,20900524,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
12773,20900533,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,3:02,62.5,71.4,153.1,150.0,-90.6,-78.6,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.125,0.125,109.82,102.86,85.71,7.0,-0.083
13108,20900547,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,18:15,89.0,86.8,99.6,97.4,-10.6,-10.6,0.300,0.75,16.7,0.000,0.000,0.000,22.2,0.350,0.414,0.333,0.340,98.95,101.26,84.38,38.0,0.019
13623,20900569,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,1:51,75.0,75.0,125.0,100.0,-50.0,-25.0,1.000,1.00,33.3,0.000,0.000,0.000,33.3,0.000,0.000,0.286,0.286,103.78,116.76,97.30,4.0,-0.167
13755,20900574,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,5:09,123.0,115.4,136.4,136.4,-13.4,-21.0,0.000,0.00,0.0,0.000,0.250,0.143,0.0,0.000,0.532,0.143,0.152,108.12,111.84,93.20,13.0,0.071
14416,20900602,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,15:56,104.2,100.0,87.3,83.8,16.9,16.2,0.400,0.00,22.2,0.043,0.000,0.022,0.0,0.346,0.419,0.326,0.337,107.05,111.51,92.93,37.0,0.143
14847,20900620,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,16:25,93.7,91.2,117.4,108.8,-23.7,-17.6,0.091,0.00,25.0,0.000,0.067,0.031,0.0,0.333,0.436,0.077,0.083,94.41,99.38,82.82,34.0,-0.017
15210,20900635,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
15351,20900641,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,0:01,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,1309.09,1309.11,1090.93,0.0,0.000
15667,20900654,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
16027,20900669,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
16363,20900683,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
17142,20900715,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,2:29,138.9,160.0,0.0,0.0,138.9,160.0,0.000,0.00,0.0,0.000,0.250,0.125,0.0,0.750,0.750,0.286,0.296,94.32,96.64,80.54,5.0,0.462
17228,20900719,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
17611,20900735,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
17861,20900745,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,0:31,227.3,200.0,0.0,0.0,227.3,200.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,40.36,91.72,76.43,1.0,0.000
18213,20900760,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
18536,20900773,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,21:11,78.7,77.6,66.5,64.6,12.2,13.0,0.500,0.00,29.4,0.000,0.214,0.100,0.0,0.318,0.379,0.226,0.234,107.52,109.88,91.57,49.0,0.226
18798,20900784,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,18:13,115.4,110.8,75.4,71.4,40.0,39.4,0.273,0.00,20.0,0.000,0.080,0.049,0.0,0.500,0.500,0.300,0.320,90.51,94.88,79.07,37.0,0.171
19078,20900796,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,16:08,98.6,102.9,80.1,82.9,18.5,20.0,0.231,0.00,30.0,0.000,0.095,0.053,0.0,0.357,0.357,0.175,0.173,108.19,104.14,86.79,35.0,0.136
19391,20900809,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,9:32,133.7,135.3,144.3,138.9,-10.6,-3.6,0.125,0.00,25.0,0.125,0.400,0.231,0.0,0.333,0.436,0.143,0.142,86.90,88.11,73.43,17.0,0.124
19618,20900818,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,9:29,121.2,116.7,86.6,83.3,34.6,33.3,0.125,1.00,14.3,0.000,0.200,0.105,14.3,0.300,0.300,0.300,0.328,87.67,91.11,75.92,18.0,0.062
19942,20900832,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,5:19,123.9,122.2,90.1,80.0,33.8,42.2,0.000,0.00,0.0,0.000,0.000,0.000,20.0,0.625,0.625,0.500,0.506,80.17,85.77,71.47,9.0,0.174
20339,20900848,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,13:25,89.8,89.7,115.2,117.2,-25.4,-27.6,0.143,1.00,14.3,0.000,0.000,0.000,14.3,0.400,0.400,0.200,0.200,104.61,103.75,86.46,29.0,0.021
20675,20900862,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,3:26,126.9,125.0,50.8,40.0,76.1,85.0,0.333,0.33,20.0,0.000,0.250,0.250,60.0,1.000,1.000,0.500,0.508,110.17,125.83,104.85,8.0,0.125
20926,20900873,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,29:26,91.4,91.4,101.1,103.4,-9.8,-12.1,0.100,0.50,5.0,0.000,0.111,0.054,10.0,0.344,0.404,0.275,0.288,95.66,94.59,78.82,58.0,0.046
21321,20900889,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,18:14,103.7,105.6,135.8,125.6,-32.1,-20.1,0.231,0.00,33.3,0.000,0.150,0.086,0.0,0.500,0.500,0.154,0.155,95.72,98.72,82.27,36.0,0.082
21849,20900911,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,6:09,119.0,116.7,139.4,115.4,-20.4,1.3,0.250,0.00,20.0,0.000,0.000,0.000,0.0,0.250,0.250,0.308,0.313,87.91,97.59,81.32,12.0,0.000
22259,20900928,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,14:12,136.3,140.7,118.7,121.4,17.6,19.3,0.083,0.00,9.1,0.000,0.091,0.048,0.0,0.550,0.550,0.345,0.335,95.53,92.96,77.46,27.0,0.103
22762,20900949,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,9:30,92.4,95.2,120.4,104.8,-27.9,-9.5,0.333,2.00,22.2,0.000,0.000,0.000,11.1,0.300,0.425,0.318,0.309,100.85,106.11,88.42,21.0,0.067
23061,20900962,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,23:34,71.2,75.6,111.8,113.3,-40.6,-37.8,0.143,0.50,6.7,0.000,0.118,0.049,13.3,0.458,0.442,0.280,0.282,95.05,91.67,76.39,45.0,0.103
23178,20900967,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,G,NaN,37:17,107.5,107.0,112.3,111.1,-4.8,-4.1,0.174,1.33,16.0,0.000,0.088,0.045,12.0,0.529,0.559,0.266,0.270,91.40,92.07,76.72,71.0,0.112
23995,20901001,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,G,NaN,36:10,91.1,92.0,103.4,104.1,-12.3,-12.1,0.364,1.60,27.6,0.000,0.029,0.015,17.2,0.267,0.349,0.263,0.260,99.65,98.88,82.40,75.0,0.018
24235,20901011,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,G,NaN,17:14,92.2,91.9,128.8,127.0,-36.6,-35.1,0.364,2.00,25.0,0.059,0.111,0.077,12.5,0.450,0.450,0.286,0.294,102.16,103.06,85.88,37.0,0.113
24511,20901022,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,G,NaN,26:13,93.5,90.7,97.6,100.0,-4.1,-9.3,0.118,1.00,15.4,0.000,0.083,0.038,15.4,0.333,0.333,0.186,0.195,97.66,97.95,81.63,54.0,-0.012
24670,20901029,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,11:10,66.3,62.5,73.5,69.6,-7.3,-7.1,0.500,2.00,25.0,0.000,0.000,0.000,12.5,0.250,0.410,0.250,0.265,95.43,101.01,84.18,24.0,0.043
25067,20901045,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,15:35,80.8,72.7,70.2,73.3,10.5,-0.6,0.200,1.00,14.3,0.053,0.091,0.073,14.3,0.200,0.200,0.158,0.173,94.01,97.03,80.86,33.0,0.054
25620,20901068,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,19:03,106.6,106.1,110.8,108.8,-4.2,-2.8,0.273,0.00,27.3,0.000,0.067,0.027,0.0,0.188,0.188,0.195,0.196,83.45,84.41,70.34,33.0,0.017
25975,20901083,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,G,NaN,39:40,120.9,124.3,99.0,97.3,21.8,27.0,0.217,0.00,20.0,0.000,0.091,0.051,0.0,0.579,0.637,0.247,0.247,90.66,90.15,75.13,74.0,0.151
26134,20901090,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,12:13,129.4,116.7,90.1,87.0,39.3,29.7,0.091,0.00,20.0,0.000,0.125,0.083,0.0,0.000,0.000,0.160,0.177,86.11,92.32,76.93,24.0,-0.065
26483,20901104,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,30:06,115.0,109.8,108.0,111.9,7.1,-2.0,0.059,1.00,5.9,0.000,0.000,0.000,5.9,0.400,0.400,0.235,0.245,95.17,95.68,79.73,61.0,0.000
26955,20901124,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
27231,20901135,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
27685,20901154,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,6:20,70.0,63.6,114.1,100.0,-44.1,-36.4,0.500,0.00,50.0,0.000,0.000,0.000,0.0,1.500,1.500,0.091,0.100,77.68,87.07,72.56,11.0,0.571
28094,20901171,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,8:55,80.5,76.2,98.5,90.0,-18.0,-13.8,0.000,0.00,0.0,0.000,0.111,0.056,0.0,0.000,0.000,0.087,0.096,102.71,110.36,91.96,21.0,-0.082
28320,20901181,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,13:34,94.8,82.9,133.5,129.0,-38.7,-46.2,0.143,1.00,16.7,0.067,0.154,0.107,16.7,0.625,0.625,0.139,0.158,107.17,116.80,97.33,35.0,0.084
28703,20901197,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,20:13,111.3,107.7,81.7,79.5,29.7,28.2,0.154,0.00,20.0,0.050,0.040,0.044,0.0,0.250,0.250,0.178,0.187,89.84,92.60,77.16,39.0,0.009
29101,20901213,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,8:53,82.4,77.8,95.2,93.8,-12.8,-16.0,0.167,1.00,20.0,0.000,0.000,0.000,20.0,0.333,0.333,0.190,0.211,88.51,91.86,76.55,18.0,0.000
29233,20901219,1.610613e+09,CHI,Chicago,2457.0,Jannero Pargo,NaN,NaN,5:24,100.0,80.0,108.7,111.1,-8.7,-31.1,0.000,0.00,0.0,0.000,0.143,0.067,0.0,0.000,0.000,0.000,0.000,76.52,84.52,70.44,10.0,0.000
59433,21100018,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,23:48,119.4,115.2,74.6,77.8,44.8,37.4,0.176,1.00,25.0,0.000,0.120,0.061,25.0,0.500,0.500,0.164,0.165,92.09,91.76,76.47,46.0,0.019
59625,21100025,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,14:16,73.0,66.7,97.3,90.0,-24.3,-23.3,0.250,0.50,11.1,0.000,0.077,0.042,22.2,0.250,0.250,0.250,0.282,92.80,100.95,84.12,30.0,-0.060
60062,21100042,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,14:41,94.3,92.6,62.2,63.0,32.0,29.6,0.625,2.50,38.5,0.071,0.211,0.152,15.4,0.200,0.340,0.250,0.262,88.00,88.26,73.55,27.0,0.208
60303,21100052,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,15:54,81.5,80.0,101.3,96.6,-19.8,-16.6,0.111,0.50,14.3,0.000,0.111,0.057,28.6,0.500,0.500,0.188,0.191,86.16,89.06,74.21,30.0,0.047
60771,21100070,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,12:35,99.7,92.0,90.1,100.0,9.5,-8.0,0.000,0.00,0.0,0.000,0.091,0.037,0.0,0.800,0.800,0.172,0.185,92.69,91.55,76.29,25.0,0.171
60951,21100077,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,13:21,52.1,51.9,96.4,100.0,-44.4,-48.1,0.200,0.00,25.0,0.000,0.077,0.037,0.0,0.500,0.500,0.103,0.112,96.79,95.28,79.40,27.0,0.000
61397,21100094,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,9:07,94.8,100.0,115.6,126.7,-20.8,-26.7,0.200,0.00,50.0,0.000,0.077,0.048,0.0,1.500,1.500,0.059,0.059,87.72,81.61,68.01,16.0,0.161
61565,21100101,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,12:18,133.3,126.1,110.2,104.5,23.1,21.5,0.375,0.00,30.0,0.000,0.000,0.000,0.0,0.583,0.654,0.250,0.272,83.20,87.80,73.17,23.0,0.171
61810,21100110,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,17:51,88.2,87.9,119.2,120.6,-31.0,-32.7,0.083,1.00,20.0,0.000,0.111,0.061,20.0,0.000,0.000,0.108,0.115,90.46,90.08,75.07,33.0,-0.049
62256,21100128,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,5:59,125.0,115.4,104.2,100.0,20.8,15.4,0.250,0.00,16.7,0.000,0.250,0.100,0.0,0.500,0.500,0.385,0.417,94.37,100.31,83.59,13.0,0.083
62667,21100144,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,14:48,69.3,64.5,98.9,93.5,-29.6,-29.0,0.167,0.00,25.0,0.000,0.077,0.034,0.0,0.000,0.000,0.086,0.091,94.31,100.54,83.78,31.0,-0.062
62939,21100154,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,10:10,78.6,78.9,95.6,95.0,-17.0,-16.1,0.250,0.00,50.0,0.000,0.125,0.045,0.0,0.000,0.000,0.042,0.042,92.03,92.13,76.77,19.0,0.000
63403,21100172,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,4:52,91.3,88.9,76.1,66.7,15.2,22.2,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.200,0.205,82.06,88.77,73.97,9.0,-0.167
63844,21100189,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,5:12,147.1,155.6,75.0,75.0,72.1,80.6,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.091,0.105,80.86,78.46,65.38,9.0,-0.200
64332,21100208,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,11:07,107.5,104.3,74.5,73.1,33.1,31.3,0.167,0.33,12.5,0.000,0.059,0.040,37.5,1.000,1.000,0.304,0.314,103.25,105.76,88.13,23.0,0.167
64552,21100217,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,12:28,101.1,100.0,98.2,91.7,2.9,8.3,0.167,0.00,16.7,0.000,0.182,0.105,0.0,0.400,0.400,0.208,0.220,85.01,88.56,73.80,22.0,0.057
64821,21100227,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,14:53,125.5,125.0,105.3,103.4,20.2,21.6,0.667,0.00,40.0,0.000,0.143,0.071,0.0,0.778,0.778,0.290,0.291,90.88,91.91,76.60,28.0,0.336
65270,21100245,1.610613e+09,ATL,Atlanta,2457.0,Jannero Pargo,NaN,NaN,6:34,108.1,107.1,129.8,135.7,-21.7,-28.6,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.667,0.667,0.200,0.202,104.24,102.34,85.28,14.0,0.066

In [234]:
# 'Joe Alexander' <---player is waived on november 13, 2010 after signing with the NOH
#https://en.wikipedia.org/wiki/Joe_Alexander

In [235]:
gi('Joe Alexander')

    game_date     Team     team_id         player   game_id
38 2010-10-27  Hornets  1610612740  Joe Alexander  21000010

In [236]:
gi2('Joe Alexander')

,game_date,Team,Acquired,Relinquished,Notes,team_id,player,game_id
38,2010-10-27,Hornets,,Joe Alexander,placed on IL,1610612740,Joe Alexander,21000010

In [237]:
go('Joe Alexander')

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [238]:
go2('Joe Alexander')

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
19393,20900809,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
21323,20900889,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,2:58,133.1,128.6,200.0,175.0,-66.9,-46.4,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,111.32,121.35,101.12,7.0,0.000
21852,20900911,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
22260,20900928,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
22765,20900949,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,2:10,41.0,40.0,133.0,100.0,-92.0,-60.0,0.000,0.0,0.0,0.250,0.250,0.250,0.0,0.000,0.000,0.333,0.340,95.70,110.77,92.31,5.0,-1.500
23064,20900962,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,12:55,104.2,110.7,132.5,120.0,-28.4,-9.3,0.167,0.0,40.0,0.063,0.100,0.077,0.0,0.333,0.333,0.094,0.092,105.83,107.84,89.86,28.0,-0.009
23183,20900967,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,2:44,169.2,180.0,168.1,114.3,1.1,65.7,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,88.78,105.69,88.07,5.0,-0.040
24000,20901001,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,0:06,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.00,240.00,200.00,0.0,0.000
24240,20901011,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
24516,20901022,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,0:24,113.6,100.0,53.2,50.0,60.4,50.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,166.29,180.75,150.63,1.0,-0.500
24674,20901029,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
25069,20901045,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN
25623,20901068,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,4:15,120.5,114.3,100.0,85.7,20.5,28.6,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.100,0.104,71.38,79.06,65.88,7.0,-0.125
25983,20901083,1.610613e+09,CHI,Chicago,201570.0,Joe Alexander,NaN,NaN,3:23,109.8,112.5,113.1,112.5,-3.3,0.0,0.000,0.0,0.0,0.000,0.333,0.167,0.0,0.000,0.758,0.100,0.098,114.63,113.50,94.58,8.0,-0.105

In [239]:
# 'Jonas Jerebko' <-- did not play this season due to achilles injury, but returns for the seasons 2011-12 thru 2018-19

In [240]:
gi('Jonas Jerebko')

    game_date     Team     team_id         player   game_id
58 2010-10-27  Pistons  1610612765  Jonas Jerebko  21000005

In [241]:
go('Jonas Jerebko')

Empty DataFrame
Columns: [game_id, TEAM_ID, PLAYER_NAME, E_OFF_RATING, game_date, cma2]
Index: []

In [242]:
go2('Jonas Jerebko')

         GAME_ID       TEAM_ID TEAM_ABBREVIATION TEAM_CITY  PLAYER_ID  \
227     20900010  1.610613e+09               DET   Detroit   201973.0
548     20900023  1.610613e+09               DET   Detroit   201973.0
845     20900036  1.610613e+09               DET   Detroit   201973.0
1281    20900054  1.610613e+09               DET   Detroit   201973.0
1436    20900061  1.610613e+09               DET   Detroit   201973.0
1747    20900074  1.610613e+09               DET   Detroit   201973.0
2189    20900092  1.610613e+09               DET   Detroit   201973.0
2667    20900112  1.610613e+09               DET   Detroit   201973.0
3230    20900136  1.610613e+09               DET   Detroit   201973.0
3410    20900143  1.610613e+09               DET   Detroit   201973.0
3733    20900157  1.610613e+09               DET   Detroit   201973.0
4020    20900169  1.610613e+09               DET   Detroit   201973.0
4523    20900190  1.610613e+09               DET   Detroit   201973.0
4667    20900196  1.610613e+09               DET   Detroit   201973.0
5063    20900212  1.610613e+09               DET   Detroit   201973.0
5398    20900226  1.610613e+09               DET   Detroit   201973.0
5710    20900239  1.610613e+09               DET   Detroit   201973.0
6298    20900264  1.610613e+09               DET   Detroit   201973.0
6572    20900275  1.610613e+09               DET   Detroit   201973.0
7003    20900293  1.610613e+09               DET   Detroit   201973.0
7398    20900310  1.610613e+09               DET   Detroit   201973.0
7577    20900317  1.610613e+09               DET   Detroit   201973.0
7936    20900332  1.610613e+09               DET   Detroit   201973.0
8475    20900355  1.610613e+09               DET   Detroit   201973.0
8715    20900365  1.610613e+09               DET   Detroit   201973.0
9099    20900381  1.610613e+09               DET   Detroit   201973.0
9471    20900396  1.610613e+09               DET   Detroit   201973.0
9675    20900405  1.610613e+09               DET   Detroit   201973.0
9925    20900415  1.610613e+09               DET   Detroit   201973.0
10491   20900439  1.610613e+09               DET   Detroit   201973.0
10866   20900454  1.610613e+09               DET   Detroit   201973.0
11226   20900469  1.610613e+09               DET   Detroit   201973.0
12009   20900502  1.610613e+09               DET   Detroit   201973.0
12283   20900513  1.610613e+09               DET   Detroit   201973.0
12749   20900532  1.610613e+09               DET   Detroit   201973.0
13087   20900547  1.610613e+09               DET   Detroit   201973.0
13254   20900554  1.610613e+09               DET   Detroit   201973.0
13770   20900575  1.610613e+09               DET   Detroit   201973.0
14060   20900587  1.610613e+09               DET   Detroit   201973.0
14216   20900594  1.610613e+09               DET   Detroit   201973.0
14685   20900613  1.610613e+09               DET   Detroit   201973.0
15073   20900629  1.610613e+09               DET   Detroit   201973.0
15312   20900639  1.610613e+09               DET   Detroit   201973.0
15962   20900666  1.610613e+09               DET   Detroit   201973.0
16298   20900680  1.610613e+09               DET   Detroit   201973.0
16725   20900698  1.610613e+09               DET   Detroit   201973.0
17098   20900714  1.610613e+09               DET   Detroit   201973.0
17506   20900731  1.610613e+09               DET   Detroit   201973.0
17830   20900744  1.610613e+09               DET   Detroit   201973.0
18324   20900765  1.610613e+09               DET   Detroit   201973.0
18480   20900771  1.610613e+09               DET   Detroit   201973.0
18768   20900783  1.610613e+09               DET   Detroit   201973.0
18976   20900792  1.610613e+09               DET   Detroit   201973.0
19349   20900807  1.610613e+09               DET   Detroit   201973.0
19779   20900825  1.610613e+09               DET   Detroit   201973.0
20198   20900843  1.610613e+09               DET   Detroit   201973.0
20487   20900855  1.610613e+09               DET   Detroit   201973.0
20775   20900867  1.610613e+09               DET   Detroit   201973.0
21015   20900877  1.610613e+09               DET   Detroit   201973.0
21459   20900895  1.610613e+09               DET   Detroit   201973.0
21638   20900903  1.610613e+09               DET   Detroit   201973.0
21927   20900915  1.610613e+09               DET   Detroit   201973.0
22443   20900936  1.610613e+09               DET   Detroit   201973.0
22899   20900955  1.610613e+09               DET   Detroit   201973.0
23211   20900968  1.610613e+09               DET   Detroit   201973.0
23391   20900976  1.610613e+09               DET   Detroit   201973.0
23776   20900992  1.610613e+09               DET   Detroit   201973.0
23932   20900998  1.610613e+09               DET   Detroit   201973.0
24400   20901018  1.610613e+09               DET   Detroit   201973.0
24929   20901040  1.610613e+09               DET   Detroit   201973.0
25277   20901054  1.610613e+09               DET   Detroit   201973.0
25817   20901077  1.610613e+09               DET   Detroit   201973.0
26141   20901090  1.610613e+09               DET   Detroit   201973.0
26670   20901112  1.610613e+09               DET   Detroit   201973.0
27030   20901127  1.610613e+09               DET   Detroit   201973.0
27162   20901133  1.610613e+09               DET   Detroit   201973.0
27594   20901151  1.610613e+09               DET   Detroit   201973.0
27822   20901160  1.610613e+09               DET   Detroit   201973.0
28266   20901179  1.610613e+09               DET   Detroit   201973.0
28458   20901187  1.610613e+09               DET   Detroit   201973.0
28878   20901204  1.610613e+09               DET   Detroit   201973.0
29322   20901223  1.610613e+09               DET   Detroit   201973.0
59223   21100010  1.610613e+09               DET   Detroit   201973.0
59646   21100026  1.610613e+09               DET   Detroit   201973.0
60017   21100041  1.610613e+09               DET   Detroit   201973.0
60286   21100051  1.610613e+09               DET   Detroit   201973.0
60802   21100071  1.610613e+09               DET   Detroit   201973.0
61214   21100087  1.610613e+09               DET   Detroit   201973.0
61506   21100099  1.610613e+09               DET   Detroit   201973.0
61881   21100113  1.610613e+09               DET   Detroit   201973.0
62302   21100130  1.610613e+09               DET   Detroit   201973.0
62443   21100135  1.610613e+09               DET   Detroit   201973.0
62946   21100155  1.610613e+09               DET   Detroit   201973.0
63102   21100161  1.610613e+09               DET   Detroit   201973.0
63630   21100181  1.610613e+09               DET   Detroit   201973.0
64112   21100200  1.610613e+09               DET   Detroit   201973.0
64369   21100210  1.610613e+09               DET   Detroit   201973.0
64666   21100221  1.610613e+09               DET   Detroit   201973.0
64897   21100230  1.610613e+09               DET   Detroit   201973.0
65319   21100247  1.610613e+09               DET   Detroit   201973.0
65668   21100260  1.610613e+09               DET   Detroit   201973.0
66031   21100274  1.610613e+09               DET   Detroit   201973.0
66301   21100285  1.610613e+09               DET   Detroit   201973.0
66740   21100302  1.610613e+09               DET   Detroit   201973.0
66974   21100311  1.610613e+09               DET   Detroit   201973.0
67152   21100318  1.610613e+09               DET   Detroit   201973.0
67626   21100336  1.610613e+09               DET   Detroit   201973.0
67887   21100346  1.610613e+09               DET   Detroit   201973.0
68692   21100378  1.610613e+09               DET   Detroit   201973.0
69094   21100393  1.610613e+09               DET   Detroit   201973.0
69530   21100410  1.610613e+09               DET   Detroit   201973.0
69839   21100422  1.610613e+09               DET   Detroit   201973.0
70058   21100431  1.610613e+09               DET   Detroit   201973.0
70509   21100448  1.610613e+09               DET   Detroit   201973.0
70865   21100462  1.610613e+09               DET   Detroit   201973.0
71339   21100481  1.610613e+09               DET   Detroit   201973.0
71467   21100486  1.610613e+09               DET   Detroit   201973.0
71968   21100505  1.610613e+09               DET   Detroit   201973.0
72277   21100517  1.610613e+09               DET   Detroit   201973.0
72907   21100542  1.610613e+09               DET   Detroit   201973.0
73565   21100567  1.610613e+09               DET   Detroit   201973.0
74083   21100587  1.610613e+09               DET   Detroit   201973.0
74313   21100596  1.610613e+09               DET   Detroit   201973.0
74790   21100615  1.610613e+09               DET   Detroit   201973.0
75279   21100634  1.610613e+09               DET   Detroit   201973.0
75684   21100650  1.610613e+09               DET   Detroit   201973.0
76015   21100663  1.610613e+09               DET   Detroit   201973.0
76730   21100691  1.610613e+09               DET   Detroit   201973.0
77076   21100704  1.610613e+09               DET   Detroit   201973.0
77294   21100713  1.610613e+09               DET   Detroit   201973.0
77677   21100728  1.610613e+09               DET   Detroit   201973.0
78137   21100746  1.610613e+09               DET   Detroit   201973.0
78570   21100763  1.610613e+09               DET   Detroit   201973.0
78815   21100772  1.610613e+09               DET   Detroit   201973.0
79404   21100795  1.610613e+09               DET   Detroit   201973.0
79843   21100812  1.610613e+09               DET   Detroit   201973.0
79987   21100818  1.610613e+09               DET   Detroit   201973.0
80499   21100838  1.610613e+09               DET   Detroit   201973.0
80628   21100843  1.610613e+09               DET   Detroit   201973.0
81298   21100869  1.610613e+09               DET   Detroit   201973.0
81594   21100880  1.610613e+09               DET   Detroit   201973.0
82037   21100897  1.610613e+09               DET   Detroit   201973.0
82473   21100914  1.610613e+09               DET   Detroit   201973.0
82670   21100922  1.610613e+09               DET   Detroit   201973.0
82964   21100933  1.610613e+09               DET   Detroit   201973.0
83533   21100955  1.610613e+09               DET   Detroit   201973.0
83679   21100961  1.610613e+09               DET   Detroit   201973.0
84129   21100978  1.610613e+09               DET   Detroit   201973.0
84591   21200006  1.610613e+09               DET   Detroit   201973.0
85042   21200024  1.610613e+09               DET   Detroit   201973.0
85477   21200041  1.610613e+09               DET   Detroit   201973.0
85761   21200052  1.610613e+09               DET   Detroit   201973.0
86049   21200063  1.610613e+09               DET   Detroit   201973.0
86352   21200075  1.610613e+09               DET   Detroit   201973.0
86611   21200085  1.610613e+09               DET   Detroit   201973.0
86933   21200097  1.610613e+09               DET   Detroit   201973.0
87231   21200109  1.610613e+09               DET   Detroit   201973.0
87601   21200123  1.610613e+09               DET   Detroit   201973.0
88138   21200144  1.610613e+09               DET   Detroit   201973.0
88480   21200158  1.610613e+09               DET   Detroit   201973.0
88921   21200175  1.610613e+09               DET   Detroit   201973.0
89345   21200192  1.610613e+09               DET   Detroit   201973.0
89512   21200198  1.610613e+09               DET   Detroit   201973.0
89890   21200213  1.610613e+09               DET   Detroit   201973.0
90258   21200228  1.610613e+09               DET   Detroit   201973.0
90560   21200240  1.610613e+09               DET   Detroit   201973.0
90727   21200246  1.610613e+09               DET   Detroit   201973.0
91106   21200261  1.610613e+09               DET   Detroit   201973.0
91436   21200274  1.610613e+09               DET   Detroit   201973.0
91751   21200287  1.610613e+09               DET   Detroit   201973.0
92026   21200298  1.610613e+09               DET   Detroit   201973.0
92245   21200306  1.610613e+09               DET   Detroit   201973.0
92785   21200328  1.610613e+09               DET   Detroit   201973.0
93102   21200340  1.610613e+09               DET   Detroit   201973.0
93400   21200352  1.610613e+09               DET   Detroit   201973.0
93746   21200366  1.610613e+09               DET   Detroit   201973.0
94218   21200384  1.610613e+09               DET   Detroit   201973.0
94356   21200390  1.610613e+09               DET   Detroit   201973.0
94968   21200414  1.610613e+09               DET   Detroit   201973.0
95335   21200428  1.610613e+09               DET   Detroit   201973.0
95844   21200448  1.610613e+09               DET   Detroit   201973.0
96151   21200460  1.610613e+09               DET   Detroit   201973.0
96714   21200482  1.610613e+09               DET   Detroit   201973.0
97192   21200501  1.610613e+09               DET   Detroit   201973.0
98090   21200537  1.610613e+09               DET   Detroit   201973.0
98308   21200545  1.610613e+09               DET   Detroit   201973.0
99209   21200580  1.610613e+09               DET   Detroit   201973.0
99798   21200603  1.610613e+09               DET   Detroit   201973.0
100103  21200615  1.610613e+09               DET   Detroit   201973.0
100218  21200620  1.610613e+09               DET   Detroit   201973.0
100570  21200634  1.610613e+09               DET   Detroit   201973.0
101079  21200654  1.610613e+09               DET   Detroit   201973.0
101425  21200667  1.610613e+09               DET   Detroit   201973.0
101511  21200671  1.610613e+09               DET   Detroit   201973.0
102014  21200690  1.610613e+09               DET   Detroit   201973.0
102422  21200706  1.610613e+09               DET   Detroit   201973.0
102513  21200710  1.610613e+09               DET   Detroit   201973.0
102966  21200727  1.610613e+09               DET   Detroit   201973.0
103274  21200739  1.610613e+09               DET   Detroit   201973.0
103517  21200749  1.610613e+09               DET   Detroit   201973.0
103937  21200765  1.610613e+09               DET   Detroit   201973.0
104348  21200781  1.610613e+09               DET   Detroit   201973.0
104628  21200792  1.610613e+09               DET   Detroit   201973.0
104793  21200799  1.610613e+09               DET   Detroit   201973.0
105172  21200814  1.610613e+09               DET   Detroit   201973.0
105511  21200827  1.610613e+09               DET   Detroit   201973.0
105837  21200840  1.610613e+09               DET   Detroit   201973.0
106180  21200854  1.610613e+09               DET   Detroit   201973.0
106615  21200871  1.610613e+09               DET   Detroit   201973.0
107003  21200886  1.610613e+09               DET   Detroit   201973.0
107469  21200904  1.610613e+09               DET   Detroit   201973.0
107858  21200919  1.610613e+09               DET   Detroit   201973.0
108431  21200942  1.610613e+09               DET   Detroit   201973.0
108502  21200945  1.610613e+09               DET   Detroit   201973.0
109043  21200966  1.610613e+09               DET   Detroit   201973.0
109501  21200984  1.610613e+09               DET   Detroit   201973.0
109848  21200997  1.610613e+09               DET   Detroit   201973.0
110574  21201026  1.610613e+09               DET   Detroit   201973.0
110756  21201033  1.610613e+09               DET   Detroit   201973.0
111327  21201055  1.610613e+09               DET   Detroit   201973.0
111893  21201077  1.610613e+09               DET   Detroit   201973.0
112396  21201097  1.610613e+09               DET   Detroit   201973.0
112470  21201100  1.610613e+09               DET   Detroit   201973.0
112855  21201115  1.610613e+09               DET   Detroit   201973.0
113519  21201141  1.610613e+09               DET   Detroit   201973.0
113763  21201150  1.610613e+09               DET   Detroit   201973.0
114185  21201167  1.610613e+09               DET   Detroit   201973.0
114552  21201181  1.610613e+09               DET   Detroit   201973.0
115186  21201206  1.610613e+09               DET   Detroit   201973.0
115430  21201217  1.610613e+09               DET   Detroit   201973.0
115957  21300007  1.610613e+09               DET   Detroit   201973.0
116434  21300026  1.610613e+09               DET   Detroit   201973.0
116833  21300041  1.610613e+09               DET   Detroit   201973.0
117146  21300053  1.610613e+09               DET   Detroit   201973.0
117789  21300078  1.610613e+09               DET   Detroit   201973.0
118473  21300105  1.610613e+09               DET   Detroit   201973.0
118576  21300109  1.610613e+09               DET   Detroit   201973.0
119244  21300135  1.610613e+09               DET   Detroit   201973.0
119601  21300149  1.610613e+09               DET   Detroit   201973.0
119822  21300157  1.610613e+09               DET   Detroit   201973.0
120042  21300166  1.610613e+09               DET   Detroit   201973.0
120415  21300180  1.610613e+09               DET   Detroit   201973.0
120843  21300197  1.610613e+09               DET   Detroit   201973.0
121034  21300204  1.610613e+09               DET   Detroit   201973.0
121439  21300220  1.610613e+09               DET   Detroit   201973.0
121776  21300233  1.610613e+09               DET   Detroit   201973.0
122208  21300250  1.610613e+09               DET   Detroit   201973.0
122553  21300264  1.610613e+09               DET   Detroit   201973.0
122757  21300272  1.610613e+09               DET   Detroit   201973.0
123269  21300292  1.610613e+09               DET   Detroit   201973.0
123485  21300300  1.610613e+09               DET   Detroit   201973.0
123872  21300315  1.610613e+09               DET   Detroit   201973.0
124065  21300323  1.610613e+09               DET   Detroit   201973.0
124361  21300334  1.610613e+09               DET   Detroit   201973.0
124824  21300352  1.610613e+09               DET   Detroit   201973.0
124911  21300356  1.610613e+09               DET   Detroit   201973.0
125348  21300373  1.610613e+09               DET   Detroit   201973.0
125695  21300386  1.610613e+09               DET   Detroit   201973.0
125956  21300396  1.610613e+09               DET   Detroit   201973.0
126251  21300408  1.610613e+09               DET   Detroit   201973.0
126766  21300428  1.610613e+09               DET   Detroit   201973.0
127050  21300439  1.610613e+09               DET   Detroit   201973.0
127420  21300453  1.610613e+09               DET   Detroit   201973.0
128569  21300498  1.610613e+09               DET   Detroit   201973.0
128919  21300512  1.610613e+09               DET   Detroit   201973.0
129141  21300521  1.610613e+09               DET   Detroit   201973.0
129421  21300532  1.610613e+09               DET   Detroit   201973.0
129763  21300545  1.610613e+09               DET   Detroit   201973.0
130832  21300587  1.610613e+09               DET   Detroit   201973.0
131025  21300595  1.610613e+09               DET   Detroit   201973.0
131346  21300607  1.610613e+09               DET   Detroit   201973.0
131870  21300628  1.610613e+09               DET   Detroit   201973.0
132165  21300639  1.610613e+09               DET   Detroit   201973.0
132663  21300659  1.610613e+09               DET   Detroit   201973.0
132925  21300669  1.610613e+09               DET   Detroit   201973.0
133114  21300677  1.610613e+09               DET   Detroit   201973.0
133712  21300700  1.610613e+09               DET   Detroit   201973.0
134027  21300713  1.610613e+09               DET   Detroit   201973.0
134531  21300733  1.610613e+09               DET   Detroit   201973.0
134821  21300744  1.610613e+09               DET   Detroit   201973.0
135000  21300751  1.610613e+09               DET   Detroit   201973.0
135381  21300766  1.610613e+09               DET   Detroit   201973.0
135786  21300782  1.610613e+09               DET   Detroit   201973.0
136113  21300795  1.610613e+09               DET   Detroit   201973.0

In [243]:
#import sqlite data on inactive player per game_id as dataframe

In [244]:
#answer items of to A.

In [245]:
#export names corrected to that of df_or as is.

datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '6injuries_2010-11_player_replace_v1.csv')
if not os.path.exists(datapath_df):
    df_inj3.to_csv(datapath_df, index=False)

<font color='red'>ABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABAB</font>

In [246]:
df_games = pd.read_csv(os.path.join('..', 'raw_data', 'nba_games_all.csv'))
df_games = df_games[df_games.season.str.contains('2010-11')]
df_games

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
1008,21001206,2011-04-11,DET vs. CLE,1610612739,f,W,18.0,63.0,0.222,240,39.0,84.0,0.464,6.0,19.0,0.316,26.0,34.0,1.0,9.0,25.0,34,28.0,9.0,3.0,6.0,25.0,110,1610612765,2010,Regular Season,2010-11
1009,21001190,2011-04-09,MIL vs. CLE,1610612739,f,L,17.0,63.0,0.213,240,37.0,77.0,0.481,7.0,17.0,0.412,20.0,24.0,1.0,8.0,30.0,38,19.0,6.0,6.0,13.0,18.0,101,1610612749,2010,Regular Season,2010-11
1010,21001123,2011-04-01,WAS vs. CLE,1610612739,f,L,15.0,60.0,0.200,240,38.0,82.0,0.463,5.0,22.0,0.227,26.0,32.0,1.0,12.0,26.0,38,22.0,6.0,5.0,8.0,24.0,107,1610612764,2010,Regular Season,2010-11
1011,21001011,2011-03-16,SAC vs. CLE,1610612739,f,W,13.0,53.0,0.197,240,38.0,74.0,0.514,2.0,9.0,0.222,19.0,30.0,1.0,7.0,35.0,42,16.0,7.0,3.0,16.0,18.0,97,1610612758,2010,Regular Season,2010-11
1012,21000985,2011-03-13,OKC @ CLE,1610612739,t,L,12.0,53.0,0.185,240,27.0,80.0,0.338,5.0,14.0,0.357,16.0,26.0,1.0,18.0,36.0,54,16.0,5.0,4.0,17.0,15.0,75,1610612760,2010,Regular Season,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101410,21000068,2010-11-05,IND vs. MIL,1610612749,f,W,2.0,4.0,0.333,240,32.0,83.0,0.386,8.0,20.0,0.400,22.0,30.0,1.0,9.0,36.0,45,16.0,9.0,2.0,15.0,24.0,94,1610612754,2010,Regular Season,2010-11
101411,21000026,NaN,MIN vs. MIL,1610612749,f,L,0.0,2.0,0.000,240,31.0,87.0,0.356,3.0,20.0,0.150,20.0,25.0,1.0,9.0,30.0,39,18.0,4.0,5.0,13.0,29.0,85,1610612750,2010,Regular Season,2010-11
101416,11000120,NaN,MIN @ MIL,1610612749,t,L,3.0,5.0,0.375,265,37.0,86.0,0.430,9.0,24.0,0.375,35.0,42.0,1.0,11.0,39.0,50,27.0,4.0,7.0,24.0,32.0,118,1610612750,2010,Pre Season,2010-11
101417,11000084,NaN,MIN vs. MIL,1610612749,f,L,3.0,3.0,0.500,240,31.0,68.0,0.456,9.0,24.0,0.375,38.0,45.0,1.0,3.0,29.0,32,18.0,6.0,2.0,14.0,27.0,109,1610612750,2010,Pre Season,2010-11
101418,11000034,NaN,CHA @ MIL,1610612749,t,W,2.0,1.0,0.667,240,28.0,78.0,0.359,7.0,18.0,0.389,23.0,29.0,1.0,13.0,34.0,47,15.0,8.0,5.0,15.0,25.0,86,1610612766,2010,Pre Season,2010-11

In [247]:
#nba_games_all.csv dataset uses the CHA terminology (and this is the year they are called the bobcats)
#New Orleans is the Hornets in 2010-11 season
print(df_games[df_games.matchup.str.contains('CHA')].shape)
df_games[df_games.matchup.str.contains('CHA')]

#is '6team_id_abbreviation_nickname.csv' updated???

(180, 32)

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
6437,11000004,NaN,CHA @ CLE,1610612739,t,W,1.0,0.0,1.000,240,28.0,77.0,0.364,3.0,12.0,0.250,28.0,35.0,1.0,16.0,43.0,59,15.0,11.0,8.0,20.0,20.0,87,1610612766,2010,Pre Season,2010-11
6464,21000385,2010-12-17,CHA @ ATL,1610612737,t,W,17.0,11.0,0.607,240,36.0,78.0,0.462,6.0,25.0,0.240,12.0,13.0,1.0,11.0,31.0,42,24.0,4.0,8.0,14.0,20.0,90,1610612766,2010,Regular Season,2010-11
6469,11000111,NaN,CHA vs. ATL,1610612737,f,L,2.0,5.0,0.286,240,22.0,68.0,0.324,5.0,19.0,0.263,17.0,24.0,1.0,11.0,25.0,36,9.0,5.0,7.0,23.0,28.0,66,1610612766,2010,Pre Season,2010-11
6520,21000537,2011-01-08,CHA vs. WAS,1610612764,f,L,9.0,26.0,0.257,240,36.0,82.0,0.439,5.0,15.0,0.333,12.0,15.0,1.0,11.0,23.0,34,24.0,9.0,8.0,16.0,24.0,89,1610612766,2010,Regular Season,2010-11
6568,21000445,2010-12-27,CHA vs. DET,1610612765,f,L,10.0,21.0,0.323,240,38.0,87.0,0.437,11.0,19.0,0.579,13.0,16.0,1.0,10.0,22.0,32,22.0,13.0,5.0,13.0,16.0,100,1610612766,2010,Regular Season,2010-11
6631,21000551,2011-01-10,CHA vs. MEM,1610612763,f,L,17.0,21.0,0.447,240,34.0,87.0,0.391,2.0,10.0,0.200,12.0,22.0,1.0,17.0,29.0,46,14.0,12.0,4.0,16.0,21.0,82,1610612766,2010,Regular Season,2010-11
6648,21001033,2011-03-19,SAS vs. CHA,1610612766,f,L,28.0,41.0,0.406,240,40.0,80.0,0.500,2.0,6.0,0.333,16.0,20.0,1.0,9.0,30.0,39,23.0,6.0,2.0,12.0,20.0,98,1610612759,2010,Regular Season,2010-11
6649,21000986,2011-03-13,TOR vs. CHA,1610612766,f,W,28.0,38.0,0.424,240,35.0,68.0,0.515,5.0,12.0,0.417,20.0,24.0,1.0,8.0,25.0,33,18.0,11.0,5.0,17.0,23.0,95,1610612761,2010,Regular Season,2010-11
6650,21000861,2011-02-25,SAC @ CHA,1610612766,t,W,26.0,32.0,0.448,240,41.0,83.0,0.494,3.0,10.0,0.300,25.0,35.0,1.0,12.0,26.0,38,20.0,6.0,6.0,7.0,16.0,110,1610612758,2010,Regular Season,2010-11
6655,21000745,2011-02-05,DAL @ CHA,1610612766,t,L,21.0,29.0,0.420,240,33.0,89.0,0.371,5.0,21.0,0.238,21.0,24.0,1.0,15.0,25.0,40,16.0,6.0,8.0,7.0,17.0,92,1610612742,2010,Regular Season,2010-11
6656,21000733,2011-02-04,MIA @ CHA,1610612766,t,L,21.0,28.0,0.429,240,35.0,74.0,0.473,9.0,20.0,0.450,18.0,23.0,1.0,11.0,22.0,33,22.0,4.0,5.0,15.0,22.0,97,1610612748,2010,Regular Season,2010-11
6657,21000626,2011-01-20,PHI @ CHA,1610612766,t,W,17.0,24.0,0.415,240,38.0,79.0,0.481,4.0,11.0,0.364,20.0,26.0,1.0,9.0,31.0,40,21.0,6.0,3.0,8.0,17.0,100,1610612755,2010,Regular Season,2010-11
6658,21000551,2011-01-10,MEM @ CHA,1610612766,t,W,14.0,21.0,0.400,240,37.0,72.0,0.514,7.0,20.0,0.350,15.0,21.0,1.0,9.0,31.0,40,24.0,9.0,10.0,18.0,15.0,96,1610612763,2010,Regular Season,2010-11
6659,21000537,2011-01-08,WAS @ CHA,1610612766,t,W,13.0,21.0,0.382,240,39.0,79.0,0.494,6.0,12.0,0.500,20.0,24.0,1.0,12.0,31.0,43,23.0,4.0,8.0,18.0,16.0,104,1610612764,2010,Regular Season,2010-11
6660,21000517,2011-01-05,MIN vs. CHA,1610612766,f,W,12.0,21.0,0.364,265,43.0,98.0,0.439,8.0,26.0,0.308,14.0,24.0,1.0,16.0,35.0,51,25.0,7.0,5.0,12.0,22.0,108,1610612750,2010,Regular Season,2010-11
6668,21000445,2010-12-27,DET @ CHA,1610612766,t,W,10.0,19.0,0.345,240,40.0,76.0,0.526,10.0,17.0,0.588,15.0,19.0,1.0,11.0,35.0,46,24.0,8.0,13.0,23.0,15.0,105,1610612765,2010,Regular Season,2010-11
6669,21000385,2010-12-17,ATL vs. CHA,1610612766,f,L,9.0,17.0,0.346,240,33.0,87.0,0.379,2.0,14.0,0.143,17.0,20.0,1.0,18.0,30.0,48,18.0,8.0,3.0,7.0,15.0,85,1610612737,2010,Regular Season,2010-11
6670,21000360,2010-12-14,TOR @ CHA,1610612766,t,W,9.0,15.0,0.375,240,39.0,75.0,0.520,1.0,6.0,0.167,18.0,29.0,1.0,11.0,32.0,43,24.0,11.0,13.0,15.0,21.0,97,1610612761,2010,Regular Season,2010-11
6671,21000275,2010-12-03,NJN @ CHA,1610612766,t,W,7.0,12.0,0.368,265,31.0,86.0,0.360,7.0,15.0,0.467,22.0,32.0,1.0,17.0,45.0,62,21.0,3.0,11.0,22.0,24.0,91,1610612751,2010,Regular Season,2010-11
6676,21000012,NaN,DAL vs. CHA,1610612766,f,L,0.0,1.0,0.000,240,29.0,73.0,0.397,5.0,13.0,0.385,23.0,24.0,1.0,8.0,28.0,36,22.0,8.0,3.0,20.0,15.0,86,1610612742,2010,Regular Season,2010-11
6677,11000111,NaN,ATL @ CHA,1610612766,t,W,4.0,4.0,0.500,240,33.0,67.0,0.493,5.0,11.0,0.455,28.0,37.0,1.0,7.0,36.0,43,21.0,13.0,6.0,16.0,26.0,99,1610612737,2010,Pre Season,2010-11
6678,11000004,NaN,CLE vs. CHA,1610612766,f,L,0.0,1.0,0.000,240,26.0,82.0,0.317,2.0,10.0,0.200,18.0,29.0,1.0,11.0,34.0,45,16.0,9.0,7.0,17.0,26.0,72,1610612739,2010,Pre Season,2010-11
6732,21000986,2011-03-13,CHA @ TOR,1610612761,t,L,18.0,48.0,0.273,240,33.0,79.0,0.418,4.0,17.0,0.235,20.0,31.0,1.0,16.0,23.0,39,19.0,8.0,1.0,19.0,23.0,90,1610612766,2010,Regular Season,2010-11
6752,21000360,2010-12-14,CHA vs. TOR,1610612761,f,L,9.0,16.0,0.360,240,36.0,89.0,0.404,8.0,26.0,0.308,11.0,21.0,1.0,20.0,23.0,43,21.0,8.0,6.0,18.0,23.0,91,1610612766,2010,Regular Season,2010-11
6868,21000275,2010-12-03,CHA vs. NJN,1610612751,f,L,6.0,14.0,0.300,265,29.0,91.0,0.319,5.0,25.0,0.200,21.0,25.0,1.0,11.0,37.0,48,17.0,10.0,4.0,14.0,27.0,84,1610612766,2010,Regular Season,2010-11
6976,21000861,2011-02-25,CHA vs. SAC,1610612758,f,L,14.0,42.0,0.250,240,36.0,83.0,0.434,7.0,15.0,0.467,19.0,21.0,1.0,14.0,30.0,44,26.0,4.0,5.0,18.0,26.0,98,1610612766,2010,Regular Season,2010-11
7009,21000626,2011-01-20,CHA vs. PHI,1610612755,f,L,17.0,25.0,0.405,240,39.0,85.0,0.459,3.0,14.0,0.214,16.0,22.0,1.0,12.0,33.0,45,22.0,6.0,4.0,9.0,21.0,97,1610612766,2010,Regular Season,2010-11
7071,21001033,2011-03-19,CHA @ SAS,1610612759,t,W,56.0,13.0,0.812,240,39.0,74.0,0.527,17.0,34.0,0.500,14.0,24.0,1.0,5.0,29.0,34,31.0,5.0,6.0,11.0,18.0,109,1610612766,2010,Regular Season,2010-11
7110,21000517,2011-01-05,CHA @ MIN,1610612750,t,L,9.0,27.0,0.250,265,38.0,85.0,0.447,10.0,25.0,0.400,19.0,30.0,1.0,11.0,42.0,53,19.0,6.0,7.0,16.0,20.0,105,1610612766,2010,Regular Season,2010-11
7131,21000745,2011-02-05,CHA vs. DAL,1610612742,f,W,35.0,15.0,0.700,240,40.0,86.0,0.465,7.0,22.0,0.318,14.0,17.0,1.0,14.0,30.0,44,20.0,3.0,14.0,10.0,20.0,101,1610612766,2010,Regular Season,2010-11
7151,21000012,NaN,CHA @ DAL,1610612742,t,W,1.0,0.0,1.000,240,41.0,75.0,0.547,4.0,15.0,0.267,15.0,18.0,1.0,7.0,34.0,41,29.0,12.0,5.0,16.0,18.0,101,1610612766,2010,Regular Season,2010-11
7433,21000733,2011-02-04,CHA vs. MIA,1610612748,f,W,36.0,14.0,0.720,240,43.0,78.0,0.551,9.0,19.0,0.474,14.0,19.0,1.0,9.0,27.0,36,24.0,12.0,3.0,8.0,25.0,109,1610612766,2010,Regular Season,2010-11
32866,21001203,2011-04-11,NJN vs. CHA,1610612766,f,W,33.0,48.0,0.407,240,45.0,79.0,0.570,4.0,13.0,0.308,11.0,16.0,1.0,9.0,21.0,30,27.0,3.0,5.0,8.0,15.0,105,1610612751,2010,Regular Season,2010-11
32867,21001121,2011-04-01,ORL vs. CHA,1610612766,f,L,32.0,43.0,0.427,240,33.0,73.0,0.452,1.0,9.0,0.111,10.0,13.0,1.0,8.0,29.0,37,23.0,6.0,2.0,16.0,20.0,77,1610612753,2010,Regular Season,2010-11
32868,21001054,2011-03-23,IND @ CHA,1610612766,t,L,28.0,42.0,0.400,240,32.0,72.0,0.444,3.0,10.0,0.300,21.0,29.0,1.0,4.0,24.0,28,21.0,6.0,6.0,12.0,25.0,88,1610612754,2010,Regular Season,2010-11
38168,21000463,2010-12-29,CHA vs. CLE,1610612739,f,L,8.0,24.0,0.250,240,32.0,79.0,0.405,4.0,22.0,0.182,24.0,29.0,1.0,11.0,27.0,38,17.0,6.0,6.0,14.0,23.0,92,1610612766,2010,Regular Season,2010-11
38207,21000796,2011-02-12,CHA @ ATL,1610612737,t,L,33.0,20.0,0.623,240,33.0,82.0,0.402,5.0,23.0,0.217,15.0,18.0,1.0,8.0,32.0,40,26.0,6.0,1.0,7.0,19.0,86,1610612766,2010,Regular Season,2010-11
38209,21000639,2011-01-22,CHA vs. ATL,1610612737,f,W,29.0,16.0,0.644,240,37.0,73.0,0.507,9.0,19.0,0.474,20.0,23.0,1.0,5.0,32.0,37,19.0,7.0,4.0,11.0,14.0,103,1610612766,2010,Regular Season,2010-11
38247,21000758,2011-02-07,CHA vs. BOS,1610612738,f,L,38.0,13.0,0.745,240,31.0,76.0,0.408,5.0,14.0,0.357,22.0,27.0,1.0,5.0,32.0,37,25.0,12.0,5.0,14.0,23.0,89,1610612766,2010,Regular Season,2010-11
38251,21000579,2011-01-14,CHA @ BOS,1610612738,t,W,30.0,9.0,0.769,240,36.0,69.0,0.522,8.0,19.0,0.421,19.0,25.0,1.0,3.0,26.0,29,22.0,3.0,8.0,11.0,27.0,99,1610612766,2010,Regular Season,2010-11
38291,21000409,2010-12-20,CHA @ WAS,1610612764,t,W,7.0,19.0,0.269,240,38.0,73.0,0.521,7.0,16.0,0.438,25.0,30.0,1.0,6.0,25.0,31,22.0,10.0,7.0,14.0,26.0,108,1610612766,2010,Regular Season,2010-11
38342,21000071,2010-11-05,CHA @ DET,1610612765,t,W,1.0,5.0,0.167,240,32.0,75.0,0.427,7.0,13.0,0.538,26.0,27.0,1.0,9.0,22.0,31,14.0,11.0,3.0,12.0,13.0,97,1610612766,2010,Regular Season,2010-11
38380,21000130,2010-11-13,CHA vs. UTA,1610612762,f,W,7.0,3.0,0.700,240,35.0,79.0,0.443,4.0,14.0,0.286,22.0,29.0,1.0,11.0,29.0,40,22.0,4.0,7.0,9.0,22.0,96,1610612766,2010,Regular Season,2010-11
38410,21000372,2010-12-15,CHA @ MEM,1610612763,t,W,12.0,14.0,0.462,240,43.0,82.0,0.524,4.0,15.0,0.267,23.0,29.0,1.0,6.0,33.0,39,30.0,12.0,6.0,11.0,22.0,113,1610612766,2010,Regular Season,2010-11
38420,21000940,2011-03-07,LAC @ CHA,1610612766,t,L,26.0,37.0,0.413,240,35.0,78.0,0.449,4.0,9.0,0.444,13.0,22.0,1.0,7.0,30.0,37,22.0,6.0,4.0,13.0,18.0,87,1610612746,2010,Regular Season,2010-11
38428,21000819,2011-02-15,CHI vs. CHA,1610612766,f,L,24.0,32.0,0.429,240,33.0,69.0,0.478,2.0,11.0,0.182,26.0,30.0,1.0,6.0,30.0,36,22.0,7.0,4.0,14.0,25.0,94,1610612741,2010,Regular Season,2010-11
38429,21000796,2011-02-12,ATL vs. CHA,1610612766,f,W,23.0,31.0,0.426,240,33.0,78.0,0.423,5.0,19.0,0.263,17.0,21.0,1.0,9.0,35.0,44,24.0,4.0,7.0,10.0,17.0,88,1610612737,2010,Regular Season,2010-11
38430,21000786,2011-02-11,NJN @ CHA,1610612766,t,L,22.0,31.0,0.415,240,29.0,68.0,0.426,4.0,14.0,0.286,27.0,39.0,1.0,5.0,37.0,42,16.0,2.0,5.0,13.0,21.0,89,1610612751,2010,Regular Season,2010-11
38431,21000758,2011-02-07,BOS @ CHA,1610612766,t,W,22.0,29.0,0.431,240,33.0,79.0,0.418,5.0,16.0,0.313,23.0,30.0,1.0,11.0,39.0,50,16.0,7.0,7.0,16.0,17.0,94,1610612738,2010,Regular Season,2010-11
38432,21000700,2011-01-29,LAC vs. CHA,1610612766,f,L,20.0,26.0,0.435,240,29.0,72.0,0.403,3.0,13.0,0.231,27.0,36.0,1.0,14.0,35.0,49,20.0,2.0,5.0,17.0,22.0,88,1610612746,2010,Regular Season,2010-11
38433,21000691,2011-01-28,GSW vs. CHA,1610612766,f,W,20.0,25.0,0.444,265,46.0,90.0,0.511,10.0,26.0,0.385,19.0,31.0,1.0,17.0,24.0,41,32.0,13.0,6.0,16.0,20.0,121,1610612744,2010,Regular Season,2010-11
38434,21000639,2011-01-22,ATL @ CHA,1610612766,t,L,17.0,25.0,0.405,240,36.0,77.0,0.468,6.0,18.0,0.333,9.0,12.0,1.0,8.0,26.0,34,23.0,6.0,4.0,8.0,16.0,87,1610612737,2010,Regular Season,2010-11
38435,21000579,2011-01-14,BOS vs. CHA,1610612766,f,L,15.0,22.0,0.405,240,32.0,76.0,0.421,3.0,9.0,0.333,27.0,34.0,1.0,13.0,29.0,42,15.0,5.0,2.0,9.0,21.0,94,1610612738,2010,Regular Season,2010-11
38439,21000499,2011-01-03,MIA @ CHA,1610612766,t,L,11.0,21.0,0.344,240,30.0,79.0,0.380,3.0,10.0,0.300,19.0,23.0,1.0,12.0,23.0,35,19.0,8.0,2.0,15.0,20.0,82,1610612748,2010,Regular Season,2010-11
38440,21000463,2010-12-29,CLE @ CHA,1610612766,t,W,11.0,19.0,0.367,240,34.0,76.0,0.447,9.0,19.0,0.474,24.0,34.0,1.0,14.0,27.0,41,20.0,7.0,4.0,11.0,22.0,101,1610612739,2010,Regular Season,2010-11
38441,21000409,2010-12-20,WAS vs. CHA,1610612766,f,L,9.0,18.0,0.333,240,28.0,62.0,0.452,2.0,9.0,0.222,17.0,25.0,1.0,9.0,25.0,34,18.0,6.0,2.0,27.0,25.0,75,1610612764,2010,Regular Season,2010-11
38443,21000372,2010-12-15,MEM vs. CHA,1610612766,f,L,9.0,16.0,0.360,240,28.0,68.0,0.412,5.0,10.0,0.500,19.0,26.0,1.0,5.0,30.0,35,15.0,7.0,7.0,20.0,20.0,80,1610612763,2010,Regular Season,2010-11
38444,21000310,2010-12-07,DEN @ CHA,1610612766,t,W,8.0,13.0,0.381,240,39.0,78.0,0.500,9.0,20.0,0.450,13.0,20.0,1.0,8.0,29.0,37,22.0,8.0,5.0,18.0,23.0,100,1610612743,2010,Regular Season,2010-11
38445,21000240,2010-11-27,MIL vs. CHA,1610612766,f,L,6.0,11.0,0.353,240,32.0,67.0,0.478,2.0,16.0,0.125,35.0,41.0,1.0,9.0,28.0,37,17.0,2.0,3.0,15.0,24.0,101,1610612749,2010,Regular Season,2010-11
38457,21000130,2010-11-13,UTA @ CHA,1610612766,t,L,3.0,7.0,0.300,240,35.0,79.0,0.443,8.0,21.0,0.381,17.0,24.0,1.0,13.0,30.0,43,26.0,5.0,8.0,8.0,24.0,95,1610612762,2010,Regular Season,2010-11
38458,21000071,2010-11-05,DET vs. CHA,1610612766,f,L,1.0,4.0,0.200,240,37.0,67.0,0.552,9.0,20.0,0.450,7.0,11.0,1.0,8.0,30.0,38,28.0,7.0,9.0,22.0,18.0,90,1610612765,2010,Regular Season,2010-11
38459,21000038,NaN,MIL vs. CHA,1610612766,f,L,0.0,3.0,0.000,240,30.0,64.0,0.469,9.0,19.0,0.474,19.0,23.0,1.0,5.0,23.0,28,13.0,6.0,5.0,18.0,28.0,88,1610612749,2010,Regular Season,2010-11
38460,11000100,NaN,NOH @ CHA,1610612766,t,W,3.0,4.0,0.429,265,36.0,77.0,0.468,5.0,14.0,0.357,28.0,33.0,1.0,12.0,28.0,40,23.0,6.0,4.0,20.0,25.0,105,1610612740,2010,Pre Season,2010-11
38540,21001121,2011-04-01,CHA @ ORL,1610612753,t,W,48.0,28.0,0.632,240,30.0,71.0,0.423,9.0,29.0,0.310,20.0,24.0,1.0,9.0,28.0,37,18.0,6.0,6.0,12.0,14.0,89,1610612766,2010,Regular Season,2010-11
38579,21001054,2011-03-23,CHA vs. IND,1610612754,f,W,32.0,40.0,0.444,240,39.0,72.0,0.542,6.0,14.0,0.429,27.0,34.0,1.0,6.0,31.0,37,20.0,9.0,3.0,11.0,24.0,111,1610612766,2010,Regular Season,2010-11
38611,21001203,2011-04-11,CHA @ NJN,1610612751,t,L,24.0,57.0,0.296,240,43.0,79.0,0.544,4.0,10.0,0.400,13.0,14.0,1.0,7.0,22.0,29,23.0,5.0,2.0,6.0,18.0,103,1610612766,2010,Regular Season,2010-11
38621,21000786,2011-02-11,CHA vs. NJN,1610612751,f,W,17.0,37.0,0.315,240,35.0,86.0,0.407,2.0,14.0,0.143,22.0,34.0,1.0,13.0,35.0,48,18.0,3.0,7.0,5.0,28.0,94,1610612766,2010,Regular Season,2010-11
38946,21000310,2010-12-07,CHA vs. DEN,1610612743,f,L,13.0,7.0,0.650,240,31.0,73.0,0.425,11.0,26.0,0.423,25.0,32.0,1.0,6.0,25.0,31,17.0,11.0,5.0,15.0,20.0,98,1610612766,2010,Regular Season,2010-11
39001,11000100,NaN,CHA vs. NOH,1610612740,f,L,1.0,6.0,0.143,265,34.0,78.0,0.436,14.0,36.0,0.389,16.0,21.0,1.0,11.0,20.0,31,24.0,9.0,4.0,22.0,30.0,98,1610612766,2010,Pre Season,2010-11
39017,21000819,2011-02-15,CHA @ CHI,1610612741,t,W,37.0,16.0,0.698,240,38.0,76.0,0.500,7.0,14.0,0.500,23.0,30.0,1.0,11.0,27.0,38,25.0,9.0,3.0,12.0,21.0,106,1610612766,2010,Regular Season,2010-11
39062,21000940,2011-03-07,CHA vs. LAC,1610612746,f,W,24.0,40.0,0.375,240,31.0,74.0,0.419,7.0,18.0,0.389,23.0,29.0,1.0,6.0,33.0,39,18.0,11.0,3.0,12.0,19.0,92,1610612766,2010,Regular Season,2010-11
39067,21000700,2011-01-29,CHA @ LAC,1610612746,t,W,18.0,28.0,0.391,240,37.0,86.0,0.430,11.0,29.0,0.379,18.0,24.0,1.0,11.0,24.0,35,26.0,10.0,5.0,6.0,26.0,103,1610612766,2010,Regular Season,2010-11
39144,21000691,2011-01-28,CHA @ GSW,1610612744,t,L,19.0,27.0,0.413,265,41.0,88.0,0.466,11.0,25.0,0.440,20.0,23.0,1.0,16.0,33.0,49,26.0,12.0,4.0,18.0,24.0,113,1610612766,2010,Regular Season,2010-11
39225,21000499,2011-01-03,CHA vs. MIA,1610612748,f,W,27.0,9.0,0.750,240,37.0,76.0,0.487,5.0,15.0,0.333,17.0,19.0,1.0,10.0,36.0,46,15.0,5.0,5.0,11.0,15.0,96,1610612766,2010,Regular Season,2010-11
39271,21000240,2010-11-27,CHA @ MIL,1610612749,t,W,6.0,10.0,0.375,240,33.0,72.0,0.458,10.0,26.0,0.385,28.0,34.0,1.0,9.0,23.0,32,25.0,7.0,2.0,12.0,33.0,104,1610612766,2010,Regular Season,2010-11
39275,21000038,NaN,CHA @ MIL,1610612749,t,W,1.0,2.0,0.333,240,32.0,71.0,0.451,11.0,22.0,0.500,23.0,27.0,1.0,14.0,26.0,40,19.0,7.0,5.0,18.0,23.0,98,1610612766,2010,Regular Season,2010-11
64258,21001217,2011-04-13,ATL @ CHA,1610612766,t,W,34.0,48.0,0.415,240,40.0,80.0,0.500,3.0,10.0,0.300,13.0,16.0,1.0,7.0,30.0,37,27.0,7.0,7.0,8.0,16.0,96,1610612737,2010,Regular Season,2010-11
64259,21001182,2011-04-08,MIA vs. CHA,1610612766,f,L,32.0,47.0,0.405,240,41.0,86.0,0.477,5.0,16.0,0.313,16.0,21.0,1.0,11.0,22.0,33,17.0,10.0,4.0,10.0,25.0,103,1610612748,2010,Regular Season,2010-11
64260,21001096,2011-03-28,MIL @ CHA,1610612766,t,W,31.0,42.0,0.425,240,33.0,68.0,0.485,3.0,11.0,0.273,18.0,26.0,1.0,4.0,33.0,37,25.0,2.0,2.0,9.0,17.0,87,1610612749,2010,Regular Season,2010-11
64261,21001082,2011-03-26,NYK @ CHA,1610612766,t,W,30.0,42.0,0.417,240,43.0,91.0,0.473,5.0,18.0,0.278,23.0,28.0,1.0,16.0,30.0,46,23.0,3.0,8.0,5.0,28.0,114,1610612752,2010,Regular Season,2010-11
64262,21001070,2011-03-25,BOS vs. CHA,1610612766,f,W,29.0,42.0,0.408,240,30.0,69.0,0.435,1.0,11.0,0.091,22.0,25.0,1.0,7.0,30.0,37,15.0,8.0,4.0,15.0,26.0,83,1610612738,2010,Regular Season,2010-11
64267,21001022,2011-03-18,CHA @ OKC,1610612760,t,W,45.0,23.0,0.662,240,38.0,72.0,0.528,7.0,18.0,0.389,16.0,22.0,1.0,6.0,30.0,36,23.0,13.0,9.0,12.0,19.0,99,1610612766,2010,Regular Season,2010-11
64326,21000095,2010-11-08,CHA vs. SAS,1610612759,f,W,5.0,1.0,0.833,240,36.0,85.0,0.424,12.0,26.0,0.462,11.0,17.0,1.0,15.0,31.0,46,22.0,9.0,9.0,16.0,20.0,95,1610612766,2010,Regular Season,2010-11
69350,21001217,2011-04-13,CHA vs. ATL,1610612737,f,L,44.0,38.0,0.537,240,34.0,79.0,0.430,1.0,8.0,0.125,16.0,20.0,1.0,10.0,27.0,37,16.0,3.0,7.0,14.0,15.0,85,1610612766,2010,Regular Season,2010-11
69401,21001070,2011-03-25,CHA @ BOS,1610612738,t,L,50.0,21.0,0.704,240,29.0,71.0,0.408,3.0,15.0,0.200,20.0,26.0,1.0,9.0,28.0,37,15.0,3.0,5.0,15.0,24.0,81,1610612766,2010,Regular Season,2010-11
69423,21000343,2010-12-11,CHA vs. BOS,1610612738,f,W,19.0,4.0,0.826,240,31.0,71.0,0.437,8.0,21.0,0.381,23.0,28.0,1.0,11.0,37.0,48,21.0,15.0,10.0,18.0,21.0,93,1610612766,2010,Regular Season,2010-11
69463,21000124,2010-11-12,CHA @ WAS,1610612764,t,L,2.0,5.0,0.286,240,36.0,86.0,0.419,5.0,21.0,0.238,8.0,10.0,1.0,13.0,17.0,30,27.0,13.0,9.0,12.0,19.0,85,1610612766,2010,Regular Season,2010-11
69483,21000722,2011-02-02,CHA @ DET,1610612765,t,L,17.0,32.0,0.347,240,34.0,78.0,0.436,7.0,19.0,0.368,12.0,17.0,1.0,6.0,24.0,30,23.0,7.0,8.0,10.0,21.0,87,1610612766,2010,Regular Season,2010-11
69510,11000072,NaN,CHA vs. DET,1610612765,f,L,2.0,4.0,0.333,240,34.0,84.0,0.405,10.0,21.0,0.476,16.0,24.0,1.0,11.0,27.0,38,20.0,9.0,3.0,17.0,30.0,94,1610612766,2010,Pre Season,2010-11
69523,21000713,2011-01-31,CHA @ UTA,1610612762,t,W,29.0,20.0,0.592,240,34.0,76.0,0.447,3.0,8.0,0.375,12.0,14.0,1.0,9.0,40.0,49,21.0,4.0,10.0,19.0,22.0,83,1610612766,2010,Regular Season,2010-11
69583,21001022,2011-03-18,OKC vs. CHA,1610612766,f,L,28.0,40.0,0.412,240,33.0,74.0,0.446,5.0,17.0,0.294,11.0,18.0,1.0,7.0,27.0,34,17.0,6.0,2.0,15.0,18.0,82,1610612760,2010,Regular Season,2010-11
69584,21000953,2011-03-09,CHI @ CHA,1610612766,t,L,26.0,38.0,0.406,240,37.0,81.0,0.457,3.0,11.0,0.273,7.0,11.0,1.0,13.0,24.0,37,26.0,2.0,9.0,11.0,14.0,84,1610612741,2010,Regular Season,2010-11
69585,21000909,2011-03-02,DEN vs. CHA,1610612766,f,L,26.0,34.0,0.433,240,29.0,79.0,0.367,4.0,17.0,0.235,18.0,23.0,1.0,6.0,22.0,28,20.0,6.0,1.0,13.0,25.0,80,1610612743,2010,Regular Season,2010-11
69586,21000883,2011-02-27,ORL vs. CHA,1610612766,f,L,26.0,33.0,0.441,240,34.0,85.0,0.400,5.0,16.0,0.313,13.0,18.0,1.0,13.0,26.0,39,14.0,9.0,2.0,12.0,22.0,86,1610612753,2010,Regular Season,2010-11
69587,21000838,2011-02-22,TOR @ CHA,1610612766,t,W,25.0,32.0,0.439,240,38.0,81.0,0.469,4.0,14.0,0.286,34.0,42.0,1.0,11.0,30.0,41,25.0,9.0,5.0,9.0,19.0,114,1610612761,2010,Regular Season,2010-11
69593,21000722,2011-02-02,DET vs. CHA,1610612766,f,W,21.0,27.0,0.438,240,37.0,73.0,0.507,3.0,10.0,0.300,20.0,25.0,1.0,8.0,38.0,46,26.0,4.0,1.0,13.0,19.0,97,1610612765,2010,Regular Season,2010-11
69594,21000713,2011-01-31,UTA vs. CHA,1610612766,f,L,20.0,27.0,0.426,240,26.0,73.0,0.356,6.0,20.0,0.300,20.0,27.0,1.0,9.0,27.0,36,12.0,7.0,3.0,13.0,22.0,78,1610612762,2010,Regular Season,2010-11
69595,21000666,2011-01-25,SAC vs. CHA,1610612766,f,W,18.0,25.0,0.419,240,32.0,71.0,0.451,3.0,8.0,0.375,27.0,36.0,1.0,11.0,39.0,50,12.0,5.0,1.0,16.0,29.0,94,1610612758,2010,Regular Season,2010-11
69596,21000588,2011-01-15,NOH @ CHA,1610612766,t,L,15.0,23.0,0.395,240,28.0,69.0,0.406,5.0,15.0,0.333,20.0,26.0,1.0,11.0,32.0,43,19.0,4.0,4.0,15.0,17.0,81,1610612740,2010,Regular Season,2010-11
69597,21000561,2011-01-12,CHI @ CHA,1610612766,t,W,15.0,21.0,0.417,240,35.0,81.0,0.432,6.0,21.0,0.286,20.0,27.0,1.0,8.0,30.0,38,23.0,4.0,8.0,7.0,23.0,96,1610612741,2010,Regular Season,2010-11
69601,21000477,2010-12-31,GSW @ CHA,1610612766,t,L,11.0,20.0,0.355,240,35.0,83.0,0.422,5.0,16.0,0.313,20.0,28.0,1.0,18.0,32.0,50,19.0,9.0,4.0,13.0,16.0,95,1610612744,2010,Regular Season,2010-11
69602,21000343,2010-12-11,BOS @ CHA,1610612766,t,L,8.0,15.0,0.348,240,24.0,71.0,0.338,1.0,11.0,0.091,13.0,23.0,1.0,11.0,27.0,38,17.0,11.0,5.0,21.0,24.0,62,1610612738,2010,Regular Season,2010-11

In [248]:
#df_games[df_games.matchup.str.contains('NOH')]

In [249]:
#check players by last name on offensive rating dataset <<<<<<