In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [2]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [3]:
#https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/work-with-files-directories-paths-in-python/set-working-directory-os-package/
path = os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2006_2018.csv')
path

'../processed_data/5boxscoreadvancedv2_2006_2018.csv'

In [4]:
df = pd.read_csv(path)

In [5]:
df

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20800716,1610612738,BOS,Boston,1718,Paul Pierce,F,NaN,37:00,112.4,117.1,96.2,97.1,16.2,20.0,0.240,3.00,17.6,0.033,0.158,0.103,5.9,0.457,0.547,0.346,0.342,93.17,90.81,75.67,70,0.182
1,20800716,1610612738,BOS,Boston,201175,Glen Davis,F,NaN,41:55,106.0,110.3,107.6,110.0,-1.6,0.3,0.069,0.67,12.5,0.100,0.211,0.162,18.8,0.545,0.524,0.159,0.157,93.32,90.48,75.40,78,0.079
2,20800716,1610612738,BOS,Boston,2570,Kendrick Perkins,C,NaN,31:47,99.1,101.7,103.4,108.6,-4.3,-6.9,0.042,1.00,20.0,0.038,0.219,0.138,20.0,0.333,0.333,0.059,0.059,91.69,88.33,73.61,59,0.064
3,20800716,1610612738,BOS,Boston,951,Ray Allen,G,NaN,43:04,107.7,109.9,105.0,107.1,2.7,2.7,0.111,1.00,12.0,0.029,0.044,0.038,12.0,0.583,0.609,0.237,0.238,93.78,91.95,76.63,81,0.090
4,20800716,1610612738,BOS,Boston,200765,Rajon Rondo,G,NaN,35:49,108.6,113.0,100.1,102.8,8.5,10.2,0.348,1.14,28.6,0.107,0.057,0.079,25.0,0.750,0.776,0.253,0.251,97.00,93.81,78.18,69,0.154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386106,21000475,1610612757,POR,Portland,201988,Patty Mills,NaN,NaN,14:49,63.1,56.3,109.7,110.3,-46.6,-54.1,0.667,0.00,22.2,0.000,0.111,0.037,0.0,0.143,0.143,0.206,0.237,93.40,98.77,82.31,32,-0.073
386107,21000475,1610612757,POR,Portland,1752,Sean Marks,NaN,NaN,6:35,59.5,53.8,124.2,115.4,-64.6,-61.5,0.000,0.00,0.0,0.111,0.000,0.077,50.0,0.000,0.000,0.143,0.157,86.91,94.78,78.99,13,-0.429
386108,21000475,1610612757,POR,Portland,202356,Armon Johnson,NaN,NaN,1:10,0.0,0.0,215.5,166.7,-215.5,-166.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,86.40,123.43,102.86,3,0.000
386109,21000475,1610612757,POR,Portland,202337,Luke Babbitt,NaN,NaN,1:10,0.0,0.0,215.5,166.7,-215.5,-166.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.667,1.064,86.40,123.43,102.86,3,-0.857
386110,21000475,1610612757,POR,Portland,200750,Brandon Roy,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [6]:
386000 * .7

270200.0

In [7]:
#regular season and playoff games for 2009-10 season?

In [8]:
path = os.path.join('..', 'processed_data', '3game_date_home_away.csv')
df2 = pd.read_csv(path)
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20600001,2006-10-31,1610612748,0.000,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006.0,1610612741,1.000,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,Regular Season,2006-07
1,20600002,2006-10-31,1610612747,1.000,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006.0,1610612756,0.000,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,Regular Season,2006-07
2,20600003,2006-11-01,1610612755,1.000,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006.0,1610612737,0.000,240,26.0,78.0,0.333,4.0,17.0,0.235,19.0,22.0,1.0,17.0,25.0,42,11.0,9.0,4.0,18.0,24.0,75,Regular Season,2006-07
3,20600004,2006-11-01,1610612766,0.000,240,37.0,78.0,0.474,4.0,10.0,0.400,21.0,32.0,1.0,11.0,35.0,46,23.0,8.0,7.0,22.0,29.0,99,2006.0,1610612754,1.000,240,35.0,86.0,0.407,6.0,16.0,0.375,30.0,41.0,1.0,18.0,32.0,50,26.0,14.0,5.0,17.0,26.0,106,Regular Season,2006-07
4,20600005,2006-11-01,1610612753,1.000,240,35.0,59.0,0.593,6.0,8.0,0.750,33.0,42.0,1.0,6.0,30.0,36,21.0,7.0,7.0,23.0,23.0,109,2006.0,1610612741,0.500,240,37.0,82.0,0.451,6.0,20.0,0.300,14.0,24.0,1.0,11.0,16.0,27,21.0,7.0,0.0,15.0,31.0,94,Regular Season,2006-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15514,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
15515,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
15516,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
15517,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
15518,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [9]:
#df2.info()

In [10]:
#df2[(df2.season == '2009-10')][(df2.season_type == 'Regular Season') | (df2.season_type == 'Playoffs')].reset_index(drop=True)
df2 = df2[(df2.season == '2009-10') |
         (df2.season == '2010-11') |
         (df2.season == '2011-12') |
         (df2.season == '2012-13') |
         (df2.season == '2013-14') |
         (df2.season == '2014-15') |
         (df2.season == '2015-16') |
         (df2.season == '2016-17') |
         (df2.season == '2017-18')].reset_index(drop=True)
df2

,game_id,game_date,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,season_type,season
0,20900001,2009-10-27,1610612739,0.000,240,29.0,70.0,0.414,6.0,17.0,0.353,25.0,32.0,1.0,6.0,26.0,32,17.0,7.0,9.0,13.0,22.0,89,2009.0,1610612738,1.000,240,32.0,72.0,0.444,9.0,19.0,0.474,22.0,26.0,1.0,6.0,32.0,38,20.0,9.0,8.0,14.0,27.0,95,Regular Season,2009-10
1,20900002,2009-10-27,1610612742,0.000,240,30.0,76.0,0.395,4.0,18.0,0.222,27.0,34.0,1.0,11.0,31.0,42,16.0,6.0,9.0,9.0,20.0,91,2009.0,1610612764,1.000,240,39.0,84.0,0.464,4.0,13.0,0.308,20.0,24.0,1.0,9.0,37.0,46,19.0,6.0,4.0,9.0,29.0,102,Regular Season,2009-10
2,20900003,2009-10-27,1610612757,1.000,240,33.0,77.0,0.429,10.0,21.0,0.476,20.0,22.0,1.0,12.0,39.0,51,23.0,9.0,12.0,26.0,27.0,96,2009.0,1610612745,0.000,240,30.0,81.0,0.370,5.0,18.0,0.278,22.0,29.0,1.0,10.0,23.0,33,18.0,12.0,2.0,16.0,26.0,87,Regular Season,2009-10
3,20900004,2009-10-27,1610612747,1.000,240,35.0,85.0,0.412,4.0,17.0,0.235,25.0,37.0,1.0,17.0,30.0,47,17.0,13.0,4.0,16.0,15.0,99,2009.0,1610612746,0.000,240,39.0,87.0,0.448,3.0,15.0,0.200,11.0,16.0,1.0,15.0,36.0,51,27.0,10.0,4.0,20.0,27.0,92,Regular Season,2009-10
4,20900005,2009-10-28,1610612737,1.000,240,46.0,87.0,0.529,7.0,12.0,0.583,21.0,29.0,1.0,8.0,27.0,35,30.0,16.0,6.0,10.0,25.0,120,2009.0,1610612754,0.000,240,39.0,73.0,0.534,10.0,18.0,0.556,21.0,25.0,1.0,6.0,34.0,40,23.0,1.0,4.0,25.0,26.0,109,Regular Season,2009-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11574,41700317,2018-05-28,1610612745,0.429,240,36.0,90.0,0.400,7.0,44.0,0.159,13.0,22.0,1.0,17.0,27.0,44,17.0,13.0,3.0,12.0,17.0,92,2017.0,1610612744,0.571,240,39.0,80.0,0.488,16.0,39.0,0.410,7.0,14.0,0.0,11.0,31.0,42,25.0,9.0,7.0,16.0,22.0,101,Playoffs,2017-18
11575,41700401,2018-05-31,1610612744,1.000,265,46.0,90.0,0.511,13.0,36.0,0.361,19.0,20.0,1.0,4.0,34.0,38,31.0,10.0,6.0,7.0,18.0,124,2017.0,1610612739,0.000,265,44.0,99.0,0.444,10.0,37.0,0.270,16.0,22.0,1.0,19.0,34.0,53,18.0,5.0,3.0,11.0,18.0,114,Playoffs,2017-18
11576,41700402,2018-06-03,1610612744,1.000,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017.0,1610612739,0.000,240,37.0,90.0,0.411,9.0,27.0,0.333,20.0,26.0,1.0,16.0,26.0,42,25.0,9.0,4.0,10.0,15.0,103,Playoffs,2017-18
11577,41700403,2018-06-06,1610612739,0.000,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017.0,1610612744,1.000,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,Playoffs,2017-18
11578,41700404,2018-06-08,1610612739,0.000,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017.0,1610612744,1.000,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,Playoffs,2017-18

In [11]:
df2.season.value_counts()

2013-14    1319
2015-16    1316
2012-13    1315
2009-10    1312
2017-18    1312
2010-11    1311
2014-15    1311
2016-17    1309
2011-12    1074
Name: season, dtype: int64

In [12]:
df2.shape

(11579, 47)

In [13]:
23 * 11579

266317

In [14]:
df.rename(columns={'GAME_ID':'game_id'}, inplace=True)
df

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20800716,1610612738,BOS,Boston,1718,Paul Pierce,F,NaN,37:00,112.4,117.1,96.2,97.1,16.2,20.0,0.240,3.00,17.6,0.033,0.158,0.103,5.9,0.457,0.547,0.346,0.342,93.17,90.81,75.67,70,0.182
1,20800716,1610612738,BOS,Boston,201175,Glen Davis,F,NaN,41:55,106.0,110.3,107.6,110.0,-1.6,0.3,0.069,0.67,12.5,0.100,0.211,0.162,18.8,0.545,0.524,0.159,0.157,93.32,90.48,75.40,78,0.079
2,20800716,1610612738,BOS,Boston,2570,Kendrick Perkins,C,NaN,31:47,99.1,101.7,103.4,108.6,-4.3,-6.9,0.042,1.00,20.0,0.038,0.219,0.138,20.0,0.333,0.333,0.059,0.059,91.69,88.33,73.61,59,0.064
3,20800716,1610612738,BOS,Boston,951,Ray Allen,G,NaN,43:04,107.7,109.9,105.0,107.1,2.7,2.7,0.111,1.00,12.0,0.029,0.044,0.038,12.0,0.583,0.609,0.237,0.238,93.78,91.95,76.63,81,0.090
4,20800716,1610612738,BOS,Boston,200765,Rajon Rondo,G,NaN,35:49,108.6,113.0,100.1,102.8,8.5,10.2,0.348,1.14,28.6,0.107,0.057,0.079,25.0,0.750,0.776,0.253,0.251,97.00,93.81,78.18,69,0.154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386106,21000475,1610612757,POR,Portland,201988,Patty Mills,NaN,NaN,14:49,63.1,56.3,109.7,110.3,-46.6,-54.1,0.667,0.00,22.2,0.000,0.111,0.037,0.0,0.143,0.143,0.206,0.237,93.40,98.77,82.31,32,-0.073
386107,21000475,1610612757,POR,Portland,1752,Sean Marks,NaN,NaN,6:35,59.5,53.8,124.2,115.4,-64.6,-61.5,0.000,0.00,0.0,0.111,0.000,0.077,50.0,0.000,0.000,0.143,0.157,86.91,94.78,78.99,13,-0.429
386108,21000475,1610612757,POR,Portland,202356,Armon Johnson,NaN,NaN,1:10,0.0,0.0,215.5,166.7,-215.5,-166.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,86.40,123.43,102.86,3,0.000
386109,21000475,1610612757,POR,Portland,202337,Luke Babbitt,NaN,NaN,1:10,0.0,0.0,215.5,166.7,-215.5,-166.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.667,1.064,86.40,123.43,102.86,3,-0.857
386110,21000475,1610612757,POR,Portland,200750,Brandon Roy,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [15]:
df = pd.merge(df, df2.game_id, how='right', on='game_id').rename(columns={'game_id':'GAME_ID'})
df

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [16]:
#df[df.GAME_ID == 20900001]
#23

In [17]:
set1=  set(df.GAME_ID)

In [18]:
set2 = set(df2.game_id)

In [19]:
set2 - set1

set()

In [20]:
set1  - set2

set()

In [21]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '5boxscoreadvancedv2_2009_2018.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=False)