In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [4]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [5]:
df_bsa = rcp('A12bsa_game_id_team_id_player_id_2009_2018.csv', ['game_date'])
p(df_bsa)

(291642, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2544.0,LeBron James,F,NaN,44.916667,99.8,101.2,99.2,101.2,0.5,0.0,0.471,1.60,19.5,0.000,0.100,0.049,12.2,0.636,0.685,0.351,0.354,93.44,91.90,76.59,86.0,0.240
1,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2760.0,Anderson Varejao,F,NaN,32.833333,109.3,108.2,115.5,116.1,-6.1,-7.9,0.050,0.00,8.3,0.179,0.091,0.140,0.0,0.333,0.418,0.167,0.168,89.69,89.89,74.91,61.0,0.040
2,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,406.0,Shaquille O'Neal,C,NaN,28.800000,98.5,96.4,95.5,96.2,3.0,0.1,0.083,1.00,7.1,0.000,0.385,0.200,7.1,0.455,0.421,0.213,0.221,89.33,89.99,75.00,55.0,0.121
3,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,1515.0,Anthony Parker,G,NaN,40.166667,108.0,107.8,101.4,103.9,6.6,3.9,0.160,1.33,23.5,0.000,0.083,0.042,17.6,0.444,0.506,0.153,0.157,93.10,92.03,76.69,77.0,0.076
4,20900001,2009-10-27,1610612739,2009-10,CLE,Cleveland,2590.0,Mo Williams,G,NaN,35.033333,98.9,92.8,109.1,107.2,-10.2,-14.5,0.167,1.50,18.8,0.000,0.000,0.000,12.5,0.375,0.564,0.176,0.187,90.74,94.53,78.77,69.0,0.044
291637,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,201156.0,Nick Young,NaN,NaN,8.983333,131.9,133.3,98.8,106.3,33.0,27.1,0.000,0.00,0.0,0.000,0.067,0.042,0.0,0.375,0.375,0.190,0.198,94.66,90.92,75.77,18.0,0.000
291638,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2561.0,David West,NaN,NaN,7.600000,97.6,92.9,128.7,135.7,-31.1,-42.9,0.333,0.00,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.071,0.075,88.67,88.42,73.68,14.0,0.039
291639,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1626172.0,Kevon Looney,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.500,0.500,0.222,0.254,102.44,94.85,79.04,6.0,0.214
291640,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2585.0,Zaza Pachulia,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.000,0.250,0.125,33.3,0.000,0.532,0.333,0.381,102.44,94.85,79.04,6.0,0.143
291641,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1627775.0,Patrick McCaw,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.000,0.000,0.000,0.000,102.44,94.85,79.04,6.0,0.071

In [6]:
df_bsa.columns

Index(['game_id', 'game_date', 'team_id', 'season', 'TEAM_ABBREVIATION',
       'TEAM_CITY', 'PLAYER_ID', 'PLAYER_NAME', 'START_POSITION', 'COMMENT',
       'MIN', 'E_OFF_RATING', 'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING',
       'E_NET_RATING', 'NET_RATING', 'AST_PCT', 'AST_TOV', 'AST_RATIO',
       'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT',
       'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE'],
      dtype='object')

In [7]:
df_bsa_gdgitispip = df_bsa[['game_date', 'game_id', 'team_id', 'season', 'PLAYER_ID', 'PLAYER_NAME']].rename(columns={'PLAYER_NAME':'player'}).drop_duplicates().reset_index(drop=True)
p(df_bsa_gdgitispip)

(291642, 6)

        game_date   game_id     team_id   season  PLAYER_ID            player
0      2009-10-27  20900001  1610612739  2009-10     2544.0      LeBron James
1      2009-10-27  20900001  1610612739  2009-10     2760.0  Anderson Varejao
2      2009-10-27  20900001  1610612739  2009-10      406.0  Shaquille O'Neal
3      2009-10-27  20900001  1610612739  2009-10     1515.0    Anthony Parker
4      2009-10-27  20900001  1610612739  2009-10     2590.0       Mo Williams
291637 2018-06-08  41700404  1610612744  2017-18   201156.0        Nick Young
291638 2018-06-08  41700404  1610612744  2017-18     2561.0        David West
291639 2018-06-08  41700404  1610612744  2017-18  1626172.0      Kevon Looney
291640 2018-06-08  41700404  1610612744  2017-18     2585.0     Zaza Pachulia
291641 2018-06-08  41700404  1610612744  2017-18  1627775.0     Patrick McCaw

<font color='red'> did we filter for regular season and playoffs here</font> -no, this was done in '3game_id_game_date_team_id.csv'

In [8]:
df_inactive = rcp('A11inactive_game_id_team_id_player_id_2010_2018.csv', ['game_date'])
p(df_inactive)

(43125, 12)

,game_id,game_date,season,PLAYER_ID,FIRST_NAME,LAST_NAME,JERSEY_NUM,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,player
0,21000001,2010-10-26,2010-11,202376,Luke,Harangody,55,1610612738,Boston,Celtics,BOS,Luke Harangody
1,21000001,2010-10-26,2010-11,2570,Kendrick,Perkins,43,1610612738,Boston,Celtics,BOS,Kendrick Perkins
2,21000001,2010-10-26,2010-11,202340,Avery,Bradley,0,1610612738,Boston,Celtics,BOS,Avery Bradley
3,21000001,2010-10-26,2010-11,202354,Dexter,Pittman,45,1610612748,Miami,Heat,MIA,Dexter Pittman
4,21000001,2010-10-26,2010-11,2034,Mike,Miller,13,1610612748,Miami,Heat,MIA,Mike Miller
43120,21701230,2018-04-11,2017-18,202697,Iman,Shumpert,4,1610612758,Sacramento,Kings,SAC,Iman Shumpert
43121,21701230,2018-04-11,2017-18,203900,Markel,Brown,26,1610612745,Houston,Rockets,HOU,Markel Brown
43122,21701230,2018-04-11,2017-18,201583,Ryan,Anderson,33,1610612745,Houston,Rockets,HOU,Ryan Anderson
43123,21701230,2018-04-11,2017-18,2772,Trevor,Ariza,1,1610612745,Houston,Rockets,HOU,Trevor Ariza
43124,21701230,2018-04-11,2017-18,201601,Luc,Mbah a Moute,12,1610612745,Houston,Rockets,HOU,Luc Mbah a Moute

In [9]:
df_inactive.columns

Index(['game_id', 'game_date', 'season', 'PLAYER_ID', 'FIRST_NAME',
       'LAST_NAME', 'JERSEY_NUM', 'TEAM_ID', 'TEAM_CITY', 'TEAM_NAME',
       'TEAM_ABBREVIATION', 'player'],
      dtype='object')

In [10]:
df_inactive_gdgitispip = df_inactive[['game_date', 'game_id', 'TEAM_ID', 'season', 'PLAYER_ID', 'player']].rename(columns={'TEAM_ID':'team_id'}).drop_duplicates().reset_index(drop=True)
p(df_inactive_gdgitispip)

(43125, 6)

       game_date   game_id     team_id   season  PLAYER_ID            player
0     2010-10-26  21000001  1610612738  2010-11     202376    Luke Harangody
1     2010-10-26  21000001  1610612738  2010-11       2570  Kendrick Perkins
2     2010-10-26  21000001  1610612738  2010-11     202340     Avery Bradley
3     2010-10-26  21000001  1610612748  2010-11     202354    Dexter Pittman
4     2010-10-26  21000001  1610612748  2010-11       2034       Mike Miller
43120 2018-04-11  21701230  1610612758  2017-18     202697     Iman Shumpert
43121 2018-04-11  21701230  1610612745  2017-18     203900      Markel Brown
43122 2018-04-11  21701230  1610612745  2017-18     201583     Ryan Anderson
43123 2018-04-11  21701230  1610612745  2017-18       2772      Trevor Ariza
43124 2018-04-11  21701230  1610612745  2017-18     201601  Luc Mbah a Moute

In [11]:
df_merged = pd.concat([df_bsa_gdgitispip, df_inactive_gdgitispip]).drop_duplicates().reset_index(drop=True)
p(df_merged)

(334767, 6)

        game_date   game_id     team_id   season  PLAYER_ID            player
0      2009-10-27  20900001  1610612739  2009-10     2544.0      LeBron James
1      2009-10-27  20900001  1610612739  2009-10     2760.0  Anderson Varejao
2      2009-10-27  20900001  1610612739  2009-10      406.0  Shaquille O'Neal
3      2009-10-27  20900001  1610612739  2009-10     1515.0    Anthony Parker
4      2009-10-27  20900001  1610612739  2009-10     2590.0       Mo Williams
334762 2018-04-11  21701230  1610612758  2017-18   202697.0     Iman Shumpert
334763 2018-04-11  21701230  1610612745  2017-18   203900.0      Markel Brown
334764 2018-04-11  21701230  1610612745  2017-18   201583.0     Ryan Anderson
334765 2018-04-11  21701230  1610612745  2017-18     2772.0      Trevor Ariza
334766 2018-04-11  21701230  1610612745  2017-18   201601.0  Luc Mbah a Moute

In [12]:
df_merged.sort_values('game_date', inplace=True)

In [13]:
p(df_merged)

(334767, 6)

        game_date   game_id     team_id   season  PLAYER_ID             player
0      2009-10-27  20900001  1610612739  2009-10     2544.0       LeBron James
69     2009-10-27  20900003  1610612745  2009-10   201978.0     Chase Budinger
68     2009-10-27  20900003  1610612745  2009-10   200822.0  Pops Mensah-Bonsu
67     2009-10-27  20900003  1610612745  2009-10     2431.0     David Andersen
66     2009-10-27  20900003  1610612745  2009-10   201171.0        Carl Landry
291618 2018-06-08  41700404  1610612739  2017-18   202684.0   Tristan Thompson
291617 2018-06-08  41700404  1610612739  2017-18   201567.0         Kevin Love
291616 2018-06-08  41700404  1610612739  2017-18     2544.0       LeBron James
291628 2018-06-08  41700404  1610612739  2017-18   203903.0    Jordan Clarkson
291641 2018-06-08  41700404  1610612744  2017-18  1627775.0      Patrick McCaw

In [14]:
df_merged.reset_index(drop=True, inplace=True)

In [15]:
p(df_merged)

(334767, 6)

        game_date   game_id     team_id   season  PLAYER_ID             player
0      2009-10-27  20900001  1610612739  2009-10     2544.0       LeBron James
1      2009-10-27  20900003  1610612745  2009-10   201978.0     Chase Budinger
2      2009-10-27  20900003  1610612745  2009-10   200822.0  Pops Mensah-Bonsu
3      2009-10-27  20900003  1610612745  2009-10     2431.0     David Andersen
4      2009-10-27  20900003  1610612745  2009-10   201171.0        Carl Landry
334762 2018-06-08  41700404  1610612739  2017-18   202684.0   Tristan Thompson
334763 2018-06-08  41700404  1610612739  2017-18   201567.0         Kevin Love
334764 2018-06-08  41700404  1610612739  2017-18     2544.0       LeBron James
334765 2018-06-08  41700404  1610612739  2017-18   203903.0    Jordan Clarkson
334766 2018-06-08  41700404  1610612744  2017-18  1627775.0      Patrick McCaw

In [16]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334767 entries, 0 to 334766
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   game_date  334767 non-null  datetime64[ns]
 1   game_id    334767 non-null  int64
 2   team_id    334767 non-null  int64
 3   season     334767 non-null  object
 4   PLAYER_ID  334767 non-null  float64
 5   player     334767 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 15.3+ MB

In [17]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '15game_date_game_id_team_id_season_player_id_player_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_merged.to_csv(datapath_df, index=False)