In [30]:
import pandas as pd

In [31]:
#game dates and stats
df = pd.DataFrame({'a':[1, 2, 3, 4, 5, 6], 'b':[1, 2, 3, 4, 0, 0]})
df

   a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  0
5  6  0

In [32]:
#injury dates
df2 = pd.DataFrame({'a':[1, 2.5, 3, 4, 5, 9], 'b':[1, 2, 3, 4, 5, 6]})
df2

     a  b
0  1.0  1
1  2.5  2
2  3.0  3
3  4.0  4
4  5.0  5
5  9.0  6

In [33]:
pd.merge(df.a.drop_duplicates(), df2, on='a', how='inner')

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/reshape/merge.py:1123: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation
  warnings.warn(

   a  b
0  1  1
1  3  3
2  4  4
3  5  5

In [34]:
pd.merge(df2.a, df, on='a', how='inner')

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/reshape/merge.py:1113: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation
  warnings.warn(

     a  b
0  1.0  1
1  3.0  3
2  4.0  4
3  5.0  0