In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
!conda install -c conda-forge fuzzywuzzy -y

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

In [3]:
import pandas as pd
import numpy as np
from fuzzywuzzy import process, fuzz

import os

ramen = pd.read_csv(os.path.join('..', 'processed_data', '6injuries_2010-11.csv'))
ramen.head()

    game_date     Team     team_id            player   game_id
0  2010-10-26  Blazers  1610612757   Elliot Williams  21000002
1  2010-10-26  Blazers  1610612757         Greg Oden  21000002
2  2010-10-26  Blazers  1610612757    Joel Przybilla  21000002
3  2010-10-26  Celtics  1610612738     Avery Bradley  21000001
4  2010-10-26  Celtics  1610612738  Kendrick Perkins  21000001

In [4]:
ramen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1678 entries, 0 to 1677
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_date  1678 non-null   object
 1   Team       1678 non-null   object
 2   team_id    1678 non-null   int64
 3   player     1678 non-null   object
 4   game_id    1678 non-null   int64
dtypes: int64(2), object(3)
memory usage: 65.7+ KB

In [5]:
ramen = ramen.applymap(str)
ramen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1678 entries, 0 to 1677
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   game_date  1678 non-null   object
 1   Team       1678 non-null   object
 2   team_id    1678 non-null   object
 3   player     1678 non-null   object
 4   game_id    1678 non-null   object
dtypes: object(5)
memory usage: 65.7+ KB

In [6]:
for col in ramen[['game_date', 'Team', 'team_id', 'player', 'game_id']]:
    ramen[col] = ramen[col].str.strip()
    print('Number of unique values in ' + str(col) +': ' + str(ramen[col].nunique()))

Number of unique values in game_date: 180
Number of unique values in Team: 30
Number of unique values in team_id: 29
Number of unique values in player: 384
Number of unique values in game_id: 911

In [7]:
unique_brand = ramen['player'].unique().tolist()
sorted(unique_brand)[:20]

['A.J. Price',
 'Aaron Brooks',
 'Aaron Gray',
 'Acie Law',
 'Al Harrington',
 'Al Horford',
 'Al Thornton',
 'Alex Ajinca',
 'Alonzo Gee',
 "Amar'e Stoudemire",
 'Amir Johnson',
 'Anderson Varejao',
 'Andray Blatche',
 'Andre Iguodala',
 'Andrea Bargnani',
 'Andrei Kirilenko',
 'Andres Nocioni',
 'Andrew Bogut',
 'Andrew Bynum',
 'Andris Biedrins']

In [8]:
process.extract('A.J. Price', unique_brand, scorer=fuzz.token_sort_ratio)

[('A.J. Price', 100),
 ('J.J. Redick', 63),
 ('Paul Pierce', 60),
 ('Maurice Ager', 57),
 ('D.J. White', 56)]

In [9]:
process.extract('Aaron Brooks', unique_brand, scorer=fuzz.token_sort_ratio)

[('Aaron Brooks', 100),
 ('Aaron Gray', 64),
 ('Rajon Rondo', 61),
 ('Jamario Moon', 58),
 ('Jose Calderon', 56)]

In [10]:
process.extract(sorted(unique_brand)[2], unique_brand, scorer=fuzz.token_sort_ratio)

[('Aaron Gray', 100),
 ('Aaron Brooks', 64),
 ('Ray Allen', 63),
 ('Ryan Anderson', 61),
 ('Baron Davis', 57)]

In [11]:
process.extract(sorted(unique_brand)[3], unique_brand, scorer=fuzz.token_sort_ratio)

[('Acie Law', 100),
 ('Gani Lawal', 67),
 ('Kelenna Azubuike', 50),
 ('Shawn Marion', 50),
 ('Zaza Pachulia', 48)]

In [12]:
process.extract(sorted(unique_brand)[4], unique_brand, scorer=fuzz.token_sort_ratio)

[('Al Harrington', 100),
 ('Al Thornton', 75),
 ('Arron Afflalo', 62),
 ('Marcus Thornton', 57),
 ('Daniel Orton', 56)]

In [13]:
process.extract(sorted(unique_brand)[5], unique_brand, scorer=fuzz.token_set_ratio)

[('Al Horford', 100),
 ('Al Thornton', 67),
 ('Daniel Orton', 55),
 ('Al Harrington', 52),
 ('Jerryd Bayless', 50)]

In [14]:
process.extract(sorted(unique_brand)[6], unique_brand, scorer=fuzz.token_set_ratio)

[('Al Thornton', 100),
 ('Marcus Thornton', 84),
 ('Al Harrington', 75),
 ('Daniel Orton', 70),
 ('Al Horford', 67)]

In [15]:
for player_ in sorted(unique_brand):
    print(player_)
    print(process.extract(player_, unique_brand, scorer=fuzz.token_set_ratio)[:2])

A.J. Price
[('A.J. Price', 100), ('Ronnie Price', 71)]
Aaron Brooks
[('Aaron Brooks', 100), ('Aaron Gray', 67)]
Aaron Gray
[('Aaron Gray', 100), ('Aaron Brooks', 67)]
Acie Law
[('Acie Law', 100), ('Gani Lawal', 67)]
Al Harrington
[('Al Harrington', 100), ('Al Thornton', 75)]
Al Horford
[('Al Horford', 100), ('Al Thornton', 67)]
Al Thornton
[('Al Thornton', 100), ('Marcus Thornton', 84)]
Alex Ajinca
[('Alex Ajinca', 100), ('Austin Daye', 55)]
Alonzo Gee
[('Alonzo Gee', 100), ('Danny Green', 57)]
Amar'e Stoudemire
[("Amar'e Stoudemire", 100), ('Martell Webster', 56)]
Amir Johnson
[('Amir Johnson', 100), ('Armon Johnson', 80)]
Anderson Varejao
[('Anderson Varejao', 100), ('Ryan Anderson', 76)]
Andray Blatche
[('Andray Blatche', 100), ('Luther Head', 56)]
Andre Iguodala
[('Andre Iguodala', 100), ('DeAndre Jordan', 64)]
Andrea Bargnani
[('Andrea Bargnani', 100), ('Andres Nocioni', 62)]
Andrei Kirilenko
[('Andrei Kirilenko', 100), ('Andris Biedrins', 65)]
Andres Nocioni
[('Andres Nocioni', 100), ('Andrea Bargnani', 62)]
Andrew Bogut
[('Andrew Bogut', 100), ('Andrew Bynum', 75)]
Andrew Bynum
[('Andrew Bynum', 100), ('Andrew Bogut', 75)]
Andris Biedrins
[('Andris Biedrins', 100), ('Kendrick Perkins', 65)]
Andy Rautins
[('Andy Rautins', 100), ('Andris Biedrins', 59)]
Antawn Jamison
[('Antawn Jamison', 100), ('Dahntay Jones', 59)]
Anthony Carter
[('Anthony Carter', 100), ('Anthony Parker', 86)]
Anthony Morrow
[('Anthony Morrow', 100), ('Anthony Parker', 71)]
Anthony Parker
[('Anthony Parker', 100), ('Tony Parker', 88)]
Anthony Randolph
[('Anthony Randolph', 100), ('Zach Randolph', 76)]
Anthony Tolliver
[('Anthony Tolliver', 100), ('Anthony Carter', 73)]
Antoine Wright
[('Antoine Wright', 100), ('Brandan Wright', 71)]
Antonio McDyess
[('Antonio McDyess', 100), ('James Anderson', 55)]
Armon Johnson
[('Armon Johnson', 100), ('Amir Johnson', 80)]
Arron Afflalo
[('Arron Afflalo', 100), ('Al Harrington', 62)]
Austin Daye
[('Austin Daye', 100), ('Alex Ajinca', 55)]
Avery Bradley
[('Avery Bradley', 100), ('Rodney Carney', 62)]
B.J. Mullens
[('B.J. Mullens', 100), ('C.J. Miles', 70)]
Baron Davis
[('Baron Davis', 100), ('Ed Davis', 77)]
Ben Uzoh
[('Ben Uzoh', 100), ('Beno Udrih', 67)]
Ben Wallace
[('Ben Wallace', 100), ('Gerald Wallace', 78)]
Beno Udrih
[('Beno Udrih', 100), ('Ben Uzoh', 67)]
Bill Walker
[('Bill Walker', 100), ('Charlie Bell', 61)]
Brad Miller
[('Brad Miller', 100), ('Mike Miller', 71)]
Brandan Wright
[('Brandan Wright', 100), ('Antoine Wright', 71)]
Brandon Bass
[('Brandon Bass', 100), ('Brandon Roy', 78)]
Brandon Jennings
[('Brandon Jennings', 100), ('Brandon Roy', 78)]
Brandon Roy
[('Brandon Roy', 100), ('Brandon Jennings', 78)]
Brandon Rush
[('Brandon Rush', 100), ('Brandon Roy', 78)]
Brendan Haywood
[('Brendan Haywood', 100), ('Gordon Hayward', 62)]
Brian Cardinal
[('Brian Cardinal', 100), ('Brian Scalabrine', 73)]
Brian Cook
[('Brian Cook', 100), ('Brian Scalabrine', 67)]
Brian Scalabrine
[('Brian Scalabrine', 100), ('Brian Cardinal', 73)]
Brian Skinner
[('Brian Skinner', 100), ('Brian Scalabrine', 69)]
C.J. Miles
[('C.J. Miles', 100), ('B.J. Mullens', 70)]
Carlos Arroyo
[('Carlos Arroyo', 100), ('Carlos Boozer', 69)]
Carlos Boozer
[('Carlos Boozer', 100), ('Carlos Arroyo', 69)]
Carlos Delfino
[('Carlos Delfino', 100), ('Carlos Boozer', 63)]
Carmelo Anthony
[('Carmelo Anthony', 100), ('Anthony Carter', 83)]
Caron Butler
[('Caron Butler', 100), ("Da'Sean Butler", 69)]
Cartier Martin
[('Cartier Martin', 100), ('Vince Carter', 69)]
Channing Frye
[('Channing Frye', 100), ('Matt Janning', 56)]
Charlie Bell
[('Charlie Bell', 100), ('Charlie Villanueva', 74)]
Charlie Villanueva
[('Charlie Villanueva', 100), ('Charlie Bell', 74)]
Chase Budinger
[('Chase Budinger', 100), ("Da'Sean Butler", 57)]
Chauncey Billups
[('Chauncey Billups', 100), ('Charlie Bell', 57)]
Chris Andersen
[('Chris Andersen', 100), ('David Andersen', 73)]
Chris Bosh
[('Chris Bosh', 100), ('Chris Douglas-Roberts', 67)]
Chris Douglas-Roberts
[('Chris Douglas-Roberts', 100), ('Toney Douglas', 70)]
Chris Duhon
[('Chris Duhon', 100), ('Chris Quinn', 73)]
Chris Kaman
[('Chris Kaman', 100), ('Manny Harris', 70)]
Chris Paul
[('Chris Paul', 100), ('Chris Douglas-Roberts', 67)]
Chris Quinn
[('Chris Quinn', 100), ('Chris Duhon', 73)]
Chris Wilcox
[('Chris Wilcox', 100), ('Chris Bosh', 67)]
Christian Eyenga
[('Christian Eyenga', 100), ('Chris Quinn', 59)]
Chuck Hayes
[('Chuck Hayes', 100), ('Kurt Thomas', 45)]
Cole Aldrich
[('Cole Aldrich', 100), ('Derrick Rose', 58)]
Corey Brewer
[('Corey Brewer', 100), ('Ronnie Brewer', 72)]
Corey Maggette
[('Corey Maggette', 100), ('Courtney Lee', 62)]
Courtney Lee
[('Courtney Lee', 100), ('Corey Maggette', 62)]
Craig Brackins
[('Craig Brackins', 100), ('Craig Smith', 62)]
Craig Smith
[('Craig Smith', 100), ('Ish Smith', 71)]
D.J. White
[('D.J. White', 100), ('Terrico White', 71)]
Da'Sean Butler
[("Da'Sean Butler", 100), ('Rasual Butler', 74)]
DaJuan Summers
[('DaJuan Summers', 100), ('Damion James', 54)]
Daequan Cook
[('Daequan Cook', 100), ('Brian Cook', 64)]
Dahntay Jones
[('Dahntay Jones', 100), ('Antawn Jamison', 59)]
Damien Wilkins
[('Damien Wilkins', 100), ('Deron Williams', 64)]
Damion James
[('Damion James', 100), ('James Anderson', 69)]
Dan Gadzuric
[('Dan Gadzuric', 100), ('Maurice Evans', 64)]
Daniel Gibson
[('Daniel Gibson', 100), ('Taj Gibson', 75)]
Daniel Orton
[('Daniel Orton', 100), ('Daniel Gibson', 72)]
Danilo Gallinari
[('Danilo Gallinari', 100), ('Daniel Gibson', 62)]
Danny Granger
[('Danny Granger', 100), ('Danny Green', 75)]
Danny Green
[('Danny Green', 100), ('Danny Granger', 75)]
Dante Cunningham
[('Dante Cunningham', 100), ('Matt Janning', 57)]
Darius Songaila
[('Darius Songaila', 100), ('Glen Davis', 56)]
Darko Milicic
[('Darko Milicic', 100), ('Deron Williams', 52)]
Darrell Arthur
[('Darrell Arthur', 100), ('DeMarre Carroll', 62)]
Darren Collison
[('Darren Collison', 100), ('Nick Collison', 76)]
David Andersen
[('David Andersen', 100), ('Chris Andersen', 73)]
David Lee
[('David Lee', 100), ('David West', 74)]
David West
[('David West', 100), ('David Lee', 74)]
DeAndre Jordan
[('DeAndre Jordan', 100), ('Jordan Hill', 71)]
DeJuan Blair
[('DeJuan Blair', 100), ("Da'Sean Butler", 62)]
DeMarre Carroll
[('DeMarre Carroll', 100), ('Matt Carroll', 74)]
DeSagana Diop
[('DeSagana Diop', 100), ('David Andersen', 52)]
Delonte West
[('Delonte West', 100), ('David West', 57)]
Deron Williams
[('Deron Williams', 100), ('Mo Williams', 84)]
Derrick Brown
[('Derrick Brown', 100), ('Derrick Rose', 80)]
Derrick Caracter
[('Derrick Caracter', 100), ('Derrick Rose', 74)]
Derrick Favors
[('Derrick Favors', 100), ('Derrick Rose', 77)]
Derrick Rose
[('Derrick Rose', 100), ('Derrick Brown', 80)]
Devin Ebanks
[('Devin Ebanks', 100), ('Devin Harris', 67)]
Devin Harris
[('Devin Harris', 100), ('Devin Ebanks', 67)]
Dexter Pittman
[('Dexter Pittman', 100), ('Quincy Pondexter', 60)]
Didier Mbenga
[('Didier Mbenga', 100), ('Jodie Meeks', 50)]
Dirk Nowitzki
[('Dirk Nowitzki', 100), ('Andres Nocioni', 52)]
Dominic McGuire
[('Dominic McGuire', 100), ('Dominique Jones', 53)]
Dominique Jones
[('Dominique Jones', 100), ('Solomon Jones', 64)]
Drew Gooden
[('Drew Gooden', 100), ('Greg Oden', 70)]
Dwight Howard
[('Dwight Howard', 100), ('Josh Howard', 71)]
Dwyane Wade
[('Dwyane Wade', 100), ('Kwame Brown', 55)]
Ed Davis
[('Ed Davis', 100), ('Glen Davis', 78)]
Eddy Curry
[('Eddy Curry', 100), ('Stephen Curry', 67)]
Eduardo Najera
[('Eduardo Najera', 100), ('Gary Neal', 52)]
Ekpe Udoh
[('Ekpe Udoh', 100), ('Ben Uzoh', 59)]
Elliot Williams
[('Elliot Williams', 100), ('Mo Williams', 84)]
Eric Gordon
[('Eric Gordon', 100), ('Gordon Hayward', 71)]
Erick Dampier
[('Erick Dampier', 100), ('Derrick Caracter', 62)]
Ersan Ilyasova
[('Ersan Ilyasova', 100), ('Deron Williams', 57)]
Etan Thomas
[('Etan Thomas', 100), ('Kurt Thomas', 73)]
Francisco Elson
[('Francisco Elson', 100), ('Francisco Garcia', 75)]
Francisco Garcia
[('Francisco Garcia', 100), ('Francisco Elson', 75)]
Gani Lawal
[('Gani Lawal', 100), ('Acie Law', 67)]
Garret Siler
[('Garret Siler', 100), ('Garrett Temple', 69)]
Garrett Temple
[('Garrett Temple', 100), ('Garret Siler', 69)]
Gary Neal
[('Gary Neal', 100), ("Jermaine O'Neal", 62)]
George Hill
[('George Hill', 100), ('Paul George', 73)]
Gerald Henderson Jr.
[('Gerald Henderson Jr.', 100), ('Ryan Anderson', 62)]
Gerald Wallace
[('Gerald Wallace', 100), ('Ben Wallace', 78)]
Gilbert Arenas
[('Gilbert Arenas', 100), ('Garret Siler', 62)]
Glen Davis
[('Glen Davis', 100), ('Ed Davis', 78)]
Goran Dragic
[('Goran Dragic', 100), ('Eric Gordon', 70)]
Gordon Hayward
[('Gordon Hayward', 100), ('Eric Gordon', 71)]
Grant Hill
[('Grant Hill', 100), ('Jordan Hill', 76)]
Greg Oden
[('Greg Oden', 100), ('Drew Gooden', 70)]
Greivis Vasquez
[('Greivis Vasquez', 100), ('Maurice Evans', 50)]
Hamady N'Diaye

[("Hamady N'Diaye", 100), ('Dahntay Jones', 52)]
Hamed Haddadi
[('Hamed Haddadi', 100), ('Ed Davis', 57)]
Hasheem Thabeet
[('Hasheem Thabeet', 100), ('Steve Nash', 56)]
Hassan Whiteside
[('Hassan Whiteside', 100), ('Wes Johnson', 52)]
Hilton Armstrong
[('Hilton Armstrong', 100), ('Armon Johnson', 62)]
Ian Mahinmi
[('Ian Mahinmi', 100), ('Kevin Martin', 61)]
Ish Smith
[('Ish Smith', 100), ('Josh Smith', 84)]
J.J. Hickson
[('J.J. Hickson', 100), ('Taj Gibson', 63)]
J.J. Redick
[('J.J. Redick', 100), ('A.J. Price', 59)]
JaVale McGee
[('JaVale McGee', 100), ('Jamaal Magloire', 59)]
Jamaal Magloire
[('Jamaal Magloire', 100), ('JaVale McGee', 59)]
Jamal Crawford
[('Jamal Crawford', 100), ('Jordan Crawford', 76)]
Jamario Moon
[('Jamario Moon', 100), ('O.J. Mayo', 60)]
Jameer Nelson
[('Jameer Nelson', 100), ('LeBron James', 64)]
James Anderson
[('James Anderson', 100), ('LeBron James', 77)]
James Posey
[('James Posey', 100), ('James Anderson', 62)]
Jannero Pargo
[('Jannero Pargo', 100), ('Anderson Varejao', 62)]
Jared Jeffries
[('Jared Jeffries', 100), ('Jeff Adrien', 64)]
Jason Collins
[('Jason Collins', 100), ('Sherron Collins', 79)]
Jason Kapono
[('Jason Kapono', 100), ('Jason Thompson', 69)]
Jason Kidd
[('Jason Kidd', 100), ('Jason Williams', 67)]
Jason Maxiell
[('Jason Maxiell', 100), ('Jason Williams', 67)]
Jason Richardson
[('Jason Richardson', 100), ('Quentin Richardson', 77)]
Jason Smith
[('Jason Smith', 100), ('Joe Smith', 80)]
Jason Thompson
[('Jason Thompson', 100), ('Jason Kapono', 69)]
Jason Williams
[('Jason Williams', 100), ('Mo Williams', 84)]
Jeff Adrien
[('Jeff Adrien', 100), ('Jeff Green', 76)]
Jeff Foster
[('Jeff Foster', 100), ('Jeff Green', 57)]
Jeff Green
[('Jeff Green', 100), ('Jeff Adrien', 76)]
Jeremy Evans
[('Jeremy Evans', 100), ('Jeremy Lin', 75)]
Jeremy Lin
[('Jeremy Lin', 100), ('Jeremy Evans', 75)]
Jermaine O'Neal
[("Jermaine O'Neal", 100), ('Jermaine Taylor', 80)]
Jermaine Taylor
[('Jermaine Taylor', 100), ("Jermaine O'Neal", 80)]
Jerry Stackhouse
[('Jerry Stackhouse', 100), ('Derrick Rose', 57)]
Jerryd Bayless
[('Jerryd Bayless', 100), ('Jeremy Evans', 54)]
Jianlian Yi
[('Jianlian Yi', 100), ('Julian Wright', 58)]
Joakim Noah
[('Joakim Noah', 100), ('Jameer Nelson', 50)]
Jodie Meeks
[('Jodie Meeks', 100), ('Devin Ebanks', 52)]
Joe Alexander
[('Joe Alexander', 100), ('Jose Calderon', 69)]
Joe Johnson
[('Joe Johnson', 100), ('Wes Johnson', 82)]
Joe Smith
[('Joe Smith', 100), ('Josh Smith', 84)]
Joel Przybilla
[('Joel Przybilla', 100), ('Zabian Dowdell', 57)]
Joey Dorsey
[('Joey Dorsey', 100), ('Toney Douglas', 58)]
Joey Graham
[('Joey Graham', 100), ('Stephen Graham', 71)]
John Lucas III
[('John Lucas III', 100), ('John Wall', 62)]
John Salmons
[('John Salmons', 100), ('Solomon Jones', 72)]
John Wall
[('John Wall', 100), ('John Wallace', 86)]
John Wallace
[('John Wallace', 100), ('John Wall', 86)]
Jon Brockman
[('Jon Brockman', 100), ('Jordan Farmar', 56)]
Jonas Jerebko
[('Jonas Jerebko', 100), ('Joe Johnson', 58)]
Jonny Flynn
[('Jonny Flynn', 100), ('Tony Allen', 57)]
Jordan Crawford
[('Jordan Crawford', 100), ('Jamal Crawford', 76)]
Jordan Farmar
[('Jordan Farmar', 100), ('Jordan Crawford', 71)]
Jordan Hill
[('Jordan Hill', 100), ('Grant Hill', 76)]
Jose Barea
[('Jose Barea', 100), ('Joe Alexander', 61)]
Jose Calderon
[('Jose Calderon', 100), ('Joe Alexander', 69)]
Josh Howard
[('Josh Howard', 100), ('Juwan Howard', 71)]
Josh McRoberts
[('Josh McRoberts', 100), ('Chris Bosh', 58)]
Josh Powell
[('Josh Powell', 100), ('John Wall', 70)]
Josh Smith
[('Josh Smith', 100), ('Ish Smith', 84)]
Julian Wright
[('Julian Wright', 100), ('Antoine Wright', 67)]
Juwan Howard
[('Juwan Howard', 100), ('Josh Howard', 71)]
Kelenna Azubuike
[('Kelenna Azubuike', 100), ('Acie Law', 50)]
Kendrick Perkins
[('Kendrick Perkins', 100), ('Andris Biedrins', 65)]
Kenyon Martin
[('Kenyon Martin', 100), ('Kevin Martin', 80)]
Kevin Durant
[('Kevin Durant', 100), ('Kevin Garnett', 72)]
Kevin Garnett
[('Kevin Garnett', 100), ('Kevin Durant', 72)]
Kevin Love
[('Kevin Love', 100), ('Kevin Seraphin', 67)]
Kevin Martin
[('Kevin Martin', 100), ('Kenyon Martin', 80)]
Kevin Seraphin
[('Kevin Seraphin', 100), ('Kevin Durant', 69)]
Keyon Dooling
[('Keyon Dooling', 100), ('Yao Ming', 57)]
Kirk Hinrich
[('Kirk Hinrich', 100), ('Richard Hamilton', 57)]
Kosta Koufos
[('Kosta Koufos', 100), ('Jerry Stackhouse', 50)]
Kris Humphries
[('Kris Humphries', 100), ('Ronnie Price', 54)]
Kurt Thomas
[('Kurt Thomas', 100), ('Etan Thomas', 73)]
Kwame Brown
[('Kwame Brown', 100), ('Derrick Brown', 62)]
Kyle Lowry
[('Kyle Lowry', 100), ('Leon Powe', 53)]
Kyrylo Fesenko
[('Kyrylo Fesenko', 100), ('Raymond Felton', 50)]
LaMarcus Aldridge
[('LaMarcus Aldridge', 100), ('Marquis Daniels', 56)]
Lance Stephenson
[('Lance Stephenson', 100), ('Stephen Jackson', 65)]
Larry Sanders
[('Larry Sanders', 100), ('Carlos Arroyo', 62)]
Lazar Hayward
[('Lazar Hayward', 100), ('Gordon Hayward', 70)]
LeBron James
[('LeBron James', 100), ('James Anderson', 77)]
Leandro Barbosa
[('Leandro Barbosa', 100), ('Brandon Bass', 59)]
Leon Powe
[('Leon Powe', 100), ('Jose Calderon', 64)]
Lester Hudson
[('Lester Hudson', 100), ('Luther Head', 58)]
Linas Kleiza
[('Linas Kleiza', 100), ('Elliot Williams', 52)]
Lou Amundson
[('Lou Amundson', 100), ('Brandon Roy', 61)]
Lou Williams
[('Lou Williams', 100), ('Mo Williams', 87)]
Luc Mbah a Moute
[('Luc Mbah a Moute', 100), ('Samuel Dalembert', 50)]
Luis Scola
[('Luis Scola', 100), ('Monta Ellis', 57)]
Luke Babbitt
[('Luke Babbitt', 100), ('Luke Walton', 61)]
Luke Harangody
[('Luke Harangody', 100), ('Luke Ridnour', 62)]
Luke Ridnour
[('Luke Ridnour', 100), ('Luke Harangody', 62)]
Luke Walton
[('Luke Walton', 100), ('Luke Babbitt', 61)]
Luther Head
[('Luther Head', 100), ('Lester Hudson', 58)]
Magnum Rolle
[('Magnum Rolle', 100), ('Will Bynum', 55)]
Malik Allen
[('Malik Allen', 100), ('Ray Allen', 71)]
Manny Harris
[('Manny Harris', 100), ('Chris Kaman', 70)]
Manu Ginobili
[('Manu Ginobili', 100), ('Marc Gasol', 52)]
Marc Gasol
[('Marc Gasol', 100), ('Marcus Banks', 64)]
Marco Belinelli
[('Marco Belinelli', 100), ('Bill Walker', 54)]
Marcus Banks
[('Marcus Banks', 100), ('Marcus Thornton', 67)]
Marcus Camby
[('Marcus Camby', 100), ('Marcus Banks', 67)]
Marcus Thornton
[('Marcus Thornton', 100), ('Al Thornton', 84)]
Mario Chalmers
[('Mario Chalmers', 100), ('Mario West', 67)]
Mario West
[('Mario West', 100), ('David West', 70)]
Marquis Daniels
[('Marquis Daniels', 100), ('Marcus Banks', 67)]
Martell Webster
[('Martell Webster', 100), ('Mario West', 64)]
Marvin Williams
[('Marvin Williams', 100), ('Mo Williams', 84)]
Matt Barnes
[('Matt Barnes', 100), ('Matt Bonner', 73)]
Matt Bonner
[('Matt Bonner', 100), ('Matt Barnes', 73)]
Matt Carroll
[('Matt Carroll', 100), ('DeMarre Carroll', 74)]
Matt Janning
[('Matt Janning', 100), ('Matt Bonner', 61)]
Maurice Ager
[('Maurice Ager', 100), ('Maurice Evans', 74)]
Maurice Evans
[('Maurice Evans', 100), ('Maurice Ager', 74)]
Mehmet Okur
[('Mehmet Okur', 100), ('Nazr Mohammed', 50)]
Melvin Ely
[('Melvin Ely', 100), ('Jeremy Lin', 60)]
Michael Beasley
[('Michael Beasley', 100), ('Michael Redd', 74)]
Michael Redd
[('Michael Redd', 100), ('Michael Beasley', 74)]
Mickael Pietrus
[('Mickael Pietrus', 100), ('Mike Miller', 62)]
Mike Conley Jr.
[('Mike Conley Jr.', 100), ('Mike Dunleavy Jr.', 80)]
Mike Dunleavy Jr.
[('Mike Dunleavy Jr.', 100), ('Mike Conley Jr.', 80)]
Mike Miller
[('Mike Miller', 100), ('Brad Miller', 71)]
Mo Williams
[('Mo Williams', 100), ('Lou Williams', 87)]
Monta Ellis
[('Monta Ellis', 100), ('Jason Collins', 58)]
Morris Peterson
[('Morris Peterson', 100), ('Patrick Patterson', 62)]
Mustafa Shakur
[('Mustafa Shakur', 100), ('Samardo Samuels', 48)]
Nate Robinson
[('Nate Robinson', 100), ('Robin Lopez', 58)]
Nazr Mohammed
[('Nazr Mohammed', 100), ('Lazar Hayward', 54)]
Nenad Krstic
[('Nenad Krstic', 100), ('Christian Eyenga', 57)]
Nene Hilario
[('Nene Hilario', 100), ('Manny Harris', 58)]
Nick Collison
[('Nick Collison', 100), ('Darren Collison', 76)]
Nick Young
[('Nick Young', 100), ('Nick Collison', 61)]
Nicolas Batum
[('Nicolas Batum', 100), ('Will Bynum', 52)]
Nikola Pekovic
[('Nikola Pekovic', 100), ('Kendrick Perkins', 53)]
O.J. Mayo
[('O.J. Mayo', 100), ('Roger Mason Jr.', 64)]
Omer Asik
[('Omer Asik', 100), ('Omri Casspi', 70)]
Omri Casspi
[('Omri Casspi', 100), ('Omer Asik', 70)]
Orien Greene
[('Orien Greene', 100), ('Greg Oden', 67)]
Othyus Jeffers
[('Othyus Jeffers', 100), ('Pooh Jeter', 58)]
Pape Sy
[('Pape Sy', 100), ('Tony Parker', 56)]
Patrick Patterson
[('Patrick Patterson', 100), ('Morris Peterson', 62)]
Patty Mills
[('Patty Mills', 100), ('Paul Millsap', 70)]
Paul George
[('Paul George', 100), ('George Hill', 73)]
Paul Millsap
[('Paul Millsap', 100), ('Patty Mills', 70)]
Paul Pierce
[('Paul Pierce', 100), ('Paul George', 73)]
Peja Stojakovic
[('Peja Stojakovic', 100), ('Nikola Pekovic', 48)]
Pooh Jeter
[('Pooh Jeter', 100), ('Othyus Jeffers', 58)]
Pops Mensah-Bonsu
[('Pops Mensah-Bonsu', 100), ('James Posey', 50)]
Quentin Richardson
[('Quentin Richardson', 100), ('Jason Richardson', 77)]
Quincy Pondexter

[('Quincy Pondexter', 100), ('Dexter Pittman', 60)]
Quinton Ross
[('Quinton Ross', 100), ('Anthony Morrow', 54)]
Raja Bell
[('Raja Bell', 100), ('Charlie Bell', 62)]
Rajon Rondo
[('Rajon Rondo', 100), ('Brandon Roy', 64)]
Randy Foye
[('Randy Foye', 100), ('Ryan Gomes', 60)]
Rashard Lewis
[('Rashard Lewis', 100), ('Dwight Howard', 54)]
Rasual Butler
[('Rasual Butler', 100), ("Da'Sean Butler", 74)]
Ray Allen
[('Ray Allen', 100), ('Tony Allen', 74)]
Raymond Felton
[('Raymond Felton', 100), ('Wayne Ellington', 62)]
Reggie Evans
[('Reggie Evans', 100), ('Tyreke Evans', 75)]
Reggie Williams
[('Reggie Williams', 100), ('Mo Williams', 84)]
Renaldo Balkman
[('Renaldo Balkman', 100), ('Brian Cardinal', 55)]
Richard Hamilton
[('Richard Hamilton', 100), ('Jason Richardson', 69)]
Robert Vaden
[('Robert Vaden', 100), ('Greg Oden', 57)]
Robin Lopez
[('Robin Lopez', 100), ('Nate Robinson', 58)]
Rodney Carney
[('Rodney Carney', 100), ('Rodney Stuckey', 74)]
Rodney Stuckey
[('Rodney Stuckey', 100), ('Rodney Carney', 74)]
Rodrigue Beaubois
[('Rodrigue Beaubois', 100), ('Craig Brackins', 52)]
Roger Mason Jr.
[('Roger Mason Jr.', 100), ('O.J. Mayo', 64)]
Ronnie Brewer
[('Ronnie Brewer', 100), ('Ronnie Price', 72)]
Ronnie Price
[('Ronnie Price', 100), ('Ronnie Brewer', 72)]
Ronny Turiaf
[('Ronny Turiaf', 100), ('Aaron Gray', 55)]
Roy Hibbert
[('Roy Hibbert', 100), ('Brandon Roy', 55)]
Rudy Fernandez
[('Rudy Fernandez', 100), ('Rudy Gay', 67)]
Rudy Gay
[('Rudy Gay', 100), ('Rudy Fernandez', 67)]
Ryan Anderson
[('Ryan Anderson', 100), ('Anderson Varejao', 76)]
Ryan Gomes
[('Ryan Gomes', 100), ('Ryan Hollins', 64)]
Ryan Hollins
[('Ryan Hollins', 100), ('Jason Collins', 72)]
Samardo Samuels
[('Samardo Samuels', 100), ('Samuel Dalembert', 65)]
Samuel Dalembert
[('Samuel Dalembert', 100), ('Samardo Samuels', 65)]
Sasha Vujacic
[('Sasha Vujacic', 100), ('Sebastian Telfair', 47)]
Sean Marks
[('Sean Marks', 100), ('Shawn Marion', 64)]
Sebastian Telfair
[('Sebastian Telfair', 100), ('Jermaine Taylor', 50)]
Semih Erden
[('Semih Erden', 100), ('Joe Smith', 60)]
Shaquille O'Neal
[("Shaquille O'Neal", 100), ("Jermaine O'Neal", 65)]
Shaun Livingston
[('Shaun Livingston', 100), ('Wayne Ellington', 65)]
Shawn Marion
[('Shawn Marion', 100), ('Sean Marks', 64)]
Shawne Williams
[('Shawne Williams', 100), ('Mo Williams', 84)]
Shelden Williams
[('Shelden Williams', 100), ('Mo Williams', 84)]
Sherron Collins
[('Sherron Collins', 100), ('Jason Collins', 79)]
Solomon Alabi
[('Solomon Alabi', 100), ('Solomon Jones', 70)]
Solomon Jones
[('Solomon Jones', 100), ('John Salmons', 72)]
Sonny Weems
[('Sonny Weems', 100), ('Wes Johnson', 64)]
Spencer Hawes
[('Spencer Hawes', 100), ('Chris Andersen', 52)]
Stephen Curry
[('Stephen Curry', 100), ('Stephen Graham', 70)]
Stephen Graham
[('Stephen Graham', 100), ('Joey Graham', 71)]
Stephen Jackson
[('Stephen Jackson', 100), ('Stephen Curry', 70)]
Steve Blake
[('Steve Blake', 100), ('Steve Novak', 73)]
Steve Nash
[('Steve Nash', 100), ('Steve Novak', 76)]
Steve Novak
[('Steve Novak', 100), ('Steve Nash', 76)]
Sundiata Gaines
[('Sundiata Gaines', 100), ('Andre Iguodala', 55)]
T.J. Ford
[('T.J. Ford', 100), ('D.J. White', 59)]
Taj Gibson
[('Taj Gibson', 100), ('Daniel Gibson', 75)]
Tayshaun Prince
[('Tayshaun Prince', 100), ('Shawn Marion', 59)]
Terrence Williams
[('Terrence Williams', 100), ('Mo Williams', 84)]
Terrico White
[('Terrico White', 100), ('D.J. White', 71)]
Thabo Sefolosha
[('Thabo Sefolosha', 100), ('Josh Smith', 48)]
Theo Ratliff
[('Theo Ratliff', 100), ('Craig Smith', 52)]
Tiago Splitter
[('Tiago Splitter', 100), ('Tony Battie', 48)]
Tim Duncan
[('Tim Duncan', 100), ('Kevin Durant', 55)]
Timofey Mozgov
[('Timofey Mozgov', 100), ('Toney Douglas', 52)]
Toney Douglas
[('Toney Douglas', 100), ('Chris Douglas-Roberts', 70)]
Tony Allen
[('Tony Allen', 100), ('Ray Allen', 74)]
Tony Battie
[('Tony Battie', 100), ('Tony Allen', 67)]
Tony Parker
[('Tony Parker', 100), ('Anthony Parker', 88)]
Tracy McGrady
[('Tracy McGrady', 100), ('Troy Murphy', 58)]
Trevor Ariza
[('Trevor Ariza', 100), ('Trevor Booker', 67)]
Trevor Booker
[('Trevor Booker', 100), ('Trevor Ariza', 67)]
Trey Johnson
[('Trey Johnson', 100), ('Joe Johnson', 78)]
Troy Murphy
[('Troy Murphy', 100), ('Tracy McGrady', 58)]
Ty Lawson
[('Ty Lawson', 100), ('Jason Smith', 60)]
Tyler Hansbrough
[('Tyler Hansbrough', 100), ('Anthony Tolliver', 50)]
Tyreke Evans
[('Tyreke Evans', 100), ('Reggie Evans', 75)]
Tyrus Thomas
[('Tyrus Thomas', 100), ('Etan Thomas', 71)]
Tyson Chandler
[('Tyson Chandler', 100), ('Wilson Chandler', 83)]
Udonis Haslem
[('Udonis Haslem', 100), ('John Salmons', 56)]
Vince Carter
[('Vince Carter', 100), ('Cartier Martin', 69)]
Von Wafer
[('Von Wafer', 100), ('Kwame Brown', 60)]
Wayne Ellington
[('Wayne Ellington', 100), ('Shaun Livingston', 65)]
Wes Johnson
[('Wes Johnson', 100), ('Joe Johnson', 82)]
Will Bynum
[('Will Bynum', 100), ('Andrew Bynum', 67)]
Willie Warren
[('Willie Warren', 100), ('Terrence Williams', 67)]
Wilson Chandler
[('Wilson Chandler', 100), ('Tyson Chandler', 83)]
Xavier Henry
[('Xavier Henry', 100), ('Anthony Parker', 54)]
Yao Ming
[('Yao Ming', 100), ('Keyon Dooling', 57)]
Zabian Dowdell
[('Zabian Dowdell', 100), ('Joel Przybilla', 57)]
Zach Randolph
[('Zach Randolph', 100), ('Anthony Randolph', 76)]
Zaza Pachulia
[('Zaza Pachulia', 100), ('Chris Kaman', 50)]
Zydrunas Ilgauskas
[('Zydrunas Ilgauskas', 100), ('Marcus Banks', 47)]

In [16]:
#process.extract('Acecook', unique_brand, scorer=fuzz.token_set_ratio)

In [17]:
#process.extract("Chef Nic's Noodles", unique_brand, scorer=fuzz.token_set_ratio)

In [18]:
#process.extract('Chorip Dong', unique_brand, scorer=fuzz.token_set_ratio)

In [19]:
#Create tuples of brand names, matched brand names, and the score
score_sort = [(x,) + i
             for x in unique_brand 
             for i in process.extract(x, unique_brand,     scorer=fuzz.token_sort_ratio)]
#Create a dataframe from the tuples
similarity_sort = pd.DataFrame(score_sort, columns=['brand_sort','match_sort','score_sort'])
similarity_sort.head()

        brand_sort       match_sort  score_sort
0  Elliot Williams  Elliot Williams         100
1  Elliot Williams     Lou Williams          81
2  Elliot Williams      Mo Williams          77
3  Elliot Williams   Deron Williams          76
4  Elliot Williams  Reggie Williams          73

In [20]:
similarity_sort['sorted_brand_sort'] = np.minimum(similarity_sort['brand_sort'], similarity_sort['match_sort'])
similarity_sort.head()

        brand_sort       match_sort  score_sort sorted_brand_sort
0  Elliot Williams  Elliot Williams         100   Elliot Williams
1  Elliot Williams     Lou Williams          81   Elliot Williams
2  Elliot Williams      Mo Williams          77   Elliot Williams
3  Elliot Williams   Deron Williams          76    Deron Williams
4  Elliot Williams  Reggie Williams          73   Elliot Williams

In [21]:
high_score_sort = similarity_sort[(similarity_sort['score_sort'] >= 80) &
                (similarity_sort['brand_sort'] !=  similarity_sort['match_sort']) &
                (similarity_sort['sorted_brand_sort'] != similarity_sort['match_sort'])]
high_score_sort = high_score_sort.drop('sorted_brand_sort',axis=1).copy()

In [22]:
high_score_sort.groupby(['brand_sort','score_sort']).agg(
                        {'match_sort': ', '.join}).sort_values(
                        ['score_sort'], ascending=False)

                                               match_sort
brand_sort      score_sort
Lou Williams    87                            Mo Williams
Anthony Carter  86                         Anthony Parker
John Wall       86                           John Wallace
Ish Smith       84                             Josh Smith
Joe Smith       84                             Josh Smith
Anthony Carter  83                        Carmelo Anthony
Tyson Chandler  83                        Wilson Chandler
Elliot Williams 81                           Lou Williams
Amir Johnson    80                          Armon Johnson
Deron Williams  80          Mo Williams, Shelden Williams
Jason Smith     80                              Joe Smith
Jason Williams  80                            Mo Williams
Jermaine O'Neal 80                        Jermaine Taylor
Kenyon Martin   80                           Kevin Martin
Mike Conley Jr. 80                      Mike Dunleavy Jr.

In [23]:
#Souper - Super - 91%
ramen[(ramen['plyer'] == 'Souper') | (ramen['player'] == 'Super')].sort_values(['player'])

KeyError: 'plyer'

In [ ]:
#Ped Chef - Red Chef - 88%
ramen[(ramen['player'] == 'Ped Chef') | (ramen['player'] == 'Red Chef')].sort_values(['player'])