In [1]:
# 0 <<<---->>> for first game of the season for stat difference

#####################################################

#create list of numeric columns to be used as stat differences: list_stats_diff

#create stat difference columns with associated game_id: df_gisd


#######################################################

# stat mean of team up to this point (diff of both teams) <<<---->>> have not had that matchup yet


#######################################################
# stat difference for matchup <<<---->>> have had matchup previously that season

In [2]:
# 0 <<<---->>> for first game of the season for stat difference


#game_date, team_id, season dataframe: df_gdtisgi
    
    #get game_date, team_id_away, season, game_id: df_gdtiagi
    
    #get game_date, team_id_home, season, game_id: df_gdtihgi
    
#order by game dates: df_gdtigi

#groupby season and get game_id for first instance of team_id

#get game_id's where first game for at least one of the teams

#################

#get number of unique matchups for each season



##################

#stat difference columns used for prediction for that game set to 0 because at least of the teams is having
#a first game




#####################################################

# difference of stat means prior to new matchup <<<---->>> not had this matchup & not first game for either team




#######################################################
# stat difference for matchup <<<---->>> have had matchup previously that season

In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [4]:
df = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv', ['game_date'])
df.sort_values('game_date', inplace=True)
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
15,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4
14,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [5]:
#df.info()

In [6]:
#pd.set_option('display.max_rows', 999)

In [7]:
# 0 <<<---->>> for first game of the season for stat difference


#game_date, team_id, season dataframe: df_gdtisgi
    
    #get game_date, team_id_away, season: df_gdtiagi
    
    #get game_date, team_id_home, season: df_gdtihgi
    
#order by game dates: df_gdtigi

#groupby season and get first instance of game_id's


#stat difference columns used for prediction for that game set to 0 because at least of the teams is having
#a first game

In [8]:
#game_date, team_id, season dataframe: df_gdtisgi
    
    #get game_date, team_id_away, season: df_gdtiagi
    
    #get game_date, team_id_home, season: df_gdtihgi
    
#order by game dates: df_gdtigi

df_gdtiasgi = df[['game_date', 'team_id_away', 'season', 'game_id']]
p(df_gdtiasgi)

(10266, 4)

       game_date  team_id_away   season   game_id
0     2010-10-26    1610612748  2010-11  21000001
1     2010-10-26    1610612756  2010-11  21000002
2     2010-10-26    1610612745  2010-11  21000003
15    2010-10-27    1610612749  2010-11  21000010
14    2010-10-27    1610612745  2010-11  21000015
10261 2018-05-28    1610612744  2017-18  41700317
10262 2018-05-31    1610612739  2017-18  41700401
10263 2018-06-03    1610612739  2017-18  41700402
10264 2018-06-06    1610612744  2017-18  41700403
10265 2018-06-08    1610612744  2017-18  41700404

In [9]:
df_gdtihsgi = df[['game_date', 'team_id_home', 'season', 'game_id']]
p(df_gdtihsgi)

(10266, 4)

       game_date  team_id_home   season   game_id
0     2010-10-26    1610612738  2010-11  21000001
1     2010-10-26    1610612757  2010-11  21000002
2     2010-10-26    1610612747  2010-11  21000003
15    2010-10-27    1610612740  2010-11  21000010
14    2010-10-27    1610612744  2010-11  21000015
10261 2018-05-28    1610612745  2017-18  41700317
10262 2018-05-31    1610612744  2017-18  41700401
10263 2018-06-03    1610612744  2017-18  41700402
10264 2018-06-06    1610612739  2017-18  41700403
10265 2018-06-08    1610612739  2017-18  41700404

In [10]:
df_gdtiahsgi = pd.concat([df_gdtiasgi.rename(columns={'team_id_away':'team_id'}), df_gdtihsgi.rename(columns={'team_id_home':'team_id'})])
p(df_gdtiahsgi)

(20532, 4)

       game_date     team_id   season   game_id
0     2010-10-26  1610612748  2010-11  21000001
1     2010-10-26  1610612756  2010-11  21000002
2     2010-10-26  1610612745  2010-11  21000003
15    2010-10-27  1610612749  2010-11  21000010
14    2010-10-27  1610612745  2010-11  21000015
10261 2018-05-28  1610612745  2017-18  41700317
10262 2018-05-31  1610612744  2017-18  41700401
10263 2018-06-03  1610612744  2017-18  41700402
10264 2018-06-06  1610612739  2017-18  41700403
10265 2018-06-08  1610612739  2017-18  41700404

In [11]:
#order by game dates: df_gdtigi

#groupby season and get first instance of game_id's


#stat difference columns used for prediction for that game set to 0 because at least of the teams is having
#a first game

In [12]:
#order by game dates: df_gdtigi
df_gdtiahsgi.sort_values('game_date', inplace=True)

In [13]:
p(df_gdtiahsgi)

(20532, 4)

       game_date     team_id   season   game_id
0     2010-10-26  1610612748  2010-11  21000001
1     2010-10-26  1610612756  2010-11  21000002
2     2010-10-26  1610612745  2010-11  21000003
1     2010-10-26  1610612757  2010-11  21000002
2     2010-10-26  1610612747  2010-11  21000003
10263 2018-06-03  1610612739  2017-18  41700402
10264 2018-06-06  1610612739  2017-18  41700403
10264 2018-06-06  1610612744  2017-18  41700403
10265 2018-06-08  1610612744  2017-18  41700404
10265 2018-06-08  1610612739  2017-18  41700404

In [14]:
#get list of unique team_id's
team_id_list = list(df_gdtiahsgi.team_id.drop_duplicates())
team_id_list

[1610612748,
 1610612756,
 1610612745,
 1610612757,
 1610612747,
 1610612738,
 1610612750,
 1610612746,
 1610612739,
 1610612751,
 1610612763,
 1610612742,
 1610612761,
 1610612760,
 1610612759,
 1610612743,
 1610612755,
 1610612744,
 1610612740,
 1610612765,
 1610612762,
 1610612754,
 1610612741,
 1610612752,
 1610612766,
 1610612737,
 1610612758,
 1610612749,
 1610612764,
 1610612753]

In [15]:
#first game_id of the season for (at least of of the team_id's)
df_sgi_first = pd.concat([df_gdtiahsgi[df_gdtiahsgi.team_id == ti].groupby('season').first()['game_id'].reset_index() for ti in team_id_list]).reset_index(drop=True)
p(df_sgi_first)

(240, 2)

      season   game_id
0    2010-11  21000001
1    2011-12  21100002
2    2012-13  21200002
3    2013-14  21300002
4    2014-15  21400007
235  2013-14  21300001
236  2014-15  21400001
237  2015-16  21500004
238  2016-17  21600004
239  2017-18  21700005

In [16]:
df_sgi_first = df_sgi_first.drop_duplicates().reset_index(drop=True)
p(df_sgi_first)

(138, 2)

      season   game_id
0    2010-11  21000001
1    2011-12  21100002
2    2012-13  21200002
3    2013-14  21300002
4    2014-15  21400007
133  2012-13  21200017
134  2017-18  21700007
135  2010-11  21000017
136  2015-16  21500004
137  2012-13  21200016

In [17]:
#create list of numeric columns to be used as stat differences: list_stats_diff

#create stat difference columns with associated game_id: df_gisd

In [18]:
#create list of numeric columns to be used as stat differences: list_stats_diff

In [19]:
df_numerics = df.select_dtypes('number')
p(df_numerics)

(10266, 94)

,game_id,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,spread_home,spread_away
0,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,2010,-8,8
1,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,2010,-14,14
2,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,2010,-2,2
15,21000010,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,2010,-4,4
14,21000015,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,2010,-4,4
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,2017,9,-9
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,2017,-10,10
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,2017,-19,19
10264,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,2017,8,-8
10265,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,2017,23,-23

In [20]:
list_numeric_col_names = list(df_numerics.columns)
list_numerics_giah = [i for i in list_numeric_col_names if i not in ['team_id_away', 'team_id_home', 'season_year']]
list_numerics_giah

['game_id',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'spread_home',
 'spread_away']

In [21]:
list_stats_h =  [i for i in list_numerics_giah if '_home' in i]
list_stats = [i.split('_home')[0] for i in list_stats_h]
list_stats

['E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread']

In [22]:
list_stat_diff = []
for stat in list_stats:
    list_stat_diff.append(stat + '_diff') 
list_stat_diff

['E_OFF_RATING_diff',
 'OFF_RATING_diff',
 'E_DEF_RATING_diff',
 'DEF_RATING_diff',
 'E_NET_RATING_diff',
 'NET_RATING_diff',
 'AST_PCT_diff',
 'AST_TOV_diff',
 'AST_RATIO_diff',
 'OREB_PCT_diff',
 'DREB_PCT_diff',
 'REB_PCT_diff',
 'E_TM_TOV_PCT_diff',
 'TM_TOV_PCT_diff',
 'EFG_PCT_diff',
 'TS_PCT_diff',
 'USG_PCT_diff',
 'E_USG_PCT_diff',
 'E_PACE_diff',
 'PACE_diff',
 'PACE_PER40_diff',
 'POSS_diff',
 'PIE_diff',
 'duration_minutes_diff',
 'w_pct_diff',
 'min_diff',
 'fgm_diff',
 'fga_diff',
 'fg_pct_diff',
 'fg3m_diff',
 'fg3a_diff',
 'fg3_pct_diff',
 'ftm_diff',
 'fta_diff',
 'ft_pct_diff',
 'oreb_diff',
 'dreb_diff',
 'reb_diff',
 'ast_diff',
 'stl_diff',
 'blk_diff',
 'tov_diff',
 'pf_diff',
 'pts_diff',
 'spread_diff']

In [23]:
df_sgi_first[list_stat_diff] = 0
p(df_sgi_first)

(138, 47)

,season,game_id,E_OFF_RATING_diff,OFF_RATING_diff,E_DEF_RATING_diff,DEF_RATING_diff,E_NET_RATING_diff,NET_RATING_diff,AST_PCT_diff,AST_TOV_diff,AST_RATIO_diff,OREB_PCT_diff,DREB_PCT_diff,REB_PCT_diff,E_TM_TOV_PCT_diff,TM_TOV_PCT_diff,EFG_PCT_diff,TS_PCT_diff,USG_PCT_diff,E_USG_PCT_diff,E_PACE_diff,PACE_diff,PACE_PER40_diff,POSS_diff,PIE_diff,duration_minutes_diff,w_pct_diff,min_diff,fgm_diff,fga_diff,fg_pct_diff,fg3m_diff,fg3a_diff,fg3_pct_diff,ftm_diff,fta_diff,ft_pct_diff,oreb_diff,dreb_diff,reb_diff,ast_diff,stl_diff,blk_diff,tov_diff,pf_diff,pts_diff,spread_diff
0,2010-11,21000001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2011-12,21100002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2012-13,21200002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2013-14,21300002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2014-15,21400007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
133,2012-13,21200017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
134,2017-18,21700007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
135,2010-11,21000017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
136,2015-16,21500004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
137,2012-13,21200016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [24]:
df_gisd = df_sgi_first
p(df_gisd)

(138, 47)

,season,game_id,E_OFF_RATING_diff,OFF_RATING_diff,E_DEF_RATING_diff,DEF_RATING_diff,E_NET_RATING_diff,NET_RATING_diff,AST_PCT_diff,AST_TOV_diff,AST_RATIO_diff,OREB_PCT_diff,DREB_PCT_diff,REB_PCT_diff,E_TM_TOV_PCT_diff,TM_TOV_PCT_diff,EFG_PCT_diff,TS_PCT_diff,USG_PCT_diff,E_USG_PCT_diff,E_PACE_diff,PACE_diff,PACE_PER40_diff,POSS_diff,PIE_diff,duration_minutes_diff,w_pct_diff,min_diff,fgm_diff,fga_diff,fg_pct_diff,fg3m_diff,fg3a_diff,fg3_pct_diff,ftm_diff,fta_diff,ft_pct_diff,oreb_diff,dreb_diff,reb_diff,ast_diff,stl_diff,blk_diff,tov_diff,pf_diff,pts_diff,spread_diff
0,2010-11,21000001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2011-12,21100002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2012-13,21200002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2013-14,21300002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2014-15,21400007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
133,2012-13,21200017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
134,2017-18,21700007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
135,2010-11,21000017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
136,2015-16,21500004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
137,2012-13,21200016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [25]:
#######################################################

# stat mean of team up to this point (diff of both teams) <<<---->>> have not had that matchup yet



#first time to have that matchup for the season and not first game for either team.

    #drop occurrences of the matchup's that already occured
        
        #get matchups where at least one team was having a first game of the season from df_gisd and df: df_matchup
        
        #remove those matchups from df by season (first game of season removed): df_fgsr
        
    #get first of matchups that have not occurred yet per season
        
        #get unique matchup, season pairs
    
        #for a given season, get a matchup and take the first occurrence with game_id

    
    
    #get mean per stat for each team up for the season prior to the game
    
        #combine game_id's collected so far
        
        #perform cma on nba team stats per season with omission of the current row
    

    
    #take the difference for each team stat for those first new matchups




#if we remove the matchup's that have already occurred per season and get the first matchup per season, does
# this give us the new matchup's per season, where each team has played at least one game???
    
#theoretically 435 matchup's possible from 30 teams

#expecting 200-400 new matchup's for team per season to take difference of stat means for???

In [26]:
# stat mean of team up to this point (diff of both teams) <<<---->>> have not had that matchup yet


#first time to have that matchup for the season and not first game for either team.

    #drop occurrences of the matchup's that already occured
        
        #get matchups where at least one team was having a first game of the season from df_gisd and df: df_matchup
        
        #remove those matchups from df by season (first game of season removed): df_fgsr

        
    #get first of matchups that have not occurred yet per season

In [27]:
#first time to have that matchup for the season and not first game for either team.

    #drop occurrences of the matchup's that already occured
        
        #get matchups where at least one team was having a first game of the season from df_gisd and df: df_ms
        
        #remove those matchups from df by season (first game of season removed): df_fgsr

In [28]:
p(df_sgi_first)

(138, 47)

,season,game_id,E_OFF_RATING_diff,OFF_RATING_diff,E_DEF_RATING_diff,DEF_RATING_diff,E_NET_RATING_diff,NET_RATING_diff,AST_PCT_diff,AST_TOV_diff,AST_RATIO_diff,OREB_PCT_diff,DREB_PCT_diff,REB_PCT_diff,E_TM_TOV_PCT_diff,TM_TOV_PCT_diff,EFG_PCT_diff,TS_PCT_diff,USG_PCT_diff,E_USG_PCT_diff,E_PACE_diff,PACE_diff,PACE_PER40_diff,POSS_diff,PIE_diff,duration_minutes_diff,w_pct_diff,min_diff,fgm_diff,fga_diff,fg_pct_diff,fg3m_diff,fg3a_diff,fg3_pct_diff,ftm_diff,fta_diff,ft_pct_diff,oreb_diff,dreb_diff,reb_diff,ast_diff,stl_diff,blk_diff,tov_diff,pf_diff,pts_diff,spread_diff
0,2010-11,21000001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2011-12,21100002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2012-13,21200002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2013-14,21300002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2014-15,21400007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
133,2012-13,21200017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
134,2017-18,21700007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
135,2010-11,21000017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
136,2015-16,21500004,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
137,2012-13,21200016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [29]:
df_sgi_first.game_id

0      21000001
1      21100002
2      21200002
3      21300002
4      21400007
5      21500008
6      21600004
7      21700005
8      21000002
9      21100014
10     21200010
11     21300015
12     21400013
13     21500014
14     21600012
15     21700012
16     21000003
17     21100008
18     21200006
19     21300009
20     21400003
21     21500010
22     21600013
23     21700002
24     21100016
25     21200012
26     21400015
27     21500015
28     21600002
29     21100003
30     21200003
31     21300003
32     21500017
33     21700016
34     21100001
35     21300006
36     21400006
37     21500005
38     21600006
39     21700001
40     21000009
41     21100011
42     21200023
43     21300010
44     21400009
45     21600009
46     21700011
47     21000016
48     21100005
49     21200011
50     21400020
51     21500016
52     21600017
53     21000004
54     21100009
55     21200001
56     21300004
57     21400018
58     21500002
59     21600001
60     21000005
61     21100006
62     21200029
63     21500006
64     21700004
65     21000008
66     21100013
67     21300013
68     21500011
69     21700008
70     21000012
71     21300012
72     21400002
73     21600005
74     21700009
75     21000007
76     21200004
77     21400008
78     21500009
79     21600007
80     21700014
81     21000011
82     21100004
83     21200014
84     21300014
85     21500013
86     21600011
87     21700015
88     21000013
89     21200008
90     21600003
91     21000014
92     21100012
93     21200005
94     21300016
95     21400011
96     21600010
97     21700010
98     21000006
99     21300005
100    21400005
101    21700006
102    21000015
103    21300017
104    21400014
105    21500003
106    21000010
107    21300011
108    21400001
109    21100010
110    21300007
111    21500001
112    21700003
113    21100022
114    21200009
115    21400012
116    21500007
117    21300001
118    21200007
119    21400010
120    21600015
121    21200020
122    21300008
123    21500012
124    21100007
125    21200015
126    21400004
127    21600008
128    21100018
129    21200018
130    21600014
131    21100015
132    21700013
133    21200017
134    21700007
135    21000017
136    21500004
137    21200016
Name: game_id, dtype: int64

In [30]:
df_ms = pd.merge(df_sgi_first.game_id, df, on='game_id', how='inner')[['matchup', 'season']]
p(df_ms)

(138, 2)

         matchup   season
0    BOS vs. MIA  2010-11
1    DAL vs. MIA  2011-12
2    BOS vs. MIA  2012-13
3    CHI vs. MIA  2013-14
4    MIA vs. WAS  2014-15
133  BOS vs. MIL  2012-13
134  BOS vs. MIL  2017-18
135  ORL vs. WAS  2010-11
136  ORL vs. WAS  2015-16
137  DEN vs. ORL  2012-13

In [31]:
#remove those matchups from df by season (first game of season removed): df_fgsr
df_temp = pd.merge(df_ms, df, on=['matchup', 'season'], how='outer', indicator=True)
p(df_temp)

(10266, 111)

,matchup,season,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season_year,wl_away,wl_home,spread_home,spread_away,_merge
0,BOS vs. MIA,2010-11,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010,L,W,-8,8,both
1,BOS vs. MIA,2010-11,21000118,2010-11-11,Celtics,BOS,Boston,240:00,0 days 04:00:00,Heat,MIA,Miami,240:00,0 days 04:00:00,120.4,121.7,115.0,116.3,5.4,5.4,0.558,2.00,19.0,0.268,0.700,0.481,12.903,13.0,0.601,0.622,1.0,0.196,93.02,92.0,76.67,92,0.512,240.0,115.0,116.3,120.4,121.7,-5.4,-5.4,0.500,1.29,14.7,0.300,0.732,0.519,15.047,15.2,0.521,0.594,1.0,0.198,93.02,92.0,76.67,92,0.488,240.0,1610612738,0.778,240,43,79,0.544,9,16,0.563,17,25,0.680000,9,26,35,24,5,0,10,30,112,1610612748,0.556,240,36,72,0.500,3,16,0.188,32,41,0.780488,11,26,37,18,4,4,14,22,107,Regular Season,2010,W,L,5,-5,both
2,BOS vs. MIA,2010-11,21000804,2011-02-13,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,89.0,93.2,95.2,97.7,-6.1,-4.5,0.548,1.00,14.4,0.304,0.773,0.533,18.454,19.3,0.439,0.487,1.0,0.194,90.72,87.5,72.92,88,0.465,240.0,95.2,97.7,89.0,93.2,6.1,4.5,0.633,1.27,16.2,0.227,0.696,0.467,16.794,17.2,0.451,0.510,1.0,0.193,90.72,87.5,72.92,87,0.535,240.0,1610612748,0.722,240,31,74,0.419,3,16,0.188,17,23,0.739130,9,32,41,17,3,3,15,21,82,1610612738,0.736,240,30,71,0.423,4,15,0.267,21,28,0.750000,9,31,40,19,6,1,13,22,85,Regular Season,2010,L,W,-3,3,both
3,BOS vs. MIA,2010-11,21001194,2011-04-10,Celtics,BOS,Boston,240:00,0 days 04:00:00,Heat,MIA,Miami,240:00,0 days 04:00:00,88.5,88.5,111.8,116.3,-23.3,-27.8,0.552,0.84,15.1,0.139,0.571,0.372,21.829,21.8,0.500,0.542,1.0,0.187,88.24,86.5,72.08,87,0.370,240.0,111.8,116.3,88.5,88.5,23.3,27.8,0.632,1.33,18.7,0.429,0.861,0.628,20.125,20.9,0.547,0.578,1.0,0.195,88.24,86.5,72.08,86,0.630,240.0,1610612738,0.688,240,29,64,0.453,6,13,0.462,13,16,0.812500,3,23,26,16,9,2,14,18,77,1610612748,0.700,240,38,75,0.507,6,18,0.333,18,26,0.692308,15,27,42,24,9,4,17,17,100,Regular Season,2010,L,W,-23,23,both
4,BOS vs. MIA,2010-11,41000211,2011-05-01,Celtics,BOS,Boston,240:00,0 days 04:00:00,Heat,MIA,Miami,240:00,0 days 04:00:00,100.1,98.9,104.1,108.8,-4.0,-9.9,0.563,1.29,15.7,0.178,0.000,0.000,15.569,15.4,0.507,0.543,1.0,0.198,92.50,91.0,75.83,91,0.448,240.0,104.1,108.8,100.1,98.9,4.0,9.9,0.531,0.94,14.5,0.000,0.822,0.000,18.931,19.8,0.537,0.603,1.0,0.190,92.50,91.0,75.83,91,0.552,240.0,1610612738,0.800,240,32,75,0.427,12,24,0.500,14,18,0.777778,7,32,39,18,7,3,13,24,90,1610612748,0.833,240,32,68,0.471,9,19,0.474,26,32,0.812500,5,34,39,17,7,8,16,21,99,Playoffs,2010,L,W,-9,9,both
10261,MIA vs. OKC,2017-18,21701206,2018-04-09,Thunder,OKC,Oklahoma City,240:00,0 days 04:00:00,Heat,MIA,Miami,240:00,0 days 04:00:00,114.2,116.2,92.9,93.9,21.3,22.2,0.600,2.10,16.3,0.216,0.780,0.495,9.929,10.1,0.519,0.588,1.0,0.199,100.44,99.0,82.50,99,0.611,240.0,92.9,93.9,114.2,116.2,-21.3,-22.2,0.525,1.40,16.3,0.220,0.784,0.505,14.976,15.2,0.489,0.499,1.0,0.200,100.44,99.0,82.50,99,0.389,240.0,1610612760,0.580,240,35,81,0.432,14,35,0.400,31,38,0.815789,7,36,43,21,9,4,9,15,115,1610612748,0.531,240,40,87,0.460,5,22,0.227,8,14,0.571429,8,35,43,21,6,4,15,24,93,Regular Season,2017,W,L,22,-22,right_only
10262,IND vs. LAC,2017-18,21701078,2018-03-23,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,Pacers,IND,Indiana,240:00,0 days 04:00:00,114.1,114.3,115.8,118.5,-1.7,-4.2,0.571,1.71,20.0,0.171,0.620,0.435,15.358,15.4,0.618,0.633,1.0,0.200,92.66,91.5,76.25,91,0.479,240.0,115.8,118.5,114.1,114.3,1.7,4.2,0.581,2.78,18.8,0.380,0.829,0.565,9.558,9.8,0.522,0.550,1.0,0.200,92.66,91.5,76.25,92,0.521,240.0,1610612746,0.528,240,42,76,0.553,10,26,0.385,10,14,0.714286,5,27,32,24,4,3,14,20,104,1610612754,0.575,240,43,93,0.462,11,31,0.355,12,14,0.857143,14,28,42,25,6,2,9,16,109,Regular Season,2017,L,W,-5,5,right_only
10263,IND vs. LAC,2017-18,21701146,2018-04-01,Pacers,IND,Indiana,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,121.7,123.3,116.6,115.6,5.0,7.8,0.548,2.09,17.8,0.422,0.683,0.547,12.056,12.2,0.552,0.583,1.0,0.198,90.20,90.0,75.00,90,0.532,240.0,116.6,115.6,121.7,123.3,-5.0,-7.8,0.571,1.85,19.2,0.317,0.578,0.453,14.581,14.4,0.567,0.590,1.0,0.200,90.20,90.0,75.00,90,0.468,240.0,1610612754,0.597,240,42,86,0.488,11,28,0.393,16,21,0.761905,15,25,40,23,8,4,10,12,111,1610612746,0.532,240,42,82,0.512,9,25,0.360,11,14,0.785714,12,24,36,24,6,6,13,19,104,Regular Season,2017,W,L,7,-7,right_only
10264,GSW vs. IND,2017-18,21701114,2018-03-27,Pacers,IND,Indiana,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,101.9,102.2,90.0,90.0,11.9,12.2,0.564,1.83,18.3,0.222,0.642,0.449,13.292,13.3,0.519,0.533,1.0,0.195,90.12,90.0,75.00,90,0.572,240.0,90.0,90.0,101.9,102.2,-11.9,-12.2,0.600,1.24,16.4,0.358,0.778,0.551,18.897,18.9,0.436,0.450,1.0,0.198,90.12,90.0,75.00,90,0.428,240.0,1610612754,0.587,240,39,81,0.481,6,21,0.286,8,12,0.666667,8,30,38,22,10,2,10,14,92,1610612744,0.730,240,35,86,0.407,5,17,0.294,6,9,0.666667,17,34,51,21,4,9,16,17,81,Regular Season,2017,W,L,11,-11,right_only
10265,GSW vs. IND,2017-18,21701175,2018-04-05,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Pacers,IND,Indiana,240:00,0 days 04:00:00,109.8,109.3,126.5,128.6,-16.7,-19.3,0.784,1.81,20.9,0.277,0.636,0.451,16.570,16.5,0.500,0.566,1.0,0.199,98.08,97.5,81.25,97,0.438,240.0,126.5,128.6,109.8,109.3,16.7,19.3,0.640,2.46,22.1,0.364,0.723,0.549,13.052,13.3,0.618,0.633,1.0,0.195,98.08,97.5,81.25,98,0.562,240.0,1610612744,0.722,240,37,83,0.446,9,29,0.310,23,24,0.958333,13,26,39,29,6,5,16,14,106,1610612754,0.595,240,50,93,0.538,15,29,0.517,11,15,0.733333,13,34,47,32,11,3,12,24,126,Regular Season,2017,L,W,-20,20,right_only

In [32]:
df_temp.value_counts('_merge')

_merge
right_only    9733
both           533
left_only        0
dtype: int64

In [33]:
df_fgsr = df_temp[df_temp._merge == 'right_only']
p(df_fgsr)

(9733, 111)

,matchup,season,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season_year,wl_away,wl_home,spread_home,spread_away,_merge
533,PHX vs. UTA,2010-11,21000018,2010-10-28,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Jazz,UTA,Utah,240:00,0 days 04:00:00,112.3,115.8,96.0,97.9,16.3,17.9,0.541,1.33,15.4,0.000,0.660,0.000,15.312,15.8,0.525,0.579,1.0,0.196,97.92,95.5,79.58,95,0.592,240.0,96.0,97.9,112.3,115.8,-16.3,-17.9,0.528,1.19,14.5,0.340,0.000,0.000,16.347,16.7,0.446,0.490,1.0,0.198,97.92,95.5,79.58,96,0.408,240.0,1610612756,0.500,240,37,80,0.463,10,26,0.385,26,34,0.764706,12,32,44,20,11,4,14,25,110,1610612762,0.000,240,36,84,0.429,3,13,0.231,19,27,0.703704,14,31,45,19,8,6,16,28,94,Regular Season,2010,W,L,16,-16,right_only
534,PHX vs. UTA,2010-11,21000795,2011-02-11,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Jazz,UTA,Utah,240:00,0 days 04:00:00,104.3,108.0,94.0,94.3,10.2,13.6,0.528,2.71,15.2,0.339,0.733,0.515,7.682,8.0,0.433,0.479,1.0,0.196,89.70,88.0,73.33,88,0.517,240.0,94.0,94.3,104.3,108.0,-10.2,-13.6,0.794,1.80,21.6,0.267,0.661,0.485,16.991,17.0,0.481,0.498,1.0,0.197,89.70,88.0,73.33,88,0.483,240.0,1610612756,0.510,240,36,89,0.404,5,23,0.217,18,23,0.782609,15,32,47,19,10,6,6,18,95,1610612762,0.564,240,34,78,0.436,7,17,0.412,8,12,0.666667,10,35,45,27,5,6,14,17,83,Regular Season,2010,W,L,12,-12,right_only
535,PHX vs. UTA,2010-11,21000822,2011-02-15,Jazz,UTA,Utah,240:00,0 days 04:00:00,Suns,PHX,Phoenix,240:00,0 days 04:00:00,99.3,106.3,102.5,106.3,-3.1,0.1,0.605,1.28,17.2,0.319,0.775,0.529,17.703,18.9,0.494,0.545,1.0,0.193,100.62,95.5,79.58,95,0.473,240.0,102.5,106.3,99.3,106.3,3.1,-0.1,0.667,1.26,19.0,0.225,0.681,0.471,19.084,19.8,0.575,0.610,1.0,0.195,100.62,95.5,79.58,96,0.527,240.0,1610612762,0.554,240,38,83,0.458,6,14,0.429,19,22,0.863636,9,30,39,23,10,3,16,25,101,1610612756,0.509,240,36,73,0.493,12,29,0.414,18,24,0.750000,3,29,32,24,6,5,17,15,102,Regular Season,2010,L,W,-1,1,right_only
536,BOS vs. NYK,2010-11,21000023,2010-10-29,Knicks,NYK,New York,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,103.2,102.0,102.0,105.0,1.2,-3.0,0.649,2.40,18.3,0.000,0.627,0.000,10.217,10.1,0.488,0.521,1.0,0.200,100.40,99.5,82.92,99,0.473,240.0,102.0,105.0,103.2,102.0,-1.2,3.0,0.750,1.83,22.0,0.373,0.000,0.000,17.489,18.0,0.511,0.531,1.0,0.197,100.40,99.5,82.92,100,0.527,240.0,1610612752,0.500,240,37,85,0.435,9,27,0.333,18,27,0.666667,9,29,38,24,8,9,10,20,101,1610612738,0.667,240,44,91,0.484,5,16,0.313,12,18,0.666667,14,40,54,33,2,1,17,23,105,Regular Season,2010,L,W,-4,4,right_only
537,BOS vs. NYK,2010-11,21000368,2010-12-15,Celtics,BOS,Boston,240:00,0 days 04:00:00,Knicks,NYK,New York,240:00,0 days 04:00:00,121.3,122.9,115.5,119.6,5.9,3.3,0.578,2.00,19.4,0.317,0.707,0.512,13.369,13.5,0.564,0.619,1.0,0.200,98.84,96.5,80.42,96,0.551,240.0,115.5,119.6,121.3,122.9,-5.9,-3.3,0.442,1.12,14.8,0.293,0.683,0.488,16.926,17.5,0.586,0.627,1.0,0.196,98.84,96.5,80.42,97,0.449,240.0,1610612738,0.833,240,45,86,0.523,7,14,0.500,21,21,1.000000,11,28,39,26,11,2,13,19,118,1610612752,0.615,240,43,81,0.531,9,23,0.391,21,26,0.807692,9,26,35,19,5,5,17,18,116,Regular Season,2010,W,L,2,-2,right_only
10261,MIA vs. OKC,2017-18,21701206,2018-04-09,Thunder,OKC,Oklahoma City,240:00,0 days 04:00:00,Heat,MIA,Miami,240:00,0 days 04:00:00,114.2,116.2,92.9,93.9,21.3,22.2,0.600,2.10,16.3,0.216,0.780,0.495,9.929,10.1,0.519,0.588,1.0,0.199,100.44,99.0,82.50,99,0.611,240.0,92.9,93.9,114.2,116.2,-21.3,-22.2,0.525,1.40,16.3,0.220,0.784,0.505,14.976,15.2,0.489,0.499,1.0,0.200,100.44,99.0,82.50,99,0.389,240.0,1610612760,0.580,240,35,81,0.432,14,35,0.400,31,38,0.815789,7,36,43,21,9,4,9,15,115,1610612748,0.531,240,40,87,0.460,5,22,0.227,8,14,0.571429,8,35,43,21,6,4,15,24,93,Regular Season,2017,W,L,22,-22,right_only
10262,IND vs. LAC,2017-18,21701078,2018-03-23,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,Pacers,IND,Indiana,240:00,0 days 04:00:00,114.1,114.3,115.8,118.5,-1.7,-4.2,0.571,1.71,20.0,0.171,0.620,0.435,15.358,15.4,0.618,0.633,1.0,0.200,92.66,91.5,76.25,91,0.479,240.0,115.8,118.5,114.1,114.3,1.7,4.2,0.581,2.78,18.8,0.380,0.829,0.565,9.558,9.8,0.522,0.550,1.0,0.200,92.66,91.5,76.25,92,0.521,240.0,1610612746,0.528,240,42,76,0.553,10,26,0.385,10,14,0.714286,5,27,32,24,4,3,14,20,104,1610612754,0.575,240,43,93,0.462,11,31,0.355,12,14,0.857143,14,28,42,25,6,2,9,16,109,Regular Season,2017,L,W,-5,5,right_only
10263,IND vs. LAC,2017-18,21701146,2018-04-01,Pacers,IND,Indiana,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,121.7,123.3,116.6,115.6,5.0,7.8,0.548,2.09,17.8,0.422,0.683,0.547,12.056,12.2,0.552,0.583,1.0,0.198,90.20,90.0,75.00,90,0.532,240.0,116.6,115.6,121.7,123.3,-5.0,-7.8,0.571,1.85,19.2,0.317,0.578,0.453,14.581,14.4,0.567,0.590,1.0,0.200,90.20,90.0,75.00,90,0.468,240.0,1610612754,0.597,240,42,86,0.488,11,28,0.393,16,21,0.761905,15,25,40,23,8,4,10,12,111,1610612746,0.532,240,42,82,0.512,9,25,0.360,11,14,0.785714,12,24,36,24,6,6,13,19,104,Regular Season,2017,W,L,7,-7,right_only
10264,GSW vs. IND,2017-18,21701114,2018-03-27,Pacers,IND,Indiana,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,101.9,102.2,90.0,90.0,11.9,12.2,0.564,1.83,18.3,0.222,0.642,0.449,13.292,13.3,0.519,0.533,1.0,0.195,90.12,90.0,75.00,90,0.572,240.0,90.0,90.0,101.9,102.2,-11.9,-12.2,0.600,1.24,16.4,0.358,0.778,0.551,18.897,18.9,0.436,0.450,1.0,0.198,90.12,90.0,75.00,90,0.428,240.0,1610612754,0.587,240,39,81,0.481,6,21,0.286,8,12,0.666667,8,30,38,22,10,2,10,14,92,1610612744,0.730,240,35,86,0.407,5,17,0.294,6,9,0.666667,17,34,51,21,4,9,16,17,81,Regular Season,2017,W,L,11,-11,right_only
10265,GSW vs. IND,2017-18,21701175,2018-04-05,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Pacers,IND,Indiana,240:00,0 days 04:00:00,109.8,109.3,126.5,128.6,-16.7,-19.3,0.784,1.81,20.9,0.277,0.636,0.451,16.570,16.5,0.500,0.566,1.0,0.199,98.08,97.5,81.25,97,0.438,240.0,126.5,128.6,109.8,109.3,16.7,19.3,0.640,2.46,22.1,0.364,0.723,0.549,13.052,13.3,0.618,0.633,1.0,0.195,98.08,97.5,81.25,98,0.562,240.0,1610612744,0.722,240,37,83,0.446,9,29,0.310,23,24,0.958333,13,26,39,29,6,5,16,14,106,1610612754,0.595,240,50,93,0.538,15,29,0.517,11,15,0.733333,13,34,47,32,11,3,12,24,126,Regular Season,2017,L,W,-20,20,right_only

In [34]:
df_fgsr = df_fgsr.sort_values('game_date').reset_index(drop=True)
p(df_fgsr)

(9733, 111)

,matchup,season,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season_year,wl_away,wl_home,spread_home,spread_away,_merge
0,PHX vs. UTA,2010-11,21000018,2010-10-28,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Jazz,UTA,Utah,240:00,0 days 04:00:00,112.3,115.8,96.0,97.9,16.3,17.9,0.541,1.33,15.4,0.000,0.660,0.000,15.312,15.8,0.525,0.579,1.0,0.196,97.92,95.50,79.58,95,0.592,240.0,96.0,97.9,112.3,115.8,-16.3,-17.9,0.528,1.19,14.5,0.340,0.000,0.000,16.347,16.7,0.446,0.490,1.0,0.198,97.92,95.50,79.58,96,0.408,240.0,1610612756,0.5,240,37,80,0.463,10,26,0.385,26,34,0.764706,12,32,44,20,11,4,14,25,110,1610612762,0.000,240,36,84,0.429,3,13,0.231,19,27,0.703704,14,31,45,19,8,6,16,28,94,Regular Season,2010,W,L,16,-16,right_only
1,MIL vs. MIN,2010-11,21000026,2010-10-29,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Timberwolves,MIN,Minnesota,240:00,0 days 04:00:00,82.5,85.0,96.2,95.0,-13.6,-10.0,0.581,1.29,13.8,0.211,0.596,0.404,13.592,14.0,0.374,0.434,1.0,0.196,101.42,100.50,83.75,100,0.379,240.0,96.2,95.0,82.5,85.0,13.6,10.0,0.406,0.68,9.8,0.404,0.789,0.596,19.030,18.8,0.412,0.476,1.0,0.200,101.42,100.50,83.75,101,0.621,240.0,1610612749,0.0,240,31,87,0.356,3,20,0.150,20,25,0.800000,9,30,39,18,4,5,13,29,85,1610612750,0.500,240,32,85,0.376,6,22,0.273,26,36,0.722222,20,42,62,13,8,11,18,27,96,Regular Season,2010,L,W,-11,11,right_only
2,DEN vs. NOH,2010-11,21000027,2010-10-29,Nuggets,DEN,Denver,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,103.3,102.2,110.3,108.6,-7.0,-6.5,0.543,0.95,15.6,0.316,0.000,0.000,21.739,21.5,0.528,0.572,1.0,0.198,91.78,93.00,77.50,93,0.446,240.0,110.3,108.6,103.3,102.2,7.0,6.5,0.605,1.53,18.3,0.000,0.684,0.000,16.383,16.1,0.532,0.577,1.0,0.199,91.78,93.00,77.50,93,0.554,240.0,1610612743,0.5,240,35,72,0.486,6,15,0.400,19,25,0.760000,11,26,37,19,9,2,19,22,95,1610612740,1.000,240,38,77,0.494,6,17,0.353,19,24,0.791667,11,24,35,23,11,8,15,22,101,Regular Season,2010,L,W,-6,6,right_only
3,MIA vs. ORL,2010-11,21000025,2010-10-29,Magic,ORL,Orlando,240:00,0 days 04:00:00,Heat,MIA,Miami,240:00,0 days 04:00:00,76.1,78.7,105.6,109.1,-29.5,-30.4,0.238,0.31,4.8,0.255,0.000,0.000,17.399,18.0,0.333,0.417,1.0,0.194,91.42,88.50,73.75,89,0.245,240.0,105.6,109.1,76.1,78.7,29.5,30.4,0.515,1.42,13.9,0.000,0.745,0.000,13.204,13.6,0.463,0.517,1.0,0.198,91.42,88.50,73.75,88,0.755,240.0,1610612753,0.5,240,21,69,0.304,4,24,0.167,24,34,0.705882,8,32,40,5,5,3,14,20,70,1610612748,0.667,240,33,81,0.407,9,18,0.500,21,27,0.777778,14,37,51,17,6,5,12,27,96,Regular Season,2010,L,W,-26,26,right_only
4,GSW vs. LAC,2010-11,21000029,2010-10-29,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,90.9,95.8,111.8,113.5,-20.9,-17.8,0.531,1.00,13.0,0.316,0.707,0.480,16.986,17.9,0.416,0.469,1.0,0.195,98.78,95.50,79.58,95,0.342,240.0,111.8,113.5,90.9,95.8,20.9,17.8,0.744,1.78,23.1,0.293,0.684,0.520,18.465,18.8,0.617,0.616,1.0,0.195,98.78,95.50,79.58,96,0.658,240.0,1610612746,0.0,240,32,83,0.386,5,18,0.278,22,32,0.687500,14,26,40,17,7,1,16,16,91,1610612744,1.000,240,43,81,0.531,14,24,0.583,9,17,0.529412,9,37,46,32,8,7,17,25,109,Regular Season,2010,L,W,-18,18,right_only
9728,BOS vs. PHI,2017-18,41700215,2018-05-09,76ers,PHI,Philadelphia,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,111.3,108.7,112.8,112.9,-1.5,-4.1,0.650,1.53,18.8,0.318,0.712,0.531,16.892,16.5,0.537,0.586,1.0,0.199,100.84,102.00,85.00,103,0.514,240.0,112.8,112.9,111.3,108.7,1.5,4.1,0.474,1.64,13.6,0.288,0.682,0.469,10.887,10.9,0.488,0.553,1.0,0.200,100.84,102.00,85.00,101,0.486,240.0,1610612755,0.2,240,40,82,0.488,8,21,0.381,24,31,0.774194,12,36,48,26,5,6,16,31,112,1610612738,0.800,240,38,85,0.447,7,20,0.350,31,41,0.756098,13,26,39,18,12,3,10,24,114,Playoffs,2017,L,W,-2,2,right_only
9729,CLE vs. GSW,2017-18,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,0.0,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017,L,W,-10,10,right_only
9730,CLE vs. GSW,2017-18,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,0.0,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017,L,W,-19,19,right_only
9731,CLE vs. GSW,2017-18,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017,W,L,8,-8,right_only
9732,CLE vs. GSW,2017-18,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017,W,L,23,-23,right_only

In [35]:
#get first of matchups that have not occurred yet per season

    #get unique matchup, season pairs

In [36]:
df_fgsr_ms = df_fgsr[['matchup', 'season']].drop_duplicates().reset_index(drop=True)
p(df_fgsr_ms)

(3342, 2)

          matchup   season
0     PHX vs. UTA  2010-11
1     MIL vs. MIN  2010-11
2     DEN vs. NOH  2010-11
3     MIA vs. ORL  2010-11
4     GSW vs. LAC  2010-11
3337  SAS vs. WAS  2017-18
3338  LAC vs. MIL  2017-18
3339  IND vs. LAC  2017-18
3340  MIA vs. OKC  2017-18
3341  GSW vs. IND  2017-18

In [37]:
seasons_list = list(df_fgsr['season'].drop_duplicates())
seasons_list

['2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18']

In [38]:
#for a given season, get a matchup and take the first occurrence with game_id

game_id_list = []

for season_ in seasons_list:
    matchup_list = list(df_fgsr_ms[df_fgsr_ms.season == season_].matchup)
    for matchup_ in matchup_list:
        game_id_list.append(df_fgsr[['game_id', 'season', 'matchup']][(df_fgsr.season == season_) & (df_fgsr.matchup == matchup_)].groupby('season').first().reset_index()['game_id'][0])

In [39]:
print(len(game_id_list))
game_id_list

3342

[21000018,
 21000026,
 21000027,
 21000025,
 21000029,
 21000021,
 21000022,
 21000020,
 21000030,
 21000019,
 21000024,
 21000028,
 21000023,
 21000034,
 21000039,
 21000038,
 21000037,
 21000035,
 21000031,
 21000036,
 21000032,
 21000033,
 21000042,
 21000040,
 21000041,
 21000043,
 21000046,
 21000045,
 21000044,
 21000052,
 21000050,
 21000047,
 21000048,
 21000053,
 21000049,
 21000060,
 21000056,
 21000059,
 21000058,
 21000054,
 21000055,
 21000062,
 21000063,
 21000061,
 21000065,
 21000064,
 21000067,
 21000066,
 21000071,
 21000068,
 21000069,
 21000072,
 21000070,
 21000077,
 21000078,
 21000074,
 21000075,
 21000073,
 21000079,
 21000076,
 21000088,
 21000086,
 21000081,
 21000080,
 21000084,
 21000087,
 21000094,
 21000089,
 21000093,
 21000090,
 21000091,
 21000092,
 21000098,
 21000097,
 21000096,
 21000095,
 21000100,
 21000105,
 21000106,
 21000102,
 21000107,
 21000104,
 21000101,
 21000103,
 21000115,
 21000110,
 21000108,
 21000113,
 21000109,
 21000111,
 21000119,
 21000120,
 21000129,
 21000127,
 21000124,
 21000121,
 21000123,
 21000122,
 21000126,
 21000125,
 21000136,
 21000135,
 21000138,
 21000130,
 21000133,
 21000134,
 21000137,
 21000132,
 21000140,
 21000141,
 21000142,
 21000150,
 21000146,
 21000147,
 21000145,
 21000144,
 21000152,
 21000157,
 21000155,
 21000154,
 21000156,
 21000153,
 21000159,
 21000164,
 21000167,
 21000158,
 21000161,
 21000162,
 21000165,
 21000166,
 21000160,
 21000169,
 21000168,
 21000170,
 21000174,
 21000179,
 21000177,
 21000178,
 21000173,
 21000175,
 21000172,
 21000189,
 21000183,
 21000187,
 21000184,
 21000188,
 21000186,
 21000185,
 21000190,
 21000182,
 21000192,
 21000193,
 21000191,
 21000195,
 21000197,
 21000198,
 21000196,
 21000199,
 21000200,
 21000201,
 21000204,
 21000207,
 21000206,
 21000208,
 21000214,
 21000212,
 21000210,
 21000215,
 21000218,
 21000219,
 21000216,
 21000221,
 21000223,
 21000225,
 21000227,
 21000230,
 21000231,
 21000228,
 21000222,
 21000237,
 21000238,
 21000239,
 21000241,
 21000236,
 21000234,
 21000246,
 21000242,
 21000249,
 21000243,
 21000252,
 21000251,
 21000253,
 21000250,
 21000255,
 21000256,
 21000260,
 21000259,
 21000257,
 21000268,
 21000271,
 21000265,
 21000264,
 21000267,
 21000270,
 21000262,
 21000266,
 21000274,
 21000273,
 21000277,
 21000282,
 21000281,
 21000285,
 21000286,
 21000276,
 21000291,
 21000293,
 21000289,
 21000288,
 21000292,
 21000296,
 21000297,
 21000300,
 21000299,
 21000307,
 21000302,
 21000306,
 21000315,
 21000313,
 21000310,
 21000312,
 21000326,
 21000321,
 21000316,
 21000317,
 21000325,
 21000328,
 21000327,
 21000329,
 21000331,
 21000336,
 21000334,
 21000340,
 21000337,
 21000347,
 21000344,
 21000345,
 21000348,
 21000341,
 21000343,
 21000354,
 21000350,
 21000351,
 21000352,
 21000353,
 21000356,
 21000358,
 21000365,
 21000364,
 21000375,
 21000377,
 21000369,
 21000370,
 21000372,
 21000376,
 21000380,
 21000378,
 21000383,
 21000384,
 21000385,
 21000388,
 21000391,
 21000382,
 21000390,
 21000395,
 21000392,
 21000399,
 21000394,
 21000397,
 21000398,
 21000405,
 21000400,
 21000408,
 21000407,
 21000416,
 21000415,
 21000417,
 21000418,
 21000419,
 21000425,
 21000426,
 21000429,
 21000427,
 21000431,
 21000436,
 21000435,
 21000434,
 21000442,
 21000444,
 21000441,
 21000443,
 21000454,
 21000447,
 21000449,
 21000458,
 21000459,
 21000460,
 21000470,
 21000464,
 21000462,
 21000463,
 21000469,
 21000467,
 21000473,
 21000476,
 21000482,
 21000477,
 21000479,
 21000481,
 21000487,
 21000484,
 21000490,
 21000493,
 21000492,
 21000495,
 21000496,
 21000501,
 21000504,
 21000500,
 21000506,
 21000510,
 21000508,
 21000518,
 21000516,
 21000529,
 21000534,
 21000533,
 21000538,
 21000539,
 21000543,
 21000550,
 21000549,
 21000547,
 21000552,
 21000560,
 21000567,
 21000569,
 21000572,
 21000562,
 21000561,
 21000564,
 21000570,
 21000573,
 21000574,
 21000575,
 21000591,
 21000587,
 21000594,
 21000599,
 21000600,
 21000610,
 21000603,
 21000607,
 21000617,
 21000623,
 21000618,
 21000624,
 21000621,
 21000620,
 21000632,
 21000650,
 21000644,
 21000649,
 21000663,
 21000666,
 21000671,
 21000688,
 21000681,
 21000683,
 21000690,
 21000682,
 21000695,
 21000700,
 21000706,
 21000702,
 21000701,
 21000712,
 21000714,
 21000727,
 21000723,
 21000743,
 21000747,
 21000768,
 21000780,
 21000787,
 21000791,
 21000800,
 21000799,
 21000808,
 21000805,
 21000813,
 21000812,
 21000832,
 21000828,
 21000845,
 21000846,
 21000849,
 21000864,
 21000878,
 21000876,
 21000888,
 21000891,
 21000904,
 21000902,
 21000923,
 21000929,
 21000958,
 21000978,
 21001027,
 21100017,
 21100020,
 21100021,
 21100019,
 21100024,
 21100029,
 21100031,
 21100027,
 21100030,
 21100032,
 21100023,
 21100026,
 21100028,
 21100025,
 21100035,
 21100038,
 21100033,
 21100034,
 21100037,
 21100036,
 21100048,
 21100040,
 21100039,
 21100049,
 21100043,
 21100047,
 21100046,
 21100041,
 21100045,
 21100053,
 21100054,
 21100055,
 21100056,
 21100050,
 21100052,
 21100065,
 21100057,
 21100058,
 21100061,
 21100064,
 21100062,
 21100060,
 21100074,
 21100069,
 21100071,
 21100066,
 21100070,
 21100072,
 21100068,
 21100075,
 21100076,
 21100077,
 21100078,
 21100079,
 21100080,
 21100081,
 21100090,
 21100083,
 21100088,
 21100091,
 21100087,
 21100093,
 21100084,
 21100086,
 21100085,
 21100092,
 21100089,
 21100096,
 21100095,
 21100097,
 21100098,
 21100102,
 21100099,
 21100100,
 21100104,
 21100109,
 21100103,
 21100106,
 21100105,
 21100101,
 21100107,
 21100108,
 21100114,
 21100119,
 21100118,
 21100112,
 21100111,
 21100116,
 21100113,
 21100117,
 21100125,
 21100124,
 21100122,
 21100121,
 21100120,
 21100123,
 21100126,
 21100127,
 21100138,
 21100132,
 21100134,
 21100142,
 21100141,
 21100136,
 21100139,
 21100133,
 21100135,
 21100150,
 21100146,
 21100143,
 21100147,
 21100145,
 21100152,
 21100153,
 21100148,
 21100144,
 21100155,
 21100156,
 21100157,
 21100158,
 21100165,
 21100160,
 21100169,
 21100163,
 21100161,
 21100164,
 21100166,
 21100162,
 21100168,
 21100167,
 21100176,
 21100180,
 21100172,
 21100171,
 21100174,
 21100175,
 21100177,
 21100179,
 21100178,
 21100181,
 21100183,
 21100186,
 21100193,
 21100189,
 21100191,
 21100184,
 21100194,
 21100192,
 21100190,
 21100187,
 21100200,
 21100197,
 21100198,
 21100196,
 21100201,
 21100206,
 21100211,
 21100207,
 21100212,
 21100208,
 21100204,
 21100210,
 21100202,
 21100205,
 21100203,
 21100215,
 21100214,
 21100213,
 21100216,
 21100217,
 21100221,
 21100219,
 21100218,
 21100224,
 21100223,
 21100222,
 21100225,
 21100220,
 21100226,
 21100228,
 21100231,
 21100227,
 21100232,
 21100230,
 21100236,
 21100229,
 21100238,
 21100241,
 21100239,
 21100240,
 21100247,
 21100245,
 21100244,
 21100251,
 21100243,
 21100246,
 21100248,
 21100253,
 21100255,
 21100256,
 21100254,
 21100265,
 21100269,
 21100266,
 21100259,
 21100260,
 21100258,
 21100257,
 21100262,
 21100261,
 21100271,
 21100284,
 21100276,
 21100278,
 21100274,
 21100277,
 21100282,
 21100272,
 21100290,
 21100288,
 21100289,
 21100287,
 21100298,
 21100291,
 21100297,
 21100296,
 21100292,
 21100305,
 21100299,
 21100307,
 21100301,
 21100314,
 21100313,
 21100312,
 21100315,
 21100318,
 21100322,
 21100324,
 21100327,
 21100326,
 21100340,
 21100335,
 21100334,
 21100338,
 21100347,
 21100352,
 21100346,
 21100345,
 21100342,
 21100355,
 21100356,
 21100365,
 21100359,
 21100361,
 21100357,
 21100362,
 21100367,
 21100368,
 21100376,
 21100374,
 21100373,
 21100377,
 21100381,
 21100384,
 21100387,
 21100385,
 21100389,
 21100392,
 21100396,
 21100394,
 21100399,
 21100390,
 21100406,
 21100405,
 21100404,
 21100401,
 21100402,
 21100407,
 21100400,
 21100403,
 21100408,
 21100410,
 21100412,
 21100415,
 21100426,
 21100427,
 21100428,
 21100422,
 21100437,
 21100432,
 21100429,
 21100435,
 21100446,
 21100454,
 21100445,
 21100450,
 21100448,
 21100468,
 21100467,
 21100465,
 21100460,
 21100463,
 21100466,
 21100478,
 21100476,
 21100483,
 21100484,
 21100482,
 21100489,
 21100487,
 21100492,
 21100486,
 21100494,
 21100502,
 21100509,
 21100508,
 21100518,
 21100512,
 21100514,
 21100520,
 21100519,
 21100516,
 21100527,
 21100526,
 21100525,
 21100528,
 21100537,
 21100535,
 21100536,
 21100539,
 21100540,
 21100545,
 21100548,
 21100555,
 21100565,
 21100567,
 21100579,
 21100572,
 21100571,
 21100570,
 21100578,
 21100588,
 21100586,
 21100597,
 21100598,
 21100602,
 21100599,
 21100607,
 21100609,
 21100615,
 21100614,
 21100617,
 21100613,
 21100620,
 21100623,
 21100624,
 21100631,
 21100636,
 21100637,
 21100635,
 21100628,
 21100638,
 21100639,
 21100653,
 21100645,
 21100647,
 21100650,
 21100651,
 21100657,
 21100660,
 21100664,
 21100663,
 21100672,
 21100675,
 21100676,
 21100682,
 21100678,
 21100688,
 21100691,
 21100685,
 21100693,
 21100695,
 21100702,
 21100717,
 21100716,
 21100722,
 21100724,
 21100733,
 21100747,
 21100762,
 21100765,
 21100759,
 21100775,
 21100773,
 21100774,
 21100780,
 21100781,
 21100777,
 21100786,
 21100792,
 21100798,
 21100801,
 21100809,
 21100819,
 21100815,
 21100840,
 21100845,
 21100866,
 21100937,
 21100950,
 21100946,
 21100953,
 21100954,
 21100964,
 21100974,
 21100985,
 21100983,
 21200024,
 21200019,
 21200021,
 21200026,
 21200025,
 21200022,
 21200030,
 21200028,
 21200033,
 21200036,
 21200027,
 21200034,
 21200032,
 21200031,
 21200035,
 21200039,
 21200038,
 21200040,
 21200041,
 21200037,
 21200048,
 21200046,
 21200045,
 21200043,
 21200044,
 21200049,
 21200047,
 21200051,
 21200050,
 21200052,
 21200060,
 21200063,
 21200062,
 21200057,
 21200064,
 21200061,
 21200053,
 21200056,
 21200058,
 21200065,
 21200055,
 21200059,
 21200067,
 21200066,
 21200074,
 21200076,
 21200070,
 21200080,
 21200079,
 21200072,
 21200071,
 21200077,
 21200075,
 21200068,
 21200078,
 21200069,
 21200073,
 21200082,
 21200088,
 21200089,
 21200087,
 21200084,
 21200081,
 21200094,
 21200093,
 21200091,
 21200092,
 21200099,
 21200100,
 21200095,
 21200096,
 21200102,
 21200098,
 21200101,
 21200103,
 21200106,
 21200107,
 21200108,
 21200104,
 21200109,
 21200112,
 21200118,
 21200110,
 21200117,
 21200113,
 21200114,
 21200116,
 21200115,
 21200111,
 21200120,
 21200119,
 21200128,
 21200126,
 21200124,
 21200127,
 21200122,
 21200130,
 21200123,
 21200125,
 21200131,
 21200137,
 21200132,
 21200136,
 21200135,
 21200134,
 21200133,
 21200143,
 21200144,
 21200140,
 21200139,
 21200146,
 21200141,
 21200145,
 21200142,
 21200150,
 21200149,
 21200153,
 21200151,
 21200148,
 21200155,
 21200156,
 21200164,
 21200162,
 21200157,
 21200161,
 21200165,
 21200160,
 21200170,
 21200163,
 21200168,
 21200166,
 21200173,
 21200171,
 21200175,
 21200174,
 21200177,
 21200178,
 21200181,
 21200180,
 21200172,
 21200182,
 21200186,
 21200183,
 21200188,
 21200192,
 21200193,
 21200194,
 21200195,
 21200196,
 21200191,
 21200197,
 21200203,
 21200200,
 21200201,
 21200013,
 21200198,
 21200204,
 21200206,
 21200208,
 21200219,
 21200210,
 21200209,
 21200214,
 21200216,
 21200215,
 ...]

In [40]:
#get mean per stat for each team up for the season prior to the game

    #combine game_id's collected so far

    #perform cma on nba team stats per season with omission of the current row

        #what if a team has a repeated matchup before they have a new matchup??? then the stat cma should include
        # repeated matchups too??

In [41]:
#combine game_id's collected so far

game_id_first_list = list(df_sgi_first.game_id)
print(len(game_id_first_list))
game_id_first_list

138

[21000001,
 21100002,
 21200002,
 21300002,
 21400007,
 21500008,
 21600004,
 21700005,
 21000002,
 21100014,
 21200010,
 21300015,
 21400013,
 21500014,
 21600012,
 21700012,
 21000003,
 21100008,
 21200006,
 21300009,
 21400003,
 21500010,
 21600013,
 21700002,
 21100016,
 21200012,
 21400015,
 21500015,
 21600002,
 21100003,
 21200003,
 21300003,
 21500017,
 21700016,
 21100001,
 21300006,
 21400006,
 21500005,
 21600006,
 21700001,
 21000009,
 21100011,
 21200023,
 21300010,
 21400009,
 21600009,
 21700011,
 21000016,
 21100005,
 21200011,
 21400020,
 21500016,
 21600017,
 21000004,
 21100009,
 21200001,
 21300004,
 21400018,
 21500002,
 21600001,
 21000005,
 21100006,
 21200029,
 21500006,
 21700004,
 21000008,
 21100013,
 21300013,
 21500011,
 21700008,
 21000012,
 21300012,
 21400002,
 21600005,
 21700009,
 21000007,
 21200004,
 21400008,
 21500009,
 21600007,
 21700014,
 21000011,
 21100004,
 21200014,
 21300014,
 21500013,
 21600011,
 21700015,
 21000013,
 21200008,
 21600003,
 21000014,
 21100012,
 21200005,
 21300016,
 21400011,
 21600010,
 21700010,
 21000006,
 21300005,
 21400005,
 21700006,
 21000015,
 21300017,
 21400014,
 21500003,
 21000010,
 21300011,
 21400001,
 21100010,
 21300007,
 21500001,
 21700003,
 21100022,
 21200009,
 21400012,
 21500007,
 21300001,
 21200007,
 21400010,
 21600015,
 21200020,
 21300008,
 21500012,
 21100007,
 21200015,
 21400004,
 21600008,
 21100018,
 21200018,
 21600014,
 21100015,
 21700013,
 21200017,
 21700007,
 21000017,
 21500004,
 21200016]

In [42]:
game_id_list_first_matchups = game_id_first_list + game_id_list
print(len(game_id_list_first_matchups))
game_id_list_first_matchups

3480

[21000001,
 21100002,
 21200002,
 21300002,
 21400007,
 21500008,
 21600004,
 21700005,
 21000002,
 21100014,
 21200010,
 21300015,
 21400013,
 21500014,
 21600012,
 21700012,
 21000003,
 21100008,
 21200006,
 21300009,
 21400003,
 21500010,
 21600013,
 21700002,
 21100016,
 21200012,
 21400015,
 21500015,
 21600002,
 21100003,
 21200003,
 21300003,
 21500017,
 21700016,
 21100001,
 21300006,
 21400006,
 21500005,
 21600006,
 21700001,
 21000009,
 21100011,
 21200023,
 21300010,
 21400009,
 21600009,
 21700011,
 21000016,
 21100005,
 21200011,
 21400020,
 21500016,
 21600017,
 21000004,
 21100009,
 21200001,
 21300004,
 21400018,
 21500002,
 21600001,
 21000005,
 21100006,
 21200029,
 21500006,
 21700004,
 21000008,
 21100013,
 21300013,
 21500011,
 21700008,
 21000012,
 21300012,
 21400002,
 21600005,
 21700009,
 21000007,
 21200004,
 21400008,
 21500009,
 21600007,
 21700014,
 21000011,
 21100004,
 21200014,
 21300014,
 21500013,
 21600011,
 21700015,
 21000013,
 21200008,
 21600003,
 21000014,
 21100012,
 21200005,
 21300016,
 21400011,
 21600010,
 21700010,
 21000006,
 21300005,
 21400005,
 21700006,
 21000015,
 21300017,
 21400014,
 21500003,
 21000010,
 21300011,
 21400001,
 21100010,
 21300007,
 21500001,
 21700003,
 21100022,
 21200009,
 21400012,
 21500007,
 21300001,
 21200007,
 21400010,
 21600015,
 21200020,
 21300008,
 21500012,
 21100007,
 21200015,
 21400004,
 21600008,
 21100018,
 21200018,
 21600014,
 21100015,
 21700013,
 21200017,
 21700007,
 21000017,
 21500004,
 21200016,
 21000018,
 21000026,
 21000027,
 21000025,
 21000029,
 21000021,
 21000022,
 21000020,
 21000030,
 21000019,
 21000024,
 21000028,
 21000023,
 21000034,
 21000039,
 21000038,
 21000037,
 21000035,
 21000031,
 21000036,
 21000032,
 21000033,
 21000042,
 21000040,
 21000041,
 21000043,
 21000046,
 21000045,
 21000044,
 21000052,
 21000050,
 21000047,
 21000048,
 21000053,
 21000049,
 21000060,
 21000056,
 21000059,
 21000058,
 21000054,
 21000055,
 21000062,
 21000063,
 21000061,
 21000065,
 21000064,
 21000067,
 21000066,
 21000071,
 21000068,
 21000069,
 21000072,
 21000070,
 21000077,
 21000078,
 21000074,
 21000075,
 21000073,
 21000079,
 21000076,
 21000088,
 21000086,
 21000081,
 21000080,
 21000084,
 21000087,
 21000094,
 21000089,
 21000093,
 21000090,
 21000091,
 21000092,
 21000098,
 21000097,
 21000096,
 21000095,
 21000100,
 21000105,
 21000106,
 21000102,
 21000107,
 21000104,
 21000101,
 21000103,
 21000115,
 21000110,
 21000108,
 21000113,
 21000109,
 21000111,
 21000119,
 21000120,
 21000129,
 21000127,
 21000124,
 21000121,
 21000123,
 21000122,
 21000126,
 21000125,
 21000136,
 21000135,
 21000138,
 21000130,
 21000133,
 21000134,
 21000137,
 21000132,
 21000140,
 21000141,
 21000142,
 21000150,
 21000146,
 21000147,
 21000145,
 21000144,
 21000152,
 21000157,
 21000155,
 21000154,
 21000156,
 21000153,
 21000159,
 21000164,
 21000167,
 21000158,
 21000161,
 21000162,
 21000165,
 21000166,
 21000160,
 21000169,
 21000168,
 21000170,
 21000174,
 21000179,
 21000177,
 21000178,
 21000173,
 21000175,
 21000172,
 21000189,
 21000183,
 21000187,
 21000184,
 21000188,
 21000186,
 21000185,
 21000190,
 21000182,
 21000192,
 21000193,
 21000191,
 21000195,
 21000197,
 21000198,
 21000196,
 21000199,
 21000200,
 21000201,
 21000204,
 21000207,
 21000206,
 21000208,
 21000214,
 21000212,
 21000210,
 21000215,
 21000218,
 21000219,
 21000216,
 21000221,
 21000223,
 21000225,
 21000227,
 21000230,
 21000231,
 21000228,
 21000222,
 21000237,
 21000238,
 21000239,
 21000241,
 21000236,
 21000234,
 21000246,
 21000242,
 21000249,
 21000243,
 21000252,
 21000251,
 21000253,
 21000250,
 21000255,
 21000256,
 21000260,
 21000259,
 21000257,
 21000268,
 21000271,
 21000265,
 21000264,
 21000267,
 21000270,
 21000262,
 21000266,
 21000274,
 21000273,
 21000277,
 21000282,
 21000281,
 21000285,
 21000286,
 21000276,
 21000291,
 21000293,
 21000289,
 21000288,
 21000292,
 21000296,
 21000297,
 21000300,
 21000299,
 21000307,
 21000302,
 21000306,
 21000315,
 21000313,
 21000310,
 21000312,
 21000326,
 21000321,
 21000316,
 21000317,
 21000325,
 21000328,
 21000327,
 21000329,
 21000331,
 21000336,
 21000334,
 21000340,
 21000337,
 21000347,
 21000344,
 21000345,
 21000348,
 21000341,
 21000343,
 21000354,
 21000350,
 21000351,
 21000352,
 21000353,
 21000356,
 21000358,
 21000365,
 21000364,
 21000375,
 21000377,
 21000369,
 21000370,
 21000372,
 21000376,
 21000380,
 21000378,
 21000383,
 21000384,
 21000385,
 21000388,
 21000391,
 21000382,
 21000390,
 21000395,
 21000392,
 21000399,
 21000394,
 21000397,
 21000398,
 21000405,
 21000400,
 21000408,
 21000407,
 21000416,
 21000415,
 21000417,
 21000418,
 21000419,
 21000425,
 21000426,
 21000429,
 21000427,
 21000431,
 21000436,
 21000435,
 21000434,
 21000442,
 21000444,
 21000441,
 21000443,
 21000454,
 21000447,
 21000449,
 21000458,
 21000459,
 21000460,
 21000470,
 21000464,
 21000462,
 21000463,
 21000469,
 21000467,
 21000473,
 21000476,
 21000482,
 21000477,
 21000479,
 21000481,
 21000487,
 21000484,
 21000490,
 21000493,
 21000492,
 21000495,
 21000496,
 21000501,
 21000504,
 21000500,
 21000506,
 21000510,
 21000508,
 21000518,
 21000516,
 21000529,
 21000534,
 21000533,
 21000538,
 21000539,
 21000543,
 21000550,
 21000549,
 21000547,
 21000552,
 21000560,
 21000567,
 21000569,
 21000572,
 21000562,
 21000561,
 21000564,
 21000570,
 21000573,
 21000574,
 21000575,
 21000591,
 21000587,
 21000594,
 21000599,
 21000600,
 21000610,
 21000603,
 21000607,
 21000617,
 21000623,
 21000618,
 21000624,
 21000621,
 21000620,
 21000632,
 21000650,
 21000644,
 21000649,
 21000663,
 21000666,
 21000671,
 21000688,
 21000681,
 21000683,
 21000690,
 21000682,
 21000695,
 21000700,
 21000706,
 21000702,
 21000701,
 21000712,
 21000714,
 21000727,
 21000723,
 21000743,
 21000747,
 21000768,
 21000780,
 21000787,
 21000791,
 21000800,
 21000799,
 21000808,
 21000805,
 21000813,
 21000812,
 21000832,
 21000828,
 21000845,
 21000846,
 21000849,
 21000864,
 21000878,
 21000876,
 21000888,
 21000891,
 21000904,
 21000902,
 21000923,
 21000929,
 21000958,
 21000978,
 21001027,
 21100017,
 21100020,
 21100021,
 21100019,
 21100024,
 21100029,
 21100031,
 21100027,
 21100030,
 21100032,
 21100023,
 21100026,
 21100028,
 21100025,
 21100035,
 21100038,
 21100033,
 21100034,
 21100037,
 21100036,
 21100048,
 21100040,
 21100039,
 21100049,
 21100043,
 21100047,
 21100046,
 21100041,
 21100045,
 21100053,
 21100054,
 21100055,
 21100056,
 21100050,
 21100052,
 21100065,
 21100057,
 21100058,
 21100061,
 21100064,
 21100062,
 21100060,
 21100074,
 21100069,
 21100071,
 21100066,
 21100070,
 21100072,
 21100068,
 21100075,
 21100076,
 21100077,
 21100078,
 21100079,
 21100080,
 21100081,
 21100090,
 21100083,
 21100088,
 21100091,
 21100087,
 21100093,
 21100084,
 21100086,
 21100085,
 21100092,
 21100089,
 21100096,
 21100095,
 21100097,
 21100098,
 21100102,
 21100099,
 21100100,
 21100104,
 21100109,
 21100103,
 21100106,
 21100105,
 21100101,
 21100107,
 21100108,
 21100114,
 21100119,
 21100118,
 21100112,
 21100111,
 21100116,
 21100113,
 21100117,
 21100125,
 21100124,
 21100122,
 21100121,
 21100120,
 21100123,
 21100126,
 21100127,
 21100138,
 21100132,
 21100134,
 21100142,
 21100141,
 21100136,
 21100139,
 21100133,
 21100135,
 21100150,
 21100146,
 21100143,
 21100147,
 21100145,
 21100152,
 21100153,
 21100148,
 21100144,
 21100155,
 21100156,
 21100157,
 21100158,
 21100165,
 21100160,
 21100169,
 21100163,
 21100161,
 21100164,
 21100166,
 21100162,
 21100168,
 21100167,
 21100176,
 21100180,
 21100172,
 21100171,
 21100174,
 21100175,
 21100177,
 21100179,
 21100178,
 21100181,
 21100183,
 21100186,
 21100193,
 21100189,
 21100191,
 21100184,
 21100194,
 21100192,
 21100190,
 21100187,
 21100200,
 21100197,
 21100198,
 21100196,
 21100201,
 21100206,
 21100211,
 21100207,
 21100212,
 21100208,
 21100204,
 21100210,
 21100202,
 21100205,
 21100203,
 21100215,
 21100214,
 21100213,
 21100216,
 21100217,
 21100221,
 21100219,
 21100218,
 21100224,
 21100223,
 21100222,
 21100225,
 21100220,
 21100226,
 21100228,
 21100231,
 21100227,
 21100232,
 21100230,
 21100236,
 21100229,
 21100238,
 21100241,
 21100239,
 21100240,
 21100247,
 21100245,
 21100244,
 21100251,
 21100243,
 21100246,
 21100248,
 21100253,
 21100255,
 21100256,
 21100254,
 21100265,
 21100269,
 21100266,
 21100259,
 21100260,
 21100258,
 21100257,
 21100262,
 21100261,
 21100271,
 21100284,
 21100276,
 21100278,
 21100274,
 21100277,
 21100282,
 21100272,
 21100290,
 21100288,
 21100289,
 21100287,
 21100298,
 21100291,
 21100297,
 21100296,
 21100292,
 21100305,
 21100299,
 21100307,
 21100301,
 21100314,
 21100313,
 21100312,
 21100315,
 21100318,
 21100322,
 21100324,
 21100327,
 21100326,
 21100340,
 21100335,
 21100334,
 21100338,
 21100347,
 21100352,
 21100346,
 21100345,
 21100342,
 21100355,
 21100356,
 21100365,
 21100359,
 21100361,
 21100357,
 21100362,
 21100367,
 21100368,
 21100376,
 21100374,
 21100373,
 21100377,
 21100381,
 21100384,
 21100387,
 21100385,
 21100389,
 21100392,
 21100396,
 21100394,
 21100399,
 21100390,
 21100406,
 21100405,
 21100404,
 21100401,
 21100402,
 21100407,
 21100400,
 21100403,
 21100408,
 21100410,
 21100412,
 21100415,
 21100426,
 21100427,
 21100428,
 21100422,
 21100437,
 21100432,
 21100429,
 21100435,
 21100446,
 21100454,
 21100445,
 21100450,
 21100448,
 21100468,
 21100467,
 21100465,
 21100460,
 21100463,
 21100466,
 21100478,
 21100476,
 21100483,
 21100484,
 21100482,
 21100489,
 21100487,
 21100492,
 21100486,
 21100494,
 21100502,
 21100509,
 21100508,
 21100518,
 21100512,
 21100514,
 21100520,
 21100519,
 21100516,
 21100527,
 21100526,
 21100525,
 21100528,
 21100537,
 21100535,
 21100536,
 21100539,
 21100540,
 21100545,
 21100548,
 21100555,
 21100565,
 21100567,
 21100579,
 21100572,
 21100571,
 21100570,
 21100578,
 21100588,
 21100586,
 21100597,
 21100598,
 21100602,
 21100599,
 21100607,
 21100609,
 21100615,
 21100614,
 21100617,
 21100613,
 21100620,
 21100623,
 21100624,
 21100631,
 21100636,
 21100637,
 21100635,
 21100628,
 21100638,
 21100639,
 21100653,
 21100645,
 21100647,
 21100650,
 21100651,
 21100657,
 21100660,
 21100664,
 21100663,
 21100672,
 21100675,
 21100676,
 21100682,
 21100678,
 21100688,
 21100691,
 21100685,
 21100693,
 21100695,
 21100702,
 21100717,
 21100716,
 21100722,
 21100724,
 21100733,
 21100747,
 21100762,
 21100765,
 21100759,
 21100775,
 21100773,
 21100774,
 21100780,
 21100781,
 21100777,
 21100786,
 21100792,
 21100798,
 21100801,
 21100809,
 21100819,
 21100815,
 21100840,
 21100845,
 21100866,
 21100937,
 21100950,
 21100946,
 21100953,
 21100954,
 21100964,
 21100974,
 21100985,
 21100983,
 21200024,
 21200019,
 21200021,
 21200026,
 21200025,
 21200022,
 21200030,
 21200028,
 21200033,
 21200036,
 21200027,
 21200034,
 21200032,
 21200031,
 21200035,
 21200039,
 21200038,
 21200040,
 21200041,
 21200037,
 21200048,
 21200046,
 21200045,
 21200043,
 21200044,
 21200049,
 21200047,
 ...]

In [43]:
pd.DataFrame({'game_id':game_id_list_first_matchups})

       game_id
0     21000001
1     21100002
2     21200002
3     21300002
4     21400007
...        ...
3475  21701071
3476  21701070
3477  21701078
3478  21701084
3479  21701114

[3480 rows x 1 columns]

In [44]:
#perform cma on nba team stats per season with omission of the current row
#i.e. difference of mean for team cma season stats

    #get team_id's into a single column for df
    #i.e. team_id_away and team_id_home to team_id instead
        
        #get column names with _home and column names with _away and column names with neither
        
        #combine dataframes with _home and _away while keep the columns with neither. use concat
            
        
    
    #what if a team has a repeated matchup before they have a new matchup??? then the stat cma should include
    # repeated matchups too?? -yes

In [45]:
#get team_id's into a single column for df

columns_list = list(df.columns)
columns_list

['game_id',
 'game_date',
 'TEAM_NAME_away',
 'TEAM_ABBREVIATION_away',
 'TEAM_CITY_away',
 'MIN_away',
 'duration_away',
 'TEAM_NAME_home',
 'TEAM_ABBREVIATION_home',
 'TEAM_CITY_home',
 'MIN_home',
 'duration_home',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'matchup',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'season_type',
 'season',
 'season_year',
 'wl_away',
 'wl_home',
 'spread_home',
 'spread_away']

In [46]:
#[k for k in columns_list if k.split('_home')[0] == '_home']

In [47]:
list_numerics_giah

['game_id',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'spread_home',
 'spread_away']

In [48]:
df_numerics

,game_id,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,spread_home,spread_away
0,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,2010,-8,8
1,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,2010,-14,14
2,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,2010,-2,2
15,21000010,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,2010,-4,4
14,21000015,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,2010,-4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,2017,9,-9
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,2017,-10,10
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,2017,-19,19
10264,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,2017,8,-8
10265,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,2017,23,-23

In [49]:
#df[list_numerics_giah]

list_numeric_col_names = list(df_numerics.columns)
list_numerics_gitiah = [i for i in list_numeric_col_names if i not in [ 'season_year']]
list_numerics_gitiah

['game_id',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'spread_home',
 'spread_away']

In [50]:
len(list_numerics_gitiah)

93

In [51]:
numeric_away_list = [k for k in list_numerics_gitiah if '_away' in k]
print(len(numeric_away_list))
numeric_away_list

46

['E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'spread_away']

In [52]:
numeric_home_list = [k for k in list_numerics_gitiah if '_home' in k]
print(len(numeric_home_list))
numeric_home_list

46

['E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'spread_home']

In [53]:
gih_numeric_list = ['game_id'] + numeric_home_list
gih_numeric_list

['game_id',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'spread_home']

In [54]:
gia_numeric_list = ['game_id'] + numeric_away_list
gia_numeric_list

['game_id',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'spread_away']

In [55]:
#get away column data with game_id

    #get column names and game_id for _away

#rename each column to drop _away

#get home column data with game_id

#rename each column to drop _home

#concat the two dataframes: df_giti_stats

In [56]:
#get away column data with game_id

    #get column names and game_id for _away

#rename each column to drop _away

In [57]:
#get list without _away
numeric_away_list

['E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'spread_away']

In [58]:
list_stats = [k.split('_away')[0] for k in numeric_away_list]
list_stats

['E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'team_id',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread']

In [59]:
list_stats_cma = [k + '_cma' for k in list_stats]
list_stats_cma

['E_OFF_RATING_cma',
 'OFF_RATING_cma',
 'E_DEF_RATING_cma',
 'DEF_RATING_cma',
 'E_NET_RATING_cma',
 'NET_RATING_cma',
 'AST_PCT_cma',
 'AST_TOV_cma',
 'AST_RATIO_cma',
 'OREB_PCT_cma',
 'DREB_PCT_cma',
 'REB_PCT_cma',
 'E_TM_TOV_PCT_cma',
 'TM_TOV_PCT_cma',
 'EFG_PCT_cma',
 'TS_PCT_cma',
 'USG_PCT_cma',
 'E_USG_PCT_cma',
 'E_PACE_cma',
 'PACE_cma',
 'PACE_PER40_cma',
 'POSS_cma',
 'PIE_cma',
 'duration_minutes_cma',
 'team_id_cma',
 'w_pct_cma',
 'min_cma',
 'fgm_cma',
 'fga_cma',
 'fg_pct_cma',
 'fg3m_cma',
 'fg3a_cma',
 'fg3_pct_cma',
 'ftm_cma',
 'fta_cma',
 'ft_pct_cma',
 'oreb_cma',
 'dreb_cma',
 'reb_cma',
 'ast_cma',
 'stl_cma',
 'blk_cma',
 'tov_cma',
 'pf_cma',
 'pts_cma',
 'spread_cma']

In [60]:
away_rename_dict = dict(zip(numeric_away_list, list_stats))
away_rename_dict

{'E_OFF_RATING_away': 'E_OFF_RATING',
 'OFF_RATING_away': 'OFF_RATING',
 'E_DEF_RATING_away': 'E_DEF_RATING',
 'DEF_RATING_away': 'DEF_RATING',
 'E_NET_RATING_away': 'E_NET_RATING',
 'NET_RATING_away': 'NET_RATING',
 'AST_PCT_away': 'AST_PCT',
 'AST_TOV_away': 'AST_TOV',
 'AST_RATIO_away': 'AST_RATIO',
 'OREB_PCT_away': 'OREB_PCT',
 'DREB_PCT_away': 'DREB_PCT',
 'REB_PCT_away': 'REB_PCT',
 'E_TM_TOV_PCT_away': 'E_TM_TOV_PCT',
 'TM_TOV_PCT_away': 'TM_TOV_PCT',
 'EFG_PCT_away': 'EFG_PCT',
 'TS_PCT_away': 'TS_PCT',
 'USG_PCT_away': 'USG_PCT',
 'E_USG_PCT_away': 'E_USG_PCT',
 'E_PACE_away': 'E_PACE',
 'PACE_away': 'PACE',
 'PACE_PER40_away': 'PACE_PER40',
 'POSS_away': 'POSS',
 'PIE_away': 'PIE',
 'duration_minutes_away': 'duration_minutes',
 'team_id_away': 'team_id',
 'w_pct_away': 'w_pct',
 'min_away': 'min',
 'fgm_away': 'fgm',
 'fga_away': 'fga',
 'fg_pct_away': 'fg_pct',
 'fg3m_away': 'fg3m',
 'fg3a_away': 'fg3a',
 'fg3_pct_away': 'fg3_pct',
 'ftm_away': 'ftm',
 'fta_away': 'fta',
 'ft_pct_away': 'ft_pct',
 'oreb_away': 'oreb',
 'dreb_away': 'dreb',
 'reb_away': 'reb',
 'ast_away': 'ast',
 'stl_away': 'stl',
 'blk_away': 'blk',
 'tov_away': 'tov',
 'pf_away': 'pf',
 'pts_away': 'pts',
 'spread_away': 'spread'}

In [61]:
home_rename_dict = dict(zip(numeric_home_list, list_stats))
home_rename_dict

{'E_OFF_RATING_home': 'E_OFF_RATING',
 'OFF_RATING_home': 'OFF_RATING',
 'E_DEF_RATING_home': 'E_DEF_RATING',
 'DEF_RATING_home': 'DEF_RATING',
 'E_NET_RATING_home': 'E_NET_RATING',
 'NET_RATING_home': 'NET_RATING',
 'AST_PCT_home': 'AST_PCT',
 'AST_TOV_home': 'AST_TOV',
 'AST_RATIO_home': 'AST_RATIO',
 'OREB_PCT_home': 'OREB_PCT',
 'DREB_PCT_home': 'DREB_PCT',
 'REB_PCT_home': 'REB_PCT',
 'E_TM_TOV_PCT_home': 'E_TM_TOV_PCT',
 'TM_TOV_PCT_home': 'TM_TOV_PCT',
 'EFG_PCT_home': 'EFG_PCT',
 'TS_PCT_home': 'TS_PCT',
 'USG_PCT_home': 'USG_PCT',
 'E_USG_PCT_home': 'E_USG_PCT',
 'E_PACE_home': 'E_PACE',
 'PACE_home': 'PACE',
 'PACE_PER40_home': 'PACE_PER40',
 'POSS_home': 'POSS',
 'PIE_home': 'PIE',
 'duration_minutes_home': 'duration_minutes',
 'team_id_home': 'team_id',
 'w_pct_home': 'w_pct',
 'min_home': 'min',
 'fgm_home': 'fgm',
 'fga_home': 'fga',
 'fg_pct_home': 'fg_pct',
 'fg3m_home': 'fg3m',
 'fg3a_home': 'fg3a',
 'fg3_pct_home': 'fg3_pct',
 'ftm_home': 'ftm',
 'fta_home': 'fta',
 'ft_pct_home': 'ft_pct',
 'oreb_home': 'oreb',
 'dreb_home': 'dreb',
 'reb_home': 'reb',
 'ast_home': 'ast',
 'stl_home': 'stl',
 'blk_home': 'blk',
 'tov_home': 'tov',
 'pf_home': 'pf',
 'pts_home': 'pts',
 'spread_home': 'spread'}

In [62]:
stats_rename_dict = dict(zip(list_stats,list_stats_cma))
stats_rename_dict

{'E_OFF_RATING': 'E_OFF_RATING_cma',
 'OFF_RATING': 'OFF_RATING_cma',
 'E_DEF_RATING': 'E_DEF_RATING_cma',
 'DEF_RATING': 'DEF_RATING_cma',
 'E_NET_RATING': 'E_NET_RATING_cma',
 'NET_RATING': 'NET_RATING_cma',
 'AST_PCT': 'AST_PCT_cma',
 'AST_TOV': 'AST_TOV_cma',
 'AST_RATIO': 'AST_RATIO_cma',
 'OREB_PCT': 'OREB_PCT_cma',
 'DREB_PCT': 'DREB_PCT_cma',
 'REB_PCT': 'REB_PCT_cma',
 'E_TM_TOV_PCT': 'E_TM_TOV_PCT_cma',
 'TM_TOV_PCT': 'TM_TOV_PCT_cma',
 'EFG_PCT': 'EFG_PCT_cma',
 'TS_PCT': 'TS_PCT_cma',
 'USG_PCT': 'USG_PCT_cma',
 'E_USG_PCT': 'E_USG_PCT_cma',
 'E_PACE': 'E_PACE_cma',
 'PACE': 'PACE_cma',
 'PACE_PER40': 'PACE_PER40_cma',
 'POSS': 'POSS_cma',
 'PIE': 'PIE_cma',
 'duration_minutes': 'duration_minutes_cma',
 'team_id': 'team_id_cma',
 'w_pct': 'w_pct_cma',
 'min': 'min_cma',
 'fgm': 'fgm_cma',
 'fga': 'fga_cma',
 'fg_pct': 'fg_pct_cma',
 'fg3m': 'fg3m_cma',
 'fg3a': 'fg3a_cma',
 'fg3_pct': 'fg3_pct_cma',
 'ftm': 'ftm_cma',
 'fta': 'fta_cma',
 'ft_pct': 'ft_pct_cma',
 'oreb': 'oreb_cma',
 'dreb': 'dreb_cma',
 'reb': 'reb_cma',
 'ast': 'ast_cma',
 'stl': 'stl_cma',
 'blk': 'blk_cma',
 'tov': 'tov_cma',
 'pf': 'pf_cma',
 'pts': 'pts_cma',
 'spread': 'spread_cma'}

In [63]:
df_gia = df[gia_numeric_list]
p(df_gia)

(10266, 47)

,game_id,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,spread_away
0,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8
1,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14
2,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,2
15,21000010,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,4
14,21000015,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,4
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,-9
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,10
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,19
10264,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8
10265,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23

In [64]:
df_gia.rename(columns=away_rename_dict, inplace=True)
p(df_gia)

(10266, 47)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread
0,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8
1,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14
2,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,2
15,21000010,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,4
14,21000015,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,4
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,-9
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,10
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,19
10264,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8
10265,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23

In [65]:
df_gih = df[gih_numeric_list]
p(df_gih)

(10266, 47)

,game_id,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,spread_home
0,21000001,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8
1,21000002,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14
2,21000003,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2
15,21000010,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,-4
14,21000015,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,-4
10261,41700317,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,9
10262,41700401,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,-10
10263,41700402,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,-19
10264,41700403,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8
10265,41700404,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23

In [66]:
df_gih.rename(columns=home_rename_dict, inplace=True)
p(df_gih)

(10266, 47)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread
0,21000001,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8
1,21000002,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14
2,21000003,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2
15,21000010,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,-4
14,21000015,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,-4
10261,41700317,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,9
10262,41700401,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,-10
10263,41700402,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,-19
10264,41700403,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8
10265,41700404,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23

In [67]:
#concat the two dataframes: df_giti_stats

df_giti_stats = pd.concat([df_gih, df_gia])
p(df_giti_stats)

(20532, 47)

,game_id,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread
0,21000001,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8
1,21000002,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14
2,21000003,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2
15,21000010,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,-4
14,21000015,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,-4
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,-9
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,10
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,19
10264,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8
10265,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23

In [68]:
#get game_id, game_date, season: df_gigds

df_gigds = df[['game_id', 'game_date', 'season']]
p(df_gigds)

(10266, 3)

        game_id  game_date   season
0      21000001 2010-10-26  2010-11
1      21000002 2010-10-26  2010-11
2      21000003 2010-10-26  2010-11
15     21000010 2010-10-27  2010-11
14     21000015 2010-10-27  2010-11
10261  41700317 2018-05-28  2017-18
10262  41700401 2018-05-31  2017-18
10263  41700402 2018-06-03  2017-18
10264  41700403 2018-06-06  2017-18
10265  41700404 2018-06-08  2017-18

In [69]:
df_gigdsti = pd.merge(df_gigds, df_giti_stats, on=['game_id'], how='inner')
p(df_gigdsti)

(20532, 49)

,game_id,game_date,season,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread
0,21000001,2010-10-26,2010-11,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8
1,21000001,2010-10-26,2010-11,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8
2,21000002,2010-10-26,2010-11,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14
3,21000002,2010-10-26,2010-11,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14
4,21000003,2010-10-26,2010-11,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,240.0,1610612747,1.0,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2
20527,41700402,2018-06-03,2017-18,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.5,79.58,97,0.435,240.0,1610612739,0.0,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,19
20528,41700403,2018-06-06,2017-18,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8
20529,41700403,2018-06-06,2017-18,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8
20530,41700404,2018-06-08,2017-18,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23
20531,41700404,2018-06-08,2017-18,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23

In [70]:
df_gigdsti.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20532 entries, 0 to 20531
Data columns (total 49 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   game_id           20532 non-null  int64
 1   game_date         20532 non-null  datetime64[ns]
 2   season            20532 non-null  object
 3   E_OFF_RATING      20532 non-null  float64
 4   OFF_RATING        20532 non-null  float64
 5   E_DEF_RATING      20532 non-null  float64
 6   DEF_RATING        20532 non-null  float64
 7   E_NET_RATING      20532 non-null  float64
 8   NET_RATING        20532 non-null  float64
 9   AST_PCT           20532 non-null  float64
 10  AST_TOV           20532 non-null  float64
 11  AST_RATIO         20532 non-null  float64
 12  OREB_PCT          20532 non-null  float64
 13  DREB_PCT          20532 non-null  float64
 14  REB_PCT           20532 non-null  float64
 15  E_TM_TOV_PCT      20532 non-null  float64
 16  TM_TOV_PCT        20532 non-null  float64
 17  EFG_PCT           20532 non-null  float64
 18  TS_PCT            20532 non-null  float64
 19  USG_PCT           20532 non-null  float64
 20  E_USG_PCT         20532 non-null  float64
 21  E_PACE            20532 non-null  float64
 22  PACE              20532 non-null  float64
 23  PACE_PER40        20532 non-null  float64
 24  POSS              20532 non-null  int64
 25  PIE               20532 non-null  float64
 26  duration_minutes  20532 non-null  float64
 27  team_id           20532 non-null  int64
 28  w_pct             20532 non-null  float64
 29  min               20532 non-null  int64
 30  fgm               20532 non-null  int64
 31  fga               20532 non-null  int64
 32  fg_pct            20532 non-null  float64
 33  fg3m              20532 non-null  int64
 34  fg3a              20532 non-null  int64
 35  fg3_pct           20532 non-null  float64
 36  ftm               20532 non-null  int64
 37  fta               20532 non-null  int64
 38  ft_pct            20532 non-null  float64
 39  oreb              20532 non-null  int64
 40  dreb              20532 non-null  int64
 41  reb               20532 non-null  int64
 42  ast               20532 non-null  int64
 43  stl               20532 non-null  int64
 44  blk               20532 non-null  int64
 45  tov               20532 non-null  int64
 46  pf                20532 non-null  int64
 47  pts               20532 non-null  int64
 48  spread            20532 non-null  int64
dtypes: datetime64[ns](1), float64(27), int64(20), object(1)
memory usage: 7.8+ MB

In [87]:
#df_gigdsti.game_date = pd.to_datetime(df_gigdsti.game_date)
#df_gigdsti.info()

'df_gigdsti.game_date = pd.to_datetime(df_gigdsti.game_date)\ndf_gigdsti.info()'

In [72]:
df_gigdsti.sort_values('game_date', inplace=True)
df_gigdsti.reset_index(drop=True, inplace=True)
p(df_gigdsti)

(20532, 49)

,game_id,game_date,season,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread
0,21000001,2010-10-26,2010-11,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8
1,21000001,2010-10-26,2010-11,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8
2,21000002,2010-10-26,2010-11,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14
3,21000002,2010-10-26,2010-11,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14
4,21000003,2010-10-26,2010-11,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,240.0,1610612747,1.0,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2
20527,41700402,2018-06-03,2017-18,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.5,79.58,97,0.435,240.0,1610612739,0.0,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,19
20528,41700403,2018-06-06,2017-18,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8
20529,41700403,2018-06-06,2017-18,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8
20530,41700404,2018-06-08,2017-18,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23
20531,41700404,2018-06-08,2017-18,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23

In [73]:
df_gigdsti.select_dtypes('number')

,game_id,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread
0,21000001,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8
1,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8
2,21000002,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14
3,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14
4,21000003,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,240.0,1610612747,1.0,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20527,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.5,79.58,97,0.435,240.0,1610612739,0.0,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,19
20528,41700403,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8
20529,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8
20530,41700404,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23
20531,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23

In [74]:
df_numerics = df.select_dtypes('number')
p(df_numerics)

(10266, 94)

,game_id,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,spread_home,spread_away
0,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,2010,-8,8
1,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,2010,-14,14
2,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,2010,-2,2
15,21000010,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,2010,-4,4
14,21000015,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,2010,-4,4
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,2017,9,-9
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,2017,-10,10
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,2017,-19,19
10264,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,2017,8,-8
10265,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,2017,23,-23

In [75]:
stats_rename_dict5 = stats_rename_dict.copy()
for key in stats_rename_dict5:
    stats_rename_dict5[key] = stats_rename_dict5[key] + '5'

In [76]:
stats_rename_dict5

{'E_OFF_RATING': 'E_OFF_RATING_cma5',
 'OFF_RATING': 'OFF_RATING_cma5',
 'E_DEF_RATING': 'E_DEF_RATING_cma5',
 'DEF_RATING': 'DEF_RATING_cma5',
 'E_NET_RATING': 'E_NET_RATING_cma5',
 'NET_RATING': 'NET_RATING_cma5',
 'AST_PCT': 'AST_PCT_cma5',
 'AST_TOV': 'AST_TOV_cma5',
 'AST_RATIO': 'AST_RATIO_cma5',
 'OREB_PCT': 'OREB_PCT_cma5',
 'DREB_PCT': 'DREB_PCT_cma5',
 'REB_PCT': 'REB_PCT_cma5',
 'E_TM_TOV_PCT': 'E_TM_TOV_PCT_cma5',
 'TM_TOV_PCT': 'TM_TOV_PCT_cma5',
 'EFG_PCT': 'EFG_PCT_cma5',
 'TS_PCT': 'TS_PCT_cma5',
 'USG_PCT': 'USG_PCT_cma5',
 'E_USG_PCT': 'E_USG_PCT_cma5',
 'E_PACE': 'E_PACE_cma5',
 'PACE': 'PACE_cma5',
 'PACE_PER40': 'PACE_PER40_cma5',
 'POSS': 'POSS_cma5',
 'PIE': 'PIE_cma5',
 'duration_minutes': 'duration_minutes_cma5',
 'team_id': 'team_id_cma5',
 'w_pct': 'w_pct_cma5',
 'min': 'min_cma5',
 'fgm': 'fgm_cma5',
 'fga': 'fga_cma5',
 'fg_pct': 'fg_pct_cma5',
 'fg3m': 'fg3m_cma5',
 'fg3a': 'fg3a_cma5',
 'fg3_pct': 'fg3_pct_cma5',
 'ftm': 'ftm_cma5',
 'fta': 'fta_cma5',
 'ft_pct': 'ft_pct_cma5',
 'oreb': 'oreb_cma5',
 'dreb': 'dreb_cma5',
 'reb': 'reb_cma5',
 'ast': 'ast_cma5',
 'stl': 'stl_cma5',
 'blk': 'blk_cma5',
 'tov': 'tov_cma5',
 'pf': 'pf_cma5',
 'pts': 'pts_cma5',
 'spread': 'spread_cma5'}

In [77]:
#get cma5
df_sti_cma5 = df_gigdsti.groupby(['season', 'team_id'])[list_stats].apply(lambda x: x.rolling(5, 1).mean().shift())
df_sti_cma5.rename(columns=stats_rename_dict5, inplace=True)
p(df_sti_cma5)

(20532, 46)

                          E_OFF_RATING_cma5  OFF_RATING_cma5  \
season  team_id
2010-11 1610612737 6                    NaN              NaN
                   50            119.400000       120.200000
                   64            115.250000       115.400000
                   96            110.433333       112.033333
                   114           110.550000       112.125000
2017-18 1610612766 20210         113.660000       115.320000
                   20218         105.800000       106.940000
                   20269         108.380000       109.880000
                   20313         111.160000       112.000000
                   20341         110.140000       111.360000

                          E_DEF_RATING_cma5  DEF_RATING_cma5  \
season  team_id
2010-11 1610612737 6                    NaN              NaN
                   50               102.000       105.100000
                   64               103.300       106.250000
                   96               102.100       104.533333
                   114              101.175       102.850000
2017-18 1610612766 20210            105.040       106.180000
                   20218            111.380       113.320000
                   20269            116.060       118.180000
                   20313            113.440       114.420000
                   20341            111.640       111.680000

                          E_NET_RATING_cma5  NET_RATING_cma5  AST_PCT_cma5  \
season  team_id
2010-11 1610612737 6                    NaN              NaN           NaN
                   50             17.500000        15.200000      0.476000
                   64             11.950000         9.200000      0.571500
                   96              8.333333         7.566667      0.567333
                   114             9.375000         9.325000      0.601250
2017-18 1610612766 20210           8.600000         9.160000      0.548400
                   20218          -5.600000        -6.360000      0.549400
                   20269          -7.660000        -8.300000      0.549400
                   20313          -2.260000        -2.440000      0.584800
                   20341          -1.480000        -0.340000      0.617200

                          AST_TOV_cma5  AST_RATIO_cma5  OREB_PCT_cma5  \
season  team_id
2010-11 1610612737 6               NaN             NaN            NaN
                   50         1.330000          15.500         0.0000
                   64         1.265000          17.150         0.1485
                   96         1.216667          16.300         0.2380
                   114        1.840000          17.225         0.2535
2017-18 1610612766 20210      1.780000          16.860         0.2814
                   20218      1.436000          15.860         0.2638
                   20269      1.352000          16.340         0.2696
                   20313      1.658000          17.480         0.2690
                   20341      1.608000          17.960         0.2554

                          DREB_PCT_cma5  REB_PCT_cma5  E_TM_TOV_PCT_cma5  \
season  team_id
2010-11 1610612737 6                NaN           NaN                NaN
                   50          0.000000      0.000000           15.05400
                   64          0.352000      0.269000           18.20600
                   96          0.480667      0.368333           17.90800
                   114         0.536750      0.398500           15.37125
2017-18 1610612766 20210       0.764200      0.535000           13.28120
                   20218       0.749200      0.511600           14.59260
                   20269       0.728800      0.510400           15.98220
                   20313       0.744400      0.523200           15.26960
                   20341       0.764800      0.522000           16.33680

                          TM_TOV_PCT_cma5  EFG_PCT_cma5  TS_PCT_cma5  \
season  team_id
2010-11 1610612737 6                  NaN           NaN          NaN
                   50              15.200      0.575000       0.6350
                   64              18.250      0.566000       0.6285
                   96              18.200      0.527667       0.5940
                   114             15.625      0.513250       0.5740
2017-18 1610612766 20210           13.440      0.546000       0.5882
                   20218           14.760      0.510200       0.5586
                   20269           16.200      0.535800       0.5834
                   20313           15.400      0.545600       0.5940
                   20341           16.520      0.550200       0.5982

                          USG_PCT_cma5  E_USG_PCT_cma5  E_PACE_cma5  \
season  team_id
2010-11 1610612737 6               NaN             NaN          NaN
                   50              1.0          0.1950      100.820
                   64              1.0          0.1970       97.950
                   96              1.0          0.1980       97.540
                   114             1.0          0.1980       95.610
2017-18 1610612766 20210           1.0          0.1988       99.024
                   20218           1.0          0.2002      100.048
                   20269           1.0          0.1996       99.660
                   20313           1.0          0.2006       99.328
                   20341           1.0          0.2004      102.104

                           PACE_cma5  PACE_PER40_cma5   POSS_cma5  PIE_cma5  \
season  team_id
2010-11 1610612737 6             NaN              NaN         NaN       NaN
                   50      99.000000           82.500   99.000000  0.619000
                   64      96.500000           80.415   96.500000  0.575500
                   96      95.666667           79.720   95.666667  0.552667
                   114     94.125000           78.435   94.000000  0.565250
2017-18 1610612766 20210   98.000000           81.666  100.000000  0.561400
                   20218   98.700000           82.250  100.600000  0.477400
                   20269   98.100000           81.750  100.000000  0.469600
                   20313   98.500000           82.084   98.400000  0.493600
                   20341  101.500000           84.584  101.200000  0.493400

                          duration_minutes_cma5  team_id_cma5  w_pct_cma5  \
season  team_id
2010-11 1610612737 6                        NaN           NaN         NaN
                   50                     240.0  1.610613e+09      1.0000
                   64                     240.0  1.610613e+09      1.0000
                   96                     240.0  1.610613e+09      1.0000
                   114                    240.0  1.610613e+09      1.0000
2017-18 1610612766 20210                  245.0  1.610613e+09      0.4452
                   20218                  245.0  1.610613e+09      0.4448
                   20269                  245.0  1.610613e+09      0.4416
                   20313                  240.0  1.610613e+09      0.4386
                   20341                  240.0  1.610613e+09      0.4356

                          min_cma5   fgm_cma5  fga_cma5  fg_pct_cma5  \
season  team_id
2010-11 1610612737 6           NaN        NaN       NaN          NaN
                   50        240.0  42.000000     80.00     0.525000
                   64        240.0  39.000000     75.00     0.519500
                   96        240.0  37.333333     77.00     0.486333
                   114       240.0  37.250000     78.75     0.474750
2017-18 1610612766 20210     245.0  41.800000     86.00     0.485800
                   20218     245.0  38.600000     84.00     0.459600
                   20269     245.0  39.600000     81.80     0.482400
                   20313     240.0  39.000000     80.40     0.484400
                   20341     240.0  39.200000     81.20     0.481800

                          fg3m_cma5  fg3a_cma5  fg3_pct_cma5   ftm_cma5  \
season  team_id
2010-11 1610612737 6            NaN        NaN           NaN        NaN
                   50      8.000000  16.000000        0.5000  27.000000
                   64      7.000000  16.500000        0.4265  26.500000
                   96      6.333333  17.333333        0.3720  26.333333
                   114     6.000000  17.250000        0.3525  25.000000
2017-18 1610612766 20210  10.600000  27.400000        0.3694  21.200000
                   20218   8.600000  25.400000        0.3344  22.000000
                   20269   8.800000  27.200000        0.3148  22.200000
                   20313  10.000000  27.800000        0.3458  22.200000
                   20341  11.200000  29.600000        0.3716  23.000000

                           fta_cma5  ft_pct_cma5  oreb_cma5  dreb_cma5  \
season  team_id
2010-11 1610612737 6            NaN          NaN        NaN        NaN
                   50     31.000000     0.870968   9.000000  35.000000
                   64     31.000000     0.854839   9.500000  35.500000
                   96     30.666667     0.858781  10.666667  33.666667
                   114    30.500000     0.819086  11.500000  32.500000
2017-18 1610612766 20210  27.000000     0.788989  10.000000  38.800000
                   20218  28.400000     0.777442   9.600000  36.600000
                   20269  28.200000     0.789511   9.000000  34.600000
                   20313  27.800000     0.802698   8.600000  36.400000
                   20341  29.000000     0.792698   8.400000  35.800000

                           reb_cma5  ast_cma5  stl_cma5  blk_cma5  tov_cma5  \
season  team_id
2010-11 1610612737 6            NaN       NaN       NaN       NaN       NaN
                   50     44.000000     20.00  7.000000       9.0      15.0
                   64     45.000000     22.00  5.000000       8.5      17.5
                   96     44.333333     21.00  4.666667       7.0      17.0
                   114    44.000000     22.25  5.250000       7.0      14.5
2017-18 1610612766 20210  48.800000     22.60  6.600000       3.2      13.0
                   20218  46.200000     21.00  6.200000       3.8      14.6
                   20269  43.600000     21.60  4.800000       3.8      16.0
                   20313  45.000000     23.00  4.600000       4.0      15.0
                   20341  44.200000     24.40  5.400000       4.2      16.6

                            pf_cma5    pts_cma5  spread_cma5
season  team_id
2010-11 1610612737 6            NaN         NaN          NaN
                   50     20.000000  119.000000   -15.000000
                   64     23.000000  111.500000    -9.000000
                   96     22.666667  107.333333    -7.333333
                   114    21.250000  105.500000    -8.500000
2017-18 1610612766 20210  14.600000  115.400000    -9.400000
                   20218  13.800000  107.800000     6.200000
                   20269  14.200000  110.200000     8.200000
                   20313  14.800000  110.200000     2.600000
                   20341  15.000000  112.600000     1.200000

In [78]:
#df_sti_cma5.iloc[(df_sti_cma5.index.get_level_values('team_id') ==  1610612766) & (df_sti_cma5.index.get_level_values('season') ==  '2017-18')]

In [79]:
stats_rename_dict20 = stats_rename_dict.copy()
for key in stats_rename_dict20:
    stats_rename_dict20[key] = stats_rename_dict20[key] + '20'

In [80]:
stats_rename_dict20

{'E_OFF_RATING': 'E_OFF_RATING_cma20',
 'OFF_RATING': 'OFF_RATING_cma20',
 'E_DEF_RATING': 'E_DEF_RATING_cma20',
 'DEF_RATING': 'DEF_RATING_cma20',
 'E_NET_RATING': 'E_NET_RATING_cma20',
 'NET_RATING': 'NET_RATING_cma20',
 'AST_PCT': 'AST_PCT_cma20',
 'AST_TOV': 'AST_TOV_cma20',
 'AST_RATIO': 'AST_RATIO_cma20',
 'OREB_PCT': 'OREB_PCT_cma20',
 'DREB_PCT': 'DREB_PCT_cma20',
 'REB_PCT': 'REB_PCT_cma20',
 'E_TM_TOV_PCT': 'E_TM_TOV_PCT_cma20',
 'TM_TOV_PCT': 'TM_TOV_PCT_cma20',
 'EFG_PCT': 'EFG_PCT_cma20',
 'TS_PCT': 'TS_PCT_cma20',
 'USG_PCT': 'USG_PCT_cma20',
 'E_USG_PCT': 'E_USG_PCT_cma20',
 'E_PACE': 'E_PACE_cma20',
 'PACE': 'PACE_cma20',
 'PACE_PER40': 'PACE_PER40_cma20',
 'POSS': 'POSS_cma20',
 'PIE': 'PIE_cma20',
 'duration_minutes': 'duration_minutes_cma20',
 'team_id': 'team_id_cma20',
 'w_pct': 'w_pct_cma20',
 'min': 'min_cma20',
 'fgm': 'fgm_cma20',
 'fga': 'fga_cma20',
 'fg_pct': 'fg_pct_cma20',
 'fg3m': 'fg3m_cma20',
 'fg3a': 'fg3a_cma20',
 'fg3_pct': 'fg3_pct_cma20',
 'ftm': 'ftm_cma20',
 'fta': 'fta_cma20',
 'ft_pct': 'ft_pct_cma20',
 'oreb': 'oreb_cma20',
 'dreb': 'dreb_cma20',
 'reb': 'reb_cma20',
 'ast': 'ast_cma20',
 'stl': 'stl_cma20',
 'blk': 'blk_cma20',
 'tov': 'tov_cma20',
 'pf': 'pf_cma20',
 'pts': 'pts_cma20',
 'spread': 'spread_cma20'}

In [81]:
#get cma20 
df_sti_cma20 = df_gigdsti.groupby(['season', 'team_id'])[list_stats].apply(lambda x: x.rolling(20, 1).mean().shift())
df_sti_cma20.rename(columns=stats_rename_dict20, inplace=True)
p(df_sti_cma20)

(20532, 46)

                          E_OFF_RATING_cma20  OFF_RATING_cma20  \
season  team_id
2010-11 1610612737 6                     NaN               NaN
                   50             119.400000        120.200000
                   64             115.250000        115.400000
                   96             110.433333        112.033333
                   114            110.550000        112.125000
2017-18 1610612766 20210          110.865000        112.460000
                   20218          110.095000        111.730000
                   20269          109.175000        110.830000
                   20313          110.605000        112.175000
                   20341          110.015000        111.640000

                          E_DEF_RATING_cma20  DEF_RATING_cma20  \
season  team_id
2010-11 1610612737 6                     NaN               NaN
                   50                102.000        105.100000
                   64                103.300        106.250000
                   96                102.100        104.533333
                   114               101.175        102.850000
2017-18 1610612766 20210             109.950        112.065000
                   20218             110.705        112.785000
                   20269             111.040        113.080000
                   20313             111.320        113.230000
                   20341             111.825        113.620000

                          E_NET_RATING_cma20  NET_RATING_cma20  AST_PCT_cma20  \
season  team_id
2010-11 1610612737 6                     NaN               NaN            NaN
                   50              17.500000         15.200000       0.476000
                   64              11.950000          9.200000       0.571500
                   96               8.333333          7.566667       0.567333
                   114              9.375000          9.325000       0.601250
2017-18 1610612766 20210            0.915000          0.405000       0.557350
                   20218           -0.610000         -1.050000       0.548600
                   20269           -1.860000         -2.250000       0.549050
                   20313           -0.705000         -1.055000       0.549050
                   20341           -1.805000         -1.980000       0.551000

                          AST_TOV_cma20  AST_RATIO_cma20  OREB_PCT_cma20  \
season  team_id
2010-11 1610612737 6                NaN              NaN             NaN
                   50          1.330000           15.500         0.00000
                   64          1.265000           17.150         0.14850
                   96          1.216667           16.300         0.23800
                   114         1.840000           17.225         0.25350
2017-18 1610612766 20210       1.974000           16.830         0.26055
                   20218       1.930500           16.450         0.25470
                   20269       1.846000           16.355         0.25425
                   20313       1.928000           16.530         0.25300
                   20341       1.892500           16.435         0.24945

                          DREB_PCT_cma20  REB_PCT_cma20  E_TM_TOV_PCT_cma20  \
season  team_id
2010-11 1610612737 6                 NaN            NaN                 NaN
                   50           0.000000       0.000000            15.05400
                   64           0.352000       0.269000            18.20600
                   96           0.480667       0.368333            17.90800
                   114          0.536750       0.398500            15.37125
2017-18 1610612766 20210        0.749850       0.501700            11.85955
                   20218        0.748650       0.496400            11.86225
                   20269        0.746900       0.497300            12.35540
                   20313        0.744900       0.498150            11.99055
                   20341        0.751100       0.499900            12.24675

                          TM_TOV_PCT_cma20  EFG_PCT_cma20  TS_PCT_cma20  \
season  team_id
2010-11 1610612737 6                   NaN            NaN           NaN
                   50               15.200       0.575000       0.63500
                   64               18.250       0.566000       0.62850
                   96               18.200       0.527667       0.59400
                   114              15.625       0.513250       0.57400
2017-18 1610612766 20210            12.025       0.524800       0.56740
                   20218            12.035       0.520350       0.56475
                   20269            12.535       0.519900       0.56445
                   20313            12.155       0.524350       0.57055
                   20341            12.420       0.521400       0.56960

                          USG_PCT_cma20  E_USG_PCT_cma20  E_PACE_cma20  \
season  team_id
2010-11 1610612737 6                NaN              NaN           NaN
                   50               1.0          0.19500       100.820
                   64               1.0          0.19700        97.950
                   96               1.0          0.19800        97.540
                   114              1.0          0.19800        95.610
2017-18 1610612766 20210            1.0          0.19855       100.518
                   20218            1.0          0.19880       100.853
                   20269            1.0          0.19900       101.252
                   20313            1.0          0.19915       101.049
                   20341            1.0          0.19915       101.515

                          PACE_cma20  PACE_PER40_cma20  POSS_cma20  PIE_cma20  \
season  team_id
2010-11 1610612737 6             NaN               NaN         NaN        NaN
                   50      99.000000           82.5000   99.000000   0.619000
                   64      96.500000           80.4150   96.500000   0.575500
                   96      95.666667           79.7200   95.666667   0.552667
                   114     94.125000           78.4350   94.000000   0.565250
2017-18 1610612766 20210   98.925000           82.4365   99.700000   0.509050
                   20218   99.250000           82.7075   99.950000   0.498150
                   20269   99.650000           83.0410  100.350000   0.494100
                   20313   99.550000           82.9580  100.200000   0.499500
                   20341  100.050000           83.3745  100.650000   0.494250

                          duration_minutes_cma20  team_id_cma20  w_pct_cma20  \
season  team_id
2010-11 1610612737 6                         NaN            NaN          NaN
                   50                     240.00   1.610613e+09      1.00000
                   64                     240.00   1.610613e+09      1.00000
                   96                     240.00   1.610613e+09      1.00000
                   114                    240.00   1.610613e+09      1.00000
2017-18 1610612766 20210                  241.25   1.610613e+09      0.43865
                   20218                  241.25   1.610613e+09      0.43890
                   20269                  241.25   1.610613e+09      0.43835
                   20313                  241.25   1.610613e+09      0.43775
                   20341                  241.25   1.610613e+09      0.43640

                          min_cma20  fgm_cma20  fga_cma20  fg_pct_cma20  \
season  team_id
2010-11 1610612737 6            NaN        NaN        NaN           NaN
                   50        240.00  42.000000      80.00      0.525000
                   64        240.00  39.000000      75.00      0.519500
                   96        240.00  37.333333      77.00      0.486333
                   114       240.00  37.250000      78.75      0.474750
2017-18 1610612766 20210     241.25  40.300000      86.70      0.465250
                   20218     241.25  39.850000      86.45      0.461200
                   20269     241.25  39.650000      86.00      0.461450
                   20313     241.25  39.950000      85.90      0.465500
                   20341     241.25  39.750000      85.80      0.463650

                          fg3m_cma20  fg3a_cma20  fg3_pct_cma20  ftm_cma20  \
season  team_id
2010-11 1610612737 6             NaN         NaN            NaN        NaN
                   50       8.000000   16.000000        0.50000  27.000000
                   64       7.000000   16.500000        0.42650  26.500000
                   96       6.333333   17.333333        0.37200  26.333333
                   114      6.000000   17.250000        0.35250  25.000000
2017-18 1610612766 20210   10.350000   27.450000        0.36180  21.150000
                   20218   10.250000   27.900000        0.35060  21.700000
                   20269   10.050000   27.650000        0.34790  21.900000
                   20313   10.100000   27.450000        0.35245  22.400000
                   20341    9.900000   27.200000        0.34935  22.950000

                          fta_cma20  ft_pct_cma20  oreb_cma20  dreb_cma20  \
season  team_id
2010-11 1610612737 6            NaN           NaN         NaN         NaN
                   50     31.000000      0.870968    9.000000   35.000000
                   64     31.000000      0.854839    9.500000   35.500000
                   96     30.666667      0.858781   10.666667   33.666667
                   114    30.500000      0.819086   11.500000   32.500000
2017-18 1610612766 20210  27.850000      0.758938    9.850000   34.950000
                   20218  28.550000      0.758644    9.650000   34.450000
                   20269  28.950000      0.753644    9.500000   35.000000
                   20313  29.100000      0.769363    9.300000   35.350000
                   20341  29.550000      0.776982    9.250000   35.450000

                          reb_cma20  ast_cma20  stl_cma20  blk_cma20  \
season  team_id
2010-11 1610612737 6            NaN        NaN        NaN        NaN
                   50     44.000000      20.00   7.000000       9.00
                   64     45.000000      22.00   5.000000       8.50
                   96     44.333333      21.00   4.666667       7.00
                   114    44.000000      22.25   5.250000       7.00
2017-18 1610612766 20210  44.800000      22.55   6.750000       4.35
                   20218  44.100000      21.95   7.000000       4.40
                   20269  44.500000      21.85   6.800000       4.35
                   20313  44.650000      22.05   6.550000       4.40
                   20341  44.700000      22.00   6.300000       4.15

                          tov_cma20   pf_cma20   pts_cma20  spread_cma20
season  team_id
2010-11 1610612737 6            NaN        NaN         NaN           NaN
                   50         15.00  20.000000  119.000000    -15.000000
                   64         17.50  23.000000  111.500000     -9.000000
                   96         17.00  22.666667  107.333333     -7.333333
                   114        14.50  21.250000  105.500000     -8.500000
2017-18 1610612766 20210      11.75  16.400000  112.100000     -1.100000
                   20218      11.85  16.300000  111.650000      0.500000
                   20269      12.45  16.200000  111.250000      1.650000
                   20313      12.00  16.000000  112.400000      0.600000
                   20341      12.35  16.150000  112.350000      1.650000

In [82]:
#get cma 
df_sti_cma = df_gigdsti.groupby(['season', 'team_id'])[list_stats].apply(lambda x: x.rolling(999, 1).mean().shift())
df_sti_cma.rename(columns=stats_rename_dict, inplace=True)
p(df_sti_cma)

(20532, 46)

                          E_OFF_RATING_cma  OFF_RATING_cma  E_DEF_RATING_cma  \
season  team_id
2010-11 1610612737 6                   NaN             NaN               NaN
                   50           119.400000      120.200000        102.000000
                   64           115.250000      115.400000        103.300000
                   96           110.433333      112.033333        102.100000
                   114          110.550000      112.125000        101.175000
2017-18 1610612766 20210        106.477922      108.480519        106.985714
                   20218        106.370513      108.384615        107.061538
                   20269        106.420253      108.427848        107.168354
                   20313        106.830000      108.820000        107.121250
                   20341        106.833333      108.801235        107.192593

                          DEF_RATING_cma  E_NET_RATING_cma  NET_RATING_cma  \
season  team_id
2010-11 1610612737 6                 NaN               NaN             NaN
                   50         105.100000         17.500000       15.200000
                   64         106.250000         11.950000        9.200000
                   96         104.533333          8.333333        7.566667
                   114        102.850000          9.375000        9.325000
2017-18 1610612766 20210      109.175325         -0.502597       -0.689610
                   20218      109.256410         -0.685897       -0.866667
                   20269      109.362025         -0.741772       -0.930380
                   20313      109.270000         -0.285000       -0.446250
                   20341      109.301235         -0.353086       -0.496296

                          AST_PCT_cma  AST_TOV_cma  AST_RATIO_cma  \
season  team_id
2010-11 1610612737 6              NaN          NaN            NaN
                   50        0.476000     1.330000      15.500000
                   64        0.571500     1.265000      17.150000
                   96        0.567333     1.216667      16.300000
                   114       0.601250     1.840000      17.225000
2017-18 1610612766 20210     0.548208     1.864545      16.016883
                   20218     0.547782     1.854231      15.979487
                   20269     0.548443     1.845949      15.998734
                   20313     0.549925     1.862875      16.085000
                   20341     0.551469     1.855802      16.122222

                          OREB_PCT_cma  DREB_PCT_cma  REB_PCT_cma  \
season  team_id
2010-11 1610612737 6               NaN           NaN          NaN
                   50         0.000000      0.000000     0.000000
                   64         0.148500      0.352000     0.269000
                   96         0.238000      0.480667     0.368333
                   114        0.253500      0.536750     0.398500
2017-18 1610612766 20210      0.271481      0.765701     0.510649
                   20218      0.271141      0.765077     0.510064
                   20269      0.271291      0.764823     0.510380
                   20313      0.271750      0.764813     0.511175
                   20341      0.270160      0.765519     0.510963

                          E_TM_TOV_PCT_cma  TM_TOV_PCT_cma  EFG_PCT_cma  \
season  team_id
2010-11 1610612737 6                   NaN             NaN          NaN
                   50            15.054000       15.200000     0.575000
                   64            18.206000       18.250000     0.566000
                   96            17.908000       18.200000     0.527667
                   114           15.371250       15.625000     0.513250
2017-18 1610612766 20210         12.411364       12.648052     0.504948
                   20218         12.449564       12.688462     0.504333
                   20269         12.537000       12.775949     0.505215
                   20313         12.507262       12.743750     0.507113
                   20341         12.590272       12.824691     0.507877

                          TS_PCT_cma  USG_PCT_cma  E_USG_PCT_cma  E_PACE_cma  \
season  team_id
2010-11 1610612737 6             NaN          NaN            NaN         NaN
                   50       0.635000          1.0       0.195000  100.820000
                   64       0.628500          1.0       0.197000   97.950000
                   96       0.594000          1.0       0.198000   97.540000
                   114      0.574000          1.0       0.198000   95.610000
2017-18 1610612766 20210    0.546247          1.0       0.198519  100.402208
                   20218    0.545987          1.0       0.198564  100.457051
                   20269    0.546810          1.0       0.198570  100.497089
                   20313    0.548763          1.0       0.198575  100.460625
                   20341    0.549741          1.0       0.198593  100.566790

                           PACE_cma  PACE_PER40_cma   POSS_cma   PIE_cma  \
season  team_id
2010-11 1610612737 6            NaN             NaN        NaN       NaN
                   50     99.000000       82.500000  99.000000  0.619000
                   64     96.500000       80.415000  96.500000  0.575500
                   96     95.666667       79.720000  95.666667  0.552667
                   114    94.125000       78.435000  94.000000  0.565250
2017-18 1610612766 20210  98.461818       82.051299  99.181818  0.497688
                   20218  98.507179       82.089103  99.205128  0.496282
                   20269  98.551392       82.125949  99.240506  0.496139
                   20313  98.544500       82.120250  99.225000  0.498400
                   20341  98.679753       82.232963  99.345679  0.498136

                          duration_minutes_cma   team_id_cma  w_pct_cma  \
season  team_id
2010-11 1610612737 6                       NaN           NaN        NaN
                   50               240.000000  1.610613e+09   1.000000
                   64               240.000000  1.610613e+09   1.000000
                   96               240.000000  1.610613e+09   1.000000
                   114              240.000000  1.610613e+09   1.000000
2017-18 1610612766 20210            241.298701  1.610613e+09   0.415636
                   20218            241.282051  1.610613e+09   0.415897
                   20269            241.265823  1.610613e+09   0.416076
                   20313            241.250000  1.610613e+09   0.416350
                   20341            241.234568  1.610613e+09   0.416543

                             min_cma    fgm_cma    fga_cma  fg_pct_cma  \
season  team_id
2010-11 1610612737 6             NaN        NaN        NaN         NaN
                   50     240.000000  42.000000  80.000000    0.525000
                   64     240.000000  39.000000  75.000000    0.519500
                   96     240.000000  37.333333  77.000000    0.486333
                   114    240.000000  37.250000  78.750000    0.474750
2017-18 1610612766 20210  241.298701  38.831169  86.727273    0.448442
                   20218  241.282051  38.756410  86.666667    0.447846
                   20269  241.265823  38.772152  86.594937    0.448430
                   20313  241.250000  38.887500  86.587500    0.449800
                   20341  241.234568  38.901235  86.506173    0.450420

                          fg3m_cma   fg3a_cma  fg3_pct_cma    ftm_cma  \
season  team_id
2010-11 1610612737 6           NaN        NaN          NaN        NaN
                   50     8.000000  16.000000     0.500000  27.000000
                   64     7.000000  16.500000     0.426500  26.500000
                   96     6.333333  17.333333     0.372000  26.333333
                   114    6.000000  17.250000     0.352500  25.000000
2017-18 1610612766 20210  9.818182  26.831169     0.360130  20.116883
                   20218  9.807692  26.871795     0.359359  20.205128
                   20269  9.848101  26.962025     0.359646  20.215190
                   20313  9.937500  27.012500     0.362000  20.262500
                   20341  9.950617  27.049383     0.362062  20.333333

                            fta_cma  ft_pct_cma   oreb_cma   dreb_cma  \
season  team_id
2010-11 1610612737 6            NaN         NaN        NaN        NaN
                   50     31.000000    0.870968   9.000000  35.000000
                   64     31.000000    0.854839   9.500000  35.500000
                   96     30.666667    0.858781  10.666667  33.666667
                   114    30.500000    0.819086  11.500000  32.500000
2017-18 1610612766 20210  27.090909    0.742785  10.142857  35.285714
                   20218  27.179487    0.743443  10.128205  35.230769
                   20269  27.189873    0.743526  10.126582  35.278481
                   20313  27.175000    0.745771  10.112500  35.350000
                   20341  27.209877    0.747263  10.049383  35.296296

                            reb_cma    ast_cma   stl_cma   blk_cma    tov_cma  \
season  team_id
2010-11 1610612737 6            NaN        NaN       NaN       NaN        NaN
                   50     44.000000  20.000000  7.000000  9.000000  15.000000
                   64     45.000000  22.000000  5.000000  8.500000  17.500000
                   96     44.333333  21.000000  4.666667  7.000000  17.000000
                   114    44.000000  22.250000  5.250000  7.000000  14.500000
2017-18 1610612766 20210  45.428571  21.337662  6.922078  4.506494  12.194805
                   20218  45.358974  21.282051  6.935897  4.538462  12.243590
                   20269  45.405063  21.316456  6.886076  4.531646  12.341772
                   20313  45.462500  21.450000  6.850000  4.537500  12.300000
                   20341  45.345679  21.518519  6.839506  4.518519  12.407407

                             pf_cma     pts_cma  spread_cma
season  team_id
2010-11 1610612737 6            NaN         NaN         NaN
                   50     20.000000  119.000000  -15.000000
                   64     23.000000  111.500000   -9.000000
                   96     22.666667  107.333333   -7.333333
                   114    21.250000  105.500000   -8.500000
2017-18 1610612766 20210  17.402597  107.597403    0.168831
                   20218  17.346154  107.525641    0.384615
                   20269  17.329114  107.607595    0.455696
                   20313  17.300000  107.975000   -0.012500
                   20341  17.296296  108.086420    0.061728

In [83]:
df_gigdsti.head(7)

,game_id,game_date,season,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread
0,21000001,2010-10-26,2010-11,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8
1,21000001,2010-10-26,2010-11,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8
2,21000002,2010-10-26,2010-11,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14
3,21000002,2010-10-26,2010-11,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14
4,21000003,2010-10-26,2010-11,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.5,86.25,104,0.493,240.0,1610612747,1.0,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,-2
5,21000003,2010-10-26,2010-11,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,2
6,21000008,2010-10-27,2010-11,119.4,120.2,102.0,105.1,17.5,15.2,0.476,1.33,15.5,0.000,0.000,0.000,15.054,15.2,0.575,0.635,1.0,0.195,100.82,99.0,82.50,99,0.619,240.0,1610612737,1.0,240,42,80,0.525,8,16,0.500,27,31,0.870968,9,35,44,20,7,9,15,20,119,-15

In [84]:
len(numeric_away_list)

46

In [85]:
len(list_stats)

46

In [86]:
# fix cma to exclude the current row

#df.groupby(['Platoon'])['Casualties'].apply(lambda x: x.rolling(2, 1).mean().shift().bfill())
df.groupby(['season']).apply(lambda x: x.rolling(2, 1).mean().shift())

IndexError: list assignment index out of range

In [ ]:
3342 + 138

In [ ]:
3480 / 8