In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

In [2]:
df = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv', ['game_date'])
df = sr(df, 'game_date')
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4
4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [3]:
column_names_list = list(df.columns)
pl(column_names_list)

110

['game_id',
 'game_date',
 'TEAM_NAME_away',
 'TEAM_ABBREVIATION_away',
 'TEAM_CITY_away',
 'MIN_away',
 'duration_away',
 'TEAM_NAME_home',
 'TEAM_ABBREVIATION_home',
 'TEAM_CITY_home',
 'MIN_home',
 'duration_home',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'matchup',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'season_type',
 'season',
 'season_year',
 'wl_away',
 'wl_home',
 'spread_home',
 'spread_away']

In [4]:
column_names_away_list = [k for k in column_names_list if '_away' in k]
pl(column_names_away_list)

52

['TEAM_NAME_away',
 'TEAM_ABBREVIATION_away',
 'TEAM_CITY_away',
 'MIN_away',
 'duration_away',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'wl_away',
 'spread_away']

In [5]:
column_names_home_list = [k for k in column_names_list if '_home' in k]
pl(column_names_home_list)

52

['TEAM_NAME_home',
 'TEAM_ABBREVIATION_home',
 'TEAM_CITY_home',
 'MIN_home',
 'duration_home',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'wl_home',
 'spread_home']

In [6]:
column_names_away_home_list = column_names_away_list + column_names_home_list
column_names_game_level_list = [k for k in column_names_list if not k in column_names_away_home_list]
pl(column_names_game_level_list)

6

['game_id', 'game_date', 'matchup', 'season_type', 'season', 'season_year']

In [7]:
52 + 52 + 6

110

In [8]:
gi_column_names_away_list = ['game_id'] + column_names_away_list
pl(gi_column_names_away_list)

53

['game_id',
 'TEAM_NAME_away',
 'TEAM_ABBREVIATION_away',
 'TEAM_CITY_away',
 'MIN_away',
 'duration_away',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'wl_away',
 'spread_away']

In [9]:
gi_column_names_home_list = ['game_id'] + column_names_home_list
pl(gi_column_names_home_list)

53

['game_id',
 'TEAM_NAME_home',
 'TEAM_ABBREVIATION_home',
 'TEAM_CITY_home',
 'MIN_home',
 'duration_home',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'wl_home',
 'spread_home']

In [10]:
df_gia = df.loc[:,gi_column_names_away_list]
p(df_gia)

(10266, 53)

,game_id,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_away,spread_away
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2
3,21000010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,L,4
4,21000015,Rockets,HOU,Houston,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,L,4
10261,41700317,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9
10262,41700401,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10
10263,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19
10264,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8
10265,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23

In [11]:
df_gia.loc[:,'away_home'] = 0
p(df_gia)

(10266, 54)

,game_id,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,wl_away,spread_away,away_home
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0
3,21000010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,L,4,0
4,21000015,Rockets,HOU,Houston,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,L,4,0
10261,41700317,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9,0
10262,41700401,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10,0
10263,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0
10264,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0
10265,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0

In [12]:
column_names_list_stripped = [k.split('_away')[0] for k in column_names_away_list]
pl(column_names_list_stripped)

52

['TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'duration',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'team_id',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'wl',
 'spread']

In [13]:
column_names_away_dict = dict(zip(column_names_away_list,column_names_list_stripped))
pdc(column_names_away_dict)

52

{'TEAM_NAME_away': 'TEAM_NAME',
 'TEAM_ABBREVIATION_away': 'TEAM_ABBREVIATION',
 'TEAM_CITY_away': 'TEAM_CITY',
 'MIN_away': 'MIN',
 'duration_away': 'duration',
 'E_OFF_RATING_away': 'E_OFF_RATING',
 'OFF_RATING_away': 'OFF_RATING',
 'E_DEF_RATING_away': 'E_DEF_RATING',
 'DEF_RATING_away': 'DEF_RATING',
 'E_NET_RATING_away': 'E_NET_RATING',
 'NET_RATING_away': 'NET_RATING',
 'AST_PCT_away': 'AST_PCT',
 'AST_TOV_away': 'AST_TOV',
 'AST_RATIO_away': 'AST_RATIO',
 'OREB_PCT_away': 'OREB_PCT',
 'DREB_PCT_away': 'DREB_PCT',
 'REB_PCT_away': 'REB_PCT',
 'E_TM_TOV_PCT_away': 'E_TM_TOV_PCT',
 'TM_TOV_PCT_away': 'TM_TOV_PCT',
 'EFG_PCT_away': 'EFG_PCT',
 'TS_PCT_away': 'TS_PCT',
 'USG_PCT_away': 'USG_PCT',
 'E_USG_PCT_away': 'E_USG_PCT',
 'E_PACE_away': 'E_PACE',
 'PACE_away': 'PACE',
 'PACE_PER40_away': 'PACE_PER40',
 'POSS_away': 'POSS',
 'PIE_away': 'PIE',
 'duration_minutes_away': 'duration_minutes',
 'team_id_away': 'team_id',
 'w_pct_away': 'w_pct',
 'min_away': 'min',
 'fgm_away': 'fgm',
 'fga_away': 'fga',
 'fg_pct_away': 'fg_pct',
 'fg3m_away': 'fg3m',
 'fg3a_away': 'fg3a',
 'fg3_pct_away': 'fg3_pct',
 'ftm_away': 'ftm',
 'fta_away': 'fta',
 'ft_pct_away': 'ft_pct',
 'oreb_away': 'oreb',
 'dreb_away': 'dreb',
 'reb_away': 'reb',
 'ast_away': 'ast',
 'stl_away': 'stl',
 'blk_away': 'blk',
 'tov_away': 'tov',
 'pf_away': 'pf',
 'pts_away': 'pts',
 'wl_away': 'wl',
 'spread_away': 'spread'}

In [14]:
column_names_home_dict = dict(zip(column_names_home_list,column_names_list_stripped))
pdc(column_names_home_dict)

52

{'TEAM_NAME_home': 'TEAM_NAME',
 'TEAM_ABBREVIATION_home': 'TEAM_ABBREVIATION',
 'TEAM_CITY_home': 'TEAM_CITY',
 'MIN_home': 'MIN',
 'duration_home': 'duration',
 'E_OFF_RATING_home': 'E_OFF_RATING',
 'OFF_RATING_home': 'OFF_RATING',
 'E_DEF_RATING_home': 'E_DEF_RATING',
 'DEF_RATING_home': 'DEF_RATING',
 'E_NET_RATING_home': 'E_NET_RATING',
 'NET_RATING_home': 'NET_RATING',
 'AST_PCT_home': 'AST_PCT',
 'AST_TOV_home': 'AST_TOV',
 'AST_RATIO_home': 'AST_RATIO',
 'OREB_PCT_home': 'OREB_PCT',
 'DREB_PCT_home': 'DREB_PCT',
 'REB_PCT_home': 'REB_PCT',
 'E_TM_TOV_PCT_home': 'E_TM_TOV_PCT',
 'TM_TOV_PCT_home': 'TM_TOV_PCT',
 'EFG_PCT_home': 'EFG_PCT',
 'TS_PCT_home': 'TS_PCT',
 'USG_PCT_home': 'USG_PCT',
 'E_USG_PCT_home': 'E_USG_PCT',
 'E_PACE_home': 'E_PACE',
 'PACE_home': 'PACE',
 'PACE_PER40_home': 'PACE_PER40',
 'POSS_home': 'POSS',
 'PIE_home': 'PIE',
 'duration_minutes_home': 'duration_minutes',
 'team_id_home': 'team_id',
 'w_pct_home': 'w_pct',
 'min_home': 'min',
 'fgm_home': 'fgm',
 'fga_home': 'fga',
 'fg_pct_home': 'fg_pct',
 'fg3m_home': 'fg3m',
 'fg3a_home': 'fg3a',
 'fg3_pct_home': 'fg3_pct',
 'ftm_home': 'ftm',
 'fta_home': 'fta',
 'ft_pct_home': 'ft_pct',
 'oreb_home': 'oreb',
 'dreb_home': 'dreb',
 'reb_home': 'reb',
 'ast_home': 'ast',
 'stl_home': 'stl',
 'blk_home': 'blk',
 'tov_home': 'tov',
 'pf_home': 'pf',
 'pts_home': 'pts',
 'wl_home': 'wl',
 'spread_home': 'spread'}

In [15]:
df_gia.rename(columns=column_names_away_dict, inplace=True)
p(df_gia)

(10266, 54)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0
3,21000010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,L,4,0
4,21000015,Rockets,HOU,Houston,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,L,4,0
10261,41700317,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9,0
10262,41700401,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10,0
10263,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0
10264,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0
10265,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0

In [16]:
df_gih = df.loc[:,gi_column_names_home_list]
p(df_gih)

(10266, 53)

,game_id,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,wl_home,spread_home
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8
1,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14
2,21000003,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2
3,21000010,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,W,-4
4,21000015,Warriors,GSW,Golden State,240:00,0 days 04:00:00,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,W,-4
10261,41700317,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9
10262,41700401,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10
10263,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19
10264,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8
10265,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23

In [17]:
df_gih.loc[:,'away_home'] = 1
p(df_gih)

(10266, 54)

,game_id,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,wl_home,spread_home,away_home
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1
1,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1
2,21000003,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1
3,21000010,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,W,-4,1
4,21000015,Warriors,GSW,Golden State,240:00,0 days 04:00:00,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,W,-4,1
10261,41700317,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1
10262,41700401,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1
10263,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1
10264,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1
10265,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1

In [18]:
df_gih.rename(columns=column_names_home_dict, inplace=True)
p(df_gih)

(10266, 54)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1
1,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1
2,21000003,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1
3,21000010,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,W,-4,1
4,21000015,Warriors,GSW,Golden State,240:00,0 days 04:00:00,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,W,-4,1
10261,41700317,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1
10262,41700401,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1
10263,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1
10264,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1
10265,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1

In [19]:
df_gi = pd.concat([df_gia, df_gih])
p(df_gi)

(20532, 54)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0
3,21000010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,L,4,0
4,21000015,Rockets,HOU,Houston,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,L,4,0
10261,41700317,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1
10262,41700401,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1
10263,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1
10264,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1
10265,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1

In [20]:
df_gl = df.loc[:, column_names_game_level_list]
p(df_gl)

(10266, 6)

        game_id  game_date      matchup     season_type   season  season_year
0      21000001 2010-10-26  BOS vs. MIA  Regular Season  2010-11         2010
1      21000002 2010-10-26  PHX vs. POR  Regular Season  2010-11         2010
2      21000003 2010-10-26  HOU vs. LAL  Regular Season  2010-11         2010
3      21000010 2010-10-27  MIL vs. NOH  Regular Season  2010-11         2010
4      21000015 2010-10-27  GSW vs. HOU  Regular Season  2010-11         2010
10261  41700317 2018-05-28  GSW vs. HOU        Playoffs  2017-18         2017
10262  41700401 2018-05-31  CLE vs. GSW        Playoffs  2017-18         2017
10263  41700402 2018-06-03  CLE vs. GSW        Playoffs  2017-18         2017
10264  41700403 2018-06-06  CLE vs. GSW        Playoffs  2017-18         2017
10265  41700404 2018-06-08  CLE vs. GSW        Playoffs  2017-18         2017

In [21]:
df_giti = pd.merge(df_gi, df_gl, on='game_id', how='inner')
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [22]:
df_giti = sr(df_giti, 'game_date')
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [23]:
df_giti['a'] = df_giti.matchup.str.split(' vs. ').str[0].str.strip()
p(df_giti)

(20532, 60)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year,a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE

In [24]:
df_giti['b'] = df_giti.matchup.str.split(' vs. ').str[1].str.strip()
p(df_giti)

(20532, 61)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year,a,b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW

In [25]:
df_numeric = df_giti.select_dtypes('number')
df_numeric = df_numeric.drop(columns=['season_year'])
p(df_numeric)

(20532, 48)

,game_id,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread,away_home
0,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8,0
1,21000001,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8,1
2,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14,0
3,21000002,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14,1
4,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,2,0
20527,41700402,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,-19,1
20528,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8,0
20529,41700403,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8,1
20530,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23,0
20531,41700404,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23,1

In [26]:
gi_column_names_numeric_list = list(df_numeric.columns)
pl(gi_column_names_numeric_list)

48

['game_id',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'team_id',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread',
 'away_home']

In [27]:
column_names_numeric_list = [k for k in gi_column_names_numeric_list if not k in ['game_id']]
pl(column_names_numeric_list)

47

['E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'team_id',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread',
 'away_home']

In [28]:
column_names_numeric_season_list = column_names_numeric_list + ['season']
pl(column_names_numeric_season_list)

48

['E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'team_id',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread',
 'away_home',
 'season']

In [29]:
df_temp = df_giti[column_names_numeric_season_list]
p(df_temp)

(20532, 48)

,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread,away_home,season
0,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,8,0,2010-11
1,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,-8,1,2010-11
2,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,14,0,2010-11
3,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,-14,1,2010-11
4,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,2,0,2010-11
20527,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,-19,1,2017-18
20528,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,-8,0,2017-18
20529,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,8,1,2017-18
20530,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,-23,0,2017-18
20531,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,23,1,2017-18

In [30]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20532 entries, 0 to 20531
Data columns (total 48 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   E_OFF_RATING      20532 non-null  float64
 1   OFF_RATING        20532 non-null  float64
 2   E_DEF_RATING      20532 non-null  float64
 3   DEF_RATING        20532 non-null  float64
 4   E_NET_RATING      20532 non-null  float64
 5   NET_RATING        20532 non-null  float64
 6   AST_PCT           20532 non-null  float64
 7   AST_TOV           20532 non-null  float64
 8   AST_RATIO         20532 non-null  float64
 9   OREB_PCT          20532 non-null  float64
 10  DREB_PCT          20532 non-null  float64
 11  REB_PCT           20532 non-null  float64
 12  E_TM_TOV_PCT      20532 non-null  float64
 13  TM_TOV_PCT        20532 non-null  float64
 14  EFG_PCT           20532 non-null  float64
 15  TS_PCT            20532 non-null  float64
 16  USG_PCT           20532 non-null  float64
 17  E_USG_PCT         20532 non-null  float64
 18  E_PACE            20532 non-null  float64
 19  PACE              20532 non-null  float64
 20  PACE_PER40        20532 non-null  float64
 21  POSS              20532 non-null  int64
 22  PIE               20532 non-null  float64
 23  duration_minutes  20532 non-null  float64
 24  team_id           20532 non-null  int64
 25  w_pct             20532 non-null  float64
 26  min               20532 non-null  int64
 27  fgm               20532 non-null  int64
 28  fga               20532 non-null  int64
 29  fg_pct            20532 non-null  float64
 30  fg3m              20532 non-null  int64
 31  fg3a              20532 non-null  int64
 32  fg3_pct           20532 non-null  float64
 33  ftm               20532 non-null  int64
 34  fta               20532 non-null  int64
 35  ft_pct            20532 non-null  float64
 36  oreb              20532 non-null  int64
 37  dreb              20532 non-null  int64
 38  reb               20532 non-null  int64
 39  ast               20532 non-null  int64
 40  stl               20532 non-null  int64
 41  blk               20532 non-null  int64
 42  tov               20532 non-null  int64
 43  pf                20532 non-null  int64
 44  pts               20532 non-null  int64
 45  spread            20532 non-null  int64
 46  away_home         20532 non-null  int64
 47  season            20532 non-null  object
dtypes: float64(27), int64(20), object(1)
memory usage: 7.5+ MB

In [31]:
column_names_numeric_list_no_tis = [k for k in column_names_numeric_season_list if not k in ['team_id', 'season']]
pl(column_names_numeric_list_no_tis)

46

['E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread',
 'away_home']

In [32]:
df_sti_cma = df_temp.groupby(['season', 'team_id']).apply(lambda x: x.rolling(12, 1).mean().shift())[column_names_numeric_list_no_tis]
p(df_sti_cma)

(20532, 46)

                          E_OFF_RATING  OFF_RATING  E_DEF_RATING  DEF_RATING  \
season  team_id
2010-11 1610612737 13              NaN         NaN           NaN         NaN
                   49       119.400000  120.200000    102.000000  105.100000
                   63       115.250000  115.400000    103.300000  106.250000
                   97       110.433333  112.033333    102.100000  104.533333
                   112      110.550000  112.125000    101.175000  102.850000
2017-18 1610612766 20217    110.041667  111.875000    109.333333  111.075000
                   20228    109.425000  111.133333    108.791667  110.283333
                   20270    108.833333  110.483333    108.958333  110.400000
                   20305    111.616667  113.091667    108.175000  109.541667
                   20339    110.225000  111.600000    108.508333  109.391667

                          E_NET_RATING  NET_RATING   AST_PCT   AST_TOV  \
season  team_id
2010-11 1610612737 13              NaN         NaN       NaN       NaN
                   49        17.500000   15.200000  0.476000  1.330000
                   63        11.950000    9.200000  0.571500  1.265000
                   97         8.333333    7.566667  0.567333  1.216667
                   112        9.375000    9.325000  0.601250  1.840000
2017-18 1610612766 20217      0.716667    0.808333  0.518667  1.765833
                   20228      0.641667    0.858333  0.523000  1.732500
                   20270     -0.116667    0.083333  0.527583  1.665833
                   20305      3.450000    3.550000  0.542417  1.801667
                   20339      1.725000    2.200000  0.544333  1.659167

                          AST_RATIO  OREB_PCT  DREB_PCT   REB_PCT  \
season  team_id
2010-11 1610612737 13           NaN       NaN       NaN       NaN
                   49     15.500000  0.000000  0.000000  0.000000
                   63     17.150000  0.148500  0.352000  0.269000
                   97     16.300000  0.238000  0.480667  0.368333
                   112    17.225000  0.253500  0.536750  0.398500
2017-18 1610612766 20217  15.691667  0.263000  0.750583  0.511917
                   20228  15.566667  0.263083  0.752333  0.511250
                   20270  15.541667  0.262583  0.745917  0.509500
                   20305  16.125000  0.269917  0.751417  0.518500
                   20339  15.933333  0.269917  0.755083  0.520000

                          E_TM_TOV_PCT  TM_TOV_PCT   EFG_PCT    TS_PCT  \
season  team_id
2010-11 1610612737 13              NaN         NaN       NaN       NaN
                   49        15.054000   15.200000  0.575000  0.635000
                   63        18.206000   18.250000  0.566000  0.628500
                   97        17.908000   18.200000  0.527667  0.594000
                   112       15.371250   15.625000  0.513250  0.574000
2017-18 1610612766 20217     12.007333   12.200000  0.516417  0.565000
                   20228     12.260167   12.441667  0.512333  0.561750
                   20270     12.910583   13.091667  0.511833  0.561250
                   20305     12.683583   12.841667  0.523083  0.573167
                   20339     13.486417   13.641667  0.518333  0.571833

                          USG_PCT  E_USG_PCT      E_PACE        PACE  \
season  team_id
2010-11 1610612737 13         NaN        NaN         NaN         NaN
                   49         1.0   0.195000  100.820000   99.000000
                   63         1.0   0.197000   97.950000   96.500000
                   97         1.0   0.198000   97.540000   95.666667
                   112        1.0   0.198000   95.610000   94.125000
2017-18 1610612766 20217      1.0   0.198833  101.743333  100.208333
                   20228      1.0   0.199167  101.721667  100.333333
                   20270      1.0   0.199083  101.805000  100.458333
                   20305      1.0   0.199250  101.011667   99.791667
                   20339      1.0   0.199583  101.281667  100.333333

                          PACE_PER40        POSS       PIE  duration_minutes  \
season  team_id
2010-11 1610612737 13            NaN         NaN       NaN               NaN
                   49      82.500000   99.000000  0.619000        240.000000
                   63      80.415000   96.500000  0.575500        240.000000
                   97      79.720000   95.666667  0.552667        240.000000
                   112     78.435000   94.000000  0.565250        240.000000
2017-18 1610612766 20217   83.505833  101.250000  0.515000        242.083333
                   20228   83.610000  101.250000  0.511833        242.083333
                   20270   83.714167  101.250000  0.506750        242.083333
                   20305   83.159167  100.583333  0.524167        242.083333
                   20339   83.610833  101.083333  0.517833        242.083333

                             w_pct         min        fgm        fga  \
season  team_id
2010-11 1610612737 13          NaN         NaN        NaN        NaN
                   49     1.000000  240.000000  42.000000  80.000000
                   63     1.000000  240.000000  39.000000  75.000000
                   97     1.000000  240.000000  37.333333  77.000000
                   112    1.000000  240.000000  37.250000  78.750000
2017-18 1610612766 20217  0.435583  242.083333  40.500000  87.500000
                   20228  0.436583  242.083333  39.833333  87.250000
                   20270  0.436333  242.083333  39.500000  86.750000
                   20305  0.437333  242.083333  39.750000  86.166667
                   20339  0.437083  242.083333  39.250000  85.583333

                            fg_pct       fg3m       fg3a   fg3_pct        ftm  \
season  team_id
2010-11 1610612737 13          NaN        NaN        NaN       NaN        NaN
                   49     0.525000   8.000000  16.000000  0.500000  27.000000
                   63     0.519500   7.000000  16.500000  0.426500  26.500000
                   97     0.486333   6.333333  17.333333  0.372000  26.333333
                   112    0.474750   6.000000  17.250000  0.352500  25.000000
2017-18 1610612766 20217  0.463417   9.333333  26.500000  0.331833  23.000000
                   20228  0.456750   9.750000  27.416667  0.339250  23.166667
                   20270  0.455750   9.750000  27.583333  0.337250  23.166667
                   20305  0.461917  10.583333  28.000000  0.360500  23.666667
                   20339  0.459500  10.083333  27.750000  0.348167  24.166667

                                fta    ft_pct       oreb       dreb  \
season  team_id
2010-11 1610612737 13           NaN       NaN        NaN        NaN
                   49     31.000000  0.870968   9.000000  35.000000
                   63     31.000000  0.854839   9.500000  35.500000
                   97     30.666667  0.858781  10.666667  33.666667
                   112    30.500000  0.819086  11.500000  32.500000
2017-18 1610612766 20217  29.416667  0.784947   9.916667  37.416667
                   20228  29.750000  0.781679  10.166667  37.500000
                   20270  29.833333  0.779364  10.416667  37.916667
                   20305  30.166667  0.788105  10.500000  38.250000
                   20339  30.166667  0.804772  10.416667  37.583333

                                reb        ast       stl       blk        tov  \
season  team_id
2010-11 1610612737 13           NaN        NaN       NaN       NaN        NaN
                   49     44.000000  20.000000  7.000000  9.000000  15.000000
                   63     45.000000  22.000000  5.000000  8.500000  17.500000
                   97     44.333333  21.000000  4.666667  7.000000  17.000000
                   112    44.000000  22.250000  5.250000  7.000000  14.500000
2017-18 1610612766 20217  47.333333  21.083333  6.500000  4.083333  12.083333
                   20228  47.666667  20.916667  6.750000  4.250000  12.333333
                   20270  48.333333  20.916667  6.083333  4.166667  13.000000
                   20305  48.750000  21.750000  5.750000  3.833333  12.666667
                   20339  48.000000  21.500000  6.000000  3.833333  13.583333

                                 pf         pts     spread  away_home
season  team_id
2010-11 1610612737 13           NaN         NaN        NaN        NaN
                   49     20.000000  119.000000 -15.000000   0.000000
                   63     23.000000  111.500000  -9.000000   0.000000
                   97     22.666667  107.333333  -7.333333   0.333333
                   112    21.250000  105.500000  -8.500000   0.250000
2017-18 1610612766 20217  15.583333  113.333333  -1.416667   0.416667
                   20228  14.916667  112.583333  -1.166667   0.416667
                   20270  14.750000  111.916667  -0.083333   0.333333
                   20305  14.916667  113.750000  -3.500000   0.333333
                   20339  14.583333  112.750000  -2.000000   0.416667

In [33]:
df_sti_cma = df_sti_cma.reset_index()
df_sti_cma.rename(columns={'level_2':'index'}, inplace=True)
p(df_sti_cma)

(20532, 49)

,season,team_id,index,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,spread,away_home
0,2010-11,1610612737,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-11,1610612737,49,119.400000,120.200000,102.000000,105.100000,17.500000,15.200000,0.476000,1.330000,15.500000,0.000000,0.000000,0.000000,15.054000,15.200000,0.575000,0.635000,1.0,0.195000,100.820000,99.000000,82.500000,99.000000,0.619000,240.000000,1.000000,240.000000,42.000000,80.000000,0.525000,8.000000,16.000000,0.500000,27.000000,31.000000,0.870968,9.000000,35.000000,44.000000,20.000000,7.000000,9.000000,15.000000,20.000000,119.000000,-15.000000,0.000000
2,2010-11,1610612737,63,115.250000,115.400000,103.300000,106.250000,11.950000,9.200000,0.571500,1.265000,17.150000,0.148500,0.352000,0.269000,18.206000,18.250000,0.566000,0.628500,1.0,0.197000,97.950000,96.500000,80.415000,96.500000,0.575500,240.000000,1.000000,240.000000,39.000000,75.000000,0.519500,7.000000,16.500000,0.426500,26.500000,31.000000,0.854839,9.500000,35.500000,45.000000,22.000000,5.000000,8.500000,17.500000,23.000000,111.500000,-9.000000,0.000000
3,2010-11,1610612737,97,110.433333,112.033333,102.100000,104.533333,8.333333,7.566667,0.567333,1.216667,16.300000,0.238000,0.480667,0.368333,17.908000,18.200000,0.527667,0.594000,1.0,0.198000,97.540000,95.666667,79.720000,95.666667,0.552667,240.000000,1.000000,240.000000,37.333333,77.000000,0.486333,6.333333,17.333333,0.372000,26.333333,30.666667,0.858781,10.666667,33.666667,44.333333,21.000000,4.666667,7.000000,17.000000,22.666667,107.333333,-7.333333,0.333333
4,2010-11,1610612737,112,110.550000,112.125000,101.175000,102.850000,9.375000,9.325000,0.601250,1.840000,17.225000,0.253500,0.536750,0.398500,15.371250,15.625000,0.513250,0.574000,1.0,0.198000,95.610000,94.125000,78.435000,94.000000,0.565250,240.000000,1.000000,240.000000,37.250000,78.750000,0.474750,6.000000,17.250000,0.352500,25.000000,30.500000,0.819086,11.500000,32.500000,44.000000,22.250000,5.250000,7.000000,14.500000,21.250000,105.500000,-8.500000,0.250000
20527,2017-18,1610612766,20217,110.041667,111.875000,109.333333,111.075000,0.716667,0.808333,0.518667,1.765833,15.691667,0.263000,0.750583,0.511917,12.007333,12.200000,0.516417,0.565000,1.0,0.198833,101.743333,100.208333,83.505833,101.250000,0.515000,242.083333,0.435583,242.083333,40.500000,87.500000,0.463417,9.333333,26.500000,0.331833,23.000000,29.416667,0.784947,9.916667,37.416667,47.333333,21.083333,6.500000,4.083333,12.083333,15.583333,113.333333,-1.416667,0.416667
20528,2017-18,1610612766,20228,109.425000,111.133333,108.791667,110.283333,0.641667,0.858333,0.523000,1.732500,15.566667,0.263083,0.752333,0.511250,12.260167,12.441667,0.512333,0.561750,1.0,0.199167,101.721667,100.333333,83.610000,101.250000,0.511833,242.083333,0.436583,242.083333,39.833333,87.250000,0.456750,9.750000,27.416667,0.339250,23.166667,29.750000,0.781679,10.166667,37.500000,47.666667,20.916667,6.750000,4.250000,12.333333,14.916667,112.583333,-1.166667,0.416667
20529,2017-18,1610612766,20270,108.833333,110.483333,108.958333,110.400000,-0.116667,0.083333,0.527583,1.665833,15.541667,0.262583,0.745917,0.509500,12.910583,13.091667,0.511833,0.561250,1.0,0.199083,101.805000,100.458333,83.714167,101.250000,0.506750,242.083333,0.436333,242.083333,39.500000,86.750000,0.455750,9.750000,27.583333,0.337250,23.166667,29.833333,0.779364,10.416667,37.916667,48.333333,20.916667,6.083333,4.166667,13.000000,14.750000,111.916667,-0.083333,0.333333
20530,2017-18,1610612766,20305,111.616667,113.091667,108.175000,109.541667,3.450000,3.550000,0.542417,1.801667,16.125000,0.269917,0.751417,0.518500,12.683583,12.841667,0.523083,0.573167,1.0,0.199250,101.011667,99.791667,83.159167,100.583333,0.524167,242.083333,0.437333,242.083333,39.750000,86.166667,0.461917,10.583333,28.000000,0.360500,23.666667,30.166667,0.788105,10.500000,38.250000,48.750000,21.750000,5.750000,3.833333,12.666667,14.916667,113.750000,-3.500000,0.333333
20531,2017-18,1610612766,20339,110.225000,111.600000,108.508333,109.391667,1.725000,2.200000,0.544333,1.659167,15.933333,0.269917,0.755083,0.520000,13.486417,13.641667,0.518333,0.571833,1.0,0.199583,101.281667,100.333333,83.610833,101.083333,0.517833,242.083333,0.437083,242.083333,39.250000,85.583333,0.459500,10.083333,27.750000,0.348167,24.166667,30.166667,0.804772,10.416667,37.583333,48.000000,21.500000,6.000000,3.833333,13.583333,14.583333,112.750000,-2.000000,0.416667

In [34]:
column_names_list_cma = [k + '_cma' for k in column_names_numeric_list_no_tis]
pl(column_names_list_cma)

46

['E_OFF_RATING_cma',
 'OFF_RATING_cma',
 'E_DEF_RATING_cma',
 'DEF_RATING_cma',
 'E_NET_RATING_cma',
 'NET_RATING_cma',
 'AST_PCT_cma',
 'AST_TOV_cma',
 'AST_RATIO_cma',
 'OREB_PCT_cma',
 'DREB_PCT_cma',
 'REB_PCT_cma',
 'E_TM_TOV_PCT_cma',
 'TM_TOV_PCT_cma',
 'EFG_PCT_cma',
 'TS_PCT_cma',
 'USG_PCT_cma',
 'E_USG_PCT_cma',
 'E_PACE_cma',
 'PACE_cma',
 'PACE_PER40_cma',
 'POSS_cma',
 'PIE_cma',
 'duration_minutes_cma',
 'w_pct_cma',
 'min_cma',
 'fgm_cma',
 'fga_cma',
 'fg_pct_cma',
 'fg3m_cma',
 'fg3a_cma',
 'fg3_pct_cma',
 'ftm_cma',
 'fta_cma',
 'ft_pct_cma',
 'oreb_cma',
 'dreb_cma',
 'reb_cma',
 'ast_cma',
 'stl_cma',
 'blk_cma',
 'tov_cma',
 'pf_cma',
 'pts_cma',
 'spread_cma',
 'away_home_cma']

In [35]:
column_names_cma_dict = dict(zip(column_names_numeric_list_no_tis, column_names_list_cma))
pdc(column_names_cma_dict)

46

{'E_OFF_RATING': 'E_OFF_RATING_cma',
 'OFF_RATING': 'OFF_RATING_cma',
 'E_DEF_RATING': 'E_DEF_RATING_cma',
 'DEF_RATING': 'DEF_RATING_cma',
 'E_NET_RATING': 'E_NET_RATING_cma',
 'NET_RATING': 'NET_RATING_cma',
 'AST_PCT': 'AST_PCT_cma',
 'AST_TOV': 'AST_TOV_cma',
 'AST_RATIO': 'AST_RATIO_cma',
 'OREB_PCT': 'OREB_PCT_cma',
 'DREB_PCT': 'DREB_PCT_cma',
 'REB_PCT': 'REB_PCT_cma',
 'E_TM_TOV_PCT': 'E_TM_TOV_PCT_cma',
 'TM_TOV_PCT': 'TM_TOV_PCT_cma',
 'EFG_PCT': 'EFG_PCT_cma',
 'TS_PCT': 'TS_PCT_cma',
 'USG_PCT': 'USG_PCT_cma',
 'E_USG_PCT': 'E_USG_PCT_cma',
 'E_PACE': 'E_PACE_cma',
 'PACE': 'PACE_cma',
 'PACE_PER40': 'PACE_PER40_cma',
 'POSS': 'POSS_cma',
 'PIE': 'PIE_cma',
 'duration_minutes': 'duration_minutes_cma',
 'w_pct': 'w_pct_cma',
 'min': 'min_cma',
 'fgm': 'fgm_cma',
 'fga': 'fga_cma',
 'fg_pct': 'fg_pct_cma',
 'fg3m': 'fg3m_cma',
 'fg3a': 'fg3a_cma',
 'fg3_pct': 'fg3_pct_cma',
 'ftm': 'ftm_cma',
 'fta': 'fta_cma',
 'ft_pct': 'ft_pct_cma',
 'oreb': 'oreb_cma',
 'dreb': 'dreb_cma',
 'reb': 'reb_cma',
 'ast': 'ast_cma',
 'stl': 'stl_cma',
 'blk': 'blk_cma',
 'tov': 'tov_cma',
 'pf': 'pf_cma',
 'pts': 'pts_cma',
 'spread': 'spread_cma',
 'away_home': 'away_home_cma'}

In [36]:
df_sti_cma.rename(columns=column_names_cma_dict,inplace=True)
p(df_sti_cma)

(20532, 49)

,season,team_id,index,E_OFF_RATING_cma,OFF_RATING_cma,E_DEF_RATING_cma,DEF_RATING_cma,E_NET_RATING_cma,NET_RATING_cma,AST_PCT_cma,AST_TOV_cma,AST_RATIO_cma,OREB_PCT_cma,DREB_PCT_cma,REB_PCT_cma,E_TM_TOV_PCT_cma,TM_TOV_PCT_cma,EFG_PCT_cma,TS_PCT_cma,USG_PCT_cma,E_USG_PCT_cma,E_PACE_cma,PACE_cma,PACE_PER40_cma,POSS_cma,PIE_cma,duration_minutes_cma,w_pct_cma,min_cma,fgm_cma,fga_cma,fg_pct_cma,fg3m_cma,fg3a_cma,fg3_pct_cma,ftm_cma,fta_cma,ft_pct_cma,oreb_cma,dreb_cma,reb_cma,ast_cma,stl_cma,blk_cma,tov_cma,pf_cma,pts_cma,spread_cma,away_home_cma
0,2010-11,1610612737,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-11,1610612737,49,119.400000,120.200000,102.000000,105.100000,17.500000,15.200000,0.476000,1.330000,15.500000,0.000000,0.000000,0.000000,15.054000,15.200000,0.575000,0.635000,1.0,0.195000,100.820000,99.000000,82.500000,99.000000,0.619000,240.000000,1.000000,240.000000,42.000000,80.000000,0.525000,8.000000,16.000000,0.500000,27.000000,31.000000,0.870968,9.000000,35.000000,44.000000,20.000000,7.000000,9.000000,15.000000,20.000000,119.000000,-15.000000,0.000000
2,2010-11,1610612737,63,115.250000,115.400000,103.300000,106.250000,11.950000,9.200000,0.571500,1.265000,17.150000,0.148500,0.352000,0.269000,18.206000,18.250000,0.566000,0.628500,1.0,0.197000,97.950000,96.500000,80.415000,96.500000,0.575500,240.000000,1.000000,240.000000,39.000000,75.000000,0.519500,7.000000,16.500000,0.426500,26.500000,31.000000,0.854839,9.500000,35.500000,45.000000,22.000000,5.000000,8.500000,17.500000,23.000000,111.500000,-9.000000,0.000000
3,2010-11,1610612737,97,110.433333,112.033333,102.100000,104.533333,8.333333,7.566667,0.567333,1.216667,16.300000,0.238000,0.480667,0.368333,17.908000,18.200000,0.527667,0.594000,1.0,0.198000,97.540000,95.666667,79.720000,95.666667,0.552667,240.000000,1.000000,240.000000,37.333333,77.000000,0.486333,6.333333,17.333333,0.372000,26.333333,30.666667,0.858781,10.666667,33.666667,44.333333,21.000000,4.666667,7.000000,17.000000,22.666667,107.333333,-7.333333,0.333333
4,2010-11,1610612737,112,110.550000,112.125000,101.175000,102.850000,9.375000,9.325000,0.601250,1.840000,17.225000,0.253500,0.536750,0.398500,15.371250,15.625000,0.513250,0.574000,1.0,0.198000,95.610000,94.125000,78.435000,94.000000,0.565250,240.000000,1.000000,240.000000,37.250000,78.750000,0.474750,6.000000,17.250000,0.352500,25.000000,30.500000,0.819086,11.500000,32.500000,44.000000,22.250000,5.250000,7.000000,14.500000,21.250000,105.500000,-8.500000,0.250000
20527,2017-18,1610612766,20217,110.041667,111.875000,109.333333,111.075000,0.716667,0.808333,0.518667,1.765833,15.691667,0.263000,0.750583,0.511917,12.007333,12.200000,0.516417,0.565000,1.0,0.198833,101.743333,100.208333,83.505833,101.250000,0.515000,242.083333,0.435583,242.083333,40.500000,87.500000,0.463417,9.333333,26.500000,0.331833,23.000000,29.416667,0.784947,9.916667,37.416667,47.333333,21.083333,6.500000,4.083333,12.083333,15.583333,113.333333,-1.416667,0.416667
20528,2017-18,1610612766,20228,109.425000,111.133333,108.791667,110.283333,0.641667,0.858333,0.523000,1.732500,15.566667,0.263083,0.752333,0.511250,12.260167,12.441667,0.512333,0.561750,1.0,0.199167,101.721667,100.333333,83.610000,101.250000,0.511833,242.083333,0.436583,242.083333,39.833333,87.250000,0.456750,9.750000,27.416667,0.339250,23.166667,29.750000,0.781679,10.166667,37.500000,47.666667,20.916667,6.750000,4.250000,12.333333,14.916667,112.583333,-1.166667,0.416667
20529,2017-18,1610612766,20270,108.833333,110.483333,108.958333,110.400000,-0.116667,0.083333,0.527583,1.665833,15.541667,0.262583,0.745917,0.509500,12.910583,13.091667,0.511833,0.561250,1.0,0.199083,101.805000,100.458333,83.714167,101.250000,0.506750,242.083333,0.436333,242.083333,39.500000,86.750000,0.455750,9.750000,27.583333,0.337250,23.166667,29.833333,0.779364,10.416667,37.916667,48.333333,20.916667,6.083333,4.166667,13.000000,14.750000,111.916667,-0.083333,0.333333
20530,2017-18,1610612766,20305,111.616667,113.091667,108.175000,109.541667,3.450000,3.550000,0.542417,1.801667,16.125000,0.269917,0.751417,0.518500,12.683583,12.841667,0.523083,0.573167,1.0,0.199250,101.011667,99.791667,83.159167,100.583333,0.524167,242.083333,0.437333,242.083333,39.750000,86.166667,0.461917,10.583333,28.000000,0.360500,23.666667,30.166667,0.788105,10.500000,38.250000,48.750000,21.750000,5.750000,3.833333,12.666667,14.916667,113.750000,-3.500000,0.333333
20531,2017-18,1610612766,20339,110.225000,111.600000,108.508333,109.391667,1.725000,2.200000,0.544333,1.659167,15.933333,0.269917,0.755083,0.520000,13.486417,13.641667,0.518333,0.571833,1.0,0.199583,101.281667,100.333333,83.610833,101.083333,0.517833,242.083333,0.437083,242.083333,39.250000,85.583333,0.459500,10.083333,27.750000,0.348167,24.166667,30.166667,0.804772,10.416667,37.583333,48.000000,21.500000,6.000000,3.833333,13.583333,14.583333,112.750000,-2.000000,0.416667

In [37]:
df_giti = df_giti.reset_index()
p(df_giti)

(20532, 62)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year,a,b
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20528,20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20529,20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20530,20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20531,20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW

In [42]:
df_merged = pd.merge(df_giti, df_sti_cma, on=['index', 'team_id', 'season'], how='inner')
p(df_merged)

(20532, 108)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year,a,b,E_OFF_RATING_cma,OFF_RATING_cma,E_DEF_RATING_cma,DEF_RATING_cma,E_NET_RATING_cma,NET_RATING_cma,AST_PCT_cma,AST_TOV_cma,AST_RATIO_cma,OREB_PCT_cma,DREB_PCT_cma,REB_PCT_cma,E_TM_TOV_PCT_cma,TM_TOV_PCT_cma,EFG_PCT_cma,TS_PCT_cma,USG_PCT_cma,E_USG_PCT_cma,E_PACE_cma,PACE_cma,PACE_PER40_cma,POSS_cma,PIE_cma,duration_minutes_cma,w_pct_cma,min_cma,fgm_cma,fga_cma,fg_pct_cma,fg3m_cma,fg3a_cma,fg3_pct_cma,ftm_cma,fta_cma,ft_pct_cma,oreb_cma,dreb_cma,reb_cma,ast_cma,stl_cma,blk_cma,tov_cma,pf_cma,pts_cma,spread_cma,away_home_cma
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,110.100000,110.766667,100.825000,102.433333,9.283333,8.333333,0.601083,2.107500,18.408333,0.231917,0.738167,0.495083,12.910833,13.033333,0.538333,0.574750,1.0,0.198500,100.480833,99.339167,82.782500,99.916667,0.556833,242.083333,0.696250,242.083333,41.333333,87.666667,0.471500,11.583333,32.666667,0.351417,16.416667,19.833333,0.822012,8.666667,35.416667,44.083333,25.000000,9.250000,5.083333,12.500000,19.166667,110.666667,-7.833333,0.500000
20528,20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,111.650000,112.333333,101.166667,102.491667,10.491667,9.833333,0.581000,2.114167,18.250000,0.238667,0.727917,0.493750,12.758167,12.875000,0.548417,0.581500,1.0,0.198583,99.140833,98.172500,81.810000,98.666667,0.559333,242.083333,0.696250,242.083333,41.666667,86.916667,0.479833,11.750000,32.333333,0.359083,15.666667,19.333333,0.805698,8.666667,34.750000,43.416667,24.333333,8.666667,5.083333,12.166667,19.750000,110.750000,-9.000000,0.500000
20529,20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,109.691667,111.725000,107.833333,109.991667,1.858333,1.716667,0.511000,2.107500,15.833333,0.276083,0.768583,0.527750,12.747417,12.975000,0.534333,0.569583,1.0,0.197000,94.514167,92.755833,77.295833,94.083333,0.514917,242.083333,0.442000,242.083333,38.916667,82.166667,0.473917,9.750000,28.916667,0.340500,17.500000,23.166667,0.750092,8.833333,33.083333,41.916667,19.750000,5.750000,4.833333,11.333333,18.750000,105.083333,-2.666667,0.416667
20530,20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,113.466667,113.916667,100.466667,101.908333,13.000000,12.008333,0.582167,2.165833,18.683333,0.237333,0.720500,0.493167,12.781167,12.866667,0.560500,0.592500,1.0,0.198667,98.354167,97.464167,81.220000,98.000000,0.573750,242.083333,0.724000,242.083333,42.250000,86.000000,0.491417,11.750000,31.916667,0.363750,15.333333,18.750000,0.812952,8.333333,34.500000,42.833333,24.750000,8.250000,5.166667,12.000000,20.000000,111.583333,-11.250000,0.500000
20531,20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,106.750000,108.950000,107.566667,109.666667,-0.825000,-0.741667,0.511000,1.532500,15.375000,0.292750,0.765500,0.531750,13.660667,13.925000,0.519583,0.555667,1.0,0.196917,94.884167,93.047500,77.539167,94.416667,0.502833,242.083333,0.358667,242.083333,38.083333,82.833333,0.460583,9.583333,29.333333,0.329417,17.166667,22.666667,0.752223,9.666667,33.333333,43.000000,19.333333,5.833333,4.916667,12.166667,19.083333,102.916667,-0.500000,0.500000

In [45]:
#fillna cma columns with 0 (leading into taking the differences)

df_merged[column_names_list_cma] = df_merged[column_names_list_cma].fillna(0)
p(df_merged)

(20532, 108)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year,a,b,E_OFF_RATING_cma,OFF_RATING_cma,E_DEF_RATING_cma,DEF_RATING_cma,E_NET_RATING_cma,NET_RATING_cma,AST_PCT_cma,AST_TOV_cma,AST_RATIO_cma,OREB_PCT_cma,DREB_PCT_cma,REB_PCT_cma,E_TM_TOV_PCT_cma,TM_TOV_PCT_cma,EFG_PCT_cma,TS_PCT_cma,USG_PCT_cma,E_USG_PCT_cma,E_PACE_cma,PACE_cma,PACE_PER40_cma,POSS_cma,PIE_cma,duration_minutes_cma,w_pct_cma,min_cma,fgm_cma,fga_cma,fg_pct_cma,fg3m_cma,fg3a_cma,fg3_pct_cma,ftm_cma,fta_cma,ft_pct_cma,oreb_cma,dreb_cma,reb_cma,ast_cma,stl_cma,blk_cma,tov_cma,pf_cma,pts_cma,spread_cma,away_home_cma
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,110.100000,110.766667,100.825000,102.433333,9.283333,8.333333,0.601083,2.107500,18.408333,0.231917,0.738167,0.495083,12.910833,13.033333,0.538333,0.574750,1.0,0.198500,100.480833,99.339167,82.782500,99.916667,0.556833,242.083333,0.696250,242.083333,41.333333,87.666667,0.471500,11.583333,32.666667,0.351417,16.416667,19.833333,0.822012,8.666667,35.416667,44.083333,25.000000,9.250000,5.083333,12.500000,19.166667,110.666667,-7.833333,0.500000
20528,20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,111.650000,112.333333,101.166667,102.491667,10.491667,9.833333,0.581000,2.114167,18.250000,0.238667,0.727917,0.493750,12.758167,12.875000,0.548417,0.581500,1.0,0.198583,99.140833,98.172500,81.810000,98.666667,0.559333,242.083333,0.696250,242.083333,41.666667,86.916667,0.479833,11.750000,32.333333,0.359083,15.666667,19.333333,0.805698,8.666667,34.750000,43.416667,24.333333,8.666667,5.083333,12.166667,19.750000,110.750000,-9.000000,0.500000
20529,20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,109.691667,111.725000,107.833333,109.991667,1.858333,1.716667,0.511000,2.107500,15.833333,0.276083,0.768583,0.527750,12.747417,12.975000,0.534333,0.569583,1.0,0.197000,94.514167,92.755833,77.295833,94.083333,0.514917,242.083333,0.442000,242.083333,38.916667,82.166667,0.473917,9.750000,28.916667,0.340500,17.500000,23.166667,0.750092,8.833333,33.083333,41.916667,19.750000,5.750000,4.833333,11.333333,18.750000,105.083333,-2.666667,0.416667
20530,20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,113.466667,113.916667,100.466667,101.908333,13.000000,12.008333,0.582167,2.165833,18.683333,0.237333,0.720500,0.493167,12.781167,12.866667,0.560500,0.592500,1.0,0.198667,98.354167,97.464167,81.220000,98.000000,0.573750,242.083333,0.724000,242.083333,42.250000,86.000000,0.491417,11.750000,31.916667,0.363750,15.333333,18.750000,0.812952,8.333333,34.500000,42.833333,24.750000,8.250000,5.166667,12.000000,20.000000,111.583333,-11.250000,0.500000
20531,20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,106.750000,108.950000,107.566667,109.666667,-0.825000,-0.741667,0.511000,1.532500,15.375000,0.292750,0.765500,0.531750,13.660667,13.925000,0.519583,0.555667,1.0,0.196917,94.884167,93.047500,77.539167,94.416667,0.502833,242.083333,0.358667,242.083333,38.083333,82.833333,0.460583,9.583333,29.333333,0.329417,17.166667,22.666667,0.752223,9.666667,33.333333,43.000000,19.333333,5.833333,4.916667,12.166667,19.083333,102.916667,-0.500000,0.500000

In [55]:
#drop columns... 'index'
df_merged.drop(columns=['index'], inplace=True)
p(df_merged)

(20532, 107)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home,game_date,matchup,season_type,season,season_year,a,b,E_OFF_RATING_cma,OFF_RATING_cma,E_DEF_RATING_cma,DEF_RATING_cma,E_NET_RATING_cma,NET_RATING_cma,AST_PCT_cma,AST_TOV_cma,AST_RATIO_cma,OREB_PCT_cma,DREB_PCT_cma,REB_PCT_cma,E_TM_TOV_PCT_cma,TM_TOV_PCT_cma,EFG_PCT_cma,TS_PCT_cma,USG_PCT_cma,E_USG_PCT_cma,E_PACE_cma,PACE_cma,PACE_PER40_cma,POSS_cma,PIE_cma,duration_minutes_cma,w_pct_cma,min_cma,fgm_cma,fga_cma,fg_pct_cma,fg3m_cma,fg3a_cma,fg3_pct_cma,ftm_cma,fta_cma,ft_pct_cma,oreb_cma,dreb_cma,reb_cma,ast_cma,stl_cma,blk_cma,tov_cma,pf_cma,pts_cma,spread_cma,away_home_cma
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,110.100000,110.766667,100.825000,102.433333,9.283333,8.333333,0.601083,2.107500,18.408333,0.231917,0.738167,0.495083,12.910833,13.033333,0.538333,0.574750,1.0,0.198500,100.480833,99.339167,82.782500,99.916667,0.556833,242.083333,0.696250,242.083333,41.333333,87.666667,0.471500,11.583333,32.666667,0.351417,16.416667,19.833333,0.822012,8.666667,35.416667,44.083333,25.000000,9.250000,5.083333,12.500000,19.166667,110.666667,-7.833333,0.500000
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,111.650000,112.333333,101.166667,102.491667,10.491667,9.833333,0.581000,2.114167,18.250000,0.238667,0.727917,0.493750,12.758167,12.875000,0.548417,0.581500,1.0,0.198583,99.140833,98.172500,81.810000,98.666667,0.559333,242.083333,0.696250,242.083333,41.666667,86.916667,0.479833,11.750000,32.333333,0.359083,15.666667,19.333333,0.805698,8.666667,34.750000,43.416667,24.333333,8.666667,5.083333,12.166667,19.750000,110.750000,-9.000000,0.500000
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,109.691667,111.725000,107.833333,109.991667,1.858333,1.716667,0.511000,2.107500,15.833333,0.276083,0.768583,0.527750,12.747417,12.975000,0.534333,0.569583,1.0,0.197000,94.514167,92.755833,77.295833,94.083333,0.514917,242.083333,0.442000,242.083333,38.916667,82.166667,0.473917,9.750000,28.916667,0.340500,17.500000,23.166667,0.750092,8.833333,33.083333,41.916667,19.750000,5.750000,4.833333,11.333333,18.750000,105.083333,-2.666667,0.416667
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,113.466667,113.916667,100.466667,101.908333,13.000000,12.008333,0.582167,2.165833,18.683333,0.237333,0.720500,0.493167,12.781167,12.866667,0.560500,0.592500,1.0,0.198667,98.354167,97.464167,81.220000,98.000000,0.573750,242.083333,0.724000,242.083333,42.250000,86.000000,0.491417,11.750000,31.916667,0.363750,15.333333,18.750000,0.812952,8.333333,34.500000,42.833333,24.750000,8.250000,5.166667,12.000000,20.000000,111.583333,-11.250000,0.500000
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,106.750000,108.950000,107.566667,109.666667,-0.825000,-0.741667,0.511000,1.532500,15.375000,0.292750,0.765500,0.531750,13.660667,13.925000,0.519583,0.555667,1.0,0.196917,94.884167,93.047500,77.539167,94.416667,0.502833,242.083333,0.358667,242.083333,38.083333,82.833333,0.460583,9.583333,29.333333,0.329417,17.166667,22.666667,0.752223,9.666667,33.333333,43.000000,19.333333,5.833333,4.916667,12.166667,19.083333,102.916667,-0.500000,0.500000