In [1]:
#########################################################
#get numeric data: df_numerics

#get numeric columns: col_names_numeric


############################################################

#get team matchup differences for each stats

#use list col_names_numeric 

#get string before _away of col_names_numeric: col_names_numeric_stats

#use contains with appended _away - contains with append _home to get stat difference

#######################################################################################

#get team matchup stat dif. cma for each stat difference (per matchup per season)


######################################################################
#get median matchup stat dif for each stat difference (per matchup per season)


################################################################################

#get team matchup stat dif. cma log() for each stat difference (per matchup per season)

#get team matchup stat dif. log() for each stat difference (per matchup per season)

#get team matchup stat dif. ln for each stat difference (per matchup per season)

#get team matchup stat dif. cma ln for each stat difference (per matchup per season)


################################################

# fix cma to exclude the current row ####<<<<<<<<<<<<<<<<

In [ ]:
################################################################################

#get team matchup stat dif. cma log() for each stat difference (per matchup per season)

#get team matchup stat dif. log() for each stat difference (per matchup per season)

#get team matchup stat dif. ln for each stat difference (per matchup per season)

#get team matchup stat dif. cma ln for each stat difference (per matchup per season)

In [ ]:
#######################################################################

#get team matchup stat dif. cma3 for each stat difference (per matchup per season)

#get team matchup stat dif. cma5 for each stat difference (per matchup per season)

#get team matchup stat dif. cma3 ln for each stat difference (per matchup per season)

#get team matchup stat dif. cma3 log() for each stat difference (per matchup per season)

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [3]:
df = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv')
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
3,21000016,2010-10-27,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,107.6,108.9,94.4,97.8,13.1,11.1,0.472,1.21,13.2,0.446,0.627,0.533,15.364,15.6,0.455,0.499,1.0,0.198,92.16,90.00,75.00,90,0.551,240.0,94.4,97.8,107.6,108.9,-13.1,-11.1,0.594,1.27,15.1,0.373,0.554,0.467,16.094,16.7,0.437,0.477,1.0,0.200,92.16,90.00,75.00,90,0.449,240.0,LAC vs. POR,1610612757,1.000,240,36,88,0.409,8,20,0.400,18,23,0.782609,21,30,51,17,9,6,12,23,98,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,0.633333,14,27,41,19,8,8,15,20,88,Regular Season,2010-11,2010,W,L,10,-10
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,BOS vs. CLE,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010,L,W,-8,8
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [4]:
#rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018_col_descriptions.csv')

In [5]:
#########################################################
#get numeric data: df_numerics

#get numeric columns: col_names_numeric

In [6]:
df_numerics = df.select_dtypes('number')
p(df_numerics)

(10266, 94)

,game_id,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_year,spread_home,spread_away
0,21000001,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,2010,-8,8
1,21000002,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,2010,-14,14
2,21000003,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,2010,-2,2
3,21000016,107.6,108.9,94.4,97.8,13.1,11.1,0.472,1.21,13.2,0.446,0.627,0.533,15.364,15.6,0.455,0.499,1.0,0.198,92.16,90.00,75.00,90,0.551,240.0,94.4,97.8,107.6,108.9,-13.1,-11.1,0.594,1.27,15.1,0.373,0.554,0.467,16.094,16.7,0.437,0.477,1.0,0.200,92.16,90.00,75.00,90,0.449,240.0,1610612757,1.000,240,36,88,0.409,8,20,0.400,18,23,0.782609,21,30,51,17,9,6,12,23,98,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,0.633333,14,27,41,19,8,8,15,20,88,2010,10,-10
4,21000004,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,2010,-8,8
10261,41700317,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,2017,9,-9
10262,41700401,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,2017,-10,10
10263,41700402,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,2017,-19,19
10264,41700403,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,2017,8,-8
10265,41700404,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,2017,23,-23

In [7]:
col_names_numeric = list(df_numerics.columns)
col_names_numeric

['game_id',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'season_year',
 'spread_home',
 'spread_away']

In [8]:
############################################################

#get team matchup differences for each stats


#use list col_names_numeric 

#get string before _away of col_names_numeric: col_names_numeric_stats

#use contains with appended _away - contains with append _home to get stat difference

In [9]:
print(len(col_names_numeric))
col_names_numeric


#difference of those ending with _away or _home, but not including team_id? #####################<<<<<<<<<<<<<

94

['game_id',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'team_id_away',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'team_id_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'season_year',
 'spread_home',
 'spread_away']

In [10]:
#difference of those ending with _away or _home, but not including team_id? *stat* + _ah_diff

list_giah = [i for i in col_names_numeric if i not in ['team_id_away', 'team_id_home', 'season_year']]
list_giah

['game_id',
 'E_OFF_RATING_away',
 'OFF_RATING_away',
 'E_DEF_RATING_away',
 'DEF_RATING_away',
 'E_NET_RATING_away',
 'NET_RATING_away',
 'AST_PCT_away',
 'AST_TOV_away',
 'AST_RATIO_away',
 'OREB_PCT_away',
 'DREB_PCT_away',
 'REB_PCT_away',
 'E_TM_TOV_PCT_away',
 'TM_TOV_PCT_away',
 'EFG_PCT_away',
 'TS_PCT_away',
 'USG_PCT_away',
 'E_USG_PCT_away',
 'E_PACE_away',
 'PACE_away',
 'PACE_PER40_away',
 'POSS_away',
 'PIE_away',
 'duration_minutes_away',
 'E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'w_pct_away',
 'min_away',
 'fgm_away',
 'fga_away',
 'fg_pct_away',
 'fg3m_away',
 'fg3a_away',
 'fg3_pct_away',
 'ftm_away',
 'fta_away',
 'ft_pct_away',
 'oreb_away',
 'dreb_away',
 'reb_away',
 'ast_away',
 'stl_away',
 'blk_away',
 'tov_away',
 'pf_away',
 'pts_away',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'spread_home',
 'spread_away']

In [11]:
len(list_giah)

91

In [12]:
#get prefix to _away and _home and store as unique list

list_stats_h =  [i for i in list_giah if '_home' in i]
list_stats_h

['E_OFF_RATING_home',
 'OFF_RATING_home',
 'E_DEF_RATING_home',
 'DEF_RATING_home',
 'E_NET_RATING_home',
 'NET_RATING_home',
 'AST_PCT_home',
 'AST_TOV_home',
 'AST_RATIO_home',
 'OREB_PCT_home',
 'DREB_PCT_home',
 'REB_PCT_home',
 'E_TM_TOV_PCT_home',
 'TM_TOV_PCT_home',
 'EFG_PCT_home',
 'TS_PCT_home',
 'USG_PCT_home',
 'E_USG_PCT_home',
 'E_PACE_home',
 'PACE_home',
 'PACE_PER40_home',
 'POSS_home',
 'PIE_home',
 'duration_minutes_home',
 'w_pct_home',
 'min_home',
 'fgm_home',
 'fga_home',
 'fg_pct_home',
 'fg3m_home',
 'fg3a_home',
 'fg3_pct_home',
 'ftm_home',
 'fta_home',
 'ft_pct_home',
 'oreb_home',
 'dreb_home',
 'reb_home',
 'ast_home',
 'stl_home',
 'blk_home',
 'tov_home',
 'pf_home',
 'pts_home',
 'spread_home']

In [13]:
list_stats = [i.split('_home')[0] for i in list_stats_h]
list_stats

['E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread']

In [14]:
len(list_stats)

45

In [15]:
# _ah_diff
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
3,21000016,2010-10-27,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,107.6,108.9,94.4,97.8,13.1,11.1,0.472,1.21,13.2,0.446,0.627,0.533,15.364,15.6,0.455,0.499,1.0,0.198,92.16,90.00,75.00,90,0.551,240.0,94.4,97.8,107.6,108.9,-13.1,-11.1,0.594,1.27,15.1,0.373,0.554,0.467,16.094,16.7,0.437,0.477,1.0,0.200,92.16,90.00,75.00,90,0.449,240.0,LAC vs. POR,1610612757,1.000,240,36,88,0.409,8,20,0.400,18,23,0.782609,21,30,51,17,9,6,12,23,98,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,0.633333,14,27,41,19,8,8,15,20,88,Regular Season,2010-11,2010,W,L,10,-10
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,BOS vs. CLE,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010,L,W,-8,8
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [16]:
for stat in list_stats:
    df[stat + '_ah_diff'] = df[stat + '_away'] - df[stat + '_home']

In [17]:
list_stat_ah_diff = []
for stat in list_stats:
    list_stat_ah_diff.append(stat + '_ah_diff')

In [18]:
list_stat_ah_diff

['E_OFF_RATING_ah_diff',
 'OFF_RATING_ah_diff',
 'E_DEF_RATING_ah_diff',
 'DEF_RATING_ah_diff',
 'E_NET_RATING_ah_diff',
 'NET_RATING_ah_diff',
 'AST_PCT_ah_diff',
 'AST_TOV_ah_diff',
 'AST_RATIO_ah_diff',
 'OREB_PCT_ah_diff',
 'DREB_PCT_ah_diff',
 'REB_PCT_ah_diff',
 'E_TM_TOV_PCT_ah_diff',
 'TM_TOV_PCT_ah_diff',
 'EFG_PCT_ah_diff',
 'TS_PCT_ah_diff',
 'USG_PCT_ah_diff',
 'E_USG_PCT_ah_diff',
 'E_PACE_ah_diff',
 'PACE_ah_diff',
 'PACE_PER40_ah_diff',
 'POSS_ah_diff',
 'PIE_ah_diff',
 'duration_minutes_ah_diff',
 'w_pct_ah_diff',
 'min_ah_diff',
 'fgm_ah_diff',
 'fga_ah_diff',
 'fg_pct_ah_diff',
 'fg3m_ah_diff',
 'fg3a_ah_diff',
 'fg3_pct_ah_diff',
 'ftm_ah_diff',
 'fta_ah_diff',
 'ft_pct_ah_diff',
 'oreb_ah_diff',
 'dreb_ah_diff',
 'reb_ah_diff',
 'ast_ah_diff',
 'stl_ah_diff',
 'blk_ah_diff',
 'tov_ah_diff',
 'pf_ah_diff',
 'pts_ah_diff',
 'spread_ah_diff']

In [19]:
p(df)

(10266, 155)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8,-7.8,-7.8,7.8,7.8,-15.4,-15.4,-0.225,-0.37,-7.2,-0.018,-0.018,-0.056,-3.058,-3.0,-0.103,-0.079,0.0,0.004,0.0,0.0,0.0,-1,-0.198,0.0,-1.000,0,-5,5,-0.099,0,4,-0.100,2,0,0.080000,3,-6,-3,-10,4,2,-1,2,-8,16
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14,-10.8,-15.6,10.8,15.6,-21.6,-31.2,-0.304,-1.28,-8.3,-0.246,-0.246,-0.218,4.893,4.4,0.031,0.036,0.0,0.004,0.0,0.0,0.0,0,-0.250,0.0,-1.000,0,-7,-19,0.024,-1,-1,-0.026,1,1,0.020833,-11,-7,-18,-16,-8,2,7,-3,-14,28
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2,-3.7,-0.9,3.7,0.9,-7.6,-1.8,0.133,-0.56,1.8,0.091,0.091,0.108,8.100,8.9,-0.002,0.015,0.0,-0.002,0.0,0.0,0.0,-1,0.014,0.0,-1.000,0,-2,-5,0.001,-1,-1,-0.029,3,0,0.107143,2,7,9,4,-5,3,8,1,-2,4
3,21000016,2010-10-27,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,107.6,108.9,94.4,97.8,13.1,11.1,0.472,1.21,13.2,0.446,0.627,0.533,15.364,15.6,0.455,0.499,1.0,0.198,92.16,90.00,75.00,90,0.551,240.0,94.4,97.8,107.6,108.9,-13.1,-11.1,0.594,1.27,15.1,0.373,0.554,0.467,16.094,16.7,0.437,0.477,1.0,0.200,92.16,90.00,75.00,90,0.449,240.0,LAC vs. POR,1610612757,1.000,240,36,88,0.409,8,20,0.400,18,23,0.782609,21,30,51,17,9,6,12,23,98,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,0.633333,14,27,41,19,8,8,15,20,88,Regular Season,2010-11,2010,W,L,10,-10,13.2,11.1,-13.2,-11.1,26.2,22.2,-0.122,-0.06,-1.9,0.073,0.073,0.066,-0.730,-1.1,0.018,0.022,0.0,-0.002,0.0,0.0,0.0,0,0.102,0.0,1.000,0,4,9,0.004,3,2,0.122,-1,-7,0.149275,7,3,10,-2,1,-2,-3,3,10,-20
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,BOS vs. CLE,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010,L,W,-8,8,-5.4,-8.7,5.4,8.7,-10.8,-17.4,0.039,-0.34,0.7,-0.067,-0.067,-0.022,4.735,4.4,0.012,0.009,0.0,0.002,0.0,0.0,0.0,0,-0.046,0.0,-0.500,0,-2,-9,0.028,-3,-8,-0.050,-1,0,-0.047619,-2,3,1,0,3,-3,5,4,-8,16
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9,12.4,9.9,-12.4,-9.9,24.8,19.8,0.169,0.05,6.3,-0.026,-0.026,0.020,5.772,5.5,0.149,0.125,0.0,-0.001,0.0,0.0,0.0,0,0.136,0.0,0.142,0,3,-10,0.088,9,-5,0.251,-6,-8,-0.090909,-6,4,-2,8,-4,4,4,5,9,-18
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10,-8.5,-12.4,8.5,12.4,-17.0,-24.8,-0.265,-2.38,-9.5,0.226,0.226,0.176,4.020,3.8,-0.088,-0.104,0.0,0.002,0.0,0.0,0.0,2,-0.188,0.0,-1.000,0,-2,9,-0.067,-3,1,-0.091,-3,2,-0.222727,15,0,15,-13,-5,-3,4,0,-10,20
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19,-20.0,-23.6,20.0,23.6,-40.0,-47.2,0.080,-0.06,-3.1,0.093,0.093,0.032,-1.063,-1.5,-0.204,-0.161,0.0,-0.003,0.0,0.0,0.0,3,-0.130,0.0,-1.000,0,-10,8,-0.162,-6,-9,-0.084,7,5,0.150183,9,-8,1,-3,6,-4,-2,-10,-19,38
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8,13.0,9.6,-13.0,-9.6,26.0,19.4,0.143,1.02,6.2,-0.194,-0.194,-0.136,-2.559,-3.0,0.090,0.102,0.0,0.002,0.0,0.0,0.0,-1,0.138,0.0,1.000,0,2,-11,0.084,0,-5,0.056,4,2,0.130031,-9,-1,-10,7,0,1,-3,2,8,-16
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23,23.7,24.3,-23.7,-24.3,47.4,48.4,-0.059,0.59,3.3,-0.014,-0.014,0.028,-1.209,-1.2,0.144,0.146,0.0,-0.002,0.0,0.0,0.0,1,0.344,0.0,1.000,0,9,-1,0.108,6,11,0.072,-1,-9,0.320000,-7,7,0,4,2,8,-3,2,23,-46

In [20]:
#######################################################################################

#get team matchup stat dif. cma for each stat difference (per matchup per season)


######################################################################
#get median matchup stat dif for each stat difference (per matchup per season)


################################################################################


#get team matchup stat dif. cma log() for each stat difference (per matchup per season)

#get team matchup stat dif. cma ln for each stat difference (per matchup per season)


#######################################################################

#get team matchup stat dif. cma3 for each stat difference (per matchup per season)

#get team matchup stat dif. cma5 for each stat difference (per matchup per season)

#get team matchup stat dif. cma3 ln for each stat difference (per matchup per season)

#get team matchup stat dif. cma3 log() for each stat difference (per matchup per season)

In [21]:
#######################################################################################

#get team matchup stat dif. (i.e. list_stat_ah_diff) cma for each stat difference (per matchup per season)

In [22]:
#sort by date and reset index
df.sort_values('game_date', inplace=True)
df = df.reset_index(drop=True)

#groupby matchup and season and take cma of stat differences
df_stats_ah_diff_cma = df.groupby(['season', 'matchup'])[list_stat_ah_diff].expanding(min_periods=0).mean().reset_index()

#keep the original index
df_stats_ah_diff_cma.rename(columns={'level_2':'index'}, inplace=True)
p(df_stats_ah_diff_cma)

(10266, 48)

,season,matchup,index,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff
0,2010-11,ATL vs. BOS,197,27.900,24.600000,-27.900,-24.600000,55.800000,49.200000,-0.100000,-0.220000,3.300000,0.139000,0.139000,0.22200,5.930000,5.400000,0.184000,0.168000,0.0,-0.003000,0.0,0.0,0.0,1.000000,0.398000,0.0,0.143000,0.0,12.000000,-6.000000,0.187000,-1.000000,-5.000000,0.080000,0.000000,1.000000,-0.045752,2.000000,18.000000,20.000000,5.000000,1.000000,5.000000,3.000000,1.000000,23.000000,-46.000000
1,2010-11,ATL vs. BOS,377,9.800,6.050000,-9.800,-6.050000,19.600000,12.100000,-0.132500,-0.830000,-2.200000,-0.085500,0.414500,0.11100,6.757500,6.250000,0.070000,0.080000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.134000,0.0,-0.052000,0.0,1.000000,-10.500000,0.078500,-2.000000,-6.500000,0.023500,5.500000,7.000000,0.009321,1.500000,10.500000,12.000000,-3.500000,-0.500000,3.000000,4.500000,-0.500000,5.500000,-11.000000
2,2010-11,ATL vs. BOS,1122,5.500,2.133333,-5.500,-2.133333,11.066667,4.266667,-0.027000,0.203333,1.166667,-0.159667,0.507000,0.07400,3.056667,2.633333,0.078000,0.061333,0.0,0.000000,0.0,0.0,0.0,0.000000,0.095333,0.0,0.003333,0.0,2.000000,-8.666667,0.078667,-0.666667,-5.666667,0.099000,-1.333333,1.333333,-0.099341,-2.666667,6.000000,3.333333,0.333333,0.666667,3.333333,1.666667,1.333333,2.000000,-4.000000
3,2010-11,ATL vs. CHA,389,-9.100,-4.600000,9.100,4.600000,-18.200000,-9.200000,-0.122000,-0.210000,-5.400000,0.418000,-0.582000,0.00000,-2.781000,-2.100000,-0.109000,-0.094000,0.0,-0.010000,0.0,0.0,0.0,-1.000000,-0.094000,0.0,-0.261000,0.0,-3.000000,9.000000,-0.083000,-4.000000,-11.000000,-0.097000,5.000000,7.000000,-0.073077,7.000000,-1.000000,6.000000,-6.000000,4.000000,-5.000000,-7.000000,-5.000000,-5.000000,10.000000
4,2010-11,ATL vs. CHA,648,1.000,7.000000,-1.000,-7.000000,2.000000,14.000000,-0.123500,-0.465000,-4.400000,0.340500,-0.659500,0.00000,-0.665000,0.150000,-0.023500,-0.001500,0.0,-0.004500,0.0,0.0,0.0,-0.500000,0.016000,0.0,-0.011000,0.0,-1.000000,2.500000,-0.022000,-0.500000,-5.000000,0.022000,8.000000,9.000000,0.023244,2.000000,2.500000,4.500000,-5.000000,2.500000,-2.500000,-2.000000,-3.500000,5.500000,-11.000000
10261,2017-18,TOR vs. WAS,10213,-6.525,-4.575000,6.525,4.575000,-13.075000,-9.125000,-0.026250,-0.102500,-1.575000,-0.022875,-0.022750,-0.03525,0.173000,0.512500,-0.025375,-0.022250,0.0,0.000000,0.0,0.0,0.0,-0.375000,-0.069000,0.0,-0.191250,0.0,-2.625000,-1.000000,-0.026625,0.125000,-3.625000,0.063125,0.125000,0.375000,-0.000295,-1.875000,-3.250000,-5.125000,-2.625000,0.875000,-2.750000,0.625000,-0.250000,-5.000000,10.000000
10262,2017-18,TOR vs. WAS,10222,-7.500,-4.955556,7.500,4.955556,-15.022222,-9.888889,-0.036222,-0.250000,-1.944444,-0.000222,-0.000111,-0.01400,0.952667,1.388889,-0.032667,-0.028778,0.0,-0.000889,0.0,0.0,0.0,-0.555556,-0.074222,0.0,-0.192222,0.0,-2.444444,0.000000,-0.029444,-0.555556,-3.111111,0.028556,-0.111111,-0.333333,0.012364,-0.777778,-2.111111,-2.888889,-2.888889,0.444444,-2.555556,1.111111,-0.222222,-5.555556,11.111111
10263,2017-18,TOR vs. WAS,10225,-5.420,-3.470000,5.420,3.470000,-10.860000,-6.900000,-0.025100,-0.054000,-1.340000,0.004300,0.004500,-0.00960,0.106300,0.460000,-0.026700,-0.026100,0.0,-0.001000,0.0,0.0,0.0,-0.400000,-0.051200,0.0,-0.139600,0.0,-1.400000,1.100000,-0.022600,-0.600000,-2.500000,0.017300,-0.600000,-0.500000,-0.005163,-0.200000,-1.900000,-2.100000,-2.000000,0.900000,-2.200000,0.200000,-0.100000,-4.000000,8.000000
10264,2017-18,UTA vs. WAS,9293,-53.300,-49.400000,53.300,49.400000,-106.600000,-98.800000,-0.283000,-1.120000,-14.500000,-0.100000,-0.100000,-0.22600,-3.527000,-3.000000,-0.358000,-0.308000,0.0,0.004000,0.0,0.0,0.0,-2.000000,-0.768000,0.0,-0.020000,0.0,-20.000000,4.000000,-0.278000,-12.000000,-14.000000,-0.271000,5.000000,5.000000,0.048309,2.000000,-23.000000,-21.000000,-20.000000,-1.000000,-1.000000,-3.000000,1.000000,-47.000000,94.000000
10265,2017-18,UTA vs. WAS,9557,-25.250,-22.600000,25.250,22.600000,-50.500000,-45.200000,-0.179000,-0.220000,-8.000000,-0.062500,-0.062500,-0.15100,-6.805000,-6.550000,-0.210500,-0.184500,0.0,0.001000,0.0,0.0,0.0,-1.500000,-0.379000,0.0,-0.083000,0.0,-9.000000,9.000000,-0.168500,-5.500000,-3.000000,-0.169000,1.500000,0.500000,0.055829,2.000000,-15.500000,-13.500000,-11.000000,3.000000,0.500000,-7.000000,0.500000,-22.000000,44.000000

In [23]:
#create lists and then dictionary for new df column renaming
list_stats_ah_diff = list(df_stats_ah_diff_cma.columns)
list_stats_ah_diff

['season',
 'matchup',
 'index',
 'E_OFF_RATING_ah_diff',
 'OFF_RATING_ah_diff',
 'E_DEF_RATING_ah_diff',
 'DEF_RATING_ah_diff',
 'E_NET_RATING_ah_diff',
 'NET_RATING_ah_diff',
 'AST_PCT_ah_diff',
 'AST_TOV_ah_diff',
 'AST_RATIO_ah_diff',
 'OREB_PCT_ah_diff',
 'DREB_PCT_ah_diff',
 'REB_PCT_ah_diff',
 'E_TM_TOV_PCT_ah_diff',
 'TM_TOV_PCT_ah_diff',
 'EFG_PCT_ah_diff',
 'TS_PCT_ah_diff',
 'USG_PCT_ah_diff',
 'E_USG_PCT_ah_diff',
 'E_PACE_ah_diff',
 'PACE_ah_diff',
 'PACE_PER40_ah_diff',
 'POSS_ah_diff',
 'PIE_ah_diff',
 'duration_minutes_ah_diff',
 'w_pct_ah_diff',
 'min_ah_diff',
 'fgm_ah_diff',
 'fga_ah_diff',
 'fg_pct_ah_diff',
 'fg3m_ah_diff',
 'fg3a_ah_diff',
 'fg3_pct_ah_diff',
 'ftm_ah_diff',
 'fta_ah_diff',
 'ft_pct_ah_diff',
 'oreb_ah_diff',
 'dreb_ah_diff',
 'reb_ah_diff',
 'ast_ah_diff',
 'stl_ah_diff',
 'blk_ah_diff',
 'tov_ah_diff',
 'pf_ah_diff',
 'pts_ah_diff',
 'spread_ah_diff']

In [24]:
list_stats_ah_diff_dsmi = [k for k in list_stats_ah_diff if k not in ['season', 'matchup', 'index']]
list_stats_ah_diff_dsmi

['E_OFF_RATING_ah_diff',
 'OFF_RATING_ah_diff',
 'E_DEF_RATING_ah_diff',
 'DEF_RATING_ah_diff',
 'E_NET_RATING_ah_diff',
 'NET_RATING_ah_diff',
 'AST_PCT_ah_diff',
 'AST_TOV_ah_diff',
 'AST_RATIO_ah_diff',
 'OREB_PCT_ah_diff',
 'DREB_PCT_ah_diff',
 'REB_PCT_ah_diff',
 'E_TM_TOV_PCT_ah_diff',
 'TM_TOV_PCT_ah_diff',
 'EFG_PCT_ah_diff',
 'TS_PCT_ah_diff',
 'USG_PCT_ah_diff',
 'E_USG_PCT_ah_diff',
 'E_PACE_ah_diff',
 'PACE_ah_diff',
 'PACE_PER40_ah_diff',
 'POSS_ah_diff',
 'PIE_ah_diff',
 'duration_minutes_ah_diff',
 'w_pct_ah_diff',
 'min_ah_diff',
 'fgm_ah_diff',
 'fga_ah_diff',
 'fg_pct_ah_diff',
 'fg3m_ah_diff',
 'fg3a_ah_diff',
 'fg3_pct_ah_diff',
 'ftm_ah_diff',
 'fta_ah_diff',
 'ft_pct_ah_diff',
 'oreb_ah_diff',
 'dreb_ah_diff',
 'reb_ah_diff',
 'ast_ah_diff',
 'stl_ah_diff',
 'blk_ah_diff',
 'tov_ah_diff',
 'pf_ah_diff',
 'pts_ah_diff',
 'spread_ah_diff']

In [25]:
list_stats_ah_diff_dsmi_cma = [k + '_cma' for k in list_stats_ah_diff_dsmi]
list_stats_ah_diff_dsmi_cma

['E_OFF_RATING_ah_diff_cma',
 'OFF_RATING_ah_diff_cma',
 'E_DEF_RATING_ah_diff_cma',
 'DEF_RATING_ah_diff_cma',
 'E_NET_RATING_ah_diff_cma',
 'NET_RATING_ah_diff_cma',
 'AST_PCT_ah_diff_cma',
 'AST_TOV_ah_diff_cma',
 'AST_RATIO_ah_diff_cma',
 'OREB_PCT_ah_diff_cma',
 'DREB_PCT_ah_diff_cma',
 'REB_PCT_ah_diff_cma',
 'E_TM_TOV_PCT_ah_diff_cma',
 'TM_TOV_PCT_ah_diff_cma',
 'EFG_PCT_ah_diff_cma',
 'TS_PCT_ah_diff_cma',
 'USG_PCT_ah_diff_cma',
 'E_USG_PCT_ah_diff_cma',
 'E_PACE_ah_diff_cma',
 'PACE_ah_diff_cma',
 'PACE_PER40_ah_diff_cma',
 'POSS_ah_diff_cma',
 'PIE_ah_diff_cma',
 'duration_minutes_ah_diff_cma',
 'w_pct_ah_diff_cma',
 'min_ah_diff_cma',
 'fgm_ah_diff_cma',
 'fga_ah_diff_cma',
 'fg_pct_ah_diff_cma',
 'fg3m_ah_diff_cma',
 'fg3a_ah_diff_cma',
 'fg3_pct_ah_diff_cma',
 'ftm_ah_diff_cma',
 'fta_ah_diff_cma',
 'ft_pct_ah_diff_cma',
 'oreb_ah_diff_cma',
 'dreb_ah_diff_cma',
 'reb_ah_diff_cma',
 'ast_ah_diff_cma',
 'stl_ah_diff_cma',
 'blk_ah_diff_cma',
 'tov_ah_diff_cma',
 'pf_ah_diff_cma',
 'pts_ah_diff_cma',
 'spread_ah_diff_cma']

In [26]:
dict_stats_ah_diff_dsmi_cma = dict(zip(list_stats_ah_diff_dsmi, list_stats_ah_diff_dsmi_cma))
dict_stats_ah_diff_dsmi_cma

{'E_OFF_RATING_ah_diff': 'E_OFF_RATING_ah_diff_cma',
 'OFF_RATING_ah_diff': 'OFF_RATING_ah_diff_cma',
 'E_DEF_RATING_ah_diff': 'E_DEF_RATING_ah_diff_cma',
 'DEF_RATING_ah_diff': 'DEF_RATING_ah_diff_cma',
 'E_NET_RATING_ah_diff': 'E_NET_RATING_ah_diff_cma',
 'NET_RATING_ah_diff': 'NET_RATING_ah_diff_cma',
 'AST_PCT_ah_diff': 'AST_PCT_ah_diff_cma',
 'AST_TOV_ah_diff': 'AST_TOV_ah_diff_cma',
 'AST_RATIO_ah_diff': 'AST_RATIO_ah_diff_cma',
 'OREB_PCT_ah_diff': 'OREB_PCT_ah_diff_cma',
 'DREB_PCT_ah_diff': 'DREB_PCT_ah_diff_cma',
 'REB_PCT_ah_diff': 'REB_PCT_ah_diff_cma',
 'E_TM_TOV_PCT_ah_diff': 'E_TM_TOV_PCT_ah_diff_cma',
 'TM_TOV_PCT_ah_diff': 'TM_TOV_PCT_ah_diff_cma',
 'EFG_PCT_ah_diff': 'EFG_PCT_ah_diff_cma',
 'TS_PCT_ah_diff': 'TS_PCT_ah_diff_cma',
 'USG_PCT_ah_diff': 'USG_PCT_ah_diff_cma',
 'E_USG_PCT_ah_diff': 'E_USG_PCT_ah_diff_cma',
 'E_PACE_ah_diff': 'E_PACE_ah_diff_cma',
 'PACE_ah_diff': 'PACE_ah_diff_cma',
 'PACE_PER40_ah_diff': 'PACE_PER40_ah_diff_cma',
 'POSS_ah_diff': 'POSS_ah_diff_cma',
 'PIE_ah_diff': 'PIE_ah_diff_cma',
 'duration_minutes_ah_diff': 'duration_minutes_ah_diff_cma',
 'w_pct_ah_diff': 'w_pct_ah_diff_cma',
 'min_ah_diff': 'min_ah_diff_cma',
 'fgm_ah_diff': 'fgm_ah_diff_cma',
 'fga_ah_diff': 'fga_ah_diff_cma',
 'fg_pct_ah_diff': 'fg_pct_ah_diff_cma',
 'fg3m_ah_diff': 'fg3m_ah_diff_cma',
 'fg3a_ah_diff': 'fg3a_ah_diff_cma',
 'fg3_pct_ah_diff': 'fg3_pct_ah_diff_cma',
 'ftm_ah_diff': 'ftm_ah_diff_cma',
 'fta_ah_diff': 'fta_ah_diff_cma',
 'ft_pct_ah_diff': 'ft_pct_ah_diff_cma',
 'oreb_ah_diff': 'oreb_ah_diff_cma',
 'dreb_ah_diff': 'dreb_ah_diff_cma',
 'reb_ah_diff': 'reb_ah_diff_cma',
 'ast_ah_diff': 'ast_ah_diff_cma',
 'stl_ah_diff': 'stl_ah_diff_cma',
 'blk_ah_diff': 'blk_ah_diff_cma',
 'tov_ah_diff': 'tov_ah_diff_cma',
 'pf_ah_diff': 'pf_ah_diff_cma',
 'pts_ah_diff': 'pts_ah_diff_cma',
 'spread_ah_diff': 'spread_ah_diff_cma'}

In [27]:
df_stats_ah_diff_cma.rename(columns=dict_stats_ah_diff_dsmi_cma, inplace=True)

In [28]:
p(df_stats_ah_diff_cma)

(10266, 48)

,season,matchup,index,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma
0,2010-11,ATL vs. BOS,197,27.900,24.600000,-27.900,-24.600000,55.800000,49.200000,-0.100000,-0.220000,3.300000,0.139000,0.139000,0.22200,5.930000,5.400000,0.184000,0.168000,0.0,-0.003000,0.0,0.0,0.0,1.000000,0.398000,0.0,0.143000,0.0,12.000000,-6.000000,0.187000,-1.000000,-5.000000,0.080000,0.000000,1.000000,-0.045752,2.000000,18.000000,20.000000,5.000000,1.000000,5.000000,3.000000,1.000000,23.000000,-46.000000
1,2010-11,ATL vs. BOS,377,9.800,6.050000,-9.800,-6.050000,19.600000,12.100000,-0.132500,-0.830000,-2.200000,-0.085500,0.414500,0.11100,6.757500,6.250000,0.070000,0.080000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.134000,0.0,-0.052000,0.0,1.000000,-10.500000,0.078500,-2.000000,-6.500000,0.023500,5.500000,7.000000,0.009321,1.500000,10.500000,12.000000,-3.500000,-0.500000,3.000000,4.500000,-0.500000,5.500000,-11.000000
2,2010-11,ATL vs. BOS,1122,5.500,2.133333,-5.500,-2.133333,11.066667,4.266667,-0.027000,0.203333,1.166667,-0.159667,0.507000,0.07400,3.056667,2.633333,0.078000,0.061333,0.0,0.000000,0.0,0.0,0.0,0.000000,0.095333,0.0,0.003333,0.0,2.000000,-8.666667,0.078667,-0.666667,-5.666667,0.099000,-1.333333,1.333333,-0.099341,-2.666667,6.000000,3.333333,0.333333,0.666667,3.333333,1.666667,1.333333,2.000000,-4.000000
3,2010-11,ATL vs. CHA,389,-9.100,-4.600000,9.100,4.600000,-18.200000,-9.200000,-0.122000,-0.210000,-5.400000,0.418000,-0.582000,0.00000,-2.781000,-2.100000,-0.109000,-0.094000,0.0,-0.010000,0.0,0.0,0.0,-1.000000,-0.094000,0.0,-0.261000,0.0,-3.000000,9.000000,-0.083000,-4.000000,-11.000000,-0.097000,5.000000,7.000000,-0.073077,7.000000,-1.000000,6.000000,-6.000000,4.000000,-5.000000,-7.000000,-5.000000,-5.000000,10.000000
4,2010-11,ATL vs. CHA,648,1.000,7.000000,-1.000,-7.000000,2.000000,14.000000,-0.123500,-0.465000,-4.400000,0.340500,-0.659500,0.00000,-0.665000,0.150000,-0.023500,-0.001500,0.0,-0.004500,0.0,0.0,0.0,-0.500000,0.016000,0.0,-0.011000,0.0,-1.000000,2.500000,-0.022000,-0.500000,-5.000000,0.022000,8.000000,9.000000,0.023244,2.000000,2.500000,4.500000,-5.000000,2.500000,-2.500000,-2.000000,-3.500000,5.500000,-11.000000
10261,2017-18,TOR vs. WAS,10213,-6.525,-4.575000,6.525,4.575000,-13.075000,-9.125000,-0.026250,-0.102500,-1.575000,-0.022875,-0.022750,-0.03525,0.173000,0.512500,-0.025375,-0.022250,0.0,0.000000,0.0,0.0,0.0,-0.375000,-0.069000,0.0,-0.191250,0.0,-2.625000,-1.000000,-0.026625,0.125000,-3.625000,0.063125,0.125000,0.375000,-0.000295,-1.875000,-3.250000,-5.125000,-2.625000,0.875000,-2.750000,0.625000,-0.250000,-5.000000,10.000000
10262,2017-18,TOR vs. WAS,10222,-7.500,-4.955556,7.500,4.955556,-15.022222,-9.888889,-0.036222,-0.250000,-1.944444,-0.000222,-0.000111,-0.01400,0.952667,1.388889,-0.032667,-0.028778,0.0,-0.000889,0.0,0.0,0.0,-0.555556,-0.074222,0.0,-0.192222,0.0,-2.444444,0.000000,-0.029444,-0.555556,-3.111111,0.028556,-0.111111,-0.333333,0.012364,-0.777778,-2.111111,-2.888889,-2.888889,0.444444,-2.555556,1.111111,-0.222222,-5.555556,11.111111
10263,2017-18,TOR vs. WAS,10225,-5.420,-3.470000,5.420,3.470000,-10.860000,-6.900000,-0.025100,-0.054000,-1.340000,0.004300,0.004500,-0.00960,0.106300,0.460000,-0.026700,-0.026100,0.0,-0.001000,0.0,0.0,0.0,-0.400000,-0.051200,0.0,-0.139600,0.0,-1.400000,1.100000,-0.022600,-0.600000,-2.500000,0.017300,-0.600000,-0.500000,-0.005163,-0.200000,-1.900000,-2.100000,-2.000000,0.900000,-2.200000,0.200000,-0.100000,-4.000000,8.000000
10264,2017-18,UTA vs. WAS,9293,-53.300,-49.400000,53.300,49.400000,-106.600000,-98.800000,-0.283000,-1.120000,-14.500000,-0.100000,-0.100000,-0.22600,-3.527000,-3.000000,-0.358000,-0.308000,0.0,0.004000,0.0,0.0,0.0,-2.000000,-0.768000,0.0,-0.020000,0.0,-20.000000,4.000000,-0.278000,-12.000000,-14.000000,-0.271000,5.000000,5.000000,0.048309,2.000000,-23.000000,-21.000000,-20.000000,-1.000000,-1.000000,-3.000000,1.000000,-47.000000,94.000000
10265,2017-18,UTA vs. WAS,9557,-25.250,-22.600000,25.250,22.600000,-50.500000,-45.200000,-0.179000,-0.220000,-8.000000,-0.062500,-0.062500,-0.15100,-6.805000,-6.550000,-0.210500,-0.184500,0.0,0.001000,0.0,0.0,0.0,-1.500000,-0.379000,0.0,-0.083000,0.0,-9.000000,9.000000,-0.168500,-5.500000,-3.000000,-0.169000,1.500000,0.500000,0.055829,2.000000,-15.500000,-13.500000,-11.000000,3.000000,0.500000,-7.000000,0.500000,-22.000000,44.000000

In [29]:
df_stats_ah_diff_cma.drop(columns=['season', 'matchup'], inplace=True)
p(df_stats_ah_diff_cma)

(10266, 46)

,index,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma
0,197,27.900,24.600000,-27.900,-24.600000,55.800000,49.200000,-0.100000,-0.220000,3.300000,0.139000,0.139000,0.22200,5.930000,5.400000,0.184000,0.168000,0.0,-0.003000,0.0,0.0,0.0,1.000000,0.398000,0.0,0.143000,0.0,12.000000,-6.000000,0.187000,-1.000000,-5.000000,0.080000,0.000000,1.000000,-0.045752,2.000000,18.000000,20.000000,5.000000,1.000000,5.000000,3.000000,1.000000,23.000000,-46.000000
1,377,9.800,6.050000,-9.800,-6.050000,19.600000,12.100000,-0.132500,-0.830000,-2.200000,-0.085500,0.414500,0.11100,6.757500,6.250000,0.070000,0.080000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.134000,0.0,-0.052000,0.0,1.000000,-10.500000,0.078500,-2.000000,-6.500000,0.023500,5.500000,7.000000,0.009321,1.500000,10.500000,12.000000,-3.500000,-0.500000,3.000000,4.500000,-0.500000,5.500000,-11.000000
2,1122,5.500,2.133333,-5.500,-2.133333,11.066667,4.266667,-0.027000,0.203333,1.166667,-0.159667,0.507000,0.07400,3.056667,2.633333,0.078000,0.061333,0.0,0.000000,0.0,0.0,0.0,0.000000,0.095333,0.0,0.003333,0.0,2.000000,-8.666667,0.078667,-0.666667,-5.666667,0.099000,-1.333333,1.333333,-0.099341,-2.666667,6.000000,3.333333,0.333333,0.666667,3.333333,1.666667,1.333333,2.000000,-4.000000
3,389,-9.100,-4.600000,9.100,4.600000,-18.200000,-9.200000,-0.122000,-0.210000,-5.400000,0.418000,-0.582000,0.00000,-2.781000,-2.100000,-0.109000,-0.094000,0.0,-0.010000,0.0,0.0,0.0,-1.000000,-0.094000,0.0,-0.261000,0.0,-3.000000,9.000000,-0.083000,-4.000000,-11.000000,-0.097000,5.000000,7.000000,-0.073077,7.000000,-1.000000,6.000000,-6.000000,4.000000,-5.000000,-7.000000,-5.000000,-5.000000,10.000000
4,648,1.000,7.000000,-1.000,-7.000000,2.000000,14.000000,-0.123500,-0.465000,-4.400000,0.340500,-0.659500,0.00000,-0.665000,0.150000,-0.023500,-0.001500,0.0,-0.004500,0.0,0.0,0.0,-0.500000,0.016000,0.0,-0.011000,0.0,-1.000000,2.500000,-0.022000,-0.500000,-5.000000,0.022000,8.000000,9.000000,0.023244,2.000000,2.500000,4.500000,-5.000000,2.500000,-2.500000,-2.000000,-3.500000,5.500000,-11.000000
10261,10213,-6.525,-4.575000,6.525,4.575000,-13.075000,-9.125000,-0.026250,-0.102500,-1.575000,-0.022875,-0.022750,-0.03525,0.173000,0.512500,-0.025375,-0.022250,0.0,0.000000,0.0,0.0,0.0,-0.375000,-0.069000,0.0,-0.191250,0.0,-2.625000,-1.000000,-0.026625,0.125000,-3.625000,0.063125,0.125000,0.375000,-0.000295,-1.875000,-3.250000,-5.125000,-2.625000,0.875000,-2.750000,0.625000,-0.250000,-5.000000,10.000000
10262,10222,-7.500,-4.955556,7.500,4.955556,-15.022222,-9.888889,-0.036222,-0.250000,-1.944444,-0.000222,-0.000111,-0.01400,0.952667,1.388889,-0.032667,-0.028778,0.0,-0.000889,0.0,0.0,0.0,-0.555556,-0.074222,0.0,-0.192222,0.0,-2.444444,0.000000,-0.029444,-0.555556,-3.111111,0.028556,-0.111111,-0.333333,0.012364,-0.777778,-2.111111,-2.888889,-2.888889,0.444444,-2.555556,1.111111,-0.222222,-5.555556,11.111111
10263,10225,-5.420,-3.470000,5.420,3.470000,-10.860000,-6.900000,-0.025100,-0.054000,-1.340000,0.004300,0.004500,-0.00960,0.106300,0.460000,-0.026700,-0.026100,0.0,-0.001000,0.0,0.0,0.0,-0.400000,-0.051200,0.0,-0.139600,0.0,-1.400000,1.100000,-0.022600,-0.600000,-2.500000,0.017300,-0.600000,-0.500000,-0.005163,-0.200000,-1.900000,-2.100000,-2.000000,0.900000,-2.200000,0.200000,-0.100000,-4.000000,8.000000
10264,9293,-53.300,-49.400000,53.300,49.400000,-106.600000,-98.800000,-0.283000,-1.120000,-14.500000,-0.100000,-0.100000,-0.22600,-3.527000,-3.000000,-0.358000,-0.308000,0.0,0.004000,0.0,0.0,0.0,-2.000000,-0.768000,0.0,-0.020000,0.0,-20.000000,4.000000,-0.278000,-12.000000,-14.000000,-0.271000,5.000000,5.000000,0.048309,2.000000,-23.000000,-21.000000,-20.000000,-1.000000,-1.000000,-3.000000,1.000000,-47.000000,94.000000
10265,9557,-25.250,-22.600000,25.250,22.600000,-50.500000,-45.200000,-0.179000,-0.220000,-8.000000,-0.062500,-0.062500,-0.15100,-6.805000,-6.550000,-0.210500,-0.184500,0.0,0.001000,0.0,0.0,0.0,-1.500000,-0.379000,0.0,-0.083000,0.0,-9.000000,9.000000,-0.168500,-5.500000,-3.000000,-0.169000,1.500000,0.500000,0.055829,2.000000,-15.500000,-13.500000,-11.000000,3.000000,0.500000,-7.000000,0.500000,-22.000000,44.000000

In [30]:
#get index column of original dataframe
df = df.reset_index()
p(df)

(10266, 156)

,index,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff
0,0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8,-7.8,-7.8,7.8,7.8,-15.4,-15.4,-0.225,-0.37,-7.2,-0.018,-0.018,-0.056,-3.058,-3.0,-0.103,-0.079,0.0,0.004,0.0,0.0,0.0,-1,-0.198,0.0,-1.000,0,-5,5,-0.099,0,4,-0.100,2,0,0.080000,3,-6,-3,-10,4,2,-1,2,-8,16
1,1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14,-10.8,-15.6,10.8,15.6,-21.6,-31.2,-0.304,-1.28,-8.3,-0.246,-0.246,-0.218,4.893,4.4,0.031,0.036,0.0,0.004,0.0,0.0,0.0,0,-0.250,0.0,-1.000,0,-7,-19,0.024,-1,-1,-0.026,1,1,0.020833,-11,-7,-18,-16,-8,2,7,-3,-14,28
2,2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2,-3.7,-0.9,3.7,0.9,-7.6,-1.8,0.133,-0.56,1.8,0.091,0.091,0.108,8.100,8.9,-0.002,0.015,0.0,-0.002,0.0,0.0,0.0,-1,0.014,0.0,-1.000,0,-2,-5,0.001,-1,-1,-0.029,3,0,0.107143,2,7,9,4,-5,3,8,1,-2,4
3,3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4,-2.8,-4.2,2.8,4.2,-5.4,-8.4,-0.252,-1.39,-6.5,0.041,0.041,0.040,3.361,3.1,0.025,-0.009,0.0,0.003,0.0,0.0,0.0,0,-0.150,0.0,-1.000,0,-1,-2,-0.001,4,6,0.113,-6,-1,-0.185961,2,-1,1,-9,0,2,3,1,-4,8
4,4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4,-5.7,-2.7,5.7,2.7,-11.2,-5.4,0.095,0.75,-0.9,-0.032,-0.032,-0.054,-4.026,-3.8,-0.104,-0.056,0.0,0.003,0.0,0.0,0.0,-1,-0.032,0.0,-1.000,0,-10,-5,-0.083,-4,-4,-0.150,20,26,-0.038462,1,-7,-6,-1,4,-5,-3,-10,-4,8
10261,10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9,12.4,9.9,-12.4,-9.9,24.8,19.8,0.169,0.05,6.3,-0.026,-0.026,0.020,5.772,5.5,0.149,0.125,0.0,-0.001,0.0,0.0,0.0,0,0.136,0.0,0.142,0,3,-10,0.088,9,-5,0.251,-6,-8,-0.090909,-6,4,-2,8,-4,4,4,5,9,-18
10262,10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10,-8.5,-12.4,8.5,12.4,-17.0,-24.8,-0.265,-2.38,-9.5,0.226,0.226,0.176,4.020,3.8,-0.088,-0.104,0.0,0.002,0.0,0.0,0.0,2,-0.188,0.0,-1.000,0,-2,9,-0.067,-3,1,-0.091,-3,2,-0.222727,15,0,15,-13,-5,-3,4,0,-10,20
10263,10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19,-20.0,-23.6,20.0,23.6,-40.0,-47.2,0.080,-0.06,-3.1,0.093,0.093,0.032,-1.063,-1.5,-0.204,-0.161,0.0,-0.003,0.0,0.0,0.0,3,-0.130,0.0,-1.000,0,-10,8,-0.162,-6,-9,-0.084,7,5,0.150183,9,-8,1,-3,6,-4,-2,-10,-19,38
10264,10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8,13.0,9.6,-13.0,-9.6,26.0,19.4,0.143,1.02,6.2,-0.194,-0.194,-0.136,-2.559,-3.0,0.090,0.102,0.0,0.002,0.0,0.0,0.0,-1,0.138,0.0,1.000,0,2,-11,0.084,0,-5,0.056,4,2,0.130031,-9,-1,-10,7,0,1,-3,2,8,-16
10265,10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23,23.7,24.3,-23.7,-24.3,47.4,48.4,-0.059,0.59,3.3,-0.014,-0.014,0.028,-1.209,-1.2,0.144,0.146,0.0,-0.002,0.0,0.0,0.0,1,0.344,0.0,1.000,0,9,-1,0.108,6,11,0.072,-1,-9,0.320000,-7,7,0,4,2,8,-3,2,23,-46

In [31]:
#merge original dataframe (i.e. df) and df_stats_ah_diff_cma
df_and_df_stats_ah_diff_cma = pd.merge(df, df_stats_ah_diff_cma, on=['index'], how='outer', indicator=True)
p(df_and_df_stats_ah_diff_cma)

(10266, 202)

,index,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma,_merge
0,0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8,-7.8,-7.8,7.8,7.8,-15.4,-15.4,-0.225,-0.37,-7.2,-0.018,-0.018,-0.056,-3.058,-3.0,-0.103,-0.079,0.0,0.004,0.0,0.0,0.0,-1,-0.198,0.0,-1.000,0,-5,5,-0.099,0,4,-0.100,2,0,0.080000,3,-6,-3,-10,4,2,-1,2,-8,16,-7.800000,-7.800000,7.800000,7.800000,-15.400000,-15.400000,-0.225000,-0.370000,-7.200000,-0.018000,-0.018000,-0.056000,-3.058000,-3.000000,-0.103000,-0.079000,0.0,0.004000,0.0,0.0,0.0,-1.0,-0.198000,0.0,-1.000000,0.0,-5.000000,5.000000,-0.099000,0.000000,4.000000,-0.100000,2.000000,0.000000,0.080000,3.000000,-6.000000,-3.000000,-10.000000,4.000000,2.000000,-1.000000,2.000000,-8.000000,16.000000,both
1,1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14,-10.8,-15.6,10.8,15.6,-21.6,-31.2,-0.304,-1.28,-8.3,-0.246,-0.246,-0.218,4.893,4.4,0.031,0.036,0.0,0.004,0.0,0.0,0.0,0,-0.250,0.0,-1.000,0,-7,-19,0.024,-1,-1,-0.026,1,1,0.020833,-11,-7,-18,-16,-8,2,7,-3,-14,28,-10.800000,-15.600000,10.800000,15.600000,-21.600000,-31.200000,-0.304000,-1.280000,-8.300000,-0.246000,-0.246000,-0.218000,4.893000,4.400000,0.031000,0.036000,0.0,0.004000,0.0,0.0,0.0,0.0,-0.250000,0.0,-1.000000,0.0,-7.000000,-19.000000,0.024000,-1.000000,-1.000000,-0.026000,1.000000,1.000000,0.020833,-11.000000,-7.000000,-18.000000,-16.000000,-8.000000,2.000000,7.000000,-3.000000,-14.000000,28.000000,both
2,2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2,-3.7,-0.9,3.7,0.9,-7.6,-1.8,0.133,-0.56,1.8,0.091,0.091,0.108,8.100,8.9,-0.002,0.015,0.0,-0.002,0.0,0.0,0.0,-1,0.014,0.0,-1.000,0,-2,-5,0.001,-1,-1,-0.029,3,0,0.107143,2,7,9,4,-5,3,8,1,-2,4,-3.700000,-0.900000,3.700000,0.900000,-7.600000,-1.800000,0.133000,-0.560000,1.800000,0.091000,0.091000,0.108000,8.100000,8.900000,-0.002000,0.015000,0.0,-0.002000,0.0,0.0,0.0,-1.0,0.014000,0.0,-1.000000,0.0,-2.000000,-5.000000,0.001000,-1.000000,-1.000000,-0.029000,3.000000,0.000000,0.107143,2.000000,7.000000,9.000000,4.000000,-5.000000,3.000000,8.000000,1.000000,-2.000000,4.000000,both
3,3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4,-2.8,-4.2,2.8,4.2,-5.4,-8.4,-0.252,-1.39,-6.5,0.041,0.041,0.040,3.361,3.1,0.025,-0.009,0.0,0.003,0.0,0.0,0.0,0,-0.150,0.0,-1.000,0,-1,-2,-0.001,4,6,0.113,-6,-1,-0.185961,2,-1,1,-9,0,2,3,1,-4,8,-2.800000,-4.200000,2.800000,4.200000,-5.400000,-8.400000,-0.252000,-1.390000,-6.500000,0.041000,0.041000,0.040000,3.361000,3.100000,0.025000,-0.009000,0.0,0.003000,0.0,0.0,0.0,0.0,-0.150000,0.0,-1.000000,0.0,-1.000000,-2.000000,-0.001000,4.000000,6.000000,0.113000,-6.000000,-1.000000,-0.185961,2.000000,-1.000000,1.000000,-9.000000,0.000000,2.000000,3.000000,1.000000,-4.000000,8.000000,both
4,4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4,-5.7,-2.7,5.7,2.7,-11.2,-5.4,0.095,0.75,-0.9,-0.032,-0.032,-0.054,-4.026,-3.8,-0.104,-0.056,0.0,0.003,0.0,0.0,0.0,-1,-0.032,0.0,-1.000,0,-10,-5,-0.083,-4,-4,-0.150,20,26,-0.038462,1,-7,-6,-1,4,-5,-3,-10,-4,8,-5.700000,-2.700000,5.700000,2.700000,-11.200000,-5.400000,0.095000,0.750000,-0.900000,-0.032000,-0.032000,-0.054000,-4.026000,-3.800000,-0.104000,-0.056000,0.0,0.003000,0.0,0.0,0.0,-1.0,-0.032000,0.0,-1.000000,0.0,-10.000000,-5.000000,-0.083000,-4.000000,-4.000000,-0.150000,20.000000,26.000000,-0.038462,1.000000,-7.000000,-6.000000,-1.000000,4.000000,-5.000000,-3.000000,-10.000000,-4.000000,8.000000,both
10261,10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9,12.4,9.9,-12.4,-9.9,24.8,19.8,0.169,0.05,6.3,-0.026,-0.026,0.020,5.772,5.5,0.149,0.125,0.0,-0.001,0.0,0.0,0.0,0,0.136,0.0,0.142,0,3,-10,0.088,9,-5,0.251,-6,-8,-0.090909,-6,4,-2,8,-4,4,4,5,9,-18,-6.810000,-6.190000,6.810000,6.190000,-13.580000,-12.360000,0.081500,-0.043000,1.820000,-0.060600,-0.060600,-0.043800,2.614000,2.760000,0.002000,-0.001100,0.0,0.000400,0.0,0.0,0.0,-0.7,-0.041000,0.0,0.173300,0.0,-2.100000,-4.700000,-0.000300,-0.300000,-3.400000,0.018100,-2.300000,-3.000000,-0.028349,-3.400000,-1.200000,-4.600000,2.300000,-1.800000,0.800000,2.300000,-0.600000,-6.800000,13.600000,both
10262,10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10,-8.5,-12.4,8.5,12.4,-17.0,-24.8,-0.265,-2.38,-9.5,0.226,0.226,0.176,4.020,3.8,-0.088,-0.104,0.0,0.002,0.0,0.0,0.0,2,-0.188,0.0,-1.000,0,-2,9,-0.067,-3,1,-0.091,-3,2,-0.222727,15,0,15,-13,-5,-3,4,0,-10,20,-0.366667,-3.733333,0.366667,3.733333,-0.800000,-7.466667,-0.124333,-1.060000,-5.566667,0.118333,0.118333,0.096667,1.870333,1.466667,-0.050333,-0.037333,0.0,0.001333,0.0,0.0,0.0,1.0,-0.112667,0.0,-0.297667,0.0,-4.666667,2.000000,-0.062333,2.333333,1.333333,0.060333,4.666667,6.000000,-0.009750,8.333333,-0.666667,7.666667,-7.333333,-1.666667,-3.000000,1.333333,0.666667,-2.333333,4.666667,both
10263,10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19,-20.0,-23.6,20.0,23.6,-40.0,-47.2,0.080,-0.06,-3.1,0.093,0.093,0.032,-1.063,-1.5,-0.204,-0.161,0.0,-0.003,0.0,0.0,0.0,3,-0.130,0.0,-1.000,0,-10,8,-0.162,-6,-9,-0.084,7,5,0.150183,9,-8,1,-3,6,-4,-2,-10,-19,38,-5.275000,-8.700000,5.275000,8.700000,-10.600000,-17.400000,-0.073250,-0.810000,-4.950000,0.112000,0.112000,0.080500,1.137000,0.725000,-0.088750,-0.068250,0.0,0.000250,0.0,0.0,0.0,1.5,-0.117000,0.0,-0.473250,0.0,-6.000000,3.500000,-0.087250,0.250000,-1.250000,0.024250,5.250000,5.750000,0.030233,8.500000,-2.500000,6.000000,-6.250000,0.250000,-3.250000,0.500000,-2.000000,-6.500000,13.000000,both
10264,10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8,13.0,9.6,-13.0,-9.6,26.0,19.4,0.143,1.02,6.2,-0.194,-0.194,-0.136,-2.559,-3.0,0.090,0.102,0.0,0.002,0.0,0.0,0.0,-1,0.138,0.0,1.000,0,2,-11,0.084,0,-5,0.056,4,2,0.130031,-9,-1,-10,7,0,1,-3,2,8,-16,-1.620000,-5.040000,1.620000,5.040000,-3.280000,-10.040000,-0.030000,-0.444000,-2.720000,0.050800,0.050800,0.037200,0.397800,-0.020000,-0.053000,-0.034200,0.0,0.000600,0.0,0.0,0.0,1.0,-0.066000,0.0,-0.178600,0.0,-4.400000,0.600000,-0.053000,0.200000,-2.000000,0.030600,5.000000,5.000000,0.050193,5.000000,-2.200000,2.800000,-3.600000,0.200000,-2.400000,-0.200000,-1.200000,-3.600000,7.200000,both
10265,10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23,23.7,24.3,-23.7,-24.3,47.4,48.4,-0.059,0.59,3.3,-0.014,-0.014,0.028,-1.209,-1.2,0.144,0.146,0.0,-0.002,0.0,0.0,0.0,1,0.344,0.0,1.000,0,9,-1,0.108,6,11,0.072,-1,-9,0.320000,-7,7,0,4,2,8,-3,2,23,-46,2.600000,-0.150000,-2.600000,0.150000,5.166667,-0.300000,-0.034833,-0.271667,-1.716667,0.040000,0.040000,0.035667,0.130000,-0.216667,-0.020167,-0.004167,0.0,0.000167,0.0,0.0,0.0,1.0,0.002333,0.0,0.017833,0.0,-2.166667,0.333333,-0.026167,1.166667,0.166667,0.037500,4.000000,2.666667,0.095160,3.000000,-0.666667,2.333333,-2.333333,0.500000,-0.666667,-0.666667,-0.666667,0.833333,-1.666667,both

In [32]:
df_and_df_stats_ah_diff_cma.value_counts('_merge')

_merge
both          10266
right_only        0
left_only         0
dtype: int64

In [33]:
df_and_df_stats_ah_diff_cma.drop(columns='_merge', inplace=True)

In [34]:
p(df_and_df_stats_ah_diff_cma)

(10266, 201)

,index,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma
0,0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8,-7.8,-7.8,7.8,7.8,-15.4,-15.4,-0.225,-0.37,-7.2,-0.018,-0.018,-0.056,-3.058,-3.0,-0.103,-0.079,0.0,0.004,0.0,0.0,0.0,-1,-0.198,0.0,-1.000,0,-5,5,-0.099,0,4,-0.100,2,0,0.080000,3,-6,-3,-10,4,2,-1,2,-8,16,-7.800000,-7.800000,7.800000,7.800000,-15.400000,-15.400000,-0.225000,-0.370000,-7.200000,-0.018000,-0.018000,-0.056000,-3.058000,-3.000000,-0.103000,-0.079000,0.0,0.004000,0.0,0.0,0.0,-1.0,-0.198000,0.0,-1.000000,0.0,-5.000000,5.000000,-0.099000,0.000000,4.000000,-0.100000,2.000000,0.000000,0.080000,3.000000,-6.000000,-3.000000,-10.000000,4.000000,2.000000,-1.000000,2.000000,-8.000000,16.000000
1,1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14,-10.8,-15.6,10.8,15.6,-21.6,-31.2,-0.304,-1.28,-8.3,-0.246,-0.246,-0.218,4.893,4.4,0.031,0.036,0.0,0.004,0.0,0.0,0.0,0,-0.250,0.0,-1.000,0,-7,-19,0.024,-1,-1,-0.026,1,1,0.020833,-11,-7,-18,-16,-8,2,7,-3,-14,28,-10.800000,-15.600000,10.800000,15.600000,-21.600000,-31.200000,-0.304000,-1.280000,-8.300000,-0.246000,-0.246000,-0.218000,4.893000,4.400000,0.031000,0.036000,0.0,0.004000,0.0,0.0,0.0,0.0,-0.250000,0.0,-1.000000,0.0,-7.000000,-19.000000,0.024000,-1.000000,-1.000000,-0.026000,1.000000,1.000000,0.020833,-11.000000,-7.000000,-18.000000,-16.000000,-8.000000,2.000000,7.000000,-3.000000,-14.000000,28.000000
2,2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2,-3.7,-0.9,3.7,0.9,-7.6,-1.8,0.133,-0.56,1.8,0.091,0.091,0.108,8.100,8.9,-0.002,0.015,0.0,-0.002,0.0,0.0,0.0,-1,0.014,0.0,-1.000,0,-2,-5,0.001,-1,-1,-0.029,3,0,0.107143,2,7,9,4,-5,3,8,1,-2,4,-3.700000,-0.900000,3.700000,0.900000,-7.600000,-1.800000,0.133000,-0.560000,1.800000,0.091000,0.091000,0.108000,8.100000,8.900000,-0.002000,0.015000,0.0,-0.002000,0.0,0.0,0.0,-1.0,0.014000,0.0,-1.000000,0.0,-2.000000,-5.000000,0.001000,-1.000000,-1.000000,-0.029000,3.000000,0.000000,0.107143,2.000000,7.000000,9.000000,4.000000,-5.000000,3.000000,8.000000,1.000000,-2.000000,4.000000
3,3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4,-2.8,-4.2,2.8,4.2,-5.4,-8.4,-0.252,-1.39,-6.5,0.041,0.041,0.040,3.361,3.1,0.025,-0.009,0.0,0.003,0.0,0.0,0.0,0,-0.150,0.0,-1.000,0,-1,-2,-0.001,4,6,0.113,-6,-1,-0.185961,2,-1,1,-9,0,2,3,1,-4,8,-2.800000,-4.200000,2.800000,4.200000,-5.400000,-8.400000,-0.252000,-1.390000,-6.500000,0.041000,0.041000,0.040000,3.361000,3.100000,0.025000,-0.009000,0.0,0.003000,0.0,0.0,0.0,0.0,-0.150000,0.0,-1.000000,0.0,-1.000000,-2.000000,-0.001000,4.000000,6.000000,0.113000,-6.000000,-1.000000,-0.185961,2.000000,-1.000000,1.000000,-9.000000,0.000000,2.000000,3.000000,1.000000,-4.000000,8.000000
4,4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4,-5.7,-2.7,5.7,2.7,-11.2,-5.4,0.095,0.75,-0.9,-0.032,-0.032,-0.054,-4.026,-3.8,-0.104,-0.056,0.0,0.003,0.0,0.0,0.0,-1,-0.032,0.0,-1.000,0,-10,-5,-0.083,-4,-4,-0.150,20,26,-0.038462,1,-7,-6,-1,4,-5,-3,-10,-4,8,-5.700000,-2.700000,5.700000,2.700000,-11.200000,-5.400000,0.095000,0.750000,-0.900000,-0.032000,-0.032000,-0.054000,-4.026000,-3.800000,-0.104000,-0.056000,0.0,0.003000,0.0,0.0,0.0,-1.0,-0.032000,0.0,-1.000000,0.0,-10.000000,-5.000000,-0.083000,-4.000000,-4.000000,-0.150000,20.000000,26.000000,-0.038462,1.000000,-7.000000,-6.000000,-1.000000,4.000000,-5.000000,-3.000000,-10.000000,-4.000000,8.000000
10261,10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9,12.4,9.9,-12.4,-9.9,24.8,19.8,0.169,0.05,6.3,-0.026,-0.026,0.020,5.772,5.5,0.149,0.125,0.0,-0.001,0.0,0.0,0.0,0,0.136,0.0,0.142,0,3,-10,0.088,9,-5,0.251,-6,-8,-0.090909,-6,4,-2,8,-4,4,4,5,9,-18,-6.810000,-6.190000,6.810000,6.190000,-13.580000,-12.360000,0.081500,-0.043000,1.820000,-0.060600,-0.060600,-0.043800,2.614000,2.760000,0.002000,-0.001100,0.0,0.000400,0.0,0.0,0.0,-0.7,-0.041000,0.0,0.173300,0.0,-2.100000,-4.700000,-0.000300,-0.300000,-3.400000,0.018100,-2.300000,-3.000000,-0.028349,-3.400000,-1.200000,-4.600000,2.300000,-1.800000,0.800000,2.300000,-0.600000,-6.800000,13.600000
10262,10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10,-8.5,-12.4,8.5,12.4,-17.0,-24.8,-0.265,-2.38,-9.5,0.226,0.226,0.176,4.020,3.8,-0.088,-0.104,0.0,0.002,0.0,0.0,0.0,2,-0.188,0.0,-1.000,0,-2,9,-0.067,-3,1,-0.091,-3,2,-0.222727,15,0,15,-13,-5,-3,4,0,-10,20,-0.366667,-3.733333,0.366667,3.733333,-0.800000,-7.466667,-0.124333,-1.060000,-5.566667,0.118333,0.118333,0.096667,1.870333,1.466667,-0.050333,-0.037333,0.0,0.001333,0.0,0.0,0.0,1.0,-0.112667,0.0,-0.297667,0.0,-4.666667,2.000000,-0.062333,2.333333,1.333333,0.060333,4.666667,6.000000,-0.009750,8.333333,-0.666667,7.666667,-7.333333,-1.666667,-3.000000,1.333333,0.666667,-2.333333,4.666667
10263,10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19,-20.0,-23.6,20.0,23.6,-40.0,-47.2,0.080,-0.06,-3.1,0.093,0.093,0.032,-1.063,-1.5,-0.204,-0.161,0.0,-0.003,0.0,0.0,0.0,3,-0.130,0.0,-1.000,0,-10,8,-0.162,-6,-9,-0.084,7,5,0.150183,9,-8,1,-3,6,-4,-2,-10,-19,38,-5.275000,-8.700000,5.275000,8.700000,-10.600000,-17.400000,-0.073250,-0.810000,-4.950000,0.112000,0.112000,0.080500,1.137000,0.725000,-0.088750,-0.068250,0.0,0.000250,0.0,0.0,0.0,1.5,-0.117000,0.0,-0.473250,0.0,-6.000000,3.500000,-0.087250,0.250000,-1.250000,0.024250,5.250000,5.750000,0.030233,8.500000,-2.500000,6.000000,-6.250000,0.250000,-3.250000,0.500000,-2.000000,-6.500000,13.000000
10264,10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8,13.0,9.6,-13.0,-9.6,26.0,19.4,0.143,1.02,6.2,-0.194,-0.194,-0.136,-2.559,-3.0,0.090,0.102,0.0,0.002,0.0,0.0,0.0,-1,0.138,0.0,1.000,0,2,-11,0.084,0,-5,0.056,4,2,0.130031,-9,-1,-10,7,0,1,-3,2,8,-16,-1.620000,-5.040000,1.620000,5.040000,-3.280000,-10.040000,-0.030000,-0.444000,-2.720000,0.050800,0.050800,0.037200,0.397800,-0.020000,-0.053000,-0.034200,0.0,0.000600,0.0,0.0,0.0,1.0,-0.066000,0.0,-0.178600,0.0,-4.400000,0.600000,-0.053000,0.200000,-2.000000,0.030600,5.000000,5.000000,0.050193,5.000000,-2.200000,2.800000,-3.600000,0.200000,-2.400000,-0.200000,-1.200000,-3.600000,7.200000
10265,10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23,23.7,24.3,-23.7,-24.3,47.4,48.4,-0.059,0.59,3.3,-0.014,-0.014,0.028,-1.209,-1.2,0.144,0.146,0.0,-0.002,0.0,0.0,0.0,1,0.344,0.0,1.000,0,9,-1,0.108,6,11,0.072,-1,-9,0.320000,-7,7,0,4,2,8,-3,2,23,-46,2.600000,-0.150000,-2.600000,0.150000,5.166667,-0.300000,-0.034833,-0.271667,-1.716667,0.040000,0.040000,0.035667,0.130000,-0.216667,-0.020167,-0.004167,0.0,0.000167,0.0,0.0,0.0,1.0,0.002333,0.0,0.017833,0.0,-2.166667,0.333333,-0.026167,1.166667,0.166667,0.037500,4.000000,2.666667,0.095160,3.000000,-0.666667,2.333333,-2.333333,0.500000,-0.666667,-0.666667,-0.666667,0.833333,-1.666667

In [35]:
#get median matchup stat dif for each stat difference (per matchup per season)

df_stats_ah_diff_median = df.groupby(['season', 'matchup'])[list_stat_ah_diff].expanding(min_periods=0).median().reset_index()
df_stats_ah_diff_median.rename(columns={'level_2':'index'}, inplace=True)
p(df_stats_ah_diff_median)

(10266, 48)

,season,matchup,index,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff
0,2010-11,ATL vs. BOS,197,27.90,24.60,-27.90,-24.60,55.8,49.2,-0.1000,-0.220,3.30,0.1390,0.1390,0.222,5.9300,5.40,0.1840,0.1680,0.0,-0.0030,0.0,0.0,0.0,1.0,0.398,0.0,0.143,0.0,12.0,-6.0,0.1870,-1.0,-5.0,0.0800,0.0,1.0,-0.045752,2.0,18.0,20.0,5.0,1.0,5.0,3.0,1.0,23.0,-46.0
1,2010-11,ATL vs. BOS,377,9.80,6.05,-9.80,-6.05,19.6,12.1,-0.1325,-0.830,-2.20,-0.0855,0.4145,0.111,6.7575,6.25,0.0700,0.0800,0.0,0.0000,0.0,0.0,0.0,0.0,0.134,0.0,-0.052,0.0,1.0,-10.5,0.0785,-2.0,-6.5,0.0235,5.5,7.0,0.009321,1.5,10.5,12.0,-3.5,-0.5,3.0,4.5,-0.5,5.5,-11.0
2,2010-11,ATL vs. BOS,1122,-3.10,-5.70,3.10,5.70,-6.0,-11.4,-0.1000,-0.220,3.30,-0.3080,0.6900,0.000,5.9300,5.40,0.0940,0.0240,0.0,0.0000,0.0,0.0,0.0,0.0,0.018,0.0,0.114,0.0,4.0,-6.0,0.0790,-1.0,-5.0,0.0800,0.0,1.0,-0.045752,1.0,3.0,4.0,5.0,1.0,4.0,3.0,1.0,-5.0,10.0
3,2010-11,ATL vs. CHA,389,-9.10,-4.60,9.10,4.60,-18.2,-9.2,-0.1220,-0.210,-5.40,0.4180,-0.5820,0.000,-2.7810,-2.10,-0.1090,-0.0940,0.0,-0.0100,0.0,0.0,0.0,-1.0,-0.094,0.0,-0.261,0.0,-3.0,9.0,-0.0830,-4.0,-11.0,-0.0970,5.0,7.0,-0.073077,7.0,-1.0,6.0,-6.0,4.0,-5.0,-7.0,-5.0,-5.0,10.0
4,2010-11,ATL vs. CHA,648,1.00,7.00,-1.00,-7.00,2.0,14.0,-0.1235,-0.465,-4.40,0.3405,-0.6595,0.000,-0.6650,0.15,-0.0235,-0.0015,0.0,-0.0045,0.0,0.0,0.0,-0.5,0.016,0.0,-0.011,0.0,-1.0,2.5,-0.0220,-0.5,-5.0,0.0220,8.0,9.0,0.023244,2.0,2.5,4.5,-5.0,2.5,-2.5,-2.0,-3.5,5.5,-11.0
10261,2017-18,TOR vs. WAS,10213,-6.70,-7.50,6.70,7.50,-13.5,-15.0,-0.0075,-0.450,-1.15,-0.0175,-0.0175,-0.022,2.3520,3.05,-0.0185,-0.0110,0.0,0.0010,0.0,0.0,0.0,-0.5,-0.083,0.0,0.000,0.0,-1.5,-1.5,-0.0265,1.0,-1.0,0.0375,-0.5,-1.5,0.030380,-1.5,-5.0,-5.0,-2.0,0.5,-4.0,3.0,0.0,-8.0,16.0
10262,2017-18,TOR vs. WAS,10222,-6.80,-8.00,6.80,8.00,-13.8,-16.0,-0.0310,-0.710,-2.30,-0.0050,-0.0050,-0.020,3.2530,3.90,-0.0250,-0.0160,0.0,0.0010,0.0,0.0,0.0,-1.0,-0.106,0.0,0.000,0.0,-1.0,-1.0,-0.0290,1.0,-1.0,-0.0060,-1.0,-2.0,0.066023,0.0,-4.0,-5.0,-4.0,-1.0,-4.0,4.0,0.0,-8.0,16.0
10263,2017-18,TOR vs. WAS,10225,-6.70,-7.50,6.70,7.50,-13.5,-15.0,-0.0075,-0.450,-1.15,0.0030,0.0030,-0.015,2.3520,3.05,-0.0185,-0.0110,0.0,0.0005,0.0,0.0,0.0,-0.5,-0.083,0.0,0.000,0.0,-0.5,-1.0,-0.0265,0.5,0.0,-0.0145,-1.0,-2.0,0.030380,0.5,-3.0,-4.0,-2.0,0.5,-2.5,3.0,0.5,-8.0,16.0
10264,2017-18,UTA vs. WAS,9293,-53.30,-49.40,53.30,49.40,-106.6,-98.8,-0.2830,-1.120,-14.50,-0.1000,-0.1000,-0.226,-3.5270,-3.00,-0.3580,-0.3080,0.0,0.0040,0.0,0.0,0.0,-2.0,-0.768,0.0,-0.020,0.0,-20.0,4.0,-0.2780,-12.0,-14.0,-0.2710,5.0,5.0,0.048309,2.0,-23.0,-21.0,-20.0,-1.0,-1.0,-3.0,1.0,-47.0,94.0
10265,2017-18,UTA vs. WAS,9557,-25.25,-22.60,25.25,22.60,-50.5,-45.2,-0.1790,-0.220,-8.00,-0.0625,-0.0625,-0.151,-6.8050,-6.55,-0.2105,-0.1845,0.0,0.0010,0.0,0.0,0.0,-1.5,-0.379,0.0,-0.083,0.0,-9.0,9.0,-0.1685,-5.5,-3.0,-0.1690,1.5,0.5,0.055829,2.0,-15.5,-13.5,-11.0,3.0,0.5,-7.0,0.5,-22.0,44.0

In [36]:
#create dictionary for renaming of df_stats_ah_diff_median columns

list_stats_ah_diff_dsmi

['E_OFF_RATING_ah_diff',
 'OFF_RATING_ah_diff',
 'E_DEF_RATING_ah_diff',
 'DEF_RATING_ah_diff',
 'E_NET_RATING_ah_diff',
 'NET_RATING_ah_diff',
 'AST_PCT_ah_diff',
 'AST_TOV_ah_diff',
 'AST_RATIO_ah_diff',
 'OREB_PCT_ah_diff',
 'DREB_PCT_ah_diff',
 'REB_PCT_ah_diff',
 'E_TM_TOV_PCT_ah_diff',
 'TM_TOV_PCT_ah_diff',
 'EFG_PCT_ah_diff',
 'TS_PCT_ah_diff',
 'USG_PCT_ah_diff',
 'E_USG_PCT_ah_diff',
 'E_PACE_ah_diff',
 'PACE_ah_diff',
 'PACE_PER40_ah_diff',
 'POSS_ah_diff',
 'PIE_ah_diff',
 'duration_minutes_ah_diff',
 'w_pct_ah_diff',
 'min_ah_diff',
 'fgm_ah_diff',
 'fga_ah_diff',
 'fg_pct_ah_diff',
 'fg3m_ah_diff',
 'fg3a_ah_diff',
 'fg3_pct_ah_diff',
 'ftm_ah_diff',
 'fta_ah_diff',
 'ft_pct_ah_diff',
 'oreb_ah_diff',
 'dreb_ah_diff',
 'reb_ah_diff',
 'ast_ah_diff',
 'stl_ah_diff',
 'blk_ah_diff',
 'tov_ah_diff',
 'pf_ah_diff',
 'pts_ah_diff',
 'spread_ah_diff']

In [37]:
list_stats_ah_diff_dsmi_median = [k + '_median' for k in list_stats_ah_diff_dsmi]
list_stats_ah_diff_dsmi_median

['E_OFF_RATING_ah_diff_median',
 'OFF_RATING_ah_diff_median',
 'E_DEF_RATING_ah_diff_median',
 'DEF_RATING_ah_diff_median',
 'E_NET_RATING_ah_diff_median',
 'NET_RATING_ah_diff_median',
 'AST_PCT_ah_diff_median',
 'AST_TOV_ah_diff_median',
 'AST_RATIO_ah_diff_median',
 'OREB_PCT_ah_diff_median',
 'DREB_PCT_ah_diff_median',
 'REB_PCT_ah_diff_median',
 'E_TM_TOV_PCT_ah_diff_median',
 'TM_TOV_PCT_ah_diff_median',
 'EFG_PCT_ah_diff_median',
 'TS_PCT_ah_diff_median',
 'USG_PCT_ah_diff_median',
 'E_USG_PCT_ah_diff_median',
 'E_PACE_ah_diff_median',
 'PACE_ah_diff_median',
 'PACE_PER40_ah_diff_median',
 'POSS_ah_diff_median',
 'PIE_ah_diff_median',
 'duration_minutes_ah_diff_median',
 'w_pct_ah_diff_median',
 'min_ah_diff_median',
 'fgm_ah_diff_median',
 'fga_ah_diff_median',
 'fg_pct_ah_diff_median',
 'fg3m_ah_diff_median',
 'fg3a_ah_diff_median',
 'fg3_pct_ah_diff_median',
 'ftm_ah_diff_median',
 'fta_ah_diff_median',
 'ft_pct_ah_diff_median',
 'oreb_ah_diff_median',
 'dreb_ah_diff_median',
 'reb_ah_diff_median',
 'ast_ah_diff_median',
 'stl_ah_diff_median',
 'blk_ah_diff_median',
 'tov_ah_diff_median',
 'pf_ah_diff_median',
 'pts_ah_diff_median',
 'spread_ah_diff_median']

In [38]:
dict_stats_ah_diff_dsmi_median = dict(zip(list_stats_ah_diff_dsmi, list_stats_ah_diff_dsmi_median))
dict_stats_ah_diff_dsmi_median

{'E_OFF_RATING_ah_diff': 'E_OFF_RATING_ah_diff_median',
 'OFF_RATING_ah_diff': 'OFF_RATING_ah_diff_median',
 'E_DEF_RATING_ah_diff': 'E_DEF_RATING_ah_diff_median',
 'DEF_RATING_ah_diff': 'DEF_RATING_ah_diff_median',
 'E_NET_RATING_ah_diff': 'E_NET_RATING_ah_diff_median',
 'NET_RATING_ah_diff': 'NET_RATING_ah_diff_median',
 'AST_PCT_ah_diff': 'AST_PCT_ah_diff_median',
 'AST_TOV_ah_diff': 'AST_TOV_ah_diff_median',
 'AST_RATIO_ah_diff': 'AST_RATIO_ah_diff_median',
 'OREB_PCT_ah_diff': 'OREB_PCT_ah_diff_median',
 'DREB_PCT_ah_diff': 'DREB_PCT_ah_diff_median',
 'REB_PCT_ah_diff': 'REB_PCT_ah_diff_median',
 'E_TM_TOV_PCT_ah_diff': 'E_TM_TOV_PCT_ah_diff_median',
 'TM_TOV_PCT_ah_diff': 'TM_TOV_PCT_ah_diff_median',
 'EFG_PCT_ah_diff': 'EFG_PCT_ah_diff_median',
 'TS_PCT_ah_diff': 'TS_PCT_ah_diff_median',
 'USG_PCT_ah_diff': 'USG_PCT_ah_diff_median',
 'E_USG_PCT_ah_diff': 'E_USG_PCT_ah_diff_median',
 'E_PACE_ah_diff': 'E_PACE_ah_diff_median',
 'PACE_ah_diff': 'PACE_ah_diff_median',
 'PACE_PER40_ah_diff': 'PACE_PER40_ah_diff_median',
 'POSS_ah_diff': 'POSS_ah_diff_median',
 'PIE_ah_diff': 'PIE_ah_diff_median',
 'duration_minutes_ah_diff': 'duration_minutes_ah_diff_median',
 'w_pct_ah_diff': 'w_pct_ah_diff_median',
 'min_ah_diff': 'min_ah_diff_median',
 'fgm_ah_diff': 'fgm_ah_diff_median',
 'fga_ah_diff': 'fga_ah_diff_median',
 'fg_pct_ah_diff': 'fg_pct_ah_diff_median',
 'fg3m_ah_diff': 'fg3m_ah_diff_median',
 'fg3a_ah_diff': 'fg3a_ah_diff_median',
 'fg3_pct_ah_diff': 'fg3_pct_ah_diff_median',
 'ftm_ah_diff': 'ftm_ah_diff_median',
 'fta_ah_diff': 'fta_ah_diff_median',
 'ft_pct_ah_diff': 'ft_pct_ah_diff_median',
 'oreb_ah_diff': 'oreb_ah_diff_median',
 'dreb_ah_diff': 'dreb_ah_diff_median',
 'reb_ah_diff': 'reb_ah_diff_median',
 'ast_ah_diff': 'ast_ah_diff_median',
 'stl_ah_diff': 'stl_ah_diff_median',
 'blk_ah_diff': 'blk_ah_diff_median',
 'tov_ah_diff': 'tov_ah_diff_median',
 'pf_ah_diff': 'pf_ah_diff_median',
 'pts_ah_diff': 'pts_ah_diff_median',
 'spread_ah_diff': 'spread_ah_diff_median'}

In [39]:
#rename columns
df_stats_ah_diff_median.rename(columns=dict_stats_ah_diff_dsmi_median, inplace=True)

In [40]:
#drop redundant (to original df) columns
df_stats_ah_diff_median.drop(columns=['season', 'matchup'], inplace=True)
p(df_stats_ah_diff_median)

(10266, 46)

,index,E_OFF_RATING_ah_diff_median,OFF_RATING_ah_diff_median,E_DEF_RATING_ah_diff_median,DEF_RATING_ah_diff_median,E_NET_RATING_ah_diff_median,NET_RATING_ah_diff_median,AST_PCT_ah_diff_median,AST_TOV_ah_diff_median,AST_RATIO_ah_diff_median,OREB_PCT_ah_diff_median,DREB_PCT_ah_diff_median,REB_PCT_ah_diff_median,E_TM_TOV_PCT_ah_diff_median,TM_TOV_PCT_ah_diff_median,EFG_PCT_ah_diff_median,TS_PCT_ah_diff_median,USG_PCT_ah_diff_median,E_USG_PCT_ah_diff_median,E_PACE_ah_diff_median,PACE_ah_diff_median,PACE_PER40_ah_diff_median,POSS_ah_diff_median,PIE_ah_diff_median,duration_minutes_ah_diff_median,w_pct_ah_diff_median,min_ah_diff_median,fgm_ah_diff_median,fga_ah_diff_median,fg_pct_ah_diff_median,fg3m_ah_diff_median,fg3a_ah_diff_median,fg3_pct_ah_diff_median,ftm_ah_diff_median,fta_ah_diff_median,ft_pct_ah_diff_median,oreb_ah_diff_median,dreb_ah_diff_median,reb_ah_diff_median,ast_ah_diff_median,stl_ah_diff_median,blk_ah_diff_median,tov_ah_diff_median,pf_ah_diff_median,pts_ah_diff_median,spread_ah_diff_median
0,197,27.90,24.60,-27.90,-24.60,55.8,49.2,-0.1000,-0.220,3.30,0.1390,0.1390,0.222,5.9300,5.40,0.1840,0.1680,0.0,-0.0030,0.0,0.0,0.0,1.0,0.398,0.0,0.143,0.0,12.0,-6.0,0.1870,-1.0,-5.0,0.0800,0.0,1.0,-0.045752,2.0,18.0,20.0,5.0,1.0,5.0,3.0,1.0,23.0,-46.0
1,377,9.80,6.05,-9.80,-6.05,19.6,12.1,-0.1325,-0.830,-2.20,-0.0855,0.4145,0.111,6.7575,6.25,0.0700,0.0800,0.0,0.0000,0.0,0.0,0.0,0.0,0.134,0.0,-0.052,0.0,1.0,-10.5,0.0785,-2.0,-6.5,0.0235,5.5,7.0,0.009321,1.5,10.5,12.0,-3.5,-0.5,3.0,4.5,-0.5,5.5,-11.0
2,1122,-3.10,-5.70,3.10,5.70,-6.0,-11.4,-0.1000,-0.220,3.30,-0.3080,0.6900,0.000,5.9300,5.40,0.0940,0.0240,0.0,0.0000,0.0,0.0,0.0,0.0,0.018,0.0,0.114,0.0,4.0,-6.0,0.0790,-1.0,-5.0,0.0800,0.0,1.0,-0.045752,1.0,3.0,4.0,5.0,1.0,4.0,3.0,1.0,-5.0,10.0
3,389,-9.10,-4.60,9.10,4.60,-18.2,-9.2,-0.1220,-0.210,-5.40,0.4180,-0.5820,0.000,-2.7810,-2.10,-0.1090,-0.0940,0.0,-0.0100,0.0,0.0,0.0,-1.0,-0.094,0.0,-0.261,0.0,-3.0,9.0,-0.0830,-4.0,-11.0,-0.0970,5.0,7.0,-0.073077,7.0,-1.0,6.0,-6.0,4.0,-5.0,-7.0,-5.0,-5.0,10.0
4,648,1.00,7.00,-1.00,-7.00,2.0,14.0,-0.1235,-0.465,-4.40,0.3405,-0.6595,0.000,-0.6650,0.15,-0.0235,-0.0015,0.0,-0.0045,0.0,0.0,0.0,-0.5,0.016,0.0,-0.011,0.0,-1.0,2.5,-0.0220,-0.5,-5.0,0.0220,8.0,9.0,0.023244,2.0,2.5,4.5,-5.0,2.5,-2.5,-2.0,-3.5,5.5,-11.0
10261,10213,-6.70,-7.50,6.70,7.50,-13.5,-15.0,-0.0075,-0.450,-1.15,-0.0175,-0.0175,-0.022,2.3520,3.05,-0.0185,-0.0110,0.0,0.0010,0.0,0.0,0.0,-0.5,-0.083,0.0,0.000,0.0,-1.5,-1.5,-0.0265,1.0,-1.0,0.0375,-0.5,-1.5,0.030380,-1.5,-5.0,-5.0,-2.0,0.5,-4.0,3.0,0.0,-8.0,16.0
10262,10222,-6.80,-8.00,6.80,8.00,-13.8,-16.0,-0.0310,-0.710,-2.30,-0.0050,-0.0050,-0.020,3.2530,3.90,-0.0250,-0.0160,0.0,0.0010,0.0,0.0,0.0,-1.0,-0.106,0.0,0.000,0.0,-1.0,-1.0,-0.0290,1.0,-1.0,-0.0060,-1.0,-2.0,0.066023,0.0,-4.0,-5.0,-4.0,-1.0,-4.0,4.0,0.0,-8.0,16.0
10263,10225,-6.70,-7.50,6.70,7.50,-13.5,-15.0,-0.0075,-0.450,-1.15,0.0030,0.0030,-0.015,2.3520,3.05,-0.0185,-0.0110,0.0,0.0005,0.0,0.0,0.0,-0.5,-0.083,0.0,0.000,0.0,-0.5,-1.0,-0.0265,0.5,0.0,-0.0145,-1.0,-2.0,0.030380,0.5,-3.0,-4.0,-2.0,0.5,-2.5,3.0,0.5,-8.0,16.0
10264,9293,-53.30,-49.40,53.30,49.40,-106.6,-98.8,-0.2830,-1.120,-14.50,-0.1000,-0.1000,-0.226,-3.5270,-3.00,-0.3580,-0.3080,0.0,0.0040,0.0,0.0,0.0,-2.0,-0.768,0.0,-0.020,0.0,-20.0,4.0,-0.2780,-12.0,-14.0,-0.2710,5.0,5.0,0.048309,2.0,-23.0,-21.0,-20.0,-1.0,-1.0,-3.0,1.0,-47.0,94.0
10265,9557,-25.25,-22.60,25.25,22.60,-50.5,-45.2,-0.1790,-0.220,-8.00,-0.0625,-0.0625,-0.151,-6.8050,-6.55,-0.2105,-0.1845,0.0,0.0010,0.0,0.0,0.0,-1.5,-0.379,0.0,-0.083,0.0,-9.0,9.0,-0.1685,-5.5,-3.0,-0.1690,1.5,0.5,0.055829,2.0,-15.5,-13.5,-11.0,3.0,0.5,-7.0,0.5,-22.0,44.0

In [41]:
#merge original dataframe (i.e. df) and df_stats_ah_diff_median
df_and_df_stats_ah_diff_cma_median = pd.merge(df_and_df_stats_ah_diff_cma, df_stats_ah_diff_median, on=['index'], how='outer', indicator=True)
p(df_and_df_stats_ah_diff_cma_median)

(10266, 247)

,index,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma,E_OFF_RATING_ah_diff_median,OFF_RATING_ah_diff_median,E_DEF_RATING_ah_diff_median,DEF_RATING_ah_diff_median,E_NET_RATING_ah_diff_median,NET_RATING_ah_diff_median,AST_PCT_ah_diff_median,AST_TOV_ah_diff_median,AST_RATIO_ah_diff_median,OREB_PCT_ah_diff_median,DREB_PCT_ah_diff_median,REB_PCT_ah_diff_median,E_TM_TOV_PCT_ah_diff_median,TM_TOV_PCT_ah_diff_median,EFG_PCT_ah_diff_median,TS_PCT_ah_diff_median,USG_PCT_ah_diff_median,E_USG_PCT_ah_diff_median,E_PACE_ah_diff_median,PACE_ah_diff_median,PACE_PER40_ah_diff_median,POSS_ah_diff_median,PIE_ah_diff_median,duration_minutes_ah_diff_median,w_pct_ah_diff_median,min_ah_diff_median,fgm_ah_diff_median,fga_ah_diff_median,fg_pct_ah_diff_median,fg3m_ah_diff_median,fg3a_ah_diff_median,fg3_pct_ah_diff_median,ftm_ah_diff_median,fta_ah_diff_median,ft_pct_ah_diff_median,oreb_ah_diff_median,dreb_ah_diff_median,reb_ah_diff_median,ast_ah_diff_median,stl_ah_diff_median,blk_ah_diff_median,tov_ah_diff_median,pf_ah_diff_median,pts_ah_diff_median,spread_ah_diff_median,_merge
0,0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8,-7.8,-7.8,7.8,7.8,-15.4,-15.4,-0.225,-0.37,-7.2,-0.018,-0.018,-0.056,-3.058,-3.0,-0.103,-0.079,0.0,0.004,0.0,0.0,0.0,-1,-0.198,0.0,-1.000,0,-5,5,-0.099,0,4,-0.100,2,0,0.080000,3,-6,-3,-10,4,2,-1,2,-8,16,-7.800000,-7.800000,7.800000,7.800000,-15.400000,-15.400000,-0.225000,-0.370000,-7.200000,-0.018000,-0.018000,-0.056000,-3.058000,-3.000000,-0.103000,-0.079000,0.0,0.004000,0.0,0.0,0.0,-1.0,-0.198000,0.0,-1.000000,0.0,-5.000000,5.000000,-0.099000,0.000000,4.000000,-0.100000,2.000000,0.000000,0.080000,3.000000,-6.000000,-3.000000,-10.000000,4.000000,2.000000,-1.000000,2.000000,-8.000000,16.000000,-7.80,-7.80,7.80,7.80,-15.4,-15.4,-0.2250,-0.370,-7.2,-0.0180,-0.0180,-0.056,-3.0580,-3.00,-0.1030,-0.079,0.0,0.0040,0.0,0.0,0.0,-1.0,-0.198,0.0,-1.0000,0.0,-5.0,5.0,-0.099,0.0,4.0,-0.1000,2.0,0.0,0.080000,3.0,-6.0,-3.0,-10.0,4.0,2.0,-1.0,2.0,-8.0,16.0,both
1,1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14,-10.8,-15.6,10.8,15.6,-21.6,-31.2,-0.304,-1.28,-8.3,-0.246,-0.246,-0.218,4.893,4.4,0.031,0.036,0.0,0.004,0.0,0.0,0.0,0,-0.250,0.0,-1.000,0,-7,-19,0.024,-1,-1,-0.026,1,1,0.020833,-11,-7,-18,-16,-8,2,7,-3,-14,28,-10.800000,-15.600000,10.800000,15.600000,-21.600000,-31.200000,-0.304000,-1.280000,-8.300000,-0.246000,-0.246000,-0.218000,4.893000,4.400000,0.031000,0.036000,0.0,0.004000,0.0,0.0,0.0,0.0,-0.250000,0.0,-1.000000,0.0,-7.000000,-19.000000,0.024000,-1.000000,-1.000000,-0.026000,1.000000,1.000000,0.020833,-11.000000,-7.000000,-18.000000,-16.000000,-8.000000,2.000000,7.000000,-3.000000,-14.000000,28.000000,-10.80,-15.60,10.80,15.60,-21.6,-31.2,-0.3040,-1.280,-8.3,-0.2460,-0.2460,-0.218,4.8930,4.40,0.0310,0.036,0.0,0.0040,0.0,0.0,0.0,0.0,-0.250,0.0,-1.0000,0.0,-7.0,-19.0,0.024,-1.0,-1.0,-0.0260,1.0,1.0,0.020833,-11.0,-7.0,-18.0,-16.0,-8.0,2.0,7.0,-3.0,-14.0,28.0,both
2,2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2,-3.7,-0.9,3.7,0.9,-7.6,-1.8,0.133,-0.56,1.8,0.091,0.091,0.108,8.100,8.9,-0.002,0.015,0.0,-0.002,0.0,0.0,0.0,-1,0.014,0.0,-1.000,0,-2,-5,0.001,-1,-1,-0.029,3,0,0.107143,2,7,9,4,-5,3,8,1,-2,4,-3.700000,-0.900000,3.700000,0.900000,-7.600000,-1.800000,0.133000,-0.560000,1.800000,0.091000,0.091000,0.108000,8.100000,8.900000,-0.002000,0.015000,0.0,-0.002000,0.0,0.0,0.0,-1.0,0.014000,0.0,-1.000000,0.0,-2.000000,-5.000000,0.001000,-1.000000,-1.000000,-0.029000,3.000000,0.000000,0.107143,2.000000,7.000000,9.000000,4.000000,-5.000000,3.000000,8.000000,1.000000,-2.000000,4.000000,-3.70,-0.90,3.70,0.90,-7.6,-1.8,0.1330,-0.560,1.8,0.0910,0.0910,0.108,8.1000,8.90,-0.0020,0.015,0.0,-0.0020,0.0,0.0,0.0,-1.0,0.014,0.0,-1.0000,0.0,-2.0,-5.0,0.001,-1.0,-1.0,-0.0290,3.0,0.0,0.107143,2.0,7.0,9.0,4.0,-5.0,3.0,8.0,1.0,-2.0,4.0,both
3,3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4,-2.8,-4.2,2.8,4.2,-5.4,-8.4,-0.252,-1.39,-6.5,0.041,0.041,0.040,3.361,3.1,0.025,-0.009,0.0,0.003,0.0,0.0,0.0,0,-0.150,0.0,-1.000,0,-1,-2,-0.001,4,6,0.113,-6,-1,-0.185961,2,-1,1,-9,0,2,3,1,-4,8,-2.800000,-4.200000,2.800000,4.200000,-5.400000,-8.400000,-0.252000,-1.390000,-6.500000,0.041000,0.041000,0.040000,3.361000,3.100000,0.025000,-0.009000,0.0,0.003000,0.0,0.0,0.0,0.0,-0.150000,0.0,-1.000000,0.0,-1.000000,-2.000000,-0.001000,4.000000,6.000000,0.113000,-6.000000,-1.000000,-0.185961,2.000000,-1.000000,1.000000,-9.000000,0.000000,2.000000,3.000000,1.000000,-4.000000,8.000000,-2.80,-4.20,2.80,4.20,-5.4,-8.4,-0.2520,-1.390,-6.5,0.0410,0.0410,0.040,3.3610,3.10,0.0250,-0.009,0.0,0.0030,0.0,0.0,0.0,0.0,-0.150,0.0,-1.0000,0.0,-1.0,-2.0,-0.001,4.0,6.0,0.1130,-6.0,-1.0,-0.185961,2.0,-1.0,1.0,-9.0,0.0,2.0,3.0,1.0,-4.0,8.0,both
4,4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4,-5.7,-2.7,5.7,2.7,-11.2,-5.4,0.095,0.75,-0.9,-0.032,-0.032,-0.054,-4.026,-3.8,-0.104,-0.056,0.0,0.003,0.0,0.0,0.0,-1,-0.032,0.0,-1.000,0,-10,-5,-0.083,-4,-4,-0.150,20,26,-0.038462,1,-7,-6,-1,4,-5,-3,-10,-4,8,-5.700000,-2.700000,5.700000,2.700000,-11.200000,-5.400000,0.095000,0.750000,-0.900000,-0.032000,-0.032000,-0.054000,-4.026000,-3.800000,-0.104000,-0.056000,0.0,0.003000,0.0,0.0,0.0,-1.0,-0.032000,0.0,-1.000000,0.0,-10.000000,-5.000000,-0.083000,-4.000000,-4.000000,-0.150000,20.000000,26.000000,-0.038462,1.000000,-7.000000,-6.000000,-1.000000,4.000000,-5.000000,-3.000000,-10.000000,-4.000000,8.000000,-5.70,-2.70,5.70,2.70,-11.2,-5.4,0.0950,0.750,-0.9,-0.0320,-0.0320,-0.054,-4.0260,-3.80,-0.1040,-0.056,0.0,0.0030,0.0,0.0,0.0,-1.0,-0.032,0.0,-1.0000,0.0,-10.0,-5.0,-0.083,-4.0,-4.0,-0.1500,20.0,26.0,-0.038462,1.0,-7.0,-6.0,-1.0,4.0,-5.0,-3.0,-10.0,-4.0,8.0,both
10261,10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9,12.4,9.9,-12.4,-9.9,24.8,19.8,0.169,0.05,6.3,-0.026,-0.026,0.020,5.772,5.5,0.149,0.125,0.0,-0.001,0.0,0.0,0.0,0,0.136,0.0,0.142,0,3,-10,0.088,9,-5,0.251,-6,-8,-0.090909,-6,4,-2,8,-4,4,4,5,9,-18,-6.810000,-6.190000,6.810000,6.190000,-13.580000,-12.360000,0.081500,-0.043000,1.820000,-0.060600,-0.060600,-0.043800,2.614000,2.760000,0.002000,-0.001100,0.0,0.000400,0.0,0.0,0.0,-0.7,-0.041000,0.0,0.173300,0.0,-2.100000,-4.700000,-0.000300,-0.300000,-3.400000,0.018100,-2.300000,-3.000000,-0.028349,-3.400000,-1.200000,-4.600000,2.300000,-1.800000,0.800000,2.300000,-0.600000,-6.800000,13.600000,-5.90,-2.70,5.90,2.70,-11.7,-5.3,0.1290,0.045,2.2,-0.0785,-0.0785,-0.094,2.9135,3.00,0.0315,0.034,0.0,-0.0005,0.0,0.0,0.0,0.0,-0.002,0.0,0.0300,0.0,1.0,-5.5,0.007,-1.0,-2.5,0.0130,-5.0,-3.5,-0.025452,-4.0,-1.5,-6.5,2.5,-2.5,2.0,3.0,0.0,-1.5,3.0,both
10262,10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10,-8.5,-12.4,8.5,12.4,-17.0,-24.8,-0.265,-2.38,-9.5,0.226,0.226,0.176,4.020,3.8,-0.088,-0.104,0.0,0.002,0.0,0.0,0.0,2,-0.188,0.0,-1.000,0,-2,9,-0.067,-3,1,-0.091,-3,2,-0.222727,15,0,15,-13,-5,-3,4,0,-10,20,-0.366667,-3.733333,0.366667,3.733333,-0.800000,-7.466667,-0.124333,-1.060000,-5.566667,0.118333,0.118333,0.096667,1.870333,1.466667,-0.050333,-0.037333,0.0,0.001333,0.0,0.0,0.0,1.0,-0.112667,0.0,-0.297667,0.0,-4.666667,2.000000,-0.062333,2.333333,1.333333,0.060333,4.666667,6.000000,-0.009750,8.333333,-0.666667,7.666667,-7.333333,-1.666667,-3.000000,1.333333,0.666667,-2.333333,4.666667,-6.90,-8.50,6.90,8.50,-13.8,-17.0,-0.2650,-1.010,-9.5,0.1000,0.1000,0.058,2.5730,1.90,-0.0880,-0.088,0.0,0.0010,0.0,0.0,0.0,1.0,-0.188,0.0,-0.0880,0.0,-2.0,6.0,-0.067,5.0,1.0,0.1250,8.0,8.0,0.075294,9.0,0.0,5.0,-13.0,-1.0,-3.0,1.0,1.0,-7.0,14.0,both
10263,10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19,-20.0,-23.6,20.0,23.6,-40.0,-47.2,0.080,-0.06,-3.1,0.093,0.093,0.032,-1.063,-1.5,-0.204,-0.161,0.0,-0.003,0.0,0.0,0.0,3,-0.130,0.0,-1.000,0,-10,8,-0.162,-6,-9,-0.084,7,5,0.150183,9,-8,1,-3,6,-4,-2,-10,-19,38,-5.275000,-8.700000,5.275000,8.700000,-10.600000,-17.400000,-0.073250,-0.810000,-4.950000,0.112000,0.112000,0.080500,1.137000,0.725000,-0.088750,-0.068250,0.0,0.000250,0.0,0.0,0.0,1.5,-0.117000,0.0,-0.473250,0.0,-6.000000,3.500000,-0.087250,0.250000,-1.250000,0.024250,5.250000,5.750000,0.030233,8.500000,-2.500000,6.000000,-6.250000,0.250000,-3.250000,0.500000,-2.000000,-6.500000,13.000000,-7.70,-10.45,7.70,10.45,-15.4,-20.9,-0.0925,-0.535,-6.3,0.0965,0.0965,0.057,0.7955,0.30,-0.1045,-0.096,0.0,0.0010,0.0,0.0,0.0,1.5,-0.159,0.0,-0.5440,0.0,-6.0,7.0,-0.106,1.0,0.0,0.0205,7.5,6.5,0.096738,9.0,-3.0,4.0,-8.0,0.0,-3.5,0.0,0.5,-8.5,17.0,both
10264,10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8,13.0,9.6,-13.0,-9.6,26.0,19.4,0.143,1.02,6.2,-0.194,-0.194,-0.136,-2.559,-3.0,0.090,0.102,0.0,0.002,0.0,0.0,0.0,-1,0.138,0.0,1.000,0,2,-11,0.084,0,-5,0.056,4,2,0.130031,-9,-1,-10,7,0,1,-3,2,8,-16,-1.620000,-5.040000,1.620000,5.040000,-3.280000,-10.040000,-0.030000,-0.444000,-2.720000,0.050800,0.050800,0.037200,0.397800,-0.020000,-0.053000,-0.034200,0.0,0.000600,0.0,0.0,0.0,1.0,-0.066000,0.0,-0.178600,0.0,-4.400000,0.600000,-0.053000,0.200000,-2.000000,0.030600,5.000000,5.000000,0.050193,5.000000,-2.200000,2.800000,-3.600000,0.200000,-2.400000,-0.200000,-1.200000,-3.600000,7.200000,-6.90,-8.50,6.90,8.50,-13.8,-17.0,0.0800,-0.060,-3.1,0.0930,0.0930,0.056,-0.9820,-1.30,-0.0880,-0.088,0.0,0.0010,0.0,0.0,0.0,1.0,-0.130,0.0,-0.0880,0.0,-2.0,6.0,-0.067,0.0,-1.0,0.0560,7.0,5.0,0.118182,9.0,-1.0,3.0,-3.0,0.0,-3.0,-1.0,1.0,-7.0,14.0,both
10265,10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23,23.7,24.3,-23.7,-24.3,47.4,48.4,-0.059,0.59,3.3,-0.014,-0.014,0.028,-1.209,-1.2,0.144,0.146,0.0,-0.002,0.0,0.0,0.0,1,0.344,0.0,1.000,0,9,-1,0.108,6,11,0.072,-1,-9,0.320000,-7,7,0,4,2,8,-3,2,23,-46,2.600000,-0.150000,-2.600000,0.150000,5.166667,-0.300000,-0.034833,-0.271667,-1.716667,0.040000,0.040000,0.035667,0.130000,-0.216667,-0.020167,-0.004167,0.0,0.000167,0.0,0.0,0.0,1.0,0.002333,0.0,0.017833,0.0,-2.166667,0.333333,-0.026167,1.166667,0.166667,0.037500,4.000000,2.666667,0.095160,3.000000,-0.666667,2.333333,-2.333333,0.500000,-0.666667,-0.666667,-0.666667,0.833333,-1.666667,3.05,0.55,-3.05,-0.55,6.1,1.2,0.0105,0.075,0.1,0.0610,0.0610,0.044,-1.0225,-1.25,-0.0150,-0.004,0.0,0.0010,0.0,0.0,0.0,1.0,0.000,0.0,0.0535,0.0,-2.0,2.5,-0.021,2.5,0.0,0.0640,5.5,3.5,0.124106,5.0,-0.5,2.0,0.5,0.5,-1.0,-1.5,1.0,0.5,-1.0,both

In [42]:
df_and_df_stats_ah_diff_cma_median.value_counts('_merge')

_merge
both          10266
right_only        0
left_only         0
dtype: int64

In [43]:
df_and_df_stats_ah_diff_cma_median.drop(columns='_merge', inplace=True)

In [44]:
p(df_and_df_stats_ah_diff_cma_median)

(10266, 246)

,index,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma,E_OFF_RATING_ah_diff_median,OFF_RATING_ah_diff_median,E_DEF_RATING_ah_diff_median,DEF_RATING_ah_diff_median,E_NET_RATING_ah_diff_median,NET_RATING_ah_diff_median,AST_PCT_ah_diff_median,AST_TOV_ah_diff_median,AST_RATIO_ah_diff_median,OREB_PCT_ah_diff_median,DREB_PCT_ah_diff_median,REB_PCT_ah_diff_median,E_TM_TOV_PCT_ah_diff_median,TM_TOV_PCT_ah_diff_median,EFG_PCT_ah_diff_median,TS_PCT_ah_diff_median,USG_PCT_ah_diff_median,E_USG_PCT_ah_diff_median,E_PACE_ah_diff_median,PACE_ah_diff_median,PACE_PER40_ah_diff_median,POSS_ah_diff_median,PIE_ah_diff_median,duration_minutes_ah_diff_median,w_pct_ah_diff_median,min_ah_diff_median,fgm_ah_diff_median,fga_ah_diff_median,fg_pct_ah_diff_median,fg3m_ah_diff_median,fg3a_ah_diff_median,fg3_pct_ah_diff_median,ftm_ah_diff_median,fta_ah_diff_median,ft_pct_ah_diff_median,oreb_ah_diff_median,dreb_ah_diff_median,reb_ah_diff_median,ast_ah_diff_median,stl_ah_diff_median,blk_ah_diff_median,tov_ah_diff_median,pf_ah_diff_median,pts_ah_diff_median,spread_ah_diff_median
0,0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8,-7.8,-7.8,7.8,7.8,-15.4,-15.4,-0.225,-0.37,-7.2,-0.018,-0.018,-0.056,-3.058,-3.0,-0.103,-0.079,0.0,0.004,0.0,0.0,0.0,-1,-0.198,0.0,-1.000,0,-5,5,-0.099,0,4,-0.100,2,0,0.080000,3,-6,-3,-10,4,2,-1,2,-8,16,-7.800000,-7.800000,7.800000,7.800000,-15.400000,-15.400000,-0.225000,-0.370000,-7.200000,-0.018000,-0.018000,-0.056000,-3.058000,-3.000000,-0.103000,-0.079000,0.0,0.004000,0.0,0.0,0.0,-1.0,-0.198000,0.0,-1.000000,0.0,-5.000000,5.000000,-0.099000,0.000000,4.000000,-0.100000,2.000000,0.000000,0.080000,3.000000,-6.000000,-3.000000,-10.000000,4.000000,2.000000,-1.000000,2.000000,-8.000000,16.000000,-7.80,-7.80,7.80,7.80,-15.4,-15.4,-0.2250,-0.370,-7.2,-0.0180,-0.0180,-0.056,-3.0580,-3.00,-0.1030,-0.079,0.0,0.0040,0.0,0.0,0.0,-1.0,-0.198,0.0,-1.0000,0.0,-5.0,5.0,-0.099,0.0,4.0,-0.1000,2.0,0.0,0.080000,3.0,-6.0,-3.0,-10.0,4.0,2.0,-1.0,2.0,-8.0,16.0
1,1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14,-10.8,-15.6,10.8,15.6,-21.6,-31.2,-0.304,-1.28,-8.3,-0.246,-0.246,-0.218,4.893,4.4,0.031,0.036,0.0,0.004,0.0,0.0,0.0,0,-0.250,0.0,-1.000,0,-7,-19,0.024,-1,-1,-0.026,1,1,0.020833,-11,-7,-18,-16,-8,2,7,-3,-14,28,-10.800000,-15.600000,10.800000,15.600000,-21.600000,-31.200000,-0.304000,-1.280000,-8.300000,-0.246000,-0.246000,-0.218000,4.893000,4.400000,0.031000,0.036000,0.0,0.004000,0.0,0.0,0.0,0.0,-0.250000,0.0,-1.000000,0.0,-7.000000,-19.000000,0.024000,-1.000000,-1.000000,-0.026000,1.000000,1.000000,0.020833,-11.000000,-7.000000,-18.000000,-16.000000,-8.000000,2.000000,7.000000,-3.000000,-14.000000,28.000000,-10.80,-15.60,10.80,15.60,-21.6,-31.2,-0.3040,-1.280,-8.3,-0.2460,-0.2460,-0.218,4.8930,4.40,0.0310,0.036,0.0,0.0040,0.0,0.0,0.0,0.0,-0.250,0.0,-1.0000,0.0,-7.0,-19.0,0.024,-1.0,-1.0,-0.0260,1.0,1.0,0.020833,-11.0,-7.0,-18.0,-16.0,-8.0,2.0,7.0,-3.0,-14.0,28.0
2,2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2,-3.7,-0.9,3.7,0.9,-7.6,-1.8,0.133,-0.56,1.8,0.091,0.091,0.108,8.100,8.9,-0.002,0.015,0.0,-0.002,0.0,0.0,0.0,-1,0.014,0.0,-1.000,0,-2,-5,0.001,-1,-1,-0.029,3,0,0.107143,2,7,9,4,-5,3,8,1,-2,4,-3.700000,-0.900000,3.700000,0.900000,-7.600000,-1.800000,0.133000,-0.560000,1.800000,0.091000,0.091000,0.108000,8.100000,8.900000,-0.002000,0.015000,0.0,-0.002000,0.0,0.0,0.0,-1.0,0.014000,0.0,-1.000000,0.0,-2.000000,-5.000000,0.001000,-1.000000,-1.000000,-0.029000,3.000000,0.000000,0.107143,2.000000,7.000000,9.000000,4.000000,-5.000000,3.000000,8.000000,1.000000,-2.000000,4.000000,-3.70,-0.90,3.70,0.90,-7.6,-1.8,0.1330,-0.560,1.8,0.0910,0.0910,0.108,8.1000,8.90,-0.0020,0.015,0.0,-0.0020,0.0,0.0,0.0,-1.0,0.014,0.0,-1.0000,0.0,-2.0,-5.0,0.001,-1.0,-1.0,-0.0290,3.0,0.0,0.107143,2.0,7.0,9.0,4.0,-5.0,3.0,8.0,1.0,-2.0,4.0
3,3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4,-2.8,-4.2,2.8,4.2,-5.4,-8.4,-0.252,-1.39,-6.5,0.041,0.041,0.040,3.361,3.1,0.025,-0.009,0.0,0.003,0.0,0.0,0.0,0,-0.150,0.0,-1.000,0,-1,-2,-0.001,4,6,0.113,-6,-1,-0.185961,2,-1,1,-9,0,2,3,1,-4,8,-2.800000,-4.200000,2.800000,4.200000,-5.400000,-8.400000,-0.252000,-1.390000,-6.500000,0.041000,0.041000,0.040000,3.361000,3.100000,0.025000,-0.009000,0.0,0.003000,0.0,0.0,0.0,0.0,-0.150000,0.0,-1.000000,0.0,-1.000000,-2.000000,-0.001000,4.000000,6.000000,0.113000,-6.000000,-1.000000,-0.185961,2.000000,-1.000000,1.000000,-9.000000,0.000000,2.000000,3.000000,1.000000,-4.000000,8.000000,-2.80,-4.20,2.80,4.20,-5.4,-8.4,-0.2520,-1.390,-6.5,0.0410,0.0410,0.040,3.3610,3.10,0.0250,-0.009,0.0,0.0030,0.0,0.0,0.0,0.0,-0.150,0.0,-1.0000,0.0,-1.0,-2.0,-0.001,4.0,6.0,0.1130,-6.0,-1.0,-0.185961,2.0,-1.0,1.0,-9.0,0.0,2.0,3.0,1.0,-4.0,8.0
4,4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4,-5.7,-2.7,5.7,2.7,-11.2,-5.4,0.095,0.75,-0.9,-0.032,-0.032,-0.054,-4.026,-3.8,-0.104,-0.056,0.0,0.003,0.0,0.0,0.0,-1,-0.032,0.0,-1.000,0,-10,-5,-0.083,-4,-4,-0.150,20,26,-0.038462,1,-7,-6,-1,4,-5,-3,-10,-4,8,-5.700000,-2.700000,5.700000,2.700000,-11.200000,-5.400000,0.095000,0.750000,-0.900000,-0.032000,-0.032000,-0.054000,-4.026000,-3.800000,-0.104000,-0.056000,0.0,0.003000,0.0,0.0,0.0,-1.0,-0.032000,0.0,-1.000000,0.0,-10.000000,-5.000000,-0.083000,-4.000000,-4.000000,-0.150000,20.000000,26.000000,-0.038462,1.000000,-7.000000,-6.000000,-1.000000,4.000000,-5.000000,-3.000000,-10.000000,-4.000000,8.000000,-5.70,-2.70,5.70,2.70,-11.2,-5.4,0.0950,0.750,-0.9,-0.0320,-0.0320,-0.054,-4.0260,-3.80,-0.1040,-0.056,0.0,0.0030,0.0,0.0,0.0,-1.0,-0.032,0.0,-1.0000,0.0,-10.0,-5.0,-0.083,-4.0,-4.0,-0.1500,20.0,26.0,-0.038462,1.0,-7.0,-6.0,-1.0,4.0,-5.0,-3.0,-10.0,-4.0,8.0
10261,10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9,12.4,9.9,-12.4,-9.9,24.8,19.8,0.169,0.05,6.3,-0.026,-0.026,0.020,5.772,5.5,0.149,0.125,0.0,-0.001,0.0,0.0,0.0,0,0.136,0.0,0.142,0,3,-10,0.088,9,-5,0.251,-6,-8,-0.090909,-6,4,-2,8,-4,4,4,5,9,-18,-6.810000,-6.190000,6.810000,6.190000,-13.580000,-12.360000,0.081500,-0.043000,1.820000,-0.060600,-0.060600,-0.043800,2.614000,2.760000,0.002000,-0.001100,0.0,0.000400,0.0,0.0,0.0,-0.7,-0.041000,0.0,0.173300,0.0,-2.100000,-4.700000,-0.000300,-0.300000,-3.400000,0.018100,-2.300000,-3.000000,-0.028349,-3.400000,-1.200000,-4.600000,2.300000,-1.800000,0.800000,2.300000,-0.600000,-6.800000,13.600000,-5.90,-2.70,5.90,2.70,-11.7,-5.3,0.1290,0.045,2.2,-0.0785,-0.0785,-0.094,2.9135,3.00,0.0315,0.034,0.0,-0.0005,0.0,0.0,0.0,0.0,-0.002,0.0,0.0300,0.0,1.0,-5.5,0.007,-1.0,-2.5,0.0130,-5.0,-3.5,-0.025452,-4.0,-1.5,-6.5,2.5,-2.5,2.0,3.0,0.0,-1.5,3.0
10262,10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10,-8.5,-12.4,8.5,12.4,-17.0,-24.8,-0.265,-2.38,-9.5,0.226,0.226,0.176,4.020,3.8,-0.088,-0.104,0.0,0.002,0.0,0.0,0.0,2,-0.188,0.0,-1.000,0,-2,9,-0.067,-3,1,-0.091,-3,2,-0.222727,15,0,15,-13,-5,-3,4,0,-10,20,-0.366667,-3.733333,0.366667,3.733333,-0.800000,-7.466667,-0.124333,-1.060000,-5.566667,0.118333,0.118333,0.096667,1.870333,1.466667,-0.050333,-0.037333,0.0,0.001333,0.0,0.0,0.0,1.0,-0.112667,0.0,-0.297667,0.0,-4.666667,2.000000,-0.062333,2.333333,1.333333,0.060333,4.666667,6.000000,-0.009750,8.333333,-0.666667,7.666667,-7.333333,-1.666667,-3.000000,1.333333,0.666667,-2.333333,4.666667,-6.90,-8.50,6.90,8.50,-13.8,-17.0,-0.2650,-1.010,-9.5,0.1000,0.1000,0.058,2.5730,1.90,-0.0880,-0.088,0.0,0.0010,0.0,0.0,0.0,1.0,-0.188,0.0,-0.0880,0.0,-2.0,6.0,-0.067,5.0,1.0,0.1250,8.0,8.0,0.075294,9.0,0.0,5.0,-13.0,-1.0,-3.0,1.0,1.0,-7.0,14.0
10263,10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19,-20.0,-23.6,20.0,23.6,-40.0,-47.2,0.080,-0.06,-3.1,0.093,0.093,0.032,-1.063,-1.5,-0.204,-0.161,0.0,-0.003,0.0,0.0,0.0,3,-0.130,0.0,-1.000,0,-10,8,-0.162,-6,-9,-0.084,7,5,0.150183,9,-8,1,-3,6,-4,-2,-10,-19,38,-5.275000,-8.700000,5.275000,8.700000,-10.600000,-17.400000,-0.073250,-0.810000,-4.950000,0.112000,0.112000,0.080500,1.137000,0.725000,-0.088750,-0.068250,0.0,0.000250,0.0,0.0,0.0,1.5,-0.117000,0.0,-0.473250,0.0,-6.000000,3.500000,-0.087250,0.250000,-1.250000,0.024250,5.250000,5.750000,0.030233,8.500000,-2.500000,6.000000,-6.250000,0.250000,-3.250000,0.500000,-2.000000,-6.500000,13.000000,-7.70,-10.45,7.70,10.45,-15.4,-20.9,-0.0925,-0.535,-6.3,0.0965,0.0965,0.057,0.7955,0.30,-0.1045,-0.096,0.0,0.0010,0.0,0.0,0.0,1.5,-0.159,0.0,-0.5440,0.0,-6.0,7.0,-0.106,1.0,0.0,0.0205,7.5,6.5,0.096738,9.0,-3.0,4.0,-8.0,0.0,-3.5,0.0,0.5,-8.5,17.0
10264,10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8,13.0,9.6,-13.0,-9.6,26.0,19.4,0.143,1.02,6.2,-0.194,-0.194,-0.136,-2.559,-3.0,0.090,0.102,0.0,0.002,0.0,0.0,0.0,-1,0.138,0.0,1.000,0,2,-11,0.084,0,-5,0.056,4,2,0.130031,-9,-1,-10,7,0,1,-3,2,8,-16,-1.620000,-5.040000,1.620000,5.040000,-3.280000,-10.040000,-0.030000,-0.444000,-2.720000,0.050800,0.050800,0.037200,0.397800,-0.020000,-0.053000,-0.034200,0.0,0.000600,0.0,0.0,0.0,1.0,-0.066000,0.0,-0.178600,0.0,-4.400000,0.600000,-0.053000,0.200000,-2.000000,0.030600,5.000000,5.000000,0.050193,5.000000,-2.200000,2.800000,-3.600000,0.200000,-2.400000,-0.200000,-1.200000,-3.600000,7.200000,-6.90,-8.50,6.90,8.50,-13.8,-17.0,0.0800,-0.060,-3.1,0.0930,0.0930,0.056,-0.9820,-1.30,-0.0880,-0.088,0.0,0.0010,0.0,0.0,0.0,1.0,-0.130,0.0,-0.0880,0.0,-2.0,6.0,-0.067,0.0,-1.0,0.0560,7.0,5.0,0.118182,9.0,-1.0,3.0,-3.0,0.0,-3.0,-1.0,1.0,-7.0,14.0
10265,10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23,23.7,24.3,-23.7,-24.3,47.4,48.4,-0.059,0.59,3.3,-0.014,-0.014,0.028,-1.209,-1.2,0.144,0.146,0.0,-0.002,0.0,0.0,0.0,1,0.344,0.0,1.000,0,9,-1,0.108,6,11,0.072,-1,-9,0.320000,-7,7,0,4,2,8,-3,2,23,-46,2.600000,-0.150000,-2.600000,0.150000,5.166667,-0.300000,-0.034833,-0.271667,-1.716667,0.040000,0.040000,0.035667,0.130000,-0.216667,-0.020167,-0.004167,0.0,0.000167,0.0,0.0,0.0,1.0,0.002333,0.0,0.017833,0.0,-2.166667,0.333333,-0.026167,1.166667,0.166667,0.037500,4.000000,2.666667,0.095160,3.000000,-0.666667,2.333333,-2.333333,0.500000,-0.666667,-0.666667,-0.666667,0.833333,-1.666667,3.05,0.55,-3.05,-0.55,6.1,1.2,0.0105,0.075,0.1,0.0610,0.0610,0.044,-1.0225,-1.25,-0.0150,-0.004,0.0,0.0010,0.0,0.0,0.0,1.0,0.000,0.0,0.0535,0.0,-2.0,2.5,-0.021,2.5,0.0,0.0640,5.5,3.5,0.124106,5.0,-0.5,2.0,0.5,0.5,-1.0,-1.5,1.0,0.5,-1.0

In [45]:
################################################################################

#get team matchup stat dif. cma log() for each stat difference (per matchup per season)

#get team matchup stat dif. log() for each stat difference (per matchup per season)

#get team matchup stat dif. ln for each stat difference (per matchup per season)

#get team matchup stat dif. cma ln for each stat difference (per matchup per season)

In [46]:
df_stats_ah_diff_cma_log = df.groupby(['season', 'matchup'])[list_stat_ah_diff].expanding(min_periods=0).mean().reset_index()
df_stats_ah_diff_cma_log.rename(columns={'level_2':'index'}, inplace=True)
p(df_stats_ah_diff_cma_log)

(10266, 48)

,season,matchup,index,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff
0,2010-11,ATL vs. BOS,197,27.900,24.600000,-27.900,-24.600000,55.800000,49.200000,-0.100000,-0.220000,3.300000,0.139000,0.139000,0.22200,5.930000,5.400000,0.184000,0.168000,0.0,-0.003000,0.0,0.0,0.0,1.000000,0.398000,0.0,0.143000,0.0,12.000000,-6.000000,0.187000,-1.000000,-5.000000,0.080000,0.000000,1.000000,-0.045752,2.000000,18.000000,20.000000,5.000000,1.000000,5.000000,3.000000,1.000000,23.000000,-46.000000
1,2010-11,ATL vs. BOS,377,9.800,6.050000,-9.800,-6.050000,19.600000,12.100000,-0.132500,-0.830000,-2.200000,-0.085500,0.414500,0.11100,6.757500,6.250000,0.070000,0.080000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.134000,0.0,-0.052000,0.0,1.000000,-10.500000,0.078500,-2.000000,-6.500000,0.023500,5.500000,7.000000,0.009321,1.500000,10.500000,12.000000,-3.500000,-0.500000,3.000000,4.500000,-0.500000,5.500000,-11.000000
2,2010-11,ATL vs. BOS,1122,5.500,2.133333,-5.500,-2.133333,11.066667,4.266667,-0.027000,0.203333,1.166667,-0.159667,0.507000,0.07400,3.056667,2.633333,0.078000,0.061333,0.0,0.000000,0.0,0.0,0.0,0.000000,0.095333,0.0,0.003333,0.0,2.000000,-8.666667,0.078667,-0.666667,-5.666667,0.099000,-1.333333,1.333333,-0.099341,-2.666667,6.000000,3.333333,0.333333,0.666667,3.333333,1.666667,1.333333,2.000000,-4.000000
3,2010-11,ATL vs. CHA,389,-9.100,-4.600000,9.100,4.600000,-18.200000,-9.200000,-0.122000,-0.210000,-5.400000,0.418000,-0.582000,0.00000,-2.781000,-2.100000,-0.109000,-0.094000,0.0,-0.010000,0.0,0.0,0.0,-1.000000,-0.094000,0.0,-0.261000,0.0,-3.000000,9.000000,-0.083000,-4.000000,-11.000000,-0.097000,5.000000,7.000000,-0.073077,7.000000,-1.000000,6.000000,-6.000000,4.000000,-5.000000,-7.000000,-5.000000,-5.000000,10.000000
4,2010-11,ATL vs. CHA,648,1.000,7.000000,-1.000,-7.000000,2.000000,14.000000,-0.123500,-0.465000,-4.400000,0.340500,-0.659500,0.00000,-0.665000,0.150000,-0.023500,-0.001500,0.0,-0.004500,0.0,0.0,0.0,-0.500000,0.016000,0.0,-0.011000,0.0,-1.000000,2.500000,-0.022000,-0.500000,-5.000000,0.022000,8.000000,9.000000,0.023244,2.000000,2.500000,4.500000,-5.000000,2.500000,-2.500000,-2.000000,-3.500000,5.500000,-11.000000
10261,2017-18,TOR vs. WAS,10213,-6.525,-4.575000,6.525,4.575000,-13.075000,-9.125000,-0.026250,-0.102500,-1.575000,-0.022875,-0.022750,-0.03525,0.173000,0.512500,-0.025375,-0.022250,0.0,0.000000,0.0,0.0,0.0,-0.375000,-0.069000,0.0,-0.191250,0.0,-2.625000,-1.000000,-0.026625,0.125000,-3.625000,0.063125,0.125000,0.375000,-0.000295,-1.875000,-3.250000,-5.125000,-2.625000,0.875000,-2.750000,0.625000,-0.250000,-5.000000,10.000000
10262,2017-18,TOR vs. WAS,10222,-7.500,-4.955556,7.500,4.955556,-15.022222,-9.888889,-0.036222,-0.250000,-1.944444,-0.000222,-0.000111,-0.01400,0.952667,1.388889,-0.032667,-0.028778,0.0,-0.000889,0.0,0.0,0.0,-0.555556,-0.074222,0.0,-0.192222,0.0,-2.444444,0.000000,-0.029444,-0.555556,-3.111111,0.028556,-0.111111,-0.333333,0.012364,-0.777778,-2.111111,-2.888889,-2.888889,0.444444,-2.555556,1.111111,-0.222222,-5.555556,11.111111
10263,2017-18,TOR vs. WAS,10225,-5.420,-3.470000,5.420,3.470000,-10.860000,-6.900000,-0.025100,-0.054000,-1.340000,0.004300,0.004500,-0.00960,0.106300,0.460000,-0.026700,-0.026100,0.0,-0.001000,0.0,0.0,0.0,-0.400000,-0.051200,0.0,-0.139600,0.0,-1.400000,1.100000,-0.022600,-0.600000,-2.500000,0.017300,-0.600000,-0.500000,-0.005163,-0.200000,-1.900000,-2.100000,-2.000000,0.900000,-2.200000,0.200000,-0.100000,-4.000000,8.000000
10264,2017-18,UTA vs. WAS,9293,-53.300,-49.400000,53.300,49.400000,-106.600000,-98.800000,-0.283000,-1.120000,-14.500000,-0.100000,-0.100000,-0.22600,-3.527000,-3.000000,-0.358000,-0.308000,0.0,0.004000,0.0,0.0,0.0,-2.000000,-0.768000,0.0,-0.020000,0.0,-20.000000,4.000000,-0.278000,-12.000000,-14.000000,-0.271000,5.000000,5.000000,0.048309,2.000000,-23.000000,-21.000000,-20.000000,-1.000000,-1.000000,-3.000000,1.000000,-47.000000,94.000000
10265,2017-18,UTA vs. WAS,9557,-25.250,-22.600000,25.250,22.600000,-50.500000,-45.200000,-0.179000,-0.220000,-8.000000,-0.062500,-0.062500,-0.15100,-6.805000,-6.550000,-0.210500,-0.184500,0.0,0.001000,0.0,0.0,0.0,-1.500000,-0.379000,0.0,-0.083000,0.0,-9.000000,9.000000,-0.168500,-5.500000,-3.000000,-0.169000,1.500000,0.500000,0.055829,2.000000,-15.500000,-13.500000,-11.000000,3.000000,0.500000,-7.000000,0.500000,-22.000000,44.000000

In [47]:
#get team matchup stat dif. cma log() for each stat difference (per matchup per season)

#m1: take diff cma and take log of them: df_stats_ah_diff_cma_log

#m2: create cma of stat differences per matchup per season and take log: df_stats_ah_diff_cma_log

#m3: take diff cma and subtract by min() and add 1; take log of them: df_stats_ah_diff_cma_logZZ

In [48]:
#m1: take diff cma and take log of them: df_stats_ah_diff_cma_log

In [49]:
df_stats_ah_diff_cma_log = pd.DataFrame({})
df_stats_ah_diff_cma_log = np.log(df_stats_ah_diff_cma[list_stats_ah_diff_dsmi_cma])
p(df_stats_ah_diff_cma_log)

(10266, 45)

<ipython-input-49-fbe1c7303e3b>:2: RuntimeWarning: divide by zero encountered in log
  df_stats_ah_diff_cma_log = np.log(df_stats_ah_diff_cma[list_stats_ah_diff_dsmi_cma])
<ipython-input-49-fbe1c7303e3b>:2: RuntimeWarning: invalid value encountered in log
  df_stats_ah_diff_cma_log = np.log(df_stats_ah_diff_cma[list_stats_ah_diff_dsmi_cma])

,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma
0,3.328627,3.202746,NaN,NaN,4.021774,3.895894,NaN,NaN,1.193922,-1.973281,-1.973281,-1.505078,1.780024,1.686399,-1.692820,-1.783791,-inf,NaN,-inf,-inf,-inf,0.0,-0.921303,-inf,-1.944911,-inf,2.484907,NaN,-1.676647,NaN,NaN,-2.525729,-inf,0.000000,NaN,0.693147,2.890372,2.995732,1.609438,0.000000,1.609438,1.098612,0.000000,3.135494,NaN
1,2.282382,1.800058,NaN,NaN,2.975530,2.493205,NaN,NaN,NaN,NaN,-0.880682,-2.198225,1.910653,1.832581,-2.659260,-2.525729,-inf,-inf,-inf,-inf,-inf,-inf,-2.009915,-inf,NaN,-inf,0.000000,NaN,-2.544657,NaN,NaN,-3.750755,1.704748,1.945910,-4.675469,0.405465,2.351375,2.484907,NaN,NaN,1.098612,1.504077,NaN,1.704748,NaN
2,1.704748,0.757686,NaN,NaN,2.403938,1.450833,NaN,-1.592909,0.154151,NaN,-0.679244,-2.603690,1.117325,0.968250,-2.551046,-2.791432,-inf,-inf,-inf,-inf,-inf,-inf,-2.350376,-inf,-5.703782,-inf,0.693147,NaN,-2.542536,NaN,NaN,-2.312635,NaN,0.287682,NaN,NaN,1.791759,1.203973,-1.098612,-0.405465,1.203973,0.510826,0.287682,0.693147,NaN
3,NaN,NaN,2.208274,1.526056,NaN,NaN,NaN,NaN,NaN,-0.872274,NaN,-inf,NaN,NaN,NaN,NaN,-inf,NaN,-inf,-inf,-inf,NaN,NaN,-inf,NaN,-inf,NaN,2.197225,NaN,NaN,NaN,NaN,1.609438,1.945910,NaN,1.945910,NaN,1.791759,NaN,1.386294,NaN,NaN,NaN,NaN,2.302585
4,0.000000,1.945910,NaN,NaN,0.693147,2.639057,NaN,NaN,NaN,-1.077340,NaN,-inf,NaN,-1.897120,NaN,NaN,-inf,NaN,-inf,-inf,-inf,NaN,-4.135167,-inf,NaN,-inf,NaN,0.916291,NaN,NaN,NaN,-3.816713,2.079442,2.197225,-3.761702,0.693147,0.916291,1.504077,NaN,0.916291,NaN,NaN,NaN,1.704748,NaN
10261,NaN,NaN,1.875641,1.520607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.754464,-0.668455,NaN,NaN,-inf,-inf,-inf,-inf,-inf,NaN,NaN,-inf,NaN,-inf,NaN,NaN,NaN,-2.079442,NaN,-2.762638,-2.079442,-0.980829,NaN,NaN,NaN,NaN,NaN,-0.133531,NaN,-0.470004,NaN,NaN,2.302585
10262,NaN,NaN,2.014903,1.600509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.048490,0.328504,NaN,NaN,-inf,NaN,-inf,-inf,-inf,NaN,NaN,-inf,NaN,-inf,NaN,-inf,NaN,NaN,NaN,-3.555904,NaN,NaN,-4.392991,NaN,NaN,NaN,NaN,-0.810930,NaN,0.105361,NaN,NaN,2.407946
10263,NaN,NaN,1.690096,1.244155,NaN,NaN,NaN,NaN,NaN,-5.449140,-5.403678,NaN,-2.241490,-0.776529,NaN,NaN,-inf,NaN,-inf,-inf,-inf,NaN,NaN,-inf,NaN,-inf,NaN,0.095310,NaN,NaN,NaN,-4.057049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.105361,NaN,-1.609438,NaN,NaN,2.079442
10264,NaN,NaN,3.975936,3.899950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-inf,-5.521461,-inf,-inf,-inf,NaN,NaN,-inf,NaN,-inf,NaN,1.386294,NaN,NaN,NaN,NaN,1.609438,1.609438,-3.030134,0.693147,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,4.543295
10265,NaN,NaN,3.228826,3.117950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-inf,-6.907755,-inf,-inf,-inf,NaN,NaN,-inf,NaN,-inf,NaN,2.197225,NaN,NaN,NaN,NaN,0.405465,-0.693147,-2.885465,0.693147,NaN,NaN,NaN,1.098612,-0.693147,NaN,-0.693147,NaN,3.784190

<font color='red'> df_stats_ah_diff_cma_log not actually used</font>

In [50]:
p(df_stats_ah_diff_cma)

(10266, 46)

,index,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma
0,197,27.900,24.600000,-27.900,-24.600000,55.800000,49.200000,-0.100000,-0.220000,3.300000,0.139000,0.139000,0.22200,5.930000,5.400000,0.184000,0.168000,0.0,-0.003000,0.0,0.0,0.0,1.000000,0.398000,0.0,0.143000,0.0,12.000000,-6.000000,0.187000,-1.000000,-5.000000,0.080000,0.000000,1.000000,-0.045752,2.000000,18.000000,20.000000,5.000000,1.000000,5.000000,3.000000,1.000000,23.000000,-46.000000
1,377,9.800,6.050000,-9.800,-6.050000,19.600000,12.100000,-0.132500,-0.830000,-2.200000,-0.085500,0.414500,0.11100,6.757500,6.250000,0.070000,0.080000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.134000,0.0,-0.052000,0.0,1.000000,-10.500000,0.078500,-2.000000,-6.500000,0.023500,5.500000,7.000000,0.009321,1.500000,10.500000,12.000000,-3.500000,-0.500000,3.000000,4.500000,-0.500000,5.500000,-11.000000
2,1122,5.500,2.133333,-5.500,-2.133333,11.066667,4.266667,-0.027000,0.203333,1.166667,-0.159667,0.507000,0.07400,3.056667,2.633333,0.078000,0.061333,0.0,0.000000,0.0,0.0,0.0,0.000000,0.095333,0.0,0.003333,0.0,2.000000,-8.666667,0.078667,-0.666667,-5.666667,0.099000,-1.333333,1.333333,-0.099341,-2.666667,6.000000,3.333333,0.333333,0.666667,3.333333,1.666667,1.333333,2.000000,-4.000000
3,389,-9.100,-4.600000,9.100,4.600000,-18.200000,-9.200000,-0.122000,-0.210000,-5.400000,0.418000,-0.582000,0.00000,-2.781000,-2.100000,-0.109000,-0.094000,0.0,-0.010000,0.0,0.0,0.0,-1.000000,-0.094000,0.0,-0.261000,0.0,-3.000000,9.000000,-0.083000,-4.000000,-11.000000,-0.097000,5.000000,7.000000,-0.073077,7.000000,-1.000000,6.000000,-6.000000,4.000000,-5.000000,-7.000000,-5.000000,-5.000000,10.000000
4,648,1.000,7.000000,-1.000,-7.000000,2.000000,14.000000,-0.123500,-0.465000,-4.400000,0.340500,-0.659500,0.00000,-0.665000,0.150000,-0.023500,-0.001500,0.0,-0.004500,0.0,0.0,0.0,-0.500000,0.016000,0.0,-0.011000,0.0,-1.000000,2.500000,-0.022000,-0.500000,-5.000000,0.022000,8.000000,9.000000,0.023244,2.000000,2.500000,4.500000,-5.000000,2.500000,-2.500000,-2.000000,-3.500000,5.500000,-11.000000
10261,10213,-6.525,-4.575000,6.525,4.575000,-13.075000,-9.125000,-0.026250,-0.102500,-1.575000,-0.022875,-0.022750,-0.03525,0.173000,0.512500,-0.025375,-0.022250,0.0,0.000000,0.0,0.0,0.0,-0.375000,-0.069000,0.0,-0.191250,0.0,-2.625000,-1.000000,-0.026625,0.125000,-3.625000,0.063125,0.125000,0.375000,-0.000295,-1.875000,-3.250000,-5.125000,-2.625000,0.875000,-2.750000,0.625000,-0.250000,-5.000000,10.000000
10262,10222,-7.500,-4.955556,7.500,4.955556,-15.022222,-9.888889,-0.036222,-0.250000,-1.944444,-0.000222,-0.000111,-0.01400,0.952667,1.388889,-0.032667,-0.028778,0.0,-0.000889,0.0,0.0,0.0,-0.555556,-0.074222,0.0,-0.192222,0.0,-2.444444,0.000000,-0.029444,-0.555556,-3.111111,0.028556,-0.111111,-0.333333,0.012364,-0.777778,-2.111111,-2.888889,-2.888889,0.444444,-2.555556,1.111111,-0.222222,-5.555556,11.111111
10263,10225,-5.420,-3.470000,5.420,3.470000,-10.860000,-6.900000,-0.025100,-0.054000,-1.340000,0.004300,0.004500,-0.00960,0.106300,0.460000,-0.026700,-0.026100,0.0,-0.001000,0.0,0.0,0.0,-0.400000,-0.051200,0.0,-0.139600,0.0,-1.400000,1.100000,-0.022600,-0.600000,-2.500000,0.017300,-0.600000,-0.500000,-0.005163,-0.200000,-1.900000,-2.100000,-2.000000,0.900000,-2.200000,0.200000,-0.100000,-4.000000,8.000000
10264,9293,-53.300,-49.400000,53.300,49.400000,-106.600000,-98.800000,-0.283000,-1.120000,-14.500000,-0.100000,-0.100000,-0.22600,-3.527000,-3.000000,-0.358000,-0.308000,0.0,0.004000,0.0,0.0,0.0,-2.000000,-0.768000,0.0,-0.020000,0.0,-20.000000,4.000000,-0.278000,-12.000000,-14.000000,-0.271000,5.000000,5.000000,0.048309,2.000000,-23.000000,-21.000000,-20.000000,-1.000000,-1.000000,-3.000000,1.000000,-47.000000,94.000000
10265,9557,-25.250,-22.600000,25.250,22.600000,-50.500000,-45.200000,-0.179000,-0.220000,-8.000000,-0.062500,-0.062500,-0.15100,-6.805000,-6.550000,-0.210500,-0.184500,0.0,0.001000,0.0,0.0,0.0,-1.500000,-0.379000,0.0,-0.083000,0.0,-9.000000,9.000000,-0.168500,-5.500000,-3.000000,-0.169000,1.500000,0.500000,0.055829,2.000000,-15.500000,-13.500000,-11.000000,3.000000,0.500000,-7.000000,0.500000,-22.000000,44.000000

<font color='red'> how to deal with negative numbers when wanting to take the log??? just do the log(abs())???</font>

In [51]:
'''#Log Transform Example
data = pd.DataFrame({'value':[2,45, -23, 85, 28, 2, 35, -12]})
data['log+1'] = (data['value']+1).transform(np.log)
#Negative Values Handling
#Note that the values are different
data['log'] = (data['value']-data['value'].min()+1) .transform(np.log)
   value  log(x+1)  log(x-min(x)+1)
0      2   1.09861          3.25810
1     45   3.82864          4.23411
2    -23       nan          0.00000
3     85   4.45435          4.69135
4     28   3.36730          3.95124
5      2   1.09861          3.25810
6     35   3.58352          4.07754
7    -12       nan          2.48491'''

#https://towardsdatascience.com/feature-engineering-for-machine-learning-3a5e293a5114

"#Log Transform Example\ndata = pd.DataFrame({'value':[2,45, -23, 85, 28, 2, 35, -12]})\ndata['log+1'] = (data['value']+1).transform(np.log)\n#Negative Values Handling\n#Note that the values are different\ndata['log'] = (data['value']-data['value'].min()+1) .transform(np.log)\n   value  log(x+1)  log(x-min(x)+1)\n0      2   1.09861          3.25810\n1     45   3.82864          4.23411\n2    -23       nan          0.00000\n3     85   4.45435          4.69135\n4     28   3.36730          3.95124\n5      2   1.09861          3.25810\n6     35   3.58352          4.07754\n7    -12       nan          2.48491"

In [52]:
#m3: take diff cma and subtract by min() and add 1; take log of them: df_stats_ah_diff_cma_log

df_stats_ah_diff_cma_log = (df_stats_ah_diff_cma[list_stats_ah_diff_dsmi_cma] - df_stats_ah_diff_cma[list_stats_ah_diff_dsmi_cma].min() + 1).transform(np.log)
p(df_stats_ah_diff_cma_log)

(10266, 45)

,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma
0,4.468204,4.447346,2.833213,3.144152,5.155601,5.133443,0.378436,1.874874,3.072693,0.502592,0.710987,0.442118,3.356409,3.339322,0.433080,0.396761,0.0,0.007968,0.0,0.0,0.0,1.791759,0.856116,0.0,0.762207,0.0,3.688879,3.295837,0.393393,2.995732,3.401197,0.491643,3.401197,3.663562,0.456949,3.044522,3.806662,3.951244,3.401197,2.772589,3.044522,3.178054,3.091042,4.369448,3.931826
1,4.235555,4.202451,3.558201,3.731699,4.921440,4.886583,0.355925,1.776646,2.778819,0.356625,0.837897,0.368109,3.384848,3.369018,0.356275,0.335758,0.0,0.010940,0.0,0.0,0.0,1.609438,0.737164,0.0,0.666803,0.0,3.367296,3.113515,0.317362,2.944439,3.349904,0.456475,3.569533,3.806662,0.491228,3.020425,3.624341,3.784190,3.068053,2.674149,2.944439,3.238678,3.020425,4.119037,4.454347
2,4.171306,4.142076,3.673766,3.821369,4.857225,4.825644,0.427227,1.937782,2.968704,0.303309,0.877134,0.342170,3.250865,3.236061,0.361861,0.322325,0.0,0.010940,0.0,0.0,0.0,1.609438,0.718490,0.0,0.694812,0.0,3.401197,3.191847,0.317484,3.012262,3.378725,0.503197,3.355735,3.672072,0.422426,2.793208,3.496508,3.564827,3.232121,2.751535,2.961831,3.120895,3.106080,4.060443,4.532599
3,3.916015,4.028917,3.988984,3.958907,4.599152,4.711330,0.363253,1.876407,2.557227,0.658556,0.273837,0.288182,2.994481,3.030134,0.222343,0.202941,0.0,0.001000,0.0,0.0,0.0,1.386294,0.621651,0.0,0.553310,0.0,3.218876,3.737670,0.192272,2.833213,3.178054,0.377066,3.555348,3.806662,0.439495,3.258097,3.258097,3.637586,2.944439,2.944439,2.397895,2.639057,2.772589,3.931826,4.672829
4,4.099332,4.216562,3.781914,3.708682,4.784153,4.900820,0.362210,1.836573,2.631889,0.617615,0.213093,0.288182,3.095170,3.133318,0.288557,0.275736,0.0,0.006479,0.0,0.0,0.0,1.504077,0.679048,0.0,0.687632,0.0,3.295837,3.569533,0.241376,3.020425,3.401197,0.455524,3.637586,3.850148,0.499711,3.044522,3.384390,3.597312,2.995732,2.862201,2.602690,2.944439,2.862201,4.119037,4.454347
10261,3.966038,4.029361,3.940124,3.958429,4.649426,4.712005,0.427716,1.892735,2.816905,0.399531,0.628209,0.261402,3.132402,3.148990,0.287151,0.259861,0.0,0.010940,0.0,0.0,0.0,1.531476,0.634988,0.0,0.592636,0.0,3.233764,3.465736,0.237737,3.050457,3.446011,0.481268,3.405355,3.647406,0.485326,2.840539,3.167583,3.291196,3.107944,2.764746,2.583998,3.073850,3.032546,3.931826,4.672829
10262,3.947390,4.022570,3.958907,3.965669,4.630621,4.705116,0.421193,1.870263,2.794568,0.414608,0.640215,0.277632,3.165841,3.185893,0.281664,0.254814,0.0,0.010060,0.0,0.0,0.0,1.491655,0.632217,0.0,0.592098,0.0,3.240855,3.496508,0.235511,3.017711,3.462258,0.459673,3.397487,3.628776,0.493087,2.902642,3.214421,3.371120,3.096080,2.737249,2.598566,3.096080,3.033884,3.920873,4.683160
10263,3.986759,4.048824,3.918403,3.937106,4.670396,4.731803,0.428465,1.900016,2.830858,0.417591,0.642643,0.280960,3.129489,3.146735,0.286156,0.256888,0.0,0.009950,0.0,0.0,0.0,1.526056,0.644377,0.0,0.620792,0.0,3.280911,3.529297,0.240905,3.015535,3.481240,0.452540,3.380995,3.624341,0.482325,2.933857,3.222868,3.397858,3.135494,2.766319,2.624669,3.054001,3.039749,3.951244,4.653960
10264,1.791759,2.433613,4.587006,4.576771,2.397895,3.072693,0.244514,1.726332,1.335001,0.346423,0.586119,0.102557,2.956420,2.985682,0.000000,0.010940,0.0,0.014889,0.0,0.0,0.0,1.098612,0.172271,0.0,0.683097,0.0,2.079442,3.610918,0.016857,2.197225,3.044522,0.249980,3.555348,3.761200,0.514803,3.044522,1.386294,2.397895,1.609438,2.639057,2.708050,2.890372,3.091042,2.197225,5.252273
10265,3.527830,3.642836,4.250636,4.254193,4.206184,4.320151,0.322808,1.874874,2.332144,0.372598,0.606772,0.168054,2.769522,2.788093,0.137586,0.126192,0.0,0.011929,0.0,0.0,0.0,1.252763,0.455524,0.0,0.650761,0.0,2.944439,3.737670,0.119115,2.740840,3.465736,0.326422,3.449988,3.650658,0.519287,3.044522,2.442347,2.917771,2.639057,2.890372,2.803360,2.639057,3.068053,3.526361,4.948760

In [53]:
list_stats_ah_diff_dsmi_cma

['E_OFF_RATING_ah_diff_cma',
 'OFF_RATING_ah_diff_cma',
 'E_DEF_RATING_ah_diff_cma',
 'DEF_RATING_ah_diff_cma',
 'E_NET_RATING_ah_diff_cma',
 'NET_RATING_ah_diff_cma',
 'AST_PCT_ah_diff_cma',
 'AST_TOV_ah_diff_cma',
 'AST_RATIO_ah_diff_cma',
 'OREB_PCT_ah_diff_cma',
 'DREB_PCT_ah_diff_cma',
 'REB_PCT_ah_diff_cma',
 'E_TM_TOV_PCT_ah_diff_cma',
 'TM_TOV_PCT_ah_diff_cma',
 'EFG_PCT_ah_diff_cma',
 'TS_PCT_ah_diff_cma',
 'USG_PCT_ah_diff_cma',
 'E_USG_PCT_ah_diff_cma',
 'E_PACE_ah_diff_cma',
 'PACE_ah_diff_cma',
 'PACE_PER40_ah_diff_cma',
 'POSS_ah_diff_cma',
 'PIE_ah_diff_cma',
 'duration_minutes_ah_diff_cma',
 'w_pct_ah_diff_cma',
 'min_ah_diff_cma',
 'fgm_ah_diff_cma',
 'fga_ah_diff_cma',
 'fg_pct_ah_diff_cma',
 'fg3m_ah_diff_cma',
 'fg3a_ah_diff_cma',
 'fg3_pct_ah_diff_cma',
 'ftm_ah_diff_cma',
 'fta_ah_diff_cma',
 'ft_pct_ah_diff_cma',
 'oreb_ah_diff_cma',
 'dreb_ah_diff_cma',
 'reb_ah_diff_cma',
 'ast_ah_diff_cma',
 'stl_ah_diff_cma',
 'blk_ah_diff_cma',
 'tov_ah_diff_cma',
 'pf_ah_diff_cma',
 'pts_ah_diff_cma',
 'spread_ah_diff_cma']

In [54]:
list_stats_ah_diff_dsmi_cma_log = [k + '_log' for k in list_stats_ah_diff_dsmi_cma]
list_stats_ah_diff_dsmi_cma_log

['E_OFF_RATING_ah_diff_cma_log',
 'OFF_RATING_ah_diff_cma_log',
 'E_DEF_RATING_ah_diff_cma_log',
 'DEF_RATING_ah_diff_cma_log',
 'E_NET_RATING_ah_diff_cma_log',
 'NET_RATING_ah_diff_cma_log',
 'AST_PCT_ah_diff_cma_log',
 'AST_TOV_ah_diff_cma_log',
 'AST_RATIO_ah_diff_cma_log',
 'OREB_PCT_ah_diff_cma_log',
 'DREB_PCT_ah_diff_cma_log',
 'REB_PCT_ah_diff_cma_log',
 'E_TM_TOV_PCT_ah_diff_cma_log',
 'TM_TOV_PCT_ah_diff_cma_log',
 'EFG_PCT_ah_diff_cma_log',
 'TS_PCT_ah_diff_cma_log',
 'USG_PCT_ah_diff_cma_log',
 'E_USG_PCT_ah_diff_cma_log',
 'E_PACE_ah_diff_cma_log',
 'PACE_ah_diff_cma_log',
 'PACE_PER40_ah_diff_cma_log',
 'POSS_ah_diff_cma_log',
 'PIE_ah_diff_cma_log',
 'duration_minutes_ah_diff_cma_log',
 'w_pct_ah_diff_cma_log',
 'min_ah_diff_cma_log',
 'fgm_ah_diff_cma_log',
 'fga_ah_diff_cma_log',
 'fg_pct_ah_diff_cma_log',
 'fg3m_ah_diff_cma_log',
 'fg3a_ah_diff_cma_log',
 'fg3_pct_ah_diff_cma_log',
 'ftm_ah_diff_cma_log',
 'fta_ah_diff_cma_log',
 'ft_pct_ah_diff_cma_log',
 'oreb_ah_diff_cma_log',
 'dreb_ah_diff_cma_log',
 'reb_ah_diff_cma_log',
 'ast_ah_diff_cma_log',
 'stl_ah_diff_cma_log',
 'blk_ah_diff_cma_log',
 'tov_ah_diff_cma_log',
 'pf_ah_diff_cma_log',
 'pts_ah_diff_cma_log',
 'spread_ah_diff_cma_log']

In [55]:
dict_stats_ah_diff_dsmi_cma_log = dict(zip(list_stats_ah_diff_dsmi_cma, list_stats_ah_diff_dsmi_cma_log))
dict_stats_ah_diff_dsmi_cma_log

{'E_OFF_RATING_ah_diff_cma': 'E_OFF_RATING_ah_diff_cma_log',
 'OFF_RATING_ah_diff_cma': 'OFF_RATING_ah_diff_cma_log',
 'E_DEF_RATING_ah_diff_cma': 'E_DEF_RATING_ah_diff_cma_log',
 'DEF_RATING_ah_diff_cma': 'DEF_RATING_ah_diff_cma_log',
 'E_NET_RATING_ah_diff_cma': 'E_NET_RATING_ah_diff_cma_log',
 'NET_RATING_ah_diff_cma': 'NET_RATING_ah_diff_cma_log',
 'AST_PCT_ah_diff_cma': 'AST_PCT_ah_diff_cma_log',
 'AST_TOV_ah_diff_cma': 'AST_TOV_ah_diff_cma_log',
 'AST_RATIO_ah_diff_cma': 'AST_RATIO_ah_diff_cma_log',
 'OREB_PCT_ah_diff_cma': 'OREB_PCT_ah_diff_cma_log',
 'DREB_PCT_ah_diff_cma': 'DREB_PCT_ah_diff_cma_log',
 'REB_PCT_ah_diff_cma': 'REB_PCT_ah_diff_cma_log',
 'E_TM_TOV_PCT_ah_diff_cma': 'E_TM_TOV_PCT_ah_diff_cma_log',
 'TM_TOV_PCT_ah_diff_cma': 'TM_TOV_PCT_ah_diff_cma_log',
 'EFG_PCT_ah_diff_cma': 'EFG_PCT_ah_diff_cma_log',
 'TS_PCT_ah_diff_cma': 'TS_PCT_ah_diff_cma_log',
 'USG_PCT_ah_diff_cma': 'USG_PCT_ah_diff_cma_log',
 'E_USG_PCT_ah_diff_cma': 'E_USG_PCT_ah_diff_cma_log',
 'E_PACE_ah_diff_cma': 'E_PACE_ah_diff_cma_log',
 'PACE_ah_diff_cma': 'PACE_ah_diff_cma_log',
 'PACE_PER40_ah_diff_cma': 'PACE_PER40_ah_diff_cma_log',
 'POSS_ah_diff_cma': 'POSS_ah_diff_cma_log',
 'PIE_ah_diff_cma': 'PIE_ah_diff_cma_log',
 'duration_minutes_ah_diff_cma': 'duration_minutes_ah_diff_cma_log',
 'w_pct_ah_diff_cma': 'w_pct_ah_diff_cma_log',
 'min_ah_diff_cma': 'min_ah_diff_cma_log',
 'fgm_ah_diff_cma': 'fgm_ah_diff_cma_log',
 'fga_ah_diff_cma': 'fga_ah_diff_cma_log',
 'fg_pct_ah_diff_cma': 'fg_pct_ah_diff_cma_log',
 'fg3m_ah_diff_cma': 'fg3m_ah_diff_cma_log',
 'fg3a_ah_diff_cma': 'fg3a_ah_diff_cma_log',
 'fg3_pct_ah_diff_cma': 'fg3_pct_ah_diff_cma_log',
 'ftm_ah_diff_cma': 'ftm_ah_diff_cma_log',
 'fta_ah_diff_cma': 'fta_ah_diff_cma_log',
 'ft_pct_ah_diff_cma': 'ft_pct_ah_diff_cma_log',
 'oreb_ah_diff_cma': 'oreb_ah_diff_cma_log',
 'dreb_ah_diff_cma': 'dreb_ah_diff_cma_log',
 'reb_ah_diff_cma': 'reb_ah_diff_cma_log',
 'ast_ah_diff_cma': 'ast_ah_diff_cma_log',
 'stl_ah_diff_cma': 'stl_ah_diff_cma_log',
 'blk_ah_diff_cma': 'blk_ah_diff_cma_log',
 'tov_ah_diff_cma': 'tov_ah_diff_cma_log',
 'pf_ah_diff_cma': 'pf_ah_diff_cma_log',
 'pts_ah_diff_cma': 'pts_ah_diff_cma_log',
 'spread_ah_diff_cma': 'spread_ah_diff_cma_log'}

In [56]:
df_stats_ah_diff_cma_log.rename(columns=dict_stats_ah_diff_dsmi_cma_log, inplace=True)

In [57]:
p(df_stats_ah_diff_cma_log)

(10266, 45)

,E_OFF_RATING_ah_diff_cma_log,OFF_RATING_ah_diff_cma_log,E_DEF_RATING_ah_diff_cma_log,DEF_RATING_ah_diff_cma_log,E_NET_RATING_ah_diff_cma_log,NET_RATING_ah_diff_cma_log,AST_PCT_ah_diff_cma_log,AST_TOV_ah_diff_cma_log,AST_RATIO_ah_diff_cma_log,OREB_PCT_ah_diff_cma_log,DREB_PCT_ah_diff_cma_log,REB_PCT_ah_diff_cma_log,E_TM_TOV_PCT_ah_diff_cma_log,TM_TOV_PCT_ah_diff_cma_log,EFG_PCT_ah_diff_cma_log,TS_PCT_ah_diff_cma_log,USG_PCT_ah_diff_cma_log,E_USG_PCT_ah_diff_cma_log,E_PACE_ah_diff_cma_log,PACE_ah_diff_cma_log,PACE_PER40_ah_diff_cma_log,POSS_ah_diff_cma_log,PIE_ah_diff_cma_log,duration_minutes_ah_diff_cma_log,w_pct_ah_diff_cma_log,min_ah_diff_cma_log,fgm_ah_diff_cma_log,fga_ah_diff_cma_log,fg_pct_ah_diff_cma_log,fg3m_ah_diff_cma_log,fg3a_ah_diff_cma_log,fg3_pct_ah_diff_cma_log,ftm_ah_diff_cma_log,fta_ah_diff_cma_log,ft_pct_ah_diff_cma_log,oreb_ah_diff_cma_log,dreb_ah_diff_cma_log,reb_ah_diff_cma_log,ast_ah_diff_cma_log,stl_ah_diff_cma_log,blk_ah_diff_cma_log,tov_ah_diff_cma_log,pf_ah_diff_cma_log,pts_ah_diff_cma_log,spread_ah_diff_cma_log
0,4.468204,4.447346,2.833213,3.144152,5.155601,5.133443,0.378436,1.874874,3.072693,0.502592,0.710987,0.442118,3.356409,3.339322,0.433080,0.396761,0.0,0.007968,0.0,0.0,0.0,1.791759,0.856116,0.0,0.762207,0.0,3.688879,3.295837,0.393393,2.995732,3.401197,0.491643,3.401197,3.663562,0.456949,3.044522,3.806662,3.951244,3.401197,2.772589,3.044522,3.178054,3.091042,4.369448,3.931826
1,4.235555,4.202451,3.558201,3.731699,4.921440,4.886583,0.355925,1.776646,2.778819,0.356625,0.837897,0.368109,3.384848,3.369018,0.356275,0.335758,0.0,0.010940,0.0,0.0,0.0,1.609438,0.737164,0.0,0.666803,0.0,3.367296,3.113515,0.317362,2.944439,3.349904,0.456475,3.569533,3.806662,0.491228,3.020425,3.624341,3.784190,3.068053,2.674149,2.944439,3.238678,3.020425,4.119037,4.454347
2,4.171306,4.142076,3.673766,3.821369,4.857225,4.825644,0.427227,1.937782,2.968704,0.303309,0.877134,0.342170,3.250865,3.236061,0.361861,0.322325,0.0,0.010940,0.0,0.0,0.0,1.609438,0.718490,0.0,0.694812,0.0,3.401197,3.191847,0.317484,3.012262,3.378725,0.503197,3.355735,3.672072,0.422426,2.793208,3.496508,3.564827,3.232121,2.751535,2.961831,3.120895,3.106080,4.060443,4.532599
3,3.916015,4.028917,3.988984,3.958907,4.599152,4.711330,0.363253,1.876407,2.557227,0.658556,0.273837,0.288182,2.994481,3.030134,0.222343,0.202941,0.0,0.001000,0.0,0.0,0.0,1.386294,0.621651,0.0,0.553310,0.0,3.218876,3.737670,0.192272,2.833213,3.178054,0.377066,3.555348,3.806662,0.439495,3.258097,3.258097,3.637586,2.944439,2.944439,2.397895,2.639057,2.772589,3.931826,4.672829
4,4.099332,4.216562,3.781914,3.708682,4.784153,4.900820,0.362210,1.836573,2.631889,0.617615,0.213093,0.288182,3.095170,3.133318,0.288557,0.275736,0.0,0.006479,0.0,0.0,0.0,1.504077,0.679048,0.0,0.687632,0.0,3.295837,3.569533,0.241376,3.020425,3.401197,0.455524,3.637586,3.850148,0.499711,3.044522,3.384390,3.597312,2.995732,2.862201,2.602690,2.944439,2.862201,4.119037,4.454347
10261,3.966038,4.029361,3.940124,3.958429,4.649426,4.712005,0.427716,1.892735,2.816905,0.399531,0.628209,0.261402,3.132402,3.148990,0.287151,0.259861,0.0,0.010940,0.0,0.0,0.0,1.531476,0.634988,0.0,0.592636,0.0,3.233764,3.465736,0.237737,3.050457,3.446011,0.481268,3.405355,3.647406,0.485326,2.840539,3.167583,3.291196,3.107944,2.764746,2.583998,3.073850,3.032546,3.931826,4.672829
10262,3.947390,4.022570,3.958907,3.965669,4.630621,4.705116,0.421193,1.870263,2.794568,0.414608,0.640215,0.277632,3.165841,3.185893,0.281664,0.254814,0.0,0.010060,0.0,0.0,0.0,1.491655,0.632217,0.0,0.592098,0.0,3.240855,3.496508,0.235511,3.017711,3.462258,0.459673,3.397487,3.628776,0.493087,2.902642,3.214421,3.371120,3.096080,2.737249,2.598566,3.096080,3.033884,3.920873,4.683160
10263,3.986759,4.048824,3.918403,3.937106,4.670396,4.731803,0.428465,1.900016,2.830858,0.417591,0.642643,0.280960,3.129489,3.146735,0.286156,0.256888,0.0,0.009950,0.0,0.0,0.0,1.526056,0.644377,0.0,0.620792,0.0,3.280911,3.529297,0.240905,3.015535,3.481240,0.452540,3.380995,3.624341,0.482325,2.933857,3.222868,3.397858,3.135494,2.766319,2.624669,3.054001,3.039749,3.951244,4.653960
10264,1.791759,2.433613,4.587006,4.576771,2.397895,3.072693,0.244514,1.726332,1.335001,0.346423,0.586119,0.102557,2.956420,2.985682,0.000000,0.010940,0.0,0.014889,0.0,0.0,0.0,1.098612,0.172271,0.0,0.683097,0.0,2.079442,3.610918,0.016857,2.197225,3.044522,0.249980,3.555348,3.761200,0.514803,3.044522,1.386294,2.397895,1.609438,2.639057,2.708050,2.890372,3.091042,2.197225,5.252273
10265,3.527830,3.642836,4.250636,4.254193,4.206184,4.320151,0.322808,1.874874,2.332144,0.372598,0.606772,0.168054,2.769522,2.788093,0.137586,0.126192,0.0,0.011929,0.0,0.0,0.0,1.252763,0.455524,0.0,0.650761,0.0,2.944439,3.737670,0.119115,2.740840,3.465736,0.326422,3.449988,3.650658,0.519287,3.044522,2.442347,2.917771,2.639057,2.890372,2.803360,2.639057,3.068053,3.526361,4.948760

In [59]:
df_stats_ah_diff_cma_log = df_stats_ah_diff_cma_log.reset_index()
p(df_stats_ah_diff_cma_log)

(10266, 46)

,index,E_OFF_RATING_ah_diff_cma_log,OFF_RATING_ah_diff_cma_log,E_DEF_RATING_ah_diff_cma_log,DEF_RATING_ah_diff_cma_log,E_NET_RATING_ah_diff_cma_log,NET_RATING_ah_diff_cma_log,AST_PCT_ah_diff_cma_log,AST_TOV_ah_diff_cma_log,AST_RATIO_ah_diff_cma_log,OREB_PCT_ah_diff_cma_log,DREB_PCT_ah_diff_cma_log,REB_PCT_ah_diff_cma_log,E_TM_TOV_PCT_ah_diff_cma_log,TM_TOV_PCT_ah_diff_cma_log,EFG_PCT_ah_diff_cma_log,TS_PCT_ah_diff_cma_log,USG_PCT_ah_diff_cma_log,E_USG_PCT_ah_diff_cma_log,E_PACE_ah_diff_cma_log,PACE_ah_diff_cma_log,PACE_PER40_ah_diff_cma_log,POSS_ah_diff_cma_log,PIE_ah_diff_cma_log,duration_minutes_ah_diff_cma_log,w_pct_ah_diff_cma_log,min_ah_diff_cma_log,fgm_ah_diff_cma_log,fga_ah_diff_cma_log,fg_pct_ah_diff_cma_log,fg3m_ah_diff_cma_log,fg3a_ah_diff_cma_log,fg3_pct_ah_diff_cma_log,ftm_ah_diff_cma_log,fta_ah_diff_cma_log,ft_pct_ah_diff_cma_log,oreb_ah_diff_cma_log,dreb_ah_diff_cma_log,reb_ah_diff_cma_log,ast_ah_diff_cma_log,stl_ah_diff_cma_log,blk_ah_diff_cma_log,tov_ah_diff_cma_log,pf_ah_diff_cma_log,pts_ah_diff_cma_log,spread_ah_diff_cma_log
0,0,4.468204,4.447346,2.833213,3.144152,5.155601,5.133443,0.378436,1.874874,3.072693,0.502592,0.710987,0.442118,3.356409,3.339322,0.433080,0.396761,0.0,0.007968,0.0,0.0,0.0,1.791759,0.856116,0.0,0.762207,0.0,3.688879,3.295837,0.393393,2.995732,3.401197,0.491643,3.401197,3.663562,0.456949,3.044522,3.806662,3.951244,3.401197,2.772589,3.044522,3.178054,3.091042,4.369448,3.931826
1,1,4.235555,4.202451,3.558201,3.731699,4.921440,4.886583,0.355925,1.776646,2.778819,0.356625,0.837897,0.368109,3.384848,3.369018,0.356275,0.335758,0.0,0.010940,0.0,0.0,0.0,1.609438,0.737164,0.0,0.666803,0.0,3.367296,3.113515,0.317362,2.944439,3.349904,0.456475,3.569533,3.806662,0.491228,3.020425,3.624341,3.784190,3.068053,2.674149,2.944439,3.238678,3.020425,4.119037,4.454347
2,2,4.171306,4.142076,3.673766,3.821369,4.857225,4.825644,0.427227,1.937782,2.968704,0.303309,0.877134,0.342170,3.250865,3.236061,0.361861,0.322325,0.0,0.010940,0.0,0.0,0.0,1.609438,0.718490,0.0,0.694812,0.0,3.401197,3.191847,0.317484,3.012262,3.378725,0.503197,3.355735,3.672072,0.422426,2.793208,3.496508,3.564827,3.232121,2.751535,2.961831,3.120895,3.106080,4.060443,4.532599
3,3,3.916015,4.028917,3.988984,3.958907,4.599152,4.711330,0.363253,1.876407,2.557227,0.658556,0.273837,0.288182,2.994481,3.030134,0.222343,0.202941,0.0,0.001000,0.0,0.0,0.0,1.386294,0.621651,0.0,0.553310,0.0,3.218876,3.737670,0.192272,2.833213,3.178054,0.377066,3.555348,3.806662,0.439495,3.258097,3.258097,3.637586,2.944439,2.944439,2.397895,2.639057,2.772589,3.931826,4.672829
4,4,4.099332,4.216562,3.781914,3.708682,4.784153,4.900820,0.362210,1.836573,2.631889,0.617615,0.213093,0.288182,3.095170,3.133318,0.288557,0.275736,0.0,0.006479,0.0,0.0,0.0,1.504077,0.679048,0.0,0.687632,0.0,3.295837,3.569533,0.241376,3.020425,3.401197,0.455524,3.637586,3.850148,0.499711,3.044522,3.384390,3.597312,2.995732,2.862201,2.602690,2.944439,2.862201,4.119037,4.454347
10261,10261,3.966038,4.029361,3.940124,3.958429,4.649426,4.712005,0.427716,1.892735,2.816905,0.399531,0.628209,0.261402,3.132402,3.148990,0.287151,0.259861,0.0,0.010940,0.0,0.0,0.0,1.531476,0.634988,0.0,0.592636,0.0,3.233764,3.465736,0.237737,3.050457,3.446011,0.481268,3.405355,3.647406,0.485326,2.840539,3.167583,3.291196,3.107944,2.764746,2.583998,3.073850,3.032546,3.931826,4.672829
10262,10262,3.947390,4.022570,3.958907,3.965669,4.630621,4.705116,0.421193,1.870263,2.794568,0.414608,0.640215,0.277632,3.165841,3.185893,0.281664,0.254814,0.0,0.010060,0.0,0.0,0.0,1.491655,0.632217,0.0,0.592098,0.0,3.240855,3.496508,0.235511,3.017711,3.462258,0.459673,3.397487,3.628776,0.493087,2.902642,3.214421,3.371120,3.096080,2.737249,2.598566,3.096080,3.033884,3.920873,4.683160
10263,10263,3.986759,4.048824,3.918403,3.937106,4.670396,4.731803,0.428465,1.900016,2.830858,0.417591,0.642643,0.280960,3.129489,3.146735,0.286156,0.256888,0.0,0.009950,0.0,0.0,0.0,1.526056,0.644377,0.0,0.620792,0.0,3.280911,3.529297,0.240905,3.015535,3.481240,0.452540,3.380995,3.624341,0.482325,2.933857,3.222868,3.397858,3.135494,2.766319,2.624669,3.054001,3.039749,3.951244,4.653960
10264,10264,1.791759,2.433613,4.587006,4.576771,2.397895,3.072693,0.244514,1.726332,1.335001,0.346423,0.586119,0.102557,2.956420,2.985682,0.000000,0.010940,0.0,0.014889,0.0,0.0,0.0,1.098612,0.172271,0.0,0.683097,0.0,2.079442,3.610918,0.016857,2.197225,3.044522,0.249980,3.555348,3.761200,0.514803,3.044522,1.386294,2.397895,1.609438,2.639057,2.708050,2.890372,3.091042,2.197225,5.252273
10265,10265,3.527830,3.642836,4.250636,4.254193,4.206184,4.320151,0.322808,1.874874,2.332144,0.372598,0.606772,0.168054,2.769522,2.788093,0.137586,0.126192,0.0,0.011929,0.0,0.0,0.0,1.252763,0.455524,0.0,0.650761,0.0,2.944439,3.737670,0.119115,2.740840,3.465736,0.326422,3.449988,3.650658,0.519287,3.044522,2.442347,2.917771,2.639057,2.890372,2.803360,2.639057,3.068053,3.526361,4.948760

In [63]:
df_and_df_stats_ah_diff_cma_median_cmalog = pd.merge(df_and_df_stats_ah_diff_cma_median, df_stats_ah_diff_cma_log, on='index', how='inner')

In [64]:
p(df_and_df_stats_ah_diff_cma_median_cmalog)

(10266, 291)

,index,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away,E_OFF_RATING_ah_diff,OFF_RATING_ah_diff,E_DEF_RATING_ah_diff,DEF_RATING_ah_diff,E_NET_RATING_ah_diff,NET_RATING_ah_diff,AST_PCT_ah_diff,AST_TOV_ah_diff,AST_RATIO_ah_diff,OREB_PCT_ah_diff,DREB_PCT_ah_diff,REB_PCT_ah_diff,E_TM_TOV_PCT_ah_diff,TM_TOV_PCT_ah_diff,EFG_PCT_ah_diff,TS_PCT_ah_diff,USG_PCT_ah_diff,E_USG_PCT_ah_diff,E_PACE_ah_diff,PACE_ah_diff,PACE_PER40_ah_diff,POSS_ah_diff,PIE_ah_diff,duration_minutes_ah_diff,w_pct_ah_diff,min_ah_diff,fgm_ah_diff,fga_ah_diff,fg_pct_ah_diff,fg3m_ah_diff,fg3a_ah_diff,fg3_pct_ah_diff,ftm_ah_diff,fta_ah_diff,ft_pct_ah_diff,oreb_ah_diff,dreb_ah_diff,reb_ah_diff,ast_ah_diff,stl_ah_diff,blk_ah_diff,tov_ah_diff,pf_ah_diff,pts_ah_diff,spread_ah_diff,E_OFF_RATING_ah_diff_cma,OFF_RATING_ah_diff_cma,E_DEF_RATING_ah_diff_cma,DEF_RATING_ah_diff_cma,E_NET_RATING_ah_diff_cma,NET_RATING_ah_diff_cma,AST_PCT_ah_diff_cma,AST_TOV_ah_diff_cma,AST_RATIO_ah_diff_cma,OREB_PCT_ah_diff_cma,DREB_PCT_ah_diff_cma,REB_PCT_ah_diff_cma,E_TM_TOV_PCT_ah_diff_cma,TM_TOV_PCT_ah_diff_cma,EFG_PCT_ah_diff_cma,TS_PCT_ah_diff_cma,USG_PCT_ah_diff_cma,E_USG_PCT_ah_diff_cma,E_PACE_ah_diff_cma,PACE_ah_diff_cma,PACE_PER40_ah_diff_cma,POSS_ah_diff_cma,PIE_ah_diff_cma,duration_minutes_ah_diff_cma,w_pct_ah_diff_cma,min_ah_diff_cma,fgm_ah_diff_cma,fga_ah_diff_cma,fg_pct_ah_diff_cma,fg3m_ah_diff_cma,fg3a_ah_diff_cma,fg3_pct_ah_diff_cma,ftm_ah_diff_cma,fta_ah_diff_cma,ft_pct_ah_diff_cma,oreb_ah_diff_cma,dreb_ah_diff_cma,reb_ah_diff_cma,ast_ah_diff_cma,stl_ah_diff_cma,blk_ah_diff_cma,tov_ah_diff_cma,pf_ah_diff_cma,pts_ah_diff_cma,spread_ah_diff_cma,E_OFF_RATING_ah_diff_median,OFF_RATING_ah_diff_median,E_DEF_RATING_ah_diff_median,DEF_RATING_ah_diff_median,E_NET_RATING_ah_diff_median,NET_RATING_ah_diff_median,AST_PCT_ah_diff_median,AST_TOV_ah_diff_median,AST_RATIO_ah_diff_median,OREB_PCT_ah_diff_median,DREB_PCT_ah_diff_median,REB_PCT_ah_diff_median,E_TM_TOV_PCT_ah_diff_median,TM_TOV_PCT_ah_diff_median,EFG_PCT_ah_diff_median,TS_PCT_ah_diff_median,USG_PCT_ah_diff_median,E_USG_PCT_ah_diff_median,E_PACE_ah_diff_median,PACE_ah_diff_median,PACE_PER40_ah_diff_median,POSS_ah_diff_median,PIE_ah_diff_median,duration_minutes_ah_diff_median,w_pct_ah_diff_median,min_ah_diff_median,fgm_ah_diff_median,fga_ah_diff_median,fg_pct_ah_diff_median,fg3m_ah_diff_median,fg3a_ah_diff_median,fg3_pct_ah_diff_median,ftm_ah_diff_median,fta_ah_diff_median,ft_pct_ah_diff_median,oreb_ah_diff_median,dreb_ah_diff_median,reb_ah_diff_median,ast_ah_diff_median,stl_ah_diff_median,blk_ah_diff_median,tov_ah_diff_median,pf_ah_diff_median,pts_ah_diff_median,spread_ah_diff_median,E_OFF_RATING_ah_diff_cma_log,OFF_RATING_ah_diff_cma_log,E_DEF_RATING_ah_diff_cma_log,DEF_RATING_ah_diff_cma_log,E_NET_RATING_ah_diff_cma_log,NET_RATING_ah_diff_cma_log,AST_PCT_ah_diff_cma_log,AST_TOV_ah_diff_cma_log,AST_RATIO_ah_diff_cma_log,OREB_PCT_ah_diff_cma_log,DREB_PCT_ah_diff_cma_log,REB_PCT_ah_diff_cma_log,E_TM_TOV_PCT_ah_diff_cma_log,TM_TOV_PCT_ah_diff_cma_log,EFG_PCT_ah_diff_cma_log,TS_PCT_ah_diff_cma_log,USG_PCT_ah_diff_cma_log,E_USG_PCT_ah_diff_cma_log,E_PACE_ah_diff_cma_log,PACE_ah_diff_cma_log,PACE_PER40_ah_diff_cma_log,POSS_ah_diff_cma_log,PIE_ah_diff_cma_log,duration_minutes_ah_diff_cma_log,w_pct_ah_diff_cma_log,min_ah_diff_cma_log,fgm_ah_diff_cma_log,fga_ah_diff_cma_log,fg_pct_ah_diff_cma_log,fg3m_ah_diff_cma_log,fg3a_ah_diff_cma_log,fg3_pct_ah_diff_cma_log,ftm_ah_diff_cma_log,fta_ah_diff_cma_log,ft_pct_ah_diff_cma_log,oreb_ah_diff_cma_log,dreb_ah_diff_cma_log,reb_ah_diff_cma_log,ast_ah_diff_cma_log,stl_ah_diff_cma_log,blk_ah_diff_cma_log,tov_ah_diff_cma_log,pf_ah_diff_cma_log,pts_ah_diff_cma_log,spread_ah_diff_cma_log
0,0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8,-7.8,-7.8,7.8,7.8,-15.4,-15.4,-0.225,-0.37,-7.2,-0.018,-0.018,-0.056,-3.058,-3.0,-0.103,-0.079,0.0,0.004,0.0,0.0,0.0,-1,-0.198,0.0,-1.000,0,-5,5,-0.099,0,4,-0.100,2,0,0.080000,3,-6,-3,-10,4,2,-1,2,-8,16,-7.800000,-7.800000,7.800000,7.800000,-15.400000,-15.400000,-0.225000,-0.370000,-7.200000,-0.018000,-0.018000,-0.056000,-3.058000,-3.000000,-0.103000,-0.079000,0.0,0.004000,0.0,0.0,0.0,-1.0,-0.198000,0.0,-1.000000,0.0,-5.000000,5.000000,-0.099000,0.000000,4.000000,-0.100000,2.000000,0.000000,0.080000,3.000000,-6.000000,-3.000000,-10.000000,4.000000,2.000000,-1.000000,2.000000,-8.000000,16.000000,-7.80,-7.80,7.80,7.80,-15.4,-15.4,-0.2250,-0.370,-7.2,-0.0180,-0.0180,-0.056,-3.0580,-3.00,-0.1030,-0.079,0.0,0.0040,0.0,0.0,0.0,-1.0,-0.198,0.0,-1.0000,0.0,-5.0,5.0,-0.099,0.0,4.0,-0.1000,2.0,0.0,0.080000,3.0,-6.0,-3.0,-10.0,4.0,2.0,-1.0,2.0,-8.0,16.0,4.468204,4.447346,2.833213,3.144152,5.155601,5.133443,0.378436,1.874874,3.072693,0.502592,0.710987,0.442118,3.356409,3.339322,0.433080,0.396761,0.0,0.007968,0.0,0.0,0.0,1.791759,0.856116,0.0,0.762207,0.0,3.688879,3.295837,0.393393,2.995732,3.401197,0.491643,3.401197,3.663562,0.456949,3.044522,3.806662,3.951244,3.401197,2.772589,3.044522,3.178054,3.091042,4.369448,3.931826
1,1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14,-10.8,-15.6,10.8,15.6,-21.6,-31.2,-0.304,-1.28,-8.3,-0.246,-0.246,-0.218,4.893,4.4,0.031,0.036,0.0,0.004,0.0,0.0,0.0,0,-0.250,0.0,-1.000,0,-7,-19,0.024,-1,-1,-0.026,1,1,0.020833,-11,-7,-18,-16,-8,2,7,-3,-14,28,-10.800000,-15.600000,10.800000,15.600000,-21.600000,-31.200000,-0.304000,-1.280000,-8.300000,-0.246000,-0.246000,-0.218000,4.893000,4.400000,0.031000,0.036000,0.0,0.004000,0.0,0.0,0.0,0.0,-0.250000,0.0,-1.000000,0.0,-7.000000,-19.000000,0.024000,-1.000000,-1.000000,-0.026000,1.000000,1.000000,0.020833,-11.000000,-7.000000,-18.000000,-16.000000,-8.000000,2.000000,7.000000,-3.000000,-14.000000,28.000000,-10.80,-15.60,10.80,15.60,-21.6,-31.2,-0.3040,-1.280,-8.3,-0.2460,-0.2460,-0.218,4.8930,4.40,0.0310,0.036,0.0,0.0040,0.0,0.0,0.0,0.0,-0.250,0.0,-1.0000,0.0,-7.0,-19.0,0.024,-1.0,-1.0,-0.0260,1.0,1.0,0.020833,-11.0,-7.0,-18.0,-16.0,-8.0,2.0,7.0,-3.0,-14.0,28.0,4.235555,4.202451,3.558201,3.731699,4.921440,4.886583,0.355925,1.776646,2.778819,0.356625,0.837897,0.368109,3.384848,3.369018,0.356275,0.335758,0.0,0.010940,0.0,0.0,0.0,1.609438,0.737164,0.0,0.666803,0.0,3.367296,3.113515,0.317362,2.944439,3.349904,0.456475,3.569533,3.806662,0.491228,3.020425,3.624341,3.784190,3.068053,2.674149,2.944439,3.238678,3.020425,4.119037,4.454347
2,2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2,-3.7,-0.9,3.7,0.9,-7.6,-1.8,0.133,-0.56,1.8,0.091,0.091,0.108,8.100,8.9,-0.002,0.015,0.0,-0.002,0.0,0.0,0.0,-1,0.014,0.0,-1.000,0,-2,-5,0.001,-1,-1,-0.029,3,0,0.107143,2,7,9,4,-5,3,8,1,-2,4,-3.700000,-0.900000,3.700000,0.900000,-7.600000,-1.800000,0.133000,-0.560000,1.800000,0.091000,0.091000,0.108000,8.100000,8.900000,-0.002000,0.015000,0.0,-0.002000,0.0,0.0,0.0,-1.0,0.014000,0.0,-1.000000,0.0,-2.000000,-5.000000,0.001000,-1.000000,-1.000000,-0.029000,3.000000,0.000000,0.107143,2.000000,7.000000,9.000000,4.000000,-5.000000,3.000000,8.000000,1.000000,-2.000000,4.000000,-3.70,-0.90,3.70,0.90,-7.6,-1.8,0.1330,-0.560,1.8,0.0910,0.0910,0.108,8.1000,8.90,-0.0020,0.015,0.0,-0.0020,0.0,0.0,0.0,-1.0,0.014,0.0,-1.0000,0.0,-2.0,-5.0,0.001,-1.0,-1.0,-0.0290,3.0,0.0,0.107143,2.0,7.0,9.0,4.0,-5.0,3.0,8.0,1.0,-2.0,4.0,4.171306,4.142076,3.673766,3.821369,4.857225,4.825644,0.427227,1.937782,2.968704,0.303309,0.877134,0.342170,3.250865,3.236061,0.361861,0.322325,0.0,0.010940,0.0,0.0,0.0,1.609438,0.718490,0.0,0.694812,0.0,3.401197,3.191847,0.317484,3.012262,3.378725,0.503197,3.355735,3.672072,0.422426,2.793208,3.496508,3.564827,3.232121,2.751535,2.961831,3.120895,3.106080,4.060443,4.532599
3,3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4,-2.8,-4.2,2.8,4.2,-5.4,-8.4,-0.252,-1.39,-6.5,0.041,0.041,0.040,3.361,3.1,0.025,-0.009,0.0,0.003,0.0,0.0,0.0,0,-0.150,0.0,-1.000,0,-1,-2,-0.001,4,6,0.113,-6,-1,-0.185961,2,-1,1,-9,0,2,3,1,-4,8,-2.800000,-4.200000,2.800000,4.200000,-5.400000,-8.400000,-0.252000,-1.390000,-6.500000,0.041000,0.041000,0.040000,3.361000,3.100000,0.025000,-0.009000,0.0,0.003000,0.0,0.0,0.0,0.0,-0.150000,0.0,-1.000000,0.0,-1.000000,-2.000000,-0.001000,4.000000,6.000000,0.113000,-6.000000,-1.000000,-0.185961,2.000000,-1.000000,1.000000,-9.000000,0.000000,2.000000,3.000000,1.000000,-4.000000,8.000000,-2.80,-4.20,2.80,4.20,-5.4,-8.4,-0.2520,-1.390,-6.5,0.0410,0.0410,0.040,3.3610,3.10,0.0250,-0.009,0.0,0.0030,0.0,0.0,0.0,0.0,-0.150,0.0,-1.0000,0.0,-1.0,-2.0,-0.001,4.0,6.0,0.1130,-6.0,-1.0,-0.185961,2.0,-1.0,1.0,-9.0,0.0,2.0,3.0,1.0,-4.0,8.0,3.916015,4.028917,3.988984,3.958907,4.599152,4.711330,0.363253,1.876407,2.557227,0.658556,0.273837,0.288182,2.994481,3.030134,0.222343,0.202941,0.0,0.001000,0.0,0.0,0.0,1.386294,0.621651,0.0,0.553310,0.0,3.218876,3.737670,0.192272,2.833213,3.178054,0.377066,3.555348,3.806662,0.439495,3.258097,3.258097,3.637586,2.944439,2.944439,2.397895,2.639057,2.772589,3.931826,4.672829
4,4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4,-5.7,-2.7,5.7,2.7,-11.2,-5.4,0.095,0.75,-0.9,-0.032,-0.032,-0.054,-4.026,-3.8,-0.104,-0.056,0.0,0.003,0.0,0.0,0.0,-1,-0.032,0.0,-1.000,0,-10,-5,-0.083,-4,-4,-0.150,20,26,-0.038462,1,-7,-6,-1,4,-5,-3,-10,-4,8,-5.700000,-2.700000,5.700000,2.700000,-11.200000,-5.400000,0.095000,0.750000,-0.900000,-0.032000,-0.032000,-0.054000,-4.026000,-3.800000,-0.104000,-0.056000,0.0,0.003000,0.0,0.0,0.0,-1.0,-0.032000,0.0,-1.000000,0.0,-10.000000,-5.000000,-0.083000,-4.000000,-4.000000,-0.150000,20.000000,26.000000,-0.038462,1.000000,-7.000000,-6.000000,-1.000000,4.000000,-5.000000,-3.000000,-10.000000,-4.000000,8.000000,-5.70,-2.70,5.70,2.70,-11.2,-5.4,0.0950,0.750,-0.9,-0.0320,-0.0320,-0.054,-4.0260,-3.80,-0.1040,-0.056,0.0,0.0030,0.0,0.0,0.0,-1.0,-0.032,0.0,-1.0000,0.0,-10.0,-5.0,-0.083,-4.0,-4.0,-0.1500,20.0,26.0,-0.038462,1.0,-7.0,-6.0,-1.0,4.0,-5.0,-3.0,-10.0,-4.0,8.0,4.099332,4.216562,3.781914,3.708682,4.784153,4.900820,0.362210,1.836573,2.631889,0.617615,0.213093,0.288182,3.095170,3.133318,0.288557,0.275736,0.0,0.006479,0.0,0.0,0.0,1.504077,0.679048,0.0,0.687632,0.0,3.295837,3.569533,0.241376,3.020425,3.401197,0.455524,3.637586,3.850148,0.499711,3.044522,3.384390,3.597312,2.995732,2.862201,2.602690,2.944439,2.862201,4.119037,4.454347
10261,10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9,12.4,9.9,-12.4,-9.9,24.8,19.8,0.169,0.05,6.3,-0.026,-0.026,0.020,5.772,5.5,0.149,0.125,0.0,-0.001,0.0,0.0,0.0,0,0.136,0.0,0.142,0,3,-10,0.088,9,-5,0.251,-6,-8,-0.090909,-6,4,-2,8,-4,4,4,5,9,-18,-6.810000,-6.190000,6.810000,6.190000,-13.580000,-12.360000,0.081500,-0.043000,1.820000,-0.060600,-0.060600,-0.043800,2.614000,2.760000,0.002000,-0.001100,0.0,0.000400,0.0,0.0,0.0,-0.7,-0.041000,0.0,0.173300,0.0,-2.100000,-4.700000,-0.000300,-0.300000,-3.400000,0.018100,-2.300000,-3.000000,-0.028349,-3.400000,-1.200000,-4.600000,2.300000,-1.800000,0.800000,2.300000,-0.600000,-6.800000,13.600000,-5.90,-2.70,5.90,2.70,-11.7,-5.3,0.1290,0.045,2.2,-0.0785,-0.0785,-0.094,2.9135,3.00,0.0315,0.034,0.0,-0.0005,0.0,0.0,0.0,0.0,-0.002,0.0,0.0300,0.0,1.0,-5.5,0.007,-1.0,-2.5,0.0130,-5.0,-3.5,-0.025452,-4.0,-1.5,-6.5,2.5,-2.5,2.0,3.0,0.0,-1.5,3.0,3.966038,4.029361,3.940124,3.958429,4.649426,4.712005,0.427716,1.892735,2.816905,0.399531,0.628209,0.261402,3.132402,3.148990,0.287151,0.259861,0.0,0.010940,0.0,0.0,0.0,1.531476,0.634988,0.0,0.592636,0.0,3.233764,3.465736,0.237737,3.050457,3.446011,0.481268,3.405355,3.647406,0.485326,2.840539,3.167583,3.291196,3.107944,2.764746,2.583998,3.073850,3.032546,3.931826,4.672829
10262,10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10,-8.5,-12.4,8.5,12.4,-17.0,-24.8,-0.265,-2.38,-9.5,0.226,0.226,0.176,4.020,3.8,-0.088,-0.104,0.0,0.002,0.0,0.0,0.0,2,-0.188,0.0,-1.000,0,-2,9,-0.067,-3,1,-0.091,-3,2,-0.222727,15,0,15,-13,-5,-3,4,0,-10,20,-0.366667,-3.733333,0.366667,3.733333,-0.800000,-7.466667,-0.124333,-1.060000,-5.566667,0.118333,0.118333,0.096667,1.870333,1.466667,-0.050333,-0.037333,0.0,0.001333,0.0,0.0,0.0,1.0,-0.112667,0.0,-0.297667,0.0,-4.666667,2.000000,-0.062333,2.333333,1.333333,0.060333,4.666667,6.000000,-0.009750,8.333333,-0.666667,7.666667,-7.333333,-1.666667,-3.000000,1.333333,0.666667,-2.333333,4.666667,-6.90,-8.50,6.90,8.50,-13.8,-17.0,-0.2650,-1.010,-9.5,0.1000,0.1000,0.058,2.5730,1.90,-0.0880,-0.088,0.0,0.0010,0.0,0.0,0.0,1.0,-0.188,0.0,-0.0880,0.0,-2.0,6.0,-0.067,5.0,1.0,0.1250,8.0,8.0,0.075294,9.0,0.0,5.0,-13.0,-1.0,-3.0,1.0,1.0,-7.0,14.0,3.947390,4.022570,3.958907,3.965669,4.630621,4.705116,0.421193,1.870263,2.794568,0.414608,0.640215,0.277632,3.165841,3.185893,0.281664,0.254814,0.0,0.010060,0.0,0.0,0.0,1.491655,0.632217,0.0,0.592098,0.0,3.240855,3.496508,0.235511,3.017711,3.462258,0.459673,3.397487,3.628776,0.493087,2.902642,3.214421,3.371120,3.096080,2.737249,2.598566,3.096080,3.033884,3.920873,4.683160
10263,10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19,-20.0,-23.6,20.0,23.6,-40.0,-47.2,0.080,-0.06,-3.1,0.093,0.093,0.032,-1.063,-1.5,-0.204,-0.161,0.0,-0.003,0.0,0.0,0.0,3,-0.130,0.0,-1.000,0,-10,8,-0.162,-6,-9,-0.084,7,5,0.150183,9,-8,1,-3,6,-4,-2,-10,-19,38,-5.275000,-8.700000,5.275000,8.700000,-10.600000,-17.400000,-0.073250,-0.810000,-4.950000,0.112000,0.112000,0.080500,1.137000,0.725000,-0.088750,-0.068250,0.0,0.000250,0.0,0.0,0.0,1.5,-0.117000,0.0,-0.473250,0.0,-6.000000,3.500000,-0.087250,0.250000,-1.250000,0.024250,5.250000,5.750000,0.030233,8.500000,-2.500000,6.000000,-6.250000,0.250000,-3.250000,0.500000,-2.000000,-6.500000,13.000000,-7.70,-10.45,7.70,10.45,-15.4,-20.9,-0.0925,-0.535,-6.3,0.0965,0.0965,0.057,0.7955,0.30,-0.1045,-0.096,0.0,0.0010,0.0,0.0,0.0,1.5,-0.159,0.0,-0.5440,0.0,-6.0,7.0,-0.106,1.0,0.0,0.0205,7.5,6.5,0.096738,9.0,-3.0,4.0,-8.0,0.0,-3.5,0.0,0.5,-8.5,17.0,3.986759,4.048824,3.918403,3.937106,4.670396,4.731803,0.428465,1.900016,2.830858,0.417591,0.642643,0.280960,3.129489,3.146735,0.286156,0.256888,0.0,0.009950,0.0,0.0,0.0,1.526056,0.644377,0.0,0.620792,0.0,3.280911,3.529297,0.240905,3.015535,3.481240,0.452540,3.380995,3.624341,0.482325,2.933857,3.222868,3.397858,3.135494,2.766319,2.624669,3.054001,3.039749,3.951244,4.653960

In [ ]:
# fix cma to exclude the current row

#df.groupby(['Platoon'])['Casualties'].apply(lambda x: x.rolling(2, 1).mean().shift().bfill())
df.groupby(['Platoon'])['Casualties'].apply(lambda x: x.rolling(2, 1).mean().shift().bfill())


df_stats_ah_diff_cma_log = df.groupby(['season', 'matchup'])[list_stat_ah_diff].expanding(min_periods=0).mean().reset_index()
df_stats_ah_diff_cma_log.rename(columns={'level_2':'index'}, inplace=True)
p(df_stats_ah_diff_cma_log)

In [58]:
list_stats

['E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'spread']