In [1]:

#number of days between games
    
    #groupby team_id, season,
    

    
#number of back to back games
    #window# number of difference in days between games equal to 1


#number of away games in coming window# (games#): future_away_count_game#

#number of home games in coming window# (games#): future_home_count_game#

#number of games in coming window# (day#): future_game_count_day#

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f



def feature_engineer(df_, group_by_columns_, column_features_, operators_, window_size_, shift_num_=1):
    
    '''
    example operators: 'max', 'min', 'count', 'median', 'mean'
    '''
    df_.groupby([group_by_columns_])\
           [column_features_]\
           .rolling(window_size_,1).agg([operators_])\
           .shift(shift_num_)
    
from functools import reduce

def merge_dataframe(df_list_, merge_on_list_):
    return reduce(lambda  left,right: pd.merge(left,right,on=column_names_common_list, how='outer'), data_frames)

In [3]:
df = rcp('64_city_proper_metro_area_gdp_2010_2018.csv', ['game_date'])
p(df)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0

In [4]:

#number of days between games
    
    #groupby team_id, season,
    

    
#number of back to back games
    #window# number of difference in days between games equal to 1


#number of away games in coming window# (games#): future_away_count_game#

#number of home games in coming window# (games#): future_home_count_game#

#number of games in coming window# (day#): future_game_count_day#

In [5]:

#number of days between games
    
    #groupby team_id, season,

In [6]:
#df.game_date - df.game_date.shift()

In [7]:
df.loc[:, 'game_date_diff'] = df.groupby(['team_id', 'season']).game_date.diff(periods=1)
p(df)

(20532, 73)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7,NaT
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaT
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaT
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaT
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaT
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0,3 days
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,3 days
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,3 days
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,2 days
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,2 days

In [8]:
df.value_counts('game_date_diff')

game_date_diff
2 days     11718
1 days      4390
3 days      3034
4 days       738
6 days       115
5 days       115
9 days        68
8 days        58
7 days        42
10 days       11
11 days        3
dtype: int64

In [9]:
4390 / 20532

0.21381258523280733

In [10]:
df.head(100)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.700,NaT
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.100,NaT
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.100,NaT
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.500,NaT
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.200,NaT
5,21000003,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,34.053691,-118.242766,34.053691,-118.242766,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Los Angeles,United States,1048.000,1528.270,NaT
6,21000004,Celtics,BOS,Boston,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,L,8,0,2010-10-27,BOS vs. CLE,Regular Season,2010-11,2010,42.360253,-71.058291,41.505161,-81.693445,549.471260,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.100,1 days
7,21000004,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,W,-8,1,2010-10-27,BOS vs. CLE,Regular Season,2010-11,2010,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.100,NaT
8,21000005,Pistons,DET,Detroit,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,L,3,0,2010-10-27,DET vs. NJN,Regular Season,2010-11,2010,42.331551,-83.046640,40.833989,-74.097087,473.715215,America/New_York,America/Detroit,0.0,0.0,Detroit,United States,267.731,407.500,NaT
9,21000005,Nets,NJN,East Rutherford,240:00,0 days 04:00:00,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,W,-3,1,2010-10-27,DET vs. NJN,Regular Season,2010-11,2010,40.833989,-74.097087,40.833989,-74.097087,0.000000,America/New_York,America/New_York,0.0,0.0,New York,United States,1732.000,1803.000,NaT
10,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.00,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,25.774173,-80.193620,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.700,1 days
11,21000006,76ers,PHI,Philadelphia,240:00,0 days 04:00:00,89.8,94.6,103.6,103.2,-13.7,-8.6,0.667,1.26,18.3,0.292,0.780,0.517,19.620,20.7,0.476,0.495,1.0,0.193,95.24,93.00,77.50,92,0.450,240.0,1610612755,0.000,240,36,83,0.434,7,18,0.389,8,11,0.727273,10,28,38,24,10,4,16,22,87,L,10,1,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,39.952724,-75.163526,39.952724,-75.163526,0.000000,America/New_York,America/New_York,0.0,0.0,Philadelphia,United States,444.148,746.500,NaT
12,21000007,Knicks,NYK,New York,240:00,0 days 04:00:00,99.5,100.0,88.9,93.9,10.6,6.1,0.316,0.75,9.7,0.275,0.644,0.473,16.247,16.3,0.472,0.513,1.0,0.197,101.52,98.50,82.08,98,0.522,240.0,1610612752,1.000,240,38,88,0.432,7,24,0.292,15,17,0.882353,13,36,49,12,4,10,15,23,98,W,-5,0,2010-10-27,NYK vs. TOR,Regular Season,2010-11,2010,40.712728,-74.006015,43.653482,-79.383935,342.074112,America/Toronto,America/New_York,0.0,0.0,New York,United States,1732.000,1803.000,NaT
13,21000007,Raptors,TOR,Toronto,240:00,0 days 04:00:00,88.9,93.9,99.5,100.0,-10.6,-6.1,0.556,1.67,14.6,0.356,0.725,0.527,11.477,12.1,0.399,0.445,1.0,0.199,101.52,98.50,82.08,99,0.478,240.0,1610612761,0.000,240,36,94,0.383,3,10,0.300,18,24,0.750000,12,33,45,20,6,5,11,20,93,L,5,1,2010-10-27,NYK vs. TOR,Regular Season,2010-11,2010,43.653482,-79.383935,43.653482,-79.383935,0.000000,America/Toronto,America/Toronto,0.0,0.0,Toronto,Canada,405.000,276.300,NaT
14,21000008,Hawks,ATL,Atlanta,240:00,0 days 04:00:00,119.4,120.2,102.0,105.1,17.5,15.2,0.476,1.33,15.5,0.000,0.000,0.000,15.054,15.2,0.575,0.635,1.0,0.195,100.82,99.00,82.50,99,0.619,240.0,1610612737,1.000,240,42,80,0.525,8,16,0.500,27,31,0.870968,9,35,44,20,7,9,15,20,119,W,-15,0,2010-10-27,ATL vs. MEM,Regular Season,2010-11,2010,33.748992,-84.390264,35.149022,-90.051629,336.698161,America/Chicago,America/New_York,-1.0,1.0,Atlanta,United States,397.261,494.400,NaT
15,21000008,Grizzlies,MEM,Memphis,240:00,0 days 04:00:00,102.0,105.1,119.4,120.2,-17.5,-15.2,0.325,0.93,10.5,0.000,0.000,0.000,13.725,14.1,0.488,0.536,1.0,0.200,100.82,99.00,82.50,99,0.381,240.0,1610612763,0.000,240,40,86,0.465,4,9,0.444,20,25,0.800000,9,30,39,13,7,4,14,26,104,L,15,1,2010-10-27,ATL vs. MEM,Regular Season,2010-11,2010,35.149022,-90.051629,35.149022,-90.051629,0.000000,America/Chicago,America/Chicago,0.0,0.0,Memphis,United States,76.749,65.000,NaT
16,21000009,Kings,SAC,Sacramento,240:00,0 days 04:00:00,111.8,114.7,110.1,112.6,1.6,2.1,0.641,1.92,17.4,0.309,0.680,0.486,12.419,12.7,0.482,0.554,1.0,0.199,105.00,102.50,85.42,102,0.518,240.0,1610612758,1.000,240,39,85,0.459,4,11,0.364,35,47,0.744681,14,31,45,25,8,4,13,24,117,W,-1,0,2010-10-27,MIN vs. SAC,Regular Season,2010-11,2010,38.581061,-121.493895,44.977300,-93.265469,1511.318417,America/Chicago,America/Los_Angeles,2.0,2.0,Sacramento,United States,145.479,127.400,NaT
17,21000009,Timberwolves,MIN,Minneapolis,240:00,0 days 04:00:00,110.1,112.6,111.8,114.7,-1.6,-2.1,0.512,1.69,15.9,0.320,0.691,0.514,12.343,12.6,0.516,0.561,1.0,0.199,105.00,102.50,85.42,103,0.482,240.0,1610612750,0.000,240,43,91,0.473,8,18,0.444,22,28,0.785714,11,35,46,22,5,8,13,32,116,L,1,1,2010-10-27,MIN vs. SAC,Regular Season,2010-11,2010,44.977300,-93.265469,44.977300,-93.265469,0.000000,America/Chicago,America/Chicago,0.0,0.0,Minneapolis/St. Paul,United States,263.690,211.400,NaT
18,21000010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,L,4,0,2010-10-27,MIL vs. NOH,Regular Season,2010-11,2010,43.034993,-87.922497,29.949932,-90.070116,911.837672,America/Chicago,America/Chicago,0.0,0.0,Milwaukee,United States,103.731,86.500,NaT
19,21000010,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,W,-4,1,2010-10-27,MIL vs. NOH,Regular Season,2010-11,2010,29.949932,-90.070116,29.949932,-90.070116,0.000000,America/Chicago,America/Chicago,0.0,0.0,New Orleans,United States,380.287,374.200,NaT
20,21000011,Bulls,CHI,Chicago,240:00,0 days 04:00:00,92.5,94.1,104.2,107.1,-11.7,-13.0,0.525,1.40,15.1,0.379,0.755,0.551,14.608,14.9,0.441,0.463,1.0,0.201,102.18,100.00,83.33,101,0.397,240.0,1610612741,0.000,240,40,93,0.430,2,14,0.143,13,22,0.590909,15,36,51,21,6,6,14,28,95,L,11,0,2010-10-27,CHI vs. OKC,Regular Season,2010-11,2010,41.875562,-87.624421,35.472989,-97.517054,692.323762,America/Chicago,America/Chicago,0.0,0.0,Chicago,United States,689.464,963.200,NaT
21,21000011,Thunder,OKC,Oklahoma City,240:00,0 days 04:00:00,104.2,107.1,92.5,94.1,11.7,13.0,0.531,1.42,13.3,0.245,0.621,0.449,11.802,12.1,0.436,0.537,1.0,0.201,102.18,100.00,83.33,99,0.603,240.0,1610612760,1.000,240,32,78,0.410,4,18,0.222,38,47,0.808511,9,35,44,17,11,10,12,15,106,W,-11,1,2010-10-27,CHI vs. OKC,Regular Season,2010-11,2010,35.472989,-97.517054,35.472989,-97.517054,0.000000,America/Chicago,America/Chicago,0.0,0.0,Oklahoma City,United States,181.016,70.010,NaT
22,21000012,Bobcats,CHA,Charlotte,240:00,0 days 04:00:00,89.1,91.5,108.7,106.3,-19.6,-14.8,0.759,1.05,17.4,0.000,0.000,0.000,21.748,22.3,0.432,0.515,1.0,0.197,94.74,94.50,78.75,94,0.384,240.0,1610612766,0.000,240,29,73,0.397,5,13,0.385,23,24,0.958333,8,28,36,22,8,3,20,15,86,L,15,0,2010-10-27,CHA vs. DAL,Regular Season,2010-11,2010,35.227209,-80.843083,32.776272,-96.796856,928.313585,America/Chicago,America/New_York,-1.0,1.0,Charlotte,United States,169.862,426.200,NaT
23,21000012,Mavericks,DAL,Dallas,240:00,0 days 04:00:00,108.7,106.3,89.1,91.5,19.6,14.8,0.707,1.71,22.5,0.000,0.000,0.000,18.295,17.9,0.573,0.609,1.0,0.198,94.74,94.50,78.75,95,0.616,240.0,1610612742,1.000,240,41,75,0.547,4,15,0.267,15,18,0.833333,7,34,41,29,12,5,16,18,101,W,-15,1,2010-10-27,CHA vs. DAL,Regular Season,2010-11,2010,32.776272,-96.796856,32.776272,-96.796856,0.000000,America/Chicago,America/Chicago,0.0,0.0,Dallas–Fort Worth,United States,620.600,712.700,NaT
24,21000013,Pacers,IND,Indianapolis,240:00,0 days 04:00:00,105.5,106.9,117.5,119.6,-12.0,-12.7,0.488,0.87,15.1,0.000,0.714,0.000,22.261,22.5,0.584,0.610,1.0,0.201,103.58,102.00,85.00,102,0.404,240.0,1610612754,0.000,240,41,77,0.532,8,21,0.381,19,28,0.678571,9,27,36,20,9,6,23,26,109,L,13,0,2010-10-27,IND vs. SAS,Regular Season,2010-11,2010,39.768333,-86.158350,29.424600,-98.495141,999.618500,America/Chicago,America/Indiana/Indianapolis,-1.0,1.0,Indianapolis,United States,140.762,113.606,NaT
25,21000013,Spurs,SAS,San Antonio,240:00,0 days 04:00:00,117.5,119.6,105.5,106.9,12.0,12.7,0.690,2.07,20.4,0.286,0.000,0.000,13.482,13.7,0.560,0.617,1.0,0.200,103.58,102.00,85.00,102,0.596,240.0,1610612759,1.000,240,42,83,0.506,9,20,0.450,29,36,0.805556,9,26,35,29,15,5,14,21,122,W,-13,1,2010-10-27,IND vs. SAS,Regular Season,2010-11,2010,29.424600,-98.495141,29.424600,-98.495141,0.000000,America/Chicago,America/Chicago,0.0,0.0,San Antonio,United States,133.633,102.771,NaT
26,21000014,Jazz,UTA,Salt Lake City,240:00,0 days 04:00:00,88.1,86.3,107.8,108.9,-19.7,-22.6,0.778,0.95,15.9,0.260,0.740,0.500,22.018,21.6,0.407,0.495,1.0,0.202,100.98,101.50,84.58,102,0.371,240.0,1610612762,0.000,240,27,70,0.386,3,13,0.231,31,43,0.720930,11,33,44,21,7,4,22,30,88,L,22,0,2010-10-27,DEN vs. UTA,Regular Season,2010-11,2010,40.759620,-111.886798,39.739236,-104.984862,370.632201,America/Denver,America/Denver,0.0,0.0,Salt Lake City,United States,94.306,173.836,NaT
27,21000014,Nuggets,DEN,Denver,240:00,0 days 04:00:00,107.8,108.9,88.1,86.3,19.7,22.6,0.657,1.44,16.8,0.260,0.740,0.500,15.680,15.8,0.475,0.561,1.0,0.198,100.98,101.50,84.58,101,0.629,240.0,1610612743,1.000,240,35,80,0.438,6,20,0.300,34,41,0.829268,12,34,46,23,9,2,15,31,110,W,-22,1,2010-10-27,DEN vs. UTA,Regular Season,2010-11,2010,39.739236,-104.984862,39.739236,-104.984862,0.000000,America/Denver,America/Denver,0.0,0.0,Denver,United States,214.157,368.400,NaT
28,21000015,Rockets,HOU,Houston,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,L,4,0,2010-10-27,GSW vs. HOU,Regular Season,2010-11,2010,29.758938,-95.367697,37.854666,-122.292136,1636.798262,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.200,1 days
29,21000015,Warriors,GSW,Golden State,240:00,0 days 04:00:00,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,W,-4,1,2010-10-27,GSW vs. HOU,Regular Season,2010-11,2010,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.000,NaT
30,21000016,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,107.6,108.9,94.4,97.8,13.1,11.1,0.472,1.21,13.2,0.446,0.627,0.533,15.364,15.6,0.455,0.499,1.0,0.198,92.16,90.00,75.00,90,0.551,240.0,1610612757,1.000,240,36,88,0.409,8,20,0.400,18,23,0.782609,21,30,51,17,9,6,12,23,98,W,-10,0,2010-10-27,LAC vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,34.053691,-118.242766,826.109058,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.500,1 days
31,21000016,Clippers,LAC,Los Angeles,240:00,0 days 04:00:00,94.4,97.8,107.6,108.9,-13.1,-11.1,0.594,1.27,15.1,0.373,0.554,0.467,16.094,16.7,0.437,0.477,1.0,0.200,92.16,90.00,75.00,90,0.449,240.0,1610612746,0.000,240,32,79,0.405,5,18,0.278,19,30,0.633333,14,27,41,19,8,8,15,20,88,L,10,1,2010-10-27,LAC vs. POR,Regular Season,2010-11,2010,34.053691,-118.242766,34.053691,-118.242766,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Los Angeles,United States,1048.000,1528.270,NaT
32,21000017,Wizards,WAS,Washington,240:00,0 days 04:00:00,82.0,86.5,110.8,115.5,-28.8,-29.0,0.586,1.31,14.0,0.135,0.605,0.347,12.846,13.5,0.397,0.455,1.0,0.196,101.14,96.50,80.42,96,0.291,240.0,1610612764,0.000,240,29,78,0.372,4,19,0.211,21,30,0.700000,3,22,25,17,10,3,13,25,83,L,29,0,2010-10-28,ORL vs. WAS,Regular Season,2010-11,2010,38.894992,-77.036558,28.542111,-81.379030,757.332545,America/New_York,America/New_York,0.0,0.0,"Washington, D.C.",United States,540.684,634.800,NaT
33,21000017,Magic,ORL,Orlando,240:00,0 days 04:00:00,110.8,115.5,82.0,86.5,28.8,29.0,0.465,0.95,15.1,0.395,0.865,0.653,20.776,21.6,0.610,0.615,1.0,0.198,101.14,96.50,80.42,97,0.709,240.0,1610612753,1.000,240,43,77,0.558,8,24,0.333,18,32,0.562500,11,42,53,20,5,3,21,22,112,W,-29,1,2010-10-28,ORL vs. WAS,Regular Season,2010-11,2010,28.542111,-81.379030,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947,316.200,NaT
34,21000018,Suns,PHX,Phoenix,240:00,0 days 04:00:00,112.3,115.8,96.0,97.9,16.3,17.9,0.541,1.33,15.4,0.000,0.660,0.000,15.312,15.8,0.525,0.579,1.0,0.196,97.92,95.50,79.58,95,0.592,240.0,1610612756,0.500,240,37,80,0.463,10,26,0.385,26,34,0.764706,12,32,44,20,11,4,14,25,110,W,-16,0,2010-10-28,PHX vs. UTA,Regular Season,2010-11,2010,33.448437,-112.074142,40.759620,-111.886798,505.259730,America/Denver,America/Phoenix,1.0,1.0,Phoenix,United States,255.211,607.100,2 days
35,21000018,Jazz,UTA,Salt Lake City,240:00,0 days 04:00:00,96.0,97.9,112.3,115.8,-16.3,-17.9,0.528,1.19,14.5,0.340,0.000,0.000,16.347,16.7,0.446,0.490,1.0,0.198,97.92,95.50,79.58,96,0.408,240.0,1610612762,0.000,240,36,84,0.429,3,13,0.231,19,27,0.703704,14,31,45,19,8,6,16,28,94,L,16,1,2010-10-28,PHX vs. UTA,Regular Season,2010-11,2010,40.759620,-111.886798,40.759620,-111.886798,0.000000,America/Denver,America/Denver,0.0,0.0,Salt Lake City,United States,94.306,173.836,1 days
36,21000019,Bobcats,CHA,Charlotte,240:00,0 days 04:00:00,110.0,109.8,112.4,114.3,-2.3,-4.5,0.548,1.00,13.7,0.391,0.739,0.565,18.519,18.5,0.471,0.562,1.0,0.200,92.18,91.50,76.25,92,0.478,240.0,1610612766,0.000,240,31,70,0.443,4,12,0.333,35,45,0.777778,15,30,45,17,3,7,17,21,101,L,3,1,2010-10-29,CHA vs. IND,Regular Season,2010-11,2010,35.227209,-80.843083,35.227209,-80.843083,0.000000,America/New_York,America/New_York,0.0,0.0,Charlotte,United States,169.862,426.200,2 days
37,21000019,Pacers,IND,Indianapolis,240:00,0 days 04:00:00,112.4,114.3,110.0,109.8,2.3,4.5,0.694,2.27,19.8,0.261,0.609,0.435,11.884,12.1,0.525,0.574,1.0,0.199,92.18,91.50,76.25,91,0.522,240.0,1610612754,0.500,240,36,80,0.450,12,29,0.414,20,24,0.833333,9,25,34,25,5,11,10,28,104,W,-3,0,2010-10-29,CHA vs. IND,Regular Season,2010-11,2010,39.768333,-86.158350,35.227209,-80.843083,428.014107,America/New_York,America/Indiana/Indianapolis,0.0,0.0,Indianapolis,United States,140.762,113.606,2 days
38,21000020,Nets,NJN,East Rutherford,240:00,0 days 04:00:00,103.1,107.1,93.9,100.0,9.2,7.1,0.563,0.67,14.3,0.281,0.700,0.554,26.265,27.3,0.574,0.656,1.0,0.197,104.62,99.50,82.92,99,0.602,240.0,1610612751,1.000,240,32,61,0.525,6,11,0.545,36,45,0.800000,5,38,43,18,2,4,26,30,106,W,-6,1,2010-10-29,NJN vs. SAC,Regular Season,2010-11,2010,40.833989,-74.097087,40.833989,-74.097087,0.000000,America/New_York,America/New_York,0.0,0.0,New York,United States,1732.000,1803.000,2 days
39,21000020,Kings,SAC,Sacramento,240:00,0 days 04:00:00,93.9,100.0,103.1,107.1,-9.2,-7.1,0.538,1.75,15.3,0.300,0.719,0.446,11.274,12.0,0.446,0.479,1.0,0.198,104.62,99.50,82.92,100,0.398,240.0,1610612758,0.500,240,39,93,0.419,5,20,0.250,17,26,0.653846,10,21,31,21,7,3,12,32,100,L,6,0,2010-10-29,NJN vs. SAC,Regular Season,2010-11,2010,38.581061,-121.493895,40.833989,-74.097087,2493.288458,America/New_York,America/Los_Angeles,3.0,3.0,Sacramento,United States,145.479,127.400,2 days

In [11]:
#number of back to back games
    #window# number of difference in days between games equal to 1
    
        #make column where 1 if game_date_diff == 1, otherwise 0
        
        #sum this column
        
    

#number of away games in coming window# (games#): future_away_count_game#

#number of home games in coming window# (games#): future_home_count_game#

#number of games in coming window# (day#): future_game_count_day#

In [12]:
#number of back to back games
    #window# number of difference in days between games equal to 1
    
        #make column where 1 if game_date_diff == 1, otherwise 0
        
        #sum this column

In [13]:
def get_group_by_sum(df_, group_by_columns_list_, window_size_max_min_):
    
    df_.loc[:, 'game_date_diff1'] = 0
    df_.loc[df.game_date_diff == pd.Timedelta(seconds=60*60*24), 'game_date_diff1'] = 1
    df_ = df_.reset_index()
    
    df_games_back_to_back_window10 = df.groupby(group_by_columns_list_)\
                                            ['game_date_diff1'].rolling(window_size_max_min_[0],
                                                                        window_size_max_min_[1]).sum().reset_index()
    
    
    gb_len = len(group_by_columns_list_)
    
    level_num = 'level_' + str(gb_len)
    
    games_back_to_back_window_num = 'games_back_to_back_count_game_window' + str(window_size_max_min_[0])
    
    df_games_back_to_back_window10 =  df_games_back_to_back_window10\
                                                .rename(columns = \
                                                {level_num:'index',
                                                 'game_date_diff1': games_back_to_back_window_num})
    
    merge_on_ = group_by_columns_list_ + ['index']
    
    df_ = pd.merge(df_, df_games_back_to_back_window10, on=merge_on_)
    
    return df_

In [14]:
df_games_b2b_window5 = get_group_by_sum(df, ['team_id', 'season'], [5,1])
p(df_games_b2b_window5)

(20532, 76)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window5
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7,NaT,0,0.0
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaT,0,0.0
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaT,0,0.0
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaT,0,0.0
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaT,0,0.0
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0,3 days,0,0.0
20528,20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,3 days,0,0.0
20529,20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,3 days,0,0.0
20530,20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,2 days,0,0.0
20531,20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,2 days,0,0.0

In [15]:
df_games_b2b_window12 = get_group_by_sum(df, ['team_id', 'season'], [12,1])
p(df_games_b2b_window12)

(20532, 76)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window12
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7,NaT,0,0.0
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaT,0,0.0
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaT,0,0.0
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaT,0,0.0
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaT,0,0.0
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0,3 days,0,0.0
20528,20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,3 days,0,0.0
20529,20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,3 days,0,0.0
20530,20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,2 days,0,0.0
20531,20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,2 days,0,0.0

In [16]:
df_games_b2b_window999 = get_group_by_sum(df, ['team_id', 'season'], [999,1])
p(df_games_b2b_window999)

(20532, 76)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window999
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7,NaT,0,0.0
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaT,0,0.0
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaT,0,0.0
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaT,0,0.0
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaT,0,0.0
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0,3 days,0,14.0
20528,20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,3 days,0,13.0
20529,20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,3 days,0,14.0
20530,20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,2 days,0,13.0
20531,20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,2 days,0,14.0

In [17]:
df_games_b2b_window2 = get_group_by_sum(df, ['team_id', 'season'], [2,1])
p(df_games_b2b_window2)

(20532, 76)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7,NaT,0,0.0
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaT,0,0.0
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaT,0,0.0
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaT,0,0.0
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaT,0,0.0
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0,3 days,0,0.0
20528,20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,3 days,0,0.0
20529,20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,3 days,0,0.0
20530,20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,2 days,0,0.0
20531,20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,2 days,0,0.0

In [18]:
column_names_common_list = [k for k in df_games_b2b_window2.columns if k in df_games_b2b_window5.columns]
pl(column_names_common_list)

75

['index',
 'game_id',
 'TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'duration',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'team_id',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'wl',
 'spread',
 'away_home_',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'latitude',
 'longitude',
 'game_latitude',
 'game_longitude',
 'travel_distance',
 'game_time_zone',
 'time_zone',
 'time_zone_diff',
 'time_zone_diff_abs',
 'city_proper_metro_area',
 'Country/Region',
 'city_proper_metro_area_GDP_bil',
 'city_proper_metro_area_GDP_bil1',
 'game_date_diff',
 'game_date_diff1']

In [19]:
from functools import reduce

In [20]:
data_frames = [df_games_b2b_window2, df_games_b2b_window5, df_games_b2b_window12, df_games_b2b_window999]

In [21]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=column_names_common_list,
                                            how='outer'), data_frames)

In [22]:
p(df_merged)

(20532, 79)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7,NaT,0,0.0,0.0,0.0,0.0
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaT,0,0.0,0.0,0.0,0.0
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaT,0,0.0,0.0,0.0,0.0
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaT,0,0.0,0.0,0.0,0.0
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaT,0,0.0,0.0,0.0,0.0
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0,3 days,0,0.0,0.0,0.0,14.0
20528,20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,3 days,0,0.0,0.0,0.0,13.0
20529,20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,3 days,0,0.0,0.0,0.0,14.0
20530,20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,2 days,0,0.0,0.0,0.0,13.0
20531,20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,2 days,0,0.0,0.0,0.0,14.0

In [23]:
#df.game_date.diff()

In [24]:
'''df.groupby(['team_id', 'season'])['OFF_RATING', 'DEF_RATING'].agg(['max', 'min', 'count', 'median', 'mean'])'''

"df.groupby(['team_id', 'season'])['OFF_RATING', 'DEF_RATING'].agg(['max', 'min', 'count', 'median', 'mean'])"

In [25]:
'''df.groupby(['team_id', 'season'])\
           ['OFF_RATING', 'DEF_RATING']\
           .rolling(10,1).agg(['max', 'min', 'count', 'median', 'mean'])\
           .shift(1)'''

"df.groupby(['team_id', 'season'])           ['OFF_RATING', 'DEF_RATING']           .rolling(10,1).agg(['max', 'min', 'count', 'median', 'mean'])           .shift(1)"

In [26]:
#df = df[['team_id','season', 'game_date_diff']]
#p(df)

In [27]:
#df = df.head(100)
#p(df)

In [28]:
#df['game_date_diff'].fillna(pd.Timedelta(seconds=60*60*24*22), inplace=True)

In [29]:
#df['game_date_diff'] = df['game_date_diff'].astype(int)
#p(df)

In [30]:
#df.game_date_diff = df.game_date_diff / 24 / 60 / 60 / 1000000000
#p(df)

In [31]:
#df.game_date_diff = df.game_date_diff.astype('int')
#p(df)

In [32]:
#len_wdw = 2
#all_ranges = [(i, i+len_wdw) for i in range(df['game_date_diff'].max()-len_wdw)]

In [33]:
'''def get_mask(df, rg):
    #rg is a range, e.g. (10-20)
    return (df['game_date_diff'] >= rg[0]) & (df['game_date_diff'] <= rg[1])

result = pd.concat({ rg[0] : 
                        df[get_mask(df, rg)].groupby(['team_id', 'season']).count()['game_date_diff']
                   for rg in all_ranges},
                 axis = 1).fillna(0)    '''

"def get_mask(df, rg):\n    #rg is a range, e.g. (10-20)\n    return (df['game_date_diff'] >= rg[0]) & (df['game_date_diff'] <= rg[1])\n\nresult = pd.concat({ rg[0] : \n                        df[get_mask(df, rg)].groupby(['team_id', 'season']).count()['game_date_diff']\n                   for rg in all_ranges},\n                 axis = 1).fillna(0)    "

In [34]:
#p(result)

In [35]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '65A_games_back_to_back_count_game_window2_5_12_999_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_merged.to_csv(datapath_df, index=False)

In [36]:
df_64_city_proper_metro_area_gdp_2010_2018_readback = rcp('65A_games_back_to_back_count_game_window2_5_12_999_2010_2018.csv')
p(df_64_city_proper_metro_area_gdp_2010_2018_readback)

(20532, 79)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7,NaN,0,0.0,0.0,0.0,0.0
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaN,0,0.0,0.0,0.0,0.0
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaN,0,0.0,0.0,0.0,0.0
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaN,0,0.0,0.0,0.0,0.0
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaN,0,0.0,0.0,0.0,0.0
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0,3 days,0,0.0,0.0,0.0,14.0
20528,20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,3 days,0,0.0,0.0,0.0,13.0
20529,20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,3 days,0,0.0,0.0,0.0,14.0
20530,20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1,2 days,0,0.0,0.0,0.0,13.0
20531,20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0,2 days,0,0.0,0.0,0.0,14.0