In [1]:
####################################

#per stat


#get cma5, cma12, cma999 for when team is away

#get cma5, cma12, cma999 for when team is home

###################################

In [ ]:
###########spill over############################


#days since previous game: days_rest



##################################

#days rest between games

#get cma5, cma12, cma999, cma1, cma2, cma3, cma4


#log diff??? plot to check??



######################

#time zone change

#distance traveled

In [1]:
############################

#opponent stat cma5, cma12, cma999

#opponent opponents stat cma5, cma12, cma999

In [2]:


########################

# away_home_

# get cma5, cma12, cma999

######################

#lost contribution by player injury cmax# for current game (no stats shown and not minutes > 0)

In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [4]:
df = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv', ['game_date'])
df = sr(df, 'game_date')
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4
4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [5]:
df_giti = f.wide2tall(df, ['game_id', 'team_id'], ['_away', '_home'])
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [6]:
df_giti = df_giti.sort_values(['game_id', 'game_date'])
df_giti = df_giti.reset_index(drop=True)
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [7]:
df_giti['a'] = df_giti.matchup.str.split(' vs. ').str[0].str.strip()
p(df_giti)

(20532, 60)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE

In [8]:
df_giti['b'] = df_giti.matchup.str.split(' vs. ').str[1].str.strip()
p(df_giti)

(20532, 61)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW

In [9]:
df_giti.loc[df_giti['a'] == df_giti['TEAM_ABBREVIATION'], '_a'] = 1
p(df_giti)

(20532, 62)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,NaN
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,NaN
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,NaN
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,NaN
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,NaN
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0

In [10]:
df_giti.loc[df_giti['a'] != df_giti['TEAM_ABBREVIATION'], '_a'] = 0
p(df_giti)

(20532, 62)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0

In [11]:
df_giti.loc[df_giti['b'] == df_giti['TEAM_ABBREVIATION'], '_b'] = 1
p(df_giti)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,NaN
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,NaN
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,NaN
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,NaN
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,NaN

In [12]:
df_giti.loc[df_giti['b'] != df_giti['TEAM_ABBREVIATION'], '_b'] = 0
p(df_giti)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0

In [16]:
#get 1 for win and 0 for loss: wl_01
df_giti.loc[df_giti.wl.str.contains('W'), ['wl_01']] = 1
df_giti.loc[df_giti.wl.str.contains('L'), ['wl_01']] = 0
p(df_giti)

(20532, 64)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b,wl_01
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0,1.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0,1.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0,0.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,1.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,0.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,0.0

In [36]:
df_ab = f.tall2wide2(df_giti,
             ['game_id', 'game_date', 'matchup', 'season', 'season_type',
              'season_year', 'a', 'b'], 
              '_a')
p(df_ab)

(10266, 118)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,E_OFF_RATING_a,OFF_RATING_a,E_DEF_RATING_a,DEF_RATING_a,E_NET_RATING_a,NET_RATING_a,AST_PCT_a,AST_TOV_a,AST_RATIO_a,OREB_PCT_a,DREB_PCT_a,REB_PCT_a,E_TM_TOV_PCT_a,TM_TOV_PCT_a,EFG_PCT_a,TS_PCT_a,USG_PCT_a,E_USG_PCT_a,E_PACE_a,PACE_a,PACE_PER40_a,POSS_a,PIE_a,duration_minutes_a,team_id_a,w_pct_a,min_a,fgm_a,fga_a,fg_pct_a,fg3m_a,fg3a_a,fg3_pct_a,ftm_a,fta_a,ft_pct_a,oreb_a,dreb_a,reb_a,ast_a,stl_a,blk_a,tov_a,pf_a,pts_a,wl_a,spread_a,away_home__a,game_date,matchup,season_type,season,season_year,a,b,_b_a,wl_01_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,E_OFF_RATING_b,OFF_RATING_b,E_DEF_RATING_b,DEF_RATING_b,E_NET_RATING_b,NET_RATING_b,AST_PCT_b,AST_TOV_b,AST_RATIO_b,OREB_PCT_b,DREB_PCT_b,REB_PCT_b,E_TM_TOV_PCT_b,TM_TOV_PCT_b,EFG_PCT_b,TS_PCT_b,USG_PCT_b,E_USG_PCT_b,E_PACE_b,PACE_b,PACE_PER40_b,POSS_b,PIE_b,duration_minutes_b,team_id_b,w_pct_b,min_b,fgm_b,fga_b,fg_pct_b,fg3m_b,fg3a_b,fg3_pct_b,ftm_b,fta_b,ft_pct_b,oreb_b,dreb_b,reb_b,ast_b,stl_b,blk_b,tov_b,pf_b,pts_b,wl_b,spread_b,away_home__b,_b_b,wl_01_b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,0.0,1.0
1,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,1.0,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,0.0,0.0
2,21000003,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,1.0,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,0.0,0.0
3,21000004,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,W,-8,1,2010-10-27,BOS vs. CLE,Regular Season,2010-11,2010,BOS,CLE,1.0,1.0,Celtics,BOS,Boston,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,L,8,0,0.0,0.0
4,21000005,Nets,NJN,New Jersey,240:00,0 days 04:00:00,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,W,-3,1,2010-10-27,DET vs. NJN,Regular Season,2010-11,2010,DET,NJN,1.0,1.0,Pistons,DET,Detroit,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,L,3,0,0.0,0.0
10261,41700317,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1,2018-05-28,GSW vs. HOU,Playoffs,2017-18,2017,GSW,HOU,1.0,0.0,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9,0,0.0,1.0
10262,41700401,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1,2018-05-31,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,1.0,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10,0,0.0,0.0
10263,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,1.0,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,0.0,0.0
10264,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,1.0,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,0.0,0.0
10265,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,1.0,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,0.0,0.0

In [ ]:
    
#take difference of numeric columns with the same prefix, store to stat_cma#_diff

#drop stat_cma# columns

def get_numeric_diff(df_, groupby_list_, not_difference_list_, suffix_list_):
    
    column_names_numeric_list_ = list(df_.select_dtypes('number').columns)
    
    column_names_numeric_list_cleaned_ = [k for k in column_names_numeric_list_
                                          if (not k in not_difference_list_)]
    
    column_names_first_second_list_ = [k.split(suffix_list_[0])[0]
                                       for k in column_names_numeric_list_cleaned_
                                       if k.endswith(suffix_list_[0])]
    
    column_names_first_second_list_rgl_ = [k for k in column_names_first_second_list_
                                           if not k in groupby_list_]

    column_names_first_second_list_rgl_first_ = [k + suffix_list_[0] for k in column_names_first_second_list_rgl_]
    
    column_names_first_second_list_rgl_second_ = [k + suffix_list_[1] for k in column_names_first_second_list_rgl_]
    
    column_names_first_second_list_rgl_diff_ = [k + '_diff' for k in column_names_first_second_list_rgl_]
    
    #return len(column_names_first_second_list_rgl_first_), len(column_names_first_second_list_rgl_second_), len(column_names_first_second_list_rgl_diff_)
    
    
    df_[column_names_first_second_list_rgl_diff_] = df_[column_names_first_second_list_rgl_first_].fillna(0).values - df_[column_names_first_second_list_rgl_second_].fillna(0)
    
    column_names_drop_ = column_names_first_second_list_rgl_first_ + column_names_first_second_list_rgl_second_
    
    df_.drop(columns = column_names_drop_, inplace=True)    
    
    #return df_[column_names_first_second_list_rgl_first_]
    
    #return df_[column_names_first_second_list_rgl_second_]
    
    return df_

In [66]:
def wide_get_cma_num_diff3(df_, groupby_list_, not_difference_list_, suffix_list_, window_size_max_min_):
    
    
    #get suffix category column name: suffix_cat
    alphanumeric = ''
    suffix_cat = ''
    for i in range(len(suffix_list_)):
        
        for character in suffix_list_[i]:
            if character.isalnum():
                alphanumeric += character
        
        suffix_cat = suffix_cat + alphanumeric + '_'
        alphanumeric = ''

    
    column_names_list_ = list(df_.columns)
    
    column_names_first_second_list_ = [k for k in column_names_list_
                                       if not k in not_difference_list_]
    
    column_names_first_second_list_first_ = [k for k in column_names_first_second_list_
                                            if k.endswith(suffix_list_[0])]
    
    column_names_first_second_list_first_stripped_ = [k.split(suffix_list_[0])[0]
                                                     for k in column_names_first_second_list_first_]
    
    
    df_ = f.wide2tall(df_, not_difference_list_, suffix_list_)
    

    
    column_names_number_list_ = list(df_.select_dtypes('number'))

    column_names_number_list_ = [k for k in column_names_number_list_ if not k in not_difference_list_]
    
    column_names_number_list_ = [k for k in column_names_number_list_ if not k in suffix_cat]
    
    gbl_column_names_number_list_ = groupby_list_ + [k for k in column_names_number_list_
                                                          if not k in groupby_list_] 
    
    df_numeric_gbl_ = df_[gbl_column_names_number_list_]
    
    
    df_gbl_cma_ = df_numeric_gbl_.groupby(
                                            groupby_list_).apply(lambda x:
                                            x.rolling(window_size_max_min_[0],
                                            window_size_max_min_[1]).mean().shift()
                                         )[column_names_number_list_]
    
    pre_rename_cma_drop_list_ = [k for k in column_names_number_list_ if k in groupby_list_]
    
    df_gbl_cma_.drop(columns=pre_rename_cma_drop_list_, inplace=True)
    
     
    column_names_number_list_cma_num_ = [k + '_cma' + str(window_size_max_min_[0]) for k in column_names_number_list_]
    
    column_names_number_dict_cma_num_ = dict(zip(column_names_number_list_, column_names_number_list_cma_num_))
        
    df_gbl_cma_.rename(columns=column_names_number_dict_cma_num_, inplace=True)
    
    df_gbl_cma_ = df_gbl_cma_.reset_index()
    
    level_num = len(groupby_list_)
    
    df_gbl_cma_.rename(columns={'level_' + str(level_num): 'index'}, inplace=True)

    df_ = df_.reset_index()
    
    column_names_merged_list = ['index'] + groupby_list_
    
   
    column_names_number_list_rgbl_ = [k for k in column_names_number_list_ if not k in groupby_list_]
    
    df_dropped_ = df_.drop(columns=column_names_number_list_rgbl_)
    
    
    #return column_names_merged_list
    
    #return df_gbl_cma_
    
    df_gbl_cma_merged_ = pd.merge(df_dropped_, df_gbl_cma_, on=column_names_merged_list)
    
    #return df_gbl_cma_merged_
    
    
    df_gbl_cma_merged_.drop(columns='index', inplace=True)
    
    
    df_wide_ = f.tall2wide2(df_gbl_cma_merged_, not_difference_list_, suffix_cat)

    df_wide_ = sr(df_wide_, 'game_date')
    
    
    
    #take difference of numeric columns with the same prefix, store to stat_cma#_diff
    
    return get_numeric_diff(df_wide_, groupby_list_, not_difference_list_, suffix_list_)
    
    #merge back to columns not taken a difference on

In [67]:
df_stat_cma5_diff = wide_get_cma_num_diff3(df_ab,
                       ['season', 'team_id', 'away_home_'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [5,1])
p(df_stat_cmax5_diff)
#df_stat_cmax5_diff

(10266, 74)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,away_home__a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,away_home__b,matchup_b,a_b,b_b,_b_diff,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,wl_01_cma5_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,0,BOS vs. MIA,BOS,MIA,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,1,BOS vs. MIA,BOS,MIA,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,1,PHX vs. POR,PHX,POR,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,0,PHX vs. POR,PHX,POR,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,1,HOU vs. LAL,HOU,LAL,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,0,HOU vs. LAL,HOU,LAL,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000015,2010-10-27,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,0,GSW vs. HOU,GSW,HOU,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,1,GSW vs. HOU,GSW,HOU,1.0,101.60,106.80,105.30,107.70,-3.80,-0.90,0.6580,1.190,16.70,0.3960,0.6950,0.5540,19.3870,20.40,0.4620,0.5320,1.0,0.1960,107.320,103.5,86.250,103.0,0.5070,240.0,0.0000,240.0,38.0,91.0,0.4180,8.0,20.0,0.4000,26.0,28.0,0.928571,16.0,37.0,53.0,25.0,6.0,7.0,20.0,25.0,110.0,2.0,0.0
4,21000014,2010-10-27,2010-11,Regular Season,2010,Jazz,UTA,Utah,240:00,0 days 04:00:00,1610612762,L,0,DEN vs. UTA,DEN,UTA,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612743,W,1,DEN vs. UTA,DEN,UTA,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,1,GSW vs. HOU,GSW,HOU,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,0,GSW vs. HOU,GSW,HOU,1.0,4.32,5.42,4.70,2.40,-0.42,3.02,-0.0838,-0.166,-2.38,0.0818,0.0804,0.0506,-0.9268,-0.86,0.0064,0.0036,0.0,-0.0030,-3.524,-2.8,-2.332,-2.0,-0.0174,0.0,-0.1834,0.0,-0.6,1.0,-0.0136,3.6,9.0,0.0128,0.6,2.0,-0.046923,2.2,0.8,3.0,-3.4,0.0,0.8,-2.2,1.6,3.0,-4.2,0.2
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,1,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,0,CLE vs. GSW,CLE,GSW,1.0,10.24,9.36,-10.92,-11.90,21.14,21.26,0.0746,-0.624,2.64,0.1110,0.0212,0.0516,0.8154,0.78,0.0226,0.0246,0.0,0.0012,7.808,8.5,7.086,8.6,0.1226,0.0,0.2992,0.0,7.6,13.6,0.0150,3.0,2.4,0.0644,0.2,-2.8,0.135286,6.2,3.2,9.4,7.6,6.4,1.6,2.0,1.2,18.4,-21.2,0.4
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,1,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,0,CLE vs. GSW,CLE,GSW,1.0,18.08,17.78,-9.20,-11.30,27.28,29.06,0.0602,1.068,4.00,0.0620,-0.0038,0.0204,-2.1974,-2.26,0.0636,0.0638,0.0,0.0006,3.720,4.8,4.002,4.6,0.1684,0.0,0.4992,0.0,9.4,10.4,0.0528,3.2,-0.6,0.1022,-0.2,-4.0,0.164695,2.8,0.6,3.4,8.0,6.4,1.2,-1.4,0.4,21.8,-27.8,0.6
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,0,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,1,CLE vs. GSW,CLE,GSW,1.0,-8.56,-12.50,-1.24,-0.68,-7.30,-11.78,0.0980,0.236,2.08,-0.1376,-0.0468,-0.0794,0.3858,0.02,-0.0242,-0.0280,0.0,0.0026,4.608,5.8,4.832,4.8,-0.0518,0.0,-0.0224,0.0,-1.8,1.0,-0.0280,0.8,6.0,-0.0478,-3.6,-4.8,-0.014915,-2.4,0.8,-1.6,3.0,0.6,-1.6,1.2,-0.6,-6.4,12.8,-0.4
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,0,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,1,CLE vs. GSW,CLE,GSW,1.0,-5.74,-9.30,2.10,3.24,-7.84,-12.48,0.0996,0.230,2.38,-0.1526,-0.1026,-0.1076,0.3542,0.02,-0.0070,-0.0056,0.0,0.0018,1.396,2.3,1.916,1.2,-0.0460,0.0,0.2276,0.0,-3.0,-4.4,-0.0118,0.4,3.4,-0.0312,-1.8,-3.0,0.004425,-4.0,-1.4,-5.4,2.4,-0.2,-1.6,0.4,-0.4,-7.4,14.4,-0.2

In [68]:
df_stat_cmax5_diff = wide_get_cma_num_diff3(df_ab,
                       ['season', 'team_id', 'away_home_'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [5,1])
p(df_stat_cmax5_diff)

(10266, 74)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,away_home__a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,away_home__b,matchup_b,a_b,b_b,_b_diff,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,wl_01_cma5_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,0,BOS vs. MIA,BOS,MIA,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,1,BOS vs. MIA,BOS,MIA,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,1,PHX vs. POR,PHX,POR,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,0,PHX vs. POR,PHX,POR,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,1,HOU vs. LAL,HOU,LAL,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,0,HOU vs. LAL,HOU,LAL,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000015,2010-10-27,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,0,GSW vs. HOU,GSW,HOU,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,1,GSW vs. HOU,GSW,HOU,1.0,101.60,106.80,105.30,107.70,-3.80,-0.90,0.6580,1.190,16.70,0.3960,0.6950,0.5540,19.3870,20.40,0.4620,0.5320,1.0,0.1960,107.320,103.5,86.250,103.0,0.5070,240.0,0.0000,240.0,38.0,91.0,0.4180,8.0,20.0,0.4000,26.0,28.0,0.928571,16.0,37.0,53.0,25.0,6.0,7.0,20.0,25.0,110.0,2.0,0.0
4,21000014,2010-10-27,2010-11,Regular Season,2010,Jazz,UTA,Utah,240:00,0 days 04:00:00,1610612762,L,0,DEN vs. UTA,DEN,UTA,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612743,W,1,DEN vs. UTA,DEN,UTA,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0,0.0000,0.000,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,1,GSW vs. HOU,GSW,HOU,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,0,GSW vs. HOU,GSW,HOU,1.0,4.32,5.42,4.70,2.40,-0.42,3.02,-0.0838,-0.166,-2.38,0.0818,0.0804,0.0506,-0.9268,-0.86,0.0064,0.0036,0.0,-0.0030,-3.524,-2.8,-2.332,-2.0,-0.0174,0.0,-0.1834,0.0,-0.6,1.0,-0.0136,3.6,9.0,0.0128,0.6,2.0,-0.046923,2.2,0.8,3.0,-3.4,0.0,0.8,-2.2,1.6,3.0,-4.2,0.2
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,1,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,0,CLE vs. GSW,CLE,GSW,1.0,10.24,9.36,-10.92,-11.90,21.14,21.26,0.0746,-0.624,2.64,0.1110,0.0212,0.0516,0.8154,0.78,0.0226,0.0246,0.0,0.0012,7.808,8.5,7.086,8.6,0.1226,0.0,0.2992,0.0,7.6,13.6,0.0150,3.0,2.4,0.0644,0.2,-2.8,0.135286,6.2,3.2,9.4,7.6,6.4,1.6,2.0,1.2,18.4,-21.2,0.4
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,1,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,0,CLE vs. GSW,CLE,GSW,1.0,18.08,17.78,-9.20,-11.30,27.28,29.06,0.0602,1.068,4.00,0.0620,-0.0038,0.0204,-2.1974,-2.26,0.0636,0.0638,0.0,0.0006,3.720,4.8,4.002,4.6,0.1684,0.0,0.4992,0.0,9.4,10.4,0.0528,3.2,-0.6,0.1022,-0.2,-4.0,0.164695,2.8,0.6,3.4,8.0,6.4,1.2,-1.4,0.4,21.8,-27.8,0.6
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,0,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,1,CLE vs. GSW,CLE,GSW,1.0,-8.56,-12.50,-1.24,-0.68,-7.30,-11.78,0.0980,0.236,2.08,-0.1376,-0.0468,-0.0794,0.3858,0.02,-0.0242,-0.0280,0.0,0.0026,4.608,5.8,4.832,4.8,-0.0518,0.0,-0.0224,0.0,-1.8,1.0,-0.0280,0.8,6.0,-0.0478,-3.6,-4.8,-0.014915,-2.4,0.8,-1.6,3.0,0.6,-1.6,1.2,-0.6,-6.4,12.8,-0.4
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,0,CLE vs. GSW,CLE,GSW,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,1,CLE vs. GSW,CLE,GSW,1.0,-5.74,-9.30,2.10,3.24,-7.84,-12.48,0.0996,0.230,2.38,-0.1526,-0.1026,-0.1076,0.3542,0.02,-0.0070,-0.0056,0.0,0.0018,1.396,2.3,1.916,1.2,-0.0460,0.0,0.2276,0.0,-3.0,-4.4,-0.0118,0.4,3.4,-0.0312,-1.8,-3.0,0.004425,-4.0,-1.4,-5.4,2.4,-0.2,-1.6,0.4,-0.4,-7.4,14.4,-0.2

In [ ]:
f.wide_get_cma_num_diff3(df_giti,
                       ['season', 'team_id'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [5,1])

In [ ]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '55Astat_cma5_cma12_cma999_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_temp.to_csv(datapath_df, index=False)

In [ ]:
df_stat_cma5_cma12_cma999_diff_readback = rcp('55Astat_cma5_cma12_cma999_diff_2010_2018.csv')
p(df_stat_cma5_cma12_cma999_diff_readback)