In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
df = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv', ['game_date'])
df = df.sort_values(['game_date', 'game_id'])
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,BOS vs. CLE,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010,L,W,-8,8
5,21000005,2010-10-27,Pistons,DET,Detroit,240:00,0 days 04:00:00,Nets,NJN,New Jersey,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,DET vs. NJN,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,Regular Season,2010-11,2010,L,W,-3,3
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [3]:
df_team_city_latitude_longitude = rcp('62_team_city_latitude_longitude_2010_2018.csv')
p(df_team_city_latitude_longitude)

(30, 3)

          TEAM_CITY   latitude   longitude
0       Los Angeles  34.053691 -118.242766
1       San Antonio  29.424600  -98.495141
2             Miami  25.774173  -80.193620
3      Golden State  37.854666 -122.292136
4     Oklahoma City  35.472989  -97.517054
25          Detroit  42.331551  -83.046640
26          Phoenix  33.448437 -112.074142
27       Sacramento  38.581061 -121.493895
28         Brooklyn  40.650104  -73.949582
29  East Rutherford  40.833989  -74.097087

In [4]:
df_giti = f.wide2tall(df, ['game_id', 'team_id'], ['_away', '_home'])
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [5]:
#fix #fix indiana to indianapolis

#fix utah to salt lake city

#fix new jersey to East Rutherford


df_giti.loc[df_giti.TEAM_CITY.str.contains('Indiana'), 'TEAM_CITY'] = 'Indianapolis'
df_giti.loc[df_giti.TEAM_CITY.str.contains('Utah'), 'TEAM_CITY'] = 'Salt Lake City'
df_giti.loc[df_giti.TEAM_CITY.str.contains('New Jersey'), 'TEAM_CITY'] = 'East Rutherford'
df_giti.loc[df_giti.TEAM_CITY.str.contains('Minnesota'), 'TEAM_CITY'] = 'Minneapolis'

In [6]:
df_giti = pd.merge(df_giti, df_team_city_latitude_longitude, on=['TEAM_CITY'])
p(df_giti)

(20532, 61)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620
1,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.0,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,25.774173,-80.193620
2,21000025,Heat,MIA,Miami,240:00,0 days 04:00:00,105.6,109.1,76.1,78.7,29.5,30.4,0.515,1.42,13.9,0.000,0.745,0.000,13.204,13.6,0.463,0.517,1.0,0.198,91.42,88.5,73.75,88,0.755,240.0,1610612748,0.667,240,33,81,0.407,9,18,0.500,21,27,0.777778,14,37,51,17,6,5,12,27,96,W,-26,1,2010-10-29,MIA vs. ORL,Regular Season,2010-11,2010,25.774173,-80.193620
3,21000040,Heat,MIA,Miami,240:00,0 days 04:00:00,118.9,114.8,85.6,90.7,33.3,24.1,0.806,3.63,24.4,0.200,0.600,0.453,9.416,9.1,0.575,0.616,1.0,0.202,88.04,87.0,72.50,88,0.757,240.0,1610612748,0.750,240,36,67,0.537,5,16,0.313,24,34,0.705882,5,35,40,29,10,6,8,21,101,W,-23,0,2010-10-31,MIA vs. NJN,Regular Season,2010-11,2010,25.774173,-80.193620
4,21000050,Heat,MIA,Miami,240:00,0 days 04:00:00,128.2,127.7,91.8,97.0,36.4,30.7,0.674,1.94,22.2,0.000,0.678,0.000,15.898,15.8,0.658,0.696,1.0,0.197,103.18,100.5,83.75,101,0.718,240.0,1610612748,0.800,240,46,79,0.582,12,21,0.571,25,31,0.806452,8,39,47,31,9,7,14,27,129,W,-32,1,2010-11-02,MIA vs. MIN,Regular Season,2010-11,2010,25.774173,-80.193620
20527,21701157,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,89.5,92.2,118.7,118.6,-29.2,-26.4,0.588,1.11,15.5,0.143,0.814,0.434,16.962,17.5,0.525,0.521,1.0,0.198,104.02,102.5,85.42,103,0.321,240.0,1610612751,0.321,240,34,81,0.420,17,42,0.405,10,23,0.434783,3,33,36,20,5,6,18,15,95,L,26,0,2018-04-03,BKN vs. PHI,Regular Season,2017-18,2017,40.650104,-73.949582
20528,21701178,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,118.7,120.2,108.6,112.1,10.1,8.1,0.732,1.50,22.3,0.194,0.709,0.505,19.952,20.2,0.673,0.706,1.0,0.194,101.22,99.0,82.50,99,0.556,240.0,1610612751,0.329,240,41,75,0.547,19,39,0.487,18,21,0.857143,4,37,41,30,3,12,17,21,119,W,-8,0,2018-04-05,BKN vs. MIL,Regular Season,2017-18,2017,40.650104,-73.949582
20529,21701193,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,116.1,119.2,90.4,93.2,25.7,26.0,0.783,2.40,24.4,0.188,0.846,0.530,14.040,14.4,0.630,0.640,1.0,0.195,106.54,103.5,86.25,104,0.646,240.0,1610612751,0.338,240,46,92,0.500,24,55,0.436,8,11,0.727273,5,41,46,36,11,10,13,18,124,W,-28,0,2018-04-07,BKN vs. CHI,Regular Season,2017-18,2017,40.650104,-73.949582
20530,21701205,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,113.3,112.9,101.7,105.0,11.7,7.9,0.780,1.78,23.1,0.167,0.714,0.462,17.893,17.8,0.610,0.643,1.0,0.197,101.94,100.5,83.75,101,0.561,240.0,1610612751,0.346,240,41,82,0.500,18,42,0.429,14,15,0.933333,6,32,38,32,8,10,17,15,114,W,-9,1,2018-04-09,BKN vs. CHI,Regular Season,2017-18,2017,40.650104,-73.949582
20531,21701219,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,93.2,95.1,107.2,107.8,-14.0,-12.7,0.730,1.69,19.1,0.228,0.603,0.417,15.379,15.7,0.467,0.495,1.0,0.196,103.32,102.0,85.00,102,0.459,240.0,1610612751,0.341,240,37,91,0.407,11,40,0.275,12,16,0.750000,10,34,44,27,10,6,15,12,97,L,13,0,2018-04-11,BKN vs. BOS,Regular Season,2017-18,2017,40.650104,-73.949582

In [7]:
df_giti = df_giti.sort_values(['game_date', 'game_id'])
df_giti = df_giti.reset_index(drop=True)
p(df_giti)

(20532, 61)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136

In [8]:
#get distance between TEAM_CITY coordinates and current game


    #get home teams
    
    #get coordinates of home teams
    
    #make dataframe of game_id, latitude, longitude (of home teams)

In [9]:
df_game_id_latitude_longitude = df_giti.loc[df_giti.away_home_ == 1, ['game_id', 'latitude', 'longitude']]
p(df_game_id_latitude_longitude)

(10266, 3)

        game_id   latitude   longitude
1      21000001  42.360253  -71.058291
3      21000002  45.520247 -122.674195
5      21000003  34.053691 -118.242766
7      21000004  41.505161  -81.693445
9      21000005  40.833989  -74.097087
20522  41700317  29.758938  -95.367697
20525  41700401  37.854666 -122.292136
20527  41700402  37.854666 -122.292136
20528  41700403  41.505161  -81.693445
20530  41700404  41.505161  -81.693445

In [10]:
df_game_id_latitude_longitude.rename(columns = {'latitude':'game_latitude', 'longitude':'game_longitude'},
                                     inplace=True)
p(df_game_id_latitude_longitude)

(10266, 3)

        game_id  game_latitude  game_longitude
1      21000001      42.360253      -71.058291
3      21000002      45.520247     -122.674195
5      21000003      34.053691     -118.242766
7      21000004      41.505161      -81.693445
9      21000005      40.833989      -74.097087
20522  41700317      29.758938      -95.367697
20525  41700401      37.854666     -122.292136
20527  41700402      37.854666     -122.292136
20528  41700403      41.505161      -81.693445
20530  41700404      41.505161      -81.693445

In [11]:
df_giti = pd.merge(df_giti, df_game_id_latitude_longitude, on=['game_id'])
p(df_giti)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445

In [12]:
!pip install haversine

Requirement already satisfied: haversine in /opt/anaconda3/lib/python3.8/site-packages (2.4.0)

In [13]:
import haversine as hs
from haversine import Unit

In [14]:
p(df_giti)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445

In [15]:
df_giti = df_giti.reset_index(drop=True)
p(df_giti)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445

In [16]:
coordinates_list = list(zip(df_giti.latitude, df_giti.longitude))
pl(coordinates_list)

20532

[(25.7741728, -80.19362),
 (42.3602534, -71.0582912),
 (33.448436699999995, -112.07414170000001),
 (45.5202471, -122.6741949),
 (29.7589382, -95.36769740000001),
 (34.0536909, -118.24276599999999),
 (42.3602534, -71.0582912),
 (41.5051613, -81.6934446),
 (42.331550899999996, -83.04664029999999),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (40.7127281, -74.0060152),
 (43.6534817, -79.38393470000001),
 (33.7489924, -84.3902644),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (41.875561600000005, -87.6244212),
 (35.4729886, -97.5170536),
 (35.227208600000004, -80.84308270000001),
 (32.7762719, -96.7968559),
 (39.7683331, -86.1583502),
 (29.424600199999997, -98.4951405),
 (40.759619799999996, -111.88679750000001),
 (39.7392364, -104.98486229999999),
 (29.7589382, -95.36769740000001),
 (37.8546664, -122.2921365),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (38.8949924, -77.0365581),
 (28.5421109, -81.3790304),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (35.227208600000004, -80.84308270000001),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (38.5810606, -121.493895),
 (39.9527237, -75.16352619999999),
 (33.7489924, -84.3902644),
 (41.5051613, -81.6934446),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (40.7127281, -74.0060152),
 (42.331550899999996, -83.04664029999999),
 (35.4729886, -97.5170536),
 (25.7741728, -80.19362),
 (28.5421109, -81.3790304),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (39.7392364, -104.98486229999999),
 (35.1490215, -90.0516285),
 (32.7762719, -96.7968559),
 (34.0536909, -118.24276599999999),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (38.5810606, -121.493895),
 (45.5202471, -122.6741949),
 (40.7127281, -74.0060152),
 (39.9527237, -75.16352619999999),
 (39.7683331, -86.1583502),
 (42.331550899999996, -83.04664029999999),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (43.0349931, -87.92249699999999),
 (35.227208600000004, -80.84308270000001),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (25.7741728, -80.19362),
 (40.833989, -74.0970865),
 (34.0536909, -118.24276599999999),
 (32.7762719, -96.7968559),
 (35.4729886, -97.5170536),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (37.8546664, -122.2921365),
 (45.5202471, -122.6741949),
 (41.875561600000005, -87.6244212),
 (43.6534817, -79.38393470000001),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (29.424600199999997, -98.4951405),
 (41.5051613, -81.6934446),
 (33.7489924, -84.3902644),
 (39.9527237, -75.16352619999999),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (44.9772995, -93.2654692),
 (45.5202471, -122.6741949),
 (43.0349931, -87.92249699999999),
 (34.0536909, -118.24276599999999),
 (35.1490215, -90.0516285),
 (42.331550899999996, -83.04664029999999),
 (33.7489924, -84.3902644),
 (40.833989, -74.0970865),
 (35.227208600000004, -80.84308270000001),
 (44.9772995, -93.2654692),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.7683331, -86.1583502),
 (42.3602534, -71.0582912),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (39.7392364, -104.98486229999999),
 (43.6534817, -79.38393470000001),
 (40.759619799999996, -111.88679750000001),
 (33.448436699999995, -112.07414170000001),
 (29.424600199999997, -98.4951405),
 (35.1490215, -90.0516285),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (40.7127281, -74.0060152),
 (41.875561600000005, -87.6244212),
 (45.5202471, -122.6741949),
 (35.4729886, -97.5170536),
 (43.0349931, -87.92249699999999),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (39.9527237, -75.16352619999999),
 (42.331550899999996, -83.04664029999999),
 (35.227208600000004, -80.84308270000001),
 (40.7127281, -74.0060152),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (41.875561600000005, -87.6244212),
 (33.7489924, -84.3902644),
 (44.9772995, -93.2654692),
 (25.7741728, -80.19362),
 (29.949932300000004, -90.0701156),
 (33.448436699999995, -112.07414170000001),
 (35.1490215, -90.0516285),
 (34.0536909, -118.24276599999999),
 (39.7392364, -104.98486229999999),
 (40.759619799999996, -111.88679750000001),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (43.6534817, -79.38393470000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (40.833989, -74.0970865),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (29.7589382, -95.36769740000001),
 (29.424600199999997, -98.4951405),
 (32.7762719, -96.7968559),
 (39.7392364, -104.98486229999999),
 (34.0536909, -118.24276599999999),
 (40.759619799999996, -111.88679750000001),
 (45.5202471, -122.6741949),
 (43.6534817, -79.38393470000001),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (39.9527237, -75.16352619999999),
 (40.7127281, -74.0060152),
 (33.448436699999995, -112.07414170000001),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (37.8546664, -122.2921365),
 (29.7589382, -95.36769740000001),
 (44.9772995, -93.2654692),
 (42.3602534, -71.0582912),
 (35.4729886, -97.5170536),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (29.424600199999997, -98.4951405),
 (33.7489924, -84.3902644),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (37.8546664, -122.2921365),
 (41.875561600000005, -87.6244212),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (35.1490215, -90.0516285),
 (42.3602534, -71.0582912),
 (32.7762719, -96.7968559),
 (39.7683331, -86.1583502),
 (39.7392364, -104.98486229999999),
 (41.5051613, -81.6934446),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (40.759619799999996, -111.88679750000001),
 (40.7127281, -74.0060152),
 (43.0349931, -87.92249699999999),
 (34.0536909, -118.24276599999999),
 (29.949932300000004, -90.0701156),
 (45.5202471, -122.6741949),
 (42.331550899999996, -83.04664029999999),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (33.7489924, -84.3902644),
 (43.0349931, -87.92249699999999),
 (40.759619799999996, -111.88679750000001),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (35.227208600000004, -80.84308270000001),
 (29.7589382, -95.36769740000001),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (40.833989, -74.0970865),
 (40.7127281, -74.0060152),
 (37.8546664, -122.2921365),
 (35.1490215, -90.0516285),
 (32.7762719, -96.7968559),
 (39.9527237, -75.16352619999999),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (29.424600199999997, -98.4951405),
 (38.5810606, -121.493895),
 (44.9772995, -93.2654692),
 (25.7741728, -80.19362),
 (42.3602534, -71.0582912),
 (41.875561600000005, -87.6244212),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (39.7392364, -104.98486229999999),
 (33.7489924, -84.3902644),
 (40.759619799999996, -111.88679750000001),
 (29.7589382, -95.36769740000001),
 (39.7683331, -86.1583502),
 (43.6534817, -79.38393470000001),
 (28.5421109, -81.3790304),
 (35.227208600000004, -80.84308270000001),
 (38.8949924, -77.0365581),
 (40.7127281, -74.0060152),
 (44.9772995, -93.2654692),
 (39.9527237, -75.16352619999999),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (38.5810606, -121.493895),
 (45.5202471, -122.6741949),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (42.331550899999996, -83.04664029999999),
 (35.227208600000004, -80.84308270000001),
 (40.759619799999996, -111.88679750000001),
 (40.833989, -74.0970865),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (39.7683331, -86.1583502),
 (25.7741728, -80.19362),
 (43.6534817, -79.38393470000001),
 (41.875561600000005, -87.6244212),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (35.1490215, -90.0516285),
 (45.5202471, -122.6741949),
 (29.949932300000004, -90.0701156),
 (43.0349931, -87.92249699999999),
 (37.8546664, -122.2921365),
 (39.9527237, -75.16352619999999),
 (29.424600199999997, -98.4951405),
 (33.7489924, -84.3902644),
 (44.9772995, -93.2654692),
 (42.331550899999996, -83.04664029999999),
 (38.5810606, -121.493895),
 (35.4729886, -97.5170536),
 (29.424600199999997, -98.4951405),
 (29.7589382, -95.36769740000001),
 (40.7127281, -74.0060152),
 (33.448436699999995, -112.07414170000001),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (35.227208600000004, -80.84308270000001),
 (35.1490215, -90.0516285),
 (28.5421109, -81.3790304),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (39.7392364, -104.98486229999999),
 (35.4729886, -97.5170536),
 (40.759619799999996, -111.88679750000001),
 (42.331550899999996, -83.04664029999999),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (40.833989, -74.0970865),
 (41.5051613, -81.6934446),
 (39.9527237, -75.16352619999999),
 (33.7489924, -84.3902644),
 (39.7683331, -86.1583502),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (45.5202471, -122.6741949),
 (35.1490215, -90.0516285),
 (34.0536909, -118.24276599999999),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (41.875561600000005, -87.6244212),
 (40.7127281, -74.0060152),
 (39.7392364, -104.98486229999999),
 (25.7741728, -80.19362),
 (33.448436699999995, -112.07414170000001),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (38.8949924, -77.0365581),
 (34.0536909, -118.24276599999999),
 (42.331550899999996, -83.04664029999999),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (35.4729886, -97.5170536),
 (40.833989, -74.0970865),
 (40.759619799999996, -111.88679750000001),
 (41.875561600000005, -87.6244212),
 (29.424600199999997, -98.4951405),
 (40.7127281, -74.0060152),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (39.7683331, -86.1583502),
 (33.448436699999995, -112.07414170000001),
 (28.5421109, -81.3790304),
 (45.5202471, -122.6741949),
 (39.7392364, -104.98486229999999),
 (42.3602534, -71.0582912),
 (35.4729886, -97.5170536),
 (39.9527237, -75.16352619999999),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (43.6534817, -79.38393470000001),
 (35.1490215, -90.0516285),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (35.227208600000004, -80.84308270000001),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (41.5051613, -81.6934446),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (40.759619799999996, -111.88679750000001),
 (41.875561600000005, -87.6244212),
 (32.7762719, -96.7968559),
 (40.833989, -74.0970865),
 (38.5810606, -121.493895),
 (40.7127281, -74.0060152),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (35.227208600000004, -80.84308270000001),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (33.7489924, -84.3902644),
 (32.7762719, -96.7968559),
 (25.7741728, -80.19362),
 (35.1490215, -90.0516285),
 (43.0349931, -87.92249699999999),
 (35.4729886, -97.5170536),
 (41.5051613, -81.6934446),
 (29.424600199999997, -98.4951405),
 (40.833989, -74.0970865),
 (39.7392364, -104.98486229999999),
 (45.5202471, -122.6741949),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (40.7127281, -74.0060152),
 (42.3602534, -71.0582912),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (38.8949924, -77.0365581),
 (38.5810606, -121.493895),
 (29.949932300000004, -90.0701156),
 (34.0536909, -118.24276599999999),
 (37.8546664, -122.2921365),
 (42.3602534, -71.0582912),
 (33.7489924, -84.3902644),
 (25.7741728, -80.19362),
 (39.7683331, -86.1583502),
 (44.9772995, -93.2654692),
 (35.4729886, -97.5170536),
 (33.448436699999995, -112.07414170000001),
 (29.7589382, -95.36769740000001),
 (29.424600199999997, -98.4951405),
 (28.5421109, -81.3790304),
 (38.5810606, -121.493895),
 (40.759619799999996, -111.88679750000001),
 (39.7392364, -104.98486229999999),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (29.949932300000004, -90.0701156),
 (41.5051613, -81.6934446),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (33.7489924, -84.3902644),
 (39.9527237, -75.16352619999999),
 (38.8949924, -77.0365581),
 (40.7127281, -74.0060152),
 (35.227208600000004, -80.84308270000001),
 (42.331550899999996, -83.04664029999999),
 (32.7762719, -96.7968559),
 (34.0536909, -118.24276599999999),
 (41.875561600000005, -87.6244212),
 (40.7127281, -74.0060152),
 (35.227208600000004, -80.84308270000001),
 (41.5051613, -81.6934446),
 (43.0349931, -87.92249699999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (28.5421109, -81.3790304),
 (42.331550899999996, -83.04664029999999),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (29.424600199999997, -98.4951405),
 (35.4729886, -97.5170536),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (41.875561600000005, -87.6244212),
 (29.949932300000004, -90.0701156),
 (40.759619799999996, -111.88679750000001),
 (33.7489924, -84.3902644),
 (38.8949924, -77.0365581),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (29.7589382, -95.36769740000001),
 (35.227208600000004, -80.84308270000001),
 (41.5051613, -81.6934446),
 (28.5421109, -81.3790304),
 (42.3602534, -71.0582912),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (43.0349931, -87.92249699999999),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (35.4729886, -97.5170536),
 (39.7683331, -86.1583502),
 (32.7762719, -96.7968559),
 (29.424600199999997, -98.4951405),
 (41.875561600000005, -87.6244212),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (40.759619799999996, -111.88679750000001),
 (35.1490215, -90.0516285),
 (37.8546664, -122.2921365),
 (45.5202471, -122.6741949),
 (29.949932300000004, -90.0701156),
 (40.7127281, -74.0060152),
 (33.7489924, -84.3902644),
 (38.8949924, -77.0365581),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (35.1490215, -90.0516285),
 (40.833989, -74.0970865),
 (39.9527237, -75.16352619999999),
 (44.9772995, -93.2654692),
 (37.8546664, -122.2921365),
 (25.7741728, -80.19362),
 (32.7762719, -96.7968559),
 (43.0349931, -87.92249699999999),
 (35.227208600000004, -80.84308270000001),
 (38.5810606, -121.493895),
 (41.875561600000005, -87.6244212),
 (43.6534817, -79.38393470000001),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (40.7127281, -74.0060152),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (34.0536909, -118.24276599999999),
 (40.759619799999996, -111.88679750000001),
 (45.5202471, -122.6741949),
 (40.833989, -74.0970865),
 (29.7589382, -95.36769740000001),
 (35.4729886, -97.5170536),
 (33.448436699999995, -112.07414170000001),
 (39.7392364, -104.98486229999999),
 (34.0536909, -118.24276599999999),
 (39.7683331, -86.1583502),
 (25.7741728, -80.19362),
 (38.8949924, -77.0365581),
 (29.949932300000004, -90.0701156),
 (35.4729886, -97.5170536),
 (29.7589382, -95.36769740000001),
 (32.7762719, -96.7968559),
 (43.0349931, -87.92249699999999),
 (40.759619799999996, -111.88679750000001),
 (42.3602534, -71.0582912),
 (41.5051613, -81.6934446),
 (42.331550899999996, -83.04664029999999),
 (28.5421109, -81.3790304),
 (45.5202471, -122.6741949),
 (39.9527237, -75.16352619999999),
 (40.833989, -74.0970865),
 (40.7127281, -74.0060152),
 (34.0536909, -118.24276599999999),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (39.7683331, -86.1583502),
 (29.424600199999997, -98.4951405),
 (37.8546664, -122.2921365),
 (33.7489924, -84.3902644),
 (35.1490215, -90.0516285),
 (40.833989, -74.0970865),
 (35.4729886, -97.5170536),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (45.5202471, -122.6741949),
 (25.7741728, -80.19362),
 (42.331550899999996, -83.04664029999999),
 (41.875561600000005, -87.6244212),
 (28.5421109, -81.3790304),
 (29.949932300000004, -90.0701156),
 (35.227208600000004, -80.84308270000001),
 (44.9772995, -93.2654692),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (34.0536909, -118.24276599999999),
 (43.0349931, -87.92249699999999),
 (39.7392364, -104.98486229999999),
 (39.7683331, -86.1583502),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (29.424600199999997, -98.4951405),
 (25.7741728, -80.19362),
 (41.5051613, -81.6934446),
 (33.448436699999995, -112.07414170000001),
 (37.8546664, -122.2921365),
 (40.833989, -74.0970865),
 (35.227208600000004, -80.84308270000001),
 (43.6534817, -79.38393470000001),
 (35.4729886, -97.5170536),
 (45.5202471, -122.6741949),
 (38.8949924, -77.0365581),
 (39.9527237, -75.16352619999999),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (28.5421109, -81.3790304),
 (42.3602534, -71.0582912),
 (41.875561600000005, -87.6244212),
 (29.7589382, -95.36769740000001),
 (35.1490215, -90.0516285),
 (40.7127281, -74.0060152),
 (29.949932300000004, -90.0701156),
 (44.9772995, -93.2654692),
 (29.424600199999997, -98.4951405),
 (34.0536909, -118.24276599999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (39.7683331, -86.1583502),
 (32.7762719, -96.7968559),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (25.7741728, -80.19362),
 (33.7489924, -84.3902644),
 (39.9527237, -75.16352619999999),
 (35.227208600000004, -80.84308270000001),
 (29.7589382, -95.36769740000001),
 (41.875561600000005, -87.6244212),
 (41.5051613, -81.6934446),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (28.5421109, -81.3790304),
 (38.5810606, -121.493895),
 (32.7762719, -96.7968559),
 (42.3602534, -71.0582912),
 (40.833989, -74.0970865),
 (40.7127281, -74.0060152),
 (43.6534817, -79.38393470000001),
 (41.5051613, -81.6934446),
 (42.331550899999996, -83.04664029999999),
 (35.4729886, -97.5170536),
 (37.8546664, -122.2921365),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (35.1490215, -90.0516285),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (38.8949924, -77.0365581),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (43.6534817, -79.38393470000001),
 (39.7683331, -86.1583502),
 (33.7489924, -84.3902644),
 (28.5421109, -81.3790304),
 (40.7127281, -74.0060152),
 (44.9772995, -93.2654692),
 (41.875561600000005, -87.6244212),
 (35.4729886, -97.5170536),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (35.1490215, -90.0516285),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),

In [17]:
game_coordinates_list = list(zip(df_giti.game_latitude, df_giti.game_longitude))
pl(game_coordinates_list)

20532

[(42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),

In [18]:
travel_distance_list = [hs.haversine(loc1,loc2,unit=Unit.MILES) for loc1, loc2 in zip(coordinates_list, game_coordinates_list)]
pl(travel_distance_list)

20532

[1257.7550908756243,
 0.0,
 1005.6068546741288,
 0.0,
 1371.0203256456189,
 0.0,
 549.4712596346186,
 0.0,
 473.7152146791305,
 0.0,
 1021.727020506881,
 0.0,
 342.0741124151013,
 0.0,
 336.69816053583213,
 0.0,
 1511.3184170911807,
 0.0,
 911.8376720732039,
 0.0,
 692.3237624109032,
 0.0,
 928.3135848797398,
 0.0,
 999.6185000198976,
 0.0,
 370.63220056318727,
 0.0,
 1636.7982620425837,
 0.0,
 826.1090577738885,
 0.0,
 757.3325451140109,
 0.0,
 505.25972991303587,
 0.0,
 0.0,
 428.0141074999891,
 0.0,
 2493.288458136063,
 0.0,
 665.6418837802362,
 189.2945626572829,
 0.0,
 0.0,
 190.24234709206948,
 0.0,
 909.1464427901321,
 0.0,
 204.65557175833678,
 0.0,
 297.42910279697315,
 0.0,
 1080.354855295494,
 419.7478977614941,
 0.0,
 346.7114177805857,
 0.0,
 0.0,
 356.77999613941813,
 0.0,
 541.8739256546274,
 0.0,
 2096.3124457495733,
 2439.0261897005403,
 0.0,
 582.8981093587582,
 0.0,
 236.7452890092217,
 0.0,
 0.0,
 699.8517215741878,
 0.0,
 878.3664879943395,
 0.0,
 658.9773889721264,
 506.8922593701188,
 0.0,
 1097.71221287464,
 0.0,
 0.0,
 1237.721897045037,
 0.0,
 860.8970820860847,
 0.0,
 346.7114177805857,
 1754.6733806950567,
 0.0,
 2195.770013896148,
 0.0,
 0.0,
 1201.4545674816625,
 0.0,
 555.7638525511979,
 123.82848953758614,
 0.0,
 611.6968737022398,
 0.0,
 0.0,
 1512.982440338859,
 1714.1564739077517,
 0.0,
 0.0,
 1599.731900421359,
 597.4649414216475,
 0.0,
 0.0,
 533.3862848039789,
 1309.1553850832252,
 0.0,
 0.0,
 582.8981093587582,
 0.0,
 856.184509998557,
 0.0,
 317.6993828030891,
 662.3957199988946,
 0.0,
 1664.6848142046217,
 0.0,
 0.0,
 846.5978247706427,
 1791.4512670054219,
 0.0,
 0.0,
 1178.3280692466935,
 361.33504430987534,
 0.0,
 710.748248484685,
 0.0,
 0.0,
 1484.1923140559552,
 243.50383115209635,
 0.0,
 943.8039325925112,
 0.0,
 358.2255063668294,
 0.0,
 0.0,
 504.95570599782053,
 0.0,
 204.06190170192284,
 0.0,
 848.3503160607481,
 907.9020862233867,
 0.0,
 668.3652260831045,
 0.0,
 0.0,
 1259.918430587992,
 830.0173643156205,
 0.0,
 590.9322513396475,
 0.0,
 0.0,
 2171.1775372309676,
 0.0,
 462.96262595090275,
 304.7544036694486,
 0.0,
 0.0,
 1097.71221287464,
 0.0,
 911.8376720732039,
 189.3092847510026,
 0.0,
 0.0,
 662.3957199988946,
 579.6038101803562,
 0.0,
 0.0,
 2108.168262136255,
 1745.5601338405384,
 0.0,
 80.46150245198206,
 0.0,
 1588.5257961150173,
 0.0,
 0.0,
 2078.6064333524573,
 0.0,
 1057.7038149366604,
 1492.6844201003407,
 0.0,
 826.1090577738885,
 0.0,
 0.0,
 1103.8568326209754,
 401.3578113976756,
 0.0,
 0.0,
 2255.507897421165,
 0.0,
 918.1896356956805,
 1259.918430587992,
 0.0,
 1549.1849079041806,
 0.0,
 0.0,
 998.1967850986543,
 397.67493269827435,
 0.0,
 0.0,
 2086.639441708349,
 732.8043912270535,
 0.0,
 1669.465639128503,
 0.0,
 0.0,
 1964.1039181875544,
 0.0,
 1521.2817948491495,
 0.0,
 669.3329502450495,
 1915.2494695355083,
 0.0,
 0.0,
 587.3548878865438,
 1218.1766231559081,
 0.0,
 0.0,
 397.67493269827435,
 0.0,
 2557.28513729573,
 0.0,
 419.7478977614941,
 1256.7321768243976,
 0.0,
 1201.4545674816625,
 0.0,
 0.0,
 1511.3184170911807,
 0.0,
 1257.7550908756243,
 0.0,
 1846.6241080361576,
 830.0173643156205,
 0.0,
 0.0,
 1580.2626542430153,
 865.8186776164094,
 0.0,
 1049.9311355093557,
 0.0,
 328.97291078996636,
 0.0,
 1016.3693093408949,
 0.0,
 1297.5101338123093,
 0.0,
 0.0,
 634.2011005280775,
 1484.1923140559552,
 0.0,
 0.0,
 1979.1623463459048,
 0.0,
 1723.4538239912054,
 0.0,
 943.8039325925112,
 0.0,
 263.02056105803024,
 0.0,
 1236.1811936889708,
 0.0,
 593.5638839862108,
 1134.7839657637262,
 0.0,
 2060.0430457880866,
 0.0,
 0.0,
 1829.0024941883546,
 1505.3700372114777,
 0.0,
 0.0,
 907.9020862233867,
 2020.4744966302394,
 0.0,
 0.0,
 421.769052086928,
 1417.5238959796427,
 0.0,
 356.77999613941813,
 0.0,
 938.5505538152904,
 0.0,
 683.1772751956723,
 0.0,
 442.1753031394606,
 0.0,
 0.0,
 585.7483872875114,
 860.8970820860847,
 0.0,
 2078.6064333524573,
 0.0,
 0.0,
 2440.192700390837,
 0.0,
 358.2255063668294,
 427.2298841912476,
 0.0,
 350.60736167935596,
 0.0,
 1845.58380513783,
 0.0,
 1740.4311991546947,
 0.0,
 0.0,
 941.9016776014989,
 1627.1250704076886,
 0.0,
 0.0,
 1978.4144747277564,
 0.0,
 335.50971852603516,
 0.0,
 394.29656854826703,
 1979.1623463459048,
 0.0,
 1521.2817948491495,
 0.0,
 0.0,
 442.1753031394606,
 414.1098914675343,
 0.0,
 1960.9853062704499,
 0.0,
 1052.8380359241532,
 0.0,
 2499.7462120921923,
 0.0,
 1805.695649251401,
 0.0,
 1842.401660057441,
 0.0,
 0.0,
 981.218538192645,
 0.0,
 1492.6844201003407,
 0.0,
 692.9806755991466,
 1301.3223611097274,
 0.0,
 762.3425772674227,
 0.0,
 0.0,
 654.2806697398152,
 1521.2817948491495,
 0.0,
 925.276616618397,
 0.0,
 1086.7513193810807,
 0.0,
 804.7205095594255,
 0.0,
 2493.288458136063,
 0.0,
 2557.28513729573,
 0.0,
 1778.7254814411679,
 0.0,
 0.0,
 822.0307246689963,
 0.0,
 719.4760725739154,
 873.197475932693,
 0.0,
 0.0,
 731.5072200975883,
 1257.0365975939926,
 0.0,
 1621.2814451856227,
 0.0,
 0.0,
 634.7854786213595,
 0.0,
 2445.4714005140036,
 429.8471679338212,
 0.0,
 0.0,
 394.48116354762044,
 0.0,
 1880.0620889175036,
 0.0,
 346.7114177805857,
 936.1601546565737,
 0.0,
 0.0,
 1026.4556691488783,
 693.6620504840113,
 0.0,
 1014.343338380677,
 0.0,
 0.0,
 1035.3691844292484,
 532.3233986913424,
 0.0,
 939.5318193386419,
 0.0,
 0.0,
 1669.465639128503,
 263.02056105803024,
 0.0,
 0.0,
 747.2132361387777,
 123.82848953758614,
 0.0,
 0.0,
 531.0133117495826,
 999.2426184998326,
 0.0,
 0.0,
 1742.4647197663835,
 531.0133117495826,
 0.0,
 0.0,
 335.4625665865379,
 335.50971852603516,
 0.0,
 0.0,
 189.12181102728692,
 204.65557175833678,
 0.0,
 623.0404260664787,
 0.0,
 0.0,
 1111.8283167245083,
 0.0,
 190.82259289154084,
 0.0,
 1636.7982620425837,
 0.0,
 1451.9619233616475,
 1432.4123899800609,
 0.0,
 0.0,
 541.8739256546274,
 0.0,
 361.33504430987534,
 925.6977754554267,
 0.0,
 895.8362709305825,
 0.0,
 0.0,
 429.8471679338212,
 0.0,
 252.33693312258433,
 0.0,
 1021.727020506881,
 688.1281231275818,
 0.0,
 252.42309911702628,
 0.0,
 918.1896356956805,
 0.0,
 0.0,
 356.77999613941813,
 579.6038101803562,
 0.0,
 0.0,
 1791.4512670054219,
 0.0,
 2060.0430457880866,
 0.0,
 745.9349350837282,
 0.0,
 757.3325451140109,
 0.0,
 630.3677518963235,
 82.8047144848537,
 0.0,
 0.0,
 1572.6208565402335,
 1109.624500256641,
 0.0,
 0.0,
 658.9773889721264,
 0.0,
 1789.3603163234845,
 0.0,
 735.280373697252,
 0.0,
 480.60434041402027,
 0.0,
 506.8922593701188,
 0.0,
 579.6038101803562,
 2431.2310445344074,
 0.0,
 0.0,
 414.1098914675343,
 585.7483872875114,
 0.0,
 0.0,
 1805.695649251401,
 0.0,
 924.9294534439942,
 576.7587141353875,
 0.0,
 224.90735849306708,
 0.0,
 1238.1674664691448,
 0.0,
 549.4712596346186,
 0.0,
 957.317037458219,
 0.0,
 2405.718940073566,
 0.0,
 9.638670816817898,
 0.0,
 1599.731900421359,
 0.0,
 0.0,
 1882.1355736425428,
 1482.1696648028337,
 0.0,
 0.0,
 336.69816053583213,
 0.0,
 1320.7219376428775,
 0.0,
 350.60736167935596,
 0.0,
 2532.763146983884,
 0.0,
 1155.4132545112197,
 0.0,
 985.683084398235,
 0.0,
 648.730450705561,
 863.9098411327615,
 0.0,
 0.0,
 1371.0203256456189,
 911.538664437991,
 0.0,
 1353.3612619249116,
 0.0,
 0.0,
 1201.4545674816625,
 1090.2762678501972,
 0.0,
 648.9061325321354,
 0.0,
 533.3862848039789,
 0.0,
 0.0,
 1115.513367403905,
 2347.414304112356,
 0.0,
 665.6418837802362,
 0.0,
 0.0,
 957.317037458219,
 0.0,
 848.3503160607481,
 484.3372457240657,
 0.0,
 1168.3582864836485,
 0.0,
 1111.8283167245083,
 0.0,
 830.0173643156205,
 0.0,
 0.0,
 1496.1585365587982,
 998.6748547554433,
 0.0,
 0.0,
 361.33504430987534,
 0.0,
 605.6067895541885,
 0.0,
 450.6806289097844,
 941.9016776014989,
 0.0,
 629.1927584744221,
 0.0,
 0.0,
 1065.5213604878866,
 0.0,
 1437.9670795429058,
 189.12181102728692,
 0.0,
 342.0741124151013,
 0.0,
 89.99946657926071,
 0.0,
 0.0,
 1378.8543924195296,
 506.8922593701188,
 0.0,
 877.0688639487374,
 0.0,
 0.0,
 1977.5975378110527,
 0.0,
 826.1090577738885,
 440.37546126747037,
 0.0,
 401.3578113976756,
 0.0,
 0.0,
 1016.3693093408949,
 0.0,
 692.3237624109032,
 1269.9593677314772,
 0.0,
 1247.2634658124746,
 0.0,
 0.0,
 361.33504430987534,
 747.2132361387777,
 0.0,
 0.0,
 1355.3679161235204,
 358.2255063668294,
 0.0,
 0.0,
 1474.555697626409,
 0.0,
 1105.8174000387953,
 1005.6068546741288,
 0.0,
 0.0,
 2294.1068193551796,
 0.0,
 1765.245449575629,
 0.0,
 307.0180387408113,
 0.0,
 342.0741124151013,
 0.0,
 243.50383115209635,
 0.0,
 693.6620504840113,
 940.1151117731339,
 0.0,
 0.0,
 1482.1696648028337,
 0.0,
 1259.918430587992,
 2086.639441708349,
 0.0,
 0.0,
 2371.7231133536548,
 0.0,
 0.0,
 270.64358899505163,
 0.0,
 1368.3966475144493,
 0.0,
 0.0,
 2525.2632101269974,
 428.0141074999891,
 0.0,
 0.0,
 1342.5106878833094,
 204.06190170192284,
 0.0,
 1742.4647197663835,
 0.0,
 542.1008515695606,
 0.0,
 0.0,
 576.7587141353875,
 1005.3645764392342,
 0.0,
 881.3631489036708,
 0.0,
 0.0,
 1005.6068546741288,
 0.0,
 1915.2494695355083,
 2584.145504672017,
 0.0,
 0.0,
 1599.731900421359,
 0.0,
 427.2298841912476,
 720.5774825143434,
 0.0,
 0.0,
 206.38674914521283,
 354.89722365019605,
 0.0,
 0.0,
 998.6748547554433,
 0.0,
 1114.514531144637,
 2547.32703458827,
 0.0,
 0.0,
 1627.1250704076886,
 0.0,
 1088.35054827345,
 2440.192700390837,
 0.0,
 949.8759010099621,
 0.0,
 1718.3868264408243,
 0.0,
 0.0,
 2197.41930669657,
 0.0,
 668.3652260831045,
 0.0,
 164.53512747698008,
 1845.58380513783,
 0.0,
 857.0466037570072,
 0.0,
 0.0,
 590.9322513396475,
 587.3548878865438,
 0.0,
 0.0,
 82.8047144848537,
 2294.1068193551796,
 0.0,
 0.0,
 597.4649414216475,
 0.0,
 1606.0254526033598,
 0.0,
 1548.7958131678793,
 1572.6208565402335,
 0.0,
 1805.695649251401,
 0.0,
 190.24234709206948,
 0.0,
 2388.213316325838,
 0.0,
 0.0,
 435.45836957530247,
 0.0,
 1090.2762678501972,
 0.0,
 519.8262624890134,
 1880.0620889175036,
 0.0,
 414.1098914675343,
 0.0,
 1107.6713727379392,
 0.0,
 0.0,
 1278.447398786448,
 1631.2631962247362,
 0.0,
 0.0,
 205.5260716310946,
 0.0,
 936.1601546565737,
 802.0287240818725,
 0.0,
 263.02056105803024,
 0.0,
 1091.5549017620242,
 0.0,
 2388.213316325838,
 0.0,
 333.1692270964438,
 0.0,
 0.0,
 226.3415680725875,
 1979.1623463459048,
 0.0,
 0.0,
 1432.4123899800609,
 1335.978087947665,
 0.0,
 0.0,
 484.3372457240657,
 884.5611256592691,
 0.0,
 0.0,
 1423.0152830946975,
 864.032817310423,
 0.0,
 924.9294534439942,
 0.0,
 0.0,
 403.79016869202155,
 1742.4647197663835,
 0.0,
 0.0,
 1238.1674664691448,
 631.7448114575376,
 0.0,
 698.2588693243663,
 0.0,
 0.0,
 530.0060745870636,
 0.0,
 805.582851668921,
 0.0,
 747.2132361387777,
 2171.1775372309676,
 0.0,
 0.0,
 940.1151117731339,
 1606.0254526033598,
 0.0,
 840.2005994415055,
 0.0,
 0.0,
 401.3578113976756,
 0.0,
 1564.1115057076697,
 713.5069902699892,
 0.0,
 328.97291078996636,
 0.0,
 0.0,
 1109.624500256641,
 846.5978247706427,
 0.0,
 0.0,
 1714.1564739077517,
 1636.7982620425837,
 0.0,
 0.0,
 1521.2817948491495,
 938.6943406826813,
 0.0,
 960.8312896536894,
 0.0,
 663.4130544605742,
 0.0,
 951.5432206793267,
 0.0,
 0.0,
 66.30620533958735,
 0.0,
 1740.4311991546947,
 555.7638525511979,
 0.0,
 206.38674914521283,
 0.0,
 593.5638839862108,
 0.0,
 0.0,
 270.64358899505163,
 0.0,
 1324.1983819186553,
 0.0,
 984.406711381413,
 1169.2169981333368,
 0.0,
 0.0,
 802.0287240818725,
 1371.0203256456189,
 0.0,
 1035.3691844292484,
 0.0,
 0.0,
 1770.2776727913017,
 1978.4144747277564,
 0.0,
 0.0,
 710.748248484685,
 1115.5834858590977,
 0.0,
 2335.1019964477055,
 0.0,
 0.0,
 503.66510345331915,
 530.0060745870636,
 0.0,
 356.77999613941813,
 0.0,
 0.0,
 629.1927584744221,
 0.0,
 236.7452890092217,
 383.90889904398625,
 0.0,
 424.16077807051124,
 0.0,
 0.0,
 1385.4792165282026,
 1574.5848286114256,
 0.0,
 504.95570599782053,
 0.0,
 0.0,
 943.8039325925112,
 816.9930943495133,
 0.0,
 669.3329502450495,
 0.0,
 0.0,
 1052.7434048235602,
 0.0,
 190.82259289154084,
 0.0,
 1218.1766231559081,
 634.7854786213595,
 0.0,
 361.33504430987534,
 0.0,
 2508.547944427655,
 0.0,
 0.0,
 895.8362709305825,
 805.582851668921,
 0.0,
 0.0,
 1091.5549017620242,
 81.53729315997106,
 0.0,
 1203.3470030062688,
 0.0,
 1201.4545674816625,
 0.0,
 981.218538192645,
 0.0,
 0.0,
 2128.13924768093,
 436.19754487154137,
 0.0,
 490.9973100034139,
 0.0,
 611.6968737022398,
 0.0,
 0.0,
 698.2588693243663,
 1669.465639128503,
 0.0,
 1320.7219376428775,
 0.0,
 966.8017616999593,
 0.0,
 0.0,
 2078.0072972535013,
 1745.5601338405384,
 0.0,
 0.0,
 579.6038101803562,
 938.7011466947141,
 0.0,
 0.0,
 252.42309911702628,
 0.0,
 634.7854786213595,
 0.0,
 1358.3385035954743,
 0.0,
 2289.223315210235,
 0.0,
 490.9973100034139,
 704.5185687170443,
 0.0,
 0.0,
 1301.3223611097274,
 755.3198580290265,
 0.0,
 0.0,
 1687.408508011513,
 0.0,
 2388.213316325838,
 964.5343561840182,
 0.0,
 307.0180387408113,
 0.0,
 0.0,
 2584.145504672017,
 1008.7044917951022,
 0.0,
 421.769052086928,
 0.0,
 0.0,
 857.0466037570072,
 886.8007559408917,
 0.0,
 1247.2634658124746,
 0.0,
 0.0,
 643.7252850043227,
 0.0,
 1932.4772334250538,
 429.8471679338212,
 0.0,
 0.0,
 1025.0026301036637,
 0.0,
 1833.7554457107258,
 634.2011005280775,
 0.0,
 0.0,
 1599.731900421359,
 654.2806697398152,
 0.0,
 2430.5158605515276,
 0.0,
 0.0,
 1120.861473149211,
 ...]

In [19]:
df_travel_distance = pd.DataFrame({'travel_distance': travel_distance_list})
p(df_travel_distance)

(20532, 1)

       travel_distance
0          1257.755091
1             0.000000
2          1005.606855
3             0.000000
4          1371.020326
20527         0.000000
20528         0.000000
20529      2153.640745
20530         0.000000
20531      2153.640745

In [20]:
df_giti = pd.concat([df_giti, df_travel_distance], axis=1)
p(df_giti)

(20532, 64)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745

In [21]:
#time zone of each team

In [22]:
!pip install timezonefinder

Requirement already satisfied: timezonefinder in /opt/anaconda3/lib/python3.8/site-packages (5.2.0)
Requirement already satisfied: numpy>=1.16 in /opt/anaconda3/lib/python3.8/site-packages (from timezonefinder) (1.19.2)

In [23]:
!pip install geopy

Requirement already satisfied: geopy in /opt/anaconda3/lib/python3.8/site-packages (2.2.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /opt/anaconda3/lib/python3.8/site-packages (from geopy) (1.52)

In [24]:
from timezonefinder import TimezoneFinder

In [25]:
# object creation
obj = TimezoneFinder()

In [26]:
# pass the longitude and latitude
# in timezone_at and
# it return time zone 
latitude = 25.6093239
longitude = 85.1235252
obj.timezone_at(lng=latitude, lat=longitude)

'Etc/GMT-2'

In [27]:
pl(coordinates_list)

20532

[(25.7741728, -80.19362),
 (42.3602534, -71.0582912),
 (33.448436699999995, -112.07414170000001),
 (45.5202471, -122.6741949),
 (29.7589382, -95.36769740000001),
 (34.0536909, -118.24276599999999),
 (42.3602534, -71.0582912),
 (41.5051613, -81.6934446),
 (42.331550899999996, -83.04664029999999),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (40.7127281, -74.0060152),
 (43.6534817, -79.38393470000001),
 (33.7489924, -84.3902644),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (41.875561600000005, -87.6244212),
 (35.4729886, -97.5170536),
 (35.227208600000004, -80.84308270000001),
 (32.7762719, -96.7968559),
 (39.7683331, -86.1583502),
 (29.424600199999997, -98.4951405),
 (40.759619799999996, -111.88679750000001),
 (39.7392364, -104.98486229999999),
 (29.7589382, -95.36769740000001),
 (37.8546664, -122.2921365),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (38.8949924, -77.0365581),
 (28.5421109, -81.3790304),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (35.227208600000004, -80.84308270000001),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (38.5810606, -121.493895),
 (39.9527237, -75.16352619999999),
 (33.7489924, -84.3902644),
 (41.5051613, -81.6934446),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (40.7127281, -74.0060152),
 (42.331550899999996, -83.04664029999999),
 (35.4729886, -97.5170536),
 (25.7741728, -80.19362),
 (28.5421109, -81.3790304),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (39.7392364, -104.98486229999999),
 (35.1490215, -90.0516285),
 (32.7762719, -96.7968559),
 (34.0536909, -118.24276599999999),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (38.5810606, -121.493895),
 (45.5202471, -122.6741949),
 (40.7127281, -74.0060152),
 (39.9527237, -75.16352619999999),
 (39.7683331, -86.1583502),
 (42.331550899999996, -83.04664029999999),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (43.0349931, -87.92249699999999),
 (35.227208600000004, -80.84308270000001),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (25.7741728, -80.19362),
 (40.833989, -74.0970865),
 (34.0536909, -118.24276599999999),
 (32.7762719, -96.7968559),
 (35.4729886, -97.5170536),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (37.8546664, -122.2921365),
 (45.5202471, -122.6741949),
 (41.875561600000005, -87.6244212),
 (43.6534817, -79.38393470000001),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (29.424600199999997, -98.4951405),
 (41.5051613, -81.6934446),
 (33.7489924, -84.3902644),
 (39.9527237, -75.16352619999999),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (44.9772995, -93.2654692),
 (45.5202471, -122.6741949),
 (43.0349931, -87.92249699999999),
 (34.0536909, -118.24276599999999),
 (35.1490215, -90.0516285),
 (42.331550899999996, -83.04664029999999),
 (33.7489924, -84.3902644),
 (40.833989, -74.0970865),
 (35.227208600000004, -80.84308270000001),
 (44.9772995, -93.2654692),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.7683331, -86.1583502),
 (42.3602534, -71.0582912),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (39.7392364, -104.98486229999999),
 (43.6534817, -79.38393470000001),
 (40.759619799999996, -111.88679750000001),
 (33.448436699999995, -112.07414170000001),
 (29.424600199999997, -98.4951405),
 (35.1490215, -90.0516285),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (40.7127281, -74.0060152),
 (41.875561600000005, -87.6244212),
 (45.5202471, -122.6741949),
 (35.4729886, -97.5170536),
 (43.0349931, -87.92249699999999),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (39.9527237, -75.16352619999999),
 (42.331550899999996, -83.04664029999999),
 (35.227208600000004, -80.84308270000001),
 (40.7127281, -74.0060152),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (41.875561600000005, -87.6244212),
 (33.7489924, -84.3902644),
 (44.9772995, -93.2654692),
 (25.7741728, -80.19362),
 (29.949932300000004, -90.0701156),
 (33.448436699999995, -112.07414170000001),
 (35.1490215, -90.0516285),
 (34.0536909, -118.24276599999999),
 (39.7392364, -104.98486229999999),
 (40.759619799999996, -111.88679750000001),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (43.6534817, -79.38393470000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (40.833989, -74.0970865),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (29.7589382, -95.36769740000001),
 (29.424600199999997, -98.4951405),
 (32.7762719, -96.7968559),
 (39.7392364, -104.98486229999999),
 (34.0536909, -118.24276599999999),
 (40.759619799999996, -111.88679750000001),
 (45.5202471, -122.6741949),
 (43.6534817, -79.38393470000001),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (39.9527237, -75.16352619999999),
 (40.7127281, -74.0060152),
 (33.448436699999995, -112.07414170000001),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (37.8546664, -122.2921365),
 (29.7589382, -95.36769740000001),
 (44.9772995, -93.2654692),
 (42.3602534, -71.0582912),
 (35.4729886, -97.5170536),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (29.424600199999997, -98.4951405),
 (33.7489924, -84.3902644),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (37.8546664, -122.2921365),
 (41.875561600000005, -87.6244212),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (35.1490215, -90.0516285),
 (42.3602534, -71.0582912),
 (32.7762719, -96.7968559),
 (39.7683331, -86.1583502),
 (39.7392364, -104.98486229999999),
 (41.5051613, -81.6934446),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (40.759619799999996, -111.88679750000001),
 (40.7127281, -74.0060152),
 (43.0349931, -87.92249699999999),
 (34.0536909, -118.24276599999999),
 (29.949932300000004, -90.0701156),
 (45.5202471, -122.6741949),
 (42.331550899999996, -83.04664029999999),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (33.7489924, -84.3902644),
 (43.0349931, -87.92249699999999),
 (40.759619799999996, -111.88679750000001),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (35.227208600000004, -80.84308270000001),
 (29.7589382, -95.36769740000001),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (40.833989, -74.0970865),
 (40.7127281, -74.0060152),
 (37.8546664, -122.2921365),
 (35.1490215, -90.0516285),
 (32.7762719, -96.7968559),
 (39.9527237, -75.16352619999999),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (29.424600199999997, -98.4951405),
 (38.5810606, -121.493895),
 (44.9772995, -93.2654692),
 (25.7741728, -80.19362),
 (42.3602534, -71.0582912),
 (41.875561600000005, -87.6244212),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (39.7392364, -104.98486229999999),
 (33.7489924, -84.3902644),
 (40.759619799999996, -111.88679750000001),
 (29.7589382, -95.36769740000001),
 (39.7683331, -86.1583502),
 (43.6534817, -79.38393470000001),
 (28.5421109, -81.3790304),
 (35.227208600000004, -80.84308270000001),
 (38.8949924, -77.0365581),
 (40.7127281, -74.0060152),
 (44.9772995, -93.2654692),
 (39.9527237, -75.16352619999999),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (38.5810606, -121.493895),
 (45.5202471, -122.6741949),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (42.331550899999996, -83.04664029999999),
 (35.227208600000004, -80.84308270000001),
 (40.759619799999996, -111.88679750000001),
 (40.833989, -74.0970865),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (39.7683331, -86.1583502),
 (25.7741728, -80.19362),
 (43.6534817, -79.38393470000001),
 (41.875561600000005, -87.6244212),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (35.1490215, -90.0516285),
 (45.5202471, -122.6741949),
 (29.949932300000004, -90.0701156),
 (43.0349931, -87.92249699999999),
 (37.8546664, -122.2921365),
 (39.9527237, -75.16352619999999),
 (29.424600199999997, -98.4951405),
 (33.7489924, -84.3902644),
 (44.9772995, -93.2654692),
 (42.331550899999996, -83.04664029999999),
 (38.5810606, -121.493895),
 (35.4729886, -97.5170536),
 (29.424600199999997, -98.4951405),
 (29.7589382, -95.36769740000001),
 (40.7127281, -74.0060152),
 (33.448436699999995, -112.07414170000001),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (35.227208600000004, -80.84308270000001),
 (35.1490215, -90.0516285),
 (28.5421109, -81.3790304),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (39.7392364, -104.98486229999999),
 (35.4729886, -97.5170536),
 (40.759619799999996, -111.88679750000001),
 (42.331550899999996, -83.04664029999999),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (40.833989, -74.0970865),
 (41.5051613, -81.6934446),
 (39.9527237, -75.16352619999999),
 (33.7489924, -84.3902644),
 (39.7683331, -86.1583502),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (45.5202471, -122.6741949),
 (35.1490215, -90.0516285),
 (34.0536909, -118.24276599999999),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (41.875561600000005, -87.6244212),
 (40.7127281, -74.0060152),
 (39.7392364, -104.98486229999999),
 (25.7741728, -80.19362),
 (33.448436699999995, -112.07414170000001),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (38.8949924, -77.0365581),
 (34.0536909, -118.24276599999999),
 (42.331550899999996, -83.04664029999999),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (35.4729886, -97.5170536),
 (40.833989, -74.0970865),
 (40.759619799999996, -111.88679750000001),
 (41.875561600000005, -87.6244212),
 (29.424600199999997, -98.4951405),
 (40.7127281, -74.0060152),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (39.7683331, -86.1583502),
 (33.448436699999995, -112.07414170000001),
 (28.5421109, -81.3790304),
 (45.5202471, -122.6741949),
 (39.7392364, -104.98486229999999),
 (42.3602534, -71.0582912),
 (35.4729886, -97.5170536),
 (39.9527237, -75.16352619999999),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (43.6534817, -79.38393470000001),
 (35.1490215, -90.0516285),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (35.227208600000004, -80.84308270000001),
 (34.0536909, -118.24276599999999),
 (44.9772995, -93.2654692),
 (41.5051613, -81.6934446),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (40.759619799999996, -111.88679750000001),
 (41.875561600000005, -87.6244212),
 (32.7762719, -96.7968559),
 (40.833989, -74.0970865),
 (38.5810606, -121.493895),
 (40.7127281, -74.0060152),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (35.227208600000004, -80.84308270000001),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (33.7489924, -84.3902644),
 (32.7762719, -96.7968559),
 (25.7741728, -80.19362),
 (35.1490215, -90.0516285),
 (43.0349931, -87.92249699999999),
 (35.4729886, -97.5170536),
 (41.5051613, -81.6934446),
 (29.424600199999997, -98.4951405),
 (40.833989, -74.0970865),
 (39.7392364, -104.98486229999999),
 (45.5202471, -122.6741949),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (40.7127281, -74.0060152),
 (42.3602534, -71.0582912),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (38.8949924, -77.0365581),
 (38.5810606, -121.493895),
 (29.949932300000004, -90.0701156),
 (34.0536909, -118.24276599999999),
 (37.8546664, -122.2921365),
 (42.3602534, -71.0582912),
 (33.7489924, -84.3902644),
 (25.7741728, -80.19362),
 (39.7683331, -86.1583502),
 (44.9772995, -93.2654692),
 (35.4729886, -97.5170536),
 (33.448436699999995, -112.07414170000001),
 (29.7589382, -95.36769740000001),
 (29.424600199999997, -98.4951405),
 (28.5421109, -81.3790304),
 (38.5810606, -121.493895),
 (40.759619799999996, -111.88679750000001),
 (39.7392364, -104.98486229999999),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (29.949932300000004, -90.0701156),
 (41.5051613, -81.6934446),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (33.7489924, -84.3902644),
 (39.9527237, -75.16352619999999),
 (38.8949924, -77.0365581),
 (40.7127281, -74.0060152),
 (35.227208600000004, -80.84308270000001),
 (42.331550899999996, -83.04664029999999),
 (32.7762719, -96.7968559),
 (34.0536909, -118.24276599999999),
 (41.875561600000005, -87.6244212),
 (40.7127281, -74.0060152),
 (35.227208600000004, -80.84308270000001),
 (41.5051613, -81.6934446),
 (43.0349931, -87.92249699999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (28.5421109, -81.3790304),
 (42.331550899999996, -83.04664029999999),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (29.424600199999997, -98.4951405),
 (35.4729886, -97.5170536),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (41.875561600000005, -87.6244212),
 (29.949932300000004, -90.0701156),
 (40.759619799999996, -111.88679750000001),
 (33.7489924, -84.3902644),
 (38.8949924, -77.0365581),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (29.7589382, -95.36769740000001),
 (35.227208600000004, -80.84308270000001),
 (41.5051613, -81.6934446),
 (28.5421109, -81.3790304),
 (42.3602534, -71.0582912),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (43.0349931, -87.92249699999999),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (35.4729886, -97.5170536),
 (39.7683331, -86.1583502),
 (32.7762719, -96.7968559),
 (29.424600199999997, -98.4951405),
 (41.875561600000005, -87.6244212),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (40.759619799999996, -111.88679750000001),
 (35.1490215, -90.0516285),
 (37.8546664, -122.2921365),
 (45.5202471, -122.6741949),
 (29.949932300000004, -90.0701156),
 (40.7127281, -74.0060152),
 (33.7489924, -84.3902644),
 (38.8949924, -77.0365581),
 (28.5421109, -81.3790304),
 (41.5051613, -81.6934446),
 (35.1490215, -90.0516285),
 (40.833989, -74.0970865),
 (39.9527237, -75.16352619999999),
 (44.9772995, -93.2654692),
 (37.8546664, -122.2921365),
 (25.7741728, -80.19362),
 (32.7762719, -96.7968559),
 (43.0349931, -87.92249699999999),
 (35.227208600000004, -80.84308270000001),
 (38.5810606, -121.493895),
 (41.875561600000005, -87.6244212),
 (43.6534817, -79.38393470000001),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (40.7127281, -74.0060152),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (34.0536909, -118.24276599999999),
 (40.759619799999996, -111.88679750000001),
 (45.5202471, -122.6741949),
 (40.833989, -74.0970865),
 (29.7589382, -95.36769740000001),
 (35.4729886, -97.5170536),
 (33.448436699999995, -112.07414170000001),
 (39.7392364, -104.98486229999999),
 (34.0536909, -118.24276599999999),
 (39.7683331, -86.1583502),
 (25.7741728, -80.19362),
 (38.8949924, -77.0365581),
 (29.949932300000004, -90.0701156),
 (35.4729886, -97.5170536),
 (29.7589382, -95.36769740000001),
 (32.7762719, -96.7968559),
 (43.0349931, -87.92249699999999),
 (40.759619799999996, -111.88679750000001),
 (42.3602534, -71.0582912),
 (41.5051613, -81.6934446),
 (42.331550899999996, -83.04664029999999),
 (28.5421109, -81.3790304),
 (45.5202471, -122.6741949),
 (39.9527237, -75.16352619999999),
 (40.833989, -74.0970865),
 (40.7127281, -74.0060152),
 (34.0536909, -118.24276599999999),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (39.7683331, -86.1583502),
 (29.424600199999997, -98.4951405),
 (37.8546664, -122.2921365),
 (33.7489924, -84.3902644),
 (35.1490215, -90.0516285),
 (40.833989, -74.0970865),
 (35.4729886, -97.5170536),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (42.3602534, -71.0582912),
 (45.5202471, -122.6741949),
 (25.7741728, -80.19362),
 (42.331550899999996, -83.04664029999999),
 (41.875561600000005, -87.6244212),
 (28.5421109, -81.3790304),
 (29.949932300000004, -90.0701156),
 (35.227208600000004, -80.84308270000001),
 (44.9772995, -93.2654692),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (34.0536909, -118.24276599999999),
 (43.0349931, -87.92249699999999),
 (39.7392364, -104.98486229999999),
 (39.7683331, -86.1583502),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (29.424600199999997, -98.4951405),
 (25.7741728, -80.19362),
 (41.5051613, -81.6934446),
 (33.448436699999995, -112.07414170000001),
 (37.8546664, -122.2921365),
 (40.833989, -74.0970865),
 (35.227208600000004, -80.84308270000001),
 (43.6534817, -79.38393470000001),
 (35.4729886, -97.5170536),
 (45.5202471, -122.6741949),
 (38.8949924, -77.0365581),
 (39.9527237, -75.16352619999999),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (28.5421109, -81.3790304),
 (42.3602534, -71.0582912),
 (41.875561600000005, -87.6244212),
 (29.7589382, -95.36769740000001),
 (35.1490215, -90.0516285),
 (40.7127281, -74.0060152),
 (29.949932300000004, -90.0701156),
 (44.9772995, -93.2654692),
 (29.424600199999997, -98.4951405),
 (34.0536909, -118.24276599999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (39.7683331, -86.1583502),
 (32.7762719, -96.7968559),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (25.7741728, -80.19362),
 (33.7489924, -84.3902644),
 (39.9527237, -75.16352619999999),
 (35.227208600000004, -80.84308270000001),
 (29.7589382, -95.36769740000001),
 (41.875561600000005, -87.6244212),
 (41.5051613, -81.6934446),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (28.5421109, -81.3790304),
 (38.5810606, -121.493895),
 (32.7762719, -96.7968559),
 (42.3602534, -71.0582912),
 (40.833989, -74.0970865),
 (40.7127281, -74.0060152),
 (43.6534817, -79.38393470000001),
 (41.5051613, -81.6934446),
 (42.331550899999996, -83.04664029999999),
 (35.4729886, -97.5170536),
 (37.8546664, -122.2921365),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (35.1490215, -90.0516285),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (38.8949924, -77.0365581),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (43.6534817, -79.38393470000001),
 (39.7683331, -86.1583502),
 (33.7489924, -84.3902644),
 (28.5421109, -81.3790304),
 (40.7127281, -74.0060152),
 (44.9772995, -93.2654692),
 (41.875561600000005, -87.6244212),
 (35.4729886, -97.5170536),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (35.1490215, -90.0516285),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),

In [28]:
time_zone_list = list = [obj.timezone_at(lng=k[1], lat=k[0]) for k in coordinates_list]
pl(time_zone_list)

20532

['America/New_York',
 'America/New_York',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Phoenix',
 'America/Denver',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Toronto',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Toronto',
 'America/Denver',
 'America/Phoenix',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Phoenix',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Denver',
 'America/Los_Angeles',
 'America/Toronto',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Phoenix',
 'America/New_York',
 'America/Detroit',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Denver',
 'America/Phoenix',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Denver',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Detroit',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Denver',
 'America/New_York',
 'America/Toronto',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Denver',
 'America/New_York',
 'America/Denver',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Detroit',
 'America/New_York',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/Toronto',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Detroit',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Denver',
 'America/Chicago',
 'America/Denver',
 'America/Detroit',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Toronto',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Denver',
 'America/New_York',
 'America/Phoenix',
 'America/New_York',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Detroit',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Denver',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Phoenix',
 'America/New_York',
 'America/Los_Angeles',
 'America/Denver',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Toronto',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Denver',
 'America/Los_Angeles',
 'America/Denver',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Detroit',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Detroit',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Denver',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Toronto',
 'America/New_York',
 'America/Detroit',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Denver',
 'America/Los_Angeles',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Denver',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/Detroit',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Denver',
 'America/Indiana/Indianapolis',
 'America/Denver',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Denver',
 'America/Phoenix',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/New_York',
 'America/Detroit',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Phoenix',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Toronto',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Detroit',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Denver',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Toronto',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Chicago',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/Chicago',
 'America/New_York',
 'America/Denver',
 'America/Los_Angeles',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Toronto',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Toronto',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/Denver',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/Detroit',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Denver',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/Toronto',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Denver',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Detroit',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Toronto',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Denver',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Phoenix',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Toronto',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Phoenix',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/New_York',
 'America/Chicago',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Denver',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/Los_Angeles',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Toronto',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Denver',
 'America/New_York',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Chicago',
 'America/Denver',
 'America/Los_Angeles',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',
 'America/New_York',
 'America/Chicago',

In [29]:
pl(game_coordinates_list)

20532

[(42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (32.7762719, -96.7968559),
 (32.7762719, -96.7968559),
 (29.7589382, -95.36769740000001),
 (29.7589382, -95.36769740000001),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (41.5051613, -81.6934446),
 (41.5051613, -81.6934446),
 (37.8546664, -122.2921365),
 (37.8546664, -122.2921365),
 (35.227208600000004, -80.84308270000001),
 (35.227208600000004, -80.84308270000001),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (38.8949924, -77.0365581),
 (38.8949924, -77.0365581),
 (33.7489924, -84.3902644),
 (33.7489924, -84.3902644),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (42.3602534, -71.0582912),
 (42.3602534, -71.0582912),
 (35.1490215, -90.0516285),
 (35.1490215, -90.0516285),
 (29.949932300000004, -90.0701156),
 (29.949932300000004, -90.0701156),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),
 (25.7741728, -80.19362),
 (25.7741728, -80.19362),
 (39.9527237, -75.16352619999999),
 (39.9527237, -75.16352619999999),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (44.9772995, -93.2654692),
 (44.9772995, -93.2654692),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (38.5810606, -121.493895),
 (38.5810606, -121.493895),
 (40.833989, -74.0970865),
 (40.833989, -74.0970865),
 (43.6534817, -79.38393470000001),
 (43.6534817, -79.38393470000001),
 (42.331550899999996, -83.04664029999999),
 (42.331550899999996, -83.04664029999999),
 (35.4729886, -97.5170536),
 (35.4729886, -97.5170536),
 (29.424600199999997, -98.4951405),
 (29.424600199999997, -98.4951405),
 (39.7392364, -104.98486229999999),
 (39.7392364, -104.98486229999999),
 (33.448436699999995, -112.07414170000001),
 (33.448436699999995, -112.07414170000001),
 (45.5202471, -122.6741949),
 (45.5202471, -122.6741949),
 (39.7683331, -86.1583502),
 (39.7683331, -86.1583502),
 (28.5421109, -81.3790304),
 (28.5421109, -81.3790304),
 (40.7127281, -74.0060152),
 (40.7127281, -74.0060152),
 (41.875561600000005, -87.6244212),
 (41.875561600000005, -87.6244212),
 (43.0349931, -87.92249699999999),
 (43.0349931, -87.92249699999999),
 (40.759619799999996, -111.88679750000001),
 (40.759619799999996, -111.88679750000001),
 (34.0536909, -118.24276599999999),
 (34.0536909, -118.24276599999999),

In [30]:
game_time_zone_list = list = [obj.timezone_at(lng=k[1], lat=k[0]) for k in game_coordinates_list]
pl(game_time_zone_list)

20532

['America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/Phoenix',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Denver',
 'America/Denver',
 'America/Phoenix',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Phoenix',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Phoenix',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Phoenix',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Toronto',
 'America/Toronto',
 'America/Detroit',
 'America/Detroit',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Phoenix',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Phoenix',
 'America/Phoenix',
 'America/Denver',
 'America/Denver',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Toronto',
 'America/Toronto',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Phoenix',
 'America/Phoenix',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Phoenix',
 'America/Phoenix',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Phoenix',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Phoenix',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Phoenix',
 'America/Phoenix',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Denver',
 'America/Denver',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/Detroit',
 'America/Detroit',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Toronto',
 'America/Toronto',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Phoenix',
 'America/Phoenix',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Chicago',
 'America/Chicago',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/Los_Angeles',
 'America/New_York',
 'America/New_York',
 'America/Indiana/Indianapolis',
 'America/Indiana/Indianapolis',
 'America/New_York',
 'America/New_York',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Denver',
 'America/Denver',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/New_York',
 'America/Detroit',
 'America/Detroit',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',
 'America/Chicago',

In [31]:
df_game_time_zone = pd.DataFrame({'game_time_zone':game_time_zone_list})
p(df_game_time_zone)

(20532, 1)

            game_time_zone
0         America/New_York
1         America/New_York
2      America/Los_Angeles
3      America/Los_Angeles
4      America/Los_Angeles
20527  America/Los_Angeles
20528     America/New_York
20529     America/New_York
20530     America/New_York
20531     America/New_York

In [32]:
df_giti = pd.concat([df_giti, df_game_time_zone], axis=1)
p(df_giti)

(20532, 65)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York

In [33]:
df_time_zone = pd.DataFrame({'time_zone':time_zone_list})
p(df_time_zone)

(20532, 1)

                 time_zone
0         America/New_York
1         America/New_York
2          America/Phoenix
3      America/Los_Angeles
4          America/Chicago
20527  America/Los_Angeles
20528     America/New_York
20529  America/Los_Angeles
20530     America/New_York
20531  America/Los_Angeles

In [34]:
df_giti = pd.concat([df_giti, df_time_zone], axis=1)
p(df_giti)

(20532, 66)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles

In [35]:
from pytz import timezone
import pandas as pd

def tz_diff(date, tz1, tz2):
    '''
    Returns the difference in hours between timezone1 and timezone2
    for a given date.
    '''
    date = pd.to_datetime(date)
    return (tz1.localize(date) - 
            tz2.localize(date).astimezone(tz1))\
            .seconds/3600 + (tz1.localize(date) - 
            tz2.localize(date).astimezone(tz1))\
            .days * 24

In [36]:
team_city_time_zone = timezone('America/New_York')
game_team_city_time_zone = timezone('America/Chicago')

tz_diff('2017-06-01', team_city_time_zone, game_team_city_time_zone)

-1.0

In [37]:
time_zone_diff_list = [tz_diff('06-06-06', timezone(k1), timezone(k2)) for k1, k2 in zip(time_zone_list, game_time_zone_list)]
pl(time_zone_diff_list)

20532

[0.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 3.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 -2.0,
 -2.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -2.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -2.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 -3.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 1.0,
 2.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 -1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 -2.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 -1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 2.0,
 -1.0,
 0.0,
 0.0,
 1.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 -1.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 3.0,
 0.0,
 3.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 -3.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -1.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -2.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 -1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 3.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -3.0,
 -2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 2.0,
 -1.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -3.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -2.0,
 -2.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 -3.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 -1.0,
 -3.0,
 0.0,
 0.0,
 2.0,
 0.0,
 1.0,
 3.0,
 0.0,
 -1.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 1.0,
 0.0,
 -1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 -2.0,
 -2.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 1.0,
 -2.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 0.0,
 -2.0,
 -2.0,
 0.0,
 0.0,
 -2.0,
 1.0,
 0.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 -1.0,
 0.0,
 0.0,
 1.0,
 -2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -2.0,
 -3.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -1.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 2.0,
 0.0,
 -1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -3.0,
 -2.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 1.0,
 0.0,
 3.0,
 0.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 -1.0,
 -1.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 -3.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 3.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 -1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -3.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 0.0,
 -2.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 1.0,
 ...]

In [38]:
df_time_zone_diff = pd.DataFrame({'time_zone_diff':time_zone_diff_list})
p(df_time_zone_diff)

(20532, 1)

       time_zone_diff
0                 0.0
1                 0.0
2                 0.0
3                 0.0
4                -2.0
20527             0.0
20528             0.0
20529             3.0
20530             0.0
20531             3.0

In [39]:
df_giti = pd.concat([df_giti, df_time_zone_diff], axis=1)
p(df_giti)

(20532, 67)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0

In [43]:
df_giti['time_zone_diff_abs'] = abs(df_giti.time_zone_diff)
df_giti = df_giti.sort_values(['game_date', 'game_id'])
df_giti = df_giti.reset_index(drop=True)
p(df_giti)

(20532, 68)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0

<font color='red'> travel_distance is not literally 0 for the home team, should an adjustment be made here???</font>

In [44]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '63_travel_distance_time_zone_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_giti.to_csv(datapath_df, index=False)

In [45]:
df_63_travel_distance_time_zone_diff_2010_2018_readback = rcp('63_travel_distance_time_zone_diff_2010_2018.csv')
p(df_63_travel_distance_time_zone_diff_2010_2018_readback)

(20532, 68)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0