In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
''' distance_longitude_latitude101.py
given the longitudes and latitudes of two cities, calculate the distance

Uses the Haversine Formula recommended for calculating short
distances by NASA's Jet Propulsion Laboratory.  For longer
distances this formula tends to overestimate trans-polar distances and
underestimate trans-equatorial distances.

tested with Python27 and Python34  by  vegaseat  19jan2015
'''

from math import radians, cos, sin, asin, sqrt

def haversine(lon1, lat1, lon2, lat2):
    '''
    calculate the great circle distance between two points
    on the Earth (coordinates specified in decimal degrees)
    '''
    # convert decimal degrees to radians
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))

    # 6367 km (3961 miles) is the radius of the Earth
    km = 6367 * c
    miles = 3961 * c
    return km, miles


# Detroit, Michigan  48235
city1 = "Detroit"
lat1  = 42.4261
lon1 = -83.1951

# Chicago, Illinois  60290
city2 = "Chicago"
lat2  = 41.9613
lon2 = -87.8849

km, miles = haversine(lon1, lat1, lon2, lat2)

sf = "The distance between {} and {} is {:0.1f} miles (air)"
print(sf.format(city1, city2, miles))

''' result ...
The distance between Detroit and Chicago is 242.3 miles (air)
'''

The distance between Detroit and Chicago is 242.3 miles (air)

' result ...\nThe distance between Detroit and Chicago is 242.3 miles (air)\n'

In [3]:
!pip install geopy

Requirement already satisfied: geopy in /opt/anaconda3/lib/python3.8/site-packages (2.2.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /opt/anaconda3/lib/python3.8/site-packages (from geopy) (1.52)

In [4]:
!pip install Nominatim

Requirement already satisfied: Nominatim in /opt/anaconda3/lib/python3.8/site-packages (0.1)

In [5]:
from geopy.geocoders import Nominatim
address='Nagpur'
geolocator = Nominatim(user_agent="Your_Name")
location = geolocator.geocode(address)
print(location.address)
print((location.latitude, location.longitude))

Nagpur Urban Taluka, Nagpur District, Maharashtra, India
(21.1498134, 79.0820556)

In [6]:
from geopy.geocoders import Nominatim
address='Chicago'
geolocator = Nominatim(user_agent="Your_Name")
location = geolocator.geocode(address)
print(location.address)
print((location.latitude, location.longitude))

Chicago, Cook County, Illinois, United States
(41.8755616, -87.6244212)

In [7]:
df = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv', ['game_date'])
df = df.sort_values(['game_date', 'game_id'])
#df = df.reset_index()
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,BOS vs. CLE,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010,L,W,-8,8
5,21000005,2010-10-27,Pistons,DET,Detroit,240:00,0 days 04:00:00,Nets,NJN,New Jersey,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,DET vs. NJN,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,Regular Season,2010-11,2010,L,W,-3,3
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [8]:
df_giti = f.wide2tall(df, ['game_id', 'team_id'], ['_away', '_home'])
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [9]:
#fix #fix indiana to indianapolis

#fix utah to salt lake city

#fix new jersey to East Rutherford


df.loc[df.TEAM_CITY_away.str.contains('Indiana'), 'TEAM_CITY_away'] = 'Indianapolis'
df.loc[df.TEAM_CITY_away.str.contains('Utah'), 'TEAM_CITY_away'] = 'Salt Lake City'
df.loc[df.TEAM_CITY_away.str.contains('New Jersey'), 'TEAM_CITY_away'] = 'East Rutherford'
df.loc[df.TEAM_CITY_away.str.contains('Minnesota'), 'TEAM_CITY_away'] = 'Minneapolis'

df.loc[df.TEAM_CITY_home.str.contains('Indiana'), 'TEAM_CITY_home'] = 'Indianapolis'
df.loc[df.TEAM_CITY_home.str.contains('Utah'), 'TEAM_CITY_home'] = 'Salt Lake City'
df.loc[df.TEAM_CITY_home.str.contains('New Jersey'), 'TEAM_CITY_home'] = 'East Rutherford'
df.loc[df.TEAM_CITY_home.str.contains('Minnesota'), 'TEAM_CITY_home'] = 'Minneapolis'

In [10]:
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
4,21000004,2010-10-27,Celtics,BOS,Boston,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,BOS vs. CLE,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,Regular Season,2010-11,2010,L,W,-8,8
5,21000005,2010-10-27,Pistons,DET,Detroit,240:00,0 days 04:00:00,Nets,NJN,East Rutherford,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,DET vs. NJN,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,Regular Season,2010-11,2010,L,W,-3,3
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [11]:
df_team_city = df.TEAM_CITY_away
p(df_team_city)

(10266,)

0               Miami
1             Phoenix
2             Houston
4              Boston
5             Detroit
10261    Golden State
10262       Cleveland
10263       Cleveland
10264    Golden State
10265    Golden State
Name: TEAM_CITY_away, dtype: object

In [12]:
city_name_list = list((df_team_city).value_counts().index)
pl(city_name_list)

30

['Los Angeles',
 'San Antonio',
 'Miami',
 'Golden State',
 'Oklahoma City',
 'Cleveland',
 'Boston',
 'Indianapolis',
 'Memphis',
 'Atlanta',
 'Houston',
 'Chicago',
 'Toronto',
 'Portland',
 'Dallas',
 'Washington',
 'Philadelphia',
 'Salt Lake City',
 'Milwaukee',
 'New York',
 'New Orleans',
 'Denver',
 'Orlando',
 'Charlotte',
 'Minneapolis',
 'Detroit',
 'Phoenix',
 'Sacramento',
 'Brooklyn',
 'East Rutherford']

In [13]:
latitude = []
longitude = []

for city_ in city_name_list:
    address = city_
    geolocator = Nominatim(user_agent="Your_Name")
    location = geolocator.geocode(address)
    print(location.address)
    print((location.latitude, location.longitude))
    latitude = latitude + [location.latitude]
    longitude = longitude + [location.longitude]

Los Angeles, California, United States
(34.0536909, -118.242766)
San Antonio, Bexar County, Texas, United States
(29.4246002, -98.4951405)
Miami, Miami-Dade County, Florida, United States
(25.7741728, -80.19362)
Golden state, Seventh Street, San Pablo Park, Berkeley, Alameda County, California, 94710, United States
(37.8546664, -122.2921365)
Oklahoma City, Oklahoma County, Oklahoma, United States
(35.4729886, -97.5170536)
Cleveland, Cuyahoga County, Ohio, United States
(41.5051613, -81.6934446)
Boston, Suffolk County, Massachusetts, United States
(42.3602534, -71.0582912)
Indianapolis, Marion, Indiana, United States
(39.7683331, -86.1583502)
Memphis, Shelby County, Tennessee, United States
(35.1490215, -90.0516285)
Atlanta, Fulton County, Georgia, United States
(33.7489924, -84.3902644)
Houston, Harris County, Texas, United States
(29.7589382, -95.3676974)
Chicago, Cook County, Illinois, United States
(41.8755616, -87.6244212)
Toronto, Golden Horseshoe, Ontario, Canada
(43.6534817, -79.3839347)
Portland, Multnomah County, Oregon, United States
(45.5202471, -122.6741949)
Dallas, Dallas County, Texas, United States
(32.7762719, -96.7968559)
Washington, District of Columbia, United States
(38.8949924, -77.0365581)
Philadelphia, Philadelphia County, Pennsylvania, United States
(39.9527237, -75.1635262)
Salt Lake City, Salt Lake County, Utah, United States
(40.7596198, -111.8867975)
Milwaukee, Milwaukee County, Wisconsin, United States
(43.0349931, -87.922497)
New York, United States
(40.7127281, -74.0060152)
New Orleans, Orleans Parish, Louisiana, United States
(29.9499323, -90.0701156)
Denver, Denver County, Colorado, United States
(39.7392364, -104.9848623)
Orlando, Orange County, Florida, United States
(28.5421109, -81.3790304)
Charlotte, Mecklenburg County, North Carolina, United States
(35.2272086, -80.8430827)
Minneapolis, Hennepin County, Minnesota, United States
(44.9772995, -93.2654692)
Detroit, Wayne County, Michigan, United States
(42.3315509, -83.0466403)
Phoenix, Maricopa County, Arizona, United States
(33.4484367, -112.0741417)
Sacramento, Sacramento County, California, United States
(38.5810606, -121.493895)
Brooklyn, Kings County, New York, United States
(40.6501038, -73.9495823)
East Rutherford, Bergen County, New Jersey, 07073, United States
(40.833989, -74.0970865)

In [16]:
df_city_name_latitude_longitude = pd.DataFrame(list(zip(city_name_list, latitude, longitude)),
                                               columns = ['TEAM_CITY', 'latitude', 'longitude'])
df_city_name_latitude_longitude

          TEAM_CITY   latitude   longitude
0       Los Angeles  34.053691 -118.242766
1       San Antonio  29.424600  -98.495141
2             Miami  25.774173  -80.193620
3      Golden State  37.854666 -122.292136
4     Oklahoma City  35.472989  -97.517054
5         Cleveland  41.505161  -81.693445
6            Boston  42.360253  -71.058291
7      Indianapolis  39.768333  -86.158350
8           Memphis  35.149022  -90.051629
9           Atlanta  33.748992  -84.390264
10          Houston  29.758938  -95.367697
11          Chicago  41.875562  -87.624421
12          Toronto  43.653482  -79.383935
13         Portland  45.520247 -122.674195
14           Dallas  32.776272  -96.796856
15       Washington  38.894992  -77.036558
16     Philadelphia  39.952724  -75.163526
17   Salt Lake City  40.759620 -111.886798
18        Milwaukee  43.034993  -87.922497
19         New York  40.712728  -74.006015
20      New Orleans  29.949932  -90.070116
21           Denver  39.739236 -104.984862
22          Orlando  28.542111  -81.379030
23        Charlotte  35.227209  -80.843083
24      Minneapolis  44.977300  -93.265469
25          Detroit  42.331551  -83.046640
26          Phoenix  33.448437 -112.074142
27       Sacramento  38.581061 -121.493895
28         Brooklyn  40.650104  -73.949582
29  East Rutherford  40.833989  -74.097087

In [17]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '62_team_city_latitude_longitude_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_city_name_latitude_longitude.to_csv(datapath_df, index=False)

In [18]:
df_62_travel_schedule_origin_2010_2018_readback = rcp('62_team_city_latitude_longitude_2010_2018.csv')
p(df_62_travel_schedule_origin_2010_2018_readback)

(30, 3)

          TEAM_CITY   latitude   longitude
0       Los Angeles  34.053691 -118.242766
1       San Antonio  29.424600  -98.495141
2             Miami  25.774173  -80.193620
3      Golden State  37.854666 -122.292136
4     Oklahoma City  35.472989  -97.517054
25          Detroit  42.331551  -83.046640
26          Phoenix  33.448437 -112.074142
27       Sacramento  38.581061 -121.493895
28         Brooklyn  40.650104  -73.949582
29  East Rutherford  40.833989  -74.097087