In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f



def feature_engineer(df_, group_by_columns_, column_features_, operators_, window_size_, shift_num_=1):
    
    '''
    example operators: 'max', 'min', 'count', 'median', 'mean'
    '''
    df_.groupby([group_by_columns_])\
           [column_features_]\
           .rolling(window_size_,1).agg([operators_])\
           .shift(shift_num_)

In [2]:
df_71C_merge_71A_71B_2010_2018 = \
rcp('71C_merge_71A_71B_2010_2018.csv')

p(df_71C_merge_71A_71B_2010_2018)

(20532, 134)

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (71,72) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

,game_id,team_id,index,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999,_merge
0,21000001,1610612748,0,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854,both
1,21000001,1610612738,1,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505,both
2,21000002,1610612756,2,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000,both
3,21000002,1610612757,3,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000,both
4,21000003,1610612745,4,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000,both
20527,41700402,1610612744,20527,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631,3 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,both
20528,41700403,1610612739,20528,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,3 days,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,both
20529,41700403,1610612744,20529,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631,3 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,both
20530,41700404,1610612739,20530,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,2 days,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,both
20531,41700404,1610612744,20531,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631,2 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,both

In [3]:
df_71C_merge_71A_71B_2010_2018.loc[:, ['time_zone_diff', 'time_zone_diff_abs']] = \
df_71C_merge_71A_71B_2010_2018.loc[:, ['time_zone_diff', 'time_zone_diff_abs']].astype('int64')

p(df_71C_merge_71A_71B_2010_2018)

(20532, 134)

,game_id,team_id,index,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999,_merge
0,21000001,1610612748,0,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854,both
1,21000001,1610612738,1,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505,both
2,21000002,1610612756,2,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000,both
3,21000002,1610612757,3,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Portland,United States,164.419,158.5,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000,both
4,21000003,1610612745,4,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000,both
20527,41700402,1610612744,20527,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,both
20528,41700403,1610612739,20528,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,3 days,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,both
20529,41700403,1610612744,20529,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,3 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,both
20530,41700404,1610612739,20530,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,2 days,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,both
20531,41700404,1610612744,20531,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,2 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,both

In [4]:
#fill difference between games for the first game of the season as 9 (i.e. previous col max) for each team
df_71C_merge_71A_71B_2010_2018.game_date_diff = \
df_71C_merge_71A_71B_2010_2018.game_date_diff.str.extract('(\d+)')


df_71C_merge_71A_71B_2010_2018.game_date_diff.fillna('9', inplace=True)


df_71C_merge_71A_71B_2010_2018.game_date_diff = \
df_71C_merge_71A_71B_2010_2018.game_date_diff.astype('int64')


p(df_71C_merge_71A_71B_2010_2018.game_date_diff)

(20532,)

0        9
1        9
2        9
3        9
4        9
20527    3
20528    3
20529    3
20530    2
20531    2
Name: game_date_diff, dtype: int64

In [5]:
list(df_71C_merge_71A_71B_2010_2018.columns)

['game_id',
 'team_id',
 'index',
 'TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'duration',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'wl',
 'spread',
 'away_home_',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'latitude',
 'longitude',
 'game_latitude',
 'game_longitude',
 'travel_distance',
 'game_time_zone',
 'time_zone',
 'time_zone_diff',
 'time_zone_diff_abs',
 'city_proper_metro_area',
 'Country/Region',
 'city_proper_metro_area_GDP_bil',
 'city_proper_metro_area_GDP_bil1',
 'game_date_diff',
 'game_date_diff1',
 'games_back_to_back_count_game_window2',
 'games_back_to_back_count_game_window5',
 'games_back_to_back_count_game_window12',
 'games_back_to_back_count_game_window999',
 'games_back_to_back_percentage_game_window2',
 'games_back_to_back_percentage_game_window5',
 'games_back_to_back_percentage_game_window12',
 'games_back_to_back_percentage_game_window999',
 'away_game_count_day_window2',
 'home_game_count_day_window2',
 'game_count_day_window2',
 'away_game_percent_day_window2',
 'home_game_percent_day_window2',
 'away_game_count_day_window5',
 'home_game_count_day_window5',
 'game_count_day_window5',
 'away_game_percent_day_window5',
 'home_game_percent_day_window5',
 'away_game_count_day_window8',
 'home_game_count_day_window8',
 'game_count_day_window8',
 'away_game_percent_day_window8',
 'home_game_percent_day_window8',
 'away_game_count_day_window12',
 'home_game_count_day_window12',
 'game_count_day_window12',
 'away_game_percent_day_window12',
 'home_game_percent_day_window12',
 'away_game_count_day_window999',
 'home_game_count_day_window999',
 'game_count_day_window999',
 'away_game_percent_day_window999',
 'home_game_percent_day_window999',
 'future_away_game_count_day_window2',
 'future_home_game_count_day_window2',
 'future_game_count_day_window2',
 'future_away_game_percent_day_window2',
 'future_home_game_percent_day_window2',
 'future_away_game_count_day_window5',
 'future_home_game_count_day_window5',
 'future_game_count_day_window5',
 'future_away_game_percent_day_window5',
 'future_home_game_percent_day_window5',
 'future_away_game_count_day_window8',
 'future_home_game_count_day_window8',
 'future_game_count_day_window8',
 'future_away_game_percent_day_window8',
 'future_home_game_percent_day_window8',
 'future_away_game_count_day_window12',
 'future_home_game_count_day_window12',
 'future_game_count_day_window12',
 'future_away_game_percent_day_window12',
 'future_home_game_percent_day_window12',
 'future_away_game_count_day_window999',
 'future_home_game_count_day_window999',
 'future_game_count_day_window999',
 'future_away_game_percent_day_window999',
 'future_home_game_percent_day_window999',
 '_merge']

In [6]:
column_drop_list = ['index',
 'TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'duration',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'wl',
 'spread',                    
 'matchup',
 'season_type',
 'season_year',
 '_merge']
pl(column_drop_list)

56

['index',
 'TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'duration',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'wl',
 'spread',
 'matchup',
 'season_type',
 'season_year',
 '_merge']

In [7]:
df_71C_merge_71A_71B_2010_2018.drop(columns=column_drop_list, inplace=True)

In [8]:
p(df_71C_merge_71A_71B_2010_2018)

(20532, 78)

,game_id,team_id,away_home_,game_date,season,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999
0,21000001,1610612748,0,2010-10-26,2010-11,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
1,21000001,1610612738,1,2010-10-26,2010-11,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505
2,21000002,1610612756,0,2010-10-26,2010-11,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000
3,21000002,1610612757,1,2010-10-26,2010-11,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Portland,United States,164.419,158.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
4,21000003,1610612745,0,2010-10-26,2010-11,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000
20527,41700402,1610612744,1,2018-06-03,2017-18,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333
20528,41700403,1610612739,1,2018-06-06,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,3,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000
20529,41700403,1610612744,0,2018-06-06,2017-18,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
20530,41700404,1610612739,1,2018-06-08,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,2,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000
20531,41700404,1610612744,0,2018-06-08,2017-18,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000

In [9]:
df_71C_merge_71A_71B_2010_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20532 entries, 0 to 20531
Data columns (total 78 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   game_id                                       20532 non-null  int64
 1   team_id                                       20532 non-null  int64
 2   away_home_                                    20532 non-null  int64
 3   game_date                                     20532 non-null  object
 4   season                                        20532 non-null  object
 5   latitude                                      20532 non-null  float64
 6   longitude                                     20532 non-null  float64
 7   game_latitude                                 20532 non-null  float64
 8   game_longitude                                20532 non-null  float64
 9   travel_distance                               20532 non-null  float64
 10  game_time_zone                                20532 non-null  object
 11  time_zone                                     20532 non-null  object
 12  time_zone_diff                                20532 non-null  int64
 13  time_zone_diff_abs                            20532 non-null  int64
 14  city_proper_metro_area                        20532 non-null  object
 15  Country/Region                                20532 non-null  object
 16  city_proper_metro_area_GDP_bil                20532 non-null  object
 17  city_proper_metro_area_GDP_bil1               20532 non-null  object
 18  game_date_diff                                20532 non-null  int64
 19  game_date_diff1                               20532 non-null  int64
 20  games_back_to_back_count_game_window2         20532 non-null  float64
 21  games_back_to_back_count_game_window5         20532 non-null  float64
 22  games_back_to_back_count_game_window12        20532 non-null  float64
 23  games_back_to_back_count_game_window999       20532 non-null  float64
 24  games_back_to_back_percentage_game_window2    20532 non-null  float64
 25  games_back_to_back_percentage_game_window5    20532 non-null  float64
 26  games_back_to_back_percentage_game_window12   20532 non-null  float64
 27  games_back_to_back_percentage_game_window999  20532 non-null  float64
 28  away_game_count_day_window2                   20532 non-null  float64
 29  home_game_count_day_window2                   20532 non-null  float64
 30  game_count_day_window2                        20532 non-null  float64
 31  away_game_percent_day_window2                 20532 non-null  float64
 32  home_game_percent_day_window2                 20532 non-null  float64
 33  away_game_count_day_window5                   20532 non-null  float64
 34  home_game_count_day_window5                   20532 non-null  float64
 35  game_count_day_window5                        20532 non-null  float64
 36  away_game_percent_day_window5                 20532 non-null  float64
 37  home_game_percent_day_window5                 20532 non-null  float64
 38  away_game_count_day_window8                   20532 non-null  float64
 39  home_game_count_day_window8                   20532 non-null  float64
 40  game_count_day_window8                        20532 non-null  float64
 41  away_game_percent_day_window8                 20532 non-null  float64
 42  home_game_percent_day_window8                 20532 non-null  float64
 43  away_game_count_day_window12                  20532 non-null  float64
 44  home_game_count_day_window12                  20532 non-null  float64
 45  game_count_day_window12                       20532 non-null  float64
 46  away_game_percent_day_window12                20532 non-null  float64
 47  home_game_percent_day_window12                20532 non-null  float64
 48  away_game_count_day_window999                 20532 non-null  float64
 49  home_game_count_day_window999                 20532 non-null  float64
 50  game_count_day_window999                      20532 non-null  float64
 51  away_game_percent_day_window999               20532 non-null  float64
 52  home_game_percent_day_window999               20532 non-null  float64
 53  future_away_game_count_day_window2            20532 non-null  float64
 54  future_home_game_count_day_window2            20532 non-null  float64
 55  future_game_count_day_window2                 20532 non-null  float64
 56  future_away_game_percent_day_window2          20532 non-null  float64
 57  future_home_game_percent_day_window2          20532 non-null  float64
 58  future_away_game_count_day_window5            20532 non-null  float64
 59  future_home_game_count_day_window5            20532 non-null  float64
 60  future_game_count_day_window5                 20532 non-null  float64
 61  future_away_game_percent_day_window5          20532 non-null  float64
 62  future_home_game_percent_day_window5          20532 non-null  float64
 63  future_away_game_count_day_window8            20532 non-null  float64
 64  future_home_game_count_day_window8            20532 non-null  float64
 65  future_game_count_day_window8                 20532 non-null  float64
 66  future_away_game_percent_day_window8          20532 non-null  float64
 67  future_home_game_percent_day_window8          20532 non-null  float64
 68  future_away_game_count_day_window12           20532 non-null  float64
 69  future_home_game_count_day_window12           20532 non-null  float64
 70  future_game_count_day_window12                20532 non-null  float64
 71  future_away_game_percent_day_window12         20532 non-null  float64
 72  future_home_game_percent_day_window12         20532 non-null  float64
 73  future_away_game_count_day_window999          20532 non-null  float64
 74  future_home_game_count_day_window999          20532 non-null  float64
 75  future_game_count_day_window999               20532 non-null  float64
 76  future_away_game_percent_day_window999        20532 non-null  float64
 77  future_home_game_percent_day_window999        20532 non-null  float64
dtypes: float64(63), int64(7), object(8)
memory usage: 12.2+ MB

In [10]:
help(f.get_numeric_diff)

Help on function get_numeric_diff in module my_functions:

get_numeric_diff(df_, groupby_list_, not_difference_list_, suffix_list_)

In [11]:
help(f.tall2wide2)

Help on function tall2wide2 in module my_functions:

tall2wide2(df_, not_first_second_list_, indicator_column_, keep_indicator_=False, first_second_column_suffix_=None)

In [12]:
p(df_71C_merge_71A_71B_2010_2018)

(20532, 78)

,game_id,team_id,away_home_,game_date,season,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999
0,21000001,1610612748,0,2010-10-26,2010-11,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
1,21000001,1610612738,1,2010-10-26,2010-11,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505
2,21000002,1610612756,0,2010-10-26,2010-11,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000
3,21000002,1610612757,1,2010-10-26,2010-11,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Portland,United States,164.419,158.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
4,21000003,1610612745,0,2010-10-26,2010-11,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000
20527,41700402,1610612744,1,2018-06-03,2017-18,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333
20528,41700403,1610612739,1,2018-06-06,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,3,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000
20529,41700403,1610612744,0,2018-06-06,2017-18,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
20530,41700404,1610612739,1,2018-06-08,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,2,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000
20531,41700404,1610612744,0,2018-06-08,2017-18,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000

In [13]:
df_56game_id_team_id_a_b_matchup_a_b_2010_2018 = \
rcp('56game_id_team_id_a_b_matchup_a_b_2010_2018.csv')

p(df_56game_id_team_id_a_b_matchup_a_b_2010_2018)

(20532, 17)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,team_id,w_pct,wl,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b
0,21000001,Heat,MIA,Miami,1610612748,0.0,L,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0
1,21000001,Celtics,BOS,Boston,1610612738,1.0,W,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0
2,21000002,Suns,PHX,Phoenix,1610612756,0.0,L,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0
3,21000002,Trail Blazers,POR,Portland,1610612757,1.0,W,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0
4,21000003,Rockets,HOU,Houston,1610612745,0.0,L,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0
20527,41700402,Warriors,GSW,Golden State,1610612744,1.0,W,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20528,41700403,Warriors,GSW,Golden State,1610612744,1.0,W,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,1610612739,0.0,L,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0
20530,41700404,Warriors,GSW,Golden State,1610612744,1.0,W,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,1610612739,0.0,L,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0

In [14]:
df_71C_merge_71A_71B_2010_2018 = pd.merge(df_56game_id_team_id_a_b_matchup_a_b_2010_2018.\
                                          loc[:, ['game_id', 'team_id', '_a']],
                                          df_71C_merge_71A_71B_2010_2018,
                                          on=['game_id', 'team_id'])
p(df_71C_merge_71A_71B_2010_2018)

(20532, 79)

,game_id,team_id,_a,away_home_,game_date,season,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999
0,21000001,1610612748,0.0,0,2010-10-26,2010-11,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
1,21000001,1610612738,1.0,1,2010-10-26,2010-11,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505
2,21000002,1610612756,1.0,0,2010-10-26,2010-11,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000
3,21000002,1610612757,0.0,1,2010-10-26,2010-11,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Portland,United States,164.419,158.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
4,21000003,1610612745,1.0,0,2010-10-26,2010-11,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000
20527,41700402,1610612744,0.0,1,2018-06-03,2017-18,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333
20528,41700403,1610612744,0.0,0,2018-06-06,2017-18,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
20529,41700403,1610612739,1.0,1,2018-06-06,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,3,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000
20530,41700404,1610612744,0.0,0,2018-06-08,2017-18,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000
20531,41700404,1610612739,1.0,1,2018-06-08,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,2,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000

In [15]:
df_71C_merge_71A_71B_2010_2018.loc[:, '_a'] = \
abs(df_71C_merge_71A_71B_2010_2018.loc[:, '_a'] - 1)

p(df_71C_merge_71A_71B_2010_2018.loc[:, '_a'])

(20532,)

0        1.0
1        0.0
2        0.0
3        1.0
4        0.0
20527    1.0
20528    1.0
20529    0.0
20530    1.0
20531    0.0
Name: _a, dtype: float64

In [16]:
###########give me arguments please
df_71C_merge_71A_71B_2010_2018_wide = \
f.tall2wide2(df_71C_merge_71A_71B_2010_2018,
             ['game_id', 'game_date', 'season'],
             '_a')

p(df_71C_merge_71A_71B_2010_2018_wide)

(10266, 153)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,team_id_a,away_home__a,game_date,season,latitude_a,longitude_a,game_latitude_a,game_longitude_a,travel_distance_a,game_time_zone_a,time_zone_a,time_zone_diff_a,time_zone_diff_abs_a,city_proper_metro_area_a,Country/Region_a,city_proper_metro_area_GDP_bil_a,city_proper_metro_area_GDP_bil1_a,game_date_diff_a,game_date_diff1_a,games_back_to_back_count_game_window2_a,games_back_to_back_count_game_window5_a,games_back_to_back_count_game_window12_a,games_back_to_back_count_game_window999_a,games_back_to_back_percentage_game_window2_a,games_back_to_back_percentage_game_window5_a,games_back_to_back_percentage_game_window12_a,games_back_to_back_percentage_game_window999_a,away_game_count_day_window2_a,home_game_count_day_window2_a,game_count_day_window2_a,away_game_percent_day_window2_a,home_game_percent_day_window2_a,away_game_count_day_window5_a,home_game_count_day_window5_a,game_count_day_window5_a,away_game_percent_day_window5_a,home_game_percent_day_window5_a,away_game_count_day_window8_a,home_game_count_day_window8_a,game_count_day_window8_a,away_game_percent_day_window8_a,home_game_percent_day_window8_a,away_game_count_day_window12_a,home_game_count_day_window12_a,game_count_day_window12_a,away_game_percent_day_window12_a,home_game_percent_day_window12_a,away_game_count_day_window999_a,home_game_count_day_window999_a,game_count_day_window999_a,away_game_percent_day_window999_a,home_game_percent_day_window999_a,future_away_game_count_day_window2_a,future_home_game_count_day_window2_a,future_game_count_day_window2_a,future_away_game_percent_day_window2_a,future_home_game_percent_day_window2_a,future_away_game_count_day_window5_a,future_home_game_count_day_window5_a,future_game_count_day_window5_a,future_away_game_percent_day_window5_a,future_home_game_percent_day_window5_a,future_away_game_count_day_window8_a,future_home_game_count_day_window8_a,future_game_count_day_window8_a,future_away_game_percent_day_window8_a,future_home_game_percent_day_window8_a,future_away_game_count_day_window12_a,future_home_game_count_day_window12_a,future_game_count_day_window12_a,future_away_game_percent_day_window12_a,future_home_game_percent_day_window12_a,future_away_game_count_day_window999_a,future_home_game_count_day_window999_a,future_game_count_day_window999_a,future_away_game_percent_day_window999_a,future_home_game_percent_day_window999_a,team_id_b,away_home__b,latitude_b,longitude_b,game_latitude_b,game_longitude_b,travel_distance_b,game_time_zone_b,time_zone_b,time_zone_diff_b,time_zone_diff_abs_b,city_proper_metro_area_b,Country/Region_b,city_proper_metro_area_GDP_bil_b,city_proper_metro_area_GDP_bil1_b,game_date_diff_b,game_date_diff1_b,games_back_to_back_count_game_window2_b,games_back_to_back_count_game_window5_b,games_back_to_back_count_game_window12_b,games_back_to_back_count_game_window999_b,games_back_to_back_percentage_game_window2_b,games_back_to_back_percentage_game_window5_b,games_back_to_back_percentage_game_window12_b,games_back_to_back_percentage_game_window999_b,away_game_count_day_window2_b,home_game_count_day_window2_b,game_count_day_window2_b,away_game_percent_day_window2_b,home_game_percent_day_window2_b,away_game_count_day_window5_b,home_game_count_day_window5_b,game_count_day_window5_b,away_game_percent_day_window5_b,home_game_percent_day_window5_b,away_game_count_day_window8_b,home_game_count_day_window8_b,game_count_day_window8_b,away_game_percent_day_window8_b,home_game_percent_day_window8_b,away_game_count_day_window12_b,home_game_count_day_window12_b,game_count_day_window12_b,away_game_percent_day_window12_b,home_game_percent_day_window12_b,away_game_count_day_window999_b,home_game_count_day_window999_b,game_count_day_window999_b,away_game_percent_day_window999_b,home_game_percent_day_window999_b,future_away_game_count_day_window2_b,future_home_game_count_day_window2_b,future_game_count_day_window2_b,future_away_game_percent_day_window2_b,future_home_game_percent_day_window2_b,future_away_game_count_day_window5_b,future_home_game_count_day_window5_b,future_game_count_day_window5_b,future_away_game_percent_day_window5_b,future_home_game_percent_day_window5_b,future_away_game_count_day_window8_b,future_home_game_count_day_window8_b,future_game_count_day_window8_b,future_away_game_percent_day_window8_b,future_home_game_percent_day_window8_b,future_away_game_count_day_window12_b,future_home_game_count_day_window12_b,future_game_count_day_window12_b,future_away_game_percent_day_window12_b,future_home_game_percent_day_window12_b,future_away_game_count_day_window999_b,future_home_game_count_day_window999_b,future_game_count_day_window999_b,future_away_game_percent_day_window999_b,future_home_game_percent_day_window999_b
0,21000001,1610612738,1,2010-10-26,2010-11,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505,1610612748,0,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
1,21000002,1610612756,0,2010-10-26,2010-11,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000,1610612757,1,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Portland,United States,164.419,158.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
2,21000003,1610612745,0,2010-10-26,2010-11,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000,1610612747,1,34.053691,-118.242766,34.053691,-118.242766,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Los Angeles,United States,"1,048","1,528.27",9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,1.0,3.0,4.0,0.250000,0.750000,2.0,4.0,6.0,0.333333,0.666667,46.0,46.0,92.0,0.500000,0.500000
3,21000006,1610612748,0,2010-10-27,2010-11,25.774173,-80.193620,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,1,1,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.00,0.00,2.0,0.0,2.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,3.0,3.0,6.0,0.500000,0.500000,50.0,52.0,102.0,0.490196,0.509804,1610612755,1,39.952724,-75.163526,39.952724,-75.163526,0.000000,America/New_York,America/New_York,0,0,Philadelphia,United States,444.148,746.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.400000,0.600000,3.0,4.0,7.0,0.428571,0.571429,44.0,43.0,87.0,0.505747,0.494253
4,21000005,1610612765,0,2010-10-27,2010-11,42.331551,-83.046640,40.833989,-74.097087,473.715215,America/New_York,America/Detroit,0,0,Detroit,United States,267.731,407.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,3.0,4.0,7.0,0.428571,0.571429,41.0,41.0,82.0,0.500000,0.500000,1610612751,1,40.833989,-74.097087,40.833989,-74.097087,0.000000,America/New_York,America/New_York,0,0,New York,United States,"1,732","1,803",9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,0.0,3.0,3.0,0.000000,1.000000,0.0,4.0,4.0,0.000000,1.000000,2.0,4.0,6.0,0.333333,0.666667,41.0,41.0,82.0,0.500000,0.500000
10261,41700317,1610612744,0,2018-05-28,2017-18,37.854666,-122.292136,29.758938,-95.367697,1636.798262,America/Chicago,America/Los_Angeles,2,2,San Francisco,United States,995,631,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.141414,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,2.0,3.0,5.0,0.40,0.60,49.0,50.0,99.0,0.494949,0.505051,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,3.0,2.0,5.0,0.600000,0.400000,3.0,2.0,5.0,0.600000,0.400000,1610612745,1,29.758938,-95.367697,29.758938,-95.367697,0.000000,America/Chicago,America/Chicago,0,0,Houston,United States,478.778,883.2,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.141414,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,3.0,2.0,5.0,0.600000,0.400000,48.0,51.0,99.0,0.484848,0.515152,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000
10262,41700401,1610612739,0,2018-05-31,2017-18,41.505161,-81.693445,37.854666,-122.292136,2153.640745,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135,215.1,4,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.128713,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,50.0,101.0,0.504950,0.495050,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,2.0,2.0,4.0,0.500000,0.500000,1610612744,1,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.140000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,49.0,51.0,100.0,0.490000,0.510000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,2.0,4.0,0.500000,0.500000
10263,41700402,1610612739,0,2018-06-03,2017-18,41.505161,-81.693445,37.854666,-122.292136,2153.640745,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135,215.1,3,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.127451,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,3.0,0.0,3.0,1.000000,0.000000,4.0,1.0,5.0,0.80,0.20,52.0,50.0,102.0,0.509804,0.490196,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667,1610612744,1,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.400000,0.600000,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333
10264,41700403,1610612739,1,2018-06-06,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,3,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,1610612744,0,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.400000,0.600000,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
10265,41700404,1610612739,1,2018-06-08,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,2,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,1610612744,0,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000

In [17]:
column_underscore_away_list = \
[k for k in df_71C_merge_71A_71B_2010_2018_wide.columns if '_away' in k]

pl(column_underscore_away_list)

20

['future_away_game_count_day_window2_a',
 'future_away_game_percent_day_window2_a',
 'future_away_game_count_day_window5_a',
 'future_away_game_percent_day_window5_a',
 'future_away_game_count_day_window8_a',
 'future_away_game_percent_day_window8_a',
 'future_away_game_count_day_window12_a',
 'future_away_game_percent_day_window12_a',
 'future_away_game_count_day_window999_a',
 'future_away_game_percent_day_window999_a',
 'future_away_game_count_day_window2_b',
 'future_away_game_percent_day_window2_b',
 'future_away_game_count_day_window5_b',
 'future_away_game_percent_day_window5_b',
 'future_away_game_count_day_window8_b',
 'future_away_game_percent_day_window8_b',
 'future_away_game_count_day_window12_b',
 'future_away_game_percent_day_window12_b',
 'future_away_game_count_day_window999_b',
 'future_away_game_percent_day_window999_b']

In [18]:
column_underscore_Away_list = \
[k.split('_away')[0] + '_Away' + k.split('_away')[1] for k in column_underscore_away_list]

pl(column_underscore_Away_list)

20

['future_Away_game_count_day_window2_a',
 'future_Away_game_percent_day_window2_a',
 'future_Away_game_count_day_window5_a',
 'future_Away_game_percent_day_window5_a',
 'future_Away_game_count_day_window8_a',
 'future_Away_game_percent_day_window8_a',
 'future_Away_game_count_day_window12_a',
 'future_Away_game_percent_day_window12_a',
 'future_Away_game_count_day_window999_a',
 'future_Away_game_percent_day_window999_a',
 'future_Away_game_count_day_window2_b',
 'future_Away_game_percent_day_window2_b',
 'future_Away_game_count_day_window5_b',
 'future_Away_game_percent_day_window5_b',
 'future_Away_game_count_day_window8_b',
 'future_Away_game_percent_day_window8_b',
 'future_Away_game_count_day_window12_b',
 'future_Away_game_percent_day_window12_b',
 'future_Away_game_count_day_window999_b',
 'future_Away_game_percent_day_window999_b']

In [19]:
column_underscore_away_Away_dict = dict(zip(column_underscore_away_list, column_underscore_Away_list))
pdc(column_underscore_away_Away_dict)

20

{'future_away_game_count_day_window2_a': 'future_Away_game_count_day_window2_a',
 'future_away_game_percent_day_window2_a': 'future_Away_game_percent_day_window2_a',
 'future_away_game_count_day_window5_a': 'future_Away_game_count_day_window5_a',
 'future_away_game_percent_day_window5_a': 'future_Away_game_percent_day_window5_a',
 'future_away_game_count_day_window8_a': 'future_Away_game_count_day_window8_a',
 'future_away_game_percent_day_window8_a': 'future_Away_game_percent_day_window8_a',
 'future_away_game_count_day_window12_a': 'future_Away_game_count_day_window12_a',
 'future_away_game_percent_day_window12_a': 'future_Away_game_percent_day_window12_a',
 'future_away_game_count_day_window999_a': 'future_Away_game_count_day_window999_a',
 'future_away_game_percent_day_window999_a': 'future_Away_game_percent_day_window999_a',
 'future_away_game_count_day_window2_b': 'future_Away_game_count_day_window2_b',
 'future_away_game_percent_day_window2_b': 'future_Away_game_percent_day_window2_b',
 'future_away_game_count_day_window5_b': 'future_Away_game_count_day_window5_b',
 'future_away_game_percent_day_window5_b': 'future_Away_game_percent_day_window5_b',
 'future_away_game_count_day_window8_b': 'future_Away_game_count_day_window8_b',
 'future_away_game_percent_day_window8_b': 'future_Away_game_percent_day_window8_b',
 'future_away_game_count_day_window12_b': 'future_Away_game_count_day_window12_b',
 'future_away_game_percent_day_window12_b': 'future_Away_game_percent_day_window12_b',
 'future_away_game_count_day_window999_b': 'future_Away_game_count_day_window999_b',
 'future_away_game_percent_day_window999_b': 'future_Away_game_percent_day_window999_b'}

In [20]:
df_71C_merge_71A_71B_2010_2018_wide.rename(columns=column_underscore_away_Away_dict, inplace=True)
p(df_71C_merge_71A_71B_2010_2018_wide)

(10266, 153)

,game_id,team_id_a,away_home__a,game_date,season,latitude_a,longitude_a,game_latitude_a,game_longitude_a,travel_distance_a,game_time_zone_a,time_zone_a,time_zone_diff_a,time_zone_diff_abs_a,city_proper_metro_area_a,Country/Region_a,city_proper_metro_area_GDP_bil_a,city_proper_metro_area_GDP_bil1_a,game_date_diff_a,game_date_diff1_a,games_back_to_back_count_game_window2_a,games_back_to_back_count_game_window5_a,games_back_to_back_count_game_window12_a,games_back_to_back_count_game_window999_a,games_back_to_back_percentage_game_window2_a,games_back_to_back_percentage_game_window5_a,games_back_to_back_percentage_game_window12_a,games_back_to_back_percentage_game_window999_a,away_game_count_day_window2_a,home_game_count_day_window2_a,game_count_day_window2_a,away_game_percent_day_window2_a,home_game_percent_day_window2_a,away_game_count_day_window5_a,home_game_count_day_window5_a,game_count_day_window5_a,away_game_percent_day_window5_a,home_game_percent_day_window5_a,away_game_count_day_window8_a,home_game_count_day_window8_a,game_count_day_window8_a,away_game_percent_day_window8_a,home_game_percent_day_window8_a,away_game_count_day_window12_a,home_game_count_day_window12_a,game_count_day_window12_a,away_game_percent_day_window12_a,home_game_percent_day_window12_a,away_game_count_day_window999_a,home_game_count_day_window999_a,game_count_day_window999_a,away_game_percent_day_window999_a,home_game_percent_day_window999_a,future_Away_game_count_day_window2_a,future_home_game_count_day_window2_a,future_game_count_day_window2_a,future_Away_game_percent_day_window2_a,future_home_game_percent_day_window2_a,future_Away_game_count_day_window5_a,future_home_game_count_day_window5_a,future_game_count_day_window5_a,future_Away_game_percent_day_window5_a,future_home_game_percent_day_window5_a,future_Away_game_count_day_window8_a,future_home_game_count_day_window8_a,future_game_count_day_window8_a,future_Away_game_percent_day_window8_a,future_home_game_percent_day_window8_a,future_Away_game_count_day_window12_a,future_home_game_count_day_window12_a,future_game_count_day_window12_a,future_Away_game_percent_day_window12_a,future_home_game_percent_day_window12_a,future_Away_game_count_day_window999_a,future_home_game_count_day_window999_a,future_game_count_day_window999_a,future_Away_game_percent_day_window999_a,future_home_game_percent_day_window999_a,team_id_b,away_home__b,latitude_b,longitude_b,game_latitude_b,game_longitude_b,travel_distance_b,game_time_zone_b,time_zone_b,time_zone_diff_b,time_zone_diff_abs_b,city_proper_metro_area_b,Country/Region_b,city_proper_metro_area_GDP_bil_b,city_proper_metro_area_GDP_bil1_b,game_date_diff_b,game_date_diff1_b,games_back_to_back_count_game_window2_b,games_back_to_back_count_game_window5_b,games_back_to_back_count_game_window12_b,games_back_to_back_count_game_window999_b,games_back_to_back_percentage_game_window2_b,games_back_to_back_percentage_game_window5_b,games_back_to_back_percentage_game_window12_b,games_back_to_back_percentage_game_window999_b,away_game_count_day_window2_b,home_game_count_day_window2_b,game_count_day_window2_b,away_game_percent_day_window2_b,home_game_percent_day_window2_b,away_game_count_day_window5_b,home_game_count_day_window5_b,game_count_day_window5_b,away_game_percent_day_window5_b,home_game_percent_day_window5_b,away_game_count_day_window8_b,home_game_count_day_window8_b,game_count_day_window8_b,away_game_percent_day_window8_b,home_game_percent_day_window8_b,away_game_count_day_window12_b,home_game_count_day_window12_b,game_count_day_window12_b,away_game_percent_day_window12_b,home_game_percent_day_window12_b,away_game_count_day_window999_b,home_game_count_day_window999_b,game_count_day_window999_b,away_game_percent_day_window999_b,home_game_percent_day_window999_b,future_Away_game_count_day_window2_b,future_home_game_count_day_window2_b,future_game_count_day_window2_b,future_Away_game_percent_day_window2_b,future_home_game_percent_day_window2_b,future_Away_game_count_day_window5_b,future_home_game_count_day_window5_b,future_game_count_day_window5_b,future_Away_game_percent_day_window5_b,future_home_game_percent_day_window5_b,future_Away_game_count_day_window8_b,future_home_game_count_day_window8_b,future_game_count_day_window8_b,future_Away_game_percent_day_window8_b,future_home_game_percent_day_window8_b,future_Away_game_count_day_window12_b,future_home_game_count_day_window12_b,future_game_count_day_window12_b,future_Away_game_percent_day_window12_b,future_home_game_percent_day_window12_b,future_Away_game_count_day_window999_b,future_home_game_count_day_window999_b,future_game_count_day_window999_b,future_Away_game_percent_day_window999_b,future_home_game_percent_day_window999_b
0,21000001,1610612738,1,2010-10-26,2010-11,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505,1610612748,0,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
1,21000002,1610612756,0,2010-10-26,2010-11,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000,1610612757,1,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Portland,United States,164.419,158.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
2,21000003,1610612745,0,2010-10-26,2010-11,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000,1610612747,1,34.053691,-118.242766,34.053691,-118.242766,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,Los Angeles,United States,"1,048","1,528.27",9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,1.0,3.0,4.0,0.250000,0.750000,2.0,4.0,6.0,0.333333,0.666667,46.0,46.0,92.0,0.500000,0.500000
3,21000006,1610612748,0,2010-10-27,2010-11,25.774173,-80.193620,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,1,1,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.00,0.00,2.0,0.0,2.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,3.0,3.0,6.0,0.500000,0.500000,50.0,52.0,102.0,0.490196,0.509804,1610612755,1,39.952724,-75.163526,39.952724,-75.163526,0.000000,America/New_York,America/New_York,0,0,Philadelphia,United States,444.148,746.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.400000,0.600000,3.0,4.0,7.0,0.428571,0.571429,44.0,43.0,87.0,0.505747,0.494253
4,21000005,1610612765,0,2010-10-27,2010-11,42.331551,-83.046640,40.833989,-74.097087,473.715215,America/New_York,America/Detroit,0,0,Detroit,United States,267.731,407.5,9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,3.0,4.0,7.0,0.428571,0.571429,41.0,41.0,82.0,0.500000,0.500000,1610612751,1,40.833989,-74.097087,40.833989,-74.097087,0.000000,America/New_York,America/New_York,0,0,New York,United States,"1,732","1,803",9,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,0.0,3.0,3.0,0.000000,1.000000,0.0,4.0,4.0,0.000000,1.000000,2.0,4.0,6.0,0.333333,0.666667,41.0,41.0,82.0,0.500000,0.500000
10261,41700317,1610612744,0,2018-05-28,2017-18,37.854666,-122.292136,29.758938,-95.367697,1636.798262,America/Chicago,America/Los_Angeles,2,2,San Francisco,United States,995,631,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.141414,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,2.0,3.0,5.0,0.40,0.60,49.0,50.0,99.0,0.494949,0.505051,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,3.0,2.0,5.0,0.600000,0.400000,3.0,2.0,5.0,0.600000,0.400000,1610612745,1,29.758938,-95.367697,29.758938,-95.367697,0.000000,America/Chicago,America/Chicago,0,0,Houston,United States,478.778,883.2,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.141414,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,3.0,2.0,5.0,0.600000,0.400000,48.0,51.0,99.0,0.484848,0.515152,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000
10262,41700401,1610612739,0,2018-05-31,2017-18,41.505161,-81.693445,37.854666,-122.292136,2153.640745,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135,215.1,4,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.128713,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,50.0,101.0,0.504950,0.495050,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,2.0,2.0,4.0,0.500000,0.500000,1610612744,1,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.140000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,49.0,51.0,100.0,0.490000,0.510000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,2.0,4.0,0.500000,0.500000
10263,41700402,1610612739,0,2018-06-03,2017-18,41.505161,-81.693445,37.854666,-122.292136,2153.640745,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135,215.1,3,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.127451,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,3.0,0.0,3.0,1.000000,0.000000,4.0,1.0,5.0,0.80,0.20,52.0,50.0,102.0,0.509804,0.490196,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667,1.0,2.0,3.0,0.333333,0.666667,1610612744,1,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0,0,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.400000,0.600000,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333
10264,41700403,1610612739,1,2018-06-06,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,3,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,1610612744,0,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,3,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.500000,0.500000,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.400000,0.600000,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
10265,41700404,1610612739,1,2018-06-08,2017-18,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,2,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,1610612744,0,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3,3,San Francisco,United States,995,631,2,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000

In [21]:
def get_numeric_diff(df_, groupby_list_, not_difference_list_, suffix_list_):
    
    column_names_numeric_list_ = list(df_.select_dtypes('number').columns)
    
    column_names_numeric_list_cleaned_ = [k for k in column_names_numeric_list_
                                          if (not k in not_difference_list_)]
    
    column_names_first_second_list_ = [k.split(suffix_list_[0])[0]
                                       for k in column_names_numeric_list_cleaned_
                                       if k.endswith(suffix_list_[0])]
    
    column_names_first_second_list_rgl_ = [k for k in column_names_first_second_list_
                                           if not k in groupby_list_]

    column_names_first_second_list_rgl_first_ = [k + suffix_list_[0] \
                                                 for k in column_names_first_second_list_rgl_]
    
    column_names_first_second_list_rgl_second_ = [k + suffix_list_[1] \
                                                  for k in column_names_first_second_list_rgl_]
    
    column_names_first_second_list_rgl_diff_ = [k + '_diff' \
                                                for k in column_names_first_second_list_rgl_]
    
    #return len(column_names_first_second_list_rgl_first_), len(column_names_first_second_list_rgl_second_), len(column_names_first_second_list_rgl_diff_)
    
    
    df_[column_names_first_second_list_rgl_diff_] = df_[column_names_first_second_list_rgl_first_]\
                                                        .fillna(0).values - \
                                                        df_[column_names_first_second_list_rgl_second_]\
                                                        .fillna(0)
    
    column_names_drop_ = column_names_first_second_list_rgl_first_ + column_names_first_second_list_rgl_second_
    
    df_.drop(columns = column_names_drop_, inplace=True)    
    
    #return df_[column_names_first_second_list_rgl_first_]
    
    #return df_[column_names_first_second_list_rgl_second_]
    
    return df_

In [22]:
###########give me arguments please
df_differences = \
get_numeric_diff(df_71C_merge_71A_71B_2010_2018_wide.drop(columns=['time_zone_diff_b', 'time_zone_diff_abs_b']),
                 ['team_id', 'season'],
                 ['game_id', 'game_date', 'season', 
                  'season_type', 'season_year', 'time_zone_diff_a', 
                  'time_zone_diff_abs_a'],
                 ['_a', '_b'])

p(df_differences)

(10266, 85)

,game_id,team_id_a,game_date,season,game_time_zone_a,time_zone_a,time_zone_diff_a,time_zone_diff_abs_a,city_proper_metro_area_a,Country/Region_a,city_proper_metro_area_GDP_bil_a,city_proper_metro_area_GDP_bil1_a,team_id_b,game_time_zone_b,time_zone_b,city_proper_metro_area_b,Country/Region_b,city_proper_metro_area_GDP_bil_b,city_proper_metro_area_GDP_bil1_b,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff
0,21000001,1610612738,2010-10-26,2010-11,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,1610612748,America/New_York,America/New_York,Miami,United States,377.5,262.7,1.0,16.586081,9.135329,0.0,0.0,-1257.755091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.5,0.5,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,-2.0,1.0,-1.0,-0.238095,0.238095,-5.0,-7.0,-12.0,0.010349,-0.010349
1,21000002,1610612756,2010-10-26,2010-11,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,1610612757,America/Los_Angeles,America/Los_Angeles,Portland,United States,164.419,158.5,-1.0,-12.071810,10.600053,0.0,0.0,1005.606855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,0.0,-1.0,-1.0,0.5,-0.5,0.0,0.0,0.0,0.000000,0.000000,-2.0,0.0,-2.0,-0.133333,0.133333,-2.0,0.0,-2.0,-0.171429,0.171429,-3.0,-3.0,-6.0,0.000000,0.000000
2,21000003,1610612745,2010-10-26,2010-11,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,1610612747,America/Los_Angeles,America/Los_Angeles,Los Angeles,United States,"1,048","1,528.27",-1.0,-4.294753,22.875069,0.0,0.0,1371.020326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,2.0,-1.0,1.0,1.0,-1.0,1.0,0.0,1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.416667,-0.416667,1.0,-2.0,-1.0,0.266667,-0.266667,-5.0,-5.0,-10.0,0.000000,0.000000
3,21000006,1610612748,2010-10-27,2010-11,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,1610612755,America/New_York,America/New_York,Philadelphia,United States,444.148,746.5,-1.0,-14.178551,-5.030094,0.0,0.0,1021.727021,-8.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,-1.0,1.0,1.0,-1.0,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,-1.0,-1.0,0.100000,-0.100000,0.0,-1.0,-1.0,0.071429,-0.071429,6.0,9.0,15.0,-0.015551,0.015551
4,21000005,1610612765,2010-10-27,2010-11,America/New_York,America/Detroit,0,0,Detroit,United States,267.731,407.5,1610612751,America/New_York,America/New_York,New York,United States,"1,732","1,803",-1.0,1.497562,-8.949554,0.0,0.0,473.715215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,0.666667,-0.666667,3.0,-2.0,1.0,0.600000,-0.600000,1.0,0.0,1.0,0.095238,-0.095238,0.0,0.0,0.0,0.000000,0.000000
10261,41700317,1610612744,2018-05-28,2017-18,America/Chicago,America/Los_Angeles,2,2,San Francisco,United States,995,631,1610612745,America/Chicago,America/Chicago,Houston,United States,478.778,883.2,-1.0,8.095728,-26.924439,0.0,0.0,1636.798262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.200000,0.200000,1.0,-1.0,0.0,0.010101,-0.010101,1.0,-1.0,0.0,1.0,-1.0,1.0,0.0,1.0,0.500000,-0.500000,1.0,1.0,2.0,0.333333,-0.333333,3.0,1.0,4.0,0.600000,-0.600000,3.0,1.0,4.0,0.600000,-0.600000
10262,41700401,1610612739,2018-05-31,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135,215.1,1610612744,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995,631,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011287,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.500000,-0.500000,0.0,-1.0,-1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.266667,-0.266667,2.0,-1.0,1.0,0.014950,-0.014950,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
10263,41700402,1610612739,2018-06-03,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135,215.1,1610612744,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995,631,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011163,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,2.0,-2.0,0.0,0.666667,-0.666667,2.0,-2.0,0.0,0.400000,-0.400000,3.0,-2.0,1.0,0.024655,-0.024655,1.0,-1.0,0.0,1.0,-1.0,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333
10264,41700403,1610612739,2018-06-06,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,1610612744,America/New_York,America/Los_Angeles,San Francisco,United States,995,631,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011041,-1.0,1.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.000000,0.000000,1.0,-1.0,0.0,0.333333,-0.333333,1.0,-2.0,-1.0,0.350000,-0.350000,2.0,-1.0,1.0,0.014658,-0.014658,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000
10265,41700404,1610612739,2018-06-08,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135,215.1,1610612744,America/New_York,America/Los_Angeles,San Francisco,United States,995,631,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.010922,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,1.0,0.0,1.0,0.004854,-0.004854,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000

In [23]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '72_71C_schedule_location_differences_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_differences.to_csv(datapath_df, index=False)

In [24]:
df_72_71C_schedule_location_differences_2010_2018_readback = \
rcp('72_71C_schedule_location_differences_2010_2018.csv')

p(df_72_71C_schedule_location_differences_2010_2018_readback)

(10266, 85)

,game_id,team_id_a,game_date,season,game_time_zone_a,time_zone_a,time_zone_diff_a,time_zone_diff_abs_a,city_proper_metro_area_a,Country/Region_a,city_proper_metro_area_GDP_bil_a,city_proper_metro_area_GDP_bil1_a,team_id_b,game_time_zone_b,time_zone_b,city_proper_metro_area_b,Country/Region_b,city_proper_metro_area_GDP_bil_b,city_proper_metro_area_GDP_bil1_b,away_home__diff,latitude_diff,longitude_diff,game_latitude_diff,game_longitude_diff,travel_distance_diff,game_date_diff_diff,game_date_diff1_diff,games_back_to_back_count_game_window2_diff,games_back_to_back_count_game_window5_diff,games_back_to_back_count_game_window12_diff,games_back_to_back_count_game_window999_diff,games_back_to_back_percentage_game_window2_diff,games_back_to_back_percentage_game_window5_diff,games_back_to_back_percentage_game_window12_diff,games_back_to_back_percentage_game_window999_diff,away_game_count_day_window2_diff,home_game_count_day_window2_diff,game_count_day_window2_diff,away_game_percent_day_window2_diff,home_game_percent_day_window2_diff,away_game_count_day_window5_diff,home_game_count_day_window5_diff,game_count_day_window5_diff,away_game_percent_day_window5_diff,home_game_percent_day_window5_diff,away_game_count_day_window8_diff,home_game_count_day_window8_diff,game_count_day_window8_diff,away_game_percent_day_window8_diff,home_game_percent_day_window8_diff,away_game_count_day_window12_diff,home_game_count_day_window12_diff,game_count_day_window12_diff,away_game_percent_day_window12_diff,home_game_percent_day_window12_diff,away_game_count_day_window999_diff,home_game_count_day_window999_diff,game_count_day_window999_diff,away_game_percent_day_window999_diff,home_game_percent_day_window999_diff,future_Away_game_count_day_window2_diff,future_home_game_count_day_window2_diff,future_game_count_day_window2_diff,future_Away_game_percent_day_window2_diff,future_home_game_percent_day_window2_diff,future_Away_game_count_day_window5_diff,future_home_game_count_day_window5_diff,future_game_count_day_window5_diff,future_Away_game_percent_day_window5_diff,future_home_game_percent_day_window5_diff,future_Away_game_count_day_window8_diff,future_home_game_count_day_window8_diff,future_game_count_day_window8_diff,future_Away_game_percent_day_window8_diff,future_home_game_percent_day_window8_diff,future_Away_game_count_day_window12_diff,future_home_game_count_day_window12_diff,future_game_count_day_window12_diff,future_Away_game_percent_day_window12_diff,future_home_game_percent_day_window12_diff,future_Away_game_count_day_window999_diff,future_home_game_count_day_window999_diff,future_game_count_day_window999_diff,future_Away_game_percent_day_window999_diff,future_home_game_percent_day_window999_diff
0,21000001,1610612738,2010-10-26,2010-11,America/New_York,America/New_York,0,0,Boston,United States,463.570,560.1,1610612748,America/New_York,America/New_York,Miami,United States,377.5,262.7,1.0,16.586081,9.135329,0.0,0.0,-1257.755091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.5,0.5,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,-2.0,1.0,-1.0,-0.238095,0.238095,-5.0,-7.0,-12.0,0.010349,-0.010349
1,21000002,1610612756,2010-10-26,2010-11,America/Los_Angeles,America/Phoenix,0,0,Phoenix,United States,255.211,607.1,1610612757,America/Los_Angeles,America/Los_Angeles,Portland,United States,164.419,158.5,-1.0,-12.071810,10.600053,0.0,0.0,1005.606855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,0.0,-1.0,-1.0,0.5,-0.5,0.0,0.0,0.0,0.000000,0.000000,-2.0,0.0,-2.0,-0.133333,0.133333,-2.0,0.0,-2.0,-0.171429,0.171429,-3.0,-3.0,-6.0,0.000000,0.000000
2,21000003,1610612745,2010-10-26,2010-11,America/Los_Angeles,America/Chicago,-2,2,Houston,United States,478.778,883.2,1610612747,America/Los_Angeles,America/Los_Angeles,Los Angeles,United States,"1,048","1,528.27",-1.0,-4.294753,22.875069,0.0,0.0,1371.020326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,2.0,-1.0,1.0,1.0,-1.0,1.0,0.0,1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.416667,-0.416667,1.0,-2.0,-1.0,0.266667,-0.266667,-5.0,-5.0,-10.0,0.000000,0.000000
3,21000006,1610612748,2010-10-27,2010-11,America/New_York,America/New_York,0,0,Miami,United States,377.5,262.7,1610612755,America/New_York,America/New_York,Philadelphia,United States,444.148,746.5,-1.0,-14.178551,-5.030094,0.0,0.0,1021.727021,-8.0,1.0,1.0,1.0,1.0,1.0,0.5,0.5,0.5,0.500000,2.0,-1.0,1.0,1.0,-1.0,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,2.0,-1.0,1.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,-1.0,-1.0,0.100000,-0.100000,0.0,-1.0,-1.0,0.071429,-0.071429,6.0,9.0,15.0,-0.015551,0.015551
4,21000005,1610612765,2010-10-27,2010-11,America/New_York,America/Detroit,0,0,Detroit,United States,267.731,407.5,1610612751,America/New_York,America/New_York,New York,United States,"1,732","1,803",-1.0,1.497562,-8.949554,0.0,0.0,473.715215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,0.666667,-0.666667,3.0,-2.0,1.0,0.600000,-0.600000,1.0,0.0,1.0,0.095238,-0.095238,0.0,0.0,0.0,0.000000,0.000000
10261,41700317,1610612744,2018-05-28,2017-18,America/Chicago,America/Los_Angeles,2,2,San Francisco,United States,995.0,631.0,1610612745,America/Chicago,America/Chicago,Houston,United States,478.778,883.2,-1.0,8.095728,-26.924439,0.0,0.0,1636.798262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.200000,0.200000,1.0,-1.0,0.0,0.010101,-0.010101,1.0,-1.0,0.0,1.0,-1.0,1.0,0.0,1.0,0.500000,-0.500000,1.0,1.0,2.0,0.333333,-0.333333,3.0,1.0,4.0,0.600000,-0.600000,3.0,1.0,4.0,0.600000,-0.600000
10262,41700401,1610612739,2018-05-31,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135.0,215.1,1610612744,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011287,1.0,-1.0,0.0,1.0,-1.0,1.0,-1.0,0.0,0.500000,-0.500000,0.0,-1.0,-1.0,0.166667,-0.166667,1.0,-2.0,-1.0,0.266667,-0.266667,2.0,-1.0,1.0,0.014950,-0.014950,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,1.0,-1.0,0.0,0.333333,-0.333333,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
10263,41700402,1610612739,2018-06-03,2017-18,America/Los_Angeles,America/New_York,-3,3,Cleveland,United States,135.0,215.1,1610612744,America/Los_Angeles,America/Los_Angeles,San Francisco,United States,995.0,631.0,-1.0,3.650495,40.598692,0.0,0.0,2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011163,1.0,-1.0,0.0,1.0,-1.0,2.0,-2.0,0.0,1.000000,-1.000000,2.0,-2.0,0.0,0.666667,-0.666667,2.0,-2.0,0.0,0.400000,-0.400000,3.0,-2.0,1.0,0.024655,-0.024655,1.0,-1.0,0.0,1.0,-1.0,0.0,0.0,0.0,0.000000,0.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,1.0,0.0,-0.333333,0.333333
10264,41700403,1610612739,2018-06-06,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135.0,215.1,1610612744,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.011041,-1.0,1.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.000000,0.000000,1.0,-1.0,0.0,0.333333,-0.333333,1.0,-2.0,-1.0,0.350000,-0.350000,2.0,-1.0,1.0,0.014658,-0.014658,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000,-2.0,2.0,0.0,-1.000000,1.000000
10265,41700404,1610612739,2018-06-08,2017-18,America/New_York,America/New_York,0,0,Cleveland,United States,135.0,215.1,1610612744,America/New_York,America/Los_Angeles,San Francisco,United States,995.0,631.0,1.0,3.650495,40.598692,0.0,0.0,-2153.640745,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-0.010922,-1.0,1.0,0.0,-1.0,1.0,-2.0,2.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-0.333333,0.333333,-1.0,0.0,-1.0,-0.100000,0.100000,1.0,0.0,1.0,0.004854,-0.004854,-1.0,1.0,0.0,-1.0,1.0,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000,-1.0,1.0,0.0,-1.000000,1.000000