In [1]:
#get season matchup diff's

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [4]:
df = rcp('51stat_cma_diff_2010_2018.csv', ['game_date'])
df = df.sort_values(['game_id', 'game_date'], ascending=[True, True])
df = df.reset_index(drop=True)
p(df)

(10266, 252)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,E_OFF_RATING_a,OFF_RATING_a,E_DEF_RATING_a,DEF_RATING_a,E_NET_RATING_a,NET_RATING_a,AST_PCT_a,AST_TOV_a,AST_RATIO_a,OREB_PCT_a,DREB_PCT_a,REB_PCT_a,E_TM_TOV_PCT_a,TM_TOV_PCT_a,EFG_PCT_a,TS_PCT_a,USG_PCT_a,E_USG_PCT_a,E_PACE_a,PACE_a,PACE_PER40_a,POSS_a,PIE_a,duration_minutes_a,team_id_a,w_pct_a,min_a,fgm_a,fga_a,fg_pct_a,fg3m_a,fg3a_a,fg3_pct_a,ftm_a,fta_a,ft_pct_a,oreb_a,dreb_a,reb_a,ast_a,stl_a,blk_a,tov_a,pf_a,pts_a,wl_a,spread_a,away_home_a,game_date,matchup,season_type,season,season_year,a,b,E_OFF_RATING_cma_a,OFF_RATING_cma_a,E_DEF_RATING_cma_a,DEF_RATING_cma_a,E_NET_RATING_cma_a,NET_RATING_cma_a,AST_PCT_cma_a,AST_TOV_cma_a,AST_RATIO_cma_a,OREB_PCT_cma_a,DREB_PCT_cma_a,REB_PCT_cma_a,E_TM_TOV_PCT_cma_a,TM_TOV_PCT_cma_a,EFG_PCT_cma_a,TS_PCT_cma_a,USG_PCT_cma_a,E_USG_PCT_cma_a,E_PACE_cma_a,PACE_cma_a,PACE_PER40_cma_a,POSS_cma_a,PIE_cma_a,duration_minutes_cma_a,w_pct_cma_a,min_cma_a,fgm_cma_a,fga_cma_a,fg_pct_cma_a,fg3m_cma_a,fg3a_cma_a,fg3_pct_cma_a,ftm_cma_a,fta_cma_a,ft_pct_cma_a,oreb_cma_a,dreb_cma_a,reb_cma_a,ast_cma_a,stl_cma_a,blk_cma_a,tov_cma_a,pf_cma_a,pts_cma_a,spread_cma_a,away_home_cma_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,E_OFF_RATING_b,OFF_RATING_b,E_DEF_RATING_b,DEF_RATING_b,E_NET_RATING_b,NET_RATING_b,AST_PCT_b,AST_TOV_b,AST_RATIO_b,OREB_PCT_b,DREB_PCT_b,REB_PCT_b,E_TM_TOV_PCT_b,TM_TOV_PCT_b,EFG_PCT_b,TS_PCT_b,USG_PCT_b,E_USG_PCT_b,E_PACE_b,PACE_b,PACE_PER40_b,POSS_b,PIE_b,duration_minutes_b,team_id_b,w_pct_b,min_b,fgm_b,fga_b,fg_pct_b,fg3m_b,fg3a_b,fg3_pct_b,ftm_b,fta_b,ft_pct_b,oreb_b,dreb_b,reb_b,ast_b,stl_b,blk_b,tov_b,pf_b,pts_b,wl_b,spread_b,away_home_b,E_OFF_RATING_cma_b,OFF_RATING_cma_b,E_DEF_RATING_cma_b,DEF_RATING_cma_b,E_NET_RATING_cma_b,NET_RATING_cma_b,AST_PCT_cma_b,AST_TOV_cma_b,AST_RATIO_cma_b,OREB_PCT_cma_b,DREB_PCT_cma_b,REB_PCT_cma_b,E_TM_TOV_PCT_cma_b,TM_TOV_PCT_cma_b,EFG_PCT_cma_b,TS_PCT_cma_b,USG_PCT_cma_b,E_USG_PCT_cma_b,E_PACE_cma_b,PACE_cma_b,PACE_PER40_cma_b,POSS_cma_b,PIE_cma_b,duration_minutes_cma_b,w_pct_cma_b,min_cma_b,fgm_cma_b,fga_cma_b,fg_pct_cma_b,fg3m_cma_b,fg3a_cma_b,fg3_pct_cma_b,ftm_cma_b,fta_cma_b,ft_pct_cma_b,oreb_cma_b,dreb_cma_b,reb_cma_b,ast_cma_b,stl_cma_b,blk_cma_b,tov_cma_b,pf_cma_b,pts_cma_b,spread_cma_b,away_home_cma_b,E_OFF_RATING_cma_diff,OFF_RATING_cma_diff,E_DEF_RATING_cma_diff,DEF_RATING_cma_diff,E_NET_RATING_cma_diff,NET_RATING_cma_diff,AST_PCT_cma_diff,AST_TOV_cma_diff,AST_RATIO_cma_diff,OREB_PCT_cma_diff,DREB_PCT_cma_diff,REB_PCT_cma_diff,E_TM_TOV_PCT_cma_diff,TM_TOV_PCT_cma_diff,EFG_PCT_cma_diff,TS_PCT_cma_diff,USG_PCT_cma_diff,E_USG_PCT_cma_diff,E_PACE_cma_diff,PACE_cma_diff,PACE_PER40_cma_diff,POSS_cma_diff,PIE_cma_diff,duration_minutes_cma_diff,w_pct_cma_diff,min_cma_diff,fgm_cma_diff,fga_cma_diff,fg_pct_cma_diff,fg3m_cma_diff,fg3a_cma_diff,fg3_pct_cma_diff,ftm_cma_diff,fta_cma_diff,ft_pct_cma_diff,oreb_cma_diff,dreb_cma_diff,reb_cma_diff,ast_cma_diff,stl_cma_diff,blk_cma_diff,tov_cma_diff,pf_cma_diff,pts_cma_diff,spread_cma_diff,away_home_cma_diff
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,Celtics,BOS,Boston,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,L,8,0,2010-10-27,BOS vs. CLE,Regular Season,2010-11,2010,BOS,CLE,95.700000,95.700000,87.900000,87.900000,7.700000,7.700000,0.781000,1.250000,20.000000,0.268000,0.750000,0.528000,21.739000,21.700000,0.522000,0.550000,1.0,0.196000,91.500000,91.500000,76.250000,92.000000,0.599000,240.000000,1.000000,240.000000,32.000000,69.000000,0.464000,8.000000,16.000000,0.500000,16.000000,25.000000,0.640000,8.000000,34.000000,42.000000,25.000000,6.000000,4.000000,18.000000,19.000000,88.000000,-8.000000,1.000000,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,W,-8,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,95.700000,95.700000,87.900000,87.900000,7.700000,7.700000,0.781000,1.250000,20.000000,0.268000,0.750000,0.528000,21.739000,21.700000,0.522000,0.550000,1.0,0.196000,91.500000,91.500000,76.250000,92.000000,0.599000,240.000000,1.000000,240.000000,32.000000,69.000000,0.464000,8.000000,16.000000,0.500000,16.000000,25.000000,0.640000,8.000000,34.000000,42.000000,25.000000,6.000000,4.000000,18.000000,19.000000,88.000000,-8.000000,1.000000
4,21000005,Pistons,DET,Detroit,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,L,3,0,2010-10-27,DET vs. NJN,Regular Season,2010-11,2010,DET,NJN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Nets,NJN,New Jersey,240:00,0 days 04:00:00,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,W,-3,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,2017,GSW,HOU,109.175000,109.158333,99.258333,100.366667,9.916667,8.791667,0.610333,2.066667,18.333333,0.230500,0.770417,0.508750,12.693083,12.750000,0.525750,0.566250,1.0,0.198750,101.796667,101.166667,84.305833,101.083333,0.560833,240.000000,0.715333,240.000000,41.000000,88.000000,0.465750,10.500000,30.916667,0.336500,17.916667,21.750000,0.830346,9.166667,36.916667,46.083333,25.166667,8.750000,5.250000,12.500000,18.750000,110.416667,-8.750000,0.583333,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1,106.641667,108.016667,106.925000,107.183333,-0.266667,0.841667,0.504833,1.845833,14.975000,0.237250,0.773167,0.497250,13.168167,13.375000,0.522000,0.561167,1.0,0.196667,98.050000,97.208333,81.008333,97.416667,0.498000,240.000000,0.579167,240.000000,37.083333,84.000000,0.440167,13.666667,38.250000,0.358333,17.333333,21.750000,0.791195,7.916667,34.666667,42.583333,19.000000,7.833333,5.333333,11.750000,19.750000,105.166667,-1.166667,0.583333,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000
10262,41700401,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,110.358333,112.808333,105.416667,107.716667,4.941667,5.083333,0.517083,2.265833,15.933333,0.269167,0.749667,0.518917,12.421750,12.675000,0.536333,0.573667,1.0,0.197417,94.120833,92.100833,76.750833,93.250000,0.532500,242.083333,0.572917,242.083333,38.333333,81.083333,0.473000,10.166667,28.916667,0.352333,18.333333,24.250000,0.749490,8.250000,33.166667,41.416667,19.750000,5.500000,5.000000,11.000000,19.666667,105.166667,-5.500000,0.500000,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1,109.716667,109.816667,99.433333,100.891667,10.283333,8.925000,0.607417,1.980833,18.341667,0.241583,0.759500,0.509167,13.362167,13.441667,0.535083,0.571167,1.0,0.198750,101.595000,100.750000,83.958333,100.666667,0.559583,240.000000,0.696250,240.000000,41.166667,87.750000,0.469250,11.416667,31.916667,0.355250,16.833333,20.833333,0.805346,9.416667,36.250000,45.666667,25.166667,9.083333,5.416667,13.000000,19.000000,110.583333,-8.833333,0.500000,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000
10263,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,109.825000,112.383333,106.275000,108.700000,3.550000,3.675000,0.504250,2.265833,15.783333,0.272000,0.761417,0.524000,12.276583,12.541667,0.535917,0.569583,1.0,0.197083,94.330000,92.231667,76.859167,94.250000,0.519750,244.166667,0.525333,244.166667,39.333333,83.166667,0.474000,10.166667,29.583333,0.346083,17.083333,22.750000,0.745513,8.583333,33.583333,42.166667,19.750000,5.416667,4.916667,10.916667,19.416667,105.916667,-4.333333,0.416667,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,110.100000,110.766667,100.825000,102.433333,9.283333,8.333333,0.601083,2.107500,18.408333,0.231917,0.738167,0.495083,12.910833,13.033333,0.538333,0.574750,1.0,0.198500,100.480833,99.339167,82.782500,99.916667,0.556833,242.083333,0.696250,242.083333,41.333333,87.666667,0.471500,11.583333,32.666667,0.351417,16.416667,19.833333,0.822012,8.666667,35.416667,44.083333,25.000000,9.250000,5.083333,12.500000,19.166667,110.666667,-7.833333,0.500000,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333

In [5]:
df = df.drop(columns=list([k for k in df.columns if k.endswith('_diff') or
                                                    k.endswith('_cma_a') or
                                                    k.endswith('_cma_b')]))
p(df)

(10266, 114)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,E_OFF_RATING_a,OFF_RATING_a,E_DEF_RATING_a,DEF_RATING_a,E_NET_RATING_a,NET_RATING_a,AST_PCT_a,AST_TOV_a,AST_RATIO_a,OREB_PCT_a,DREB_PCT_a,REB_PCT_a,E_TM_TOV_PCT_a,TM_TOV_PCT_a,EFG_PCT_a,TS_PCT_a,USG_PCT_a,E_USG_PCT_a,E_PACE_a,PACE_a,PACE_PER40_a,POSS_a,PIE_a,duration_minutes_a,team_id_a,w_pct_a,min_a,fgm_a,fga_a,fg_pct_a,fg3m_a,fg3a_a,fg3_pct_a,ftm_a,fta_a,ft_pct_a,oreb_a,dreb_a,reb_a,ast_a,stl_a,blk_a,tov_a,pf_a,pts_a,wl_a,spread_a,away_home_a,game_date,matchup,season_type,season,season_year,a,b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,E_OFF_RATING_b,OFF_RATING_b,E_DEF_RATING_b,DEF_RATING_b,E_NET_RATING_b,NET_RATING_b,AST_PCT_b,AST_TOV_b,AST_RATIO_b,OREB_PCT_b,DREB_PCT_b,REB_PCT_b,E_TM_TOV_PCT_b,TM_TOV_PCT_b,EFG_PCT_b,TS_PCT_b,USG_PCT_b,E_USG_PCT_b,E_PACE_b,PACE_b,PACE_PER40_b,POSS_b,PIE_b,duration_minutes_b,team_id_b,w_pct_b,min_b,fgm_b,fga_b,fg_pct_b,fg3m_b,fg3a_b,fg3_pct_b,ftm_b,fta_b,ft_pct_b,oreb_b,dreb_b,reb_b,ast_b,stl_b,blk_b,tov_b,pf_b,pts_b,wl_b,spread_b,away_home_b
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1
3,21000004,Celtics,BOS,Boston,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,L,8,0,2010-10-27,BOS vs. CLE,Regular Season,2010-11,2010,BOS,CLE,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,W,-8,1
4,21000005,Pistons,DET,Detroit,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,L,3,0,2010-10-27,DET vs. NJN,Regular Season,2010-11,2010,DET,NJN,Nets,NJN,New Jersey,240:00,0 days 04:00:00,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,W,-3,1
10261,41700317,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,2017,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1
10262,41700401,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1
10263,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1
10264,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0
10265,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0

In [6]:
column_names_not_diff_list = [k for k in df.columns if not k.endswith('_a') and
                                                       not k.endswith('_b')] + ['team_id_a', 'team_id_b']
pl(column_names_not_diff_list)

10

['game_id',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'a',
 'b',
 'team_id_a',
 'team_id_b']

In [7]:
column_names_not_diff_list = [k for k in column_names_not_diff_list if not k in ['season', 'matchup']]
pl(column_names_not_diff_list)

8

['game_id',
 'game_date',
 'season_type',
 'season_year',
 'a',
 'b',
 'team_id_a',
 'team_id_b']

In [8]:
p(df)

(10266, 114)

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,E_OFF_RATING_a,OFF_RATING_a,E_DEF_RATING_a,DEF_RATING_a,E_NET_RATING_a,NET_RATING_a,AST_PCT_a,AST_TOV_a,AST_RATIO_a,OREB_PCT_a,DREB_PCT_a,REB_PCT_a,E_TM_TOV_PCT_a,TM_TOV_PCT_a,EFG_PCT_a,TS_PCT_a,USG_PCT_a,E_USG_PCT_a,E_PACE_a,PACE_a,PACE_PER40_a,POSS_a,PIE_a,duration_minutes_a,team_id_a,w_pct_a,min_a,fgm_a,fga_a,fg_pct_a,fg3m_a,fg3a_a,fg3_pct_a,ftm_a,fta_a,ft_pct_a,oreb_a,dreb_a,reb_a,ast_a,stl_a,blk_a,tov_a,pf_a,pts_a,wl_a,spread_a,away_home_a,game_date,matchup,season_type,season,season_year,a,b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,E_OFF_RATING_b,OFF_RATING_b,E_DEF_RATING_b,DEF_RATING_b,E_NET_RATING_b,NET_RATING_b,AST_PCT_b,AST_TOV_b,AST_RATIO_b,OREB_PCT_b,DREB_PCT_b,REB_PCT_b,E_TM_TOV_PCT_b,TM_TOV_PCT_b,EFG_PCT_b,TS_PCT_b,USG_PCT_b,E_USG_PCT_b,E_PACE_b,PACE_b,PACE_PER40_b,POSS_b,PIE_b,duration_minutes_b,team_id_b,w_pct_b,min_b,fgm_b,fga_b,fg_pct_b,fg3m_b,fg3a_b,fg3_pct_b,ftm_b,fta_b,ft_pct_b,oreb_b,dreb_b,reb_b,ast_b,stl_b,blk_b,tov_b,pf_b,pts_b,wl_b,spread_b,away_home_b
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1
3,21000004,Celtics,BOS,Boston,240:00,0 days 04:00:00,92.3,94.6,97.7,103.3,-5.4,-8.7,0.706,1.26,19.3,0.225,0.708,0.489,20.161,20.7,0.493,0.535,1.0,0.198,95.74,92.00,76.67,92,0.477,240.0,1610612738,0.500,240,34,72,0.472,3,12,0.250,16,21,0.761905,6,32,38,24,8,1,19,24,87,L,8,0,2010-10-27,BOS vs. CLE,Regular Season,2010-11,2010,BOS,CLE,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,97.7,103.3,92.3,94.6,5.4,8.7,0.667,1.60,18.6,0.292,0.775,0.511,15.426,16.3,0.481,0.526,1.0,0.196,95.74,92.00,76.67,92,0.523,240.0,1610612739,1.000,240,36,81,0.444,6,20,0.300,17,21,0.809524,8,29,37,24,5,4,14,20,95,W,-8,1
4,21000005,Pistons,DET,Detroit,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,L,3,0,2010-10-27,DET vs. NJN,Regular Season,2010-11,2010,DET,NJN,Nets,NJN,New Jersey,240:00,0 days 04:00:00,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,W,-3,1
10261,41700317,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,2017,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1
10262,41700401,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1
10263,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1
10264,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0
10265,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0

In [9]:
def wide_get_cma_num_diff3(df_, groupby_list_, not_difference_list_, suffix_list_, window_size_max_min_):
    
    
    #get suffix category column name: suffix_cat
    alphanumeric = ''
    suffix_cat = ''
    for i in range(len(suffix_list_)):
        
        for character in suffix_list_[i]:
            if character.isalnum():
                alphanumeric += character
        
        suffix_cat = suffix_cat + alphanumeric + '_'
        alphanumeric = ''

    
    column_names_list_ = list(df_.columns)
    
    column_names_first_second_list_ = [k for k in column_names_list_
                                       if not k in not_difference_list_]
    
    column_names_first_second_list_first_ = [k for k in column_names_first_second_list_
                                            if k.endswith(suffix_list_[0])]
    
    column_names_first_second_list_first_stripped_ = [k.split(suffix_list_[0])[0]
                                                     for k in column_names_first_second_list_first_]
    
    
    df_ = f.wide2tall(df_, not_difference_list_, suffix_list_)
    
    #return df_
    #good up to here...

    
    column_names_number_list_ = list(df_.select_dtypes('number'))

    column_names_number_list_ = [k for k in column_names_number_list_ if not k in not_difference_list_]
    
    column_names_number_list_ = [k for k in column_names_number_list_ if not k in suffix_cat]
    
    gbl_column_names_number_list_ = groupby_list_ + [k for k in column_names_number_list_
                                                          if not k in groupby_list_] 
    
    df_numeric_gbl_ = df_[gbl_column_names_number_list_]
    
    #return df_numeric_gbl_
    
    
    df_gbl_cma_ = df_numeric_gbl_.groupby(
                                            groupby_list_).apply(lambda x:
                                            x.rolling(window_size_max_min_[0],
                                            window_size_max_min_[1]).mean().shift()
                                         )[column_names_number_list_]
    #return df_gbl_cma_
    
    #vision: df_stat_season_match_numeric.groupby(['season', 'matchup']).apply(lambda x: x.rolling(12, 1).mean().shift())
    
    index_num_ = len(df_gbl_cma_.index[0])
    
    pre_rename_cma_drop_list_ = [k for k in column_names_number_list_ if k in groupby_list_]
    
    df_gbl_cma_.drop(columns=pre_rename_cma_drop_list_, inplace=True)
    
     
    column_names_number_list_cma_num_ = [k + '_cma' + str(window_size_max_min_[0]) for k in column_names_number_list_]
    
    column_names_number_dict_cma_num_ = dict(zip(column_names_number_list_, column_names_number_list_cma_num_))
        
    df_gbl_cma_.rename(columns=column_names_number_dict_cma_num_, inplace=True)
    
    df_gbl_cma_ = df_gbl_cma_.reset_index()
    
    
    df_gbl_cma_.rename(columns={'level_' + str(index_num_ - 1): 'index'}, inplace=True)

    #return df_gbl_cma_
    
    df_ = df_.reset_index()
    
    column_names_merged_list = ['index'] + groupby_list_
    
   
    column_names_number_list_rgbl_ = [k for k in column_names_number_list_ if not k in groupby_list_]
    
    df_dropped_ = df_.drop(columns=column_names_number_list_rgbl_)
        
    df_gbl_cma_merged_ = pd.merge(df_dropped_, df_gbl_cma_, on=column_names_merged_list)
    
    #return df_gbl_cma_merged_
    
    df_gbl_cma_merged_.drop(columns='index', inplace=True)
    
    
    df_wide_ = f.tall2wide2(df_gbl_cma_merged_, not_difference_list_, suffix_cat)

    df_wide_ = sr(df_wide_, 'game_date')
    
    
    
    #take difference of numeric columns with the same prefix, store to stat_cma#_diff
    
    return f.get_numeric_diff(df_wide_, groupby_list_, not_difference_list_, suffix_list_)
    
    #merge back to columns not taken a difference on

In [10]:
df_stat_season_matchup_cma12_diff = wide_get_cma_num_diff3(df,
                                                            ['season', 'matchup', 'team_id'],
                                                            ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                                                            ['_a', '_b'],
                                                            [12,1])
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home_cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000014,2010-10-27,2010-11,Regular Season,2010,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612743,W,DEN vs. UTA,DEN,UTA,Jazz,UTA,Utah,240:00,0 days 04:00:00,1610612762,L,DEN vs. UTA,DEN,UTA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [11]:
#df_stat_season_matchup_cma12_diff.drop(columns=['team_id_cma12_diff'], inplace=True)

In [12]:
df_stat_season_matchup_cma12_diff = sr(df_stat_season_matchup_cma12_diff, 'game_id')
df_stat_season_matchup_cma12_diff = sr(df_stat_season_matchup_cma12_diff, 'game_date')
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home_cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000014,2010-10-27,2010-11,Regular Season,2010,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612743,W,DEN vs. UTA,DEN,UTA,Jazz,UTA,Utah,240:00,0 days 04:00:00,1610612762,L,DEN vs. UTA,DEN,UTA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [13]:
help(f.wide_get_cma_num_diff3)

Help on function wide_get_cma_num_diff3 in module my_functions:

wide_get_cma_num_diff3(df_, groupby_list_, not_difference_list_, suffix_list_, window_size_max_min_)

In [14]:
list(df_stat_season_matchup_cma12_diff.columns)

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'team_id_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'team_id_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'E_OFF_RATING_cma12_diff',
 'OFF_RATING_cma12_diff',
 'E_DEF_RATING_cma12_diff',
 'DEF_RATING_cma12_diff',
 'E_NET_RATING_cma12_diff',
 'NET_RATING_cma12_diff',
 'AST_PCT_cma12_diff',
 'AST_TOV_cma12_diff',
 'AST_RATIO_cma12_diff',
 'OREB_PCT_cma12_diff',
 'DREB_PCT_cma12_diff',
 'REB_PCT_cma12_diff',
 'E_TM_TOV_PCT_cma12_diff',
 'TM_TOV_PCT_cma12_diff',
 'EFG_PCT_cma12_diff',
 'TS_PCT_cma12_diff',
 'USG_PCT_cma12_diff',
 'E_USG_PCT_cma12_diff',
 'E_PACE_cma12_diff',
 'PACE_cma12_diff',
 'PACE_PER40_cma12_diff',
 'POSS_cma12_diff',
 'PIE_cma12_diff',
 'duration_minutes_cma12_diff',
 'w_pct_cma12_diff',
 'min_cma12_diff',
 'fgm_cma12_diff',
 'fga_cma12_diff',
 'fg_pct_cma12_diff',
 'fg3m_cma12_diff',
 'fg3a_cma12_diff',
 'fg3_pct_cma12_diff',
 'ftm_cma12_diff',
 'fta_cma12_diff',
 'ft_pct_cma12_diff',
 'oreb_cma12_diff',
 'dreb_cma12_diff',
 'reb_cma12_diff',
 'ast_cma12_diff',
 'stl_cma12_diff',
 'blk_cma12_diff',
 'tov_cma12_diff',
 'pf_cma12_diff',
 'pts_cma12_diff',
 'spread_cma12_diff',
 'away_home_cma12_diff']

In [15]:
column_names_season_matchup_cma12_diff_dict = {k : k.split('_cma12_diff')[0] + '_sm_cma12_diff'
                                               for k in list(df_stat_season_matchup_cma12_diff.columns)
                                               if k.endswith('_cma12_diff')}
pl(column_names_season_matchup_cma12_diff_dict)

46

{'E_OFF_RATING_cma12_diff': 'E_OFF_RATING_sm_cma12_diff',
 'OFF_RATING_cma12_diff': 'OFF_RATING_sm_cma12_diff',
 'E_DEF_RATING_cma12_diff': 'E_DEF_RATING_sm_cma12_diff',
 'DEF_RATING_cma12_diff': 'DEF_RATING_sm_cma12_diff',
 'E_NET_RATING_cma12_diff': 'E_NET_RATING_sm_cma12_diff',
 'NET_RATING_cma12_diff': 'NET_RATING_sm_cma12_diff',
 'AST_PCT_cma12_diff': 'AST_PCT_sm_cma12_diff',
 'AST_TOV_cma12_diff': 'AST_TOV_sm_cma12_diff',
 'AST_RATIO_cma12_diff': 'AST_RATIO_sm_cma12_diff',
 'OREB_PCT_cma12_diff': 'OREB_PCT_sm_cma12_diff',
 'DREB_PCT_cma12_diff': 'DREB_PCT_sm_cma12_diff',
 'REB_PCT_cma12_diff': 'REB_PCT_sm_cma12_diff',
 'E_TM_TOV_PCT_cma12_diff': 'E_TM_TOV_PCT_sm_cma12_diff',
 'TM_TOV_PCT_cma12_diff': 'TM_TOV_PCT_sm_cma12_diff',
 'EFG_PCT_cma12_diff': 'EFG_PCT_sm_cma12_diff',
 'TS_PCT_cma12_diff': 'TS_PCT_sm_cma12_diff',
 'USG_PCT_cma12_diff': 'USG_PCT_sm_cma12_diff',
 'E_USG_PCT_cma12_diff': 'E_USG_PCT_sm_cma12_diff',
 'E_PACE_cma12_diff': 'E_PACE_sm_cma12_diff',
 'PACE_cma12_diff': 'PACE_sm_cma12_diff',
 'PACE_PER40_cma12_diff': 'PACE_PER40_sm_cma12_diff',
 'POSS_cma12_diff': 'POSS_sm_cma12_diff',
 'PIE_cma12_diff': 'PIE_sm_cma12_diff',
 'duration_minutes_cma12_diff': 'duration_minutes_sm_cma12_diff',
 'w_pct_cma12_diff': 'w_pct_sm_cma12_diff',
 'min_cma12_diff': 'min_sm_cma12_diff',
 'fgm_cma12_diff': 'fgm_sm_cma12_diff',
 'fga_cma12_diff': 'fga_sm_cma12_diff',
 'fg_pct_cma12_diff': 'fg_pct_sm_cma12_diff',
 'fg3m_cma12_diff': 'fg3m_sm_cma12_diff',
 'fg3a_cma12_diff': 'fg3a_sm_cma12_diff',
 'fg3_pct_cma12_diff': 'fg3_pct_sm_cma12_diff',
 'ftm_cma12_diff': 'ftm_sm_cma12_diff',
 'fta_cma12_diff': 'fta_sm_cma12_diff',
 'ft_pct_cma12_diff': 'ft_pct_sm_cma12_diff',
 'oreb_cma12_diff': 'oreb_sm_cma12_diff',
 'dreb_cma12_diff': 'dreb_sm_cma12_diff',
 'reb_cma12_diff': 'reb_sm_cma12_diff',
 'ast_cma12_diff': 'ast_sm_cma12_diff',
 'stl_cma12_diff': 'stl_sm_cma12_diff',
 'blk_cma12_diff': 'blk_sm_cma12_diff',
 'tov_cma12_diff': 'tov_sm_cma12_diff',
 'pf_cma12_diff': 'pf_sm_cma12_diff',
 'pts_cma12_diff': 'pts_sm_cma12_diff',
 'spread_cma12_diff': 'spread_sm_cma12_diff',
 'away_home_cma12_diff': 'away_home_sm_cma12_diff'}

In [16]:
df_stat_season_matchup_cma12_diff.rename(columns=column_names_season_matchup_cma12_diff_dict, inplace=True)

In [17]:
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000014,2010-10-27,2010-11,Regular Season,2010,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612743,W,DEN vs. UTA,DEN,UTA,Jazz,UTA,Utah,240:00,0 days 04:00:00,1610612762,L,DEN vs. UTA,DEN,UTA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [18]:
df_gitaabtiab = df.loc[:, ['game_id', 'TEAM_ABBREVIATION_a', 'TEAM_ABBREVIATION_b', 'team_id_a', 'team_id_b']]
p(df_gitaabtiab)

(10266, 5)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b
0,21000001,BOS,MIA,1610612738,1610612748
1,21000002,PHX,POR,1610612756,1610612757
2,21000003,HOU,LAL,1610612745,1610612747
3,21000004,BOS,CLE,1610612738,1610612739
4,21000005,DET,NJN,1610612765,1610612751
10261,41700317,GSW,HOU,1610612744,1610612745
10262,41700401,CLE,GSW,1610612739,1610612744
10263,41700402,CLE,GSW,1610612739,1610612744
10264,41700403,CLE,GSW,1610612739,1610612744
10265,41700404,CLE,GSW,1610612739,1610612744

In [19]:
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000014,2010-10-27,2010-11,Regular Season,2010,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612743,W,DEN vs. UTA,DEN,UTA,Jazz,UTA,Utah,240:00,0 days 04:00:00,1610612762,L,DEN vs. UTA,DEN,UTA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [20]:
#df_gitaabtiab.loc[:,['game_id', 'TEAM_ABBREVIATION_a', 'TEAM_ABBREVIATION_b']].info()
df_gitaabtiab['TEAM_ABBREVIATION_a'] = df_gitaabtiab['TEAM_ABBREVIATION_a'].str.strip()
df_gitaabtiab['TEAM_ABBREVIATION_b'] = df_gitaabtiab['TEAM_ABBREVIATION_b'].str.strip()

In [21]:
p(df_gitaabtiab)

(10266, 5)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b
0,21000001,BOS,MIA,1610612738,1610612748
1,21000002,PHX,POR,1610612756,1610612757
2,21000003,HOU,LAL,1610612745,1610612747
3,21000004,BOS,CLE,1610612738,1610612739
4,21000005,DET,NJN,1610612765,1610612751
10261,41700317,GSW,HOU,1610612744,1610612745
10262,41700401,CLE,GSW,1610612739,1610612744
10263,41700402,CLE,GSW,1610612739,1610612744
10264,41700403,CLE,GSW,1610612739,1610612744
10265,41700404,CLE,GSW,1610612739,1610612744

In [22]:
#df_stat_season_matchup_cma12_diff.loc[:,['game_id', 'TEAM_ABBREVIATION_a', 'TEAM_ABBREVIATION_b']].info()
df_stat_season_matchup_cma12_diff['TEAM_ABBREVIATION_a'] = df_stat_season_matchup_cma12_diff['TEAM_ABBREVIATION_a'].str.strip()
df_stat_season_matchup_cma12_diff['TEAM_ABBREVIATION_b'] = df_stat_season_matchup_cma12_diff['TEAM_ABBREVIATION_b'].str.strip()

In [23]:
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000014,2010-10-27,2010-11,Regular Season,2010,Nuggets,DEN,Denver,240:00,0 days 04:00:00,1610612743,W,DEN vs. UTA,DEN,UTA,Jazz,UTA,Utah,240:00,0 days 04:00:00,1610612762,L,DEN vs. UTA,DEN,UTA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [24]:
df_stat_season_matchup_cma12_diff = pd.merge(df_gitaabtiab,
                                             df_stat_season_matchup_cma12_diff,
                                             on=['game_id', 'TEAM_ABBREVIATION_a', 'TEAM_ABBREVIATION_b',
                                                 'team_id_a', 'team_id_b'])
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [25]:
df_stat_season_matchup_cma12_diff = df_stat_season_matchup_cma12_diff.sort_values(['game_id', 'game_date'], ascending=[True, True])
df_stat_season_matchup_cma12_diff = df_stat_season_matchup_cma12_diff.reset_index(drop=True)
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [26]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '52stat_season_matchup_cma12_diff_2010_2018_my_functions.csv')
if not os.path.exists(datapath_df):
    df_stat_season_matchup_cma12_diff.to_csv(datapath_df, index=False)

In [27]:
df_stat_season_matchup_cma12_diff_my_functions_readback = rcp('52stat_season_matchup_cma12_diff_2010_2018_my_functions.csv')
p(df_stat_season_matchup_cma12_diff_my_functions_readback)

(10266, 71)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

<font color='red'> seems like there is something wrong with the 'stat_season_matchup_cma12_diff' calculated by using my_functions module??????????????????</font> -fixed

<font color='red'> negative 95 is too high the E_OFF_RATING_sm_cma_diff for a first game of the season??????? should be zero??????</font> -fixed

In [38]:
list_rb_mf = [k for k in df_stat_season_matchup_cma12_diff_my_functions_readback.columns if k.endswith('_diff')]
pl(list_rb_mf)

46

['E_OFF_RATING_sm_cma12_diff',
 'OFF_RATING_sm_cma12_diff',
 'E_DEF_RATING_sm_cma12_diff',
 'DEF_RATING_sm_cma12_diff',
 'E_NET_RATING_sm_cma12_diff',
 'NET_RATING_sm_cma12_diff',
 'AST_PCT_sm_cma12_diff',
 'AST_TOV_sm_cma12_diff',
 'AST_RATIO_sm_cma12_diff',
 'OREB_PCT_sm_cma12_diff',
 'DREB_PCT_sm_cma12_diff',
 'REB_PCT_sm_cma12_diff',
 'E_TM_TOV_PCT_sm_cma12_diff',
 'TM_TOV_PCT_sm_cma12_diff',
 'EFG_PCT_sm_cma12_diff',
 'TS_PCT_sm_cma12_diff',
 'USG_PCT_sm_cma12_diff',
 'E_USG_PCT_sm_cma12_diff',
 'E_PACE_sm_cma12_diff',
 'PACE_sm_cma12_diff',
 'PACE_PER40_sm_cma12_diff',
 'POSS_sm_cma12_diff',
 'PIE_sm_cma12_diff',
 'duration_minutes_sm_cma12_diff',
 'w_pct_sm_cma12_diff',
 'min_sm_cma12_diff',
 'fgm_sm_cma12_diff',
 'fga_sm_cma12_diff',
 'fg_pct_sm_cma12_diff',
 'fg3m_sm_cma12_diff',
 'fg3a_sm_cma12_diff',
 'fg3_pct_sm_cma12_diff',
 'ftm_sm_cma12_diff',
 'fta_sm_cma12_diff',
 'ft_pct_sm_cma12_diff',
 'oreb_sm_cma12_diff',
 'dreb_sm_cma12_diff',
 'reb_sm_cma12_diff',
 'ast_sm_cma12_diff',
 'stl_sm_cma12_diff',
 'blk_sm_cma12_diff',
 'tov_sm_cma12_diff',
 'pf_sm_cma12_diff',
 'pts_sm_cma12_diff',
 'spread_sm_cma12_diff',
 'away_home_sm_cma12_diff']

In [39]:
df_stat_season_matchup_cma12_diff_readback = rcp('52stat_season_matchup_cma12_diff_2010_2018.csv')
p(df_stat_season_matchup_cma12_diff_readback)

(10266, 52)

,game_id,game_date,team_id_a,team_id_b,season,matchup,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,2010-10-26,1610612738,1610612748,2010-11,BOS vs. MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,1610612756,1610612757,2010-11,PHX vs. POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,1610612745,1610612747,2010-11,HOU vs. LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,1610612738,1610612739,2010-11,BOS vs. CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000005,2010-10-27,1610612765,1610612751,2010-11,DET vs. NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,1610612744,1610612745,2017-18,GSW vs. HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,2018-05-31,1610612739,1610612744,2017-18,CLE vs. GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,2018-06-03,1610612739,1610612744,2017-18,CLE vs. GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,2018-06-06,1610612739,1610612744,2017-18,CLE vs. GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,2018-06-08,1610612739,1610612744,2017-18,CLE vs. GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [40]:
list_rb = [k for k in df_stat_season_matchup_cma12_diff_readback.columns if k.endswith('_diff')]
pl(list_rb)

46

['E_OFF_RATING_sm_cma12_diff',
 'OFF_RATING_sm_cma12_diff',
 'E_DEF_RATING_sm_cma12_diff',
 'DEF_RATING_sm_cma12_diff',
 'E_NET_RATING_sm_cma12_diff',
 'NET_RATING_sm_cma12_diff',
 'AST_PCT_sm_cma12_diff',
 'AST_TOV_sm_cma12_diff',
 'AST_RATIO_sm_cma12_diff',
 'OREB_PCT_sm_cma12_diff',
 'DREB_PCT_sm_cma12_diff',
 'REB_PCT_sm_cma12_diff',
 'E_TM_TOV_PCT_sm_cma12_diff',
 'TM_TOV_PCT_sm_cma12_diff',
 'EFG_PCT_sm_cma12_diff',
 'TS_PCT_sm_cma12_diff',
 'USG_PCT_sm_cma12_diff',
 'E_USG_PCT_sm_cma12_diff',
 'E_PACE_sm_cma12_diff',
 'PACE_sm_cma12_diff',
 'PACE_PER40_sm_cma12_diff',
 'POSS_sm_cma12_diff',
 'PIE_sm_cma12_diff',
 'duration_minutes_sm_cma12_diff',
 'w_pct_sm_cma12_diff',
 'min_sm_cma12_diff',
 'fgm_sm_cma12_diff',
 'fga_sm_cma12_diff',
 'fg_pct_sm_cma12_diff',
 'fg3m_sm_cma12_diff',
 'fg3a_sm_cma12_diff',
 'fg3_pct_sm_cma12_diff',
 'ftm_sm_cma12_diff',
 'fta_sm_cma12_diff',
 'ft_pct_sm_cma12_diff',
 'oreb_sm_cma12_diff',
 'dreb_sm_cma12_diff',
 'reb_sm_cma12_diff',
 'ast_sm_cma12_diff',
 'stl_sm_cma12_diff',
 'blk_sm_cma12_diff',
 'tov_sm_cma12_diff',
 'pf_sm_cma12_diff',
 'pts_sm_cma12_diff',
 'spread_sm_cma12_diff',
 'away_home_sm_cma12_diff']

In [41]:
[k for k in list_rb_mf if not k in list_rb]

[]

In [42]:
list_rb_mf_gitiab = list_rb_mf + ['game_id', 'team_id_a', 'team_id_b']
pl(list_rb_mf_gitiab)

49

['E_OFF_RATING_sm_cma12_diff',
 'OFF_RATING_sm_cma12_diff',
 'E_DEF_RATING_sm_cma12_diff',
 'DEF_RATING_sm_cma12_diff',
 'E_NET_RATING_sm_cma12_diff',
 'NET_RATING_sm_cma12_diff',
 'AST_PCT_sm_cma12_diff',
 'AST_TOV_sm_cma12_diff',
 'AST_RATIO_sm_cma12_diff',
 'OREB_PCT_sm_cma12_diff',
 'DREB_PCT_sm_cma12_diff',
 'REB_PCT_sm_cma12_diff',
 'E_TM_TOV_PCT_sm_cma12_diff',
 'TM_TOV_PCT_sm_cma12_diff',
 'EFG_PCT_sm_cma12_diff',
 'TS_PCT_sm_cma12_diff',
 'USG_PCT_sm_cma12_diff',
 'E_USG_PCT_sm_cma12_diff',
 'E_PACE_sm_cma12_diff',
 'PACE_sm_cma12_diff',
 'PACE_PER40_sm_cma12_diff',
 'POSS_sm_cma12_diff',
 'PIE_sm_cma12_diff',
 'duration_minutes_sm_cma12_diff',
 'w_pct_sm_cma12_diff',
 'min_sm_cma12_diff',
 'fgm_sm_cma12_diff',
 'fga_sm_cma12_diff',
 'fg_pct_sm_cma12_diff',
 'fg3m_sm_cma12_diff',
 'fg3a_sm_cma12_diff',
 'fg3_pct_sm_cma12_diff',
 'ftm_sm_cma12_diff',
 'fta_sm_cma12_diff',
 'ft_pct_sm_cma12_diff',
 'oreb_sm_cma12_diff',
 'dreb_sm_cma12_diff',
 'reb_sm_cma12_diff',
 'ast_sm_cma12_diff',
 'stl_sm_cma12_diff',
 'blk_sm_cma12_diff',
 'tov_sm_cma12_diff',
 'pf_sm_cma12_diff',
 'pts_sm_cma12_diff',
 'spread_sm_cma12_diff',
 'away_home_sm_cma12_diff',
 'game_id',
 'team_id_a',
 'team_id_b']

In [43]:
pd.merge(df_stat_season_matchup_cma12_diff_readback[list_rb_mf_gitiab], 
         df_stat_season_matchup_cma12_diff_my_functions_readback[list_rb_mf_gitiab],
         on=['game_id', 'team_id_a', 'team_id_b'])

,E_OFF_RATING_sm_cma12_diff_x,OFF_RATING_sm_cma12_diff_x,E_DEF_RATING_sm_cma12_diff_x,DEF_RATING_sm_cma12_diff_x,E_NET_RATING_sm_cma12_diff_x,NET_RATING_sm_cma12_diff_x,AST_PCT_sm_cma12_diff_x,AST_TOV_sm_cma12_diff_x,AST_RATIO_sm_cma12_diff_x,OREB_PCT_sm_cma12_diff_x,DREB_PCT_sm_cma12_diff_x,REB_PCT_sm_cma12_diff_x,E_TM_TOV_PCT_sm_cma12_diff_x,TM_TOV_PCT_sm_cma12_diff_x,EFG_PCT_sm_cma12_diff_x,TS_PCT_sm_cma12_diff_x,USG_PCT_sm_cma12_diff_x,E_USG_PCT_sm_cma12_diff_x,E_PACE_sm_cma12_diff_x,PACE_sm_cma12_diff_x,PACE_PER40_sm_cma12_diff_x,POSS_sm_cma12_diff_x,PIE_sm_cma12_diff_x,duration_minutes_sm_cma12_diff_x,w_pct_sm_cma12_diff_x,min_sm_cma12_diff_x,fgm_sm_cma12_diff_x,fga_sm_cma12_diff_x,fg_pct_sm_cma12_diff_x,fg3m_sm_cma12_diff_x,fg3a_sm_cma12_diff_x,fg3_pct_sm_cma12_diff_x,ftm_sm_cma12_diff_x,fta_sm_cma12_diff_x,ft_pct_sm_cma12_diff_x,oreb_sm_cma12_diff_x,dreb_sm_cma12_diff_x,reb_sm_cma12_diff_x,ast_sm_cma12_diff_x,stl_sm_cma12_diff_x,blk_sm_cma12_diff_x,tov_sm_cma12_diff_x,pf_sm_cma12_diff_x,pts_sm_cma12_diff_x,spread_sm_cma12_diff_x,away_home_sm_cma12_diff_x,game_id,team_id_a,team_id_b,E_OFF_RATING_sm_cma12_diff_y,OFF_RATING_sm_cma12_diff_y,E_DEF_RATING_sm_cma12_diff_y,DEF_RATING_sm_cma12_diff_y,E_NET_RATING_sm_cma12_diff_y,NET_RATING_sm_cma12_diff_y,AST_PCT_sm_cma12_diff_y,AST_TOV_sm_cma12_diff_y,AST_RATIO_sm_cma12_diff_y,OREB_PCT_sm_cma12_diff_y,DREB_PCT_sm_cma12_diff_y,REB_PCT_sm_cma12_diff_y,E_TM_TOV_PCT_sm_cma12_diff_y,TM_TOV_PCT_sm_cma12_diff_y,EFG_PCT_sm_cma12_diff_y,TS_PCT_sm_cma12_diff_y,USG_PCT_sm_cma12_diff_y,E_USG_PCT_sm_cma12_diff_y,E_PACE_sm_cma12_diff_y,PACE_sm_cma12_diff_y,PACE_PER40_sm_cma12_diff_y,POSS_sm_cma12_diff_y,PIE_sm_cma12_diff_y,duration_minutes_sm_cma12_diff_y,w_pct_sm_cma12_diff_y,min_sm_cma12_diff_y,fgm_sm_cma12_diff_y,fga_sm_cma12_diff_y,fg_pct_sm_cma12_diff_y,fg3m_sm_cma12_diff_y,fg3a_sm_cma12_diff_y,fg3_pct_sm_cma12_diff_y,ftm_sm_cma12_diff_y,fta_sm_cma12_diff_y,ft_pct_sm_cma12_diff_y,oreb_sm_cma12_diff_y,dreb_sm_cma12_diff_y,reb_sm_cma12_diff_y,ast_sm_cma12_diff_y,stl_sm_cma12_diff_y,blk_sm_cma12_diff_y,tov_sm_cma12_diff_y,pf_sm_cma12_diff_y,pts_sm_cma12_diff_y,spread_sm_cma12_diff_y,away_home_sm_cma12_diff_y
0,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21000001,1610612738,1610612748,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21000002,1610612756,1610612757,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21000003,1610612745,1610612747,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21000004,1610612738,1610612739,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21000005,1610612765,1610612751,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10261,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,41700317,1610612744,1610612745,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,41700401,1610612739,1610612744,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,41700402,1610612739,1610612744,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,41700403,1610612739,1610612744,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,41700404,1610612739,1610612744,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [44]:
df_diff_diff = df_stat_season_matchup_cma12_diff_readback.loc[:, list_rb_mf] \
- df_stat_season_matchup_cma12_diff_my_functions_readback.loc[:, list_rb_mf].values
p(df_diff_diff)

(10266, 46)

,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10264,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10265,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
df_diff_diff.sum()

E_OFF_RATING_sm_cma12_diff        0.0
OFF_RATING_sm_cma12_diff          0.0
E_DEF_RATING_sm_cma12_diff        0.0
DEF_RATING_sm_cma12_diff          0.0
E_NET_RATING_sm_cma12_diff        0.0
NET_RATING_sm_cma12_diff          0.0
AST_PCT_sm_cma12_diff             0.0
AST_TOV_sm_cma12_diff             0.0
AST_RATIO_sm_cma12_diff           0.0
OREB_PCT_sm_cma12_diff            0.0
DREB_PCT_sm_cma12_diff            0.0
REB_PCT_sm_cma12_diff             0.0
E_TM_TOV_PCT_sm_cma12_diff        0.0
TM_TOV_PCT_sm_cma12_diff          0.0
EFG_PCT_sm_cma12_diff             0.0
TS_PCT_sm_cma12_diff              0.0
USG_PCT_sm_cma12_diff             0.0
E_USG_PCT_sm_cma12_diff           0.0
E_PACE_sm_cma12_diff              0.0
PACE_sm_cma12_diff                0.0
PACE_PER40_sm_cma12_diff          0.0
POSS_sm_cma12_diff                0.0
PIE_sm_cma12_diff                 0.0
duration_minutes_sm_cma12_diff    0.0
w_pct_sm_cma12_diff               0.0
min_sm_cma12_diff                 0.0
fgm_sm_cma12_diff                 0.0
fga_sm_cma12_diff                 0.0
fg_pct_sm_cma12_diff              0.0
fg3m_sm_cma12_diff                0.0
fg3a_sm_cma12_diff                0.0
fg3_pct_sm_cma12_diff             0.0
ftm_sm_cma12_diff                 0.0
fta_sm_cma12_diff                 0.0
ft_pct_sm_cma12_diff              0.0
oreb_sm_cma12_diff                0.0
dreb_sm_cma12_diff                0.0
reb_sm_cma12_diff                 0.0
ast_sm_cma12_diff                 0.0
stl_sm_cma12_diff                 0.0
blk_sm_cma12_diff                 0.0
tov_sm_cma12_diff                 0.0
pf_sm_cma12_diff                  0.0
pts_sm_cma12_diff                 0.0
spread_sm_cma12_diff              0.0
away_home_sm_cma12_diff           0.0
dtype: float64