In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
def df_inj1020_fix_Date_Team(df_):
    df_.loc[5923, ['Team']] = 'Pacers'
    return df_

def get_5bsa1018_inj1018_player_diff():
    print(len(set(df_inj1018r.player) - set(df_5bsa1018.PLAYER_NAME)))
    print(set(df_inj1018r.player) - set(df_5bsa1018.PLAYER_NAME))
    print()
    
    print(len(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1018r.player)))
    print(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1018r.player))
    return 0
    

#return first 5 and last 5 rows of dataframe
def p(df_):
    return pd.concat([df_.head(), df_.tail()])

In [4]:
df_5bsa1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
print(df_5bsa1018.shape)
p(df_5bsa1018)

(291643, 31)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [5]:
df_5bsa1018.PLAYER_NAME = df_5bsa1018.PLAYER_NAME.fillna('')
df_5bsa1018.MIN = df_5bsa1018.MIN.fillna('00:00')
df_5bsa1018.MIN = pd.to_timedelta('00:' + df_5bsa1018.MIN).astype('timedelta64[s]').astype('float64') / 60
df_5bsa1018.TEAM_ID = df_5bsa1018.TEAM_ID.fillna(0).astype('int64')
print(df_5bsa1018.shape)
p(df_5bsa1018)

(291643, 31)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1610612738,BOS,Boston,1718.0,Paul Pierce,F,NaN,37.983333,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1610612738,BOS,Boston,708.0,Kevin Garnett,F,NaN,33.083333,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1610612738,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25.700000,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1610612738,BOS,Boston,951.0,Ray Allen,G,NaN,42.350000,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1610612738,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34.483333,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
291638,41700404,1610612739,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23.200000,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1610612739,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1610612739,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1610612739,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1.666667,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.000000,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [6]:
path = os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv')
path
df_3gigdti = pd.read_csv(path, parse_dates=['game_date'])
df_3gigdti1018 = df_3gigdti[(df_3gigdti.season == '2010-11') |
                            (df_3gigdti.season == '2011-12') |
                            (df_3gigdti.season == '2012-13') |
                            (df_3gigdti.season == '2013-14') |
                            (df_3gigdti.season == '2014-15') |
                            (df_3gigdti.season == '2015-16') |
                            (df_3gigdti.season == '2016-17') |
                            (df_3gigdti.season == '2017-18')]
print(df_3gigdti1018.shape)
p(df_3gigdti1018)

(20534, 27)

,game_id,game_date,team_id,is_home,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
9840,21000001,2010-10-26,1610612738,t,1.0,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010,Regular Season,2010-11
9841,21000001,2010-10-26,1610612748,f,0.0,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,2010,Regular Season,2010-11
9842,21000002,2010-10-26,1610612757,t,1.0,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010,Regular Season,2010-11
9843,21000002,2010-10-26,1610612756,f,0.0,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,2010,Regular Season,2010-11
9844,21000003,2010-10-26,1610612745,f,0.0,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,2010,Regular Season,2010-11
31033,41700402,2018-06-03,1610612744,t,1.0,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017,Playoffs,2017-18
31034,41700403,2018-06-06,1610612744,f,1.0,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,2017,Playoffs,2017-18
31035,41700403,2018-06-06,1610612739,t,0.0,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017,Playoffs,2017-18
31036,41700404,2018-06-08,1610612739,t,0.0,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017,Playoffs,2017-18
31037,41700404,2018-06-08,1610612744,f,1.0,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,2017,Playoffs,2017-18

In [7]:
#filter for 2010-11 thru 2017-18 seasons: df_5bsa1018
df_5bsa1018 = pd.merge(df_3gigdti1018[['game_id', 'game_date', 'team_id', 'season']], df_5bsa1018.rename(columns={'GAME_ID':'game_id', 'TEAM_ID':'team_id'}), on=['game_id', 'team_id'], how='inner')
print(df_5bsa1018.shape)
p(df_5bsa1018)

(260161, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,1718.0,Paul Pierce,F,NaN,40.550000,104.9,103.9,87.0,87.2,17.9,16.7,0.120,1.00,18.8,0.033,0.182,0.122,18.8,0.786,0.903,0.153,0.156,91.36,91.74,76.45,77.0,0.193
1,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,708.0,Kevin Garnett,F,NaN,35.216667,104.8,104.5,95.1,94.0,9.7,10.4,0.143,0.43,13.0,0.077,0.235,0.167,30.4,0.364,0.392,0.274,0.279,90.67,91.32,76.10,67.0,0.038
2,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,406.0,Shaquille O'Neal,C,NaN,18.150000,100.5,100.0,80.2,76.5,20.2,23.5,0.000,0.00,0.0,0.143,0.333,0.241,8.3,0.429,0.428,0.324,0.326,86.28,88.60,73.84,33.0,0.081
3,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,951.0,Ray Allen,G,NaN,39.266667,86.9,86.7,91.6,90.5,-4.7,-3.9,0.063,1.00,6.7,0.000,0.027,0.014,6.7,0.731,0.744,0.167,0.171,90.41,91.07,75.89,75.0,0.148
4,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,200765.0,Rajon Rondo,G,NaN,41.483333,94.0,93.6,91.7,90.8,2.3,2.8,0.708,5.67,58.6,0.026,0.108,0.067,10.3,0.222,0.222,0.136,0.140,88.47,89.10,74.25,78.0,0.158
260156,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,201156.0,Nick Young,NaN,NaN,8.983333,131.9,133.3,98.8,106.3,33.0,27.1,0.000,0.00,0.0,0.000,0.067,0.042,0.0,0.375,0.375,0.190,0.198,94.66,90.92,75.77,18.0,0.000
260157,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2561.0,David West,NaN,NaN,7.600000,97.6,92.9,128.7,135.7,-31.1,-42.9,0.333,0.00,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.071,0.075,88.67,88.42,73.68,14.0,0.039
260158,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1626172.0,Kevon Looney,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.500,0.500,0.222,0.254,102.44,94.85,79.04,6.0,0.214
260159,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,2585.0,Zaza Pachulia,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.000,0.250,0.125,33.3,0.000,0.532,0.333,0.381,102.44,94.85,79.04,6.0,0.143
260160,41700404,2018-06-08,1610612744,2017-18,GSW,Golden State,1627775.0,Patrick McCaw,NaN,NaN,2.783333,68.0,66.7,100.0,120.0,-32.0,-53.3,0.000,0.00,0.0,0.250,0.000,0.125,0.0,0.000,0.000,0.000,0.000,102.44,94.85,79.04,6.0,0.071

In [8]:
#pd.merge(df_5bsa1018.rename(columns={'GAME_ID':'game_id'}), df_3gigdti1018[['game_id', 'game_date', 'season']].drop_duplicates(), on=['game_id'] , how='inner')

In [9]:
df_5bsa1018 = df_5bsa1018[df_5bsa1018.MIN == 0]
print(df_5bsa1018[df_5bsa1018.MIN == 0].shape)
p(df_5bsa1018[df_5bsa1018.MIN == 0])

(44547, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
9,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,201623.0,Semih Erden,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
10,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,101144.0,Von Wafer,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
11,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,2753.0,Delonte West,NaN,NWT - League Suspension,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
21,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
22,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,436.0,Juwan Howard,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
260131,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,101181.0,Jose Calderon,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
260132,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
260133,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1626224.0,Cedi Osman,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
260134,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1627790.0,Ante Zizic,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
260147,41700404,2018-06-08,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN

In [10]:
df_5bsa1018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44547 entries, 9 to 260147
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            44547 non-null  int64
 1   game_date          44547 non-null  datetime64[ns]
 2   team_id            44547 non-null  int64
 3   season             44547 non-null  object
 4   TEAM_ABBREVIATION  44547 non-null  object
 5   TEAM_CITY          44547 non-null  object
 6   PLAYER_ID          44547 non-null  float64
 7   PLAYER_NAME        44547 non-null  object
 8   START_POSITION     0 non-null      object
 9   COMMENT            44504 non-null  object
 10  MIN                44547 non-null  float64
 11  E_OFF_RATING       43 non-null     float64
 12  OFF_RATING         44547 non-null  float64
 13  E_DEF_RATING       43 non-null     float64
 14  DEF_RATING         44547 non-null  float64
 15  E_NET_RATING       43 non-null     float64
 16  NET_RATING         44547 non-null  float64
 17  AST_PCT            43 non-null     float64
 18  AST_TOV            43 non-null     float64
 19  AST_RATIO          43 non-null     float64
 20  OREB_PCT           44547 non-null  float64
 21  DREB_PCT           44547 non-null  float64
 22  REB_PCT            44547 non-null  float64
 23  TM_TOV_PCT         43 non-null     float64
 24  EFG_PCT            43 non-null     float64
 25  TS_PCT             43 non-null     float64
 26  USG_PCT            44547 non-null  float64
 27  E_USG_PCT          44547 non-null  float64
 28  E_PACE             43 non-null     float64
 29  PACE               43 non-null     float64
 30  PACE_PER40         43 non-null     float64
 31  POSS               44547 non-null  float64
 32  PIE                43 non-null     float64
dtypes: datetime64[ns](1), float64(24), int64(2), object(6)
memory usage: 11.6+ MB

In [11]:
df_5bsa1018[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']] = df_5bsa1018[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']].fillna(0)

In [12]:
print(df_5bsa1018.shape)
p(df_5bsa1018)

(44547, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
9,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,201623.0,Semih Erden,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,101144.0,Von Wafer,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,2753.0,Delonte West,NaN,NWT - League Suspension,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,436.0,Juwan Howard,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260131,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,101181.0,Jose Calderon,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260132,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260133,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1626224.0,Cedi Osman,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260134,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1627790.0,Ante Zizic,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260147,41700404,2018-06-08,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
df_5bsa1018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44547 entries, 9 to 260147
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            44547 non-null  int64
 1   game_date          44547 non-null  datetime64[ns]
 2   team_id            44547 non-null  int64
 3   season             44547 non-null  object
 4   TEAM_ABBREVIATION  44547 non-null  object
 5   TEAM_CITY          44547 non-null  object
 6   PLAYER_ID          44547 non-null  float64
 7   PLAYER_NAME        44547 non-null  object
 8   START_POSITION     0 non-null      object
 9   COMMENT            44504 non-null  object
 10  MIN                44547 non-null  float64
 11  E_OFF_RATING       44547 non-null  float64
 12  OFF_RATING         44547 non-null  float64
 13  E_DEF_RATING       44547 non-null  float64
 14  DEF_RATING         44547 non-null  float64
 15  E_NET_RATING       44547 non-null  float64
 16  NET_RATING         44547 non-null  float64
 17  AST_PCT            44547 non-null  float64
 18  AST_TOV            44547 non-null  float64
 19  AST_RATIO          44547 non-null  float64
 20  OREB_PCT           44547 non-null  float64
 21  DREB_PCT           44547 non-null  float64
 22  REB_PCT            44547 non-null  float64
 23  TM_TOV_PCT         44547 non-null  float64
 24  EFG_PCT            44547 non-null  float64
 25  TS_PCT             44547 non-null  float64
 26  USG_PCT            44547 non-null  float64
 27  E_USG_PCT          44547 non-null  float64
 28  E_PACE             44547 non-null  float64
 29  PACE               44547 non-null  float64
 30  PACE_PER40         44547 non-null  float64
 31  POSS               44547 non-null  float64
 32  PIE                44547 non-null  float64
dtypes: datetime64[ns](1), float64(24), int64(2), object(6)
memory usage: 11.6+ MB

In [14]:
df_5bsa1018.reset_index(drop=True, inplace=True)

In [15]:
df_5bsa1018_pip = df_5bsa1018[['PLAYER_ID','PLAYER_NAME']].drop_duplicates()
print(df_5bsa1018_pip.shape)
p(df_5bsa1018_pip)

(1059, 2)

       PLAYER_ID     PLAYER_NAME
0       201623.0     Semih Erden
1       101144.0       Von Wafer
2         2753.0    Delonte West
3       201596.0  Mario Chalmers
4          436.0    Juwan Howard
41280  1627821.0  James Webb III
41428  1628369.0    Jayson Tatum
41667     2420.0    Nenad Krstic
42420   101204.0    Dwayne Jones
44286  1628935.0   Aaron Jackson

In [16]:
print(df_5bsa1018_pip.value_counts('PLAYER_ID').shape)
p(df_5bsa1018_pip.value_counts('PLAYER_ID'))

(1059,)

PLAYER_ID
1628935.0    1
201588.0     1
201611.0     1
201609.0     1
201607.0     1
203506.0     1
203505.0     1
203504.0     1
203503.0     1
255.0        1
dtype: int64

In [17]:
print(df_5bsa1018_pip.value_counts('PLAYER_NAME').shape)
p(df_5bsa1018_pip.value_counts('PLAYER_NAME'))

(1055,)

PLAYER_NAME
Mike James            2
Chris Johnson         2
Tony Mitchell         2
Chris Wright          2
Zydrunas Ilgauskas    1
Markieff Morris       1
Markelle Fultz        1
Markel Brown          1
Mario West            1
AJ Hammons            1
dtype: int64

In [18]:
playerl = list(df_5bsa1018_pip.value_counts('PLAYER_NAME')[df_5bsa1018_pip.value_counts('PLAYER_NAME') > 1].reset_index().PLAYER_NAME)
playerl

['Mike James', 'Chris Johnson', 'Tony Mitchell', 'Chris Wright']

In [19]:
playerl[0]

'Mike James'

In [20]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[0])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
5008,21100162,2012-01-13,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5055,21100174,2012-01-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5101,21100185,2012-01-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5179,21100198,2012-01-17,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5396,21100244,2012-01-23,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5475,21100261,2012-01-25,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5549,21100277,2012-01-27,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6216,21100423,2012-02-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7218,21100629,2012-03-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7303,21100647,2012-03-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7440,21100673,2012-03-19,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7476,21100683,2012-03-21,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8125,21100813,2012-04-05,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8239,21100835,2012-04-08,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8407,21100870,2012-04-12,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8544,21100897,2012-04-15,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8598,21100907,2012-04-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8727,21100934,2012-04-19,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8788,21100946,2012-04-21,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8927,21100973,2012-04-25,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11920,21200668,2013-01-29,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12222,21200730,2013-02-06,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14618,21300002,2013-10-29,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14701,21300018,2013-10-31,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14760,21300034,2013-11-02,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15071,21300102,2013-11-11,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15174,21300126,2013-11-15,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15244,21300140,2013-11-16,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15288,21300151,2013-11-18,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15406,21300175,2013-11-21,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15459,21300185,2013-11-22,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15610,21300220,2013-11-27,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15884,21300279,2013-12-05,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15929,21300292,2013-12-07,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16038,21300316,2013-12-10,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16087,21300324,2013-12-11,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16161,21300337,2013-12-13,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17799,21300683,2014-01-29,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20111,21301181,2014-04-11,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20195,21301197,2014-04-13,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20254,21301208,2014-04-14,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20336,21301223,2014-04-16,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38290,21700434,2017-12-16,1610612756,2017-18,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38427,21700469,2017-12-21,1610612756,2017-18,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39086,21700635,2018-01-14,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39144,21700650,2018-01-16,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39163,21700654,2018-01-17,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39262,21700677,2018-01-20,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39326,21700692,2018-01-22,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39363,21700701,2018-01-24,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39435,21700720,2018-01-26,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39480,21700733,2018-01-28,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39790,21700818,2018-02-09,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,NWT - Personal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41804,41100101,2012-04-28,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41811,41100102,2012-05-01,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41818,41100103,2012-05-04,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41824,41100104,2012-05-06,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41832,41100105,2012-05-08,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41835,41100106,2012-05-10,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42755,41300131,2014-04-20,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42761,41300132,2014-04-22,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42770,41300133,2014-04-25,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42775,41300134,2014-04-27,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42787,41300135,2014-04-29,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<font color='red'> how to deal with changing PLAYER_ID?? this just from a team change??? </font> -no, these are different players

In [21]:
df_5bsa1018[df_5bsa1018.PLAYER_ID == 1628455.0]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
38290,21700434,2017-12-16,1610612756,2017-18,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38427,21700469,2017-12-21,1610612756,2017-18,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39086,21700635,2018-01-14,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39144,21700650,2018-01-16,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39163,21700654,2018-01-17,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39262,21700677,2018-01-20,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39326,21700692,2018-01-22,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39363,21700701,2018-01-24,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39435,21700720,2018-01-26,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39480,21700733,2018-01-28,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39790,21700818,2018-02-09,1610612740,2017-18,NOP,New Orleans,1628455.0,Mike James,NaN,NWT - Personal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
df_5bsa1018[df_5bsa1018.PLAYER_ID == 2229.0]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
5008,21100162,2012-01-13,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5055,21100174,2012-01-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5101,21100185,2012-01-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5179,21100198,2012-01-17,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5396,21100244,2012-01-23,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5475,21100261,2012-01-25,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5549,21100277,2012-01-27,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6216,21100423,2012-02-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7218,21100629,2012-03-14,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7303,21100647,2012-03-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7440,21100673,2012-03-19,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7476,21100683,2012-03-21,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8125,21100813,2012-04-05,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8239,21100835,2012-04-08,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8407,21100870,2012-04-12,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8544,21100897,2012-04-15,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8598,21100907,2012-04-16,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8727,21100934,2012-04-19,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8788,21100946,2012-04-21,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8927,21100973,2012-04-25,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11920,21200668,2013-01-29,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12222,21200730,2013-02-06,1610612742,2012-13,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14618,21300002,2013-10-29,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14701,21300018,2013-10-31,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14760,21300034,2013-11-02,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15071,21300102,2013-11-11,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15174,21300126,2013-11-15,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15244,21300140,2013-11-16,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15288,21300151,2013-11-18,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15406,21300175,2013-11-21,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15459,21300185,2013-11-22,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15610,21300220,2013-11-27,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15884,21300279,2013-12-05,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15929,21300292,2013-12-07,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16038,21300316,2013-12-10,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16087,21300324,2013-12-11,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16161,21300337,2013-12-13,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17799,21300683,2014-01-29,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20111,21301181,2014-04-11,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20195,21301197,2014-04-13,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20254,21301208,2014-04-14,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20336,21301223,2014-04-16,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41804,41100101,2012-04-28,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41811,41100102,2012-05-01,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41818,41100103,2012-05-04,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41824,41100104,2012-05-06,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41832,41100105,2012-05-08,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41835,41100106,2012-05-10,1610612741,2011-12,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42755,41300131,2014-04-20,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42761,41300132,2014-04-22,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42770,41300133,2014-04-25,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42775,41300134,2014-04-27,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42787,41300135,2014-04-29,1610612741,2013-14,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
#two different players
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
2262,21000661,2011-01-24,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2327,21000680,2011-01-27,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3169,21000905,2011-03-02,1610612738,2010-11,BOS,Boston,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3487,21001002,2011-03-15,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3594,21001034,2011-03-19,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3629,21001043,2011-03-20,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3748,21001078,2011-03-25,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3806,21001092,2011-03-27,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3841,21001099,2011-03-28,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3898,21001114,2011-03-30,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3940,21001130,2011-04-01,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4469,21100037,2011-12-29,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4572,21100065,2012-01-01,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4640,21100079,2012-01-03,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4703,21100097,2012-01-05,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4897,21100140,2012-01-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4961,21100152,2012-01-11,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5070,21100176,2012-01-14,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5131,21100190,2012-01-16,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5229,21100208,2012-01-18,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5274,21100216,2012-01-20,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5506,21100269,2012-01-25,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5650,21100305,2012-01-30,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5753,21100329,2012-02-02,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5927,21100366,2012-02-06,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6018,21100383,2012-02-08,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6090,21100397,2012-02-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6132,21100405,2012-02-11,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6229,21100427,2012-02-14,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6311,21100444,2012-02-16,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6704,21100527,2012-03-01,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7039,21100594,2012-03-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7502,21100688,2012-03-21,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8075,21100805,2012-04-04,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8175,21100822,2012-04-06,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NWT - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8223,21100830,2012-04-07,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8288,21100847,2012-04-09,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11962,21200677,2013-01-30,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12027,21200691,2013-02-01,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12136,21200713,2013-02-04,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12227,21200731,2013-02-06,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12273,21200742,2013-02-08,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12360,21200763,2013-02-11,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12398,21200771,2013-02-12,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12550,21200805,2013-02-20,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12654,21200832,2013-02-24,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12734,21200849,2013-02-26,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13452,21201000,2013-03-18,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13551,21201021,2013-03-21,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13769,21201066,2013-03-27,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13846,21201081,2013-03-29,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13976,21201105,2013-04-01,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14031,21201116,2013-04-03,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14110,21201132,2013-04-05,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14151,21201141,2013-04-06,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14419,21201193,2013-04-13,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17329,21300586,2014-01-17,1610612738,2013-14,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17409,21300602,2014-01-19,1610612738,2013-14,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23341,21400690,2015-01-28,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23400,21400703,2015-01-30,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23511,21400729,2015-02-03,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24841,21401022,2015-03-20,1610612749,2014-15,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24986,21401055,2015-03-24,1610612749,2014-15,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25575,21401185,2015-04-10,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25840,21500007,2015-10-28,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26151,21500091,2015-11-07,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26298,21500124,2015-11-12,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26875,21500259,2015-11-30,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27136,21500318,2015-12-08,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27246,21500341,2015-12-11,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27308,21500356,2015-12-13,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27459,21500395,2015-12-18,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27625,21500434,2015-12-23,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30616,21501119,2016-03-30,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30949,21501187,2016-04-08,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31050,21501210,2016-04-11,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41596,41000161,2011-04-16,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41602,41000162,2011-04-19,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1]) & (df_5bsa1018.PLAYER_ID == 202419.0)]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
2262,21000661,2011-01-24,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2327,21000680,2011-01-27,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3169,21000905,2011-03-02,1610612738,2010-11,BOS,Boston,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3487,21001002,2011-03-15,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3594,21001034,2011-03-19,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3629,21001043,2011-03-20,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3748,21001078,2011-03-25,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3806,21001092,2011-03-27,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3841,21001099,2011-03-28,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3898,21001114,2011-03-30,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3940,21001130,2011-04-01,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4469,21100037,2011-12-29,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4572,21100065,2012-01-01,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4640,21100079,2012-01-03,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4703,21100097,2012-01-05,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4897,21100140,2012-01-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4961,21100152,2012-01-11,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5070,21100176,2012-01-14,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5131,21100190,2012-01-16,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5229,21100208,2012-01-18,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5274,21100216,2012-01-20,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5506,21100269,2012-01-25,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5650,21100305,2012-01-30,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5753,21100329,2012-02-02,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5927,21100366,2012-02-06,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6018,21100383,2012-02-08,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6090,21100397,2012-02-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6132,21100405,2012-02-11,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6229,21100427,2012-02-14,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6311,21100444,2012-02-16,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6704,21100527,2012-03-01,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7039,21100594,2012-03-10,1610612757,2011-12,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7502,21100688,2012-03-21,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8075,21100805,2012-04-04,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8175,21100822,2012-04-06,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,NWT - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8223,21100830,2012-04-07,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8288,21100847,2012-04-09,1610612740,2011-12,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11962,21200677,2013-01-30,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12136,21200713,2013-02-04,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12227,21200731,2013-02-06,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12360,21200763,2013-02-11,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12550,21200805,2013-02-20,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12654,21200832,2013-02-24,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12734,21200849,2013-02-26,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13452,21201000,2013-03-18,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13551,21201021,2013-03-21,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13769,21201066,2013-03-27,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13846,21201081,2013-03-29,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13976,21201105,2013-04-01,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14031,21201116,2013-04-03,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14110,21201132,2013-04-05,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14151,21201141,2013-04-06,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14419,21201193,2013-04-13,1610612750,2012-13,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41596,41000161,2011-04-16,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41602,41000162,2011-04-19,1610612757,2010-11,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1]) & (df_5bsa1018.PLAYER_ID == 203187.0)]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
12027,21200691,2013-02-01,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12273,21200742,2013-02-08,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12398,21200771,2013-02-12,1610612763,2012-13,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17329,21300586,2014-01-17,1610612738,2013-14,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17409,21300602,2014-01-19,1610612738,2013-14,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23341,21400690,2015-01-28,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23400,21400703,2015-01-30,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23511,21400729,2015-02-03,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24841,21401022,2015-03-20,1610612749,2014-15,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24986,21401055,2015-03-24,1610612749,2014-15,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25575,21401185,2015-04-10,1610612762,2014-15,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25840,21500007,2015-10-28,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26151,21500091,2015-11-07,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26298,21500124,2015-11-12,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26875,21500259,2015-11-30,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27136,21500318,2015-12-08,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27246,21500341,2015-12-11,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27308,21500356,2015-12-13,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27459,21500395,2015-12-18,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27625,21500434,2015-12-23,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30616,21501119,2016-03-30,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30949,21501187,2016-04-08,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31050,21501210,2016-04-11,1610612762,2015-16,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1])][['PLAYER_ID', 'PLAYER_NAME']].value_counts('PLAYER_ID')

PLAYER_ID
202419.0    55
203187.0    23
dtype: int64

In [27]:
#different players
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[2])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
14736,21300026,2013-11-01,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14798,21300041,2013-11-03,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14853,21300053,2013-11-05,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14964,21300078,2013-11-08,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15088,21300105,2013-11-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15216,21300135,2013-11-15,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15322,21300157,2013-11-19,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15359,21300166,2013-11-20,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15431,21300180,2013-11-22,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15661,21300233,2013-11-29,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15813,21300264,2013-12-03,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15851,21300272,2013-12-04,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15932,21300292,2013-12-07,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16083,21300323,2013-12-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16147,21300334,2013-12-13,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16247,21300356,2013-12-16,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16332,21300373,2013-12-18,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16407,21300386,2013-12-20,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17373,21300595,2014-01-18,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17427,21300607,2014-01-20,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17536,21300628,2014-01-22,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17590,21300639,2014-01-24,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17762,21300677,2014-04-08,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18347,21300795,2014-02-18,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18729,21300876,2014-03-01,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18810,21300892,2014-03-03,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18876,21300909,2014-03-05,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18919,21300922,2014-03-07,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18924,21300923,2014-03-07,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18977,21300937,2014-03-09,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19023,21300947,2014-03-10,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19041,21300951,2014-03-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19116,21300969,2014-03-13,1610612749,2013-14,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19186,21300984,2014-03-15,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19325,21301015,2014-03-19,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19376,21301029,2014-03-21,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19417,21301039,2014-03-22,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19542,21301064,2014-03-26,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19718,21301104,2014-03-31,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19771,21301114,2014-04-02,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19865,21301134,2014-04-04,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19925,21301146,2014-04-05,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20106,21301181,2014-04-11,1610612765,2013-14,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20423,21400011,2014-10-29,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20444,21400017,2014-10-30,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20519,21400033,2014-11-01,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20645,21400061,2014-11-05,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20705,21400076,2014-11-07,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20782,21400091,2014-11-09,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20833,21400101,2014-11-10,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20873,21400109,2014-11-12,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20956,21400129,2014-11-14,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20989,21400136,2014-11-15,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21042,21400150,2014-11-17,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21121,21400165,2014-11-19,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21154,21400174,2014-11-21,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21287,21400207,2014-11-25,1610612765,2014-15,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22450,21400469,2014-12-30,1610612756,2014-15,PHX,Phoenix,203502.0,Tony Mitchell,NaN,NWT - Not With Team,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[2]) & (df_5bsa1018.PLAYER_ID == 203502.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID    PLAYER_NAME TEAM_CITY
14736   203502.0  Tony Mitchell   Detroit
14798   203502.0  Tony Mitchell   Detroit
14853   203502.0  Tony Mitchell   Detroit
14964   203502.0  Tony Mitchell   Detroit
15088   203502.0  Tony Mitchell   Detroit
15216   203502.0  Tony Mitchell   Detroit
15322   203502.0  Tony Mitchell   Detroit
15359   203502.0  Tony Mitchell   Detroit
15431   203502.0  Tony Mitchell   Detroit
15661   203502.0  Tony Mitchell   Detroit
15813   203502.0  Tony Mitchell   Detroit
15851   203502.0  Tony Mitchell   Detroit
15932   203502.0  Tony Mitchell   Detroit
16083   203502.0  Tony Mitchell   Detroit
16147   203502.0  Tony Mitchell   Detroit
16247   203502.0  Tony Mitchell   Detroit
16332   203502.0  Tony Mitchell   Detroit
16407   203502.0  Tony Mitchell   Detroit
17373   203502.0  Tony Mitchell   Detroit
17427   203502.0  Tony Mitchell   Detroit
17536   203502.0  Tony Mitchell   Detroit
17590   203502.0  Tony Mitchell   Detroit
17762   203502.0  Tony Mitchell   Detroit
18347   203502.0  Tony Mitchell   Detroit
18729   203502.0  Tony Mitchell   Detroit
18810   203502.0  Tony Mitchell   Detroit
18876   203502.0  Tony Mitchell   Detroit
18919   203502.0  Tony Mitchell   Detroit
18977   203502.0  Tony Mitchell   Detroit
19041   203502.0  Tony Mitchell   Detroit
19186   203502.0  Tony Mitchell   Detroit
19325   203502.0  Tony Mitchell   Detroit
19376   203502.0  Tony Mitchell   Detroit
19417   203502.0  Tony Mitchell   Detroit
19542   203502.0  Tony Mitchell   Detroit
19718   203502.0  Tony Mitchell   Detroit
19771   203502.0  Tony Mitchell   Detroit
19865   203502.0  Tony Mitchell   Detroit
19925   203502.0  Tony Mitchell   Detroit
20106   203502.0  Tony Mitchell   Detroit
20423   203502.0  Tony Mitchell   Detroit
20444   203502.0  Tony Mitchell   Detroit
20519   203502.0  Tony Mitchell   Detroit
20645   203502.0  Tony Mitchell   Detroit
20705   203502.0  Tony Mitchell   Detroit
20782   203502.0  Tony Mitchell   Detroit
20833   203502.0  Tony Mitchell   Detroit
20873   203502.0  Tony Mitchell   Detroit
20956   203502.0  Tony Mitchell   Detroit
20989   203502.0  Tony Mitchell   Detroit
21042   203502.0  Tony Mitchell   Detroit
21121   203502.0  Tony Mitchell   Detroit
21154   203502.0  Tony Mitchell   Detroit
21287   203502.0  Tony Mitchell   Detroit
22450   203502.0  Tony Mitchell   Phoenix

In [29]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[2]) & (df_5bsa1018.PLAYER_ID == 203183.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID    PLAYER_NAME  TEAM_CITY
18924   203183.0  Tony Mitchell  Milwaukee
19023   203183.0  Tony Mitchell  Milwaukee
19116   203183.0  Tony Mitchell  Milwaukee

In [30]:
#two different players
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[3])]

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
4449,21100032,2011-12-28,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4580,21100066,2012-01-02,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4989,21100158,2012-01-12,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5173,21100196,2012-01-17,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5221,21100206,2012-01-18,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5960,21100372,2012-02-07,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6197,21100419,2012-02-13,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6292,21100440,2012-02-15,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6378,21100458,2012-02-18,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6482,21100480,2012-02-20,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6562,21100496,2012-02-22,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6657,21100516,2012-02-29,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7122,21100610,2012-03-11,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7263,21100637,2012-03-14,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7376,21100661,2012-03-17,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7449,21100675,2012-03-19,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7506,21100688,2012-03-21,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8084,21100806,2012-04-04,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8184,21100824,2012-04-06,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8800,21100948,2012-04-21,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8854,21100957,2012-04-22,1610612744,2011-12,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13282,21200967,2013-03-14,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13401,21200990,2013-03-17,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13587,21201029,2013-03-22,1610612742,2012-13,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19199,21300987,2014-03-16,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19273,21301005,2014-03-18,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19352,21301021,2014-03-20,1610612749,2013-14,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[3]) & (df_5bsa1018.PLAYER_ID == 202874.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID   PLAYER_NAME     TEAM_CITY
4449    202874.0  Chris Wright  Golden State
4580    202874.0  Chris Wright  Golden State
4989    202874.0  Chris Wright  Golden State
5173    202874.0  Chris Wright  Golden State
5221    202874.0  Chris Wright  Golden State
5960    202874.0  Chris Wright  Golden State
6197    202874.0  Chris Wright  Golden State
6292    202874.0  Chris Wright  Golden State
6378    202874.0  Chris Wright  Golden State
6482    202874.0  Chris Wright  Golden State
6562    202874.0  Chris Wright  Golden State
6657    202874.0  Chris Wright  Golden State
7122    202874.0  Chris Wright  Golden State
7263    202874.0  Chris Wright  Golden State
7376    202874.0  Chris Wright  Golden State
7449    202874.0  Chris Wright  Golden State
7506    202874.0  Chris Wright  Golden State
8084    202874.0  Chris Wright  Golden State
8184    202874.0  Chris Wright  Golden State
8800    202874.0  Chris Wright  Golden State
8854    202874.0  Chris Wright  Golden State
19199   202874.0  Chris Wright     Milwaukee
19273   202874.0  Chris Wright     Milwaukee
19352   202874.0  Chris Wright     Milwaukee

In [32]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[3]) & (df_5bsa1018.PLAYER_ID == 203203.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID   PLAYER_NAME TEAM_CITY
13282   203203.0  Chris Wright    Dallas
13401   203203.0  Chris Wright    Dallas
13587   203203.0  Chris Wright    Dallas

In [33]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [ ]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 'A12bsa_game_id_team_id_player_id_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_5bsa1018.to_csv(datapath_df, index=False)

In [ ]:
df = pd.read_csv(os.path.join('..', 'processed_data', 'A12bsa_game_id_team_id_player_id_2010_2018.csv'))
print(df.shape)
p(df)