In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
df_lost_contribution_mean_sum_max_cma5_12_999_diff = rcp('57Alost_contribution_mean_sum_max_cma5_cma12_cma999_diff_2010_2018.csv')
p(df_lost_contribution_mean_sum_max_cma5_12_999_diff)

(10266, 236)

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,w_pct_cma5_diff,away_home__cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,w_pct_cma12_diff,away_home__cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,w_pct_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000010,2010-10-27,2010-11,Regular Season,2010,1610612749,Bucks,Bucks,MIL,Milwaukee,L,MIL vs. NOH,MIL,NOH,1610612740,Hornets,Hornets,NOH,New Orleans,W,MIL vs. NOH,MIL,NOH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000004,2010-10-27,2010-11,Regular Season,2010,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,1.0000,1.0,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,1.000000,1.000000,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,1.000000,1.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,-31.999206,-153.530749,-146.182173,-134.628644,-130.924314,-18.884348,-15.260006,-0.139548,-0.775662,-12.872695,-0.018867,-0.145735,-0.074359,-12.977122,-0.456749,-0.489657,-0.197222,-0.207522,-138.793051,-146.674582,-122.227353,-66.118610,0.004319,-3.980618,-2.558975,-1.020145,5.667162,7.173202,-8.220550,-8.193097,0.000614,-0.113836,1.870235,0.026135,0.015662,0.027743,1.218917,0.081358,0.081835,0.014827,0.014220,0.488711,-1.638810,-1.365246,-8.250536,0.046982,-7.513777,-2.727645,-3.039995,4.122781,4.171058,-8.864994,-9.727559,-0.039914,-0.464904,2.149464,0.014621,-0.001195,0.015549,-0.421584,0.030801,0.027151,0.005149,0.005190,-0.279197,-5.509257,-4.589849,-15.204746,0.033940,0.0268,0.2,-17.318256,-71.996600,-64.240402,-63.700793,-58.430147,-8.278147,-5.808385,-0.068799,-0.089831,-2.772403,0.039147,-0.033314,0.009905,-6.041763,-0.015400,-0.038297,-0.078231,-0.084942,-71.399120,-81.103910,-67.584931,-35.069199,0.041897,-4.410990,-14.644223,-11.714746,-11.252869,-8.817884,-3.384485,-2.895616,-0.017252,-0.030880,-0.067059,0.025784,0.008561,0.021118,-1.052684,0.064973,0.055460,-0.008442,-0.010547,-15.028524,-18.908925,-15.756794,-8.844680,0.025662,-7.635114,-15.656687,-13.591320,-13.176070,-12.269733,-7.549719,-6.616691,-0.043466,-0.165660,1.113203,0.013021,0.000410,0.012991,-1.400942,0.000465,-0.000946,-0.011304,-0.012969,-15.599917,-22.878910,-19.064495,-15.391675,0.021606,0.136167,0.000000,-19.159105,-176.375992,-143.688463,-187.459589,-190.054513,11.103983,46.321370,-0.414678,-0.393730,-37.090801,0.122039,-0.386404,-0.198716,-32.279522,-0.310448,-0.295001,-0.193852,-0.177536,-203.337934,-215.991445,-179.987279,-38.751742,-0.108908,0.543754,6.052768,9.231191,3.825283,1.539100,2.231859,7.683247,-0.030797,0.085560,-1.494556,0.045985,-0.016340,0.005423,-1.940087,0.094303,0.110626,0.030743,0.035409,-4.515376,-5.345412,-4.453471,1.480317,0.013798,-4.444511,-30.752873,9.819569,-4.229659,-16.070646,-75.064537,-27.165498,-0.293530,-1.007473,-25.361786,0.124436,-0.015974,-0.050575,-4.150115,0.020393,0.046321,0.071337,0.092490,-0.850150,-9.866467,-8.220363,-8.135294,-0.130921,-0.018908,0.000000

In [3]:
column_names_list = list(df_lost_contribution_mean_sum_max_cma5_12_999_diff.columns)
pl(column_names_list)

236

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'team_id_a',
 'Team_a',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'team_id_b',
 'Team_b',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'lc_sum_MIN_cma5_diff',
 'lc_sum_E_OFF_RATING_cma5_diff',
 'lc_sum_OFF_RATING_cma5_diff',
 'lc_sum_E_DEF_RATING_cma5_diff',
 'lc_sum_DEF_RATING_cma5_diff',
 'lc_sum_E_NET_RATING_cma5_diff',
 'lc_sum_NET_RATING_cma5_diff',
 'lc_sum_AST_PCT_cma5_diff',
 'lc_sum_AST_TOV_cma5_diff',
 'lc_sum_AST_RATIO_cma5_diff',
 'lc_sum_OREB_PCT_cma5_diff',
 'lc_sum_DREB_PCT_cma5_diff',
 'lc_sum_REB_PCT_cma5_diff',
 'lc_sum_TM_TOV_PCT_cma5_diff',
 'lc_sum_EFG_PCT_cma5_diff',
 'lc_sum_TS_PCT_cma5_diff',
 'lc_sum_USG_PCT_cma5_diff',
 'lc_sum_E_USG_PCT_cma5_diff',
 'lc_sum_E_PACE_cma5_diff',
 'lc_sum_PACE_cma5_diff',
 'lc_sum_PACE_PER40_cma5_diff',
 'lc_sum_POSS_cma5_diff',
 'lc_sum_PIE_cma5_diff',
 'lc_mean_MIN_cma5_diff',
 'lc_mean_E_OFF_RATING_cma5_diff',
 'lc_mean_OFF_RATING_cma5_diff',
 'lc_mean_E_DEF_RATING_cma5_diff',
 'lc_mean_DEF_RATING_cma5_diff',
 'lc_mean_E_NET_RATING_cma5_diff',
 'lc_mean_NET_RATING_cma5_diff',
 'lc_mean_AST_PCT_cma5_diff',
 'lc_mean_AST_TOV_cma5_diff',
 'lc_mean_AST_RATIO_cma5_diff',
 'lc_mean_OREB_PCT_cma5_diff',
 'lc_mean_DREB_PCT_cma5_diff',
 'lc_mean_REB_PCT_cma5_diff',
 'lc_mean_TM_TOV_PCT_cma5_diff',
 'lc_mean_EFG_PCT_cma5_diff',
 'lc_mean_TS_PCT_cma5_diff',
 'lc_mean_USG_PCT_cma5_diff',
 'lc_mean_E_USG_PCT_cma5_diff',
 'lc_mean_E_PACE_cma5_diff',
 'lc_mean_PACE_cma5_diff',
 'lc_mean_PACE_PER40_cma5_diff',
 'lc_mean_POSS_cma5_diff',
 'lc_mean_PIE_cma5_diff',
 'lc_max_MIN_cma5_diff',
 'lc_max_E_OFF_RATING_cma5_diff',
 'lc_max_OFF_RATING_cma5_diff',
 'lc_max_E_DEF_RATING_cma5_diff',
 'lc_max_DEF_RATING_cma5_diff',
 'lc_max_E_NET_RATING_cma5_diff',
 'lc_max_NET_RATING_cma5_diff',
 'lc_max_AST_PCT_cma5_diff',
 'lc_max_AST_TOV_cma5_diff',
 'lc_max_AST_RATIO_cma5_diff',
 'lc_max_OREB_PCT_cma5_diff',
 'lc_max_DREB_PCT_cma5_diff',
 'lc_max_REB_PCT_cma5_diff',
 'lc_max_TM_TOV_PCT_cma5_diff',
 'lc_max_EFG_PCT_cma5_diff',
 'lc_max_TS_PCT_cma5_diff',
 'lc_max_USG_PCT_cma5_diff',
 'lc_max_E_USG_PCT_cma5_diff',
 'lc_max_E_PACE_cma5_diff',
 'lc_max_PACE_cma5_diff',
 'lc_max_PACE_PER40_cma5_diff',
 'lc_max_POSS_cma5_diff',
 'lc_max_PIE_cma5_diff',
 'w_pct_cma5_diff',
 'away_home__cma5_diff',
 'lc_sum_MIN_cma12_diff',
 'lc_sum_E_OFF_RATING_cma12_diff',
 'lc_sum_OFF_RATING_cma12_diff',
 'lc_sum_E_DEF_RATING_cma12_diff',
 'lc_sum_DEF_RATING_cma12_diff',
 'lc_sum_E_NET_RATING_cma12_diff',
 'lc_sum_NET_RATING_cma12_diff',
 'lc_sum_AST_PCT_cma12_diff',
 'lc_sum_AST_TOV_cma12_diff',
 'lc_sum_AST_RATIO_cma12_diff',
 'lc_sum_OREB_PCT_cma12_diff',
 'lc_sum_DREB_PCT_cma12_diff',
 'lc_sum_REB_PCT_cma12_diff',
 'lc_sum_TM_TOV_PCT_cma12_diff',
 'lc_sum_EFG_PCT_cma12_diff',
 'lc_sum_TS_PCT_cma12_diff',
 'lc_sum_USG_PCT_cma12_diff',
 'lc_sum_E_USG_PCT_cma12_diff',
 'lc_sum_E_PACE_cma12_diff',
 'lc_sum_PACE_cma12_diff',
 'lc_sum_PACE_PER40_cma12_diff',
 'lc_sum_POSS_cma12_diff',
 'lc_sum_PIE_cma12_diff',
 'lc_mean_MIN_cma12_diff',
 'lc_mean_E_OFF_RATING_cma12_diff',
 'lc_mean_OFF_RATING_cma12_diff',
 'lc_mean_E_DEF_RATING_cma12_diff',
 'lc_mean_DEF_RATING_cma12_diff',
 'lc_mean_E_NET_RATING_cma12_diff',
 'lc_mean_NET_RATING_cma12_diff',
 'lc_mean_AST_PCT_cma12_diff',
 'lc_mean_AST_TOV_cma12_diff',
 'lc_mean_AST_RATIO_cma12_diff',
 'lc_mean_OREB_PCT_cma12_diff',
 'lc_mean_DREB_PCT_cma12_diff',
 'lc_mean_REB_PCT_cma12_diff',
 'lc_mean_TM_TOV_PCT_cma12_diff',
 'lc_mean_EFG_PCT_cma12_diff',
 'lc_mean_TS_PCT_cma12_diff',
 'lc_mean_USG_PCT_cma12_diff',
 'lc_mean_E_USG_PCT_cma12_diff',
 'lc_mean_E_PACE_cma12_diff',
 'lc_mean_PACE_cma12_diff',
 'lc_mean_PACE_PER40_cma12_diff',
 'lc_mean_POSS_cma12_diff',
 'lc_mean_PIE_cma12_diff',
 'lc_max_MIN_cma12_diff',
 'lc_max_E_OFF_RATING_cma12_diff',
 'lc_max_OFF_RATING_cma12_diff',
 'lc_max_E_DEF_RATING_cma12_diff',
 'lc_max_DEF_RATING_cma12_diff',
 'lc_max_E_NET_RATING_cma12_diff',
 'lc_max_NET_RATING_cma12_diff',
 'lc_max_AST_PCT_cma12_diff',
 'lc_max_AST_TOV_cma12_diff',
 'lc_max_AST_RATIO_cma12_diff',
 'lc_max_OREB_PCT_cma12_diff',
 'lc_max_DREB_PCT_cma12_diff',
 'lc_max_REB_PCT_cma12_diff',
 'lc_max_TM_TOV_PCT_cma12_diff',
 'lc_max_EFG_PCT_cma12_diff',
 'lc_max_TS_PCT_cma12_diff',
 'lc_max_USG_PCT_cma12_diff',
 'lc_max_E_USG_PCT_cma12_diff',
 'lc_max_E_PACE_cma12_diff',
 'lc_max_PACE_cma12_diff',
 'lc_max_PACE_PER40_cma12_diff',
 'lc_max_POSS_cma12_diff',
 'lc_max_PIE_cma12_diff',
 'w_pct_cma12_diff',
 'away_home__cma12_diff',
 'lc_sum_MIN_cma999_diff',
 'lc_sum_E_OFF_RATING_cma999_diff',
 'lc_sum_OFF_RATING_cma999_diff',
 'lc_sum_E_DEF_RATING_cma999_diff',
 'lc_sum_DEF_RATING_cma999_diff',
 'lc_sum_E_NET_RATING_cma999_diff',
 'lc_sum_NET_RATING_cma999_diff',
 'lc_sum_AST_PCT_cma999_diff',
 'lc_sum_AST_TOV_cma999_diff',
 'lc_sum_AST_RATIO_cma999_diff',
 'lc_sum_OREB_PCT_cma999_diff',
 'lc_sum_DREB_PCT_cma999_diff',
 'lc_sum_REB_PCT_cma999_diff',
 'lc_sum_TM_TOV_PCT_cma999_diff',
 'lc_sum_EFG_PCT_cma999_diff',
 'lc_sum_TS_PCT_cma999_diff',
 'lc_sum_USG_PCT_cma999_diff',
 'lc_sum_E_USG_PCT_cma999_diff',
 'lc_sum_E_PACE_cma999_diff',
 'lc_sum_PACE_cma999_diff',
 'lc_sum_PACE_PER40_cma999_diff',
 'lc_sum_POSS_cma999_diff',
 'lc_sum_PIE_cma999_diff',
 'lc_mean_MIN_cma999_diff',
 'lc_mean_E_OFF_RATING_cma999_diff',
 'lc_mean_OFF_RATING_cma999_diff',
 'lc_mean_E_DEF_RATING_cma999_diff',
 'lc_mean_DEF_RATING_cma999_diff',
 'lc_mean_E_NET_RATING_cma999_diff',
 'lc_mean_NET_RATING_cma999_diff',
 'lc_mean_AST_PCT_cma999_diff',
 'lc_mean_AST_TOV_cma999_diff',
 'lc_mean_AST_RATIO_cma999_diff',
 'lc_mean_OREB_PCT_cma999_diff',
 'lc_mean_DREB_PCT_cma999_diff',
 'lc_mean_REB_PCT_cma999_diff',
 'lc_mean_TM_TOV_PCT_cma999_diff',
 'lc_mean_EFG_PCT_cma999_diff',
 'lc_mean_TS_PCT_cma999_diff',
 'lc_mean_USG_PCT_cma999_diff',
 'lc_mean_E_USG_PCT_cma999_diff',
 'lc_mean_E_PACE_cma999_diff',
 'lc_mean_PACE_cma999_diff',
 'lc_mean_PACE_PER40_cma999_diff',
 'lc_mean_POSS_cma999_diff',
 'lc_mean_PIE_cma999_diff',
 'lc_max_MIN_cma999_diff',
 'lc_max_E_OFF_RATING_cma999_diff',
 'lc_max_OFF_RATING_cma999_diff',
 'lc_max_E_DEF_RATING_cma999_diff',
 'lc_max_DEF_RATING_cma999_diff',
 'lc_max_E_NET_RATING_cma999_diff',
 'lc_max_NET_RATING_cma999_diff',
 'lc_max_AST_PCT_cma999_diff',
 'lc_max_AST_TOV_cma999_diff',
 'lc_max_AST_RATIO_cma999_diff',
 'lc_max_OREB_PCT_cma999_diff',
 'lc_max_DREB_PCT_cma999_diff',
 'lc_max_REB_PCT_cma999_diff',
 'lc_max_TM_TOV_PCT_cma999_diff',
 'lc_max_EFG_PCT_cma999_diff',
 'lc_max_TS_PCT_cma999_diff',
 'lc_max_USG_PCT_cma999_diff',
 'lc_max_E_USG_PCT_cma999_diff',
 'lc_max_E_PACE_cma999_diff',
 'lc_max_PACE_cma999_diff',
 'lc_max_PACE_PER40_cma999_diff',
 'lc_max_POSS_cma999_diff',
 'lc_max_PIE_cma999_diff',
 'w_pct_cma999_diff',
 'away_home__cma999_diff']

In [4]:
column_names_list_diff = [k for k in column_names_list if k.endswith('_diff')]
pl(column_names_list_diff)

213

['lc_sum_MIN_cma5_diff',
 'lc_sum_E_OFF_RATING_cma5_diff',
 'lc_sum_OFF_RATING_cma5_diff',
 'lc_sum_E_DEF_RATING_cma5_diff',
 'lc_sum_DEF_RATING_cma5_diff',
 'lc_sum_E_NET_RATING_cma5_diff',
 'lc_sum_NET_RATING_cma5_diff',
 'lc_sum_AST_PCT_cma5_diff',
 'lc_sum_AST_TOV_cma5_diff',
 'lc_sum_AST_RATIO_cma5_diff',
 'lc_sum_OREB_PCT_cma5_diff',
 'lc_sum_DREB_PCT_cma5_diff',
 'lc_sum_REB_PCT_cma5_diff',
 'lc_sum_TM_TOV_PCT_cma5_diff',
 'lc_sum_EFG_PCT_cma5_diff',
 'lc_sum_TS_PCT_cma5_diff',
 'lc_sum_USG_PCT_cma5_diff',
 'lc_sum_E_USG_PCT_cma5_diff',
 'lc_sum_E_PACE_cma5_diff',
 'lc_sum_PACE_cma5_diff',
 'lc_sum_PACE_PER40_cma5_diff',
 'lc_sum_POSS_cma5_diff',
 'lc_sum_PIE_cma5_diff',
 'lc_mean_MIN_cma5_diff',
 'lc_mean_E_OFF_RATING_cma5_diff',
 'lc_mean_OFF_RATING_cma5_diff',
 'lc_mean_E_DEF_RATING_cma5_diff',
 'lc_mean_DEF_RATING_cma5_diff',
 'lc_mean_E_NET_RATING_cma5_diff',
 'lc_mean_NET_RATING_cma5_diff',
 'lc_mean_AST_PCT_cma5_diff',
 'lc_mean_AST_TOV_cma5_diff',
 'lc_mean_AST_RATIO_cma5_diff',
 'lc_mean_OREB_PCT_cma5_diff',
 'lc_mean_DREB_PCT_cma5_diff',
 'lc_mean_REB_PCT_cma5_diff',
 'lc_mean_TM_TOV_PCT_cma5_diff',
 'lc_mean_EFG_PCT_cma5_diff',
 'lc_mean_TS_PCT_cma5_diff',
 'lc_mean_USG_PCT_cma5_diff',
 'lc_mean_E_USG_PCT_cma5_diff',
 'lc_mean_E_PACE_cma5_diff',
 'lc_mean_PACE_cma5_diff',
 'lc_mean_PACE_PER40_cma5_diff',
 'lc_mean_POSS_cma5_diff',
 'lc_mean_PIE_cma5_diff',
 'lc_max_MIN_cma5_diff',
 'lc_max_E_OFF_RATING_cma5_diff',
 'lc_max_OFF_RATING_cma5_diff',
 'lc_max_E_DEF_RATING_cma5_diff',
 'lc_max_DEF_RATING_cma5_diff',
 'lc_max_E_NET_RATING_cma5_diff',
 'lc_max_NET_RATING_cma5_diff',
 'lc_max_AST_PCT_cma5_diff',
 'lc_max_AST_TOV_cma5_diff',
 'lc_max_AST_RATIO_cma5_diff',
 'lc_max_OREB_PCT_cma5_diff',
 'lc_max_DREB_PCT_cma5_diff',
 'lc_max_REB_PCT_cma5_diff',
 'lc_max_TM_TOV_PCT_cma5_diff',
 'lc_max_EFG_PCT_cma5_diff',
 'lc_max_TS_PCT_cma5_diff',
 'lc_max_USG_PCT_cma5_diff',
 'lc_max_E_USG_PCT_cma5_diff',
 'lc_max_E_PACE_cma5_diff',
 'lc_max_PACE_cma5_diff',
 'lc_max_PACE_PER40_cma5_diff',
 'lc_max_POSS_cma5_diff',
 'lc_max_PIE_cma5_diff',
 'w_pct_cma5_diff',
 'away_home__cma5_diff',
 'lc_sum_MIN_cma12_diff',
 'lc_sum_E_OFF_RATING_cma12_diff',
 'lc_sum_OFF_RATING_cma12_diff',
 'lc_sum_E_DEF_RATING_cma12_diff',
 'lc_sum_DEF_RATING_cma12_diff',
 'lc_sum_E_NET_RATING_cma12_diff',
 'lc_sum_NET_RATING_cma12_diff',
 'lc_sum_AST_PCT_cma12_diff',
 'lc_sum_AST_TOV_cma12_diff',
 'lc_sum_AST_RATIO_cma12_diff',
 'lc_sum_OREB_PCT_cma12_diff',
 'lc_sum_DREB_PCT_cma12_diff',
 'lc_sum_REB_PCT_cma12_diff',
 'lc_sum_TM_TOV_PCT_cma12_diff',
 'lc_sum_EFG_PCT_cma12_diff',
 'lc_sum_TS_PCT_cma12_diff',
 'lc_sum_USG_PCT_cma12_diff',
 'lc_sum_E_USG_PCT_cma12_diff',
 'lc_sum_E_PACE_cma12_diff',
 'lc_sum_PACE_cma12_diff',
 'lc_sum_PACE_PER40_cma12_diff',
 'lc_sum_POSS_cma12_diff',
 'lc_sum_PIE_cma12_diff',
 'lc_mean_MIN_cma12_diff',
 'lc_mean_E_OFF_RATING_cma12_diff',
 'lc_mean_OFF_RATING_cma12_diff',
 'lc_mean_E_DEF_RATING_cma12_diff',
 'lc_mean_DEF_RATING_cma12_diff',
 'lc_mean_E_NET_RATING_cma12_diff',
 'lc_mean_NET_RATING_cma12_diff',
 'lc_mean_AST_PCT_cma12_diff',
 'lc_mean_AST_TOV_cma12_diff',
 'lc_mean_AST_RATIO_cma12_diff',
 'lc_mean_OREB_PCT_cma12_diff',
 'lc_mean_DREB_PCT_cma12_diff',
 'lc_mean_REB_PCT_cma12_diff',
 'lc_mean_TM_TOV_PCT_cma12_diff',
 'lc_mean_EFG_PCT_cma12_diff',
 'lc_mean_TS_PCT_cma12_diff',
 'lc_mean_USG_PCT_cma12_diff',
 'lc_mean_E_USG_PCT_cma12_diff',
 'lc_mean_E_PACE_cma12_diff',
 'lc_mean_PACE_cma12_diff',
 'lc_mean_PACE_PER40_cma12_diff',
 'lc_mean_POSS_cma12_diff',
 'lc_mean_PIE_cma12_diff',
 'lc_max_MIN_cma12_diff',
 'lc_max_E_OFF_RATING_cma12_diff',
 'lc_max_OFF_RATING_cma12_diff',
 'lc_max_E_DEF_RATING_cma12_diff',
 'lc_max_DEF_RATING_cma12_diff',
 'lc_max_E_NET_RATING_cma12_diff',
 'lc_max_NET_RATING_cma12_diff',
 'lc_max_AST_PCT_cma12_diff',
 'lc_max_AST_TOV_cma12_diff',
 'lc_max_AST_RATIO_cma12_diff',
 'lc_max_OREB_PCT_cma12_diff',
 'lc_max_DREB_PCT_cma12_diff',
 'lc_max_REB_PCT_cma12_diff',
 'lc_max_TM_TOV_PCT_cma12_diff',
 'lc_max_EFG_PCT_cma12_diff',
 'lc_max_TS_PCT_cma12_diff',
 'lc_max_USG_PCT_cma12_diff',
 'lc_max_E_USG_PCT_cma12_diff',
 'lc_max_E_PACE_cma12_diff',
 'lc_max_PACE_cma12_diff',
 'lc_max_PACE_PER40_cma12_diff',
 'lc_max_POSS_cma12_diff',
 'lc_max_PIE_cma12_diff',
 'w_pct_cma12_diff',
 'away_home__cma12_diff',
 'lc_sum_MIN_cma999_diff',
 'lc_sum_E_OFF_RATING_cma999_diff',
 'lc_sum_OFF_RATING_cma999_diff',
 'lc_sum_E_DEF_RATING_cma999_diff',
 'lc_sum_DEF_RATING_cma999_diff',
 'lc_sum_E_NET_RATING_cma999_diff',
 'lc_sum_NET_RATING_cma999_diff',
 'lc_sum_AST_PCT_cma999_diff',
 'lc_sum_AST_TOV_cma999_diff',
 'lc_sum_AST_RATIO_cma999_diff',
 'lc_sum_OREB_PCT_cma999_diff',
 'lc_sum_DREB_PCT_cma999_diff',
 'lc_sum_REB_PCT_cma999_diff',
 'lc_sum_TM_TOV_PCT_cma999_diff',
 'lc_sum_EFG_PCT_cma999_diff',
 'lc_sum_TS_PCT_cma999_diff',
 'lc_sum_USG_PCT_cma999_diff',
 'lc_sum_E_USG_PCT_cma999_diff',
 'lc_sum_E_PACE_cma999_diff',
 'lc_sum_PACE_cma999_diff',
 'lc_sum_PACE_PER40_cma999_diff',
 'lc_sum_POSS_cma999_diff',
 'lc_sum_PIE_cma999_diff',
 'lc_mean_MIN_cma999_diff',
 'lc_mean_E_OFF_RATING_cma999_diff',
 'lc_mean_OFF_RATING_cma999_diff',
 'lc_mean_E_DEF_RATING_cma999_diff',
 'lc_mean_DEF_RATING_cma999_diff',
 'lc_mean_E_NET_RATING_cma999_diff',
 'lc_mean_NET_RATING_cma999_diff',
 'lc_mean_AST_PCT_cma999_diff',
 'lc_mean_AST_TOV_cma999_diff',
 'lc_mean_AST_RATIO_cma999_diff',
 'lc_mean_OREB_PCT_cma999_diff',
 'lc_mean_DREB_PCT_cma999_diff',
 'lc_mean_REB_PCT_cma999_diff',
 'lc_mean_TM_TOV_PCT_cma999_diff',
 'lc_mean_EFG_PCT_cma999_diff',
 'lc_mean_TS_PCT_cma999_diff',
 'lc_mean_USG_PCT_cma999_diff',
 'lc_mean_E_USG_PCT_cma999_diff',
 'lc_mean_E_PACE_cma999_diff',
 'lc_mean_PACE_cma999_diff',
 'lc_mean_PACE_PER40_cma999_diff',
 'lc_mean_POSS_cma999_diff',
 'lc_mean_PIE_cma999_diff',
 'lc_max_MIN_cma999_diff',
 'lc_max_E_OFF_RATING_cma999_diff',
 'lc_max_OFF_RATING_cma999_diff',
 'lc_max_E_DEF_RATING_cma999_diff',
 'lc_max_DEF_RATING_cma999_diff',
 'lc_max_E_NET_RATING_cma999_diff',
 'lc_max_NET_RATING_cma999_diff',
 'lc_max_AST_PCT_cma999_diff',
 'lc_max_AST_TOV_cma999_diff',
 'lc_max_AST_RATIO_cma999_diff',
 'lc_max_OREB_PCT_cma999_diff',
 'lc_max_DREB_PCT_cma999_diff',
 'lc_max_REB_PCT_cma999_diff',
 'lc_max_TM_TOV_PCT_cma999_diff',
 'lc_max_EFG_PCT_cma999_diff',
 'lc_max_TS_PCT_cma999_diff',
 'lc_max_USG_PCT_cma999_diff',
 'lc_max_E_USG_PCT_cma999_diff',
 'lc_max_E_PACE_cma999_diff',
 'lc_max_PACE_cma999_diff',
 'lc_max_PACE_PER40_cma999_diff',
 'lc_max_POSS_cma999_diff',
 'lc_max_PIE_cma999_diff',
 'w_pct_cma999_diff',
 'away_home__cma999_diff']

In [5]:
column_names_list_not_diff = [k for k in column_names_list if not k in column_names_list_diff]
pl(column_names_list_not_diff)

23

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'team_id_a',
 'Team_a',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'team_id_b',
 'Team_b',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b']

In [6]:
df_lost_contribution_mean_sum_max_cmax5_12_999_diff = rcp('57Blost_contribution_mean_sum_max_cmax5_cmax12_cmax999_diff_2010_2018.csv')
p(df_lost_contribution_mean_sum_max_cmax5_12_999_diff)

(10266, 236)

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cmax5_diff,lc_sum_E_OFF_RATING_cmax5_diff,lc_sum_OFF_RATING_cmax5_diff,lc_sum_E_DEF_RATING_cmax5_diff,lc_sum_DEF_RATING_cmax5_diff,lc_sum_E_NET_RATING_cmax5_diff,lc_sum_NET_RATING_cmax5_diff,lc_sum_AST_PCT_cmax5_diff,lc_sum_AST_TOV_cmax5_diff,lc_sum_AST_RATIO_cmax5_diff,lc_sum_OREB_PCT_cmax5_diff,lc_sum_DREB_PCT_cmax5_diff,lc_sum_REB_PCT_cmax5_diff,lc_sum_TM_TOV_PCT_cmax5_diff,lc_sum_EFG_PCT_cmax5_diff,lc_sum_TS_PCT_cmax5_diff,lc_sum_USG_PCT_cmax5_diff,lc_sum_E_USG_PCT_cmax5_diff,lc_sum_E_PACE_cmax5_diff,lc_sum_PACE_cmax5_diff,lc_sum_PACE_PER40_cmax5_diff,lc_sum_POSS_cmax5_diff,lc_sum_PIE_cmax5_diff,lc_mean_MIN_cmax5_diff,lc_mean_E_OFF_RATING_cmax5_diff,lc_mean_OFF_RATING_cmax5_diff,lc_mean_E_DEF_RATING_cmax5_diff,lc_mean_DEF_RATING_cmax5_diff,lc_mean_E_NET_RATING_cmax5_diff,lc_mean_NET_RATING_cmax5_diff,lc_mean_AST_PCT_cmax5_diff,lc_mean_AST_TOV_cmax5_diff,lc_mean_AST_RATIO_cmax5_diff,lc_mean_OREB_PCT_cmax5_diff,lc_mean_DREB_PCT_cmax5_diff,lc_mean_REB_PCT_cmax5_diff,lc_mean_TM_TOV_PCT_cmax5_diff,lc_mean_EFG_PCT_cmax5_diff,lc_mean_TS_PCT_cmax5_diff,lc_mean_USG_PCT_cmax5_diff,lc_mean_E_USG_PCT_cmax5_diff,lc_mean_E_PACE_cmax5_diff,lc_mean_PACE_cmax5_diff,lc_mean_PACE_PER40_cmax5_diff,lc_mean_POSS_cmax5_diff,lc_mean_PIE_cmax5_diff,lc_max_MIN_cmax5_diff,lc_max_E_OFF_RATING_cmax5_diff,lc_max_OFF_RATING_cmax5_diff,lc_max_E_DEF_RATING_cmax5_diff,lc_max_DEF_RATING_cmax5_diff,lc_max_E_NET_RATING_cmax5_diff,lc_max_NET_RATING_cmax5_diff,lc_max_AST_PCT_cmax5_diff,lc_max_AST_TOV_cmax5_diff,lc_max_AST_RATIO_cmax5_diff,lc_max_OREB_PCT_cmax5_diff,lc_max_DREB_PCT_cmax5_diff,lc_max_REB_PCT_cmax5_diff,lc_max_TM_TOV_PCT_cmax5_diff,lc_max_EFG_PCT_cmax5_diff,lc_max_TS_PCT_cmax5_diff,lc_max_USG_PCT_cmax5_diff,lc_max_E_USG_PCT_cmax5_diff,lc_max_E_PACE_cmax5_diff,lc_max_PACE_cmax5_diff,lc_max_PACE_PER40_cmax5_diff,lc_max_POSS_cmax5_diff,lc_max_PIE_cmax5_diff,w_pct_cmax5_diff,away_home__cmax5_diff,lc_sum_MIN_cmax12_diff,lc_sum_E_OFF_RATING_cmax12_diff,lc_sum_OFF_RATING_cmax12_diff,lc_sum_E_DEF_RATING_cmax12_diff,lc_sum_DEF_RATING_cmax12_diff,lc_sum_E_NET_RATING_cmax12_diff,lc_sum_NET_RATING_cmax12_diff,lc_sum_AST_PCT_cmax12_diff,lc_sum_AST_TOV_cmax12_diff,lc_sum_AST_RATIO_cmax12_diff,lc_sum_OREB_PCT_cmax12_diff,lc_sum_DREB_PCT_cmax12_diff,lc_sum_REB_PCT_cmax12_diff,lc_sum_TM_TOV_PCT_cmax12_diff,lc_sum_EFG_PCT_cmax12_diff,lc_sum_TS_PCT_cmax12_diff,lc_sum_USG_PCT_cmax12_diff,lc_sum_E_USG_PCT_cmax12_diff,lc_sum_E_PACE_cmax12_diff,lc_sum_PACE_cmax12_diff,lc_sum_PACE_PER40_cmax12_diff,lc_sum_POSS_cmax12_diff,lc_sum_PIE_cmax12_diff,lc_mean_MIN_cmax12_diff,lc_mean_E_OFF_RATING_cmax12_diff,lc_mean_OFF_RATING_cmax12_diff,lc_mean_E_DEF_RATING_cmax12_diff,lc_mean_DEF_RATING_cmax12_diff,lc_mean_E_NET_RATING_cmax12_diff,lc_mean_NET_RATING_cmax12_diff,lc_mean_AST_PCT_cmax12_diff,lc_mean_AST_TOV_cmax12_diff,lc_mean_AST_RATIO_cmax12_diff,lc_mean_OREB_PCT_cmax12_diff,lc_mean_DREB_PCT_cmax12_diff,lc_mean_REB_PCT_cmax12_diff,lc_mean_TM_TOV_PCT_cmax12_diff,lc_mean_EFG_PCT_cmax12_diff,lc_mean_TS_PCT_cmax12_diff,lc_mean_USG_PCT_cmax12_diff,lc_mean_E_USG_PCT_cmax12_diff,lc_mean_E_PACE_cmax12_diff,lc_mean_PACE_cmax12_diff,lc_mean_PACE_PER40_cmax12_diff,lc_mean_POSS_cmax12_diff,lc_mean_PIE_cmax12_diff,lc_max_MIN_cmax12_diff,lc_max_E_OFF_RATING_cmax12_diff,lc_max_OFF_RATING_cmax12_diff,lc_max_E_DEF_RATING_cmax12_diff,lc_max_DEF_RATING_cmax12_diff,lc_max_E_NET_RATING_cmax12_diff,lc_max_NET_RATING_cmax12_diff,lc_max_AST_PCT_cmax12_diff,lc_max_AST_TOV_cmax12_diff,lc_max_AST_RATIO_cmax12_diff,lc_max_OREB_PCT_cmax12_diff,lc_max_DREB_PCT_cmax12_diff,lc_max_REB_PCT_cmax12_diff,lc_max_TM_TOV_PCT_cmax12_diff,lc_max_EFG_PCT_cmax12_diff,lc_max_TS_PCT_cmax12_diff,lc_max_USG_PCT_cmax12_diff,lc_max_E_USG_PCT_cmax12_diff,lc_max_E_PACE_cmax12_diff,lc_max_PACE_cmax12_diff,lc_max_PACE_PER40_cmax12_diff,lc_max_POSS_cmax12_diff,lc_max_PIE_cmax12_diff,w_pct_cmax12_diff,away_home__cmax12_diff,lc_sum_MIN_cmax999_diff,lc_sum_E_OFF_RATING_cmax999_diff,lc_sum_OFF_RATING_cmax999_diff,lc_sum_E_DEF_RATING_cmax999_diff,lc_sum_DEF_RATING_cmax999_diff,lc_sum_E_NET_RATING_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_sum_AST_PCT_cmax999_diff,lc_sum_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cmax999_diff,lc_sum_OREB_PCT_cmax999_diff,lc_sum_DREB_PCT_cmax999_diff,lc_sum_REB_PCT_cmax999_diff,lc_sum_TM_TOV_PCT_cmax999_diff,lc_sum_EFG_PCT_cmax999_diff,lc_sum_TS_PCT_cmax999_diff,lc_sum_USG_PCT_cmax999_diff,lc_sum_E_USG_PCT_cmax999_diff,lc_sum_E_PACE_cmax999_diff,lc_sum_PACE_cmax999_diff,lc_sum_PACE_PER40_cmax999_diff,lc_sum_POSS_cmax999_diff,lc_sum_PIE_cmax999_diff,lc_mean_MIN_cmax999_diff,lc_mean_E_OFF_RATING_cmax999_diff,lc_mean_OFF_RATING_cmax999_diff,lc_mean_E_DEF_RATING_cmax999_diff,lc_mean_DEF_RATING_cmax999_diff,lc_mean_E_NET_RATING_cmax999_diff,lc_mean_NET_RATING_cmax999_diff,lc_mean_AST_PCT_cmax999_diff,lc_mean_AST_TOV_cmax999_diff,lc_mean_AST_RATIO_cmax999_diff,lc_mean_OREB_PCT_cmax999_diff,lc_mean_DREB_PCT_cmax999_diff,lc_mean_REB_PCT_cmax999_diff,lc_mean_TM_TOV_PCT_cmax999_diff,lc_mean_EFG_PCT_cmax999_diff,lc_mean_TS_PCT_cmax999_diff,lc_mean_USG_PCT_cmax999_diff,lc_mean_E_USG_PCT_cmax999_diff,lc_mean_E_PACE_cmax999_diff,lc_mean_PACE_cmax999_diff,lc_mean_PACE_PER40_cmax999_diff,lc_mean_POSS_cmax999_diff,lc_mean_PIE_cmax999_diff,lc_max_MIN_cmax999_diff,lc_max_E_OFF_RATING_cmax999_diff,lc_max_OFF_RATING_cmax999_diff,lc_max_E_DEF_RATING_cmax999_diff,lc_max_DEF_RATING_cmax999_diff,lc_max_E_NET_RATING_cmax999_diff,lc_max_NET_RATING_cmax999_diff,lc_max_AST_PCT_cmax999_diff,lc_max_AST_TOV_cmax999_diff,lc_max_AST_RATIO_cmax999_diff,lc_max_OREB_PCT_cmax999_diff,lc_max_DREB_PCT_cmax999_diff,lc_max_REB_PCT_cmax999_diff,lc_max_TM_TOV_PCT_cmax999_diff,lc_max_EFG_PCT_cmax999_diff,lc_max_TS_PCT_cmax999_diff,lc_max_USG_PCT_cmax999_diff,lc_max_E_USG_PCT_cmax999_diff,lc_max_E_PACE_cmax999_diff,lc_max_PACE_cmax999_diff,lc_max_PACE_PER40_cmax999_diff,lc_max_POSS_cmax999_diff,lc_max_PIE_cmax999_diff,w_pct_cmax999_diff,away_home__cmax999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,21000010,2010-10-27,2010-11,Regular Season,2010,1610612749,Bucks,Bucks,MIL,Milwaukee,L,MIL vs. NOH,MIL,NOH,1610612740,Hornets,Hornets,NOH,New Orleans,W,MIL vs. NOH,MIL,NOH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,21000004,2010-10-27,2010-11,Regular Season,2010,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,1.000,1.0,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,1.0,1.0,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,1.481089e-01,19.710891,5.715941e-01,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,1.0,1.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,-31.948673,-109.151965,-98.979454,-94.402230,-89.183634,-22.616881,-16.956396,0.068722,-0.820324,17.644481,0.053172,-0.020170,0.026934,-1.991514,-0.110714,-0.096724,-0.082978,-0.092316,-97.876966,-108.978378,-90.812980,-65.008336,0.184782,-5.069960,-4.099828,-4.888160,6.446684,7.993282,-9.966088,-11.142110,0.041745,-0.426288,6.588939,0.034118,-0.007934,0.023913,2.608358,0.053488,0.041562,0.032317,0.030474,0.555932,-3.389526,-2.823577,-10.295390,0.042337,-6.671675,-0.090411,-0.467123,2.432000,1.286521,-1.835065,-2.916438,-0.154905,-1.959141,3.055186,0.014494,0.024189,0.023600,3.767669,0.038209,0.014885,-0.027217,-0.029265,0.555932,-7.311272,-6.091037,-12.098559,-0.024860,0.067,0.0,-31.948673,-106.037969,-98.003668,-78.690689,-77.995414,-13.108673,-9.267824,0.068722,-0.748555,17.644481,0.053172,-0.020170,0.026934,-1.991514,-0.110714,-0.096724,-0.082978,-0.092316,-97.876966,-107.025283,-89.186194,-65.008336,0.184782,-6.737879,2.400759,2.458178,4.425437,5.466934,-11.736957,-8.752899,0.041745,-0.426288,5.515882,0.034118,0.046031,0.039737,0.136989,0.053488,0.041562,0.032317,0.030474,0.666142,-8.896986,-7.412466,-13.118571,0.042337,-6.671675,-0.090411,-0.467123,2.432000,2.662423,-8.489827,-5.452283,-0.154905,-1.922754,3.055186,0.015307,0.027043,0.027023,5.034921,0.038209,0.014885,-0.027217,-0.029265,0.723217,-8.179688,-6.815000,-12.098559,-0.024860,0.0,0.0,-85.229680,-207.745202,-248.601929,-128.203333,-247.940476,-71.306428,66.118527,-0.835839,-3.988929,-49.179248,0.429081,-0.088930,-0.076366,-44.796767,-1.558978,-0.928855,-0.183761,-0.152255,-213.650378,-195.763881,-163.146036,-163.362655,-1.705610,-0.254739,17.139394,23.715368,34.406667,15.427619,-9.302425,16.233550,-0.027539,-3.351022,-7.619909,0.114020,0.127070,0.034913,0.772200,0.161284,0.189373,0.251233,0.252291,0.309665,-5.647570,-4.704858,1.216602,-0.143975,-1.106753,-50.000000,75.000000,62.775000,1.525000,-210.880000,-25.000000,-0.696000,-6.676923,-60.492000,0.372276,0.500000,2.975398e-14,-16.666667,4.474199e-13,0.136000,0.583000,0.598000,4.960000,-10.720769,-8.933846,-0.010390,-1.468389,0.0,0.0

In [7]:
df_lost_contribution_mean_sum_max_cma5_12_999_diff_cmax5_12_999_diff = pd.merge(df_lost_contribution_mean_sum_max_cma5_12_999_diff, df_lost_contribution_mean_sum_max_cmax5_12_999_diff, on=column_names_list_not_diff)
p(df_lost_contribution_mean_sum_max_cma5_12_999_diff_cmax5_12_999_diff)

(10266, 449)

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,w_pct_cma5_diff,away_home__cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,w_pct_cma12_diff,away_home__cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,w_pct_cma999_diff,away_home__cma999_diff,lc_sum_MIN_cmax5_diff,lc_sum_E_OFF_RATING_cmax5_diff,lc_sum_OFF_RATING_cmax5_diff,lc_sum_E_DEF_RATING_cmax5_diff,lc_sum_DEF_RATING_cmax5_diff,lc_sum_E_NET_RATING_cmax5_diff,lc_sum_NET_RATING_cmax5_diff,lc_sum_AST_PCT_cmax5_diff,lc_sum_AST_TOV_cmax5_diff,lc_sum_AST_RATIO_cmax5_diff,lc_sum_OREB_PCT_cmax5_diff,lc_sum_DREB_PCT_cmax5_diff,lc_sum_REB_PCT_cmax5_diff,lc_sum_TM_TOV_PCT_cmax5_diff,lc_sum_EFG_PCT_cmax5_diff,lc_sum_TS_PCT_cmax5_diff,lc_sum_USG_PCT_cmax5_diff,lc_sum_E_USG_PCT_cmax5_diff,lc_sum_E_PACE_cmax5_diff,lc_sum_PACE_cmax5_diff,lc_sum_PACE_PER40_cmax5_diff,lc_sum_POSS_cmax5_diff,lc_sum_PIE_cmax5_diff,lc_mean_MIN_cmax5_diff,lc_mean_E_OFF_RATING_cmax5_diff,lc_mean_OFF_RATING_cmax5_diff,lc_mean_E_DEF_RATING_cmax5_diff,lc_mean_DEF_RATING_cmax5_diff,lc_mean_E_NET_RATING_cmax5_diff,lc_mean_NET_RATING_cmax5_diff,lc_mean_AST_PCT_cmax5_diff,lc_mean_AST_TOV_cmax5_diff,lc_mean_AST_RATIO_cmax5_diff,lc_mean_OREB_PCT_cmax5_diff,lc_mean_DREB_PCT_cmax5_diff,lc_mean_REB_PCT_cmax5_diff,lc_mean_TM_TOV_PCT_cmax5_diff,lc_mean_EFG_PCT_cmax5_diff,lc_mean_TS_PCT_cmax5_diff,lc_mean_USG_PCT_cmax5_diff,lc_mean_E_USG_PCT_cmax5_diff,lc_mean_E_PACE_cmax5_diff,lc_mean_PACE_cmax5_diff,lc_mean_PACE_PER40_cmax5_diff,lc_mean_POSS_cmax5_diff,lc_mean_PIE_cmax5_diff,lc_max_MIN_cmax5_diff,lc_max_E_OFF_RATING_cmax5_diff,lc_max_OFF_RATING_cmax5_diff,lc_max_E_DEF_RATING_cmax5_diff,lc_max_DEF_RATING_cmax5_diff,lc_max_E_NET_RATING_cmax5_diff,lc_max_NET_RATING_cmax5_diff,lc_max_AST_PCT_cmax5_diff,lc_max_AST_TOV_cmax5_diff,lc_max_AST_RATIO_cmax5_diff,lc_max_OREB_PCT_cmax5_diff,lc_max_DREB_PCT_cmax5_diff,lc_max_REB_PCT_cmax5_diff,lc_max_TM_TOV_PCT_cmax5_diff,lc_max_EFG_PCT_cmax5_diff,lc_max_TS_PCT_cmax5_diff,lc_max_USG_PCT_cmax5_diff,lc_max_E_USG_PCT_cmax5_diff,lc_max_E_PACE_cmax5_diff,lc_max_PACE_cmax5_diff,lc_max_PACE_PER40_cmax5_diff,lc_max_POSS_cmax5_diff,lc_max_PIE_cmax5_diff,w_pct_cmax5_diff,away_home__cmax5_diff,lc_sum_MIN_cmax12_diff,lc_sum_E_OFF_RATING_cmax12_diff,lc_sum_OFF_RATING_cmax12_diff,lc_sum_E_DEF_RATING_cmax12_diff,lc_sum_DEF_RATING_cmax12_diff,lc_sum_E_NET_RATING_cmax12_diff,lc_sum_NET_RATING_cmax12_diff,lc_sum_AST_PCT_cmax12_diff,lc_sum_AST_TOV_cmax12_diff,lc_sum_AST_RATIO_cmax12_diff,lc_sum_OREB_PCT_cmax12_diff,lc_sum_DREB_PCT_cmax12_diff,lc_sum_REB_PCT_cmax12_diff,lc_sum_TM_TOV_PCT_cmax12_diff,lc_sum_EFG_PCT_cmax12_diff,lc_sum_TS_PCT_cmax12_diff,lc_sum_USG_PCT_cmax12_diff,lc_sum_E_USG_PCT_cmax12_diff,lc_sum_E_PACE_cmax12_diff,lc_sum_PACE_cmax12_diff,lc_sum_PACE_PER40_cmax12_diff,lc_sum_POSS_cmax12_diff,lc_sum_PIE_cmax12_diff,lc_mean_MIN_cmax12_diff,lc_mean_E_OFF_RATING_cmax12_diff,lc_mean_OFF_RATING_cmax12_diff,lc_mean_E_DEF_RATING_cmax12_diff,lc_mean_DEF_RATING_cmax12_diff,lc_mean_E_NET_RATING_cmax12_diff,lc_mean_NET_RATING_cmax12_diff,lc_mean_AST_PCT_cmax12_diff,lc_mean_AST_TOV_cmax12_diff,lc_mean_AST_RATIO_cmax12_diff,lc_mean_OREB_PCT_cmax12_diff,lc_mean_DREB_PCT_cmax12_diff,lc_mean_REB_PCT_cmax12_diff,lc_mean_TM_TOV_PCT_cmax12_diff,lc_mean_EFG_PCT_cmax12_diff,lc_mean_TS_PCT_cmax12_diff,lc_mean_USG_PCT_cmax12_diff,lc_mean_E_USG_PCT_cmax12_diff,lc_mean_E_PACE_cmax12_diff,lc_mean_PACE_cmax12_diff,lc_mean_PACE_PER40_cmax12_diff,lc_mean_POSS_cmax12_diff,lc_mean_PIE_cmax12_diff,lc_max_MIN_cmax12_diff,lc_max_E_OFF_RATING_cmax12_diff,lc_max_OFF_RATING_cmax12_diff,lc_max_E_DEF_RATING_cmax12_diff,lc_max_DEF_RATING_cmax12_diff,lc_max_E_NET_RATING_cmax12_diff,lc_max_NET_RATING_cmax12_diff,lc_max_AST_PCT_cmax12_diff,lc_max_AST_TOV_cmax12_diff,lc_max_AST_RATIO_cmax12_diff,lc_max_OREB_PCT_cmax12_diff,lc_max_DREB_PCT_cmax12_diff,lc_max_REB_PCT_cmax12_diff,lc_max_TM_TOV_PCT_cmax12_diff,lc_max_EFG_PCT_cmax12_diff,lc_max_TS_PCT_cmax12_diff,lc_max_USG_PCT_cmax12_diff,lc_max_E_USG_PCT_cmax12_diff,lc_max_E_PACE_cmax12_diff,lc_max_PACE_cmax12_diff,lc_max_PACE_PER40_cmax12_diff,lc_max_POSS_cmax12_diff,lc_max_PIE_cmax12_diff,w_pct_cmax12_diff,away_home__cmax12_diff,lc_sum_MIN_cmax999_diff,lc_sum_E_OFF_RATING_cmax999_diff,lc_sum_OFF_RATING_cmax999_diff,lc_sum_E_DEF_RATING_cmax999_diff,lc_sum_DEF_RATING_cmax999_diff,lc_sum_E_NET_RATING_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_sum_AST_PCT_cmax999_diff,lc_sum_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cmax999_diff,lc_sum_OREB_PCT_cmax999_diff,lc_sum_DREB_PCT_cmax999_diff,lc_sum_REB_PCT_cmax999_diff,lc_sum_TM_TOV_PCT_cmax999_diff,lc_sum_EFG_PCT_cmax999_diff,lc_sum_TS_PCT_cmax999_diff,lc_sum_USG_PCT_cmax999_diff,lc_sum_E_USG_PCT_cmax999_diff,lc_sum_E_PACE_cmax999_diff,lc_sum_PACE_cmax999_diff,lc_sum_PACE_PER40_cmax999_diff,lc_sum_POSS_cmax999_diff,lc_sum_PIE_cmax999_diff,lc_mean_MIN_cmax999_diff,lc_mean_E_OFF_RATING_cmax999_diff,lc_mean_OFF_RATING_cmax999_diff,lc_mean_E_DEF_RATING_cmax999_diff,lc_mean_DEF_RATING_cmax999_diff,lc_mean_E_NET_RATING_cmax999_diff,lc_mean_NET_RATING_cmax999_diff,lc_mean_AST_PCT_cmax999_diff,lc_mean_AST_TOV_cmax999_diff,lc_mean_AST_RATIO_cmax999_diff,lc_mean_OREB_PCT_cmax999_diff,lc_mean_DREB_PCT_cmax999_diff,lc_mean_REB_PCT_cmax999_diff,lc_mean_TM_TOV_PCT_cmax999_diff,lc_mean_EFG_PCT_cmax999_diff,lc_mean_TS_PCT_cmax999_diff,lc_mean_USG_PCT_cmax999_diff,lc_mean_E_USG_PCT_cmax999_diff,lc_mean_E_PACE_cmax999_diff,lc_mean_PACE_cmax999_diff,lc_mean_PACE_PER40_cmax999_diff,lc_mean_POSS_cmax999_diff,lc_mean_PIE_cmax999_diff,lc_max_MIN_cmax999_diff,lc_max_E_OFF_RATING_cmax999_diff,lc_max_OFF_RATING_cmax999_diff,lc_max_E_DEF_RATING_cmax999_diff,lc_max_DEF_RATING_cmax999_diff,lc_max_E_NET_RATING_cmax999_diff,lc_max_NET_RATING_cmax999_diff,lc_max_AST_PCT_cmax999_diff,lc_max_AST_TOV_cmax999_diff,lc_max_AST_RATIO_cmax999_diff,lc_max_OREB_PCT_cmax999_diff,lc_max_DREB_PCT_cmax999_diff,lc_max_REB_PCT_cmax999_diff,lc_max_TM_TOV_PCT_cmax999_diff,lc_max_EFG_PCT_cmax999_diff,lc_max_TS_PCT_cmax999_diff,lc_max_USG_PCT_cmax999_diff,lc_max_E_USG_PCT_cmax999_diff,lc_max_E_PACE_cmax999_diff,lc_max_PACE_cmax999_diff,lc_max_PACE_PER40_cmax999_diff,lc_max_POSS_cmax999_diff,lc_max_PIE_cmax999_diff,w_pct_cmax999_diff,away_home__cmax999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [8]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '58Alost_contribution_mean_sum_max_cma5_12_999_diff_cmax5_12_999_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_lost_contribution_mean_sum_max_cma5_12_999_diff_cmax5_12_999_diff.to_csv(datapath_df, index=False)

In [9]:
df_readback = rcp('58Alost_contribution_mean_sum_max_cma5_12_999_diff_cmax5_12_999_diff_2010_2018.csv')
p(df_readback)

(10266, 449)

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,w_pct_cma5_diff,away_home__cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,w_pct_cma12_diff,away_home__cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,w_pct_cma999_diff,away_home__cma999_diff,lc_sum_MIN_cmax5_diff,lc_sum_E_OFF_RATING_cmax5_diff,lc_sum_OFF_RATING_cmax5_diff,lc_sum_E_DEF_RATING_cmax5_diff,lc_sum_DEF_RATING_cmax5_diff,lc_sum_E_NET_RATING_cmax5_diff,lc_sum_NET_RATING_cmax5_diff,lc_sum_AST_PCT_cmax5_diff,lc_sum_AST_TOV_cmax5_diff,lc_sum_AST_RATIO_cmax5_diff,lc_sum_OREB_PCT_cmax5_diff,lc_sum_DREB_PCT_cmax5_diff,lc_sum_REB_PCT_cmax5_diff,lc_sum_TM_TOV_PCT_cmax5_diff,lc_sum_EFG_PCT_cmax5_diff,lc_sum_TS_PCT_cmax5_diff,lc_sum_USG_PCT_cmax5_diff,lc_sum_E_USG_PCT_cmax5_diff,lc_sum_E_PACE_cmax5_diff,lc_sum_PACE_cmax5_diff,lc_sum_PACE_PER40_cmax5_diff,lc_sum_POSS_cmax5_diff,lc_sum_PIE_cmax5_diff,lc_mean_MIN_cmax5_diff,lc_mean_E_OFF_RATING_cmax5_diff,lc_mean_OFF_RATING_cmax5_diff,lc_mean_E_DEF_RATING_cmax5_diff,lc_mean_DEF_RATING_cmax5_diff,lc_mean_E_NET_RATING_cmax5_diff,lc_mean_NET_RATING_cmax5_diff,lc_mean_AST_PCT_cmax5_diff,lc_mean_AST_TOV_cmax5_diff,lc_mean_AST_RATIO_cmax5_diff,lc_mean_OREB_PCT_cmax5_diff,lc_mean_DREB_PCT_cmax5_diff,lc_mean_REB_PCT_cmax5_diff,lc_mean_TM_TOV_PCT_cmax5_diff,lc_mean_EFG_PCT_cmax5_diff,lc_mean_TS_PCT_cmax5_diff,lc_mean_USG_PCT_cmax5_diff,lc_mean_E_USG_PCT_cmax5_diff,lc_mean_E_PACE_cmax5_diff,lc_mean_PACE_cmax5_diff,lc_mean_PACE_PER40_cmax5_diff,lc_mean_POSS_cmax5_diff,lc_mean_PIE_cmax5_diff,lc_max_MIN_cmax5_diff,lc_max_E_OFF_RATING_cmax5_diff,lc_max_OFF_RATING_cmax5_diff,lc_max_E_DEF_RATING_cmax5_diff,lc_max_DEF_RATING_cmax5_diff,lc_max_E_NET_RATING_cmax5_diff,lc_max_NET_RATING_cmax5_diff,lc_max_AST_PCT_cmax5_diff,lc_max_AST_TOV_cmax5_diff,lc_max_AST_RATIO_cmax5_diff,lc_max_OREB_PCT_cmax5_diff,lc_max_DREB_PCT_cmax5_diff,lc_max_REB_PCT_cmax5_diff,lc_max_TM_TOV_PCT_cmax5_diff,lc_max_EFG_PCT_cmax5_diff,lc_max_TS_PCT_cmax5_diff,lc_max_USG_PCT_cmax5_diff,lc_max_E_USG_PCT_cmax5_diff,lc_max_E_PACE_cmax5_diff,lc_max_PACE_cmax5_diff,lc_max_PACE_PER40_cmax5_diff,lc_max_POSS_cmax5_diff,lc_max_PIE_cmax5_diff,w_pct_cmax5_diff,away_home__cmax5_diff,lc_sum_MIN_cmax12_diff,lc_sum_E_OFF_RATING_cmax12_diff,lc_sum_OFF_RATING_cmax12_diff,lc_sum_E_DEF_RATING_cmax12_diff,lc_sum_DEF_RATING_cmax12_diff,lc_sum_E_NET_RATING_cmax12_diff,lc_sum_NET_RATING_cmax12_diff,lc_sum_AST_PCT_cmax12_diff,lc_sum_AST_TOV_cmax12_diff,lc_sum_AST_RATIO_cmax12_diff,lc_sum_OREB_PCT_cmax12_diff,lc_sum_DREB_PCT_cmax12_diff,lc_sum_REB_PCT_cmax12_diff,lc_sum_TM_TOV_PCT_cmax12_diff,lc_sum_EFG_PCT_cmax12_diff,lc_sum_TS_PCT_cmax12_diff,lc_sum_USG_PCT_cmax12_diff,lc_sum_E_USG_PCT_cmax12_diff,lc_sum_E_PACE_cmax12_diff,lc_sum_PACE_cmax12_diff,lc_sum_PACE_PER40_cmax12_diff,lc_sum_POSS_cmax12_diff,lc_sum_PIE_cmax12_diff,lc_mean_MIN_cmax12_diff,lc_mean_E_OFF_RATING_cmax12_diff,lc_mean_OFF_RATING_cmax12_diff,lc_mean_E_DEF_RATING_cmax12_diff,lc_mean_DEF_RATING_cmax12_diff,lc_mean_E_NET_RATING_cmax12_diff,lc_mean_NET_RATING_cmax12_diff,lc_mean_AST_PCT_cmax12_diff,lc_mean_AST_TOV_cmax12_diff,lc_mean_AST_RATIO_cmax12_diff,lc_mean_OREB_PCT_cmax12_diff,lc_mean_DREB_PCT_cmax12_diff,lc_mean_REB_PCT_cmax12_diff,lc_mean_TM_TOV_PCT_cmax12_diff,lc_mean_EFG_PCT_cmax12_diff,lc_mean_TS_PCT_cmax12_diff,lc_mean_USG_PCT_cmax12_diff,lc_mean_E_USG_PCT_cmax12_diff,lc_mean_E_PACE_cmax12_diff,lc_mean_PACE_cmax12_diff,lc_mean_PACE_PER40_cmax12_diff,lc_mean_POSS_cmax12_diff,lc_mean_PIE_cmax12_diff,lc_max_MIN_cmax12_diff,lc_max_E_OFF_RATING_cmax12_diff,lc_max_OFF_RATING_cmax12_diff,lc_max_E_DEF_RATING_cmax12_diff,lc_max_DEF_RATING_cmax12_diff,lc_max_E_NET_RATING_cmax12_diff,lc_max_NET_RATING_cmax12_diff,lc_max_AST_PCT_cmax12_diff,lc_max_AST_TOV_cmax12_diff,lc_max_AST_RATIO_cmax12_diff,lc_max_OREB_PCT_cmax12_diff,lc_max_DREB_PCT_cmax12_diff,lc_max_REB_PCT_cmax12_diff,lc_max_TM_TOV_PCT_cmax12_diff,lc_max_EFG_PCT_cmax12_diff,lc_max_TS_PCT_cmax12_diff,lc_max_USG_PCT_cmax12_diff,lc_max_E_USG_PCT_cmax12_diff,lc_max_E_PACE_cmax12_diff,lc_max_PACE_cmax12_diff,lc_max_PACE_PER40_cmax12_diff,lc_max_POSS_cmax12_diff,lc_max_PIE_cmax12_diff,w_pct_cmax12_diff,away_home__cmax12_diff,lc_sum_MIN_cmax999_diff,lc_sum_E_OFF_RATING_cmax999_diff,lc_sum_OFF_RATING_cmax999_diff,lc_sum_E_DEF_RATING_cmax999_diff,lc_sum_DEF_RATING_cmax999_diff,lc_sum_E_NET_RATING_cmax999_diff,lc_sum_NET_RATING_cmax999_diff,lc_sum_AST_PCT_cmax999_diff,lc_sum_AST_TOV_cmax999_diff,lc_sum_AST_RATIO_cmax999_diff,lc_sum_OREB_PCT_cmax999_diff,lc_sum_DREB_PCT_cmax999_diff,lc_sum_REB_PCT_cmax999_diff,lc_sum_TM_TOV_PCT_cmax999_diff,lc_sum_EFG_PCT_cmax999_diff,lc_sum_TS_PCT_cmax999_diff,lc_sum_USG_PCT_cmax999_diff,lc_sum_E_USG_PCT_cmax999_diff,lc_sum_E_PACE_cmax999_diff,lc_sum_PACE_cmax999_diff,lc_sum_PACE_PER40_cmax999_diff,lc_sum_POSS_cmax999_diff,lc_sum_PIE_cmax999_diff,lc_mean_MIN_cmax999_diff,lc_mean_E_OFF_RATING_cmax999_diff,lc_mean_OFF_RATING_cmax999_diff,lc_mean_E_DEF_RATING_cmax999_diff,lc_mean_DEF_RATING_cmax999_diff,lc_mean_E_NET_RATING_cmax999_diff,lc_mean_NET_RATING_cmax999_diff,lc_mean_AST_PCT_cmax999_diff,lc_mean_AST_TOV_cmax999_diff,lc_mean_AST_RATIO_cmax999_diff,lc_mean_OREB_PCT_cmax999_diff,lc_mean_DREB_PCT_cmax999_diff,lc_mean_REB_PCT_cmax999_diff,lc_mean_TM_TOV_PCT_cmax999_diff,lc_mean_EFG_PCT_cmax999_diff,lc_mean_TS_PCT_cmax999_diff,lc_mean_USG_PCT_cmax999_diff,lc_mean_E_USG_PCT_cmax999_diff,lc_mean_E_PACE_cmax999_diff,lc_mean_PACE_cmax999_diff,lc_mean_PACE_PER40_cmax999_diff,lc_mean_POSS_cmax999_diff,lc_mean_PIE_cmax999_diff,lc_max_MIN_cmax999_diff,lc_max_E_OFF_RATING_cmax999_diff,lc_max_OFF_RATING_cmax999_diff,lc_max_E_DEF_RATING_cmax999_diff,lc_max_DEF_RATING_cmax999_diff,lc_max_E_NET_RATING_cmax999_diff,lc_max_NET_RATING_cmax999_diff,lc_max_AST_PCT_cmax999_diff,lc_max_AST_TOV_cmax999_diff,lc_max_AST_RATIO_cmax999_diff,lc_max_OREB_PCT_cmax999_diff,lc_max_DREB_PCT_cmax999_diff,lc_max_REB_PCT_cmax999_diff,lc_max_TM_TOV_PCT_cmax999_diff,lc_max_EFG_PCT_cmax999_diff,lc_max_TS_PCT_cmax999_diff,lc_max_USG_PCT_cmax999_diff,lc_max_E_USG_PCT_cmax999_diff,lc_max_E_PACE_cmax999_diff,lc_max_PACE_cmax999_diff,lc_max_PACE_PER40_cmax999_diff,lc_max_POSS_cmax999_diff,lc_max_PIE_cmax999_diff,w_pct_cmax999_diff,away_home__cmax999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0