In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [4]:
df_lc_sum_mean_max = rcp('50lost_contribution_sum_mean_max_2010_2018.csv')
p(df_lc_sum_mean_max)

(20534, 74)

,team_id,season,Team,game_id,game_date,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,1610612748,2010-11,Heat,21000001,2010-10-26,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
1,1610612748,2010-11,Heat,21000006,2010-10-27,68.098002,302.118241,301.192054,316.407153,317.218723,-14.287357,-16.017267,0.420140,3.540788,54.791826,0.148277,0.466348,0.299508,45.084396,1.425022,1.496048,0.453213,0.467014,274.789836,275.375124,229.479856,129.945214,0.024157,22.699334,100.706080,100.397351,105.469051,105.739574,-4.762452,-5.339089,0.140047,1.180263,18.263942,0.049426,0.155449,0.099836,15.028132,0.475007,0.498683,0.151071,0.155671,91.596612,91.791708,76.493285,43.315071,0.008052,33.424383,103.151852,104.377778,109.601852,109.838889,-2.065385,-3.383333,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.162833,0.166718,93.101111,92.464444,77.053889,64.370370,0.109481
2,1610612748,2010-11,Heat,21000025,2010-10-29,42.624383,316.751852,320.077778,416.801852,392.338889,-100.046296,-72.255556,0.430759,1.827222,60.196296,0.032093,0.667370,0.242556,14.911111,0.617593,1.173889,0.346704,0.349944,269.961111,274.434444,228.703889,81.370370,0.229481,14.208128,105.583951,106.692593,138.933951,130.779630,-33.348765,-24.085185,0.143586,0.609074,20.065432,0.010698,0.222457,0.080852,4.970370,0.205864,0.391296,0.115568,0.116648,89.987037,91.478148,76.234630,27.123457,0.076494,33.424383,131.600000,130.000000,185.700000,162.500000,10.100000,10.000000,0.250000,1.827222,33.300000,0.032093,0.500000,0.143000,14.911111,0.617593,0.641889,0.200000,0.202000,93.101111,93.810000,78.180000,64.370370,0.120000
3,1610612748,2010-11,Heat,21000040,2010-10-31,37.507716,185.151852,190.077778,295.301852,272.338889,-110.146296,-82.255556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,177.271111,180.624444,150.523889,71.370370,0.109481,18.753858,92.575926,95.038889,147.650926,136.169444,-55.073148,-41.127778,0.090380,0.913611,13.448148,0.016046,0.083685,0.049778,7.455556,0.308796,0.320944,0.073352,0.073972,88.635556,90.312222,75.261944,35.685185,0.054741,33.424383,103.151852,104.377778,185.700000,162.500000,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,92.464444,77.053889,64.370370,0.109481
4,1610612748,2010-11,Heat,21000050,2010-11-02,37.399383,168.751852,171.827778,200.951852,188.188889,-32.146296,-16.305556,0.180759,1.827222,26.896296,0.215593,0.167370,0.224556,14.911111,0.617593,0.925889,0.247704,0.252944,185.456111,189.489444,157.908889,72.370370,-0.051519,18.699691,84.375926,85.913889,100.475926,94.094444,-16.073148,-8.152778,0.090380,0.913611,13.448148,0.107796,0.083685,0.112278,7.455556,0.308796,0.462944,0.123852,0.126472,92.728056,94.744722,78.954444,36.185185,-0.025759,33.424383,103.151852,104.377778,109.601852,109.838889,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.183500,0.167370,0.125000,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,97.025000,80.855000,64.370370,0.109481
20529,1610612746,2017-18,Clippers,21701168,2018-04-03,146.678499,640.596671,640.331742,639.969085,637.281548,0.679793,3.080758,0.849233,6.483335,104.912492,0.131071,0.613417,0.370362,63.656900,2.850910,3.039054,1.109180,1.135039,601.033065,602.486983,502.077797,302.530047,0.427708,24.446416,106.766112,106.721957,106.661514,106.213591,0.113299,0.513460,0.141539,1.080556,17.485415,0.021845,0.102236,0.061727,10.609483,0.475152,0.506509,0.184863,0.189173,100.172178,100.414497,83.679633,50.421674,0.071285,31.955556,110.581818,111.754545,107.928986,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.140855,0.090014,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,104.263768,86.886812,65.380952,0.099952
20530,1610612746,2017-18,Clippers,21701179,2018-04-05,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952
20531,1610612746,2017-18,Clippers,21701191,2018-04-07,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952
20532,1610612746,2017-18,Clippers,21701212,2018-04-09,201.553878,752.156727,755.949091,751.941829,752.733135,0.262756,3.232761,1.234384,10.547727,134.376165,0.120098,0.588777,0.353180,74.587966,3.393490,3.652293,1.457945,1.487396,700.358026,698.050265,581.712857,415.990788,0.555500,28.793411,107.450961,107.992727,107.420261,107.533305,0.037537,0.461823,0.176341,1.506818,19.196595,0.017157,0.084111,0.050454,10.655424,0.484784,0.521756,0.208278,0.212485,100.051147,99.721466,83.101837,59.427255,0.079357,33.941667,110.581818,111.754545,110.096667,111.300000,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861
20533,1610612746,2017-18,Clippers,21701228,2018-04-11,167.612211,643.875060,646.212424,641.845162,641.433135,2.077756,4.796095,1.059534,8.519894,115.196165,0.106565,0.531410,0.317930,65.814632,2.893840,3.139059,1.250762,1.276563,601.243693,600.167265,500.144024,346.824121,0.483583,27.935369,107.312510,107.702071,106.974194,106.905522,0.346293,0.799349,0.176589,1.419982,19.199361,0.017761,0.088568,0.052988,10.969105,0.482307,0.523177,0.208460,0.212760,100.207282,100.027878,83.357337,57.804020,0.080597,32.774051,110.581818,111.754545,109.805063,109.924051,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861

In [5]:
#add matchup column and a_b_ column

df_game_id_team_id_matchup_ab = rcp('56game_id_team_id_a_b_matchup_a_b_2010_2018.csv')
p(df_game_id_team_id_matchup_ab)

(20532, 17)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,team_id,w_pct,wl,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b
0,21000001,Heat,MIA,Miami,1610612748,0.0,L,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0
1,21000001,Celtics,BOS,Boston,1610612738,1.0,W,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0
2,21000002,Suns,PHX,Phoenix,1610612756,0.0,L,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0
3,21000002,Trail Blazers,POR,Portland,1610612757,1.0,W,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0
4,21000003,Rockets,HOU,Houston,1610612745,0.0,L,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0
20527,41700402,Warriors,GSW,Golden State,1610612744,1.0,W,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20528,41700403,Warriors,GSW,Golden State,1610612744,1.0,W,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,1610612739,0.0,L,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0
20530,41700404,Warriors,GSW,Golden State,1610612744,1.0,W,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,1610612739,0.0,L,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0

In [6]:
column_names_gitimab_list = df_game_id_team_id_matchup_ab.columns
pl(column_names_gitimab_list)

17

Index(['game_id', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'team_id',
       'w_pct', 'wl', 'away_home_', 'game_date', 'matchup', 'season_type',
       'season', 'season_year', 'a', 'b', '_a', '_b'],
      dtype='object')

In [7]:
column_names_lcsmm_list = list(df_lc_sum_mean_max.columns)
pl(column_names_lcsmm_list)

74

['team_id',
 'season',
 'Team',
 'game_id',
 'game_date',
 'lc_sum_MIN',
 'lc_sum_E_OFF_RATING',
 'lc_sum_OFF_RATING',
 'lc_sum_E_DEF_RATING',
 'lc_sum_DEF_RATING',
 'lc_sum_E_NET_RATING',
 'lc_sum_NET_RATING',
 'lc_sum_AST_PCT',
 'lc_sum_AST_TOV',
 'lc_sum_AST_RATIO',
 'lc_sum_OREB_PCT',
 'lc_sum_DREB_PCT',
 'lc_sum_REB_PCT',
 'lc_sum_TM_TOV_PCT',
 'lc_sum_EFG_PCT',
 'lc_sum_TS_PCT',
 'lc_sum_USG_PCT',
 'lc_sum_E_USG_PCT',
 'lc_sum_E_PACE',
 'lc_sum_PACE',
 'lc_sum_PACE_PER40',
 'lc_sum_POSS',
 'lc_sum_PIE',
 'lc_mean_MIN',
 'lc_mean_E_OFF_RATING',
 'lc_mean_OFF_RATING',
 'lc_mean_E_DEF_RATING',
 'lc_mean_DEF_RATING',
 'lc_mean_E_NET_RATING',
 'lc_mean_NET_RATING',
 'lc_mean_AST_PCT',
 'lc_mean_AST_TOV',
 'lc_mean_AST_RATIO',
 'lc_mean_OREB_PCT',
 'lc_mean_DREB_PCT',
 'lc_mean_REB_PCT',
 'lc_mean_TM_TOV_PCT',
 'lc_mean_EFG_PCT',
 'lc_mean_TS_PCT',
 'lc_mean_USG_PCT',
 'lc_mean_E_USG_PCT',
 'lc_mean_E_PACE',
 'lc_mean_PACE',
 'lc_mean_PACE_PER40',
 'lc_mean_POSS',
 'lc_mean_PIE',
 'lc_max_MIN',
 'lc_max_E_OFF_RATING',
 'lc_max_OFF_RATING',
 'lc_max_E_DEF_RATING',
 'lc_max_DEF_RATING',
 'lc_max_E_NET_RATING',
 'lc_max_NET_RATING',
 'lc_max_AST_PCT',
 'lc_max_AST_TOV',
 'lc_max_AST_RATIO',
 'lc_max_OREB_PCT',
 'lc_max_DREB_PCT',
 'lc_max_REB_PCT',
 'lc_max_TM_TOV_PCT',
 'lc_max_EFG_PCT',
 'lc_max_TS_PCT',
 'lc_max_USG_PCT',
 'lc_max_E_USG_PCT',
 'lc_max_E_PACE',
 'lc_max_PACE',
 'lc_max_PACE_PER40',
 'lc_max_POSS',
 'lc_max_PIE']

In [8]:
#rearrange column order

In [9]:
column_names_lcsmm_list = [k for k in column_names_lcsmm_list if not k in ['game_id', 'game_date', 'team_id', 'season', 'Team']]
column_names_lcsmm_list = ['game_id', 'game_date', 'team_id', 'season', 'Team']  + column_names_lcsmm_list
pl(column_names_lcsmm_list)

74

['game_id',
 'game_date',
 'team_id',
 'season',
 'Team',
 'lc_sum_MIN',
 'lc_sum_E_OFF_RATING',
 'lc_sum_OFF_RATING',
 'lc_sum_E_DEF_RATING',
 'lc_sum_DEF_RATING',
 'lc_sum_E_NET_RATING',
 'lc_sum_NET_RATING',
 'lc_sum_AST_PCT',
 'lc_sum_AST_TOV',
 'lc_sum_AST_RATIO',
 'lc_sum_OREB_PCT',
 'lc_sum_DREB_PCT',
 'lc_sum_REB_PCT',
 'lc_sum_TM_TOV_PCT',
 'lc_sum_EFG_PCT',
 'lc_sum_TS_PCT',
 'lc_sum_USG_PCT',
 'lc_sum_E_USG_PCT',
 'lc_sum_E_PACE',
 'lc_sum_PACE',
 'lc_sum_PACE_PER40',
 'lc_sum_POSS',
 'lc_sum_PIE',
 'lc_mean_MIN',
 'lc_mean_E_OFF_RATING',
 'lc_mean_OFF_RATING',
 'lc_mean_E_DEF_RATING',
 'lc_mean_DEF_RATING',
 'lc_mean_E_NET_RATING',
 'lc_mean_NET_RATING',
 'lc_mean_AST_PCT',
 'lc_mean_AST_TOV',
 'lc_mean_AST_RATIO',
 'lc_mean_OREB_PCT',
 'lc_mean_DREB_PCT',
 'lc_mean_REB_PCT',
 'lc_mean_TM_TOV_PCT',
 'lc_mean_EFG_PCT',
 'lc_mean_TS_PCT',
 'lc_mean_USG_PCT',
 'lc_mean_E_USG_PCT',
 'lc_mean_E_PACE',
 'lc_mean_PACE',
 'lc_mean_PACE_PER40',
 'lc_mean_POSS',
 'lc_mean_PIE',
 'lc_max_MIN',
 'lc_max_E_OFF_RATING',
 'lc_max_OFF_RATING',
 'lc_max_E_DEF_RATING',
 'lc_max_DEF_RATING',
 'lc_max_E_NET_RATING',
 'lc_max_NET_RATING',
 'lc_max_AST_PCT',
 'lc_max_AST_TOV',
 'lc_max_AST_RATIO',
 'lc_max_OREB_PCT',
 'lc_max_DREB_PCT',
 'lc_max_REB_PCT',
 'lc_max_TM_TOV_PCT',
 'lc_max_EFG_PCT',
 'lc_max_TS_PCT',
 'lc_max_USG_PCT',
 'lc_max_E_USG_PCT',
 'lc_max_E_PACE',
 'lc_max_PACE',
 'lc_max_PACE_PER40',
 'lc_max_POSS',
 'lc_max_PIE']

In [10]:
df_lc_sum_mean_max = df_lc_sum_mean_max.loc[:, column_names_lcsmm_list]
p(df_lc_sum_mean_max)

(20534, 74)

,game_id,game_date,team_id,season,Team,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,21000001,2010-10-26,1610612748,2010-11,Heat,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
1,21000006,2010-10-27,1610612748,2010-11,Heat,68.098002,302.118241,301.192054,316.407153,317.218723,-14.287357,-16.017267,0.420140,3.540788,54.791826,0.148277,0.466348,0.299508,45.084396,1.425022,1.496048,0.453213,0.467014,274.789836,275.375124,229.479856,129.945214,0.024157,22.699334,100.706080,100.397351,105.469051,105.739574,-4.762452,-5.339089,0.140047,1.180263,18.263942,0.049426,0.155449,0.099836,15.028132,0.475007,0.498683,0.151071,0.155671,91.596612,91.791708,76.493285,43.315071,0.008052,33.424383,103.151852,104.377778,109.601852,109.838889,-2.065385,-3.383333,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.162833,0.166718,93.101111,92.464444,77.053889,64.370370,0.109481
2,21000025,2010-10-29,1610612748,2010-11,Heat,42.624383,316.751852,320.077778,416.801852,392.338889,-100.046296,-72.255556,0.430759,1.827222,60.196296,0.032093,0.667370,0.242556,14.911111,0.617593,1.173889,0.346704,0.349944,269.961111,274.434444,228.703889,81.370370,0.229481,14.208128,105.583951,106.692593,138.933951,130.779630,-33.348765,-24.085185,0.143586,0.609074,20.065432,0.010698,0.222457,0.080852,4.970370,0.205864,0.391296,0.115568,0.116648,89.987037,91.478148,76.234630,27.123457,0.076494,33.424383,131.600000,130.000000,185.700000,162.500000,10.100000,10.000000,0.250000,1.827222,33.300000,0.032093,0.500000,0.143000,14.911111,0.617593,0.641889,0.200000,0.202000,93.101111,93.810000,78.180000,64.370370,0.120000
3,21000040,2010-10-31,1610612748,2010-11,Heat,37.507716,185.151852,190.077778,295.301852,272.338889,-110.146296,-82.255556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,177.271111,180.624444,150.523889,71.370370,0.109481,18.753858,92.575926,95.038889,147.650926,136.169444,-55.073148,-41.127778,0.090380,0.913611,13.448148,0.016046,0.083685,0.049778,7.455556,0.308796,0.320944,0.073352,0.073972,88.635556,90.312222,75.261944,35.685185,0.054741,33.424383,103.151852,104.377778,185.700000,162.500000,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,92.464444,77.053889,64.370370,0.109481
4,21000050,2010-11-02,1610612748,2010-11,Heat,37.399383,168.751852,171.827778,200.951852,188.188889,-32.146296,-16.305556,0.180759,1.827222,26.896296,0.215593,0.167370,0.224556,14.911111,0.617593,0.925889,0.247704,0.252944,185.456111,189.489444,157.908889,72.370370,-0.051519,18.699691,84.375926,85.913889,100.475926,94.094444,-16.073148,-8.152778,0.090380,0.913611,13.448148,0.107796,0.083685,0.112278,7.455556,0.308796,0.462944,0.123852,0.126472,92.728056,94.744722,78.954444,36.185185,-0.025759,33.424383,103.151852,104.377778,109.601852,109.838889,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.183500,0.167370,0.125000,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,97.025000,80.855000,64.370370,0.109481
20529,21701168,2018-04-03,1610612746,2017-18,Clippers,146.678499,640.596671,640.331742,639.969085,637.281548,0.679793,3.080758,0.849233,6.483335,104.912492,0.131071,0.613417,0.370362,63.656900,2.850910,3.039054,1.109180,1.135039,601.033065,602.486983,502.077797,302.530047,0.427708,24.446416,106.766112,106.721957,106.661514,106.213591,0.113299,0.513460,0.141539,1.080556,17.485415,0.021845,0.102236,0.061727,10.609483,0.475152,0.506509,0.184863,0.189173,100.172178,100.414497,83.679633,50.421674,0.071285,31.955556,110.581818,111.754545,107.928986,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.140855,0.090014,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,104.263768,86.886812,65.380952,0.099952
20530,21701179,2018-04-05,1610612746,2017-18,Clippers,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952
20531,21701191,2018-04-07,1610612746,2017-18,Clippers,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952
20532,21701212,2018-04-09,1610612746,2017-18,Clippers,201.553878,752.156727,755.949091,751.941829,752.733135,0.262756,3.232761,1.234384,10.547727,134.376165,0.120098,0.588777,0.353180,74.587966,3.393490,3.652293,1.457945,1.487396,700.358026,698.050265,581.712857,415.990788,0.555500,28.793411,107.450961,107.992727,107.420261,107.533305,0.037537,0.461823,0.176341,1.506818,19.196595,0.017157,0.084111,0.050454,10.655424,0.484784,0.521756,0.208278,0.212485,100.051147,99.721466,83.101837,59.427255,0.079357,33.941667,110.581818,111.754545,110.096667,111.300000,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861
20533,21701228,2018-04-11,1610612746,2017-18,Clippers,167.612211,643.875060,646.212424,641.845162,641.433135,2.077756,4.796095,1.059534,8.519894,115.196165,0.106565,0.531410,0.317930,65.814632,2.893840,3.139059,1.250762,1.276563,601.243693,600.167265,500.144024,346.824121,0.483583,27.935369,107.312510,107.702071,106.974194,106.905522,0.346293,0.799349,0.176589,1.419982,19.199361,0.017761,0.088568,0.052988,10.969105,0.482307,0.523177,0.208460,0.212760,100.207282,100.027878,83.357337,57.804020,0.080597,32.774051,110.581818,111.754545,109.805063,109.924051,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861

In [11]:
#sort and reset_index()

In [12]:
df_lc_sum_mean_max = sr(df_lc_sum_mean_max, 'game_id')
df_lc_sum_mean_max = sr(df_lc_sum_mean_max, 'game_date')
p(df_lc_sum_mean_max)

(20534, 74)

,game_id,game_date,team_id,season,Team,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,21000001,2010-10-26,1610612748,2010-11,Heat,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
1,21000001,2010-10-26,1610612738,2010-11,Celtics,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296
2,21000002,2010-10-26,1610612757,2010-11,Trail Blazers,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143
3,21000002,2010-10-26,1610612756,2010-11,Suns,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185
4,21000003,2010-10-26,1610612747,2010-11,Lakers,45.471555,311.425148,307.926411,302.871703,300.404159,8.554744,7.529242,0.347421,1.383516,46.364610,0.141115,0.346645,0.245898,25.639408,1.219038,1.317815,0.479160,0.493594,292.963369,302.203547,251.835655,88.592496,0.200797,15.157185,103.808383,102.642137,100.957234,100.134720,2.851581,2.509747,0.115807,0.461172,15.454870,0.047038,0.115548,0.081966,8.546469,0.406346,0.439272,0.159720,0.164531,97.654456,100.734516,83.945218,29.530832,0.066932,28.842045,107.911688,108.867045,102.922727,103.612500,10.366234,9.763636,0.194844,0.688889,26.300000,0.094114,0.180375,0.139080,11.331818,0.549227,0.581750,0.190909,0.192875,101.721778,105.801039,88.167143,55.909091,0.117761
20529,41700402,2018-06-03,1610612744,2017-18,Warriors,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20530,41700403,2018-06-06,1610612744,2017-18,Warriors,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507
20531,41700403,2018-06-06,1610612739,2017-18,Cavaliers,52.338461,400.631457,380.411271,426.728326,421.938512,-26.111453,-41.525423,0.522395,2.162777,62.147909,0.135526,0.476935,0.345398,33.347526,1.738520,1.830872,0.631322,0.668179,387.988989,439.216727,366.013324,108.527412,0.277195,13.084615,100.157864,95.102818,106.682081,105.484628,-6.527863,-10.381356,0.130599,0.540694,15.536977,0.033882,0.119234,0.086349,8.336882,0.434630,0.457718,0.157831,0.167045,96.997247,109.804182,91.503331,27.131853,0.069299,21.729167,105.781159,102.107000,112.497436,112.869231,5.518841,2.226087,0.193159,1.180900,31.084058,0.079872,0.164635,0.142769,9.991000,0.482949,0.505487,0.247070,0.254070,102.021757,120.379189,100.316757,45.520000,0.087910
20532,41700404,2018-06-08,1610612739,2017-18,Cavaliers,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910
20533,41700404,2018-06-08,1610612744,2017-18,Warriors,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [13]:
column_names_common_list = [k for k in column_names_lcsmm_list if k in column_names_gitimab_list]
pl(column_names_common_list)

4

['game_id', 'game_date', 'team_id', 'season']

In [14]:
df_merged = pd.merge(df_lc_sum_mean_max, df_game_id_team_id_matchup_ab, on=column_names_common_list)
p(df_merged)

(20532, 87)

,game_id,game_date,team_id,season,Team,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,w_pct,wl,away_home_,matchup,season_type,season_year,a,b,_a,_b
0,21000001,2010-10-26,1610612748,2010-11,Heat,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481,Heat,MIA,Miami,0.0,L,0,BOS vs. MIA,Regular Season,2010,BOS,MIA,0.0,1.0
1,21000001,2010-10-26,1610612738,2010-11,Celtics,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,Celtics,BOS,Boston,1.0,W,1,BOS vs. MIA,Regular Season,2010,BOS,MIA,1.0,0.0
2,21000002,2010-10-26,1610612757,2010-11,Trail Blazers,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143,Trail Blazers,POR,Portland,1.0,W,1,PHX vs. POR,Regular Season,2010,PHX,POR,0.0,1.0
3,21000002,2010-10-26,1610612756,2010-11,Suns,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,Suns,PHX,Phoenix,0.0,L,0,PHX vs. POR,Regular Season,2010,PHX,POR,1.0,0.0
4,21000003,2010-10-26,1610612747,2010-11,Lakers,45.471555,311.425148,307.926411,302.871703,300.404159,8.554744,7.529242,0.347421,1.383516,46.364610,0.141115,0.346645,0.245898,25.639408,1.219038,1.317815,0.479160,0.493594,292.963369,302.203547,251.835655,88.592496,0.200797,15.157185,103.808383,102.642137,100.957234,100.134720,2.851581,2.509747,0.115807,0.461172,15.454870,0.047038,0.115548,0.081966,8.546469,0.406346,0.439272,0.159720,0.164531,97.654456,100.734516,83.945218,29.530832,0.066932,28.842045,107.911688,108.867045,102.922727,103.612500,10.366234,9.763636,0.194844,0.688889,26.300000,0.094114,0.180375,0.139080,11.331818,0.549227,0.581750,0.190909,0.192875,101.721778,105.801039,88.167143,55.909091,0.117761,Lakers,LAL,Los Angeles,1.0,W,1,HOU vs. LAL,Regular Season,2010,HOU,LAL,0.0,1.0
20527,41700402,2018-06-03,1610612744,2017-18,Warriors,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Warriors,GSW,Golden State,1.0,W,1,CLE vs. GSW,Playoffs,2017,CLE,GSW,0.0,1.0
20528,41700403,2018-06-06,1610612744,2017-18,Warriors,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,Warriors,GSW,Golden State,1.0,W,0,CLE vs. GSW,Playoffs,2017,CLE,GSW,0.0,1.0
20529,41700403,2018-06-06,1610612739,2017-18,Cavaliers,52.338461,400.631457,380.411271,426.728326,421.938512,-26.111453,-41.525423,0.522395,2.162777,62.147909,0.135526,0.476935,0.345398,33.347526,1.738520,1.830872,0.631322,0.668179,387.988989,439.216727,366.013324,108.527412,0.277195,13.084615,100.157864,95.102818,106.682081,105.484628,-6.527863,-10.381356,0.130599,0.540694,15.536977,0.033882,0.119234,0.086349,8.336882,0.434630,0.457718,0.157831,0.167045,96.997247,109.804182,91.503331,27.131853,0.069299,21.729167,105.781159,102.107000,112.497436,112.869231,5.518841,2.226087,0.193159,1.180900,31.084058,0.079872,0.164635,0.142769,9.991000,0.482949,0.505487,0.247070,0.254070,102.021757,120.379189,100.316757,45.520000,0.087910,Cavaliers,CLE,Cleveland,0.0,L,1,CLE vs. GSW,Playoffs,2017,CLE,GSW,1.0,0.0
20530,41700404,2018-06-08,1610612739,2017-18,Cavaliers,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,Cavaliers,CLE,Cleveland,0.0,L,1,CLE vs. GSW,Playoffs,2017,CLE,GSW,1.0,0.0
20531,41700404,2018-06-08,1610612744,2017-18,Warriors,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Warriors,GSW,Golden State,1.0,W,0,CLE vs. GSW,Playoffs,2017,CLE,GSW,0.0,1.0

In [15]:
help(f.tall2wide2)

Help on function tall2wide2 in module my_functions:

tall2wide2(df_, not_first_second_list_, indicator_column_, keep_indicator_=False, first_second_column_suffix_=None)

In [16]:
df_merged.drop(columns='_b', inplace=True)

In [ ]:
df_merged.loc[:, '_a'] = abs(df_merged.loc[:, '_a'] - 1)

In [17]:
df_lc_sum_mean_max_ab = f.tall2wide2(df_merged, ['game_id', 'season', 'game_date', 'matchup', 'season_type', 'a', 'b', 'season_year'], '_a')
p(df_lc_sum_mean_max_ab)

(10266, 162)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,team_id_a,season,Team_a,lc_sum_MIN_a,lc_sum_E_OFF_RATING_a,lc_sum_OFF_RATING_a,lc_sum_E_DEF_RATING_a,lc_sum_DEF_RATING_a,lc_sum_E_NET_RATING_a,lc_sum_NET_RATING_a,lc_sum_AST_PCT_a,lc_sum_AST_TOV_a,lc_sum_AST_RATIO_a,lc_sum_OREB_PCT_a,lc_sum_DREB_PCT_a,lc_sum_REB_PCT_a,lc_sum_TM_TOV_PCT_a,lc_sum_EFG_PCT_a,lc_sum_TS_PCT_a,lc_sum_USG_PCT_a,lc_sum_E_USG_PCT_a,lc_sum_E_PACE_a,lc_sum_PACE_a,lc_sum_PACE_PER40_a,lc_sum_POSS_a,lc_sum_PIE_a,lc_mean_MIN_a,lc_mean_E_OFF_RATING_a,lc_mean_OFF_RATING_a,lc_mean_E_DEF_RATING_a,lc_mean_DEF_RATING_a,lc_mean_E_NET_RATING_a,lc_mean_NET_RATING_a,lc_mean_AST_PCT_a,lc_mean_AST_TOV_a,lc_mean_AST_RATIO_a,lc_mean_OREB_PCT_a,lc_mean_DREB_PCT_a,lc_mean_REB_PCT_a,lc_mean_TM_TOV_PCT_a,lc_mean_EFG_PCT_a,lc_mean_TS_PCT_a,lc_mean_USG_PCT_a,lc_mean_E_USG_PCT_a,lc_mean_E_PACE_a,lc_mean_PACE_a,lc_mean_PACE_PER40_a,lc_mean_POSS_a,lc_mean_PIE_a,lc_max_MIN_a,lc_max_E_OFF_RATING_a,lc_max_OFF_RATING_a,lc_max_E_DEF_RATING_a,lc_max_DEF_RATING_a,lc_max_E_NET_RATING_a,lc_max_NET_RATING_a,lc_max_AST_PCT_a,lc_max_AST_TOV_a,lc_max_AST_RATIO_a,lc_max_OREB_PCT_a,lc_max_DREB_PCT_a,lc_max_REB_PCT_a,lc_max_TM_TOV_PCT_a,lc_max_EFG_PCT_a,lc_max_TS_PCT_a,lc_max_USG_PCT_a,lc_max_E_USG_PCT_a,lc_max_E_PACE_a,lc_max_PACE_a,lc_max_PACE_PER40_a,lc_max_POSS_a,lc_max_PIE_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,w_pct_a,wl_a,away_home__a,matchup,season_type,season_year,a,b,team_id_b,Team_b,lc_sum_MIN_b,lc_sum_E_OFF_RATING_b,lc_sum_OFF_RATING_b,lc_sum_E_DEF_RATING_b,lc_sum_DEF_RATING_b,lc_sum_E_NET_RATING_b,lc_sum_NET_RATING_b,lc_sum_AST_PCT_b,lc_sum_AST_TOV_b,lc_sum_AST_RATIO_b,lc_sum_OREB_PCT_b,lc_sum_DREB_PCT_b,lc_sum_REB_PCT_b,lc_sum_TM_TOV_PCT_b,lc_sum_EFG_PCT_b,lc_sum_TS_PCT_b,lc_sum_USG_PCT_b,lc_sum_E_USG_PCT_b,lc_sum_E_PACE_b,lc_sum_PACE_b,lc_sum_PACE_PER40_b,lc_sum_POSS_b,lc_sum_PIE_b,lc_mean_MIN_b,lc_mean_E_OFF_RATING_b,lc_mean_OFF_RATING_b,lc_mean_E_DEF_RATING_b,lc_mean_DEF_RATING_b,lc_mean_E_NET_RATING_b,lc_mean_NET_RATING_b,lc_mean_AST_PCT_b,lc_mean_AST_TOV_b,lc_mean_AST_RATIO_b,lc_mean_OREB_PCT_b,lc_mean_DREB_PCT_b,lc_mean_REB_PCT_b,lc_mean_TM_TOV_PCT_b,lc_mean_EFG_PCT_b,lc_mean_TS_PCT_b,lc_mean_USG_PCT_b,lc_mean_E_USG_PCT_b,lc_mean_E_PACE_b,lc_mean_PACE_b,lc_mean_PACE_PER40_b,lc_mean_POSS_b,lc_mean_PIE_b,lc_max_MIN_b,lc_max_E_OFF_RATING_b,lc_max_OFF_RATING_b,lc_max_E_DEF_RATING_b,lc_max_DEF_RATING_b,lc_max_E_NET_RATING_b,lc_max_NET_RATING_b,lc_max_AST_PCT_b,lc_max_AST_TOV_b,lc_max_AST_RATIO_b,lc_max_OREB_PCT_b,lc_max_DREB_PCT_b,lc_max_REB_PCT_b,lc_max_TM_TOV_PCT_b,lc_max_EFG_PCT_b,lc_max_TS_PCT_b,lc_max_USG_PCT_b,lc_max_E_USG_PCT_b,lc_max_E_PACE_b,lc_max_PACE_b,lc_max_PACE_PER40_b,lc_max_POSS_b,lc_max_PIE_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,w_pct_b,wl_b,away_home__b
0,21000001,2010-10-26,1610612738,2010-11,Celtics,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296,Celtics,BOS,Boston,1.000,W,1,BOS vs. MIA,Regular Season,2010,BOS,MIA,1610612748,Heat,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481,Heat,MIA,Miami,0.000,L,0
1,21000002,2010-10-26,1610612756,2010-11,Suns,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,Suns,PHX,Phoenix,0.000,L,0,PHX vs. POR,Regular Season,2010,PHX,POR,1610612757,Trail Blazers,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143,Trail Blazers,POR,Portland,1.000,W,1
2,21000003,2010-10-26,1610612745,2010-11,Rockets,72.948233,412.334764,407.967536,438.575371,431.164547,-26.242041,-23.182540,0.523228,3.688711,63.663037,0.269792,0.418425,0.347123,48.814252,1.599116,1.856396,0.721490,0.741075,392.134212,399.519088,332.932128,145.438289,0.280267,18.237058,103.083691,101.991884,109.643843,107.791137,-6.560510,-5.795635,0.130807,0.922178,15.915759,0.067448,0.104606,0.086781,12.203563,0.399779,0.464099,0.180372,0.185269,98.033553,99.879772,83.233032,36.359572,0.070067,25.621905,105.238235,106.551471,118.183871,112.083871,1.380882,3.101471,0.284706,2.379853,30.129412,0.103404,0.151787,0.126298,14.452857,0.431643,0.522544,0.232258,0.242452,103.683548,110.925161,92.437419,50.342857,0.105765,Rockets,HOU,Houston,0.000,L,0,HOU vs. LAL,Regular Season,2010,HOU,LAL,1610612747,Lakers,45.471555,311.425148,307.926411,302.871703,300.404159,8.554744,7.529242,0.347421,1.383516,46.364610,0.141115,0.346645,0.245898,25.639408,1.219038,1.317815,0.479160,0.493594,292.963369,302.203547,251.835655,88.592496,0.200797,15.157185,103.808383,102.642137,100.957234,100.134720,2.851581,2.509747,0.115807,0.461172,15.454870,0.047038,0.115548,0.081966,8.546469,0.406346,0.439272,0.159720,0.164531,97.654456,100.734516,83.945218,29.530832,0.066932,28.842045,107.911688,108.867045,102.922727,103.612500,10.366234,9.763636,0.194844,0.688889,26.300000,0.094114,0.180375,0.139080,11.331818,0.549227,0.581750,0.190909,0.192875,101.721778,105.801039,88.167143,55.909091,0.117761,Lakers,LAL,Los Angeles,1.000,W,1
3,21000012,2010-10-27,1610612766,2010-11,Bobcats,38.729357,374.577837,365.648605,425.148350,407.823737,-50.570268,-42.178563,0.184802,0.615762,35.597229,0.196995,0.539148,0.357487,47.757928,1.443427,1.432352,0.571382,0.618385,377.371129,409.859749,341.548094,76.501697,0.103538,9.682339,93.644459,91.412151,106.287088,101.955934,-12.642567,-10.544641,0.046200,0.153940,8.899307,0.049249,0.134787,0.089372,11.939482,0.360857,0.358088,0.142846,0.154596,94.342782,102.464937,85.387023,19.125424,0.025885,14.132353,102.011538,97.629412,112.852941,107.729412,1.846154,2.719231,0.053500,0.235294,10.188235,0.073292,0.221063,0.138583,19.843750,0.441563,0.426745,0.208192,0.234308,101.860588,122.786667,102.321765,28.745098,0.183731,Bobcats,CHA,Charlotte,0.000,L,0,CHA vs. DAL,Regular Season,2010,CHA,DAL,1610612742,Mavericks,37.481121,398.779016,393.522205,387.349332,370.767842,11.383915,22.737842,0.266038,0.970211,35.914504,0.053149,0.322428,0.201885,35.203718,1.314242,1.416853,0.710841,0.739016,454.089218,519.901033,433.251083,75.292416,0.320542,9.370280,99.694754,98.380551,96.837333,92.691961,2.845979,5.684460,0.066510,0.242553,8.978626,0.013287,0.080607,0.050471,8.800929,0.328561,0.354213,0.177710,0.184754,113.522304,129.975258,108.312771,18.823104,0.080136,13.470455,110.100000,109.050000,110.615152,109.113636,41.366667,41.650000,0.167153,0.576271,17.239394,0.023833,0.095061,0.075500,12.427119,0.463492,0.487169,0.245203,0.254864,131.807407,178.722222,148.934815,26.757576,0.169894,Mavericks,DAL,Dallas,1.000,W,1
4,21000013,2010-10-27,1610612754,2010-11,Pacers,104.260160,501.295375,502.099831,525.909379,523.354626,-24.605246,-21.231917,0.610305,3.723586,74.918037,0.241600,0.689864,0.450034,52.398413,2.146576,2.411073,0.898928,0.915827,498.650102,499.315362,416.096378,214.921810,0.254090,20.852032,100.259075,100.419966,105.181876,104.670925,-4.921049,-4.246383,0.122061,0.744717,14.983607,0.048320,0.137973,0.090007,10.479683,0.429315,0.482215,0.179786,0.183165,99.730020,99.863072,83.219276,42.984362,0.050818,30.377236,103.421429,103.748214,114.381250,114.762500,6.601786,8.494643,0.178196,1.047763,20.725000,0.095172,0.212688,0.148125,14.068750,0.502463,0.510463,0.242034,0.248552,100.740179,101.633571,84.694286,61.890244,0.077069,Pacers,IND,Indiana,0.000,L,0,IND vs. SAS,Regular Season,2010,IND,SAS,1610612759,Spurs,16.516667,105.927273,104.245455,100.936364,101.400000,4.972727,2.854545,0.059455,0.363636,6.072727,0.080182,0.141091,0.107545,8.781818,0.569273,0.577636,0.216727,0.221818,90.993636,91.364545,76.137273,31.363636,0.124909,16.516667,105.927273,104.245455,100.936364,101.400000,4.972727,2.854545,0.059455,0.363636,6.072727,0.080182,0.141091,0.107545,8.781818,0.569273,0.577636,0.216727,0.221818,90.993636,91.364545,76.137273,31.363636,0.124909,16.516667,105.927273,104.245455,100.936364,101.400000,4.972727,2.854545,0.059455,0.363636,6.072727,0.080182,0.141091,0.107545,8.781818,0.569273,0.577636,0.216727,0.221818,90.993636,91.364545,76.137273,31.363636,0.124909,Spurs,SAS,San Antonio,1.000,W,1
10261,41700317,2018-05-28,1610612744,2017-18,Warriors,36.281249,327.397328,325.168002,316.729139,319.797592,10.678596,5.380615,0.422142,1.531622,54.727617,0.259091,0.521709,0.417990,41.678829,1.649647,1.758100,0.566558,0.581968,302.581073,302.420850,252.017030,75.718701,0.354829,12.093750,109.132443,108.389334,105.576380,106.599197,3.559532,1.793538,0.140714,0.510541,18.242539,0.086364,0.173903,0.139330,13.892943,0.549882,0.586033,0.188853,0.193989,100.860358,100.806950,84.005677,25.239567,0.118276,13.404730,114.643243,114.364865,109.798649,110.360811,10.741892,9.566216,0.223575,0.820000,24.173563,0.099000,0.213527,0.159392,17.962162,0.572931,0.597816,0.214437,0.218414,102.307973,102.798514,85.665405,28.472973,0.137586,Warriors,GSW,Golden State,0.571,W,0,GSW vs. HOU,Playoffs,2017,GSW,HOU,1610612745,Rockets,86.859988,532.699904,517.347739,512.727467,504.613318,19.931778,12.739791,0.777622,4.345292,86.488619,0.244140,0.707721,0.467646,65.607594,2.087595,2.270962,0.824166,0.858288,495.628808,511.774434,426.476992,179.843561,0.421658,17.371998,106.539981,103.469548,102.545493,100.922664,3.986356,2.547958,0.155524,0.869058,17.297724,0.048828,0.141544,0.093529,13.121519,0.417519,0.454192,0.164833,0.171658,99.125762,102.354887,85.295398,35.968712,0.084332,32.375571,114.934247,115.224658,106.391379,106.217241,11.973016,12.580822,0.375247,3.300959,29.487671,0.085862,0.185414,0.133414,16.662500,0.536438,0.585233,0.244123,0.250041,101.832698,107.105000,89.252500,66.397260,0.164260,Rockets,HOU,Houston,0.429,L,1
10262,41700401,2018-05-31,1610612739,2017-18,Cavaliers,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Cavaliers,CLE,Cleveland,0.000,L,0,CLE vs. GSW,Playoffs,2017,CLE,GSW,1610612744,Warriors,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176,Warriors,GSW,Golden State,1.000,W,1
10263,41700402,2018-06-03,1610612739,2017-18,Cavaliers,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Cavaliers,CLE,Cleveland,0.000,L,0,CLE vs. GSW,Playoffs,2017,CLE,GSW,1610612744,Warriors,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Warriors,GSW,Golden State,1.000,W,1
10264,41700403,2018-06-06,1610612739,2017-18,Cavaliers,52.338461,400.631457,380.411271,426.728326,421.938512,-26.111453,-41.525423,0.522395,2.162777,62.147909,0.135526,0.476935,0.345398,33.347526,1.738520,1.830872,0.631322,0.668179,387.988989,439.216727,366.013324,108.527412,0.277195,13.084615,100.157864,95.102818,106.682081,105.484628,-6.527863,-10.381356,0.130599,0.540694,15.536977,0.033882,0.119234,0.086349,8.336882,0.434630,0.457718,0.157831,0.167045,96.997247,109.804182,91.503331,27.131853,0.069299,21.729167,105.781159,102.107000,112.497436,112.869231,5.518841,2.226087,0.193159,1.180900,31.084058,0.079872,0.164635,0.142769,9.991000,0.482949,0.505487,0.247070,0.254070,102.021757,120.379189,100.316757,45.520000,0.087910,Cavaliers,CLE,Cleveland,0.000,L,1,CLE vs. GSW,Playoffs,2017,CLE,GSW,1610612744,Warriors,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,Warriors,GSW,Golden State,1.000,W,0
10265,41700404,2018-06-08,1610612739,2017-18,Cavaliers,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,Cavaliers,CLE,Cleveland,0.000,L,1,CLE vs. GSW,Playoffs,2017,CLE,GSW,1610612744,Warriors,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Warriors,GSW,Golden State,1.000,W,0

In [18]:
help(f.tall2wide2)

Help on function tall2wide2 in module my_functions:

tall2wide2(df_, not_first_second_list_, indicator_column_, keep_indicator_=False, first_second_column_suffix_=None)

In [19]:
def wide_get_cma_num_diff3(df_, groupby_list_, not_difference_list_, suffix_list_, window_size_max_min_):
    
    
    #get suffix category column name: suffix_cat
    alphanumeric = ''
    suffix_cat = ''
    for i in range(len(suffix_list_)):
        
        for character in suffix_list_[i]:
            if character.isalnum():
                alphanumeric += character
        
        suffix_cat = suffix_cat + alphanumeric + '_'
        alphanumeric = ''

    
    column_names_list_ = list(df_.columns)
    
    column_names_first_second_list_ = [k for k in column_names_list_
                                       if not k in not_difference_list_]
    
    column_names_first_second_list_first_ = [k for k in column_names_first_second_list_
                                            if k.endswith(suffix_list_[0])]
    
    column_names_first_second_list_first_stripped_ = [k.split(suffix_list_[0])[0]
                                                     for k in column_names_first_second_list_first_]
    
    
    df_ = f.wide2tall(df_, not_difference_list_, suffix_list_)
    

    
    column_names_number_list_ = list(df_.select_dtypes('number'))

    column_names_number_list_ = [k for k in column_names_number_list_ if not k in not_difference_list_]
    
    column_names_number_list_ = [k for k in column_names_number_list_ if not k in suffix_cat]
    
    gbl_column_names_number_list_ = groupby_list_ + [k for k in column_names_number_list_
                                                          if not k in groupby_list_] 
    
    df_numeric_gbl_ = df_[gbl_column_names_number_list_]
    
    
    df_gbl_cma_ = df_numeric_gbl_.groupby(
                                            groupby_list_).apply(lambda x:
                                            x.rolling(window_size_max_min_[0],
                                            window_size_max_min_[1]).mean().shift()
                                         )[column_names_number_list_]
    
    pre_rename_cma_drop_list_ = [k for k in column_names_number_list_ if k in groupby_list_]
    
    df_gbl_cma_.drop(columns=pre_rename_cma_drop_list_, inplace=True)
    
     
    column_names_number_list_cma_num_ = [k + '_cma' + str(window_size_max_min_[0]) for k in column_names_number_list_]
    
    column_names_number_dict_cma_num_ = dict(zip(column_names_number_list_, column_names_number_list_cma_num_))
        
    df_gbl_cma_.rename(columns=column_names_number_dict_cma_num_, inplace=True)
    
    df_gbl_cma_ = df_gbl_cma_.reset_index()
    
    df_gbl_cma_.rename(columns={'level_2': 'index'}, inplace=True)

    df_ = df_.reset_index()
    
    column_names_merged_list = ['index'] + groupby_list_
    
   
    column_names_number_list_rgbl_ = [k for k in column_names_number_list_ if not k in groupby_list_]
    
    df_dropped_ = df_.drop(columns=column_names_number_list_rgbl_)
        
    df_gbl_cma_merged_ = pd.merge(df_dropped_, df_gbl_cma_, on=column_names_merged_list)
    
    
    
    df_gbl_cma_merged_.drop(columns='index', inplace=True)
    
    
    df_wide_ = f.tall2wide2(df_gbl_cma_merged_, not_difference_list_, suffix_cat)

    df_wide_ = sr(df_wide_, 'game_date')
    
    
    
    #take difference of numeric columns with the same prefix, store to stat_cma#_diff
    
    return get_numeric_diff(df_wide_, groupby_list_, not_difference_list_, suffix_list_)
    
    #merge back to columns not taken a difference on

In [20]:
#take difference of numeric columns with the same prefix, store to stat_cma#_diff

#drop stat_cma# columns

def get_numeric_diff(df_, groupby_list_, not_difference_list_, suffix_list_):
    
    column_names_numeric_list_ = list(df_.select_dtypes('number').columns)
    
    column_names_numeric_list_cleaned_ = [k for k in column_names_numeric_list_
                                          if (not k in not_difference_list_)]
    
    column_names_first_second_list_ = [k.split(suffix_list_[0])[0]
                                       for k in column_names_numeric_list_cleaned_
                                       if k.endswith(suffix_list_[0])]
    
    column_names_first_second_list_rgl_ = [k for k in column_names_first_second_list_
                                           if not k in groupby_list_]

    column_names_first_second_list_rgl_first_ = [k + suffix_list_[0] for k in column_names_first_second_list_rgl_]
    
    column_names_first_second_list_rgl_second_ = [k + suffix_list_[1] for k in column_names_first_second_list_rgl_]
    
    column_names_first_second_list_rgl_diff_ = [k + '_diff' for k in column_names_first_second_list_rgl_]
    
    #return len(column_names_first_second_list_rgl_first_), len(column_names_first_second_list_rgl_second_), len(column_names_first_second_list_rgl_diff_)
    
    
    df_[column_names_first_second_list_rgl_diff_] = df_[column_names_first_second_list_rgl_first_].fillna(0).values - df_[column_names_first_second_list_rgl_second_].fillna(0)
    
    column_names_drop_ = column_names_first_second_list_rgl_first_ + column_names_first_second_list_rgl_second_
    
    df_.drop(columns = column_names_drop_, inplace=True)    
    
    #return df_[column_names_first_second_list_rgl_first_]
    
    #return df_[column_names_first_second_list_rgl_second_]
    
    return df_

In [21]:
df_lc_sum_mean_max_cma5_diff = wide_get_cma_num_diff3(df_lc_sum_mean_max_ab,
                       ['season', 'team_id'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [5,1])
p(df_lc_sum_mean_max_cma5_diff)

(10266, 94)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,w_pct_cma5_diff,away_home__cma5_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0
3,21000004,2010-10-27,2010-11,Regular Season,2010,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.0000,-1.0
4,21000005,2010-10-27,2010-11,Regular Season,2010,1610612751,Nets,Nets,NJN,New Jersey,W,DET vs. NJN,DET,NJN,1610612765,Pistons,Pistons,DET,Detroit,L,DET vs. NJN,DET,NJN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,31.999206,153.530749,146.182173,134.628644,130.924314,18.884348,15.260006,0.139548,0.775662,12.872695,0.018867,0.145735,0.074359,12.977122,0.456749,0.489657,0.197222,0.207522,138.793051,146.674582,122.227353,66.118610,-0.004319,3.980618,2.558975,1.020145,-5.667162,-7.173202,8.220550,8.193097,-0.000614,0.113836,-1.870235,-0.026135,-0.015662,-0.027743,-1.218917,-0.081358,-0.081835,-0.014827,-0.014220,-0.488711,1.638810,1.365246,8.250536,-0.046982,7.513777,2.727645,3.039995,-4.122781,-4.171058,8.864994,9.727559,0.039914,0.464904,-2.149464,-0.014621,0.001195,-0.015549,0.421584,-0.030801,-0.027151,-0.005149,-0.005190,0.279197,5.509257,4.589849,15.204746,-0.033940,-0.0268,-0.2
10262,41700401,2018-05-31,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-6.805813,24.997946,30.014940,11.760503,13.674456,13.249553,16.349068,0.001497,-0.276208,2.162002,0.133173,0.142599,0.135582,17.496603,0.208186,0.240004,0.060294,0.053804,28.622001,22.680907,18.899855,-12.128419,0.156159,-2.475478,22.850680,24.319727,18.038562,18.829748,4.817384,5.494852,0.026933,-0.039400,4.004252,0.058660,0.071621,0.067915,7.295770,0.152782,0.165414,0.041547,0.040254,23.157270,21.450543,17.875265,-4.474183,0.069877,-4.927525,22.997943,21.110266,16.858231,16.657112,4.700494,2.332039,0.037624,-0.124785,0.884862,0.038770,0.065224,0.044524,9.023597,0.178870,0.186404,0.021020,0.021052,22.706641,18.601926,15.501797,-8.946479,0.068546,0.0668,0.0
10263,41700402,2018-06-03,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-1.735660,48.039405,52.935122,34.320275,36.081744,13.730435,16.860138,0.003471,-0.180183,3.496566,0.140760,0.173124,0.154847,20.349924,0.293185,0.335615,0.095600,0.090449,48.754574,42.976443,35.812727,-1.562648,0.162776,2.594676,45.892139,47.239909,40.598333,41.237035,5.298265,6.005922,0.028907,0.056625,5.338816,0.066247,0.102146,0.087180,10.149091,0.237780,0.261024,0.076853,0.076899,43.289843,41.746079,34.788137,6.091588,0.076493,0.142628,46.039402,44.030448,39.418003,39.064399,5.181376,2.843110,0.039598,-0.028760,2.219426,0.046357,0.095749,0.063788,11.876918,0.263869,0.282014,0.056326,0.057697,42.839214,38.897462,32.414670,1.619292,0.075162,0.2000,0.2
10264,41700403,2018-06-06,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-5.855421,3.774961,7.085470,-5.002585,-3.267599,8.787531,10.358464,-0.041571,-0.456330,-4.854561,0.093677,0.088699,0.090509,10.403114,0.081227,0.105418,0.031750,0.027287,5.969675,1.239254,1.031817,-10.723785,0.083938,3.020678,45.131277,45.731211,41.567714,42.187773,3.567341,3.546061,0.030014,0.043006,4.966708,0.059769,0.094150,0.080824,8.809521,0.231031,0.253456,0.077200,0.078267,42.364438,41.339766,34.449554,6.810539,0.065198,0.046155,44.313059,42.018386,40.581892,40.669459,3.625099,0.936293,0.032887,-0.138517,1.831461,0.043862,0.089129,0.063319,9.119358,0.243373,0.262944,0.057970,0.059872,41.765130,38.794093,32.328366,1.009552,0.061943,0.4000,0.4
10265,41700404,2018-06-08,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-19.367256,-115.147011,-106.586569,-134.663516,-131.270396,19.531470,24.688822,-0.164716,-0.934815,-20.379006,0.035194,-0.059989,-0.020818,-3.141634,-0.419949,-0.434051,-0.156135,-0.171489,-111.283703,-127.618594,-106.349575,-38.845680,-0.018221,1.158641,27.433056,29.403830,19.350920,20.561727,8.087685,8.844802,0.014570,-0.008158,3.341292,0.054819,0.081219,0.070885,7.213419,0.163228,0.181001,0.047947,0.046630,23.371155,19.321971,16.101383,3.005365,0.049566,-4.353589,23.085927,21.480146,16.559471,17.037318,2.445952,0.379266,-0.006439,-0.377668,-4.488649,0.026517,0.057305,0.035482,6.103586,0.142356,0.159750,0.006074,0.006047,21.329846,14.580366,12.150041,-8.207873,0.041073,0.6000,0.2

In [22]:
df_lc_sum_mean_max_cma12_diff = wide_get_cma_num_diff3(df_lc_sum_mean_max_ab,
                       ['season', 'team_id'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [12,1])
p(df_lc_sum_mean_max_cma12_diff)

(10266, 94)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,w_pct_cma12_diff,away_home__cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,2010-11,Regular Season,2010,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.000000,-1.000000
4,21000005,2010-10-27,2010-11,Regular Season,2010,1610612751,Nets,Nets,NJN,New Jersey,W,DET vs. NJN,DET,NJN,1610612765,Pistons,Pistons,DET,Detroit,L,DET vs. NJN,DET,NJN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,17.318256,71.996600,64.240402,63.700793,58.430147,8.278147,5.808385,0.068799,0.089831,2.772403,-0.039147,0.033314,-0.009905,6.041763,0.015400,0.038297,0.078231,0.084942,71.399120,81.103910,67.584931,35.069199,-0.041897,4.410990,14.644223,11.714746,11.252869,8.817884,3.384485,2.895616,0.017252,0.030880,0.067059,-0.025784,-0.008561,-0.021118,1.052684,-0.064973,-0.055460,0.008442,0.010547,15.028524,18.908925,15.756794,8.844680,-0.025662,7.635114,15.656687,13.591320,13.176070,12.269733,7.549719,6.616691,0.043466,0.165660,-1.113203,-0.013021,-0.000410,-0.012991,1.400942,-0.000465,0.000946,0.011304,0.012969,15.599917,22.878910,19.064495,15.391675,-0.021606,-0.136167,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-6.771330,-8.659764,-1.633332,-27.520548,-26.341919,18.875552,24.716189,-0.039321,-0.246636,-3.033305,0.074153,0.055153,0.054702,10.124345,-0.002112,0.029294,0.015061,0.005554,-9.276427,-17.082238,-14.235758,-12.430706,0.077618,-3.179814,3.792906,6.118285,-3.524334,-2.975915,7.323045,9.098293,-0.004332,-0.100652,0.643625,0.035395,0.035626,0.034909,4.383935,0.041782,0.052413,0.009260,0.006251,3.125087,0.650643,0.542105,-5.980846,0.034937,-5.316571,1.978425,1.162525,-7.576379,-7.779070,4.053055,2.284160,-0.017672,-0.266400,-3.502601,0.016260,0.029331,0.014761,5.839092,0.040007,0.051648,-0.004629,-0.009177,1.419312,-3.175107,-2.645922,-10.260795,0.028175,0.123333,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-2.844711,26.989535,33.176482,9.853496,10.693514,17.149093,22.490817,0.003898,0.008598,3.773464,0.084574,0.094928,0.083384,13.760434,0.152147,0.190118,0.056452,0.049735,23.862797,17.457815,14.547912,-4.430794,0.097010,-2.240572,12.719890,14.849430,5.677945,6.111475,7.047400,8.742103,0.006345,-0.039332,2.281427,0.038240,0.045509,0.042192,5.347476,0.079316,0.091794,0.019526,0.017238,11.384003,9.275562,7.729612,-4.071779,0.040302,-4.041445,12.281304,12.409114,2.502230,2.353923,4.827682,4.084364,-0.001466,-0.103052,-0.812787,0.024446,0.043179,0.027709,7.303451,0.081146,0.094915,0.007454,0.004549,10.175703,6.364962,5.304192,-7.677708,0.036283,0.170917,0.083333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-3.675643,16.949349,22.196808,1.123461,2.172115,15.837501,20.031880,-0.007398,-0.115202,2.003350,0.074529,0.081615,0.074781,10.590554,0.121055,0.147023,0.035205,0.028890,15.202883,9.765917,8.138043,-6.305228,0.082332,-2.179231,12.409374,14.260846,5.760432,6.225741,6.654006,8.039106,0.005847,-0.057729,2.189736,0.037149,0.045268,0.042334,4.856978,0.081225,0.091543,0.017489,0.015432,11.300778,9.471051,7.892526,-3.976111,0.038621,-4.077261,11.705311,11.500754,3.452483,3.359671,4.394247,3.522867,0.000651,-0.147553,-0.472447,0.024263,0.041471,0.027374,6.202977,0.084361,0.094886,0.004629,0.002473,10.425044,7.322999,6.102637,-7.701856,0.036174,0.254250,0.083333
10265,41700404,2018-06-08,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-5.047991,9.805671,15.393720,-6.784304,-5.277276,16.602118,20.678008,-0.018267,-0.179073,1.547989,0.079721,0.078142,0.075259,10.743936,0.097141,0.123704,0.018071,0.011331,7.170401,-1.583071,-1.319468,-9.133262,0.075642,-1.222020,21.954412,23.541759,15.037778,15.669320,6.921770,7.876446,0.016576,-0.022017,4.042304,0.046408,0.062431,0.056461,6.366854,0.127450,0.142044,0.029217,0.027912,19.625358,17.201449,14.334487,-1.954141,0.045364,-3.450349,21.389056,21.069992,13.026727,13.071295,5.046996,4.064955,0.011493,-0.130434,1.155796,0.033152,0.058946,0.041658,7.647686,0.130554,0.145161,0.010515,0.009783,18.365412,14.344706,11.953887,-6.440888,0.042800,0.365333,0.000000

In [23]:
df_lc_sum_mean_max_cma999_diff = wide_get_cma_num_diff3(df_lc_sum_mean_max_ab,
                       ['season', 'team_id'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [999,1])
p(df_lc_sum_mean_max_cma999_diff)

(10266, 94)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,w_pct_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,2010-11,Regular Season,2010,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.000000,-1.000000
4,21000005,2010-10-27,2010-11,Regular Season,2010,1610612751,Nets,Nets,NJN,New Jersey,W,DET vs. NJN,DET,NJN,1610612765,Pistons,Pistons,DET,Detroit,L,DET vs. NJN,DET,NJN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,19.159105,176.375992,143.688463,187.459589,190.054513,-11.103983,-46.321370,0.414678,0.393730,37.090801,-0.122039,0.386404,0.198716,32.279522,0.310448,0.295001,0.193852,0.177536,203.337934,215.991445,179.987279,38.751742,0.108908,-0.543754,-6.052768,-9.231191,-3.825283,-1.539100,-2.231859,-7.683247,0.030797,-0.085560,1.494556,-0.045985,0.016340,-0.005423,1.940087,-0.094303,-0.110626,-0.030743,-0.035409,4.515376,5.345412,4.453471,-1.480317,-0.013798,4.444511,30.752873,-9.819569,4.229659,16.070646,75.064537,27.165498,0.293530,1.007473,25.361786,-0.124436,0.015974,0.050575,4.150115,-0.020393,-0.046321,-0.071337,-0.092490,0.850150,9.866467,8.220363,8.135294,0.130921,0.018908,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-15.466440,11.602309,10.881629,-78.292272,-85.952397,89.889872,96.776930,-0.028803,0.401134,6.189346,0.146458,0.130546,0.112400,-0.211128,0.033858,0.093320,-0.080776,-0.080535,-53.949300,-72.640898,-60.530963,-29.251654,0.171630,-2.323803,16.689440,16.144048,-0.803375,-4.058061,17.491852,20.190836,0.001330,0.126900,2.348935,0.044449,0.042635,0.037790,1.915477,0.066708,0.085640,0.012222,0.012724,1.682201,-1.051951,-0.875970,-4.101885,0.044967,-5.151565,13.129785,12.801444,-9.173129,-23.654964,4.246442,11.579342,-0.037588,-0.041822,0.742495,0.110564,0.115293,0.059764,4.160423,0.061700,0.083756,0.053536,0.072731,1.935054,-3.718747,-3.098701,-8.451067,0.061168,0.140104,0.005051
10263,41700402,2018-06-03,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-15.184931,12.591039,11.876418,-76.522300,-84.096386,89.108704,95.916289,-0.027279,0.402338,6.313059,0.145884,0.131327,0.112836,-0.033692,0.038620,0.097935,-0.078368,-0.078093,-52.432600,-70.941504,-59.114836,-28.689373,0.170887,-2.168083,17.659970,17.117612,0.232645,-2.980457,17.426399,20.086922,0.002591,0.131065,2.515278,0.044907,0.044333,0.038999,2.075054,0.071278,0.090478,0.013765,0.014301,2.676993,-0.031434,-0.025549,-3.779381,0.045505,-4.968766,14.133801,13.806046,-8.056248,-22.384281,4.310512,11.558429,-0.035952,-0.036071,0.923670,0.110356,0.116256,0.060745,4.297056,0.066303,0.088596,0.054656,0.073698,2.926613,-2.672304,-2.226672,-8.087518,0.061535,0.148643,0.014950
10264,41700403,2018-06-06,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-15.041577,12.425918,11.719960,-75.815121,-83.313751,88.236449,94.977753,-0.027057,0.398084,6.245252,0.144424,0.129979,0.111685,-0.037530,0.038069,0.096786,-0.077673,-0.077405,-51.955825,-70.284603,-58.567448,-28.419846,0.169178,-2.148136,17.476375,16.939741,0.219611,-2.961602,17.255847,19.890305,0.002554,0.129708,2.489175,0.044459,0.043884,0.038605,2.053644,0.070535,0.089543,0.013611,0.014142,2.641526,-0.040685,-0.033264,-3.745110,0.045051,-4.922254,13.983070,13.658644,-7.989966,-22.176115,4.266976,11.443231,-0.035619,-0.035871,0.912129,0.109255,0.115086,0.060129,4.253167,0.065594,0.087663,0.054087,0.072941,2.887992,-2.656129,-2.213195,-8.012968,0.060913,0.157015,0.024655
10265,41700404,2018-06-08,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-15.278921,9.497631,8.993350,-78.242406,-85.611900,87.735659,94.549833,-0.030667,0.378235,5.760322,0.142580,0.126138,0.108779,-0.191223,0.025821,0.083538,-0.081439,-0.081489,-54.252651,-72.902879,-60.749372,-28.932519,0.165826,-2.125469,17.446586,16.961536,0.192715,-2.936944,17.253025,19.887558,0.002494,0.128444,2.497586,0.044595,0.044395,0.038956,2.125482,0.070756,0.089834,0.013609,0.014091,2.667022,-0.114562,-0.094836,-3.698397,0.044947,-4.957447,13.930945,13.642353,-7.995508,-22.037498,4.271775,11.397961,-0.035926,-0.041823,0.783898,0.108304,0.114449,0.059714,4.286916,0.065379,0.087494,0.052812,0.071459,2.861627,-2.807733,-2.339545,-8.105244,0.060465,0.165224,0.014658

In [24]:
columns_list = (df_lc_sum_mean_max_cma999_diff.columns)
pl(columns_list)

94

Index(['game_id', 'game_date', 'season', 'season_type', 'season_year',
       'team_id_a', 'Team_a', 'TEAM_NAME_a', 'TEAM_ABBREVIATION_a',
       'TEAM_CITY_a', 'wl_a', 'matchup_a', 'a_a', 'b_a', 'team_id_b', 'Team_b',
       'TEAM_NAME_b', 'TEAM_ABBREVIATION_b', 'TEAM_CITY_b', 'wl_b',
       'matchup_b', 'a_b', 'b_b', 'lc_sum_MIN_cma999_diff',
       'lc_sum_E_OFF_RATING_cma999_diff', 'lc_sum_OFF_RATING_cma999_diff',
       'lc_sum_E_DEF_RATING_cma999_diff', 'lc_sum_DEF_RATING_cma999_diff',
       'lc_sum_E_NET_RATING_cma999_diff', 'lc_sum_NET_RATING_cma999_diff',
       'lc_sum_AST_PCT_cma999_diff', 'lc_sum_AST_TOV_cma999_diff',
       'lc_sum_AST_RATIO_cma999_diff', 'lc_sum_OREB_PCT_cma999_diff',
       'lc_sum_DREB_PCT_cma999_diff', 'lc_sum_REB_PCT_cma999_diff',
       'lc_sum_TM_TOV_PCT_cma999_diff', 'lc_sum_EFG_PCT_cma999_diff',
       'lc_sum_TS_PCT_cma999_diff', 'lc_sum_USG_PCT_cma999_diff',
       'lc_sum_E_USG_PCT_cma999_diff', 'lc_sum_E_PACE_cma999_diff',
       'lc_sum_PACE_cma999_diff', 'lc_sum_PACE_PER40_cma999_diff',
       'lc_sum_POSS_cma999_diff', 'lc_sum_PIE_cma999_diff',
       'lc_mean_MIN_cma999_diff', 'lc_mean_E_OFF_RATING_cma999_diff',
       'lc_mean_OFF_RATING_cma999_diff', 'lc_mean_E_DEF_RATING_cma999_diff',
       'lc_mean_DEF_RATING_cma999_diff', 'lc_mean_E_NET_RATING_cma999_diff',
       'lc_mean_NET_RATING_cma999_diff', 'lc_mean_AST_PCT_cma999_diff',
       'lc_mean_AST_TOV_cma999_diff', 'lc_mean_AST_RATIO_cma999_diff',
       'lc_mean_OREB_PCT_cma999_diff', 'lc_mean_DREB_PCT_cma999_diff',
       'lc_mean_REB_PCT_cma999_diff', 'lc_mean_TM_TOV_PCT_cma999_diff',
       'lc_mean_EFG_PCT_cma999_diff', 'lc_mean_TS_PCT_cma999_diff',
       'lc_mean_USG_PCT_cma999_diff', 'lc_mean_E_USG_PCT_cma999_diff',
       'lc_mean_E_PACE_cma999_diff', 'lc_mean_PACE_cma999_diff',
       'lc_mean_PACE_PER40_cma999_diff', 'lc_mean_POSS_cma999_diff',
       'lc_mean_PIE_cma999_diff', 'lc_max_MIN_cma999_diff',
       'lc_max_E_OFF_RATING_cma999_diff', 'lc_max_OFF_RATING_cma999_diff',
       'lc_max_E_DEF_RATING_cma999_diff', 'lc_max_DEF_RATING_cma999_diff',
       'lc_max_E_NET_RATING_cma999_diff', 'lc_max_NET_RATING_cma999_diff',
       'lc_max_AST_PCT_cma999_diff', 'lc_max_AST_TOV_cma999_diff',
       'lc_max_AST_RATIO_cma999_diff', 'lc_max_OREB_PCT_cma999_diff',
       'lc_max_DREB_PCT_cma999_diff', 'lc_max_REB_PCT_cma999_diff',
       'lc_max_TM_TOV_PCT_cma999_diff', 'lc_max_EFG_PCT_cma999_diff',
       'lc_max_TS_PCT_cma999_diff', 'lc_max_USG_PCT_cma999_diff',
       'lc_max_E_USG_PCT_cma999_diff', 'lc_max_E_PACE_cma999_diff',
       'lc_max_PACE_cma999_diff', 'lc_max_PACE_PER40_cma999_diff',
       'lc_max_POSS_cma999_diff', 'lc_max_PIE_cma999_diff',
       'w_pct_cma999_diff', 'away_home__cma999_diff'],
      dtype='object')

In [25]:
columns_list_not_diff = [k for k in columns_list if not k.endswith('_diff')]
pl(columns_list_not_diff)

23

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'team_id_a',
 'Team_a',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'team_id_b',
 'Team_b',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b']

In [26]:
df_temp = pd.merge(df_lc_sum_mean_max_cma5_diff, df_lc_sum_mean_max_cma12_diff, on=columns_list_not_diff)
p(df_temp)

(10266, 165)

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,w_pct_cma5_diff,away_home__cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,w_pct_cma12_diff,away_home__cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,2010-11,Regular Season,2010,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.0000,-1.0,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.000000,-1.000000
4,21000005,2010-10-27,2010-11,Regular Season,2010,1610612751,Nets,Nets,NJN,New Jersey,W,DET vs. NJN,DET,NJN,1610612765,Pistons,Pistons,DET,Detroit,L,DET vs. NJN,DET,NJN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,31.999206,153.530749,146.182173,134.628644,130.924314,18.884348,15.260006,0.139548,0.775662,12.872695,0.018867,0.145735,0.074359,12.977122,0.456749,0.489657,0.197222,0.207522,138.793051,146.674582,122.227353,66.118610,-0.004319,3.980618,2.558975,1.020145,-5.667162,-7.173202,8.220550,8.193097,-0.000614,0.113836,-1.870235,-0.026135,-0.015662,-0.027743,-1.218917,-0.081358,-0.081835,-0.014827,-0.014220,-0.488711,1.638810,1.365246,8.250536,-0.046982,7.513777,2.727645,3.039995,-4.122781,-4.171058,8.864994,9.727559,0.039914,0.464904,-2.149464,-0.014621,0.001195,-0.015549,0.421584,-0.030801,-0.027151,-0.005149,-0.005190,0.279197,5.509257,4.589849,15.204746,-0.033940,-0.0268,-0.2,17.318256,71.996600,64.240402,63.700793,58.430147,8.278147,5.808385,0.068799,0.089831,2.772403,-0.039147,0.033314,-0.009905,6.041763,0.015400,0.038297,0.078231,0.084942,71.399120,81.103910,67.584931,35.069199,-0.041897,4.410990,14.644223,11.714746,11.252869,8.817884,3.384485,2.895616,0.017252,0.030880,0.067059,-0.025784,-0.008561,-0.021118,1.052684,-0.064973,-0.055460,0.008442,0.010547,15.028524,18.908925,15.756794,8.844680,-0.025662,7.635114,15.656687,13.591320,13.176070,12.269733,7.549719,6.616691,0.043466,0.165660,-1.113203,-0.013021,-0.000410,-0.012991,1.400942,-0.000465,0.000946,0.011304,0.012969,15.599917,22.878910,19.064495,15.391675,-0.021606,-0.136167,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-6.805813,24.997946,30.014940,11.760503,13.674456,13.249553,16.349068,0.001497,-0.276208,2.162002,0.133173,0.142599,0.135582,17.496603,0.208186,0.240004,0.060294,0.053804,28.622001,22.680907,18.899855,-12.128419,0.156159,-2.475478,22.850680,24.319727,18.038562,18.829748,4.817384,5.494852,0.026933,-0.039400,4.004252,0.058660,0.071621,0.067915,7.295770,0.152782,0.165414,0.041547,0.040254,23.157270,21.450543,17.875265,-4.474183,0.069877,-4.927525,22.997943,21.110266,16.858231,16.657112,4.700494,2.332039,0.037624,-0.124785,0.884862,0.038770,0.065224,0.044524,9.023597,0.178870,0.186404,0.021020,0.021052,22.706641,18.601926,15.501797,-8.946479,0.068546,0.0668,0.0,-6.771330,-8.659764,-1.633332,-27.520548,-26.341919,18.875552,24.716189,-0.039321,-0.246636,-3.033305,0.074153,0.055153,0.054702,10.124345,-0.002112,0.029294,0.015061,0.005554,-9.276427,-17.082238,-14.235758,-12.430706,0.077618,-3.179814,3.792906,6.118285,-3.524334,-2.975915,7.323045,9.098293,-0.004332,-0.100652,0.643625,0.035395,0.035626,0.034909,4.383935,0.041782,0.052413,0.009260,0.006251,3.125087,0.650643,0.542105,-5.980846,0.034937,-5.316571,1.978425,1.162525,-7.576379,-7.779070,4.053055,2.284160,-0.017672,-0.266400,-3.502601,0.016260,0.029331,0.014761,5.839092,0.040007,0.051648,-0.004629,-0.009177,1.419312,-3.175107,-2.645922,-10.260795,0.028175,0.123333,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-1.735660,48.039405,52.935122,34.320275,36.081744,13.730435,16.860138,0.003471,-0.180183,3.496566,0.140760,0.173124,0.154847,20.349924,0.293185,0.335615,0.095600,0.090449,48.754574,42.976443,35.812727,-1.562648,0.162776,2.594676,45.892139,47.239909,40.598333,41.237035,5.298265,6.005922,0.028907,0.056625,5.338816,0.066247,0.102146,0.087180,10.149091,0.237780,0.261024,0.076853,0.076899,43.289843,41.746079,34.788137,6.091588,0.076493,0.142628,46.039402,44.030448,39.418003,39.064399,5.181376,2.843110,0.039598,-0.028760,2.219426,0.046357,0.095749,0.063788,11.876918,0.263869,0.282014,0.056326,0.057697,42.839214,38.897462,32.414670,1.619292,0.075162,0.2000,0.2,-2.844711,26.989535,33.176482,9.853496,10.693514,17.149093,22.490817,0.003898,0.008598,3.773464,0.084574,0.094928,0.083384,13.760434,0.152147,0.190118,0.056452,0.049735,23.862797,17.457815,14.547912,-4.430794,0.097010,-2.240572,12.719890,14.849430,5.677945,6.111475,7.047400,8.742103,0.006345,-0.039332,2.281427,0.038240,0.045509,0.042192,5.347476,0.079316,0.091794,0.019526,0.017238,11.384003,9.275562,7.729612,-4.071779,0.040302,-4.041445,12.281304,12.409114,2.502230,2.353923,4.827682,4.084364,-0.001466,-0.103052,-0.812787,0.024446,0.043179,0.027709,7.303451,0.081146,0.094915,0.007454,0.004549,10.175703,6.364962,5.304192,-7.677708,0.036283,0.170917,0.083333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-5.855421,3.774961,7.085470,-5.002585,-3.267599,8.787531,10.358464,-0.041571,-0.456330,-4.854561,0.093677,0.088699,0.090509,10.403114,0.081227,0.105418,0.031750,0.027287,5.969675,1.239254,1.031817,-10.723785,0.083938,3.020678,45.131277,45.731211,41.567714,42.187773,3.567341,3.546061,0.030014,0.043006,4.966708,0.059769,0.094150,0.080824,8.809521,0.231031,0.253456,0.077200,0.078267,42.364438,41.339766,34.449554,6.810539,0.065198,0.046155,44.313059,42.018386,40.581892,40.669459,3.625099,0.936293,0.032887,-0.138517,1.831461,0.043862,0.089129,0.063319,9.119358,0.243373,0.262944,0.057970,0.059872,41.765130,38.794093,32.328366,1.009552,0.061943,0.4000,0.4,-3.675643,16.949349,22.196808,1.123461,2.172115,15.837501,20.031880,-0.007398,-0.115202,2.003350,0.074529,0.081615,0.074781,10.590554,0.121055,0.147023,0.035205,0.028890,15.202883,9.765917,8.138043,-6.305228,0.082332,-2.179231,12.409374,14.260846,5.760432,6.225741,6.654006,8.039106,0.005847,-0.057729,2.189736,0.037149,0.045268,0.042334,4.856978,0.081225,0.091543,0.017489,0.015432,11.300778,9.471051,7.892526,-3.976111,0.038621,-4.077261,11.705311,11.500754,3.452483,3.359671,4.394247,3.522867,0.000651,-0.147553,-0.472447,0.024263,0.041471,0.027374,6.202977,0.084361,0.094886,0.004629,0.002473,10.425044,7.322999,6.102637,-7.701856,0.036174,0.254250,0.083333
10265,41700404,2018-06-08,2017-18,Playoffs,2017,1610612744,Warriors,Warriors,GSW,Golden State,W,CLE vs. GSW,CLE,GSW,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,L,CLE vs. GSW,CLE,GSW,-19.367256,-115.147011,-106.586569,-134.663516,-131.270396,19.531470,24.688822,-0.164716,-0.934815,-20.379006,0.035194,-0.059989,-0.020818,-3.141634,-0.419949,-0.434051,-0.156135,-0.171489,-111.283703,-127.618594,-106.349575,-38.845680,-0.018221,1.158641,27.433056,29.403830,19.350920,20.561727,8.087685,8.844802,0.014570,-0.008158,3.341292,0.054819,0.081219,0.070885,7.213419,0.163228,0.181001,0.047947,0.046630,23.371155,19.321971,16.101383,3.005365,0.049566,-4.353589,23.085927,21.480146,16.559471,17.037318,2.445952,0.379266,-0.006439,-0.377668,-4.488649,0.026517,0.057305,0.035482,6.103586,0.142356,0.159750,0.006074,0.006047,21.329846,14.580366,12.150041,-8.207873,0.041073,0.6000,0.2,-5.047991,9.805671,15.393720,-6.784304,-5.277276,16.602118,20.678008,-0.018267,-0.179073,1.547989,0.079721,0.078142,0.075259,10.743936,0.097141,0.123704,0.018071,0.011331,7.170401,-1.583071,-1.319468,-9.133262,0.075642,-1.222020,21.954412,23.541759,15.037778,15.669320,6.921770,7.876446,0.016576,-0.022017,4.042304,0.046408,0.062431,0.056461,6.366854,0.127450,0.142044,0.029217,0.027912,19.625358,17.201449,14.334487,-1.954141,0.045364,-3.450349,21.389056,21.069992,13.026727,13.071295,5.046996,4.064955,0.011493,-0.130434,1.155796,0.033152,0.058946,0.041658,7.647686,0.130554,0.145161,0.010515,0.009783,18.365412,14.344706,11.953887,-6.440888,0.042800,0.365333,0.000000

In [27]:
df_temp = pd.merge(df_temp, df_lc_sum_mean_max_cma999_diff, on=columns_list_not_diff)
p(df_temp)

(10266, 236)

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,w_pct_cma5_diff,away_home__cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,w_pct_cma12_diff,away_home__cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,w_pct_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,2010-11,Regular Season,2010,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.0000,-1.0,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.000000,-1.000000,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.000000,-1.000000
4,21000005,2010-10-27,2010-11,Regular Season,2010,1610612751,Nets,Nets,NJN,New Jersey,W,DET vs. NJN,DET,NJN,1610612765,Pistons,Pistons,DET,Detroit,L,DET vs. NJN,DET,NJN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,31.999206,153.530749,146.182173,134.628644,130.924314,18.884348,15.260006,0.139548,0.775662,12.872695,0.018867,0.145735,0.074359,12.977122,0.456749,0.489657,0.197222,0.207522,138.793051,146.674582,122.227353,66.118610,-0.004319,3.980618,2.558975,1.020145,-5.667162,-7.173202,8.220550,8.193097,-0.000614,0.113836,-1.870235,-0.026135,-0.015662,-0.027743,-1.218917,-0.081358,-0.081835,-0.014827,-0.014220,-0.488711,1.638810,1.365246,8.250536,-0.046982,7.513777,2.727645,3.039995,-4.122781,-4.171058,8.864994,9.727559,0.039914,0.464904,-2.149464,-0.014621,0.001195,-0.015549,0.421584,-0.030801,-0.027151,-0.005149,-0.005190,0.279197,5.509257,4.589849,15.204746,-0.033940,-0.0268,-0.2,17.318256,71.996600,64.240402,63.700793,58.430147,8.278147,5.808385,0.068799,0.089831,2.772403,-0.039147,0.033314,-0.009905,6.041763,0.015400,0.038297,0.078231,0.084942,71.399120,81.103910,67.584931,35.069199,-0.041897,4.410990,14.644223,11.714746,11.252869,8.817884,3.384485,2.895616,0.017252,0.030880,0.067059,-0.025784,-0.008561,-0.021118,1.052684,-0.064973,-0.055460,0.008442,0.010547,15.028524,18.908925,15.756794,8.844680,-0.025662,7.635114,15.656687,13.591320,13.176070,12.269733,7.549719,6.616691,0.043466,0.165660,-1.113203,-0.013021,-0.000410,-0.012991,1.400942,-0.000465,0.000946,0.011304,0.012969,15.599917,22.878910,19.064495,15.391675,-0.021606,-0.136167,0.000000,19.159105,176.375992,143.688463,187.459589,190.054513,-11.103983,-46.321370,0.414678,0.393730,37.090801,-0.122039,0.386404,0.198716,32.279522,0.310448,0.295001,0.193852,0.177536,203.337934,215.991445,179.987279,38.751742,0.108908,-0.543754,-6.052768,-9.231191,-3.825283,-1.539100,-2.231859,-7.683247,0.030797,-0.085560,1.494556,-0.045985,0.016340,-0.005423,1.940087,-0.094303,-0.110626,-0.030743,-0.035409,4.515376,5.345412,4.453471,-1.480317,-0.013798,4.444511,30.752873,-9.819569,4.229659,16.070646,75.064537,27.165498,0.293530,1.007473,25.361786,-0.124436,0.015974,0.050575,4.150115,-0.020393,-0.046321,-0.071337,-0.092490,0.850150,9.866467,8.220363,8.135294,0.130921,0.018908,0.000000

In [28]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '57Alost_contribution_mean_sum_max_cma5_cma12_cma999_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_temp.to_csv(datapath_df, index=False)

In [29]:
df_readback = rcp('57Alost_contribution_mean_sum_max_cma5_cma12_cma999_diff_2010_2018.csv')
p(df_readback)

(10266, 236)

,game_id,game_date,season,season_type,season_year,team_id_a,Team_a,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,wl_a,matchup_a,a_a,b_a,team_id_b,Team_b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,wl_b,matchup_b,a_b,b_b,lc_sum_MIN_cma5_diff,lc_sum_E_OFF_RATING_cma5_diff,lc_sum_OFF_RATING_cma5_diff,lc_sum_E_DEF_RATING_cma5_diff,lc_sum_DEF_RATING_cma5_diff,lc_sum_E_NET_RATING_cma5_diff,lc_sum_NET_RATING_cma5_diff,lc_sum_AST_PCT_cma5_diff,lc_sum_AST_TOV_cma5_diff,lc_sum_AST_RATIO_cma5_diff,lc_sum_OREB_PCT_cma5_diff,lc_sum_DREB_PCT_cma5_diff,lc_sum_REB_PCT_cma5_diff,lc_sum_TM_TOV_PCT_cma5_diff,lc_sum_EFG_PCT_cma5_diff,lc_sum_TS_PCT_cma5_diff,lc_sum_USG_PCT_cma5_diff,lc_sum_E_USG_PCT_cma5_diff,lc_sum_E_PACE_cma5_diff,lc_sum_PACE_cma5_diff,lc_sum_PACE_PER40_cma5_diff,lc_sum_POSS_cma5_diff,lc_sum_PIE_cma5_diff,lc_mean_MIN_cma5_diff,lc_mean_E_OFF_RATING_cma5_diff,lc_mean_OFF_RATING_cma5_diff,lc_mean_E_DEF_RATING_cma5_diff,lc_mean_DEF_RATING_cma5_diff,lc_mean_E_NET_RATING_cma5_diff,lc_mean_NET_RATING_cma5_diff,lc_mean_AST_PCT_cma5_diff,lc_mean_AST_TOV_cma5_diff,lc_mean_AST_RATIO_cma5_diff,lc_mean_OREB_PCT_cma5_diff,lc_mean_DREB_PCT_cma5_diff,lc_mean_REB_PCT_cma5_diff,lc_mean_TM_TOV_PCT_cma5_diff,lc_mean_EFG_PCT_cma5_diff,lc_mean_TS_PCT_cma5_diff,lc_mean_USG_PCT_cma5_diff,lc_mean_E_USG_PCT_cma5_diff,lc_mean_E_PACE_cma5_diff,lc_mean_PACE_cma5_diff,lc_mean_PACE_PER40_cma5_diff,lc_mean_POSS_cma5_diff,lc_mean_PIE_cma5_diff,lc_max_MIN_cma5_diff,lc_max_E_OFF_RATING_cma5_diff,lc_max_OFF_RATING_cma5_diff,lc_max_E_DEF_RATING_cma5_diff,lc_max_DEF_RATING_cma5_diff,lc_max_E_NET_RATING_cma5_diff,lc_max_NET_RATING_cma5_diff,lc_max_AST_PCT_cma5_diff,lc_max_AST_TOV_cma5_diff,lc_max_AST_RATIO_cma5_diff,lc_max_OREB_PCT_cma5_diff,lc_max_DREB_PCT_cma5_diff,lc_max_REB_PCT_cma5_diff,lc_max_TM_TOV_PCT_cma5_diff,lc_max_EFG_PCT_cma5_diff,lc_max_TS_PCT_cma5_diff,lc_max_USG_PCT_cma5_diff,lc_max_E_USG_PCT_cma5_diff,lc_max_E_PACE_cma5_diff,lc_max_PACE_cma5_diff,lc_max_PACE_PER40_cma5_diff,lc_max_POSS_cma5_diff,lc_max_PIE_cma5_diff,w_pct_cma5_diff,away_home__cma5_diff,lc_sum_MIN_cma12_diff,lc_sum_E_OFF_RATING_cma12_diff,lc_sum_OFF_RATING_cma12_diff,lc_sum_E_DEF_RATING_cma12_diff,lc_sum_DEF_RATING_cma12_diff,lc_sum_E_NET_RATING_cma12_diff,lc_sum_NET_RATING_cma12_diff,lc_sum_AST_PCT_cma12_diff,lc_sum_AST_TOV_cma12_diff,lc_sum_AST_RATIO_cma12_diff,lc_sum_OREB_PCT_cma12_diff,lc_sum_DREB_PCT_cma12_diff,lc_sum_REB_PCT_cma12_diff,lc_sum_TM_TOV_PCT_cma12_diff,lc_sum_EFG_PCT_cma12_diff,lc_sum_TS_PCT_cma12_diff,lc_sum_USG_PCT_cma12_diff,lc_sum_E_USG_PCT_cma12_diff,lc_sum_E_PACE_cma12_diff,lc_sum_PACE_cma12_diff,lc_sum_PACE_PER40_cma12_diff,lc_sum_POSS_cma12_diff,lc_sum_PIE_cma12_diff,lc_mean_MIN_cma12_diff,lc_mean_E_OFF_RATING_cma12_diff,lc_mean_OFF_RATING_cma12_diff,lc_mean_E_DEF_RATING_cma12_diff,lc_mean_DEF_RATING_cma12_diff,lc_mean_E_NET_RATING_cma12_diff,lc_mean_NET_RATING_cma12_diff,lc_mean_AST_PCT_cma12_diff,lc_mean_AST_TOV_cma12_diff,lc_mean_AST_RATIO_cma12_diff,lc_mean_OREB_PCT_cma12_diff,lc_mean_DREB_PCT_cma12_diff,lc_mean_REB_PCT_cma12_diff,lc_mean_TM_TOV_PCT_cma12_diff,lc_mean_EFG_PCT_cma12_diff,lc_mean_TS_PCT_cma12_diff,lc_mean_USG_PCT_cma12_diff,lc_mean_E_USG_PCT_cma12_diff,lc_mean_E_PACE_cma12_diff,lc_mean_PACE_cma12_diff,lc_mean_PACE_PER40_cma12_diff,lc_mean_POSS_cma12_diff,lc_mean_PIE_cma12_diff,lc_max_MIN_cma12_diff,lc_max_E_OFF_RATING_cma12_diff,lc_max_OFF_RATING_cma12_diff,lc_max_E_DEF_RATING_cma12_diff,lc_max_DEF_RATING_cma12_diff,lc_max_E_NET_RATING_cma12_diff,lc_max_NET_RATING_cma12_diff,lc_max_AST_PCT_cma12_diff,lc_max_AST_TOV_cma12_diff,lc_max_AST_RATIO_cma12_diff,lc_max_OREB_PCT_cma12_diff,lc_max_DREB_PCT_cma12_diff,lc_max_REB_PCT_cma12_diff,lc_max_TM_TOV_PCT_cma12_diff,lc_max_EFG_PCT_cma12_diff,lc_max_TS_PCT_cma12_diff,lc_max_USG_PCT_cma12_diff,lc_max_E_USG_PCT_cma12_diff,lc_max_E_PACE_cma12_diff,lc_max_PACE_cma12_diff,lc_max_PACE_PER40_cma12_diff,lc_max_POSS_cma12_diff,lc_max_PIE_cma12_diff,w_pct_cma12_diff,away_home__cma12_diff,lc_sum_MIN_cma999_diff,lc_sum_E_OFF_RATING_cma999_diff,lc_sum_OFF_RATING_cma999_diff,lc_sum_E_DEF_RATING_cma999_diff,lc_sum_DEF_RATING_cma999_diff,lc_sum_E_NET_RATING_cma999_diff,lc_sum_NET_RATING_cma999_diff,lc_sum_AST_PCT_cma999_diff,lc_sum_AST_TOV_cma999_diff,lc_sum_AST_RATIO_cma999_diff,lc_sum_OREB_PCT_cma999_diff,lc_sum_DREB_PCT_cma999_diff,lc_sum_REB_PCT_cma999_diff,lc_sum_TM_TOV_PCT_cma999_diff,lc_sum_EFG_PCT_cma999_diff,lc_sum_TS_PCT_cma999_diff,lc_sum_USG_PCT_cma999_diff,lc_sum_E_USG_PCT_cma999_diff,lc_sum_E_PACE_cma999_diff,lc_sum_PACE_cma999_diff,lc_sum_PACE_PER40_cma999_diff,lc_sum_POSS_cma999_diff,lc_sum_PIE_cma999_diff,lc_mean_MIN_cma999_diff,lc_mean_E_OFF_RATING_cma999_diff,lc_mean_OFF_RATING_cma999_diff,lc_mean_E_DEF_RATING_cma999_diff,lc_mean_DEF_RATING_cma999_diff,lc_mean_E_NET_RATING_cma999_diff,lc_mean_NET_RATING_cma999_diff,lc_mean_AST_PCT_cma999_diff,lc_mean_AST_TOV_cma999_diff,lc_mean_AST_RATIO_cma999_diff,lc_mean_OREB_PCT_cma999_diff,lc_mean_DREB_PCT_cma999_diff,lc_mean_REB_PCT_cma999_diff,lc_mean_TM_TOV_PCT_cma999_diff,lc_mean_EFG_PCT_cma999_diff,lc_mean_TS_PCT_cma999_diff,lc_mean_USG_PCT_cma999_diff,lc_mean_E_USG_PCT_cma999_diff,lc_mean_E_PACE_cma999_diff,lc_mean_PACE_cma999_diff,lc_mean_PACE_PER40_cma999_diff,lc_mean_POSS_cma999_diff,lc_mean_PIE_cma999_diff,lc_max_MIN_cma999_diff,lc_max_E_OFF_RATING_cma999_diff,lc_max_OFF_RATING_cma999_diff,lc_max_E_DEF_RATING_cma999_diff,lc_max_DEF_RATING_cma999_diff,lc_max_E_NET_RATING_cma999_diff,lc_max_NET_RATING_cma999_diff,lc_max_AST_PCT_cma999_diff,lc_max_AST_TOV_cma999_diff,lc_max_AST_RATIO_cma999_diff,lc_max_OREB_PCT_cma999_diff,lc_max_DREB_PCT_cma999_diff,lc_max_REB_PCT_cma999_diff,lc_max_TM_TOV_PCT_cma999_diff,lc_max_EFG_PCT_cma999_diff,lc_max_TS_PCT_cma999_diff,lc_max_USG_PCT_cma999_diff,lc_max_E_USG_PCT_cma999_diff,lc_max_E_PACE_cma999_diff,lc_max_PACE_cma999_diff,lc_max_PACE_PER40_cma999_diff,lc_max_POSS_cma999_diff,lc_max_PIE_cma999_diff,w_pct_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,1610612748,Heat,Heat,MIA,Miami,L,BOS vs. MIA,BOS,MIA,1610612738,Celtics,Celtics,BOS,Boston,W,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,1610612757,Trail Blazers,Trail Blazers,POR,Portland,W,PHX vs. POR,PHX,POR,1610612756,Suns,Suns,PHX,Phoenix,L,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,1610612747,Lakers,Lakers,LAL,Los Angeles,W,HOU vs. LAL,HOU,LAL,1610612745,Rockets,Rockets,HOU,Houston,L,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,2010-11,Regular Season,2010,1610612739,Cavaliers,Cavaliers,CLE,Cleveland,W,BOS vs. CLE,BOS,CLE,1610612738,Celtics,Celtics,BOS,Boston,L,BOS vs. CLE,BOS,CLE,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.0000,-1.0,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.000000,-1.000000,-51.924227,-211.872235,-213.259085,-201.560675,-204.284577,-10.321001,-8.965179,-0.271101,-1.990024,-34.827346,-0.106651,-0.289929,-0.204024,-31.643285,-0.998045,-1.058208,-0.339048,-0.345030,-186.953514,-185.147720,-154.291124,-99.953981,-0.183028,-25.962114,-105.936118,-106.629543,-100.780337,-102.142288,-5.160501,-4.482590,-0.135551,-0.995012,-17.413673,-0.053326,-0.144965,-0.102012,-15.821643,-0.499022,-0.529104,-0.169524,-0.172515,-93.476757,-92.573860,-77.145562,-49.976991,-0.091514,-27.011551,-106.862376,-107.916832,-101.867606,-103.301408,-7.170297,-6.925743,-0.215141,-1.477746,-25.788732,-0.084158,-0.204901,-0.148109,-19.710891,-0.571594,-0.580842,-0.173662,-0.177535,-93.861683,-92.810396,-77.342673,-52.108911,-0.092296,-1.000000,-1.000000
4,21000005,2010-10-27,2010-11,Regular Season,2010,1610612751,Nets,Nets,NJN,New Jersey,W,DET vs. NJN,DET,NJN,1610612765,Pistons,Pistons,DET,Detroit,L,DET vs. NJN,DET,NJN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,1610612745,Rockets,Rockets,HOU,Houston,L,GSW vs. HOU,GSW,HOU,1610612744,Warriors,Warriors,GSW,Golden State,W,GSW vs. HOU,GSW,HOU,31.999206,153.530749,146.182173,134.628644,130.924314,18.884348,15.260006,0.139548,0.775662,12.872695,0.018867,0.145735,0.074359,12.977122,0.456749,0.489657,0.197222,0.207522,138.793051,146.674582,122.227353,66.118610,-0.004319,3.980618,2.558975,1.020145,-5.667162,-7.173202,8.220550,8.193097,-0.000614,0.113836,-1.870235,-0.026135,-0.015662,-0.027743,-1.218917,-0.081358,-0.081835,-0.014827,-0.014220,-0.488711,1.638810,1.365246,8.250536,-0.046982,7.513777,2.727645,3.039995,-4.122781,-4.171058,8.864994,9.727559,0.039914,0.464904,-2.149464,-0.014621,0.001195,-0.015549,0.421584,-0.030801,-0.027151,-0.005149,-0.005190,0.279197,5.509257,4.589849,15.204746,-0.033940,-0.0268,-0.2,17.318256,71.996600,64.240402,63.700793,58.430147,8.278147,5.808385,0.068799,0.089831,2.772403,-0.039147,0.033314,-0.009905,6.041763,0.015400,0.038297,0.078231,0.084942,71.399120,81.103910,67.584931,35.069199,-0.041897,4.410990,14.644223,11.714746,11.252869,8.817884,3.384485,2.895616,0.017252,0.030880,0.067059,-0.025784,-0.008561,-0.021118,1.052684,-0.064973,-0.055460,0.008442,0.010547,15.028524,18.908925,15.756794,8.844680,-0.025662,7.635114,15.656687,13.591320,13.176070,12.269733,7.549719,6.616691,0.043466,0.165660,-1.113203,-0.013021,-0.000410,-0.012991,1.400942,-0.000465,0.000946,0.011304,0.012969,15.599917,22.878910,19.064495,15.391675,-0.021606,-0.136167,0.000000,19.159105,176.375992,143.688463,187.459589,190.054513,-11.103983,-46.321370,0.414678,0.393730,37.090801,-0.122039,0.386404,0.198716,32.279522,0.310448,0.295001,0.193852,0.177536,203.337934,215.991445,179.987279,38.751742,0.108908,-0.543754,-6.052768,-9.231191,-3.825283,-1.539100,-2.231859,-7.683247,0.030797,-0.085560,1.494556,-0.045985,0.016340,-0.005423,1.940087,-0.094303,-0.110626,-0.030743,-0.035409,4.515376,5.345412,4.453471,-1.480317,-0.013798,4.444511,30.752873,-9.819569,4.229659,16.070646,75.064537,27.165498,0.293530,1.007473,25.361786,-0.124436,0.015974,0.050575,4.150115,-0.020393,-0.046321,-0.071337,-0.092490,0.850150,9.866467,8.220363,8.135294,0.130921,0.018908,0.000000