In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f



def feature_engineer(df_, group_by_columns_, column_features_, operators_, window_size_, shift_num_=1):
    
    '''
    example operators: 'max', 'min', 'count', 'median', 'mean'
    '''
    df_.groupby([group_by_columns_])\
           [column_features_]\
           .rolling(window_size_,1).agg([operators_])\
           .shift(shift_num_)

In [4]:
df_71A_merge_62_63_64_2010_2018 = \
rcp('71A_merge_62_63_64_2010_2018.csv')

p(df_71A_merge_62_63_64_2010_2018)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0

In [5]:
df_71B_merge_65A_65B_66A_66B_2010_2018 = \
rcp('71B_merge_65A_65B_66A_66B_2010_2018.csv')

p(df_71B_merge_65A_65B_66A_66B_2010_2018)

(20532, 133)

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3338: DtypeWarning: Columns (71,72) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,4.0,3.0,7.0,0.571429,0.428571,51.0,52.0,103.0,0.495146,0.504854
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,4.0,6.0,0.333333,0.666667,46.0,45.0,91.0,0.505495,0.494505
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,3.0,5.0,0.400000,0.600000,41.0,41.0,82.0,0.500000,0.500000
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.00,1.00,0.0,1.0,1.0,0.000000,1.000000,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,4.0,1.0,5.0,0.800000,0.200000,4.0,3.0,7.0,0.571429,0.428571,44.0,44.0,88.0,0.500000,0.500000
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.00,0.00,1.0,0.0,1.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.600000,0.400000,41.0,41.0,82.0,0.500000,0.500000
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631,3 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333
20528,20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,3 days,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000
20529,20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631,3 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000
20530,20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,2 days,0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000
20531,20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631,2 days,0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000

In [6]:
column_names_common_list = [k for k in df_71A_merge_62_63_64_2010_2018.columns
                            if k in df_71B_merge_65A_65B_66A_66B_2010_2018.columns]
pl(column_names_common_list)

72

['game_id',
 'TEAM_NAME',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'MIN',
 'duration',
 'E_OFF_RATING',
 'OFF_RATING',
 'E_DEF_RATING',
 'DEF_RATING',
 'E_NET_RATING',
 'NET_RATING',
 'AST_PCT',
 'AST_TOV',
 'AST_RATIO',
 'OREB_PCT',
 'DREB_PCT',
 'REB_PCT',
 'E_TM_TOV_PCT',
 'TM_TOV_PCT',
 'EFG_PCT',
 'TS_PCT',
 'USG_PCT',
 'E_USG_PCT',
 'E_PACE',
 'PACE',
 'PACE_PER40',
 'POSS',
 'PIE',
 'duration_minutes',
 'team_id',
 'w_pct',
 'min',
 'fgm',
 'fga',
 'fg_pct',
 'fg3m',
 'fg3a',
 'fg3_pct',
 'ftm',
 'fta',
 'ft_pct',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'wl',
 'spread',
 'away_home_',
 'game_date',
 'matchup',
 'season_type',
 'season',
 'season_year',
 'latitude',
 'longitude',
 'game_latitude',
 'game_longitude',
 'travel_distance',
 'game_time_zone',
 'time_zone',
 'time_zone_diff',
 'time_zone_diff_abs',
 'city_proper_metro_area',
 'Country/Region',
 'city_proper_metro_area_GDP_bil',
 'city_proper_metro_area_GDP_bil1']

In [7]:
df_merged = pd.merge(df_71A_merge_62_63_64_2010_2018, 
                     df_71B_merge_65A_65B_66A_66B_2010_2018,
                     on=column_names_common_list,
                     how='outer',
                     indicator=True)
p(df_merged)

(38785, 134)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,index,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999,_merge
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
38780,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631,20527.0,3 days,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.138614,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,49.0,52.0,101.0,0.485149,0.514851,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,right_only
38781,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,20528.0,3 days,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.126214,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.5,0.5,2.0,1.0,3.0,0.666667,0.333333,3.0,1.0,4.0,0.75,0.25,52.0,51.0,103.0,0.504854,0.495146,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,0.0,2.0,2.0,0.000000,1.000000,right_only
38782,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631,20529.0,3 days,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.137255,1.0,0.0,1.0,1.0,0.0,1.0,1.0,2.0,0.5,0.5,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.40,0.60,50.0,52.0,102.0,0.490196,0.509804,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,right_only
38783,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,20530.0,2 days,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.125000,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.50,0.50,52.0,52.0,104.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,right_only
38784,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631,20531.0,2 days,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.135922,1.0,0.0,1.0,1.0,0.0,2.0,0.0,2.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,3.0,2.0,5.0,0.60,0.40,51.0,52.0,103.0,0.495146,0.504854,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,1.000000,0.000000,right_only

In [11]:
df_concat = pd.concat([df_71A_merge_62_63_64_2010_2018[column_names_common_list], df_71B_merge_65A_65B_66A_66B_2010_2018[column_names_common_list]])
p(df_concat)

(41064, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631

In [24]:
#pandas take difference of rows that have columns that are the same

(abs(df_concat.select_dtypes('number').groupby(['game_id', 'team_id']).diff()).fillna(0) == .0000).sum()

E_OFF_RATING          41064
OFF_RATING            41064
E_DEF_RATING          41064
DEF_RATING            41064
E_NET_RATING          41064
NET_RATING            41064
AST_PCT               40122
AST_TOV               41064
AST_RATIO             41064
OREB_PCT              38270
DREB_PCT              41042
REB_PCT               39247
E_TM_TOV_PCT          37427
TM_TOV_PCT            41064
EFG_PCT               38323
TS_PCT                39862
USG_PCT               41064
E_USG_PCT             33221
E_PACE                41064
PACE                  41064
PACE_PER40            41064
POSS                  41064
PIE                   38603
duration_minutes      41064
w_pct                 39140
min                   41064
fgm                   41064
fga                   41064
fg_pct                36694
fg3m                  41064
fg3a                  41064
fg3_pct               37597
ftm                   41064
fta                   41064
ft_pct                41034
oreb                  41064
dreb                  41064
reb                   41064
ast                   41064
stl                   41064
blk                   41064
tov                   41064
pf                    41064
pts                   41064
spread                41064
away_home_            41064
season_year           41064
latitude              39012
longitude             37035
game_latitude         39014
game_longitude        37034
travel_distance       41033
time_zone_diff        41064
time_zone_diff_abs    41064
dtype: int64

In [25]:
(abs(df_concat.select_dtypes('number').groupby(['game_id', 'team_id']).diff()).fillna(0) < .00001).sum()

E_OFF_RATING          41064
OFF_RATING            41064
E_DEF_RATING          41064
DEF_RATING            41064
E_NET_RATING          41064
NET_RATING            41064
AST_PCT               41064
AST_TOV               41064
AST_RATIO             41064
OREB_PCT              41064
DREB_PCT              41064
REB_PCT               41064
E_TM_TOV_PCT          41064
TM_TOV_PCT            41064
EFG_PCT               41064
TS_PCT                41064
USG_PCT               41064
E_USG_PCT             41064
E_PACE                41064
PACE                  41064
PACE_PER40            41064
POSS                  41064
PIE                   41064
duration_minutes      41064
w_pct                 41064
min                   41064
fgm                   41064
fga                   41064
fg_pct                41064
fg3m                  41064
fg3a                  41064
fg3_pct               41064
ftm                   41064
fta                   41064
ft_pct                41064
oreb                  41064
dreb                  41064
reb                   41064
ast                   41064
stl                   41064
blk                   41064
tov                   41064
pf                    41064
pts                   41064
spread                41064
away_home_            41064
season_year           41064
latitude              41064
longitude             41064
game_latitude         41064
game_longitude        41064
travel_distance       41064
time_zone_diff        41064
time_zone_diff_abs    41064
dtype: int64

In [9]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '71C_merge_71A_71B_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_merged.to_csv(datapath_df, index=False)

In [10]:
df_71C_merge_71A_71B_2010_2018_readback = \
rcp('71C_merge_71A_71B_2010_2018.csv')

p(df_71C_merge_71A_71B_2010_2018_readback)

(2279, 133)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1,index,game_date_diff,game_date_diff1,games_back_to_back_count_game_window2,games_back_to_back_count_game_window5,games_back_to_back_count_game_window12,games_back_to_back_count_game_window999,games_back_to_back_percentage_game_window2,games_back_to_back_percentage_game_window5,games_back_to_back_percentage_game_window12,games_back_to_back_percentage_game_window999,away_game_count_day_window2,home_game_count_day_window2,game_count_day_window2,away_game_percent_day_window2,home_game_percent_day_window2,away_game_count_day_window5,home_game_count_day_window5,game_count_day_window5,away_game_percent_day_window5,home_game_percent_day_window5,away_game_count_day_window8,home_game_count_day_window8,game_count_day_window8,away_game_percent_day_window8,home_game_percent_day_window8,away_game_count_day_window12,home_game_count_day_window12,game_count_day_window12,away_game_percent_day_window12,home_game_percent_day_window12,away_game_count_day_window999,home_game_count_day_window999,game_count_day_window999,away_game_percent_day_window999,home_game_percent_day_window999,future_away_game_count_day_window2,future_home_game_count_day_window2,future_game_count_day_window2,future_away_game_percent_day_window2,future_home_game_percent_day_window2,future_away_game_count_day_window5,future_home_game_count_day_window5,future_game_count_day_window5,future_away_game_percent_day_window5,future_home_game_percent_day_window5,future_away_game_count_day_window8,future_home_game_count_day_window8,future_game_count_day_window8,future_away_game_percent_day_window8,future_home_game_percent_day_window8,future_away_game_count_day_window12,future_home_game_count_day_window12,future_game_count_day_window12,future_away_game_percent_day_window12,future_home_game_percent_day_window12,future_away_game_count_day_window999,future_home_game_count_day_window999,future_game_count_day_window999,future_away_game_percent_day_window999,future_home_game_percent_day_window999
0,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.0,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,25.774173,-80.193620,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7,10,1 days,1,1.0,1.0,1.0,1.0,0.5,0.5,0.500000,0.500000,2.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.000000,0.000000,2.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.000000,0.000000,1.0,0.0,1.0,1.0,0.0,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,3.0,3.0,6.0,0.500000,0.500000,50.0,52.0,102.0,0.490196,0.509804
1,21000008,Grizzlies,MEM,Memphis,240:00,0 days 04:00:00,102.0,105.1,119.4,120.2,-17.5,-15.2,0.325,0.93,10.5,0.000,0.000,0.000,13.725,14.1,0.488,0.536,1.0,0.200,100.82,99.0,82.50,99,0.381,240.0,1610612763,0.000,240,40,86,0.465,4,9,0.444,20,25,0.800000,9,30,39,13,7,4,14,26,104,L,15,1,2010-10-27,ATL vs. MEM,Regular Season,2010-11,2010,35.149022,-90.051629,35.149022,-90.051629,0.000000,America/Chicago,America/Chicago,0.0,0.0,Memphis,United States,76.749,65.0,15,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,3.0,2.0,5.0,0.600000,0.400000,5.0,2.0,7.0,0.714286,0.285714,48.0,47.0,95.0,0.505263,0.494737
2,21000010,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.0,79.17,95,0.575,240.0,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,W,-4,1,2010-10-27,MIL vs. NOH,Regular Season,2010-11,2010,29.949932,-90.070116,29.949932,-90.070116,0.000000,America/Chicago,America/Chicago,0.0,0.0,New Orleans,United States,380.287,374.2,19,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,3.0,3.0,6.0,0.500000,0.500000,44.0,44.0,88.0,0.500000,0.500000
3,21000011,Thunder,OKC,Oklahoma City,240:00,0 days 04:00:00,104.2,107.1,92.5,94.1,11.7,13.0,0.531,1.42,13.3,0.245,0.621,0.449,11.802,12.1,0.436,0.537,1.0,0.201,102.18,100.0,83.33,99,0.603,240.0,1610612760,1.000,240,32,78,0.410,4,18,0.222,38,47,0.808511,9,35,44,17,11,10,12,15,106,W,-11,1,2010-10-27,CHI vs. OKC,Regular Season,2010-11,2010,35.472989,-97.517054,35.472989,-97.517054,0.000000,America/Chicago,America/Chicago,0.0,0.0,Oklahoma City,United States,181.016,70.010,21,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,3.0,3.0,6.0,0.500000,0.500000,49.0,50.0,99.0,0.494949,0.505051
4,21000012,Mavericks,DAL,Dallas,240:00,0 days 04:00:00,108.7,106.3,89.1,91.5,19.6,14.8,0.707,1.71,22.5,0.000,0.000,0.000,18.295,17.9,0.573,0.609,1.0,0.198,94.74,94.5,78.75,95,0.616,240.0,1610612742,1.000,240,41,75,0.547,4,15,0.267,15,18,0.833333,7,34,41,29,12,5,16,18,101,W,-15,1,2010-10-27,CHA vs. DAL,Regular Season,2010-11,2010,32.776272,-96.796856,32.776272,-96.796856,0.000000,America/Chicago,America/Chicago,0.0,0.0,Dallas–Fort Worth,United States,620.6,712.7,23,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,2.0,3.0,5.0,0.400000,0.600000,51.0,52.0,103.0,0.495146,0.504854
2274,41700115,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.8,97.9,87.2,91.6,8.6,6.3,0.759,1.22,17.9,0.190,0.776,0.530,18.734,19.1,0.493,0.554,1.0,0.198,97.94,94.5,78.75,94,0.594,240.0,1610612738,0.600,240,29,69,0.420,10,31,0.323,24,32,0.750000,5,45,50,22,7,7,17,21,92,W,-5,1,2018-04-24,BOS vs. MIL,Playoffs,2017-18,2017,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,20432,2 days,0,0.0,0.0,2.0,14.0,0.0,0.0,0.166667,0.160920,0.0,1.0,1.0,0.0,1.0,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,2.0,3.0,5.0,0.4,0.6,43.0,44.0,87.0,0.494253,0.505747,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,1.0,3.0,4.0,0.250000,0.750000,2.0,4.0,6.0,0.333333,0.666667,6.0,9.0,15.0,0.400000,0.600000
2275,41700136,Pacers,IND,Indianapolis,240:00,0 days 04:00:00,132.7,134.4,92.5,96.7,40.2,37.8,0.551,3.86,21.2,0.293,0.735,0.533,7.679,7.8,0.649,0.649,1.0,0.200,92.60,90.0,75.00,90,0.711,240.0,1610612754,0.500,240,49,87,0.563,15,30,0.500,8,14,0.571429,9,36,45,27,9,1,7,18,121,W,-34,1,2018-04-27,CLE vs. IND,Playoffs,2017-18,2017,39.768333,-86.158350,39.768333,-86.158350,0.000000,America/Indiana/Indianapolis,America/Indiana/Indianapolis,0.0,0.0,Indianapolis,United States,140.762,113.606,20451,2 days,0,0.0,0.0,1.0,14.0,0.0,0.0,0.083333,0.159091,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,1.0,3.0,4.0,0.250000,0.750000,2.0,3.0,5.0,0.4,0.6,44.0,44.0,88.0,0.500000,0.500000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,2.0,0.500000,0.500000,1.0,1.0,2.0,0.500000,0.500000,1.0,1.0,2.0,0.500000,0.500000,1.0,1.0,2.0,0.500000,0.500000
2276,41700117,Celtics,BOS,Boston,240:00,0 days 04:00:00,115.2,117.9,102.2,103.2,13.0,14.7,0.622,1.87,20.6,0.341,0.846,0.578,15.426,15.8,0.589,0.601,1.0,0.196,95.58,94.0,78.33,95,0.573,240.0,1610612738,0.571,240,45,84,0.536,9,26,0.346,13,21,0.619048,11,31,42,28,9,4,14,23,112,W,-16,1,2018-04-28,BOS vs. MIL,Playoffs,2017-18,2017,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1,20454,2 days,0,0.0,0.0,2.0,14.0,0.0,0.0,0.166667,0.157303,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,3.0,3.0,6.0,0.5,0.5,44.0,45.0,89.0,0.494382,0.505618,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,3.0,4.0,0.250000,0.750000,2.0,4.0,6.0,0.333333,0.666667,5.0,8.0,13.0,0.384615,0.615385
2277,41700137,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,118.5,118.0,110.3,113.5,8.2,4.5,0.563,1.50,14.8,0.370,0.681,0.527,13.544,13.5,0.500,0.573,1.0,0.201,90.08,89.0,74.17,89,0.559,240.0,1610612739,0.571,240,32,74,0.432,10,29,0.345,31,40,0.775000,15,29,44,18,6,4,12,21,105,W,-4,1,2018-04-29,CLE vs. IND,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1,20458,2 days,0,0.0,0.0,1.0,13.0,0.0,0.0,0.083333,0.146067,0.0,1.0,1.0,0.0,1.0,1.0,2.0,3.0,0.333333,0.666667,2.0,2.0,4.0,0.500000,0.500000,3.0,3.0,6.0,0.5,0.5,44.0,45.0,89.0,0.494382,0.505618,0.0,1.0,1.0,0.0,1.0,2.0,1.0,3.0,0.666667,0.333333,2.0,2.0,4.0,0.500000,0.500000,2.0,3.0,5.0,0.400000,0.600000,8.0,8.0,16.0,0.500000,0.500000
2278,41700202,Raptors,TOR,Toronto,240:00,0 days 04:00:00,119.8,120.9,138.9,140.7,-19.2,-19.8,0.591,2.36,21.2,0.158,0.811,0.480,11.977,12.1,0.617,0.641,1.0,0.196,91.98,91.0,75.83,91,0.424,240.0,1610612761,0.000,240,44,81,0.543,12,30,0.400,10,11,0.909091,5,30,35,26,2,2,11,24,110,L,18,1,2018-05-03,CLE vs. TOR,Playoffs,2017-18,2017,43.653482,-79.383935,43.653482,-79.383935,0.000000,America/Toronto,America/Toronto,0.0,0.0,Toronto,Canada,405,276.3,20471,2 days,0,0.0,0.0,1.0,14.0,0.0,0.0,0.083333,0.155556,0.0,1.0,1.0,0.0,1.0,0.0,2.0,2.0,0.000000,1.000000,1.0,2.0,3.0,0.333333,0.666667,2.0,3.0,5.0,0.4,0.6,44.0,46.0,90.0,0.488889,0.511111,0.0,1.0,1.0,0.0,1.0,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333,2.0,1.0,3.0,0.666667,0.333333