In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
#https://en.wikipedia.org/wiki/List_of_cities_by_GDP
df_city_gdp = rcr('city_gdp.csv')
p(df_city_gdp)

(440, 5)

,City proper /Metropolitan area,Country/Region,UNSDsub‑region[4],GDP ($billions),GDP ($billions).1
0,City proper /Metropolitan area,Country/Region,UNSDsub‑region[4],Official est.up to date,Brookings[5]2014 est.PPP-adjusted
1,Aachen-Liège-Maastricht,Germany Belgium Netherlands,Western Europe,NaN,99.7
2,"Abbotsford, British Columbia",Canada,North America,5.313 (2016)[6],NaN
3,Aberdeen,Scotland,Northern Europe,16.986 (2013)[7],NaN
4,Abidjan,Ivory Coast,Africa,27 (2017)[8],NaN
435,Zhengzhou,China,East Asia,144 (2018)[18],156.0
436,Zhongshan,China,East Asia,51.1 (2017)[18],68.7
437,Zhuhai,China,East Asia,38.0 (2017)[18],41.3
438,Zibo,China,East Asia,70.8 (2017)[18],100.3
439,Zürich,Switzerland,Western Europe,NaN,109.1

In [3]:
df_city_gdp = df_city_gdp[(df_city_gdp.loc[:, 'Country/Region'] == 'United States') | \
                          (df_city_gdp.loc[:, 'Country/Region'] == 'Canada')]
df_city_gdp.reset_index(drop=True, inplace=True)
p(df_city_gdp)

(115, 5)

,City proper /Metropolitan area,Country/Region,UNSDsub‑region[4],GDP ($billions),GDP ($billions).1
0,"Abbotsford, British Columbia",Canada,North America,5.313 (2016)[6],NaN
1,Akron,United States,North America,36.800 (2018)[12],32.8
2,Albany,United States,North America,59.657 (2018)[12],58.4
3,Albuquerque,United States,North America,42.896 (2018)[12],39.9
4,Allentown,United States,North America,45.024 (2018)[12],37.3
110,"Washington, D.C.",United States,North America,540.684 (2018)[12],634.8
111,Wichita,United States,North America,32.832 (2018)[159],NaN
112,"Windsor, Ontario",Canada,North America,3.542 (2016)[160],NaN
113,Winnipeg,Canada,North America,NaN,32.5
114,Worcester,United States,North America,50.934 (2018)[12],44.7

In [4]:
us_ca_city_proper_metro_area_list = list(set(df_city_gdp['City proper /Metropolitan area']))
pl(us_ca_city_proper_metro_area_list)

115

['San Francisco',
 'Oklahoma City',
 'Peterborough, Ontario',
 'Riverside–San Bernardino',
 'Portland',
 'Chicago',
 'Detroit',
 'Orlando',
 'Tucson',
 'Atlanta',
 'Kelowna',
 'Honolulu',
 'New Orleans',
 'Nashville',
 'Washington, D.C.',
 'Milwaukee',
 'Virginia Beach',
 'Quebec City',
 'Dallas–Fort Worth',
 'Greater Sudbury',
 'Phoenix',
 'Dayton',
 'Little Rock',
 'San Jose',
 'Saint John, New Brunswick',
 'Oshawa',
 'New York',
 'Knoxville',
 'Kansas City',
 'Vancouver',
 'Barrie',
 'Buffalo',
 'Moncton',
 'Albuquerque',
 'New Haven',
 'Oxnard',
 'Toronto',
 'Belleville, Ontario',
 'Abbotsford, British Columbia',
 'Miami',
 'San Diego',
 'Columbus',
 'Denver',
 'Indianapolis',
 'Worcester',
 'Kingston, Ontario',
 'Trois-Rivières',
 'St. Catharines–Niagara Falls',
 'Albany',
 'Seattle',
 'Greenville',
 'Birmingham, Alabama',
 'Syracuse',
 'Victoria, British Columbia',
 'Des Moines',
 'Baton Rouge',
 'Louisville',
 'Springfield',
 'Madison',
 'Rochester',
 'Hartford',
 'Bakersfield',
 'Ottawa',
 'Durham',
 'Richmond',
 'Windsor, Ontario',
 'Los Angeles',
 'Philadelphia',
 'London, Ontario',
 'Fresno',
 'Boston',
 'Greensboro',
 'Omaha',
 'Baltimore',
 'Sacramento',
 'Akron',
 'St. Louis',
 'Guelph',
 'Providence',
 'Columbia',
 'Calgary',
 'Cincinnati',
 'Thunder Bay',
 'Montreal',
 'Winnipeg',
 'Saskatoon',
 'Cleveland',
 'Salt Lake City',
 'Las Vegas',
 'Edmonton',
 'Pittsburgh',
 'Grand Rapids',
 'Charlotte',
 'Houston',
 'Austin',
 'Raleigh',
 'Regina, Saskatchewan',
 'Tampa',
 "St. John's, Newfoundland and Labrador",
 'Memphis',
 'Lethbridge',
 'Minneapolis/St. Paul',
 'Jacksonville',
 'Wichita',
 'Sherbrooke',
 'Tulsa',
 'Halifax, Nova Scotia',
 'Harrisburg',
 'El Paso',
 'San Antonio',
 'Huntsville',
 'Kitchener, Ontario',
 'Brantford',
 'Allentown',
 'Bridgeport']

In [5]:
df_travel_distance = rcp('63_travel_distance_time_zone_diff_2010_2018.csv', ['game_date'])
df_travel_distance = df_travel_distance.sort_values(['game_date', 'game_id'])
p(df_travel_distance)

(20532, 68)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0

In [6]:
team_city_name_list = list(set(df_travel_distance.TEAM_CITY))
pl(team_city_name_list)

30

['Brooklyn',
 'Oklahoma City',
 'Cleveland',
 'Portland',
 'East Rutherford',
 'Chicago',
 'Salt Lake City',
 'Detroit',
 'Orlando',
 'Charlotte',
 'Golden State',
 'Toronto',
 'Atlanta',
 'Houston',
 'Memphis',
 'Miami',
 'Denver',
 'Indianapolis',
 'Minneapolis',
 'New Orleans',
 'Washington',
 'Los Angeles',
 'Philadelphia',
 'Dallas',
 'Milwaukee',
 'Boston',
 'Sacramento',
 'Phoenix',
 'San Antonio',
 'New York']

In [7]:
team_city_match_list = [k for k in team_city_name_list if 
                        any(k in string for string in us_ca_city_proper_metro_area_list)]
pl(team_city_match_list)

27

['Oklahoma City',
 'Cleveland',
 'Portland',
 'Chicago',
 'Salt Lake City',
 'Detroit',
 'Orlando',
 'Charlotte',
 'Toronto',
 'Atlanta',
 'Houston',
 'Memphis',
 'Miami',
 'Denver',
 'Indianapolis',
 'Minneapolis',
 'New Orleans',
 'Washington',
 'Los Angeles',
 'Philadelphia',
 'Dallas',
 'Milwaukee',
 'Boston',
 'Sacramento',
 'Phoenix',
 'San Antonio',
 'New York']

In [8]:
df_team_city = pd.DataFrame({'team_city':team_city_name_list})
p(df_team_city)

(30, 1)

          team_city
0          Brooklyn
1     Oklahoma City
2         Cleveland
3          Portland
4   East Rutherford
25           Boston
26       Sacramento
27          Phoenix
28      San Antonio
29         New York

In [9]:
[k for k in team_city_name_list if not k in team_city_match_list]

['Brooklyn', 'East Rutherford', 'Golden State']

In [10]:
def index_containing_substring(the_list, substring):
    for i, s in enumerate(the_list):
        if substring in s:
              return i
    return -1

In [11]:
l1 = ['Golden State', us_ca_city_proper_metro_area_list[index_containing_substring(us_ca_city_proper_metro_area_list, 'San Francisco')]]
l1

['Golden State', 'San Francisco']

In [12]:
l2 = ['East Rutherford' , us_ca_city_proper_metro_area_list[index_containing_substring(us_ca_city_proper_metro_area_list, 'New York')]]
l2

['East Rutherford', 'New York']

In [13]:
l3 = ['Brooklyn' , us_ca_city_proper_metro_area_list[index_containing_substring(us_ca_city_proper_metro_area_list, 'New York')]]
l3

['Brooklyn', 'New York']

In [14]:
sf_ny_list = [l1, l2, l3]
sf_ny_list

[['Golden State', 'San Francisco'],
 ['East Rutherford', 'New York'],
 ['Brooklyn', 'New York']]

In [15]:
df_sf_ny = pd.DataFrame(sf_ny_list, columns = ['team_city', 'city_proper_metro_area'])
df_sf_ny

         team_city city_proper_metro_area
0     Golden State          San Francisco
1  East Rutherford               New York
2         Brooklyn               New York

In [16]:
city_team_city_proper_metro_area_list = [[k,
                                          us_ca_city_proper_metro_area_list[index_containing_substring(us_ca_city_proper_metro_area_list, k)]]
                                         for k in team_city_match_list ]
pl(city_team_city_proper_metro_area_list)

27

[['Oklahoma City', 'Oklahoma City'],
 ['Cleveland', 'Cleveland'],
 ['Portland', 'Portland'],
 ['Chicago', 'Chicago'],
 ['Salt Lake City', 'Salt Lake City'],
 ['Detroit', 'Detroit'],
 ['Orlando', 'Orlando'],
 ['Charlotte', 'Charlotte'],
 ['Toronto', 'Toronto'],
 ['Atlanta', 'Atlanta'],
 ['Houston', 'Houston'],
 ['Memphis', 'Memphis'],
 ['Miami', 'Miami'],
 ['Denver', 'Denver'],
 ['Indianapolis', 'Indianapolis'],
 ['Minneapolis', 'Minneapolis/St. Paul'],
 ['New Orleans', 'New Orleans'],
 ['Washington', 'Washington, D.C.'],
 ['Los Angeles', 'Los Angeles'],
 ['Philadelphia', 'Philadelphia'],
 ['Dallas', 'Dallas–Fort Worth'],
 ['Milwaukee', 'Milwaukee'],
 ['Boston', 'Boston'],
 ['Sacramento', 'Sacramento'],
 ['Phoenix', 'Phoenix'],
 ['San Antonio', 'San Antonio'],
 ['New York', 'New York']]

In [17]:
df_team_city_city_proper_metro_area = pd.DataFrame(city_team_city_proper_metro_area_list, 
                                                   columns = ['team_city', 'city_proper_metro_area'])
df_team_city_city_proper_metro_area

         team_city city_proper_metro_area
0    Oklahoma City          Oklahoma City
1        Cleveland              Cleveland
2         Portland               Portland
3          Chicago                Chicago
4   Salt Lake City         Salt Lake City
5          Detroit                Detroit
6          Orlando                Orlando
7        Charlotte              Charlotte
8          Toronto                Toronto
9          Atlanta                Atlanta
10         Houston                Houston
11         Memphis                Memphis
12           Miami                  Miami
13          Denver                 Denver
14    Indianapolis           Indianapolis
15     Minneapolis   Minneapolis/St. Paul
16     New Orleans            New Orleans
17      Washington       Washington, D.C.
18     Los Angeles            Los Angeles
19    Philadelphia           Philadelphia
20          Dallas      Dallas–Fort Worth
21       Milwaukee              Milwaukee
22          Boston                 Boston
23      Sacramento             Sacramento
24         Phoenix                Phoenix
25     San Antonio            San Antonio
26        New York               New York

In [18]:
df_team_city_city_proper_metro_area = pd.concat([df_sf_ny, df_team_city_city_proper_metro_area], axis=0)
df_team_city_city_proper_metro_area.reset_index(drop=True, inplace=True)
p(df_team_city_city_proper_metro_area)

(30, 2)

          team_city city_proper_metro_area
0      Golden State          San Francisco
1   East Rutherford               New York
2          Brooklyn               New York
3     Oklahoma City          Oklahoma City
4         Cleveland              Cleveland
25           Boston                 Boston
26       Sacramento             Sacramento
27          Phoenix                Phoenix
28      San Antonio            San Antonio
29         New York               New York

In [19]:
p(df_travel_distance)

(20532, 68)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0

In [20]:
df = pd.merge(df_travel_distance,
              df_team_city_city_proper_metro_area.rename(columns={'team_city':'TEAM_CITY'}),
              on=['TEAM_CITY'])
p(df)

(20532, 69)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami
1,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.0,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,25.774173,-80.193620,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0.0,0.0,Miami
2,21000025,Heat,MIA,Miami,240:00,0 days 04:00:00,105.6,109.1,76.1,78.7,29.5,30.4,0.515,1.42,13.9,0.000,0.745,0.000,13.204,13.6,0.463,0.517,1.0,0.198,91.42,88.5,73.75,88,0.755,240.0,1610612748,0.667,240,33,81,0.407,9,18,0.500,21,27,0.777778,14,37,51,17,6,5,12,27,96,W,-26,1,2010-10-29,MIA vs. ORL,Regular Season,2010-11,2010,25.774173,-80.193620,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami
3,21000040,Heat,MIA,Miami,240:00,0 days 04:00:00,118.9,114.8,85.6,90.7,33.3,24.1,0.806,3.63,24.4,0.200,0.600,0.453,9.416,9.1,0.575,0.616,1.0,0.202,88.04,87.0,72.50,88,0.757,240.0,1610612748,0.750,240,36,67,0.537,5,16,0.313,24,34,0.705882,5,35,40,29,10,6,8,21,101,W,-23,0,2010-10-31,MIA vs. NJN,Regular Season,2010-11,2010,25.774173,-80.193620,40.833989,-74.097087,1097.712213,America/New_York,America/New_York,0.0,0.0,Miami
4,21000050,Heat,MIA,Miami,240:00,0 days 04:00:00,128.2,127.7,91.8,97.0,36.4,30.7,0.674,1.94,22.2,0.000,0.678,0.000,15.898,15.8,0.658,0.696,1.0,0.197,103.18,100.5,83.75,101,0.718,240.0,1610612748,0.800,240,46,79,0.582,12,21,0.571,25,31,0.806452,8,39,47,31,9,7,14,27,129,W,-32,1,2010-11-02,MIA vs. MIN,Regular Season,2010-11,2010,25.774173,-80.193620,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami
20527,21701157,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,89.5,92.2,118.7,118.6,-29.2,-26.4,0.588,1.11,15.5,0.143,0.814,0.434,16.962,17.5,0.525,0.521,1.0,0.198,104.02,102.5,85.42,103,0.321,240.0,1610612751,0.321,240,34,81,0.420,17,42,0.405,10,23,0.434783,3,33,36,20,5,6,18,15,95,L,26,0,2018-04-03,BKN vs. PHI,Regular Season,2017-18,2017,40.650104,-73.949582,39.952724,-75.163526,80.083704,America/New_York,America/New_York,0.0,0.0,New York
20528,21701178,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,118.7,120.2,108.6,112.1,10.1,8.1,0.732,1.50,22.3,0.194,0.709,0.505,19.952,20.2,0.673,0.706,1.0,0.194,101.22,99.0,82.50,99,0.556,240.0,1610612751,0.329,240,41,75,0.547,19,39,0.487,18,21,0.857143,4,37,41,30,3,12,17,21,119,W,-8,0,2018-04-05,BKN vs. MIL,Regular Season,2017-18,2017,40.650104,-73.949582,43.034993,-87.922497,736.918347,America/Chicago,America/New_York,-1.0,1.0,New York
20529,21701193,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,116.1,119.2,90.4,93.2,25.7,26.0,0.783,2.40,24.4,0.188,0.846,0.530,14.040,14.4,0.630,0.640,1.0,0.195,106.54,103.5,86.25,104,0.646,240.0,1610612751,0.338,240,46,92,0.500,24,55,0.436,8,11,0.727273,5,41,46,36,11,10,13,18,124,W,-28,0,2018-04-07,BKN vs. CHI,Regular Season,2017-18,2017,40.650104,-73.949582,41.875562,-87.624421,714.484385,America/Chicago,America/New_York,-1.0,1.0,New York
20530,21701205,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,113.3,112.9,101.7,105.0,11.7,7.9,0.780,1.78,23.1,0.167,0.714,0.462,17.893,17.8,0.610,0.643,1.0,0.197,101.94,100.5,83.75,101,0.561,240.0,1610612751,0.346,240,41,82,0.500,18,42,0.429,14,15,0.933333,6,32,38,32,8,10,17,15,114,W,-9,1,2018-04-09,BKN vs. CHI,Regular Season,2017-18,2017,40.650104,-73.949582,40.650104,-73.949582,0.000000,America/New_York,America/New_York,0.0,0.0,New York
20531,21701219,Nets,BKN,Brooklyn,240:00,0 days 04:00:00,93.2,95.1,107.2,107.8,-14.0,-12.7,0.730,1.69,19.1,0.228,0.603,0.417,15.379,15.7,0.467,0.495,1.0,0.196,103.32,102.0,85.00,102,0.459,240.0,1610612751,0.341,240,37,91,0.407,11,40,0.275,12,16,0.750000,10,34,44,27,10,6,15,12,97,L,13,0,2018-04-11,BKN vs. BOS,Regular Season,2017-18,2017,40.650104,-73.949582,42.360253,-71.058291,190.620573,America/New_York,America/New_York,0.0,0.0,New York

In [21]:
#df.info()

In [22]:
df.sort_values(['game_date', 'game_id'], inplace=True)
df.reset_index(drop=True, inplace=True)
p(df)

(20532, 69)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco

In [23]:
p(df_city_gdp)

(115, 5)

,City proper /Metropolitan area,Country/Region,UNSDsub‑region[4],GDP ($billions),GDP ($billions).1
0,"Abbotsford, British Columbia",Canada,North America,5.313 (2016)[6],NaN
1,Akron,United States,North America,36.800 (2018)[12],32.8
2,Albany,United States,North America,59.657 (2018)[12],58.4
3,Albuquerque,United States,North America,42.896 (2018)[12],39.9
4,Allentown,United States,North America,45.024 (2018)[12],37.3
110,"Washington, D.C.",United States,North America,540.684 (2018)[12],634.8
111,Wichita,United States,North America,32.832 (2018)[159],NaN
112,"Windsor, Ontario",Canada,North America,3.542 (2016)[160],NaN
113,Winnipeg,Canada,North America,NaN,32.5
114,Worcester,United States,North America,50.934 (2018)[12],44.7

In [24]:
df_city_gdp.drop(columns='UNSDsub‑region[4]', inplace=True)
p(df_city_gdp)

(115, 4)

,City proper /Metropolitan area,Country/Region,GDP ($billions),GDP ($billions).1
0,"Abbotsford, British Columbia",Canada,5.313 (2016)[6],NaN
1,Akron,United States,36.800 (2018)[12],32.8
2,Albany,United States,59.657 (2018)[12],58.4
3,Albuquerque,United States,42.896 (2018)[12],39.9
4,Allentown,United States,45.024 (2018)[12],37.3
110,"Washington, D.C.",United States,540.684 (2018)[12],634.8
111,Wichita,United States,32.832 (2018)[159],NaN
112,"Windsor, Ontario",Canada,3.542 (2016)[160],NaN
113,Winnipeg,Canada,NaN,32.5
114,Worcester,United States,50.934 (2018)[12],44.7

In [25]:
df = pd.merge(df,
              df_city_gdp.rename(columns= {'City proper /Metropolitan area':'city_proper_metro_area'}),
              on='city_proper_metro_area')
p(df)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,GDP ($billions),GDP ($billions).1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.19362,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
1,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.0,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,25.774173,-80.19362,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
2,21000025,Heat,MIA,Miami,240:00,0 days 04:00:00,105.6,109.1,76.1,78.7,29.5,30.4,0.515,1.42,13.9,0.000,0.745,0.000,13.204,13.6,0.463,0.517,1.0,0.198,91.42,88.5,73.75,88,0.755,240.0,1610612748,0.667,240,33,81,0.407,9,18,0.500,21,27,0.777778,14,37,51,17,6,5,12,27,96,W,-26,1,2010-10-29,MIA vs. ORL,Regular Season,2010-11,2010,25.774173,-80.19362,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
3,21000040,Heat,MIA,Miami,240:00,0 days 04:00:00,118.9,114.8,85.6,90.7,33.3,24.1,0.806,3.63,24.4,0.200,0.600,0.453,9.416,9.1,0.575,0.616,1.0,0.202,88.04,87.0,72.50,88,0.757,240.0,1610612748,0.750,240,36,67,0.537,5,16,0.313,24,34,0.705882,5,35,40,29,10,6,8,21,101,W,-23,0,2010-10-31,MIA vs. NJN,Regular Season,2010-11,2010,25.774173,-80.19362,40.833989,-74.097087,1097.712213,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
4,21000050,Heat,MIA,Miami,240:00,0 days 04:00:00,128.2,127.7,91.8,97.0,36.4,30.7,0.674,1.94,22.2,0.000,0.678,0.000,15.898,15.8,0.658,0.696,1.0,0.197,103.18,100.5,83.75,101,0.718,240.0,1610612748,0.800,240,46,79,0.582,12,21,0.571,25,31,0.806452,8,39,47,31,9,7,14,27,129,W,-32,1,2010-11-02,MIA vs. MIN,Regular Season,2010-11,2010,25.774173,-80.19362,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
20527,21701170,Magic,ORL,Orlando,240:00,0 days 04:00:00,106.2,110.5,102.6,105.3,3.6,5.3,0.692,2.08,19.6,0.340,0.692,0.520,13.147,13.7,0.500,0.536,1.0,0.198,98.18,95.0,79.17,95,0.569,240.0,1610612753,0.308,240,39,86,0.453,8,29,0.276,19,27,0.703704,12,35,47,27,4,10,13,15,105,W,-5,1,2018-04-04,DAL vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2
20528,21701182,Magic,ORL,Orlando,240:00,0 days 04:00:00,103.4,102.0,139.2,139.8,-35.8,-37.8,0.643,3.00,19.9,0.236,0.692,0.426,9.305,9.2,0.495,0.501,1.0,0.199,97.58,98.0,81.67,98,0.323,240.0,1610612753,0.304,240,42,94,0.447,9,23,0.391,7,13,0.538462,12,24,36,27,2,3,8,19,100,L,37,1,2018-04-06,CHA vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2
20529,21701200,Magic,ORL,Orlando,240:00,0 days 04:00:00,99.5,104.1,112.5,114.3,-13.0,-10.2,0.595,2.27,18.9,0.196,0.818,0.484,10.840,11.3,0.511,0.523,1.0,0.195,100.52,97.5,81.25,97,0.467,240.0,1610612753,0.300,240,42,89,0.472,7,23,0.304,10,17,0.588235,6,36,42,25,12,4,10,17,101,L,11,0,2018-04-08,ORL vs. TOR,Regular Season,2017-18,2017,28.542111,-81.37903,43.653482,-79.383935,1049.931136,America/Toronto,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2
20530,21701208,Magic,ORL,Orlando,240:00,0 days 04:00:00,81.3,82.7,98.2,99.0,-16.9,-16.3,0.706,1.20,17.8,0.170,0.755,0.462,18.904,19.2,0.445,0.474,1.0,0.197,104.86,103.5,86.25,104,0.412,240.0,1610612753,0.296,240,34,82,0.415,5,24,0.208,13,20,0.650000,5,38,43,24,8,4,19,14,86,L,16,0,2018-04-09,MIL vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,43.034993,-87.922497,1065.521360,America/Chicago,America/New_York,-1.0,1.0,Orlando,United States,138.947 (2018)[12],316.2
20531,21701222,Magic,ORL,Orlando,240:00,0 days 04:00:00,102.1,104.1,91.2,93.9,10.9,10.2,0.606,1.25,16.0,0.200,0.642,0.464,16.181,16.5,0.513,0.568,1.0,0.200,99.88,97.5,81.25,97,0.630,240.0,1610612753,0.305,240,33,77,0.429,13,32,0.406,22,27,0.814815,6,36,42,20,6,7,16,27,101,W,-9,1,2018-04-11,ORL vs. WAS,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2

In [26]:
df.rename(columns={'GDP ($billions)': 'GDP_bil', 'GDP ($billions).1': 'GDP_bil1'}, inplace=True)
p(df)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,GDP_bil,GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.19362,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
1,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.0,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,25.774173,-80.19362,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
2,21000025,Heat,MIA,Miami,240:00,0 days 04:00:00,105.6,109.1,76.1,78.7,29.5,30.4,0.515,1.42,13.9,0.000,0.745,0.000,13.204,13.6,0.463,0.517,1.0,0.198,91.42,88.5,73.75,88,0.755,240.0,1610612748,0.667,240,33,81,0.407,9,18,0.500,21,27,0.777778,14,37,51,17,6,5,12,27,96,W,-26,1,2010-10-29,MIA vs. ORL,Regular Season,2010-11,2010,25.774173,-80.19362,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
3,21000040,Heat,MIA,Miami,240:00,0 days 04:00:00,118.9,114.8,85.6,90.7,33.3,24.1,0.806,3.63,24.4,0.200,0.600,0.453,9.416,9.1,0.575,0.616,1.0,0.202,88.04,87.0,72.50,88,0.757,240.0,1610612748,0.750,240,36,67,0.537,5,16,0.313,24,34,0.705882,5,35,40,29,10,6,8,21,101,W,-23,0,2010-10-31,MIA vs. NJN,Regular Season,2010-11,2010,25.774173,-80.19362,40.833989,-74.097087,1097.712213,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
4,21000050,Heat,MIA,Miami,240:00,0 days 04:00:00,128.2,127.7,91.8,97.0,36.4,30.7,0.674,1.94,22.2,0.000,0.678,0.000,15.898,15.8,0.658,0.696,1.0,0.197,103.18,100.5,83.75,101,0.718,240.0,1610612748,0.800,240,46,79,0.582,12,21,0.571,25,31,0.806452,8,39,47,31,9,7,14,27,129,W,-32,1,2010-11-02,MIA vs. MIN,Regular Season,2010-11,2010,25.774173,-80.19362,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5 (2019)[92][93],262.7
20527,21701170,Magic,ORL,Orlando,240:00,0 days 04:00:00,106.2,110.5,102.6,105.3,3.6,5.3,0.692,2.08,19.6,0.340,0.692,0.520,13.147,13.7,0.500,0.536,1.0,0.198,98.18,95.0,79.17,95,0.569,240.0,1610612753,0.308,240,39,86,0.453,8,29,0.276,19,27,0.703704,12,35,47,27,4,10,13,15,105,W,-5,1,2018-04-04,DAL vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2
20528,21701182,Magic,ORL,Orlando,240:00,0 days 04:00:00,103.4,102.0,139.2,139.8,-35.8,-37.8,0.643,3.00,19.9,0.236,0.692,0.426,9.305,9.2,0.495,0.501,1.0,0.199,97.58,98.0,81.67,98,0.323,240.0,1610612753,0.304,240,42,94,0.447,9,23,0.391,7,13,0.538462,12,24,36,27,2,3,8,19,100,L,37,1,2018-04-06,CHA vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2
20529,21701200,Magic,ORL,Orlando,240:00,0 days 04:00:00,99.5,104.1,112.5,114.3,-13.0,-10.2,0.595,2.27,18.9,0.196,0.818,0.484,10.840,11.3,0.511,0.523,1.0,0.195,100.52,97.5,81.25,97,0.467,240.0,1610612753,0.300,240,42,89,0.472,7,23,0.304,10,17,0.588235,6,36,42,25,12,4,10,17,101,L,11,0,2018-04-08,ORL vs. TOR,Regular Season,2017-18,2017,28.542111,-81.37903,43.653482,-79.383935,1049.931136,America/Toronto,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2
20530,21701208,Magic,ORL,Orlando,240:00,0 days 04:00:00,81.3,82.7,98.2,99.0,-16.9,-16.3,0.706,1.20,17.8,0.170,0.755,0.462,18.904,19.2,0.445,0.474,1.0,0.197,104.86,103.5,86.25,104,0.412,240.0,1610612753,0.296,240,34,82,0.415,5,24,0.208,13,20,0.650000,5,38,43,24,8,4,19,14,86,L,16,0,2018-04-09,MIL vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,43.034993,-87.922497,1065.521360,America/Chicago,America/New_York,-1.0,1.0,Orlando,United States,138.947 (2018)[12],316.2
20531,21701222,Magic,ORL,Orlando,240:00,0 days 04:00:00,102.1,104.1,91.2,93.9,10.9,10.2,0.606,1.25,16.0,0.200,0.642,0.464,16.181,16.5,0.513,0.568,1.0,0.200,99.88,97.5,81.25,97,0.630,240.0,1610612753,0.305,240,33,77,0.429,13,32,0.406,22,27,0.814815,6,36,42,20,6,7,16,27,101,W,-9,1,2018-04-11,ORL vs. WAS,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947 (2018)[12],316.2

In [27]:
#https://stackoverflow.com/questions/51713273/extract-string-before-colon-or-parenthesis-with-regex-in-python
df.GDP_bil = df.GDP_bil.str.extract('([^\(:]+)')
p(df)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,GDP_bil,GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.19362,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
1,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.0,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,25.774173,-80.19362,39.952724,-75.163526,1021.727021,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
2,21000025,Heat,MIA,Miami,240:00,0 days 04:00:00,105.6,109.1,76.1,78.7,29.5,30.4,0.515,1.42,13.9,0.000,0.745,0.000,13.204,13.6,0.463,0.517,1.0,0.198,91.42,88.5,73.75,88,0.755,240.0,1610612748,0.667,240,33,81,0.407,9,18,0.500,21,27,0.777778,14,37,51,17,6,5,12,27,96,W,-26,1,2010-10-29,MIA vs. ORL,Regular Season,2010-11,2010,25.774173,-80.19362,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
3,21000040,Heat,MIA,Miami,240:00,0 days 04:00:00,118.9,114.8,85.6,90.7,33.3,24.1,0.806,3.63,24.4,0.200,0.600,0.453,9.416,9.1,0.575,0.616,1.0,0.202,88.04,87.0,72.50,88,0.757,240.0,1610612748,0.750,240,36,67,0.537,5,16,0.313,24,34,0.705882,5,35,40,29,10,6,8,21,101,W,-23,0,2010-10-31,MIA vs. NJN,Regular Season,2010-11,2010,25.774173,-80.19362,40.833989,-74.097087,1097.712213,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
4,21000050,Heat,MIA,Miami,240:00,0 days 04:00:00,128.2,127.7,91.8,97.0,36.4,30.7,0.674,1.94,22.2,0.000,0.678,0.000,15.898,15.8,0.658,0.696,1.0,0.197,103.18,100.5,83.75,101,0.718,240.0,1610612748,0.800,240,46,79,0.582,12,21,0.571,25,31,0.806452,8,39,47,31,9,7,14,27,129,W,-32,1,2010-11-02,MIA vs. MIN,Regular Season,2010-11,2010,25.774173,-80.19362,25.774173,-80.193620,0.000000,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
20527,21701170,Magic,ORL,Orlando,240:00,0 days 04:00:00,106.2,110.5,102.6,105.3,3.6,5.3,0.692,2.08,19.6,0.340,0.692,0.520,13.147,13.7,0.500,0.536,1.0,0.198,98.18,95.0,79.17,95,0.569,240.0,1610612753,0.308,240,39,86,0.453,8,29,0.276,19,27,0.703704,12,35,47,27,4,10,13,15,105,W,-5,1,2018-04-04,DAL vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947,316.2
20528,21701182,Magic,ORL,Orlando,240:00,0 days 04:00:00,103.4,102.0,139.2,139.8,-35.8,-37.8,0.643,3.00,19.9,0.236,0.692,0.426,9.305,9.2,0.495,0.501,1.0,0.199,97.58,98.0,81.67,98,0.323,240.0,1610612753,0.304,240,42,94,0.447,9,23,0.391,7,13,0.538462,12,24,36,27,2,3,8,19,100,L,37,1,2018-04-06,CHA vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947,316.2
20529,21701200,Magic,ORL,Orlando,240:00,0 days 04:00:00,99.5,104.1,112.5,114.3,-13.0,-10.2,0.595,2.27,18.9,0.196,0.818,0.484,10.840,11.3,0.511,0.523,1.0,0.195,100.52,97.5,81.25,97,0.467,240.0,1610612753,0.300,240,42,89,0.472,7,23,0.304,10,17,0.588235,6,36,42,25,12,4,10,17,101,L,11,0,2018-04-08,ORL vs. TOR,Regular Season,2017-18,2017,28.542111,-81.37903,43.653482,-79.383935,1049.931136,America/Toronto,America/New_York,0.0,0.0,Orlando,United States,138.947,316.2
20530,21701208,Magic,ORL,Orlando,240:00,0 days 04:00:00,81.3,82.7,98.2,99.0,-16.9,-16.3,0.706,1.20,17.8,0.170,0.755,0.462,18.904,19.2,0.445,0.474,1.0,0.197,104.86,103.5,86.25,104,0.412,240.0,1610612753,0.296,240,34,82,0.415,5,24,0.208,13,20,0.650000,5,38,43,24,8,4,19,14,86,L,16,0,2018-04-09,MIL vs. ORL,Regular Season,2017-18,2017,28.542111,-81.37903,43.034993,-87.922497,1065.521360,America/Chicago,America/New_York,-1.0,1.0,Orlando,United States,138.947,316.2
20531,21701222,Magic,ORL,Orlando,240:00,0 days 04:00:00,102.1,104.1,91.2,93.9,10.9,10.2,0.606,1.25,16.0,0.200,0.642,0.464,16.181,16.5,0.513,0.568,1.0,0.200,99.88,97.5,81.25,97,0.630,240.0,1610612753,0.305,240,33,77,0.429,13,32,0.406,22,27,0.814815,6,36,42,20,6,7,16,27,101,W,-9,1,2018-04-11,ORL vs. WAS,Regular Season,2017-18,2017,28.542111,-81.37903,28.542111,-81.379030,0.000000,America/New_York,America/New_York,0.0,0.0,Orlando,United States,138.947,316.2

In [28]:
df.sort_values(['game_date', 'game_id'], inplace=True)
df.reset_index(drop=True, inplace=True)
df.rename(columns = {'GDP_bil':'city_proper_metro_area_GDP_bil',
                     'GDP_bil1':'city_proper_metro_area_GDP_bil1'},
          inplace=True)
p(df)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.5,262.7
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995,631.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135,215.1
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995,631.0

In [29]:
df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20532 entries, 0 to 20531
Data columns (total 2 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   city_proper_metro_area_GDP_bil   20532 non-null  object
 1   city_proper_metro_area_GDP_bil1  20532 non-null  object
dtypes: object(2)
memory usage: 320.9+ KB

In [30]:
df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']] =\
df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']].replace(',','', regex=True)

df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']] =\
df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']].replace(' ','', regex=True)

p(df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']])

(20532, 2)

      city_proper_metro_area_GDP_bil city_proper_metro_area_GDP_bil1
0                              377.5                           262.7
1                            463.570                           560.1
2                            255.211                           607.1
3                            164.419                           158.5
4                            478.778                           883.2
20527                            995                           631.0
20528                            135                           215.1
20529                            995                           631.0
20530                            135                           215.1
20531                            995                           631.0

In [31]:
df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']] = \
df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']].astype('float64')

p(df.loc[:, ['city_proper_metro_area_GDP_bil', 'city_proper_metro_area_GDP_bil1']])

(20532, 2)

       city_proper_metro_area_GDP_bil  city_proper_metro_area_GDP_bil1
0                             377.500                            262.7
1                             463.570                            560.1
2                             255.211                            607.1
3                             164.419                            158.5
4                             478.778                            883.2
20527                         995.000                            631.0
20528                         135.000                            215.1
20529                         995.000                            631.0
20530                         135.000                            215.1
20531                         995.000                            631.0

In [32]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '64_city_proper_metro_area_gdp_2010_2018.csv')
if not os.path.exists(datapath_df):
    df.to_csv(datapath_df, index=False)

In [33]:
df_64_city_proper_metro_area_gdp_2010_2018_readback = rcp('64_city_proper_metro_area_gdp_2010_2018.csv')
p(df_64_city_proper_metro_area_gdp_2010_2018_readback)

(20532, 72)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,latitude,longitude,game_latitude,game_longitude,travel_distance,game_time_zone,time_zone,time_zone_diff,time_zone_diff_abs,city_proper_metro_area,Country/Region,city_proper_metro_area_GDP_bil,city_proper_metro_area_GDP_bil1
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,25.774173,-80.193620,42.360253,-71.058291,1257.755091,America/New_York,America/New_York,0.0,0.0,Miami,United States,377.500,262.7
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,42.360253,-71.058291,42.360253,-71.058291,0.000000,America/New_York,America/New_York,0.0,0.0,Boston,United States,463.570,560.1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,33.448437,-112.074142,45.520247,-122.674195,1005.606855,America/Los_Angeles,America/Phoenix,0.0,0.0,Phoenix,United States,255.211,607.1
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,45.520247,-122.674195,45.520247,-122.674195,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,Portland,United States,164.419,158.5
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,29.758938,-95.367697,34.053691,-118.242766,1371.020326,America/Los_Angeles,America/Chicago,-2.0,2.0,Houston,United States,478.778,883.2
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,37.854666,-122.292136,0.000000,America/Los_Angeles,America/Los_Angeles,0.0,0.0,San Francisco,United States,995.000,631.0
20528,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1
20529,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0
20530,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,41.505161,-81.693445,41.505161,-81.693445,0.000000,America/New_York,America/New_York,0.0,0.0,Cleveland,United States,135.000,215.1
20531,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,37.854666,-122.292136,41.505161,-81.693445,2153.640745,America/New_York,America/Los_Angeles,3.0,3.0,San Francisco,United States,995.000,631.0