<a id=’section_1’></a>
### Section 1


* [destination](#destination)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
def df_inj1020_fix_Date_Team(df_):
    df_.loc[5923, ['Team']] = 'Pacers'
    return df_

def get_5bsa1018_inj1018_player_diff():
    print(len(set(df_inj1018r.player) - set(df_5bsa1018.PLAYER_NAME)))
    print(set(df_inj1018r.player) - set(df_5bsa1018.PLAYER_NAME))
    print()
    
    print(len(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1018r.player)))
    print(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1018r.player))
    return 0
    

#return first 5 and last 5 rows of dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        print(df_.shape)
        return df_


    

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [4]:
df_5bsa1018 = pd.read_csv(os.path.join('..', 'processed_data', '5boxscoreadvancedv2_2009_2018.csv'))
print(df_5bsa1018.shape)
p(df_5bsa1018)

(291643, 31)
(291643, 31)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1.610613e+09,BOS,Boston,1718.0,Paul Pierce,F,NaN,37:59,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1.610613e+09,BOS,Boston,708.0,Kevin Garnett,F,NaN,33:05,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1.610613e+09,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25:42,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1.610613e+09,BOS,Boston,951.0,Ray Allen,G,NaN,42:21,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1.610613e+09,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34:29,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
291638,41700404,1.610613e+09,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23:12,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1.610613e+09,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1.610613e+09,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4:03,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1.610613e+09,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1:40,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1.610613e+09,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [5]:
df_5bsa1018.PLAYER_NAME = df_5bsa1018.PLAYER_NAME.fillna('')
df_5bsa1018.MIN = df_5bsa1018.MIN.fillna('00:00')
df_5bsa1018.MIN = pd.to_timedelta('00:' + df_5bsa1018.MIN).astype('timedelta64[s]').astype('float64') / 60
df_5bsa1018.TEAM_ID = df_5bsa1018.TEAM_ID.fillna(0).astype('int64')
print(df_5bsa1018.shape)
p(df_5bsa1018)

(291643, 31)
(291643, 31)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,20900001,1610612738,BOS,Boston,1718.0,Paul Pierce,F,NaN,37.983333,95.3,97.4,96.5,98.6,-1.2,-1.3,0.053,0.50,4.8,0.028,0.270,0.151,9.5,0.538,0.661,0.233,0.239,96.88,94.76,78.97,76.0,0.189
1,20900001,1610612738,BOS,Boston,708.0,Kevin Garnett,F,NaN,33.083333,95.6,95.5,101.0,103.1,-5.4,-7.6,0.059,1.00,7.1,0.097,0.233,0.164,7.1,0.500,0.553,0.178,0.181,95.96,95.03,79.19,66.0,0.147
2,20900001,1610612738,BOS,Boston,2570.0,Kendrick Perkins,C,NaN,25.700000,99.2,100.0,108.2,104.3,-9.1,-4.3,0.077,0.33,9.1,0.000,0.050,0.024,27.3,0.571,0.605,0.196,0.198,86.53,87.77,73.14,47.0,0.030
3,20900001,1610612738,BOS,Boston,951.0,Ray Allen,G,NaN,42.350000,105.2,108.8,105.4,105.1,-0.2,3.7,0.120,1.00,12.5,0.000,0.054,0.028,12.5,0.375,0.440,0.236,0.240,91.50,90.12,75.10,80.0,0.051
4,20900001,1610612738,BOS,Boston,200765.0,Rajon Rondo,G,NaN,34.483333,92.7,94.1,98.0,97.1,-5.3,-3.0,0.526,5.00,50.0,0.061,0.125,0.092,10.0,0.500,0.500,0.130,0.133,95.63,95.36,79.46,68.0,0.158
291638,41700404,1610612739,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23.200000,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
291639,41700404,1610612739,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
291640,41700404,1610612739,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
291641,41700404,1610612739,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1.666667,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
291642,41700404,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.000000,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [6]:
path = os.path.join('..', 'processed_data', '3game_id_game_date_team_id.csv')
path
df_3gigdti = pd.read_csv(path, parse_dates=['game_date'])
df_3gigdti1018 = df_3gigdti[(df_3gigdti.season == '2010-11') |
                            (df_3gigdti.season == '2011-12') |
                            (df_3gigdti.season == '2012-13') |
                            (df_3gigdti.season == '2013-14') |
                            (df_3gigdti.season == '2014-15') |
                            (df_3gigdti.season == '2015-16') |
                            (df_3gigdti.season == '2016-17') |
                            (df_3gigdti.season == '2017-18')]
print(df_3gigdti1018.shape)
p(df_3gigdti1018)

(20534, 27)
(20534, 27)

,game_id,game_date,team_id,is_home,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
9840,21000001,2010-10-26,1610612738,t,1.0,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010,Regular Season,2010-11
9841,21000001,2010-10-26,1610612748,f,0.0,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,2010,Regular Season,2010-11
9842,21000002,2010-10-26,1610612757,t,1.0,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010,Regular Season,2010-11
9843,21000002,2010-10-26,1610612756,f,0.0,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,2010,Regular Season,2010-11
9844,21000003,2010-10-26,1610612745,f,0.0,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,2010,Regular Season,2010-11
31033,41700402,2018-06-03,1610612744,t,1.0,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017,Playoffs,2017-18
31034,41700403,2018-06-06,1610612744,f,1.0,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,2017,Playoffs,2017-18
31035,41700403,2018-06-06,1610612739,t,0.0,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017,Playoffs,2017-18
31036,41700404,2018-06-08,1610612739,t,0.0,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017,Playoffs,2017-18
31037,41700404,2018-06-08,1610612744,f,1.0,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,2017,Playoffs,2017-18

In [7]:
#filter for 2010-11 thru 2017-18 seasons: df_5bsa1018
df_5bsa1018 = pd.merge(df_3gigdti1018[['game_id', 'game_date', 'season']], df_5bsa1018.rename(columns={'GAME_ID':'game_id', 'TEAM_ID':'team_id'}), on=['game_id'], how='inner')
p(df_5bsa1018)

(520324, 33)

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,2544.0,LeBron James,F,NaN,42.650000,91.3,90.1,89.2,87.8,2.0,2.3,0.214,0.38,8.1,0.000,0.100,0.050,21.6,0.548,0.590,0.378,0.382,90.42,91.72,76.44,81.0,0.157
1,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,2547.0,Chris Bosh,F,NaN,37.616667,86.7,87.1,112.5,109.9,-25.8,-22.7,0.111,2.00,13.3,0.050,0.231,0.121,6.7,0.273,0.337,0.160,0.162,89.14,89.96,74.97,70.0,0.049
2,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,201202.0,Joel Anthony,C,NaN,16.683333,49.1,48.3,84.5,86.7,-35.4,-38.4,0.250,0.00,50.0,0.200,0.267,0.233,0.0,1.000,1.000,0.031,0.032,85.27,84.87,70.72,29.0,0.318
3,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,2548.0,Dwyane Wade,G,NaN,36.683333,81.9,82.4,108.1,107.2,-26.1,-24.9,0.400,1.00,19.4,0.000,0.154,0.062,19.4,0.281,0.349,0.316,0.319,89.52,89.63,74.69,68.0,0.020
4,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,2306.0,Carlos Arroyo,G,NaN,12.550000,73.9,72.7,97.0,95.5,-23.1,-22.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.436,0.130,0.133,82.77,84.14,70.12,22.0,0.040
520319,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,1626204.0,Larry Nance Jr.,NaN,NaN,23.200000,93.4,97.6,93.1,95.2,0.3,2.3,0.333,0.00,33.3,0.176,0.077,0.133,0.0,0.429,0.444,0.148,0.146,88.76,85.87,71.56,41.0,0.139
520320,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,1626224.0,Cedi Osman,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.333,0.333,0.333,0.333,94.10,88.89,74.07,7.0,0.000
520321,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,101181.0,Jose Calderon,NaN,NaN,4.050000,100.0,114.3,76.1,75.0,23.9,39.3,0.250,0.00,50.0,0.000,0.200,0.100,0.0,0.000,0.000,0.111,0.111,94.10,88.89,74.07,7.0,0.174
520322,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,1627790.0,Ante Zizic,NaN,NaN,1.666667,100.0,133.3,0.0,0.0,100.0,133.3,0.000,0.00,0.0,0.333,0.000,0.200,0.0,1.000,1.000,0.400,0.400,100.80,86.40,72.00,3.0,2.250
520323,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.000000,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000,0.000,0.000,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0.0,NaN

In [8]:
df_merged_1018 = rcp('df_merged_lo_1018.csv', ['game_date']).drop(columns='_merge')
p(df_merged_1018)

(3, 2)

   game_date        player
0 2016-01-21   P.J. Tucker
1 2016-12-07  Jamal Murray
2 2017-02-23   Omri Casspi

In [9]:
pd.merge(df_5bsa1018.rename(columns={'PLAYER_NAME':'player'}), df_merged_1018, on=['game_date', 'player'])

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,player,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21500644,2016-01-21,2015-16,1610612756,PHX,Phoenix,200782.0,P.J. Tucker,F,NaN,6.050000,67.3,72.7,101.7,116.7,-34.4,-43.9,0.000,0.0,0.0,0.000,0.125,0.071,0.0,0.000,0.000,0.000,0.000,101.71,91.24,76.03,11.0,0.061
1,21500644,2016-01-21,2015-16,1610612756,PHX,Phoenix,200782.0,P.J. Tucker,F,NaN,6.050000,67.3,72.7,101.7,116.7,-34.4,-43.9,0.000,0.0,0.0,0.000,0.125,0.071,0.0,0.000,0.000,0.000,0.000,101.71,91.24,76.03,11.0,0.061
2,21600323,2016-12-07,2016-17,1610612743,DEN,Denver,1627750.0,Jamal Murray,NaN,NaN,33.550000,117.3,118.1,91.5,88.9,25.7,29.2,0.107,0.0,16.7,0.021,0.114,0.060,0.0,0.357,0.403,0.156,0.157,101.87,103.01,85.84,72.0,0.072
3,21600323,2016-12-07,2016-17,1610612743,DEN,Denver,1627750.0,Jamal Murray,NaN,NaN,33.550000,117.3,118.1,91.5,88.9,25.7,29.2,0.107,0.0,16.7,0.021,0.114,0.060,0.0,0.357,0.403,0.156,0.157,101.87,103.01,85.84,72.0,0.072
4,21600852,2017-02-23,2016-17,1610612740,NOP,New Orleans,201956.0,Omri Casspi,NaN,NaN,23.716667,107.0,109.6,128.2,123.2,-21.2,-13.6,0.000,0.0,0.0,0.043,0.036,0.039,18.2,0.667,0.667,0.190,0.186,108.39,109.28,91.07,52.0,0.039
5,21600852,2017-02-23,2016-17,1610612740,NOP,New Orleans,201956.0,Omri Casspi,NaN,NaN,23.716667,107.0,109.6,128.2,123.2,-21.2,-13.6,0.000,0.0,0.0,0.043,0.036,0.039,18.2,0.667,0.667,0.190,0.186,108.39,109.28,91.07,52.0,0.039

In [10]:
pd.merge(df_5bsa1018.rename(columns={'PLAYER_NAME':'player'}), df_merged_1018, on=['game_date', 'player']).drop_duplicates()

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,player,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21500644,2016-01-21,2015-16,1610612756,PHX,Phoenix,200782.0,P.J. Tucker,F,NaN,6.050000,67.3,72.7,101.7,116.7,-34.4,-43.9,0.000,0.0,0.0,0.000,0.125,0.071,0.0,0.000,0.000,0.000,0.000,101.71,91.24,76.03,11.0,0.061
2,21600323,2016-12-07,2016-17,1610612743,DEN,Denver,1627750.0,Jamal Murray,NaN,NaN,33.550000,117.3,118.1,91.5,88.9,25.7,29.2,0.107,0.0,16.7,0.021,0.114,0.060,0.0,0.357,0.403,0.156,0.157,101.87,103.01,85.84,72.0,0.072
4,21600852,2017-02-23,2016-17,1610612740,NOP,New Orleans,201956.0,Omri Casspi,NaN,NaN,23.716667,107.0,109.6,128.2,123.2,-21.2,-13.6,0.000,0.0,0.0,0.043,0.036,0.039,18.2,0.667,0.667,0.190,0.186,108.39,109.28,91.07,52.0,0.039

In [43]:
rcp('14player_id_player_team_id_season_team_2010_2018.csv')

      PLAYER_ID             player     team_id     Team   season
0      202376.0     Luke Harangody  1610612738  Celtics  2010-11
1        2570.0   Kendrick Perkins  1610612738  Celtics  2010-11
2      202340.0      Avery Bradley  1610612738  Celtics  2010-11
3      202354.0     Dexter Pittman  1610612748     Heat  2010-11
4        2034.0        Mike Miller  1610612748     Heat  2010-11
...         ...                ...         ...      ...      ...
4257  1626195.0  Willy Hernangomez  1610612752   Knicks  2017-18
4258   203504.0         Trey Burke  1610612752   Knicks  2017-18
4259   202722.0      Davis Bertans  1610612759    Spurs  2017-18
4260  1627749.0    Dejounte Murray  1610612759    Spurs  2017-18
4261  1627854.0        Bryn Forbes  1610612759    Spurs  2017-18

[4262 rows x 5 columns]


#### destination<a id='#destination'></a>

In [11]:
df_209 = rcp('9inj_bsa_nzm_209.csv', ['game_date'])
df_209

,game_id,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,player,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,game_date,season,Team,Relinquished,Notes
0,21000212,1.610613e+09,BOS,Boston,2753.0,Delonte West,NaN,NaN,11.916667,66.7,66.7,117.0,104.3,-50.3,-37.7,0.400,0.00,33.3,0.000,0.000,0.000,0.0,0.500,0.500,0.160,0.167,83.62,88.62,73.85,21.0,0.154,2010-11-24,2010-11,Celtics,Delonte West,broken right wrist (out indefinitely)
1,21000224,1.610613e+09,TOR,Toronto,2501.0,Reggie Evans,F,NaN,20.216667,82.8,78.6,129.5,130.0,-46.7,-51.4,0.000,0.00,0.0,0.130,0.273,0.176,16.7,0.667,0.673,0.122,0.128,94.97,97.35,81.12,42.0,0.094,2010-11-26,2010-11,Raptors,Reggie Evans,broken right foot (out indefinitely)
2,21000342,1.610613e+09,IND,Indiana,1902.0,Jeff Foster,NaN,NaN,3.483333,114.2,150.0,111.1,114.3,3.1,35.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.500,0.500,0.250,0.254,104.15,89.78,74.82,6.0,0.100,2010-12-11,2010-11,Pacers,Jeff Foster,placed on IL
3,21000342,1.610613e+09,ATL,Atlanta,2585.0,Zaza Pachulia,NaN,NaN,5.883333,107.8,110.0,108.7,127.3,-0.9,-17.3,0.333,1.00,50.0,0.200,0.167,0.182,50.0,0.000,0.000,0.083,0.082,94.15,85.67,71.39,10.0,0.057,2010-12-11,2010-11,Hawks,Zaza Pachulia,placed on IL with illness
4,21000345,1.610613e+09,CHI,Chicago,703.0,Kurt Thomas,NaN,NaN,3.333333,116.3,100.0,88.8,85.7,27.5,14.3,0.500,0.00,50.0,0.000,0.167,0.143,0.0,1.000,1.000,0.125,0.145,98.21,108.00,90.00,8.0,0.333,2010-12-11,2010-11,Bulls,Kurt Thomas,placed on IL
5,21000370,1.610613e+09,CHI,Chicago,201149.0,Joakim Noah,C,NaN,26.216667,124.7,129.2,81.7,78.0,43.0,51.2,0.000,0.00,0.0,0.143,0.258,0.212,20.0,0.667,0.709,0.175,0.173,89.24,89.71,74.76,48.0,0.169,2010-12-15,2010-11,Bulls,Joakim Noah,torn ligament in right thumb (out indefinitely)
6,21000578,1.610613e+09,TOR,Toronto,2571.0,Leandro Barbosa,NaN,NaN,9.466667,119.6,115.8,131.0,130.0,-11.5,-14.2,0.200,1.00,14.3,0.000,0.111,0.050,14.3,0.250,0.205,0.250,0.256,96.96,98.89,82.41,19.0,-0.087,2011-01-14,2010-11,Raptors,Leandro Barbosa,strained right hamstring (DTD)
7,21000580,1.610613e+09,NYK,New York,101142.0,Ronny Turiaf,C,NaN,15.933333,88.3,87.9,82.4,82.4,6.0,5.5,0.000,0.00,0.0,0.053,0.174,0.119,0.0,0.333,0.333,0.081,0.081,100.68,100.92,84.10,33.0,0.120,2011-01-14,2010-11,Knicks,Ronny Turiaf,right hip pointer (DTD)
8,21000581,1.610613e+09,SAS,San Antonio,2588.0,Matt Bonner,NaN,NaN,7.900000,133.2,123.5,75.6,76.5,57.7,47.1,0.000,0.00,0.0,0.000,0.182,0.111,0.0,1.500,1.500,0.105,0.113,100.13,103.29,86.08,17.0,0.262,2011-01-14,2010-11,Spurs,Matt Bonner,sore right knee (DTD)
9,21000629,1.610613e+09,DET,Detroit,101111.0,Charlie Villanueva,NaN,NaN,10.250000,95.7,89.5,90.1,94.1,5.6,-4.6,0.000,0.00,0.0,0.000,0.167,0.083,0.0,0.000,0.000,0.130,0.145,83.17,84.29,70.24,19.0,-0.087,2011-01-21,2010-11,Pistons,Charlie Villanueva,sprained left ankle (DTD)
10,21000630,1.610613e+09,TOR,Toronto,201595.0,Joey Dorsey,F,NaN,15.066667,68.7,67.9,108.1,111.1,-39.3,-43.3,0.000,0.00,0.0,0.050,0.294,0.162,0.0,0.000,0.000,0.065,0.065,88.27,87.63,73.03,28.0,0.026,2011-01-21,2010-11,Raptors,Joey Dorsey,sore right knee (DTD)
11,21000632,1.610613e+09,BOS,Boston,406.0,Shaquille O'Neal,C,NaN,6.316667,144.6,141.7,92.9,83.3,51.6,58.3,0.200,0.00,50.0,0.000,0.000,0.000,0.0,1.000,1.000,0.083,0.085,85.56,91.19,75.99,12.0,0.107,2011-01-21,2010-11,Celtics,Shaquille O'Neal,hip injury (DTD)
12,21000634,1.610613e+09,WAS,Washington,2550.0,Kirk Hinrich,NaN,NaN,12.883333,105.0,100.0,81.9,89.3,23.1,10.7,0.286,1.00,22.2,0.000,0.125,0.069,22.2,0.800,0.800,0.233,0.243,103.03,100.65,83.87,26.0,0.148,2011-01-21,2010-11,Wizards,Kirk Hinrich,sprained elbow (DTD)
13,21000646,1.610613e+09,SAS,San Antonio,201588.0,George Hill,NaN,NaN,19.416667,69.1,69.7,100.7,100.0,-31.6,-30.3,0.000,0.00,0.0,0.000,0.053,0.027,12.5,0.417,0.515,0.222,0.227,82.86,82.82,69.01,33.0,0.107,2011-01-22,2010-11,Spurs,George Hill,sprained right thumb (DNP)
14,21000646,1.610613e+09,NOH,New Orleans,2772.0,Trevor Ariza,F,NaN,25.933333,109.2,108.5,53.9,54.3,55.3,54.2,0.071,0.50,8.3,0.000,0.276,0.136,16.7,0.875,0.805,0.193,0.194,86.18,86.07,71.72,47.0,0.288,2011-01-22,2010-11,Hornets,Trevor Ariza,right knee tendinitis (DNP)
15,21000689,1.610613e+09,UTA,Utah,2246.0,Mehmet Okur,NaN,NaN,8.783333,137.5,128.6,134.1,140.0,3.4,-11.4,0.125,0.00,25.0,0.143,0.400,0.250,0.0,0.333,0.333,0.130,0.139,110.72,112.03,93.36,21.0,0.078,2011-01-28,2010-11,Jazz,Mehmet Okur,strained lower back (DTD)
16,21000736,1.610613e+09,MIN,Minnesota,201563.0,Michael Beasley,F,NaN,12.633333,101.2,103.4,133.0,139.3,-31.8,-35.8,0.100,1.00,11.1,0.083,0.000,0.045,11.1,0.286,0.286,0.229,0.238,112.01,108.28,90.24,29.0,-0.020,2011-02-04,2010-11,Timberwolves,Michael Beasley,left ankle injury (DTD)
17,21000747,1.610613e+09,POR,Portland,201967.0,Dante Cunningham,C,NaN,13.216667,109.0,108.0,121.2,115.4,-12.1,-7.4,0.000,0.00,0.0,0.077,0.100,0.087,0.0,0.429,0.429,0.250,0.252,89.92,92.61,77.18,25.0,0.061,2011-02-05,2010-11,Blazers,Dante Cunningham,facial injury (DNP)
18,21000757,1.610613e+09,BOS,Boston,2605.0,Marquis Daniels,NaN,NaN,3.716667,68.0,50.0,44.4,57.1,23.6,-7.1,0.000,0.00,0.0,0.000,0.143,0.111,0.0,0.000,0.000,0.000,0.000,96.09,96.86,80.72,8.0,0.667,2011-02-06,2010-11,Celtics,Marquis Daniels,bruised spinal cord (out indefinitely)
19,21000881,1.610613e+09,CLE,Cleveland,1712.0,Antawn Jamison,F,NaN,29.700000,86.1,86.2,104.0,107.0,-17.9,-20.8,0.000,0.00,0.0,0.000,0.138,0.068,16.7,0.500,0.538,0.281,0.286,94.27,92.91,77.42,58.0,0.093,2011-02-27,2010-11,Cavaliers,Antawn Jamison,broken left little finger (out indefinitely)
20,21001049,1.610613e+09,SAS,San Antonio,1495.0,Tim Duncan,F,NaN,4.216667,161.9,160.0,70.9,70.0,91.1,90.0,0.000,0.00,0.0,0.000,0.429,0.375,0.0,1.000,1.000,0.200,0.202,112.47,113.83,94.86,10.0,0.288,2011-03-21,2010-11,Spurs,Tim Duncan,sprained left ankle (out indefinitely)
21,21001061,1.610613e+09,UTA,Utah,1905.0,Andrei Kirilenko,F,NaN,13.700000,83.4,85.7,117.7,103.6,-34.2,-17.9,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.300,0.300,0.161,0.163,93.57,98.13,81.77,28.0,0.019,2011-03-23,2010-11,Jazz,Andrei Kirilenko,bruised left knee (DTD)
22,21001144,1.610613e+09,ORL,Orlando,201583.0,Ryan Anderson,NaN,NaN,19.083333,108.3,115.8,125.0,118.9,-16.7,-3.1,0.067,0.00,20.0,0.000,0.200,0.081,0.0,0.750,0.750,0.095,0.094,95.40,94.35,78.62,38.0,0.125,2011-04-03,2010-11,Magic,Ryan Anderson,placed on IL (out for season)
23,21001215,1.610613e+09,LAL,Los Angeles,101115.0,Andrew Bynum,C,NaN,13.066667,96.0,96.3,93.2,88.9,2.8,7.4,0.000,0.00,0.0,0.000,0.250,0.129,0.0,0.667,0.667,0.107,0.111,97.05,99.18,82.65,27.0,0.163,2011-04-12,2010-11,Lakers,Andrew Bynum,hyperextended right knee (left game)
24,21100001,1.610613e+09,NYK,New York,202697.0,Iman Shumpert,NaN,NaN,22.033333,92.4,93.8,119.8,119.6,-27.4,-25.8,0.077,0.50,5.6,0.045,0.167,0.100,11.1,0.231,0.362,0.309,0.322,103.06,102.37,85.31,48.0,0.020,2011-12-25,2011-12,Knicks,Iman Shumpert,sprained MCL in right knee (out indefinitely)
25,21100072,1.610613e+09,SAS,San Antonio,1938.0,Manu Ginobili,G,NaN,12.666667,135.7,126.9,153.5,152.0,-17.8,-25.1,0.200,0.00,25.0,0.000,0.286,0.105,0.0,0.583,0.621,0.207,0.220,92.99,96.63,80.53,26.0,0.122,2012-01-02,2011-12,Spurs,Manu Ginobili,broken bone in left hand (out indefinitely)
26,21100112,1.610613e+09,MIA,Miami,2544.0,LeBron James,F,NaN,37.383333,104.8,103.9,91.1,92.4,13.7,11.5,0.474,1.13,23.1,0.000,0.140,0.089,20.5,0.647,0.718,0.361,0.364,100.46,100.15,83.46,77.0,0.256,2012-01-07,2011-12,Heat,LeBron James,sprained left ankle (DNP)
27,21100589,1.610613e+09,MIN,Minnesota,201937.0,Ricky Rubio,G,NaN,38.983333,112.3,116.4,107.6,109.3,4.8,7.1,0.400,2.50,35.7,0.029,0.077,0.054,14.3,0.458,0.528,0.209,0.213,93.55,91.13,75.94,73.0,0.113,2012-03-09,2011-12,Timberwolves,Ricky Rubio,torn ACL in left knee (out for season)
28,21100600,1.610613e+09,MIN,Minnesota,201567.0,Kevin Love,F,NaN,41.216667,96.4,92.6,101.0,105.0,-4.6,-12.4,0.000,0.00,0.0,0.116,0.282,0.195,6.7,0.478,0.566,0.316,0.327,93.73,93.76,78.13,81.0,0.208,2012-03-10,2011-12,Timberwolves,Kevin Love,back spasms (DNP)
29,21100674,1.610613e+09,DEN,Denver,201568.0,Danilo Gallinari,F,NaN,22.950000,100.8,100.0,119.1,121.3,-18.4,-21.3,0.389,2.33,38.9,0.111,0.190,0.154,16.7,0.143,0.254,0.216,0.222,98.80,98.30,81.92,47.0,0.047,2012-03-19,2011-12,Nuggets,Danilo Gallinari,fractured right thumb (DTD)
30,21200152,1.610613e+09,SAS,San Antonio,1536.0,Stephen Jackson,F,NaN,10.650000,104.9,104.3,73.5,66.7,31.4,37.7,0.000,0.00,0.0,0.000,0.133,0.077,0.0,0.333,0.333,0.120,0.121,100.68,106.00,88.33,23.0,0.029,2012-11-19,2012-13,Spurs,Stephen Jackson,fractured right pinky finger (out indefinitely)
31,21200238,1.610613e+09,MIL,Milwaukee,202327.0,Ekpe Udoh,C,NaN,15.133333,66.2,66.7,112.6,109.4,-46.4,-42.7,0.000,0.00,0.0,0.000,0.111,0.042,20.0,0.667,0.644,0.167,0.166,97.18,98.33,81.94,30.0,0.018,2012-12-01,2012-13,Bucks,Ekpe Udoh,placed on IL
32,21200380,1.610613e+09,TOR,Toronto,202685.0,Jonas Valanciunas,C,NaN,4.483333,40.0,33.3,66.7,66.7,-26.7,-33.3,0.000,0.00,0.0,0.200,0.000,0.100,0.0,0.000,0.000,0.000,0.000,58.88,64.24,53.53,6.0,0.250,2012-12-21,2012-13,Raptors,Jonas Valanciunas,fractured right ring finger (out indefinitely)
33,21200673,1.610613e+09,ORL,Orlando,201175.0,Glen Davis,F,NaN,4.333333,175.0,175.0,112.5,100.0,62.5,75.0,0.600,0.00,60.0,0.000,0.000,0.000,0.0,0.500,0.500,0.250,0.250,88.62,94.15,78.46,8.0,0.131,2013-01-30,2012-13,Magic,Glen Davis,fractured left foot (out indefinitely)
34,21200781,1.610613e+09,WAS,Washington,202344.0,Trevor Booker,NaN,NaN,0.050000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,1.000,1.000,533.33,533.33,444.44,1.0,1.000,2013-02-13,2012-13,Wizards,Trevor Booker,sore left wrist (DNP)
35,21200799,1.610613e+09,CHA,Charlotte,2732.0,Ben Gordon,NaN,NaN,10.500000,123.4,121.1,126.4,127.8,-3.0,-6.7,0.167,0.00,12.5,0.000,0.111,0.048,0.0,0.357,0.357,0.280,0.296,84.18,84.54,70.45,19.0,0.026,2013-02-20,2012-13,Bobcats,Ben Gordon,sore right knee (DNP)
36,21200990,1.610613e+09,DAL,Dallas,201958.0,Rodrigue Beaubois,NaN,NaN,6.616667,97.0,100.0,110.2,114.3,-13.2,-14.3,0.000,0.00,0.0,0.000,0.000,0.000,75.0,0.000,0.000,0.286,0.277,105.04,101.56,84.63,14.0,-0.244,2013-03-17,2012-13,Mavericks,Rodrigue Beaubois,fractured left hand (out indefinitely)
37,21201068,1.610613e+09,UTA,Utah,202683.0,Enes Kanter,NaN,NaN,3.483333,140.0,140.0,83.3,83.3,56.7,56.7,0.000,0.00,0.0,0.000,0.333,0.200,50.0,0.000,0.000,0.333,0.333,75.79,75.79,63.16,5.0,-0.118,2013-03-27,2012-13,Jazz,Enes Kanter,dislocated left shoulder (out indefinitely)
38,21201189,1.610613e+09,LAL,Los Angeles,977.0,Kobe Bryant,G,NaN,44.900000,121.8,121.1,123.6,122.5,-1.8,-1.4,0.174,0.80,10.5,0.000,0.104,0.060,13.2,0.524,0.606,0.351,0.368,94.95,95.68,79.73,90.0,0.102,2013-04-12,2012-13,Lakers,Kobe Bryant,torn left Achilles tendon (out indefinitely)
39,21201209,1.610613e+09,SAC,Sacramento,201936.0,Tyreke Evans,G,NaN,10.000000,73.5,80.0,101.7,100.0,-28.2,-20.0,0.333,0.00,16.7,0.000,0.000,0.000,0.0,0.800,0.800,0.217,0.220,101.76,98.40,82.00,20.0,0.302,2013-04-15,2012-13,Kings,Tyreke Evans,sore left shoulder (DNP)
40,21300025,1.610613e+09,HOU,Houston,201956.0,Omri Casspi,NaN,NaN,21.233333,127.3,125.0,89.1,91.5,38.3,33.5,0.133,2.00,16.7,0.038,0.032,0.035,8.3,0.688,0.676,0.167,0.172,107.83,107.38,89.48,48.0,0.114,2013-11-01,2013-14,Rockets,Omri Casspi,sprained left ankle (DNP)
41,21300027,1.610613e+09,MIN,Minnesota,101142.0,Ronny Turiaf,NaN,NaN,3.116667,156.2,112.5,116.3,114.3,40.0,-1.8,0.333,0.00,100.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,97.33,115.51,96.26,8.0,0.000,2013-11-01,2013-14,Timberwolves,Ronny Turiaf,fractured right elbow (out indefinitely)
42,21300029,1.610613e+09,POR,Portland,201964.0,Victor Claver,NaN,NaN,1.366667,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,70.24,87.80,73.17,3.0,0.000,2013-11-01,2013-14,Blazers,Victor Claver,placed on IL
43,21300254,1.610613e+09,NOP,New Orleans,203076.0,Anthony Davis,F,NaN,10.450000,75.5,84.2,100.0,94.7,-24.5,-10.5,0.000,0.00,0.0,0.071,0.333,0.174,12.5,0.333,0.478,0.333,0.331,90.03,87.27,72.73,19.0,0.177,2013-12-01,2013-14,Pelicans,Anthony Davis,fractured left hand (out indefinitely)
44,21300361,1.610613e+09,NYK,New York,203143.0,Pablo Prigioni,G,NaN,18.333333,71.5,73.0,116.4,116.7,-44.9,-43.7,0.273,3.00,42.9,0.000,0.071,0.026,14.3,0.000,0.000,0.098,0.098,96.66,95.56,79.64,37.0,0.000,2013-12-16,2013-14,Knicks,Pablo Prigioni,fractured right toe (out indefinitely)
45,21300396,1.610613e+09,HOU,Houston,201976.0,Patrick Beverley,G,NaN,14.583333,117.2,118.2,98.8,97.0,18.4,21.2,0.182,2.00,18.2,0.000,0.214,0.111,9.1,0.500,0.644,0.243,0.248,108.09,108.62,90.51,33.0,0.161,2013-12-21,2013-14,Rockets,Patrick Beverley,fractured right hand (out indefinitely)
46,21300486,1.610613e+09,LAC,Los Angeles,101108.0,Chris Paul,G,NaN,21.816667,128.8,124.4,109.5,108.9,19.3,15.6,0.462,6.00,35.3,0.000,0.150,0.075,5.9,0.938,0.973,0.220,0.227,97.09,99.02,82.52,45.0,0.233,2014-01-03,2013-14,Clippers,Chris Paul,separated right shoulder (out indefinitely)
47,21300630,1.610613e+09,SAS,San Antonio,202695.0,Kawhi Leonard,F,NaN,15.083333,104.0,103.2,113.8,106.3,-9.8,-3.0,0.083,0.50,20.0,0.071,0.000,0.043,40.0,0.750,0.750,0.114,0.115,96.49,100.24,83.54,31.0,0.023,2014-01-22,2013-14,Spurs,Kawhi Leonard,fractured right hand (out indefinitely)
48,21300641,1.610613e+09,LAC,Los Angeles,2584.0,Willie Green,NaN,NaN,5.683333,100.0,90.0,88.9,88.9,11.1,1.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.667,0.667,0.300,0.333,76.01,80.23,66.86,10.0,0.171,2014-01-24,2013-14,Clippers,Willie Green,placed on IL (P)
49,21400003,1.610613e+09,LAL,Los Angeles,203944.0,Julius Randle,NaN,NaN,13.566667,58.3,60.0,132.4,126.9,-74.1,-66.9,0.000,0.00,0.0,0.000,0.000,0.000,20.0,0.333,0.258,0.172,0.174,89.58,90.22,75.18,25.0,-0.242,2014-10-28,2014-15,Lakers,Julius Randle,fractured tibia in right leg (out for season)
50,21400020,1.610613e+09,OKC,Oklahoma City,201566.0,Russell Westbrook,G,NaN,8.716667,84.0,90.0,113.4,110.5,-29.4,-20.5,0.500,1.33,40.0,0.000,0.000,0.000,30.0,0.333,0.333,0.261,0.256,110.02,107.38,89.48,20.0,0.000,2014-10-30,2014-15,Thunder,Russell Westbrook,fractured right hand (DTD)
51,21400271,1.610613e+09,UTA,Utah,203504.0,Trey Burke,G,NaN,33.900000,122.6,126.6,136.6,139.4,-14.0,-12.8,0.286,8.00,33.3,0.029,0.077,0.049,4.2,0.500,0.500,0.216,0.213,94.49,92.05,76.71,64.0,0.084,2014-12-03,2014-15,Jazz,Trey Burke,placed on IL
52,21400653,1.610613e+09,DET,Detroit,201943.0,Brandon Jennings,G,NaN,26.133333,86.5,87.3,103.3,105.7,-16.9,-18.4,0.308,0.80,16.7,0.030,0.042,0.035,20.8,0.464,0.508,0.303,0.305,100.76,99.18,82.65,55.0,0.073,2015-01-24,2014-15,Pistons,Brandon Jennings,torn left Achilles (out for season)
53,21400661,1.610613e+09,MIN,Minnesota,203133.0,Robbie Hummel,NaN,NaN,22.733333,115.0,111.4,127.6,136.4,-12.5,-25.0,0.077,1.00,11.1,0.000,0.211,0.095,11.1,0.583,0.654,0.154,0.158,94.63,92.90,77.42,44.0,0.090,2015-01-25,2014-15,Timberwolves,Robbie Hummel,fractured right hand (out indefinitely)
54,21400699,1.610613e+09,TOR,Toronto,101161.0,Amir Johnson,F,NaN,34.566667,130.2,129.0,107.1,105.8,23.1,23.2,0.000,0.00,0.0,0.143,0.071,0.100,13.3,0.909,0.940,0.195,0.196,94.79,95.81,79.85,69.0,0.150,2015-01-30,2014-15,Raptors,Amir Johnson,placed on IL
55,21500054,1.610613e+09,IND,Indiana,101133.0,Ian Mahinmi,C,NaN,5.483333,91.7,84.6,116.5,115.4,-24.8,-30.8,0.000,0.00,0.0,0.000,0.000,0.000,100.0,0.000,0.000,0.071,0.077,108.90,113.80,94.83,13.0,-0.085,2015-11-03,2015-16,Pacers,Ian Mahinmi,sore lower back (DTD)
56,21500064,1.610613e+09,ORL,Orlando,202696.0,Nikola Vucevic,C,NaN,16.750000,130.7,131.4,124.6,126.5,6.1,5.0,0.125,0.00,25.0,0.000,0.133,0.083,0.0,0.500,0.500,0.162,0.166,99.90,98.87,82.39,35.0,0.075,2015-11-04,2015-16,Magic,Nikola Vucevic,sprained right knee (DTD)
57,21500064,1.610613e+09,HOU,Houston,201976.0,Patrick Beverley,NaN,NaN,12.016667,115.6,120.0,106.4,111.1,9.2,8.9,0.000,0.00,0.0,0.000,0.143,0.083,0.0,0.375,0.375,0.143,0.138,108.17,103.86,86.55,25.0,0.019,2015-11-04,2015-16,Rockets,Patrick Beverley,concussion (DTD)
58,21500099,1.610613e+09,IND,Indiana,201155.0,Rodney Stuckey,NaN,NaN,17.816667,92.2,94.4,92.1,97.3,0.1,-2.9,0.364,0.00,33.3,0.000,0.105,0.053,0.0,0.375,0.375,0.205,0.201,102.32,98.33,81.95,36.0,0.129,2015-11-09,2015-16,Pacers,Rodney Stuckey,sore right ankle (DTD)
59,21500123,1.610613e+09,POR,Portland,203086.0,Meyers Leonard,F,NaN,23.933333,112.3,114.6,108.3,106.3,4.0,8.3,0.105,0.00,33.3,0.000,0.227,0.109,0.0,0.875,0.875,0.077,0.077,96.31,96.27,80.22,48.0,0.114,2015-11-11,2015-16,Blazers,Meyers Leonard,dislocated left shoulder (out indefinitely)
60,21500147,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,9.466667,140.8,138.9,111.9,111.1,28.9,27.8,0.000,0.00,0.0,0.143,0.000,0.071,0.0,0.500,0.500,0.100,0.101,90.35,91.27,76.06,18.0,0.060,2015-11-15,2015-16,Hornets,P.J. Hairston,placed on IL with bruised right quadricep
61,21500153,1.610613e+09,CHI,Chicago,201565.0,Derrick Rose,G,NaN,33.216667,93.0,94.1,83.3,84.3,9.7,9.8,0.400,0.00,23.1,0.024,0.022,0.023,0.0,0.556,0.582,0.260,0.260,100.89,99.71,83.09,68.0,0.179,2015-11-16,2015-16,Bulls,Derrick Rose,sprained left ankle (DTD)
62,21500176,1.610613e+09,CLE,Cleveland,202389.0,Timofey Mozgov,C,NaN,11.250000,166.0,165.0,97.0,100.0,69.0,65.0,0.000,0.00,0.0,0.000,0.000,0.000,33.3,0.500,0.500,0.143,0.144,88.58,87.47,72.89,20.0,-0.038,2015-11-19,2015-16,Cavaliers,Timofey Mozgov,strained right shoulder (DTD)
63,21500191,1.610613e+09,ATL,Atlanta,201168.0,Tiago Splitter,NaN,NaN,9.466667,68.4,68.4,117.4,110.5,-49.0,-42.1,0.000,0.00,0.0,0.000,0.000,0.000,0.0,1.000,1.000,0.105,0.105,93.50,96.34,80.28,19.0,0.086,2015-11-21,2015-16,Hawks,Tiago Splitter,sore right hip (DTD)
64,21500204,1.610613e+09,MIA,Miami,2736.0,Luol Deng,F,NaN,31.133333,94.7,94.9,97.4,100.0,-2.7,-5.1,0.000,0.00,0.0,0.028,0.061,0.043,10.0,0.500,0.500,0.145,0.145,92.32,90.96,75.80,59.0,0.060,2015-11-23,2015-16,Heat,Luol Deng,sore hamstring (DTD)
65,21500215,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,16.200000,100.8,94.1,109.9,109.1,-9.1,-15.0,0.182,2.00,25.0,0.000,0.143,0.077,12.5,0.375,0.512,0.154,0.163,95.59,99.26,82.72,34.0,0.045,2015-11-25,2015-16,Hornets,P.J. Hairston,placed on IL
66,21500282,1.610613e+09,SAC,Sacramento,1626161.0,Willie Cauley-Stein,F,NaN,17.666667,123.9,125.6,94.9,97.4,29.0,28.2,0.091,1.00,14.3,0.077,0.174,0.139,14.3,1.000,0.862,0.143,0.144,108.11,105.93,88.28,39.0,0.130,2015-12-03,2015-16,Kings,Willie Cauley-Stein,dislocated right index finger (out indefinitely)
67,21500372,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,21.950000,100.1,102.3,125.9,131.8,-25.8,-29.5,0.000,0.00,0.0,0.050,0.077,0.061,15.4,0.591,0.612,0.271,0.266,98.45,95.13,79.27,43.0,0.072,2015-12-16,2015-16,Hornets,P.J. Hairston,placed on IL
68,21500399,1.610613e+09,CHA,Charlotte,203798.0,PJ Hairston,F,NaN,18.666667,86.0,89.5,109.1,107.3,-23.1,-17.8,0.250,2.00,20.0,0.115,0.176,0.140,10.0,0.667,0.727,0.170,0.168,102.65,101.57,84.64,38.0,0.160,2015-12-19,2015-16,Hornets,P.J. Hairston,placed on IL
69,21500414,1.610613e+09,CHI,Chicago,201149.0,Joakim Noah,NaN,NaN,15.933333,108.0,109.1,108.3,109.4,-0.2,-0.3,0.615,0.00,66.7,0.143,0.313,0.216,0.0,0.500,0.500,0.098,0.099,98.92,97.96,81.63,33.0,0.203,2015-12-21,2015-16,Bulls,Joakim Noah,sprained left shoulder (DTD)
70,21500421,1.610613e+09,DAL,Dallas,101114.0,Deron Williams,G,NaN,23.333333,82.4,86.7,111.4,104.3,-29.0,-17.7,0.462,0.00,42.9,0.000,0.095,0.042,0.0,0.286,0.421,0.170,0.169,92.98,93.60,78.00,45.0,0.123,2015-12-22,2015-16,Mavericks,Deron Williams,strained left hamstring (DTD)
71,21500451,1.610613e+09,PHX,Phoenix,202339.0,Eric Bledsoe,G,NaN,8.150000,47.1,47.1,83.9,83.3,-36.8,-36.3,0.000,0.00,0.0,0.000,0.286,0.118,33.3,0.500,0.500,0.353,0.353,102.71,103.07,85.89,17.0,0.000,2015-12-26,2015-16,Suns,Eric Bledsoe,sprained left knee (out for season)

In [12]:
df_merge = pd.merge(df_5bsa1018.rename(columns={'PLAYER_NAME':'player'}), df_209, on=['game_date', 'player'], indicator=True)
df_merge

     game_id_x  game_date season_x     team_id TEAM_ABBREVIATION_x  \
0     21000212 2010-11-24  2010-11  1610612738                 BOS
1     21000212 2010-11-24  2010-11  1610612738                 BOS
2     21000224 2010-11-26  2010-11  1610612761                 TOR
3     21000224 2010-11-26  2010-11  1610612761                 TOR
4     21000342 2010-12-11  2010-11  1610612754                 IND
5     21000342 2010-12-11  2010-11  1610612754                 IND
6     21000342 2010-12-11  2010-11  1610612737                 ATL
7     21000342 2010-12-11  2010-11  1610612737                 ATL
8     21000345 2010-12-11  2010-11  1610612741                 CHI
9     21000345 2010-12-11  2010-11  1610612741                 CHI
10    21000370 2010-12-15  2010-11  1610612741                 CHI
11    21000370 2010-12-15  2010-11  1610612741                 CHI
12    21000578 2011-01-14  2010-11  1610612761                 TOR
13    21000578 2011-01-14  2010-11  1610612761                 TOR
14    21000580 2011-01-14  2010-11  1610612752                 NYK
15    21000580 2011-01-14  2010-11  1610612752                 NYK
16    21000581 2011-01-14  2010-11  1610612759                 SAS
17    21000581 2011-01-14  2010-11  1610612759                 SAS
18    21000629 2011-01-21  2010-11  1610612765                 DET
19    21000629 2011-01-21  2010-11  1610612765                 DET
20    21000630 2011-01-21  2010-11  1610612761                 TOR
21    21000630 2011-01-21  2010-11  1610612761                 TOR
22    21000632 2011-01-21  2010-11  1610612738                 BOS
23    21000632 2011-01-21  2010-11  1610612738                 BOS
24    21000634 2011-01-21  2010-11  1610612764                 WAS
25    21000634 2011-01-21  2010-11  1610612764                 WAS
26    21000646 2011-01-22  2010-11  1610612759                 SAS
27    21000646 2011-01-22  2010-11  1610612759                 SAS
28    21000646 2011-01-22  2010-11  1610612740                 NOH
29    21000646 2011-01-22  2010-11  1610612740                 NOH
30    21000689 2011-01-28  2010-11  1610612762                 UTA
31    21000689 2011-01-28  2010-11  1610612762                 UTA
32    21000736 2011-02-04  2010-11  1610612750                 MIN
33    21000736 2011-02-04  2010-11  1610612750                 MIN
34    21000747 2011-02-05  2010-11  1610612757                 POR
35    21000747 2011-02-05  2010-11  1610612757                 POR
36    21000757 2011-02-06  2010-11  1610612738                 BOS
37    21000757 2011-02-06  2010-11  1610612738                 BOS
38    21000881 2011-02-27  2010-11  1610612739                 CLE
39    21000881 2011-02-27  2010-11  1610612739                 CLE
40    21001049 2011-03-21  2010-11  1610612759                 SAS
41    21001049 2011-03-21  2010-11  1610612759                 SAS
42    21001061 2011-03-23  2010-11  1610612762                 UTA
43    21001061 2011-03-23  2010-11  1610612762                 UTA
44    21001144 2011-04-03  2010-11  1610612753                 ORL
45    21001144 2011-04-03  2010-11  1610612753                 ORL
46    21001215 2011-04-12  2010-11  1610612747                 LAL
47    21001215 2011-04-12  2010-11  1610612747                 LAL
48    21100001 2011-12-25  2011-12  1610612752                 NYK
49    21100001 2011-12-25  2011-12  1610612752                 NYK
50    21100072 2012-01-02  2011-12  1610612759                 SAS
51    21100072 2012-01-02  2011-12  1610612759                 SAS
52    21100112 2012-01-07  2011-12  1610612748                 MIA
53    21100112 2012-01-07  2011-12  1610612748                 MIA
54    21100589 2012-03-09  2011-12  1610612750                 MIN
55    21100589 2012-03-09  2011-12  1610612750                 MIN
56    21100600 2012-03-10  2011-12  1610612750                 MIN
57    21100600 2012-03-10  2011-12  1610612750                 MIN
58    21100674 2012-03-19  2011-12  1610612743                 DEN
59    21100674 2012-03-19  2011-12  1610612743                 DEN
60    21200152 2012-11-19  2012-13  1610612759                 SAS
61    21200152 2012-11-19  2012-13  1610612759                 SAS
62    21200238 2012-12-01  2012-13  1610612749                 MIL
63    21200238 2012-12-01  2012-13  1610612749                 MIL
64    21200380 2012-12-21  2012-13  1610612761                 TOR
65    21200380 2012-12-21  2012-13  1610612761                 TOR
66    21200673 2013-01-30  2012-13  1610612753                 ORL
67    21200673 2013-01-30  2012-13  1610612753                 ORL
68    21200781 2013-02-13  2012-13  1610612764                 WAS
69    21200781 2013-02-13  2012-13  1610612764                 WAS
70    21200799 2013-02-20  2012-13  1610612766                 CHA
71    21200799 2013-02-20  2012-13  1610612766                 CHA
72    21200990 2013-03-17  2012-13  1610612742                 DAL
73    21200990 2013-03-17  2012-13  1610612742                 DAL
74    21201068 2013-03-27  2012-13  1610612762                 UTA
75    21201068 2013-03-27  2012-13  1610612762                 UTA
76    21201189 2013-04-12  2012-13  1610612747                 LAL
77    21201189 2013-04-12  2012-13  1610612747                 LAL
78    21201209 2013-04-15  2012-13  1610612758                 SAC
79    21201209 2013-04-15  2012-13  1610612758                 SAC
80    21300025 2013-11-01  2013-14  1610612745                 HOU
81    21300025 2013-11-01  2013-14  1610612745                 HOU
82    21300027 2013-11-01  2013-14  1610612750                 MIN
83    21300027 2013-11-01  2013-14  1610612750                 MIN
84    21300029 2013-11-01  2013-14  1610612757                 POR
85    21300029 2013-11-01  2013-14  1610612757                 POR
86    21300254 2013-12-01  2013-14  1610612740                 NOP
87    21300254 2013-12-01  2013-14  1610612740                 NOP
88    21300361 2013-12-16  2013-14  1610612752                 NYK
89    21300361 2013-12-16  2013-14  1610612752                 NYK
90    21300396 2013-12-21  2013-14  1610612745                 HOU
91    21300396 2013-12-21  2013-14  1610612745                 HOU
92    21300486 2014-01-03  2013-14  1610612746                 LAC
93    21300486 2014-01-03  2013-14  1610612746                 LAC
94    21300630 2014-01-22  2013-14  1610612759                 SAS
95    21300630 2014-01-22  2013-14  1610612759                 SAS
96    21300641 2014-01-24  2013-14  1610612746                 LAC
97    21300641 2014-01-24  2013-14  1610612746                 LAC
98    21400003 2014-10-28  2014-15  1610612747                 LAL
99    21400003 2014-10-28  2014-15  1610612747                 LAL
100   21400020 2014-10-30  2014-15  1610612760                 OKC
101   21400020 2014-10-30  2014-15  1610612760                 OKC
102   21400271 2014-12-03  2014-15  1610612762                 UTA
103   21400271 2014-12-03  2014-15  1610612762                 UTA
104   21400653 2015-01-24  2014-15  1610612765                 DET
105   21400653 2015-01-24  2014-15  1610612765                 DET
106   21400661 2015-01-25  2014-15  1610612750                 MIN
107   21400661 2015-01-25  2014-15  1610612750                 MIN
108   21400699 2015-01-30  2014-15  1610612761                 TOR
109   21400699 2015-01-30  2014-15  1610612761                 TOR
110   21500054 2015-11-03  2015-16  1610612754                 IND
111   21500054 2015-11-03  2015-16  1610612754                 IND
112   21500064 2015-11-04  2015-16  1610612753                 ORL
113   21500064 2015-11-04  2015-16  1610612753                 ORL
114   21500064 2015-11-04  2015-16  1610612745                 HOU
115   21500064 2015-11-04  2015-16  1610612745                 HOU
116   21500099 2015-11-09  2015-16  1610612754                 IND
117   21500099 2015-11-09  2015-16  1610612754                 IND
118   21500123 2015-11-11  2015-16  1610612757                 POR
119   21500123 2015-11-11  2015-16  1610612757                 POR
120   21500147 2015-11-15  2015-16  1610612766                 CHA
121   21500147 2015-11-15  2015-16  1610612766                 CHA
122   21500153 2015-11-16  2015-16  1610612741                 CHI
123   21500153 2015-11-16  2015-16  1610612741                 CHI
124   21500176 2015-11-19  2015-16  1610612739                 CLE
125   21500176 2015-11-19  2015-16  1610612739                 CLE
126   21500191 2015-11-21  2015-16  1610612737                 ATL
127   21500191 2015-11-21  2015-16  1610612737                 ATL
128   21500204 2015-11-23  2015-16  1610612748                 MIA
129   21500204 2015-11-23  2015-16  1610612748                 MIA
130   21500215 2015-11-25  2015-16  1610612766                 CHA
131   21500215 2015-11-25  2015-16  1610612766                 CHA
132   21500282 2015-12-03  2015-16  1610612758                 SAC
133   21500282 2015-12-03  2015-16  1610612758                 SAC
134   21500372 2015-12-16  2015-16  1610612766                 CHA
135   21500372 2015-12-16  2015-16  1610612766                 CHA
136   21500399 2015-12-19  2015-16  1610612766                 CHA
137   21500399 2015-12-19  2015-16  1610612766                 CHA
138   21500414 2015-12-21  2015-16  1610612741                 CHI
139   21500414 2015-12-21  2015-16  1610612741                 CHI
140   21500421 2015-12-22  2015-16  1610612742                 DAL
141   21500421 2015-12-22  2015-16  1610612742                 DAL
142   21500451 2015-12-26  2015-16  1610612756                 PHX
143   21500451 2015-12-26  2015-16  1610612756                 PHX
144   21500491 2016-01-01  2015-16  1610612742                 DAL
145   21500491 2016-01-01  2015-16  1610612742                 DAL
146   21500495 2016-01-02  2015-16  1610612738                 BOS
147   21500495 2016-01-02  2015-16  1610612738                 BOS
148   21500519 2016-01-04  2015-16  1610612763                 MEM
149   21500519 2016-01-04  2015-16  1610612763                 MEM
150   21500538 2016-01-07  2015-16  1610612762                 UTA
151   21500538 2016-01-07  2015-16  1610612762                 UTA
152   21500544 2016-01-08  2015-16  1610612740                 NOP
153   21500544 2016-01-08  2015-16  1610612740                 NOP
154   21500549 2016-01-08  2015-16  1610612747                 LAL
155   21500549 2016-01-08  2015-16  1610612747                 LAL
156   21500551 2016-01-09  2015-16  1610612737                 ATL
157   21500551 2016-01-09  2015-16  1610612737                 ATL
158   21500569 2016-01-12  2015-16  1610612754                 IND
159   21500569 2016-01-12  2015-16  1610612754                 IND
160   21500597 2016-01-15  2015-16  1610612741                 CHI
161   21500597 2016-01-15  2015-16  1610612741                 CHI
162   21500626 2016-01-19  2015-16  1610612740                 NOP
163   21500626 2016-01-19  2015-16  1610612740                 NOP
164   21500630 2016-01-20  2015-16  1610612748                 MIA
165   21500630 2016-01-20  2015-16  1610612748                 MIA
166   21500644 2016-01-21  2015-16  1610612756                 PHX
167   21500644 2016-01-21  2015-16  1610612756                 PHX
168   21500671 2016-01-25  2015-16  1610612740                 NOP
169   21500671 2016-01-25  2015-16  1610612740                 NOP
170   21500688 2016-01-27  2015-16  1610612760                 OKC
171   21500688 2016-01-27  2015-16  1610612760                 OKC
172   21500690 2016-01-27  2015-16  1610612766                 CHA
173   21500690 2016-01-27  2015-16  1610612766                 CHA
174   21500692 2016-01-28  2015-16  1610612737                 ATL
175   21500692 2016-01-28  2015-16  1610612737                 ATL
176   21500712 2016-01-30  2015-16  1610612758                 SAC
177   21500712 2016-01-30  2015-16  1610612758                 SAC
178   21500723 2016-02-01  2015-16  1610612742                 DAL
179   21500723 2016-02-01  2015-16  1610612742                 DAL
180   21500735 2016-02-03  2015-16  1610612766                 CHA
181   21500735 2016-02-03  2015-16  1610612766                 CHA
182   21500736 2016-02-03  2015-16  1610612755                 PHI
183   21500736 2016-02-03  2015-16  1610612755                 PHI
184   21500752 2016-02-05  2015-16  1610612753                 ORL
185   21500752 2016-02-05  2015-16  1610612753                 ORL
186   21500781 2016-02-08  2015-16  1610612763                 MEM
187   21500781 2016-02-08  2015-16  1610612763                 MEM
188   21500884 2016-02-29  2015-16  1610612739                 CLE
189   21500884 2016-02-29  2015-16  1610612739                 CLE
190   21500890 2016-02-29  2015-16  1610612746                 LAC
191   21500890 2016-02-29  2015-16  1610612746                 LAC
192   21500953 2016-03-09  2015-16  1610612763                 MEM
193   21500953 2016-03-09  2015-16  1610612763                 MEM
194   21500992 2016-03-14  2015-16  1610612763                 MEM
195   21500992 2016-03-14  2015-16  1610612763                 MEM
196   21501016 2016-03-17  2015-16  1610612741                 CHI
197   21501016 2016-03-17  2015-16  1610612741                 CHI
198   21501023 2016-03-18  2015-16  1610612761                 TOR
199   21501023 2016-03-18  2015-16  1610612761                 TOR
200   21501026 2016-03-18  2015-16  1610612742                 DAL
201   21501026 2016-03-18  2015-16  1610612742                 DAL
202   21501035 2016-03-19  2015-16  1610612746                 LAC
203   21501035 2016-03-19  2015-16  1610612746                 LAC
204   21501063 2016-03-23  2015-16  1610612759                 SAS
205   21501063 2016-03-23  2015-16  1610612759                 SAS
206   21501068 2016-03-24  2015-16  1610612754                 IND
207   21501068 2016-03-24  2015-16  1610612754                 IND
208   21501117 2016-03-30  2015-16  1610612752                 NYK
209   21501117 2016-03-30  2015-16  1610612752                 NYK
210   21600019 2016-10-28  2016-17  1610612754                 IND
211   21600019 2016-10-28  2016-17  1610612754                 IND
212   21600027 2016-10-29  2016-17  1610612766                 CHA
213   21600027 2016-10-29  2016-17  1610612766                 CHA
214   21600031 2016-10-29  2016-17  1610612751                 BKN
215   21600031 2016-10-29  2016-17  1610612751                 BKN
216   21600057 2016-11-02  2016-17  1610612751                 BKN
217   21600057 2016-11-02  2016-17  1610612751                 BKN
218   21600060 2016-11-02  2016-17  1610612740                 NOP
219   21600060 2016-11-02  2016-17  1610612740                 NOP
220   21600060 2016-11-02  2016-17  1610612763                 MEM
221   21600060 2016-11-02  2016-17  1610612763                 MEM
222   21600061 2016-11-02  2016-17  1610612738                 BOS
223   21600061 2016-11-02  2016-17  1610612738                 BOS
224   21600062 2016-11-02  2016-17  1610612742                 DAL
225   21600062 2016-11-02  2016-17  1610612742                 DAL
226   21600076 2016-11-04  2016-17  1610612742                 DAL
227   21600076 2016-11-04  2016-17  1610612742                 DAL
228   21600107 2016-11-09  2016-17  1610612764                 WAS
229   21600107 2016-11-09  2016-17  1610612764                 WAS
230   21600131 2016-11-12  2016-17  1610612752                 NYK
231   21600131 2016-11-12  2016-17  1610612752                 NYK
232   21600133 2016-11-12  2016-17  1610612741                 CHI
233   21600133 2016-11-12  2016-17  1610612741                 CHI
234   21600176 2016-11-18  2016-17  1610612756                 PHX
235   21600176 2016-11-18  2016-17  1610612756                 PHX
236   21600176 2016-11-18  2016-17  1610612754                 IND
237   21600176 2016-11-18  2016-17  1610612754                 IND
238   21600178 2016-11-18  2016-17  1610612760                 OKC
239   21600178 2016-11-18  2016-17  1610612760                 OKC
240   21600271 2016-11-30  2016-17  1610612752                 NYK
241   21600271 2016-11-30  2016-17  1610612752                 NYK
242   21600282 2016-12-02  2016-17  1610612755                 PHI
243   21600282 2016-12-02  2016-17  1610612755                 PHI
244   21600305 2016-12-05  2016-17  1610612739                 CLE
245   21600305 2016-12-05  2016-17  1610612739                 CLE
246   21600323 2016-12-07  2016-17  1610612743                 DEN
247   21600323 2016-12-07  2016-17  1610612743                 DEN
248   21600324 2016-12-07  2016-17  1610612748                 MIA
249   21600324 2016-12-07  2016-17  1610612748                 MIA
250   21600365 2016-12-12  2016-17  1610612743                 DEN
251   21600365 2016-12-12  2016-17  1610612743                 DEN
252   21600430 2016-12-21  2016-17  1610612737                 ATL
253   21600430 2016-12-21  2016-17  1610612737                 ATL
254   21600476 2016-12-28  2016-17  1610612764                 WAS
255   21600476 2016-12-28  2016-17  1610612764                 WAS
256   21600490 2016-12-29  2016-17  1610612761                 TOR
257   21600490 2016-12-29  2016-17  1610612761                 TOR
258   21600509 2017-01-01  2016-17  1610612765                 DET
259   21600509 2017-01-01  2016-17  1610612765                 DET
260   21600520 2017-01-02  2016-17  1610612744                 GSW
261   21600520 2017-01-02  2016-17  1610612744                 GSW
262   21600607 2017-01-15  2016-17  1610612737                 ATL
263   21600607 2017-01-15  2016-17  1610612737                 ATL
264   21600617 2017-01-16  2016-17  1610612743                 DEN
265   21600617 2017-01-16  2016-17  1610612743                 DEN
266   21600631 2017-01-18  2016-17  1610612753                 ORL
267   21600631 2017-01-18  2016-17  1610612753                 ORL
268   21600634 2017-01-18  2016-17  1610612744                 GSW
269   21600634 2017-01-18  2016-17  1610612744                 GSW
270   21600635 2017-01-18  2016-17  1610612758                 SAC
271   21600635 2017-01-18  2016-17  1610612758                 SAC
272   21600641 2017-01-20  2016-17  1610612755                 PHI
273   21600641 2017-01-20  2016-17  1610612755                 PHI
274   21600648 2017-01-20  2016-17  1610612742                 DAL
275   21600648 2017-01-20  2016-17  1610612742                 DAL
276   21600663 2017-01-22  2016-17  1610612756                 PHX
277   21600663 2017-01-22  2016-17  1610612756                 PHX
278   21600663 2017-01-22  2016-17  1610612761                 TOR
279   21600663 2017-01-22  2016-17  1610612761                 TOR
280   21600688 2017-01-25  2016-17  1610612742                 DAL
281   21600688 2017-01-25  2016-17  1610612742                 DAL
282   21600690 2017-01-26  2016-17  1610612760                 OKC
283   21600690 2017-01-26  2016-17  1610612760                 OKC
284   21600738 2017-02-01  2016-17  1610612762                 UTA
285   21600738 2017-02-01  2016-17  1610612762                 UTA
286   21600748 2017-02-03  2016-17  1610612750                 MIN
287   21600748 2017-02-03  2016-17  1610612750                 MIN
288   21600781 2017-02-07  2016-17  1610612757                 POR
289   21600781 2017-02-07  2016-17  1610612757                 POR
290   21600785 2017-02-08  2016-17  1610612743                 DEN
291   21600785 2017-02-08  2016-17  1610612743                 DEN
292   21600787 2017-02-08  2016-17  1610612749                 MIL
293   21600787 2017-02-08  2016-17  1610612749                 MIL
294   21600834 2017-02-15  2016-17  1610612759                 SAS
295   21600834 2017-02-15  2016-17  1610612759                 SAS
296   21600834 2017-02-15  2016-17  1610612753                 ORL

In [13]:
df_merge._merge

0      both
1      both
2      both
3      both
4      both
5      both
6      both
7      both
8      both
9      both
10     both
11     both
12     both
13     both
14     both
15     both
16     both
17     both
18     both
19     both
20     both
21     both
22     both
23     both
24     both
25     both
26     both
27     both
28     both
29     both
30     both
31     both
32     both
33     both
34     both
35     both
36     both
37     both
38     both
39     both
40     both
41     both
42     both
43     both
44     both
45     both
46     both
47     both
48     both
49     both
50     both
51     both
52     both
53     both
54     both
55     both
56     both
57     both
58     both
59     both
60     both
61     both
62     both
63     both
64     both
65     both
66     both
67     both
68     both
69     both
70     both
71     both
72     both
73     both
74     both
75     both
76     both
77     both
78     both
79     both
80     both
81     both
82     both
83     both
84     both
85     both
86     both
87     both
88     both
89     both
90     both
91     both
92     both
93     both
94     both
95     both
96     both
97     both
98     both
99     both
100    both
101    both
102    both
103    both
104    both
105    both
106    both
107    both
108    both
109    both
110    both
111    both
112    both
113    both
114    both
115    both
116    both
117    both
118    both
119    both
120    both
121    both
122    both
123    both
124    both
125    both
126    both
127    both
128    both
129    both
130    both
131    both
132    both
133    both
134    both
135    both
136    both
137    both
138    both
139    both
140    both
141    both
142    both
143    both
144    both
145    both
146    both
147    both
148    both
149    both
150    both
151    both
152    both
153    both
154    both
155    both
156    both
157    both
158    both
159    both
160    both
161    both
162    both
163    both
164    both
165    both
166    both
167    both
168    both
169    both
170    both
171    both
172    both
173    both
174    both
175    both
176    both
177    both
178    both
179    both
180    both
181    both
182    both
183    both
184    both
185    both
186    both
187    both
188    both
189    both
190    both
191    both
192    both
193    both
194    both
195    both
196    both
197    both
198    both
199    both
200    both
201    both
202    both
203    both
204    both
205    both
206    both
207    both
208    both
209    both
210    both
211    both
212    both
213    both
214    both
215    both
216    both
217    both
218    both
219    both
220    both
221    both
222    both
223    both
224    both
225    both
226    both
227    both
228    both
229    both
230    both
231    both
232    both
233    both
234    both
235    both
236    both
237    both
238    both
239    both
240    both
241    both
242    both
243    both
244    both
245    both
246    both
247    both
248    both
249    both
250    both
251    both
252    both
253    both
254    both
255    both
256    both
257    both
258    both
259    both
260    both
261    both
262    both
263    both
264    both
265    both
266    both
267    both
268    both
269    both
270    both
271    both
272    both
273    both
274    both
275    both
276    both
277    both
278    both
279    both
280    both
281    both
282    both
283    both
284    both
285    both
286    both
287    both
288    both
289    both
290    both
291    both
292    both
293    both
294    both
295    both
296    both
297    both
298    both
299    both
300    both
301    both
302    both
303    both
304    both
305    both
306    both
307    both
308    both
309    both
310    both
311    both
312    both
313    both
314    both
315    both
316    both
317    both
318    both
319    both
320    both
321    both
322    both
323    both
324    both
325    both
326    both
327    both
328    both
329    both
330    both
331    both
332    both
333    both
334    both
335    both
336    both
337    both
338    both
339    both
340    both
341    both
342    both
343    both
344    both
345    both
346    both
347    both
348    both
349    both
350    both
351    both
352    both
353    both
354    both
355    both
356    both
357    both
358    both
359    both
360    both
361    both
362    both
363    both
364    both
365    both
366    both
367    both
368    both
369    both
370    both
371    both
372    both
373    both
374    both
375    both
376    both
377    both
378    both
379    both
380    both
381    both
382    both
383    both
384    both
385    both
386    both
387    both
388    both
389    both
390    both
391    both
392    both
393    both
394    both
395    both
396    both
397    both
398    both
399    both
400    both
401    both
402    both
403    both
404    both
405    both
406    both
407    both
408    both
409    both
410    both
411    both
412    both
413    both
414    both
415    both
416    both
417    both
Name: _merge, dtype: category
Categories (3, object): ['left_only', 'right_only', 'both']

In [14]:
#pd.merge(df_5bsa1018.rename(columns={'GAME_ID':'game_id'}), df_3gigdti1018[['game_id', 'game_date', 'season']].drop_duplicates(), on=['game_id'] , how='inner')

In [15]:
df_5bsa1018 = df_5bsa1018[df_5bsa1018.MIN == 0]
print(df_5bsa1018[df_5bsa1018.MIN == 0].shape)
p(df_5bsa1018[df_5bsa1018.MIN == 0])

(89096, 33)
(89096, 33)

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
9,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
10,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,436.0,Juwan Howard,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
11,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,2048.0,Jamaal Magloire,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
21,21000001,2010-10-26,2010-11,1610612738,BOS,Boston,201623.0,Semih Erden,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
22,21000001,2010-10-26,2010-11,1610612738,BOS,Boston,101144.0,Von Wafer,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
520269,41700403,2018-06-06,2017-18,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
520270,41700403,2018-06-06,2017-18,1610612739,CLE,Cleveland,1626224.0,Cedi Osman,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
520271,41700403,2018-06-06,2017-18,1610612739,CLE,Cleveland,1627790.0,Ante Zizic,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
520297,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN
520323,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN

In [16]:
df_5bsa1018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 89096 entries, 9 to 520323
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            89096 non-null  int64
 1   game_date          89096 non-null  datetime64[ns]
 2   season             89096 non-null  object
 3   team_id            89096 non-null  int64
 4   TEAM_ABBREVIATION  89094 non-null  object
 5   TEAM_CITY          89094 non-null  object
 6   PLAYER_ID          89094 non-null  float64
 7   PLAYER_NAME        89096 non-null  object
 8   START_POSITION     0 non-null      object
 9   COMMENT            89008 non-null  object
 10  MIN                89096 non-null  float64
 11  E_OFF_RATING       86 non-null     float64
 12  OFF_RATING         89094 non-null  float64
 13  E_DEF_RATING       86 non-null     float64
 14  DEF_RATING         89094 non-null  float64
 15  E_NET_RATING       86 non-null     float64
 16  NET_RATING         89094 non-null  float64
 17  AST_PCT            86 non-null     float64
 18  AST_TOV            86 non-null     float64
 19  AST_RATIO          86 non-null     float64
 20  OREB_PCT           89094 non-null  float64
 21  DREB_PCT           89094 non-null  float64
 22  REB_PCT            89094 non-null  float64
 23  TM_TOV_PCT         86 non-null     float64
 24  EFG_PCT            86 non-null     float64
 25  TS_PCT             86 non-null     float64
 26  USG_PCT            89094 non-null  float64
 27  E_USG_PCT          89094 non-null  float64
 28  E_PACE             86 non-null     float64
 29  PACE               86 non-null     float64
 30  PACE_PER40         86 non-null     float64
 31  POSS               89094 non-null  float64
 32  PIE                86 non-null     float64
dtypes: datetime64[ns](1), float64(24), int64(2), object(6)
memory usage: 23.1+ MB

In [17]:
df_5bsa1018[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']] = df_5bsa1018[['E_OFF_RATING', 'OFF_RATING',
       'E_DEF_RATING', 'DEF_RATING', 'E_NET_RATING', 'NET_RATING', 'AST_PCT',
       'AST_TOV', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE']].fillna(0)

In [18]:
print(df_5bsa1018.shape)
p(df_5bsa1018)

(89096, 33)
(89096, 33)

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
9,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,436.0,Juwan Howard,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,21000001,2010-10-26,2010-11,1610612748,MIA,Miami,2048.0,Jamaal Magloire,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,21000001,2010-10-26,2010-11,1610612738,BOS,Boston,201623.0,Semih Erden,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,21000001,2010-10-26,2010-11,1610612738,BOS,Boston,101144.0,Von Wafer,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
520269,41700403,2018-06-06,2017-18,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
520270,41700403,2018-06-06,2017-18,1610612739,CLE,Cleveland,1626224.0,Cedi Osman,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
520271,41700403,2018-06-06,2017-18,1610612739,CLE,Cleveland,1627790.0,Ante Zizic,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
520297,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
520323,41700404,2018-06-08,2017-18,1610612739,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df_5bsa1018.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 89096 entries, 9 to 520323
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            89096 non-null  int64
 1   game_date          89096 non-null  datetime64[ns]
 2   season             89096 non-null  object
 3   team_id            89096 non-null  int64
 4   TEAM_ABBREVIATION  89094 non-null  object
 5   TEAM_CITY          89094 non-null  object
 6   PLAYER_ID          89094 non-null  float64
 7   PLAYER_NAME        89096 non-null  object
 8   START_POSITION     0 non-null      object
 9   COMMENT            89008 non-null  object
 10  MIN                89096 non-null  float64
 11  E_OFF_RATING       89096 non-null  float64
 12  OFF_RATING         89096 non-null  float64
 13  E_DEF_RATING       89096 non-null  float64
 14  DEF_RATING         89096 non-null  float64
 15  E_NET_RATING       89096 non-null  float64
 16  NET_RATING         89096 non-null  float64
 17  AST_PCT            89096 non-null  float64
 18  AST_TOV            89096 non-null  float64
 19  AST_RATIO          89096 non-null  float64
 20  OREB_PCT           89096 non-null  float64
 21  DREB_PCT           89096 non-null  float64
 22  REB_PCT            89096 non-null  float64
 23  TM_TOV_PCT         89096 non-null  float64
 24  EFG_PCT            89096 non-null  float64
 25  TS_PCT             89096 non-null  float64
 26  USG_PCT            89096 non-null  float64
 27  E_USG_PCT          89096 non-null  float64
 28  E_PACE             89096 non-null  float64
 29  PACE               89096 non-null  float64
 30  PACE_PER40         89096 non-null  float64
 31  POSS               89096 non-null  float64
 32  PIE                89096 non-null  float64
dtypes: datetime64[ns](1), float64(24), int64(2), object(6)
memory usage: 23.1+ MB

In [20]:
df_5bsa1018.reset_index(drop=True, inplace=True)

In [21]:
df_5bsa1018_pip = df_5bsa1018[['PLAYER_ID','PLAYER_NAME']].drop_duplicates()
print(df_5bsa1018_pip.shape)
p(df_5bsa1018_pip)

(1060, 2)
(1060, 2)

       PLAYER_ID      PLAYER_NAME
0       201596.0   Mario Chalmers
1          436.0     Juwan Howard
2         2048.0  Jamaal Magloire
3       201623.0      Semih Erden
4       101144.0        Von Wafer
82554  1627821.0   James Webb III
82854  1628369.0     Jayson Tatum
83339     2420.0     Nenad Krstic
84831   101204.0     Dwayne Jones
88576  1628935.0    Aaron Jackson

In [22]:
print(df_5bsa1018_pip.value_counts('PLAYER_ID').shape)
p(df_5bsa1018_pip.value_counts('PLAYER_ID'))

(1059,)
(1059,)

PLAYER_ID
1628935.0    1
201588.0     1
201611.0     1
201609.0     1
201607.0     1
203506.0     1
203505.0     1
203504.0     1
203503.0     1
255.0        1
dtype: int64

In [23]:
print(df_5bsa1018_pip.value_counts('PLAYER_NAME').shape)
p(df_5bsa1018_pip.value_counts('PLAYER_NAME'))

(1056,)
(1056,)

PLAYER_NAME
Mike James            2
Chris Johnson         2
Tony Mitchell         2
Chris Wright          2
Zydrunas Ilgauskas    1
Markieff Morris       1
Markelle Fultz        1
Markel Brown          1
Mario West            1
                      1
dtype: int64

In [24]:
playerl = list(df_5bsa1018_pip.value_counts('PLAYER_NAME')[df_5bsa1018_pip.value_counts('PLAYER_NAME') > 1].reset_index().PLAYER_NAME)
playerl

['Mike James', 'Chris Johnson', 'Tony Mitchell', 'Chris Wright']

In [25]:
playerl[0]

'Mike James'

In [26]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[0])]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
10014,21100162,2012-01-13,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10017,21100162,2012-01-13,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10111,21100174,2012-01-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10118,21100174,2012-01-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10202,21100185,2012-01-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10206,21100185,2012-01-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10360,21100198,2012-01-17,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10363,21100198,2012-01-17,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10791,21100244,2012-01-23,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10796,21100244,2012-01-23,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10946,21100261,2012-01-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10952,21100261,2012-01-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11096,21100277,2012-01-27,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11101,21100277,2012-01-27,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12428,21100423,2012-02-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12435,21100423,2012-02-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14433,21100629,2012-03-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14439,21100629,2012-03-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14605,21100647,2012-03-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14609,21100647,2012-03-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14878,21100673,2012-03-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14881,21100673,2012-03-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14951,21100683,2012-03-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14958,21100683,2012-03-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16253,21100813,2012-04-05,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16258,21100813,2012-04-05,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16478,21100835,2012-04-08,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16484,21100835,2012-04-08,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16818,21100870,2012-04-12,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16824,21100870,2012-04-12,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17082,21100897,2012-04-15,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17087,21100897,2012-04-15,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17192,21100907,2012-04-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17198,21100907,2012-04-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17447,21100934,2012-04-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17453,21100934,2012-04-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17577,21100946,2012-04-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17582,21100946,2012-04-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17853,21100973,2012-04-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17858,21100973,2012-04-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23840,21200668,2013-01-29,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23844,21200668,2013-01-29,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24442,21200730,2013-02-06,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24447,21200730,2013-02-06,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29230,21300002,2013-10-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29237,21300002,2013-10-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29401,21300018,2013-10-31,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29408,21300018,2013-10-31,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29522,21300034,2013-11-02,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29527,21300034,2013-11-02,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30142,21300102,2013-11-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30147,21300102,2013-11-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30348,21300126,2013-11-15,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30351,21300126,2013-11-15,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30491,21300140,2013-11-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30494,21300140,2013-11-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30582,21300151,2013-11-18,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30590,21300151,2013-11-18,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30814,21300175,2013-11-21,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30817,21300175,2013-11-21,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30912,21300185,2013-11-22,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30919,21300185,2013-11-22,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31222,21300220,2013-11-27,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31223,21300220,2013-11-27,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31767,21300279,2013-12-05,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31771,21300279,2013-12-05,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31861,21300292,2013-12-07,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31868,21300292,2013-12-07,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32080,21300316,2013-12-10,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32088,21300316,2013-12-10,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32174,21300324,2013-12-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32181,21300324,2013-12-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32317,21300337,2013-12-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32324,21300337,2013-12-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35600,21300683,2014-01-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35604,21300683,2014-01-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40218,21301181,2014-04-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40226,21301181,2014-04-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40390,21301197,2014-04-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40395,21301197,2014-04-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40506,21301208,2014-04-14,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40511,21301208,2014-04-14,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40665,21301223,2014-04-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40672,21301223,2014-04-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76582,21700434,2017-12-16,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76588,21700434,2017-12-16,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76854,21700469,2017-12-21,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76857,21700469,2017-12-21,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78166,21700635,2018-01-14,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78174,21700635,2018-01-14,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78286,21700650,2018-01-16,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78292,21700650,2018-01-16,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78322,21700654,2018-01-17,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78328,21700654,2018-01-17,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78521,21700677,2018-01-20,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78529,21700677,2018-01-20,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78655,21700692,2018-01-22,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78662,21700692,2018-01-22,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78727,21700701,2018-01-24,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78732,21700701,2018-01-24,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78872,21700720,2018-01-26,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<font color='red'> how to deal with changing PLAYER_ID?? this just from a team change??? </font> -no, these are different players

In [27]:
df_5bsa1018[df_5bsa1018.PLAYER_ID == 1628455.0]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
76582,21700434,2017-12-16,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76588,21700434,2017-12-16,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76854,21700469,2017-12-21,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76857,21700469,2017-12-21,2017-18,1610612756,PHX,Phoenix,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78166,21700635,2018-01-14,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78174,21700635,2018-01-14,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78286,21700650,2018-01-16,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78292,21700650,2018-01-16,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78322,21700654,2018-01-17,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78328,21700654,2018-01-17,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78521,21700677,2018-01-20,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78529,21700677,2018-01-20,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78655,21700692,2018-01-22,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78662,21700692,2018-01-22,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78727,21700701,2018-01-24,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78732,21700701,2018-01-24,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78872,21700720,2018-01-26,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78877,21700720,2018-01-26,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78957,21700733,2018-01-28,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78963,21700733,2018-01-28,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79582,21700818,2018-02-09,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,NWT - Personal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79583,21700818,2018-02-09,2017-18,1610612740,NOP,New Orleans,1628455.0,Mike James,NaN,NWT - Personal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
df_5bsa1018[df_5bsa1018.PLAYER_ID == 2229.0]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
10014,21100162,2012-01-13,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10017,21100162,2012-01-13,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10111,21100174,2012-01-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10118,21100174,2012-01-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10202,21100185,2012-01-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10206,21100185,2012-01-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10360,21100198,2012-01-17,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10363,21100198,2012-01-17,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10791,21100244,2012-01-23,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10796,21100244,2012-01-23,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10946,21100261,2012-01-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10952,21100261,2012-01-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11096,21100277,2012-01-27,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11101,21100277,2012-01-27,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12428,21100423,2012-02-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12435,21100423,2012-02-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14433,21100629,2012-03-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14439,21100629,2012-03-14,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14605,21100647,2012-03-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14609,21100647,2012-03-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14878,21100673,2012-03-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14881,21100673,2012-03-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14951,21100683,2012-03-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14958,21100683,2012-03-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16253,21100813,2012-04-05,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16258,21100813,2012-04-05,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16478,21100835,2012-04-08,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16484,21100835,2012-04-08,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16818,21100870,2012-04-12,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16824,21100870,2012-04-12,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17082,21100897,2012-04-15,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17087,21100897,2012-04-15,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17192,21100907,2012-04-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17198,21100907,2012-04-16,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17447,21100934,2012-04-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17453,21100934,2012-04-19,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17577,21100946,2012-04-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17582,21100946,2012-04-21,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17853,21100973,2012-04-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17858,21100973,2012-04-25,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23840,21200668,2013-01-29,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23844,21200668,2013-01-29,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24442,21200730,2013-02-06,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24447,21200730,2013-02-06,2012-13,1610612742,DAL,Dallas,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29230,21300002,2013-10-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29237,21300002,2013-10-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29401,21300018,2013-10-31,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29408,21300018,2013-10-31,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29522,21300034,2013-11-02,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29527,21300034,2013-11-02,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30142,21300102,2013-11-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30147,21300102,2013-11-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30348,21300126,2013-11-15,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30351,21300126,2013-11-15,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30491,21300140,2013-11-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30494,21300140,2013-11-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30582,21300151,2013-11-18,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30590,21300151,2013-11-18,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30814,21300175,2013-11-21,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30817,21300175,2013-11-21,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30912,21300185,2013-11-22,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30919,21300185,2013-11-22,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31222,21300220,2013-11-27,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31223,21300220,2013-11-27,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31767,21300279,2013-12-05,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31771,21300279,2013-12-05,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31861,21300292,2013-12-07,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31868,21300292,2013-12-07,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DND - Right Knee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32080,21300316,2013-12-10,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32088,21300316,2013-12-10,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32174,21300324,2013-12-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32181,21300324,2013-12-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32317,21300337,2013-12-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32324,21300337,2013-12-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35600,21300683,2014-01-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35604,21300683,2014-01-29,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40218,21301181,2014-04-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40226,21301181,2014-04-11,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40390,21301197,2014-04-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40395,21301197,2014-04-13,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40506,21301208,2014-04-14,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40511,21301208,2014-04-14,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40665,21301223,2014-04-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40672,21301223,2014-04-16,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83606,41100101,2012-04-28,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83612,41100101,2012-04-28,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83619,41100102,2012-05-01,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83626,41100102,2012-05-01,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83629,41100103,2012-05-04,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83636,41100103,2012-05-04,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83642,41100104,2012-05-06,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83649,41100104,2012-05-06,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83661,41100105,2012-05-08,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83669,41100105,2012-05-08,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83672,41100106,2012-05-10,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83680,41100106,2012-05-10,2011-12,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85511,41300131,2014-04-20,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85517,41300131,2014-04-20,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85524,41300132,2014-04-22,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85531,41300132,2014-04-22,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85535,41300133,2014-04-25,2013-14,1610612741,CHI,Chicago,2229.0,Mike James,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
#two different players
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1])]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
4519,21000661,2011-01-24,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4525,21000661,2011-01-24,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4651,21000680,2011-01-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4656,21000680,2011-01-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6336,21000905,2011-03-02,2010-11,1610612738,BOS,Boston,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6340,21000905,2011-03-02,2010-11,1610612738,BOS,Boston,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6974,21001002,2011-03-15,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6979,21001002,2011-03-15,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7184,21001034,2011-03-19,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7189,21001034,2011-03-19,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7256,21001043,2011-03-20,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7261,21001043,2011-03-20,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7497,21001078,2011-03-25,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7502,21001078,2011-03-25,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7607,21001092,2011-03-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7612,21001092,2011-03-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7676,21001099,2011-03-28,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7681,21001099,2011-03-28,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7794,21001114,2011-03-30,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7798,21001114,2011-03-30,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7880,21001130,2011-04-01,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7886,21001130,2011-04-01,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8934,21100037,2011-12-29,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8942,21100037,2011-12-29,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9143,21100065,2012-01-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9151,21100065,2012-01-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9273,21100079,2012-01-03,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9280,21100079,2012-01-03,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9403,21100097,2012-01-05,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9409,21100097,2012-01-05,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9790,21100140,2012-01-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9797,21100140,2012-01-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9918,21100152,2012-01-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9925,21100152,2012-01-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10130,21100176,2012-01-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10138,21100176,2012-01-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10260,21100190,2012-01-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10267,21100190,2012-01-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10456,21100208,2012-01-18,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10463,21100208,2012-01-18,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10543,21100216,2012-01-20,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10548,21100216,2012-01-20,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11011,21100269,2012-01-25,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11016,21100269,2012-01-25,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11299,21100305,2012-01-30,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11305,21100305,2012-01-30,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11504,21100329,2012-02-02,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11512,21100329,2012-02-02,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11856,21100366,2012-02-06,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11864,21100366,2012-02-06,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12032,21100383,2012-02-08,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12039,21100383,2012-02-08,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12179,21100397,2012-02-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12187,21100397,2012-02-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12257,21100405,2012-02-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12264,21100405,2012-02-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12460,21100427,2012-02-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12465,21100427,2012-02-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12616,21100444,2012-02-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12624,21100444,2012-02-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13403,21100527,2012-03-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13410,21100527,2012-03-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14071,21100594,2012-03-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14078,21100594,2012-03-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15006,21100688,2012-03-21,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15011,21100688,2012-03-21,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16153,21100805,2012-04-04,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16160,21100805,2012-04-04,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16349,21100822,2012-04-06,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,NWT - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16351,21100822,2012-04-06,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,NWT - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16447,21100830,2012-04-07,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16451,21100830,2012-04-07,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16576,21100847,2012-04-09,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16583,21100847,2012-04-09,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23921,21200677,2013-01-30,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23926,21200677,2013-01-30,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24057,21200691,2013-02-01,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24062,21200691,2013-02-01,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24274,21200713,2013-02-04,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24280,21200713,2013-02-04,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24452,21200731,2013-02-06,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24457,21200731,2013-02-06,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24547,21200742,2013-02-08,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24551,21200742,2013-02-08,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24720,21200763,2013-02-11,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24726,21200763,2013-02-11,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24799,21200771,2013-02-12,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24805,21200771,2013-02-12,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25101,21200805,2013-02-20,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25105,21200805,2013-02-20,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25307,21200832,2013-02-24,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25310,21200832,2013-02-24,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25468,21200849,2013-02-26,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25472,21200849,2013-02-26,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26898,21201000,2013-03-18,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26903,21201000,2013-03-18,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27097,21201021,2013-03-21,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27102,21201021,2013-03-21,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1]) & (df_5bsa1018.PLAYER_ID == 202419.0)]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
4519,21000661,2011-01-24,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4525,21000661,2011-01-24,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4651,21000680,2011-01-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4656,21000680,2011-01-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6336,21000905,2011-03-02,2010-11,1610612738,BOS,Boston,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6340,21000905,2011-03-02,2010-11,1610612738,BOS,Boston,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6974,21001002,2011-03-15,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6979,21001002,2011-03-15,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7184,21001034,2011-03-19,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7189,21001034,2011-03-19,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7256,21001043,2011-03-20,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7261,21001043,2011-03-20,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7497,21001078,2011-03-25,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7502,21001078,2011-03-25,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7607,21001092,2011-03-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7612,21001092,2011-03-27,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7676,21001099,2011-03-28,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7681,21001099,2011-03-28,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7794,21001114,2011-03-30,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7798,21001114,2011-03-30,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7880,21001130,2011-04-01,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7886,21001130,2011-04-01,2010-11,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8934,21100037,2011-12-29,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8942,21100037,2011-12-29,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9143,21100065,2012-01-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9151,21100065,2012-01-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9273,21100079,2012-01-03,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9280,21100079,2012-01-03,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9403,21100097,2012-01-05,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9409,21100097,2012-01-05,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9790,21100140,2012-01-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9797,21100140,2012-01-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9918,21100152,2012-01-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9925,21100152,2012-01-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10130,21100176,2012-01-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10138,21100176,2012-01-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10260,21100190,2012-01-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10267,21100190,2012-01-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10456,21100208,2012-01-18,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10463,21100208,2012-01-18,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10543,21100216,2012-01-20,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10548,21100216,2012-01-20,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11011,21100269,2012-01-25,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11016,21100269,2012-01-25,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11299,21100305,2012-01-30,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11305,21100305,2012-01-30,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11504,21100329,2012-02-02,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11512,21100329,2012-02-02,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11856,21100366,2012-02-06,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11864,21100366,2012-02-06,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12032,21100383,2012-02-08,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12039,21100383,2012-02-08,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12179,21100397,2012-02-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12187,21100397,2012-02-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12257,21100405,2012-02-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12264,21100405,2012-02-11,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12460,21100427,2012-02-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12465,21100427,2012-02-14,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12616,21100444,2012-02-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12624,21100444,2012-02-16,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13403,21100527,2012-03-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13410,21100527,2012-03-01,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14071,21100594,2012-03-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14078,21100594,2012-03-10,2011-12,1610612757,POR,Portland,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15006,21100688,2012-03-21,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15011,21100688,2012-03-21,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16153,21100805,2012-04-04,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16160,21100805,2012-04-04,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16349,21100822,2012-04-06,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,NWT - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16351,21100822,2012-04-06,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,NWT - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16447,21100830,2012-04-07,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16451,21100830,2012-04-07,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16576,21100847,2012-04-09,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16583,21100847,2012-04-09,2011-12,1610612740,NOH,New Orleans,202419.0,Chris Johnson,NaN,DND - Concussion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23921,21200677,2013-01-30,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23926,21200677,2013-01-30,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24274,21200713,2013-02-04,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24280,21200713,2013-02-04,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24452,21200731,2013-02-06,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24457,21200731,2013-02-06,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24720,21200763,2013-02-11,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24726,21200763,2013-02-11,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25101,21200805,2013-02-20,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25105,21200805,2013-02-20,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25307,21200832,2013-02-24,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25310,21200832,2013-02-24,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25468,21200849,2013-02-26,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25472,21200849,2013-02-26,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26898,21201000,2013-03-18,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26903,21201000,2013-03-18,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27097,21201021,2013-03-21,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27102,21201021,2013-03-21,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27542,21201066,2013-03-27,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27550,21201066,2013-03-27,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27694,21201081,2013-03-29,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27700,21201081,2013-03-29,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27953,21201105,2013-04-01,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27959,21201105,2013-04-01,2012-13,1610612750,MIN,Minnesota,202419.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1]) & (df_5bsa1018.PLAYER_ID == 203187.0)]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
24057,21200691,2013-02-01,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24062,21200691,2013-02-01,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24547,21200742,2013-02-08,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24551,21200742,2013-02-08,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24799,21200771,2013-02-12,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24805,21200771,2013-02-12,2012-13,1610612763,MEM,Memphis,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34654,21300586,2014-01-17,2013-14,1610612738,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34661,21300586,2014-01-17,2013-14,1610612738,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34806,21300602,2014-01-19,2013-14,1610612738,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34815,21300602,2014-01-19,2013-14,1610612738,BOS,Boston,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46679,21400690,2015-01-28,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46686,21400690,2015-01-28,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46802,21400703,2015-01-30,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46808,21400703,2015-01-30,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47022,21400729,2015-02-03,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47029,21400729,2015-02-03,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49679,21401022,2015-03-20,2014-15,1610612749,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49685,21401022,2015-03-20,2014-15,1610612749,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49977,21401055,2015-03-24,2014-15,1610612749,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49984,21401055,2015-03-24,2014-15,1610612749,MIL,Milwaukee,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51149,21401185,2015-04-10,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51153,21401185,2015-04-10,2014-15,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51681,21500007,2015-10-28,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51686,21500007,2015-10-28,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52306,21500091,2015-11-07,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52311,21500091,2015-11-07,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52590,21500124,2015-11-12,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52596,21500124,2015-11-12,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53751,21500259,2015-11-30,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53755,21500259,2015-11-30,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54273,21500318,2015-12-08,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54281,21500318,2015-12-08,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54496,21500341,2015-12-11,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54501,21500341,2015-12-11,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54617,21500356,2015-12-13,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54623,21500356,2015-12-13,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54918,21500395,2015-12-18,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54922,21500395,2015-12-18,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55252,21500434,2015-12-23,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55257,21500434,2015-12-23,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61232,21501119,2016-03-30,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61236,21501119,2016-03-30,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61903,21501187,2016-04-08,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61910,21501187,2016-04-08,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62098,21501210,2016-04-11,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62103,21501210,2016-04-11,2015-16,1610612762,UTA,Utah,203187.0,Chris Johnson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[1])][['PLAYER_ID', 'PLAYER_NAME']].value_counts('PLAYER_ID')

PLAYER_ID
202419.0    110
203187.0     46
dtype: int64

In [33]:
#different players
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[2])]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
29472,21300026,2013-11-01,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29479,21300026,2013-11-01,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29594,21300041,2013-11-03,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29600,21300041,2013-11-03,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29703,21300053,2013-11-05,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29709,21300053,2013-11-05,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29926,21300078,2013-11-08,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29931,21300078,2013-11-08,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30175,21300105,2013-11-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30183,21300105,2013-11-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30430,21300135,2013-11-15,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30435,21300135,2013-11-15,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30648,21300157,2013-11-19,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30656,21300157,2013-11-19,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30713,21300166,2013-11-20,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30719,21300166,2013-11-20,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30866,21300180,2013-11-22,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30872,21300180,2013-11-22,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31324,21300233,2013-11-29,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31329,21300233,2013-11-29,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31621,21300264,2013-12-03,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31628,21300264,2013-12-03,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31703,21300272,2013-12-04,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31708,21300272,2013-12-04,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31857,21300292,2013-12-07,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31864,21300292,2013-12-07,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32161,21300323,2013-12-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32167,21300323,2013-12-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32291,21300334,2013-12-13,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32298,21300334,2013-12-13,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32495,21300356,2013-12-16,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32501,21300356,2013-12-16,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32665,21300373,2013-12-18,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32670,21300373,2013-12-18,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32812,21300386,2013-12-20,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32818,21300386,2013-12-20,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34745,21300595,2014-01-18,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34754,21300595,2014-01-18,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34858,21300607,2014-01-20,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34864,21300607,2014-01-20,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35071,21300628,2014-01-22,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35080,21300628,2014-01-22,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35176,21300639,2014-01-24,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35184,21300639,2014-01-24,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35525,21300677,2014-04-08,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35531,21300677,2014-04-08,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36698,21300795,2014-02-18,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36706,21300795,2014-02-18,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37459,21300876,2014-03-01,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37466,21300876,2014-03-01,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37623,21300892,2014-03-03,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37629,21300892,2014-03-03,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37755,21300909,2014-03-05,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37763,21300909,2014-03-05,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37840,21300922,2014-03-07,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37844,21300922,2014-03-07,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37849,21300923,2014-03-07,2013-14,1610612749,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37854,21300923,2014-03-07,2013-14,1610612749,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37955,21300937,2014-03-09,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37961,21300937,2014-03-09,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38045,21300947,2014-03-10,2013-14,1610612749,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38051,21300947,2014-03-10,2013-14,1610612749,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38085,21300951,2014-03-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38091,21300951,2014-03-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38231,21300969,2014-03-13,2013-14,1610612749,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38236,21300969,2014-03-13,2013-14,1610612749,MIL,Milwaukee,203183.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38370,21300984,2014-03-15,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38376,21300984,2014-03-15,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38650,21301015,2014-03-19,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38657,21301015,2014-03-19,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38753,21301029,2014-03-21,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38760,21301029,2014-03-21,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38835,21301039,2014-03-22,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38843,21301039,2014-03-22,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39089,21301064,2014-03-26,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39097,21301064,2014-03-26,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39442,21301104,2014-03-31,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39450,21301104,2014-03-31,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39543,21301114,2014-04-02,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39549,21301114,2014-04-02,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39731,21301134,2014-04-04,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39735,21301134,2014-04-04,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39854,21301146,2014-04-05,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39860,21301146,2014-04-05,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40213,21301181,2014-04-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40221,21301181,2014-04-11,2013-14,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40845,21400011,2014-10-29,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40849,21400011,2014-10-29,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40888,21400017,2014-10-30,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40894,21400017,2014-10-30,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41038,21400033,2014-11-01,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41045,21400033,2014-11-01,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41291,21400061,2014-11-05,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41295,21400061,2014-11-05,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41408,21400076,2014-11-07,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41413,21400076,2014-11-07,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41559,21400091,2014-11-09,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41567,21400091,2014-11-09,2014-15,1610612765,DET,Detroit,203502.0,Tony Mitchell,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[2]) & (df_5bsa1018.PLAYER_ID == 203502.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID    PLAYER_NAME TEAM_CITY
29472   203502.0  Tony Mitchell   Detroit
29479   203502.0  Tony Mitchell   Detroit
29594   203502.0  Tony Mitchell   Detroit
29600   203502.0  Tony Mitchell   Detroit
29703   203502.0  Tony Mitchell   Detroit
29709   203502.0  Tony Mitchell   Detroit
29926   203502.0  Tony Mitchell   Detroit
29931   203502.0  Tony Mitchell   Detroit
30175   203502.0  Tony Mitchell   Detroit
30183   203502.0  Tony Mitchell   Detroit
30430   203502.0  Tony Mitchell   Detroit
30435   203502.0  Tony Mitchell   Detroit
30648   203502.0  Tony Mitchell   Detroit
30656   203502.0  Tony Mitchell   Detroit
30713   203502.0  Tony Mitchell   Detroit
30719   203502.0  Tony Mitchell   Detroit
30866   203502.0  Tony Mitchell   Detroit
30872   203502.0  Tony Mitchell   Detroit
31324   203502.0  Tony Mitchell   Detroit
31329   203502.0  Tony Mitchell   Detroit
31621   203502.0  Tony Mitchell   Detroit
31628   203502.0  Tony Mitchell   Detroit
31703   203502.0  Tony Mitchell   Detroit
31708   203502.0  Tony Mitchell   Detroit
31857   203502.0  Tony Mitchell   Detroit
31864   203502.0  Tony Mitchell   Detroit
32161   203502.0  Tony Mitchell   Detroit
32167   203502.0  Tony Mitchell   Detroit
32291   203502.0  Tony Mitchell   Detroit
32298   203502.0  Tony Mitchell   Detroit
32495   203502.0  Tony Mitchell   Detroit
32501   203502.0  Tony Mitchell   Detroit
32665   203502.0  Tony Mitchell   Detroit
32670   203502.0  Tony Mitchell   Detroit
32812   203502.0  Tony Mitchell   Detroit
32818   203502.0  Tony Mitchell   Detroit
34745   203502.0  Tony Mitchell   Detroit
34754   203502.0  Tony Mitchell   Detroit
34858   203502.0  Tony Mitchell   Detroit
34864   203502.0  Tony Mitchell   Detroit
35071   203502.0  Tony Mitchell   Detroit
35080   203502.0  Tony Mitchell   Detroit
35176   203502.0  Tony Mitchell   Detroit
35184   203502.0  Tony Mitchell   Detroit
35525   203502.0  Tony Mitchell   Detroit
35531   203502.0  Tony Mitchell   Detroit
36698   203502.0  Tony Mitchell   Detroit
36706   203502.0  Tony Mitchell   Detroit
37459   203502.0  Tony Mitchell   Detroit
37466   203502.0  Tony Mitchell   Detroit
37623   203502.0  Tony Mitchell   Detroit
37629   203502.0  Tony Mitchell   Detroit
37755   203502.0  Tony Mitchell   Detroit
37763   203502.0  Tony Mitchell   Detroit
37840   203502.0  Tony Mitchell   Detroit
37844   203502.0  Tony Mitchell   Detroit
37955   203502.0  Tony Mitchell   Detroit
37961   203502.0  Tony Mitchell   Detroit
38085   203502.0  Tony Mitchell   Detroit
38091   203502.0  Tony Mitchell   Detroit
38370   203502.0  Tony Mitchell   Detroit
38376   203502.0  Tony Mitchell   Detroit
38650   203502.0  Tony Mitchell   Detroit
38657   203502.0  Tony Mitchell   Detroit
38753   203502.0  Tony Mitchell   Detroit
38760   203502.0  Tony Mitchell   Detroit
38835   203502.0  Tony Mitchell   Detroit
38843   203502.0  Tony Mitchell   Detroit
39089   203502.0  Tony Mitchell   Detroit
39097   203502.0  Tony Mitchell   Detroit
39442   203502.0  Tony Mitchell   Detroit
39450   203502.0  Tony Mitchell   Detroit
39543   203502.0  Tony Mitchell   Detroit
39549   203502.0  Tony Mitchell   Detroit
39731   203502.0  Tony Mitchell   Detroit
39735   203502.0  Tony Mitchell   Detroit
39854   203502.0  Tony Mitchell   Detroit
39860   203502.0  Tony Mitchell   Detroit
40213   203502.0  Tony Mitchell   Detroit
40221   203502.0  Tony Mitchell   Detroit
40845   203502.0  Tony Mitchell   Detroit
40849   203502.0  Tony Mitchell   Detroit
40888   203502.0  Tony Mitchell   Detroit
40894   203502.0  Tony Mitchell   Detroit
41038   203502.0  Tony Mitchell   Detroit
41045   203502.0  Tony Mitchell   Detroit
41291   203502.0  Tony Mitchell   Detroit
41295   203502.0  Tony Mitchell   Detroit
41408   203502.0  Tony Mitchell   Detroit
41413   203502.0  Tony Mitchell   Detroit
41559   203502.0  Tony Mitchell   Detroit
41567   203502.0  Tony Mitchell   Detroit
41658   203502.0  Tony Mitchell   Detroit
41666   203502.0  Tony Mitchell   Detroit
41740   203502.0  Tony Mitchell   Detroit
41746   203502.0  Tony Mitchell   Detroit
41903   203502.0  Tony Mitchell   Detroit
41911   203502.0  Tony Mitchell   Detroit
41972   203502.0  Tony Mitchell   Detroit
41978   203502.0  Tony Mitchell   Detroit
42086   203502.0  Tony Mitchell   Detroit
42091   203502.0  Tony Mitchell   Detroit
42239   203502.0  Tony Mitchell   Detroit
42245   203502.0  Tony Mitchell   Detroit
42307   203502.0  Tony Mitchell   Detroit
42314   203502.0  Tony Mitchell   Detroit
42571   203502.0  Tony Mitchell   Detroit
42575   203502.0  Tony Mitchell   Detroit
44893   203502.0  Tony Mitchell   Phoenix
44900   203502.0  Tony Mitchell   Phoenix

In [35]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[2]) & (df_5bsa1018.PLAYER_ID == 203183.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID    PLAYER_NAME  TEAM_CITY
37849   203183.0  Tony Mitchell  Milwaukee
37854   203183.0  Tony Mitchell  Milwaukee
38045   203183.0  Tony Mitchell  Milwaukee
38051   203183.0  Tony Mitchell  Milwaukee
38231   203183.0  Tony Mitchell  Milwaukee
38236   203183.0  Tony Mitchell  Milwaukee

In [36]:
#two different players
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[3])]

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
8898,21100032,2011-12-28,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8899,21100032,2011-12-28,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9159,21100066,2012-01-02,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9164,21100066,2012-01-02,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9980,21100158,2012-01-12,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9986,21100158,2012-01-12,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10344,21100196,2012-01-17,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10351,21100196,2012-01-17,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10434,21100206,2012-01-18,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10440,21100206,2012-01-18,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11914,21100372,2012-02-07,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11921,21100372,2012-02-07,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12393,21100419,2012-02-13,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12397,21100419,2012-02-13,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12579,21100440,2012-02-15,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12585,21100440,2012-02-15,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12752,21100458,2012-02-18,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12756,21100458,2012-02-18,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12957,21100480,2012-02-20,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12965,21100480,2012-02-20,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13116,21100496,2012-02-22,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13122,21100496,2012-02-22,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13307,21100516,2012-02-29,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13312,21100516,2012-02-29,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14235,21100610,2012-03-11,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14241,21100610,2012-03-11,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14521,21100637,2012-03-14,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14527,21100637,2012-03-14,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14750,21100661,2012-03-17,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14755,21100661,2012-03-17,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14894,21100675,2012-03-19,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14899,21100675,2012-03-19,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15005,21100688,2012-03-21,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15010,21100688,2012-03-21,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16162,21100806,2012-04-04,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16166,21100806,2012-04-04,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16367,21100824,2012-04-06,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16372,21100824,2012-04-06,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17597,21100948,2012-04-21,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17604,21100948,2012-04-21,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17697,21100957,2012-04-22,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17706,21100957,2012-04-22,2011-12,1610612744,GSW,Golden State,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26555,21200967,2013-03-14,2012-13,1610612742,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26562,21200967,2013-03-14,2012-13,1610612742,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26797,21200990,2013-03-17,2012-13,1610612742,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26803,21200990,2013-03-17,2012-13,1610612742,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27174,21201029,2013-03-22,2012-13,1610612742,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27179,21201029,2013-03-22,2012-13,1610612742,DAL,Dallas,203203.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38395,21300987,2014-03-16,2013-14,1610612749,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38401,21300987,2014-03-16,2013-14,1610612749,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38545,21301005,2014-03-18,2013-14,1610612749,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38552,21301005,2014-03-18,2013-14,1610612749,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38703,21301021,2014-03-20,2013-14,1610612749,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38708,21301021,2014-03-20,2013-14,1610612749,MIL,Milwaukee,202874.0,Chris Wright,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[3]) & (df_5bsa1018.PLAYER_ID == 202874.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID   PLAYER_NAME     TEAM_CITY
8898    202874.0  Chris Wright  Golden State
8899    202874.0  Chris Wright  Golden State
9159    202874.0  Chris Wright  Golden State
9164    202874.0  Chris Wright  Golden State
9980    202874.0  Chris Wright  Golden State
9986    202874.0  Chris Wright  Golden State
10344   202874.0  Chris Wright  Golden State
10351   202874.0  Chris Wright  Golden State
10434   202874.0  Chris Wright  Golden State
10440   202874.0  Chris Wright  Golden State
11914   202874.0  Chris Wright  Golden State
11921   202874.0  Chris Wright  Golden State
12393   202874.0  Chris Wright  Golden State
12397   202874.0  Chris Wright  Golden State
12579   202874.0  Chris Wright  Golden State
12585   202874.0  Chris Wright  Golden State
12752   202874.0  Chris Wright  Golden State
12756   202874.0  Chris Wright  Golden State
12957   202874.0  Chris Wright  Golden State
12965   202874.0  Chris Wright  Golden State
13116   202874.0  Chris Wright  Golden State
13122   202874.0  Chris Wright  Golden State
13307   202874.0  Chris Wright  Golden State
13312   202874.0  Chris Wright  Golden State
14235   202874.0  Chris Wright  Golden State
14241   202874.0  Chris Wright  Golden State
14521   202874.0  Chris Wright  Golden State
14527   202874.0  Chris Wright  Golden State
14750   202874.0  Chris Wright  Golden State
14755   202874.0  Chris Wright  Golden State
14894   202874.0  Chris Wright  Golden State
14899   202874.0  Chris Wright  Golden State
15005   202874.0  Chris Wright  Golden State
15010   202874.0  Chris Wright  Golden State
16162   202874.0  Chris Wright  Golden State
16166   202874.0  Chris Wright  Golden State
16367   202874.0  Chris Wright  Golden State
16372   202874.0  Chris Wright  Golden State
17597   202874.0  Chris Wright  Golden State
17604   202874.0  Chris Wright  Golden State
17697   202874.0  Chris Wright  Golden State
17706   202874.0  Chris Wright  Golden State
38395   202874.0  Chris Wright     Milwaukee
38401   202874.0  Chris Wright     Milwaukee
38545   202874.0  Chris Wright     Milwaukee
38552   202874.0  Chris Wright     Milwaukee
38703   202874.0  Chris Wright     Milwaukee
38708   202874.0  Chris Wright     Milwaukee

In [38]:
df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(playerl[3]) & (df_5bsa1018.PLAYER_ID == 203203.0)][['PLAYER_ID', 'PLAYER_NAME', 'TEAM_CITY']]

       PLAYER_ID   PLAYER_NAME TEAM_CITY
26555   203203.0  Chris Wright    Dallas
26562   203203.0  Chris Wright    Dallas
26797   203203.0  Chris Wright    Dallas
26803   203203.0  Chris Wright    Dallas
27174   203203.0  Chris Wright    Dallas
27179   203203.0  Chris Wright    Dallas

In [39]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [40]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 'A12bsa_game_id_team_id_player_id_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_5bsa1018.to_csv(datapath_df, index=False)

In [41]:
df = pd.read_csv(os.path.join('..', 'processed_data', 'A12bsa_game_id_team_id_player_id_2010_2018.csv'))
print(df.shape)
p(df)

(44547, 33)
(44547, 33)

,game_id,game_date,team_id,season,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,201623.0,Semih Erden,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,101144.0,Von Wafer,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000001,2010-10-26,1610612738,2010-11,BOS,Boston,2753.0,Delonte West,NaN,NWT - League Suspension,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,201596.0,Mario Chalmers,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21000001,2010-10-26,1610612748,2010-11,MIA,Miami,436.0,Juwan Howard,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44542,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,101181.0,Jose Calderon,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44543,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44544,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1626224.0,Cedi Osman,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44545,41700403,2018-06-06,1610612739,2017-18,CLE,Cleveland,1627790.0,Ante Zizic,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44546,41700404,2018-06-08,1610612739,2017-18,CLE,Cleveland,203903.0,Jordan Clarkson,NaN,DNP - Coach's Decision,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0