In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sqlite3

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('max_colwidth', None)

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [3]:
def replace_player(df_):
    df_.player.replace({'J.J. Redick':'JJ Redick'}, inplace=True)
    
    df_.player.replace({'A.J. Price': 'AJ Price'}, inplace=True)
    
    df_.player.replace({'Alex Ajinca':'Alexis Ajinca'}, inplace=True)
    
    df_.player.replace({'C.J. Miles': 'CJ Miles'}, inplace=True)
    
    df_.player.replace({'D.J. White': 'DJ White'}, inplace=True)
    
    df_.player.replace({"Hamady N'Diaye" : 'Hamady Ndiaye'}, inplace=True)
    
    df_.player.replace({'J.J. Hickson': 'JJ Hickson'}, inplace=True)
    
    df_.player.replace({'John Wallace' : 'John Wall'}, inplace=True)
    
    df_.player.replace({'Jose Barea' : 'J.J. Barea'}, inplace=True)
    
    df_.player.replace({'Wes Johnson':'Wesley Johnson'}, inplace=True)
    
    df_.player.replace({'B.J. Mullens':'Byron Mullens'}, inplace=True)
    
    df_.player.replace({'Bill Walker':'Henry Walker'}, inplace=True)
    
    df_.player.replace({'Gerald Henderson Jr.':'Gerald Henderson'}, inplace=True)
    
    df_.player.replace({'Jianlian Yi':'Yi Jianlian'}, inplace=True)
    
    df_.player.replace({'Mike Conley Jr.':'Mike Conley'}, inplace=True)
    
    df_.player.replace({'Mike Dunleavy Jr.':'Mike Dunleavy'}, inplace=True)
    
    df_.player.replace({'Nene Hilario': 'Nene'}, inplace=True)
    
    df_.player.replace({'Didier Mbenga':'DJ Mbenga'}, inplace=True)
    
    df_.player.replace({'A.J. Hammons':'AJ Hammons'}, inplace=True)
    
    df_.player.replace({'C.J. McCollum':'CJ McCollum'}, inplace=True)
    
    df_.player.replace({'D.J. Augustine':'D.J. Augustin'}, inplace=True)
    
    df_.player.replace({'DeAndre Bembry':"DeAndre' Bembry"}, inplace=True)
    
    df_.player.replace({'Giorgios Papagiannis':'Georgios Papagiannis'}, inplace=True)
    
    df_.player.replace({'Glen Rice Jr.':'Glen Rice'}, inplace=True)
    
    df_.player.replace({'J.R. Smith':'JR Smith'}, inplace=True)
    
    df_.player.replace({'James Ennis':'James Ennis III'}, inplace=True)
    
    df_.player.replace({'John Collins  John Collins':'John Collins'}, inplace=True)
    
    df_.player.replace({'Juan Hernangomez':'Juancho Hernangomez'}, inplace=True)
    
    df_.player.replace({'Billy Ouattara':'Yakuba Ouattara'}, inplace=True)
    
    df_.player.replace({'Courtney Simpson':'Diamon Simpson'}, inplace=True)
    
    df_.player.replace({'Danuel House':'Danuel House Jr.'}, inplace=True)
    
    df_.player.replace({'Domas Sabonis':'Domantas Sabonis'}, inplace=True)
    
    df_.player.replace({'Jake Wiley':'Jacob Wiley'}, inplace=True)
    
    df_.player.replace({'James McAdoo':'James Michael McAdoo'}, inplace=True)
    
    df_.player.replace({'Jeff Pendergraph':'Jeff Ayres'}, inplace=True)
    
    df_.player.replace({'Jeff Taylor':'Jeffery Taylor'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'K.J. McDaniels':'KJ McDaniels'}, inplace=True)
    
    df_.player.replace({'Malcom Lee':'Malcolm Lee'}, inplace=True)
    
    df_.player.replace({'Marcus Morris':'Marcus Morris Sr.'}, inplace=True)
    
    df_.player.replace({'Matt Williams':'Matt Williams Jr.'}, inplace=True)
    
    df_.player.replace({"Maurice N'dour":'Maurice Ndour'}, inplace=True)
    
    df_.player.replace({'Milos Tedosic':'Milos Teodosic'}, inplace=True)
    
    df_.player.replace({'Moe Harkless':'Maurice Harkless'}, inplace=True)
    
    df_.player.replace({'O.G. Anunoby':'OG Anunoby'}, inplace=True)
    
    df_.player.replace({'Ognen Kuzmic':'Ognjen Kuzmic'}, inplace=True)
    
    df_.player.replace({'P.J. Dozier':'PJ Dozier'}, inplace=True)
    
    df_.player.replace({'P.J. Hairston':'PJ Hairston'}, inplace=True)
    
    df_.player.replace({'Qi Zhou':'Zhou Qi'}, inplace=True)
    
    df_.player.replace({'R.J. Hunter':'RJ Hunter'}, inplace=True)
    
    df_.player.replace({'Ray McCallum Jr.':'Ray McCallum'}, inplace=True)
    
    df_.player.replace({'Ron Artest':'Metta World Peace'}, inplace=True)
    
    df_.player.replace({'Roy Marble':'Devyn Marble'}, inplace=True)
    
    df_.player.replace({'Stephen Zimmerman Jr.':'Stephen Zimmerman'}, inplace=True)
    
    df_.player.replace({'Tony Wroten Jr.':'Tony Wroten'}, inplace=True)
    
    df_.player.replace({'Toure Murry':"Toure' Murry"}, inplace=True)
    
    df_.player.replace({'Viacheslav Kravstov':'Viacheslav Kravtsov'}, inplace=True)
    
    df_.player.replace({'Vince Hunter':'Vincent Hunter'}, inplace=True)
    
    df_.player.replace({'Walker Russell Jr.':'Walker Russell'}, inplace=True)
    
    df_.player.replace({'Wayne Selden Jr.':'Wayne Selden'}, inplace=True)
    
    df_.player.replace({'Wes Matthews Jr.':'Wesley Matthews'}, inplace=True)
    
    return df_

#names dropped from Injury Report dataframe df_inj1018 for the following reasons:
#a. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons.
#b. player did not play an nba regular season or playoff game between the 2009-10 and 2017-18 seasons.
#c. no player nba regular season or playoff boxscore advanced stats between the 2009-10 and 2017-18 seasons. Player plays in nba games
#   following the 2017-18 season.
#d. this is the injury of a coach, not a player. coaches do not have boxscore advanced stats


def drop_player(df_):
    df_.drop(df_[df_.player.str.contains('Marion Hillard')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Matt Janning')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains("Da'Sean Butler")].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Eric Griffin')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Harry Giles')].index, inplace = True) #c
    
    df_.drop(df_[df_.player.str.contains('Magnum Rolle')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Robert Vaden')].index, inplace = True) #a
    
    df_.drop(df_[df_.player.str.contains('Steve Clifford')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Steve Kerr')].index, inplace = True) #d
    
    df_.drop(df_[df_.player.str.contains('Terrico White')].index, inplace = True)#a
    
    df_.drop(df_[df_.player.str.contains('Tyronn Lue')].index, inplace = True) #d
    
    return df_

def df_inj1020_fix_Date_Team(df_):
    df_.loc[5923, ['Team']] = 'Pacers'
    return df_

def manual_not_the_actual_game_date_drop(df_):
    df_.drop(21307, inplace=True) #df_[(df_.game_date == '2013-05-10') & (df_.player == 'Eric Gordon')]
    df_.reset_index(drop=True, inplace=True)
    return df_

'''def manual_not_the_game_date_drop2(df_):
    df_ = df_.drop(14084) #df_[(df_.game_date == '2013-05-10') & (df_.player == 'Eric Gordon')]
    df_ = df_.reset_index(drop=True)
    return df_'''


def get_5bsa1018_inj1018_player_diff():
    print(len(set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME)))
    print(set(df_inj1018.player) - set(df_5bsa1018.PLAYER_NAME))
    print()
    
    print(len(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player)))
    print(set(df_5bsa1018.PLAYER_NAME) - set(df_inj1020.player))
    return 0
    
    
#get injury data for player
def gi(player_):
    return df_inj1018[df_inj1018.player.str.contains(player_)] 

#get boxscore advance for player
def gb(player_):
    return df_5bsa1018[df_5bsa1018.PLAYER_NAME.str.contains(player_)]

#get inactive player game-by-game
def gia(player_):
    return df_ina1018[df_ina1018.player.str.contains(player_)]

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [4]:
def fix_chris_wright_Team(df_):
    indexes_ = list(df_[((df_.Date == '2011-12-25') |
                        (df_.Date == '2011-12-28') |
                        (df_.Date == '2012-01-04') |
                        (df_.Date == '2012-01-20'))
                      & (df_.player == 'Chris Wright')].index)
    df_.at[indexes_, 'Team'] = 'Warriors'
    return df_

In [5]:
#drop '2011-12-25', 'Jeff Green' from df_inj1018 bc he didn't play the 2011-12 season

def drop_jeff_green_2011_12(df_):
    indexes_ = list(df_[((df_.Date == '2011-12-17') |
                         (df_.Date == '2011-12-25'))
                      & (df_.player == 'Jeff Green')].index)
    df_.drop(indexes_, inplace=True)
    return df_
#not seen as inactive/active on nba.com boxscores for the 2011-12 season

#'preseason physical with his employer, the Boston Celtics...failed his physical, voiding his one-year deal with the team, and won't play at all in the 2011-12 season'
#https://www.espn.com/nba/story/_/id/23713648/nba-how-jeff-green-returned-heart-defect-almost-ended-life

In [6]:
#fix Team from Cavaliers to Pistons on '2014-04-04' and '2013-11-29' game_date's for 'Will Bynum'
def fix_will_bynum_team_2013_14(df_):

    indexes_ = list(df_[df_.player.str.contains('Will Bynum') & ((df_.Date == '2014-04-04') | (df_.Date == '2013-11-29'))].index)

    df_.at[indexes_, 'Team'] = 'Pistons'

    return df_

In [7]:
#Bogdan Bogdanovic on game_date '2017-10-18' should have Team changed from Pacers to Kings since the Pacers play has a first name of Bojan not Bogdan
def fix_bogdan_bogdanovic_Team(df_):

    index_ = list(df_[df_.player.str.contains('Bogdan Bogdanovic') & (df_.Date == '2017-10-18')].index)

    df_.at[index_, 'Team'] = 'Kings'

    return df_

In [8]:
#drop jason kidd for game_date '2015-12-20' since he was a coach here
def drop_jason_kidd_2015_16(df_):
    index = list(df_[df_.player.str.contains('Jason Kidd') & (df_.Date == '2015-12-20')].index)
    df_.drop(index, inplace=True)
    return df_

In [9]:
#fix Team from hornets to Cavaliers for Chris Andersen on game_date '2017-02-13'
def fix_chris_andersen_Team(df_):
    index_ = list(df_[df_.player.str.contains('Chris Andersen') & (df_.Date == '2017-02-13')].index)
    df_.at[index_, 'Team']  = 'Cavaliers'
    return df_

In [10]:
#for Date '2017-02-13' and player/Relinquished 'Chris Wilcox', replace name with C.J. Wilcox and Team with 'Magic'

#earlier in season tenditis, but not on specific date https://www.nba.com/clippers/news/hand-injury-frustrating-wilcox-after-finally-feeling-healthy
#Wilcox of Magic inactive https://statsdmz.nba.com/pdfs/20170213/20170213_ORLMIA.pdf
#C.J. Wilcox of the Magic that 2016-17 season https://www.basketball-reference.com/players/w/wilcocj01.html
def fix_cj_wilcox_Team_player(df_):
    index_ = list(df_[(df_.Date == '2017-02-13') & df_.player.str.contains('Chris Wilcox')].index)
    df_.at[index_, 'Team'] = 'Magic'
    df_.at[index_, 'player'] = 'C.J. Wilcox'
    if True in df_inj1020.columns.str.contains('Relinquished'):
        df_.at[index_, 'Relinquished'] = 'C.J. Wilcox'
    return df_

In [11]:
def drop_okaro_white_sheldon_mac_hawks_2018_02_08(df_):
    index_ = list(df_[df_.player.str.contains('Okaro White') & (df_.Date == '2018-02-08')].index)
    df_.drop(index_, inplace=True)
    
    index_ = list(df_inj1018[df_inj1018.player.str.contains('Sheldon Mac') & (df_inj1018.Date == '2018-02-08')].index)
    df_.drop(index_, inplace=True)
    
    return df_

#Andrew White of the hawks was an inactive player on this Team and date. why does the injury report show player was Acquired???
#andrew white inactive https://statsdmz.nba.com/pdfs/20180208/20180208_ATLORL.pdf
#andrew white, hawk the 2017-18 season https://www.basketball-reference.com/players/w/whitean01.html


#okaro white , heat, left foot surgery inactive https://statsdmz.nba.com/pdfs/20180207/20180207_HOUMIA.pdf
# okaro white, not on heat inactive list the following nba game https://statsdmz.nba.com/pdfs/20180209/20180209_MILMIA.pdf

#Sheldon Mac
#'He did not appear in a game for the Wizards in 2017–18, and on February 8, 2018,
# he was traded to the Atlanta Hawks alongside cash considerations in exchange for a protected 2019 second round draft pick.'


#okaro white get his Team, Notes, Acquired, Relinquished, Date messed with?????

In [12]:
os.getcwd()

'/Users/pauljacob/Documents/GitHub/DSCapstone2/02_Data_Wrangling'

In [13]:
#get injury report for 2010-11 thru 2017-18 sesasons: df_inj1018

#last game_date of 2017-18 season
path = os.path.join('..', 'processed_data', '7season_first_game_date_last_game_date.csv')
df_7sfgdlgd = pd.read_csv(path, parse_dates=['first', 'last'])
last_game_date_s1718 = df_7sfgdlgd.iloc[8]['last']
last_game_date_s1718

Timestamp('2018-06-08 00:00:00')

In [14]:
#read in raw injury report
path = os.path.join('..', 'raw_data', 'injuries_2010-2020.csv')
df_inj1020 = pd.read_csv(path, parse_dates=['Date'])
print(df_inj1020.shape)
p(df_inj1020)

(27105, 5)
(27105, 5)

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out indefinitely)
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out indefinitely)
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left foot
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

In [15]:
#preprocess player & Date
df_inj1020.Acquired.fillna('', inplace=True)
df_inj1020.Relinquished.fillna('', inplace=True)
df_inj1020['player'] = df_inj1020.Relinquished + ' ' + df_inj1020.Acquired
df_inj1020.player = df_inj1020.player.str.strip()
df_inj1020 = df_inj1020_fix_Date_Team(df_inj1020)
print(df_inj1020.shape)
p(df_inj1020)

(27105, 6)
(27105, 6)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
27100,2020-09-30,Lakers,Dion Waiters,,activated from IL,Dion Waiters
27101,2020-10-02,Heat,,Bam Adebayo,strained neck (DTD),Bam Adebayo
27102,2020-10-02,Heat,,Goran Dragic,placed on IL with torn plantar fascia in left foot,Goran Dragic
27103,2020-10-02,Heat,Chris Silva,,activated from IL,Chris Silva
27104,2020-10-06,Heat,Bam Adebayo,,returned to lineup,Bam Adebayo

In [16]:
#bound last game date and make new dateframe: df_inj1018
df_inj1018 = df_inj1020.loc[df_inj1020['Date'] <= last_game_date_s1718]
print(df_inj1018.shape)
p(df_inj1018)

(22257, 6)
(22257, 6)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
2,2010-10-06,Pistons,,Terrico White,broken fifth metatarsal in right foot (out indefinitely),Terrico White
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [17]:
#fix player (name)
df_inj1018 = replace_player(df_inj1018)
df_inj1018 = drop_player(df_inj1018)
print(df_inj1018.shape)
p(df_inj1018)

(22232, 6)
(22232, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4563: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [18]:
#fix chris wright team to 'Warriors'
df_inj1018 = fix_chris_wright_Team(df_inj1018)
p(df_inj1018)

(22232, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [19]:
#drop 2011-12 season rows for jeff green since he was out for the season to heart surgery. contract voided
df_inj1018 = drop_jeff_green_2011_12(df_inj1018)
p(df_inj1018)

(22230, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [20]:
df_inj1018 = fix_will_bynum_team_2013_14(df_inj1018)
p(df_inj1018)

(22230, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [21]:
#drop jason kidd for game_date '2015-12-20' since he was a coach here
df_inj1018 = drop_jason_kidd_2015_16(df_inj1018)
p(df_inj1018)

(22229, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [22]:
#fix Team from hornets to Cavaliers for Chris Andersen on game_date '2017-02-13'
df_inj1018 = fix_chris_andersen_Team(df_inj1018)
p(df_inj1018)

(22229, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [23]:
#Bogdan Bogdanovic on game_date '2017-10-18' should have Team changed from Pacers to Kings since the Pacers play has a first name of Bojan not Bogdan
df_inj1018 = fix_bogdan_bogdanovic_Team(df_inj1018)
p(df_inj1018)

(22229, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [24]:
df_inj1018 = fix_cj_wilcox_Team_player(df_inj1018)
p(df_inj1018)

(22229, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [25]:
df_inj1018 = drop_okaro_white_sheldon_mac_hawks_2018_02_08(df_inj1018)
p(df_inj1018)

(22227, 6)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Date,Team,Acquired,Relinquished,Notes,player
0,2010-10-03,Bulls,,Carlos Boozer,fractured bone in right pinky finger (out indefinitely),Carlos Boozer
1,2010-10-06,Pistons,,Jonas Jerebko,torn right Achilles tendon (out indefinitely),Jonas Jerebko
3,2010-10-08,Blazers,,Jeff Ayres,torn ACL in right knee (out indefinitely),Jeff Ayres
4,2010-10-08,Nets,,Troy Murphy,strained lower back (out indefinitely),Troy Murphy
5,2010-10-08,Pistons,,Jonas Jerebko,surgery to repair torn right Achilles tendon,Jonas Jerebko
22252,2018-05-25,Rockets,,Chris Paul,strained right hamstring (out for season),Chris Paul
22253,2018-05-26,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
22254,2018-05-26,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
22255,2018-05-31,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
22256,2018-06-06,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

In [26]:
#add team_id, player_id, game_id

In [27]:
#team_id

#merge 3gdgiti (game_date, season) with od get unique --> season

#season, Team --> team_id

In [28]:
df_3gds = rcp('3game_id_game_date_team_id.csv', ['game_date'])[['game_date', 'season']].drop_duplicates().reset_index(drop=True)
p(df_3gds)

(2450, 2)

      game_date   season
0    2006-10-31  2006-07
1    2006-11-01  2006-07
2    2006-11-02  2006-07
3    2006-11-03  2006-07
4    2006-11-04  2006-07
2445 2018-05-28  2017-18
2446 2018-05-31  2017-18
2447 2018-06-03  2017-18
2448 2018-06-06  2017-18
2449 2018-06-08  2017-18

In [29]:
#merge 3gdgiti (game_date, season) with od get unique --> season
df_inj1018_dgd = pd.merge(df_3gds.rename(columns={'game_date':'Date_game_date'}), df_inj1018.rename(columns={'Date':'Date_game_date'}), on='Date_game_date', how='inner')
p(df_inj1018_dgd)

(21917, 7)

,Date_game_date,season,Team,Acquired,Relinquished,Notes,player
0,2010-10-26,2010-11,Blazers,,Elliot Williams,placed on IL,Elliot Williams
1,2010-10-26,2010-11,Blazers,,Greg Oden,placed on IL with left knee injury (out for season),Greg Oden
2,2010-10-26,2010-11,Blazers,,Joel Przybilla,placed on IL placed on IL recovering from surgery on right knee to repair ruptured patella tendon,Joel Przybilla
3,2010-10-26,2010-11,Celtics,,Avery Bradley,placed on IL recovering from surgery on left ankle,Avery Bradley
4,2010-10-26,2010-11,Celtics,,Kendrick Perkins,placed on IL recovering from surgery on right knee to repair torn ACL,Kendrick Perkins
21912,2018-05-22,2017-18,Warriors,,Andre Iguodala,bruised left leg (DTD),Andre Iguodala
21913,2018-05-26,2017-18,Cavaliers,,Kevin Love,concussion (DTD),Kevin Love
21914,2018-05-26,2017-18,Warriors,Patrick McCaw,,activated from IL,Patrick McCaw
21915,2018-05-31,2017-18,Cavaliers,Kevin Love,,returned to lineup,Kevin Love
21916,2018-06-06,2017-18,Warriors,Andre Iguodala,,returned to lineup,Andre Iguodala

<font color='red'>are these the actual game dates or just dates nba games are played on which a player injury report was made on??? </font>

In [30]:
#season, Team --> team_id
df_tist = rcp('10team_id_season_team_2010_2018.csv')
p(df_tist)

(240, 3)

        TEAM_ID   season      Team
0    1610612748  2010-11      Heat
1    1610612749  2010-11     Bucks
2    1610612765  2010-11   Pistons
3    1610612753  2010-11     Magic
4    1610612737  2010-11     Hawks
235  1610612752  2017-18    Knicks
236  1610612758  2017-18     Kings
237  1610612744  2017-18  Warriors
238  1610612765  2017-18   Pistons
239  1610612746  2017-18  Clippers

In [31]:
df_inj1018_dgdti = pd.merge(df_tist, df_inj1018_dgd, on=['season', 'Team'], how='inner')
p(df_inj1018_dgdti)

(21916, 8)

,TEAM_ID,season,Team,Date_game_date,Acquired,Relinquished,Notes,player
0,1610612748,2010-11,Heat,2010-10-26,,Dexter Pittman,placed on IL,Dexter Pittman
1,1610612748,2010-11,Heat,2010-10-26,,Jerry Stackhouse,placed on IL,Jerry Stackhouse
2,1610612748,2010-11,Heat,2010-10-26,,Mario Chalmers,sprained ankle (out indefinitely),Mario Chalmers
3,1610612748,2010-11,Heat,2010-10-26,,Mike Miller,placed on IL recovering from surgery on right hand to repair a broken thumb and ligament damage,Mike Miller
4,1610612748,2010-11,Heat,2010-10-27,,Jamaal Magloire,placed on IL,Jamaal Magloire
21911,1610612746,2017-18,Clippers,2018-03-30,Danilo Gallinari,,activated from IL,Danilo Gallinari
21912,1610612746,2017-18,Clippers,2018-04-03,,Danilo Gallinari,sore right hand (out for season),Danilo Gallinari
21913,1610612746,2017-18,Clippers,2018-04-03,,Jawun Evans,placed on IL with abdominal injury / sports hernia / athletic pubalgia (out for season),Jawun Evans
21914,1610612746,2017-18,Clippers,2018-04-09,,Austin Rivers,sore right elbow (out for season),Austin Rivers
21915,1610612746,2017-18,Clippers,2018-04-09,,Lou Williams,sprained right ankle (out for season),Lou Williams

In [32]:
#game_id

#team_id, Date_game_date --> game_date

#team_id, game_date --> game_id

#team_id, player, (season,) game_date --> game_id

<font color='red'> team_id and a game_date all i need to get game_id????</font>

In [33]:
#game_id

#team_id, Date_game_date --> game_date

In [34]:
df_3gdti = rcp('3game_id_game_date_team_id.csv', ['game_date'])[['game_date', 'team_id']].drop_duplicates().reset_index(drop=True)
p(df_3gdti)

(31038, 2)

       game_date     team_id
0     2006-10-31  1610612748
1     2006-10-31  1610612741
2     2006-10-31  1610612747
3     2006-10-31  1610612756
4     2006-11-01  1610612755
31033 2018-06-03  1610612744
31034 2018-06-06  1610612744
31035 2018-06-06  1610612739
31036 2018-06-08  1610612739
31037 2018-06-08  1610612744

In [35]:
#team_id, Date_game_date --> game_date
df_inj1018_gdti = pd.merge(df_inj1018_dgdti.rename(columns={'Date_game_date':'game_date', 'TEAM_ID':'team_id'}), df_3gdti, how='inner', on=['game_date', 'team_id'])
df_inj1018_gdti

,team_id,season,Team,game_date,Acquired,Relinquished,Notes,player
0,1610612748,2010-11,Heat,2010-10-26,,Dexter Pittman,placed on IL,Dexter Pittman
1,1610612748,2010-11,Heat,2010-10-26,,Jerry Stackhouse,placed on IL,Jerry Stackhouse
2,1610612748,2010-11,Heat,2010-10-26,,Mario Chalmers,sprained ankle (out indefinitely),Mario Chalmers
3,1610612748,2010-11,Heat,2010-10-26,,Mike Miller,placed on IL recovering from surgery on right hand to repair a broken thumb and ligament damage,Mike Miller
4,1610612748,2010-11,Heat,2010-10-27,,Jamaal Magloire,placed on IL,Jamaal Magloire
...,...,...,...,...,...,...,...,...
21060,1610612746,2017-18,Clippers,2018-03-30,Danilo Gallinari,,activated from IL,Danilo Gallinari
21061,1610612746,2017-18,Clippers,2018-04-03,,Danilo Gallinari,sore right hand (out for season),Danilo Gallinari
21062,1610612746,2017-18,Clippers,2018-04-03,,Jawun Evans,placed on IL with abdominal injury / sports hernia / athletic pubalgia (out for season),Jawun Evans
21063,1610612746,2017-18,Clippers,2018-04-09,,Austin Rivers,sore right elbow (out for season),Austin Rivers
21064,1610612746,2017-18,Clippers,2018-04-09,,Lou Williams,sprained right ankle (out for season),Lou Williams

In [36]:
#game_id

#team_id, game_date --> game_id
df_3gdtigi = rcp('3game_id_game_date_team_id.csv', ['game_date'])[['game_date', 'team_id','game_id']].drop_duplicates().reset_index(drop=True)
p(df_3gdtigi)

(31038, 3)

       game_date     team_id   game_id
0     2006-10-31  1610612748  20600001
1     2006-10-31  1610612741  20600001
2     2006-10-31  1610612747  20600002
3     2006-10-31  1610612756  20600002
4     2006-11-01  1610612755  20600003
31033 2018-06-03  1610612744  41700402
31034 2018-06-06  1610612744  41700403
31035 2018-06-06  1610612739  41700403
31036 2018-06-08  1610612739  41700404
31037 2018-06-08  1610612744  41700404

In [37]:
df_inj1018_gdti.columns

Index(['team_id', 'season', 'Team', 'game_date', 'Acquired', 'Relinquished',
       'Notes', 'player'],
      dtype='object')

In [38]:
#team_id, game_date --> game_id
df_inj1018_gdtigi = pd.merge(df_inj1018_gdti, df_3gdtigi, on=['team_id', 'game_date'])
p(df_inj1018_gdtigi)

(21065, 9)

,team_id,season,Team,game_date,Acquired,Relinquished,Notes,player,game_id
0,1610612748,2010-11,Heat,2010-10-26,,Dexter Pittman,placed on IL,Dexter Pittman,21000001
1,1610612748,2010-11,Heat,2010-10-26,,Jerry Stackhouse,placed on IL,Jerry Stackhouse,21000001
2,1610612748,2010-11,Heat,2010-10-26,,Mario Chalmers,sprained ankle (out indefinitely),Mario Chalmers,21000001
3,1610612748,2010-11,Heat,2010-10-26,,Mike Miller,placed on IL recovering from surgery on right hand to repair a broken thumb and ligament damage,Mike Miller,21000001
4,1610612748,2010-11,Heat,2010-10-27,,Jamaal Magloire,placed on IL,Jamaal Magloire,21000006
21060,1610612746,2017-18,Clippers,2018-03-30,Danilo Gallinari,,activated from IL,Danilo Gallinari,21701137
21061,1610612746,2017-18,Clippers,2018-04-03,,Danilo Gallinari,sore right hand (out for season),Danilo Gallinari,21701168
21062,1610612746,2017-18,Clippers,2018-04-03,,Jawun Evans,placed on IL with abdominal injury / sports hernia / athletic pubalgia (out for season),Jawun Evans,21701168
21063,1610612746,2017-18,Clippers,2018-04-09,,Austin Rivers,sore right elbow (out for season),Austin Rivers,21701212
21064,1610612746,2017-18,Clippers,2018-04-09,,Lou Williams,sprained right ankle (out for season),Lou Williams,21701212

In [39]:
df_inj1018_gdtigi.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21065 entries, 0 to 21064
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   team_id       21065 non-null  int64
 1   season        21065 non-null  object
 2   Team          21065 non-null  object
 3   game_date     21065 non-null  datetime64[ns]
 4   Acquired      21065 non-null  object
 5   Relinquished  21065 non-null  object
 6   Notes         21065 non-null  object
 7   player        21065 non-null  object
 8   game_id       21065 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 1.6+ MB

In [40]:
#player_id

#team_id, season, player --> player_id

#^-- acceptable bc no player's of the same name played for the same same team during the same season for 2010-11 thru 2017-18 seasons

In [41]:
df_gdgitispip = rcp('15game_date_game_id_team_id_season_player_id_player_2010_2018.csv', ['game_date'])
p(df_gdgitispip)

(334767, 6)

        game_date   game_id     team_id   season  PLAYER_ID             player
0      2009-10-27  20900001  1610612739  2009-10     2544.0       LeBron James
1      2009-10-27  20900003  1610612745  2009-10   201978.0     Chase Budinger
2      2009-10-27  20900003  1610612745  2009-10   200822.0  Pops Mensah-Bonsu
3      2009-10-27  20900003  1610612745  2009-10     2431.0     David Andersen
4      2009-10-27  20900003  1610612745  2009-10   201171.0        Carl Landry
334762 2018-06-08  41700404  1610612739  2017-18   202684.0   Tristan Thompson
334763 2018-06-08  41700404  1610612739  2017-18   201567.0         Kevin Love
334764 2018-06-08  41700404  1610612739  2017-18     2544.0       LeBron James
334765 2018-06-08  41700404  1610612739  2017-18   203903.0    Jordan Clarkson
334766 2018-06-08  41700404  1610612744  2017-18  1627775.0      Patrick McCaw

In [42]:
df_tispip = df_gdgitispip[['team_id', 'season', 'player', 'PLAYER_ID']].drop_duplicates().reset_index(drop=True)
p(df_tispip)

(5057, 4)

         team_id   season             player  PLAYER_ID
0     1610612739  2009-10       LeBron James     2544.0
1     1610612745  2009-10     Chase Budinger   201978.0
2     1610612745  2009-10  Pops Mensah-Bonsu   200822.0
3     1610612745  2009-10     David Andersen     2431.0
4     1610612745  2009-10        Carl Landry   201171.0
5052  1610612738  2017-18    Jonathan Gibson  1626780.0
5053  1610612747  2017-18       Andre Ingram   201281.0
5054  1610612745  2017-18      Aaron Jackson  1628935.0
5055  1610612739  2017-18   Kendrick Perkins     2570.0
5056  1610612764  2017-18          Ty Lawson   201951.0

In [43]:
p(df_inj1018_gdtigi)

(21065, 9)

,team_id,season,Team,game_date,Acquired,Relinquished,Notes,player,game_id
0,1610612748,2010-11,Heat,2010-10-26,,Dexter Pittman,placed on IL,Dexter Pittman,21000001
1,1610612748,2010-11,Heat,2010-10-26,,Jerry Stackhouse,placed on IL,Jerry Stackhouse,21000001
2,1610612748,2010-11,Heat,2010-10-26,,Mario Chalmers,sprained ankle (out indefinitely),Mario Chalmers,21000001
3,1610612748,2010-11,Heat,2010-10-26,,Mike Miller,placed on IL recovering from surgery on right hand to repair a broken thumb and ligament damage,Mike Miller,21000001
4,1610612748,2010-11,Heat,2010-10-27,,Jamaal Magloire,placed on IL,Jamaal Magloire,21000006
21060,1610612746,2017-18,Clippers,2018-03-30,Danilo Gallinari,,activated from IL,Danilo Gallinari,21701137
21061,1610612746,2017-18,Clippers,2018-04-03,,Danilo Gallinari,sore right hand (out for season),Danilo Gallinari,21701168
21062,1610612746,2017-18,Clippers,2018-04-03,,Jawun Evans,placed on IL with abdominal injury / sports hernia / athletic pubalgia (out for season),Jawun Evans,21701168
21063,1610612746,2017-18,Clippers,2018-04-09,,Austin Rivers,sore right elbow (out for season),Austin Rivers,21701212
21064,1610612746,2017-18,Clippers,2018-04-09,,Lou Williams,sprained right ankle (out for season),Lou Williams,21701212

In [44]:
df_inj1018_gdtigipi = pd.merge(df_inj1018_gdtigi, df_tispip, on=['team_id','season','player'], how='inner', indicator=True)
p(df_inj1018_gdtigipi)

(21065, 11)

,team_id,season,Team,game_date,Acquired,Relinquished,Notes,player,game_id,PLAYER_ID,_merge
0,1610612748,2010-11,Heat,2010-10-26,,Dexter Pittman,placed on IL,Dexter Pittman,21000001,202354.0,both
1,1610612748,2010-11,Heat,2011-02-15,,Dexter Pittman,surgery on right knee to repair cartilage (out indefinitely),Dexter Pittman,21000818,202354.0,both
2,1610612748,2010-11,Heat,2011-04-01,Dexter Pittman,,activated from IL,Dexter Pittman,21001126,202354.0,both
3,1610612748,2010-11,Heat,2011-04-03,,Dexter Pittman,placed on IL (out for season),Dexter Pittman,21001142,202354.0,both
4,1610612748,2010-11,Heat,2010-10-26,,Jerry Stackhouse,placed on IL,Jerry Stackhouse,21000001,711.0,both
21060,1610612746,2017-18,Clippers,2018-02-03,Avery Bradley,,activated from IL,Avery Bradley,21700775,202340.0,both
21061,1610612746,2017-18,Clippers,2018-02-22,,Avery Bradley,placed on IL with athletic pubalgia / sports hernia (out for season),Avery Bradley,21700872,202340.0,both
21062,1610612746,2017-18,Clippers,2018-03-13,,Avery Bradley,surgery to repair athletic pubalgia / sports hernia (out for season),Avery Bradley,21701010,202340.0,both
21063,1610612746,2017-18,Clippers,2018-02-28,,Tyrone Wallace,placed on IL,Tyrone Wallace,21700921,1627820.0,both
21064,1610612746,2017-18,Clippers,2018-03-27,Tyrone Wallace,,activated from IL,Tyrone Wallace,21701115,1627820.0,both

In [45]:
df_inj1018_gdtigipi.value_counts('_merge')

_merge
both          21065
right_only        0
left_only         0
dtype: int64

In [46]:
df_inj1018_gdtigipi.drop(columns=['_merge'], inplace=True)

In [47]:
p(df_inj1018_gdtigipi)

(21065, 10)

,team_id,season,Team,game_date,Acquired,Relinquished,Notes,player,game_id,PLAYER_ID
0,1610612748,2010-11,Heat,2010-10-26,,Dexter Pittman,placed on IL,Dexter Pittman,21000001,202354.0
1,1610612748,2010-11,Heat,2011-02-15,,Dexter Pittman,surgery on right knee to repair cartilage (out indefinitely),Dexter Pittman,21000818,202354.0
2,1610612748,2010-11,Heat,2011-04-01,Dexter Pittman,,activated from IL,Dexter Pittman,21001126,202354.0
3,1610612748,2010-11,Heat,2011-04-03,,Dexter Pittman,placed on IL (out for season),Dexter Pittman,21001142,202354.0
4,1610612748,2010-11,Heat,2010-10-26,,Jerry Stackhouse,placed on IL,Jerry Stackhouse,21000001,711.0
21060,1610612746,2017-18,Clippers,2018-02-03,Avery Bradley,,activated from IL,Avery Bradley,21700775,202340.0
21061,1610612746,2017-18,Clippers,2018-02-22,,Avery Bradley,placed on IL with athletic pubalgia / sports hernia (out for season),Avery Bradley,21700872,202340.0
21062,1610612746,2017-18,Clippers,2018-03-13,,Avery Bradley,surgery to repair athletic pubalgia / sports hernia (out for season),Avery Bradley,21701010,202340.0
21063,1610612746,2017-18,Clippers,2018-02-28,,Tyrone Wallace,placed on IL,Tyrone Wallace,21700921,1627820.0
21064,1610612746,2017-18,Clippers,2018-03-27,Tyrone Wallace,,activated from IL,Tyrone Wallace,21701115,1627820.0

In [48]:
#filter for relinquished

#drop Relinquished, Acquired, Notes

#drop duplicates and reset index

#write out

#read back in

In [49]:
#filter for relinquished

df_inj1018_gdtigipi = df_inj1018_gdtigipi[df_inj1018_gdtigipi.Relinquished != '']
p(df_inj1018_gdtigipi)

(13711, 10)

,team_id,season,Team,game_date,Acquired,Relinquished,Notes,player,game_id,PLAYER_ID
0,1610612748,2010-11,Heat,2010-10-26,,Dexter Pittman,placed on IL,Dexter Pittman,21000001,202354.0
1,1610612748,2010-11,Heat,2011-02-15,,Dexter Pittman,surgery on right knee to repair cartilage (out indefinitely),Dexter Pittman,21000818,202354.0
3,1610612748,2010-11,Heat,2011-04-03,,Dexter Pittman,placed on IL (out for season),Dexter Pittman,21001142,202354.0
4,1610612748,2010-11,Heat,2010-10-26,,Jerry Stackhouse,placed on IL,Jerry Stackhouse,21000001,711.0
6,1610612748,2010-11,Heat,2010-10-26,,Mario Chalmers,sprained ankle (out indefinitely),Mario Chalmers,21000001,201596.0
21057,1610612746,2017-18,Clippers,2018-01-13,,DeAndre Jordan,sprained left ankle (DTD),DeAndre Jordan,21700628,201599.0
21059,1610612746,2017-18,Clippers,2018-01-30,,Avery Bradley,placed on IL with sore right groin/hamstring,Avery Bradley,21700752,202340.0
21061,1610612746,2017-18,Clippers,2018-02-22,,Avery Bradley,placed on IL with athletic pubalgia / sports hernia (out for season),Avery Bradley,21700872,202340.0
21062,1610612746,2017-18,Clippers,2018-03-13,,Avery Bradley,surgery to repair athletic pubalgia / sports hernia (out for season),Avery Bradley,21701010,202340.0
21063,1610612746,2017-18,Clippers,2018-02-28,,Tyrone Wallace,placed on IL,Tyrone Wallace,21700921,1627820.0

In [50]:
#drop Relinquished, Acquired, Notes

df_inj1018_gdtigipi.drop(columns=['Relinquished', 'Acquired', 'Notes'], inplace=True)
p(df_inj1018_gdtigipi)

(13711, 7)

,team_id,season,Team,game_date,player,game_id,PLAYER_ID
0,1610612748,2010-11,Heat,2010-10-26,Dexter Pittman,21000001,202354.0
1,1610612748,2010-11,Heat,2011-02-15,Dexter Pittman,21000818,202354.0
3,1610612748,2010-11,Heat,2011-04-03,Dexter Pittman,21001142,202354.0
4,1610612748,2010-11,Heat,2010-10-26,Jerry Stackhouse,21000001,711.0
6,1610612748,2010-11,Heat,2010-10-26,Mario Chalmers,21000001,201596.0
21057,1610612746,2017-18,Clippers,2018-01-13,DeAndre Jordan,21700628,201599.0
21059,1610612746,2017-18,Clippers,2018-01-30,Avery Bradley,21700752,202340.0
21061,1610612746,2017-18,Clippers,2018-02-22,Avery Bradley,21700872,202340.0
21062,1610612746,2017-18,Clippers,2018-03-13,Avery Bradley,21701010,202340.0
21063,1610612746,2017-18,Clippers,2018-02-28,Tyrone Wallace,21700921,1627820.0

In [51]:
#drop duplicates and reset index

df_inj1018_gdtigipi = df_inj1018_gdtigipi.drop_duplicates().reset_index(drop=True)
p(df_inj1018_gdtigipi)

(13606, 7)

,team_id,season,Team,game_date,player,game_id,PLAYER_ID
0,1610612748,2010-11,Heat,2010-10-26,Dexter Pittman,21000001,202354.0
1,1610612748,2010-11,Heat,2011-02-15,Dexter Pittman,21000818,202354.0
2,1610612748,2010-11,Heat,2011-04-03,Dexter Pittman,21001142,202354.0
3,1610612748,2010-11,Heat,2010-10-26,Jerry Stackhouse,21000001,711.0
4,1610612748,2010-11,Heat,2010-10-26,Mario Chalmers,21000001,201596.0
13601,1610612746,2017-18,Clippers,2018-01-13,DeAndre Jordan,21700628,201599.0
13602,1610612746,2017-18,Clippers,2018-01-30,Avery Bradley,21700752,202340.0
13603,1610612746,2017-18,Clippers,2018-02-22,Avery Bradley,21700872,202340.0
13604,1610612746,2017-18,Clippers,2018-03-13,Avery Bradley,21701010,202340.0
13605,1610612746,2017-18,Clippers,2018-02-28,Tyrone Wallace,21700921,1627820.0

In [52]:
df_inj1018_gdtigipi.value_counts('Team')

Team
Spurs           601
Bucks           566
Nets            551
Rockets         538
Nuggets         531
Lakers          518
Raptors         510
Timberwolves    507
Cavaliers       507
Celtics         495
Knicks          489
Warriors        489
Wizards         478
Magic           473
Hawks           463
Mavericks       452
Heat            450
Jazz            430
76ers           428
Bulls           423
Grizzlies       401
Hornets         379
Kings           378
Pacers          378
Clippers        371
Suns            339
Pistons         337
Blazers         311
Thunder         309
Bobcats         256
Pelicans        248
dtype: int64

In [53]:
p(df_inj1018_gdtigipi[df_inj1018_gdtigipi.Team.str.contains('Blazers')])

(311, 7)

,team_id,season,Team,game_date,player,game_id,PLAYER_ID
516,1610612757,2010-11,Blazers,2010-10-26,Elliot Williams,21000002,202343.0
517,1610612757,2010-11,Blazers,2010-11-04,Elliot Williams,21000067,202343.0
518,1610612757,2010-11,Blazers,2010-11-06,Elliot Williams,21000087,202343.0
519,1610612757,2010-11,Blazers,2010-10-26,Greg Oden,21000002,201141.0
520,1610612757,2010-11,Blazers,2010-10-26,Joel Przybilla,21000002,2038.0
12235,1610612757,2017-18,Blazers,2018-03-23,Shabazz Napier,21701086,203894.0
12236,1610612757,2017-18,Blazers,2018-03-30,Georgios Papagiannis,21701137,1627834.0
12237,1610612757,2017-18,Blazers,2018-04-09,Georgios Papagiannis,21701211,1627834.0
12238,1610612757,2017-18,Blazers,2018-04-01,Ed Davis,21701154,202334.0
12239,1610612757,2017-18,Blazers,2018-04-17,Jake Layman,41700162,1627774.0

In [54]:
blazers_list = list(df_inj1018_gdtigipi[df_inj1018_gdtigipi.Team.str.contains('Blazers')].index)
blazers_list

[516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 3307,
 3308,
 3309,
 3310,
 3311,
 3312,
 3313,
 3314,
 3315,
 3316,
 3317,
 3318,
 3319,
 3320,
 3321,
 3322,
 3323,
 3324,
 3325,
 3326,
 3327,
 3328,
 3329,
 3330,
 3331,
 3332,
 3333,
 3334,
 3335,
 3336,
 3337,
 3338,
 3339,
 3340,
 3341,
 3342,
 3343,
 3344,
 3345,
 3346,
 3347,
 3348,
 3349,
 3350,
 4707,
 4708,
 4709,
 4710,
 4711,
 4712,
 4713,
 4714,
 4715,
 4716,
 4717,
 4718,
 4719,
 4720,
 4721,
 4722,
 4723,
 4724,
 4725,
 4726,
 4727,
 4728,
 4729,
 4730,
 4731,
 4732,
 4733,
 4734,
 4735,
 4736,
 4737,
 4738,
 4739,
 4740,
 4741,
 4742,
 4743,
 4744,
 4745,
 4746,
 4747,
 4748,
 4749,
 4750,
 6392,
 6393,
 6394,
 6395,
 6396,
 6397,
 6398,
 6399,
 6400,
 6401,
 6402,
 6403,
 6404,
 6405,
 6406,
 6407,
 6408,
 6409,
 6410,
 6411,
 6412,
 6413,
 6414,
 6415,
 6416,
 6417,
 6418,
 6419,
 6420,
 6421,
 6422,
 6423,
 8813,
 8814,
 8815,
 8816,
 8817,
 8818,
 8819,
 8820,
 8821,
 8822,
 8823,
 8824,
 8825,
 8826,
 8827,
 8828,
 8829,
 8830,
 8831,
 8832,
 8833,
 8834,
 8835,
 8836,
 8837,
 8838,
 8839,
 8840,
 8841,
 8842,
 8843,
 8844,
 8845,
 8846,
 8847,
 8848,
 8849,
 8850,
 8851,
 8852,
 8853,
 8854,
 8855,
 8856,
 8857,
 8858,
 9865,
 9866,
 9867,
 9868,
 9869,
 9870,
 9871,
 9872,
 9873,
 9874,
 9875,
 9876,
 9877,
 9878,
 9879,
 9880,
 9881,
 9882,
 9883,
 9884,
 9885,
 9886,
 9887,
 9888,
 9889,
 9890,
 9891,
 10535,
 10536,
 10537,
 10538,
 10539,
 10540,
 10541,
 10542,
 10543,
 10544,
 10545,
 10546,
 10547,
 10548,
 10549,
 10550,
 10551,
 10552,
 10553,
 10554,
 10555,
 10556,
 10557,
 10558,
 10559,
 10560,
 10561,
 10562,
 10563,
 10564,
 10565,
 10566,
 10567,
 10568,
 10569,
 10570,
 10571,
 10572,
 10573,
 12206,
 12207,
 12208,
 12209,
 12210,
 12211,
 12212,
 12213,
 12214,
 12215,
 12216,
 12217,
 12218,
 12219,
 12220,
 12221,
 12222,
 12223,
 12224,
 12225,
 12226,
 12227,
 12228,
 12229,
 12230,
 12231,
 12232,
 12233,
 12234,
 12235,
 12236,
 12237,
 12238,
 12239]

In [55]:
df_inj1018_gdtigipi.at[blazers_list, 'Team'] = 'Trail Blazers'

In [56]:
df_inj1018_gdtigipi.value_counts('Team')

Team
Spurs            601
Bucks            566
Nets             551
Rockets          538
Nuggets          531
Lakers           518
Raptors          510
Timberwolves     507
Cavaliers        507
Celtics          495
Knicks           489
Warriors         489
Wizards          478
Magic            473
Hawks            463
Mavericks        452
Heat             450
Jazz             430
76ers            428
Bulls            423
Grizzlies        401
Hornets          379
Kings            378
Pacers           378
Clippers         371
Suns             339
Pistons          337
Trail Blazers    311
Thunder          309
Bobcats          256
Pelicans         248
dtype: int64

In [57]:
#write out

datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, 'A9injury_game_id_team_id_player_id_2010_2018_v2.csv')
if not os.path.exists(datapath_df):
    df_inj1018_gdtigipi.to_csv(datapath_df, index=False)

In [58]:
df = rcp('A9injury_game_id_team_id_player_id_2010_2018_v2.csv')
p(df)

(13606, 7)

,team_id,season,Team,game_date,player,game_id,PLAYER_ID
0,1610612748,2010-11,Heat,2010-10-26,Dexter Pittman,21000001,202354.0
1,1610612748,2010-11,Heat,2011-02-15,Dexter Pittman,21000818,202354.0
2,1610612748,2010-11,Heat,2011-04-03,Dexter Pittman,21001142,202354.0
3,1610612748,2010-11,Heat,2010-10-26,Jerry Stackhouse,21000001,711.0
4,1610612748,2010-11,Heat,2010-10-26,Mario Chalmers,21000001,201596.0
13601,1610612746,2017-18,Clippers,2018-01-13,DeAndre Jordan,21700628,201599.0
13602,1610612746,2017-18,Clippers,2018-01-30,Avery Bradley,21700752,202340.0
13603,1610612746,2017-18,Clippers,2018-02-22,Avery Bradley,21700872,202340.0
13604,1610612746,2017-18,Clippers,2018-03-13,Avery Bradley,21701010,202340.0
13605,1610612746,2017-18,Clippers,2018-02-28,Tyrone Wallace,21700921,1627820.0