In [1]:

#function to perform cma_#_diff
    #specify the columns to groupby
    
    #specify the window size, and minimum
    
    #specify the columns to not take the difference for

    #specifc the df
    
#get cma5, cma12, cma999

In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [3]:
df = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv', ['game_date'])
df = sr(df, 'game_date')
p(df)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4
4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [4]:
df_giti = f.wide2tall(df, ['game_id', 'team_id'], ['_away', '_home'])
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [5]:
df_giti = sr(df_giti, 'game_date')
p(df_giti)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [6]:
df_giti['a'] = df_giti.matchup.str.split(' vs. ').str[0].str.strip()
p(df_giti)

(20532, 60)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE

In [7]:
df_giti['b'] = df_giti.matchup.str.split(' vs. ').str[1].str.strip()
p(df_giti)

(20532, 61)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW

In [8]:
df_giti.loc[df_giti['a'] == df_giti['TEAM_ABBREVIATION'], '_a'] = 1
p(df_giti)

(20532, 62)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,NaN
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,NaN
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,NaN
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,NaN
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,NaN
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0

In [9]:
df_giti.loc[df_giti['a'] != df_giti['TEAM_ABBREVIATION'], '_a'] = 0
p(df_giti)

(20532, 62)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0

In [10]:
df_giti.loc[df_giti['b'] == df_giti['TEAM_ABBREVIATION'], '_b'] = 1
p(df_giti)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,NaN
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,NaN
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,NaN
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,NaN
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,NaN

In [11]:
df_giti.loc[df_giti['b'] != df_giti['TEAM_ABBREVIATION'], '_b'] = 0
p(df_giti)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0

In [12]:
df_giti.drop(columns='_b', inplace=True)

In [13]:
df_giti._a = abs(df_giti._a - 1)
p(df_giti)

(20532, 62)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,0.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0

In [14]:
df_ab = f.tall2wide2(df_giti,
                     ['game_id', 'game_date', 'season', 'season_year', 
                      'season_type', 'matchup', 'a', 'b'],
                     '_a')
p(df_ab)

(10266, 114)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,E_OFF_RATING_a,OFF_RATING_a,E_DEF_RATING_a,DEF_RATING_a,E_NET_RATING_a,NET_RATING_a,AST_PCT_a,AST_TOV_a,AST_RATIO_a,OREB_PCT_a,DREB_PCT_a,REB_PCT_a,E_TM_TOV_PCT_a,TM_TOV_PCT_a,EFG_PCT_a,TS_PCT_a,USG_PCT_a,E_USG_PCT_a,E_PACE_a,PACE_a,PACE_PER40_a,POSS_a,PIE_a,duration_minutes_a,team_id_a,w_pct_a,min_a,fgm_a,fga_a,fg_pct_a,fg3m_a,fg3a_a,fg3_pct_a,ftm_a,fta_a,ft_pct_a,oreb_a,dreb_a,reb_a,ast_a,stl_a,blk_a,tov_a,pf_a,pts_a,wl_a,spread_a,away_home__a,game_date,matchup,season_type,season,season_year,a,b,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,E_OFF_RATING_b,OFF_RATING_b,E_DEF_RATING_b,DEF_RATING_b,E_NET_RATING_b,NET_RATING_b,AST_PCT_b,AST_TOV_b,AST_RATIO_b,OREB_PCT_b,DREB_PCT_b,REB_PCT_b,E_TM_TOV_PCT_b,TM_TOV_PCT_b,EFG_PCT_b,TS_PCT_b,USG_PCT_b,E_USG_PCT_b,E_PACE_b,PACE_b,PACE_PER40_b,POSS_b,PIE_b,duration_minutes_b,team_id_b,w_pct_b,min_b,fgm_b,fga_b,fg_pct_b,fg3m_b,fg3a_b,fg3_pct_b,ftm_b,fta_b,ft_pct_b,oreb_b,dreb_b,reb_b,ast_b,stl_b,blk_b,tov_b,pf_b,pts_b,wl_b,spread_b,away_home__b
0,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0
1,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1
2,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,W,-2,1
3,21000006,Heat,MIA,Miami,240:00,0 days 04:00:00,103.6,103.2,89.8,94.6,13.7,8.6,0.455,0.94,13.2,0.220,0.708,0.483,17.087,17.0,0.536,0.587,1.0,0.201,95.24,93.00,77.50,94,0.550,240.0,1610612748,0.500,240,33,69,0.478,8,16,0.500,23,31,0.741935,5,32,37,15,8,6,16,18,97,W,-10,0,2010-10-27,MIA vs. PHI,Regular Season,2010-11,2010,MIA,PHI,76ers,PHI,Philadelphia,240:00,0 days 04:00:00,89.8,94.6,103.6,103.2,-13.7,-8.6,0.667,1.26,18.3,0.292,0.780,0.517,19.620,20.7,0.476,0.495,1.0,0.193,95.24,93.00,77.50,92,0.450,240.0,1610612755,0.000,240,36,83,0.434,7,18,0.389,8,11,0.727273,10,28,38,24,10,4,16,22,87,L,10,1
4,21000005,Pistons,DET,Detroit,240:00,0 days 04:00:00,106.3,108.9,108.0,113.5,-1.7,-4.6,0.568,3.50,17.0,0.288,0.682,0.469,6.508,6.7,0.494,0.509,1.0,0.200,92.88,89.50,74.58,90,0.481,240.0,1610612765,0.000,240,37,83,0.446,8,19,0.421,16,30,0.533333,10,27,37,21,7,3,6,19,98,L,3,0,2010-10-27,DET vs. NJN,Regular Season,2010-11,2010,DET,NJN,Nets,NJN,New Jersey,240:00,0 days 04:00:00,108.0,113.5,106.3,108.9,1.7,4.6,0.436,1.42,14.2,0.318,0.712,0.531,12.826,13.5,0.525,0.558,1.0,0.197,92.88,89.50,74.58,89,0.519,240.0,1610612751,1.000,240,39,80,0.488,6,14,0.429,17,24,0.708333,9,35,44,17,4,4,11,23,101,W,-3,1
10261,41700317,Warriors,GSW,Golden State,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,W,-9,0,2018-05-28,GSW vs. HOU,Playoffs,2017-18,2017,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,L,9,1
10262,41700401,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,L,10,0,2018-05-31,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,W,-10,1
10263,41700402,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,L,19,0,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1
10264,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0
10265,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0

In [15]:

#function to perform cma_#_diff
    #specify the columns to groupby
    
    #specify the window size, and minimum
    
    #specify the columns to not take the difference for

    #specifc the df
    
    ##############################
    
    # convert to tall
    
    
    
    # take cma of numeric columns
    
    
    # rename columns to cma#
    
    
    #convert to wide, e.g. suffix '_a', '_b'
    
    #take difference of numeric columns with the same prefix, store to stat_cma#_diff
    
    #merge back to columns not taken a difference on
    
    #return the output dataframe
    

    
#get cma5, cma12, cma999

In [16]:
def wide_get_cma_num_diff3(df_, groupby_list_, not_difference_list_, suffix_list_, window_size_max_min_):
    
    
    #get suffix category column name: suffix_cat
    alphanumeric = ''
    suffix_cat = ''
    for i in range(len(suffix_list_)):
        
        for character in suffix_list_[i]:
            if character.isalnum():
                alphanumeric += character
        
        suffix_cat = suffix_cat + alphanumeric + '_'
        alphanumeric = ''

    
    column_names_list_ = list(df_.columns)
    
    column_names_first_second_list_ = [k for k in column_names_list_
                                       if not k in not_difference_list_]
    
    column_names_first_second_list_first_ = [k for k in column_names_first_second_list_
                                            if k.endswith(suffix_list_[0])]
    
    column_names_first_second_list_first_stripped_ = [k.split(suffix_list_[0])[0]
                                                     for k in column_names_first_second_list_first_]
    
    
    df_ = f.wide2tall(df_, not_difference_list_, suffix_list_)
    
    #return df_
    
    ##########issue after here#################
    

    
    column_names_number_list_ = list(df_.select_dtypes('number'))

    column_names_number_list_ = [k for k in column_names_number_list_ if not k in not_difference_list_]
    
    column_names_number_list_ = [k for k in column_names_number_list_ if not k in suffix_cat]
    
    gbl_column_names_number_list_ = groupby_list_ + [k for k in column_names_number_list_
                                                          if not k in groupby_list_] 
    
    df_numeric_gbl_ = df_[gbl_column_names_number_list_]
    
    
    df_gbl_cma_ = df_numeric_gbl_.groupby(
                                            groupby_list_).apply(lambda x:
                                            x.rolling(window_size_max_min_[0],
                                            window_size_max_min_[1]).mean().shift()
                                         )[column_names_number_list_]
    
    pre_rename_cma_drop_list_ = [k for k in column_names_number_list_ if k in groupby_list_]
    
    df_gbl_cma_.drop(columns=pre_rename_cma_drop_list_, inplace=True)
    
     
    column_names_number_list_cma_num_ = [k + '_cma' + str(window_size_max_min_[0]) for k in column_names_number_list_]
    
    column_names_number_dict_cma_num_ = dict(zip(column_names_number_list_, column_names_number_list_cma_num_))
        
    df_gbl_cma_.rename(columns=column_names_number_dict_cma_num_, inplace=True)
    
    df_gbl_cma_ = df_gbl_cma_.reset_index()
    
    df_gbl_cma_.rename(columns={'level_2': 'index'}, inplace=True)

    df_ = df_.reset_index()
    
    column_names_merged_list = ['index'] + groupby_list_
    
   
    column_names_number_list_rgbl_ = [k for k in column_names_number_list_ if not k in groupby_list_]
    
    df_dropped_ = df_.drop(columns=column_names_number_list_rgbl_)
        
    df_gbl_cma_merged_ = pd.merge(df_dropped_, df_gbl_cma_, on=column_names_merged_list)
    
    
    
    df_gbl_cma_merged_.drop(columns='index', inplace=True)
    
    #return df_gbl_cma_merged_
    
    df_wide_ = f.tall2wide2(df_gbl_cma_merged_, not_difference_list_, suffix_cat)

    df_wide_ = sr(df_wide_, 'game_date')
    
    ########issue before here############
    #return df_wide_
    
    #take difference of numeric columns with the same prefix, store to stat_cma#_diff
    
    return f.get_numeric_diff(df_wide_, groupby_list_, not_difference_list_, suffix_list_)
    
    #merge back to columns not taken a difference on

In [17]:
#f.get_numeric_diff(df_ab,
#                   ['season', 'team_id'],
#                   ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
#                   ['_a', '_b'])

In [18]:
df_stat_cma5_diff = wide_get_cma_num_diff3(df_ab,
                       ['season', 'team_id'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [5,1])
p(df_stat_cma5_diff)

(10266, 71)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000012,2010-10-27,2010-11,Regular Season,2010,Bobcats,CHA,Charlotte,240:00,0 days 04:00:00,1610612766,L,CHA vs. DAL,CHA,DAL,Mavericks,DAL,Dallas,240:00,0 days 04:00:00,1610612742,W,CHA vs. DAL,CHA,DAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.60,-3.98,3.72,4.32,-8.32,-8.34,-0.1340,-0.676,-4.22,-0.0048,0.0666,0.0312,-0.3668,-0.24,-0.0276,-2.460000e-02,0.0,-0.0010,-4.640000e-01,-0.9,-0.752,-0.6,-0.0694,0.0,-0.2000,0.0,-1.6,-2.2,-0.0070,-3.8,-2.8,-0.0758,2.6,5.4,-0.062235,0.0,1.4,1.4,-6.6,-3.8,0.8,-0.4,-0.4,-4.4,7.4,-0.2
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.66,-11.32,7.40,8.66,-18.06,-20.02,-0.1112,-0.670,-4.94,0.0206,0.0810,0.0330,-0.8788,-0.94,-0.0908,-7.860000e-02,0.0,-0.0014,-1.856000e+00,-2.0,-1.668,-1.2,-0.1148,0.0,-0.4000,0.0,-4.8,1.0,-0.0620,-4.8,-3.8,-0.0956,2.4,3.4,0.008688,3.2,-1.2,2.0,-7.4,-2.6,-1.0,-1.2,-2.2,-12.0,17.4,-0.4
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-11.30,-11.32,10.84,11.02,-22.12,-22.40,-0.1368,-0.900,-6.12,0.0752,0.1324,0.0746,0.1990,0.22,-0.1020,-8.540000e-02,0.0,-0.0024,-1.884000e+00,-1.8,-1.500,-0.6,-0.1234,0.0,-0.6000,0.0,-5.0,2.8,-0.0738,-4.6,-4.4,-0.0828,3.2,3.8,0.030279,5.2,-0.8,4.4,-8.6,-1.8,-2.4,-0.4,-2.2,-11.4,18.8,-0.2

In [19]:
df_stat_cma12_diff = wide_get_cma_num_diff3(df_ab,
                       ['season', 'team_id'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [12,1])
p(df_stat_cma12_diff)

(10266, 71)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000012,2010-10-27,2010-11,Regular Season,2010,Bobcats,CHA,Charlotte,240:00,0 days 04:00:00,1610612766,L,CHA vs. DAL,CHA,DAL,Mavericks,DAL,Dallas,240:00,0 days 04:00:00,1610612742,W,CHA vs. DAL,CHA,DAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000

In [20]:
df_stat_cma999_diff = wide_get_cma_num_diff3(df_ab,
                       ['season', 'team_id'],
                       ['game_id', 'game_date', 'season', 'season_type', 'season_year'],
                       ['_a', '_b'],
                       [999,1])
p(df_stat_cma999_diff)

(10266, 71)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000012,2010-10-27,2010-11,Regular Season,2010,Bobcats,CHA,Charlotte,240:00,0 days 04:00:00,1610612766,L,CHA vs. DAL,CHA,DAL,Mavericks,DAL,Dallas,240:00,0 days 04:00:00,1610612742,W,CHA vs. DAL,CHA,DAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-1.901545,-0.857465,5.452475,4.759653,-7.349000,-5.623109,-0.107564,-0.197637,-3.449980,0.004219,0.014580,-0.003960,-1.280636,-1.171089,-0.020696,-0.018612,0.0,-0.000144,-2.523637,-2.570218,-2.142013,-2.408911,-0.055020,0.240099,-0.148643,0.240099,-2.717525,-1.399802,-0.024299,0.413564,2.571386,-0.015929,1.359802,2.857426,-0.044027,-0.075248,-1.933762,-2.009010,-6.185050,-1.188614,-3.159208,-1.510693,-0.718020,-3.661683,5.618812,-0.014950
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-2.080421,-1.082120,5.594787,4.944341,-7.670239,-6.032392,-0.105718,-0.196316,-3.446612,0.005084,0.015359,-0.003606,-1.278266,-1.174102,-0.022503,-0.020015,0.0,-0.000172,-2.498403,-2.544582,-2.120647,-2.355271,-0.055756,0.237818,-0.157015,0.237818,-2.789361,-1.307319,-0.025657,0.350320,2.457290,-0.016600,1.415453,2.878373,-0.042104,0.013881,-1.993108,-1.979227,-6.153757,-1.117647,-3.167540,-1.515240,-0.809552,-3.812949,5.937488,-0.024655
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-2.186865,-1.165239,5.666686,4.989406,-7.848629,-6.162469,-0.106077,-0.204353,-3.473396,0.006923,0.017103,-0.002244,-1.240705,-1.133267,-0.023159,-0.020812,0.0,-0.000190,-2.473677,-2.519357,-2.099625,-2.322102,-0.056556,0.235580,-0.165224,0.235580,-2.781649,-1.187417,-0.026225,0.347135,2.482296,-0.016979,1.362840,2.831144,-0.042965,0.101371,-1.963640,-1.862269,-6.161812,-1.106606,-3.146297,-1.470969,-0.821150,-3.853322,6.035313,-0.014658

In [21]:
columns_list = (df_stat_cma999_diff.columns)
pl(columns_list)

71

Index(['game_id', 'game_date', 'season', 'season_type', 'season_year',
       'TEAM_NAME_a', 'TEAM_ABBREVIATION_a', 'TEAM_CITY_a', 'MIN_a',
       'duration_a', 'team_id_a', 'wl_a', 'matchup_a', 'a_a', 'b_a',
       'TEAM_NAME_b', 'TEAM_ABBREVIATION_b', 'TEAM_CITY_b', 'MIN_b',
       'duration_b', 'team_id_b', 'wl_b', 'matchup_b', 'a_b', 'b_b',
       'E_OFF_RATING_cma999_diff', 'OFF_RATING_cma999_diff',
       'E_DEF_RATING_cma999_diff', 'DEF_RATING_cma999_diff',
       'E_NET_RATING_cma999_diff', 'NET_RATING_cma999_diff',
       'AST_PCT_cma999_diff', 'AST_TOV_cma999_diff', 'AST_RATIO_cma999_diff',
       'OREB_PCT_cma999_diff', 'DREB_PCT_cma999_diff', 'REB_PCT_cma999_diff',
       'E_TM_TOV_PCT_cma999_diff', 'TM_TOV_PCT_cma999_diff',
       'EFG_PCT_cma999_diff', 'TS_PCT_cma999_diff', 'USG_PCT_cma999_diff',
       'E_USG_PCT_cma999_diff', 'E_PACE_cma999_diff', 'PACE_cma999_diff',
       'PACE_PER40_cma999_diff', 'POSS_cma999_diff', 'PIE_cma999_diff',
       'duration_minutes_cma999_diff', 'w_pct_cma999_diff', 'min_cma999_diff',
       'fgm_cma999_diff', 'fga_cma999_diff', 'fg_pct_cma999_diff',
       'fg3m_cma999_diff', 'fg3a_cma999_diff', 'fg3_pct_cma999_diff',
       'ftm_cma999_diff', 'fta_cma999_diff', 'ft_pct_cma999_diff',
       'oreb_cma999_diff', 'dreb_cma999_diff', 'reb_cma999_diff',
       'ast_cma999_diff', 'stl_cma999_diff', 'blk_cma999_diff',
       'tov_cma999_diff', 'pf_cma999_diff', 'pts_cma999_diff',
       'spread_cma999_diff', 'away_home__cma999_diff'],
      dtype='object')

In [22]:
columns_list_not_diff = [k for k in columns_list if not k.endswith('_diff')]
pl(columns_list_not_diff)

25

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'team_id_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'team_id_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b']

In [23]:
df_temp = pd.merge(df_stat_cma5_diff, df_stat_cma12_diff, on=columns_list_not_diff)
p(df_temp)

(10266, 117)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000012,2010-10-27,2010-11,Regular Season,2010,Bobcats,CHA,Charlotte,240:00,0 days 04:00:00,1610612766,L,CHA vs. DAL,CHA,DAL,Mavericks,DAL,Dallas,240:00,0 days 04:00:00,1610612742,W,CHA vs. DAL,CHA,DAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.60,-3.98,3.72,4.32,-8.32,-8.34,-0.1340,-0.676,-4.22,-0.0048,0.0666,0.0312,-0.3668,-0.24,-0.0276,-2.460000e-02,0.0,-0.0010,-4.640000e-01,-0.9,-0.752,-0.6,-0.0694,0.0,-0.2000,0.0,-1.6,-2.2,-0.0070,-3.8,-2.8,-0.0758,2.6,5.4,-0.062235,0.0,1.4,1.4,-6.6,-3.8,0.8,-0.4,-0.4,-4.4,7.4,-0.2,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.66,-11.32,7.40,8.66,-18.06,-20.02,-0.1112,-0.670,-4.94,0.0206,0.0810,0.0330,-0.8788,-0.94,-0.0908,-7.860000e-02,0.0,-0.0014,-1.856000e+00,-2.0,-1.668,-1.2,-0.1148,0.0,-0.4000,0.0,-4.8,1.0,-0.0620,-4.8,-3.8,-0.0956,2.4,3.4,0.008688,3.2,-1.2,2.0,-7.4,-2.6,-1.0,-1.2,-2.2,-12.0,17.4,-0.4,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-11.30,-11.32,10.84,11.02,-22.12,-22.40,-0.1368,-0.900,-6.12,0.0752,0.1324,0.0746,0.1990,0.22,-0.1020,-8.540000e-02,0.0,-0.0024,-1.884000e+00,-1.8,-1.500,-0.6,-0.1234,0.0,-0.6000,0.0,-5.0,2.8,-0.0738,-4.6,-4.4,-0.0828,3.2,3.8,0.030279,5.2,-0.8,4.4,-8.6,-1.8,-2.4,-0.4,-2.2,-11.4,18.8,-0.2,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000

In [24]:
df_temp = pd.merge(df_temp, df_stat_cma999_diff, on=columns_list_not_diff)
p(df_temp)

(10266, 163)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000012,2010-10-27,2010-11,Regular Season,2010,Bobcats,CHA,Charlotte,240:00,0 days 04:00:00,1610612766,L,CHA vs. DAL,CHA,DAL,Mavericks,DAL,Dallas,240:00,0 days 04:00:00,1610612742,W,CHA vs. DAL,CHA,DAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.60,-3.98,3.72,4.32,-8.32,-8.34,-0.1340,-0.676,-4.22,-0.0048,0.0666,0.0312,-0.3668,-0.24,-0.0276,-2.460000e-02,0.0,-0.0010,-4.640000e-01,-0.9,-0.752,-0.6,-0.0694,0.0,-0.2000,0.0,-1.6,-2.2,-0.0070,-3.8,-2.8,-0.0758,2.6,5.4,-0.062235,0.0,1.4,1.4,-6.6,-3.8,0.8,-0.4,-0.4,-4.4,7.4,-0.2,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-1.901545,-0.857465,5.452475,4.759653,-7.349000,-5.623109,-0.107564,-0.197637,-3.449980,0.004219,0.014580,-0.003960,-1.280636,-1.171089,-0.020696,-0.018612,0.0,-0.000144,-2.523637,-2.570218,-2.142013,-2.408911,-0.055020,0.240099,-0.148643,0.240099,-2.717525,-1.399802,-0.024299,0.413564,2.571386,-0.015929,1.359802,2.857426,-0.044027,-0.075248,-1.933762,-2.009010,-6.185050,-1.188614,-3.159208,-1.510693,-0.718020,-3.661683,5.618812,-0.014950
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.66,-11.32,7.40,8.66,-18.06,-20.02,-0.1112,-0.670,-4.94,0.0206,0.0810,0.0330,-0.8788,-0.94,-0.0908,-7.860000e-02,0.0,-0.0014,-1.856000e+00,-2.0,-1.668,-1.2,-0.1148,0.0,-0.4000,0.0,-4.8,1.0,-0.0620,-4.8,-3.8,-0.0956,2.4,3.4,0.008688,3.2,-1.2,2.0,-7.4,-2.6,-1.0,-1.2,-2.2,-12.0,17.4,-0.4,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-2.080421,-1.082120,5.594787,4.944341,-7.670239,-6.032392,-0.105718,-0.196316,-3.446612,0.005084,0.015359,-0.003606,-1.278266,-1.174102,-0.022503,-0.020015,0.0,-0.000172,-2.498403,-2.544582,-2.120647,-2.355271,-0.055756,0.237818,-0.157015,0.237818,-2.789361,-1.307319,-0.025657,0.350320,2.457290,-0.016600,1.415453,2.878373,-0.042104,0.013881,-1.993108,-1.979227,-6.153757,-1.117647,-3.167540,-1.515240,-0.809552,-3.812949,5.937488,-0.024655
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-11.30,-11.32,10.84,11.02,-22.12,-22.40,-0.1368,-0.900,-6.12,0.0752,0.1324,0.0746,0.1990,0.22,-0.1020,-8.540000e-02,0.0,-0.0024,-1.884000e+00,-1.8,-1.500,-0.6,-0.1234,0.0,-0.6000,0.0,-5.0,2.8,-0.0738,-4.6,-4.4,-0.0828,3.2,3.8,0.030279,5.2,-0.8,4.4,-8.6,-1.8,-2.4,-0.4,-2.2,-11.4,18.8,-0.2,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-2.186865,-1.165239,5.666686,4.989406,-7.848629,-6.162469,-0.106077,-0.204353,-3.473396,0.006923,0.017103,-0.002244,-1.240705,-1.133267,-0.023159,-0.020812,0.0,-0.000190,-2.473677,-2.519357,-2.099625,-2.322102,-0.056556,0.235580,-0.165224,0.235580,-2.781649,-1.187417,-0.026225,0.347135,2.482296,-0.016979,1.362840,2.831144,-0.042965,0.101371,-1.963640,-1.862269,-6.161812,-1.106606,-3.146297,-1.470969,-0.821150,-3.853322,6.035313,-0.014658

In [25]:
df_temp = df_temp.sort_values(['game_id', 'game_date'], ascending=[True, True])
df_temp = df_temp.reset_index(drop=True)
p(df_temp)

(10266, 163)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,L,BOS vs. CLE,BOS,CLE,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,W,BOS vs. CLE,BOS,CLE,95.70,95.70,87.90,87.90,7.70,7.70,0.7810,1.250,20.00,0.2680,0.7500,0.5280,21.7390,21.70,0.5220,5.500000e-01,1.0,0.1960,9.150000e+01,91.5,76.250,92.0,0.5990,240.0,1.0000,240.0,32.0,69.0,0.4640,8.0,16.0,0.5000,16.0,25.0,0.640000,8.0,34.0,42.0,25.0,6.0,4.0,18.0,19.0,88.0,-8.0,1.0,95.700000,95.700000,87.900000,87.900000,7.700000,7.700000,0.781000,1.250000,20.000000,0.268000,0.750000,0.528000,21.739000,21.700000,0.522000,0.550000,1.0,0.196000,91.500000,91.500000,76.250000,92.000000,0.599000,240.000000,1.000000,240.000000,32.000000,69.000000,0.464000,8.000000,16.000000,0.500000,16.000000,25.000000,0.640000,8.000000,34.000000,42.000000,25.000000,6.000000,4.000000,18.000000,19.000000,88.000000,-8.000000,1.000000,95.700000,95.700000,87.900000,87.900000,7.700000,7.700000,0.781000,1.250000,20.000000,0.268000,0.750000,0.528000,21.739000,21.700000,0.522000,0.550000,1.0,0.196000,91.500000,91.500000,76.250000,92.000000,0.599000,240.000000,1.000000,240.000000,32.000000,69.000000,0.464000,8.000000,16.000000,0.500000,16.000000,25.000000,0.640000,8.000000,34.000000,42.000000,25.000000,6.000000,4.000000,18.000000,19.000000,88.000000,-8.000000,1.000000
4,21000005,2010-10-27,2010-11,Regular Season,2010,Pistons,DET,Detroit,240:00,0 days 04:00:00,1610612765,L,DET vs. NJN,DET,NJN,Nets,NJN,New Jersey,240:00,0 days 04:00:00,1610612751,W,DET vs. NJN,DET,NJN,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.60,-3.98,3.72,4.32,-8.32,-8.34,-0.1340,-0.676,-4.22,-0.0048,0.0666,0.0312,-0.3668,-0.24,-0.0276,-2.460000e-02,0.0,-0.0010,-4.640000e-01,-0.9,-0.752,-0.6,-0.0694,0.0,-0.2000,0.0,-1.6,-2.2,-0.0070,-3.8,-2.8,-0.0758,2.6,5.4,-0.062235,0.0,1.4,1.4,-6.6,-3.8,0.8,-0.4,-0.4,-4.4,7.4,-0.2,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-1.901545,-0.857465,5.452475,4.759653,-7.349000,-5.623109,-0.107564,-0.197637,-3.449980,0.004219,0.014580,-0.003960,-1.280636,-1.171089,-0.020696,-0.018612,0.0,-0.000144,-2.523637,-2.570218,-2.142013,-2.408911,-0.055020,0.240099,-0.148643,0.240099,-2.717525,-1.399802,-0.024299,0.413564,2.571386,-0.015929,1.359802,2.857426,-0.044027,-0.075248,-1.933762,-2.009010,-6.185050,-1.188614,-3.159208,-1.510693,-0.718020,-3.661683,5.618812,-0.014950
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.66,-11.32,7.40,8.66,-18.06,-20.02,-0.1112,-0.670,-4.94,0.0206,0.0810,0.0330,-0.8788,-0.94,-0.0908,-7.860000e-02,0.0,-0.0014,-1.856000e+00,-2.0,-1.668,-1.2,-0.1148,0.0,-0.4000,0.0,-4.8,1.0,-0.0620,-4.8,-3.8,-0.0956,2.4,3.4,0.008688,3.2,-1.2,2.0,-7.4,-2.6,-1.0,-1.2,-2.2,-12.0,17.4,-0.4,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-2.080421,-1.082120,5.594787,4.944341,-7.670239,-6.032392,-0.105718,-0.196316,-3.446612,0.005084,0.015359,-0.003606,-1.278266,-1.174102,-0.022503,-0.020015,0.0,-0.000172,-2.498403,-2.544582,-2.120647,-2.355271,-0.055756,0.237818,-0.157015,0.237818,-2.789361,-1.307319,-0.025657,0.350320,2.457290,-0.016600,1.415453,2.878373,-0.042104,0.013881,-1.993108,-1.979227,-6.153757,-1.117647,-3.167540,-1.515240,-0.809552,-3.812949,5.937488,-0.024655
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-11.30,-11.32,10.84,11.02,-22.12,-22.40,-0.1368,-0.900,-6.12,0.0752,0.1324,0.0746,0.1990,0.22,-0.1020,-8.540000e-02,0.0,-0.0024,-1.884000e+00,-1.8,-1.500,-0.6,-0.1234,0.0,-0.6000,0.0,-5.0,2.8,-0.0738,-4.6,-4.4,-0.0828,3.2,3.8,0.030279,5.2,-0.8,4.4,-8.6,-1.8,-2.4,-0.4,-2.2,-11.4,18.8,-0.2,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-2.186865,-1.165239,5.666686,4.989406,-7.848629,-6.162469,-0.106077,-0.204353,-3.473396,0.006923,0.017103,-0.002244,-1.240705,-1.133267,-0.023159,-0.020812,0.0,-0.000190,-2.473677,-2.519357,-2.099625,-2.322102,-0.056556,0.235580,-0.165224,0.235580,-2.781649,-1.187417,-0.026225,0.347135,2.482296,-0.016979,1.362840,2.831144,-0.042965,0.101371,-1.963640,-1.862269,-6.161812,-1.106606,-3.146297,-1.470969,-0.821150,-3.853322,6.035313,-0.014658

In [26]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '55Astat_cma5_cma12_cma999_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_temp.to_csv(datapath_df, index=False)

In [27]:
df_stat_cma5_cma12_cma999_diff_readback = rcp('55Astat_cma5_cma12_cma999_diff_2010_2018.csv')
p(df_stat_cma5_cma12_cma999_diff_readback)

(10266, 163)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,2010-10-27,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,L,BOS vs. CLE,BOS,CLE,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,W,BOS vs. CLE,BOS,CLE,95.70,95.70,87.90,87.90,7.70,7.70,0.7810,1.250,20.00,0.2680,0.7500,0.5280,21.7390,21.70,0.5220,5.500000e-01,1.0,0.1960,9.150000e+01,91.5,76.250,92.0,0.5990,240.0,1.0000,240.0,32.0,69.0,0.4640,8.0,16.0,0.5000,16.0,25.0,0.640000,8.0,34.0,42.0,25.0,6.0,4.0,18.0,19.0,88.0,-8.0,1.0,95.700000,95.700000,87.900000,87.900000,7.700000,7.700000,0.781000,1.250000,20.000000,0.268000,0.750000,0.528000,21.739000,21.700000,0.522000,0.550000,1.0,0.196000,91.500000,91.500000,76.250000,92.000000,0.599000,240.000000,1.000000,240.000000,32.000000,69.000000,0.464000,8.000000,16.000000,0.500000,16.000000,25.000000,0.640000,8.000000,34.000000,42.000000,25.000000,6.000000,4.000000,18.000000,19.000000,88.000000,-8.000000,1.000000,95.700000,95.700000,87.900000,87.900000,7.700000,7.700000,0.781000,1.250000,20.000000,0.268000,0.750000,0.528000,21.739000,21.700000,0.522000,0.550000,1.0,0.196000,91.500000,91.500000,76.250000,92.000000,0.599000,240.000000,1.000000,240.000000,32.000000,69.000000,0.464000,8.000000,16.000000,0.500000,16.000000,25.000000,0.640000,8.000000,34.000000,42.000000,25.000000,6.000000,4.000000,18.000000,19.000000,88.000000,-8.000000,1.000000
4,21000005,2010-10-27,2010-11,Regular Season,2010,Pistons,DET,Detroit,240:00,0 days 04:00:00,1610612765,L,DET vs. NJN,DET,NJN,Nets,NJN,New Jersey,240:00,0 days 04:00:00,1610612751,W,DET vs. NJN,DET,NJN,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.60,-3.98,3.72,4.32,-8.32,-8.34,-0.1340,-0.676,-4.22,-0.0048,0.0666,0.0312,-0.3668,-0.24,-0.0276,-2.460000e-02,0.0,-0.0010,-4.640000e-01,-0.9,-0.752,-0.6,-0.0694,0.0,-0.2000,0.0,-1.6,-2.2,-0.0070,-3.8,-2.8,-0.0758,2.6,5.4,-0.062235,0.0,1.4,1.4,-6.6,-3.8,0.8,-0.4,-0.4,-4.4,7.4,-0.2,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-1.901545,-0.857465,5.452475,4.759653,-7.349000,-5.623109,-0.107564,-0.197637,-3.449980,0.004219,0.014580,-0.003960,-1.280636,-1.171089,-0.020696,-0.018612,0.0,-0.000144,-2.523637,-2.570218,-2.142013,-2.408911,-0.055020,0.240099,-0.148643,0.240099,-2.717525,-1.399802,-0.024299,0.413564,2.571386,-0.015929,1.359802,2.857426,-0.044027,-0.075248,-1.933762,-2.009010,-6.185050,-1.188614,-3.159208,-1.510693,-0.718020,-3.661683,5.618812,-0.014950
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.66,-11.32,7.40,8.66,-18.06,-20.02,-0.1112,-0.670,-4.94,0.0206,0.0810,0.0330,-0.8788,-0.94,-0.0908,-7.860000e-02,0.0,-0.0014,-1.856000e+00,-2.0,-1.668,-1.2,-0.1148,0.0,-0.4000,0.0,-4.8,1.0,-0.0620,-4.8,-3.8,-0.0956,2.4,3.4,0.008688,3.2,-1.2,2.0,-7.4,-2.6,-1.0,-1.2,-2.2,-12.0,17.4,-0.4,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-2.080421,-1.082120,5.594787,4.944341,-7.670239,-6.032392,-0.105718,-0.196316,-3.446612,0.005084,0.015359,-0.003606,-1.278266,-1.174102,-0.022503,-0.020015,0.0,-0.000172,-2.498403,-2.544582,-2.120647,-2.355271,-0.055756,0.237818,-0.157015,0.237818,-2.789361,-1.307319,-0.025657,0.350320,2.457290,-0.016600,1.415453,2.878373,-0.042104,0.013881,-1.993108,-1.979227,-6.153757,-1.117647,-3.167540,-1.515240,-0.809552,-3.812949,5.937488,-0.024655
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-11.30,-11.32,10.84,11.02,-22.12,-22.40,-0.1368,-0.900,-6.12,0.0752,0.1324,0.0746,0.1990,0.22,-0.1020,-8.540000e-02,0.0,-0.0024,-1.884000e+00,-1.8,-1.500,-0.6,-0.1234,0.0,-0.6000,0.0,-5.0,2.8,-0.0738,-4.6,-4.4,-0.0828,3.2,3.8,0.030279,5.2,-0.8,4.4,-8.6,-1.8,-2.4,-0.4,-2.2,-11.4,18.8,-0.2,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-2.186865,-1.165239,5.666686,4.989406,-7.848629,-6.162469,-0.106077,-0.204353,-3.473396,0.006923,0.017103,-0.002244,-1.240705,-1.133267,-0.023159,-0.020812,0.0,-0.000190,-2.473677,-2.519357,-2.099625,-2.322102,-0.056556,0.235580,-0.165224,0.235580,-2.781649,-1.187417,-0.026225,0.347135,2.482296,-0.016979,1.362840,2.831144,-0.042965,0.101371,-1.963640,-1.862269,-6.161812,-1.106606,-3.146297,-1.470969,-0.821150,-3.853322,6.035313,-0.014658