In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
df_stat_season_matchup_cma12_diff = rcp('52Astat_season_matchup_cma12_diff_2010_2018_my_functions.csv')
p(df_stat_season_matchup_cma12_diff)

(10266, 71)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000

In [3]:
column_names_list = list(df_stat_season_matchup_cma12_diff.columns)
pl(column_names_list)

71

['game_id',
 'TEAM_ABBREVIATION_a',
 'TEAM_ABBREVIATION_b',
 'team_id_a',
 'team_id_b',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'E_OFF_RATING_sm_cma12_diff',
 'OFF_RATING_sm_cma12_diff',
 'E_DEF_RATING_sm_cma12_diff',
 'DEF_RATING_sm_cma12_diff',
 'E_NET_RATING_sm_cma12_diff',
 'NET_RATING_sm_cma12_diff',
 'AST_PCT_sm_cma12_diff',
 'AST_TOV_sm_cma12_diff',
 'AST_RATIO_sm_cma12_diff',
 'OREB_PCT_sm_cma12_diff',
 'DREB_PCT_sm_cma12_diff',
 'REB_PCT_sm_cma12_diff',
 'E_TM_TOV_PCT_sm_cma12_diff',
 'TM_TOV_PCT_sm_cma12_diff',
 'EFG_PCT_sm_cma12_diff',
 'TS_PCT_sm_cma12_diff',
 'USG_PCT_sm_cma12_diff',
 'E_USG_PCT_sm_cma12_diff',
 'E_PACE_sm_cma12_diff',
 'PACE_sm_cma12_diff',
 'PACE_PER40_sm_cma12_diff',
 'POSS_sm_cma12_diff',
 'PIE_sm_cma12_diff',
 'duration_minutes_sm_cma12_diff',
 'w_pct_sm_cma12_diff',
 'min_sm_cma12_diff',
 'fgm_sm_cma12_diff',
 'fga_sm_cma12_diff',
 'fg_pct_sm_cma12_diff',
 'fg3m_sm_cma12_diff',
 'fg3a_sm_cma12_diff',
 'fg3_pct_sm_cma12_diff',
 'ftm_sm_cma12_diff',
 'fta_sm_cma12_diff',
 'ft_pct_sm_cma12_diff',
 'oreb_sm_cma12_diff',
 'dreb_sm_cma12_diff',
 'reb_sm_cma12_diff',
 'ast_sm_cma12_diff',
 'stl_sm_cma12_diff',
 'blk_sm_cma12_diff',
 'tov_sm_cma12_diff',
 'pf_sm_cma12_diff',
 'pts_sm_cma12_diff',
 'spread_sm_cma12_diff',
 'away_home_sm_cma12_diff']

In [4]:
column_names_list_diff = [k for k in column_names_list if k.endswith('_diff')]
pl(column_names_list_diff)

46

['E_OFF_RATING_sm_cma12_diff',
 'OFF_RATING_sm_cma12_diff',
 'E_DEF_RATING_sm_cma12_diff',
 'DEF_RATING_sm_cma12_diff',
 'E_NET_RATING_sm_cma12_diff',
 'NET_RATING_sm_cma12_diff',
 'AST_PCT_sm_cma12_diff',
 'AST_TOV_sm_cma12_diff',
 'AST_RATIO_sm_cma12_diff',
 'OREB_PCT_sm_cma12_diff',
 'DREB_PCT_sm_cma12_diff',
 'REB_PCT_sm_cma12_diff',
 'E_TM_TOV_PCT_sm_cma12_diff',
 'TM_TOV_PCT_sm_cma12_diff',
 'EFG_PCT_sm_cma12_diff',
 'TS_PCT_sm_cma12_diff',
 'USG_PCT_sm_cma12_diff',
 'E_USG_PCT_sm_cma12_diff',
 'E_PACE_sm_cma12_diff',
 'PACE_sm_cma12_diff',
 'PACE_PER40_sm_cma12_diff',
 'POSS_sm_cma12_diff',
 'PIE_sm_cma12_diff',
 'duration_minutes_sm_cma12_diff',
 'w_pct_sm_cma12_diff',
 'min_sm_cma12_diff',
 'fgm_sm_cma12_diff',
 'fga_sm_cma12_diff',
 'fg_pct_sm_cma12_diff',
 'fg3m_sm_cma12_diff',
 'fg3a_sm_cma12_diff',
 'fg3_pct_sm_cma12_diff',
 'ftm_sm_cma12_diff',
 'fta_sm_cma12_diff',
 'ft_pct_sm_cma12_diff',
 'oreb_sm_cma12_diff',
 'dreb_sm_cma12_diff',
 'reb_sm_cma12_diff',
 'ast_sm_cma12_diff',
 'stl_sm_cma12_diff',
 'blk_sm_cma12_diff',
 'tov_sm_cma12_diff',
 'pf_sm_cma12_diff',
 'pts_sm_cma12_diff',
 'spread_sm_cma12_diff',
 'away_home_sm_cma12_diff']

In [5]:
column_names_list_not_diff = [k for k in column_names_list if not k in column_names_list_diff]
pl(column_names_list_not_diff)

25

['game_id',
 'TEAM_ABBREVIATION_a',
 'TEAM_ABBREVIATION_b',
 'team_id_a',
 'team_id_b',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b']

In [6]:
df_stat_season_matchup_cmax12_diff = rcp('52Bstat_season_matchup_cmax12_diff_2010_2018_my_functions.csv')
p(df_stat_season_matchup_cmax12_diff)

(10266, 117)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,7.7,5.3,-7.7,-5.3,24.1,24.6,0.195,0.54,5.2,0.022,-0.080,-0.011,-2.597,-3.6,0.036,0.042,0.0,0.003,0.0,0.0,0.0,-1.0,0.121,0.0,0.000,0.0,1.0,-5.0,0.041,0.0,-12.0,0.148,-5.0,-7.0,0.092593,4.0,2.0,2.0,7.0,-3.0,1.0,-2.0,1.0,-1.0,-19.0,0.0,4.8,4.341667,-1.091667,0.325000,1.858333,0.991667,0.138250,0.127500,5.841667,-0.029333,-0.010333,0.005583,1.6335,1.641667,0.043583,0.035917,0.0,0.00125,1.653333,1.111667,0.925833,-0.916667,0.033583,-2.083333,0.067583,-2.083333,4.916667,-1.416667,0.068167,-4.250000,-13.50,0.036083,-3.416667,-5.333333,0.029458,-1.166667,1.833333,3.000000,8.916667,0.000000,1.750000,1.333333,-1.416667,3.000000,0.00,0.083333
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-14.3,-9.7,14.3,9.7,-21.1,-18.2,-0.200,-0.21,-4.3,0.017,0.054,-0.001,-1.740,-1.8,-0.058,-0.080,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.094,0.0,2.0,9.0,-0.025,3.0,-1.0,0.042,-3.0,-5.0,0.040000,6.0,-6.0,2.0,-7.0,1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-3.650000,-1.950000,-0.059667,-0.265000,-1.658333,-0.028250,0.023667,-0.023000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.461667,-2.125000,-1.770000,-2.666667,-0.051583,-4.166667,-0.078667,-4.166667,-2.666667,-0.833333,-0.008500,3.666667,6.00,0.049583,1.416667,2.250000,-0.010437,0.500000,-3.333333,-2.833333,-4.250000,-0.583333,-4.833333,-2.833333,-1.333333,-2.833333,10.75,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-8.5,-12.4,8.5,12.4,-21.1,-20.9,-0.200,-2.15,-4.5,0.071,0.126,0.059,-1.740,-1.8,-0.088,-0.104,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-2.0,9.0,-0.054,2.0,0.0,0.042,-3.0,-5.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,-0.000167,-0.009833,0.002167,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,-2.083333,-0.078667,-2.083333,-2.666667,-3.083333,-0.008500,2.583333,2.00,0.049583,1.416667,2.750000,-0.010437,-0.250000,-3.083333,-4.166667,-4.250000,-1.333333,-3.583333,-2.833333,0.666667,-2.833333,10.75,0.000000
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,0.002667,0.001917,0.007250,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.416667,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,0.500000,-2.833333,10.75,0.000000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.341667,-2.608333,-0.059667,-0.098333,-1.658333,0.006750,0.009083,0.011000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.250000,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,-0.083333,-2.833333,10.75,0.000000

In [7]:
df_stat_season_matchup_cma12_diff_cmax12_diff = pd.merge(df_stat_season_matchup_cma12_diff, df_stat_season_matchup_cmax12_diff, on=column_names_list_not_diff)
p(df_stat_season_matchup_cma12_diff_cmax12_diff)

(10266, 163)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,7.7,5.3,-7.7,-5.3,24.1,24.6,0.195,0.54,5.2,0.022,-0.080,-0.011,-2.597,-3.6,0.036,0.042,0.0,0.003,0.0,0.0,0.0,-1.0,0.121,0.0,0.000,0.0,1.0,-5.0,0.041,0.0,-12.0,0.148,-5.0,-7.0,0.092593,4.0,2.0,2.0,7.0,-3.0,1.0,-2.0,1.0,-1.0,-19.0,0.0,4.8,4.341667,-1.091667,0.325000,1.858333,0.991667,0.138250,0.127500,5.841667,-0.029333,-0.010333,0.005583,1.6335,1.641667,0.043583,0.035917,0.0,0.00125,1.653333,1.111667,0.925833,-0.916667,0.033583,-2.083333,0.067583,-2.083333,4.916667,-1.416667,0.068167,-4.250000,-13.50,0.036083,-3.416667,-5.333333,0.029458,-1.166667,1.833333,3.000000,8.916667,0.000000,1.750000,1.333333,-1.416667,3.000000,0.00,0.083333
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,-14.3,-9.7,14.3,9.7,-21.1,-18.2,-0.200,-0.21,-4.3,0.017,0.054,-0.001,-1.740,-1.8,-0.058,-0.080,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.094,0.0,2.0,9.0,-0.025,3.0,-1.0,0.042,-3.0,-5.0,0.040000,6.0,-6.0,2.0,-7.0,1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-3.650000,-1.950000,-0.059667,-0.265000,-1.658333,-0.028250,0.023667,-0.023000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.461667,-2.125000,-1.770000,-2.666667,-0.051583,-4.166667,-0.078667,-4.166667,-2.666667,-0.833333,-0.008500,3.666667,6.00,0.049583,1.416667,2.250000,-0.010437,0.500000,-3.333333,-2.833333,-4.250000,-0.583333,-4.833333,-2.833333,-1.333333,-2.833333,10.75,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,-8.5,-12.4,8.5,12.4,-21.1,-20.9,-0.200,-2.15,-4.5,0.071,0.126,0.059,-1.740,-1.8,-0.088,-0.104,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-2.0,9.0,-0.054,2.0,0.0,0.042,-3.0,-5.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,-0.000167,-0.009833,0.002167,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,-2.083333,-0.078667,-2.083333,-2.666667,-3.083333,-0.008500,2.583333,2.00,0.049583,1.416667,2.750000,-0.010437,-0.250000,-3.083333,-4.166667,-4.250000,-1.333333,-3.583333,-2.833333,0.666667,-2.833333,10.75,0.000000
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,0.002667,0.001917,0.007250,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.416667,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,0.500000,-2.833333,10.75,0.000000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.341667,-2.608333,-0.059667,-0.098333,-1.658333,0.006750,0.009083,0.011000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.250000,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,-0.083333,-2.833333,10.75,0.000000

In [8]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '58Cstat_season_matchup_cmax12_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_stat_season_matchup_cma12_diff_cmax12_diff.to_csv(datapath_df, index=False)

In [9]:
df_readback = rcp('58Cstat_season_matchup_cmax12_diff_2010_2018.csv')
p(df_readback)

(10266, 163)

,game_id,TEAM_ABBREVIATION_a,TEAM_ABBREVIATION_b,team_id_a,team_id_b,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_CITY_a,MIN_a,duration_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_CITY_b,MIN_b,duration_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_sm_cma12_diff,OFF_RATING_sm_cma12_diff,E_DEF_RATING_sm_cma12_diff,DEF_RATING_sm_cma12_diff,E_NET_RATING_sm_cma12_diff,NET_RATING_sm_cma12_diff,AST_PCT_sm_cma12_diff,AST_TOV_sm_cma12_diff,AST_RATIO_sm_cma12_diff,OREB_PCT_sm_cma12_diff,DREB_PCT_sm_cma12_diff,REB_PCT_sm_cma12_diff,E_TM_TOV_PCT_sm_cma12_diff,TM_TOV_PCT_sm_cma12_diff,EFG_PCT_sm_cma12_diff,TS_PCT_sm_cma12_diff,USG_PCT_sm_cma12_diff,E_USG_PCT_sm_cma12_diff,E_PACE_sm_cma12_diff,PACE_sm_cma12_diff,PACE_PER40_sm_cma12_diff,POSS_sm_cma12_diff,PIE_sm_cma12_diff,duration_minutes_sm_cma12_diff,w_pct_sm_cma12_diff,min_sm_cma12_diff,fgm_sm_cma12_diff,fga_sm_cma12_diff,fg_pct_sm_cma12_diff,fg3m_sm_cma12_diff,fg3a_sm_cma12_diff,fg3_pct_sm_cma12_diff,ftm_sm_cma12_diff,fta_sm_cma12_diff,ft_pct_sm_cma12_diff,oreb_sm_cma12_diff,dreb_sm_cma12_diff,reb_sm_cma12_diff,ast_sm_cma12_diff,stl_sm_cma12_diff,blk_sm_cma12_diff,tov_sm_cma12_diff,pf_sm_cma12_diff,pts_sm_cma12_diff,spread_sm_cma12_diff,away_home_sm_cma12_diff,E_OFF_RATING_sm_cmax12_diff,OFF_RATING_sm_cmax12_diff,E_DEF_RATING_sm_cmax12_diff,DEF_RATING_sm_cmax12_diff,E_NET_RATING_sm_cmax12_diff,NET_RATING_sm_cmax12_diff,AST_PCT_sm_cmax12_diff,AST_TOV_sm_cmax12_diff,AST_RATIO_sm_cmax12_diff,OREB_PCT_sm_cmax12_diff,DREB_PCT_sm_cmax12_diff,REB_PCT_sm_cmax12_diff,E_TM_TOV_PCT_sm_cmax12_diff,TM_TOV_PCT_sm_cmax12_diff,EFG_PCT_sm_cmax12_diff,TS_PCT_sm_cmax12_diff,USG_PCT_sm_cmax12_diff,E_USG_PCT_sm_cmax12_diff,E_PACE_sm_cmax12_diff,PACE_sm_cmax12_diff,PACE_PER40_sm_cmax12_diff,POSS_sm_cmax12_diff,PIE_sm_cmax12_diff,duration_minutes_sm_cmax12_diff,w_pct_sm_cmax12_diff,min_sm_cmax12_diff,fgm_sm_cmax12_diff,fga_sm_cmax12_diff,fg_pct_sm_cmax12_diff,fg3m_sm_cmax12_diff,fg3a_sm_cmax12_diff,fg3_pct_sm_cmax12_diff,ftm_sm_cmax12_diff,fta_sm_cmax12_diff,ft_pct_sm_cmax12_diff,oreb_sm_cmax12_diff,dreb_sm_cmax12_diff,reb_sm_cmax12_diff,ast_sm_cmax12_diff,stl_sm_cmax12_diff,blk_sm_cmax12_diff,tov_sm_cmax12_diff,pf_sm_cmax12_diff,pts_sm_cmax12_diff,spread_sm_cmax12_diff,away_home_sm_cmax12_diff,E_OFF_RATING_cma_sm_cmax12_diff,OFF_RATING_cma_sm_cmax12_diff,E_DEF_RATING_cma_sm_cmax12_diff,DEF_RATING_cma_sm_cmax12_diff,E_NET_RATING_cma_sm_cmax12_diff,NET_RATING_cma_sm_cmax12_diff,AST_PCT_cma_sm_cmax12_diff,AST_TOV_cma_sm_cmax12_diff,AST_RATIO_cma_sm_cmax12_diff,OREB_PCT_cma_sm_cmax12_diff,DREB_PCT_cma_sm_cmax12_diff,REB_PCT_cma_sm_cmax12_diff,E_TM_TOV_PCT_cma_sm_cmax12_diff,TM_TOV_PCT_cma_sm_cmax12_diff,EFG_PCT_cma_sm_cmax12_diff,TS_PCT_cma_sm_cmax12_diff,USG_PCT_cma_sm_cmax12_diff,E_USG_PCT_cma_sm_cmax12_diff,E_PACE_cma_sm_cmax12_diff,PACE_cma_sm_cmax12_diff,PACE_PER40_cma_sm_cmax12_diff,POSS_cma_sm_cmax12_diff,PIE_cma_sm_cmax12_diff,duration_minutes_cma_sm_cmax12_diff,w_pct_cma_sm_cmax12_diff,min_cma_sm_cmax12_diff,fgm_cma_sm_cmax12_diff,fga_cma_sm_cmax12_diff,fg_pct_cma_sm_cmax12_diff,fg3m_cma_sm_cmax12_diff,fg3a_cma_sm_cmax12_diff,fg3_pct_cma_sm_cmax12_diff,ftm_cma_sm_cmax12_diff,fta_cma_sm_cmax12_diff,ft_pct_cma_sm_cmax12_diff,oreb_cma_sm_cmax12_diff,dreb_cma_sm_cmax12_diff,reb_cma_sm_cmax12_diff,ast_cma_sm_cmax12_diff,stl_cma_sm_cmax12_diff,blk_cma_sm_cmax12_diff,tov_cma_sm_cmax12_diff,pf_cma_sm_cmax12_diff,pts_cma_sm_cmax12_diff,spread_cma_sm_cmax12_diff,away_home_cma_sm_cmax12_diff
0,21000001,BOS,MIA,1610612738,1610612748,2010-10-26,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,W,BOS vs. MIA,BOS,MIA,Heat,Miami,240:00,0 days 04:00:00,L,BOS vs. MIA,BOS,MIA,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
1,21000002,PHX,POR,1610612756,1610612757,2010-10-26,2010-11,Regular Season,2010,Suns,Phoenix,240:00,0 days 04:00:00,L,PHX vs. POR,PHX,POR,Trail Blazers,Portland,240:00,0 days 04:00:00,W,PHX vs. POR,PHX,POR,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
2,21000003,HOU,LAL,1610612745,1610612747,2010-10-26,2010-11,Regular Season,2010,Rockets,Houston,240:00,0 days 04:00:00,L,HOU vs. LAL,HOU,LAL,Lakers,Los Angeles,240:00,0 days 04:00:00,W,HOU vs. LAL,HOU,LAL,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
3,21000004,BOS,CLE,1610612738,1610612739,2010-10-27,2010-11,Regular Season,2010,Celtics,Boston,240:00,0 days 04:00:00,L,BOS vs. CLE,BOS,CLE,Cavaliers,Cleveland,240:00,0 days 04:00:00,W,BOS vs. CLE,BOS,CLE,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
4,21000005,DET,NJN,1610612765,1610612751,2010-10-27,2010-11,Regular Season,2010,Pistons,Detroit,240:00,0 days 04:00:00,L,DET vs. NJN,DET,NJN,Nets,New Jersey,240:00,0 days 04:00:00,W,DET vs. NJN,DET,NJN,0.000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
10261,41700317,GSW,HOU,1610612744,1610612745,2018-05-28,2017-18,Playoffs,2017,Warriors,Golden State,240:00,0 days 04:00:00,W,GSW vs. HOU,GSW,HOU,Rockets,Houston,240:00,0 days 04:00:00,L,GSW vs. HOU,GSW,HOU,8.900,6.222222,-8.900,-6.222222,17.800000,12.422222,0.117111,0.593333,4.611111,-0.035333,-0.035333,-0.002444,-0.648444,-0.966667,0.04500,0.047778,0.0,0.002111,0.0,0.0,0.0,0.111111,0.106000,0.0,0.028778,0.0,3.777778,-0.555556,0.050778,-1.111111,-8.777778,0.059333,-0.333333,-3.333333,0.117998,-0.666667,0.888889,0.222222,6.555556,-0.222222,2.222222,0.111111,1.444444,6.111111,-12.222222,-0.111111,7.7,5.3,-7.7,-5.3,24.1,24.6,0.195,0.54,5.2,0.022,-0.080,-0.011,-2.597,-3.6,0.036,0.042,0.0,0.003,0.0,0.0,0.0,-1.0,0.121,0.0,0.000,0.0,1.0,-5.0,0.041,0.0,-12.0,0.148,-5.0,-7.0,0.092593,4.0,2.0,2.0,7.0,-3.0,1.0,-2.0,1.0,-1.0,-19.0,0.0,4.8,4.341667,-1.091667,0.325000,1.858333,0.991667,0.138250,0.127500,5.841667,-0.029333,-0.010333,0.005583,1.6335,1.641667,0.043583,0.035917,0.0,0.00125,1.653333,1.111667,0.925833,-0.916667,0.033583,-2.083333,0.067583,-2.083333,4.916667,-1.416667,0.068167,-4.250000,-13.50,0.036083,-3.416667,-5.333333,0.029458,-1.166667,1.833333,3.000000,8.916667,0.000000,1.750000,1.333333,-1.416667,3.000000,0.00,0.083333
10262,41700401,CLE,GSW,1610612739,1610612744,2018-05-31,2017-18,Playoffs,2017,Cavaliers,Cleveland,265:00,0 days 04:25:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,265:00,0 days 04:25:00,W,CLE vs. GSW,CLE,GSW,-10.600,-9.100000,10.600,9.100000,-21.100000,-18.200000,-0.254000,-0.610000,-7.900000,0.035500,0.035500,-0.001000,-1.777500,-1.600000,-0.08950,-0.084000,0.0,0.000000,0.0,0.0,0.0,0.500000,-0.205000,0.0,-0.141500,0.0,-4.000000,7.500000,-0.085000,0.000000,-2.500000,0.011000,-0.500000,0.000000,-0.021444,4.000000,-5.000000,-1.000000,-11.500000,1.000000,-4.000000,-1.000000,0.000000,-8.500000,17.000000,0.000000,-14.3,-9.7,14.3,9.7,-21.1,-18.2,-0.200,-0.21,-4.3,0.017,0.054,-0.001,-1.740,-1.8,-0.058,-0.080,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.094,0.0,2.0,9.0,-0.025,3.0,-1.0,0.042,-3.0,-5.0,0.040000,6.0,-6.0,2.0,-7.0,1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-3.650000,-1.950000,-0.059667,-0.265000,-1.658333,-0.028250,0.023667,-0.023000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.461667,-2.125000,-1.770000,-2.666667,-0.051583,-4.166667,-0.078667,-4.166667,-2.666667,-0.833333,-0.008500,3.666667,6.00,0.049583,1.416667,2.250000,-0.010437,0.500000,-3.333333,-2.833333,-4.250000,-0.583333,-4.833333,-2.833333,-1.333333,-2.833333,10.75,0.000000
10263,41700402,CLE,GSW,1610612739,1610612744,2018-06-03,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-9.900,-10.200000,9.900,10.200000,-19.733333,-20.400000,-0.257667,-1.200000,-8.433333,0.099000,0.099000,0.058000,0.155000,0.200000,-0.08900,-0.090667,0.0,0.000667,0.0,0.0,0.0,1.000000,-0.199333,0.0,-0.427667,0.0,-3.333333,8.000000,-0.079000,-1.000000,-1.333333,-0.023000,-1.333333,0.666667,-0.088538,7.666667,-3.333333,4.333333,-12.000000,-1.000000,-3.666667,0.666667,0.000000,-9.000000,18.000000,-0.333333,-8.5,-12.4,8.5,12.4,-21.1,-20.9,-0.200,-2.15,-4.5,0.071,0.126,0.059,-1.740,-1.8,-0.088,-0.104,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-2.0,9.0,-0.054,2.0,0.0,0.042,-3.0,-5.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-2.0,-1.0,-1.0,-10.0,17.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,-0.000167,-0.009833,0.002167,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,-2.083333,-0.078667,-2.083333,-2.666667,-3.083333,-0.008500,2.583333,2.00,0.049583,1.416667,2.750000,-0.010437,-0.250000,-3.083333,-4.166667,-4.250000,-1.333333,-3.583333,-2.833333,0.666667,-2.833333,10.75,0.000000
10264,41700403,CLE,GSW,1610612739,1610612744,2018-06-06,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.425,-13.550000,12.425,13.550000,-24.800000,-27.100000,-0.173250,-0.915000,-7.100000,0.097500,0.097500,0.051500,-0.149500,-0.225000,-0.11775,-0.108250,0.0,-0.000250,0.0,0.0,0.0,1.500000,-0.182000,0.0,-0.570750,0.0,-5.000000,8.000000,-0.099750,-2.250000,-3.250000,-0.038250,0.750000,1.750000,-0.028858,8.000000,-4.500000,3.500000,-9.750000,0.750000,-3.750000,0.000000,-2.500000,-11.500000,23.000000,-0.500000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.133333,-1.950000,-0.059667,-0.098333,-1.658333,0.002667,0.001917,0.007250,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.416667,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,0.500000,-2.833333,10.75,0.000000
10265,41700404,CLE,GSW,1610612739,1610612744,2018-06-08,2017-18,Playoffs,2017,Cavaliers,Cleveland,240:00,0 days 04:00:00,L,CLE vs. GSW,CLE,GSW,Warriors,Golden State,240:00,0 days 04:00:00,W,CLE vs. GSW,CLE,GSW,-12.540,-12.760000,12.540,12.760000,-25.040000,-25.560000,-0.167200,-0.936000,-6.920000,0.116800,0.116800,0.068400,0.392200,0.420000,-0.11220,-0.107000,0.0,-0.000600,0.0,0.0,0.0,1.400000,-0.173200,0.0,-0.656600,0.0,-4.400000,8.600000,-0.096600,-1.800000,-1.600000,-0.041800,-0.200000,1.000000,-0.049093,8.200000,-3.400000,4.800000,-9.200000,0.600000,-3.200000,0.600000,-2.400000,-10.800000,21.600000,-0.200000,-14.7,-16.9,14.7,16.9,-26.9,-32.1,-0.129,-1.61,-4.3,0.071,0.126,0.059,-1.740,-1.8,-0.170,-0.145,0.0,0.000,0.0,0.0,0.0,0.0,-0.205,0.0,-0.294,0.0,-3.0,9.0,-0.116,0.0,0.0,0.000,-3.0,-4.0,-0.110000,6.0,-3.0,5.0,-7.0,-1.0,-3.0,-1.0,-3.0,-10.0,26.0,0.0,1.7,1.566667,4.091667,3.666667,-4.341667,-2.608333,-0.059667,-0.098333,-1.658333,0.006750,0.009083,0.011000,-1.8750,-1.950000,0.017333,0.014667,0.0,-0.00050,-2.518333,-3.250000,-2.708333,-3.250000,-0.049167,0.000000,-0.078667,0.000000,-2.666667,-3.083333,-0.008500,2.250000,1.25,0.049583,1.416667,2.750000,-0.011629,-0.250000,-2.666667,-3.500000,-4.250000,-1.500000,-3.583333,-2.833333,-0.083333,-2.833333,10.75,0.000000