In [1]:
#########################################################################
# team, score, and betting data to be read in: df_team_score_betting

#######################################

# '16lc_mean_advanced_stat_2010_2018' csv read in
# '16lc_sum_advanced_stat_2010_2018' csv read in

######################################
#df_lc_mean and df_lc_sum to be combined: df_lc_mean_sum

#merge with game_id's, team_id's for 2010-11 thru 2017-18 seasons by reading in 3game_id (game_id, team_id); merge left on 3game_id

#fill games with NaN for lost contribution with 0

#######################################
#combine betting data with lost_contributions

#a. for each rows with a team_id and game_id, determine which row is the team_id_home and which is the team_id_away

#a1. who got drop durring the merges?

#b. rename columns to fit _home or _away

#c. concat dataframes

#d. fillna with 0 for lc_ columns

#e. groupby game_id, (season), (game_date) and sum

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [4]:
#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)

In [5]:
#########################################################################
# team, score, and betting data to be read in: df_team_score_betting

In [6]:
#df_game_betting_totals = rcp('4game_id_team_stats_betting_totals_2010_2018.csv')
#p(df_game_betting_totals)

In [7]:
df_lc_mean = rcp('16lc_mean_advanced_stat_2010_2018.csv')
p(df_lc_mean)

(20311, 27)

,game_id,team_id,game_date,season,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE
0,21000001,1610612738,2010-10-26,2010-11,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514
1,21000001,1610612748,2010-10-26,2010-11,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554
2,21000002,1610612756,2010-10-26,2010-11,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185
3,21000002,1610612757,2010-10-26,2010-11,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189
4,21000003,1610612745,2010-10-26,2010-11,18.237058,103.083691,101.991884,109.643843,107.791137,-6.560510,-5.795635,0.130807,0.922178,15.915759,0.067448,0.104606,0.086781,12.203563,0.399779,0.464099,0.180372,0.185269,98.033553,99.879772,83.233032,36.359572,0.070067
20306,41700317,1610612745,2018-05-28,2017-18,17.371998,106.539981,103.469548,102.545493,100.922664,3.986356,2.547958,0.155524,0.869058,17.297724,0.048828,0.141544,0.093529,13.121519,0.417519,0.454192,0.164833,0.171658,99.125762,102.354887,85.295398,35.968712,0.084332
20307,41700401,1610612744,2018-05-31,2017-18,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176
20308,41700403,1610612739,2018-06-06,2017-18,13.084615,100.157864,95.102818,106.682081,105.484628,-6.527863,-10.381356,0.130599,0.540694,15.536977,0.033882,0.119234,0.086349,8.336882,0.434630,0.457718,0.157831,0.167045,96.997247,109.804182,91.503331,27.131853,0.069299
20309,41700403,1610612744,2018-06-06,2017-18,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507
20310,41700404,1610612739,2018-06-08,2017-18,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910

In [8]:
df_lc_sum = rcp('16lc_sum_advanced_stat_2010_2018.csv')
p(df_lc_sum)

(20311, 27)

,game_id,team_id,game_date,season,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE
0,21000001,1610612738,2010-10-26,2010-11,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028
1,21000001,1610612748,2010-10-26,2010-11,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771
2,21000002,1610612756,2010-10-26,2010-11,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185
3,21000002,1610612757,2010-10-26,2010-11,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566
4,21000003,1610612745,2010-10-26,2010-11,72.948233,412.334764,407.967536,438.575371,431.164547,-26.242041,-23.182540,0.523228,3.688711,63.663037,0.269792,0.418425,0.347123,48.814252,1.599116,1.856396,0.721490,0.741075,392.134212,399.519088,332.932128,145.438289,0.280267
20306,41700317,1610612745,2018-05-28,2017-18,86.859988,532.699904,517.347739,512.727467,504.613318,19.931778,12.739791,0.777622,4.345292,86.488619,0.244140,0.707721,0.467646,65.607594,2.087595,2.270962,0.824166,0.858288,495.628808,511.774434,426.476992,179.843561,0.421658
20307,41700401,1610612744,2018-05-31,2017-18,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176
20308,41700403,1610612739,2018-06-06,2017-18,52.338461,400.631457,380.411271,426.728326,421.938512,-26.111453,-41.525423,0.522395,2.162777,62.147909,0.135526,0.476935,0.345398,33.347526,1.738520,1.830872,0.631322,0.668179,387.988989,439.216727,366.013324,108.527412,0.277195
20309,41700403,1610612744,2018-06-06,2017-18,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507
20310,41700404,1610612739,2018-06-08,2017-18,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910

In [9]:
df_lc_max = rcp('16lc_max_advanced_stat_2010_2018.csv')
p(df_lc_max)

(20311, 27)

,game_id,team_id,game_date,season,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,21000001,1610612738,2010-10-26,2010-11,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296
1,21000001,1610612748,2010-10-26,2010-11,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
2,21000002,1610612756,2010-10-26,2010-11,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185
3,21000002,1610612757,2010-10-26,2010-11,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143
4,21000003,1610612745,2010-10-26,2010-11,25.621905,105.238235,106.551471,118.183871,112.083871,1.380882,3.101471,0.284706,2.379853,30.129412,0.103404,0.151787,0.126298,14.452857,0.431643,0.522544,0.232258,0.242452,103.683548,110.925161,92.437419,50.342857,0.105765
20306,41700317,1610612745,2018-05-28,2017-18,32.375571,114.934247,115.224658,106.391379,106.217241,11.973016,12.580822,0.375247,3.300959,29.487671,0.085862,0.185414,0.133414,16.662500,0.536438,0.585233,0.244123,0.250041,101.832698,107.105000,89.252500,66.397260,0.164260
20307,41700401,1610612744,2018-05-31,2017-18,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176
20308,41700403,1610612739,2018-06-06,2017-18,21.729167,105.781159,102.107000,112.497436,112.869231,5.518841,2.226087,0.193159,1.180900,31.084058,0.079872,0.164635,0.142769,9.991000,0.482949,0.505487,0.247070,0.254070,102.021757,120.379189,100.316757,45.520000,0.087910
20309,41700403,1610612744,2018-06-06,2017-18,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507
20310,41700404,1610612739,2018-06-08,2017-18,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910

In [10]:
'''######################################
#df_lc_mean and df_lc_sum to be combined: df_lc_mean_sum

df_lc_mean_sum = pd.merge(df_lc_sum, df_lc_mean, on=['game_id', 'team_id', 'game_date', 'season'], how='inner')
df_lc_mean_sum'''

"######################################\n#df_lc_mean and df_lc_sum to be combined: df_lc_mean_sum\n\ndf_lc_mean_sum = pd.merge(df_lc_sum, df_lc_mean, on=['game_id', 'team_id', 'game_date', 'season'], how='inner')\ndf_lc_mean_sum"

In [11]:
from functools import reduce
data_frames = [df_lc_sum, df_lc_mean, df_lc_max]

In [12]:
df_lc_sum_mean_max = reduce(lambda  left,right: pd.merge(left,right,on=['game_id', 'team_id', 'game_date', 'season'],
                                                how='inner'), data_frames)
p(df_lc_sum_mean_max)

(20311, 73)

,game_id,team_id,game_date,season,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,21000001,1610612738,2010-10-26,2010-11,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296
1,21000001,1610612748,2010-10-26,2010-11,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
2,21000002,1610612756,2010-10-26,2010-11,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185
3,21000002,1610612757,2010-10-26,2010-11,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143
4,21000003,1610612745,2010-10-26,2010-11,72.948233,412.334764,407.967536,438.575371,431.164547,-26.242041,-23.182540,0.523228,3.688711,63.663037,0.269792,0.418425,0.347123,48.814252,1.599116,1.856396,0.721490,0.741075,392.134212,399.519088,332.932128,145.438289,0.280267,18.237058,103.083691,101.991884,109.643843,107.791137,-6.560510,-5.795635,0.130807,0.922178,15.915759,0.067448,0.104606,0.086781,12.203563,0.399779,0.464099,0.180372,0.185269,98.033553,99.879772,83.233032,36.359572,0.070067,25.621905,105.238235,106.551471,118.183871,112.083871,1.380882,3.101471,0.284706,2.379853,30.129412,0.103404,0.151787,0.126298,14.452857,0.431643,0.522544,0.232258,0.242452,103.683548,110.925161,92.437419,50.342857,0.105765
20306,41700317,1610612745,2018-05-28,2017-18,86.859988,532.699904,517.347739,512.727467,504.613318,19.931778,12.739791,0.777622,4.345292,86.488619,0.244140,0.707721,0.467646,65.607594,2.087595,2.270962,0.824166,0.858288,495.628808,511.774434,426.476992,179.843561,0.421658,17.371998,106.539981,103.469548,102.545493,100.922664,3.986356,2.547958,0.155524,0.869058,17.297724,0.048828,0.141544,0.093529,13.121519,0.417519,0.454192,0.164833,0.171658,99.125762,102.354887,85.295398,35.968712,0.084332,32.375571,114.934247,115.224658,106.391379,106.217241,11.973016,12.580822,0.375247,3.300959,29.487671,0.085862,0.185414,0.133414,16.662500,0.536438,0.585233,0.244123,0.250041,101.832698,107.105000,89.252500,66.397260,0.164260
20307,41700401,1610612744,2018-05-31,2017-18,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176,13.404730,114.643243,114.364865,103.904054,104.800000,10.741892,9.566216,0.128446,0.549459,19.106757,0.090689,0.213527,0.159392,17.962162,0.527473,0.573405,0.168311,0.172351,102.084595,101.984865,84.987027,28.472973,0.099176
20308,41700403,1610612739,2018-06-06,2017-18,52.338461,400.631457,380.411271,426.728326,421.938512,-26.111453,-41.525423,0.522395,2.162777,62.147909,0.135526,0.476935,0.345398,33.347526,1.738520,1.830872,0.631322,0.668179,387.988989,439.216727,366.013324,108.527412,0.277195,13.084615,100.157864,95.102818,106.682081,105.484628,-6.527863,-10.381356,0.130599,0.540694,15.536977,0.033882,0.119234,0.086349,8.336882,0.434630,0.457718,0.157831,0.167045,96.997247,109.804182,91.503331,27.131853,0.069299,21.729167,105.781159,102.107000,112.497436,112.869231,5.518841,2.226087,0.193159,1.180900,31.084058,0.079872,0.164635,0.142769,9.991000,0.482949,0.505487,0.247070,0.254070,102.021757,120.379189,100.316757,45.520000,0.087910
20309,41700403,1610612744,2018-06-06,2017-18,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507
20310,41700404,1610612739,2018-06-08,2017-18,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910

In [13]:
######################################
#df_lc_mean and df_lc_sum to be combined: df_lc_mean_sum

#merge with game_id's, team_id's for 2010-11 thru 2017-18 seasons by reading in 3game_id (game_id, team_id); merge left on 3game_id

#fill games with NaN for lost contribution with 0

In [14]:
df_gitis = rcp('3game_id_game_date_team_id.csv')
p(df_gitis)

(31038, 27)

,game_id,game_date,team_id,is_home,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
0,20600001,2006-10-31,1610612748,t,0.0,240,25.0,65.0,0.385,3.0,17.0,0.176,13.0,22.0,1.0,4.0,25.0,29,13.0,6.0,3.0,21.0,24.0,66,2006,Regular Season,2006-07
1,20600001,2006-10-31,1610612741,f,1.0,240,39.0,79.0,0.494,7.0,13.0,0.538,23.0,32.0,1.0,13.0,36.0,49,22.0,10.0,5.0,16.0,21.0,108,2006,Regular Season,2006-07
2,20600002,2006-10-31,1610612747,t,1.0,240,46.0,83.0,0.554,6.0,12.0,0.500,16.0,24.0,1.0,12.0,31.0,43,30.0,11.0,1.0,20.0,19.0,114,2006,Regular Season,2006-07
3,20600002,2006-10-31,1610612756,f,0.0,240,40.0,77.0,0.519,13.0,30.0,0.433,13.0,17.0,1.0,4.0,25.0,29,29.0,7.0,5.0,21.0,25.0,106,2006,Regular Season,2006-07
4,20600003,2006-11-01,1610612755,t,1.0,240,31.0,74.0,0.419,3.0,9.0,0.333,23.0,25.0,1.0,15.0,32.0,47,19.0,10.0,6.0,16.0,22.0,88,2006,Regular Season,2006-07
31033,41700402,2018-06-03,1610612744,t,1.0,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017,Playoffs,2017-18
31034,41700403,2018-06-06,1610612744,f,1.0,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,2017,Playoffs,2017-18
31035,41700403,2018-06-06,1610612739,t,0.0,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017,Playoffs,2017-18
31036,41700404,2018-06-08,1610612739,t,0.0,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017,Playoffs,2017-18
31037,41700404,2018-06-08,1610612744,f,1.0,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,2017,Playoffs,2017-18

In [15]:
df_gitis1018 = df_gitis[(df_gitis.season == '2010-11') | 
         (df_gitis.season == '2011-12') | 
         (df_gitis.season == '2012-13') | 
         (df_gitis.season == '2013-14') | 
         (df_gitis.season == '2014-15') | 
         (df_gitis.season == '2015-16') | 
         (df_gitis.season == '2016-17') | 
         (df_gitis.season == '2017-18')].reset_index(drop=True)
p(df_gitis1018)

(20534, 27)

,game_id,game_date,team_id,is_home,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,season_year,season_type,season
0,21000001,2010-10-26,1610612738,t,1.0,240,32.0,69.0,0.464,8.0,16.0,0.500,16.0,25.0,1.0,8.0,34.0,42,25.0,6.0,4.0,18.0,19.0,88,2010,Regular Season,2010-11
1,21000001,2010-10-26,1610612748,f,0.0,240,27.0,74.0,0.365,8.0,20.0,0.400,18.0,25.0,1.0,11.0,28.0,39,15.0,10.0,6.0,17.0,21.0,80,2010,Regular Season,2010-11
2,21000002,2010-10-26,1610612757,t,1.0,240,43.0,93.0,0.462,10.0,20.0,0.500,10.0,15.0,1.0,18.0,30.0,48,31.0,11.0,2.0,12.0,22.0,106,2010,Regular Season,2010-11
3,21000002,2010-10-26,1610612756,f,0.0,240,36.0,74.0,0.486,9.0,19.0,0.474,11.0,16.0,1.0,7.0,23.0,30,15.0,3.0,4.0,19.0,19.0,92,2010,Regular Season,2010-11
4,21000003,2010-10-26,1610612745,f,0.0,240,38.0,91.0,0.418,8.0,20.0,0.400,26.0,28.0,1.0,16.0,37.0,53,25.0,6.0,7.0,20.0,25.0,110,2010,Regular Season,2010-11
20529,41700402,2018-06-03,1610612744,t,1.0,240,47.0,82.0,0.573,15.0,36.0,0.417,13.0,21.0,1.0,7.0,34.0,41,28.0,3.0,8.0,12.0,25.0,122,2017,Playoffs,2017-18
20530,41700403,2018-06-06,1610612744,f,1.0,240,42.0,81.0,0.519,9.0,26.0,0.346,17.0,19.0,1.0,6.0,31.0,37,27.0,6.0,5.0,10.0,20.0,110,2017,Playoffs,2017-18
20531,41700403,2018-06-06,1610612739,t,0.0,240,40.0,92.0,0.435,9.0,31.0,0.290,13.0,17.0,1.0,15.0,32.0,47,20.0,6.0,4.0,13.0,18.0,102,2017,Playoffs,2017-18
20532,41700404,2018-06-08,1610612739,t,0.0,240,30.0,87.0,0.345,8.0,27.0,0.296,17.0,25.0,1.0,17.0,27.0,44,21.0,5.0,5.0,11.0,22.0,85,2017,Playoffs,2017-18
20533,41700404,2018-06-08,1610612744,f,1.0,240,39.0,86.0,0.453,14.0,38.0,0.368,16.0,16.0,1.0,10.0,34.0,44,25.0,7.0,13.0,8.0,24.0,108,2017,Playoffs,2017-18

In [16]:
df_gitis1018 = df_gitis1018[['game_id', 'game_date', 'team_id', 'season']]
p(df_gitis1018)

(20534, 4)

        game_id   game_date     team_id   season
0      21000001  2010-10-26  1610612738  2010-11
1      21000001  2010-10-26  1610612748  2010-11
2      21000002  2010-10-26  1610612757  2010-11
3      21000002  2010-10-26  1610612756  2010-11
4      21000003  2010-10-26  1610612745  2010-11
20529  41700402  2018-06-03  1610612744  2017-18
20530  41700403  2018-06-06  1610612744  2017-18
20531  41700403  2018-06-06  1610612739  2017-18
20532  41700404  2018-06-08  1610612739  2017-18
20533  41700404  2018-06-08  1610612744  2017-18

In [17]:
#get all game_id's, and team_id's for the 2010-11 thru 2017-18 seasons
df_lc_sum_mean_max_merged1 = pd.merge(df_gitis1018, df_lc_sum_mean_max, on=['game_id', 'game_date', 'team_id', 'season'], how='left')
df_lc_sum_mean_max_merged1

,game_id,game_date,team_id,season,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,21000001,2010-10-26,1610612738,2010-11,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296
1,21000001,2010-10-26,1610612748,2010-11,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
2,21000002,2010-10-26,1610612757,2010-11,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143
3,21000002,2010-10-26,1610612756,2010-11,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185
4,21000003,2010-10-26,1610612745,2010-11,72.948233,412.334764,407.967536,438.575371,431.164547,-26.242041,-23.182540,0.523228,3.688711,63.663037,0.269792,0.418425,0.347123,48.814252,1.599116,1.856396,0.721490,0.741075,392.134212,399.519088,332.932128,145.438289,0.280267,18.237058,103.083691,101.991884,109.643843,107.791137,-6.560510,-5.795635,0.130807,0.922178,15.915759,0.067448,0.104606,0.086781,12.203563,0.399779,0.464099,0.180372,0.185269,98.033553,99.879772,83.233032,36.359572,0.070067,25.621905,105.238235,106.551471,118.183871,112.083871,1.380882,3.101471,0.284706,2.379853,30.129412,0.103404,0.151787,0.126298,14.452857,0.431643,0.522544,0.232258,0.242452,103.683548,110.925161,92.437419,50.342857,0.105765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20529,41700402,2018-06-03,1610612744,2017-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20530,41700403,2018-06-06,1610612744,2017-18,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507
20531,41700403,2018-06-06,1610612739,2017-18,52.338461,400.631457,380.411271,426.728326,421.938512,-26.111453,-41.525423,0.522395,2.162777,62.147909,0.135526,0.476935,0.345398,33.347526,1.738520,1.830872,0.631322,0.668179,387.988989,439.216727,366.013324,108.527412,0.277195,13.084615,100.157864,95.102818,106.682081,105.484628,-6.527863,-10.381356,0.130599,0.540694,15.536977,0.033882,0.119234,0.086349,8.336882,0.434630,0.457718,0.157831,0.167045,96.997247,109.804182,91.503331,27.131853,0.069299,21.729167,105.781159,102.107000,112.497436,112.869231,5.518841,2.226087,0.193159,1.180900,31.084058,0.079872,0.164635,0.142769,9.991000,0.482949,0.505487,0.247070,0.254070,102.021757,120.379189,100.316757,45.520000,0.087910
20532,41700404,2018-06-08,1610612739,2017-18,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910
20533,41700404,2018-06-08,1610612744,2017-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_lc_sum_mean_max_merged1.fillna(0, inplace=True)

In [19]:
p(df_lc_sum_mean_max_merged1)

(20534, 73)

,game_id,game_date,team_id,season,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,21000001,2010-10-26,1610612738,2010-11,51.924227,211.872235,213.259085,201.560675,204.284577,10.321001,8.965179,0.271101,1.990024,34.827346,0.106651,0.289929,0.204024,31.643285,0.998045,1.058208,0.339048,0.345030,186.953514,185.147720,154.291124,99.953981,0.183028,25.962114,105.936118,106.629543,100.780337,102.142288,5.160501,4.482590,0.135551,0.995012,17.413673,0.053326,0.144965,0.102012,15.821643,0.499022,0.529104,0.169524,0.172515,93.476757,92.573860,77.145562,49.976991,0.091514,27.011551,106.862376,107.916832,101.867606,103.301408,7.170297,6.925743,0.215141,1.477746,25.788732,0.084158,0.204901,0.148109,19.710891,0.571594,0.580842,0.173662,0.177535,93.861683,92.810396,77.342673,52.108911,0.092296
1,21000001,2010-10-26,1610612748,2010-11,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
2,21000002,2010-10-26,1610612757,2010-11,50.458291,316.665128,317.949634,318.083077,310.663040,-1.416447,7.270403,0.328857,0.781418,32.385897,0.282006,0.520890,0.405909,52.022308,1.391468,1.519216,0.543589,0.581734,276.853861,281.646315,234.705436,94.308425,0.309566,16.819430,105.555043,105.983211,106.027692,103.554347,-0.472149,2.423468,0.109619,0.260473,10.795299,0.094002,0.173630,0.135303,17.340769,0.463823,0.506405,0.181196,0.193911,92.284620,93.882105,78.235145,31.436142,0.103189,23.894444,110.733333,111.938095,119.023077,111.869231,9.323810,10.638095,0.250000,0.498571,21.569231,0.134857,0.259033,0.196714,26.896667,0.587286,0.619190,0.243385,0.277077,98.715385,103.763077,86.470769,43.190476,0.161143
3,21000002,2010-10-26,1610612756,2010-11,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185,7.336111,94.955556,93.225926,101.974074,98.822222,-7.024074,-5.598148,0.088778,0.203704,9.392593,0.035574,0.118204,0.084574,10.553704,0.256611,0.294630,0.202870,0.214407,107.874074,109.840741,91.535000,15.259259,0.009185
4,21000003,2010-10-26,1610612745,2010-11,72.948233,412.334764,407.967536,438.575371,431.164547,-26.242041,-23.182540,0.523228,3.688711,63.663037,0.269792,0.418425,0.347123,48.814252,1.599116,1.856396,0.721490,0.741075,392.134212,399.519088,332.932128,145.438289,0.280267,18.237058,103.083691,101.991884,109.643843,107.791137,-6.560510,-5.795635,0.130807,0.922178,15.915759,0.067448,0.104606,0.086781,12.203563,0.399779,0.464099,0.180372,0.185269,98.033553,99.879772,83.233032,36.359572,0.070067,25.621905,105.238235,106.551471,118.183871,112.083871,1.380882,3.101471,0.284706,2.379853,30.129412,0.103404,0.151787,0.126298,14.452857,0.431643,0.522544,0.232258,0.242452,103.683548,110.925161,92.437419,50.342857,0.105765
20529,41700402,2018-06-03,1610612744,2017-18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20530,41700403,2018-06-06,1610612744,2017-18,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507,13.272000,114.489333,114.173333,104.185333,105.069333,10.306667,9.105333,0.126733,0.542133,18.852000,0.092147,0.215120,0.160600,17.722667,0.527107,0.576400,0.171400,0.176147,102.185200,102.109067,85.090533,28.200000,0.103507
20531,41700403,2018-06-06,1610612739,2017-18,52.338461,400.631457,380.411271,426.728326,421.938512,-26.111453,-41.525423,0.522395,2.162777,62.147909,0.135526,0.476935,0.345398,33.347526,1.738520,1.830872,0.631322,0.668179,387.988989,439.216727,366.013324,108.527412,0.277195,13.084615,100.157864,95.102818,106.682081,105.484628,-6.527863,-10.381356,0.130599,0.540694,15.536977,0.033882,0.119234,0.086349,8.336882,0.434630,0.457718,0.157831,0.167045,96.997247,109.804182,91.503331,27.131853,0.069299,21.729167,105.781159,102.107000,112.497436,112.869231,5.518841,2.226087,0.193159,1.180900,31.084058,0.079872,0.164635,0.142769,9.991000,0.482949,0.505487,0.247070,0.254070,102.021757,120.379189,100.316757,45.520000,0.087910
20532,41700404,2018-06-08,1610612739,2017-18,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910,21.729167,102.010000,102.107000,107.554000,108.108000,-5.541000,-6.003000,0.173480,1.180900,13.809000,0.026670,0.082420,0.053930,9.991000,0.456100,0.483360,0.247070,0.254070,100.444300,100.012800,83.343100,45.520000,0.087910
20533,41700404,2018-06-08,1610612744,2017-18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [20]:
df_tist = rcp('10team_id_season_team_2010_2018.csv')
p(df_tist)

(240, 3)

        TEAM_ID   season      Team
0    1610612748  2010-11      Heat
1    1610612749  2010-11     Bucks
2    1610612765  2010-11   Pistons
3    1610612753  2010-11     Magic
4    1610612737  2010-11     Hawks
235  1610612752  2017-18    Knicks
236  1610612758  2017-18     Kings
237  1610612744  2017-18  Warriors
238  1610612765  2017-18   Pistons
239  1610612746  2017-18  Clippers

In [21]:
df_x = pd.merge(df_tist.rename(columns={'TEAM_ID': 'team_id'}), df_lc_sum_mean_max_merged1, on=['team_id', 'season'], how='outer', indicator=True)
p(df_x)

(20534, 75)

,team_id,season,Team,game_id,game_date,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE,_merge
0,1610612748,2010-11,Heat,21000001,2010-10-26,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481,both
1,1610612748,2010-11,Heat,21000006,2010-10-27,68.098002,302.118241,301.192054,316.407153,317.218723,-14.287357,-16.017267,0.420140,3.540788,54.791826,0.148277,0.466348,0.299508,45.084396,1.425022,1.496048,0.453213,0.467014,274.789836,275.375124,229.479856,129.945214,0.024157,22.699334,100.706080,100.397351,105.469051,105.739574,-4.762452,-5.339089,0.140047,1.180263,18.263942,0.049426,0.155449,0.099836,15.028132,0.475007,0.498683,0.151071,0.155671,91.596612,91.791708,76.493285,43.315071,0.008052,33.424383,103.151852,104.377778,109.601852,109.838889,-2.065385,-3.383333,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.162833,0.166718,93.101111,92.464444,77.053889,64.370370,0.109481,both
2,1610612748,2010-11,Heat,21000025,2010-10-29,42.624383,316.751852,320.077778,416.801852,392.338889,-100.046296,-72.255556,0.430759,1.827222,60.196296,0.032093,0.667370,0.242556,14.911111,0.617593,1.173889,0.346704,0.349944,269.961111,274.434444,228.703889,81.370370,0.229481,14.208128,105.583951,106.692593,138.933951,130.779630,-33.348765,-24.085185,0.143586,0.609074,20.065432,0.010698,0.222457,0.080852,4.970370,0.205864,0.391296,0.115568,0.116648,89.987037,91.478148,76.234630,27.123457,0.076494,33.424383,131.600000,130.000000,185.700000,162.500000,10.100000,10.000000,0.250000,1.827222,33.300000,0.032093,0.500000,0.143000,14.911111,0.617593,0.641889,0.200000,0.202000,93.101111,93.810000,78.180000,64.370370,0.120000,both
3,1610612748,2010-11,Heat,21000040,2010-10-31,37.507716,185.151852,190.077778,295.301852,272.338889,-110.146296,-82.255556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,177.271111,180.624444,150.523889,71.370370,0.109481,18.753858,92.575926,95.038889,147.650926,136.169444,-55.073148,-41.127778,0.090380,0.913611,13.448148,0.016046,0.083685,0.049778,7.455556,0.308796,0.320944,0.073352,0.073972,88.635556,90.312222,75.261944,35.685185,0.054741,33.424383,103.151852,104.377778,185.700000,162.500000,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,92.464444,77.053889,64.370370,0.109481,both
4,1610612748,2010-11,Heat,21000050,2010-11-02,37.399383,168.751852,171.827778,200.951852,188.188889,-32.146296,-16.305556,0.180759,1.827222,26.896296,0.215593,0.167370,0.224556,14.911111,0.617593,0.925889,0.247704,0.252944,185.456111,189.489444,157.908889,72.370370,-0.051519,18.699691,84.375926,85.913889,100.475926,94.094444,-16.073148,-8.152778,0.090380,0.913611,13.448148,0.107796,0.083685,0.112278,7.455556,0.308796,0.462944,0.123852,0.126472,92.728056,94.744722,78.954444,36.185185,-0.025759,33.424383,103.151852,104.377778,109.601852,109.838889,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.183500,0.167370,0.125000,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,97.025000,80.855000,64.370370,0.109481,both
20529,1610612746,2017-18,Clippers,21701168,2018-04-03,146.678499,640.596671,640.331742,639.969085,637.281548,0.679793,3.080758,0.849233,6.483335,104.912492,0.131071,0.613417,0.370362,63.656900,2.850910,3.039054,1.109180,1.135039,601.033065,602.486983,502.077797,302.530047,0.427708,24.446416,106.766112,106.721957,106.661514,106.213591,0.113299,0.513460,0.141539,1.080556,17.485415,0.021845,0.102236,0.061727,10.609483,0.475152,0.506509,0.184863,0.189173,100.172178,100.414497,83.679633,50.421674,0.071285,31.955556,110.581818,111.754545,107.928986,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.140855,0.090014,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,104.263768,86.886812,65.380952,0.099952,both
20530,1610612746,2017-18,Clippers,21701179,2018-04-05,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952,both
20531,1610612746,2017-18,Clippers,21701191,2018-04-07,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952,both
20532,1610612746,2017-18,Clippers,21701212,2018-04-09,201.553878,752.156727,755.949091,751.941829,752.733135,0.262756,3.232761,1.234384,10.547727,134.376165,0.120098,0.588777,0.353180,74.587966,3.393490,3.652293,1.457945,1.487396,700.358026,698.050265,581.712857,415.990788,0.555500,28.793411,107.450961,107.992727,107.420261,107.533305,0.037537,0.461823,0.176341,1.506818,19.196595,0.017157,0.084111,0.050454,10.655424,0.484784,0.521756,0.208278,0.212485,100.051147,99.721466,83.101837,59.427255,0.079357,33.941667,110.581818,111.754545,110.096667,111.300000,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861,both
20533,1610612746,2017-18,Clippers,21701228,2018-04-11,167.612211,643.875060,646.212424,641.845162,641.433135,2.077756,4.796095,1.059534,8.519894,115.196165,0.106565,0.531410,0.317930,65.814632,2.893840,3.139059,1.250762,1.276563,601.243693,600.167265,500.144024,346.824121,0.483583,27.935369,107.312510,107.702071,106.974194,106.905522,0.346293,0.799349,0.176589,1.419982,19.199361,0.017761,0.088568,0.052988,10.969105,0.482307,0.523177,0.208460,0.212760,100.207282,100.027878,83.357337,57.804020,0.080597,32.774051,110.581818,111.754545,109.805063,109.924051,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861,both

In [22]:
df_x.value_counts('_merge')

_merge
both          20534
right_only        0
left_only         0
dtype: int64

In [23]:
df_x.drop(columns=['_merge'], inplace=True)

In [26]:
p(df_x)

(20534, 74)

,team_id,season,Team,game_id,game_date,lc_sum_MIN,lc_sum_E_OFF_RATING,lc_sum_OFF_RATING,lc_sum_E_DEF_RATING,lc_sum_DEF_RATING,lc_sum_E_NET_RATING,lc_sum_NET_RATING,lc_sum_AST_PCT,lc_sum_AST_TOV,lc_sum_AST_RATIO,lc_sum_OREB_PCT,lc_sum_DREB_PCT,lc_sum_REB_PCT,lc_sum_TM_TOV_PCT,lc_sum_EFG_PCT,lc_sum_TS_PCT,lc_sum_USG_PCT,lc_sum_E_USG_PCT,lc_sum_E_PACE,lc_sum_PACE,lc_sum_PACE_PER40,lc_sum_POSS,lc_sum_PIE,lc_mean_MIN,lc_mean_E_OFF_RATING,lc_mean_OFF_RATING,lc_mean_E_DEF_RATING,lc_mean_DEF_RATING,lc_mean_E_NET_RATING,lc_mean_NET_RATING,lc_mean_AST_PCT,lc_mean_AST_TOV,lc_mean_AST_RATIO,lc_mean_OREB_PCT,lc_mean_DREB_PCT,lc_mean_REB_PCT,lc_mean_TM_TOV_PCT,lc_mean_EFG_PCT,lc_mean_TS_PCT,lc_mean_USG_PCT,lc_mean_E_USG_PCT,lc_mean_E_PACE,lc_mean_PACE,lc_mean_PACE_PER40,lc_mean_POSS,lc_mean_PIE,lc_max_MIN,lc_max_E_OFF_RATING,lc_max_OFF_RATING,lc_max_E_DEF_RATING,lc_max_DEF_RATING,lc_max_E_NET_RATING,lc_max_NET_RATING,lc_max_AST_PCT,lc_max_AST_TOV,lc_max_AST_RATIO,lc_max_OREB_PCT,lc_max_DREB_PCT,lc_max_REB_PCT,lc_max_TM_TOV_PCT,lc_max_EFG_PCT,lc_max_TS_PCT,lc_max_USG_PCT,lc_max_E_USG_PCT,lc_max_E_PACE,lc_max_PACE,lc_max_PACE_PER40,lc_max_POSS,lc_max_PIE
0,1610612748,2010-11,Heat,21000001,2010-10-26,110.238328,507.593932,506.705203,529.659259,529.555276,-22.053076,-22.846304,0.600020,4.750808,79.579039,0.228306,0.699159,0.459315,69.738878,2.298579,2.473118,0.805941,0.827111,456.041944,456.667921,380.556947,209.063530,0.162771,22.047666,101.518786,101.341041,105.931852,105.911055,-4.410615,-4.569261,0.120004,0.950162,15.915808,0.045661,0.139832,0.091863,13.947776,0.459716,0.494624,0.161188,0.165422,91.208389,91.333584,76.111389,41.812706,0.032554,33.424383,104.443038,104.377778,110.258228,110.056962,-1.953061,0.210204,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.211918,0.215490,93.101111,92.464444,77.053889,64.370370,0.109481
1,1610612748,2010-11,Heat,21000006,2010-10-27,68.098002,302.118241,301.192054,316.407153,317.218723,-14.287357,-16.017267,0.420140,3.540788,54.791826,0.148277,0.466348,0.299508,45.084396,1.425022,1.496048,0.453213,0.467014,274.789836,275.375124,229.479856,129.945214,0.024157,22.699334,100.706080,100.397351,105.469051,105.739574,-4.762452,-5.339089,0.140047,1.180263,18.263942,0.049426,0.155449,0.099836,15.028132,0.475007,0.498683,0.151071,0.155671,91.596612,91.791708,76.493285,43.315071,0.008052,33.424383,103.151852,104.377778,109.601852,109.838889,-2.065385,-3.383333,0.237462,1.827222,27.557692,0.103351,0.234811,0.161568,16.054054,0.617593,0.641889,0.162833,0.166718,93.101111,92.464444,77.053889,64.370370,0.109481
2,1610612748,2010-11,Heat,21000025,2010-10-29,42.624383,316.751852,320.077778,416.801852,392.338889,-100.046296,-72.255556,0.430759,1.827222,60.196296,0.032093,0.667370,0.242556,14.911111,0.617593,1.173889,0.346704,0.349944,269.961111,274.434444,228.703889,81.370370,0.229481,14.208128,105.583951,106.692593,138.933951,130.779630,-33.348765,-24.085185,0.143586,0.609074,20.065432,0.010698,0.222457,0.080852,4.970370,0.205864,0.391296,0.115568,0.116648,89.987037,91.478148,76.234630,27.123457,0.076494,33.424383,131.600000,130.000000,185.700000,162.500000,10.100000,10.000000,0.250000,1.827222,33.300000,0.032093,0.500000,0.143000,14.911111,0.617593,0.641889,0.200000,0.202000,93.101111,93.810000,78.180000,64.370370,0.120000
3,1610612748,2010-11,Heat,21000040,2010-10-31,37.507716,185.151852,190.077778,295.301852,272.338889,-110.146296,-82.255556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,177.271111,180.624444,150.523889,71.370370,0.109481,18.753858,92.575926,95.038889,147.650926,136.169444,-55.073148,-41.127778,0.090380,0.913611,13.448148,0.016046,0.083685,0.049778,7.455556,0.308796,0.320944,0.073352,0.073972,88.635556,90.312222,75.261944,35.685185,0.054741,33.424383,103.151852,104.377778,185.700000,162.500000,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.032093,0.167370,0.099556,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,92.464444,77.053889,64.370370,0.109481
4,1610612748,2010-11,Heat,21000050,2010-11-02,37.399383,168.751852,171.827778,200.951852,188.188889,-32.146296,-16.305556,0.180759,1.827222,26.896296,0.215593,0.167370,0.224556,14.911111,0.617593,0.925889,0.247704,0.252944,185.456111,189.489444,157.908889,72.370370,-0.051519,18.699691,84.375926,85.913889,100.475926,94.094444,-16.073148,-8.152778,0.090380,0.913611,13.448148,0.107796,0.083685,0.112278,7.455556,0.308796,0.462944,0.123852,0.126472,92.728056,94.744722,78.954444,36.185185,-0.025759,33.424383,103.151852,104.377778,109.601852,109.838889,-6.446296,-5.455556,0.180759,1.827222,26.896296,0.183500,0.167370,0.125000,14.911111,0.617593,0.641889,0.146704,0.147944,93.101111,97.025000,80.855000,64.370370,0.109481
20529,1610612746,2017-18,Clippers,21701168,2018-04-03,146.678499,640.596671,640.331742,639.969085,637.281548,0.679793,3.080758,0.849233,6.483335,104.912492,0.131071,0.613417,0.370362,63.656900,2.850910,3.039054,1.109180,1.135039,601.033065,602.486983,502.077797,302.530047,0.427708,24.446416,106.766112,106.721957,106.661514,106.213591,0.113299,0.513460,0.141539,1.080556,17.485415,0.021845,0.102236,0.061727,10.609483,0.475152,0.506509,0.184863,0.189173,100.172178,100.414497,83.679633,50.421674,0.071285,31.955556,110.581818,111.754545,107.928986,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.140855,0.090014,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,104.263768,86.886812,65.380952,0.099952
20530,1610612746,2017-18,Clippers,21701179,2018-04-05,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952
20531,1610612746,2017-18,Clippers,21701191,2018-04-07,134.838161,533.545946,534.849133,532.040099,531.509084,1.553706,3.361917,0.801711,6.290147,96.483507,0.091970,0.472562,0.280348,55.082987,2.391359,2.567794,0.966281,0.986575,498.700022,498.223215,415.190986,277.153235,0.357723,26.967632,106.709189,106.969827,106.408020,106.301817,0.310741,0.672383,0.160342,1.258029,19.296701,0.018394,0.094512,0.056070,11.016597,0.478272,0.513559,0.193256,0.197315,99.740004,99.644643,83.038197,55.430647,0.071545,31.955556,110.581818,111.754545,107.848889,108.643478,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.227304,0.231435,102.772708,103.863125,86.552708,65.380952,0.099952
20532,1610612746,2017-18,Clippers,21701212,2018-04-09,201.553878,752.156727,755.949091,751.941829,752.733135,0.262756,3.232761,1.234384,10.547727,134.376165,0.120098,0.588777,0.353180,74.587966,3.393490,3.652293,1.457945,1.487396,700.358026,698.050265,581.712857,415.990788,0.555500,28.793411,107.450961,107.992727,107.420261,107.533305,0.037537,0.461823,0.176341,1.506818,19.196595,0.017157,0.084111,0.050454,10.655424,0.484784,0.521756,0.208278,0.212485,100.051147,99.721466,83.101837,59.427255,0.079357,33.941667,110.581818,111.754545,110.096667,111.300000,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861
20533,1610612746,2017-18,Clippers,21701228,2018-04-11,167.612211,643.875060,646.212424,641.845162,641.433135,2.077756,4.796095,1.059534,8.519894,115.196165,0.106565,0.531410,0.317930,65.814632,2.893840,3.139059,1.250762,1.276563,601.243693,600.167265,500.144024,346.824121,0.483583,27.935369,107.312510,107.702071,106.974194,106.905522,0.346293,0.799349,0.176589,1.419982,19.199361,0.017761,0.088568,0.052988,10.969105,0.482307,0.523177,0.208460,0.212760,100.207282,100.027878,83.357337,57.804020,0.080597,32.774051,110.581818,111.754545,109.805063,109.924051,4.381818,6.136364,0.259844,2.239778,31.075556,0.040455,0.130095,0.073095,14.180000,0.564022,0.577533,0.284481,0.289987,102.772708,103.863125,86.552708,69.670886,0.125861

In [28]:
20534 / 2

10267.0

In [27]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '50lost_contribution_sum_mean_max_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_x.to_csv(datapath_df, index=False)