In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
df_away_home = rcp('21boxscoreadvancedv2_boxscores_team_away_home_2010_2018.csv', ['game_date'])
df_away_home = sr(df_away_home, 'game_date')
p(df_away_home)

(10266, 110)

,game_id,game_date,TEAM_NAME_away,TEAM_ABBREVIATION_away,TEAM_CITY_away,MIN_away,duration_away,TEAM_NAME_home,TEAM_ABBREVIATION_home,TEAM_CITY_home,MIN_home,duration_home,E_OFF_RATING_away,OFF_RATING_away,E_DEF_RATING_away,DEF_RATING_away,E_NET_RATING_away,NET_RATING_away,AST_PCT_away,AST_TOV_away,AST_RATIO_away,OREB_PCT_away,DREB_PCT_away,REB_PCT_away,E_TM_TOV_PCT_away,TM_TOV_PCT_away,EFG_PCT_away,TS_PCT_away,USG_PCT_away,E_USG_PCT_away,E_PACE_away,PACE_away,PACE_PER40_away,POSS_away,PIE_away,duration_minutes_away,E_OFF_RATING_home,OFF_RATING_home,E_DEF_RATING_home,DEF_RATING_home,E_NET_RATING_home,NET_RATING_home,AST_PCT_home,AST_TOV_home,AST_RATIO_home,OREB_PCT_home,DREB_PCT_home,REB_PCT_home,E_TM_TOV_PCT_home,TM_TOV_PCT_home,EFG_PCT_home,TS_PCT_home,USG_PCT_home,E_USG_PCT_home,E_PACE_home,PACE_home,PACE_PER40_home,POSS_home,PIE_home,duration_minutes_home,matchup,team_id_away,w_pct_away,min_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,team_id_home,w_pct_home,min_home,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,season_type,season,season_year,wl_away,wl_home,spread_home,spread_away
0,21000001,2010-10-26,Heat,MIA,Miami,240:00,0 days 04:00:00,Celtics,BOS,Boston,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.50,76.25,91,0.401,240.0,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.50,76.25,92,0.599,240.0,BOS vs. MIA,1610612748,0.000,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,1610612738,1.000,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,Regular Season,2010-11,2010,L,W,-8,8
1,21000002,2010-10-26,Suns,PHX,Phoenix,240:00,0 days 04:00:00,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.00,75.00,90,0.375,240.0,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.00,75.00,90,0.625,240.0,PHX vs. POR,1610612756,0.000,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,1610612757,1.000,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,Regular Season,2010-11,2010,L,W,-14,14
2,21000003,2010-10-26,Rockets,HOU,Houston,240:00,0 days 04:00:00,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.50,86.25,103,0.507,240.0,105.3,107.7,101.6,106.8,3.8,0.9,0.525,1.75,14.9,0.305,0.604,0.446,11.287,11.5,0.464,0.517,1.0,0.198,107.32,103.50,86.25,104,0.493,240.0,HOU vs. LAL,1610612745,0.000,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,1610612747,1.000,240,40,96,0.417,9,21,0.429,23,28,0.821429,14,30,44,21,11,4,12,24,112,Regular Season,2010-11,2010,L,W,-2,2
3,21000010,2010-10-27,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,97.5,95.8,100.3,100.0,-2.7,-4.2,0.424,1.17,12.1,0.184,0.857,0.520,12.859,12.6,0.481,0.509,1.0,0.201,94.04,95.00,79.17,95,0.425,240.0,100.3,100.0,97.5,95.8,2.7,4.2,0.676,2.56,18.6,0.143,0.816,0.480,9.498,9.5,0.456,0.518,1.0,0.198,94.04,95.00,79.17,95,0.575,240.0,MIL vs. NOH,1610612749,0.000,240,33,77,0.429,8,23,0.348,17,28,0.607143,8,37,45,14,4,2,12,27,91,1610612740,1.000,240,34,79,0.430,4,17,0.235,23,29,0.793103,6,38,44,23,4,0,9,26,95,Regular Season,2010-11,2010,L,W,-4,4
4,21000015,2010-10-27,Rockets,HOU,Houston,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,123.2,125.5,128.9,128.2,-5.6,-2.7,0.585,2.67,16.8,0.373,0.595,0.473,8.664,8.8,0.494,0.582,1.0,0.202,103.16,102.50,85.42,102,0.484,240.0,128.9,128.2,123.2,125.5,5.6,2.7,0.490,1.92,17.7,0.405,0.627,0.527,12.690,12.6,0.598,0.638,1.0,0.199,103.16,102.50,85.42,103,0.516,240.0,GSW vs. HOU,1610612745,0.000,240,41,87,0.471,4,16,0.250,42,52,0.807692,15,24,39,24,9,2,9,20,128,1610612744,1.000,240,51,92,0.554,8,20,0.400,22,26,0.846154,14,31,45,25,5,7,12,30,132,Regular Season,2010-11,2010,L,W,-4,4
10261,41700317,2018-05-28,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Rockets,HOU,Houston,240:00,0 days 04:00:00,109.6,111.0,97.2,101.1,12.4,9.9,0.641,1.47,19.5,0.341,0.633,0.510,18.446,18.7,0.588,0.586,1.0,0.200,93.42,91.00,75.83,91,0.568,240.0,97.2,101.1,109.6,111.0,-12.4,-9.9,0.472,1.42,13.2,0.367,0.659,0.490,12.674,13.2,0.439,0.461,1.0,0.201,93.42,91.00,75.83,91,0.432,240.0,GSW vs. HOU,1610612744,0.571,240,39,80,0.488,16,39,0.410,7,14,0.500000,11,31,42,25,9,7,16,22,101,1610612745,0.429,240,36,90,0.400,7,44,0.159,13,22,0.590909,17,27,44,17,13,3,12,17,92,Playoffs,2017-18,2017,W,L,9,-9
10262,41700401,2018-05-31,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,Warriors,GSW,Golden State,265:00,0 days 04:25:00,112.1,112.9,120.6,125.3,-8.5,-12.4,0.409,1.50,13.0,0.404,0.822,0.588,11.802,11.9,0.495,0.524,1.0,0.197,92.59,90.57,75.47,101,0.406,265.0,120.6,125.3,112.1,112.9,8.5,12.4,0.674,3.88,22.5,0.178,0.596,0.412,7.782,8.1,0.583,0.628,1.0,0.195,92.59,90.57,75.47,99,0.594,265.0,CLE vs. GSW,1610612739,0.000,265,44,99,0.444,10,37,0.270,16,22,0.727273,19,34,53,18,5,3,11,18,114,1610612744,1.000,265,46,90,0.511,13,36,0.361,19,20,0.950000,4,34,38,31,10,6,7,18,124,Playoffs,2017-18,2017,L,W,-10,10
10263,41700402,2018-06-03,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,Warriors,GSW,Golden State,240:00,0 days 04:00:00,106.8,106.2,126.8,129.8,-20.0,-23.6,0.676,2.27,18.2,0.382,0.711,0.516,11.406,11.3,0.461,0.508,1.0,0.197,96.34,95.50,79.58,97,0.435,240.0,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.50,79.58,94,0.565,240.0,CLE vs. GSW,1610612739,0.000,240,37,90,0.411,9,27,0.333,20,26,0.769231,16,26,42,25,9,4,10,15,103,1610612744,1.000,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,Playoffs,2017-18,2017,L,W,-19,19
10264,41700403,2018-06-06,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.50,78.75,94,0.569,240.0,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.50,78.75,95,0.431,240.0,CLE vs. GSW,1610612744,1.000,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,1610612739,0.000,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,Playoffs,2017-18,2017,W,L,8,-8
10265,41700404,2018-06-08,Warriors,GSW,Golden State,240:00,0 days 04:00:00,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.50,75.42,91,0.672,240.0,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.50,75.42,90,0.328,240.0,CLE vs. GSW,1610612744,1.000,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,1610612739,0.000,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,Playoffs,2017-18,2017,W,L,23,-23

In [3]:
df_game_id_team_id = f.wide2tall(df_away_home, ['game_id', 'team_id'], ['_away', '_home'])
df_game_id_team_id = sr(df_game_id_team_id, 'game_date')
p(df_game_id_team_id)

(20532, 59)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017

In [4]:
df_game_id_team_id['a'] = df_game_id_team_id.matchup.str.split(' vs. ').str[0].str.strip()

df_game_id_team_id['b'] = df_game_id_team_id.matchup.str.split(' vs. ').str[1].str.strip()


p(df_game_id_team_id)

(20532, 61)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW

In [5]:
df_game_id_team_id.loc[df_game_id_team_id['a'] == df_game_id_team_id['TEAM_ABBREVIATION'], '_a'] = 1

df_game_id_team_id.loc[df_game_id_team_id['a'] != df_game_id_team_id['TEAM_ABBREVIATION'], '_a'] = 0


p(df_game_id_team_id)

(20532, 62)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0

In [6]:
df_game_id_team_id.loc[df_game_id_team_id['b'] == df_game_id_team_id['TEAM_ABBREVIATION'], '_b'] = 1

df_game_id_team_id.loc[df_game_id_team_id['b'] != df_game_id_team_id['TEAM_ABBREVIATION'], '_b'] = 0


p(df_game_id_team_id)

(20532, 63)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0

In [7]:
df_game_id_team_id = pd.concat([df_game_id_team_id, pd.get_dummies(df_game_id_team_id[['wl']])], axis=1)
p(df_game_id_team_id)

(20532, 65)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b,wl_L,wl_W
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0,1,0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0,0,1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0,1,0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0,0,1
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0,1,0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,1,0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,1,0

In [8]:
df_game_id_team_id.rename(columns={'wl_L': 'loss', 'wl_W': 'win'}, inplace=True)

In [9]:
p(df_game_id_team_id)

(20532, 65)

,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b,loss,win
0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0,1,0
1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0,0,1
2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0,1,0
3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0,0,1
4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0,1,0
20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,1,0
20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,1,0

In [10]:
df_loss_win = df_game_id_team_id.loc[:, ['game_id', 'team_id', 'season', 'loss', 'win']]
p(df_loss_win)

(20532, 5)

        game_id     team_id   season  loss  win
0      21000001  1610612748  2010-11     1    0
1      21000001  1610612738  2010-11     0    1
2      21000002  1610612756  2010-11     1    0
3      21000002  1610612757  2010-11     0    1
4      21000003  1610612745  2010-11     1    0
20527  41700402  1610612744  2017-18     0    1
20528  41700403  1610612744  2017-18     0    1
20529  41700403  1610612739  2017-18     1    0
20530  41700404  1610612744  2017-18     0    1
20531  41700404  1610612739  2017-18     1    0

In [11]:
df_losses_wins = df_loss_win.groupby(['team_id', 'season']).apply(lambda x: x.rolling(9999, 1).sum().shift())[['loss', 'win']]
p(df_losses_wins)

(20532, 2)

                          loss   win
team_id    season
1610612737 2010-11 13      NaN   NaN
                   49      0.0   1.0
                   63      0.0   2.0
                   97      0.0   3.0
                   112     0.0   4.0
1610612766 2017-18 20217  43.0  34.0
                   20228  44.0  34.0
                   20270  45.0  34.0
                   20305  45.0  35.0
                   20339  46.0  35.0

In [12]:
df_losses_wins = df_losses_wins.reset_index()
p(df_losses_wins)

(20532, 5)

          team_id   season  level_2  loss   win
0      1610612737  2010-11       13   NaN   NaN
1      1610612737  2010-11       49   0.0   1.0
2      1610612737  2010-11       63   0.0   2.0
3      1610612737  2010-11       97   0.0   3.0
4      1610612737  2010-11      112   0.0   4.0
20527  1610612766  2017-18    20217  43.0  34.0
20528  1610612766  2017-18    20228  44.0  34.0
20529  1610612766  2017-18    20270  45.0  34.0
20530  1610612766  2017-18    20305  45.0  35.0
20531  1610612766  2017-18    20339  46.0  35.0

In [13]:
df_losses_wins.rename(columns={'level_2': 'index', 'loss':'losses', 'win':'wins'}, inplace=True)
p(df_losses_wins)

(20532, 5)

          team_id   season  index  losses  wins
0      1610612737  2010-11     13     NaN   NaN
1      1610612737  2010-11     49     0.0   1.0
2      1610612737  2010-11     63     0.0   2.0
3      1610612737  2010-11     97     0.0   3.0
4      1610612737  2010-11    112     0.0   4.0
20527  1610612766  2017-18  20217    43.0  34.0
20528  1610612766  2017-18  20228    44.0  34.0
20529  1610612766  2017-18  20270    45.0  34.0
20530  1610612766  2017-18  20305    45.0  35.0
20531  1610612766  2017-18  20339    46.0  35.0

In [14]:
df_game_id_team_id = df_game_id_team_id.reset_index()
p(df_game_id_team_id)

(20532, 66)

,index,game_id,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,duration,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,duration_minutes,team_id,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,wl,spread,away_home_,game_date,matchup,season_type,season,season_year,a,b,_a,_b,loss,win
0,0,21000001,Heat,MIA,Miami,240:00,0 days 04:00:00,87.9,87.9,95.7,95.7,-7.7,-7.7,0.556,0.88,12.8,0.250,0.732,0.472,18.681,18.7,0.419,0.471,1.0,0.200,91.50,91.5,76.25,91,0.401,240.0,1610612748,0.0,240,27,74,0.365,8,20,0.400,18,25,0.720000,11,28,39,15,10,6,17,21,80,L,8,0,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,0.0,1.0,1,0
1,1,21000001,Celtics,BOS,Boston,240:00,0 days 04:00:00,95.7,95.7,87.9,87.9,7.7,7.7,0.781,1.25,20.0,0.268,0.750,0.528,21.739,21.7,0.522,0.550,1.0,0.196,91.50,91.5,76.25,92,0.599,240.0,1610612738,1.0,240,32,69,0.464,8,16,0.500,16,25,0.640000,8,34,42,25,6,4,18,19,88,W,-8,1,2010-10-26,BOS vs. MIA,Regular Season,2010-11,2010,BOS,MIA,1.0,0.0,0,1
2,2,21000002,Suns,PHX,Phoenix,240:00,0 days 04:00:00,98.9,102.2,109.7,117.8,-10.8,-15.6,0.417,0.79,13.0,0.244,0.510,0.391,20.421,21.1,0.547,0.568,1.0,0.196,94.82,90.0,75.00,90,0.375,240.0,1610612756,0.0,240,36,74,0.486,9,19,0.474,11,16,0.687500,7,23,30,15,3,4,19,19,92,L,14,0,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,1.0,0.0,1,0
3,3,21000002,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,109.7,117.8,98.9,102.2,10.8,15.6,0.721,2.07,21.3,0.490,0.756,0.609,15.528,16.7,0.516,0.532,1.0,0.192,94.82,90.0,75.00,90,0.625,240.0,1610612757,1.0,240,43,93,0.462,10,20,0.500,10,15,0.666667,18,30,48,31,11,2,12,22,106,W,-14,1,2010-10-26,PHX vs. POR,Regular Season,2010-11,2010,PHX,POR,0.0,1.0,0,1
4,4,21000003,Rockets,HOU,Houston,240:00,0 days 04:00:00,101.6,106.8,105.3,107.7,-3.8,-0.9,0.658,1.19,16.7,0.396,0.695,0.554,19.387,20.4,0.462,0.532,1.0,0.196,107.32,103.5,86.25,103,0.507,240.0,1610612745,0.0,240,38,91,0.418,8,20,0.400,26,28,0.928571,16,37,53,25,6,7,20,25,110,L,2,0,2010-10-26,HOU vs. LAL,Regular Season,2010-11,2010,HOU,LAL,1.0,0.0,1,0
20527,20527,41700402,Warriors,GSW,Golden State,240:00,0 days 04:00:00,126.8,129.8,106.8,106.2,20.0,23.6,0.596,2.33,21.3,0.289,0.618,0.484,12.469,12.8,0.665,0.669,1.0,0.200,96.34,95.5,79.58,94,0.565,240.0,1610612744,1.0,240,47,82,0.573,15,36,0.417,13,21,0.619048,7,34,41,28,3,8,12,25,122,W,-19,1,2018-06-03,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20528,20528,41700403,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.6,117.0,103.6,107.4,13.0,9.7,0.643,2.45,21.2,0.195,0.611,0.432,11.657,11.7,0.574,0.615,1.0,0.199,96.42,94.5,78.75,94,0.569,240.0,1610612744,1.0,240,42,81,0.519,9,26,0.346,17,19,0.894737,6,31,37,27,6,5,10,20,110,W,-8,0,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20529,20529,41700403,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,103.6,107.4,116.6,117.0,-13.0,-9.7,0.500,1.43,15.0,0.389,0.805,0.568,14.216,14.7,0.484,0.513,1.0,0.197,96.42,94.5,78.75,95,0.431,240.0,1610612739,0.0,240,40,92,0.435,9,31,0.290,13,17,0.764706,15,32,47,20,6,4,13,18,102,L,8,1,2018-06-06,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,1,0
20530,20530,41700404,Warriors,GSW,Golden State,240:00,0 days 04:00:00,116.1,118.7,92.4,94.4,23.7,24.2,0.641,2.50,19.5,0.319,0.667,0.514,10.748,11.0,0.535,0.580,1.0,0.196,92.52,90.5,75.42,91,0.672,240.0,1610612744,1.0,240,39,86,0.453,14,38,0.368,16,16,1.000000,10,34,44,25,7,13,8,24,108,W,-23,0,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,0.0,1.0,0,1
20531,20531,41700404,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,92.4,94.4,116.1,118.7,-23.7,-24.2,0.700,1.91,16.2,0.333,0.681,0.486,11.957,12.2,0.391,0.434,1.0,0.198,92.52,90.5,75.42,90,0.328,240.0,1610612739,0.0,240,30,87,0.345,8,27,0.296,17,25,0.680000,17,27,44,21,5,5,11,22,85,L,23,1,2018-06-08,CLE vs. GSW,Playoffs,2017-18,2017,CLE,GSW,1.0,0.0,1,0

In [15]:
df_game_id_team_id_subset = df_game_id_team_id.loc[:, ['index', 'game_id', 'game_date', 'season', 'team_id', 'TEAM_ABBREVIATION', '_a']]
p(df_game_id_team_id_subset)

(20532, 7)

       index   game_id  game_date   season     team_id TEAM_ABBREVIATION   _a
0          0  21000001 2010-10-26  2010-11  1610612748               MIA  0.0
1          1  21000001 2010-10-26  2010-11  1610612738               BOS  1.0
2          2  21000002 2010-10-26  2010-11  1610612756               PHX  1.0
3          3  21000002 2010-10-26  2010-11  1610612757               POR  0.0
4          4  21000003 2010-10-26  2010-11  1610612745               HOU  1.0
20527  20527  41700402 2018-06-03  2017-18  1610612744               GSW  0.0
20528  20528  41700403 2018-06-06  2017-18  1610612744               GSW  0.0
20529  20529  41700403 2018-06-06  2017-18  1610612739               CLE  1.0
20530  20530  41700404 2018-06-08  2017-18  1610612744               GSW  0.0
20531  20531  41700404 2018-06-08  2017-18  1610612739               CLE  1.0

In [16]:
df_losses_wins = pd.merge(df_game_id_team_id_subset, df_losses_wins, on=['index', 'season', 'team_id'])
p(df_losses_wins)

(20532, 9)

,index,game_id,game_date,season,team_id,TEAM_ABBREVIATION,_a,losses,wins
0,0,21000001,2010-10-26,2010-11,1610612748,MIA,0.0,NaN,NaN
1,1,21000001,2010-10-26,2010-11,1610612738,BOS,1.0,NaN,NaN
2,2,21000002,2010-10-26,2010-11,1610612756,PHX,1.0,NaN,NaN
3,3,21000002,2010-10-26,2010-11,1610612757,POR,0.0,NaN,NaN
4,4,21000003,2010-10-26,2010-11,1610612745,HOU,1.0,NaN,NaN
20527,20527,41700402,2018-06-03,2017-18,1610612744,GSW,0.0,29.0,71.0
20528,20528,41700403,2018-06-06,2017-18,1610612744,GSW,0.0,29.0,72.0
20529,20529,41700403,2018-06-06,2017-18,1610612739,CLE,1.0,40.0,62.0
20530,20530,41700404,2018-06-08,2017-18,1610612744,GSW,0.0,29.0,73.0
20531,20531,41700404,2018-06-08,2017-18,1610612739,CLE,1.0,41.0,62.0

In [17]:
df_losses_wins['win_pct'] = df_losses_wins.loc[:,'wins'] / \
                            (df_losses_wins.loc[:,'wins'] + df_losses_wins.loc[:,'losses'])
p(df_losses_wins)

(20532, 10)

,index,game_id,game_date,season,team_id,TEAM_ABBREVIATION,_a,losses,wins,win_pct
0,0,21000001,2010-10-26,2010-11,1610612748,MIA,0.0,NaN,NaN,NaN
1,1,21000001,2010-10-26,2010-11,1610612738,BOS,1.0,NaN,NaN,NaN
2,2,21000002,2010-10-26,2010-11,1610612756,PHX,1.0,NaN,NaN,NaN
3,3,21000002,2010-10-26,2010-11,1610612757,POR,0.0,NaN,NaN,NaN
4,4,21000003,2010-10-26,2010-11,1610612745,HOU,1.0,NaN,NaN,NaN
20527,20527,41700402,2018-06-03,2017-18,1610612744,GSW,0.0,29.0,71.0,0.710000
20528,20528,41700403,2018-06-06,2017-18,1610612744,GSW,0.0,29.0,72.0,0.712871
20529,20529,41700403,2018-06-06,2017-18,1610612739,CLE,1.0,40.0,62.0,0.607843
20530,20530,41700404,2018-06-08,2017-18,1610612744,GSW,0.0,29.0,73.0,0.715686
20531,20531,41700404,2018-06-08,2017-18,1610612739,CLE,1.0,41.0,62.0,0.601942

In [18]:
df_losses_wins.drop(columns='index', inplace=True)
p(df_losses_wins)

(20532, 9)

,game_id,game_date,season,team_id,TEAM_ABBREVIATION,_a,losses,wins,win_pct
0,21000001,2010-10-26,2010-11,1610612748,MIA,0.0,NaN,NaN,NaN
1,21000001,2010-10-26,2010-11,1610612738,BOS,1.0,NaN,NaN,NaN
2,21000002,2010-10-26,2010-11,1610612756,PHX,1.0,NaN,NaN,NaN
3,21000002,2010-10-26,2010-11,1610612757,POR,0.0,NaN,NaN,NaN
4,21000003,2010-10-26,2010-11,1610612745,HOU,1.0,NaN,NaN,NaN
20527,41700402,2018-06-03,2017-18,1610612744,GSW,0.0,29.0,71.0,0.710000
20528,41700403,2018-06-06,2017-18,1610612744,GSW,0.0,29.0,72.0,0.712871
20529,41700403,2018-06-06,2017-18,1610612739,CLE,1.0,40.0,62.0,0.607843
20530,41700404,2018-06-08,2017-18,1610612744,GSW,0.0,29.0,73.0,0.715686
20531,41700404,2018-06-08,2017-18,1610612739,CLE,1.0,41.0,62.0,0.601942

In [19]:
df_losses_wins_ab = f.tall2wide2(df_losses_wins, ['game_id', 'game_date', 'season'], '_a')
p(df_losses_wins_ab)

(10266, 13)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,game_date,season,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b
0,21000001,2010-10-26,2010-11,1610612738,BOS,NaN,NaN,NaN,1610612748,MIA,NaN,NaN,NaN
1,21000002,2010-10-26,2010-11,1610612756,PHX,NaN,NaN,NaN,1610612757,POR,NaN,NaN,NaN
2,21000003,2010-10-26,2010-11,1610612745,HOU,NaN,NaN,NaN,1610612747,LAL,NaN,NaN,NaN
3,21000006,2010-10-27,2010-11,1610612748,MIA,1.0,0.0,0.000000,1610612755,PHI,NaN,NaN,NaN
4,21000005,2010-10-27,2010-11,1610612765,DET,NaN,NaN,NaN,1610612751,NJN,NaN,NaN,NaN
10261,41700317,2018-05-28,2017-18,1610612744,GSW,29.0,69.0,0.704082,1610612745,HOU,22.0,76.0,0.775510
10262,41700401,2018-05-31,2017-18,1610612739,CLE,38.0,62.0,0.620000,1610612744,GSW,29.0,70.0,0.707071
10263,41700402,2018-06-03,2017-18,1610612739,CLE,39.0,62.0,0.613861,1610612744,GSW,29.0,71.0,0.710000
10264,41700403,2018-06-06,2017-18,1610612739,CLE,40.0,62.0,0.607843,1610612744,GSW,29.0,72.0,0.712871
10265,41700404,2018-06-08,2017-18,1610612739,CLE,41.0,62.0,0.601942,1610612744,GSW,29.0,73.0,0.715686

In [20]:
df_losses_wins_ab['opp_win_pct_a'] = df_losses_wins_ab['win_pct_b']
df_losses_wins_ab['opp_win_pct_b'] = df_losses_wins_ab['win_pct_a']

df_losses_wins_ab['opp_losses_a'] = df_losses_wins_ab['losses_b']
df_losses_wins_ab['opp_wins_a'] = df_losses_wins_ab['wins_b']

df_losses_wins_ab['opp_losses_b'] = df_losses_wins_ab['losses_a']
df_losses_wins_ab['opp_wins_b'] = df_losses_wins_ab['wins_a']

p(df_losses_wins_ab)

(10266, 19)

,game_id,game_date,season,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_a,opp_win_pct_b,opp_losses_a,opp_wins_a,opp_losses_b,opp_wins_b
0,21000001,2010-10-26,2010-11,1610612738,BOS,NaN,NaN,NaN,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,2010-10-26,2010-11,1610612756,PHX,NaN,NaN,NaN,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,2010-10-26,2010-11,1610612745,HOU,NaN,NaN,NaN,1610612747,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000006,2010-10-27,2010-11,1610612748,MIA,1.0,0.0,0.000000,1610612755,PHI,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,1.0,0.0
4,21000005,2010-10-27,2010-11,1610612765,DET,NaN,NaN,NaN,1610612751,NJN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10261,41700317,2018-05-28,2017-18,1610612744,GSW,29.0,69.0,0.704082,1610612745,HOU,22.0,76.0,0.775510,0.775510,0.704082,22.0,76.0,29.0,69.0
10262,41700401,2018-05-31,2017-18,1610612739,CLE,38.0,62.0,0.620000,1610612744,GSW,29.0,70.0,0.707071,0.707071,0.620000,29.0,70.0,38.0,62.0
10263,41700402,2018-06-03,2017-18,1610612739,CLE,39.0,62.0,0.613861,1610612744,GSW,29.0,71.0,0.710000,0.710000,0.613861,29.0,71.0,39.0,62.0
10264,41700403,2018-06-06,2017-18,1610612739,CLE,40.0,62.0,0.607843,1610612744,GSW,29.0,72.0,0.712871,0.712871,0.607843,29.0,72.0,40.0,62.0
10265,41700404,2018-06-08,2017-18,1610612739,CLE,41.0,62.0,0.601942,1610612744,GSW,29.0,73.0,0.715686,0.715686,0.601942,29.0,73.0,41.0,62.0

In [21]:
df_losses_wins_opp_losses_wins = f.wide2tall(df_losses_wins_ab, ['game_id', 'team_id'], ['_a', '_b'])
p(df_losses_wins_opp_losses_wins)

(20532, 12)

,game_id,team_id,TEAM_ABBREVIATION,losses,wins,win_pct,opp_win_pct,opp_losses,opp_wins,a_b_,game_date,season
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
1,21000001,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11
2,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
3,21000002,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11
4,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
20527,41700402,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,1,2018-06-03,2017-18
20528,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,0,2018-06-06,2017-18
20529,41700403,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,1,2018-06-06,2017-18
20530,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,0,2018-06-08,2017-18
20531,41700404,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,1,2018-06-08,2017-18

In [22]:
df_losses_wins_opp_losses_wins = sr(df_losses_wins_opp_losses_wins, ['game_date'])
p(df_losses_wins_opp_losses_wins)

(20532, 12)

,game_id,team_id,TEAM_ABBREVIATION,losses,wins,win_pct,opp_win_pct,opp_losses,opp_wins,a_b_,game_date,season
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
1,21000001,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11
2,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
3,21000002,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11
4,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
20527,41700402,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,1,2018-06-03,2017-18
20528,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,0,2018-06-06,2017-18
20529,41700403,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,1,2018-06-06,2017-18
20530,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,0,2018-06-08,2017-18
20531,41700404,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,1,2018-06-08,2017-18

In [23]:
df_losses_wins_opp_losses_wins_rgd = df_losses_wins_opp_losses_wins.drop(columns=['game_date'])
p(df_losses_wins_opp_losses_wins_rgd)

(20532, 11)

,game_id,team_id,TEAM_ABBREVIATION,losses,wins,win_pct,opp_win_pct,opp_losses,opp_wins,a_b_,season
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-11
1,21000001,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-11
2,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-11
3,21000002,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-11
4,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-11
20527,41700402,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,1,2017-18
20528,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,0,2017-18
20529,41700403,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,1,2017-18
20530,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,0,2017-18
20531,41700404,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,1,2017-18

In [24]:
df_opp_losses_wins = df_losses_wins_opp_losses_wins_rgd.loc[:, ['team_id', 'season', 'opp_losses', 'opp_wins']]
p(df_opp_losses_wins)

(20532, 4)

          team_id   season  opp_losses  opp_wins
0      1610612738  2010-11         NaN       NaN
1      1610612748  2010-11         NaN       NaN
2      1610612756  2010-11         NaN       NaN
3      1610612757  2010-11         NaN       NaN
4      1610612745  2010-11         NaN       NaN
20527  1610612744  2017-18        39.0      62.0
20528  1610612739  2017-18        29.0      72.0
20529  1610612744  2017-18        40.0      62.0
20530  1610612739  2017-18        29.0      73.0
20531  1610612744  2017-18        41.0      62.0

In [25]:
df_opp_losses_wins_csum = df_opp_losses_wins.groupby(['team_id', 'season']).apply(lambda x: x.rolling(9999, 1).sum())
p(df_opp_losses_wins_csum)

(20532, 3)

                               team_id  opp_losses  opp_wins
team_id    season
1610612737 2010-11 22     1.610613e+09         NaN       NaN
                   47     3.221225e+09         1.0       0.0
                   74     4.831838e+09         2.0       0.0
                   98     6.442451e+09         4.0       1.0
                   118    8.053064e+09         8.0       1.0
1610612766 2017-18 20200  1.256278e+11      1569.0    1456.0
                   20241  1.272384e+11      1620.0    1482.0
                   20286  1.288490e+11      1674.0    1506.0
                   20313  1.304596e+11      1707.0    1553.0
                   20336  1.320702e+11      1740.0    1601.0

In [26]:
df_opp_losses_wins_csum.drop(columns=['team_id'], inplace=True)
p(df_opp_losses_wins_csum)

(20532, 2)

                          opp_losses  opp_wins
team_id    season
1610612737 2010-11 22            NaN       NaN
                   47            1.0       0.0
                   74            2.0       0.0
                   98            4.0       1.0
                   118           8.0       1.0
1610612766 2017-18 20200      1569.0    1456.0
                   20241      1620.0    1482.0
                   20286      1674.0    1506.0
                   20313      1707.0    1553.0
                   20336      1740.0    1601.0

In [27]:
df_opp_losses_wins_csum = df_opp_losses_wins_csum.reset_index()
p(df_opp_losses_wins_csum)

(20532, 5)

          team_id   season  level_2  opp_losses  opp_wins
0      1610612737  2010-11       22         NaN       NaN
1      1610612737  2010-11       47         1.0       0.0
2      1610612737  2010-11       74         2.0       0.0
3      1610612737  2010-11       98         4.0       1.0
4      1610612737  2010-11      118         8.0       1.0
20527  1610612766  2017-18    20200      1569.0    1456.0
20528  1610612766  2017-18    20241      1620.0    1482.0
20529  1610612766  2017-18    20286      1674.0    1506.0
20530  1610612766  2017-18    20313      1707.0    1553.0
20531  1610612766  2017-18    20336      1740.0    1601.0

In [28]:
df_opp_losses_wins_csum.rename(columns={'level_2':'index', 
                                          'opp_losses':'opp_losses_csum',
                                          'opp_wins':'opp_wins_csum'}, inplace=True)
p(df_opp_losses_wins_csum)

(20532, 5)

          team_id   season  index  opp_losses_csum  opp_wins_csum
0      1610612737  2010-11     22              NaN            NaN
1      1610612737  2010-11     47              1.0            0.0
2      1610612737  2010-11     74              2.0            0.0
3      1610612737  2010-11     98              4.0            1.0
4      1610612737  2010-11    118              8.0            1.0
20527  1610612766  2017-18  20200           1569.0         1456.0
20528  1610612766  2017-18  20241           1620.0         1482.0
20529  1610612766  2017-18  20286           1674.0         1506.0
20530  1610612766  2017-18  20313           1707.0         1553.0
20531  1610612766  2017-18  20336           1740.0         1601.0

In [29]:
df_losses_wins_opp_losses_wins = df_losses_wins_opp_losses_wins.reset_index()
p(df_losses_wins_opp_losses_wins)

(20532, 13)

,index,game_id,team_id,TEAM_ABBREVIATION,losses,wins,win_pct,opp_win_pct,opp_losses,opp_wins,a_b_,game_date,season
0,0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
1,1,21000001,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11
2,2,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
3,3,21000002,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11
4,4,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11
20527,20527,41700402,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,1,2018-06-03,2017-18
20528,20528,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,0,2018-06-06,2017-18
20529,20529,41700403,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,1,2018-06-06,2017-18
20530,20530,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,0,2018-06-08,2017-18
20531,20531,41700404,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,1,2018-06-08,2017-18

In [30]:
df_lw_opplw_opplwcsum = pd.merge(df_losses_wins_opp_losses_wins,
                                          df_opp_losses_wins_csum,
                                          on=['team_id', 'season', 'index'])
p(df_lw_opplw_opplwcsum)

(20532, 15)

,index,game_id,team_id,TEAM_ABBREVIATION,losses,wins,win_pct,opp_win_pct,opp_losses,opp_wins,a_b_,game_date,season,opp_losses_csum,opp_wins_csum
0,0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11,NaN,NaN
1,1,21000001,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11,NaN,NaN
2,2,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11,NaN,NaN
3,3,21000002,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11,NaN,NaN
4,4,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11,NaN,NaN
20527,20527,41700402,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,1,2018-06-03,2017-18,2294.0,2719.0
20528,20528,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,0,2018-06-06,2017-18,2362.0,2898.0
20529,20529,41700403,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,1,2018-06-06,2017-18,2334.0,2781.0
20530,20530,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,0,2018-06-08,2017-18,2391.0,2971.0
20531,20531,41700404,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,1,2018-06-08,2017-18,2375.0,2843.0

In [31]:
#bit flip
df_lw_opplw_opplwcsum['a_b_'] = abs(df_lw_opplw_opplwcsum['a_b_'] - 1)
p(df_lw_opplw_opplwcsum)

(20532, 15)

,index,game_id,team_id,TEAM_ABBREVIATION,losses,wins,win_pct,opp_win_pct,opp_losses,opp_wins,a_b_,game_date,season,opp_losses_csum,opp_wins_csum
0,0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11,NaN,NaN
1,1,21000001,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11,NaN,NaN
2,2,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11,NaN,NaN
3,3,21000002,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-10-26,2010-11,NaN,NaN
4,4,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,1,2010-10-26,2010-11,NaN,NaN
20527,20527,41700402,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,0,2018-06-03,2017-18,2294.0,2719.0
20528,20528,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,1,2018-06-06,2017-18,2362.0,2898.0
20529,20529,41700403,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,0,2018-06-06,2017-18,2334.0,2781.0
20530,20530,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,1,2018-06-08,2017-18,2391.0,2971.0
20531,20531,41700404,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,0,2018-06-08,2017-18,2375.0,2843.0

In [32]:
df_lw_opplw_opplwcsum.drop(columns=['index'], inplace=True)

In [33]:
df_lw_opplw_opplwcsum_ab = f.tall2wide2(df_lw_opplw_opplwcsum,
                                  ['game_id', 'game_date', 'season'],
                                  'a_b_')
p(df_lw_opplw_opplwcsum_ab)

(10266, 23)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,game_id,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,opp_win_pct_a,opp_losses_a,opp_wins_a,game_date,season,opp_losses_csum_a,opp_wins_csum_a,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_b,opp_losses_b,opp_wins_b,opp_losses_csum_b,opp_wins_csum_b
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612747,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000013,1610612754,IND,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612759,SAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21000014,1610612743,DEN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612762,UTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10261,41700317,1610612744,GSW,29.0,69.0,0.704082,0.775510,22.0,76.0,2018-05-28,2017-18,2217.0,2595.0,1610612745,HOU,22.0,76.0,0.775510,0.704082,29.0,69.0,2243.0,2676.0
10262,41700401,1610612739,CLE,38.0,62.0,0.620000,0.707071,29.0,70.0,2018-05-31,2017-18,2304.0,2755.0,1610612744,GSW,29.0,70.0,0.707071,0.620000,38.0,62.0,2255.0,2657.0
10263,41700402,1610612739,CLE,39.0,62.0,0.613861,0.710000,29.0,71.0,2018-06-03,2017-18,2333.0,2826.0,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,2294.0,2719.0
10264,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,2018-06-06,2017-18,2362.0,2898.0,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,2334.0,2781.0
10265,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,2018-06-08,2017-18,2391.0,2971.0,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,2375.0,2843.0

In [34]:
df_lw_opplw_opplwcsum_ab.rename(columns={'opp_losses_csum_a':'opp_opps_losses_b',
                             'opp_wins_csum_a':'opp_opps_wins_b',
                             'opp_losses_csum_b':'opp_opps_losses_a',
                             'opp_wins_csum_b':'opp_opps_wins_a'}, inplace=True)
p(df_lw_opplw_opplwcsum_ab)

(10266, 23)

,game_id,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,opp_win_pct_a,opp_losses_a,opp_wins_a,game_date,season,opp_opps_losses_b,opp_opps_wins_b,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_b,opp_losses_b,opp_wins_b,opp_opps_losses_a,opp_opps_wins_a
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612747,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000013,1610612754,IND,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612759,SAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21000014,1610612743,DEN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612762,UTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10261,41700317,1610612744,GSW,29.0,69.0,0.704082,0.775510,22.0,76.0,2018-05-28,2017-18,2217.0,2595.0,1610612745,HOU,22.0,76.0,0.775510,0.704082,29.0,69.0,2243.0,2676.0
10262,41700401,1610612739,CLE,38.0,62.0,0.620000,0.707071,29.0,70.0,2018-05-31,2017-18,2304.0,2755.0,1610612744,GSW,29.0,70.0,0.707071,0.620000,38.0,62.0,2255.0,2657.0
10263,41700402,1610612739,CLE,39.0,62.0,0.613861,0.710000,29.0,71.0,2018-06-03,2017-18,2333.0,2826.0,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,2294.0,2719.0
10264,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,2018-06-06,2017-18,2362.0,2898.0,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,2334.0,2781.0
10265,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,2018-06-08,2017-18,2391.0,2971.0,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,2375.0,2843.0

In [35]:
p(df_lw_opplw_opplwcsum_ab)

(10266, 23)

,game_id,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,opp_win_pct_a,opp_losses_a,opp_wins_a,game_date,season,opp_opps_losses_b,opp_opps_wins_b,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_b,opp_losses_b,opp_wins_b,opp_opps_losses_a,opp_opps_wins_a
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612747,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000013,1610612754,IND,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612759,SAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21000014,1610612743,DEN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612762,UTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10261,41700317,1610612744,GSW,29.0,69.0,0.704082,0.775510,22.0,76.0,2018-05-28,2017-18,2217.0,2595.0,1610612745,HOU,22.0,76.0,0.775510,0.704082,29.0,69.0,2243.0,2676.0
10262,41700401,1610612739,CLE,38.0,62.0,0.620000,0.707071,29.0,70.0,2018-05-31,2017-18,2304.0,2755.0,1610612744,GSW,29.0,70.0,0.707071,0.620000,38.0,62.0,2255.0,2657.0
10263,41700402,1610612739,CLE,39.0,62.0,0.613861,0.710000,29.0,71.0,2018-06-03,2017-18,2333.0,2826.0,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,2294.0,2719.0
10264,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,2018-06-06,2017-18,2362.0,2898.0,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,2334.0,2781.0
10265,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,2018-06-08,2017-18,2391.0,2971.0,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,2375.0,2843.0

In [36]:
df_lw_opplw_opplwcsum_ab['opp_opps_win_pct_a'] = df_lw_opplw_opplwcsum_ab['opp_opps_wins_a'] \
                                                        / (df_lw_opplw_opplwcsum_ab['opp_opps_losses_a']
                                                         + df_lw_opplw_opplwcsum_ab['opp_opps_wins_a'])

df_lw_opplw_opplwcsum_ab['opp_opps_win_pct_b'] = df_lw_opplw_opplwcsum_ab['opp_opps_wins_b'] \
                                                        / (df_lw_opplw_opplwcsum_ab['opp_opps_losses_b']
                                                         + df_lw_opplw_opplwcsum_ab['opp_opps_wins_b'])
p(df_lw_opplw_opplwcsum_ab)

(10266, 25)

,game_id,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,opp_win_pct_a,opp_losses_a,opp_wins_a,game_date,season,opp_opps_losses_b,opp_opps_wins_b,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_b,opp_losses_b,opp_wins_b,opp_opps_losses_a,opp_opps_wins_a,opp_opps_win_pct_a,opp_opps_win_pct_b
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612747,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000013,1610612754,IND,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612759,SAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21000014,1610612743,DEN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612762,UTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10261,41700317,1610612744,GSW,29.0,69.0,0.704082,0.775510,22.0,76.0,2018-05-28,2017-18,2217.0,2595.0,1610612745,HOU,22.0,76.0,0.775510,0.704082,29.0,69.0,2243.0,2676.0,0.544013,0.539277
10262,41700401,1610612739,CLE,38.0,62.0,0.620000,0.707071,29.0,70.0,2018-05-31,2017-18,2304.0,2755.0,1610612744,GSW,29.0,70.0,0.707071,0.620000,38.0,62.0,2255.0,2657.0,0.540920,0.544574
10263,41700402,1610612739,CLE,39.0,62.0,0.613861,0.710000,29.0,71.0,2018-06-03,2017-18,2333.0,2826.0,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,2294.0,2719.0,0.542390,0.547781
10264,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,2018-06-06,2017-18,2362.0,2898.0,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,2334.0,2781.0,0.543695,0.550951
10265,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,2018-06-08,2017-18,2391.0,2971.0,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,2375.0,2843.0,0.544845,0.554084

In [37]:
df_lw_opplw_opplwcsum_ab['strength_of_schedule_a'] = (2 * df_lw_opplw_opplwcsum_ab['opp_win_pct_a']
                                                        + df_lw_opplw_opplwcsum_ab['opp_opps_win_pct_a']) \
                                                        / 3

df_lw_opplw_opplwcsum_ab['strength_of_schedule_b'] = (2 * df_lw_opplw_opplwcsum_ab['opp_win_pct_b'] 
                                                        + df_lw_opplw_opplwcsum_ab['opp_opps_win_pct_b']) \
                                                        / 3

p(df_lw_opplw_opplwcsum_ab)

(10266, 27)

,game_id,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,opp_win_pct_a,opp_losses_a,opp_wins_a,game_date,season,opp_opps_losses_b,opp_opps_wins_b,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_b,opp_losses_b,opp_wins_b,opp_opps_losses_a,opp_opps_wins_a,opp_opps_win_pct_a,opp_opps_win_pct_b,strength_of_schedule_a,strength_of_schedule_b
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612747,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000013,1610612754,IND,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612759,SAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21000014,1610612743,DEN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612762,UTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10261,41700317,1610612744,GSW,29.0,69.0,0.704082,0.775510,22.0,76.0,2018-05-28,2017-18,2217.0,2595.0,1610612745,HOU,22.0,76.0,0.775510,0.704082,29.0,69.0,2243.0,2676.0,0.544013,0.539277,0.698344,0.649147
10262,41700401,1610612739,CLE,38.0,62.0,0.620000,0.707071,29.0,70.0,2018-05-31,2017-18,2304.0,2755.0,1610612744,GSW,29.0,70.0,0.707071,0.620000,38.0,62.0,2255.0,2657.0,0.540920,0.544574,0.651687,0.594858
10263,41700402,1610612739,CLE,39.0,62.0,0.613861,0.710000,29.0,71.0,2018-06-03,2017-18,2333.0,2826.0,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,2294.0,2719.0,0.542390,0.547781,0.654130,0.591834
10264,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,2018-06-06,2017-18,2362.0,2898.0,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,2334.0,2781.0,0.543695,0.550951,0.656479,0.588879
10265,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,2018-06-08,2017-18,2391.0,2971.0,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,2375.0,2843.0,0.544845,0.554084,0.658739,0.585989

In [38]:
df_lw_opplw_opplwcsum_ab.head(100)

,game_id,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,opp_win_pct_a,opp_losses_a,opp_wins_a,game_date,season,opp_opps_losses_b,opp_opps_wins_b,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_b,opp_losses_b,opp_wins_b,opp_opps_losses_a,opp_opps_wins_a,opp_opps_win_pct_a,opp_opps_win_pct_b,strength_of_schedule_a,strength_of_schedule_b
0,21000001,1610612738,BOS,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612748,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21000002,1610612756,PHX,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612757,POR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21000003,1610612745,HOU,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-26,2010-11,NaN,NaN,1610612747,LAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21000013,1610612754,IND,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612759,SAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21000014,1610612743,DEN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612762,UTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,21000015,1610612744,GSW,NaN,NaN,NaN,0.000000,1.0,0.0,2010-10-27,2010-11,1.0,0.0,1610612745,HOU,1.0,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
6,21000010,1610612749,MIL,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612740,NOH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,21000011,1610612741,CHI,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612760,OKC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,21000012,1610612766,CHA,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612742,DAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,21000009,1610612750,MIN,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612758,SAC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,21000008,1610612737,ATL,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612763,MEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,21000016,1610612746,LAC,NaN,NaN,NaN,1.000000,0.0,1.0,2010-10-27,2010-11,0.0,1.0,1610612757,POR,0.0,1.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
12,21000004,1610612738,BOS,0.0,1.0,1.000000,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612739,CLE,NaN,NaN,NaN,1.000000,0.0,1.0,0.0,1.0,1.000000,NaN,NaN,NaN
13,21000005,1610612765,DET,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612751,NJN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,21000006,1610612748,MIA,1.0,0.0,0.000000,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612755,PHI,NaN,NaN,NaN,0.000000,1.0,0.0,1.0,0.0,0.000000,NaN,NaN,NaN
15,21000007,1610612752,NYK,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-27,2010-11,NaN,NaN,1610612761,TOR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,21000018,1610612756,PHX,1.0,0.0,0.000000,0.000000,1.0,0.0,2010-10-28,2010-11,1.0,0.0,1610612762,UTA,1.0,0.0,0.000000,0.000000,1.0,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000
17,21000017,1610612753,ORL,NaN,NaN,NaN,NaN,NaN,NaN,2010-10-28,2010-11,NaN,NaN,1610612764,WAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,21000019,1610612766,CHA,1.0,0.0,0.000000,0.000000,1.0,0.0,2010-10-29,2010-11,1.0,0.0,1610612754,IND,1.0,0.0,0.000000,0.000000,1.0,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000
19,21000022,1610612739,CLE,0.0,1.0,1.000000,0.000000,1.0,0.0,2010-10-29,2010-11,1.0,1.0,1610612761,TOR,1.0,0.0,0.000000,1.000000,0.0,1.0,0.0,1.0,1.000000,0.500000,0.333333,0.833333
20,21000020,1610612751,NJN,0.0,1.0,1.000000,1.000000,0.0,1.0,2010-10-29,2010-11,0.0,1.0,1610612758,SAC,0.0,1.0,1.000000,1.000000,0.0,1.0,0.0,1.0,1.000000,1.000000,1.000000,1.000000
21,21000023,1610612738,BOS,1.0,1.0,0.500000,1.000000,0.0,1.0,2010-10-29,2010-11,0.0,1.0,1610612752,NYK,0.0,1.0,1.000000,0.500000,1.0,1.0,1.0,1.0,0.500000,1.000000,0.833333,0.666667
22,21000024,1610612765,DET,1.0,0.0,0.000000,1.000000,0.0,1.0,2010-10-29,2010-11,0.0,1.0,1610612760,OKC,0.0,1.0,1.000000,0.000000,1.0,0.0,1.0,0.0,0.000000,1.000000,0.666667,0.333333
23,21000021,1610612737,ATL,0.0,1.0,1.000000,0.000000,1.0,0.0,2010-10-29,2010-11,1.0,0.0,1610612755,PHI,1.0,0.0,0.000000,1.000000,0.0,1.0,1.0,1.0,0.500000,0.000000,0.166667,0.666667
24,21000026,1610612749,MIL,1.0,0.0,0.000000,0.000000,1.0,0.0,2010-10-29,2010-11,1.0,0.0,1610612750,MIN,1.0,0.0,0.000000,0.000000,1.0,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000
25,21000027,1610612743,DEN,0.0,1.0,1.000000,1.000000,0.0,1.0,2010-10-29,2010-11,0.0,1.0,1610612740,NOH,0.0,1.0,1.000000,1.000000,0.0,1.0,0.0,1.0,1.000000,1.000000,1.000000,1.000000
26,21000029,1610612744,GSW,0.0,1.0,1.000000,0.000000,1.0,0.0,2010-10-29,2010-11,2.0,0.0,1610612746,LAC,1.0,0.0,0.000000,1.000000,0.0,1.0,0.0,2.0,1.000000,0.000000,0.333333,0.666667
27,21000025,1610612748,MIA,1.0,1.0,0.500000,1.000000,0.0,1.0,2010-10-29,2010-11,0.0,1.0,1610612753,ORL,0.0,1.0,1.000000,0.500000,1.0,1.0,1.0,1.0,0.500000,1.000000,0.833333,0.666667
28,21000030,1610612747,LAL,0.0,1.0,1.000000,0.500000,1.0,1.0,2010-10-29,2010-11,1.0,1.0,1610612756,PHX,1.0,1.0,0.500000,1.000000,0.0,1.0,1.0,1.0,0.500000,0.500000,0.500000,0.833333
29,21000028,1610612742,DAL,0.0,1.0,1.000000,0.000000,1.0,0.0,2010-10-29,2010-11,1.0,0.0,1610612763,MEM,1.0,0.0,0.000000,1.000000,0.0,1.0,0.0,1.0,1.000000,0.000000,0.333333,0.666667
30,21000037,1610612743,DEN,1.0,1.0,0.500000,0.000000,2.0,0.0,2010-10-30,2010-11,2.0,1.0,1610612745,HOU,2.0,0.0,0.000000,0.500000,1.0,1.0,1.0,1.0,0.500000,0.333333,0.166667,0.444444
31,21000039,1610612740,NOH,0.0,2.0,1.000000,1.000000,0.0,1.0,2010-10-30,2010-11,0.0,2.0,1610612759,SAS,0.0,1.0,1.000000,1.000000,0.0,2.0,0.0,2.0,1.000000,1.000000,1.000000,1.000000
32,21000038,1610612766,CHA,2.0,0.0,0.000000,0.000000,2.0,0.0,2010-10-30,2010-11,3.0,0.0,1610612749,MIL,2.0,0.0,0.000000,0.000000,2.0,0.0,3.0,0.0,0.000000,0.000000,0.000000,0.000000
33,21000035,1610612741,CHI,1.0,0.0,0.000000,0.000000,2.0,0.0,2010-10-30,2010-11,2.0,0.0,1610612765,DET,2.0,0.0,0.000000,0.000000,1.0,0.0,1.0,1.0,0.500000,0.000000,0.166667,0.000000
34,21000032,1610612739,CLE,1.0,1.0,0.500000,0.500000,1.0,1.0,2010-10-30,2010-11,2.0,2.0,1610612758,SAC,1.0,1.0,0.500000,0.500000,1.0,1.0,1.0,2.0,0.666667,0.500000,0.555556,0.500000
35,21000033,1610612752,NYK,1.0,1.0,0.500000,1.000000,0.0,2.0,2010-10-30,2010-11,1.0,3.0,1610612757,POR,0.0,2.0,1.000000,0.500000,1.0,1.0,1.0,1.0,0.500000,0.750000,0.833333,0.583333
36,21000031,1610612737,ATL,0.0,2.0,1.000000,0.000000,1.0,0.0,2010-10-30,2010-11,2.0,0.0,1610612764,WAS,1.0,0.0,0.000000,1.000000,0.0,2.0,0.0,2.0,1.000000,0.000000,0.333333,0.666667
37,21000034,1610612754,IND,1.0,1.0,0.500000,0.000000,2.0,0.0,2010-10-30,2010-11,3.0,0.0,1610612755,PHI,2.0,0.0,0.000000,0.500000,1.0,1.0,2.0,2.0,0.500000,0.000000,0.166667,0.333333
38,21000036,1610612763,MEM,1.0,1.0,0.500000,0.500000,1.0,1.0,2010-10-30,2010-11,1.0,2.0,1610612750,MIN,1.0,1.0,0.500000,0.500000,1.0,1.0,2.0,1.0,0.333333,0.666667,0.444444,0.555556
39,21000040,1610612748,MIA,1.0,2.0,0.666667,1.000000,0.0,2.0,2010-10-31,2010-11,0.0,3.0,1610612751,NJN,0.0,2.0,1.000000,0.666667,1.0,2.0,1.0,3.0,0.750000,1.000000,0.916667,0.777778
40,21000041,1610612742,DAL,1.0,1.0,0.500000,0.000000,2.0,0.0,2010-10-31,2010-11,3.0,0.0,1610612746,LAC,2.0,0.0,0.000000,0.500000,1.0,1.0,1.0,3.0,0.750000,0.000000,0.250000,0.333333
41,21000042,1610612760,OKC,0.0,2.0,1.000000,0.000000,2.0,0.0,2010-10-31,2010-11,3.0,0.0,1610612762,UTA,2.0,0.0,0.000000,1.000000,0.0,2.0,1.0,2.0,0.666667,0.000000,0.222222,0.666667
42,21000043,1610612744,GSW,0.0,2.0,1.000000,1.000000,0.0,2.0,2010-10-31,2010-11,2.0,2.0,1610612747,LAL,0.0,2.0,1.000000,1.000000,0.0,2.0,1.0,3.0,0.750000,0.500000,0.916667,0.833333
43,21000044,1610612741,CHI,1.0,1.0,0.500000,1.000000,0.0,3.0,2010-11-01,2010-11,2.0,3.0,1610612757,POR,0.0,3.0,1.000000,0.500000,1.0,1.0,2.0,2.0,0.500000,0.600000,0.833333,0.533333
44,21000045,1610612758,SAC,1.0,2.0,0.666667,0.500000,1.0,1.0,2010-11-01,2010-11,2.0,3.0,1610612761,TOR,1.0,1.0,0.500000,0.666667,1.0,2.0,1.0,3.0,0.750000,0.600000,0.583333,0.644444
45,21000046,1610612746,LAC,3.0,0.0,0.000000,0.500000,1.0,1.0,2010-11-01,2010-11,2.0,4.0,1610612759,SAS,1.0,1.0,0.500000,0.000000,3.0,0.0,3.0,2.0,0.400000,0.666667,0.466667,0.222222
46,21000050,1610612748,MIA,1.0,3.0,0.750000,0.333333,2.0,1.0,2010-11-02,2010-11,2.0,4.0,1610612750,MIN,2.0,1.0,0.333333,0.750000,1.0,3.0,3.0,4.0,0.571429,0.666667,0.412698,0.722222
47,21000052,1610612749,MIL,2.0,1.0,0.333333,0.750000,1.0,3.0,2010-11-02,2010-11,4.0,3.0,1610612757,POR,1.0,3.0,0.750000,0.333333,2.0,1.0,4.0,3.0,0.428571,0.428571,0.642857,0.365079
48,21000053,1610612747,LAL,0.0,3.0,1.000000,0.666667,1.0,2.0,2010-11-02,2010-11,2.0,5.0,1610612763,MEM,1.0,2.0,0.666667,1.000000,0.0,3.0,1.0,5.0,0.833333,0.714286,0.722222,0.904762
49,21000047,1610612737,ATL,0.0,3.0,1.000000,0.333333,2.0,1.0,2010-11-02,2010-11,4.0,1.0,1610612739,CLE,2.0,1.0,0.333333,1.000000,0.0,3.0,2.0,5.0,0.714286,0.200000,0.460317,0.733333
50,21000049,1610612738,BOS,1.0,2.0,0.666667,0.000000,3.0,0.0,2010-11-02,2010-11,3.0,1.0,1610612765,DET,3.0,0.0,0.000000,0.666667,1.0,2.0,2.0,3.0,0.600000,0.250000,0.200000,0.527778
51,21000048,1610612755,PHI,3.0,0.0,0.000000,0.000000,2.0,0.0,2010-11-02,2010-11,4.0,2.0,1610612764,WAS,2.0,0.0,0.000000,0.000000,3.0,0.0,3.0,2.0,0.400000,0.333333,0.133333,0.111111
52,21000063,1610612744,GSW,1.0,2.0,0.666667,0.500000,2.0,2.0,2010-11-03,2010-11,4.0,4.0,1610612763,MEM,2.0,2.0,0.500000,0.666667,1.0,2.0,2.0,7.0,0.777778,0.500000,0.592593,0.611111
53,21000061,1610612761,TOR,2.0,1.0,0.333333,0.333333,2.0,1.0,2010-11-03,2010-11,3.0,4.0,1610612762,UTA,2.0,1.0,0.333333,0.333333,2.0,1.0,3.0,3.0,0.500000,0.571429,0.388889,0.412698
54,21000060,1610612742,DAL,1.0,2.0,0.666667,0.666667,1.0,2.0,2010-11-03,2010-11,4.0,2.0,1610612743,DEN,1.0,2.0,0.666667,0.666667,1.0,2.0,3.0,3.0,0.500000,0.333333,0.611111,0.555556
55,21000065,1610612747,LAL,0.0,4.0,1.000000,0.750000,1.0,3.0,2010-11-03,2010-11,3.0,8.0,1610612758,SAC,1.0,3.0,0.750000,1.000000,0.0,4.0,2.0,7.0,0.777778,0.727273,0.759259,0.909091
56,21000062,1610612756,PHX,2.0,1.0,0.333333,0.666667,1.0,2.0,2010-11-03,2010-11,2.0,3.0,1610612759,SAS,1.0,2.0,0.666667,0.333333,2.0,1.0,5.0,3.0,0.375000,0.600000,0.569444,0.422222
57,21000064,1610612746,LAC,4.0,0.0,0.000000,0.666667,1.0,2.0,2010-11-03,2010-11,3.0,6.0,1610612760,OKC,1.0,2.0,0.666667,0.000000,4.0,0.0,7.0,0.0,0.000000,0.666667,0.444444,0.222222
58,21000057,1610612754,IND,1.0,2.0,0.666667,0.000000,4.0,0.0,2010-11-03,2010-11,7.0,0.0,1610612755,PHI,4.0,0.0,0.000000,0.666667,1.0,2.0,5.0,4.0,0.444444,0.000000,0.148148,0.444444
59,21000054,1610612737,ATL,0.0,4.0,1.000000,0.000000,4.0,0.0,2010-11-03,2010-11,8.0,1.0,1610612765,DET,4.0,0.0,0.000000,1.000000,0.0,4.0,2.0,7.0,0.777778,0.111111,0.259259,0.703704
60,21000056,1610612750,MIN,3.0,1.0,0.250000,0.500000,1.0,1.0,2010-11-03,2010-11,4.0,5.0,1610612753,ORL,1.0,1.0,0.500000,0.250000,3.0,1.0,4.0,2.0,0.333333,0.555556,0.444444,0.351852
61,21000059,1610612745,HOU,3.0,0.0,0.000000,1.000000,0.0,3.0,2010-11-03,2010-11,1.0,4.0,1610612740,NOH,0.0,3.0,1.000000,0.000000,3.0,0.0,3.0,2.0,0.400000,0.800000,0.800000,0.266667
62,21000058,1610612738,BOS,1.0,3.0,0.750000,0.250000,3.0,1.0,2010-11-03,2010-11,6.0,2.0,1610612749,MIL,3.0,1.0,0.250000,0.750000,1.0,3.0,5.0,6.0,0.545455,0.250000,0.348485,0.583333
63,21000055,1610612766,CHA,3.0,0.0,0.000000,0.666667,1.0,2.0,2010-11-03,2010-11,4.0,2.0,1610612751,NJN,1.0,2.0,0.666667,0.000000,3.0,0.0,4.0,3.0,0.428571,0.333333,0.587302,0.111111
64,21000067,1610612760,OKC,2.0,2.0,0.500000,0.800000,1.0,4.0,2010-11-04,2010-11,8.0,4.0,1610612757,POR,1.0,4.0,0.800000,0.500000,2.0,2.0,6.0,5.0,0.454545,0.333333,0.684848,0.444444
65,21000066,1610612741,CHI,1.0,2.0,0.666667,0.333333,2.0,1.0,2010-11-04,2010-11,4.0,4.0,1610612752,NYK,2.0,1.0,0.333333,0.666667,1.0,2.0,2.0,5.0,0.714286,0.500000,0.460317,0.611111
66,21000079,1610612747,LAL,0.0,5.0,1.000000,0.250000,3.0,1.0,2010-11-05,2010-11,6.0,9.0,1610612761,TOR,3.0,1.0,0.250000,1.000000,0.0,5.0,3.0,9.0,0.750000,0.600000,0.416667,0.866667
67,21000073,1610612738,BOS,1.0,4.0,0.800000,0.500000,2.0,2.0,2010-11-05,2010-11,8.0,4.0,1610612741,CHI,2.0,2.0,0.500000,0.800000,1.0,4.0,5.0,8.0,0.615385,0.333333,0.538462,0.644444
68,21000075,1610612748,MIA,1.0,4.0,0.800000,1.000000,0.0,4.0,2010-11-05,2010-11,2.0,8.0,1610612740,NOH,0.0,4.0,1.000000,0.800000,1.0,4.0,4.0,6.0,0.600000,0.800000,0.866667,0.800000
69,21000074,1610612737,ATL,0.0,5.0,1.000000,0.200000,4.0,1.0,2010-11-05,2010-11,12.0,2.0,1610612750,MIN,4.0,1.0,0.200000,1.000000,0.0,5.0,4.0,10.0,0.714286,0.142857,0.371429,0.714286
70,21000078,1610612744,GSW,1.0,3.0,0.750000,0.500000,2.0,2.0,2010-11-05,2010-11,6.0,6.0,1610612762,UTA,2.0,2.0,0.500000,0.750000,1.0,3.0,4.0,6.0,0.600000,0.500000,0.533333,0.666667
71,21000077,1610612743,DEN,2.0,2.0,0.500000,0.200000,4.0,1.0,2010-11-05,2010-11,7.0,4.0,1610612746,LAC,4.0,1.0,0.200000,0.500000,2.0,2.0,5.0,8.0,0.615385,0.363636,0.338462,0.454545
72,21000070,1610612739,CLE,3.0,1.0,0.250000,0.200000,4.0,1.0,2010-11-05,2010-11,6.0,6.0,1610612755,PHI,4.0,1.0,0.200000,0.250000,3.0,1.0,8.0,5.0,0.384615,0.500000,0.261538,0.333333
73,21000071,1610612766,CHA,3.0,1.0,0.250000,0.000000,5.0,0.0,2010-11-05,2010-11,9.0,2.0,1610612765,DET,5.0,0.0,0.000000,0.250000,3.0,1.0,5.0,8.0,0.615385,0.181818,0.205128,0.227273
74,21000069,1610612751,NJN,2.0,2.0,0.500000,0.666667,1.0,2.0,2010-11-05,2010-11,5.0,5.0,1610612753,ORL,1.0,2.0,0.666667,0.500000,2.0,2.0,6.0,4.0,0.400000,0.500000,0.577778,0.500000
75,21000068,1610612754,IND,2.0,2.0,0.500000,0.200000,4.0,1.0,2010-11-05,2010-11,11.0,1.0,1610612749,MIL,4.0,1.0,0.200000,0.500000,2.0,2.0,7.0,8.0,0.533333,0.083333,0.311111,0.361111
76,21000072,1610612752,NYK,2.0,2.0,0.500000,0.333333,2.0,1.0,2010-11-05,2010-11,4.0,6.0,1610612764,WAS,2.0,1.0,0.333333,0.500000,2.0,2.0,5.0,4.0,0.444444,0.600000,0.370370,0.533333
77,21000076,1610612763,MEM,3.0,2.0,0.400000,0.250000,3.0,1.0,2010-11-05,2010-11,5.0,8.0,1610612756,PHX,3.0,1.0,0.250000,0.400000,3.0,2.0,5.0,5.0,0.500000,0.615385,0.333333,0.471795
78,21000085,1610612742,DAL,1.0,3.0,0.750000,0.600000,2.0,3.0,2010-11-06,2010-11,6.0,5.0,1610612743,DEN,2.0,3.0,0.600000,0.750000,1.0,3.0,8.0,7.0,0.466667,0.454545,0.555556,0.651515
79,21000084,1610612745,HOU,4.0,0.0,0.000000,0.750000,1.0,3.0,2010-11-06,2010-11,2.0,7.0,1610612759,SAS,1.0,3.0,0.750000,0.000000,4.0,0.0,9.0,3.0,0.250000,0.777778,0.583333,0.259259
80,21000088,1610612763,MEM,4.0,2.0,0.333333,0.600000,2.0,3.0,2010-11-06,2010-11,7.0,11.0,1610612758,SAC,2.0,3.0,0.600000,0.333333,4.0,2.0,6.0,9.0,0.600000,0.611111,0.600000,0.425926
81,21000087,1610612757,POR,2.0,4.0,0.666667,0.200000,4.0,1.0,2010-11-06,2010-11,10.0,6.0,1610612761,TOR,4.0,1.0,0.200000,0.666667,2.0,4.0,5.0,13.0,0.722222,0.375000,0.374074,0.569444
82,21000083,1610612749,MIL,4.0,2.0,0.333333,1.000000,0.0,5.0,2010-11-06,2010-11,7.0,13.0,1610612740,NOH,0.0,5.0,1.000000,0.333333,4.0,2.0,8.0,8.0,0.500000,0.650000,0.833333,0.438889
83,21000086,1610612746,LAC,5.0,1.0,0.166667,0.400000,3.0,2.0,2010-11-06,2010-11,8.0,10.0,1610612762,UTA,3.0,2.0,0.400000,0.166667,5.0,1.0,9.0,7.0,0.437500,0.555556,0.412500,0.296296
84,21000080,1610612766,CHA,4.0,1.0,0.200000,0.750000,1.0,3.0,2010-11-06,2010-11,10.0,5.0,1610612753,ORL,1.0,3.0,0.750000,0.200000,4.0,1.0,10.0,5.0,0.333333,0.333333,0.611111,0.244444
85,21000082,1610612748,MIA,2.0,4.0,0.666667,0.400000,3.0,2.0,2010-11-06,2010-11,5.0,10.0,1610612751,NJN,3.0,2.0,0.400000,0.666667,2.0,4.0,7.0,9.0,0.562500,0.666667,0.454167,0.666667
86,21000081,1610612739,CLE,3.0,2.0,0.400000,0.250000,3.0,1.0,2010-11-06,2010-11,9.0,7.0,1610612764,WAS,3.0,1.0,0.250000,0.400000,3.0,2.0,8.0,6.0,0.428571,0.437500,0.309524,0.412500
87,21000093,1610612738,BOS,1.0,5.0,0.833333,0.600000,2.0,3.0,2010-11-07,2010-11,10.0,7.0,1610612760,OKC,2.0,3.0,0.600000,0.833333,1.0,5.0,9.0,9.0,0.500000,0.411765,0.566667,0.692810
88,21000094,1610612747,LAL,0.0,6.0,1.000000,0.714286,2.0,5.0,2010-11-07,2010-11,8.0,14.0,1610612757,POR,2.0,5.0,0.714286,1.000000,0.0,6.0,10.0,12.0,0.545455,0.636364,0.658009,0.878788
89,21000091,1610612765,DET,5.0,1.0,0.166667,0.800000,1.0,4.0,2010-11-07,2010-11,6.0,12.0,1610612744,GSW,1.0,4.0,0.800000,0.166667,5.0,1.0,11.0,7.0,0.388889,0.666667,0.662963,0.333333
90,21000092,1610612745,HOU,5.0,0.0,0.000000,0.166667,5.0,1.0,2010-11-07,2010-11,7.0,8.0,1610612750,MIN,5.0,1.0,0.166667,0.000000,5.0,0.0,9.0,10.0,0.526316,0.533333,0.286550,0.177778
91,21000089,1610612752,NYK,2.0,3.0,0.600000,0.166667,5.0,1.0,2010-11-07,2010-11,9.0,7.0,1610612755,PHI,5.0,1.0,0.166667,0.600000,2.0,3.0,10.0,8.0,0.444444,0.437500,0.259259,0.545833
92,21000090,1610612737,ATL,0.0,6.0,1.000000,0.400000,3.0,2.0,2010-11-07,2010-11,15.0,4.0,1610612756,PHX,3.0,2.0,0.400000,1.000000,0.0,6.0,5.0,11.0,0.687500,0.210526,0.495833,0.736842
93,21000097,1610612744,GSW,2.0,4.0,0.666667,0.166667,5.0,1.0,2010-11-08,2010-11,16.0,8.0,1610612761,TOR,5.0,1.0,0.166667,0.666667,2.0,4.0,7.0,17.0,0.708333,0.333333,0.347222,0.555556
94,21000095,1610612766,CHA,5.0,1.0,0.166667,0.800000,1.0,4.0,2010-11-08,2010-11,11.0,9.0,1610612759,SAS,1.0,4.0,0.800000,0.166667,5.0,1.0,14.0,4.0,0.222222,0.450000,0.607407,0.261111
95,21000096,1610612737,ATL,1.0,6.0,0.857143,0.800000,1.0,4.0,2010-11-08,2010-11,16.0,8.0,1610612753,ORL,1.0,4.0,0.800000,0.857143,1.0,6.0,11.0,11.0,0.500000,0.333333,0.700000,0.682540
96,21000099,1610612763,MEM,4.0,3.0,0.428571,0.500000,3.0,3.0,2010-11-08,2010-11,10.0,14.0,1610612756,PHX,3.0,3.0,0.500000,0.428571,4.0,3.0,9.0,14.0,0.608696,0.583333,0.536232,0.480159
97,21000100,1610612738,BOS,1.0,6.0,0.857143,0.600000,2.0,3.0,2010-11-08,2010-11,12.0,10.0,1610612742,DAL,2.0,3.0,0.600000,0.857143,1.0,6.0,7.0,11.0,0.611111,0.454545,0.603704,0.722944
98,21000098,1610612741,CHI,3.0,2.0,0.400000,0.666667,2.0,4.0,2010-11-08,2010-11,7.0,12.0,1610612743,DEN,2.0,4.0,0.666667,0.400000,3.0,2.0,11.0,9.0,0.450000,0.631579,0.594444,0.477193
99,21000105,1610612746,LAC,6.0,1.0,0.142857,1.000000,0.0,6.0,2010-11-09,2010-11,8.0,16.0,1610612740,NOH,0.0,6.0,1.000000,0.142857,6.0,1.0,14.0,9.0,0.391304,0.666667,0.797101,0.317460

<font color='red'> SOS calculted correctly here??????</font>

In [39]:
#http://www.nationalchamps.net/NCAA/BCS/strength_of_schedule_explain.htm#opps

In [40]:
df_lw_opplw_opplwcsum_ab.fillna(0, inplace=True)
p(df_lw_opplw_opplwcsum_ab)

(10266, 27)

,game_id,team_id_a,TEAM_ABBREVIATION_a,losses_a,wins_a,win_pct_a,opp_win_pct_a,opp_losses_a,opp_wins_a,game_date,season,opp_opps_losses_b,opp_opps_wins_b,team_id_b,TEAM_ABBREVIATION_b,losses_b,wins_b,win_pct_b,opp_win_pct_b,opp_losses_b,opp_wins_b,opp_opps_losses_a,opp_opps_wins_a,opp_opps_win_pct_a,opp_opps_win_pct_b,strength_of_schedule_a,strength_of_schedule_b
0,21000001,1610612738,BOS,0.0,0.0,0.000000,0.000000,0.0,0.0,2010-10-26,2010-11,0.0,0.0,1610612748,MIA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
1,21000002,1610612756,PHX,0.0,0.0,0.000000,0.000000,0.0,0.0,2010-10-26,2010-11,0.0,0.0,1610612757,POR,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
2,21000003,1610612745,HOU,0.0,0.0,0.000000,0.000000,0.0,0.0,2010-10-26,2010-11,0.0,0.0,1610612747,LAL,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
3,21000013,1610612754,IND,0.0,0.0,0.000000,0.000000,0.0,0.0,2010-10-27,2010-11,0.0,0.0,1610612759,SAS,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
4,21000014,1610612743,DEN,0.0,0.0,0.000000,0.000000,0.0,0.0,2010-10-27,2010-11,0.0,0.0,1610612762,UTA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
10261,41700317,1610612744,GSW,29.0,69.0,0.704082,0.775510,22.0,76.0,2018-05-28,2017-18,2217.0,2595.0,1610612745,HOU,22.0,76.0,0.775510,0.704082,29.0,69.0,2243.0,2676.0,0.544013,0.539277,0.698344,0.649147
10262,41700401,1610612739,CLE,38.0,62.0,0.620000,0.707071,29.0,70.0,2018-05-31,2017-18,2304.0,2755.0,1610612744,GSW,29.0,70.0,0.707071,0.620000,38.0,62.0,2255.0,2657.0,0.540920,0.544574,0.651687,0.594858
10263,41700402,1610612739,CLE,39.0,62.0,0.613861,0.710000,29.0,71.0,2018-06-03,2017-18,2333.0,2826.0,1610612744,GSW,29.0,71.0,0.710000,0.613861,39.0,62.0,2294.0,2719.0,0.542390,0.547781,0.654130,0.591834
10264,41700403,1610612739,CLE,40.0,62.0,0.607843,0.712871,29.0,72.0,2018-06-06,2017-18,2362.0,2898.0,1610612744,GSW,29.0,72.0,0.712871,0.607843,40.0,62.0,2334.0,2781.0,0.543695,0.550951,0.656479,0.588879
10265,41700404,1610612739,CLE,41.0,62.0,0.601942,0.715686,29.0,73.0,2018-06-08,2017-18,2391.0,2971.0,1610612744,GSW,29.0,73.0,0.715686,0.601942,41.0,62.0,2375.0,2843.0,0.544845,0.554084,0.658739,0.585989

In [41]:
column_names_list = list(df_lw_opplw_opplwcsum_ab.columns)
pl(column_names_list)

27

['game_id',
 'team_id_a',
 'TEAM_ABBREVIATION_a',
 'losses_a',
 'wins_a',
 'win_pct_a',
 'opp_win_pct_a',
 'opp_losses_a',
 'opp_wins_a',
 'game_date',
 'season',
 'opp_opps_losses_b',
 'opp_opps_wins_b',
 'team_id_b',
 'TEAM_ABBREVIATION_b',
 'losses_b',
 'wins_b',
 'win_pct_b',
 'opp_win_pct_b',
 'opp_losses_b',
 'opp_wins_b',
 'opp_opps_losses_a',
 'opp_opps_wins_a',
 'opp_opps_win_pct_a',
 'opp_opps_win_pct_b',
 'strength_of_schedule_a',
 'strength_of_schedule_b']

In [42]:
column_names_not_diff_list = [k for k in column_names_list if not k in [
 'losses_a',
 'wins_a',
 'win_pct_a',
 'opp_win_pct_a',
 'opp_losses_a',
 'opp_wins_a',
 'opp_opps_losses_b',
 'opp_opps_wins_b',
 'losses_b',
 'wins_b',
 'win_pct_b',
 'opp_win_pct_b',
 'opp_losses_b',
 'opp_wins_b',
 'opp_opps_losses_a',
 'opp_opps_wins_a',
 'opp_opps_win_pct_a',
 'opp_opps_win_pct_b',
 'strength_of_schedule_a',
 'strength_of_schedule_b']]
pl(column_names_not_diff_list)

7

['game_id',
 'team_id_a',
 'TEAM_ABBREVIATION_a',
 'game_date',
 'season',
 'team_id_b',
 'TEAM_ABBREVIATION_b']

In [43]:
df_diff = f.get_numeric_diff(df_lw_opplw_opplwcsum_ab,
                   [],
                   column_names_not_diff_list,
                   ['_a','_b'])
p(df_diff)

(10266, 17)

,game_id,team_id_a,TEAM_ABBREVIATION_a,game_date,season,team_id_b,TEAM_ABBREVIATION_b,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff
0,21000001,1610612738,BOS,2010-10-26,2010-11,1610612748,MIA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
1,21000002,1610612756,PHX,2010-10-26,2010-11,1610612757,POR,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
2,21000003,1610612745,HOU,2010-10-26,2010-11,1610612747,LAL,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
3,21000013,1610612754,IND,2010-10-27,2010-11,1610612759,SAS,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
4,21000014,1610612743,DEN,2010-10-27,2010-11,1610612762,UTA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
10261,41700317,1610612744,GSW,2018-05-28,2017-18,1610612745,HOU,7.0,-7.0,-0.071429,0.071429,-7.0,7.0,26.0,81.0,0.004736,0.049198
10262,41700401,1610612739,CLE,2018-05-31,2017-18,1610612744,GSW,9.0,-8.0,-0.087071,0.087071,-9.0,8.0,-49.0,-98.0,-0.003654,0.056829
10263,41700402,1610612739,CLE,2018-06-03,2017-18,1610612744,GSW,10.0,-9.0,-0.096139,0.096139,-10.0,9.0,-39.0,-107.0,-0.005391,0.062295
10264,41700403,1610612739,CLE,2018-06-06,2017-18,1610612744,GSW,11.0,-10.0,-0.105028,0.105028,-11.0,10.0,-28.0,-117.0,-0.007256,0.067600
10265,41700404,1610612739,CLE,2018-06-08,2017-18,1610612744,GSW,12.0,-11.0,-0.113745,0.113745,-12.0,11.0,-16.0,-128.0,-0.009240,0.072750

In [44]:
help(f.get_numeric_diff)

Help on function get_numeric_diff in module my_functions:

get_numeric_diff(df_, groupby_list_, not_difference_list_, suffix_list_)

In [45]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '54strength_of_schedule_diff_opp_win_pct_diff_win_pct_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_diff.to_csv(datapath_df, index=False)

In [46]:
df_diff_readback = rcp('54strength_of_schedule_diff_opp_win_pct_diff_win_pct_diff_2010_2018.csv')
p(df_diff_readback)

(10266, 17)

,game_id,team_id_a,TEAM_ABBREVIATION_a,game_date,season,team_id_b,TEAM_ABBREVIATION_b,losses_diff,wins_diff,win_pct_diff,opp_win_pct_diff,opp_losses_diff,opp_wins_diff,opp_opps_losses_diff,opp_opps_wins_diff,opp_opps_win_pct_diff,strength_of_schedule_diff
0,21000001,1610612738,BOS,2010-10-26,2010-11,1610612748,MIA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
1,21000002,1610612756,PHX,2010-10-26,2010-11,1610612757,POR,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
2,21000003,1610612745,HOU,2010-10-26,2010-11,1610612747,LAL,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
3,21000013,1610612754,IND,2010-10-27,2010-11,1610612759,SAS,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
4,21000014,1610612743,DEN,2010-10-27,2010-11,1610612762,UTA,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000
10261,41700317,1610612744,GSW,2018-05-28,2017-18,1610612745,HOU,7.0,-7.0,-0.071429,0.071429,-7.0,7.0,26.0,81.0,0.004736,0.049198
10262,41700401,1610612739,CLE,2018-05-31,2017-18,1610612744,GSW,9.0,-8.0,-0.087071,0.087071,-9.0,8.0,-49.0,-98.0,-0.003654,0.056829
10263,41700402,1610612739,CLE,2018-06-03,2017-18,1610612744,GSW,10.0,-9.0,-0.096139,0.096139,-10.0,9.0,-39.0,-107.0,-0.005391,0.062295
10264,41700403,1610612739,CLE,2018-06-06,2017-18,1610612744,GSW,11.0,-10.0,-0.105028,0.105028,-11.0,10.0,-28.0,-117.0,-0.007256,0.067600
10265,41700404,1610612739,CLE,2018-06-08,2017-18,1610612744,GSW,12.0,-11.0,-0.113745,0.113745,-12.0,11.0,-16.0,-128.0,-0.009240,0.072750