In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale


pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

pd.set_option('display.max_colwidth', None)
pd.options.display.max_info_columns = 999

#return the first 5 and last 5 rows of this dataframe
def p(df_):
    if df_.shape[0] > 6:
        print(df_.shape)
        return pd.concat([df_.head(), df_.tail()])
    else:
        return df_

def rcp(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'processed_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'processed_data', file_), parse_dates=pd_)
    
def rcr(file_, pd_=None):
    if pd_ == None:
        return pd.read_csv(os.path.join('..', 'raw_data', file_))
    else:
        return pd.read_csv(os.path.join('..', 'raw_data', file_), parse_dates=pd_)
    
#sort dataframe by column
def s(df_, column_):
    return df_.sort_values(column_)

#reset index and sort dataframe by column
def sr(df_, column_):
    df_ = df_.sort_values(column_)
    return df_.reset_index(drop=True)

#print length of list
def pl(list_):
    print(len(list_))
    return list_

#print length of list
def pdc(dict_):
    print(len(dict_))
    return dict_

#import my functions
import my_functions as f

In [2]:
df_stats_cma5_12_999_diff = rcp('55Astat_cma5_cma12_cma999_diff_2010_2018.csv')
p(df_stats_cma5_12_999_diff)

(10266, 163)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,-101.60,-106.80,-105.30,-107.70,3.80,0.90,-0.6580,-1.190,-16.70,-0.3960,-0.6950,-0.5540,-19.3870,-20.40,-0.4620,-5.320000e-01,-1.0,-0.1960,-1.073200e+02,-103.5,-86.250,-103.0,-0.5070,-240.0,0.0000,-240.0,-38.0,-91.0,-0.4180,-8.0,-20.0,-0.4000,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.60,-3.98,3.72,4.32,-8.32,-8.34,-0.1340,-0.676,-4.22,-0.0048,0.0666,0.0312,-0.3668,-0.24,-0.0276,-2.460000e-02,0.0,-0.0010,-4.640000e-01,-0.9,-0.752,-0.6,-0.0694,0.0,-0.2000,0.0,-1.6,-2.2,-0.0070,-3.8,-2.8,-0.0758,2.6,5.4,-0.062235,0.0,1.4,1.4,-6.6,-3.8,0.8,-0.4,-0.4,-4.4,7.4,-0.2,-0.275000,1.616667,5.450000,6.266667,-5.733333,-4.658333,-0.096833,0.158333,-2.625000,0.040083,0.023250,0.028917,-0.634250,-0.491667,-0.002417,-0.005167,0.0,-0.001417,-6.150833,-7.107500,-5.923333,-5.666667,-0.037083,2.083333,-0.170917,2.083333,-2.000000,-4.500000,0.002500,-1.416667,-3.083333,-0.005333,0.666667,2.916667,-0.076499,-0.083333,-1.833333,-1.916667,-5.250000,-3.833333,-0.166667,-1.583333,0.250000,-4.750000,3.500000,-0.083333,-1.901545,-0.857465,5.452475,4.759653,-7.349000,-5.623109,-0.107564,-0.197637,-3.449980,0.004219,0.014580,-0.003960,-1.280636,-1.171089,-0.020696,-0.018612,0.0,-0.000144,-2.523637,-2.570218,-2.142013,-2.408911,-0.055020,0.240099,-0.148643,0.240099,-2.717525,-1.399802,-0.024299,0.413564,2.571386,-0.015929,1.359802,2.857426,-0.044027,-0.075248,-1.933762,-2.009010,-6.185050,-1.188614,-3.159208,-1.510693,-0.718020,-3.661683,5.618812,-0.014950
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-10.66,-11.32,7.40,8.66,-18.06,-20.02,-0.1112,-0.670,-4.94,0.0206,0.0810,0.0330,-0.8788,-0.94,-0.0908,-7.860000e-02,0.0,-0.0014,-1.856000e+00,-2.0,-1.668,-1.2,-0.1148,0.0,-0.4000,0.0,-4.8,1.0,-0.0620,-4.8,-3.8,-0.0956,2.4,3.4,0.008688,3.2,-1.2,2.0,-7.4,-2.6,-1.0,-1.2,-2.2,-12.0,17.4,-0.4,-1.958333,-0.608333,6.666667,7.500000,-8.633333,-8.116667,-0.070000,-0.006667,-2.416667,0.037417,0.040667,0.034000,-0.010750,0.100000,-0.014083,-0.011917,0.0,-0.001583,-4.626667,-5.416667,-4.514167,-4.583333,-0.044417,0.000000,-0.254250,0.000000,-2.750000,-4.750000,-0.005917,-2.000000,-3.416667,-0.018583,1.833333,3.833333,-0.055607,0.166667,-1.666667,-1.500000,-4.583333,-2.916667,-0.250000,-0.833333,-1.000000,-5.666667,6.333333,-0.083333,-2.080421,-1.082120,5.594787,4.944341,-7.670239,-6.032392,-0.105718,-0.196316,-3.446612,0.005084,0.015359,-0.003606,-1.278266,-1.174102,-0.022503,-0.020015,0.0,-0.000172,-2.498403,-2.544582,-2.120647,-2.355271,-0.055756,0.237818,-0.157015,0.237818,-2.789361,-1.307319,-0.025657,0.350320,2.457290,-0.016600,1.415453,2.878373,-0.042104,0.013881,-1.993108,-1.979227,-6.153757,-1.117647,-3.167540,-1.515240,-0.809552,-3.812949,5.937488,-0.024655
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-11.30,-11.32,10.84,11.02,-22.12,-22.40,-0.1368,-0.900,-6.12,0.0752,0.1324,0.0746,0.1990,0.22,-0.1020,-8.540000e-02,0.0,-0.0024,-1.884000e+00,-1.8,-1.500,-0.6,-0.1234,0.0,-0.6000,0.0,-5.0,2.8,-0.0738,-4.6,-4.4,-0.0828,3.2,3.8,0.030279,5.2,-0.8,4.4,-8.6,-1.8,-2.4,-0.4,-2.2,-11.4,18.8,-0.2,-6.716667,-4.966667,7.100000,7.758333,-13.825000,-12.750000,-0.071167,-0.633333,-3.308333,0.055417,0.045000,0.038583,0.879500,1.058333,-0.040917,-0.036833,0.0,-0.001750,-3.470000,-4.416667,-3.680833,-3.583333,-0.070917,0.000000,-0.365333,0.000000,-4.166667,-3.166667,-0.030833,-2.166667,-2.583333,-0.034333,1.833333,3.916667,-0.060729,1.333333,-1.166667,0.166667,-5.416667,-2.416667,-0.250000,0.166667,-0.916667,-8.666667,10.750000,0.000000,-2.186865,-1.165239,5.666686,4.989406,-7.848629,-6.162469,-0.106077,-0.204353,-3.473396,0.006923,0.017103,-0.002244,-1.240705,-1.133267,-0.023159,-0.020812,0.0,-0.000190,-2.473677,-2.519357,-2.099625,-2.322102,-0.056556,0.235580,-0.165224,0.235580,-2.781649,-1.187417,-0.026225,0.347135,2.482296,-0.016979,1.362840,2.831144,-0.042965,0.101371,-1.963640,-1.862269,-6.161812,-1.106606,-3.146297,-1.470969,-0.821150,-3.853322,6.035313,-0.014658

In [3]:
column_names_list = list(df_stats_cma5_12_999_diff.columns)
pl(column_names_list)

163

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'team_id_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'team_id_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b',
 'E_OFF_RATING_cma5_diff',
 'OFF_RATING_cma5_diff',
 'E_DEF_RATING_cma5_diff',
 'DEF_RATING_cma5_diff',
 'E_NET_RATING_cma5_diff',
 'NET_RATING_cma5_diff',
 'AST_PCT_cma5_diff',
 'AST_TOV_cma5_diff',
 'AST_RATIO_cma5_diff',
 'OREB_PCT_cma5_diff',
 'DREB_PCT_cma5_diff',
 'REB_PCT_cma5_diff',
 'E_TM_TOV_PCT_cma5_diff',
 'TM_TOV_PCT_cma5_diff',
 'EFG_PCT_cma5_diff',
 'TS_PCT_cma5_diff',
 'USG_PCT_cma5_diff',
 'E_USG_PCT_cma5_diff',
 'E_PACE_cma5_diff',
 'PACE_cma5_diff',
 'PACE_PER40_cma5_diff',
 'POSS_cma5_diff',
 'PIE_cma5_diff',
 'duration_minutes_cma5_diff',
 'w_pct_cma5_diff',
 'min_cma5_diff',
 'fgm_cma5_diff',
 'fga_cma5_diff',
 'fg_pct_cma5_diff',
 'fg3m_cma5_diff',
 'fg3a_cma5_diff',
 'fg3_pct_cma5_diff',
 'ftm_cma5_diff',
 'fta_cma5_diff',
 'ft_pct_cma5_diff',
 'oreb_cma5_diff',
 'dreb_cma5_diff',
 'reb_cma5_diff',
 'ast_cma5_diff',
 'stl_cma5_diff',
 'blk_cma5_diff',
 'tov_cma5_diff',
 'pf_cma5_diff',
 'pts_cma5_diff',
 'spread_cma5_diff',
 'away_home__cma5_diff',
 'E_OFF_RATING_cma12_diff',
 'OFF_RATING_cma12_diff',
 'E_DEF_RATING_cma12_diff',
 'DEF_RATING_cma12_diff',
 'E_NET_RATING_cma12_diff',
 'NET_RATING_cma12_diff',
 'AST_PCT_cma12_diff',
 'AST_TOV_cma12_diff',
 'AST_RATIO_cma12_diff',
 'OREB_PCT_cma12_diff',
 'DREB_PCT_cma12_diff',
 'REB_PCT_cma12_diff',
 'E_TM_TOV_PCT_cma12_diff',
 'TM_TOV_PCT_cma12_diff',
 'EFG_PCT_cma12_diff',
 'TS_PCT_cma12_diff',
 'USG_PCT_cma12_diff',
 'E_USG_PCT_cma12_diff',
 'E_PACE_cma12_diff',
 'PACE_cma12_diff',
 'PACE_PER40_cma12_diff',
 'POSS_cma12_diff',
 'PIE_cma12_diff',
 'duration_minutes_cma12_diff',
 'w_pct_cma12_diff',
 'min_cma12_diff',
 'fgm_cma12_diff',
 'fga_cma12_diff',
 'fg_pct_cma12_diff',
 'fg3m_cma12_diff',
 'fg3a_cma12_diff',
 'fg3_pct_cma12_diff',
 'ftm_cma12_diff',
 'fta_cma12_diff',
 'ft_pct_cma12_diff',
 'oreb_cma12_diff',
 'dreb_cma12_diff',
 'reb_cma12_diff',
 'ast_cma12_diff',
 'stl_cma12_diff',
 'blk_cma12_diff',
 'tov_cma12_diff',
 'pf_cma12_diff',
 'pts_cma12_diff',
 'spread_cma12_diff',
 'away_home__cma12_diff',
 'E_OFF_RATING_cma999_diff',
 'OFF_RATING_cma999_diff',
 'E_DEF_RATING_cma999_diff',
 'DEF_RATING_cma999_diff',
 'E_NET_RATING_cma999_diff',
 'NET_RATING_cma999_diff',
 'AST_PCT_cma999_diff',
 'AST_TOV_cma999_diff',
 'AST_RATIO_cma999_diff',
 'OREB_PCT_cma999_diff',
 'DREB_PCT_cma999_diff',
 'REB_PCT_cma999_diff',
 'E_TM_TOV_PCT_cma999_diff',
 'TM_TOV_PCT_cma999_diff',
 'EFG_PCT_cma999_diff',
 'TS_PCT_cma999_diff',
 'USG_PCT_cma999_diff',
 'E_USG_PCT_cma999_diff',
 'E_PACE_cma999_diff',
 'PACE_cma999_diff',
 'PACE_PER40_cma999_diff',
 'POSS_cma999_diff',
 'PIE_cma999_diff',
 'duration_minutes_cma999_diff',
 'w_pct_cma999_diff',
 'min_cma999_diff',
 'fgm_cma999_diff',
 'fga_cma999_diff',
 'fg_pct_cma999_diff',
 'fg3m_cma999_diff',
 'fg3a_cma999_diff',
 'fg3_pct_cma999_diff',
 'ftm_cma999_diff',
 'fta_cma999_diff',
 'ft_pct_cma999_diff',
 'oreb_cma999_diff',
 'dreb_cma999_diff',
 'reb_cma999_diff',
 'ast_cma999_diff',
 'stl_cma999_diff',
 'blk_cma999_diff',
 'tov_cma999_diff',
 'pf_cma999_diff',
 'pts_cma999_diff',
 'spread_cma999_diff',
 'away_home__cma999_diff']

In [4]:
column_names_list_diff = [k for k in column_names_list if k.endswith('_diff')]
pl(column_names_list_diff)

138

['E_OFF_RATING_cma5_diff',
 'OFF_RATING_cma5_diff',
 'E_DEF_RATING_cma5_diff',
 'DEF_RATING_cma5_diff',
 'E_NET_RATING_cma5_diff',
 'NET_RATING_cma5_diff',
 'AST_PCT_cma5_diff',
 'AST_TOV_cma5_diff',
 'AST_RATIO_cma5_diff',
 'OREB_PCT_cma5_diff',
 'DREB_PCT_cma5_diff',
 'REB_PCT_cma5_diff',
 'E_TM_TOV_PCT_cma5_diff',
 'TM_TOV_PCT_cma5_diff',
 'EFG_PCT_cma5_diff',
 'TS_PCT_cma5_diff',
 'USG_PCT_cma5_diff',
 'E_USG_PCT_cma5_diff',
 'E_PACE_cma5_diff',
 'PACE_cma5_diff',
 'PACE_PER40_cma5_diff',
 'POSS_cma5_diff',
 'PIE_cma5_diff',
 'duration_minutes_cma5_diff',
 'w_pct_cma5_diff',
 'min_cma5_diff',
 'fgm_cma5_diff',
 'fga_cma5_diff',
 'fg_pct_cma5_diff',
 'fg3m_cma5_diff',
 'fg3a_cma5_diff',
 'fg3_pct_cma5_diff',
 'ftm_cma5_diff',
 'fta_cma5_diff',
 'ft_pct_cma5_diff',
 'oreb_cma5_diff',
 'dreb_cma5_diff',
 'reb_cma5_diff',
 'ast_cma5_diff',
 'stl_cma5_diff',
 'blk_cma5_diff',
 'tov_cma5_diff',
 'pf_cma5_diff',
 'pts_cma5_diff',
 'spread_cma5_diff',
 'away_home__cma5_diff',
 'E_OFF_RATING_cma12_diff',
 'OFF_RATING_cma12_diff',
 'E_DEF_RATING_cma12_diff',
 'DEF_RATING_cma12_diff',
 'E_NET_RATING_cma12_diff',
 'NET_RATING_cma12_diff',
 'AST_PCT_cma12_diff',
 'AST_TOV_cma12_diff',
 'AST_RATIO_cma12_diff',
 'OREB_PCT_cma12_diff',
 'DREB_PCT_cma12_diff',
 'REB_PCT_cma12_diff',
 'E_TM_TOV_PCT_cma12_diff',
 'TM_TOV_PCT_cma12_diff',
 'EFG_PCT_cma12_diff',
 'TS_PCT_cma12_diff',
 'USG_PCT_cma12_diff',
 'E_USG_PCT_cma12_diff',
 'E_PACE_cma12_diff',
 'PACE_cma12_diff',
 'PACE_PER40_cma12_diff',
 'POSS_cma12_diff',
 'PIE_cma12_diff',
 'duration_minutes_cma12_diff',
 'w_pct_cma12_diff',
 'min_cma12_diff',
 'fgm_cma12_diff',
 'fga_cma12_diff',
 'fg_pct_cma12_diff',
 'fg3m_cma12_diff',
 'fg3a_cma12_diff',
 'fg3_pct_cma12_diff',
 'ftm_cma12_diff',
 'fta_cma12_diff',
 'ft_pct_cma12_diff',
 'oreb_cma12_diff',
 'dreb_cma12_diff',
 'reb_cma12_diff',
 'ast_cma12_diff',
 'stl_cma12_diff',
 'blk_cma12_diff',
 'tov_cma12_diff',
 'pf_cma12_diff',
 'pts_cma12_diff',
 'spread_cma12_diff',
 'away_home__cma12_diff',
 'E_OFF_RATING_cma999_diff',
 'OFF_RATING_cma999_diff',
 'E_DEF_RATING_cma999_diff',
 'DEF_RATING_cma999_diff',
 'E_NET_RATING_cma999_diff',
 'NET_RATING_cma999_diff',
 'AST_PCT_cma999_diff',
 'AST_TOV_cma999_diff',
 'AST_RATIO_cma999_diff',
 'OREB_PCT_cma999_diff',
 'DREB_PCT_cma999_diff',
 'REB_PCT_cma999_diff',
 'E_TM_TOV_PCT_cma999_diff',
 'TM_TOV_PCT_cma999_diff',
 'EFG_PCT_cma999_diff',
 'TS_PCT_cma999_diff',
 'USG_PCT_cma999_diff',
 'E_USG_PCT_cma999_diff',
 'E_PACE_cma999_diff',
 'PACE_cma999_diff',
 'PACE_PER40_cma999_diff',
 'POSS_cma999_diff',
 'PIE_cma999_diff',
 'duration_minutes_cma999_diff',
 'w_pct_cma999_diff',
 'min_cma999_diff',
 'fgm_cma999_diff',
 'fga_cma999_diff',
 'fg_pct_cma999_diff',
 'fg3m_cma999_diff',
 'fg3a_cma999_diff',
 'fg3_pct_cma999_diff',
 'ftm_cma999_diff',
 'fta_cma999_diff',
 'ft_pct_cma999_diff',
 'oreb_cma999_diff',
 'dreb_cma999_diff',
 'reb_cma999_diff',
 'ast_cma999_diff',
 'stl_cma999_diff',
 'blk_cma999_diff',
 'tov_cma999_diff',
 'pf_cma999_diff',
 'pts_cma999_diff',
 'spread_cma999_diff',
 'away_home__cma999_diff']

In [5]:
column_names_list_not_diff = [k for k in column_names_list if not k in column_names_list_diff]
pl(column_names_list_not_diff)

25

['game_id',
 'game_date',
 'season',
 'season_type',
 'season_year',
 'TEAM_NAME_a',
 'TEAM_ABBREVIATION_a',
 'TEAM_CITY_a',
 'MIN_a',
 'duration_a',
 'team_id_a',
 'wl_a',
 'matchup_a',
 'a_a',
 'b_a',
 'TEAM_NAME_b',
 'TEAM_ABBREVIATION_b',
 'TEAM_CITY_b',
 'MIN_b',
 'duration_b',
 'team_id_b',
 'wl_b',
 'matchup_b',
 'a_b',
 'b_b']

In [6]:
df_stats_cmax5_12_999_diff = rcp('55Bstat_cmax5_cmax12_cmax999_diff_2010_2018.csv')
p(df_stats_cmax5_12_999_diff)

(10266, 163)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.000,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,7.7,5.3,-7.7,-5.3,24.1,24.6,0.011,0.86,2.7,0.034,-0.002,-0.005,-2.597,-3.8,-0.010,-0.005,0.0,0.002,0.00,0.0,0.00,-4.0,0.121,0.0,0.067,0.0,3.0,4.0,0.011,0.0,-5.0,0.036,-7.0,-9.0,0.092593,6.0,1.0,2.0,3.0,1.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,-0.7,-4.0,-7.7,-5.3,20.5,21.7,0.193,-3.11,1.0,0.034,-0.029,0.013,-2.597,-3.8,-0.008,0.018,0.0,0.003,7.48,5.0,4.17,4.0,0.076,0.0,0.0,0.0,3.0,4.0,0.014,-2.0,-4.0,-0.110,-3.0,0.0,0.003268,5.0,4.0,8.0,7.0,0.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,6.6,5.4,-0.3,3.0,18.1,13.9,0.089,-1.80,6.9,0.014,-0.029,0.012,3.969,5.0,-0.024,-0.022,0.0,0.000,2.26,2.0,1.67,-3.0,0.124,-25.0,0.0,-25.0,6.0,1.0,0.032,-2.0,-16.0,-0.022,-8.0,-12.0,0.058824,7.0,4.0,7.0,15.0,0.0,3.0,3.0,-5.0,-5.0,-1.0,0.0
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.4,-7.8,5.8,6.9,-11.7,-12.5,-0.019,-0.97,-1.4,0.047,0.001,0.033,-0.416,0.2,0.007,0.019,0.0,0.000,4.66,1.0,0.83,2.0,-0.019,0.0,-0.096,0.0,-7.0,-5.0,-0.016,1.0,-4.0,0.079,5.0,7.0,-0.111111,-1.0,1.0,-2.0,-3.0,-2.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-2.5,-2.4,-11.1,-5.6,-0.215,5.64,-1.4,0.047,-0.052,0.015,-0.416,0.2,0.061,0.036,0.0,-0.001,-10.94,-10.5,-8.75,-9.0,-0.019,25.0,0.0,25.0,2.0,3.0,0.070,1.0,-5.0,0.079,7.0,8.0,-0.094444,-1.0,-5.0,-10.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0
10263,41700402,2018-06-03,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.3,-5.5,8.5,12.4,-24.7,-18.8,-0.126,-2.38,-7.6,0.047,0.014,0.033,-0.416,0.2,-0.032,-0.036,0.0,-0.001,5.06,4.0,3.33,2.0,-0.129,0.0,-0.429,0.0,-2.0,9.0,-0.005,-6.0,-2.0,-0.030,1.0,6.0,-0.131818,3.0,2.0,4.0,-13.0,-3.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-1.7,2.0,-11.1,-5.6,-0.215,4.45,-1.4,0.047,-0.052,0.033,-0.416,0.2,0.061,0.036,0.0,-0.002,-10.94,-10.5,-8.75,-8.0,-0.019,0.0,0.0,0.0,2.0,3.0,0.070,1.0,-3.0,0.079,3.0,3.0,-0.100000,3.0,-3.0,1.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0
10264,41700403,2018-06-06,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.2,-10.0,14.7,16.9,-24.7,-18.8,0.002,-1.61,-4.3,0.088,0.014,0.050,-2.830,-2.8,-0.142,-0.104,0.0,-0.001,-0.08,0.0,0.00,2.0,-0.129,0.0,-0.429,0.0,-3.0,9.0,-0.102,-6.0,-2.0,-0.030,0.0,3.0,-0.131818,6.0,2.0,6.0,-6.0,-2.0,-1.0,-1.0,-4.0,-10.0,15.0,0.0,8.9,10.9,4.5,6.5,-11.1,-5.6,-0.053,4.45,-1.2,0.047,-0.052,0.033,-0.416,0.2,0.002,0.021,0.0,-0.002,-8.08,-8.5,-7.08,-6.0,-0.019,0.0,0.0,0.0,2.0,0.0,0.022,1.0,-2.0,0.079,3.0,4.0,-0.100000,3.0,-2.0,1.0,-6.0,-2.0,-1.0,2.0,-2.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0
10265,41700404,2018-06-08,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,240:00,0 days 04:00:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,CLE vs. GSW,CLE,GSW,-9.2,-10.0,14.7,16.9,-24.7,-18.8,0.002,-1.61,-4.3,0.088,0.067,0.050,-3.673,-3.8,-0.142,-0.104,0.0,-0.003,0.00,0.0,0.00,2.0,-0.129,0.0,-0.429,0.0,-3.0,9.0,-0.102,-6.0,-2.0,-0.030,1.0,5.0,-0.131818,6.0,5.0,6.0,-6.0,-2.0,-1.0,-3.0,-4.0,-10.0,27.0,0.0,0.9,6.4,4.5,6.5,-11.1,-5.6,-0.053,-1.24,-1.2,0.047,-0.072,0.033,-0.416,0.2,0.002,0.021,0.0,-0.002,-8.08,-8.5,-7.08,-6.0,-0.019,0.0,0.0,0.0,2.0,0.0,0.022,1.0,-2.0,0.079,3.0,5.0,-0.100000,3.0,-2.0,1.0,-6.0,-2.0,-1.0,2.0,-2.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0

In [7]:
df_stats_cma5_12_999_diff_cmax5_12_999_diff = pd.merge(df_stats_cma5_12_999_diff, df_stats_cmax5_12_999_diff, on=column_names_list_not_diff)
p(df_stats_cma5_12_999_diff_cmax5_12_999_diff)

(10266, 301)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,-101.60,-106.80,-105.30,-107.70,3.80,0.90,-0.6580,-1.190,-16.70,-0.3960,-0.6950,-0.5540,-19.3870,-20.40,-0.4620,-5.320000e-01,-1.0,-0.1960,-1.073200e+02,-103.5,-86.250,-103.0,-0.5070,-240.0,0.0000,-240.0,-38.0,-91.0,-0.4180,-8.0,-20.0,-0.4000,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.000,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000,7.7,5.3,-7.7,-5.3,24.1,24.6,0.011,0.86,2.7,0.034,-0.002,-0.005,-2.597,-3.8,-0.010,-0.005,0.0,0.002,0.00,0.0,0.00,-4.0,0.121,0.0,0.067,0.0,3.0,4.0,0.011,0.0,-5.0,0.036,-7.0,-9.0,0.092593,6.0,1.0,2.0,3.0,1.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,-0.7,-4.0,-7.7,-5.3,20.5,21.7,0.193,-3.11,1.0,0.034,-0.029,0.013,-2.597,-3.8,-0.008,0.018,0.0,0.003,7.48,5.0,4.17,4.0,0.076,0.0,0.0,0.0,3.0,4.0,0.014,-2.0,-4.0,-0.110,-3.0,0.0,0.003268,5.0,4.0,8.0,7.0,0.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,6.6,5.4,-0.3,3.0,18.1,13.9,0.089,-1.80,6.9,0.014,-0.029,0.012,3.969,5.0,-0.024,-0.022,0.0,0.000,2.26,2.0,1.67,-3.0,0.124,-25.0,0.0,-25.0,6.0,1.0,0.032,-2.0,-16.0,-0.022,-8.0,-12.0,0.058824,7.0,4.0,7.0,15.0,0.0,3.0,3.0,-5.0,-5.0,-1.0,0.0
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051,-9.4,-7.8,5.8,6.9,-11.7,-12.5,-0.019,-0.97,-1.4,0.047,0.001,0.033,-0.416,0.2,0.007,0.019,0.0,0.000,4.66,1.0,0.83,2.0,-0.019,0.0,-0.096,0.0,-7.0,-5.0,-0.016,1.0,-4.0,0.079,5.0,7.0,-0.111111,-1.0,1.0,-2.0,-3.0,-2.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-2.5,-2.4,-11.1,-5.6,-0.215,5.64,-1.4,0.047,-0.052,0.015,-0.416,0.2,0.061,0.036,0.0,-0.001,-10.94,-10.5,-8.75,-9.0,-0.019,25.0,0.0,25.0,2.0,3.0,0.070,1.0,-5.0,0.079,7.0,8.0,-0.094444,-1.0,-5.0,-10.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0

In [8]:
datapath = os.path.join('..', 'processed_data')

if not os.path.exists(datapath):
    os.mkdir(datapath)

datapath_df = os.path.join(datapath, '58Bstats_cma5_12_999_diff_cmax5_12_999_diff_2010_2018.csv')
if not os.path.exists(datapath_df):
    df_stats_cma5_12_999_diff_cmax5_12_999_diff.to_csv(datapath_df, index=False)

In [9]:
df_readback = rcp('58Bstats_cma5_12_999_diff_cmax5_12_999_diff_2010_2018.csv')
p(df_readback)

(10266, 301)

,game_id,game_date,season,season_type,season_year,TEAM_NAME_a,TEAM_ABBREVIATION_a,TEAM_CITY_a,MIN_a,duration_a,team_id_a,wl_a,matchup_a,a_a,b_a,TEAM_NAME_b,TEAM_ABBREVIATION_b,TEAM_CITY_b,MIN_b,duration_b,team_id_b,wl_b,matchup_b,a_b,b_b,E_OFF_RATING_cma5_diff,OFF_RATING_cma5_diff,E_DEF_RATING_cma5_diff,DEF_RATING_cma5_diff,E_NET_RATING_cma5_diff,NET_RATING_cma5_diff,AST_PCT_cma5_diff,AST_TOV_cma5_diff,AST_RATIO_cma5_diff,OREB_PCT_cma5_diff,DREB_PCT_cma5_diff,REB_PCT_cma5_diff,E_TM_TOV_PCT_cma5_diff,TM_TOV_PCT_cma5_diff,EFG_PCT_cma5_diff,TS_PCT_cma5_diff,USG_PCT_cma5_diff,E_USG_PCT_cma5_diff,E_PACE_cma5_diff,PACE_cma5_diff,PACE_PER40_cma5_diff,POSS_cma5_diff,PIE_cma5_diff,duration_minutes_cma5_diff,w_pct_cma5_diff,min_cma5_diff,fgm_cma5_diff,fga_cma5_diff,fg_pct_cma5_diff,fg3m_cma5_diff,fg3a_cma5_diff,fg3_pct_cma5_diff,ftm_cma5_diff,fta_cma5_diff,ft_pct_cma5_diff,oreb_cma5_diff,dreb_cma5_diff,reb_cma5_diff,ast_cma5_diff,stl_cma5_diff,blk_cma5_diff,tov_cma5_diff,pf_cma5_diff,pts_cma5_diff,spread_cma5_diff,away_home__cma5_diff,E_OFF_RATING_cma12_diff,OFF_RATING_cma12_diff,E_DEF_RATING_cma12_diff,DEF_RATING_cma12_diff,E_NET_RATING_cma12_diff,NET_RATING_cma12_diff,AST_PCT_cma12_diff,AST_TOV_cma12_diff,AST_RATIO_cma12_diff,OREB_PCT_cma12_diff,DREB_PCT_cma12_diff,REB_PCT_cma12_diff,E_TM_TOV_PCT_cma12_diff,TM_TOV_PCT_cma12_diff,EFG_PCT_cma12_diff,TS_PCT_cma12_diff,USG_PCT_cma12_diff,E_USG_PCT_cma12_diff,E_PACE_cma12_diff,PACE_cma12_diff,PACE_PER40_cma12_diff,POSS_cma12_diff,PIE_cma12_diff,duration_minutes_cma12_diff,w_pct_cma12_diff,min_cma12_diff,fgm_cma12_diff,fga_cma12_diff,fg_pct_cma12_diff,fg3m_cma12_diff,fg3a_cma12_diff,fg3_pct_cma12_diff,ftm_cma12_diff,fta_cma12_diff,ft_pct_cma12_diff,oreb_cma12_diff,dreb_cma12_diff,reb_cma12_diff,ast_cma12_diff,stl_cma12_diff,blk_cma12_diff,tov_cma12_diff,pf_cma12_diff,pts_cma12_diff,spread_cma12_diff,away_home__cma12_diff,E_OFF_RATING_cma999_diff,OFF_RATING_cma999_diff,E_DEF_RATING_cma999_diff,DEF_RATING_cma999_diff,E_NET_RATING_cma999_diff,NET_RATING_cma999_diff,AST_PCT_cma999_diff,AST_TOV_cma999_diff,AST_RATIO_cma999_diff,OREB_PCT_cma999_diff,DREB_PCT_cma999_diff,REB_PCT_cma999_diff,E_TM_TOV_PCT_cma999_diff,TM_TOV_PCT_cma999_diff,EFG_PCT_cma999_diff,TS_PCT_cma999_diff,USG_PCT_cma999_diff,E_USG_PCT_cma999_diff,E_PACE_cma999_diff,PACE_cma999_diff,PACE_PER40_cma999_diff,POSS_cma999_diff,PIE_cma999_diff,duration_minutes_cma999_diff,w_pct_cma999_diff,min_cma999_diff,fgm_cma999_diff,fga_cma999_diff,fg_pct_cma999_diff,fg3m_cma999_diff,fg3a_cma999_diff,fg3_pct_cma999_diff,ftm_cma999_diff,fta_cma999_diff,ft_pct_cma999_diff,oreb_cma999_diff,dreb_cma999_diff,reb_cma999_diff,ast_cma999_diff,stl_cma999_diff,blk_cma999_diff,tov_cma999_diff,pf_cma999_diff,pts_cma999_diff,spread_cma999_diff,away_home__cma999_diff,E_OFF_RATING_cmax5_diff,OFF_RATING_cmax5_diff,E_DEF_RATING_cmax5_diff,DEF_RATING_cmax5_diff,E_NET_RATING_cmax5_diff,NET_RATING_cmax5_diff,AST_PCT_cmax5_diff,AST_TOV_cmax5_diff,AST_RATIO_cmax5_diff,OREB_PCT_cmax5_diff,DREB_PCT_cmax5_diff,REB_PCT_cmax5_diff,E_TM_TOV_PCT_cmax5_diff,TM_TOV_PCT_cmax5_diff,EFG_PCT_cmax5_diff,TS_PCT_cmax5_diff,USG_PCT_cmax5_diff,E_USG_PCT_cmax5_diff,E_PACE_cmax5_diff,PACE_cmax5_diff,PACE_PER40_cmax5_diff,POSS_cmax5_diff,PIE_cmax5_diff,duration_minutes_cmax5_diff,w_pct_cmax5_diff,min_cmax5_diff,fgm_cmax5_diff,fga_cmax5_diff,fg_pct_cmax5_diff,fg3m_cmax5_diff,fg3a_cmax5_diff,fg3_pct_cmax5_diff,ftm_cmax5_diff,fta_cmax5_diff,ft_pct_cmax5_diff,oreb_cmax5_diff,dreb_cmax5_diff,reb_cmax5_diff,ast_cmax5_diff,stl_cmax5_diff,blk_cmax5_diff,tov_cmax5_diff,pf_cmax5_diff,pts_cmax5_diff,spread_cmax5_diff,away_home__cmax5_diff,E_OFF_RATING_cmax12_diff,OFF_RATING_cmax12_diff,E_DEF_RATING_cmax12_diff,DEF_RATING_cmax12_diff,E_NET_RATING_cmax12_diff,NET_RATING_cmax12_diff,AST_PCT_cmax12_diff,AST_TOV_cmax12_diff,AST_RATIO_cmax12_diff,OREB_PCT_cmax12_diff,DREB_PCT_cmax12_diff,REB_PCT_cmax12_diff,E_TM_TOV_PCT_cmax12_diff,TM_TOV_PCT_cmax12_diff,EFG_PCT_cmax12_diff,TS_PCT_cmax12_diff,USG_PCT_cmax12_diff,E_USG_PCT_cmax12_diff,E_PACE_cmax12_diff,PACE_cmax12_diff,PACE_PER40_cmax12_diff,POSS_cmax12_diff,PIE_cmax12_diff,duration_minutes_cmax12_diff,w_pct_cmax12_diff,min_cmax12_diff,fgm_cmax12_diff,fga_cmax12_diff,fg_pct_cmax12_diff,fg3m_cmax12_diff,fg3a_cmax12_diff,fg3_pct_cmax12_diff,ftm_cmax12_diff,fta_cmax12_diff,ft_pct_cmax12_diff,oreb_cmax12_diff,dreb_cmax12_diff,reb_cmax12_diff,ast_cmax12_diff,stl_cmax12_diff,blk_cmax12_diff,tov_cmax12_diff,pf_cmax12_diff,pts_cmax12_diff,spread_cmax12_diff,away_home__cmax12_diff,E_OFF_RATING_cmax999_diff,OFF_RATING_cmax999_diff,E_DEF_RATING_cmax999_diff,DEF_RATING_cmax999_diff,E_NET_RATING_cmax999_diff,NET_RATING_cmax999_diff,AST_PCT_cmax999_diff,AST_TOV_cmax999_diff,AST_RATIO_cmax999_diff,OREB_PCT_cmax999_diff,DREB_PCT_cmax999_diff,REB_PCT_cmax999_diff,E_TM_TOV_PCT_cmax999_diff,TM_TOV_PCT_cmax999_diff,EFG_PCT_cmax999_diff,TS_PCT_cmax999_diff,USG_PCT_cmax999_diff,E_USG_PCT_cmax999_diff,E_PACE_cmax999_diff,PACE_cmax999_diff,PACE_PER40_cmax999_diff,POSS_cmax999_diff,PIE_cmax999_diff,duration_minutes_cmax999_diff,w_pct_cmax999_diff,min_cmax999_diff,fgm_cmax999_diff,fga_cmax999_diff,fg_pct_cmax999_diff,fg3m_cmax999_diff,fg3a_cmax999_diff,fg3_pct_cmax999_diff,ftm_cmax999_diff,fta_cmax999_diff,ft_pct_cmax999_diff,oreb_cmax999_diff,dreb_cmax999_diff,reb_cmax999_diff,ast_cmax999_diff,stl_cmax999_diff,blk_cmax999_diff,tov_cmax999_diff,pf_cmax999_diff,pts_cmax999_diff,spread_cmax999_diff,away_home__cmax999_diff
0,21000001,2010-10-26,2010-11,Regular Season,2010,Celtics,BOS,Boston,240:00,0 days 04:00:00,1610612738,W,BOS vs. MIA,BOS,MIA,Heat,MIA,Miami,240:00,0 days 04:00:00,1610612748,L,BOS vs. MIA,BOS,MIA,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21000002,2010-10-26,2010-11,Regular Season,2010,Suns,PHX,Phoenix,240:00,0 days 04:00:00,1610612756,L,PHX vs. POR,PHX,POR,Trail Blazers,POR,Portland,240:00,0 days 04:00:00,1610612757,W,PHX vs. POR,PHX,POR,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21000003,2010-10-26,2010-11,Regular Season,2010,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,HOU vs. LAL,HOU,LAL,Lakers,LAL,Los Angeles,240:00,0 days 04:00:00,1610612747,W,HOU vs. LAL,HOU,LAL,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,21000010,2010-10-27,2010-11,Regular Season,2010,Bucks,MIL,Milwaukee,240:00,0 days 04:00:00,1610612749,L,MIL vs. NOH,MIL,NOH,Hornets,NOH,New Orleans,240:00,0 days 04:00:00,1610612740,W,MIL vs. NOH,MIL,NOH,0.00,0.00,0.00,0.00,0.00,0.00,0.0000,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.000000e+00,0.0,0.0000,0.000000e+00,0.0,0.000,0.0,0.0000,0.0,0.0000,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0.0,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.000,0.00,0.0,0.00,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21000015,2010-10-27,2010-11,Regular Season,2010,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,-101.60,-106.80,-105.30,-107.70,3.80,0.90,-0.6580,-1.190,-16.70,-0.3960,-0.6950,-0.5540,-19.3870,-20.40,-0.4620,-5.320000e-01,-1.0,-0.1960,-1.073200e+02,-103.5,-86.250,-103.0,-0.5070,-240.0,0.0000,-240.0,-38.0,-91.0,-0.4180,-8.0,-20.0,-0.4000,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.600000,-106.800000,-105.300000,-107.700000,3.800000,0.900000,-0.658000,-1.190000,-16.700000,-0.396000,-0.695000,-0.554000,-19.387000,-20.400000,-0.462000,-0.532000,-1.0,-0.196000,-107.320000,-103.500000,-86.250000,-103.000000,-0.507000,-240.000000,0.000000,-240.000000,-38.000000,-91.000000,-0.418000,-8.000000,-20.000000,-0.400000,-26.000000,-28.000000,-0.928571,-16.000000,-37.000000,-53.000000,-25.000000,-6.000000,-7.000000,-20.000000,-25.000000,-110.000000,-2.000000,0.000000,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.000,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0,-101.6,-106.8,-105.3,-107.7,3.8,0.9,-0.658,-1.19,-16.7,-0.396,-0.695,-0.554,-19.387,-20.4,-0.462,-0.532,-1.0,-0.196,-107.32,-103.5,-86.25,-103.0,-0.507,-240.0,0.0,-240.0,-38.0,-91.0,-0.418,-8.0,-20.0,-0.400,-26.0,-28.0,-0.928571,-16.0,-37.0,-53.0,-25.0,-6.0,-7.0,-20.0,-25.0,-110.0,-2.0,0.0
10261,41700317,2018-05-28,2017-18,Playoffs,2017,Warriors,GSW,Golden State,240:00,0 days 04:00:00,1610612744,W,GSW vs. HOU,GSW,HOU,Rockets,HOU,Houston,240:00,0 days 04:00:00,1610612745,L,GSW vs. HOU,GSW,HOU,10.00,8.26,-10.00,-8.26,19.96,16.52,0.0370,0.564,2.78,0.0368,0.0368,0.0484,-2.0810,-2.34,0.0320,2.840000e-02,0.0,0.0018,-9.947598e-14,0.0,0.000,0.4,0.1128,0.0,0.0268,0.0,6.0,4.8,0.0482,-2.0,-8.6,0.0274,-1.8,-4.0,0.094590,2.0,1.0,3.0,4.0,1.0,1.0,-1.2,0.6,8.2,-16.4,0.2,2.533333,1.141667,-7.666667,-6.816667,10.183333,7.950000,0.105500,0.220833,3.358333,-0.006750,-0.002750,0.011500,-0.475083,-0.625000,0.003750,0.005083,0.0,0.002083,3.746667,3.958333,3.297500,3.666667,0.062833,0.000000,0.136167,0.000000,3.916667,4.000000,0.025583,-3.166667,-7.333333,-0.021833,0.583333,0.000000,0.039151,1.250000,2.250000,3.500000,6.166667,0.916667,-0.083333,0.750000,-1.000000,5.250000,-7.583333,0.000000,0.444898,-0.909184,-0.579592,0.063265,1.015306,-0.963265,0.126092,0.304898,4.490816,-0.010398,-0.032990,-0.000918,1.380969,1.229592,0.017735,0.013776,0.0,0.001112,2.122857,2.355918,1.962959,2.132653,0.029337,-0.255102,-0.018908,-0.255102,4.000000,1.040816,0.041531,-3.908163,-12.734694,0.020010,-2.530612,-4.193878,0.037360,-0.265306,0.877551,0.612245,7.581633,-0.387755,2.173469,1.816327,0.071429,1.561224,1.061224,0.000000,7.7,5.3,-7.7,-5.3,24.1,24.6,0.011,0.86,2.7,0.034,-0.002,-0.005,-2.597,-3.8,-0.010,-0.005,0.0,0.002,0.00,0.0,0.00,-4.0,0.121,0.0,0.067,0.0,3.0,4.0,0.011,0.0,-5.0,0.036,-7.0,-9.0,0.092593,6.0,1.0,2.0,3.0,1.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,-0.7,-4.0,-7.7,-5.3,20.5,21.7,0.193,-3.11,1.0,0.034,-0.029,0.013,-2.597,-3.8,-0.008,0.018,0.0,0.003,7.48,5.0,4.17,4.0,0.076,0.0,0.0,0.0,3.0,4.0,0.014,-2.0,-4.0,-0.110,-3.0,0.0,0.003268,5.0,4.0,8.0,7.0,0.0,1.0,-5.0,0.0,-1.0,-19.0,0.0,6.6,5.4,-0.3,3.0,18.1,13.9,0.089,-1.80,6.9,0.014,-0.029,0.012,3.969,5.0,-0.024,-0.022,0.0,0.000,2.26,2.0,1.67,-3.0,0.124,-25.0,0.0,-25.0,6.0,1.0,0.032,-2.0,-16.0,-0.022,-8.0,-12.0,0.058824,7.0,4.0,7.0,15.0,0.0,3.0,3.0,-5.0,-5.0,-1.0,0.0
10262,41700401,2018-05-31,2017-18,Playoffs,2017,Cavaliers,CLE,Cleveland,265:00,0 days 04:25:00,1610612739,L,CLE vs. GSW,CLE,GSW,Warriors,GSW,Golden State,265:00,0 days 04:25:00,1610612744,W,CLE vs. GSW,CLE,GSW,-4.78,-3.06,2.48,2.80,-7.26,-5.88,-0.0400,-0.394,-1.82,-0.0426,0.0240,0.0010,0.2970,0.48,-0.0086,2.220446e-16,0.0,-0.0010,-6.760000e-01,-1.5,-1.252,-1.4,-0.0356,0.0,-0.0668,0.0,-3.4,-7.2,-0.0006,-2.4,-2.6,-0.0388,4.8,7.4,-0.039912,-3.6,1.2,-2.4,-3.4,-3.2,0.6,0.0,1.0,-4.4,5.6,0.0,0.641667,2.991667,5.983333,6.825000,-5.341667,-3.841667,-0.090333,0.285000,-2.408333,0.027583,-0.009833,0.009750,-0.940417,-0.766667,0.001250,0.002500,0.0,-0.001333,-7.474167,-8.649167,-7.207500,-7.416667,-0.027083,2.083333,-0.123333,2.083333,-2.833333,-6.666667,0.003750,-1.250000,-3.000000,-0.002917,1.500000,3.416667,-0.055855,-1.166667,-3.083333,-4.250000,-5.416667,-3.583333,-0.416667,-2.000000,0.666667,-5.416667,3.333333,0.000000,-1.834687,-0.740737,5.422859,4.683949,-7.252475,-5.430737,-0.105990,-0.175626,-3.389293,0.001994,0.012453,-0.005768,-1.334362,-1.221495,-0.020021,-0.017755,0.0,-0.000166,-2.549764,-2.596874,-2.164228,-2.453131,-0.053686,0.244949,-0.140104,0.244949,-2.724343,-1.503333,-0.023871,0.447879,2.587778,-0.015180,1.403636,2.865960,-0.042226,-0.226465,-1.953232,-2.179697,-6.116667,-1.150303,-3.160909,-1.566566,-0.725354,-3.597172,5.474646,-0.005051,-9.4,-7.8,5.8,6.9,-11.7,-12.5,-0.019,-0.97,-1.4,0.047,0.001,0.033,-0.416,0.2,0.007,0.019,0.0,0.000,4.66,1.0,0.83,2.0,-0.019,0.0,-0.096,0.0,-7.0,-5.0,-0.016,1.0,-4.0,0.079,5.0,7.0,-0.111111,-1.0,1.0,-2.0,-3.0,-2.0,-1.0,2.0,-1.0,-10.0,9.0,0.0,8.9,12.1,-2.5,-2.4,-11.1,-5.6,-0.215,5.64,-1.4,0.047,-0.052,0.015,-0.416,0.2,0.061,0.036,0.0,-0.001,-10.94,-10.5,-8.75,-9.0,-0.019,25.0,0.0,25.0,2.0,3.0,0.070,1.0,-5.0,0.079,7.0,8.0,-0.094444,-1.0,-5.0,-10.0,-7.0,-2.0,-1.0,2.0,-1.0,2.0,3.0,0.0,-3.5,-3.2,5.9,4.2,-17.5,-11.4,-0.113,4.33,-3.8,-0.027,0.017,-0.008,-5.605,-7.1,-0.001,-0.006,0.0,0.000,3.96,1.0,0.83,-3.0,-0.120,0.0,0.0,0.0,-3.0,-5.0,-0.022,0.0,4.0,0.057,3.0,3.0,0.000000,-5.0,-8.0,-6.0,-11.0,-2.0,-7.0,-4.0,2.0,-3.0,-6.0,0.0